### ISSUE TITLE
convertLineEndings=true raises exception in pages plugin

### ISSUE THREAD

**Issue by leancode** [octobercms/october#1002]
convertLineEndings=true is no longer working. When editing something using the pages plugin with convertLineEndings=true users get a popup like this:
<code>
"Class RainLab\Pages\Controllers\Index does not have a method definition for convertLineEndings" on line 302 of /srv/www/oktick/html/vendor/october/rain/src/Extension/ExtendableTrait.php
</code>

**Comment by tresbach** [comment]
+1

**Comment by leancode** [comment]
Thanks for that. I could not figure it out otherwise I would have proposed! Thanks again for the great product!!
