### ISSUE TITLE
problems with hasOne/belongsTo after upgrading to RC release

### ISSUE THREAD

**Issue by karnold** [octobercms/october#1005]
I have a relationship that is a one to one that worked before upgrading to the RC release.

Now when I try and save the related object I get the following error:

```
"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: update `dma_friends_usermetas` set `gender` = Female where `id` is null)" on line 620 of /Users/karnold/src/sites/friends.dma.org-rc/vendor/laravel/framework/src/Illuminate/Database/Connection.php
```

I am trying to save the relation with the following code snippet:

```
        $user = $this->getUser();

        $vars = post();
        foreach($vars as $key => $val) {
            if ($key == 'metadata') {
                $metadata = $user->metadata;
                foreach($val as $metakey => $metaval) {
                    $metadata->{$metakey} = $metaval;
                }

                $user->metadata()->save($metadata);

            } else {
                $user->{$key} = $val;
            }
        }

        if ($user->save()) {
            Flash::info(Lang::get('dma.friends::lang.user.save'));
        } else {
            Flash::info(Lang::get('dma.friends::lang.user.saveFailed'));
        }
```

And the relations are defined as follows:

Plugin.php
```
    /**
     * {@inheritDoc}
     */
    public function boot()
    {
       User::extend(function($model) {        
            $model->hasOne['metadata']          = ['DMA\Friends\Models\Usermeta'];     
       });
    }
```

Usermeta.php:
```
    /**
     * @var array Relations
     */
    public $belongsTo = [
        'user' => ['RainLab\User\Models\User',
            'key' => 'user_id',        
        ],
    ];
```

**Comment by daftspunk** [comment]
This might have been caused by something in Laravel 5...

Shouldn't `$user->metadata()->save($metadata);` be `$metadata->save()`?

**Comment by karnold** [comment]
If i do that then it fails with "Column not found: 1054 Unknown column 'id' in 'where clause'"  as the primary key for the table is user_id.

I've also tried just updating $user->metadata directly and calling $user->push() instead of $user->save().  to no avail.

**Comment by karnold** [comment]
I am starting to think this is a bug in the relationship configuration.

This following snippet of code is the closest i've had to success:

```
      $user = $this->getUser();

        $vars = post();
        foreach($vars as $key => $val) {
            if ($key == 'metadata') {
                $metadata = $user->metadata;

                foreach($val as $metakey => $metaval) {
                    $metadata->{$metakey} = $metaval;
                }

                $user->metadata = $metadata;

            } else {
                $user->{$key} = $val;
            }
        }

        if ($user->push()) {
            Flash::info(Lang::get('dma.friends::lang.user.save'));
        } else {
            Flash::info(Lang::get('dma.friends::lang.user.saveFailed'));
        }
```

however it returns the following SQL error:

```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`octoberfriends`.`dma_friends_usermetas`, CONSTRAINT `dma_friends_usermetas_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) (SQL: update `dma_friends_usermetas` set `dma_friends_usermetas`.`user_id` =  where `dma_friends_usermetas`.`user_id` = 13642)" on line 620 of /Users/karnold/src/sites/friends.dma.org-rc/vendor/laravel/framework/src/Illuminate/Database/Connection.php
```

notice specifically "pdate `dma_friends_usermetas` set `dma_friends_usermetas`.`user_id` =  where `dma_friends_usermetas`.`user_id` = 13642".  But outputting the value of $metadata before it is returned to the user object shows that the property user_id is properly set.

**Comment by karnold** [comment]
and here is another attempt where i attempt to alter the values directly in $user->metadata that fails with a different error

```
        foreach($vars as $key => $val) {
            if ($key == 'metadata') {
                foreach($val as $metakey => $metaval) {
                    $user->metadata->{$metakey} = $metaval;
                }

            } else {
                $user->{$key} = $val;
            }
        }

        if ($user->push()) {
            Flash::info(Lang::get('dma.friends::lang.user.save'));
        } else {
            Flash::info(Lang::get('dma.friends::lang.user.saveFailed'));
        }
```

This fails with ""Call to a member function push() on a non-object" on line 1104 of /Users/karnold/src/sites/friends.dma.org-rc/vendor/october/rain/src/Database/Model.php"  

And after inserting some debug code in the following:

```
1089     public function push($sessionKey = null, $options = [])
1090     {
1091         $always = array_get($options, 'always', false);
1092 
1093         if (!$this->save(null, $sessionKey) && !$always)
1094             return false;
1095 
1096         foreach ($this->relations as $name => $models) {
1097             if (!$this->isRelationPushable($name))
1098                 continue;
1099 
1100
1101 \Debugbar::info($models);
1102             foreach (Collection::make($models) as $model) {
1103 \Debugbar::info($model);
1104                 if (!$model->push($sessionKey))
1105                     return false;
1106             }
1107         }
```
I can see that $models contains my usermeta object, however the results of Collection::make($models) as $model returns $model = NUMERIC_ID thus triggering the error message

**Comment by karnold** [comment]
still struggling with this if anyone has any guesses

**Comment by shina** [comment]
This is related to october/library issue 
https://github.com/octobercms/library/pull/101

Apply this patch while it's not solved

**Comment by karnold** [comment]
That seems to have fixed the error "Call to a member function push() on a non-object" on line 1104 of /Users/karnold/src/sites/friends.dma.org-rc/vendor/october/rain/src/Database/Model.php"  but now I am back to the original error message i was getting

```
"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: update `dma_friends_usermetas` set `gender` = Female where `id` is null)" on line 620 of /Users/karnold/src/sites/friends.dma.org-rc/vendor/laravel/framework/src/Illuminate/Database/Connection.php
```

**Comment by daftspunk** [comment]
I haven't been able to replicate this, can you prepare something that does? Feel free to fork this:
http://github.com/daftspunk/oc-test-plugin

**Comment by karnold** [comment]
Yup.  that was the next thing i planned on trying to isolate the issue.

**Comment by karnold** [comment]
Ok, using the test plugin helped me narrow down what is causing the issue.

So it appears that in the RC a unique "id" is also required along with the foreign key reference "user_id".  

Do you happen to know if that is a hard requirement?  AKA, do i have to have the incrementing "id" column as well as "user_id".  I don't necessarily mind adding that column.  But my preferred resolve would be to point laravel to use the "user_id" column as the primary key.

**Comment by shina** [comment]
Hi kernold,

I'm not sure if October need the column id to be the primary key.

However, you can tweak in your model definition.
From Laravel's docs:
> Note: Eloquent will also assume that each table has a primary key column named id. You may define a primaryKey property to override this convention.

http://laravel.com/docs/5.0/eloquent#basic-usage

**Comment by karnold** [comment]
sure enough that was it :) thanks so much for the pointers.  that one was driving me nuts
