### ISSUE TITLE
mobile-touch backend hover menu not work

### ISSUE THREAD

**Issue by toome123** [octobercms/october#1007]
I have problem to manage cms , when i navigate between plugins ('blog, user, cms') links work properly, but CMS plugin with hover menu is not working. I cant navigate to pages, parties, and all sub links in plugins

**Comment by daftspunk** [comment]
Touch devices generally cannot hover, can you provide a screenshot?

**Comment by toome123** [comment]
I know touch devices not support hover, and this is reason to open this issue.. I want to find a way to make it work correctly on touch devices... I can't provide screenshot right now , the device is not with me at the moment.

**Comment by daftspunk** [comment]
This issue is not actionable, closing for now.
