### ISSUE TITLE
pagination of mail templates error

### ISSUE THREAD

**Issue by keiosweb** [octobercms/october#1009]
Hi daftspunk,

Bug summary:
On first page of mail templates view pagination is shown as 1-20 of 20, on second 20-25 of 25, total count is broken and limited to items on current page. 

Images:
Page 1: http://gyazo.com/f11205fdf0aba0237b442f600b4d0981
Page 2: http://gyazo.com/bbbc797827117b881e0cf0ba0630b067

Reproduce steps:
- Install HHVM 3.5.1
- Install OctoberCMS b230
- Register over 20 mail templates

Expected result:
- Pagination should be: "1 - 20 of 25" if more than 20 items in mail templates view

Actual result:
- 1-20 of 20 on first page, 20-25 of 25 on second page etc

Environment: 
- build 230
- hhvm 3.5.1

Request location:
- /backend/system/mailtemplates

Additional bug:
20tal (:to vs :total string replacement on HHVM) still broken, was it posted to upstream as you mentioned before?

**Comment by daftspunk** [comment]
Unable to replicate this in the stable build. 

- Getting `Displayed records: 1-20 of 21` and `Displayed records: 21-21 of 21` respectively.

Assume fixed through general maintenance.
