### ISSUE TITLE
Debugging mode and Font Awesome bug?

### ISSUE THREAD

**Issue by exotickg1** [octobercms/october#1010]
#### Trouble:
After turning off debugging mode Font Awesome icons do not work.

#### File:
config/app.php

#### Example on screenshot
http://i.imgur.com/EZpX3Zv.png
http://i.imgur.com/G1dOBHL.png

**Comment by daftspunk** [comment]
Somehow your CSS generation has been impacted, this requires more information and greater troubleshooting. Please connect to the Live Chat (IRC) room during support hours to get assistance.
