### ISSUE TITLE
Versionning of the config folder

### ISSUE THREAD

**Issue by Flo-Schield-Bobby** [octobercms/october#1015]
I am using October with CLI only for installing / updating / deploying / migrating etc.

Basically when I work, I pull the repository, launch apache (Mamp mostly or linux httpd on production),
And one bad point for me did that the config is versioned.

I updated my project .gitignore to exclure app.php (working with vhosts --> URL change) and database.php

But it seems like a hacky way...

Symfony natively uses a parameters.yml file, excluded of versionning (but with an exemple parameters.yml.dist which is versionned), only containing local specific informations like database password etc.

Would this solution be possible with October ?
(I can create a PR but first I would like to have feedback about it)

Otherwise, if you dislike having a parameters file, could we think to version an original copy of the confit file, excluding a local folder used for the app ?
(For instance config/app/database.php etc.)

Except if I missed a main part of enjoying October ?

**Comment by daftspunk** [comment]
Use a folder like `/config/production` and then set your `APP_ENV` to production

**Comment by Flo-Schield-Bobby** [comment]
Okay, I missed something. Thanks ! Could you just tell me where is this APP_ENV ?

**Comment by NemoD503** [comment]
You can set APP_ENV in the .env file in the root of your project, 
More details in the Laravel documentation
http://laravel.com/docs/5.0/configuration#environment-configuration

**Comment by Flo-Schield-Bobby** [comment]
Perfect, works fine, thanks!
I had never used Laravel before, that's why I'm not aware of this environment configuration.

Wouldn't this trick have his place in the Installation doc page ? Or maybe the CLI page ?
A chapter about "Environment" maybe ?
