### ISSUE TITLE
Redactor 10.0.9

### ISSUE THREAD

**Issue by mod3st** [octobercms/october#1028]
Could you upgrade redactor.js plugin? There are two versions ahead.

**Comment by daftspunk** [comment]
We usually don't update things just to update them, it may cause breakages and unnecessary work. Do you have a reason for needing 10.0.9?

**Comment by mod3st** [comment]
Yes, there's problem if you want to create list:
<ul><li>(....)</li></ul>
is pretended by empty paragraph block:
<p>&nbsp;</p><ul><li>(....)</li></ul>
