### ISSUE TITLE
Scrolling doesn't work on iPad/iPhone

### ISSUE THREAD

**Issue by Hambern** [octobercms/october#1030]
Seems like the input-field in the backend system doesn't allow scrolling on iPad and iPhone yet.

**Comment by daftspunk** [comment]
What input field?

**Comment by Hambern** [comment]
The main input fields where you write the code:  
textarea .ace_text-input

**Comment by DanielHitchen** [comment]
This is a known issue in [ACE editor](https://github.com/ajaxorg/ace/issues/37)

**Comment by daftspunk** [comment]
We need to wait for ACE to fix it
