### ISSUE TITLE
CURLOPT_FOLLOWLOCATION 

### ISSUE THREAD

**Issue by Shahiem** [octobercms/october#1034]
When I click on "Check for updates" on backend site of October CMS I receive the following error message: 

ERROR MESSAGE:
"curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set"

It works well when I change this line

    curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);

to

    curl_setopt($curl, CURLOPT_FOLLOWLOCATION, false);
 in vendor\october\rain\src\Network\Http.php 

But that isn't a good solution, cause it change when there is a new core update.

**Comment by daftspunk** [comment]
Can you find a way to conditionally check if this error will occur? Something like

```
if (openbasedirset()) { ... }
```

There is already a condition in the Http class that checks for CURLOPT_FOLLOWLOCATION definition, but yours appears to be defined and it doesn't allow it.

**Comment by snetty** [comment]
client of mine is also experiencing this, looks to me like the CURLOPT_FOLLOWLOCATION definition conditionals also needs to check for open_basedir.  I'd submit a pull request but dunno if that's welcome on the OctoberRain/Network repo as it says Read Only.

**Comment by daftspunk** [comment]
Try here: 
https://github.com/octobercms/library/blob/master/src/Network/Http.php

**Comment by snetty** [comment]
pull request submitted, I have nfc what I'm doing with PRs so please let me know if I've screwed anything up.

https://github.com/octobercms/library/pull/97

**Comment by daftspunk** [comment]
Couple of things:

* Wrong branch, needs to go to `develop`
* You used `‘ ’` chars... did you edit this in Word?!

Hehe, I'll fix it! Thanks
