### ISSUE TITLE
DependsOn event not fired on checkboxlist "all" or "none" buttons

### ISSUE THREAD

**Issue by scottbedard** [octobercms/october#1035]
A checkboxlist's form widget does not trigger an ajax event for dependsOn fields to use when the "all" or "none" buttons are clicked.

##### Steps to reproduce
1. Set up a checkboxlist with enough options to enable the "all" and "none" helper buttons to appear.
2. Create a form element that depends on the checkboxlist
3. Verify that the dependent field is reacting to the toggling of individual checkboxes
4. Click the "all" or "none" helper buttons

##### Expected result
The dependent field should notice the checkboxlist has changed when "all" or "none" is clicked, and react accordingly.

##### Actual result
Nothing happens

**Comment by daftspunk** [comment]
Confirmed fixed by #1035
