### ISSUE TITLE
Install Error: Building Configuration Files

### ISSUE THREAD

**Issue by LithionLabs** [octobercms/october#1045]
I encountered this while installing on an Ubuntu 14.04 EC2 instance. Exactly the same issue as #162

**Comment by LithionLabs** [comment]
Here is an excerpt from my install.log
```
.============================ POST REQUEST ==========================.
[2015/04/08 07:03:28] Postback payload: Array
(
    [step] => setupConfig
    [meta] => Array
        (
            [core] => Array
                (
                    [hash] => 8c4d2e8771d041d411737d8a462917e9
                    [build] => 238
                    [uhash] => 48a31188c0d15135af322d2da6919574
                )

        )

    [db_type] => mysql
    [db_host] => localhost
    [db_port] => 
    [db_name] => bobknobdb
    [db_user] => admin
    [db_pass] => *******
    [admin_first_name] => Bob
    [admin_last_name] => Knob
    [admin_email] => *******@*****.com
    [admin_login] => admin
    [admin_password] => *******
    [admin_confirm_password] => *******
    [backend_uri] => /backend
    [encryption_code] => *******
    [file_mask] => 777
    [folder_mask] => 777
    [handler] => onInstallStep
)

[2015/04/08 07:03:28] Install step: setupConfig
```
As you can see, there are no errors. Same with my php error log...nothing. Any ideas? Anyone?

**Comment by daftspunk** [comment]
I haven't been able to replicate this so am unable to troubleshoot. It is a mystery why this happens.

**Comment by LithionLabs** [comment]
I get the same error trying to install on my WAMP server on my local machine which is ver 2.5 I believe. The only time I have ever had a successfull installation was on my MAMP server about 2 months ago. This one has really got me scratching my head.

**Comment by daftspunk** [comment]
The more information you can provide the better, such as:

- the request headers
- whether or not the `install.php` is subsequently available
- any php / web server errors (from the error log)
- the file mask applied to the config files in `/config`

**Comment by devnulldevzero** [comment]
` PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /home/**/**.site/www/vendor/laravel/framework/src/Illuminate/Container/Container.php`

I'm using web installer on PHP 8.0

Downgrading PHP to 7.4 will be work, but why you can't make compitablity with 8.0? As I saw, laravel is supporting PHP 8.0

**Comment by bennothommo** [comment]
@devnulldevzero PHP 8 compatibility is being worked on - see https://github.com/octobercms/october/pull/5454.
