### ISSUE TITLE
Can't login in backend after installing the October CMS successfully

### ISSUE THREAD

**Issue by JKChen** [octobercms/october#1052]
When I try to login ”http://127.0.0.1/october/backend/backend/auth/signin“ with correct account & password after installing the October CMS successfully,I get an error of ”A user was not found with the given credentials.“,and I find that there is no record in the table of `backend_users`.
How can i fix it? Looking forward for your help.Thanks.

**Comment by DanielHitchen** [comment]
Try seeding the ```backend_users``` table with a default user - the seed file can be found [here](https://github.com/octobercms/october/blob/master/modules/backend/database/seeds/SeedSetupAdmin.php), then just login with ```admin``` ```admin``` and change the user details from the CMS backend

**Comment by daftspunk** [comment]
If the migration process fails for whatever reason, the seed scripts can get skipped. To fix it you can rebuild the entire database with these commands:

```
php artisan october:down
php artisan october:up
```

**Comment by JKChen** [comment]
Thanks for your reply.I‘ll try.

**Comment by samargurjar** [comment]
I am facing similar issue where backend login works on sub-domains but for main domain it shows no errors or message. I can not login to backend

**Comment by LukeTowers** [comment]
@samargurjar please make your own issue with a detailed report of what your setup is and what is going wrong instead of adding onto this separate issue that is unlikely to have anything to do with your current problem.

**Comment by cesarmarinhorj** [comment]
after migration, system displays the password it has defined.
"\Backend\Database\Seeds\DatabaseSeeder reported:
 - The following password has been automatically generated for the "admin" account: xxxxxxx"

this is the password, not the one we have entered before... 
:/
after login with this "imposed" password, change it as you wish.

**Comment by bennothommo** [comment]
@cesarmarinhorj This is being fixed as part of https://github.com/octobercms/october/pull/5481.
