### ISSUE TITLE
Cannot upload files anymore

### ISSUE THREAD

**Issue by Zeichen32** [octobercms/october#1064]
After last update, if i try to upload a file it throws this error:

```code
"Call to a member function isValid() on a non-object" on line 311 of /xxx/modules/backend/formwidgets/FileUpload.php
```
https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/FileUpload.php#L311

**Comment by Zeichen32** [comment]
Can be closed... FileUploads are disabled on the server...

**Comment by DanielHitchen** [comment]
Hi, after latest update (243), i'm now gettingbthe following error when trying to upload images via the FileUpload widget:
```
Error uploading file: Object of class Symfony\Component\HttpFoundation\File\UploadedFile could not be converted to boolean
```
Any help would be appreciated, thanks.
