### ISSUE TITLE
$model->push() fails when single belongsTo relationship exists

### ISSUE THREAD

**Issue by pfrend** [octobercms/october#1067]
When trying to push() a model with a belongsTo relationship attached, you get the following error:

[Symfony\Component\Debug\Exception\FatalErrorException]
  Call to a member function push() on a non-object

Issue is on line 1117, in October\Rain\Database\Model, there's a cast to array instead of wrapping the object in an array.

**Comment by pfrend** [comment]
Added pull request to octobercms/library:
https://github.com/octobercms/library/pull/101

**Comment by shina** [comment]
Duplicated issue https://github.com/octobercms/library/commit/9e53e750f1b3fcb3e68ae7319728c7bea684dc10



 


Leonardo Shinagawa


about.me/leonardo.shinagawa

**Comment by daftspunk** [comment]
PR merged, this should be resolved now.
