### ISSUE TITLE
[error] File/Image Upload

### ISSUE THREAD

**Issue by DanielHitchen** [octobercms/october#1068]
Hi, after latest update (243), i'm now getting the following error popup when trying to upload images via the FileUpload widget:
```
Error uploading file: Object of class Symfony\Component\HttpFoundation\File\UploadedFile could not be converted to boolean
```
![error](https://cloud.githubusercontent.com/assets/7501909/7113910/34399668-e1d0-11e4-81c9-eacdd9028211.jpg)

Any help would be appreciated, thanks.

**Comment by alxy** [comment]
https://github.com/octobercms/october/commit/0a26827abdccb27293812e49bd25f57add6b9561
This commit probably casues the error, as it indeed tries to covnert an object to a boolean.

**Comment by DanielHitchen** [comment]
Thanks @daftspunk @alxy , can confirm fixed
