### ISSUE TITLE
Unable to force update

### ISSUE THREAD

**Issue by tremst** [octobercms/october#1071]
I'm currently running Octobercms version 244, now when i'm trying to force an update it give me this error message:

Update failed
"Error while sending STMT_PREPARE packet. PID=182399 (SQL: select * from `system_parameters` where `namespace` = system and `group` = core and `item` = hash limit 1)" on line 620 of /public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php

Now i don't know if i did something wrong or if its a bug.

**Comment by daftspunk** [comment]
This looks like an error with MySQL internally, try searching google for an answer. Perhaps it is related to configuration.
