### ISSUE TITLE
Unable to get 'getPath()' on beforeSave()

### ISSUE THREAD

**Issue by nozreh** [octobercms/october#1075]
There are some consistency when using the fileupload widget.
I have created a model and attached the File model but having this error:

Call to a member function getPath() on a non-object.

![fileupload-model](https://cloud.githubusercontent.com/assets/1023733/7218947/00f8308a-e6bb-11e4-845c-d93d508785ea.png)

But sometimes it's working on Update mode, so there is really some weird inconsistency in building the file object.

**Comment by scottbedard** [comment]
I believe file attachments work via [deferred bindings](http://octobercms.com/docs/database/model#deferred-binding), so when a file is being attached to a newly created model the relationship won't exist until afterSave(). This would explain why it works during updates, but not during creates.

**Comment by nozreh** [comment]
Hi Scott,

Thanks for the info.
I'm relatively new to October and Laravel, in the octobercms documentation the sample is rather vague as  I do not know where to put those code exactly, can you give me example that will be very helpful.

**Comment by daftspunk** [comment]
You would need to use

```
$this->file()->withDeferred($this->sessionKey)->first()->getPath();
```

Because the file doesn't exist yet to obtain the path.

**Comment by nozreh** [comment]
Hi Samuel,

Thanks for the code, I have tested it and it's working but only during
Update but not  during create.
If I want to make it work on initial Create, on which method should I put
it?
Sorry for my stupid questions, I'm so lost with the this Defer function


*Herzon Garlan*
Web Developer | Web Designer
H: +65 9171 5864
E: herzgarlan22@gmail.com
