### ISSUE TITLE
Record Finder field type and listExtendQuery

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#1076]
I used listExtendQuery in my controller to filter some records from the list.

Next I used a Record Finder field type in my fields definition for "client" to fetch records from Client Model. 

    client:
        label: Client
        type: recordfinder
        list: $/total4net/clients/models/client/columns.yaml
        prompt: Click the %s button to find a client
        nameFrom: name
        descriptionFrom: email

I get a list of clients in Record Finder but it is not appling listExtendQuery constrain.

**Comment by daftspunk** [comment]
The recordfinder results are constrained by the [relationship definition in the model](http://octobercms.com/docs/database/model#relationships) (scope or conditions). The controller method `listExtendQuery` is used by the [ListBehavior extension](http://octobercms.com/docs/backend/lists) only.

**Comment by mplodowski** [comment]
Record Finder field is not constrained by scope or conditions I specified in my model relation definition.

I have in Order model:

    public $belongsTo = [
        'client' => [
            'Total4Net\Clients\Models\Client',
            'scope'      => 'currentCompany'
        ]
    ];

and Record Finder is not appling my scope to query.
