### ISSUE TITLE
Report widget layout

### ISSUE THREAD

**Issue by scottbedard** [octobercms/october#1077]
I've got a fairly complicated dashboard set up, and i'm encountering a bug with how the widgets are positioned. The first screenshot shows how I've set up the dashboard, the second shows what is displayed when I refresh the backend. As you can see, the widgets are not maintaining their position. I'll try and poke around a bit tonight and see if I can find the cause of the issue.

![screenshot 2015-04-21 01 41 13](https://cloud.githubusercontent.com/assets/7980426/7246222/beed08ba-e7c7-11e4-9662-80c82357a2ac.png)

![screenshot 2015-04-21 01 41 29](https://cloud.githubusercontent.com/assets/7980426/7246240/e5a6ff06-e7c7-11e4-91f5-ba7c14bc7386.png)

**Comment by daftspunk** [comment]
Fixed by #1100

**Comment by scottbedard** [comment]
Uhg, this nuisance appears to be back...
https://www.dropbox.com/s/udu9ax0qvu1rq09/Screenshot%202015-05-16%2009.15.00.png?dl=0

Please re-open this, I will look into this again later today.
