### ISSUE TITLE
Media Manager - Possible bug with file paths

### ISSUE THREAD

**Issue by jonpxpx** [octobercms/october#1081]
Currently when you upload a file, the filepath shown in the media manager as /storage/temp/media/ and the files are not uploaded there, they are uploaded to the correct path. This therefore means that thumbnails are not being shown.

Have I missed something from the local storage configuration or is this a bug?

Many thanks,
Jon

**Comment by Shahiem** [comment]
http://octobercms.com/blog/post/introducing-media-manager

Note for the existing installations

You will need to update .htaccess file to allow public access files to storage/temp/public directory. That's not required for new installations.

Find this line in .htaccess file:

    RewriteRule ^storage/temp/.* index.php [L,NC]

and add RewriteCond rule before that line. The result should look like this:

    RewriteCond %{REQUEST_URI} !storage/temp/public
    RewriteRule ^storage/temp/.* index.php [L,NC]

**Comment by jonpxpx** [comment]
Thanks @Shahiem that's perfect, I never saw the twitter post (tried to stay away from Social media today) so when I saw that I instantly came here to find you had also replied ;) Sorry for my stupidity.

**Comment by Shahiem** [comment]
Haha, It's not stupidity.  I had the same problem,  till I read the whole post.
