### ISSUE TITLE
Mediamanger in editor

### ISSUE THREAD

**Issue by Shahiem** [octobercms/october#1082]
Is it possible to implement the mediamanger in a wysiwyg editor like CKedtor?

**Comment by daftspunk** [comment]
Yes, take a look at the Redactor plugin:

`modules\cms\widgets\mediamanager\assets\js\mediamanager.redactor.js`

It would need to be adapted for CKEditor

**Comment by Shahiem** [comment]
Thank you.  It's now implemented in my plugin
