### ISSUE TITLE
Media Manager doesn't work on Safari

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [octobercms/october#1084]
The media manager doesn't seem to work on Safari. It encounters and error so the rest of the JS doesn't load, so I cannot perform any actions. I tested on Chrome and Firefox and it works well. Here's the error I get

![Safari Media Manager Issue](http://i.imgur.com/RkCQlEl.png)

**Comment by hybridvision** [comment]
Which version of Safari? It works fine for me and I have v7.0.6.

I had some javascript errors initially in Chrome but it was a cache problem so make sure you've cleared your cache.

**Comment by SaifurRahmanMohsin** [comment]
I'm running Safari Version 8.0.5 (10600.5.17)

**Comment by hybridvision** [comment]
Glad it worked :)

I should probably update my Safari at some point!
