### ISSUE TITLE
Session and cookie cannot saved after reload

### ISSUE THREAD

**Issue by json-wong** [octobercms/october#1090]
Hi, I found a problem that are session and cookie cannot saved after reload. session can be manually calling `session::save()` to achieve conservation, but there is no workaround with cookie.

I'm sure there directory permissions are correct, and my app/config/session.php:

```php
'driver' => 'file',
'lifetime' => 120,
'expire_on_close' => false,
```

I use build 249, that was a bug?

**Comment by daftspunk** [comment]
Can you provide clear instructions on how to replicate this issue?

**Comment by daftspunk** [comment]
I have no idea what this issue is trying to convey.

**Comment by sampoyigi** [comment]
I'm experiencing the same issue here. 

I'm trying to set an additional cookie after login. I've being able to extend the Account Component and within the onSignin method after loading parent::onSignin, i have 

```
        $cookie = Cookie::make('foo', 'bar');
        $redirect->withCookie($cookie);
```
Cookie doesn't save after redirect. Am i missing something?

**Comment by sampoyigi** [comment]
Got it working.. Had to change the logic such that cookie is set onRun instead on redirect.. Not sure why that worked.
