### ISSUE TITLE
Upgrade problem not show images

### ISSUE THREAD

**Issue by ribsousa** [octobercms/october#1091]
After upgrade the latest october build 250 the images not show, the path url not work! return **-1**

`"path":"\/storage\/app\/uploads\/public\/553\/ee1\/1e9\/553ee11e93c94565792907.jpg","extension":"jpg"}`

**Comment by daftspunk** [comment]
What path? Can you give more information?

**Comment by ribsousa** [comment]
Path variable in array blog image:
'"path":"\/storage\/app\/uploads\/public\/553\/ee1\/1e9\/553ee11e93c94565792907.jpg","extension":"jpg"}'

**Comment by daftspunk** [comment]
Can you please add more detail?

- **Bug summary**: Make sure your summary reflects what the problem is and where it is.

- **Request location**: Enter the URL where this bug occurs, if applicable.

- **Reproduce steps**: Clearly mention the steps to reproduce the bug.

- **Expected result**: How OctoberCMS should behave on above mentioned steps.

**Comment by ribsousa** [comment]
the code block works well before work upgrade:

` ` `{% for image in post.featured_images %}
								      
	 <li class="{% if loop.index == 1 %}clearing-featured-img{% endif %}">
             <a href="{{ image.path }}"><img data-caption="{{ image.description }}" src="{{ image.path }}" title="Exibir galeria de imagens"></a>
	</li>
{% endfor %}` ` `

The variabe **image.path** should return: /storage/app/uploads/public/553/ee1/1e9/553ee11e93c94565792907.jpg

After upgrage return: **-1**

**Comment by netbuild** [comment]
Hello,

the same problem as here. After upgrading on build 250 the object returns -1 on the path property.

```HTML
{% for image in post.featured_images %}
<p><img src="{{ image.path }}" alt="{{ image.description }}" width="100%" /></p>
{% endfor %}
````

**Comment by daftspunk** [comment]
Thanks for reporting this, it should be fixed in build 251

**Comment by netbuild** [comment]
not for this :-)

fix is already patched in and works successfully. thx for your fast help :+1:
