### ISSUE TITLE
Table partial inside table in list causes popup to trigger twice

### ISSUE THREAD

**Issue by dubcanada** [octobercms/october#1092]
Hello,

I have a list, and inside that list I have a partial which renders a table. If I click on that column in the list the popup comes up twice. Every other column triggers the popup only once.

**Comment by daftspunk** [comment]
Can you provide example code and/or screenshots?

**Comment by daftspunk** [comment]
Might have something to do with `october.rowlink.js`

Either way I have no where near enough information to replicate this. See if you can prepare a [test plugin](https://github.com/daftspunk/oc-test-plugin) and reopen if it is still an issue.
