### ISSUE TITLE
Feature Request: Modify output of images

### ISSUE THREAD

**Issue by jonpxpx** [octobercms/october#1093]
Right now we are able to modify the output of Videos and Audio, could we have the ability to change the output of images too? There are times when people need to add classes to their images. In my case I need to add "img-responsive" to save me on doubling up code when using bootstrap (which I have done in the interim).

**Comment by daftspunk** [comment]
This is a complicated proposal for something that can be easily handled in CSS. Add this to your CSS file:

```
.container-with-content img {
    display:block;
    max-width:100%;
    height:auto;
}
```

**Comment by jonpxpx** [comment]
No worries, was just hoping to use bootstrap but agree it is extra overhead for no reason.
