### ISSUE TITLE
october:up command doesn't execute plugin's boot method

### ISSUE THREAD

**Issue by arall** [octobercms/october#1094]
My **Plugin A** extends from **Plugin B**, adding some field on **Plugin B** tables. On **Plugin A** PluginBase, I used extended method, to add a relation:

```php
public function boot()
{
    // User extension
    UserFromPluginB::extend(function ($model) {
        $model->belongsTo['client'] = ['Acme\PluginA\Models\Client'];
    });
}
```

In the **Plugin A** updates, I have some seeders too, that create some random users on **Plugin B** tables:

```php
$user = new UserFromPluginB;
$user->client()->associate($someRandomClient);
$user->save();
```

Since `boot` method from **Plugin A** is not being executed, `UserFromPluginB` model doesn't have `Client` relation:

```php
[BadMethodCallException]                                               
Call to undefined method October\Rain\Database\QueryBuilder::client() 
```

But it works if I run `plugin:refresh` command. In fact, if I print some debug data on `boot` method, its not being prompted with `october:up` command.

And, of course, I deleted all my database tables before run `october:up` command.

**Comment by daftspunk** [comment]
This is an elevated command and requires elevated permission. Try setting this in your plugin registration file:

```
    /**
     * @var boolean Determine if this plugin should have elevated privileges.
     */
    public $elevated = true;
```
