### ISSUE TITLE
Ajax Framework and Laravel Queues

### ISSUE THREAD

**Issue by chrisvanderpoel** [octobercms/october#1095]
This is more of an system architecture question within October-land.  Is it possible for the Ajax framework to interact with Laravel queues for longer backend requests (such as behind the scenes synchronous API calls) ?

Seems easy enough to post to the queue via the Ajax handler but do you have a suggestion as to how we might update the front-end based on the item in the queue being processed?

**Comment by daftspunk** [comment]
Laravel 5.1 is introducing a "Broadcasting" feature that interfaces with pusher / node.js, but this might be fairly convoluted to set up if you intend to distribute your work.

A nicer solution might be to use [a plugin like this](https://github.com/serkanyersen/ifvisible.js) to monitor the users presence and then poll for updates using the AJAX framework. It's not as efficient as web sockets but it could get the job done.
