### ISSUE TITLE
Class 'Log' not found

### ISSUE THREAD

**Issue by alvaro-canepa** [octobercms/october#1098]
After the latest update (Build 256) the artisan command prompt this error message:

    PHP Fatal error:  Class 'Log' not found in /home/mag/public_html/vendor/october/rain/src/Foundation/Exception/Handler.php on line 38

Thanks

**Comment by daftspunk** [comment]
It works for me, what command are you running exactly?

**Comment by alvaro-canepa** [comment]
I try any command, like `php artisan cache:clear` or `php artisan plugin:create ...`

**Comment by daftspunk** [comment]
It's possible a file did not overwrite correctly, try another update or Force update. Does it help?

**Comment by alvaro-canepa** [comment]
I do this, and not work. A week ago it working fine. I create a new Model, but now I can't use artisan.

**Comment by daftspunk** [comment]
Confirm you are on Build 257?

**Comment by alvaro-canepa** [comment]
Sorry, now work. The problem was on build 256.

**Comment by daftspunk** [comment]
Yay! Great, thanks!
