### ISSUE TITLE
Can't get cron to work

### ISSUE THREAD

**Issue by jerryxh** [octobercms/october#1102]
Using my cPanel, I manually set up a cron job to run every 30 minutes (my hosting company does not allow me to set my cron jobs to run in less than 30 minute increments) as follows:

    0,30 * * * * /usr/local/bin/php -q /home/example/public_html/artisan scheduled:run 1>> /dev/null 2>&1

I also added the **registerSchedule** method to my Plugin registration file, **Plugin.php** as shown below:

    use Example\MySearch\Components\GetProducts;
    class Plugin extends PluginBase
    {
        public function registerSchedule($schedule)
        {
            $schedule->call(function() {
                GetProducts::instance()->sendMail();
            })->everyFiveMinutes();
        }
    }

But no matter what I do, nothing ever happens. When I run **php artisan scheduled:summary** on my server this is what I get:

    +----------------+------+-----------+--------+------+--------------+-------+-------------+--------+
    | Environment(s) | Name | Args/Opts | Minute | Hour | Day of Month | Month | Day of Week | Run as |
    +----------------+------+-----------+--------+------+--------------+-------+-------------+--------+
    +----------------+------+-----------+--------+------+--------------+-------+-------------+--------+

I have checked separately that the sendMail() method I wrote works, so that is not the problem. I have even tried manually running **php artisan scheduled:run** and that doesn't work. I am not getting any error messages either.

What am I missing or what am I doing wrong?

**Comment by daftspunk** [comment]
For the scheduler to work properly, it must be running every minute. This is a condition introduced by [Laravel's scheduler](http://laravel.com/docs/master/artisan).

Alternatively you could make the command run every minute and it will run every time:

```
use Example\MySearch\Components\GetProducts;
class Plugin extends PluginBase
{
    public function registerSchedule($schedule)
    {
        $schedule->call(function() {
            GetProducts::instance()->sendMail();
        }); // Defaults to every minute (every execution)
    }
}
```

The command **php artisan scheduled:summary** comes from an old library in October's Beta version, it should no longer be available and events won't appear in the summary. I'm not sure how it works for you, are you running the RC version? If not, you may need to reinstall October.
