### ISSUE TITLE
Malformed plugin version.yaml causes login issues

### ISSUE THREAD

**Issue by BrendonPark** [octobercms/october#1104]
If a plugin's version.yaml is empty or malformed, the login flow will fail to redirect to the backend upon a successful login. The login page will flash the following messages:

Empty version.yaml:
```array_keys() expects parameter 1 to be array, null given```

Malformed (e.g. "asdf"):
```uksort() expects parameter 1 to be array, string given```

**Comment by dubcanada** [comment]
I guess we need some checks for valid yaml syntax?
