### ISSUE TITLE
fileTypes doesn't work correctly for file upload fields

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#1105]
When a file upload field is set to `mode: image`, setting `fileTypes: jpg,png` will result in an invalid file type every time you try to upload an image - whether it be a jpg or not. After failing to upload the image the first time, trying to upload another results in a 'cant upload any more' error. I consider this to be a second bug.

I've whipped up a plugin you can replicate on complete with installation and usage instructions [here](https://github.com/Flynsarmy/oc-badavatar-plugin).

**Comment by 7talents** [comment]
I had the same problem today. Both problems, by the way, but I also think these could be two different bugs. So, +1.
Thanks for a great tool making my work life much more fun and easier, by the way.

**Comment by 7talents** [comment]
Additional info: also setting fileTypes to just "jpg" or just "png" fails, the error message being "Error uploading file: The file data must be a file of type: jpg.".
About that second bug: that only happen with "attachOne" relations, not with "attachMany" relations.

**Comment by 7talents** [comment]
I would like to add some more information: in my case also setting <code>fileTypes: mp3</code> and <code>mode: file</code> and uploading an mp3-file returned the error "Error uploading file: The file data must be a file of type: mp3" - while strangely <code>fileTypes: mp4</code> and uploading an mp4-file worked.
And the error appears to be thrown after the upload is finished.

**Comment by daftspunk** [comment]
This was fixed by 50e4840216be0006cc1c24c852c7dfa698ad1737

Prior to this `fileTypes` was acting as "mime types".
