### ISSUE TITLE
Build 257 - Backend JavaScript error

### ISSUE THREAD

**Issue by kawhite** [octobercms/october#1107]
After updating to Build 257 this morning, backend code editor and rich editor controls no longer work. It appears the issue is the javascript updates, as I'm seeing an "Uncaught TypeError: Cannot read property 'markDisposable' of undefined' in the console logs. This seems to occur in at least codeeditor.js and treeview.js.

**Comment by kawhite** [comment]
Also, issue appears to occur in only in Google Chrome, version 42.02311.135 m (current version). Tested in both Firefox and IE, and it's executing normally.

**Comment by daviskoko** [comment]
Yeah, am experiencing the same thing on Mozilla

**Comment by justin-lau** [comment]
I think the old version of the javascript files were cached. I cleared the cache after updating and didn't encounter such issue.

**Comment by daviskoko** [comment]
Well, I've cleared my cache several times, chrome is working well, but
Mozilla is not.
The add page button at the CMS is not working & when i click on an existing
page (Ex: home) it shows a plain white background. but everything was
working fine & i've been using Mozilla before the latest build. I prefer it
because of the firebug addon.

**Comment by justin-lau** [comment]
@daviskoko Have you cleared both the server cache and the browser cache?

**Comment by justin-lau** [comment]
Just tested with another October setup. I was able to reproduce the problem right after updating to the latest build:

```
/modules/backend/FormWidgets/codeeditor/assets/js/codeeditor.js?v257:41
Uncaught TypeError: Cannot read property 'markDisposable' of undefined
```

After refreshing the cache and reloaded the page, the problem is gone.

**Comment by kawhite** [comment]
I've verified this on a couple of my installations, all it takes is a refresh of the browser cache.

**Comment by daviskoko** [comment]
Yeah. It worked after I refresh my cache.

I see the latest build is related  to the CSS customization. Does this mean
that issue with back-end
customization(/octobercms/admin/system/settings/update/october/backend/branding)
has been resolved?
