### ISSUE TITLE
Code editor problem

### ISSUE THREAD

**Issue by bayramoff** [octobercms/october#1109]
Code editor problem on build 257 

i check this with two projects. both are get problem
code editor is white, i can type anything, but editor shows nothing.

![2015-05-06 23-48-40 page not found 404 cms october cms yandex](https://cloud.githubusercontent.com/assets/9781379/7501256/2e7d18ce-f44c-11e4-87ef-96a39f4ff687.png)
.

**Comment by kawhite** [comment]
I had this issue with my installations, all you'll need to do is to refresh your browser cache.

**Comment by bayramoff** [comment]
you made my day. thanks!
