### ISSUE TITLE
Code editor broken as of build 257

### ISSUE THREAD

**Issue by scottbedard** [octobercms/october#1110]
As of build 257, the code editor is broken. This prevents large portions of the backend from being used.

https://www.dropbox.com/s/paxhq6qw976nt1n/Screenshot%202015-05-06%2015.28.10.png?dl=0
https://www.dropbox.com/s/33gc59psbbhab4l/Screenshot%202015-05-06%2015.28.34.png?dl=0
https://www.dropbox.com/s/gujb0ic8zul7jj1/Screenshot%202015-05-06%2015.28.57.png?dl=0

```
Uncaught TypeError: Cannot read property 'markDisposable' of undefined
```
The bug occurs at line 41 of [codeeditor.js](https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/codeeditor/assets/js/codeeditor.js#L41)

**Comment by hybridvision** [comment]
It is probably just a cache problem - see a few other issues that were posted recently about this and were related to the cache (eg. https://github.com/octobercms/october/issues/1107).

Try clearing your cache and see if that helps :)

**Comment by scottbedard** [comment]
thanks @hybridvision, that fixed it!

**Comment by hybridvision** [comment]
Glad it was that simple!
