### ISSUE TITLE
Trouble with PostgreSQL & nest_left

### ISSUE THREAD

**Issue by dcrawkstar** [octobercms/october#1111]
This is with a pluggin but i get this frequently from the core code too
Upon installing the pluggin after it unpacks i get:

Update failed

"SQLSTATE[42803]: Grouping error: 7 ERROR: column "rainlab_forum_channels.nest_left" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: ...ainlab_forum_channels" where "slug" = $1 order by "nest_left... ^ (SQL: select count(*) as aggregate from "rainlab_forum_channels" where "slug" = channel-orange order by "nest_left" asc)" on line 624 of /home/vagrant/designmalice/vendor/laravel/framework/src/Illuminate/Database/Connection.php

My System Stats:
psql (PostgreSQL) 9.3.6
PHP (fpm) 5.6.7-1+deb.sury.org~trusty+1 (cli) (built: Mar 24 2015 11:21:10)
Ubuntu 14.04.2 LTS - 4 MB Upload Limit & 512 MB Memory & 2 vCPUs
Laravel Framework version 5.0.28
OctoberCMS version: 257

**Comment by daftspunk** [comment]
Unless someone is able to find a blanket fix for this, I think we may need to remove PostgreSQL from the list of supported drivers. Laravel doesn't seem to handle this internally.

**Comment by dcrawkstar** [comment]
MySQL's totally non standards compliant GROUP BY can be emulated by Postgres' DISTINCT ON. Consider this :

mysql : SELECT a,b,c,d,e FROM table GROUP BY a
This delivers 1 row per value of a (which one, you don't really know). Well actually you can guess, because MySQL doesn't know about hash aggregates, so it will probably use a sort... but it will only sort on a, so the order of the rows could be random. Unless it uses a multicolumn index instead of sorting. Well, anyway, it's not specified by the query.

postgres : SELECT DISTINCT ON (a) a,b,c,d,e FROM table ORDER BY a,b,c
This delivers 1 row per value of a, this row will be the first one in the sort according to the ORDER BY specified by the query. Simple.

Could just be a simple check for the database type. I want to pull the code and see if I can change how the nest left is written into the query. I need to truly understand how the query is even being built. But i will very happily be your Postgres guy.

-Chris

**Comment by daftspunk** [comment]
I think I may have figured out what is causing this, will prepare a PR for Laravel. We can implement a workaround in the meantime.

**Comment by daftspunk** [comment]
Can you please monkey patch this change to confirm it fixes the issue? 

https://github.com/octobercms/library/commit/6c4d023dbb6725345c54a089b2fecd452821ba72

Should go in vendor\october\rain\src\Database\QueryBuilder.php

**Comment by daftspunk** [comment]
Nevermind this is a bad solution.

**Comment by daftspunk** [comment]
Try this one instead:

https://github.com/octobercms/library/commit/f14180927afa2433dd1cc9606f1e1dbac1c5c7f1

**Comment by daftspunk** [comment]
Try adding this to file **vendor\october\rain\src\Database\QueryBuilder.php**

```
    /**
     * Retrieve the "count" result of the query,
     * also strips off any orderBy clause.
     *
     * @param  string  $columns
     * @return int
     */
    public function count($columns = '*')
    {
        $previousOrders = $this->orders;

        $this->orders = null;

        $result = parent::count($columns);

        $this->orders = $previousOrders;

        return $result;
    }
```

**Comment by dcrawkstar** [comment]
Hey mate,

I fell asleep last night going through the October queryBuilder and then tracked to the Laravel Grammar 'compileAggregate'. 
I wake up and it looks like you solved the problem ahead of me. Excellent job sir. I am testing all aspects currently and should take me about an hour to run through so burn tests.
-Chris

**Comment by dcrawkstar** [comment]
Looks like this is the fix. Burn tests pass.
