### ISSUE TITLE
CSS parsing error after editing custom backend styles

### ISSUE THREAD

**Issue by dojd** [octobercms/october#1114]
![3536c66c322596af45089ac5f33d784f](https://cloud.githubusercontent.com/assets/68890/7528442/8e86a4c6-f530-11e4-87e7-5b94366c192b.png)

I't impossible to fix wrong custom backend css without manupulating with _system_settings_ in database and clearing the cache.

**Comment by daftspunk** [comment]
Fixed already by 445c95ad461e1a739d6d4d37806f829c5857b435
