### ISSUE TITLE
Can't open backend media manager. 

### ISSUE THREAD

**Issue by dojd** [octobercms/october#1115]
![8a803d78c33d74e4449195cb058218d0](https://cloud.githubusercontent.com/assets/68890/7528504/8091651c-f531-11e4-9a99-a0d5361c49ef.png)

**Comment by daftspunk** [comment]
Collection::where() was added to Laravel 5. You must be running Laravel 4 somehow? You may need to reinstall October to get the RC version (Laravel 5). It looks like you may be running the Beta version (Laravel 4).
