### ISSUE TITLE
Create a overwrite changes prompt in Media Manager

### ISSUE THREAD

**Issue by kalatabe** [octobercms/october#1117]
Bug summary: **Media Manager files are overwritten automatically without warning or prompt**

I'm not sure if this is configurable in any way, I couldn't find a relevant parameter, but the Media Manager allows you to upload a file with the same name as an existing file in the current directory, overwriting it in the process. I would expect this to not be allowed (similar to attempting to create a new directory with the name of an existing one), or at least a warning should be shown that you are about to overwrite an existing file. Is there any way around this?

**Comment by kdoichinov** [comment]
Any news on this?

**Comment by daftspunk** [comment]
I think this behavior is intended for now. We will leave this open for review again later.

**Comment by LukeTowers** [comment]
#3124 is a duplicate, switching conversation to there instead as it has more interactions.
