### ISSUE TITLE
[EROR]"Call to undefined method Less_Tree_Call::toHSL()"

### ISSUE THREAD

**Issue by audio99** [octobercms/october#1122]
when im trying to save changes in backend colors customization i got this error message,anybody knows?,im stuck here. @daftspunk 
![capture](https://cloud.githubusercontent.com/assets/9496025/7564171/3bef9994-f80e-11e4-91a0-388579d68c3d.PNG)

**Comment by daftspunk** [comment]
What build are you using?

**Comment by audio99** [comment]
latest build (257)
i use apache

**Comment by daftspunk** [comment]
Duplicate of #1137
