### ISSUE TITLE
always got this error message when save changes on backend section

### ISSUE THREAD

**Issue by audio99** [octobercms/october#1123]
![capture](https://cloud.githubusercontent.com/assets/9496025/7565513/b13b0826-f81a-11e4-9141-27985d912922.PNG)

pls help @daftspunk

**Comment by daftspunk** [comment]
More information is needed. The form works for me.

What web server are you using? Is it the latest build of October? What does the "Network" response say in the browser console?

**Comment by audio99** [comment]
i use apache webserver with xampp,
yes,latest build (257),
i forgot to saw the browser console.
