### ISSUE TITLE
[MediaManager] Permissions

### ISSUE THREAD

**Issue by alxy** [octobercms/october#1124]
Permissions need to be registered for the MediaManager to maintain access to the manager. Possibly one should be able to also allow/deny for specific content types (images, videos, ...).

Needs to be implemented here: https://github.com/octobercms/october/blob/master/modules/cms/ServiceProvider.php#L153-L183

Note: Maybe it is possible to also hide/show the icons in the richeditor widget according to the permissions of the current user, so he doesnt see these buttons if he isnt allowed to manage media files.

**Comment by daftspunk** [comment]
Great, can you submit a pull request?
