### ISSUE TITLE
Ability to set the default when using getDropdownOptions() or get*Field*Options()

### ISSUE THREAD

**Issue by that0n3guy** [octobercms/october#1125]
We can not dynamically set the default default when settings dropdown options.

Here is an example:

2 fields: State and City.  If I pick "California" as the state... I want the capital to be the default for the "city".  This default city would be different depending on the selected state.

Currently the only way to do this is to move the "default" to the top of the options list.

**Comment by daftspunk** [comment]
This can be handled in the model with a mutator

```
public function getStateAttribute()
{
    return array_get($this->attributes, 'state', 'some default value');
}
```
