### ISSUE TITLE
[Bug]? Cannot upload fonts in assets manager

### ISSUE THREAD

**Issue by bestxp** [octobercms/october#1127]
When i try to upload fonts ( font awesome ) i saw 

Ошибка загрузки файла 'fontawesome-webfont.woff2': Разрешены только файлы следующих типов: jpg, jpeg, bmp, png, gif, css, js, woff, svg, ttf, eot, json, md, less, sass, scss

Why i cant upload any file? Why woff2 or any ext of file is restricted?

**Comment by scottbedard** [comment]
I cannot replicate this, I have no problems uploading eof, ttf, svg, woff, or woff2
https://www.dropbox.com/s/8cd4zi60cf8gev0/Screenshot%202015-05-20%2022.50.04.png?dl=0

Perhaps there is something wrong with your permissions?

**Comment by jBOKA** [comment]
I had the same problem. I think woff2 in opposite to woff files are not allowed... it also doesnt show up in the message of allowed types...

**Comment by daftspunk** [comment]
Fixed by #1783
