### ISSUE TITLE
listExtendQuery() does not fire from relation manager

### ISSUE THREAD

**Issue by that0n3guy** [octobercms/october#1128]
I have a "quotes" list embeded in an update page for a "quoterequest" using `<?= $this->relationRender('quotes') ?>` In my quotes controller, I have listExtendQuery().  This method gets fired just fine if I look at the quotes index page... but not when the list is added using relation manager (http://octobercms.com/docs/backend/relations#relation-display).

The workaround is just to use the global even in the Plugin.php like so:

```
        /**
         * See: http://goradiantweb.com/blog/post/how-predispose-your-backend-list-views-filtering/
         * listExtendQuery (does not work with relation manager) so this is my workaround
         */
        Event::listen('backend.list.extendQuery', function($list, $query){
            $user = BackendAuth::getUser();
            if(get_class($list->model) == 'Oca\Quotes\Models\Quote'){
                // for di-broker....
                if ($user->hasAccess('oca.quotes.dibroker_quotes') && !$user->hasAccess('oca.quotes.guardian_quotes')) {
                    $query->where('company', '!=', 'Guardian');
                }

                // for guardian
                if (!$user->hasAccess('oca.quotes.dibroker_quotes')) {
                    $query->where('company', '=', 'Guardian');
                }
            }
        });
```

**Comment by daftspunk** [comment]
`listExtendQuery` belongs to the ListController behavior.
`relationExtendQuery` belongs to the RelationController behavior.

Try the latter.
