### ISSUE TITLE
Database table prefix causes SQL error in List widget

### ISSUE THREAD

**Issue by krisawzm** [octobercms/october#1129]
When specifying a database table prefix, you get some nasty SQL errors (column not found) when searching in the List widget.

The error is that in some table names, the prefix isn't included in the actual query.

**Illuminate\Database\QueryException:**
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'system_event_logs.id' in 'where clause' (SQL: select count(*) as aggregate from `prefix_system_event_logs` where (((lower(system_event_logs.id) LIKE %fd%) or (lower(system_event_logs.created_at) LIKE %fd%) or (lower(system_event_logs.message) LIKE %fd%))))
```

In this example (System/EventLogs), the prefix is set to `prefix_` and the search query is `fd` (not really relevant to this error.)

#### Reproduce steps
1.  Set a table prefix in the database configuration
2. Open any of the logs in the back end.
3.  Enter a search query in the search box.
4.  ???
5.  profit

**Comment by daftspunk** [comment]
We don't really support table prefixes, but alright
