### ISSUE TITLE
Automatically assign dashboard configuration to backend users

### ISSUE THREAD

**Issue by karnold** [octobercms/october#1131]
Is there already a way to automatically assign backend users a dashboard configuration?  I was thinking this could probably be handled in model events, but if a way exists already i don't want to duplicate efforts.

**Comment by daftspunk** [comment]
It's a complex issue, we could specify defaults but then it will only impact newly created administrators. Existing administrators already have the dashboard defined to their liking. We hope to solve it by plugins providing dashboard presets that can be selected by the user.

**Comment by karnold** [comment]
this is something that would be a real A+ feature for us to incorporate into the project I'm on. thus is be happy to put forth some dev time to build out the feature and submit a pull request. Could you offer proper guidance on the best play to put the code in the source tree?



—
Kristen

**Comment by daftspunk** [comment]
That would be fantastic, the feature is planned so go for it. As high level guidance I would say to mimic the code existing structure, patterns and methodology but don't stress too much about it. We can work through any issues and amend the code along the way. Please work on a branch called `dashboard-presets`. Thanks!

**Comment by daftspunk** [comment]
A flavour of this feature has been implemented in bb769db2233363401d06a5c9b69539315ef50f2f

A dashboard layout can be saved as the default for all users.
