### ISSUE TITLE
Record Finder field is not bind by scope

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#1133]
Record Finder field is not constrained by scope or conditions I specified in my model relation definition.

I have in Order model:

    public $belongsTo = [
        'client' => [
            'Total4Net\Clients\Models\Client',
            'scope'      => 'currentCompany'
        ]
    ];

and Record Finder is not appling my scope to query.

**Comment by devillom** [comment]
Oh i need fix it (

**Comment by rosuji-mms** [comment]
Bump to also needing a fix for this. Both scope & conditions are being ignored. To elaborate looking at the logs 3 queries get generated the first applies conditions & scope. But the later queries do not. I am not sure what is going on.

**Comment by roscoecairney** [comment]
Bump - I'm having the same issue

**Comment by daftspunk** [comment]
This is fixed in https://github.com/octobercms/october/commit/3bad70f0416b99aefb2c0ffbf7de2ad224361a77
