### ISSUE TITLE
Empty response from the server

### ISSUE THREAD

**Issue by saicho34** [octobercms/october#1136]
I cant update octobercms error is empty response from the  server. 

current build is 248.
![empty response from the server](https://cloud.githubusercontent.com/assets/4668227/7646495/f31916d2-faf6-11e4-967b-1458dafc022c.png)

Hope you can help thank you.

**Comment by daftspunk** [comment]
Check to make sure you webserver can make an outgoing connection to octobercms.com on port 80. It is possible your firewall or web server is preventing the outgoing connection.

**Comment by saicho34** [comment]
Hi even i disable my firewall same problem occur.

**Comment by saicho34** [comment]
.============================ POST REQUEST ==========================.
[2015/05/15 09:36:53] Postback payload: Array
(
    [code] => liveConnection
    [handler] => onCheckRequirement
)

[2015/05/15 09:36:53] System check: liveConnection
[2015/05/15 09:36:53] Server request: ping
[2015/05/15 09:36:53] Request information: Array
(
    [url] => http://octobercms.com/api/ping
    [content_type] => 
    [http_code] => 0
    [header_size] => 0
    [request_size] => 0
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.000482
    [namelookup_time] => 0
    [connect_time] => 0
    [pretransfer_time] => 0
    [size_upload] => 0
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => -1
    [starttransfer_time] => 0
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 
    [certinfo] => Array
        (
        )

    [primary_port] => 0
    [local_ip] => 
    [local_port] => 0
)

**Comment by saicho34** [comment]
When i reinstall octobercms using wizard the problem that keep occuring is Test connection to the installation server error. please see log above.

**Comment by daftspunk** [comment]
Yes, it confirms that your webserver is unable to make an outgoing connection. Check Apache / PHP error logs.

**Comment by saicho34** [comment]
Hi I found out the problem in Ubuntu 14.04 using vps this will serve as another resolution. It's the resolvconf in ubuntu that cause unstable connection firewall has no problem for me. If Anyone encounter it. Please try to Uninstall resolvconf then reinstall it if you have resolvconf. and make sure to set your /etc/resolv.conf permanent using chattr +i /etc/resolv.conf .
