### ISSUE TITLE
Server goes offline after customizing backend logo, App name, etc

### ISSUE THREAD

**Issue by daviskoko** [octobercms/october#1137]
Hi, I downloaded a new installation & installed it on wamp server. Everything worked just fine. Then I customized the backend style - logo, App Name, etc. ...  the server goes offline.
![october](https://cloud.githubusercontent.com/assets/4718067/7650611/2f7563f8-faf0-11e4-9f62-d72efe7ee06f.PNG)
![octobererror](https://cloud.githubusercontent.com/assets/4718067/7650655/8fd935f8-faf0-11e4-883d-514599e461a5.PNG)

**Comment by Shahiem** [comment]
Same.  It's still  a bug

**Comment by daftspunk** [comment]
Try adding this to your `/config/cms.php` file:

```
// 256KB stack. Win32 Apache
ini_set('pcre.recursion_limit', '524');
```

**Comment by daviskoko** [comment]
It didn't work.

**Comment by daftspunk** [comment]
Bummer.

I have implemented a solution that should take care of it hopefully. See 4f2c11e9db7f20a42f58fd74b2797a84c5234a9d
