### ISSUE TITLE
Invalid data alert while moving report widgets

### ISSUE THREAD

**Issue by scottbedard** [octobercms/october#1140]
Report widgets cannot be re-ordered after one has been deleted, a sweetalert of "Invalid data posted." is displayed, and new position is not saved.

### Steps to reproduce
1. Create a dashboard with at least 3 report widgets
2. Delete one of the widgets
3. Reorder the remaining two widgets

### Expected result
The report widgets should be swapped

### Actual result
An error message of "Invalid data posted." is displayed.

![invalid](https://cloud.githubusercontent.com/assets/7980426/7665166/5bd6598c-fb79-11e4-947f-546592c363f8.png)

**Comment by daftspunk** [comment]
Replicated succesfully

**Comment by daftspunk** [comment]
Fixed by #1141
