### ISSUE TITLE
[Build 260] `cms.enableRedirects` not implemented?

### ISSUE THREAD

**Issue by justin-lau** [octobercms/october#1144]
The commit bb6910a068c6ead6da1b5d1ecd9f2dfe5cec2c23 did not include an implementation of the redirection, just the config value. No redirections happened with multiple slashes in the URL. I wonder if some files were omitted in the commit.

**Comment by daftspunk** [comment]
https://github.com/octobercms/library/commit/690b4d570972271b0128fe26dfe06923c1483f67
