### ISSUE TITLE
colorpicker displays behind partial

### ISSUE THREAD

**Issue by jamiegrand** [octobercms/october#1145]
if colorpicker is being used on a partial, the colorpicker selector sits on a layer behind the partial and can not be selected.
![colrpickerjpg](https://cloud.githubusercontent.com/assets/6545316/7676035/8c89d53a-fd37-11e4-90eb-6c8ff018c957.jpg)

**Comment by scottbedard** [comment]
There is already an issue for this, take a look at #1021
