### ISSUE TITLE
.htaccess uppercase file extension 

### ISSUE THREAD

**Issue by wetgi** [octobercms/october#1147]
I had to add some lines to the .htaccess File:
...
RewriteCond %{REQUEST_URI} !\.JPG
....
because the image upload widget didn't make the file extension lowercase when the file is uploaded. The thumb is thumb_name.JPG if I upload an Image like name.JPG

**Comment by daftspunk** [comment]
Rules are not case sensitive, as indicated by the `NC` part of this definition

```
RewriteRule ^ index.php [L,NC]
```
