### ISSUE TITLE
Upper case jpg image is in incorrect category (documents)

### ISSUE THREAD

**Issue by dk547** [octobercms/october#1156]
http://take.ms/DR82g

If image name is in upper case (3434DF.JPG) it thinks that it isn't image, but document

**Comment by romaldyminaya** [comment]
I have the same problem,

I have uploaded an image file called `Capture.PNG` and then when it generates the link to it `(http://localhost/october/storage/app/media/Capture.PNG)`, it says 404 not found.

Thanks in advice.

**Comment by wetgi** [comment]
I had the same problems here: https://github.com/octobercms/october/issues/1147
I added all extensions in Uppercase to the .htaccess file and now it works

**Comment by daftspunk** [comment]
Looks like we made need to force lower case extensions

**Comment by daftspunk** [comment]
Fixed a while back by e1bb4ec3de2c3cce5a63f75661c940c12d916954
