### ISSUE TITLE
repo tags ? 

### ISSUE THREAD

**Issue by obayesshelton** [octobercms/october#1157]
Hi, 

Is there a reason why there are no tags ? I want to get the composoer.json for a specific version but I cannot figure out how I would get it ? 

obayesshelton

**Comment by daftspunk** [comment]
Tags are not needed as October is evergreen. Feel free to navigate the git history to find an older version, any issues will be unsupported.

**Comment by zdavis** [comment]
Seems like this position might be worth rethinking. Evergreen is nice in theory, but in practice there are often good reasons why people can't update, especially if new releases introduce regressions or breaking changes. Evergreen or not, you're going to be releasing versions, such as the RC1 that you recently announced on your blog. Deciding to put out a release candidate is not an arbitrary decision, and tags help your development community to see important moments in the repository history. 

Just my .02—we're in the process of seriously considering using October on a relatively large, potentially high profile project, and the lack of tagging and versioning will definitely give my team pause.

**Comment by daftspunk** [comment]
October's architecture is built so the front-end is entirely abstracted from the core and the application value is delivered by Plugins, which do carry versioning and should use tags.

Thanks for your feedback, we will introduce tags in the core should the day come when a breaking change occurs beyond RC.

**Comment by obayesshelton** [comment]
nice to know how much you value your users input, I won't be using october on any other projects anyway so not a great loss.

**Comment by daftspunk** [comment]
Not sure what you mean by that, I said we would be using tags in future. It was due to user input that we had an open beta in the first place. It is impossible to win with everyone. If you think you can do it better, then make your own CMS, or there is always WordPress.

**Comment by daftspunk** [comment]
Deleting this issue because it annoys me, clearly @obayesshelton has decided to use the beta version for a production site and complains of no support [tagging], when no support was ever offered for beta and using a beta version was strongly advised not to be used for production sites.
