### ISSUE TITLE
Error: "Mass assignment failed for model attribute"

### ISSUE THREAD

**Issue by daviskoko** [octobercms/october#1159]
Hi, I followed the back-end relations video by Samuel. I have a Model "Model1" which has many records in "Model2". But whenever i add fields in the field.yaml file of "Model2" i get this error "Mass assignment failed for model attribute"

**Comment by scottbedard** [comment]
http://laravel.com/docs/5.0/eloquent#mass-assignment

**Comment by daftspunk** [comment]
Yes, make sure the guarded property is empty.

The plugin itself is available for you to test:

https://github.com/daftspunk/oc-crm-plugin

**Comment by daviskoko** [comment]
Yeah. the laravel doc. was helpful
