### ISSUE TITLE
Installation fails when creating admin account

### ISSUE THREAD

**Issue by patschi** [octobercms/october#1163]
I'm trying since couple of hours to get OctoberCMS installed for the first time, but I ran out of ideas... It seems that the part for creating an admin account does fail because of invalid mysql credentials?

I'm quite sure that the entered mysql database data was correct and that I did not entered "root" as username as I can read in the "tracelog #0" line.

Thanks for any help!

<pre>[2015/05/26 01:09:17] Install step: createAdmin
[2015/05/25 11:09:17] Handler error (onInstallStep): SQLSTATE[HY000] [2002] No such file or directory
[2015/05/25 11:09:17] Trace log:
#0 /var/www/domain.tld/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(47): PDO->__construct('mysql:host=loca...', 'root', '', Array)
#1 /var/www/domain.tld/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 /var/www/domain.tld/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(58): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 /var/www/domain.tld/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(47): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 /var/www/domain.tld/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(177): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#5 /var/www/domain.tld/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(65): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 /var/www/domain.tld/plugins/renatio/dynamicpdf/vendor/illuminate/support/Facades/Schema.php(26): Illuminate\Database\DatabaseManager->connection()
#7 /var/www/domain.tld/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(118): Illuminate\Support\Facades\Schema::getFacadeAccessor()
#8 /var/www/domain.tld/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(202): Illuminate\Support\Facades\Facade::getFacadeRoot()
#9 /var/www/domain.tld/modules/system/classes/UpdateManager.php(121): Illuminate\Support\Facades\Facade::__callStatic('hasTable', Array)
#10 /var/www/domain.tld/modules/system/classes/UpdateManager.php(121): Illuminate\Support\Facades\Schema::hasTable('migrations')
#11 /var/www/domain.tld/install_files/php/Installer.php(512): System\Classes\UpdateManager->update()
#12 /var/www/domain.tld/install_files/php/Installer.php(369): Installer->createAdminAccount()
#13 /var/www/domain.tld/install_files/php/Installer.php(48): Installer->onInstallStep()
#14 /var/www/domain.tld/install_files/php/boot.php(74): Installer->__construct()
#15 /var/www/domain.tld/install.php(1): include('/var/www/site...')
#16 {main}</pre>

(BTW: It seems that the time is also jumping one hour backwards in the trace log messages. Maybe the framework does overwrite it?)

**Comment by daftspunk** [comment]
This is a problem with your MySQL server. You may need to explicitly define the socket to use, for example in your database.php file using `unix_socket`:

```
'connections' => array(

		'mysql' => array(
			'driver'   => 'mysql',
			'host'     => 'localhost',
			'unix_socket'   => '/Applications/MAMP/tmp/mysql/mysql.sock',
			'database' => 'database',
			'username' => 'user',
			'password' => 'pass',
			'charset'  => 'utf8',
			'prefix'   => '',
		),

	),
```
The path needs to be correct to your **mysql.sock** file

**Comment by patschi** [comment]
Thanks for your fast response.

The problem is, that I do not have a MySQL socket in the machine, 
because the database is running in an own virtualized machine - so only 
TCP/IP is possible. The MySQL data is correct for sure, because the 
connection from the phpMyAdmin interface in the same virtual machine is 
possible to the database. That's why I'm a bit confused.

Before I tried SQLite as the database, but with this method I also got 
the error `SQLSTATE[HY000] [2002] No such file or directory`... But 
sadly I don't have the trace log anymore of it. I can try it later at 
home again.

**Comment by patschi** [comment]
I just tried it once again, selected SQLite as database and selected "Use a project ID" for the "installation method", but the error seems to be the same:
<pre>[2015/06/05 11:55:44] Install step: createAdmin
[2015/06/05 09:55:44] Handler error (onInstallStep): SQLSTATE[HY000] [2002] No such file or directory
[2015/06/05 09:55:44] Trace log:
#0 /var/www/domain.tld/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(47): PDO->__construct('mysql:host=loca...', 'root', '', Array)
#1 /var/www/domain.tld/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 /var/www/domain.tld/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(58): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 /var/www/domain.tld/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(47): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 /var/www/domain.tld/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(177): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#5 /var/www/domain.tld/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(65): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 /var/www/domain.tld/plugins/renatio/dynamicpdf/vendor/illuminate/support/Facades/Schema.php(26): Illuminate\Database\DatabaseManager->connection()
#7 /var/www/domain.tld/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(118): Illuminate\Support\Facades\Schema::getFacadeAccessor()
#8 /var/www/domain.tld/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(202): Illuminate\Support\Facades\Facade::getFacadeRoot()
#9 /var/www/domain.tld/modules/system/classes/UpdateManager.php(121): Illuminate\Support\Facades\Facade::__callStatic('hasTable', Array)
#10 /var/www/domain.tld/modules/system/classes/UpdateManager.php(121): Illuminate\Support\Facades\Schema::hasTable('migrations')
#11 /var/www/domain.tld/install_files/php/Installer.php(512): System\Classes\UpdateManager->update()
#12 /var/www/domain.tld/install_files/php/Installer.php(369): Installer->createAdminAccount()
#13 /var/www/domain.tld/install_files/php/Installer.php(48): Installer->onInstallStep()
#14 /var/www/domain.tld/install_files/php/boot.php(74): Installer->__construct()
#15 /var/www/domain.tld/install.php(1): include('/var/www/...')
#16 {main}</pre>

Any suggestions?
