### ISSUE TITLE
Error Upon CLI Install

### ISSUE THREAD

**Issue by n3tninj40** [octobercms/october#1164]
Getting an error after the command upon install: "php artisan october:up"

Error reads>>> "[PDOException] SQLSTATE[HY000]: General error: 2030 This command is not supported in the prepared statement protocol yet"

Config= PHP5, Apache2 with all updates and possible error caveats configured, MemSQL with the MySQL client driver on Ubuntu 14.04.2 full patched. Any feedback welcome as I'd like to use October in production asap.

(Possible solution?: https://github.com/laravel/framework/issues/53 )

**Comment by daftspunk** [comment]
MemSQL is not supported by Laravel, hence October, at this time.
