### ISSUE TITLE
Form Object Missing Layout

### ISSUE THREAD

**Issue by Eein** [octobercms/october#1175]
Short and sweet issue I can circumvent on my end, but was wondering if this was intended behavior:

When editing a CMS page, i'm dumping the Form object at the `backend.form.extendFields` event. (see dump below) Theres a `layout` parameter registered in the class, but it doesn't ever look like it gets assigned. Having that fill in the Layout object relative to the page (on load, and maybe changed on refresh) would make it trivial to access component parameters through the layout. 

![](http://i.imgur.com/HYgI0Wk.png)

More details on what i'm doing:

I'm creating a custom fields plugin, that allows you to just drop components in, select a field type, then edit those fields on the Page / Static Pages. (Template Variables ala MODX).

I need access to the layout at this point, to determine what custom fields have been added to the pages layout.

If this is the intended behavior at this point in the lifecycle, then feel free to close this issue. But personally I don't think theres any reason not to have a reference to the layout object at this point, unless theres an deeper rooted problem when you change the layout.

This isn't a rush or game-breaking deal, because I can get what I need by other means. Just an observation!

Thanks for all your hard work!

**Comment by daftspunk** [comment]
That layout property is coming from the ViewMaker trait, it makes reference to the *backend* layout. I think it would be wise to make your own custom object, in favor of re-purposing existing ones -- It may have undesirable consequences.
