### ISSUE TITLE
config/cms uploaded files incorrect storage path used

### ISSUE THREAD

**Issue by ARH-Digital** [octobercms/october#1183]
When editing config/cms.php 

Changing the default uploads directory will change all links to the files for the new path, but not where the file is actually uploaded to and stored. 

![screen shot 2015-06-02 at 10 15 20 am](https://cloud.githubusercontent.com/assets/5818660/7926174/d5050b8c-0911-11e5-9290-210eab1fc2fa.png)

This renders images as been broken but with the supplied path 

![screen shot 2015-06-02 at 10 31 16 am](https://cloud.githubusercontent.com/assets/5818660/7926214/8e768e06-0912-11e5-9d64-f1775f452bd9.png)

However, the image uploaded is stored in the default '/storage/app/uploads'
So all links to images in the backend and front end are pointing to an invalid location.

![screen shot 2015-06-02 at 10 15 41 am](https://cloud.githubusercontent.com/assets/5818660/7926198/482fd0f6-0912-11e5-8d5c-047369e346d2.png)

The default configuration is not editable as it creates broken images everywhere.

**Comment by LukeTowers** [comment]
@daftspunk For further consideration, we may need to add support for custom paths in the `october:mirror` console command

**Comment by daftspunk** [comment]
Thanks @LukeTowers, were you able to replicate this by any chance?

**Comment by LukeTowers** [comment]
@daftspunk Not yet, I'll bump it up on my todo list

**Comment by daftspunk** [comment]
The actual locally stored path is set by the config `filesystems.disks.local.root`. The `cms.storage.uploads.path` config item is used for determining the public path. Both will need to be changed.
