### ISSUE TITLE
[Question] RelationController Behavior

### ISSUE THREAD

**Issue by cybear-d** [octobercms/october#1184]
When relation behavior pop up the form (e.g. create, update), it requesting the form using ajax to the main controller, then generating the form again for the main controller. 

e.g when relation form is use, it requesting to the same controller and action depending on where the relation behavior called, like when create action or update action. After that it will create the main form makeWidget('Form') again before initRelation() called. Then if we have plugin that extended by a lot of other plugins (e.g extend the form fields), it will call all the extended plugins even though we don't need them for the relation form.

I think it is not necessary because when we use the relation we don't use the main form from main controller. 
It's taking more resources for the database and memory if we have more logic when there is a lot of plugin extending the form fields from the main controller.

**Comment by daftspunk** [comment]
What is the question? The entire workflow you describe is necessary for the AJAX to function correctly. All widgets should be initialised in the constructor process, this is not as costly as you might think.

**Comment by cybear-d** [comment]
sorry for the unclear question.
i want to ask can we bypass the makewidget form when relation was called? 
like using context relation?
because we don't use the whole widget for the relation right?

Example:
http://laravel.io/bin/DeeNz#33-34,58

**Comment by daftspunk** [comment]
I see what you mean, FormControllers works complimentary to RelationController. If you want to use RelationController by itself, then all you need to do is `initRelation()` against the parent model in the controller's constructor or action method.
