### ISSUE TITLE
[Bug]? My settings menus disappear.

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#1186]
When I navigate to the Updates page, the My settings menu group disappear in slide menu. Is it bug?
![update-menu](https://cloud.githubusercontent.com/assets/2959112/7978186/039d8028-0a93-11e5-8456-614bbb11119e.jpg)

**Comment by daftspunk** [comment]
Paste the code you are using to register the settings menu

**Comment by gergo85** [comment]
I use the old code, sorry.

But the following code is used by the Backend Plus plugin:
<code>        BackendMenu::registerContextSidenavPartial(
            'October.System',
            'system',
            '~/plugins/indikator/backend/partials/_system_sidebar.htm'
        );</code>
The own partial doesn't load in Updates page. But it works in other pages.

**Comment by daftspunk** [comment]
The back-end settings navigation links can be extended by overriding the `registerSettings()` method inside the [Plugin registration class](registration#registration-file). When you create a configuration link you have two options - create a link to a specific back-end page, or create a link to a settings model. The next example shows how to create a link to a back-end page.

    public function registerSettings()
    {
        return [
            'location' => [
                'label'       => 'Locations',
                'description' => 'Manage available user countries and states.',
                'category'    => 'Users',
                'icon'        => 'icon-globe',
                'url'         => Backend::url('october/user/locations'),
                'order'       => 500,
                'keywords'    => 'geography place placement'
            ]
        ];
    }

**Comment by daftspunk** [comment]
Ah yes, plugins are not booted for the system updates page for stability reasons. This plugin may need to define

```
public $elevated = true;
```

In the plugin registration file

**Comment by gergo85** [comment]
Thank you so much for your speedy reply.
