### ISSUE TITLE
Fileupload issues

### ISSUE THREAD

**Issue by ariponce** [octobercms/october#1202]
I've detected several little issues with the new fileupload widget

1. When using the fileupload on a modal, first the upload icon has a little design problem and after uploading an image, the image preview overflows it's container

![1](https://cloud.githubusercontent.com/assets/1083390/8102952/95e96f1e-1024-11e5-8f08-4eb48b382b55.png)

![2015-06-11-102917_1920x1027_scrot](https://cloud.githubusercontent.com/assets/1083390/8102985/fcf182d2-1024-11e5-992b-5e90c8b5d6b6.png)

The overflowing problem comes from the ```width: auto;``` property set on the image itself, removing it, displays the image correctly.

2 . When uploading an XLS file, an upload error is thrown, saying that the file data must be a file of type and a list of file formats, including XLS.
Also, any reason why XLSX files are not accepted? We could use them before, but now they're not accepted
![2015-06-11-103641_1920x1027_scrot](https://cloud.githubusercontent.com/assets/1083390/8103064/c8b2f2d4-1025-11e5-895f-ed5dfb2456c9.png)

**Comment by daftspunk** [comment]
Fixed the styling issues.

Point (2) is addressed in Build 271 - *File Upload form widget can now specify `mimeTypes` to define MIME types that are accepted by the uploader, either as file extension or fully qualified name.*
