### ISSUE TITLE
Media Manager - Form  Field type 'mediafinder'

### ISSUE THREAD

**Issue by hjfigueira** [octobercms/october#1211]
Hello,

When using an form widget with type 'mediafinder' the system throws an exception.

throw new SystemException(Lang::get('backend::lang.partial.not_found_name', ['name' => $partialPath])); at line 61

Aparently the file 'widgets/form/partials/_field_mediafinder.htm' cant be found, so i  searched for this file literaly everywhere, (even github), but nothing.

**Comment by Shahiem** [comment]
Same bug.

**Comment by jonpxpx** [comment]
I can confirm the same. Haven't seen a version update past 262 though so has it been rolled out?

**Comment by daftspunk** [comment]
This feature is introduced in Build 269 make sure you have updated and are using `edgeUpdates`

**Comment by jonpxpx** [comment]
$value is pulled through as an array throwing this error:

substr() expects parameter 1 to be string, array given
/modules/cms/FormWidgets/mediafinder/partials/_image_single.htm line 19

Likely anything else after will throw the same error?

Sorry for re-opening.

**Comment by jonpxpx** [comment]
Just for the other guys, dont try adding this to an attachMany field... This was human error and my rookie mistake and is what causes the above problem :) :+1:

**Comment by jonpxpx** [comment]
I did hit an issue in the end...

**To replicate:**
Set image, save and close.
Go back to image, it no longer shows the thumbnail with the delete icon.

![Imgur](http://i.imgur.com/QGUXiXB.png)

On a quick look through the console, it's not pulling in the source path.

![Imgur](http://i.imgur.com/6aRoWPI.png)

Also, I assumed there would be a way to potentially use the .thumb() helper on the front-end, I understand that it wouldn't work based on it being a string saved, but options do we potentially have here?

The path is also relative path from the media directory and we have no way of determining whether that's in storage/uploads or storage/media (I have 2 folders for my app atm).

Would it be possible to {{ post.featured_image|storage }} or something similar?

Hopefully the above helps somewhat.

**Comment by hjfigueira** [comment]
@jonpxpx guess you should open a new issue, the same problem is happening to me too.

**Comment by jonpxpx** [comment]
Yes, already did @hjfigueira it's here #1215

**Comment by hjfigueira** [comment]
:+1:

**Comment by arbuuuud** [comment]
type: Cms\FormWidgets\MediaFinder
instead of
type: mediafinder

**Comment by daftspunk** [comment]
Please open a new issue if this still exists for anyone.
