### ISSUE TITLE
Allow other tags in richeditor

### ISSUE THREAD

**Issue by Rias500** [octobercms/october#1212]
Right now the richeditor is stripping tags like `<div>` and replacing them with `<p>`, this is causing some issues for us when trying to create some layouts with bootstrap columns inside the richeditor.

Could it be possible to allow for some other safe tags like div & span?

**Comment by jonpxpx** [comment]
You may want to place any code you are trying to post within a Markdown code wrapper.

**Comment by Rias500** [comment]
What I want to write:
```
<div class="col-sm-7 slide-left" id="parallax">
	<img src="http://placehold.it/300x300" class="img-responsive layer" data-depth="0.1">
</div>
<div class="col-sm-5 slide-right">
<h1>Test title</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Non enim iam stirpis bonum quaeret, sed animalis. <br/>Verum hoc idem saepe faciamus. Praeclare hoc quidem. Hoc est non dividere, sed frangere. Itaque et manendi in vita et migrandi ratio omnis iis rebus, quas supra dixi, metienda.  </p>
</div>

```

What ends up being inside the richeditor:
```
<p class="col-sm-7 slide-left" id="parallax">
	<img src="http://placehold.it/300x300" class="img-responsive layer" data-depth="0.1">
</p>
<h1>Test title</h1>
<p class="col-sm-5 slide-right">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Non enim iam stirpis bonum quaeret, sed animalis. <br/>Verum hoc idem saepe faciamus. Praeclare hoc quidem. Hoc est non dividere, sed frangere. Itaque et manendi in vita et migrandi ratio omnis iis rebus, quas supra dixi, metienda.  
</p>

```

As you can see the <h1> gets kicked out of the container and the div tags are replaced by <p>. Allowing <div> would help a lot.

**Comment by hybridvision** [comment]
Have you considered using snippets? See: https://octobercms.com/blog/post/introducing-snippets

Maybe that will be a more robust and elegant solution, depending on what you're trying to achieve... Or alternatively partials / components.

**Comment by RuZniki** [comment]
I also want to customise allowed tags, I want to have ability to add `div` tags.
I found how it's [possible to do](http://imperavi.com/redactor/docs/settings/clean/).
Now I don't understand where I need to put my custom js, to overide redactorJs settings, so it will not be erased during update.

**Comment by daftspunk** [comment]
The ability to allow custom tags is now possible in the #2005 enhancement.
