### ISSUE TITLE
Extra for Media Manager - Form Field type 'mediafinder' #1211

### ISSUE THREAD

**Issue by jonpxpx** [octobercms/october#1215]
I did hit an issue in the end...

**To replicate:**
Set image, save and close.
Go back to image, it no longer shows the thumbnail with the delete icon.

![Imgur](http://i.imgur.com/QGUXiXB.png)

On a quick look through the console, it's not pulling in the source path.

![Imgur](http://i.imgur.com/6aRoWPI.png)

Also, I assumed there would be a way to potentially use the .thumb() helper on the front-end, I understand that it wouldn't work based on it being a string saved, but what options do we potentially have here as a user could select an image that is huge in size?

The path is also a relative path from the media directory and we have no way of determining whether that's in storage/uploads or storage/media (I have 2 folders for my app atm).

Would it be possible to {{ post.featured_image|storage }} or something similar?

Hopefully the above helps somewhat.

**Comment by daftspunk** [comment]
Fixed in 91c061f60a0e9da8d9b6940df1269f03ef398b57 (Build 270)
