### ISSUE TITLE
Slug generator crashes when typing "this"

### ISSUE THREAD

**Issue by krisawzm** [octobercms/october#1223]
The slug generator thing "crashes" when typing "this". Well, it doesn't crash, it just stops slugifying whatever is after "this". Meaning, if you make changes to the text before "this", it updates.

### Steps to reproduce:

1. Go to CMS > Pages in the backend.
1. Add a new page.
1. Fill in any text containing the following characters into the title text box: **this**

### Result:

In the URL text box, you'll see that the auto generated URL stops where "this" starts.

### Expected result:

The URL text box should contain a value where "this" is slugified just like any other word.

### Example:

<img src="https://photos-2.dropbox.com/t/2/AABuoVVkNu6Cb1QAyhp5YdVhUATLnvy1ZEEQDGM9fM45TA/12/404676860/png/32x32/1/1434729600/0/2/Screenshot%202015-06-19%2016.21.37.png/CPzB-8ABIAEoAQ/FDxALrspBX9Y8Epkv0KR3WWnKmDANTHCUJ1yvii5cnY?size=1280x960&size_mode=2">

**October Build:** 270

**Comment by daftspunk** [comment]
The slug generator ignores fluff words like "is" , "this", etc

**Comment by krisawzm** [comment]
Why?

**Comment by flip4bytes** [comment]
@krisawzm it's for a few reasons primarily SEO purposes. Word like "is, the, that, then, etc. Are not useful in th URI. The a just unnecessary fluff words. Go look at some major blogs, they don't include those unnecessary words either. You can override th slug if you really want to, though what @daftspunk did out of the box is regarded as the more proper way to handle slugs. Again, you can always override the slug after-the-fact.

**Comment by krisawzm** [comment]
Fair enough.
