### ISSUE TITLE
Markup : flash session doesn't display multiple messages of the same type

### ISSUE THREAD

**Issue by ArisuOngaku** [octobercms/october#1225]
I found a bug in markup that prevents multiple flash messages of the same type to show width the {% flash %} tag.

Exemple :
if I register 5 error flash messages and 5 warning messages, {% flash %} {% endflash %} will only show up the first registered error message and the first warning one.
However, we can pass over this bug by specifying a message type to show.
To make my exemple work, I have to write {% flash error %} {% endflash %}  {% flash warning %} {% endflash %}. Works but not fine as I have to repeat code in some cases.

Best regards

**Comment by jwilson8767** [comment]
confirmed.

Replication: `Flash::error('some message');` a couple times, then check output of `Flash::all()` or use the {% flash %} twig tag to see errors after the first are dropped.

**Comment by daftspunk** [comment]
Fixed by #1693
