### ISSUE TITLE
Cannot AJAX update with subfolder partials

### ISSUE THREAD

**Issue by damanic** [octobercms/october#1226]
It is not clear how you would use `data-request-update=` to make use of partials in subfolders.

For example, if a I have a partial `members\details_form.htm` the following form request causes a parse error,

```<form data-request="onSaveMemberDetails" data-request-update="members\details_form: '#members_detail_form_container'">```

**Comment by daftspunk** [comment]
Try this

```
<form data-request="onSaveMemberDetails" data-request-update="'members\details_form': '#members_detail_form_container'">
```

**Comment by damanic** [comment]
facepalm? I was certainly tired... but amazed if I didn't see the slash orientation. By the time I found an alternative solution my slash dyslexia must have passed. 

Note to self: Sleep before posting issues!

```
			$(this).request('onAction', {
				update: { 'members/details_form' : '#details'},
				beforeSend: function() {
					
				},
				complete: function() {
	
				},
				success: function(data) {
	
				}
			});
```
