### ISSUE TITLE
Dependency Plugin - Problem

### ISSUE THREAD

**Issue by LucasZdv** [octobercms/october#1227]
Hello,
I'm developing a plugin that requires ["laravelcollective/remote"](http://laravelcollective.com/docs/5.0/ssh) and I'm trying this:

In plugin.php

        // Register ServiceProviders
        App::register('Collective\Remote\RemoteServiceProvider');

        // Register aliases
        $alias = AliasLoader::getInstance();
        $alias->alias('SSH', 'Collective\Remote\RemoteFacade');

And I created a composer.json file in the folder of plugin.

    {
        "name": "author/plugin",
        "description": "description.",
        "homepage": "homepage",
        "authors": [
            {
                "name": "LucasZdv"
            }
        ],
        "require": {
            "laravelcollective/remote": "~5.0"
        }
    }

But this does not work, I get the following error: [see screenshot](http://nimb.ws/mFgAuG)

however if I try this on October composer.json file, this works.

    "require": {
            "php": ">=5.4",
            "october/rain": "~1.0",
            "october/system": "~1.0",
            "october/backend": "~1.0",
            "october/cms": "~1.0",
            "laravel/framework": "5.0.*",
            "illuminate/html": "5.0.*",
    +       "laravelcollective/remote": "~5.0" 
        },

Any Ideas?

On the other hand, it behaves as october when two or more plugins require the same dependencies. creates X times vendor/dependencies?
for example

    author1/plugin1/vendor/laravelcollective/remote
    author2/plugin2/vendor/laravelcollective/remote
    author3/plugin3/vendor/laravelcollective/remote

if this is so I do not consider good.
I think the plugins must use the main composer.json of october

**Comment by felixinx** [comment]
Hi,

I think that you **can't** make a `composer.json` in you're plugin, but you *should not* modify the original October composer.

Just include the vendor folder and built it you're self.

**Comment by daftspunk** [comment]
This error shows you might be including a package that requires Laravel 5.1, October currently uses Laravel 5.0

**Comment by LucasZdv** [comment]
Thanks for answering,
But I could not resolve this error, using a composer.json in the plugin is not working.
But if I do it in October composer.json, this works fine.

This works! "october/composer.json"

    "require": {
            "php": ">=5.4",
            "october/rain": "~1.0",
            "october/system": "~1.0",
            "october/backend": "~1.0",
            "october/cms": "~1.0",
            "laravel/framework": "5.0.*",
            "illuminate/html": "5.0.*",
    +       "laravelcollective/remote": "~5.0" 
        },
