### ISSUE TITLE
MediaManager not working with Firefox and IE

### ISSUE THREAD

**Issue by dhb52** [octobercms/october#1242]
When I use mediafinder as form field on backend, which triggers MediaManager to upload or select a picture, It seems to be problem with both Firefox and IE11

```
Firefox 38.0.5, Windows8.1 x64: can't select a picture using mouse click, only work with arrows on keyboard.
IE11: totally disaster, I can't even see the uploaded pictures.
```

**Comment by dotgreg** [comment]
Same problem here

On a vanilla octobercms installation, the mediafinder opens on windows 8 Firefox, we can browser categories, upload a file, but impossible to select a file.
There is no js error related.

**Comment by daftspunk** [comment]
Unable to replicate,

Was able to select a file. Make sure you highlight it then click "Insert" or use double click.

- Tested Firefox 47.0.1.
- Looks fine in IE Edge and IE 11.

Windows 10

**Comment by LukeTowers** [comment]
Closed due to lack of follow up from @dhb52 or @dotgreg.
