### ISSUE TITLE
Add Code tag and highlight to the Rich Text Editor

### ISSUE THREAD

**Issue by exotickg1** [octobercms/october#1243]
Of course, we can just use the ```<code>```, but with icon on panel, it would be more useful.
october/modules/backend/formwidgets/richeditor/
Thanks.

![c9755de19bc4c80cc9350699b1665395 1](https://cloud.githubusercontent.com/assets/7385304/8396747/30f1ee24-1dd5-11e5-8541-cb01136b678f.png)

**Comment by daftspunk** [comment]
Nice idea, how do we do it?

**Comment by exotickg1** [comment]
What about https://highlightjs.org/ ?

After clicking on icon -> open Popup window, which contain list of syntax, theme chooser (highlight) and text area for code?

**Comment by exotickg1** [comment]
I found one more syntax highlighting.

https://github.com/chriskempson/base16

**Comment by daftspunk** [comment]
After #2005, this should now be possible by using custom CSS classes.
