### ISSUE TITLE
Backend Login Redirect - does not go to backend.

### ISSUE THREAD

**Issue by damanic** [octobercms/october#1244]
Having an issue on backend. After login we are getting redirected to the wrong place. 

I often get redirected to /favicon.ico

Any idea what might be causing this?

This is on bleeding edge updates.

**Comment by lazycms** [comment]
reinstall...

**Comment by damanic** [comment]
re-install again... rather not... 

is that hopeful solution or do you know what the cause might be?

**Comment by lazycms** [comment]
What  your server environment?

**Comment by lazycms** [comment]
I don't have problem.everything ok

**Comment by damanic** [comment]
Centos, Apache, PHP 5.4

**Comment by daftspunk** [comment]
Not sure what might be causing this, the information provided is pretty limited. However it does sound like a webserver configuration issue, perhaps not redirecting properly.
