### ISSUE TITLE
OctoberCMS have plans to upgrade to Laravel 5.1?

### ISSUE THREAD

**Issue by prhost** [octobercms/october#1245]
If you want, you are expected? long deadline or short deadline.

**Comment by oliverpool** [comment]
:+1: As soon as OctoberCMS is upgraded to Laravel 5.1, I plan to start a big project!

**Comment by lazycms** [comment]
please open source your big project.... :-D

**Comment by scottbedard** [comment]
I think the plan is to stay at the current version for a little while because of L5.1's increased PHP requirements

http://octobercms.com/forum/post/is-there-any-schedule-to-move-october-onto-laravel-51-lts

**Comment by prhost** [comment]
Thanks for the reply.
