### ISSUE TITLE
cache:clear CmsException

### ISSUE THREAD

**Issue by DanielHitchen** [octobercms/october#1249]
Hi guys,

Any reason I get the below error in the CLI whenever I try to clear the cache? 
```
[Cms\Classes\CmsException]
The active theme is not found.
```
I do have an active theme, so not really sure what's causing it.

**Comment by DanielHitchen** [comment]
I've since copied the original "demo" theme back into the themes directory, but now when I do a ```php artisan cache:clear``` I get the following exception:
```
[PDOException]
SQLSTATE[HY000] [2002] No such file or directory
```
?

**Comment by DanielHitchen** [comment]
Seems to be a conflict in one of my plugins that's causing the issue, can't understand why though as there's nothing out of the norm in the plugin - I will continue the investigation :)

**Comment by jonpxpx** [comment]
Daniel, that looks to be a mysql issue. Are you working on this localhost? If so, double check your mysql server settings, could be localhost or 127.0.0.1. I know on my localhost that I need to use the latter. Hope that helps.

**Comment by DanielHitchen** [comment]
@jonpxpx , hi, yes I'm just working on Localhost at the moment, but I've never had the issue before (that I know of). I'm still narrowing down the issue by debugging my loaded plugins - will update when I find the cause for future reference

**Comment by jonpxpx** [comment]
Ah ok, good luck with it... Worth checking which server has the correct permissions for the database you are trying to access too though. Hope it all goes well.

**Comment by DanielHitchen** [comment]
Have managed to fix it - it was some of my older plugins built pre-RC (but updated accordingly) that had some old code residing in their ```boot()``` methods - have updated and all running smooth again :)
