### ISSUE TITLE
Erasing exception message when throwing a ValidationException

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1253]
in /rain/src/Exception/ValidationException on line 61 there are the following lines

     if (!is_array($fields))
            $fields = [];

This erases any message someone tries to post via ValidationException and no message is given that ValidationException expects ['fieldname' => 'error message'] as argument. Just a blank message pops up and vanishes again.

I propse it to be changed to either

     if (!is_array($fields))
            $fields = ['unknown'=>$fields];

or

       if (!is_array($fields))
            $fields = ['coder error' => 'Dear developper. If you see this message you have provided the wrong parameters to ValidationException. Please provide the errors in the following format: [\'fieldname\'=>\'Error message\']. The message you tried to post was: '.$fields];

or something like that.

**Comment by daftspunk** [comment]
Fixed by https://github.com/octobercms/library/pull/146
