### ISSUE TITLE
[Bug?] Code Editor issues (Build 275)

### ISSUE THREAD

**Issue by DanielHitchen** [octobercms/october#1257]
Hi,

When updating to Build 275 from 271, the markup section in the CMS > PAGES code editor stops working properly e.g

- Spacebar stops working
- tabs & spaces are out of alignment
- cursor is 2 spaces ahead of typed-text on any existing lines of code

I thought it was my browser at first or a plugin I had installed, but there are no errors in the console, and when I've re-installed back to Build 271 all is fine, but as soon as I update to 275 the above happens - any thoughts?

**Comment by daftspunk** [comment]
Try Build 276

**Comment by DanielHitchen** [comment]
@daftspunk yeah that's fixed now, what was it?

**Comment by daftspunk** [comment]
Minified ACE editor twice
