### ISSUE TITLE
[Bug?] Theme variables not outputting correct info

### ISSUE THREAD

**Issue by DanielHitchen** [octobercms/october#1267]
Hi,

```{{ this.theme.id }}``` is now outputting the ID in number format instead of theme directory, and ```{{ this.theme.description }}``` isn't outputting anything.

**Comment by jwilson8767** [comment]
You may use `{{ this.theme.getId }}` and `{{ this.theme.getConfigValue('description') }}` instead. {{ this.theme.id }} gets the theme model's id number.

**Comment by DanielHitchen** [comment]
Thanks @jwilson8767 , if this is the case, then the [Theme Markup Page](https://octobercms.com/docs/markup/this-theme) will need updating with this info, as previously ```{{ this.theme.id }}``` returned the directory name & ```{{ this.theme.description }}``` returned the description, so guess the docs pages just need updating

**Comment by DanielHitchen** [comment]
For anyone wanting to know how to get the Theme information as listed [here](https://octobercms.com/docs/themes/development#theme-information), you can simply use the method jwilson8767 mentioned above:
```
{{ this.theme.getConfigValue('description') }}
```
Needs adding to docs.

**Comment by daftspunk** [comment]
Using `{{ this.theme.description }}` would refer to a form field called "description" when using the [theme customization](https://octobercms.com/docs/themes/development#customization).

I think in this case you actually want to refer to the theme configuration, right? Then it would be `{{ this.theme.config.description }}`.

The docs appear to be based on `this.page`, etc. so it has included description by mistake. Will fix this.

Good catch!
