### ISSUE TITLE
JavaScript anchors have deprecated href attribute value

### ISSUE THREAD

**Issue by powelski** [octobercms/october#1269]
In October, every anchor being used for triggering JavaScript events has href attribute set to `javascript:;`. This is unnecessary and deprecated. With HTML5, in such cases href attribute should be skipped instead.

Source: http://www.w3.org/TR/html5/document-metadata.html#attr-link-href

**Comment by hybridvision** [comment]
It's true that you don't have to include the `href` but then it becomes a placeholder link and it doesn't behave like a normal link - ie. no cursor change on hover and no link related styling.

Often you do want it to look and work like a normal link so including a `href` doesn't seem like a bad thing, especially if you include a fallback URL for when JavaScript is not working.

Also, your source link refers to document metadata, not anchors...

**Comment by daftspunk** [comment]
Good to know, thanks!
