### ISSUE TITLE
October uses onkeyup instead of oninput

### ISSUE THREAD

**Issue by powelski** [octobercms/october#1270]
October CMS uses `onkeyup` event to trigger functions related to user input, like slug generation. There's better way of handling it. `oninput` event gives immediate effect and therefore provides much smoother experience. The only drawback is that IE8 doesn't support it, so if you want to comfort this browser, a fallback must be used.

**Comment by tschallacka** [comment]
would be good for ie ;-)

**Comment by powelski** [comment]
There's no need to add HTML for IE8, `oninput` can be handled in pure JS for IE8 by a fallback.

**Comment by daftspunk** [comment]
We need to make an assessment at some point to find out what the cut off for IE browsers is. I sincerely doubt IE8 will make the cut, so this shouldn't be a problem. I'll do some testing with `oninput`, thanks.

**Comment by LukeTowers** [comment]
IE8 through 10 are no longer officially supported by Microsoft: https://dln-rad.forces.gc.ca/login-lien/index-eng.jsp

**Comment by danhrrn** [comment]
Currently, IE8 > is only used by 0.21% of people ([source](https://caniuse.com/usage-table)).
I think we can safely say that the majority of these people **do not** use October CMS. Why sacrifice an enhancement for 99% of people just for the sake of the < 0.21% stuck in the stone age?
Can I make a PR for this please?

**Comment by LukeTowers** [comment]
It's save to say that we don't support IE8, heck IE8 doesn't even support media queries so I can guarantee we don't support it.

**Comment by powelski** [comment]
I created this issue almost 3 years ago. As for today, I believe it's good idea to just let IE8-IE10 rest in peace.

**Comment by LukeTowers** [comment]
So does anyone want to open a PR to switch to oninput instead? Provide a detailed explanation for the benefits of doing so please.

**Comment by danhrrn** [comment]
@LukeTowers I am working on a fix now.

**Comment by danhrrn** [comment]
Are there any other repos I need to grep in, or just this one?

**Comment by tschallacka** [comment]
From my personal experience on a different project, oninput is best to use because it catches everything. Also when something is pasted in it without using the keyboard. 
It also prevents race conditions where the "order of events" is going bottoms up.
for example, if you wish to catch when someone **holds** a key down and do things, you need oninput because onkeyup will only trigger when the key is released

See https://jsfiddle.net/70nk1b5x/
Just keep a key pressed in the fields. The oninput updates on every entry.
```
$('#keyup').on('keyup',function() {
    $('#output_keyup').text(this.value.length);
});
$('#oninput').on('input',function() {
    $('#output_oninput').text(this.value.length);
});
```
```
<input type="text" id="keyup">

   onkeyup characters typed <span id="output_keyup"></span><BR/>
<input type="text" id="oninput">

oninput characters typed <span id="output_oninput"></span>
```

**Comment by danhrrn** [comment]
@tschallacka that's exactly why we are moving to `oninput`.

**Comment by LukeTowers** [comment]
Awesome, thanks for the explanation @tschallacka; @danhrrn grep is your friend :) Also, please include @tschallacka's explanation in the PR
