### ISSUE TITLE
In list widget type:switch only shows yes/no

### ISSUE THREAD

**Issue by jBOKA** [octobercms/october#1271]
Hi,

is there a reason why in list columns type switch is not yet rendered as an icon instead of the current Yes/No string?

Referencing this:
```php
    protected function evalSwitchTypeValue($record, $column, $value)
    {
        // return ($value) ? '<i class="icon-check"></i>' : '<i class="icon-times"></i>';
        return ($value) ? 'Yes' : 'No';
    }
```

in

https://github.com/octobercms/october/blob/9ed73e0cbaf4538eecb160e58f819c40e077ed0f/modules/backend/widgets/Lists.php#L855

**Comment by daftspunk** [comment]
Text looks better
