### ISSUE TITLE
Agreeing to the MIT license isn't required

### ISSUE THREAD

**Issue by Calinou** [octobercms/october#1273]
The installer asks you to agree to the MIT license, which is not required.

[GPL FAQ](https://gnu.org/licenses/gpl-faq.en.html#ClickThrough) says:

> **Can software installers ask people to click to agree to the GPL? If I get some software under the GPL, do I have to agree to anything?**
>
> Some software packaging systems have a place which requires you to click through or otherwise indicate assent to the terms of the GPL. This is neither required nor forbidden. With or without a click through, the GPL's rules remain the same.
>
> Merely agreeing to the GPL doesn't place any obligations on you. You are not required to agree to anything to merely use software which is licensed under the GPL. You only have obligations if you modify or distribute the software. If it really bothers you to click through the GPL, nothing stops you from hacking the GPLed software to bypass this.

This is just as valid for the MIT license.

**Comment by daftspunk** [comment]
Good to know, thanks!
