### ISSUE TITLE
[Bug] Theme export error

### ISSUE THREAD

**Issue by DanielHitchen** [octobercms/october#1275]
Hi,

Receiving this pop-up (error) when trying to export a theme:

![error](https://cloud.githubusercontent.com/assets/7501909/8614770/da4377e6-26e4-11e5-8846-8df8724a576c.jpeg)

**Comment by daftspunk** [comment]
Seems to be working for me. Need instructions on how to replicate successfully.

**Comment by daftspunk** [comment]
This only occured on my Mac, the Windows PC seemed unaffected. I think the solution is simple, will push the change now.

**Comment by DanielHitchen** [comment]
Thanks @daftspunk , can confirm now working
