### ISSUE TITLE
UI: Toolbar conflicts with dropdown

### ISSUE THREAD

**Issue by scottbedard** [octobercms/october#1276]
Noticed that dropdowns do not work inside toobars, not a huge issue because I only have a couple buttons, but I thought I'd post it here anyway.

Works...
```html
<div>
    <div class="dropdown">
        <a href="#" data-toggle="dropdown" class="btn btn-primary oc-icon-plus">Add small</a>
        <ul class="dropdown-menu" role="menu" data-dropdown-title="Add something small">
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="oc-icon-folder-close">Group</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="oc-icon-copy">Page</a></li>
        </ul>
    </div>
</div>
```

Doesn't work...
```html
<div data-control="toolbar">
    <div class="dropdown">
        <a href="#" data-toggle="dropdown" class="btn btn-primary oc-icon-plus">Add small</a>
        <ul class="dropdown-menu" role="menu" data-dropdown-title="Add something small">
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="oc-icon-folder-close">Group</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="oc-icon-copy">Page</a></li>
        </ul>
    </div>
</div>
```

**Comment by daftspunk** [comment]
Fixed by adding `dropdown-fixed` class to the dropdown to make it "fixed" positioned

            <div class="dropdown dropdown-fixed">
                <button
                    type="button"
                    class="btn btn-default oc-icon-users"
                    data-toggle="dropdown">
                    Assign selected to...
                </button>
                <ul class="dropdown-menu" data-dropdown-title="Assign selected to...">
                    <li><a href="#" tabindex="-1" class="oc-icon-user">Sally</a></li>
                    <li><a href="#" tabindex="-1" class="oc-icon-user">Steve</a></li>
                    <li><a href="#" tabindex="-1" class="oc-icon-user">Justin</a></li>
                </ul>
            </div>

See docs: http://octobercms.com/docs/ui/toolbar
