### ISSUE TITLE
Crop and Insert button on mediafinder fields

### ISSUE THREAD

**Issue by webdevlocalhost** [octobercms/october#1280]
Crop and insert button in the media manager is not working on mediafinder fields in the backend, because when firing the insert-cropped event the path field is missing.

The issue where the missing path in the items object is causing problems [mediafinder.js line 74](https://github.com/octobercms/october/blob/master/modules/cms/formwidgets/mediafinder/assets/js/mediafinder.js#L74). Lines 91 and 97 with a path of undefined would result in isPopulated false and prevent the image from displaying in mediafinder field.

**Comment by webdevlocalhost** [comment]
[Here is my pull request on this issue.](https://github.com/octobercms/october/pull/1281)

**Comment by daftspunk** [comment]
Fixed by #1281
