### ISSUE TITLE
Feature request : Intergrate Translate plugin in the October core

### ISSUE THREAD

**Issue by felixinx** [octobercms/october#1287]
Hi,

I think that the [Translate Plugin](https://github.com/rainlab/translate-plugin) should be intergrated in the core of October. This will be easier for plugins developers to work with it, as all will have the plugin installed.

Some improvement that could be done if the integration will be made;

- Add a translate button to the Editor.
- Add a Markup function for translating, like `{' translate '}`
- Better plugin integration, directly from the core

Thanks!

**Comment by daftspunk** [comment]
We considered this idea early on, it creates mess and complexity everywhere for single-language sites who don't care for these features (majority). The RainLab.Translate plugin should be capable of handling this by extension, that is the power of October.
