### ISSUE TITLE
Backend tabs are not responsive

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1288]
Everything in the backend is responsive except the tabs defined in fields.yaml

This makes it impossible to navigate the tabs on mobile or smaller screens.

**Comment by daftspunk** [comment]
You should be able to click and drag, just like the main menu.

**Comment by tschallacka** [comment]
Responsive doesn't mean click and drag... It means that it'll work on smaller screens. Right now if you have 7 tabs on mobile they'll go off screen instead of neatly collapsing like all other october features.

--- Oorspronkelijk bericht ---

Van: "Samuel Georges" <notifications@github.com>
Verzonden: 14 juli 2015 09:52
Aan: "octobercms/october" <october@noreply.github.com>
CC: "tschallacka" <mdibbets@outlook.com>
Onderwerp: Re: [october] Backend tabs are not responsive (#1288)

You should be able to click and drag, just like the main menu.

---

**Comment by daftspunk** [comment]
You can use your finger to swipe the entire tab content left/right too.

**Comment by tschallacka** [comment]
hmmmh, that's a bit less intuitive than that it would automatically fold... but okay.
