### ISSUE TITLE
/backend/widgets/Lists.php fails on null

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1289]
When a belongsTo relationship is defined, but a NULL value exists in the relationship column a fatal error occurs crashing with a nondescript error message(Trying to get property of non object)

The issue lies in /backend/widgets/Lists.php line 752

```
elseif ($this->isColumnRelated($column)) {
            $value = $record->{$columnName}->{$column->valueFrom};
        }
```

imho it should be something like:

```
 elseif ($this->isColumnRelated($column)) {
            if(isset($record->{$columnName}) && isset($record->{$columnName}->{$column->valueFrom})) {
                 $value = $record->{$columnName}->{$column->valueFrom};
             }
             else {
                  $value = null;
             }
        }
```

**Comment by daftspunk** [comment]
What is the list column definition you're using?

**Comment by baszczewski** [comment]
Unfortunately, this bug affects me too.

**Comment by LukeTowers** [comment]
@tschallacka @baszczewski is this bug still present in the latest build?

**Comment by tschallacka** [comment]
As far as i can see its fixed now.

**Comment by LukeTowers** [comment]
Thanks for the update @tschallacka!
