### ISSUE TITLE
[Bug?] Theme data not deleted after theme deleted

### ISSUE THREAD

**Issue by DanielHitchen** [octobercms/october#1292]
Hi,

When I delete a Theme via the "Manage" dropdown in the `Settings > CMS > Front-End Theme` section, the related theme data in the DB table `cms_theme_data` isn't removed - should it be?

**Comment by daftspunk** [comment]
Yes, it probably should, but I'm not sure it is a huge issue to have it left behind...

**Comment by DanHarrin** [comment]
Fixed with #4529.

**Comment by bennothommo** [comment]
Fixed by #4529, as @DanHarrin indicated.
