### ISSUE TITLE
Can't change relation name defined on model class

### ISSUE THREAD

**Issue by ahlechandre** [octobercms/october#1299]
> Each definition is an array where the key is the **relation name** and the value is a detail array.

i have 2 Models:
* Professor
* Programa

above summarized code
```php
// Professor model class
protected $table = 'professor';

public $hasMany = [
  'programa' => ['Author\Plugin\Models\Programa']
];

// Programa model class (look at relation name)
protected $table = 'programa';

public $belongsTo = [
  'professor' => ['Author\Plugin\Models\Professor']
];
```
i can normally access
```twig
{{ programa.professor }}  // all right, returning one model
```

but if i change the relation name in Programa, for example
```php
public $belongsTo = [
  'coordenador' => ['Author\Plugin\Models\Professor']
];
```
when i try access
```twig
{{ programa.coordenador }} // returning null
```

am curious for the reason that's happening because i did the same with others relation name in these models and worked fine

**Comment by daftspunk** [comment]
I hope you found a fix for this!
