### ISSUE TITLE
Flash messages are shared between frontend and backend.

### ISSUE THREAD

**Issue by jayalfredprufrock** [octobercms/october#1305]
If a frontend layout doesn't contain the code to display a flash message, it gets displayed by the backend on the next page change. Ideally there could be some kind of separation between the two to prevent this from happening.

**Comment by inna-kostyakova** [comment]
eweee

**Comment by daftspunk** [comment]
Under normal circumstances this should never be an issue, a flash message should always be displayed on the subsequent page load. Unless you have 4 hands and are navigating two sites simultaneously. Flash can remain a shared class for now, unless there is a use case where we need to separate the contexts.

**Comment by felipe-alves-reis** [comment]
On my site I do not use flash message. I have this problem when I use the Ghost plugin, which simulates the login on the front with the user registered in the plugin "frontend user". When I move the user on the frontend, when I go to the administrative part, the message "you were successfully disconnected" @daftspunk

**Comment by LukeTowers** [comment]
@felipe-alves-reis that's an issue with the Ghost plugin then. Either you should implement flash message handling in the frontend or ask the author of that plugin to make flash messages optional. The Flash logic will remain a shared class.
