### ISSUE TITLE
unexpected type of array. Should attribute "attribute" be Jsonable?

### ISSUE THREAD

**Issue by daviskoko** [octobercms/october#1314]
Am not sure what could be coursing this error. 
Using the has many relationship already existing in the controller, I created an 'add more fields' in a component file using jquery. On submission, i get this error
"unexpected type of array. Should attribute "course" be Jsonable?"
However from the backend, the defer binding and relationship works perfect.
Please what am i missing? or is this a bug?:
```
//input from component .htm
<form data-request="onCreate">
<input name="name" type="text" class="form-control" />
<input name="age" type="text" class="form-control" />
<input name="sex" type="text" class="form-control" />
<input name="course[]" type="text" class="form-control" />
<input name="classs[]" type="text" class="form-control" />
</form>

------------------------------------------------------------------------------------------

//component .php
use Wall\Students\Models\Student as StudentModel;
use Wall\Students\Models\Level as LevelModel;
public function onCreate()
{
    $leveldetails = new LevelModel;
    $leveldetails->course = post('course');
    $leveldetails->classs = post('classs');
    $leveldetails->save();
    
	$data = [
        "name" => post('name'),            
        "age" => post('age'),
        "sex" => post('gender'),
    ];

    $student = StudentModel::create($data);

    $student->levels()->add($leveldetails);
}


// Student Model
public $hasMany = [
        'levels' => ['Wall\Students\Models\Level']
    ];


// Level Model
protected $fillable = [
        'name',
        'age',
        'sex',
    ];
```

**Comment by daftspunk** [comment]
course and classes are being submitted as arrays. Try adding to your model

    /**
     * @var array List of attribute names which are json encoded and decoded from the database.
     */
    protected $jsonable = ['course', 'classes'];

This will magically serialize those values for you, or you could just not submit them as html arrays instead:

    <input name="course" type="text" class="form-control" />
    <input name="classs" type="text" class="form-control" />

**Comment by daviskoko** [comment]
Making the fields Jsonable from the Model added the values, but that only works for data type 'String'. It does not work for data type 'Integer', 'Date' and 'DateTime'. Also, removing the block quote '[]' from the input name made it return only the last edited fields, I believe th block quote has to be there to enable it return an array.

**Comment by daviskoko** [comment]
This is the schema for the fields:

```

//Levels Schema
class CreateLevelsTable extends Migration
{

    public function up()
    {
        Schema::create('wall_students_levels', function($table)
        {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->string('course');
            $table->string('class');
            $table->date('start_date');
            $table->date('end_date');
            $table->integer('student_id')->unsigned()->nullable()->index();
            $table->timestamps();
        });
    }

//Students Schema
class CreateStudentsTable extends Migration
{

    public function up()
    {
        Schema::create('wall_students_students', function($table)
        {
            $table->engine = 'InnoDB';
            $table->increments('id'))->unsigned()->index();
            $table->string('name');
            $table->string('age');
            $table->string('sex');
            $table->timestamps();
        });
    }

```

**Comment by tschallacka** [comment]
@daviskoko you should expect some logic from a programmer too... JSON is a string format for data storage. that you are even attempting to store it in a field you assigend to be an integer value or a datetime is... let's just leave it at that, but it's most definately not an october bug.
