### ISSUE TITLE
Validation rules "unique:..." exceptions and additional where clause possible?

### ISSUE THREAD

**Issue by jBOKA** [octobercms/october#1317]
Hi,

in a model's rules definition I'd like to require an attribute say *unique_attribute* to be unique like so:
```php
public $rules = [
    'unique_attribute' => 'unique'
];
```
But I want it to be unique against a subset of the table defined by a where-clause.
(In my case it should be unique against all table entries, where `another_attribute` is equal to current model's `another attribute`, which is not changing during the form post)

In the Laravel documentation the validation rule with additional where-clause is defined as follows:
*You may also specify more conditions that will be added as "where" clauses to the query:*
```php
'unique_attribute' => 'unique:table,column,'.$id.',id_column,where_clause_column,'.$where_clause_value
```

I'd like to specify a where clause value from the request data or an attribute of the model, but the `$this->attribute` reference (as in the Laravel docs example) is not available when defining the rule.

I hope you get my problem. Is this possible?

**Comment by daftspunk** [comment]
You probably want to use the `beforeValidate()` method. Off the top of my head, something like:

```
public function beforeValidate()
{
    $invalid = $this->newQuery()->where(....)->count() > 0;
    if ($invalid) {
        throw new \ValidationException(['unique_attribute' => 'This thing is not valid, try again']);
    }
}
```

**Comment by jBOKA** [comment]
Works like a charm!
Thank you
