### ISSUE TITLE
Fileupload field on belongsTo relation not being saved with the related system file record

### ISSUE THREAD

**Issue by lthurston** [octobercms/october#1319]
Here's how this is set up:

I have a model called Exhibition. It has a belongsTo relation in a field called "image", relation is to another model called DigitalAssets. This model, in turn, has an AttachOne relation configured as a "fileupload" type.

From the editor's perspective, they create an exhibition, and click "Create Image" to add the Image relation. This pops up a creation form for a DigitalAsset. Then the editor can add the image field the upload interface and save. This all seems to work, except that the system file is never actually associated properly with the Image field.

I've made a handful of changes to the logic that handles the deferred bindings, because although they are always stored in the database with the correct master_* and slave_* field values, the code to query for deferred bindings to resolve seems flawed. For example (I can put together code diffs, but I wanted to just get this message out there before the end of the day):

* the query for deferred bindings to resolve isn't passed the current session key, so it's always null, and therefore never finds bindings to resolve
* the query for deferred bindings always queries for the DeferredBindings model as the master_type, instead of the correct type
* in the commitDeferred method in the DeferredBinding trait, ->isDeferrable($relationName) and ->$relationName() is called on $this, rather that on an instance of the master type model. This is again a case where if $this was the master model, it would work, but it doesn't seem to work for me.

With some core changes to ensure that the query and reflection is working as it needs to for the deferred binding, the system files seem to be created correctly. I have other issues with the associated system file being accessible as an attribute on the Exhibition model, but I assume that's something else.

Does it sounds like 1) I'm doing something seriously wrong or 2) that there's maybe a problem with attachOne relations from a belongsTo? I can provide diff snippets if that's helpful, but my main question is just whether is this a known shortcoming / bug or if it would be expected to work if done properly?

**Comment by lthurston** [comment]
I think I might have been overthinking this one a bit. With a call to commitDeferred() in afterSave/() on the DigitalAsset, the binding is committed. Sorry for the clutter.

**Comment by tschallacka** [comment]
In RelationController.php

    public function onRelationManageCreate()
    {
        $this->forceManageMode = 'form';
        $this->beforeAjax();
        $saveData = $this->manageWidget->getSaveData();

        if ($this->viewMode == 'multi') {
            $sessionKey = $this->deferredBinding ? $this->relationGetSessionKey(true) : null;

            if ($this->relationType == 'hasMany') {
                $newModel = $this->relationObject->create($saveData, $sessionKey);
            }
            elseif ($this->relationType == 'belongsToMany') {
                $newModel = $this->relationObject->create($saveData, [], $sessionKey);
            }

            $newModel->commitDeferred($this->manageWidget->getSessionKey());
        }
        elseif ($this->viewMode == 'single') {
            $newModel = $this->viewModel;
            $this->viewWidget->setFormValues($saveData);

            if ($this->relationType == 'belongsTo') {
                $newModel->save();
                                // This here, committing the deferred things
				$newModel->commitDeferred($this->manageWidget->getSessionKey());
                $this->relationObject->associate($newModel);
                $this->relationObject->getParent()->save();
				
            }
            elseif ($this->relationType == 'hasOne') {
                $this->relationObject->add($newModel);
            }
        }

        return $this->relationRefresh();
    }

And in the update function

 public function onRelationManageUpdate()
    {
        $this->forceManageMode = 'form';
        $this->beforeAjax();
        $saveData = $this->manageWidget->getSaveData();

        if ($this->viewMode == 'multi') {
            $model = $this->relationModel->find($this->manageId);
                        // Keep comitting the defferreds
            $model->save($saveData, $this->manageWidget->getSessionKey());
        }
        elseif ($this->viewMode == 'single') {
            $this->viewWidget->setFormValues($saveData);
            $this->viewModel->save();
                        // Keep comitting the defferreds
			$this->viewModel->commitDeferred($this->manageWidget->getSessionKey());
        }

        return ['#'.$this->relationGetId('view') => $this->relationRenderView()];
    }

When I have time i'll try to shape it into a pull request
