### ISSUE TITLE
Internationalize the artisan scaffolded Controller views

### ISSUE THREAD

**Issue by jBOKA** [octobercms/october#1323]
Hi,

my clients are non-English speaking, so I usually setup my Plugins in another language (not the internal class names etc. but the views) The [!]only thing that produces unnecessary effort is to translate the artisan generated scaffold in the controller views each time. I know this is not really a thing to complain about, but would it be possible with some lines of code, to internationalize the scaffold templates based on the default language set in the `app/config.php` of october?

Or better make use of the `Lang` facade und only use those `Lang::get` in the templates?

**Comment by gabsource** [comment]
Hello,

Maybe you could try [https://github.com/gabsource/oc-scaffold-translation-plugin/tree/production].
I've just submitted the plugin `ScaffoldTranslation` on October MarketPlace also.

**Comment by daftspunk** [comment]
As @gabsource mentioned, there's a plugin for that!
