### ISSUE TITLE
Default value for datepicker widget

### ISSUE THREAD

**Issue by axomat** [octobercms/october#1333]
When the datepicker is used with a date / datetime / timestamp column and the value has not been set yet and is therefore null, the initial date of the datepicker is displayed as the minDate. 

The cause is the php conversion of a null date to "-0001-11-30". I made a hack in datepicker.php to look for that value and replace it with Carbon::create()->toDateString() which works but is probably a bad way to fix this, it would be better to catch the null value when the value is got. 

Incidentally, I could not get the default setting for the datepicker type in form.yaml to work. It is not a big deal for me as long as default to today works but it may be for someone else?

**Comment by annejan** [comment]
I would love to be able to set a default of "today" in the (blog) published field.

**Comment by daftspunk** [comment]
Fixed today by #2299!

**Comment by axomat** [comment]
Thank you @daftspunk
