### ISSUE TITLE
Database prefix causes error in /backend/backend/usergroups

### ISSUE THREAD

**Issue by jBOKA** [octobercms/october#1334]
On a clean fresh install (composer), after configuring the database with a prefix (here `test_`) and logging in to the backend I get an SQL error in the backend page for administrator groups, i.e.
`/backend/backend/usergroups`
which is caused by a missing prefix in the query. Is there anything I didn't consider when setting things up? Everthing else works fine.

I get the error with the master and the develop branch as of now.

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'backend_users_groups.user_group_id' in 'field list' (SQL: select backend_users_groups.user_group_id, count(*) as count, `test_backend_users_groups`.`user_group_id` as `pivot_user_group_id`, `test_backend_users_groups`.`user_id` as `pivot_user_id` from `test_backend_users` inner join `test_backend_users_groups` on `test_backend_users`.`id` = `test_backend_users_groups`.`user_id` where `test_backend_users_groups`.`user_group_id` in (1) group by `test_backend_users_groups`.`user_group_id`)
```

I found this QueryBuilder object being the problem, when handed to the SQL compiler of Laravel, where the expression column is not prefixed correctly:
```
QueryBuilder {#428 ▼
  #cacheKey: null
  #cacheMinutes: null
  #cacheTags: null
  #connection: MySqlConnection {#291 ▶}
  #grammar: MySqlGrammar {#293 ▶}
  #processor: MySqlProcessor {#294}
  #bindings: array:5 [▶]
  +aggregate: null
  +columns: array:3 [▼
    0 => Expression {#432 ▼
      #value: "backend_users_groups.user_group_id, count(*) as count"
    }
    1 => "backend_users_groups.user_group_id as pivot_user_group_id"
    2 => "backend_users_groups.user_id as pivot_user_id"
  ]
  +distinct: false
  +from: "backend_users"
  +joins: array:1 [▼
    0 => JoinClause {#431 ▼
      +type: "inner"
      +table: "backend_users_groups"
      +clauses: array:1 [▶]
      +bindings: []
    }
  ]
  +wheres: array:1 [▶]
  +groups: array:1 [▶]
  +havings: null
  +orders: null
  +limit: null
  +offset: null
  +unions: null
  +unionLimit: null
  +unionOffset: null
  +unionOrders: null
  +lock: null
  #backups: []
  #operators: array:26 [▶]
  #useWritePdo: false
}
```

where the Laravel Class `Illuminate\Database\Grammar` simply doesn't wrap columns of type `Expression` with \`...\` and therefore doesn't add the prefix. See https://github.com/illuminate/database/blob/master/Grammar.php#L51

Does nobody else have this problem? Almost seems like I've got some configuration problems...

**Comment by johngray** [comment]
I have a similar issue

**Comment by dshoreman** [comment]
I came across this in google earlier when researching for a prefix-related bug somebody had with Octoshop. Now that's fixed, I've had a bit of time to look into this one.

The reason for the error was count relations not getting the table prefix applied to the column name correctly. I'll post a fix for this over on the [octobercms/library](https://github.com/octobercms/library) repo soon.

**Comment by dshoreman** [comment]
This is now PR'd here: octobercms/library#175
