### ISSUE TITLE
Improve dropdown-fixed styling

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#1335]
With larger drop downs, dropdown-fixed becomes very long and unwieldy. I suggest adding a max-height with scrollbar and a filter field at the top. Here's an example of how a 30 row drop down looks as it stands at the moment (Note that the pic doesn't even even show half the drop down):
![](https://i.imgur.com/TrfU7Ts.png)

**Comment by daftspunk** [comment]
Suggest submitting a PR for this, using overflow: auto and max-height
