### ISSUE TITLE
No error thrown when upload fails

### ISSUE THREAD

**Issue by vojtasvoboda** [octobercms/october#1349]
When I have PHP config `post_max_size = 8M` and try to upload 12MB file, media manager shows green status line with "Upload done" msg, but no file is visible in list:

![snimek obrazovky 2015-08-05 v 11 26 26](https://cloud.githubusercontent.com/assets/374917/9082481/9fe5fd96-3b64-11e5-83c4-5cb1e3cf94b1.png)

POST request returns HTTP 200 code.

**Comment by daftspunk** [comment]
Fixed by #1518
