### ISSUE TITLE
\October\Rain\Database\Traits\Validation ignores database connection

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1354]
In \October\Rain\Database\Traits\Validation the database connection used by a model is totally ignored and it tries to validate on the table via the default connection.

This of course fails/throws sql errors because the table it tries to access doesn't exist on the default table.

**Comment by tschallacka** [comment]
related:
https://github.com/laravel/framework/issues/1262

**Comment by tschallacka** [comment]
chances needed:

line 214: $validator = 

    self::makeValidator($data, $rules, $customMessages, $attributeNames,$this->connection);

Line 80:

    protected static function makeValidator($data, $rules, $customMessages,      

    $attributeNames,$connection = null)
        {
            $validator = Validator::make($data, $rules, $customMessages, $attributeNames);
            if($connection !== null) {
            	$validator->getPresenceVerifier()->setConnection($connection);
            }
            return $validator;
        }

**Comment by ahlechandre** [comment]
+1

**Comment by ahlechandre** [comment]
great

**Comment by ahlechandre** [comment]
@tschallacka will create a pull request?

**Comment by der-On** [comment]
Any chance of getting this fixed?

**Comment by daftspunk** [comment]
This is fixed as of Build 381, please update October to get the changes.

Merged in https://github.com/octobercms/library/commit/bb7037fde174cb590667675836c23dd85a2c56f8
