### ISSUE TITLE
Media manager constant cache refreshing cripples use

### ISSUE THREAD

**Issue by DjGMory** [octobercms/october#1358]
When working with a large number of media, the media manager's constant cache refreshing causes very long load times when uploading, removing, and renaming images, as well as navigating into folders that have a large number of media.

For instance, I am working with 560 images being pulled from a S3/CloudFront. Those live in /media/images. When I first access the media manager (pointed at /media), it loads in an appropriate amount of time. But as soon as you enter that images folder, the load time to refresh the cache winds up hitting between 45-60 seconds.

This becomes very problematic when frequent use of the media manager is required, such as adding many blog posts that each require images.

**Comment by daftspunk** [comment]
User has confirmed that:
- opening a folder with 2-3 images opens quickly
- opening a folder with 500+ opens slowly (~90 seconds)
- reopening a folder with 500+ opens slowly
- all other actions cause the same delay, renaming, moving files, etc.

**Comment by alekseybobkov** [comment]
Please confirm that navigating between folders is slow (takes 45-60 seconds). The folder contents is cached, but the cache has to be refreshed every time users perform any operations with files. That includes uploading files, cropping images, renaming, deleting, moving, copying, etc. Also, the cache invalidates every 10 minutes automatically. You can try to increase the cache TTL with adding the `ttl` parameter to the config/cms.php script, in the storage/media array. The default value is `10` (ten minutes).

    'storage' => [

        'media' => [
            'disk'   => '...',
            'folder' => '...',
            'path'   => '...',
            'ttl' => 60
        ],

    ],

The slow loading could also be caused with the server-side processing of the file list, including preparing the file list markup, and client-side parsing and rendering of the AJAX response, even if a cached data was used. Try to keep the number of files in folders lower to reduce the load.

**Comment by DjGMory** [comment]
Recently moved servers and we're no longer encountering this problem, leading me to believe it was a never an issue with October's caching or anything related to October at all but rather a problem with the server's configuration we were on. Thanks for the attention and sorry the issue was inaccurate.
