### ISSUE TITLE
repeater element vague documented

### ISSUE THREAD

**Issue by JurekRaben** [octobercms/october#1365]
Utilizing the repeater element or a variable with the type "repeater" within a template is not working here. I tried a lot of combinations to use the repeater element in templates.

Could you add a short, working example, how to use the repeater element?

Thanks!

**Comment by daftspunk** [comment]
I assume you mean using the repeater inside the Static Pages plugin? If so, it is not support yet but will be soon. Refer to the https://github.com/rainlab/pages-plugin/issues repo for updates.
