### ISSUE TITLE
Request: Update css-combine also for nested less files / imported less

### ISSUE THREAD

**Issue by JurekRaben** [octobercms/october#1367]
Hi,

I use a parent less file that imports other less files.

If I now change a sub less file, october cms won't recombine / regenerate the generated css, until I also update the parent less file.

So my request is: Add regeneration on updated imports in less files.

**Comment by DanielHitchen** [comment]
https://github.com/octobercms/october/issues/179

**Comment by JurekRaben** [comment]
Thanks... Maybe october could itself look at all less files in the dir, compare timestamp and then renew timestamp of the main less?

;)

**Comment by DanielHitchen** [comment]
Well the [Less PHP library](http://lessphp.gpeasy.com/) that's utilised uses caching anyway, it just needs implementing: http://lessphp.gpeasy.com/#caching

**Comment by daftspunk** [comment]
If anyone can figure this out, by all means, submit a PR.

**Comment by DanielHitchen** [comment]
Hi Sam, I've already implemented this in a plugin I've built via a Twig function, so will send you the code for you to check out & see what you think.

**Comment by DanielHitchen** [comment]
@daftspunk Is there an email I can send you the .ZIP for this? Cheers

**Comment by vizo** [comment]
:+1:

**Comment by prasanthsd** [comment]
Is this going to be fixed sometime soon?

**Comment by daftspunk** [comment]
Doesn't look like it.

**Comment by daftspunk** [comment]
An attempt is being made in https://github.com/octobercms/library/pull/220

**Comment by igneosaur** [comment]
This is still a problem which wasn't solved by #220.

**Comment by LukeTowers** [comment]
@igneosaur That's correct, October asset compiling still only supports listening for changes on one subfile from the main file. If you would like to work on adding that support, please go for it!

The mentioned PR simply added support for SCSS compilation.

**Comment by daftspunk** [comment]
I work around this problem by only including one level of imports in the theme. This discipline ends up producing much cleaner LESS files that are easier to understand and manage.

**Comment by igneosaur** [comment]
Ah I see. I guess because the Demo theme's styles are Less I thought that was October's standard. Good to see Sass support. I guess I'll just use the less command line application to compile and watch files and just move to Sass for my next project.

**Comment by LukeTowers** [comment]
@igneosaur October's standard is LESS files. Always has been. The PR (https://github.com/octobercms/library/pull/220) didn't add support for multilevel change watching, it merely added support for Sass compilation. Hence my earlier comment.

To be perfectly clear, October does support LESS compilation :)
