### ISSUE TITLE
"Error uploading file" modal

### ISSUE THREAD

**Issue by hayatbiralem** [octobercms/october#1369]
This view a little bad. Maybe just "413 Request Entity Too Large" could be fine, and maybe response also available in textarea or code block.

![image](https://cloud.githubusercontent.com/assets/2085468/9228186/04034282-4120-11e5-832b-b1ad7eb0c70b.png)

**Comment by daftspunk** [comment]
This response comes directly from your server we have no control over it other than to display it to you so you have all the details at hand.

**Comment by tiipiik** [comment]
There's a quick fix [here](https://cnedelcu.blogspot.fr/2013/09/nginx-error-413-request-entity-too-large.html)
