### ISSUE TITLE
Fileupload form widget should not blow up smaller images with imageHeight or imageWidth

### ISSUE THREAD

**Issue by lthurston** [octobercms/october#1376]
Currently the fileupload form field configuration allows the specification of a height and width for the image to be displayed in the form at after upload. When displayed, the image is rendered as a thumb with one or both of these values. This works well for setting a maximum width or height which might exceed a viewport, or just to tighten up the form a little bit, but it also blows up small images.

A better solution would be to resize only if it makes the image smaller. If the blown up images are desirable for some reason, then a new set of configuration alternatives for maximum width and maximum height should be added. Alternatively appending an "m" at the end of these pixel values could signify that it's a maximum value.

While this would need to be implemented in Backend\FormWidgets\FileUpload, the actual changes in the logic for rendering should be in the getThumb() or getThumbURL() methods so that this functionality can be used in other places where thumbs are rendered.

**Comment by hybridvision** [comment]
There's also a CSS issue where the `fileupload` images in the backend have a `min-height` and `min-width` set on them and this breaks their responsive nature. 

For example, at a certain point, if an image is very wide (say 600 x 150), the height will become relatively small as the width decreases. If I want the image displayed at 300px wide, the height should be 75px to maintain proportions. However, the `min-height: 100px` CSS rule forces it out of proportion and makes the image look ugly (I have this problem with some logos).

These are the CSS rules responsible: https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/fileupload/assets/less/fileupload.imagesingle.less#L29-L33

According to the comment in the CSS, the `min-width` and `min-height` are necessary but surely there is a better way to handle this without breaking the responsive scaling? Before I saw the comment in the CSS, I would have suggested removing those constraints but I don't know what that will do to the dropzone...

Any thoughts on how to improve this? I know it's not a huge issue but distorted images bother me a lot in the admin!

**Comment by daftspunk** [comment]
This makes sense conceptually. We probably should have a clear use case that needs fixing, or someone can submit a PR that addresses it.
