### ISSUE TITLE
TestCase for plugins using DB

### ISSUE THREAD

**Issue by andriytkachiv** [octobercms/october#1380]
Hi, could you please give a working example of TestCase (phpunit) which loads plugins and use database.
The best option will be if it will work for normal database and SQLite :memory: driver as well.
I found a lot of examples, also tried to use Artisan::call('october:up'), boot all plugins manually, but none of this examples work.

It is very important to make it work, because one couldn't build big project without Unit Tests.

Regards

**Comment by daftspunk** [comment]
Documentation:

https://github.com/octobercms/october/blob/develop/tests/README.md

Example test:

https://github.com/rainlab/translate-plugin/blob/master/tests/models/MessageTest.php

**Comment by andriytkachiv** [comment]
Thank you very much! PluginTestCase was exactly what I needed!

**Comment by SaifurRahmanMohsin** [comment]
I see that the tests run in-memory due to:

```
$app['config']->set('database.default', 'sqlite');
$app['config']->set('database.connections.sqlite', [
    'driver'   => 'sqlite',
    'database' => ':memory:',
    'prefix'   => ''
]);
```

Is there a provision to use other DB like say the production DB? Like is it possible to specify in phpunit.xml or any other way without like directly editing this?

**Comment by daftspunk** [comment]
Tests shouldn't really depend on a live database like this. Although there is nothing stopping you from developing your own class that behaves like this.

**Comment by SaifurRahmanMohsin** [comment]
I was working with REST-based APIs so I wanted to make some Http::get() requests to verify that data has been added properly. But, the tests failed because it all happened in memory. That’s why I asked how to make this work with a production db.
