### ISSUE TITLE
Most of codeeditor's mode-....js files are deleted after october updated from composer.

### ISSUE THREAD

**Issue by ukebako** [octobercms/october#1382]
Most of codeeditor's mode-....js files are deleted after october was updated from composer.

**Comment by daftspunk** [comment]
Which modes do you need?

**Comment by ukebako** [comment]
Well, now I have added yaml and json model manually.

**Comment by ukebako** [comment]
Hi.
Is it possible to add at least mode-json.js to codeeditor?
Or maybe there is some organic way to add needed format files to codeeditor widget?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
