### ISSUE TITLE
After backend form fields are hidden via a trigger, tabs without any visible fields should be hidden too

### ISSUE THREAD

**Issue by lthurston** [octobercms/october#1390]
Currently one can set triggers on fields so that they show / hide based on the values of other fields. This show / hide should -- in a perfect world -- bubble up to the tab level, and tabs with no fields should hide as well. This certainly would add some complexity to the form JS, but would be so magical.

**Comment by daftspunk** [comment]
[We have logic for this already](https://github.com/octobercms/october/blob/master/modules/backend/widgets/form/assets/js/october.form.js#L134-L147) that is applied when `dependsOn` is used, but not for `trigger`, should be pretty simple to implement.

**Comment by lthurston** [comment]
Could dependsOn replace trigger in this particular case? I'm not seeing an example in the documentation that is doing value-based dependent show / hide.

**Comment by daftspunk** [comment]
[This is probably what you're after](http://octobercms.com/docs/backend/forms#filter-form-fields). However, good news: it looks like there is a PR incoming that will resolve the issue for the trigger API!

**Comment by lthurston** [comment]
Woot!

**Comment by daftspunk** [comment]
Fixed by #1401

This will become available in Build 293+
