### ISSUE TITLE
When working with plugins and trying to edit them the input fields show nothing.

### ISSUE THREAD

**Issue by chowraid** [octobercms/october#1392]
When working with plugins and trying to edit them the input fields show nothing making it hard to edit, the only solution that I have found was to refresh the page.

**Comment by daftspunk** [comment]
Can you provide more detail? I am unsure what you mean

**Comment by b0gok** [comment]
Same problem here
![2015-09-10 16-35-34](https://cloud.githubusercontent.com/assets/4283162/9789670/2f1bb7f8-57da-11e5-96b2-120a961d8120.png)

**Comment by CptMeatball** [comment]
+1 Same here. 

Seems to be happening more often with several other plugins. Might be related to #928 . Throwing the error clears entire input.

Workaround:
* Add Component to page
* Save
* Reload
* Edit settings

**Comment by jxngai** [comment]
Seeing the same problem while using RJSlider plugin.

In a page that uses the plugin, things are working fine while clicking the component. I can edit the properties. But after done with editing. Save all the setting. The second time clicking will show all fields with empty values..

The only work around is to refresh the entire backend page.

**Comment by v2pwww** [comment]
We have observed this problem when you turn on the server google pagespeed

**Comment by daftspunk** [comment]
Please confirm what browser you are using and what October build you are using, also provide clear replication instructions.

**Comment by v2pwww** [comment]
I was wrong. This advice to the problem of overlapping tabs and components 

> We have seen this problem when on the server is turned on Google pagespeed

https://github.com/octobercms/october/issues/1428

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by daftspunk** [comment]
Inspector 2.0 has probably fixed this issue. If it still occurs, please resubmit another issue. Make sure some good replication instructions are included too! Thanks
