### ISSUE TITLE
Media Manager deletes parent directory if '..' selected

### ISSUE THREAD

**Issue by andreaslof** [octobercms/october#1393]
If you're in a folder in the Media Manager, and have the parent directory item selected, the whole parent directory gets deleted. Ideally that item should only be a link, and not be deletable.
This can cause users to accidentally delete their whole media library.

**Steps to reproduce**
- Go into the Media manager
- Create a folder
- Go into that folder
- Highlight the parent directory-item
- Click "Delete"

**Expected result**
- Should trigger a warning/prompt to select an item

**Actual result**
- The parent directory gets deleted, and if not careful, the whole library

**Comment by daftspunk** [comment]
The delete button is greyed out and I am unable to click it?

**Comment by andreaslof** [comment]
Might be the build we're running (build 286)?

**Comment by daftspunk** [comment]
Yes, please update to the latest build (290) and try again

**Comment by andreaslof** [comment]
Great – that solved it! Thanks!

**Comment by daftspunk** [comment]
:+1: Good stuff!

**Comment by andreaslof** [comment]
Ok sorry to bring this up again, but after deploying some changes to our server, even on running build 290, the Media Manager has still the old behaviour?

We're deploying the code with Jenkins, and it checks out code via git, and runs `composer install` before sending it off to the server, so each deploy should effectively get the latest build based on what is being pulled from Composer.
