### ISSUE TITLE
Partial components inaccessible in life-cycle functions(onEnd)

### ISSUE THREAD

**Issue by HwapX** [octobercms/october#1394]
With build 290 I can not access components in the 'onEnd' life-cycle function.

Steps to reproduce:
Create an partial _post-list_.
Add **Post List** component from **RainLab\Blog** plugin.
In markup tab render it.

```
{% component 'blogPosts' %}
```

in code tab add the following code.

```
function onEnd() {
    var_dump($this->blogPosts);
}
```

Create an page _blog_ and render the partial.

```
{% partial 'post-list' %}
```

Create some dummy posts and preview the page.

You will see that the component was rendered, but `var_dump` prints `null`

**Comment by Alex360hd** [comment]
Can confirm the issue.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

Also Build 290 is quite out of date, try updating to the latest build.
