### ISSUE TITLE
HTML markup in mail templates

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#1406]
I created the new HTML mail template. I sent it for me, but the email likes as plan text. When I opened the source of mail, I saw this:

`<div id=3D"example">Lorem ipsum</div>`

This is the example code. I used the latest (292) OctoberCMS.

**Comment by gergo85** [comment]
Is it core bug or something else? Please help me, because my client would like to send html emails.

**Comment by dshoreman** [comment]
If you're outputting HTML from a variable, you need to use the `|raw` twig filter as you would in CMS pages. If you're typing HTML in the backend Mail settings, make sure the editor isn't in WYSIWYG mode.

If you've tried that and still have an issue, please post some example template code so we can try to reproduce.

**Comment by gergo85** [comment]
The html layout of my e-mail is:
``<html>
    <head>
        <style type="text/css" media="screen">
            {{ css|raw }}
        </style>
    </head>
    <body>
        <header>
            <img src="https://github.com/octobercms/october/blob/master/themes/demo/assets/images/october.png?raw=true" alt="">
        </header>
        <section>
            <h1>Title</h1>
            {{ content|raw }}
        </section>
        <footer>
            Lorem impus
        </footer>
    </body>
</html>``

I sent the test e-mail to myself. In Thunderbird the source code of e-mail is:
``<html>
    <head>
        <style type=3D"text/css" media=3D"screen">
=
            header {
    text-align: center;
    width: 400px;
}
section {
    padding: 20px;
    width: 400px;
}
footer {
    text-align: left;
    width: 400px;
}
        </style>
    </head>
    <body>
        <header>
      =
      <img src=3D"https://github.com/octobercms/october/blob/master/themes/=
demo/assets/images/october.png?raw=3Dtrue" alt=3D"">
        </header>
=
        <section>
            <h1>Title</h1>
            <p>Lorem ipsum=
 dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidid=
unt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud=
 exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis=
 aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu=
 fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sun=
t in culpa qui officia deserunt mollit anim id est laborum.</p>
        <=
/section>
        <footer>
            Lorem impus
        </footer>=

    </body>
</html>``

**Comment by dshoreman** [comment]
For reference, this issue is also posted here:
http://octobercms.com/forum/post/mail-templates-bug
