### ISSUE TITLE
Relation Manager with pivot data and validation in pivot model.

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#1407]
I used pivot model and added validation trait into it. I added some validation rules. 

I opened relation manager popup with pivot data. Filled form data and submit it. I received validation error, but popup was closed and there is no way to correct form errors.

That bug occurs only when using pivot model with relation manager.

Popup should reopen if there were any validation errors.

**Comment by daftspunk** [comment]
Fixed by #1408
