### ISSUE TITLE
Problem with duplicate entry during add a element in relation

### ISSUE THREAD

**Issue by jbartoszek** [octobercms/october#1411]
Hi everybody,
I noticed a problem when i try add a item in relation belongsToMany.
https://www.dropbox.com/s/ktil2jwwjqnnqkv/Screenshot%202015-08-31%2012.09.31.png?dl=0

This problem occurs when We add several times the same item to other.
For example:
We have a two elements Main A & B & C and two subelement  d.  I adds element of d to A save relation and goes to edit element of B and adds element of d, in this moment "October" adds to my relation 2  elements of d. After save the entry, exit and return to form all is okey i have only one element. 
In next element of C after this same action, i have 3 elements of d after save all is okey.
I think this is a problem with deffered elements.

Why?

Best regards
Jacek Bartoszek
P.S Sorry for my English ;)

**Comment by bombozama** [comment]
Same problem here... I'll try to do as the docs say and report it:

**Bug summary:**
On model creation, after creating a deferred binding, the relation appears many times. After saving the parent model, the relation appears ok.

![screen shot 2015-09-01 at 22 16 55](https://cloud.githubusercontent.com/assets/1273093/9620975/54857ed2-50f7-11e5-85de-2995707146f8.png)

**Reproduce steps:**
1. Enter the create model form. Add new deferred binding. Save model.
2. Enter the create model form again for a new model. Add new deferred binding (same as last one).

If step 2 is repeated, the deferred binding appears more times on the list.

**Expected result:**
The deferred binding field should show only one instance per model.

**Comment by CptMeatball** [comment]
Issue still exists.

**Comment by IcedLime** [comment]
Issue still exists for me too.

**Comment by chesterx** [comment]
issue still exists

**Comment by filipac** [comment]
have this issue too!

**Comment by GvErikk** [comment]
I have this issue too! anyone a workaround?
