### ISSUE TITLE
Installing plugins with dependencies

### ISSUE THREAD

**Issue by dogiedog** [octobercms/october#1414]
Hello,

I'm trying to install a plugin with dependencies, when installing the Blog Tags Extension (or the RainLab Blog Video Extension) it doens't install the Blog plugin while the plugins have dependencies on RainLab.Blog (in the plugin.php it has the public $require = ['RainLab.Blog'];).

What is going wrong in this case?

**Comment by vojtasvoboda** [comment]
+1 Same problem here

**Comment by dshoreman** [comment]
As @vojtasvoboda mentioned, this is still being worked on in #36. In the mean time, install dependencies first and any dependant plugins will work fine.

You may need to re-enable plugins if they once had dependencies that weren't installed, worth checking the backend updates page just in case.
