### ISSUE TITLE
Idea! Private installing plugins through the panel

### ISSUE THREAD

**Issue by prhost** [octobercms/october#1415]
Idea! What do you think of the idea you can install private plugins through the same panel acotence with Store plugins? I do not know if this goes against the concept that Octobercms works. Give your suggestions.

**Comment by alvaro-canepa** [comment]
I'm working in a plugin that make this. Actually tested only with Bitbucked and is in development version. I hope to end soon and publish them to the marketplace. It was a free plugin ;)

**Comment by seanthepottingshed** [comment]
This is exactly what I'm looking for. Any progress?

**Comment by prhost** [comment]
I'm currently using the composer himself with the installer https://github.com/composer/installers there is a type for october

**Comment by alvaro-canepa** [comment]
@prhost Very good option. But require a shell access, and some time is not possible to have it.

@seanthepottingshed  Right now, I don't have time to continue developing the installer plugin for october. But i will resume it soon on next year.

**Comment by Alex360hd** [comment]
@alvaro-canepa any update on this ? If you don't have time to work on it, do you think you could release what you have already to let others people continue your work ?

**Comment by daftspunk** [comment]
This could be handled by a simple git manager. A plugin that provides a UI for cloning git repos, pulling git repos, etc. There are plenty of great git libraries for PHP out there.

**Comment by Alex360hd** [comment]
@daftspunk Hi, thank your for your answer.

Do you have an example in mind ?

I'm looking for something as simple as october cms default plugin install. I go to the october backend, I go to plugins > private page, I type the name of one of my private plugin and it automatically download the package from my repositories, install the database stuff (if any) etc.... 

And it should be compatible with most git plateform as I'm not using github but bitbucket

**Comment by alvaro-canepa** [comment]
@Alex360hd sorry, I have no time right now. This project are paused. If you want, I can send the plugin code, but is not too much... and is made for a very old version of OC. 
I think, the best solution is to write a new one from zero, and like say @daftspunk, using some free library to do that!

**Comment by Alex360hd** [comment]
Ok thanks, I will try to investigate this. But I'm new to laravel, october and github, so I think it will be challenging ! ^^

**Comment by alvaro-canepa** [comment]
@Alex360hd In my plugin I only check for the version.yaml and compare with the installed. The work I have is very basic. And I use bitbucket too. (more private repos than github with a free account) ;)

Best regards

**Comment by alvaro-canepa** [comment]
## I glad to inform about the new plugin, for install private plugins, is coming to Marketplace. 
 
The plugins must be in Bitbucket or Github. The installation process check for missing dependencies, try to find it in marketplace, and if found, recommend to normal installation.

The Bitbucket process are ready. Now i need work on Github.
I need more work for autorun composer if `composer.json` is detected.

### Some pics:
**Plugin detected in Marketplace**
![image](https://user-images.githubusercontent.com/5142298/34256264-380b0370-e633-11e7-8dc2-59ca871e903a.png)

**Plugin with dependencies**
![image](https://user-images.githubusercontent.com/5142298/34256348-976aecfe-e633-11e7-949b-f745f1d88496.png)

**Plugin with missing dependencies**
![image](https://user-images.githubusercontent.com/5142298/34256371-b3633bbe-e633-11e7-9039-ac42599cd614.png)

More work is coming...

**Comment by Alex360hd** [comment]
Good! I don't see it on the marketplace yet, hope to see it validated very soon !

**Comment by prhost** [comment]
@alvaro-canepa sooner than ever hehe, I hope to see this plugin soon in the marketplace. Congratulations

**Comment by LukeTowers** [comment]
@alvaro-canepa if you're running the composer requirements, make sure you trigger the run in the project root, not the plugin dir.

**Comment by alvaro-canepa** [comment]
@LukeTowers, but the `composer.json` must be in plugin root folder. If i run `composer install` in project root, give error if OC was installed without composer (using web installer).
I use `Symfony Process` to run composer commands.

@prhost jeje, no, now I focus on this plugin, because I needed too ;)

**Comment by LukeTowers** [comment]
@alvaro-canepa True. Perhaps just add detection for the October instance using composer (composer.json present in project root) and call it in the correct location accordingly. One other thing that you'll have to consider with composer support if you're calling it in the plugin directory (this gets done on the marketplace as well) is to utilize the `replace` property of composer.json to prevent composer from loading dependencies in the plugin that the project already has, and worse than that, other versions of dependencies that are already loaded by October.

**Comment by alvaro-canepa** [comment]
@LukeTowers Is there any way to run `composer install/update` from root project but without affecting the main `/vendor` folder? Something like `composer install "plugins/author/name/"`

**Comment by alvaro-canepa** [comment]
The first plugin with composer has been installed fine. I use the @LukeTowers code on #2831 .
I use the [@norotaro](https://github.com/octobercms/october/issues/2831#issuecomment-299879815) list. But removing `composer-plugin-api`, that made "Not installed package" error.

Now, go to github API devel and test.

**Comment by LukeTowers** [comment]
@alvaro-canepa that list is outdated since the update to 5.5, you're best of generating your own or just using only the `illuminate/*: 5.5.*` packages.

**Comment by alvaro-canepa** [comment]
@LukeTowers you right, thanks

**Comment by alvaro-canepa** [comment]
Hi all, for a christmas present, I have a testing version of my plugin. Named **Private Plugins**. I need someone with private github repos to test. I use Bitbucket and free Github account.
it was to be published as pay plugin in marketplace. And of course, is in private repo, so if someone has interest in testing, tell me how send the zip repo plugin.

Thanks and MERRY CHRISTMAS !!!

**Comment by LukeTowers** [comment]
@alvaro-canepa Octobercms@luketowers.ca

**Comment by alvaro-canepa** [comment]
Hi @LukeTowers I send the link to download the zip plugin. For private repos, use **Token** auth in GitHub and **OAuth2** auth for Bitbucket. I forget to remove the others authorization methods from settings. 

Thanks

**Comment by alvaro-canepa** [comment]
Sorry people, but my plugin has been rejected, because "conflict" with Pond. 

![image](https://user-images.githubusercontent.com/5142298/34406754-6b90c5fc-eb99-11e7-9ea0-d6a941ec5d83.png)

I love OctoberCMS, but I disagree with that. How I see, my plugin was rejected because Pond is a paid service to deploy private plugins. My plugin do that with less money, only $15 for unique payment.

So, if someone needed, know where findme. ;)
The plugin is in [Bitbuket](https://bitbucket.org/planetadeleste/oc-private-plugins)

Thanks and happy holidays !!!

**Comment by Zmove** [comment]
Hmm yes, also disagree, in addition, pond is not available yet. In addition, this plugin just allow to install some private plugins whereas pond will provide a whole development ecosystem.

Don't understand why the october team doesn't validate this plugin and, at the same time, validated at least 4 plugins that create the same contact form on the frontend.

PS : Your plugin in bitbucket is not available, I can just access to the issues page

**Comment by alvaro-canepa** [comment]
Thanks @Zmove for your comment. The repo is public now. Be free to use it ;)
Remember to uncompress into `planetadeleste/privateplugins` folders (inside `/plugins`).

Happy 2018 !!!

**Comment by prhost** [comment]
@alvaro-canepa is a shame, unfortunately octobercms will give preference to them. Why not put it in github?

**Comment by alvaro-canepa** [comment]
@prhost I use Bitbucket because has free private repos. And, at first, this plugin was be a paid plugin. Now I release the repo to be used by anybody ;)

https://bitbucket.org/planetadeleste/oc-private-plugins/overview

Also have a slack channel on [#oc_private_plugins](https://planetadeleste.slack.com/messages/C8LPN7T7G)
