### ISSUE TITLE
Pls Give Instructions on How to Install on Openshift

### ISSUE THREAD

**Issue by rt7651** [octobercms/october#1420]
Pls Give Step by Step Installation Instructions on october cms on openshift or cpanel hosting

**Comment by felixinx** [comment]
On OpenShift : [Check the forum post](https://octobercms.com/forum/post/support-for-openshift-cloud-hosting)
On regular hosting, it **may not work** since it's use command line.

In any way, use the [octobercms/install](https://github.com/octobercms/install)

**Comment by rt7651** [comment]
@felixinx the link is not useful for now , since it has no information on how to install..on openshift or cpanel hosting

**Comment by felixinx** [comment]
On cPanel, download the installer and upload it with FTP, open `install.php` in your browser, and follow the instuction.

On openshift,

- Add an application,
- Create a PHP 5.4 application,
- In the source code, put `https://github.com/octobercms/install.git` as the clone URL and the branch `master`.

**Comment by rt7651** [comment]
Here is a clear instructions from your tip.. https://medium.com/@rt7651/installing-october-cms-on-openshift-f08d6f1acfa8

**Comment by felixinx** [comment]
No problem! Don't forget to mark as closed.
