### ISSUE TITLE
Class 'RainLab\Pages\Classes\Theme' not found 

### ISSUE THREAD

**Issue by FelixINX** [octobercms/october#1421]
Hi,

I am getting this error when accessing front-end:

`Class 'RainLab\Pages\Classes\Theme' not found`

in `H:\www\october\plugins\rainlab\pages\classes\Controller.php line 30`

Twig Template : `Symfony\Component\Debug\Exception\FatalErrorException`

with code:
```php
  

    /**

     * Initialize this singleton.

     */

    protected function init()

    {

        $this->theme = Theme::getActiveTheme();

        if (!$this->theme) {

            throw new CmsException(Lang::get('cms::lang.theme.active.not_found'));

        }

    }

  

    /**
```

Thanks.

**Comment by felixinx** [comment]
Console returns a 500 error,

**Comment by dme3us** [comment]
To the top of your file see if this is present:
```php
use Cms\Classes\Theme;
```

**Comment by felixinx** [comment]
Yes it is https://github.com/rainlab/pages-plugin/blob/master/classes/Controller.php#L5

**Comment by vojtasvoboda** [comment]
Try to update system and Pages plugin at first (and try Force update).

**Comment by dshoreman** [comment]
Please contact the author using the support tab on the plugin page.
