### ISSUE TITLE
Error messages of FileUpload are not translatable

### ISSUE THREAD

**Issue by c-barre** [octobercms/october#1427]
Hi,
It's possible to make the error messages of FormWidget ( like FileUpload ) translatable ?

eg of messages : 
- confirm alert to remove
- button "Remove"
- Upload error : "You can't upload files of this type."
  - ![capture](https://cloud.githubusercontent.com/assets/6083617/9712389/966d6aba-554a-11e5-8329-136cbb3a495b.PNG)
- ...

Why don't you use "Lang::get()" on partials and the javascript object "Dropzone.prototype.defaultOptions" on dropzone.js ?

**Comment by gergo85** [comment]
+1

**Comment by felixinx** [comment]
This is pretty easy to implent. I will try working on it.

**Comment by vojtasvoboda** [comment]
Check http://www.dropzonejs.com/#config-dictDefaultMessage

**Comment by IcedLime** [comment]
Hi, Thank's vojtasvoboda. I think it's a good answer. I try it latter

**Comment by daftspunk** [comment]
Is this still an issue? A Pull Request would be nice!

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
