### ISSUE TITLE
Duplicate tabs with pages in CMS

### ISSUE THREAD

**Issue by b0gok** [octobercms/october#1428]
When working with CMS and trying to open page from Pages it open two identical tabs. In console, you can see that two of the same query is executed.
![2015-09-10 16-45-05](https://cloud.githubusercontent.com/assets/4283162/9790002/0a13cbce-57dc-11e5-82ee-59da1ce86c47.png)

**Comment by dshoreman** [comment]
This could be a duplicate of #1391, please provide more detail so we can reproduce it. Are you on latest build? When did you start experiencing the issue? Anything you think might be useful.

**Comment by b0gok** [comment]
I'am on 289 build. It happens periodically. I did not find any patterns.

**Comment by daftspunk** [comment]
I can replicate this by double clicking real fast on an item. Perhaps
that's what is happening?

**Comment by keiosweb** [comment]
@daftspunk replicated on older builds too

**Comment by b0gok** [comment]
@daftspunk unfortunately, it isn't the case

**Comment by daftspunk** [comment]
Unable to replicate this, sorry.

**Comment by JosBouma** [comment]
I came across this problem as well. After disabling mod_pagespeed for the backend the problem went away.
