### ISSUE TITLE
asset minification 

### ISSUE THREAD

**Issue by jamiegrand** [octobercms/october#1430]
something strange happening with asset minification , I have a large site and when I spider the site using Screaming frog web Seo spider, it eventually cause a serialization error after which all pages spidered gets the same error. clearing cache reverts the site back to normal. setting asset minification to false prevents this from happening. which I have done. this could be a big issue if happening with other sites as you could potentially take them offline.

**Comment by daftspunk** [comment]
I tried [raising this issue with Laravel](https://github.com/laravel/framework/pull/3382) but it would appear they want the exception to occur. This may also be related to #1250.

**Comment by shina** [comment]
Yes, it seems to be the same issue. I'm adding more info on the issue.

**Comment by daftspunk** [comment]
Related to #1422
Related to #1250

Making #1250 master
