### ISSUE TITLE
Add support for conditional components using `@component`

### ISSUE THREAD

**Issue by nsrosenqvist** [octobercms/october#1431]
Now you can only specify what plugins your theme depends on. It doesn't make sense for theme authors to bake in support for every popular plugin if it pulls in all those dependencies as well. However, a theme might have support for it but not require it. This would need a mechanism for themes to check if a plugin is activated and then include code.

This would also be a huge benefit to the theme marketplace since the users can search for themes that supports RainLab.Blog, for example.

**Comment by daftspunk** [comment]
If a theme supports a plugin, but does not require it, it should not include that plugin in the require definition. However, the front end page will crash if a component is used that doesn't exist (this is desirable). So we need to add "soft" component implementation definitions like this

```
[@someComponent]
willNot = "fail if missing"

[\Full\Path\To\Component @softFail]
==
{% if someComponent %}
    <p>The plugin with someComponent is installed!</p>
{% else %}
    <p>Do something else...</p>
{% endif %}
```

The above code instructions are simple: prefix the component alias with an `@` symbol and it will not cause the page to crash if the component is not found. This will allow themes to have optional support for plugin functionality.

**Comment by scazzy** [comment]
@daftspunk I tried escape using the `@` while importing a component, but it didn't work. the page would throw
`An exception has been thrown during the rendering of a template ("Class name is not registered for the component "@SeoCmsPage". Check the component plugin.").
`

**Comment by LukeTowers** [comment]
@scazzy @daftspunk was describing how it should work, not how it does work unfortunately. That feature hasn't been implemented yet.

**Comment by viamage** [comment]
Let me know what do you think about this approach:
https://github.com/viamage/october/pull/1/files

Works properly
http://uploads.keios.eu/video/october-softcomponents.html

but we could go deeper into makeComponent and soft-check only there, or maybe don't go with catch at all and do it differently?

**Comment by LukeTowers** [comment]
@viamage could you make the PR to this repo so we can review it in a PR here instead?

**Comment by viamage** [comment]
Sure, made at https://github.com/octobercms/october/pull/3577

**Comment by bennothommo** [comment]
Implemented by https://github.com/octobercms/october/pull/4539.

**Comment by trollkotze** [comment]
This "soft dependency" functionality seems to be broken by October 2.0.

**Comment by daftspunk** [comment]
Hey @trollkotze,

Thanks for your message. Yes, unfortunately, the implementation here is not quite right and was not carried over to v2. Could you kindly email us at hello@octobercms.com to discuss your requirements to use this feature?

Best regards
