### ISSUE TITLE
BelongsToMany to BelongsToMany via table with deferred bindings chunk iteration fails if primary key is named id

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1432]
Basically what the title says:

When you have a belongstomany to a belongs to many

hotelroom

    public $belongsToMany = ['pricerules' =>
    							['ExitControl\PriceManager\Models\PriceRule',
    								'table'=>'hotel_room_to_pricerule',
    								'key' => 'hotel_room_id',
    							    'otherKey' => 'pricerule_id'
    							],
    ];

pricerule

    public $belongsToMany = ['hotelrooms' =>
    							['ExitControl\HotelManager\Models\HotelRoom',
    								'table'=>'hotel_room_to_pricerule',
    								'otherKey' => 'hotel_room_id',
    							    'key' => 'pricerule_id'
    							],
    		
    ];

With deferred bindings

     $this->vars['value'] = $this->getRelationObject()
    								->withDeferred($this->sessionKey)
    								->orderBy('created_at','desc');

and you do chunk iteration

    $value->chunk(25,function($values) use($saturation, $count,$indexrules, $rules) {
          foreach($values as $val) {
          .....
          }
     });

and if the $primaryKey is named **id** in your table, you'll run into an erro that there is a duplicate entry of the field **id** in the temp table.

    exception 'PDOException' with message 'SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]The column 'id' was specified multiple times for 'temp_table'.

and this is the query it generates

    SELECT * 
    FROM   ( 
                 SELECT    *, 
                           Row_number() OVER (ORDER BY [created_at] DESC) AS row_num 
                 FROM      [price_rules] 
                 LEFT JOIN [hotel_room_to_pricerule] 
                 ON        [price_rules].[id] = [hotel_room_to_pricerule].[pricerule_id] 
                 WHERE     ( 
                                     [hotel_room_to_pricerule].[hotel_room_id] = 2 
                           OR        EXISTS 
                                     ( 
                                            SELECT * 
                                            FROM   [deferred_bindings] 
                                            WHERE  slave_id = price_rules.id 
                                            AND    [master_field] = pricerules 
                                            AND    [master_type] = exitcontrol\hotelmanager\models\hotelroom
                                            AND    [session_key] = tpyqf1z92winmzhxuoz31np2bu1mafq0nlxapvaz
                                            AND    [is_bind] = 1)) 
                 AND       NOT EXISTS 
                           ( 
                                  SELECT * 
                                  FROM   [deferred_bindings] 
                                  WHERE  slave_id = price_rules.id 
                                  AND    [master_field] = pricerules 
                                  AND    [master_type] = exitcontrol\hotelmanager\models\hotelroom
                                  AND    [session_key] = tpyqf1z92winmzhxuoz31np2bu1mafq0nlxapvaz
                                  AND    [is_bind] = 0 
                                  AND    id > isnull( 
                                         ( 
                                                SELECT max(id) 
                                                from   deferred_bindings 
                                                WHERE  slave_id = price_rules.id 
                                                AND    master_field = pricerules 
                                                AND    master_type = exitcontrol\hotelmanager\models\hotelroom
                                                AND    session_key = tpyqf1z92winmzhxuoz31np2bu1mafq0nlxapvaz
                                                AND    is_bind = 1 ), 0))) AS temp_table 
    WHERE  row_num BETWEEN 26 AND    50

As you can see it uses id too for the deferred bindings and the [price_rules].[id]

I managed to solve this by rebranding the primaryKey to rule_id in the database, but i'd prefer it if somehow this duplicate id entry could be resolved ;-)

Or else leave this out there or mentioned in the documentation clearly that this niche case where you use AND deferred binding AND chunk iteration can cause issues if your primary keys are named id instead of a unique name among the set of joins.

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by daftspunk** [comment]
Also, just check to make sure this hasn't been fixed already. Sorry for the delay in replying.
