### ISSUE TITLE
Update FontAwesome

### ISSUE THREAD

**Issue by montogeek** [octobercms/october#1434]
Hi!

It is fine to update the FA version?

I can make a PR :)

**Comment by SaifurRahmanMohsin** [comment]
OctoberCMS uses [FontAutumn](http://daftspunk.github.io/Font-Autumn/) so I think that project should update itself to the current version of FA.

**Comment by daftspunk** [comment]
It's already using the latest, FontAutumn has been deprecated in favor of [Storm UI "icon"](http://octobercms.com/docs/ui/icon), this will be released soon.

**Comment by montogeek** [comment]
@daftspunk Does Storm UI Icon support icon sizes?

**Comment by daftspunk** [comment]
Can you give me an example of the code?

**Comment by montogeek** [comment]
I just need to change the icon size, just like in FA `icon-4x`.

**Comment by daftspunk** [comment]
Added in 6db2018f288a2fd7c4736c5004de809608539f95

**Comment by montogeek** [comment]
Thanks @daftspunk <3
