### ISSUE TITLE
Bug: Media manager and uppercase .JPG files

### ISSUE THREAD

**Issue by nickmealey** [octobercms/october#1436]
If you upload an image within the media manager with an uppercase .JPG extension, things break and the image isn't viewable. It seems like it's treating it as a document not an image. If I rename (the same file) the file extension with a lowercase: ".jpg" it works fine.

**Comment by b0gok** [comment]
I made a pull request:
https://github.com/octobercms/october/pull/1437

**Comment by daftspunk** [comment]
Fixed by #1437
