### ISSUE TITLE
Wrong pending badge color in author dash

### ISSUE THREAD

**Issue by vojtasvoboda** [octobercms/october#1439]
When I have plugin in pending status, it should have yellow badge not gree - `pending` class is missing:

Left screen: actual code
Right screen: manually added pending class by Chrome code inspector

![pending](https://cloud.githubusercontent.com/assets/374917/9955067/42472b04-5dee-11e5-9ebf-9622fb317408.png)

**Comment by daftspunk** [comment]
Thanks for reporting this, it should be fixed in the next website version.
