### ISSUE TITLE
\ not allowed in CMS page URL regex

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#1441]
In the [URL Syntax docs](http://octobercms.com/docs/cms/pages#url-syntax) you have `/blog/:post_name?|^[a-z0-9\-]+$` however if you actually try to save a page with this URL you'll get the error

> Invalid URL format. The URL should start with the forward slash symbol and can contain digits, Latin letters and the following symbols: ._-[]:?|\/+*^$

Remove the \ from the regex section of the URL above and the page saves successfully. This bug is possibly related to https://github.com/octobercms/october/issues/614

**Comment by daftspunk** [comment]
Fixed by #1446
