### ISSUE TITLE
Installing in subfolder /public_html/cms

### ISSUE THREAD

**Issue by cheles** [octobercms/october#1447]
I have a laravel app in root (public_html). Can I install OctoberCMS in a sub-folder like cms? And if yes, what do I need to edit in the laravel clean instance to not mix the route (when I'll try to access site.com/cms to not search for a Route?

Thanks

**Comment by mplodowski** [comment]
Hi,

I think better solution will be to create a subdomain e.g. http://cms.site.com

That way you have seperate OctoberCMS installation and Laravel app installation.

Second solution will be to use .htaccess file in public_html folder and add rule to skip cms folder.

**Comment by tawaffan** [comment]
You can add .htaccess file in public_html folder.

```
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteCond %{REQUEST_URI} !^cms
    RewriteRule ^(.*)$ cms/$1 [L]
</IfModule>
```
