### ISSUE TITLE
Error on create form widget.

### ISSUE THREAD

**Issue by valiknet18** [octobercms/october#1449]
Hello, i want to create own form widget,
but when i create it in own plugin, and include him in model "fields.yaml" file.
i get error 
![image](https://cloud.githubusercontent.com/assets/5772019/10019557/e5bea1f8-6146-11e5-8753-3e852ffee16c.png)

Please, help me resolve this problem :)

**Comment by FelixINX** [comment]
Does the partial exsists?

**Comment by valiknet18** [comment]
Yes, but his path ~/plugin/vendor/namePlugin/formwidget, 
and his declared in Plugin file, but October not find his...
I am resolve this problem, i add form declare in modules/backend/ServiceProvider.php, but this solution not like me

**Comment by FelixINX** [comment]
Where does the file is decleared, and how?
Because you can't really modify the system files...

**Comment by valiknet18** [comment]
I am declare this method in Plugin file (Plugin root dir (Vendor\PluginName))

```php
public function registerFormWidgets()
    {
        return [
            'Vendor\PluginName\FormWidgets\Snippet' => [
                'label' => 'Snipet form',
                'code'  => 'snippetform'
            ]
        ];
    }
```

**Comment by FelixINX** [comment]
You're form widget is not correctlt decleared. Please use the following:
```php
public function registerFormWidgets()
{
    return [
        'Backend\FormWidgets\CodeEditor' => [
            'label' => 'Code editor',
            'code'  => 'codeeditor'
        ]
    ];
}
```
It should be `Backend\FormWidgets\Snippet` in your case.

**Comment by mplodowski** [comment]
His namespace for formwidget inside his plugin (Vendor\PluginName) seems correct:

    Vendor\PluginName\FormWidgets\Snippet

Just replace Vendor and PluginName with plugin details.

@valiknet18 I recommend you to use october artisan command for creating new form widgets.

Just type in console, in project root:

    php artisan create:formwidget Vendor.PluginName SnippetForm

Now just register this form widget in your Plugin.php file like you did and you are good to go.

Fields.yaml:

    mysnippetform:
        type: snippetform

**Comment by valiknet18** [comment]
@mplodowski thx for help ;)
