### ISSUE TITLE
https pagination problem

### ISSUE THREAD

**Issue by lzodevelopment** [octobercms/october#1459]
the url are afterwards with http
when you try to go to second page

**Comment by tawaffan** [comment]
How do you render pagination?

I use this way :

```
{{ posts.render|raw }}
```

and the url like this 

```
http://mydomain.ltd/posts/?page=2
```

**Comment by KB1RMA** [comment]
I'm also running into this same issue.

Code like:

```html
<li><a href="{{ portfolioItems.items.nextPageUrl|raw }}" rel="next">»</a></li>
```
returns an HTTP URL regardless of what app.linkPolicy is set to. Or whether the site is being accessed via https/http.

For shits and giggles I also tried running it through the `|app` filter, but it doesn't take care of the issue unfortunately.

This appears to be the method at fault in Laravel: https://github.com/laravel/framework/blob/5.0/src/Illuminate/Pagination/AbstractPaginator.php#L114-L131

**Comment by daftspunk** [comment]
[Here's a workaround](https://github.com/rainlab/forum-plugin/blob/master/components/partials/pagination-list.htm) you can use in the meantime.
