### ISSUE TITLE
Richeditor content jumps when hitting top of scrolled window

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#1463]
Here's a demonstration of what I'm talking about https://dl.dropboxusercontent.com/u/7629436/richeditor-jump.mov

Notice when the richeditor hits the top of my window as I'm scrolling down, the content inside it is lost. It seems when you `position:absolute` the top, you need to add `margin-top` of the same height to stop the jump.

**Comment by daftspunk** [comment]
I think this is actually a feature of Redactor that we can disable? Not sure.

**Comment by daftspunk** [comment]
This should be sorted in Build 305+
