### ISSUE TITLE
Test connection to the installation server (Faild)

### ISSUE THREAD

**Issue by mohamed3a6ala** [octobercms/october#1471]
I have this issue in installation wizard (Test connection to the installation server)

Any Suggestions ?

**Comment by daftspunk** [comment]
Make sure that your server can make outgoing connections on port 80, specifically to `octobercms.com`.

**Comment by Simplesmente** [comment]
I'm having identic problem, I already used the server embedded of the php and server apache2, but nothing solved. Someone can help me ?

**Comment by AasemElrayes** [comment]
I solved the problem by changing port check in "\install_files\js\vendor.js" from "80" to "your port" .

**Comment by Hein-Thu-Ya** [comment]
how to solve Test connection to the installation server on October CMS. Please!

**Comment by AasemElrayes** [comment]
If you use something like xxamp and changed port from 80 to 8082 , you have to chang port in "\install_files\js\vendor.js" from 80 to 8082 , it works fine after editing files @Hein-Thu-Ya

**Comment by Hein-Thu-Ya** [comment]
Thank You Bro! I Got it
