### ISSUE TITLE
Download Doc file by uploader problem

### ISSUE THREAD

**Issue by jbartoszek** [octobercms/october#1472]
Hi All!
I have a problem with download doc/docx uploaded in backend form by "fileupload".
File in storage folder is correct. When i try download this file by link on frontend or "Attachment URL" in bakend I recevies a blank page and I can`t download this file(page is loading very long time). 
End result is failed in "Network Tab - Developer Tools".

https://www.dropbox.com/s/dcgtr7bax99e8i2/Zrzut%20ekranu%202015-09-28%2011.43.44.png?dl=0

Team, please check this out
Thanks Jacek

**Comment by daftspunk** [comment]
This sounds like an issue with your webserver refusing to deliver the .doc file. Since the failing request is directed to a .DOC file and not a .PHP script, it's possible this is unrelated to October.
