### ISSUE TITLE
Class 'IntlDateFormatter' not found in Media manager

### ISSUE THREAD

**Issue by alvaro-canepa** [octobercms/october#1476]
After update to build 299, when I try to upload or view images in the media manager, get the error `Class 'IntlDateFormatter' not found`
Here is a capture:
![Capture](https://box.everhelper.me/attachment/297202/r7lzpnvLFnkALhTZaxr2E4PptDrX4Yrf/397815-uHPycKEPOeZQgNVO/screen.png)

Tested in fresh installed OctoberCMS.

**Comment by daftspunk** [comment]
Fixed by 2ecf2db311bd462993c6db2481a02cba04a15359

**Comment by alvaro-canepa** [comment]
Woow, too fast!!!
Thanks. 
Other problem here is in my php settings. I don't have the Intl extension installed.

    sudo apt-get install php5-intl
    sudo service apache2 restart

But the use of Carbon is better ;)
