### ISSUE TITLE
shown.oc.popup gets fired twice in the backend

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1481]
I have the following code

```
(function() {
    var infoelem = $('<div class="icon-info-circle readallcomments-icon"  data-control="popup" data-size="huge" data-request-data="date:something" data-handler="formPricerules::onAllComments" data-keyboard="true" href="#">');
    infoelem.on("click",function(e){
        if(!e.isPropagationStopped()) {
            e.stopPropagation();
            var once = true;
            infoelem.on('shown.oc.popup',function(e){if(!once)return;once=false;console.log('here')});
            infoelem.popup();


        }
    });
    commentelem.append(infoelem);
})();
```

I only had one problem with this code, and that's that the event shown.oc.popup gets fired **twice** for every modal that gets opened in the backend.

I traced it down to october-min.js on line 2526

```
this.$modal.on('shown.bs.modal',function(){self.triggerEvent('shown.oc.popup')})
```

and popup.js on line 71-73

```
this.$modal.on('shown.bs.modal', function(){
        self.triggerEvent('shown.oc.popup')
    })
```

I had to hack in the scoped variable check to test if it's the second round triggering it, but it's far from ideal. 

Maybe add in a check that the event will fire only once? or name it differently? or strip one of the fired events.

**Comment by LukeTowers** [comment]
@tschallacka is this still an issue in the latest build?

**Comment by tschallacka** [comment]
Will check and test

**Comment by LukeTowers** [comment]
Awesome, thanks @tschallacka!
