### ISSUE TITLE
Hide tab close buttons on inactive tabs in CMS

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#1483]
It's very easy to accidentally click the 'Close' icon on inactive tabs when trying to switch to them in CMS by accident. And because they're not actual browser tabs, it's impossible to 'open last closed tab' which can result in confusion for the user who may not know which tab they just closed by accident.

I propose removing the close icon from inactive tabs and only having it visible for the active one. Below is a before and after mockup - I'm sure the padding could be messed with a bit to make things look prettier but it's a decent enough showcase of what I'm talking about:

Before:
![screen shot 2015-10-02 at 7 26 52 am](https://cloud.githubusercontent.com/assets/334808/10234398/a72b07c2-68d7-11e5-95c9-51e9438e9621.png)
After:
![screen shot 2015-10-02 at 7 29 01 am](https://cloud.githubusercontent.com/assets/334808/10234399/a72c7aa8-68d7-11e5-9538-8e3cc2de3c48.png)

Both Chrome and Firefox do this same thing when tabs get small enough. Our tabs are far smaller than browser tabs so I feel this feature would be a pretty good improvement.

**Comment by daftspunk** [comment]
These icons have been made bigger in stable. No one else has reported this UX issue. Should be OK now.
