### ISSUE TITLE
Managing jsonable fields in relation.

### ISSUE THREAD

**Issue by gpasztor87** [octobercms/october#1484]
Hi! I want to managing a jsonable field in relationmanager. I tryed using the datatable formwidget, but it's not working.

**Comment by daftspunk** [comment]
Relation manager is for managing model relations. The `repeater` form field will return an array and can be used with jsonable.

**Comment by gpasztor87** [comment]
Hi!
I drafted wrong, sorry. 
I have a jsonable field in the related model(I don't want to managing the relation), and I wanted to manage it with the datatable widget:


![screen](https://cloud.githubusercontent.com/assets/3843377/10411975/e95d59d2-6f77-11e5-90e8-8be38a437070.png)

But it doesn't work. I will try it with repeater then.

**Comment by ghostix** [comment]
I have similiar problem with datatable for relation model. After Saving is stored empty Json :/ .. the field with type datatable is not in the request params
