### ISSUE TITLE
I can't update online

### ISSUE THREAD

**Issue by yozman** [octobercms/october#1485]
http://octobercms.wx.jaeapp.com/backend/system/updates
admin/admin

this is my demo site,
I can't update it,
could u help me?

**Comment by gergo85** [comment]
Try to increase the php timeout (http://php.net/manual/en/function.set-time-limit.php).

**Comment by daftspunk** [comment]
Yes it would appear your server has a very short timeout limit for each request. It looks like it is set to about 30 seconds, you can try updating via the command line or contacting your hosting provider to see how to have the limited extended to a more realistic setting.
