### ISSUE TITLE
[Postgres] Error on `october:up`

### ISSUE THREAD

**Issue by dustinleblanc** [octobercms/october#1493]
Trying out october (cheatin on Drupal a bit :) ) and ran across this everytime I try to  run `php artisan october:up`:

```
 [Illuminate\Database\QueryException]                                                                                                                                                           
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "sessions" already exists (SQL: create table "sessions" ("id" varchar(255) not null, "payload" text null, "last_activity" integer null))  






  [PDOException]                                                                  
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "sessions" already exists
```

**Comment by daftspunk** [comment]
Try `october:down` and retry, also is it an empty database? I don't see any code that would cause this table creation to execute twice.

**Comment by dustinleblanc** [comment]
It is an empty db, and october:down followed by october:up producres the same results. I should note: the application *does* still run when I run `php artisan serve` but the error happens every time I run october:up. I have tried this with two seperate installs (both run via the composer project create command). If it makes any difference, I am using Postgres instead of MySql.

**Comment by SaifurRahmanMohsin** [comment]
+1 I’m getting an even weird error
```
Fatal error: unexpected St12length_error: basic_string::_S_create
```

**Comment by qbunt** [comment]
I'm seeing this on MySQL as well. Maybe this is a laravel based problem

**Comment by daftspunk** [comment]
Very strange. Not sure how this is happening. It has come up before though. We should probably add a check to `DbSystemSessions` migration file to check if the table exists first.

modules\system\database\migrations\2014_10_01_000013_Db_System_Sessions.php

Please submit a PR for it. It would be unrelated to PostgreSQL too.

**Comment by qbunt** [comment]
@daftspunk I traced my MySQL issue back to the way October was being configured with a host filesystem mount inside a VM. Since then, everything's been fine. I was getting some odd MySQL issues but we were also running the beta build with the static pages plugin. 

Love October, keep it up! It's running http://deutsch.com
