### ISSUE TITLE
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

### ISSUE THREAD

**Issue by SinisaPerovic** [octobercms/october#1495]
While "Building configuration files" with RC from 7th October 2015., on Site5 shared hosting where I have two OctoberCMS systems installed previously as beta version without any issues.
I understand that it has something to do with MySQL password hash methods but interestingly I get the same error message with SQLite installation option
![screenshot from 2015-10-07 12 04 03](https://cloud.githubusercontent.com/assets/6765137/10337090/c18fcca4-6cfd-11e5-82b6-74dcf3c705ba.png)

**Comment by daftspunk** [comment]
This issue relates to your hosting provider. The MySQL account you're using probably has an old 16 character long password (hash). You can test that with a MySQL client (like HeidiSQL, the MySQL console client or any other client) and an account that has access to the mysql.user table.

Source: http://stackoverflow.com/a/1340538

**Comment by SinisaPerovic** [comment]
Thank you daftspunk but that is exactly what the Site5 support team said to me, to the word. So here I am, not being able to get pass installation and I've received "it's not us, it's them" answer from both parties. And from the past experiences I thing I will go with Site5 on this.

One more thing. Here at issues there is one similar post marked as solved where the solution was to get the hosting company to lower the Apache version from 2.4 to 2.2 or 2.0.  Now I love the OctoberCMS but with this attitude from your side I cannot support my clients.

Good bye and good luck with October.

**Comment by daftspunk** [comment]
Please show the link I posted above to your hosting provider. I think the solution may be as simple as resetting your database password. So long, and good luck!
