### ISSUE TITLE
Call to undefined method October\Rain\Support\Facades\Ini::parse() after updating 

### ISSUE THREAD

**Issue by lowerends** [octobercms/october#1497]
I updated October by running a composer update command and now I'm getting the following error when trying to load the frontend: 

`Call to undefined method October\Rain\Support\Facades\Ini::parse()`

The backend is running fine and can be accessed. Any idea what could cause this issue?

**Comment by MatissJanis** [comment]
I was experiencing the same issue. This fixed it for me

    rm -r vendor/
    composer install

**Comment by lowerends** [comment]
Thanks a lot! It fixes the issue and now it's documented for others experiencing the same issue :+1:
