### ISSUE TITLE
[BUG] Undefined method Ini::parse()

### ISSUE THREAD

**Issue by ab192130** [octobercms/october#1501]
Hi OctoTeam,

When I've upgraded CMS to the version **BUILD#303** got an error like:

```
Call to undefined method October\Rain\Support\Facades\Ini::parse()
```

The old version was **BUILD#292**.

Thanks for attention.

**Comment by SebastiaandenBoer** [comment]
I have the same bug. It has been occurring since build 302 over here, but it only seems to affect on of the two websites that I've got running on OctoberCMS. Hopefully this helps.

**Comment by MatissJanis** [comment]
Hardcoded solution: https://github.com/octobercms/october/issues/1497

**Comment by daftspunk** [comment]
Just run ` php artisan clear-compiled`

**Comment by daftspunk** [comment]
Fixed for good in Build 304

**Comment by ab192130** [comment]
Yay! Thank you guys, it works now.
