### ISSUE TITLE
Bug: Demoting a super admin

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [octobercms/october#1503]
There is a bug in OctoberCMS by which any administrator with permission to manage other administrators can demote super admin accounts.

Steps to reproduce:
1. Make a fresh install OctoberCMS with admin:admin account.
2. From the **admin** account, create an account **client** which will be the main administrative account (but does not have access to CMS tab and certain settings, code editor preferences, etc.).
3. Add this **client** account to the **Owners** group and also allow permission to Manage other administrators. This allows **client** to add as many admin / moderator accounts with different sets of permissions.
4. Log in to **client** account. From here go Administrators section to **admin** account permissions tab. Change ANY permission and save.

Internally, the database value for this super user account now changes from `{"superuser":1}` to an array containing the permissions that was selected in step 4.

There are no longer any super administrator accounts nor can **client** or **admin** create a new super administrator.

**Comment by daftspunk** [comment]
Including the super user flag as part of the permissions could be seen as a minor security flaw, for the reasons outlined above. It would be wise to extract this out to its own flag (`is_superuser`) and have it guarded in the model. This will impact the RainLab.User plugin and backend users.

We will action this today. Thanks for pointing this out.

**Comment by SaifurRahmanMohsin** [comment]
No problem. I originally looked for a bounty program hoping to make some money but there wasn’t one. In any case, I love the platform and do make money writing plugins so I’m glad to contribute. 👍
