### ISSUE TITLE
Collection::pluck is part of Laravel 5.1

### ISSUE THREAD

**Issue by alvaro-canepa** [octobercms/october#1505]
In the new documentation of OctoberCMS has `Collection::pluck()` method, but OctoberCMS use Laravel 5.0. When I try to use it, I have the exception `Call to undefined method October\Rain\Support\Collection::pluck()`

**Comment by daftspunk** [comment]
October now uses Laravel 5.1 as part of the stable release.

**Comment by alvaro-canepa** [comment]
Great!
