### ISSUE TITLE
How to retrieve image attachment in Backend Form

### ISSUE THREAD

**Issue by andriytkachiv** [octobercms/october#1507]
Hi, I need to to add ajax handler in Backend Form. I can retrieve all form data except image attachment. 
```Request::all()``` and ```Request::file()``` doesnt work. 
How could I get the image which is defined as a field? 

Thanks in advance

**Comment by daftspunk** [comment]
File attachments, generally speaking, cannot be sent via AJAX. October uses a system called deferred binding that sends the attachment over a separate request.

To get the file attachment, do so via the model relation, something like this:

```
$model->attachment()->withDeferred($model->sessionKey)->getPath();
```
