### ISSUE TITLE
Permission to access maintenance mode

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [octobercms/october#1512]
The current version of OctoberCMS prevents non-superadmins to change the web app between maintenance mode and live. It would be better to have an exclusive permission to allow specific backend users to change the maintenance mode. I doubt that a plugin can achieve this since this feature is pretty much a part of the core. So, it would be nice to have this.

**Comment by jwilson8767** [comment]
@SaifurRahmanMohsin The permission you are seeking is system.manage_themes.

**Comment by daftspunk** [comment]
As above

**Comment by SaifurRahmanMohsin** [comment]
I’m trying to make only the maintenance mode visible to client backend account and not the manage_themes. I scaffolded a new plugin and added the code below to the boot method hoping that since the permission replaces it would hide. But when I logged into a ‘client’ account without the *cms.manage_themes_only* permission it still appears so it doesn’t seem to work for some reason. What can I achieve this?

```
\Event::listen('backend.menu.extendItems', function($manager) {
    $item = SettingsManager::instance()->findSettingItem('October.Cms', 'theme');
    $pos = array_search('cms.manage_themes', $item->permissions);
    if ($pos !== FALSE)
       $item->permissions[$pos] = 'cms.manage_themes_only';
});
```
