### ISSUE TITLE
[Postgres] Inserting NULL into database tries to insert empty string

### ISSUE THREAD

**Issue by initbiz** [octobercms/october#1515]
Hi,
A couple of days ago I have posted a question about inserting empty string to Postgres on OctoberCMS forum: http://octobercms.com/forum/post/bug-inserting-null-into-postgresql-database-tries-to-pass-empty-string
As I mentioned I was wondering if it is not a bug. Now I am pretty sure it is. After I added 

```
$nullValue = $this->formWidget->getSaveData();
if ($nullValue['parent_id']=="") {
    $nullValue['parent_id'] = null;
}
$modelsToSave = $this->prepareModelsToSave($model, $nullValue);
```

to `modules\backend\behaviors\FormController.php` `create_onSave` method it seems to be working. So I guess the solution is to check if any of the arguments is empty string and convert it to null value. Does anyone try to insert empty string to database that is not null?
I have no idea if the issue is applicable on MySQL, but I hope it might be sort of help.
Take care.

**Comment by initbiz** [comment]
OK, I found the problem in adding comments in Sozonov Alexey's comments plugin as well. I had to change DB to MySQL. After that the problem is gone...

As I mentioned before I guess it is about converting from null to empty string in SQL queries which PostgreSQL PDO can't handle. It has to have null instead of empty string.

I hope the problem is not deeper, like in Laravel.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
