### ISSUE TITLE
all my october files are removed !

### ISSUE THREAD

**Issue by gabrieltong** [octobercms/october#1517]
1. after I install october by  `composer create-project october/october myoctober dev-master` 
2. open dir by sublime
3. wait minutes , all my files are removed , it's not by me !

**Comment by ameech** [comment]
Is this happening consistently for you? I'm not able to reproduce this.

**Comment by Mr118** [comment]
![aliens](http://assets.diylol.com/hfs/853/098/358/resized/ancient-aliens-invisible-something-meme-generator-im-not-saying-it-was-aliens-but-it-was-aliens-a0f6bd.jpg)

sorry guys, i had to ;p

**Comment by ameech** [comment]
It's always a possibility!

**Comment by gabrieltong** [comment]
I also don't believe that , but it happened to me , twice !
but it doesn't happen now . maybe I invoke a `remove all` shortcut  in my sublime ? I think it's the alien

**Comment by gabrieltong** [comment]
@ameech what possibility ? alien ?

**Comment by ameech** [comment]
@gabrieltong Yeah, aliens. Just doesn't seem like it's something that would happen from installing. I'm guessing you accidentally hit something, or it's something with your system.
