### ISSUE TITLE
Question (?) char in file name

### ISSUE THREAD

**Issue by AlexRadch** [octobercms/october#1528]
I got next error on Windows
 'file_exists(): open_basedir restriction in effect. File(C:\htdocs\laravel\webserver\www/lang/en/Do you really want to delete selected files or directories?.php) is not within the allowed path(s): (C:\htdocs)'

As you can see CMS try to check file with question (?) char in name and PHP returns open_basedir restriction error where PHP shouldn't return error.

**Comment by daftspunk** [comment]
Looks like a web server configuration issue, not related to October. Delete the file manually, that should fix it.
