### ISSUE TITLE
Allow custom accessors for relation fields

### ISSUE THREAD

**Issue by devcompl** [octobercms/october#1533]
Right now relations use 'nameFrom' that must be existing column name [here](https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/Relation.php#L119).

Which means there is no way (at least I could not find any) to for example concat two table columns.

Lets say I have a user model. I would like to make the relation field values take form of:

```
first_name . ' ' . second_name
```

First way I could think of is to allow custom accessor names. My temp [fix](https://gist.github.com/devcompl/6cffad47391769750101#file-gistfile1-txt-L4-L9) (highlighted diff with Illuminate\Database\Eloquent\Builder.php) would enable to use it like this:

```
// fields.yaml
nameFrom: full_name

// User.php model
public function getFullNameAttribute($value){
    return $value->first_name . ' ' . $value->second_name;
}
```

But for sure there is a better way to do this than my terrible fix.

Second way is to add a 'select' like in list columns, or maybe make 'nameFrom' work like it. This would work then:

```
select: CONCAT_WS(' ', first_name, second_name)
```

**Comment by arzola** [comment]
Any update on this?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
