### ISSUE TITLE
Javascript error in Docs > UI section

### ISSUE THREAD

**Issue by alvaro-canepa** [octobercms/october#1536]
The Documentation > UI section have a javascript error and is not possible to use it.

### The error detected by Firebug
![Firebug](https://box.everhelper.me/attachment/309806/r7lzpnvLFnkALhTZaxr2E4PptDrX4Yrf/397815-Kp9l7OVs0xyLc4Gi/october-cms-doc-ui-js-error.png)

Thanks

**Comment by daftspunk** [comment]
Looks like it might be fixed now.
