### ISSUE TITLE
Theme settings do not support file uploads/images

### ISSUE THREAD

**Issue by nsrosenqvist** [octobercms/october#1539]
A very common use case for theme customization is to let the user set a header image. Currently the theme settings implementation doesn't support any kind of file uploads. 

I find that really limiting and believe that empowering theme developers to create more customizable themes to fit more users/market groups would really unlock creativity and time investment from third party developers to invest into the platform.

**Comment by tplessis** [comment]
Check the relax theme, you can use "variables" from static pages plugin, like here : https://github.com/rainlab/relax-theme/blob/cbb54520e967388ae5b4a53f064e962b933b16f7/layouts/chair.htm#L19

**Comment by nsrosenqvist** [comment]
Interesting! Though it looks like it doesn't fulfill the need completely because it would require a dependency on StaticPages and only works on static pages and a global header could be used on other types of layouts as well.

I will definitely look into using it as a temporary workaround though! Thanks!

**Comment by daftspunk** [comment]
This is fixed and will be available in Build 342+
