### ISSUE TITLE
Compressed page & Uncaught Error

### ISSUE THREAD

**Issue by DanielHitchen** [octobercms/october#1543]
Hi guys,

Any idea why this has started happening where the menu is getting cropped & the search box has shifted over:

![bug](https://cloud.githubusercontent.com/assets/7501909/10631122/a8d8a6b4-77d3-11e5-926c-5ca0a6421698.jpg)

Have I missed a class off somewhere? It's only just started happening as of Build 306

**Comment by DanielHitchen** [comment]
It seems that the style ```style="width:110px"``` isn't being applied to the search ```toolbar-item```:

![before](https://cloud.githubusercontent.com/assets/7501909/10632365/f19c8dae-77db-11e5-8684-8490442317bb.jpg)

once applied, all is ok again:

![after](https://cloud.githubusercontent.com/assets/7501909/10632380/02aa1490-77dc-11e5-87ef-270a53625041.jpg)

![correct](https://cloud.githubusercontent.com/assets/7501909/10632384/06657cdc-77dc-11e5-804d-425ad5579318.jpg)

**Comment by DanielHitchen** [comment]
Might be something to do with this error  in console:
```
Uncaught Error: Trigger action is not specified.
storm-min.js?v306:2882
```

**Comment by HwapX** [comment]
Same here

**Comment by kdoichinov** [comment]
Having the same issue, but only on some elements in the nav...

**Comment by kdoichinov** [comment]
I found the problem. I had to "refactor" my Delete button to this:
    <button
            class="btn btn-default oc-icon-trash-o"
            disabled="disabled"
            onclick="$(this).data('request-data', {
                checked: $('.control-list').listWidget('getChecked')
            })"
            data-request="index_onDelete"
            data-request-confirm="Are you sure?"
            data-trigger-type="select"
            data-trigger-action="enable"
            data-trigger=".control-list input[type=checkbox]"
            data-trigger-condition="checked"
            data-stripe-load-indicator>
        Delete
    </button>

**Comment by kdoichinov** [comment]
I found the problem, the Delete button needs a property called `data-trigger-action`, this gets rid of the error.

    <button
            class="btn btn-default oc-icon-trash-o"
            disabled="disabled"
            onclick="$(this).data('request-data', {
                checked: $('.control-list').listWidget('getChecked')
            })"
            data-request="index_onDelete"
            data-request-confirm="Are you sure?"
            data-trigger-type="select"
            data-trigger-action="enable"
            data-trigger=".control-list input[type=checkbox]"
            data-trigger-condition="checked"
            data-stripe-load-indicator>
        Delete
    </button>

**Comment by DanielHitchen** [comment]
Thanks @kdoichinov that seems to have fixed the issue :)
