### ISSUE TITLE
Sorting on a relationship rendered in a list fails because it's not part of the join

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1544]
```
"SQLSTATE[42S22]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'cityname'. (SQL:
SELECT TOP 20 [hotels].* 
FROM   [hotels] 
WHERE  ( ( ( Lower(hotels.hotel_name) LIKE %tropicana% ) 
        OR ( Lower(hotels.hotel_zipcode) LIKE %tropicana% ) 
        OR ( Lower(hotels.tti_code) LIKE %tropicana% ) ) 
      OR (SELECT Count(*) 
          FROM   [geo_city] 
          WHERE  [hotels].[hotel_city_id] = [geo_city].[id] 
                 AND (( Lower(geo_city.cityname) LIKE %tropicana% ))) >= 1 ) 
ORDER  BY [cityname] ASC 
)" on line 624 of F:\MassWeb\nl\newyorkhotel\wp\install-master\vendor\laravel\framework\src\Illuminate\Database\Connection.php
```

I tracked this down to \modules\backend\widgets\Lists.php to the Method prepareModel();

I managed to get the column in the select list by  adding 

```
$selects[] = $this->model->makeRelation($column->relation)->getTable().'.'.$column->valueFrom;
```

in https://github.com/octobercms/october/blob/master/modules/backend/widgets/Lists.php#L361

but it didn't resolve the issue becuase the table needs to be joined in the query itself.
I tried some fiddling around, but I can't seem to figure out how to get the relationship details(is it done via a linking table so a double join, is it done directly, is there a key/otherKey defined, etc.. sorted out or figure out which method gives those parameters.

How to replicate:

_columns.yaml_

```
city:
    relation: hotel_city
    nameFrom: cityname
    valueFrom: cityname
    label: exitcontrol.hotelmanager::lang.hotelmanagermodel.hotel_city
    searchable: true
```

_relation definition_

```
public $belongsTo = ['hotel_city' => [
        'ExitControl\CountryManager\Models\CityModel',
          ],
  ];
```

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
