### ISSUE TITLE
Relation behavior does not work with pivot data

### ISSUE THREAD

**Issue by myst6re** [octobercms/october#1553]
I tried [the example](http://octobercms.com/docs/backend/relations#belongs-to-many-pivot) from the documentation, and when there is no "form" key in manage section, an error is thrown on onRelationButtonCreate action:

    <div id=""Call to a member function getId() on a non-object" on line 1 of C:\wamp\www\ffdream-cms\modules\backend\behaviors\relationcontroller\partials\_manage_form.htm

I investigated a little, and the detected mode for this action is always "form".
I also searched why the error message is so opaque, that's because "RelationController::makeConfigForMode" can return null or false, and nobody test this case.

I continue my investigation, because I have no solution yet to make it work.

**Comment by myst6re** [comment]
Ok, here is the main problem: create and delete buttons in the toolbar does not work with pivot data.
By default, the toolbar is populated with create|add|delete|remove, you need to specify "toolbarButtons: add|remove" in the view.

I think the documentation needs an update, and the error message should be clearer.

**Comment by daftspunk** [comment]
Feel free to submit a PR to improve the docs.

**Comment by jpruiz114** [comment]
Is there a workaround to make the create option work for pivot data?

**Comment by LukeTowers** [comment]
Deferred binding (which is used to save relationship data for records that haven't been created yet, so when you are first creating them) is not supported for pivot data in the RelationController behavior yet. 

If you would like to see support for that added, consider [opening a bounty](https://www.bountysource.com/teams/october) or implementing it yourself and making a pull request.

**Comment by LukeTowers** [comment]
This is a duplicate of #1409
