### ISSUE TITLE
Image upload fails if extension is in upper case

### ISSUE THREAD

**Issue by JoelESvensson** [octobercms/october#1556]
More specifically it fails when I drag and drop into a `fileupload` field with a mode set to `image`

**Comment by wetgi** [comment]
See https://github.com/octobercms/october/issues/1156

**Comment by xjchengo** [comment]
You can set `fileTypes` option with `jpg,jpeg,bmp,png,gif,svg,JPG,JPEG,BMP,PNG,GIF,SVG` to support upper case extension.

**Comment by JoelESvensson** [comment]
Sure. But wouldn't it be better if the extensions got normalized to lower case?

**Comment by daftspunk** [comment]
Duplicate #1156
