### ISSUE TITLE
repeater drag and drop only works on top level

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1558]
The repeater form has some nice drop and drag functionality, but it only works for top level.
You can drag nested level elements away, but you can only drop them at the top level :-(

    menuitems:
        span: left
        type: repeater
        prompt: Add new menu item
        form: 
            fields:
                added_at:
                    label: menuitem
                menuitems2:
                    type: repeater
                    prompt: Add new menu item/layer
                    form: 
                        fields:
                            added_at:
                               label: menuitem
                            menuitems3:
                                type: repeater
                                prompt: Add new menu item/layer
                                form: 
                                    fields:
                                        added_at:
                                            label: menuitem
                                        menuitems4:
                                            type: repeater
                                            prompt: Add new menu item/layer
                                            form: 
                                                fields:
                                                    added_at:
                                                       label: menuitem

**Comment by daftspunk** [comment]
Duplicate #1679
