### ISSUE TITLE
repeater opens same subset of nested repeaters on add item

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1559]
![image](http://i.imgur.com/D0T1xf8.png)

If I click on add item on the blue, red or black line it adds the same added set that was added to the nested set before.

This is not desirable... Just add the most top level form as if it's a fresh form. I do not need a repeat of the same nested levels I made above, I want to make a seperate set...

    menuitems:
        span: left
        type: repeater
        prompt: Add new menu item
        form: 
            fields:
                added_at:
                    label: menuitem
                menuitems2:
                    type: repeater
                    prompt: Add new menu item/layer
                    form: 
                        fields:
                            added_at:
                               label: menuitem
                            menuitems3:
                                type: repeater
                                prompt: Add new menu item/layer
                                form: 
                                    fields:
                                        added_at:
                                            label: menuitem
                                        menuitems4:
                                            type: repeater
                                            prompt: Add new menu item/layer
                                            form: 
                                                fields:
                                                    added_at:
                                                       label: menuitem

**Comment by daftspunk** [comment]
This was fixed a while ago.
