### ISSUE TITLE
jsdon data not saved from datatable widget used in a pivot model

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#1563]
jsdon data not saved from datatable widget used in a pivot model
only a double braket [] is saved 

however, the if i setup the json data in the database, the datatable widget is ble to read the value in the pivot model, but losse the value when saved again.

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.
