### ISSUE TITLE
Ability to edit CoffeeScript in Assets

### ISSUE THREAD

**Issue by filipac** [octobercms/october#1564]
Hello all, I would like to edit CoffeeScript right in the backend. Right now i edited the editableAssetType config like so:
```php
'editableAssetTypes' => ['css','js','less','sass','scss','coffee']
```

But there is no syntax highlighter for Ace Coffeescript. How can I do this?

**Comment by daftspunk** [comment]
We can add the file type, feel free to submit a pull request. Adding the highlighter support would be a question for the Ace team.
