### ISSUE TITLE
Proxy settings during installation 

### ISSUE THREAD

**Issue by lucandrade** [octobercms/october#1567]
Add proxy settings on installation.
I've had to set the proxy manually on curl request.

**Comment by daftspunk** [comment]
Related to https://github.com/octobercms/install/pull/27

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
