### ISSUE TITLE
ViewBag component required properties

### ISSUE THREAD

**Issue by MatissJanis** [octobercms/october#1571]
Currently, if I have a partial that uses the ViewBag component, and the component property is not defined - this will result in an error.

**Example partial:**
````
<div class="container">
    {{ viewBag.someProperty }}
    {{ viewBag.someOtherProperty }}
</div>
````
**Example page:**
````
url = "/"

[viewBag]
someProperty = "TEST"
==
{% partial 'somename' %}
````

**Expected result:** 200
**Actual result:** 500 - An exception has been thrown during the rendering of a template ("The component 'Cms\Classes\ViewBag' does not contain a method 'someOtherProperty'.").

**Example working page:**
````
url = "/"

[viewBag]
someProperty = "Hello World"
someOtherProperty = "TEST"
==
{% partial 'somename' %}
````

**Workaround partial**
````
<div class="container">
    {{ viewBag.properties.someProperty }}
    {{ viewBag.properties.someOtherProperty }}
</div>
````

**Comment by daftspunk** [comment]
Twig is supposed to fail gracefully in any case. In other words the error `The component 'Cms\Classes\ViewBag' does not contain a method 'someOtherProperty'` should be suppressed by Twig.
