### ISSUE TITLE
Feature suggestion: Layout builder

### ISSUE THREAD

**Issue by nsrosenqvist** [octobercms/october#1573]
I read somewhere about a form builder being in construction. It got me thinking about a way to implement a layout builder and that way being able to completely hide the CMS file editing functionality but still have a fully customizable solution for the user by relying on StaticPages, Blog and the builder functionality.

The idea is basically that layouts can as previously use components. They can be both user created and loaded from a theme but instead of being direct html in the theme, the file is a JSON-formatted (simply because it's easier to edit by hand than XML), hierarchical file format that describes the layout. Then they are rendered into twig files in the cache so that the other plugins can continue to work as before.

The implementation in the mockup is based on how the bootstrap framework's responsive features work. (excuse the weird mix of fonts and quality, my app decided to quit on me and I didn't want to redo things)

![layout](https://cloud.githubusercontent.com/assets/1303475/10861610/a236836a-7feb-11e5-90df-3f19aea1ba10.png)

The sketch looks really cramped but with a scrollable window and colour coding it can be made to look much more cleaner.

Examples of building blocks that can be used in the layout builder are:
* Theme blocks (partials basically)
* User created blocks
* Everything supported by the "variable" tag
* A component (e.g. blogPosts)
* Container
* Rows (can only be inserted when there's a parent "container")
* Columns (can only be inserted into rows - these rules apply also when rearranging items)

In the top of the layout builder there's a toolbar with settings for testing the layout on different device sizes (it simulates the column wrapping) and zooming (could potentially be implemented through something like [this solution](http://stackoverflow.com/questions/166160/how-can-i-scale-the-content-of-an-iframe))

I started thinking way too much about this so I just needed to draw it out to be able to let it go. Hopefully this is something that the project would appreciate.

**Comment by riuson** [comment]
How this feature can implement themes like this?
http://octobercms.com/theme/simpleweb-landed

**Comment by nsrosenqvist** [comment]
That would probably be done by theme blocks, e.g. a Hero block. When the user edit the page he/she would fill out the needed fields through the staticPages "variable" theme tags.

Then for the screenshot with the grid positioned items you would use a row x  2 > column x 3 > theme block (that has variables for icon, title and text).

**Comment by hybridvision** [comment]
Nice ideas - thanks for going to such effort to explain it :) I think a feature like this could be really useful and I've noticed that these kind of layout builders are all the rage currently, especially in the WordPress world. Some of them are quite nice while others are very clunky so a lot of effort will be required to make sure the UI is streamlined and doesn't get too complicated.

Another one I've seen is CraftCMS and their approach to handling content and flexible layouts: http://buildwithcraft.com/features/matrix - I haven't used it myself but it looks nice.

Interested to see more discussion about this...

**Comment by tsioukas** [comment]
Layout builder is good for users that they want something quick, but we lose the October motto "Back to the basics". So if someone build it, it must be only as optional add-on. 

All the other CMS began to serve these features and finally they lose their way. Just simplicity, that’s why I love on OctoberCMS.

**Comment by riuson** [comment]
@tsioukas +1
Layout manager in Drupal makes a pain.

**Comment by jBOKA** [comment]
@tsioukas +1
I think October was always about having control over your html markup in regard to designing while being able to very freely and quickly develop custom backends for the customer. I can imagine a lot of people would like to use such a feature, but there are great tools for this already.
I was also thinking about creating some kind of layout plugin for more generic website structures, but in the end this is not what using october is about (to me at least).
Also I don't think it would be a senseful approach to lose the decoupling of the cms/theme and the plugin/functionality, which is very important.
But anyway, if someone builds it, someone will use it.

**Comment by luizbills** [comment]
-1
The layout will need a css framework.

**Comment by amdad** [comment]
Guys, take a look : http://gantry.org/

**Comment by daftspunk** [comment]
This is a great idea for a plugin! Although this issue does not belong in the main October repo.
