### ISSUE TITLE
datepicker widget post back data even though it is set hidden

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#1574]
event if i set hidden attribute to true, a datepicker type field is always post back to the controller in the attributes, and apparently it should not be according to the following and according to the behavior of the rest of type field like text.

in the FormField.class php, i found this attribute and comment

/**
     * @var bool Specify if the field is hidden. Hiddens fields are not included in postbacks.
     */
    public $hidden = false;

**Comment by chrisvidal** [comment]
actually, the issue is happeining for all widget type as per the code in class Form.php.
Any widget will return an attributes value event if it is hidden, and this behavior is not standardize with the other type field as per comment above.

        /*
         * Give widgets an opportunity to process the data.
         */
        foreach ($this->formWidgets as $field => $widget) {
            $parts = HtmlHelper::nameToArray($field);

            $widgetValue = $widget->getSaveValue($this->dataArrayGet($result, $parts));
            $this->dataArraySet($result, $parts, $widgetValue);
        }

**Comment by daftspunk** [comment]
This was fixed in cb86e655ddfee65eb6ccf818acbacf0e52d5273f
