### ISSUE TITLE
validation unique ignores $connection

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1580]
I have my shared data database in a different table from the octobercms table.
this however means I can't use the rule

```
public $rules = [ 'name' => 'required|unique:rich_block_block,name']
```

because it won't use the database defined in $connection but the default database.

```
SQLSTATE[42S02]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]
Invalid object name 'rich_block_block'. (SQL: 
       select count(*) as aggregate from [rich_block_block] where [name] = Hawaii
 )" on line 624 of F:\*\vendor\laravel\framework\src\Illuminate\Database\Connection.php
```

**Comment by der-On** [comment]
This refers to #1354 and I would be very happy if it could be merged into an official build.

**Comment by daftspunk** [comment]
This is fixed as of Build 381, please update October to get the changes.

Merged in https://github.com/octobercms/library/commit/bb7037fde174cb590667675836c23dd85a2c56f8

**Comment by der-On** [comment]
Thank you allot.

**Comment by AugmentBLU** [comment]
No idea why but this is happening in 426. 

My rule
```
'name' => 'required|min:4|unique:dashboard.my_table,name',
```

It's checking the default DB instead. If I do something like this... it does work but I don't really want to have to override via the config.

```
public function beforeValidate()
{
   \Config::set('database.default', 'dashboard');
}
```
