### ISSUE TITLE
Controller redirect when returning false in beforeSave

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1581]
If i'm in the create module of my controller and I return false in the model `beforeSave()` the controller still redirects to `/update/:id` but instead of a nice number(becuase that wasn't created of course) it fills the url with the text `:id` and so it can't do a query becuase it can't convert the text to int so the user gets presented with a nice exception.

I can circumvent it by throwing an exception

    public function beforeSave() {
        $q = $this->where('name',$this->name)->count();
        if($q) {
        	throw new \Exception("The given name already exists");
        }
    }

But I'd rather just return false and use Flash::error

I propose that if in create the model doesn't safe itself and no id is generated that the controller aborts and displays any give Flash::error messages.

**Comment by xjchengo** [comment]
If you return false from `beforeSave`, how to pass error message?

**Comment by tschallacka** [comment]
Throw a modelexceptio

**Comment by daftspunk** [comment]
It would be safer to define your own AJAX handler for this custom logic, in the controller.
