### ISSUE TITLE
Prevent slug duplication

### ISSUE THREAD

**Issue by vizo** [octobercms/october#1583]
I see in test https://github.com/octobercms/october/search?utf8=%E2%9C%93&q=duplicate+slug&type=Code this is covered.

But in admin i can still give same slug to two different pages or to two different blog posts.

Any idea?

**Comment by daftspunk** [comment]
It is hard to tell what is failing in your code without seeing it

**Comment by vizo** [comment]
It is clean installation, with RewriteBase /subfolder.

**Comment by jBOKA** [comment]
Slugs are not part of anything in a clean installation. The only thing that might be duplicated are urls e.g. of pages. Do you mean that?

// Indeed, two pages in the CMS area can have the same url (without a visible collision when saving), one of them is then served, the other is not reachable obviously

**Comment by vizo** [comment]
Yes i mean that... pages, also blog post urls from RainLab. I guess there should be some warning?

**Comment by jBOKA** [comment]
You are right, this should be adressed here
https://github.com/rainlab/blog-plugin/blob/master/models/Post.php#L26
in case of the Blog plugin.

But generally I don't know if Octobers routing is that centralized to avoid
collisions. Every Plugin would have to implement it's own solution...

vizo <notifications@github.com> schrieb am Sa., 14. Nov. 2015 um 19:16 Uhr:
