### ISSUE TITLE
Cache folder permissions

### ISSUE THREAD

**Issue by bnymn** [octobercms/october#1584]
Hello,

I have set folder permissions to 755, and file permissions to 644 during the installation process. I get the following error. The permissions of directories under the cache folder are 644, which should be 755. The permissions of all other folders and files are correct.

file_put_contents(/home/.../public_html/storage/framework/cache/8c/53/8c53ed3bfd167d2f85044017a3c25db9): failed to open stream: Permission denied

Something went wrong during the installation. Please check the log file or see the documentation for more information.

**Comment by xjchengo** [comment]
Check your webserver user.  Maybe your webserver user is different from your file owner.  So webserver user has no permission to write.

**Comment by bnymn** [comment]
It's my fault. In the installation processes, I have mistyped folder permissions.
