### ISSUE TITLE
Extensible widgets

### ISSUE THREAD

**Issue by jwilson8767** [octobercms/october#1586]
Right now formwidgets and general widgets are not extensible outside of the use of events (limited at best) or completely re-creating them with new names.

Example: I wanted to add an extra js file to the richeditor when it loads, but cannot.
Example: I wanted to replace the _field_number.htm partial with a custom partial, but cannot.

**Comment by daftspunk** [comment]
This enhancement should be performed before the stable release, as it potentially poses a breaking change for edge cases.

Enhancement is: Make `WidgetBase` class extend the `Extensible` class, like `ComponentBase` and others.
