### ISSUE TITLE
Extensible CmsCompoundObject

### ISSUE THREAD

**Issue by jwilson8767** [octobercms/october#1587]
Pages, StaticPages, Partials, Layouts all extend CmsCompoundObject, but there is no way to extend any of them without relying on events. I propose that CmsCompoundObject or CmsObject should implement the ExtendableTrait, or be made extensible in some other manner.

Example use case: I could use a dropdown parser variable on a static page layout, but I cannot add a method to the static page instance from which to return the dropdown options.

**Comment by daftspunk** [comment]
CmsObject's are extensible since the implementation of Halcyon.
