### ISSUE TITLE
yaml instead of ini configuration

### ISSUE THREAD

**Issue by jwilson8767** [octobercms/october#1588]
In the interest of consistency, I propose that the configuration sections at the top of CmsCompountObjects should be yaml instead of ini.

**Comment by jwilson8767** [comment]
On a related note, could the files in /config be yaml as well? I'm just tired of having so many methods of configuration which are all so different from one another.

**Comment by daftspunk** [comment]
Each configuration syntax is hand picked for its purpose. Config files are in PHP for speed. INI syntax is used for simplicity. YAML is too prone to syntax issues with indentation, front-end developers don't need to learn YAML for implementing components.

**Comment by jwilson8767** [comment]
Great to know, thanks!
