### ISSUE TITLE
Why are some of the drivers so out of date?

### ISSUE THREAD

**Issue by tseven** [octobercms/october#1592]
* aws/aws-sdk-php at version ~2.0 -> [Current version is **3.0**](https://github.com/aws/aws-sdk-php)
* guzzlehttp/guzzle at version ~4.0 -> [Current version is **6.0**](https://github.com/guzzle/guzzle)

These are the two drives I'm most interested in at the moment.

Is there a reason why these are running several major versions behind?

**Comment by jBOKA** [comment]
This is sort of related: I'd like to know what the workflow is for updates of dependent libs.
I'd like to propose a PR that depends on a slightly newer version of Carbon (now 1.19 -> depends on 1.21).
Are dependency changes handled by october's update mechanism (I guess not)? Is such a PR useless before some major update that includes dependency updates?

**Comment by that0n3guy** [comment]
@daftspunk the driver plugin page (http://octobercms.com/plugin/october-drivers) says aws and guzzle are 3.0 & 6.0 respectively, but I just installed the driver plugin and composer does not show that: 

```
    "require": {
        "php": ">=5.4",

        "aws/aws-sdk-php": "~2.0",
        "pda/pheanstalk": "~3.0",
        "iron-io/iron_mq": "~1.5",
        "predis/predis": "~1.0",

        "league/flysystem-rackspace": "~1.0",
        "league/flysystem-aws-s3-v2": "~1.0",

        "guzzlehttp/guzzle": "~5.0"
    },
```

So the plugin page is wrong...

**Comment by daftspunk** [comment]
Look at the changelog. Enable edgeUpdates to get these versions.

**Comment by daftspunk** [comment]
These packages have been updated ready for the stable release.
