### ISSUE TITLE
close.oc.popup not fired when relation render modal is closed

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1597]
When you have the relation renderer modal and you close that after saving it doesn't fire the october event `close.oc.popup`.

This can be bypassed by listening to the `hidden.bs.modal` from bootstrap, but it's not exactly what one would expect.

On a related note, relation render doesn't seem to fire an update event that can be handled by dependsOn. Not sure if I should make a seperate issue for that or if that can be wrapped up in one ticket.

**Comment by daftspunk** [comment]
This should probably be a pull request.
