### ISSUE TITLE
File Upload forms does not work with Relation Behavior and Pivot Model

### ISSUE THREAD

**Issue by myst6re** [octobercms/october#1600]
When you add a file upload form in a pivot field in the controller's relation configuration, the attachment is not saved/attached with the pivot model: the image is uploaded, an entry seems to be added in system_files table, but after saving the page, the association between the pivot table and system_files is not correctly saved.

**Comment by tschallacka** [comment]
+1 I'm encountering the same issue.
 
owning model RichIndexPage


    public $belongsToMany = ['richblock' => ['\ExitControl\RichIndexPageManager\Models\RichBlock',
    		                                  'key' =>'rich_page_id',
                                                'otherKey'=>'rich_block_id',
                                                'table' => 'rich_block_to_page',
                                                'order' => 'sortorder',
                                                'pivot'=>'sortorder',
                                                'timestamps'=>'true']];


Relation model RichBlock

    public $belongsToMany = ['richpage' => ['\ExitControl\RichIndexPageManager\Models\RichIndexPage',
    		                                  'key' =>'rich_page_id',
                                                'otherKey'=>'rich_block_id',
                                                'table' => 'rich_block_to_page',
                                                'pivot'=>'sortorder',
                                                'timestamps'=>'true']];
    public $attachOne = ['image' => ['System\Models\File',]];

**Comment by tschallacka** [comment]
It has to do with deferred binding messing up, if I add this in 
FileUpload.php on line 263 ish

    if(strpos($this->alias,'Pivot')){
        $this->getRelationObject()->remove($file);
    }
    else {
        $this->getRelationObject()->remove($file, $this->sessionKey);
    }

then it works ish, although the ajax postback still fails miserably.

**Comment by tschallacka** [comment]
I made a dirty workaround to allow me to do both things in the mean time...

in the relation render fields yaml add a partial where you will define your form fields for the pivot data

    <div class="form-group  text-field span-full   " data-field-name="subtitle" id="Form-relationRichblockManageForm-field-RichBlock-subtitle-group">
        
        <?php
        $pivot = '';
        foreach($this->vars['formModel']->richblock as $block) {
            if($model->getKey() == $block->getKey()) {
                $pivot = $block->pivot->sortorder;
            }
        }
        ?>
        
        <input type="hidden" name="RichBlock[pivot][owner]" value="<?= $this->vars['formModel']->getKey(); ?>">
        
        <input type="text" name="RichBlock[pivot][sortorder]" id="Form-relationRichblockManageForm-field-RichBlock-sortorder" value="<?= $pivot ?>" placeholder="" class="form-control" autocomplete="off" maxlength="255">
    </div>

Then in your Model(mine is RichBlock)

    public function beforeSave() {
        $post = post('RichBlock');
        // I have only ONE relation field here... you miht have to fiddle around with sending additonal parameters
        // if you have multipe pivots to discern which field/property to find
        if(isset($post['pivot']) && isset($post['pivot']['owner'])) {
            // Ugly ugly ugly...
            $richpage = $this->richpage()->where($this->richpage()->first()->getKeyName(),$x['pivot']['owner'])->first();
            $richpage->pivot->sortorder = $x['pivot']['sortorder'];
            $richpage->pivot->save();
        }
    }

**Comment by tschallacka** [comment]
if you don't rely on overly complicated pivot data you could use a workaround like I hacked together in my comment in https://github.com/octobercms/october/issues/1600

it's not pretty, and probaly has room for improvement, but it allows you to work in the mean time.
Just remove the pivot entry from the relation manager and add a partial to the normal fields.yaml.

**Comment by myst6re** [comment]
In fact there is two problems by using an attachment in a pivot model:
* The deferred binding is not committed
* The method getKey() of the pivot model seems to return null, even after saving the model

For the first problem, you can fix it by specify the session key in the save lines in modules/backend/behaviors/RelationController.php:

    public function onRelationManagePivotCreate()
    {
        [...]
                    foreach ($modelsToSave as $modelToSave) {
                        $modelToSave->save(null, $this->pivotWidget->getSessionKey());
                    }
        [...]
    }

    public function onRelationManagePivotUpdate()
    {
        [...]
            foreach ($modelsToSave as $modelToSave) {
                $modelToSave->save(null, $this->pivotWidget->getSessionKey());
            }
        [...]
    }

For the second problem, I guess that a pivot model is identified by two ids (the associated models), and not by a main integer. But the system_files table needs an id to identify the model where the file is associated. There is many solutions to this problem, but that is not a simple change.

**Comment by myst6re** [comment]
Ok, I found a solution to my problem.

The patch above is needed, and you also need to add some attributes to your pivot table:
* An attribute "id" auto-increment (it implies that the other keys will not be the primary, just unique)
* An attribute with the name of the attachment (this works for attachOne, I don't know for attachMany). Not that this is a fake attribute, only used to lie to October.

Both attributes must be declared in the schema database and declared pivot attributes in the parent model.

Now the system_files table is correctly filled.

**Comment by myst6re** [comment]
In the documentation and in #1409 it says deferred binding is not supported for pivot data. But I wonder if my fix is enough to enable deferred binding, it seems to work, no?

**Comment by daftspunk** [comment]
Fixed by #1641

**Comment by LukeTowers** [comment]
@myst6re your fix fixes pivot data having other relationships that are deferred to the pivot record directly, however it doesn't support the pivot record itself being deferred.

**Comment by mihailbishkek** [comment]
I can't attach file in pivot relation Manager. How I can do it?

**Comment by daftspunk** [comment]
> I can't attach file in pivot relation Manager. How I can do it?

Pivot models do not use a primary key and are therefore not compatible with system files or deferred binding so cannot be used with the `fileupload` widget. As an alternative, try using the `mediafinder` widget instead.
