### ISSUE TITLE
[Rich Editor] Characters are stripped out in richeditor

### ISSUE THREAD

**Issue by andreaslof** [octobercms/october#1611]
Have noticed an issue where characters that appear *after* emphasised text is being stripped out by the JS from time to time. This seem to only be occurring when the emphasised toggle is de-selected and then more text is inserted directly afterwards.

Here is an excerpt of what gets posted over the wire:
```
[...]
Page[standfirst]:<p>​Standfirst for the page</p>
Page[hero_image]:/image.jpg
Page[hero_image_caption]:<p>​A caption. <em data-verified="redactor">Emphasised</em></p>
[...]
```
In the above, after the emphasised part, this is what actually should be posted over the wire:
![image](https://cloud.githubusercontent.com/assets/357990/11299940/ed221172-8f82-11e5-8711-92b15c4e72f8.png)

**Comment by daftspunk** [comment]
This was retested using the implementation in #2005 and could no longer be replicated. If the issue still exists, please log a new issue for it.
