### ISSUE TITLE
Allow access to .htaccess subfolder

### ISSUE THREAD

**Issue by prhost** [octobercms/october#1615]
Hello, I wonder if this is where I ask about this, but as I am working with a project will october question.I wanted to have full access to a folder and subfolder without the october change the route and go to the 404, would be another project on october with its own 404, example "public/projects/foo/bar/" being the october It is in the public root.

**Comment by prhost** [comment]
someone please :cry:

**Comment by jwilson8767** [comment]
Is your server using Apache or Nginx? What sort of files need to be accessible?

**Comment by prhost** [comment]
apache, all files in a subfolder that does not pass through the route october

**Comment by jwilson8767** [comment]
Try this solution: http://stackoverflow.com/questions/1848500/htaccess-mod-rewrite-how-to-exclude-directory-from-rewrite-rule

Apply the change to your project's .htaccess

**Comment by prhost** [comment]
worked, thank you friend (:

**Comment by nyxzryu** [comment]
Hi, 

Also needed this to be done. What i want is i want to exclude some folder (/test, /chat, /shortener). I wanted that folder to use another script that's not october part. However, for php files, it returns blank pages. 
What i already did is : 

1. Editing my .htaccess in the folder where my october is installed, i added : 
```
    RewriteEngine On
    RewriteRule ^(test|test2|test3|test4|test5)($|/) - [L]
```
But when i access /test/myfiles.php it returns blank page, while i access /test/myfiles.html it works

2. Editing my .htaccess in the folder where i need to exclude the folder (for ex: /test ) is installed, i added : 
```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule !index\.php$ /index.php [L]
```
Stll no luck, and returns blank page.

Any solution ?

**Comment by daftspunk** [comment]
There are several layers of protection at work here, the layer you are hitting here is the statement that says

> Block all PHP files

If you remove this line, a layer of security will be removed, but it will allow the PHP files to execute 

```
RewriteCond %{REQUEST_FILENAME} \.php$
```
