### ISSUE TITLE
Fileupload ignores disabled form flag

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1616]
When I have a file upload field for images, and I set the yaml attribute to `disabled: true` I'm still able to remove the file or modify the attributes.

    # works as expected
    link_url:
        label: Url
        disabled: true
       
    # I do what I want
    image:
        label: Link image within grid(220x400)
        type: fileupload
        disabled: true

**Comment by daftspunk** [comment]
Pretty sure this was fixed a while ago. Don't know when, sorry.
