### ISSUE TITLE
[Inconsistentcy]: Current item called $record in lists and $model in views. Confusion ensues

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1617]
I am very often debugging stuff thanks to a naming convention because i'm mixing up things because of where it's used.

When i'm using a partial in a list, to access the current model I need to use $record. But when I'm in a relation view or a normal update view I need to use $model to access the current model.

This is really confusing at times when you wish to re-use a bit of code somewhere but have to swap out all the $record or $model references in that piece of code.

I propose that either `$record`(which is logical) is used or `$model`, but not both. It would make life as a dev a lot easier to know "That thing points to current thing i'm working on" instead of having to reflect on what am I working on again, what is it called in this context... google, no resulsts, `dump(get_defined_vars())` oh right it's `$record` in this context.

**Comment by daftspunk** [comment]
A list returns a collection of `$record`s while a form returns a `$model`

Are you saying there is a place where a list is returning a collection of `$model`s?

**Comment by tschallacka** [comment]
No, but if you have partial, to show something from a relation(for example a canvas rendering based on relation values) then in the update view the partial needs $model, but the list needs $record, but I'd like to have the same consistent method of calling current data item.

Not having to remember in which scope im working and what the current scope variable is called,  $record $model or anything.

Also this means you can't reuse a partial in a model or list without a current render scope test.

It complicates programming workflow. Or expose a method getCurrentModel that backemd partial programmers can use to get the current main model for rendering things.

Verzonden vanuit Outlook Mobile<https://aka.ms/blhgte>



On Fri, Dec 4, 2015 at 3:49 PM -0800, "Samuel Georges" <notifications@github.com<mailto:notifications@github.com>> wrote:


A list returns a collection of $records while a form returns a $model

Are you saying there is a place where a list is returning a collection of $models?

-

**Comment by LukeTowers** [comment]
@tschallacka are you interested in making a PR to make this feature available?

**Comment by tschallacka** [comment]
I could, but after having more comfort dealing with october i usually use this when i need this functionality.

    if(!isset($model) && isset($record)) {
        $model = $record;
    }

Keeps me as a dev on my toes when i look at a partial code that is also used in a list.

I think it might be more productive to add a comment to documentation about this use case. 
Shall i add such a thing to docs?

**Comment by LukeTowers** [comment]
Sure, if you think it would be beneficial I would appreciate it!

**Comment by Samuell1** [comment]
This already exists in docs for partial:
https://octobercms.com/docs/backend/forms#field-partial
https://octobercms.com/docs/backend/lists#column-partial
