### ISSUE TITLE
october:up vagrant problem

### ISSUE THREAD

**Issue by zsoro2** [octobercms/october#1619]
I updated my virtual machine. I use vagrant - laravel/homestead box on windows. I want use php artisan october:up , because my  database disappeared and i want to rebuild. But i always get this error
![bug1](https://cloud.githubusercontent.com/assets/3978697/11367084/989e6fc4-92b1-11e5-968e-b0f3b01b592b.jpg)

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at' (SQL: create table `deferred_bindings` (`id` int unsi
  gned not null auto_increment primary key, `master_type` varchar(255) not null, `master_field` varchar(255) not null, `slave_type` varchar(255) not n
  ull, `slave_id` varchar(255) not null, `session_key` varchar(255) not null, `is_bind` tinyint(1) not null default '1', `created_at` timestamp defaul
  t 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci engine = InnoDB)

I think it's because of the new homestead box, but i can't find any real solution.

**Comment by zsoro2** [comment]
I found a solution. If you add to config/database.php 

'strict'    => true,

![bug2](https://cloud.githubusercontent.com/assets/3978697/11368343/9050970e-92b9-11e5-8fca-53c116d6d517.jpg)

**Comment by jwilson8767** [comment]
please close this issue since it is now resolved

**Comment by vospascal** [comment]
thnx for the solution zsoro2
