### ISSUE TITLE
Backend just stopped working.

### ISSUE THREAD

**Issue by fuzzybaird** [octobercms/october#1620]
First off I just want to preface that I am on shared hosting on justhost.com so I am not excluding them as a possible culprit and minimal proper PDO support. I just know that the site worked for a while before the error, and very little changed. 

I was logged into my backend from one computer, then logged in with the same account on a another computer and i got this error

>**could not find driver**

> (sitename).com/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php line 47  
---- 
> public function createConnection($dsn, array $config, array $options) {
>   
>    $username = array_get($config, 'username');
>  
>    $password = array_get($config, 'password');
> 
>    **return new PDO($dsn, $username, $password, $options);**
>    }

I have not changed anything except what exists in the themes folder of the site. 

I have checked my database config file, and all of that information has remained the same. Is there a direction I should look to solve this?

**Comment by FelixINX** [comment]
-> http://stackoverflow.com/questions/33904228/october-cms-could-not-find-driver

**Comment by fuzzybaird** [comment]
Ok after trying out all of your advice I have discovered that of course it was my crappy hosting. There shared PDO support is having some bugs I guess. Your solution for installing the October Driver plugins actually fixed some other issues I was having.
