### ISSUE TITLE
Subdomain Page routing [important]

### ISSUE THREAD

**Issue by andriytkachiv** [octobercms/october#1622]
Hi, it will be very useful feature, for example for blogs. 

Will it be planned? 

https://octobercms.com/forum/post/cms-page-subdomain-routing-feature

**Comment by daftspunk** [comment]
This could be handled easily by a plugin. The RainLab.Translate plugin does something similar to this with languages in the URL.

**Comment by tsioukas** [comment]
Translate plugin recognizes standard urls for Translation proposes only, not for content or for example client page with different data but same layout. Also it doesn’t recognize wildcards. See my examples in above post in forum.

Maybe I am wrong but I don’t get it how it will works, I will search Tranlsate plugin code to see what you mean.

Thanks

**Comment by LukeTowers** [comment]
@ikanell you can use route grouping to accomplish what you want.
