### ISSUE TITLE
black backhround for thumbs

### ISSUE THREAD

**Issue by hitch90** [octobercms/october#1623]
Hey,

I have problem with thumbs :) I uploaded png files and use getThumb filter in twig, like image.getThumb(300,300 auto). 

I works but have problem with transparent background. Always set black background. I tried png and jpg extension.

**Comment by daftspunk** [comment]
The default thumb extension is JPG, try

```
$file->getThumb(64, 64, ['extension' => 'png'])

{{ file.getThumb(64, 64, { extension: png }) }}
```

**Comment by hitch90** [comment]
I'll tried change extension to PNG but thumb still had black background :)

**Comment by Develop-FM** [comment]
My source image is transparent png, i forced to use "{ extension: png }" even on 0.5mb thumbnails?

Request option to change default background color for thumbs jpg (without transparent color/alpha formats).

**Comment by jbartoszek** [comment]
I have this bug too.

**Comment by daftspunk** [comment]
Please provide a sample image that you are using.

**Comment by hitch90** [comment]
When I wrote this post png transparent image had black background. Now I see you fixed this ;) More than 7 months I didn't check it. Thanks!

**Comment by fresswolf** [comment]
There still is an issue with black backgrounds when resizing a png and explicitly use mode: 'jpg'. The alpha channel is rendered black in that case. A better default in my opinion would be a white background for alpha blending when saving jpgs.

**Comment by bennothommo** [comment]
@fresswolf JPGs have no alpha channel, which is why transparent backgrounds are rendered as black when mode is `jpg`.

It is possible to layer a PNG on top of a specific layer of colour with the GD library - which is what Resizer uses - but I don't believe it has that capability yet.

A PR to add in functionality like that would be a welcome addition.
