### ISSUE TITLE
Using Artisan::add in init.php does not work

### ISSUE THREAD

**Issue by JoelESvensson** [octobercms/october#1624]
https://octobercms.com/docs/console/development states that you should be able to write `Artisan::add(new Acme\Blog\Console\MyCommand);` in `init.php` and the command will be added

Instead I get an exception

```
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method October\Rain\Foundation\Console\Kernel::add()
```

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
