### ISSUE TITLE
Backend relation behavior error on PostgreSql

### ISSUE THREAD

**Issue by lolek77** [octobercms/october#1625]
When adding a relation record return sql error: SQLSTATE[23502]: Not null violation. In query primary key is null.

**Comment by jwilson8767** [comment]
So far as I know October currently only officially supports MySQL even though the Laravel framework upon which October is built does support other dbms options. So the answer to your issue is **use MySQL**

**Comment by daftspunk** [comment]
This looks like the column needs to be set to nullable, not so much an issue with the driver itself.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
