### ISSUE TITLE
[Rich editor] Saving while in HTML doesn't save the latest changes

### ISSUE THREAD

**Issue by JoelESvensson** [octobercms/october#1627]
If you edit something in HTML mode, the changes you've made won't be saveable until you actually exit HTML mode

**Comment by jacobalvarez** [comment]
I have experienced this as well using the WYSIWYG on pages in the Static Pages plugin.

**Comment by jwilson8767** [comment]
I believe this is a bug in redactor, but can't be sure.

**Comment by jwilson8767** [comment]
Replication instructions: go to a page with a richeditor, enter html mode, make some changes, save the page. Examine the raw post data to see that the changes were not saved.

**Comment by jacobalvarez** [comment]
[Related issue](https://github.com/rainlab/pages-plugin/issues/112)

**Comment by daftspunk** [comment]
This was retested using the implementation in #2005 and could no longer be replicated. If the issue still exists, please log a new issue for it.
