### ISSUE TITLE
Login / Forgot Pass responsive

### ISSUE THREAD

**Issue by robinbonnes** [octobercms/october#1633]
Hello,

Since almost the complete backend is responsive, will it be possible to also make the login / forgot pass page responsive?

When I find out how to have a good workspace for OctoberCMS I will make the pull request myself.

Keep up the amazing work!

- Robin

**Comment by FelixINX** [comment]
For me the button is responsive.
`btn btn-primary login-button` and `text-muted` is based on Bootstrap, that is responsive. Can you please give out a screenshot or something more descriptive, or even a fix, to your issue?

**Comment by robinbonnes** [comment]
Thanks for your fast reply.

This is how it looks on my mobile phone:

![screenshot_2015-12-04-09-55-24](https://cloud.githubusercontent.com/assets/5117166/11585667/e9a1111a-9a6d-11e5-9a63-90e67b72abe3.png)

![screenshot_2015-12-04-09-55-07](https://cloud.githubusercontent.com/assets/5117166/11585668/e9a36f78-9a6d-11e5-8d5f-e4b3d3271048.png)

I will fix it myself when I'm able to setup the SCSS thing.

**Comment by FelixINX** [comment]
I see. The form isn't responsive. It may just be HTML related.

**Comment by daftspunk** [comment]
Fixed in https://github.com/octobercms/october/commit/00ced6c79f912976f18072ae56b340b5335ab9fa#diff-4f8aecaaf6cc0cecc392aa703387cecaR115
