### ISSUE TITLE
Repeater button almost invisible in modal popup

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1635]
I use one of the october default templates with a lightgray background for the backend, and the repeater remove button becomes practiacally invisible in a modal popup.

Thanks to this little css rule

    .modal-content .close {    /*october.css?v271:2741*/
         color: #fff; 
    }

adding a 

    .repeater-item-remove button.close {
        color: #000;
    }

Solves that issue

**Comment by gblair** [comment]
We came across this, too -- pull request attached.  Thanks!

**Comment by daftspunk** [comment]
Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by daftspunk** [comment]
Looks like we have one already!

https://github.com/daftspunk/oc-test-plugin/pull/12

**Comment by daftspunk** [comment]
Fixed by #1998
