### ISSUE TITLE
[Feature Request] Allow plugin to extend image processing options

### ISSUE THREAD

**Issue by jofrysutanto** [octobercms/october#1638]
At the moment there is no possible way for Developers to easily hook into `Resizer` class and provides additional options (`fit` option from [Intervention](http://image.intervention.io/) library comes to mind). 

At the moment, extending from `System\Models\File` seems to be the only way to do it:

```
/**
 * Deakin File attachment model
*/
class File extends FileBase
{

    protected $extendedMode = ['fit'];

    /**
     * Extended local thumb generator, with additional 'fit' option
     * At the moment it's creating Intervention/Image class from url,
     * unsure about the issue with creating it from local path.
     */
    protected function makeThumbLocal($thumbFile, $thumbPath, $width, $height, $options)
    {
        // Bail early if not using extended mode
        if (in_array($options['mode'], $this->extendedMode)) {
            parent::makeThumbLocal($thumbFile, $thumbPath, $width, $height, $options);
            return;
        }

        $rootPath = $this->getLocalRootPath();
        $filePath = $rootPath.'/'.$this->getDiskPath();
        $thumbPath = $rootPath.'/'.$thumbPath;
        $thumbPublic = $this->getPublicPath() . $this->getPartitionDirectory() . $thumbFile;

        /*
         * Handle a broken source image
         */
        if (!$this->hasFile($this->disk_name)) {
            BrokenImage::copyTo($thumbPath);
        }
        
        /*
         * Generate thumbnail using custom method
         */
        else {

            \Image::make(url($this->getPath()))
                    ->fit($width, $height, function($constraint)
                    {
                        $constraint->upsize();
                    })
                    ->save($thumbPath);
        }

        FileHelper::chmod($thumbPath);
    }
```

Am I missing something here, is there an easier way to implement custom image processing logic that plays well into `getThumb`?

**Comment by daftspunk** [comment]
Looks good, unless you want your logic to have a global reach, then we would need to implement a dynamic method, like `getThumbSpecial`

```
\System\Models\File::extend(function($model) {
    $model->addDynamicMethod('getThumbSpecial', function() use ($model) {
        // Custom logic
    });
});
```

**Comment by SaifurRahmanMohsin** [comment]
+1 I have a different use case for this. Google Webmaster tool **PageSpeed Insights** showed me that the generated thumbs on my OctoberCMS website could be reduced by 70%. So, I think this would be a great feature to have--I could use this dynamic method to put in some sort of image compression/optimisation functions as well.

**Comment by shina** [comment]
I did a different approach to handle global images.
@SaifurRahmanMohsin I'm using the http://tinypng.com/ API to dynamically reduce the image size.

Extending the Storage's s3 provider:

`
\Storage::extend('s3', function($app, $config) {
            $s3Config = array_only($config, ['key', 'region', 'secret', 'signature', 'base_url']);

            return new \Your\Customised\Filesystem(new AwsS3Adapter(S3Client::factory($s3Config), $config['bucket']));
});
`

My implementation of Filesystem using the Tinify:

`
class Filesystem extends \League\Flysystem\Filesystem
{

    /**
     * @inheritDoc
     */
    public function put($path, $contents, array $config = [])
    {
        if (in_array(strtolower(substr($path, -4, 4)), ['.png', '.jpg', 'jpeg']) && \Config::get('filesystems.imageOptimize.tinify.enabled', false)) {

            \Tinify\setKey(\Config::get('filesystems.imageOptimize.tinify.key'));
            $contents = \Tinify\fromBuffer($contents)->toBuffer();
        }

        return parent::put($path, $contents, $config);
    }

}
`
