### ISSUE TITLE
Unable to use getDropdownOptions with a jsonable form field in the backend

### ISSUE THREAD

**Issue by philltrue** [octobercms/october#1643]
Hey guys, we might be the only one trying to do this, but would be great if it could be fixed.

I have a model with:

```
protected $jsonable = ['meta'];
```

and then in my backend fields I use it as:

```
meta[menu_template]:
   label: Menu Template
```

Normally this works fine, but if I try it with a dropdown field and want to store the options in the model, I get the following error:

"get_class() expects parameter 1 to be object, array given"
modules\backend\widgets\Form.php line 908

The issue is that the $model returned a few lines above is an array rather than the current class.

Cheers,
Phill

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
