### ISSUE TITLE
Plugin should extend october:mirror

### ISSUE THREAD

**Issue by skydiver** [octobercms/october#1644]
When using the public folder setup, the Wysiwyg Editor plugin has missing files.

Please, add

```
plugins/anandpatel/wysiwygeditors/resources/
```

to 

```
modules/system/console/OctoberMirror.php
```

**Comment by skydiver** [comment]
Same happens with Blog Tags plugin:

```
/plugins/bedard/blogtags/vendor/owl/tagbox/widget/assets
```

**Comment by daftspunk** [comment]
This will need some way for the plugins to define their asset folders.

**Comment by LukeTowers** [comment]
Technically fixed by https://github.com/octobercms/october/commit/d3b2809866d135b4d88f032929736602298b2210#diff-24f9a53bb5ca54f39c2ab34945d2d652, however leaving open as we still need the ability to hook into this command by plugins.

**Comment by daftspunk** [comment]
Note this event name has been renamed to `system.console.mirror.extendPaths`.
