### ISSUE TITLE
Upgrade to Laravel 5.1 LTS

### ISSUE THREAD

**Issue by dearhulu** [octobercms/october#1645]
the october cms is based on laravel 5.0,but my plugin uses the package which is based on laravel 5.1.so how can i upgrade the october to Laravel 5.1?

**Summary (added by daftspunk)** To test the LTS version, clone the `stable` branch and run `composer install`.

**Comment by prhost** [comment]
You can try updating the composer.json, but it does work, october can undo your changes at any time in future builds ;/

**Comment by mplodowski** [comment]
I would recommend you to wait for October team to handle this.

I tried this myself, but updating composer.json to laravel 5.1 was not enough. There are many differences in October libraries to handle. Even if you fix them all you will be blocked from any October updates because they will overwrite your changes.

**Comment by leocavalcante** [comment]
@daftspunk There is a roadmap for the upgrade?

**Comment by ametad** [comment]
:+1:

**Comment by williamzid** [comment]
maybe we should wait October team to handle this problem

**Comment by provectusblue** [comment]
I wish they would include Guzzle Client? Driver does not install it.

**Comment by robinbonnes** [comment]
The 'stable' branch contains Laravel 5.1. However when I download this branch and run composer install, Apache is crashing.

**Comment by daftspunk** [comment]
@robinbonnes This should be fixed by https://github.com/octobercms/library/commit/83888f4a35ec5919d23f57ab1a8e51c096921385

**Comment by robinbonnes** [comment]
Thanks. It does indeed. Just for the sake of curiosity; How did you find this bug? Because I was looking at it the whole day :(

**Comment by daftspunk** [comment]
We used XDebug and a process of elimination: checking that routes work, locating at what point in the CMS route it failed, troubleshooted the first model to be called (MaintenanceSettings), and narrowed it down to the `remember()` method. This remember feature that we loved and kept from Laravel 4.2 so it required some maintenance to work with 5.1.

**Comment by nanohard** [comment]
:+1:

**Comment by daftspunk** [comment]
October build 319+ uses Laravel 5.1 LTS
