### ISSUE TITLE
Impossible to use relation in Backend List with a Tree model

### ISSUE THREAD

**Issue by xNok** [octobercms/october#1647]
I have an entity (Job) which belongs to another entity (Mandate). I build a list showing Job and related Mandate
![membership-ok](https://cloud.githubusercontent.com/assets/9772542/11696851/baa12de4-9eb6-11e5-91aa-06558bac7f89.png)

Then I added a Tree relationship on Job model and I actived showTree in the config_list.yaml
>use \October\Rain\Database\Traits\SimpleTree;

 Then the bug appear in the Mandate column.
![membership-nok](https://cloud.githubusercontent.com/assets/9772542/11696965/7ff6950c-9eb7-11e5-87c7-835905f9d0c3.png)

**Comment by xNok** [comment]
# Bug explanation

> in Backend\Widgets\Lists

In the getRecords function you can see that recrad using a Tree model use a quite different way

```php
    /**
     * Returns all the records from the supplied model, after filtering.
     * @return Collection
     */
    protected function getRecords()
    {
        if ($this->showTree) {
            $records = $this->model->getAllRoot();
        }
        else {
            $model = $this->prepareModel();
            $records = ($this->showPagination)
                ? $model->paginate($this->recordsPerPage, $this->currentPageNumber)
                : $model->get();

        }

        return $this->records = $records;
    }
```

in the getColumnValue function you can see the $value comes from an specific attribut withe the column name

```php
        /*
         * Otherwise, if the column is a relation, it will be a custom select,
         * so prevent the Model from attempting to load the relation
         * if the value is NULL.
         */
        else {
            if ($record->hasRelation($columnName) && array_key_exists($columnName, $record->attributes)) {
                $value = $record->attributes[$columnName];
            }
            else {
                $value = $record->{$columnName};
            }
        }
```

However this attribute's value is fill thanks to the extra query created in the prepareModel function.
Thus a Tree model have not an extra query when we set a column with a relation 

```php
            /*
             * Relation column
             */
            if (isset($column->relation)) {

                // @todo Find a way...
                $relationType = $this->model->getRelationType($column->relation);
                if ($relationType == 'morphTo') {
                    throw new ApplicationException('The relationship morphTo is not supported for list columns.');
                }

                $table =  $this->model->makeRelation($column->relation)->getTable();
                $sqlSelect = $this->parseTableName($column->sqlSelect, $table);

                /*
                 * Manipulate a count query for the sub query
                 */
                $relationObj = $this->model->{$column->relation}();
                $countQuery = $relationObj->getRelationCountQuery($relationObj->getRelated()->newQuery(), $query);

                $joinSql = $this->isColumnRelated($column, true)
                    ? DbDongle::raw("group_concat(" . $sqlSelect . " separator ', ')")
                    : DbDongle::raw($sqlSelect);

                $joinSql = $countQuery->select($joinSql)->toSql();

                $selects[] = Db::raw("(".$joinSql.") as ".$alias);
            }
```

## exemple of query
* columns.yaml
>mandate:
        label: Mandate
        relation: mandate
        select: name

* $selects[] 
> (select name from `xnok_membership_mandates` where `xnok_membership_jobs`.`mandate_id` = `xnok_membership_mandates`.`id`) as `mandate`

## How to solve this bug

I see where the problem is but I do not know how to start

*  create a specific prepareModel function ?

* improve the prepareModel function ?

* improve the getAllRoot function ?

**Comment by daftspunk** [comment]
Can you submit a PR to [the test plugin](https://github.com/daftspunk/oc-test-plugin) that demonstrates this problem?
