### ISSUE TITLE
CombineAssets -> registerCallback from Plugin

### ISSUE THREAD

**Issue by christianWilling** [octobercms/october#1648]
The problem is that if i call this
```
\System\Classes\CombineAssets::registerCallback(function($combiner){
    $combiner->registerFilter('js', new \Test\Js\Classes\Compiler);
});
```
from the `boot` function it work fine in backend.
But when i add a filter the problem is that the assets are compiled by `System\Classes\Controller@combine` but there the `boot` of a plugin dont get called.

I fixt it by adding the  `registerCallback` in the `__construct`.

But im not sure if that is the correct way?

**Comment by daftspunk** [comment]
You may need to set the `$elevated` property to `true` in your plugin registration file.

```
    /**
     * @var boolean Determine if this plugin should have elevated privileges.
     */
    public $elevated = true;
```

Most plugins are not booted for system critical pages or requests that need to be efficient, so elevating them will ensure it is always registered and booted regardless.

**Comment by christianWilling** [comment]
ok thx for the help i will fix this in my plugin
