### ISSUE TITLE
October\Rain\Support\Traits\Singleton is not documented

### ISSUE THREAD

**Issue by JoelESvensson** [octobercms/october#1649]
Are you supposed to use `October\Rain\Support\Traits\Singleton` when developing plugins? It is pretty useful but doesn't seem to be documented anywhere

**Comment by daftspunk** [comment]
If you want, this will be documented as part of the API docs.

**Comment by JoelESvensson** [comment]
Great! I was worried it was a private API that eventually could get removed

**Comment by scottbedard** [comment]
@daftspunk is there an ETA on API docs? I think they would be really helpful.
