### ISSUE TITLE
Filters are applied twice

### ISSUE THREAD

**Issue by alxy** [octobercms/october#1653]
List filters are applied two times to the query:

![query](https://cloud.githubusercontent.com/assets/2057062/11762466/8ebf9cc8-a0e7-11e5-80ca-ab87b705865b.PNG)

That does not casue any problems with the functionality, but still it is not nice, especially when the queries get more complex and long.

**Comment by daftspunk** [comment]
Confirmed. This is a soft bug that is harmless in most cases. Need to check why the "apply filter" event is getting called twice.

**Comment by daftspunk** [comment]
We fixed this a while ago =)
