### ISSUE TITLE
Deferred fileupload within deferred hasOne relation not stored

### ISSUE THREAD

**Issue by jBOKA** [octobercms/october#1654]
I have the following construction:
```
Project
    |
    -hasOne: ProjectElement
             |
             - attachOne: System\Models\File
```
I am using the `RelationController` to handle the ProjectElement within the ProjectController. Therefore I get a popup (using update button as described in the `RelationController` docs). In this popup I attach the File.
On saving the ProjectElement and the Project afterwards, the deferred binding of the ProjectElement is stored correctly, but the deferred binding of the file attachment is lost and stays deferred.

Is there a flaw in my construction?

Thanks in advance.

**Comment by jBOKA** [comment]
Alright, according to daftspunk in https://github.com/octobercms/october/pull/1526#issuecomment-148876345, attachOne/Many and morphOne/Many are not supported in the RelationController.

If this has changed by now, please correct me.

**Comment by daftspunk** [comment]
Just check to make sure there are not multiple records for a hasOne relationship. There is a known bug that results in zero records showing when a hasOne relation actually has data that shows as hasMany.

Ref: https://github.com/daftspunk/oc-test-plugin/blob/ca20d3026ca44a4deb6da0be6a97b10261bfab51/readme.md#tests-that-need-attention
*HasOne relations acting as HasMany will break the list completely.*
