### ISSUE TITLE
Octobercms pages/layouts/etc not saving correctly

### ISSUE THREAD

**Issue by marcoelho97** [octobercms/october#1660]
This is a small bug I've been experiencing over the past few months, it's not a bad bug, it's just somewhat annoying.
Sometimes, when editing a file in the CMS, it will "save". If you close and re-open the file, it will be exactly as you left it, but if you preview it, it will be as if you never saved it. I have to re-save it so that I can see the changes in the frontview.
I have experienced this locally and online.

Locally, my setup is:
laravel/homestead (virtualbox, 0.2.7)

I experience this very often when I'm saving multiple files at once.

But, even with this bug, I enjoy OctoberCMS Very much! Keep it up ;D

**Comment by dqsully** [comment]
Sounds like this problem: http://octobercms.com/forum/post/template-asset-caching-during-development,  I'm trying to get it fixed.

**Comment by daftspunk** [comment]
This is a known issue and should be fixed in an upcoming build

See 5a70cec7a2f17494a5e519236095e831bac9daa3

Refs #1672
