### ISSUE TITLE
form widget for morphOne / morphMany relation

### ISSUE THREAD

**Issue by IcedLime** [octobercms/october#1661]
Hi,
I would like to know if it's possible to make a form widget for create the MorphModel on the same form 
please see : https://github.com/october-widgets/library/issues/10

Thank's

**Comment by daftspunk** [comment]
This is possible using a custom Form Widget, see some of the examples in the `backend/formwidgets` directory to see how it's done. Also make sure the widget is registered in the plugin file:

```
    public function registerFormWidgets()
    {
        return [
            'Backend\FormWidgets\CodeEditor' => [
                'label' => 'Code editor',
                'code'  => 'codeeditor'
            ]
        ];
    }
```
