### ISSUE TITLE
Index of array in jsonable

### ISSUE THREAD

**Issue by brenodouglas** [octobercms/october#1662]
I'm using repeater widget and jsonable for attribute of repeater. But to save in database my json look likes this:
```json
{"1": {"hour":"12:00"}, "2": {"hour": "13:00"}}
```
And my ideal json in database is:
```json
[{"hour": "12:00"}, {"hour":"13:00"}]
```
How could solve this problem? Or do you believe is correct that first form?

**Comment by jwilson8767** [comment]
afaik this is done by the repeater formwidget to allow it to be compatible with php arrays and cannot be changed.

**Comment by daftspunk** [comment]
Yes, that's right. These are generated identifiers, particularly useful when sorting and maintaining a unique reference to an item. To strip them out you would need to post-process the attribute. For example if the field name is called `foo_bar`, you could use a mutator method in the model:

```
public function setFooBarAttribute($value)
{
    $this->attributes['foo_bar'] = json_encode(array_values($value));
}
```
