### ISSUE TITLE
Change the configuration of a relation based on its context.

### ISSUE THREAD

**Issue by Beaudinn** [octobercms/october#1664]
Hey, 

I would like to change the `relationConfig` property of a controller on its create, update and preview actions before the form behavior automatically initialize the model, in order to change the relationship name definition specific for a action method. 

Now the building of the configuration property is done inside the constructor of the Relation behavior.
I suggest the proper position for this is inside the `initRelation` method.

Or maybe it's better to also specify its context inside the relationship name definition.

**Comment by daftspunk** [comment]
What specifically did you want to change? It is possible to use `context` to apply a context to the form fields.

```
context:
  update: relationUpdate
  create: relationCreate
```
