### ISSUE TITLE
MediaManager -  Cannot read property 'setAttribute' of null

### ISSUE THREAD

**Issue by silentwarrior** [octobercms/october#1666]
Hello.

I installed October today and have been trying it out.

I wanted to try the media manager, but in Chrome console I got this:
mediamanager-browser-min.js:204 Uncaught TypeError: Cannot read property 'setAttribute' of null

Thus, the page is unusable.

Is this a known problem?

**Comment by daftspunk** [comment]
I can't seem to replicate this issue, have you noticed it is a recurring error?

**Comment by LukeTowers** [comment]
Closed due to no follow up from @silentwarrior
