### ISSUE TITLE
Installation issue with Database

### ISSUE THREAD

**Issue by mambax7** [octobercms/october#1667]
Installing on MySQL 5.7.9:
SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at' (SQL: create table `deferred_bindings` (`id` int unsigned not null auto_increment primary key, `master_type` varchar(255) not null, `master_field` varchar(255) not null, `slave_type` varchar(255) not null, `slave_id` varchar(255) not null, `session_key` varchar(255) not null, `is_bind` tinyint(1) not null default '1', `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci engine = InnoDB)

**Comment by daftspunk** [comment]
As per #1668, try adding to your database configuration:
```
'strict'    => true
```

**Comment by daftspunk** [comment]
We fixed this as part of the stable release. For further details: 

http://octobercms.com/support/article/rn-4
