### ISSUE TITLE
[OctoberCMS Website] No way to remove Projects

### ISSUE THREAD

**Issue by JohannesMP** [octobercms/october#167]
Correct me if I'm wrong, but I can't seem to find a way to remove Projects from my OctoberCMS Account Project page.

http://octobercms.com/account/projects Only displays a list of projects, and clicking on any one of them yields no way to simply remove the project:
![drawing](https://cloud.githubusercontent.com/assets/662874/3011206/0e7e116c-df27-11e3-8e3f-a1bd28b9ee01.png)

**Comment by huglester** [comment]
close?

**Comment by BenjaVR** [comment]
Removing projects is now possible, so this issue can be closed!
