### ISSUE TITLE
Next big thing

### ISSUE THREAD

**Issue by yozman** [octobercms/october#1670]
hi,
first of all I'm a biggest fan to `octobercms`,
it's really beautiful, fast and useful.

since now I will tell you my idea,
u could laugh as a joke,
it's just my suggestion :)

there are too many CMS we have,
like wordpress, drupal, ghost also october.

I call wordpress, drupal, ghost `CMS 1.0`.
`CMS 1.0` can use the site to create content like write blog.
I call october `CMS 2.0` although it's not good enough,
maybe `CMS 1.5` I think.
`CMS 2.0` can use the site to create site like develop features.
the workflow should like this:

there should be a `develop` menu like `cms` menu,
when I want to add a features to the site,
1. click the `new feature button`
2. change the layout code and add some
3. click the `new migration` button to change database tables if I need
4. click `done` to apply the feature
5. it will be a backup point so I can rollback the changes like `git`

So on `CMS 2.0` I can do anything about the site
without `ssh`, `phpmyadmin`, `editor`, `git command` and others,
use `/backend` is enough with button click.

**Comment by fuzzybaird** [comment]
See I like the thought of this, But my fear, is that the more we get away from the beautiful flat file (IDE ready), and plug in design of October, the more volatile the code becomes. The more we diverge from Laravel, which is the intelligent glue that holds this together the more foreign it is to develop in. Just my thoughts though.

**Comment by yozman** [comment]
@fuzzybaird 
I get idea from [`eclipse che`](http://www.eclipse.org/che/)
everything in cloud,
but eclipse is just an editor,
I wish october could be a platform,
maybe `CMS 2.0`

**Comment by yozman** [comment]
all the software is made by number `1` & `0`
and `1` + `0` is `10` name october,
wish october can make `CMS 2.0` come ture

**Comment by FelixINX** [comment]
Please see October Builder.

http://octobercms.com/blog/post/builder-idea
https://www.facebook.com/octobercms/videos

**Comment by daftspunk** [comment]
What you've described is a [rapid builder-type CMS](https://octobercms.com/blog/post/putting-octobercms-words), October is capable of something like this, provided by a plugin of course. We are in the process of building our own interpretation with the RainLab.Builder plugin which will be available soon.
