### ISSUE TITLE
Backend user that can manage users can give more permissions to self

### ISSUE THREAD

**Issue by bbrala** [octobercms/october#1673]
This seems kind of counter-intuitive and you could see it as a bug. 

When i backend user had a set of permissions, but that permission includes the management of users. The user can give himself any other permission available. This seems quite counterintuitive. Shouldn't a backend user only have the right to give out permission he has himself?

Reproduce steps: 
1. create a user and user group with only manage users and usergroups permissions
2. log in as such a user and change add permissions to your user group.

Expected: you cannot give yourself or other users more permissions you yourself have.

Result: You can give more permissions.

**Comment by daftspunk** [comment]
This is an interesting point, and sounds like a good solution: only allow a user to grant other users permissions that they themselves have.

**Comment by bbrala** [comment]
I was thinking about this, and this would also mean you should only be able to assign a group which has the same or less permission than you have.

The next problem is, how would you have the managing of users. When is a user visible for the managing account. I mean, should that account be able to change the name of an superadmin or someone in a group that has more permissions. And if you do, what happens when you save that user. Does the system ignore the permissions parts you don't have the rights to?

Anyhow, this might be slightly complicated :)

**Comment by LukeTowers** [comment]
@bbrala This should be addressed in https://github.com/octobercms/october/commit/2046efb51d8682de9aca68881b378e0e3dcc44eb although the issue with being able to manage a group that has more permissions than your user account does still exists. Discussion on that shall continue in #2367.

**Comment by bbrala** [comment]
Ok thanks for getting back to us.

**Comment by LukeTowers** [comment]
Another update:

With the Role system introduced in Build 420+ and the improvements from https://github.com/octobercms/october/commit/fa840d79f6cbd054830d0f4e345bf024da9f18a7 this should be mitigated even further. Users (even with the `manage_users` permission) cannot manage roles, they can only manage the assigning of roles to users. Only SuperUsers are able to manage roles. 

The only minor risk remaining is a user assigning a role with more permissions then they themselves have to another user, however this is almost a non-issue given the level of trust someone with manage_users needs to have. This could in theory be even further mitigated with a four tier user permission system as suggested in the above commit.
