### ISSUE TITLE
[feature request]set admin account on october:up 

### ISSUE THREAD

**Issue by jwilson8767** [octobercms/october#1674]
~~Some users may not know to change the default admin/admin login. Therefore I suggest that on first login October should require a new password.~~ alxy informed me that the installer does this already.

Bonus: it would be cool if we could pass a username and password when running `artisan october:up` to use as the default admin login.

**Comment by daftspunk** [comment]
Perhaps an `october:install` command would be more useful, allowing the user to set database configuration as well.

**Comment by jwilson8767** [comment]
That...that sounds great!
