### ISSUE TITLE
Retina Images Support

### ISSUE THREAD

**Issue by buckhornmktg** [octobercms/october#1681]
When uploading a @2x image via the media uploader the special charter @ is removed.

**Comment by opterons** [comment]
file: modules/cms/widgets/MediaManager.php
line: 1004
function: validateFileName
dependant functions: onApplyName, onCreateFolder, checkUploadPostback
from: if (!preg_match('/^[0-9a-z\.\s_\-]+$/i', $name)) {
to: if (!preg_match('/^[0-9a-z@\.\s_\-]+$/i', $name)) {
comment: added a @ into the regular expression to allow the @ symbol in file names when renaming/moving/creating/uploading.

**Comment by daftspunk** [comment]
Fixed by #1631

**Comment by buckhornmktg** [comment]
Thanks!
