### ISSUE TITLE
Plugins Router.php not running on Laravel/Forge Servers. 

### ISSUE THREAD

**Issue by fuzzybaird** [octobercms/october#1682]
OctoberCMS Specific Problem,

When declaring routes in the {my}/{plugin}/Routes.php file they work on my local development environment which is a laravel Homestead Box. When I push it up to my production environment a Laravel-Forge provisioned (similar to homestead), it fails to register plugin routes.

There is the exact same code base on local & dev where I ran artisan route:list.

	(LOCAL)vagrant@homestead:~/default$ php artisan route:list
	| Method   | URI                 | Action                                              |
	|----------|---------------------|-----------------------------------------------------|
	| GET|HEAD | chg/api/email/index | Chg\Email\Http\Controllers\ReferralController@index |
	| POST     | chg/api/email/send  | Chg\Email\Http\Controllers\ReferralController@send  |
	| GET|HEAD | index_eli           | Closure                                             |

	(REMOTE)forge@personal:~/default$ php artisan route:list
	| Method   | URI         |      | Action  |
	|----------|-------------|------|---------|
	| GET|HEAD | sitemap.xml |      | Closure |

Here are my plugins Routes.php file

	<?php
	Route::group(['prefix' => 'chg/api/email/'], function() {
		Route::get('index', 'Chg\Email\Http\Controllers\ReferralController@index');
		Route::post('send', 'Chg\Email\Http\Controllers\ReferralController@send');
	});
	Route::get('index_eli', function (){
		return 'hello';
	});

I want to point out that if I were to register a route under modules/cms/routes.php it works both locally and remotely.

besides the generic 404 page not found error I am not getting any errors. So my question is has anyone seen this before? and do they know where to look to diagnose this?

**Comment by daftspunk** [comment]
Have you tried `routes.php` (all lower case)?

**Comment by fuzzybaird** [comment]
Oh my gosh I could kiss you!!!!! It worked. That is so weird. So some severs don't like capitals?

**Comment by jwilson8767** [comment]
Paths are case sensitive in all unix environments. routes.php just happens to be loaded by filename.

**Comment by fuzzybaird** [comment]
Yah but we could do a case for both.
