### ISSUE TITLE
Backend Settings for plugins fail to load on first instance.

### ISSUE THREAD

**Issue by ARH-Digital** [octobercms/october#1683]
I just encountered an odd bug in /backend/system/settings for custom plugin settings.
After copying the database and themes/plugins from a live site to develop on locally, all the pages plugins and data appear to work fine, apart from any that rely on settings. 

The settings appear empty even though there is data in the database. 
Entering any arbitrary data then clicking save will enable it. Refreshing the page shows that arbitrary data gone and the data from the database been displayed correctly as intended, due to it reading the first entry as the arbitrary data is given a new id.
Further changes to the settings and subsequent saves will save to the correct database entry and affect the data.

Its an odd little bug during an install with pre-existing data.

**Comment by daftspunk** [comment]
The settings data is usually cached pretty heavily. Have you noticed if clearing the cache (`php artisan cache:clear`) has any effect?
