### ISSUE TITLE
Fix inconsistency in popup.js API

### ISSUE THREAD

**Issue by jBOKA** [octobercms/october#1685]
In the Docs it says, one can use an additional attribute
`data-extra-data="file_id: 1"`
see https://github.com/octobercms/october/blob/3b4ee3340ea3afd932e6bf5e3e779c4ffaaa0df2/modules/system/assets/ui/docs/popup.md#L111
to submit additional data to the popup request handler.
In my Browser console, the AJAX post looks like this is not parsed correctly (see screenshot).
I now just used the usual `data-request-data` which I can grab with the Input Facade.
Is this just a mistake in the Docs?

![AJAX Post data](https://cloud.githubusercontent.com/assets/8607110/12216600/d74cbaf0-b6e7-11e5-8909-119b7ffdf4ee.JPG)

**Comment by daftspunk** [comment]
Using `data-request-data` is preferable, I think data-extra-data needs JS object syntax

```
data-extra-data="{ file_id: 1 }"
```

**Comment by jBOKA** [comment]
I tried that syntax as well, came up with the same result, each character parsed into an array.
Anyway, `data-request-data` works fine.
I just wanted to refer to the docs, which need correction, but I didn't find what was wrong.

**Comment by jofrysutanto** [comment]
I agree that for consistency, `data-request-data` is preferred over `data-extra-data`, popup.md should be updated to reflect.

However it's possible to fix the `data-extra-data` issue by having the same `paramToObj()` made available from `framework.js`. In our attempt to replicate the same popup in the front end, having `data-extra-data` fed through `paramToObj()` fixes the issue found by @jBOKA

**Comment by SaifurRahmanMohsin** [comment]
+1 It would be a good idea to at-least update the doc until this is resolved. I was using `data-extra-data` and wasted 30 minutes trying to figure out why it came out as an array.

**Comment by tschallacka** [comment]
https://octobercms.com/docs/ui/popup needs updating too

**Comment by daftspunk** [comment]
@tschallacka, submit a pull request
