### ISSUE TITLE
Add information about asset combining & minification to docs

### ISSUE THREAD

**Issue by envision** [octobercms/october#1686]
Hi,

I am about to start my first October project soon. I didn't find any information about asset combining and minification from the docs, and barely by googling... Could you please add a section about this to the docs.

For what I come to understand assets can be combined and minified automatically (combining affected by how you are linking to assets, and minification with a config line). Does that include assets that come with plugins?

One of the drawbacks with Wordpress has been that as it's extended with seperate plugins, each plugins add often several new asset links to HTML thus having negative and stacking impact to the website's load times. And it's almost impossible to optimize (by having all those assets combined). How is it with October? And if there is something that could still be done better, are such improvements coming at some point?

**Comment by jwilson8767** [comment]
Please see [the |theme filter docs](https://octobercms.com/docs/markup/filter-theme#combine-css-javascript).

To answer your question directly: assets are not combined or minified automatically. October assumes that assets are to be loaded individually unless you explicitly combine them. If the `cms.enableAssetMinify` config value is true then there is a limited degree of minification that happens on combined assets, however it's still best if you make sure to minify your own assets during your build process.

Managing plugin assets starts to get into a very complex area and will depend on the way each plugin decides to serve their assets. I've seen some that were fully combined and minified, and other that dumped js straight into every page's html.

**Comment by daftspunk** [comment]
The WordPress (WP) example you gave is more of a "dumb" way of injecting assets: When a WP plugin is installed, it blindly injects the JavaScript and StyleSheets it needs on to the page, whether the page uses them or not.

October's solution is "smart" by comparison, plugins provide components that can be used on the front-end. The component will only inject the JS or CSS files if it is actually used on a page. This has significant benefits in general and overcomes the issue with load times. It is also possible to completely override the component markup and combine the assets yourself inside the theme.
