### ISSUE TITLE
Columns definition doesn't handle lang for 'default' option

### ISSUE THREAD

**Issue by MarvinDurot** [octobercms/october#1690]
Hi,

I noticed that when I try to use lang in a list columns definition, it does not work for the 'default' option (specifies the default value for the column if value is empty). When the list is loaded, it only displays the reference to the string in the lang file.

![image](https://cloud.githubusercontent.com/assets/7080301/12229348/2bfdaa68-b847-11e5-9830-3342ae46b2ac.png)

Thanks for reading, I love your job ;)

**Comment by daftspunk** [comment]
Column values, unlike column headers, are not usually translated by default. You would need to specify a column option like this:

```
type: partial
path: translated_column
```

Then create a partial called `_translated_column.htm` with the content inside

```
<?= trans($value) ?>
```
