### ISSUE TITLE
Sharpening of thumbs

### ISSUE THREAD

**Issue by jBOKA** [octobercms/october#1694]
Some of my customers complain about a lack of sharpness with the images. I already switched to displaying the generated thumbs in native solution where possible, but still agree in many cases, that a little more sharpness wouldn't be amiss.
Thus it would be great if one could sharpen generated thumbs.

Since the filenames of generated thumbs includes the usual options, there might be a problem with backwards compatibility. But maybe one could include sharpening as a global config option?

Since the feature could easily be implemented with
```php
imageconvolution ( $image , $matrix , $divisor , $offset )
```
and some parameters it could be put in the Resizer class and only trigger if the app config says so.
I will volunteer for looking for sane default parameters (e.g. radius and strength or just strength), if you guys decide to add this feature in this way or another.

**Comment by daftspunk** [comment]
The resizer is intended for basic image manipulation. If you can make it work with no extra dependencies then it sounds like a good idea to add an option for it. Otherwise it might be possible to build a plugin that  uses a more robust library for thumbnail creation. This could be made possible by implementing the `Macroable` trait on the File model.

**Comment by jBOKA** [comment]
I've had a look into the 3x3 imageconvolution and the sharpening possibilities.

I wrote some lines ( see https://github.com/octobercms/library/pull/171 ) that transform a 0-100 scale of sharpening values to a range of convolution values that make sense. The way I normalized the value, one could easily use any int or float value, but the relevant changes occur from 0 to 100.

Unfortunately, I didn't know how to prepare the Config setting for the sharpening, without creating dependencies within the octobercms/library. I see that even the getThumb and makeThumbLocal would need the global sharpening config value, so I left it this far.

Anyway, setting sharpen to `false` would override the image sharpening, while any other `float` or `int` should do its job in the relevant range of 0 to 100.

Also see attached some sample images, named by the sharpening value (generated by October with the code from the PR):
![000](https://cloud.githubusercontent.com/assets/8607110/12466094/3e16ef24-bfd2-11e5-8a58-e1099169368c.jpg)
![010](https://cloud.githubusercontent.com/assets/8607110/12466095/3e182bfa-bfd2-11e5-8445-39d31d85dc87.jpg)
![020](https://cloud.githubusercontent.com/assets/8607110/12466097/3e1e6ec0-bfd2-11e5-8c1f-d6b2a99e07de.jpg)
![030](https://cloud.githubusercontent.com/assets/8607110/12466099/3e1fddb4-bfd2-11e5-8b5f-cec17a3094da.jpg)
![040](https://cloud.githubusercontent.com/assets/8607110/12466098/3e1f4d22-bfd2-11e5-97bd-7a96d0616d4b.jpg)
![050](https://cloud.githubusercontent.com/assets/8607110/12466096/3e1ccab6-bfd2-11e5-9270-d49b0d6d97a6.jpg)
![060](https://cloud.githubusercontent.com/assets/8607110/12466100/3e2c1d2c-bfd2-11e5-81a9-e7e19a7e3751.jpg)
![070](https://cloud.githubusercontent.com/assets/8607110/12466101/3e31892e-bfd2-11e5-9393-ab544eec9fe2.jpg)
![080](https://cloud.githubusercontent.com/assets/8607110/12466102/3e356594-bfd2-11e5-8a6f-7487286a740c.jpg)
![090](https://cloud.githubusercontent.com/assets/8607110/12466104/3e397684-bfd2-11e5-938c-b25bb3acddbf.jpg)
![100](https://cloud.githubusercontent.com/assets/8607110/12466103/3e3925da-bfd2-11e5-9835-5ac2a6b59469.jpg)

**Comment by jBOKA** [comment]
My prepared config block:
```php
    /*
    |--------------------------------------------------------------------------
    | Thumb sharpening
    |--------------------------------------------------------------------------
    |
    | The sharpening value for thumbs generated for file attachments using the
    | getThumb() method. This option can be set to false for no sharpening
    | or to values from 0 to 100, with 100 being the highest sharpness.
    |
    */

    'thumb_sharpening' => false,
```

**Comment by hybridvision** [comment]
I think this could be a really useful feature to add and it's safe enough to generalise the setting for images that have been resized - they always benefit from a bit of sharpening afterwards.

Thanks for your work jBOKA, I hope this can be included :)

**Comment by jBOKA** [comment]
I ran into some limit memory issues. I will have another look at alternatives or check my code again. I will let you know, when I find the time.

**Comment by daftspunk** [comment]
This is implemented in `stable` branch and will be available soon.

You can just pass a sharpen option to `getThumb`, eg:

```
$user->avatar->getThumb(100, 100, ['sharpen' => 100]);
```

**Comment by jBOKA** [comment]
Thanks a lot! The only thing to keep in mind with the current solution would be, that switching between different sharpening values doesn't really work, since the sharpening is not reflected in the thumb's filename.
Therefore if an unsharpened thumb has been generated once, no new thumb would be generated if one changes the sharpening value, right?

**Comment by daftspunk** [comment]
In the real world, would you seriously need to have 2 different sharpness settings for the same image dimensions and configuration? I can't think of a story where this would be the case.

**Comment by hybridvision** [comment]
I think the point is more about regenerating images when you update your sharpening settings. In the real world you might have the sharpening value tied to a configuration variable and when you update that, you'd want the images using that setting to be regenerated...

What would be the best approach to this? Clearing the cached images and letting them regenerate? I guess in reality it should be something that doesn't change often, if at all, once set.

**Comment by daftspunk** [comment]
Ah true. This might need to apply to the `quality` setting also. There is the `october:util purge thumbs` command, but this would be pretty cumbersome I imagine for the purpose of tweaking the settings.

**Comment by jBOKA** [comment]
@hybridvision That's exactly what I meant. And yes, same holds for quality. I was just thinking about backwards compatibility.

**Comment by jBOKA** [comment]
There is a wrong variable definition, I opened a PR to fix.
https://github.com/octobercms/library/pull/200
