### ISSUE TITLE
Add support for regular expressions in URLs

### ISSUE THREAD

**Issue by the-foreigner** [octobercms/october#1695]
Currently the URLs are restricted to a specific format:

```Invalid URL format. The URL should start with the forward slash symbol and can contain digits, Latin letters and the following symbols: ._-[]:?|/+*^```

I would like this to be a bit more flexible. For example I wish to have 2 URLs matching a single page. This could be done easily with regex or I would like to use different character set than Latin.

How feasible is this enhancement?

**Comment by daftspunk** [comment]
Can you provide an example of the URL you are trying to use?
