### ISSUE TITLE
Repeater array keys don't get reindexed when removing first element

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1696]
When you have a repeater, they get automatically assigned integer keys, but when you remove the first element of an existing set, the array keys don't get reindexed. This makes array keys in the resulting JSON harder to iterate and check for resulting values.

**Comment by daftspunk** [comment]
Think of them as auto incrementing identifiers, rather than indexes. If you need an incrementing index use `{{ loop.index }}` instead

**Comment by daftspunk** [comment]
This should be addressed now as part of #2772, the data is no longer stored as an object with indexes but as a pure array. Hopefully it will clear up some confusion here.
