### ISSUE TITLE
Class 'Barryvdh\Elfinder\ElfinderServiceProvider' not found

### ISSUE THREAD

**Issue by SunnyTeater** [octobercms/october#1699]
Hello,

i try logging in into my october administrator page and i got this error: 

Class 'Barryvdh\Elfinder\ElfinderServiceProvider' not found
/var/www/sunnyteater.de/vendor/laravel/framework/src/Illuminate/Foundation/Application.php line 541

TYPE

Undefined

EXCEPTION

Symfony\Component\Debug\Exception\FatalErrorException

533     *
536     * @param  string  $provider
537     * @return \Illuminate\Support\ServiceProvider
538     */
539     public function resolveProviderClass($provider)
540    {
541        return new $provider($this);
542    }
543  
544    /**
545     * Mark the given provider as registered.
546     *
547     * @param  \Illuminate\Support\ServiceProvider

 later my webpage was down with that error too..

**Comment by MatissJanis** [comment]
It may be that a broken plugin that you recelty installed is causing this problem. Can you recall what was the last thing you installed?

**Comment by SunnyTeater** [comment]
i updated some plugins like  WYSIWYG EDITORS, Twitter, YouTube and CAPTCHA.

these were previously disabled. But after I looked for updates they has been reactivated.

You mean it will help when i remove some plugins and check it then ?

**Comment by hybridvision** [comment]
Did disabling the plugins fix it? I think it might be the WYSIWYG editors plugin - I remember having a similar error with that plugin in the past. Try removing it completely and see if that fixes it.

**Comment by SunnyTeater** [comment]
@hybridvision the Problem is, it was disabled. I stop my work for ca. 1 hour and wanted to sign in again. And then i saw this error on ervery page.

The only option would be to erase the program via Linux, but i don´t know the command.

**Comment by SunnyTeater** [comment]
To delete the plugin -wysiwygeditors helped.
