### ISSUE TITLE
Component not rendering in page

### ISSUE THREAD

**Issue by kmcluckie** [octobercms/october#1706]
HI there,

I'm the author of the Instagram Toolkit plugin, and I had a user complain a while ago about the components not being injected into the page at all (https://octobercms.com/plugin/metaphorceps-instagram/current-version-is-broken). I couldn't replicate it at the time, but I have just done a new install of OctoberCMS and installed my plugin and am finding the same behaviour.

I can confirm that the plugin onRun() is executing and retrieving valid data from the Instagram API, but the components just do not show on the page.

Any ideas?

**Comment by daftspunk** [comment]
Could it be something to do with the fact that the [component folders](https://bitbucket.org/kyle_m/october-instagram-plugin/src/15904cb8f47bad7451c450f44e053f65362c85d3/components/?at=master) are using uppercase characters?

**Comment by kmcluckie** [comment]
Brilliant! It had worked for so long I was absolutely stumped. Thank you.
