### ISSUE TITLE
Partials not working in deeper nested directories

### ISSUE THREAD

**Issue by pedzed** [octobercms/october#1707]
* `/partials/header.htm` works.
* `/partials/layout/header.htm` works.
* `/partials/layouts/main/header.htm` fails.

It's the exact same file, but it doesn't work if it is nested two deep. It would be nice to be able to nest deeper.

**Comment by jwilson8767** [comment]
Confirmed.

**Comment by jwilson8767** [comment]
Looks like this is [by design](https://github.com/octobercms/october/blob/master/modules/cms/classes/CmsObject.php#L191).

**Comment by daftspunk** [comment]
[It sure is](http://octobercms.com/docs/cms/themes#subdirectories), try using 

* `/partials/header.htm` 
* `/partials/layout/header.htm` 
* `/partials/layout-main/header.htm`

**Comment by pedzed** [comment]
@daftspunk Personally, it bugs me quite a lot. I might also want `/partials/pages/about/faq.htm` for example.

Is there any reason why the limit is set to two?

**Comment by pedzed** [comment]
This issue applies to content blocks as well.

**Comment by jonpxpx** [comment]
I personally think it's best to keep it limited to two, keeps things more organised IMO. Creating umpteen number of levels just gets messy.

**Comment by daftspunk** [comment]
Supporting more than one level of nesting creates a more complicated user interface in the back-end area. It is quite easy to overcome using a simple convention like `/partials/pages-about/faq.htm` and this ends up being far more manageable in the long run. The plugin class and controller directories in October use the same "single level" approach for the same reason, and of course simplicity.

**Comment by pedzed** [comment]
> I personally think it's best to keep it limited to two, keeps things more organised IMO. Creating umpteen number of levels just gets messy.

To each his own, right? If this won't possible, then I guess OctoberCMS is just not for big websites. Being able to nest deeper is especially nice if you are migrating from another CMS, and want to keep the file structure the same. The primary reason I use October is because of its beauty and the powerful backend. This limitation puts me down however.

> Supporting more than one level of nesting creates a more complicated user interface in the back-end area. It is quite easy to overcome using a simple convention like /partials/pages-about/faq.htm and this ends up being far more manageable in the long run. The plugin class and controller directories in October use the same "single level" approach for the same reason, and of course simplicity.

Alright, I have a suggestion which may make us both satisfied. Make the option to nest at least one deeper than we currently can nest. If it gets deeper than that, then you should display a notice, because as of now, it's just unexpected behavior. A bug in the design I would say.

**Comment by daftspunk** [comment]
The October website is quite large and the most it has is 15 partial folders, it could easily expand to 2-3 times this size and still be manageable. It really depends on how well the theme is organised and it requires some level of discipline.

Thanks for the suggestion, we may reconsider this in the future. It would require some modification to the user interface. For now we are focusing on the stable release.

**Comment by pedzed** [comment]
I just realized that there is no problem with this with the assets. And it works quite good, so I don't really see the issue to be honest. @daftspunk What do you think?

**Comment by pedzed** [comment]
bump

**Comment by pedzed** [comment]
I just realized that there is no problem with this regarding the assets. And it works quite good. Actually, I find it even better than the one for the partials and content blocks. There is an unnecessary inconsistency here.

@daftspunk What do you think?

**Comment by PubliAlex** [comment]
Issue was created some times ago but wanted to add my +1 for more level of nested folder support.

Actually, you have some themes that heavily use partials (shopaholic,  mall) that use more than 2 levels of directory to keep things organized. They just decided to ignore october limitation cause it's too frustrating.

I'm quite surprised by the october answer about that. "Everything should make us smile" remember :). With that logic, you could also apply that limitation to the assets theme. Well organized themers should be able to deal with that..... no.

In addition, we already have the behaviors we want on assets theme. Just apply that navigation script to the other parts of CMS tab. If you really want to keep simplicity or legacy behaviors, add an option under backend preferences to unleash the power of deep nesting.

I don't even understand how this is debatable.

Best regards,

**Comment by RomainMazB** [comment]
Hi @publixalex ,
You're saying it "it's not working" and then "shopaholic/mall heavily use partials".

So I just looked the demo theme of shopaholic and they use nested subdirectory as well. Can't look further for now but does it use a trick do to so? Or maybe this issue doesn't belong anymore?

**Comment by bennothommo** [comment]
There is already a [proposed enhancement](https://github.com/octobercms/october/issues/5093) to increase the amount of levels, but the UI itself only supports one level of subdirectories at the moment, as far as I know, so any implementation is going to need to factor that in.

It's low priority though, given there is a valid workaround for the moment. If you would like us to prioritise this, please feel free to [put a bounty](https://www.bountysource.com/issues/91589619-allow-multiple-subdirectory-levels-in-filedatasource-select-method) on it.

**Comment by PubliAlex** [comment]
@RomainMazB the shopaholic demo theme may not use deep partial nesting, but the bootstrap one yes. I think they just don't use backend to edit partials (they can't) and use IDE instead.

@bennothommo Thank you for the answer. I will take a look for the bounty.
