### ISSUE TITLE
Markdown editor translation

### ISSUE THREAD

**Issue by adrenth** [octobercms/october#1709]
I'm trying to get OctoberCMS fully translated to Dutch. Everything works pretty well, but there's one thing I can't get to work. And that is translating the Markdown Editor.

I've provided the Dutch translation in `/modules/system/lang/nl/client.php` and executed the command `php artisan october:util compile lang`. My PR is already merged (see https://github.com/octobercms/october/pull/1589), but nothing happens to the buttons 'Bold', 'Italic', etc.

The buttons added by the MediaManager.redactor plugin are getting translated fine: "mediamanager.insert_link", "mediamanager.insert_image", "mediamanager.insert_video", "mediamanager.insert_audio"

**Comment by joris-vdlp** [comment]
I think this issue can be closed. With the new editor in place it looks fine now. Stil missing some dutch translations, but thats no showstopper :)

**Comment by daftspunk** [comment]
Thanks for the update!
