### ISSUE TITLE
Limiting a repeater for a plugin

### ISSUE THREAD

**Issue by Benpxpx** [octobercms/october#1710]
I'm looking to limit how many repeaters are used in a plugin setting.
My use case is I want people to put in the days of the week but I obviously don't want more then 7 to be inputted by the user.

Any recommendations on how best to tackle this?

/cc @jonpxpx

**Comment by daftspunk** [comment]
An option called `maxItems` could be introduced to handle this, hiding the "Add" button when the limit is reached.

**Comment by Benpxpx** [comment]
That would be perfect, it's not mission critical so to speak, but would be nice to see down the road.

**Comment by arzola** [comment]
I already did this thing i can send a PR but i can't find how to test it, do you have an example of a Testing a FormWidget  to add my assertions ? related #2649

**Comment by LukeTowers** [comment]
Duplicate of #2649, Fixed by #2723
