### ISSUE TITLE
Media Manager reports success after upload error

### ISSUE THREAD

**Issue by fresswolf** [octobercms/october#1712]
The default values for upload_max_filesize and/or post_max_size in php.ini are 2MB, which today is already exceeded with any mobile phone image.

When trying to upload files exceeding that limit, Media Manager doesn't handle the error properly. Instead, it reports a successful upload while no new file appears

**Comment by daftspunk** [comment]
Hmmm, I thought we fixed this already in #1518.

**Comment by marfatabdullahi** [comment]
I'm also experiencing this issue.

**Comment by daftspunk** [comment]
##### This bug has been fixed via live stream:
:movie_camera: https://youtu.be/XHmLnLgJNWo
