### ISSUE TITLE
Installation plugins directly from github

### ISSUE THREAD

**Issue by AWMEdev** [octobercms/october#1717]
it has been considered to make installation plugins directly from github? this would help us developers, wanted to make a plugin to do this task, where I can start?
I could use the update classes plugins and themes for this?

**Comment by LucasZdv** [comment]
october/modules/system/classes/UpdateManager.php
it can be done using this class?

**Comment by jwilson8767** [comment]
`composer require vendor/project` then `php artisan plugin:refresh Vendor.Plugin` should do it.

**Comment by LucasZdv** [comment]
jwilson8767  I tried this but it does not work that way.

**Comment by daftspunk** [comment]
We may consider this in the future.

**Comment by daftspunk** [comment]
For now you could create a plugin that does it, or like @jwilson8767 says install via composer (this would require plugin authors to actually publish their plugins with packagist).
