### ISSUE TITLE
|media filter should be registered globally

### ISSUE THREAD

**Issue by chesterx** [octobercms/october#1718]
Hello,

There is a problem when i use twig media filter in "mail layout".

```
{{ 'mailing/welcome/mail_03.jpg'|media }}
```

This throws 

```
Unknown "media" filter in "__string_template__a79d44d3a173d7b33003f53b35f263f2420c7c2675d82bb4ca3444d962d66894" at line 36.
```

**Comment by Beaudinn** [comment]
Same here.

**Comment by daftspunk** [comment]
The filter is considered part of the CMS Twig engine, calling `Cms\Controller::mediaUrl` for the result. We would need to register this as part of System twig in `System\ServiceProvider::registerMarkupTags` to make it available in both instances.

**Comment by LukeTowers** [comment]
@daftspunk Bumping this for further consideration to move the MediaManager widget to the system module. We should be able to do that but leave a class within the cms module that extends the new location without breaking backwards compatibility.

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/08f9cd844831f9b6088301fbd08944b02809f676
