### ISSUE TITLE
Definetely folder permissions and owner

### ISSUE THREAD

**Issue by queengab** [octobercms/october#1725]
Hi to all,

i'm struggling since 2 days to give right permissions and ownership of my october installation.
I managed to install plugins after give 777 on plugins/storage/thems folder but i know it's unsecure.

Plus actually apache storage/vendor/module have www-data:www-data ownership while other folders have myuser:mygroup. My user belong to www-data group and www-data user belong to mygroup.

Now october when do stuff impersonate www-data or general user?

Which are the right permissions, that can permit mysel to update plugins on a production server?

This is my config on a ipothtycal stage server, is it correct???

-rw-r--r--  1 myuser  mygroup   artisan
drwxr-xr-x  2 myuser  mygroup   bootstrap
-rw-r--r--  1 myuser  mygroup   CHANGELOG.md
-rw-r--r--  1 myuser  mygroup   composer.json
-rw-r--r--  1 myuser  mygroup   composer.lock
drwxr-xr-x  4 myuser  mygroup   config
-rw-r--r--  1 myuser  mygroup   CONTRIBUTING.md
-rw-r--r--  1 myuser  mygroup   .editorconfig
drwxr-xr-x  8 myuser  mygroup   .git
-rw-r--r--  1 myuser  mygroup   .gitattributes
-rw-r--r--  1 myuser  mygroup   .gitignore
-rw-r--r--  1 myuser  mygroup   .htaccess
-rw-r--r--  1 myuser  mygroup   index.php
drwxrwxrwx  2 myuser  mygroup   log
drwxrwxr-x  5 www-data www-data modules
-rw-r--r--  1 myuser  mygroup   phpunit.xml
drwxrwxrwx  9 myuser  mygroup   plugins
-rw-r--r--  1 myuser  mygroup   README.md
-rw-r--r--  1 myuser  mygroup   server.php
drwxrwxrwx  7 www-data www-data storage
drwxr-xr-x  5 myuser  mygroup   tests
drwxrwxrwx  4 myuser  mygroup   themes
-rw-r--r--  1 myuser  mygroup   .travis.yml
drwxrwxr-x 34 www-data www-data  vendor

**Comment by hybridvision** [comment]
A lot depends on your server setup but generally speaking, the web server's process should run as your user ID or be in a group that has permission to access your files. I'm not an expert on such matters but it seems like it should work from what you say... Did you try 755 permissions also?

If you want to see which user the PHP process is running as, you can try putting this in a PHP file and visiting it from the browser:

`<?php print_r(posix_getpwuid(posix_geteuid())); ?>`

The name in the array will be the username of the process, which I'm guessing will be www-data.

Is this your own server or are you with a hosting company? You should be very cautious with security if it is your own server and if it is with a company, try asking their support desk. In my experience, some hosts are really painful to work with while others make it very easy (eg. WebFaction).

You might also find this link helpful: https://serversforhackers.com/

Good luck :)

PS: This isn't really an OctoberCMS issue but rather a configuration problem with your server so it doesn't warrant a ticket. You can also try the [forums](http://octobercms.com/forum) on the OctoberCMS site.

**Comment by queengab** [comment]
Hi,

thanks for your response. I'm trying to find, plus or minus, a standard way that works on various server. Now I'm doing some tests on my rasberry pi with debian but the aim is to manage a server of my own and manage all. The secuirty is the first thing i think...everyday :) So this the cause for this post. 

Thanks for yours advice i want to find a standard config for debian-like server. In centos environment disable se-linux and find the good way. 

Bye, i'll try others configuration. 

Gabriele

Ps: i think git-hub issues are more professionals than october forum so i post

**Comment by hybridvision** [comment]
Hi Gabriele,

It's great that you are experimenting and learning about security but I'm not sure I understand the connection to OctoberCMS - yes, you need to have the correct permissions for it to work securely but it would be exactly the same if you were installing WordPress, Drupal or some other CMS... This is a very general problem and not one that directly relates to OctoberCMS.

While GitHub is full of knowledgeable people, it's considered bad etiquette to open unrelated / general tickets. The developers are already very busy and are doing this amazing work for free so we don't want to overload them with unrelated tickets. Generally your ticket will be closed and you'll be told to ask elsewhere. Have you tried StackOverflow? Or there's even an IRC channel for October: https://octobercms.com/chat

Regarding PHP running as www-data, that sounds like a standard setup and the best solution depends completely on what you are doing - for example if you have other users or applications sharing the same server, you want to keep them as isolated as possible from each other so if one site gets hacked, it won't compromise the rest. Check this video out specifically: https://serversforhackers.com/video/linux-acls

Cheers,

Stephen

**Comment by queengab** [comment]
Thanks Hybrid,

excuse me for the OT and thanks for the link! I really appreciate your suggestions.
I will write on git only for developing purpose only.
Bye!

**Comment by hybridvision** [comment]
You're welcome Gabriele :) I hope you find what you need!

Since we're finished here now, you should close this ticket.

Ciao!
