### ISSUE TITLE
Double popup when clicking list widget row with onclick handler

### ISSUE THREAD

**Issue by jofrysutanto** [octobercms/october#1730]
The library `list.rowlink.js` does not seem to prevent the actual `<a onclick="">` from being fired, causing it to be triggered twice.

***Replicate steps***
- Create backend controller, with relation behaviour.
- The relation configuration define both manage.list and manage.form
- Clicking on the name of the first column (exactly on the text), causing the double popup to appear with the form to manage the related item.

**Comment by daftspunk** [comment]
I was unable to replicate this.

1. Install test plugin https://github.com/daftspunk/oc-test-plugin
1. Navigate to backend/october/test/posts/update/1
1. Click the `1` or `2` text in the ID column of Comments
1. A single popup is opened

**Comment by jofrysutanto** [comment]
Unable to replicate this on OC Test Plugin as well: to fit our case I changed the first column of Comments to ***partial***, and the framework still produce output as expected (no double popups).

By comparing produced first column's `<td></td>`, I can see a big difference which I highly suspect is the main cause:
- On test plugin the partial is wrapped inside `<a></a>` with AJAX handler, set to `display: none`, and also ***duplicated*** (on the same level as `<a></a>`.
- On our site the partial is wrapped inside `<a></a>` with AJAX handler, however is not set to `display:none` and there is no duplicated column value.

Manual manipulation of live HTML document via inspector fix the issue (no more double popups when clicking on the first column). A bit unsure what this means, but suspect it might be something from our side.

**Comment by daftspunk** [comment]
Have a look at the `list.rowlink.js` jQuery plugin that is used to handle these events. There may be something interesting happening in here.

modules\system\assets\ui\js\list.rowlink.js
