### ISSUE TITLE
Richeditor removes all text that was inserted after pasting (ctrl+v)

### ISSUE THREAD

**Issue by fresswolf** [octobercms/october#1739]
To reproduce:

1. Open a form with a richeditor

2.  Type some text into it

3. Copy this text: blabla. And paste it into the document

4. Don't save the document yet (this would be the workaround until this gets fixed, saving immediately after pasting anything)

5. Type in more text after the pasted text

6. Save

7. Refresh the form

8. All text after the pasted text ("blabla") is gone!

I'm using the latest build and tested it on a Mac with all sorts of browsers

Edit: After pasting in the text and writing more text, you could also click the HTML button twice to see how the text disappears

**Comment by daftspunk** [comment]
Very strange!

**Comment by daftspunk** [comment]
This was retested using the implementation in #2005 and could no longer be replicated. If the issue still exists, please log a new issue for it.
