### ISSUE TITLE
Pages not saving

### ISSUE THREAD

**Issue by Pyroglyph** [octobercms/october#1742]
After my third fresh install, I'm starting to get a bit annoyed now. I'm using the default backend settings and the demo theme. Whenever I edit and try and save a layout, page, or content file using October's editor, the saving spinner appears for a while and then goes back to the save button without actually saving the page. As you may guess this is extremely irritating. I've also looked online and nobody else seems to be having the same problem. Similar, but not the same.

**Comment by daftspunk** [comment]
Which hosting provider are you with? Some treat posting html as a security
threat and block the request. GoDaddy comes to mind.

**Comment by Pyroglyph** [comment]
I'm with X10Hosting. The funny thing is, I managed to get a page to save one time just after my 3rd reinstall. But then it went back to not saving.

**Comment by Pyroglyph** [comment]
Also, in the event logs, an error keeps coming up saying 'Class name is not registered for the component "gaCode". Check the component plugin.'

**Comment by D3m1urg0** [comment]
i have same issue with the same host

but i managed to understand tath the bug only occours when html tags are inside the editor..

if you try to save plain markdown or text it will save...

**Comment by daftspunk** [comment]
Please contact your hosting provide to ask for the security settings to be loosened to allow posting of HTML to the server.

For example: Posting `<div></div>` is returning an empty 200 response.

This is unacceptable for hosting modern web applications.
