### ISSUE TITLE
Rich Text Editor options

### ISSUE THREAD

**Issue by MarvinDurot** [octobercms/october#1743]
Hi,

The default rich text editor is very great in backend, but it have not enough option available.
It would be aswome if there were options to choose what is displayed in the toolbar.

![image](https://cloud.githubusercontent.com/assets/7080301/12712232/3a28a792-c8c7-11e5-8194-84a5b2b98dc9.png)

For now, I must edit your rich text editor js script to disable media manager buttons.

I see there are 5 options when redactor script is loaded : fullscreen, figure, table, pagelinks and mediamanager. It could be easier if we can modify them directly in the form yaml configuration file.

Thanks for reading, 
I love your work !

**Comment by jwilson8767** [comment]
This is already on the General Todo list. #858 

That said, I plan to address several issues with RichEditor this week. What sort of buttons would you like to display?

**Comment by daftspunk** [comment]
Waiting on #1744

**Comment by daftspunk** [comment]
After #2005, it is now possible to define the toolbar buttons in the form field definition. See Backend > Forms docs for more info.

Option | Description
------------- | -------------
**toolbarButtons** | which buttons to show on the editor toolbar.

The available toolbar buttons are:

    fullscreen, bold, italic, underline, strikeThrough, subscript, superscript, fontFamily, fontSize, |, color, emoticons, inlineStyle, paragraphStyle, |, paragraphFormat, align, formatOL, formatUL, outdent, indent, quote, insertHR, -, insertLink, insertImage, insertVideo, insertAudio, insertFile, insertTable, undo, redo, clearFormatting, selectAll, html

> **Note**: `|` will insert a vertical separator line in the toolbar and `-` a horizontal one.

**Comment by LukeTowers** [comment]
Support for changing the global default toolbar buttons has been added in https://github.com/octobercms/october/commit/dfcf324d008b6c20122a20a2b26b43a22111583f by @Harti

**Comment by goeroe** [comment]
The docs mention you can use the 'inlineStyle' button but can't seem to figure out how to config these styles...

Defining them as mentioned at https://www.froala.com/wysiwyg-editor/examples/inline-styles doesn't seem to work in this case.

```
<script>
        $(function() {
            $('div.field-richeditor').froalaEditor({
                inlineStyles: {
                    'Big Red': 'font-size: 20px; color: red;',
                    'Small Blue': 'font-size: 14px; color: blue;'
                }            
            })
        });
    
    </script>
```

**Comment by LukeTowers** [comment]
@goeroe you would set that up in the editor settings: http://example.com/backend/system/settings/update/october/backend/editor. Alternatively, you can access the Froala editor directly by extending the DEFAULTS object in JS:
```javascript
+function ($) { "use strict";
    $(document).render(function() {
        if ($.FroalaEditor) {
            $.FroalaEditor.DEFAULTS = $.extend($.FroalaEditor.DEFAULTS, {
                inlineStyles: {
                    'Big Red': 'font-size: 20px; color: red;',
                    'Small Blue': 'font-size: 14px; color: blue;'
                }
            });
        }        
    })
}(window.jQuery);
```

**Comment by richardwo** [comment]
@LukeTowers I'd like to enable the pastePlain option on Froala to remove formatting - where would JS like your example need to go in an October site?

**Comment by LukeTowers** [comment]
put it in a JS file that your plugin extends the Backend\Classes\Controller class to add the script file.

**Comment by LukeTowers** [comment]
Example as asked for via email:
JS File (`plugins/myauthor/myplugin/assets/js/froala.js`)
```js
+function ($) { "use strict";
    $(document).render(function() {
        if ($.FroalaEditor) {
            $.FroalaEditor.DEFAULTS = $.extend($.FroalaEditor.DEFAULTS, {
                inlineStyles: {
                    'Big Red': 'font-size: 20px; color: red;',
                    'Small Blue': 'font-size: 14px; color: blue;'
                }
            });
        }        
    })
}(window.jQuery);
```
Extending the backend controller to include your JS file on every backend page (Note, you should be more selective what pages you include it on, i.e. if you just want to add it to your plugin, then extend only your plugin's controllers)
Plugin.php (`plugins/myauthor/myplugin/plugin.php`):
```php
public function boot()
{
    \Backend\Classes\Controller::extend(function($controller) {
        $controller->addJs('/plugins/myauthor/myplugin/assets/js/froala.js');
    });
}
```

**Comment by arashonline** [comment]
Hi, Is there any way to make rich Text Editor to use Html5 tag format for audio and video now it is like:
`<figure class="" data-label="Prerequisites.mp4" data-video="/storage/app/media/Prerequisites.mp4">&nbsp;</figure>
`
it should be like:
`<video width="320" height="240" controls>
  <source src="/storage/app/media/Prerequisites.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video>`

**Comment by LukeTowers** [comment]
@arashonline please don't hijack old unrelated issues, make new issues instead or ask for help on Slack.

**Comment by climao** [comment]
@LukeTowers I used your suggestion to use a JS file in my plugin but to configure tableStyles, instead of inlineStyles. 

Unfortunately that didn't work. Any ideas  why?
