### ISSUE TITLE
Compiled Class File path not corrected after update

### ISSUE THREAD

**Issue by ametad** [octobercms/october#1746]
Continuing #1608 

How is this fix being deployed to existing projects? I ask this because I have still the old code in my october project, like so:

bootstrap/autoload.php
```php
...
$compiledPath = __DIR__.'/../vendor/compiled.php';
...
```

This is after (a few) updates of this October project, with
* artisan october:update
* composer update
* update through the backend application

I expected the $compiledPath to be changed to the storage location, but it has not. Am I doing something wrong?

**Comment by krisawzm** [comment]
I believe the `bootstrap` directory does not get updated when running the `artisan october:update` command. Which means you'll have to change the path manually.

**Comment by daftspunk** [comment]
Correct, you will need to update this location manually to:

```
$compiledPath = __DIR__.'/../storage/framework/compiled.php';
```
