### ISSUE TITLE
Selenium tests doesn't works

### ISSUE THREAD

**Issue by vojtasvoboda** [octobercms/october#1751]
I tried master, develop and also stable branch - latest commit 23da833. Just pull repository, create selenium.php file and then:

```
composer install
php artisan october:up
php vendor/bin/phpunit tests/unit
php artisan serve
```

all good, site runs, backend with login works. Than:

```
selenium-server -p 4444
```

Prints:

```
16:49:01.679 INFO - Launching a standalone server
16:49:01.736 INFO - Java: Oracle Corporation 25.66-b17
16:49:01.736 INFO - OS: Mac OS X 10.11.3 x86_64
16:49:01.753 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
```

Console at `http://127.0.0.1:4444/wd/hub/static/resource/hub.html` works well. But:

```
php vendor/bin/phpunit tests/functional
```

Render:

```
PHP Fatal error:  Class 'PHPUnit_Extensions_SeleniumTestCase' not found in /tests/UiTestCase.php on line 4
```

When I modified file UiTestCase and rewrite extending class to `PHPUnit_Extensions_Selenium2TestCase`, then reinstall Selenium to latest version (2.48.2), then in `selenium.php` rewrite `*firefox` to `firefox` I got:

```
BadMethodCallException: The command 'open' is not existent or not supported yet.
```

Looks like functional tests are not compatible with Selenium 2 but also don't works with Selenium 1.

Any idea?

**Comment by daftspunk** [comment]
Probably because composer is requesting Selenium v2.0 when it should be asking for v1.0

**Comment by jakesyl** [comment]
Hey, any fix for this issue?
