### ISSUE TITLE
`relationRefresh` does not work in custom controller actions

### ISSUE THREAD

**Issue by tobias-kuendig** [octobercms/october#1752]
I've got a custom relation toolbar button that makes a call to `onRelationButtonApprove`:

```html
<button ... data-request="onRelationButtonApprove">
     Approve selected
</button>
```

In my controller action I return

```php
public function update_onRelationButtonApprove()
{
    // ... do stuff

    return $this->relationRefresh('bookings');
}
```

Unfortunately, this returns the following error (translated): `Relation behavior used in :class does not have a model defined`. The built-in `onRelationButtonDelete` works like a charm.

As stated by [jirikubak](https://octobercms.com/forum/user/jirikubak) in [this forum thread](https://octobercms.com/forum/post/problem-with-relationrefresh)  reinitialising the relationship in the controller fixes this problem:

```php
public function update_onRelationButtonApprove()
{
    // ... do stuff

    $model = \Acme\Plugin\Models\Model::find(post('model_id'));
    $this->initForm($model);
    $this->initRelation($model, 'bookings');

    // Works!
    return $this->relationRefresh('bookings');
}
```

Am I using the `relationRefresh` method wrong or is this a valid bug?

**Comment by daftspunk** [comment]
You do need to tell the `RelationController` about the model and relation definition. So calling `initRelation` is necessary, the same is true for `FormController` although I'm not sure you need to be calling both (`initForm` and `initRelation`).

**Comment by tobias-kuendig** [comment]
It looks like both calls are necessary in my case since I use `$this->formGetModel()->id` in the partial to pass the model's id to the controller. Without the `initForm` call `formGetModel()` returns null.

```html
<button onclick="$(this).data('request-data', {
    checked: $('#longId .control-list').listWidget('getChecked'),
    model_id: '<?= $this->formGetModel()->id ?>'
})">
```

With both calls everything is working as expected.

Thanks!

**Comment by SaifurRahmanMohsin** [comment]
Isn't this more of a workaround than a fix? Why does the system think the relation isn't initialized to begin with when it clearly is by the controller that implements the relation behaviour?

**Comment by LukeTowers** [comment]
Because it's the responsibility of the FormController to initialize the RelationController (see https://github.com/octobercms/october/blob/master/modules/backend/behaviors/FormController.php#L165-L170) however `initForm()` is called by the FormController behaviour's AJAX handlers, so you need to make sure you also call `initForm()` in your custom AJAX handlers. 

As a note @tobias-kuendig, @daftspunk meant you should only have to call `initForm()`, you shouldn't need to call `initRelation()` too.
