### ISSUE TITLE
Table users doesn't exist

### ISSUE THREAD

**Issue by kienle83** [octobercms/october#1759]
Hi daftspunk,

i try to plugin:refresh rainlab.user but got error: "Base table or view not found: 1146 Table 'october.users' doesn't exist". Before i try to refresh this plugin, I had deleted all related table of plugin in database and then run "php artisan plugin:refresh Rainlab.User".  I always get that error, could you help me? May be should I drop all tables and try to run october:up ???? Or maybe version from table "system_plugin_versions" causes this error?

**Comment by daftspunk** [comment]
I assume this is caused by the `UsersAddDeletedAt` script. Comment out the code inside the `down()` method and try again:

    public function down()
    {
        // Schema::table('users', function($table)
        // {
        //     $table->dropColumn('deleted_at');
        // });
    }
