### ISSUE TITLE
FileUpload widget faillure with belongsTo relationManager

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1760]
![capture](https://cloud.githubusercontent.com/assets/8638425/12885432/2f1eaa14-ce66-11e5-9e99-727e058b15c9.JPG)

When having the fileupload widget via the relation manager in a belongsTo relation ship, when you click on it, you can't modify the image details from the view page. but the menu gets presented to mondify anyways.

**Comment by daftspunk** [comment]
Please set up a test case for this
https://github.com/daftspunk/oc-test-plugin

**Comment by LukeTowers** [comment]
@daftspunk is this still an issue?

**Comment by tschallacka** [comment]
It was me trying to use files in belongsto manner instead of attachone.
Mostly me when I was new to october doing stuff i didn't fully understand.

**Comment by LukeTowers** [comment]
@tschallacka thanks for the update!
