### ISSUE TITLE
Form handling example not working on Index Page 

### ISSUE THREAD

**Issue by Upperfoot** [octobercms/october#1763]
Hello!

I've tried implementing your example on the Index (Demonstration) page for the Default theme, and it looks as though the request name isn't being handled, I followed the instructions below.

[https://octobercms.com/docs/cms/pages#handling-forms](https://octobercms.com/docs/cms/pages#handling-forms)

Cheers

**Comment by daftspunk** [comment]
Have you included the `{% framework %}` tags somewhere in your page or layout? This is necessary for the AJAX framework to operate.

**Comment by Upperfoot** [comment]
@daftspunk Yes it would be included in the default installation of Octobercms, using the demo theme.

**Comment by daftspunk** [comment]
Please paste the entire page file code so we can test it.

**Comment by Upperfoot** [comment]
@daftspunk Seems to be solved by updating to latest commit, closing.
