### ISSUE TITLE
[Bug] Media Manager: Unable to move file to root directory

### ISSUE THREAD

**Issue by DanielHitchen** [octobercms/october#1765]
As title - say you have images in a sub-folder in your media library, if you wanted to move any of the images into the root i.e the top level Library directory (as it appears in the Media plugin), there is currently no option in the dropdown to select that directory. Have tried leaving the dropdown empty & clicking move, but you have to select a destination.

**Comment by daftspunk** [comment]
This sounds like a bug more than a feature request. Confirmed it is not possible to move a file to the root level directory.
