### ISSUE TITLE
Flash Message

### ISSUE THREAD

**Issue by all-for-web** [octobercms/october#1767]
Здравствуйте уважаемые разработчики. В первую очередь хочу Вас поблагодарить за проделанную вами работу.

После обновления на версию 314 у меня начались на сайтах Flash сообщения отображаться по 2 раза.

Пример отправки формы на Ajax:
Не заполнил поле, нажал на кнопку отправить, сверху отобразилось сообщение как и должно быть. После этого нажал сверху по навигации на другую подстраницу вылезло опять это же сообщение. После второго раза больше не отображается.

Я обновил за последнее время 3 сайта и на всех 3-х сайта появилась эта ошибка.

**Comment by daftspunk** [comment]
Please submit issues in English.
