### ISSUE TITLE
CMS 'New partial' title doesn't get updated when saving partial

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#1773]
When adding a new partial in CMS, the page title changes to _New partial_ however after saving, it doesn't change to the partial name. Flicking CMS tabs back and forward between existing and the new partial doesn't fix it.

![screen shot 2016-02-12 at 5 59 34 pm](https://cloud.githubusercontent.com/assets/334808/13001514/6bd45748-d1b2-11e5-869b-fe96ac6f36a1.png)

**Comment by daftspunk** [comment]
How to replicate, from Flynsarmy: 
1. Make any partial
1. Save it
1. Look at your browser title bar

Unable to replicate, the browser title is updated after saving.

**Comment by Flynsarmy** [comment]
I can't replicate anymore either. Guess it's fixed.
