### ISSUE TITLE
List sorting: documentation gap and possible issue

### ISSUE THREAD

**Issue by tillathenun** [octobercms/october#1774]
Firstly, the [documentation](https://octobercms.com/docs/backend/reorder) for sortable records should probably mention that an integer 'sort_order' column is expected in the DB table.

Once I worked out I needed to add that column, I added it to my existing table but sorting the records failed to work as all the rows had sort_order = 0. Once I changed them all to NULL, it worked fine.

Obviously not a very big issue, and I worked it out fairly quickly, but it may trip up people even more newbie than me!

**Comment by daftspunk** [comment]
Is this not covered by the [Sortable documentation](https://octobercms.com/docs/database/traits#sortable)?

Feel free to submit a PR to the docs repo with any suggestions.
