### ISSUE TITLE
A non well formed numeric value encountered when installing using Project ID

### ISSUE THREAD

**Issue by adwidianjaya** [octobercms/october#1776]
I've already set up local server octobercms.localhost and fill the right username, password and db name while installing October CMS. Finally, I use my Project ID from account and project I created. All downloading process was finished, but I got this error message in the end: A non well formed numeric value encountered. Is there any log file october cms provide for this installation? 

![screen shot 2016-02-13 at 13 20 16](https://cloud.githubusercontent.com/assets/5211073/13026284/e96fb97a-d254-11e5-9e8f-cffd3645073d.png)

**Comment by daftspunk** [comment]
> **Note:** A detailed installation log can be found in the `install_files/install.log` file.

**Comment by adwidianjaya** [comment]
Thank you so much @daftspunk . I found the installation log and see this error:

[2016/02/13 06:10:58] Install step: createAdmin
[2016/02/13 06:10:58] Handler error (onInstallStep): A non well formed numeric value encountered
[2016/02/13 06:10:58] Trace log:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'A non well form...', '/Users/adhe/Cod...', 333, Array)
#1 /Users/adhe/Code64/octobercms-experimental/plugins/bedard/debugbar/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php(333): Exception->__construct('Cannot add Mail...', '42S02', Object(Illuminate\Database\QueryException))
#2 /Users/adhe/Code64/octobercms-experimental/plugins/bedard/debugbar/vendor/barryvdh/laravel-debugbar/src/ServiceProvider.php(108): Barryvdh\Debugbar\LaravelDebugbar->boot()
#3 [internal function]: Barryvdh\Debugbar\ServiceProvider->boot()
#4 /Users/adhe/Code64/octobercms-experimental/vendor/laravel/framework/src/Illuminate/Container/Container.php(526): call_user_func_array(Array, Array)
#5 /Users/adhe/Code64/octobercms-experimental/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(703): Illuminate\Container\Container->call(Array)
#6 /Users/adhe/Code64/octobercms-experimental/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(685): Illuminate\Foundation\Application->bootProvider(Object(Barryvdh\Debugbar\ServiceProvider))
#7 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Barryvdh\Debugbar\ServiceProvider), 20)
#8 /Users/adhe/Code64/octobercms-experimental/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(686): array_walk(Array, Object(Closure))
#9 /Users/adhe/Code64/octobercms-experimental/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(15): Illuminate\Foundation\Application->boot()
#10 /Users/adhe/Code64/octobercms-experimental/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(183): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(October\Rain\Foundation\Application))
#11 /Users/adhe/Code64/octobercms-experimental/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(195): Illuminate\Foundation\Application->bootstrapWith(Array)
#12 /Users/adhe/Code64/octobercms-experimental/install_files/php/Installer.php(677): Illuminate\Foundation\Console\Kernel->bootstrap()
#13 /Users/adhe/Code64/octobercms-experimental/install_files/php/Installer.php(506): Installer->bootFramework()
#14 /Users/adhe/Code64/octobercms-experimental/install_files/php/Installer.php(382): Installer->createAdminAccount()
#15 /Users/adhe/Code64/octobercms-experimental/install_files/php/Installer.php(48): Installer->onInstallStep()
#16 /Users/adhe/Code64/octobercms-experimental/install_files/php/boot.php(74): Installer->__construct()
#17 /Users/adhe/Code64/octobercms-experimental/install.php(1): include('/Users/adhe/Cod...')
#18 {main}


I think that it is something error with Debugbar plugin I included through project I created.

**Comment by daftspunk** [comment]
Try installing without the project and then add it later.

This plugin may be faulty and abandoned by the author.

**Comment by adwidianjaya** [comment]
I've remove the plugin from project I created online. It now works, thank you so much.
