### ISSUE TITLE
CombineAssets -> makeCacheId

### ISSUE THREAD

**Issue by christianWilling** [octobercms/october#1778]
Could you add an event in the `makeCacheId` function in the `System\Classes\CombineAssets` class to modify the cache id. So you can add included files to the File like less or scss import.

**Comment by christianWilling** [comment]
the request comes from christianWilling/Scss#1

**Comment by daftspunk** [comment]
Can you submit a PR for this? Include the example code you want to use as well.

**Comment by christianWilling** [comment]
yes #1794 

´´´
 protected function makeCacheId(array $assets)
     {
         //build cacheId for every file
         $cacheIds = [];

         foreach ($assets as $asset) {
             $cacheId = $asset;

             //calls event so plugins can modify the cacheId
             Event::fire('cms.combineassets.makecacheid', [$cacheId, $asset, $this]);

             $cacheIds[] = $cacheId;
         }

         //put all cacheIds together
         return md5($this->localPath . implode('|', $cacheIds));
    }
´´´
