### ISSUE TITLE
Argument 1 passed to October\Rain\Translation\FileLoader::loadNamespaceOverrides() must be of the type array, integer given

### ISSUE THREAD

**Issue by LaravelNick** [octobercms/october#1785]
Just developed a site which works perfectly well on my development machine.

Uploaded it to hosting and whilst the front end works fine, when I log into the backend, it crashes with the following error:-

Argument 1 passed to October\Rain\Translation\FileLoader::loadNamespaceOverrides() must be of the type array, integer given

The only plugins I've used are the Rainlab blog one and the WYSIWYG editor one.

Any help appreciated please.

**Comment by LaravelNick** [comment]
I deleted the site and uploaded all my files again and the issue disappeared.

**Comment by sozonovalexey** [comment]
The problem appears when lang.php file is empty for selected language

**Comment by daftspunk** [comment]
@sozonovalexey can you submit another issue (bug) with complete replication instructions and we can look at implementing a fix.

**Comment by sozonovalexey** [comment]
@daftspunk done - https://github.com/octobercms/october/issues/2607
