### ISSUE TITLE
Improve visibility of missing plugin dependencies

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#1787]
If you add a plugin to the `$requirement` attrib of your Plugin method and don't have that required plugin installed, doing a `php artisan plugin:refresh Your.Plugin` will result in:

> Plugin "Your.Plugin" not found.

it should instead provide a message about not meeting requirements.

Example:

``` php
class Plugin extends PluginBase
{

    public $require = [
        'RainLab.User',
        'RainLab.Location',
        'RainLab.UserPlus',
    ];
```

If I don't have _RainLab.UserPlug_ installed, doing a plugin:refresh will result in the above message. It really should say something along the lines of

> Plugin "Your.Plugin" requires a plugin "RainLab.Userplus" not currently installed.

**Comment by daftspunk** [comment]
Fixed by a40357cec951beecfadb0b730ab95324dc1eac7f
