### ISSUE TITLE
Rain\Auth\Manager queries database too often on Auth::check() or Auth::getUser()

### ISSUE THREAD

**Issue by philipptempel** [octobercms/october#1790]
**Bug summary:**
Using `Auth::check()` or `Auth::getUser()` queries the database for every single call when there is no authenticated user

**Request location:**
Anywhere

**Reproduce steps:**
Install plugin Rainlab.User, create a page with the code

``` php
function onStart() {
    \Auth::check();
    \Auth::check();
    \Auth::check();
    \Auth::check();
}
```

and see how the database gets queried four times trying to find a valid user object

**Expected result:**
Database is queried only once and result is then cached

**Actual result:**
In above example, the database is queried 4 times

**Recommendation**

The problem with `Auth::check()` actually comes from the fact that it checks for existence of `$this->user` (actually checks `is_null($this->user)`).
Now, the problem I see here is, if the check fails because the user is not logged in, the value of `$this->user` never changes and always stays `NULL` thus there will be subsequent queries to the database (and in the first instance to the session/cookie). It might be best for `Auth::check()` to check whether `$this->user` is `NULL` and only then query the session/cookie or database. If it does not find a valid user, then it should set `$this->user` to something like `-1` or another value that distinctively defines a non-logged-in user.
Of course, `Auth::getUser()` must be adjusted then to `return ( $this->user && $this->user != -1 ? $this->user : NULL );` or something like that.
Another easy fix could be to use `$this->createUserModel()->remember(10)->find($id)` on [L:344](https://github.com/octobercms/library/blob/master/src/Auth/Manager.php#L344) though this could potentially lead to problems elsewhere.

I see this a flaw in the design. Or would it be compensated with proper query caching? Any other guesses/comments/thoughts on it?

**Comment by tschallacka** [comment]
Maybe default "guest" user that has 0 access priveleges? that way all code can still run, access checks will deny access, and there's a default access level that can be modified by plugins by modifying the guest user(useful for demo sites etc...)

**Comment by daftspunk** [comment]
I think `Auth::getUser` should be cached, but not `Auth::check`, that would make sense. Performing a check should be forced, getting the user should be cached. However the `check` method should bust the cache at the same time.

```
// *** In the same cycle

// false
!!Auth::getUser();

// false
Auth::check();

// *** User signs in

// false (should be true)
!!Auth::getUser();

// true
Auth::check();

// true
!!Auth::getUser();
```

**Comment by LukeTowers** [comment]
Non-issue since https://github.com/octobercms/library/pull/253 implemented an in-memory DB query cache for requests removing all duplicate queries in one fell swoop. Another round of applause for @acasar!
