### ISSUE TITLE
filterfields issue

### ISSUE THREAD

**Issue by oadslug** [octobercms/october#1791]
If the template is built using separate formRender methods (i.e. outside, primaryTabs, secondaryTabs) then changing a `dependsOn: myfield` field will not trigger `filterfields` when fields are defined in different areas (Note: works on initial page load, but does not ajax reload when changing dependent field values when editing content).

```
 // `dependsOn` doesn't work if dependent fields defined in different sections 
 <?= $this->formRenderOutsideFields() ?>
 <?= $this->formRenderPrimaryTabs() ?>
 <?= $this->formRenderSecondaryTabs() ?>
```
## 

```
 // `dependsOn` works if dependent fields are defined in different sections 
 <?= $this->formRender() ?>
```

The `trigger` attribute seems to work in either scenario.

Here is the page code:

``` php

<?php Block::put('breadcrumb') ?>
    <ul>
        <li><a href="<?= Backend::url('terrain/site/posts') ?>">Posts</a></li>
        <li><?= e(trans($this->pageTitle)) ?></li>
    </ul>
<?php Block::endPut() ?>

<?php if (!$this->fatalError): ?>

    <?php Block::put('form-contents') ?>

        <div class="layout-row">
            <?= $this->formRenderOutsideFields() ?>
            <?= $this->formRenderPrimaryTabs() ?>
        </div>

    <?php Block::endPut() ?>

    <?php Block::put('form-sidebar') ?>

        <div class="hide-tabs form"><?= $this->formRenderSecondaryTabs() ?></div>

        <div class="form-buttons">
            <div class="loading-indicator-container">
                <button
                    type="submit"
                    data-request="onSave"
                    data-hotkey="ctrl+s, cmd+s"
                    class="btn btn-primary">
                    <?= e(trans('backend::lang.form.create')) ?>
                </button>
                <button 
                    type="button"
                    data-request="onSave"
                    data-request-data="close:1"
                    data-hotkey="ctrl+enter, cmd+enter"
                    class="btn btn-default">
                    <?= e(trans('backend::lang.form.create_and_close')) ?>
                </button>
                <span class="btn-text">
                    <?= e(trans('backend::lang.form.or')) ?> <a href="<?= Backend::url('terrain/site/posts') ?>"><?= e(trans('backend::lang.form.cancel')) ?></a>
                </span>
            </div>
        </div>

    <?php Block::endPut() ?>

    <?php Block::put('body') ?>
        <?= Form::open(['class'=>'layout stretch']) ?>
            <?= $this->makeLayout('form-with-sidebar-custom') ?>
        <?= Form::close() ?>
    <?php Block::endPut() ?>

<?php else: ?>
    <p class="flash-message static error"><?= e(trans($this->fatalError)) ?></p>
    <p><a href="<?= Backend::url('terrain/site/posts') ?>" class="btn btn-default"><?= e(trans('backend::lang.form.return_to_list')) ?></a></p>
<?php endif ?>

```

**Comment by daftspunk** [comment]
There is no example code here for me to reference.

When a form is rendered in pieces like this, it creates an instance of `october.form.js` for each one. Field dependencies are contained to each instance, to prevent pollution among multiple forms. Trigger API attaches to a global instance and is prone to such conflicts.

You can create custom logic to refresh fields in your own JavaScript and take advantage of the `onRefresh` AJAX handler used by `dependsOn`.

**Comment by oadslug** [comment]
Thanks for clarifying. I've included the file in my original question if it helps. I assumed it was a javascript scope issue. And I certainly understand the issue.  But it does make the 'dependsOn' (and other javascript) less useful. I'll look into rolling my own js, but perhaps there is more fundamental solution - like providing a 'scope' to the render method? Or providing a global scope for the entire page for things like this. Thanks again.

**Comment by oadslug** [comment]
I have found a temporary workaround by rendering the form sections without containers, and then manually wrapping the whole form in a container — although it would be great to have a more permanent solution. 

    <?php Block::put('form-contents') ?>
        <div class="layout-row">
            <?= $this->formRender(['section' => 'outside', 'useContainer' => false]) ?>
            <?= $this->formRender(['section' => 'primary', 'useContainer' => false]) ?>
        </div>
    <?php Block::endPut() ?>

    <?php Block::put('form-sidebar') ?>
        <div class="hide-tabs form"><?= $this->formRender(['section' => 'secondary', 'useContainer' => false]) ?></div>
    <?php Block::endPut() ?>

    <?php Block::put('body') ?>
        <?= Form::open(['class'=>'layout stretch']) ?>
            <div data-control="formwidget" data-refresh-handler="form::onRefresh" class="form-widget form-elements layout" role="form" id="Form" data-disposable="">
                <?= $this->makeLayout('form-with-sidebar') ?>
            </div>
        <?= Form::close() ?>
    <?php Block::endPut() ?>

**Comment by danielbidala** [comment]
@oadslug thanks for your solution, it works well! I've spent hours trying to figure out what's happening.

**Comment by Eoler** [comment]
> @oadslug thanks for your solution, it works well! I've spent hours trying to figure out what's happening.

You're not the only one: https://github.com/octobercms/october/issues/1698

**Comment by LukeTowers** [comment]
@bennothommo could you review this and verify that the trigger API and dependsOn support have different behaviour when rendering a form in pieces vs one render call (assuming that both are under a single containing form element of course).

@daftspunk could you provide more background information as to why the trigger API is allowed to cross sections whereas the dependsOn isn't? I would think that if they're all a part of the same containing Form HTML element then why does it matter how they were rendered internally?

**Comment by bennothommo** [comment]
@LukeTowers I can't confirm any particular difference between the two scenarios. Dependent fields are based on the fields available within the main `form` element, which in the normal course means that it's basically every field except for those within a modal window, or those within a nested form widget.

I was able to confirm that a dependent field was refreshed in separated sections by changing the Blog plugin "Author" field to depend on the title field - since that uses the "fancy" layout and renders the sections separately, I believe that's a similar layout to the one posted in the OP. In my test, the author field was being refreshed each time the title was changed.

**Comment by LukeTowers** [comment]
@Eoler @oadslug @danielbidala could you guys provide more specifics on what exactly isn't working and we can look into it further?

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions on how to replicate it *using the test plugin*.

**Comment by Eoler** [comment]
Problem is only reproducible on sidebar area in [form-with-sidebar layout](https://github.com/octobercms/october/blob/master/modules/backend/layouts/form-with-sidebar.htm#L21), workaround is to use single wrapper form on that layout. Maybe worth mentioning in the documentation (can't find `form-with-sidebar` in the docs right now?)

**Comment by bennothommo** [comment]
@Eoler The sidebar is still within the `form` element though, isn't it?

**Comment by Eoler** [comment]
> @Eoler The sidebar is still within the `form` element though, isn't it?

Yes, sorry I misremembered - all my plugins manage backend controllers with custom list/form/relation behaviors (like in #4473 for example) so there's rendering with `'useContainer' => false` and some CSS/JS enhancements which doesn't expose this issue. Closest explanation is the comment here: https://github.com/octobercms/october/issues/1698#issuecomment-297148662  
Maybe not relevant anymore?

**Comment by iboved** [comment]
5 years later... I have the same problem. Why isn't this fixed yet?

**Comment by daftspunk** [comment]
> 5 years later... I have the same problem. Why isn't this fixed yet?

Hi @iboved, thanks for your comment. It would appear nothing was fixed because this is not a bug, forms have context and `dependsOn` relies upon that context. The solution is given to ensure all fields belong to the same `<form>` HTML element.

In more complex cases where two `<form>` elements need interdependencies, custom JavaScript should be used. This also includes nested form fields.

The reason this cannot be solved is that multiple forms can contain the same field names (used by dependsOn) and the event logic cannot leak to impact nested or sibling form fields. This is the bug that would result.

I hope this makes sense, if you require further assistance, feel free to send us an email

Thanks!

**Comment by daftspunk** [comment]
Update: A solution for this has been added in v3 - https://github.com/octobercms/docs/commit/f3a12e0c93b118a0c9b0df7d74f4e304f78d39e1

The `changeHandler` property lets you escape the `dependsOn` implementation and build custom layouts.

Thanks
