### ISSUE TITLE
Sluggable stripping suffix off genuine slugs

### ISSUE THREAD

**Issue by oadslug** [octobercms/october#1793]
The 'sluggable' model property creates strange looking slugs, as compared to the field preset 'slug'.

Using the field preset (i.e. `preset: field: title type: slug`) creates normal looking slugs.

    'Type 1' -> 'type-1'
    'Type 2' -> 'type-2'
    'Type 3' -> 'type-3'

Using the sluggable model property (i.e. `protected $slugs = ['slug' => 'title'];`) (and then seeding the table) creates very odd results.

    'Type 1' -> 'type'
    'Type 2' -> 'type-2-2'
    'Type 3' -> 'type-3-2'

Also, when seeding the table with slugs defined explicitly, the slugs get overwritten by the 'sluggable' method.

**Comment by daftspunk** [comment]
This is by design, sluggable will create unique slugs. It is searching for records that already exist with `slug` and will affix -1, -2, -3 accordingly if it already exists.

**Comment by oadslug** [comment]
I understand why it is affixing the -1, -2, etc. That is not the issue. It is not creating the initial slug as expected (or at least not using the same logic as does the field `preset: slug`). 'Sluggifying' typically takes the string, and replaces whitespace and punctuation with dashes, but keeps numbers. This seems like it is excluding numbers on the first pass (when comparing if there is already a slug with this name), and then including them on secondary passes as it adds additional numbers? Not sure, but  very odd none-the-less.

Having titles that are 'Title 1', 'Title 2' and 'Title 3' should produce the slugs 'title-1', 'title-2', 'title-3'. There should be no duplication errors and thus no reason for it to append any numbers.

Using the field preset:slug produces the expected results: 'title-1', 'title-2', 'title-3'. I would have to look, but I'm assuming you could just copy the function used for the preset:slug method, and paste into the 'sluggable' behavior.

**Comment by daftspunk** [comment]
Indeed, very strange.
