### ISSUE TITLE
Bug: Disabled plugins showing up in main nav

### ISSUE THREAD

**Issue by oadslug** [octobercms/october#1795]
When logging in as superuser disabled plugins are showing up in the main nav (top nav);  it is also possible to view, edit, create, save entries in disabled plugins. They only disappear again when entering Settings/Manage Plugins page or Builder page.

While I haven't tested this I assume that disabled plugins will also show up for any user that has permission to access them. 

This could potentially introduce a security issues.

**Comment by daftspunk** [comment]
Is this a bug report? If so can you provide replication instructions, which plugin does this occur on?

I disable my plugins and they do not appear in the top nav.

**Comment by oadslug** [comment]
It is happening every time for me on this project, in it's current state, but I would have no way of knowing how to duplicate this issue. Possibly a conflict with the Builder plugin. Regardless, this doesn't seem like something that should be possible under any circumstances. I'll try and provide more details if I can. Or try and replicate the issue. 

Current installed plugins are:

RainLab.Blog	1.2.2 - disabled
RainLab.User	1.2.1
RainLab.Location	1.0.3
RainLab.UserPlus	1.0.3
RainLab.Builder	1.0.6
Bedard.Debugbar	1.0.3
October.Test	1.0.3 - disabled
Terrain.Backend	1.0.1
ShahiemSeymor.Roles	1.0.10
Autumn.Pages	1.0.11 - disabled

Terrain.Site	1.0.3 (project plugin)
Terrain.Products 1.0.3 (project plugin)

**Comment by Hessel91** [comment]
Maybe you can use some of my information, I'm having an sort of same issue.
I created an smaller version of the company plugin. everything works fine.
However the plugin only shows up in the main nav when superuser is on. If superuser is of, and all acces is granted it will not appear in the main nav

**Comment by daftspunk** [comment]
We need clear replication instructions to be able to assist. See the contribution guidelines for more information.

**Comment by uxms** [comment]
This bug is duplicated for us, too. Tried both local installation (debug true) and on live site (debug false).

Replication steps:
1- Disable any plugin from manage plugins page
2- Log out from backend (if you not logged-out, plugin seems disabled, neither setting page nor menu page reachable)
3- re-login backend. menu pages shown and settings pages is reachable.
4- Click Updates on settings
5- Plugin disabled from menu and settings, also is not reachable as expected.


Hope this detailed a bit more..

**Comment by uxms** [comment]
System checking permissions first, probably. When opened updates page, disabled plugin is disappearing from menu and also prohibited to open any page of related plugin (direct url access). Maybe related to cache issue or similar.

* Superuser has all permissions so it can reach plugin even tough it is disabled.
* If we grant "Allow" permission for plugin to a backend user (who is not superuser), it can reach plugin pages or settings even tough plugin is disabled.

**Comment by JeyKeu** [comment]
@uxms I confirm same behavior as of today.

**Comment by madonion** [comment]
I have this problem too.
I only have to visit /backend/system/updates and the disabled plugins disappear for the entire session.

**Comment by LukeTowers** [comment]
Just to pitch in for this as well, I'm noticing that if you disabled the Bedard.DebugBar plugin, then login with another backend user, the plugin will be re-enabled for that user.

**Comment by GinoPane** [comment]
Here's the video where this bug is reproduced: https://www.youtube.com/watch?v=5iijs0xH7iU&feature=youtu.be

Could please someone explain why `disabled.json` was implemented? It seems completely unreliable.

**Comment by GinoPane** [comment]
@LukeTowers 

The reason for this issue is

```
CacheHelper::clear(); // UpdateManager.php:159
```

It calls `clearMeta` which removes `disabled.json`. I don't know why it was done like that but it looks wrong to me. Anyway I left it untouched and made a fix for the issue.

**Comment by daftspunk** [comment]
Thanks everyone for helping us locate this long standing problem.

Fixed in ab7dda260baf2b0489f6fe2753a5fabc6f910b93
Available in Build 440+
