### ISSUE TITLE
storage/app/uploads 404 with october cms on subdomain

### ISSUE THREAD

**Issue by arekan127** [octobercms/october#1797]
I have mirrored october cms in subdomain folder on regular hosting, through command 

> php artisan october:mirror

And found an issue that folder storage was not hard linked, as it should be I guess, cause 404 alert on uploaded img is not good:)... i hard linked it manually, but is it safe, and may be there is another way to solve issue with 404 on app/uploads files?

**Comment by daftspunk** [comment]
These directories are currently mirrored, which includes the app uploads directory:

```
    protected $directories = [
        'storage/app/uploads',
        'storage/app/media',
        'storage/temp/public',
    ];
```

Is this a bug report? Can you provide replication instructions.
