### ISSUE TITLE
Please add deferred bindings support for pivot data

### ISSUE THREAD

**Issue by jajacobs** [octobercms/october#1803]
There are many scenarios were this is useful. For example when adding order items while creating an order.

**Comment by daftspunk** [comment]
We will get around to it eventually.

**Comment by priitperna** [comment]
Any progress on this issue?

**Comment by LukeTowers** [comment]
@priitperna Did #1641 fix it for you? Please let us know so we can close this issue and document the new support if it did.

**Comment by daftspunk** [comment]
Still thinking of the best way to handle this. We may need to add a jsonable field to the deferred bindings table to allow the pivot data to be stored temporarily.

**Comment by LukeTowers** [comment]
Duplicate of #1409
