### ISSUE TITLE
Page slug params incorrect with extra slash in param.

### ISSUE THREAD

**Issue by Upperfoot** [octobercms/october#1806]
Just tried this out, following on from https://github.com/octobercms/october/pull/781

`/categories/:slug*/:page?|^[0-9]+$`\- which works out to.
# /categories/test - Works

`:slug = test`
`:page = (blank)`
# /categories/test/1 - Works

`:slug = test`
`:page = 1`

But if for example example I have the a slash in the slug name so that I have the following
# /categories/test/test/1 - Works

`:slug = test/test`
`:page = 1`
# /categories/test/test - Doesn't work

`:slug = test`
`:page = test`

**:page** thinks the value is test even though the regex should be matching only on numeric values 
`:page?|^[0-9]+$`

Any idea what I am doing wrong or is this a bug?

Cheers!

**Comment by Upperfoot** [comment]
The friendliest and humblest of bumps @daftspunk @alekseybobkov

**Comment by Upperfoot** [comment]
Has this been reviewed yet at all? Sorry to be pushy.

**Comment by LukeTowers** [comment]
Why would you want to have a slug that has a slash in it? That seems like a headache to support.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
