### ISSUE TITLE
Allow form field comments in HTML/MD formats

### ISSUE THREAD

**Issue by daftspunk** [octobercms/october#1808]
This attribute could handle it

```
commentFormat: md|html|text
```

### Concerns:

1. There was an issue trying this previously, since `Markdown::parse` would take a single line comment and wrap it in `<p></p>` tags, causing it to look quite bad. Need to find some way to render markdown as a single line, perhaps?

1. @Flynsarmy suggested an improved structure similar to the `trigger` and `preset` options. We can look at this later with a backward compatible solution.

        comment:
            text: foo bar baz
            position: above
            format: markdown

1. Be sure to test multi-lined markdown:

        comment: |
            I like chicken
            I like liver
            Meow mix meow mix
            Please deliver

1. There are also some other interesting properties we could have, such as `previewComment` (different comment for preview context), `previewLink` (provide a link to another page), `previewHelp`, `previewNoRelation` (disable the non-existent feature of providing a relation preview)

**Comment by Codenator81** [comment]
I start work on this
So this field don`t needed there? 
https://github.com/octobercms/october/blob/stable/modules/backend/classes/FormField.php#L125

**Comment by daftspunk** [comment]
Thanks for pointing this out, it looks like we made room for this in the early days but never completed the feature. It raises an interesting point, do we really need markdown in comments? We might be over thinking this.

**Comment by Flynsarmy** [comment]
HTML would work and be far more flexible than markdown. I'm fine with this. Can it be entered into yaml though? Might be better having a commentPartial line for HTML comments.

**Comment by Codenator81** [comment]
@daftspunk  I am happy with html ) Ok so I find out markdown add p tag. You do the same as I so not going to do pull request

**Comment by Codenator81** [comment]
@Flynsarmy in yaml add commentHtml and add true or false. That is

**Comment by Flynsarmy** [comment]
@Codenator81 You misinterpreted what I said. I was questioning whether entering actual HTML into the comment line when commentHTML is true will work well.

**Comment by daftspunk** [comment]
I use YAML + HTML together all the time, they was like peas and carrots.

**Comment by gavinworks** [comment]
Could we add this to static page variables too? Be most useful :D

**Comment by chris5555** [comment]
Hello, this is my first issue report on github ever. So I hope here is the right place for this.

I just realized, that `commentHtml = true` doesn't work with fields of type checkbox, switch and section. 

Is this intended?

Thank you

**Comment by daftspunk** [comment]
@chris5555 Please log a new issue for this so we can investigate. Thanks!
