### ISSUE TITLE
json_encode inside php section of a page

### ISSUE THREAD

**Issue by kvailas** [octobercms/october#1814]
Hi there, thanks for the great cms you provided.

I have a problem trying to render a json_encode variable to twig page.

when i try to render the variable with {{ variable }} the json string is rendered but it is htmlentities encoded.
When i tried to enter it as {!! variable !!} i got no luck because the system not seem to understand {!! !!} command as laravel does.

Is there any solution?
Thanks.

**Comment by daftspunk** [comment]
You are probably looking for the `|raw` filter.

    {{ variable|raw }}

Check the docs for more details: http://octobercms.com/docs/markup/filter-raw
