### ISSUE TITLE
Need a way to refresh settings models after middleware resets connection

### ISSUE THREAD

**Issue by DMeganoski** [octobercms/october#1815]
I have a middleware that dynamically replaces the configuration for the primary database and resets the connection. This works as expected for most Eloquent Models, however it seems that the settings models are cached in memory and thus still rely on the original connection that was made before my middleware runs. At the very least, a static method to flush the cache would do the trick.

Edit: I had a second question here, but to keep things neat and tidy I'll create a second feature request as to keep discussion separate.

**Comment by daftspunk** [comment]
Added the [static] method `System\Behaviors\SettingsModel::clearInternalCache();` that should clear out the cache stored in memory.

**Comment by daftspunk** [comment]
##### This feature has been implemented via live stream:
:movie_camera: https://youtu.be/LbXAvFJkdZw

**Comment by DMeganoski** [comment]
Thank you very much. :)
