### ISSUE TITLE
feature request: allow 'select-no-search' to be defined in yaml file

### ISSUE THREAD

**Issue by oadslug** [octobercms/october#1817]
Consider adding css rule to allow the 'select-no-search' class to be defined in yaml field definition files, so that the 'select' tag can inherit the definition from the 'drop-down-field' class.

fields.yaml

```
type: dropdown
cssClass: select-no-search
```

css definition

```
.drop-down-field.select-no-search > select {
    // hide search ui
}
```

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
