### ISSUE TITLE
Plugin function that is executed by middleware

### ISSUE THREAD

**Issue by DMeganoski** [octobercms/october#1818]
I have written a plugin which includes a new copy of Kernel.php which just simply extend's October's default one and adds my middleware to the list.

I have to manually add these new files to the autoloader and replace the singleton in bootstrap/app.php, though, and I do not like the idea of having to modify files outside of the plugins folder as such extra actions could cause problems if I wanted to introduce it to the market.

A simple solution could be to have a particular middleware search each Plugin.php for a certain function I.E. 

`public function pluginMiddleware(Application $app) {}`

and execute it if the function exists. This would solve my problem, and give us developers, especially those familiar with Laravel, a lot of power over the application.

**Comment by DMeganoski** [comment]
This could also be useful for detecting languages in the url

**Comment by mplodowski** [comment]
You can use plugin boot() method to register new middleware like this:

    $kernel = $this->app->make('Illuminate\Contracts\Http\Kernel');
    $kernel->pushMiddleware(YourMiddlewareClass::class);

**Comment by DMeganoski** [comment]
Oh, wow. nice. I had not seen the pushMiddleware function thank you very much.
