### ISSUE TITLE
Bug: Integrity constraint violation: 1048 Column 'is_custom' cannot be null 

### ISSUE THREAD

**Issue by serega-kasyanow** [octobercms/october#1819]
clean db
artisan october:up
go to /backend/system/mailtemplates

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'is_custom' cannot be null (SQL: insert into`system_mail_templates`(`code`,`description`,`is_custom`,`layout_id`,`updated_at`,`created_at`) values (backend::mail.invite, Invitation for newly created administrators., , 2, 2016-02-29 08:53:53, 2016-02-29 08:53:53))
`

change modules/system/models/MailTemplate.php:99
from `$template->is_custom = false;` to `$template->is_custom = 0;` solves the problem

**Comment by daftspunk** [comment]
Can you submit a PR for this?

**Comment by Kilgaloon** [comment]
@daftspunk This is resolved, i guess you should just close it :)
