### ISSUE TITLE
Add pagination on ReorderController

### ISSUE THREAD

**Issue by FrancescoPassanti** [octobercms/october#1822]
Hello.
I am working on a project to manage Medical Records. I imported a disease from an Open Source Database in my table. I would use Nested Tree's traits to set parents and children in disease model.
The problem is that when i open the reorder page October generates an error because the list is very long. 
It is possible to add pagination in the reorder Controller?

Thanks a lot for October CMS. It is amazing and the Builder is awesome!!

**Comment by daftspunk** [comment]
It is an unsupported feature at the moment. You could consider writing a custom implementation that can handle this for you, it is always possible.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
