### ISSUE TITLE
HasOne sometimes null

### ISSUE THREAD

**Issue by cesarzagonel** [octobercms/october#1823]
Clicking save I can see at the query log the value set as null and after set as actual value.
Clicking save again I see the value just set as null.

I think the problem is here, at  October\Rain\Database\Relations\HashOne:

        if ($instance) {
            $this->parent->setRelation($this->relationName, $instance);

            $this->parent->bindEventOnce('model.afterSave', function() use ($instance){
                $this->update([$this->getPlainForeignKey() => null]);
                $instance->setAttribute($this->getPlainForeignKey(), $this->getParentKey());
                $instance->save();
            });
        }

When there is no value or a different one, the old record it is set as null
$this->update([$this->getPlainForeignKey() => null]);
Ok, and after, the new record is set with the actual value.
$instance->setAttribute($this->getPlainForeignKey(), $this->getParentKey());

But, when the value is same, the record is set as null:
$this->update([$this->getPlainForeignKey() => null]);
And set the same value the another instance of same record.
$instance->setAttribute($this->getPlainForeignKey(), $this->getParentKey());
So, the model is not dirty, preventing save it.

Am I wrong?
Thanks.

**Comment by daftspunk** [comment]
Can you provide clear instructions how to replicate the issue? Some basic PHP code is fine, please include expected behavior and current (bug) behavior.

**Comment by cesarzagonel** [comment]
Area Model with a $hasOne relation:
public $hasOne = ['place' => ['Acme\Area\Models\Place']];

Form Field Definitions:
    place:
        label: Place
        type: relation
        nameFrom: title
        emptyOption: (any)
        span: left

With a standard controller that implements FormController, clicking at save at edit form, the expected is Place.area_id is equal the Area.id but sometimes it is null.

Is it sufficient?

**Comment by daftspunk** [comment]
Please submit a PR to the [test plugin](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Not sure about "sometimes", we need an instruction that gives us the result "always" instead.
