### ISSUE TITLE
Internal server error - htaccess rewrite 

### ISSUE THREAD

**Issue by Eoler** [octobercms/october#1826]
Recent Apache 2.4.18 compiled with EasyApache/cPanel chokes on .htaccess rewrite whitelisting folders/files, discussion here:
https://forums.cpanel.net/threads/500-internal-server-error.529521/

It probably needs index.php exclusion like:
`RewriteCond %{REQUEST_URI} !/index\.php$`
in this block:
https://github.com/octobercms/october/blob/master/.htaccess#L29-L68

**Comment by daftspunk** [comment]
Feel free to submit a PR to rectify this.

**Comment by Eoler** [comment]
cPanel reverted Apache rewrite hardening in EasyApache 3.32.11:
https://forums.cpanel.net/threads/500-internal-server-error.529521/#post-2148751

I'll prepare a PR anyway - for those poor souls staying on Apache built with EA 3.32.10
