### ISSUE TITLE
Backend Form Behavior resets disabled fields with type "relation" on update context

### ISSUE THREAD

**Issue by ternavsky** [octobercms/october#1827]
I use "Backend Form Behavior" for model create/update actions and need to disable some fields on update context.  So when I save updated model I expect that disabled fields will have the same value as before. For all field types it's true, except Widget type. In my case it was "relation" widget. After saving edited model disabled relation field was reset (become 0, but it was positive int before). 

When we submit update form, disabled fields don't be sent in request so why it was reset? I've looked into source to understand reason and found that in modules/backend/behaviours/FormController.php in function update_onSave we have $this->formWidget->getSaveData(); function that adds null value for disabled relation widget fields. In form widget source (modules/backend/widgets/Form.php) I've found getSaveData function, that calls widget's getSaveValue function. And this function returns null if field is not set.

**Comment by daftspunk** [comment]
Can you submit a PR to the [test plugin](https://github.com/daftspunk/oc-test-plugin) that demonstrates this issue?

**Comment by ternavsky** [comment]
Done. Assume that we want to set related post when creating comment and disable post selection when updating. Just try to create comment with post and update it then. Open comment editing window after update and you'll see that relation was reset. Bug appears with "widget" fields http://octobercms.com/docs/backend/forms#field-widget

**Comment by ternavsky** [comment]
Step by step:
![step1](https://cloud.githubusercontent.com/assets/11328673/14243019/c00ec358-fa5b-11e5-92f8-043734fd3de3.png)
![step2](https://cloud.githubusercontent.com/assets/11328673/14243022/c4c14506-fa5b-11e5-945b-6679061ba65a.png)
![step3](https://cloud.githubusercontent.com/assets/11328673/14243027/c9480ce0-fa5b-11e5-8572-bb2f3e160558.png)

**Comment by daftspunk** [comment]
Thanks for the explanation. The "step by step" helped quite a lot.
