### ISSUE TITLE
[Suggestion] Multisite support.

### ISSUE THREAD

**Issue by caiotarifa** [octobercms/october#183]
I think it would be very useful control many projects with the same core.

**Comment by larswiwi** [comment]
Your ideas are very interesting, I am currently looking for a multi site CMS with this kind of permission handling. Are the suggestions above still a feature request, or are they already further up the pipeline?

**Comment by medrockstar** [comment]
Any new about this feature ?

**Comment by LukeTowers** [comment]
Multisite or multitenant implementations are relatively easy to build in OctoberCMS and are easily done through a plugin. If anyone would like to talk to me about specific implementations or use cases, then I'm available on the Slack.

**Comment by medrockstar** [comment]
can we have just a tutorial for that ?

**Comment by w20k** [comment]
@medrockstar contact @LukeTowers or look at those plugins:

https://octobercms.com/plugin/voipdeploy-multisite
https://octobercms.com/plugin/briddle-multisite

**Comment by medrockstar** [comment]
tks, good plugins,  briddle-multisite share users and plugins, but how can we limit access to the content created by plugins? like in SAAS or wordpress and drupal did.

**Comment by w20k** [comment]
@medrockstar user plugin -> permissions, as simple as that?
I haven't used WP or Drupal with multisite enabled.

**Comment by medrockstar** [comment]
plugin data is also shared, if we have multiple clients, all clients will see data of each others.

What we want :

**Admin1**
Site 1 : has backend with specific plugin data.

**Admin2**
Site 2 : has backend with specific plugin data.

Admin1 can't see the data insered in backend (plugins) by Admin2.

So simple. like SAAS, gmail... 

Tks,

**Comment by LukeTowers** [comment]
@medrockstar if it was simple, then there would be a plugin for it already. Multi tenant applications in October are highly dependant on each individual usage case which makes it not so simple for a single plugin to handle everyone's needs simultaneously.

**Comment by medrockstar** [comment]
Tks @LukeTowers  we want just a tutorial with for example laravel-tenancy.com to help Us to make this, and build Saas platform.

Super Admin for all the platfom, and every site has an sub-admin.
Every site has specific, content, plugin, themes.

**Comment by LukeTowers** [comment]
@medrockstar you'll notice there's a team of 6 behind that project and 2 sponsors and 23 backers. If people are willing to pay for the time it would take me to put something like that together then we can talk.
