### ISSUE TITLE
Bug: Model events not firing when using only increment()

### ISSUE THREAD

**Issue by uxms** [octobercms/october#1834]
Possibly this bug is stemming from eloquent, but we are not sure if we made something wrong. For replicating this issue:

* Use RequestLog in plugin's Plugin.php file
* Add Model::event handler or bindEvent in boot method
* Request any page from front-end which is not exist (any request which forwards to 404)

Sample code in Plugin.php:
```php
use System\Models\RequestLog;

public function boot()
{
    $rlog = new RequestLog;

    // Undefined variable: model - on next line
    $rlog->bindEvent('model.beforeSave', function() use ($model) {
        // Not reaching here
    });

    // Also not working
    RequestLog::saving(function($rlog) {
        // Not reaching here
    });

    // Also not working
    RequestLog::updating(function($rlog) {
        // Not reaching here
    });
}
```

It works if model creates new request log because on [line 51](https://github.com/octobercms/october/blob/master/modules/system/models/RequestLog.php#L51) it triggers save(). But on [line 54](https://github.com/octobercms/october/blob/master/modules/system/models/RequestLog.php#L54) it triggers only increment() and saving, saved or else not triggering.

**Comment by daftspunk** [comment]
`increment()` occurs at the Query level, not the Model level. You would need to do something like this for the model events to fire:

```
$model->column = $model->column++;
$model->save();
```
