### ISSUE TITLE
search in static options on list filter 

### ISSUE THREAD

**Issue by chesterx** [octobercms/october#1839]
Hello,

On the list filter, we can search in a model relationship, but if we use a static options array not.

I have already investigate the problem there is no development on this case.

<img width="280" alt="ekran resmi 2016-03-10 01 38 05" src="https://cloud.githubusercontent.com/assets/533209/13654383/b492cb96-e660-11e5-9c7f-704fc0aa6a42.png">

https://github.com/octobercms/october/blob/master/modules/backend/widgets/Filter.php#L181

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
