### ISSUE TITLE
How to disable assets combining on development in OctoberCMS

### ISSUE THREAD

**Issue by rsobon** [octobercms/october#1840]
Is there possibility to disable asset combining in development environment and enable in production without modifying the twig layout file?

Note: This has nothing to do with asset minification and `enableAssetMinify` flag in the `app/config/cms.php`

For example if there is debug set to true in config/app.php: `'debug' => true`, the twig array in the `<script>` tag should output scripts separately.

Twig array:

```
<script src="{{ [
    'assets/js/one.js',
    'assets/js/two.js',
    '@framework',
    '@framework.extras'
]|theme }}"></script>
{% scripts %}
```

Rendered result should be:
```
<script src="http://localhost/themes/demo/assets/js/one.js"></script>
<script src="http://localhost/themes/demo/assets/js/two.js"></script>
<script src="/modules/system/assets/js/framework.js"></script>
<script src="/modules/system/assets/js/framework.extras.js"></script>
<script src="/modules/system/assets/js/framework.extras.css"></script>
```

And if there is debug set to false in config/app.php: `'debug' => false`

Rendered result should be something like:
```
<script src="http://localhost/combine/2cdc17b704821cd2ffbd9be8e4d340f9-1457016128"></script>
```

Detailed issue on stackoverfow:
https://stackoverflow.com/questions/35892560/how-to-disable-assets-combining-on-development-in-octobercms

**Comment by rsobon** [comment]
OK I managed to work this out but not with the `config/app.php` mentioned in the question.

Other solution requires to create `.env` file in the root directory of OctoberCMS. This file is by default in the `.gitignore` so you can have different .env files on production and development ([Piece of documentation][1])

Contents of this file should be:

    APP_ENV=dev

Then you can access variable in the twig:

    {% if this.environment == 'dev' %}
        <script src="{{ 'assets/vendor/jquery.min.js'|theme }}"></script>
        <script src="{{ 'assets/semantic/dist/semantic.min.js'|theme }}"></script>
        <script src="{{ 'assets/javascript/app.js' | theme }}"></script>
        {% framework extras %}
    {% else %}
        <script src="{{ [
         'assets/vendor/jquery.js',
         'assets/semantic/dist/semantic.js',
         'assets/javascript/app.js',
         '@framework',
         '@framework.extras'
         ]|theme }}"></script>
    {% endif %}


  [1]: http://octobercms.com/docs/setup/configuration#environment-config

**Comment by daftspunk** [comment]
This is probably the best way to handle it. The combiner returns a URL without knowing what tag it is being used for.
