### ISSUE TITLE
Possible Bug: NestedTree occasionally sets incorrect 'nest_depth'

### ISSUE THREAD

**Issue by oadslug** [octobercms/october#1843]
Occasionally a NestedTree sets the 'nest_depth' one higher than it should be. For example, if 'nest_depth' should be 1, it is saved as 2 (even when the parent is 0, and there is no record with a 'nest_depth' of 1 within that node tree).

It doesn't seem to happen with all NestedTrees, or even for all nodes within the same NestedTree, which is very strange. It also seems to occur toward the end of a list, or after a certain node within a list, making me think that the data (nest_left, nest_right, etc) is corrupted in some way. Looking at the data, however, I can't determine what might be causing the problem. I am including a screenshot of the tree in question, in case you can determine any irregularities. Notice the 'nest_depth' of record 84 is 2, when it should be 1. I will continue to investigate to try and find a reproducible scenario.

<img width="893" alt="nested-tree-screenshot" src="https://cloud.githubusercontent.com/assets/8769174/13724639/191b301c-e841-11e5-86bc-9d298b07eb44.png">

**Comment by daftspunk** [comment]
Do you have a reliable way to replicate this? See if you can get it to happen using the [Test plugin](https://github.com/daftspunk/oc-test-plugin).

**Comment by oadslug** [comment]
I was unable to replicate with the Test Plugin — I know that would help. I'll continue to investigate and report back any findings. Thanks.
