### ISSUE TITLE
Backend Javascript Error

### ISSUE THREAD

**Issue by ducminhn** [octobercms/october#1844]
I've just installed OctoberCMS on an EC2 Ubuntu. The installation process was successful, but when I logged into the back-end, I got many JS error whenever I tried to do anything such as add new widget to the dashboard, attach project ID to the site ... any popup windows are not working.
Although the front-end still working well with no error.

![screenshot_031216_040841_pm](https://cloud.githubusercontent.com/assets/7876935/13726096/056d56ea-e86d-11e5-8e05-19080bf1f27c.jpg)

**Comment by ducminhn** [comment]
Nvm, I figured out the problem was with my CloudFlare rocket settings.

**Comment by LukeTowers** [comment]
Duplicate of #3602
