### ISSUE TITLE
OrderBy on Union not working

### ISSUE THREAD

**Issue by kdon80** [octobercms/october#1845]
OrderBy on Union not working

thanks.

**Comment by daftspunk** [comment]
Show us your query.

**Comment by kdon80** [comment]
here is simplified version - I only renamed the table names here: 


    $myListAll` = DB::table('C')->select ('A.main_items_count', 'A.user_item_submissions_count', 'A.user_questions_count', 'B.icon', 'B.B_name', 'B.id as B_id',  'C.order','D.title', 'D.color_hex', 'E.points' ) 
                                    -> leftJoin('E', function ($join) use($userId) {	
										$join->on('C.B_id', '=', 'E.B_id');
									}) 
                                    -> join ('B', function ($join){	
										$join->on('B.id', '=', 'C.B_id');
									}) 
                                    -> join ('A', function ($join)  {	
										$join->on('A.set_id', '=', 'C.B_id');
									}) 
                                    -> join ('D', 'D.id', '=', 'E.D_id')  
                                    -> where('C.user_id', $userId)
            			    -> where('B.enabled', 1)
            			    -> where('A.set_type', 1)
            			    -> where('E.user_id', '=', $userId)
                                    -> orderBy('C.order','asc') 
                                    -> take(10);
                            
					$myList = DB::table('C')->select ('A.main_items_count', 'A.user_item_submissions_count', 'A.user_questions_count', 'B.icon', 'B.B_name', 'B.id as B_id',  'C.order','D.title', 'D.color_hex', 'E.points' ) 
				    -> where('C.user_id', $userId)
            			    -> where('B.enabled', 1)
            			    -> where('A.set_type', 1)
            			    -> where('E.user_id', '=', $userId)
					-> leftJoin('E', function ($join) use($userId) {	
								$join->on('C.B_id', '=', 'E.B_id');
						}) 
					-> join ('B', function ($join){	
							$join->on('B.id', '=', 'C.B_id');
			       		}) 
					-> join ('A', function ($join)  {	
							$join->on('A.set_id', '=', 'C.B_id');
			       		}) 
					-> join ('D', 'D.id', '=', 'E.D_id')  
					-> orderBy('C.order','asc') 
					-> union($myListAll)	
					-> get();

**Comment by daftspunk** [comment]
Can you provide a less complicated example that still exhibits the bug
behaviour?

**Comment by kdon80** [comment]
I simplified the same query by removing most of the joins. Still not ordering by properly:

	$myListAll = DB::table('A')->select ( 'B.icon', 'B.category_name', 'B.id as category_id',  'A.order') 
				-> join ('category', function ($join){	
					$join->on('B.id', '=', 'A.category_id');
				}) 
				-> where('A.user_id', $userId)
				-> where('B.enabled', 1)
				-> orderBy('A.order','asc');

				
	  $myList = DB::table('A')->select ('B.icon', 'B.category_name', 'B.id as category_id',  'A.order' ) 
			-> where('A.user_id', $userId)
			-> where('B.enabled', 1)
			-> join ('category', function ($join){	
				$join->on('B.id', '=', 'A.category_id');
			}) 
			-> orderBy('A.order','asc') 
			-> union($myListAll)	
			-> get();

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
