### ISSUE TITLE
Feature Request: Is it possible to add relation to viewBag?

### ISSUE THREAD

**Issue by uxms** [octobercms/october#1846]
We are trying to add fileupload relation to viewBag with "backend.form.extendFields" event. But it's not possible.

I know it not have any db relation but it is useful in some cases.

Is there a way to do it possible? Maybe it will be handy for some other plugins like RainLab.Pages etc. Example for Pages plugin:

```php
public function boot()
{
    Event::listen('backend.form.extendFields', function ($widget) {

        if (
            !$widget->getController() instanceof \RainLab\Pages\Controllers\Index ||
            !$widget->model instanceof \RainLab\Pages\Classes\Page
        ) {
            return;
        }

        $widget->model->attachMany = [
            'images' => ['System\Models\File', 'order' => 'sort_order']
        ];

        $widget->addTabFields([
            'images' => [
                'tab' => 'Images',
                'label' => 'Images',
                'comment' => 'Gallery images for this page',
                'type' => 'fileupload',
                'mode' => 'image',
                'imageHeight' => 150,
                'imageWidth' => 250
            ]
        ]);
    });
}
```

**Comment by daftspunk** [comment]
This example is not really possible, the `fileupload` widget requires a database model with a file model relationship definition. You could try using the `mediafinder` type instead which simply returns a string.

**Comment by uxms** [comment]
Ok, that maybe a solution. I need to have multiple usage so tried this:

```php
$widget->addTabFields([
    'images' => [
        'tab' => 'Images',
        'label' => 'Images',
        'type' => 'repeater',
        'prompt' => 'Add image',
        'form' => [
            'fields' => [
                'image' => [
                    'label' => 'Banner image',
                    'type' => 'mediafinder'
                ]
            ]
        ]
    ]
]);
```

but this renders also repeater itself and getting stuck with js. Any luck?

**Comment by seanthepottingshed** [comment]
@uxms - when you say renders the repeater itself, do you mean that the repeater form fields are visible in the frontend. If so then I'm having exactly the same issues.

**Comment by uxms** [comment]
Not meant front-end buddy. In backend, "Pages plugin" page.

![screen shot 2016-03-21 at 11 21 05](https://cloud.githubusercontent.com/assets/14033288/13914496/5a1dd020-ef57-11e5-9b4a-51ec82551bd6.png)

**Comment by seanthepottingshed** [comment]
No worries @uxms I'm having a different issue where the repeater is actually rendering in the frontend.

**Comment by seanthepottingshed** [comment]
To explain a little further here is the backend repeater

![screen shot 2016-03-21 at 09 45 38](https://cloud.githubusercontent.com/assets/12046965/13914984/d90b72d8-ef49-11e5-99be-9b50ca51e62b.png)

Then this is the source of the corresponding front-end where I've had too comment out the rendered content from the repeater:

![screen shot 2016-03-21 at 09 38 58](https://cloud.githubusercontent.com/assets/12046965/13915002/eeac6b60-ef49-11e5-9ef3-21c006c7a5c8.png)
