### ISSUE TITLE
Compression for transferring combine

### ISSUE THREAD

**Issue by vebam** [octobercms/october#1847]
Hello,
Why /combine/* stylesheet is gziped,
/combine/* script don't.

![clipboard01](https://cloud.githubusercontent.com/assets/6676468/13806086/8fbd627e-eb59-11e5-9da0-89019b44c4e5.jpg)

**Comment by gabsource** [comment]
Apache `/etc/apache2/mods-available/deflate.conf` may look like this (should be the defaults on Ubuntu 14.04) : 
```
    AddOutputFilterByType DEFLATE text/css
    AddOutputFilterByType DEFLATE application/x-javascript application/javascript application/ecmascript
```

So it does not recognize `text/javascript` Content-Type header as a candidate to compression.

Adding `AddOutputFilterByType DEFLATE text/javascript` in `.htaccess` should trigger compression for combined javascript.

`\System\Classes\CombineAssets@getContents` sets `$mime = 'text/javascript';` at line 178.

**Comment by vebam** [comment]
Thanks, is working.

I will add:
AddOutputFilterByType DEFLATE text/html
AddOutputFilterByType DEFLATE text/xml
AddOutputFilterByType DEFLATE text/css

**Comment by daftspunk** [comment]
@gabsource Should this be changed to `application/javascript`?

**Comment by gabsource** [comment]
`text/javascript` is deprecated per RFC 4329 in favor of `application/javascript`
https://www.rfc-editor.org/rfc/rfc4329.txt

```
 Use of the "text" top-level type for this kind of content is known to
   be problematic.  This document thus defines text/javascript and text/
   ecmascript but marks them as "obsolete".  Use of experimental and
   unregistered media types, as listed in part above, is discouraged.
 The media types,

      * application/javascript
      * application/ecmascript

   which are also defined in this document, are intended for common use
   and should be used instead.
```
