### ISSUE TITLE
Allow developers to change preview image

### ISSUE THREAD

**Issue by pedzed** [octobercms/october#1848]
Related: http://octobercms.com/docs/themes/development#preview-image

The theme preview **MUST** be placed into `assets/images/theme-preview.png`. This is a very annoying limitation.
- This prevent the usage of JPG, GIF, SVG, etc.
- This forces you to create an images directory.

In our case, we're using an image minifier (with Gulp) which minifies everything from `assets/src/images` to `assets/dist/images`. It would be silly to create a new directory, just for the theme preview image.

**Comment by daftspunk** [comment]
Fixed by #2426
