### ISSUE TITLE
Mail password configuration not secured

### ISSUE THREAD

**Issue by vanmil** [octobercms/october#1850]
Hi all,

One thing I noticed today was that the password in Settings --> Mail Configuration --> Password, the password is visible in plain text. I think it (at least) desirable that the password here is presented in stars (*******). 

I have made a (edited) screenshot:
![Image of problem](http://s11.postimg.org/syd2pk4ib/mailoctober.jpg)

I think this is a serious issue as a personal email password can be viewed by all persons who can acces this particular back-end account (like the web-developer).

**Comment by daftspunk** [comment]
I can see how this would be an issue if you were using your Gmail account to send mail. Usually this password is for an API / robot account so the password is less sensitive.

Presenting the password with stars would still make it possible to see the underlying password by viewing the source. We would have to empty the field instead, this can sometimes make it look like it hasn't been populated.

**Comment by LukeTowers** [comment]
Closing in favour of #1061

**Comment by bennothommo** [comment]
Fixed by #5201.
