### ISSUE TITLE
Install in subfolder and public mirror folder, no assets loaded

### ISSUE THREAD

**Issue by scosist** [octobercms/october#1851]
This issue is similar to many of those that have been posted before (#100, #257, #59, #829), however in this case assets load for both frontend and backend when **_not_** using a public folder (#1331) but no assets are loaded when using a public folder (`october:mirror`).

Apache conf: `Alias /october /var/www/october/public`
```
    <Directory /var/www/october/public>
         Options Indexes FollowSymLinks
         AllowOverride All
         Order allow,deny
         allow from all
     </Directory>
```
.htaccess: `RewriteBase /october/`
```
# a2enmod rewrite
Module rewrite already enabled
```
It seems the only thing not getting loaded is the file returned by `getCombinedUrl` function in `CombineAssets.php` as indicated by the error log:
```
... [error] ... File does not exist: /var/www/october/public/combine
```
and it only occurs when using a public folder.

**Comment by daftspunk** [comment]
Do you have a .htaccess file inside the public folder? I think it should be `RewriteBase /` instead.

**Comment by scosist** [comment]
Ah yes, lack of an .htaccess file was the problem. I think the proper way to do this is to also mirror the .htaccess file when using a public folder. I tried `RewriteBase /` which resulted in a redirect loop. In this case, since it is in a subfolder, leaving it as `RewriteBase /october/` works as expected.

**Comment by daftspunk** [comment]
Duplicate #1750

**Comment by scosist** [comment]
Thanks again, my mistake. That's what I get for running [dev-master](https://octobercms.com/docs/console/commands) and not checking stable. After looking at packagist earlier today I figured I should probably be running dev-stable.
