### ISSUE TITLE
Attachments inside a Relation "One to One" don't work

### ISSUE THREAD

**Issue by FrancescoPassanti** [octobercms/october#1858]
Hello guys, 
i have created two entities and i have connected them with a relation one to one. When i have attached a file in the second entities (connected with the first through a one to one partial) it doesn't store the file. 
To be precise the system adds the value in the "system_files" table but it doesn't store the connection.

I thought that was my fault so i have tested the same thing using October test plugin(oc-test-plugin). I have used the Person and Phone Models. 
The result is the same.

I hope I was helpful.

**Comment by daftspunk** [comment]
Please provide step by step instructions on how to replicate using the October test plugin.

**Comment by FrancescoPassanti** [comment]
Of course. I write below all the steps.

- Open  http://mydomain/backend/october/test/people
- Select the first record (http://mydomain/backend/october/test/people/update/1)
- Choose relation controller (http://mydomain/backend/october/test/people/update/1/relationcontroller)
- Click update phone (Relation button)
- Upload something ( I am using the "picture" attachment)
- Click update on the relation
- Now i see the preview of the upload.
- Click on save

If i refresh the page ( http://mydomain/backend/october/test/people/update/1/relationcontroller) the file is disappeared). But if i check the database (system_files), there is a new record insert without the following fields filled in ( "field","attachment_id","attachment_type").

**Attachment with the screen** 
https://www.dropbox.com/s/lbu313n5ortudy1/october.pdf?dl=0

**Comment by Teranode** [comment]
For the file upload, are you creating a field in mysql for the relation?
Example: lets say your field is 'image' in the picture.php model in a one to one relation.

if you also have the 'image' field in mysql for the model's table, remove that field in the table. The process is a relation, so the 'image' table field will override the relation and remove it.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
