### ISSUE TITLE
IE 10, Windows 7 Backend Rendering Issue

### ISSUE THREAD

**Issue by philltrue** [octobercms/october#1859]
Hi October Team,

We are having issues with the backend not rendering properly on IE10, Windows 7 (screenshot attached). This happens upon updating October from Build 309 -> 317, highly suspect this has something to do with the addition of flex layout?

![ie10](https://cloud.githubusercontent.com/assets/11036526/13910061/882fe5e8-ef70-11e5-873e-1cadce356458.png)

Andsomewhat related, what is October's browser support policy? Which will be good to know since our client have their hands tied to IE10 for foreseeable future.

**Comment by philltrue** [comment]
**Update**

Our teammates had this fixed before, but had to modify october core layout files. Obviously it gets replaced on core update. The fix was to add

`<meta http-equiv="X-UA-Compatible" content="IE=edge" />`

to `backend/layouts/_head.htm` and `backend/layouts/auth.htm`. Looks like IE10 somehow has 'render in IE7 standards' mode set to default without this meta tag.

**Comment by jareis** [comment]
you can put it in htaccess...
http://stackoverflow.com/questions/7567661/http-equiv-x-ua-compatible-content-ie-edge-chrome-1-putting-this-in-hta

philltrue <notifications@github.com> escreveu em seg, 21/03/2016 às 04:02 :
