### ISSUE TITLE
Providing proxy details for HTTP class

### ISSUE THREAD

**Issue by richlove1** [octobercms/october#1861]
My production site sits on a server behind a proxy server so can't make calls out via CURL. I've implemented a workaround but by editing core code. Wondering if something can be incorporated.

I've added a config item in app.php called 'proxy' which is set to empty string locally and set to prox server on production server.

In /vendor/octoberarin/src/Network/Http/php I am then doing the following test on line 241:

`if (config('app.proxy'))
        {
            curl_setopt($curl, CURLOPT_PROXY, config('app.proxy'));
        }`

Which seems to be working. Would you consider implementing a similar strategy to core?

**Comment by daftspunk** [comment]
Can you provide an example of the proxy type and authentication details you are using? i.e the contents of `app.proxy` (sensitive information removed of course).

**Comment by richlove1** [comment]
Hiya, thanks for the reply.

Here's my current approach:

I've added:

`'proxy' => 'http://wwwcache.servername.uk:80'`

to app.php config where i need the proxy. I then added this code at ln241 of vendor/october/rain/src/Network/Http.php

`        if (config('app.proxy'))
        {
            curl_setopt($curl, CURLOPT_PROXY, config('app.proxy'));
        }`

(this consequently has been overwritten during a recent core update to OctoberCMS).

---------------------------------------------

A colleague had an alternative approach, by adding the following code to applyHttpAttributes() function at ln860 in /modules/system/classes/UpdateManager, which uses environment variables and accounts for http and https:

`        if(($proxy = env('HTTP_PROXY', false)) && ($proxy = parse_url($proxy))) {
            $username = !empty($proxy['user']) ? $proxy['user'] : null;
            $password = !empty($proxy['pass']) ?: null;
            $http->proxy('http', $proxy['scheme'].'://'.$proxy['host'], $proxy['port'], $username, $password);
        }`


I'm not sure which the best solution is and there may be something more elegant you can think of.

Cheers

**Comment by richlove1** [comment]
I should probably add that 'vendor/october/rain/src/Network/Http.php' already has some proxy related code in but I'm not sure if this can be leveraged out of the box for updates to core, plugins etc

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
