### ISSUE TITLE
Database foreign keys for system tables

### ISSUE THREAD

**Issue by filipac** [octobercms/october#1864]
I think that the database could be improved by using keys.

Short example: i have an users in the back-end that belongs to two user groups. Delete the user, the record is deleted from `backend_users` table but the permissions for that users are still on `backend_user_groups`. Also, references to the deleted user are still on `backend_user_throttle` table.

I think a modern application like October has to improve it's database with foreign keys whenever this is possible. This leads to a more consistent databse. What do you say?

**Comment by daftspunk** [comment]
I'm all for tidying up these inconsistencies. October should handle this on the PHP side (using `delete=>true` in the relation definition), we want to keep to the simple life and the database as dumb as possible. Applying constraints to the database is a slippery slope to complexity and may create more headaches than it's worth.

**Comment by filipac** [comment]
So
```php
public $belongsToMany = [
        'groups' => ['Backend\Models\UserGroup', 'table' => 'backend_users_groups']
    ];
```

becomes:
```php
public $belongsToMany = [
        'groups' => ['Backend\Models\UserGroup', 'table' => 'backend_users_groups','delete' => true]
    ];
```
?

**Comment by daftspunk** [comment]
Oh no, that will delete the entire group when the user is deleted. Other users may still belong to the group. If you are simply wanting the join/pivot table to be cleaned up, this [occurs automatically in the next major release](https://github.com/octobercms/library/commit/2d29cbc42e7a29d3312493b0b741f92b433606aa) of October.

**Comment by filipac** [comment]
Oh, right, sorry :+1: ok, the commit you referenced seems to fix this.
