### ISSUE TITLE
Backend form relation disable

### ISSUE THREAD

**Issue by shoguniphicus** [octobercms/october#1866]
I am not sure whether this has been reported before or not but a search in the issues didn't come up anything for this.

In the models' field.yaml, I define one of the field as disable = true

categories:
        label: Categories
        type: relation
        nameFrom: title
        disabled: true

However, the checkboxes can still be checked and unchecked.

**Comment by shoguniphicus** [comment]
To clarify, this happens on checkboxlist formwidget when I have a type:relation in field.yaml

**Comment by LukeTowers** [comment]
Fixed by #2803
