### ISSUE TITLE
Default value for $allowedAssetTypes [modules/cms/widgets/AssetList.php]

### ISSUE THREAD

**Issue by TigersWay** [octobercms/october#1869]
Hi,

The **"ico" file type** is not included among the default values, but a favicon.ico is known to be a good thing :-)
And do I understand well: the config cms.allowedAssetTypes does override and not complete the default values, right?

Thanks

**Comment by daftspunk** [comment]
Yes, it does override the entire set of values. Perhaps we should add `ico`, it is a common file type.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
