### ISSUE TITLE
Add SSL HTTPS Switch to the Backend Admin Screen

### ISSUE THREAD

**Issue by kdoonboli** [octobercms/october#1874]
Please add the switch for enforcing HTTPS to the admin site settings. 
Also, there was no mention of it in the official documentations. It took me several hours to search through the Forum to know I have to hard code it in the config file myself.

thanks,

**Comment by CptMeatball** [comment]
Can't you just redirect http to https through nginx or apache?

**Comment by DrTrills** [comment]
Yeah, this should just be done from nginx or apache

**Comment by daftspunk** [comment]
There is a link policy for this in the CMS, however it dictates how URLs are generated and October will never force any type of redirect because this is too magical. It is possible to implement it using a plugin with custom logic or as mentioned via the web server configuration.
