### ISSUE TITLE
Backend Editor - All last "newline" are both stripped out or not loaded

### ISSUE THREAD

**Issue by TigersWay** [octobercms/october#1875]
Hi,
Any specific reason why all "empty" lines are stripped out when saving any content, partial, layout, etc file? 
Or why aren't they even loaded when files are modified outside October?

Kinda difficult without it/them to have a clean html, easier to debug!

Thanks

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
