### ISSUE TITLE
Assets rename error

### ISSUE THREAD

**Issue by goeroe** [octobercms/october#1881]
You are able to upload files with (for example) brackets in the filename. If you try to rename the file you get an error (popup) "Path can contain only digits, Latin letters, spaces and the following symbols: ._-/" and won't be able to rename the file. If you try to delete the file, same error will occure making it uneditable and undeletable.

**Comment by LukeTowers** [comment]
As of today when tested via the latest dev branch the media manager automatically removed such illegal characters from the filename on upload. Unless further information comes to light I'm assuming that this has been fixed in the past 9 months.
