### ISSUE TITLE
Subdomain routing

### ISSUE THREAD

**Issue by andriytkachiv** [octobercms/october#1889]
Could you please add some tips or examples how to implement this feature? 

Or it will be amazing if this feature could be a part of OctoberCMS, it's really useful.

Tried to do as in Translate plugin, but no result.

**Comment by daftspunk** [comment]
In your own words, please describe *subdomain routing* for someone who might not know what that is.

**Comment by andriytkachiv** [comment]
Sorry for my bad explanation :) 

I mean to be able use ```pages``` with subdomain. 
For example I have some pages which are available only for logged users and want them to be on ```app``` subdomain

I see it like this:
In page configuration

```
url = "/mypage"
subdomain="app"
layout = "main"
```

**Comment by matheusrrocha** [comment]
@andriytkachiv The "protected" page options is not an option for you?

**Comment by andriytkachiv** [comment]
@matheusrrocha What is protection page option? I need to place my page on subdomain, that's the task

**Comment by matheusrrocha** [comment]
@andriytkachiv Sorry, the option name is "Hidden". Only logged users are able to access these king of pages. You can create your pages under a /app section. It's just a suggestion ;)

**Comment by matheusrrocha** [comment]
@andriytkachiv  Another thing you can try it's to use a plugin called "Multisite". It allows you to set a different theme to a specific subdomain/domain. This way, you can create your protected area in another theme and serve to your users under a custom subdomain.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
