### ISSUE TITLE
Relevancy of placeholder order is unclear

### ISSUE THREAD

**Issue by tobias-kuendig** [octobercms/october#1893]
When working with placeholders the order seems to be relevant. 

In the following example the placeholder `test` remains empty:

```php
{% placeholder test %}

{% put test %}
<script>alert('test');</script>
{% endput %}
```

When placing the placeholder below the `put` statement, everything works as expected:

```php
{% put test %}
<script>alert('test');</script>
{% endput %}

{% placeholder test %}
```

Injecting into the placeholder from a partial is also only possible, if the placeholder is declared _after_ the partial is included.

The following use case is therefore not possible:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    {% styles %}
</head>
<body>
    {% partial 'gallery' %}
</body>
</html>
```

```html
<!-- partial 'gallery' -->
<div class="gallery-markup">
    <!-- ... -->
</div>

{% put styles %}
<link href="gallery.css" rel="stylesheet" />
{% endput %}
```

[The documentation mentions](http://octobercms.com/docs/markup/tag-placeholder):

> Content can then be injected into the placeholder **in any subsequent page or partial**.

Wouldn't that be the case in the above example?

Is this a bug or am I misunderstandig the use cases for placeholders?

**Comment by daftspunk** [comment]
It does raise an interesting point. The `{% placeholder %}` tag will render all the content `{% put %}` in to it beforehand. It has no way of knowing about any content added after it has rendered.

**Comment by daftspunk** [comment]
I thought about this, the reason it works is because the Page renders before the Layout.

So really, placeholders are designed for use in Layouts, for injection by Pages, or Partials that are rendered at first render.

**Comment by iboved** [comment]
@daftspunk is there any way to make it work in Partials like in Pages? Maybe there are some Events where we can generate/render Partials earlier, before the Layout (like Page)?
Thanks!
