### ISSUE TITLE
Stable branch removal broked my app

### ISSUE THREAD

**Issue by alvarezmario** [octobercms/october#1894]
Hi guys, 
Today I was trying to make a fresh install the project I'm currently working on, which is based on the now merged `stable` branch, and as the branch is merged my project is not working any more, as composer is not able to find that branch. 
I switched my project to the `develop` branch and everything but the `static pages plugin` is working. I tried to do a fast update to the `static pages plugin` code to make it work but is not as straighforward as I though. 
Can you guys please suggest a solution to me so I can get my project working again? Right now I'm locked with this issue with no idea on how to solve it :sob: 

Thanks a lot!

**Comment by daftspunk** [comment]
The plugins are getting merged today. If you update from git, pull from `master` branch, otherwise switch on `cms.edgeUpdates` to receive the compatible versions.

**Comment by daftspunk** [comment]
This is complete now. Affected plugins have been updated.

**Comment by alvarezmario** [comment]
@daftspunk thanks a lot man!
