### ISSUE TITLE
Build 319 cannot load all frontend page of theme

### ISSUE THREAD

**Issue by json-wong** [octobercms/october#1899]
Yesterday I upgrade to 319, many changes were found. but the frontend page cannot load in all themes, there display an error:

    Trying to get property of non-object
    \octobercms\modules\cms\classes\Router.php line 231
    /* The item doesn't exist in the cache, create the map*/
    $pages = $this->theme->listPages();
    $map = [];
    foreach ($pages as $page) {
        if (!$page->url) {  // This is 231 line.
            continue;
        }
        $map[] = ['file' => $page->getFileName(), 'pattern' => $page->url];
    }

the value of variable `$pages` are null:

    dd($pages)
    // output
    array(0 => null, 1 => null, 2 => null, ...... n => null)

All themes are the same problem.

**Comment by daftspunk** [comment]
Fixed by ca3e13ed330d97fab89c75cfb826a006d126ce67
