### ISSUE TITLE
Subdirectory URL without trailing slash causes 403 error

### ISSUE THREAD

**Issue by erJasp** [octobercms/october#19]
When putting October into a subdirectory, it only works when adding the trailing slash to the URL ([http://localhost/october/](http://localhost/october/)). The URL without trailing slash ([http://localhost/october](http://localhost/october)) will display a 403 error or the directory listing.

To fix this issue, add the following to the **.htaccess** file:

``` ApacheConf
RewriteOptions AllowNoSlash
```

Info: https://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewriteoptions

When installing to a subdirectory, a `RewriteBase` should also be set in the **.htaccess**. It would be great if this could be automated during the install (since it's one of my most heard questions when installing a CMS), but this might as well be just a little note in the installation doc.

**Comment by RichiUfo** [comment]
i'm sorry but can you help me  if i want to add trailing slash to url how my code must look like?

**Comment by daftspunk** [comment]
@RichiUfo try this link:
http://stackoverflow.com/questions/7780859/htaccess-rewrite-to-force-trailing-slash-at-the-end
