### ISSUE TITLE
Artisan create:plugin generates double nested directories

### ISSUE THREAD

**Issue by CptMeatball** [octobercms/october#1904]
**Build 308**
When running ````artisan create:plugin author.pluginname```` the scaffolding creates duplicate nested directories.
### Desired Result
Command:

    §artisan create:plugin author.pluginname
Output:

    /plugins/author/pluginname/updates/version.yaml
    /plugins/author/pluginname/plugin.php

### Actual Result
Command:

    §artisan create:plugin unrebel.ucseo
Output:

    /plugins/unrebel/ucseo/unrebel/ucseo/updates/version.yaml
    /plugins/unrebel/ucseo/unrebel/ucseo/plugin.php

### Notes
- This is tested on local homestead environment and production server. 
- This does not occur on local installed **build 316**
- ````create:component```` / ````create:model```` and ````create:controller```` do not show this behaviour

**Comment by jj199611** [comment]
![screen shot 2016-04-04 at 15 03 28](https://cloud.githubusercontent.com/assets/11719420/14248737/6e9cb424-fa76-11e5-9b01-4ce4ca00da29.png)

Recreated on 4-3-2016 on localhost/MAMP octobercms build 318 on OSX 10.11.3

Realised I still had the installation files and stuff in my directory but removing them didnt help.

Running artisan with sudo doesn't help either.

**Comment by daftspunk** [comment]
Reported several times before

Duplicate #1945
