### ISSUE TITLE
Repeater delete button inside modal not visible

### ISSUE THREAD

**Issue by Almusamim** [octobercms/october#1906]
the repeater delete button not visible inside a modal because of being overridden by another css class (the modal close button in the header)

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by daftspunk** [comment]
Fixed in #1998
