### ISSUE TITLE
Allows backend partials to read .php files

### ISSUE THREAD

**Issue by yourwebmaker** [octobercms/october#1908]
Backend partials (widgets and controllers) are just PHP code. 

Why not allow us to define _foo.php files instead of .htm?

**Benefits?**
PHP Syntax highlighting in editors.

**ps: Sorry for the summarized text. No time to type detailed explanation here.**

**Comment by mg-freelancer** [comment]
You mean that u need url ends with .php files instead of .htm ?

**Comment by daftspunk** [comment]
This has been discussed before. Technically it should be `_foo.html.php` and theme files should be `page.html.php.twig`.

We use the abandoned extension `htm` as an "October view file". The syntax highlighting should support: HTML, PHP and Twig combined. Sublime Text 3 had support for this but it recently broke in their latest build, still looking for a fix, we may need to create our own syntax highlighters. In the meantime we just use PHP + HTML syntax for `htm` files.

**Comment by yourwebmaker** [comment]
@mg-freelancer , @daftspunk already answered your question.

@mg-freelancer , just for you information, this is how PHPStorm currently shows partial backend files:
<img width="484" alt="screen shot 2016-04-05 at 7 10 48 pm" src="https://cloud.githubusercontent.com/assets/812971/14299697/514e3a4a-fb62-11e5-9b42-60bdbcdab20f.png">

And this is how is should do:
<img width="397" alt="screen shot 2016-04-05 at 7 13 43 pm" src="https://cloud.githubusercontent.com/assets/812971/14299746/8e29077e-fb62-11e5-904f-9ba979c233d6.png">

Backend's Partial files are just plain PHP files. I'm pretty sure it's not too hard to locate both files.

**Comment by keiosweb** [comment]
+1. Both backend partials and frontend files use .htm extension. I basically have *twig* enabled for .htm extensions in PhpStorm and my highlighting for backend files looks like on the first screenshot of @yourwebmaker 

These files have different syntax, so it makes sense for them to use different extensions. 

"There are plugins for sublime that will highlight everything" is not really the best argument, some of us still prefer IDE ;)

**Comment by daftspunk** [comment]
The hope is that one day someone will develop an October syntax parser for inline Twig + PHP together, bound to the `.htm` file extension. In which case, problem solved.
