### ISSUE TITLE
Atter update to 318 version - Class 'name' not found in .../modules/cms/widgets/ComponentList.php line 113

### ISSUE THREAD

**Issue by artras** [octobercms/october#1916]
After update to 318 version , then click to "CMS" in backend I get error

Event log: 
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'name' not found' in /home/cmsbalti/public_html/zkredits.lv/cms/modules/cms/widgets/ComponentList.php:113
Stack trace:
#0 {main}

Screen : 
https://onedrive.live.com/redir?resid=B270C705B2DAAF95!1280&authkey=!AJRkQbnOBITaq4Q&v=3&ithint=photo%2cPNG

**Comment by daftspunk** [comment]
Caused by some plugin you have installed
