### ISSUE TITLE
Backend list filter fails to show filtered options on searching, if there is already 2 (or more) active options

### ISSUE THREAD

**Issue by canthis** [octobercms/october#1918]
Probably something is wrong with **inArrayFunc** found in [filter.js](https://github.com/octobercms/october/blob/develop/modules/system/assets/ui/js/filter.js#L300).

I have played around this issue,  and replacing this:
```
var compareFunc = function(a, b) { return a.id == b.id },
    inArrayFunc = function(elem, array, testFunc) {
        var i = array.length
        do { if (i-- === 0) return i } while (testFunc(array[i], elem))
        return i
    }

filtered = $.grep(available, function(item) {
    return !inArrayFunc(item, items.active, compareFunc)
})
```

with my crappy piece of code from there [Gitlab Snippet](http://gitlab.canthis.lv/snippets/2), makes filter working as it should, when you search for new filter options, if there is already 2 or more active options.

**Comment by canthis** [comment]
In addition for this I've added ability to force Ajax request for getting filter items for particular filter. This is useful in cases, when one filters set of available items should depend on active items of another filter and you use **listFilterExtendQuery** in your controller, where you extend query like you want.

All you need to do is to define **forceAjaxLoad: true** option for particular filter scope in your **config_filter.yaml** like that:
```
auto:
    label: 'YourLabel'
    scope: YourScope
    modelClass: CanThis\Catalogue\Models\Auto
    nameFrom: name
    conditions: auto_id in (:filtered)
    forceAjaxLoad: true
```

In result you get something like this:
![Imgur](http://i.imgur.com/h3YS9Xx.gif)

I've modified two files (links are gitlab snippets of modified files):
1. [filter.js](http://gitlab.canthis.lv/snippets/3) - modules/system/assets/ui/js/filter.js
2. [_scope_group.htm](http://gitlab.canthis.lv/snippets/4) - modules/backend/widgets/filter/partials/_scope_group.htm

@daftspunk What do you think about this? Should I create a pull request?

**Comment by daftspunk** [comment]
Yes please, make sure you reference this issue in the PR.

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by canthis** [comment]
I've submitted a [Pull request to the test plugin](https://github.com/daftspunk/oc-test-plugin/pull/14) to demonstrate this issue. Steps to replicate included.

I need to mention, that I ran too far in my [second comment](https://github.com/octobercms/october/issues/1918#issuecomment-207608586) and [pull request 1990 here](https://github.com/octobercms/october/pull/1990), because everything mentioned in that comment was more about filters enhancement, which is not related to this issue, and pull request contained both - fix for this issue and that enhancement. Sorry about that mess.

As soon as bug will be confirmed I can add commit to [pull request 1990](https://github.com/octobercms/october/pull/1990) to respect newest changes in filter.js and include a bugfix only, if it would be necessery.

Regarding [enhancement](https://github.com/octobercms/october/issues/1918#issuecomment-207608586) I wrote about, as I think, it should be moved to separate issue / pull request.
@daftspunk Let me know if I'm going in the right direction.

**Comment by simonorono** [comment]
Was the `forceAjaxLoad` option merged? 

I can't find anything in the documentation. If it is not merged, how can that behaviour be achieved?

**Comment by LukeTowers** [comment]
@simonorono what behaviour? Isn't this issue resolved?

**Comment by simonorono** [comment]
@LukeTowers no. The pull request #1990 was not merged. I am referring to the `forceAjaxLoad` option.

**Comment by LukeTowers** [comment]
@simonorono create a new issue that re-introduces that feature along with an explanation of why it's required.
