### ISSUE TITLE
Fatal error: Class 'October\Rain\Filesystem\Definitions' not found

### ISSUE THREAD

**Issue by triasrahman** [octobercms/october#1928]
After I updated the october modules, there is an error:

![screen shot 2016-04-12 at 1 30 36 pm](https://cloud.githubusercontent.com/assets/7110859/14451652/f580f422-00b2-11e6-932c-20ae62e10a78.png)

I use the `dev-stable` version in my composer.json since it's used for our production app. I couldn't find the Definitions.php file in october/rain folder too.

Thanks,

**Comment by daftspunk** [comment]
Use `dev-master`

Or use `dev-develop` with `cms.edgeUpdates` config enabled

**Comment by jonpxpx** [comment]
Pretty sure this is resolved if you use composer update.

Be sure to back everything up first though.
