### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by ahlechandre** [octobercms/october#1931]
Actually this is the reality of my OctoberCMS application on Windows 10 + XAMPP 7.0.1 (`PHP Version 7.0.1`).

![october](https://cloud.githubusercontent.com/assets/7119058/14492373/3485074c-0155-11e6-9f76-25582b40503e.jpg)
![october2](https://cloud.githubusercontent.com/assets/7119058/14492374/34866308-0155-11e6-852a-f667a2b67f55.jpg)
![october3](https://cloud.githubusercontent.com/assets/7119058/14492375/348eb256-0155-11e6-9554-3d067ec416e3.jpg)
![october4](https://cloud.githubusercontent.com/assets/7119058/14492376/34984e2e-0155-11e6-8b5a-eb4cf4f7cf63.jpg)
![october5](https://cloud.githubusercontent.com/assets/7119058/14492377/349b01b4-0155-11e6-996f-1604e3c357bc.jpg)
![october6](https://cloud.githubusercontent.com/assets/7119058/14492378/349ff958-0155-11e6-975b-7d862a6b511e.jpg)
![october7](https://cloud.githubusercontent.com/assets/7119058/14492379/34d0538c-0155-11e6-8adf-0d5695759a1b.jpg)

Others `php` apps is running well on local server. This only occurs with my OctoberCMS.  

Why the reasons for this to happen? How i can prevent of happen in production? (increase the script execution time limit does not seem a good solution)

> I'm using `127.0.0.1` instead of `localhost` to connect with mysql

**Comment by daftspunk** [comment]
I would be asking myself, what process is running that is taking 30 seconds? I assure you October does not take this long to execute. It must be some problem with your web server configuration.

**Comment by daftspunk** [comment]
This would be a separate issue, but I notice you are running PHP 7. The version of Laravel used by October (Verison 5.0) has poor support for PHP 7, this will be fixed in the stable release. You can obtain this codebase by enabling edge updates.
