### ISSUE TITLE
'Customize Back-end: Styles' css no longer working after recent UI updates in dev branch

### ISSUE THREAD

**Issue by oadslug** [octobercms/october#1934]
It seems like the 'customized back-end: styles' css is no longer working after the recent dev branch UI updates. I can't tell if the custom css is not being included at all or if the order has changed, thus overwriting the custom styles. (However, no matter how I write the css selectors or use of !important it is not recognized, which leads me to believe that it's not being included at all.)

**Comment by daftspunk** [comment]
Fixed in Build 325

9fd0681ee7688e6280a6704111441a264ef93818

**Comment by oadslug** [comment]
I wasn't referring to the brand settings. I was referring to the fact that custom styles (i.e. styles defined in the 'styles' tab) don't seem to be working.

**Comment by daftspunk** [comment]
Post your CSS for testing next time. Works for me, sorry

```
.svg-icon-container.svg-active-effects {
    display: none !important;
}
```
