### ISSUE TITLE
How provide a convenient mechanism for filtering HTTP requests?

### ISSUE THREAD

**Issue by ahlechandre** [octobercms/october#1936]
How I can provide a convenient mechanism for filtering HTTP requests entering my application?

The correct would be filter the requests for each route in page `onStart()` function or using routes/middlewares?

**Comment by shina** [comment]
Using the Middleware is the best approach. Though it is not so easy like install a plugin.
Take a look at the Laravel's documentation https://laravel.com/docs/5.0/middleware

**Comment by ahlechandre** [comment]
Yeah, I really want to use it but I don't know how to delegate Middleware for each route of my CMS pages.

For example, I have a CMS page with url `/dashboard`.
* Only users with certain session key should have access.
* If the user is not authenticated, need to redirect to CMS page `/home`.

I did not find (in OctoberCMS docs) how to implement Laravel's middlewares at the right way. Can you help me with some example? .

**Comment by tobias-kuendig** [comment]
Have a look at my [Responsive Images](https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin) plugin, there I am using a middleware. 

The relevant part is in the Plugin.php's boot method: https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/blob/master/Plugin.php#L15

**Comment by ahlechandre** [comment]
@tobias-kuendig This Middleware will be called and filter all requests entering the application, right? What I need is delegate a Middleware for each route (or groups). For example, using `routes.php` in plugin folder:

```php
Route::get('/dashboard', ['middleware' => 'auth', function () {
  // This prevents the CMS to render "/dashboard" page.
  // What I need to return here in success cases?
}])
```

**Comment by tobias-kuendig** [comment]
You could use `$request->getPathInfo()` in your middleware to check if the visited page is restricted. 

Then do your checks and prevent access if needed.

```php
class GuardCMSPagesMiddleware
{
    public function handle($request, Closure $next, $guard = null)
    {
        if ($request->getPathInfo() === 'dashboard' && ! Session::has('token-or-whatever')) {
            // Redirect to a access denied page
            return redirect('/403');
        }
       
        // Allow access to this page
        return $next($request);
    }
}
```

This is untested, but something linke this should work.

**Comment by ahlechandre** [comment]
@tobias-kuendig But what I need to return in `Route` callback function?

**Comment by tobias-kuendig** [comment]
If you only need to protect cms pages maybe it's easiest to create a custom component and add that to the pages that need to be protected.

Do your authorization checks in the `onRun` method and return a redirect to disallow access:

```php
public function onRun() {
    if($notAllowed) {
        return $this->controller->run('403');
    }
}

**Comment by ahlechandre** [comment]
@tobias-kuendig Oh yeah, actually I'm using this way.

**Comment by ahlechandre** [comment]
Finally found:

`routes.php`
```php
  Route::get('/dashboard', ['middleware' => 'MyMiddleware', function() {
    // This callback function is called only if middleware handle 
    // returns $next($request).
    // Apparently, here is what I've searched.
    return App::make('Cms\Classes\Controller')->run('/dashboard');
  }]);

``` 

`MyMiddleware.php`

```php
use Closure;

class MyMiddleware {

  public function handle($request, Closure $next) {

    // The function/method/whatever to check if user is authenticated.
    if (!isAuth()) {
       return Redirect::to('/403');
    }
    // All right, invokes the callback function of Route.
    return $next($request);
  }
}
```

**Comment by ahlechandre** [comment]
Finally found:

`routes.php`
```php
  Route::get('/dashboard', ['middleware' => 'MyMiddleware', function() {
    // This callback function is called only if middleware handle 
    // returns $next($request).
    // Apparently, here is what I've searched.
    return App::make('Cms\Classes\Controller')->run('/dashboard');
  }]);

``` 

`MyMiddleware.php`

```php
use Closure;

class MyMiddleware {

  public function handle($request, Closure $next) {

    // The function/method/whatever to check if user is authenticated.
    if (!isAuth()) {
       return Redirect::to('/403');
    }
    // All right, invokes the callback function of Route.
    return $next($request);
  }
}
```
