### ISSUE TITLE
[Website] Separation of Plugin-Docs for "Front" and for "Back" Developers

### ISSUE THREAD

**Issue by w4tsn** [octobercms/october#1937]
[low priority] 
Hey there,

it may be useful to separate the documentation of how to use the plugin in the page and it's components and how to extend it or use it in development. Dividing the docs into a front-end and a dev part could make things more clear.

Saw already that a toc is planned, but I think of a logic separation.

What do you guys think?

**Comment by daftspunk** [comment]
Currently the "CMS" section is for the front-end part, the rest is the dev part.

**Comment by lionax** [comment]
Sorry, my Question is badly written and leads to misunderstanding. I don't talk about the docs at Support/Documentation, these are great.

My Question aims at the Plugin-Repository of OctoberCMS.com. E.g. at the RainLab/User Plugin-Page https://octobercms.com/plugin/rainlab-user there is a short overview and a Documentation page. The Docs page only covers topics for front-end development, for integration into a page or use.

A separate section for backend developers who want to use and extend that plugin would be helpful. Giving a more in-depth view of the mechanics of that plugin.

I hope this makes it more clear. Updated the Issue Header accordingly.

**Comment by LukeTowers** [comment]
This would be better solved by the advent of inline code documentation as currently implemented on the October core via https://octobercms.com/docs/api but for plugins.
