### ISSUE TITLE
Translatable Richeditor buttons.

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#1941]
I can't find a way to translate richeditor buttons. Only mediamanager buttons are translatable, but others are hardcoded in redactor.js and only english translatation is available.

**Comment by daftspunk** [comment]
Have you tested this in the latest build, I think they are translated now.

Enable `cms.edgeUpdates` in the config.

**Comment by mplodowski** [comment]
Yeah latest build with `cms.edgeUpdates` has been translated.

Thanks
