### ISSUE TITLE
DeferredBinding cleanup not compatible with sqlite

### ISSUE THREAD

**Issue by jBOKA** [octobercms/october#1944]
The `cleanUp` function for deferred bindings is not working with sqlite.
https://github.com/octobercms/library/blob/master/src/Database/Models/DeferredBinding.php#L84
The SQL statement
`ADDDATE(created_at, INTERVAL :days DAY) < NOW()` doesn't work, I think it's the `ADDDATE` function which doesn't exist in SQLite.

**Comment by SeriousKen** [comment]
I've hit this issue. `ADDDATE` seems to be a MySQL only, its `DATEADD` on Microsoft SQL and `date` in SQLite.

**Comment by LukeTowers** [comment]
@SeriousKen @jBOKA does https://github.com/octobercms/library/pull/271 fix this for you?

**Comment by SeriousKen** [comment]
This solves it for me, thanks

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/library/pull/271
