### ISSUE TITLE
Hovering onver dropdown items in the RTE causes flicker in Firefox

### ISSUE THREAD

**Issue by blnkt** [octobercms/october#1946]
In Firefox 45.0.2, when creating or editing a text content block for a page, if I attempt to insert or edit a link, or insert a table (i.e. any RTE option involving a dropdown) the modal for the editor and the dropdown both experience wild and disruptive z-index and/or positioning problems.  To reproduce, start with a vanilla install, create a new page, add a standard text content block, enter some text, place the cursor on a chunk of text, and click the table button or the link button in the RTE toolbar.  It's hard for me to explain exactly what I mean by flickering so I've included a GIF to better illustrate this issue.  There are no errors in the console.
![firefoxoctoberbug](https://cloud.githubusercontent.com/assets/8166060/14623275/8a887e92-0585-11e6-9f51-bf0c12bc18c1.gif)

**Comment by daftspunk** [comment]
I think I know why this happens, it's because a new "canvas" is drawn inside the modal and it throws off all the JS calculations.

See https://github.com/twbs/bootstrap/issues/15856 for more details on this.

**Comment by daftspunk** [comment]
This should be fixed in the stable release.
