### ISSUE TITLE
On upgrade to build 318 got mcrypt_get_iv_size(): Module initialization failed

### ISSUE THREAD

**Issue by scosist** [octobercms/october#1947]
Used composer to install:
`composer create-project october/october october-dev dev-develop`

I'm using `dev-develop` in this case. What happened to the stable branch (dev-stable on packagist)?

During an upgrade in the backend interface I got the following error:
```
mcrypt_get_iv_size(): Module initialization failed
/var/www/october-dev/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php line 303
```

Recently upgraded from debian wheezy to debian jessie and thought maybe this might be related to the notices given in relation to the PHP upgrade and changes with mcrypt.

To clarify, mcrypt had already been installed and enabled:
```
apt-get install php5-mcrypt
php5enmod mcrypt
service apache2 restart
```

I tried `php artisan key:generate` first as recommended [here](http://stackoverflow.com/questions/23997121/lamp-laravel-errorexception-mcrypt-get-iv-size-module-initialization-failed) but that didn't seem to help.

Other recommendations were to change the [cipher](http://laravel.io/forum/05-30-2014-mcrypt-error-after-new-pc-laravel-installation) in config/app.php to a [constant](http://stackoverflow.com/questions/14005669/php-mcrypt-keeps-throwing-module-initialization-failed-warning/22651645#22651645):
```
    'cipher' => MCRYPT_RIJNDAEL_256,
```
Once I did that I was able to proceed with the upgrade. I would submit a PR, but not sure if this or something else should be done to properly solve the issue.

(Accidentally posted to the builder-plugin repository rainlab/builder-plugin#76 for anyone that lands there.)

**Comment by daftspunk** [comment]
Pull master

Or pull develop and enable cms.edgeUpdates in config

**Comment by scosist** [comment]
Thanks, that did the trick.

Just have to be sure to enable `edgeUpdates` before running updates otherwise you may get stuck at build 318 with the above error.

**Comment by alexbom** [comment]
I have the same problem. Everything tried.
I've got legacy project without initiated Git.
How can i resolve this error without "pull master"?
Maybe i can just copy some directories from the repo?

**Comment by LukeTowers** [comment]
@alexbom if you haven't used encryption anywhere in your legacy project I would recommend that you change the value of `cipher` in config/app.php to `AES-256-CBC` and then run `php artisan key:generate`

**Comment by alexbom** [comment]
Thanks! I've did this already. But no profit.

**Comment by bennothommo** [comment]
@alexbom Would you mind either doing a `phpinfo()` or running `php -i` in your console, and screenshot which ciphers are available on your system? They should be listed within the **mcrypt** section.

**Comment by alexbom** [comment]
![Снимок экрана от 2020-01-16 17-46-24](https://user-images.githubusercontent.com/1853593/72594093-a8f6d080-3917-11ea-9a48-8d81ce7f3fdd.png)

**Comment by bennothommo** [comment]
@alexbom You should be able to use the `MCRYPT_RIJNDAEL_256` constant as the cipher, but note that your `mcrypt` install is very out-of-date and it's generally recommended to keep up to date with the latest security practices. I would recommend, if possible, getting your PHP installation upgraded to at least 7.2 as soon as possible to take advantage of better encryption libraries.

**Comment by alexbom** [comment]
I've tried this, but got the different Error:

Function mcrypt_get_iv_size() is deprecated
/home/c/cc77564/public_html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php line 303

And ciphers didn't changed after updating PHP to vesion 7.2:

![image](https://user-images.githubusercontent.com/1853593/72610581-d30cba80-3938-11ea-9b5a-ba70db538018.png)

It's simple hosting, so i can't install new PHP modules. Do i have to buy VDS for configure this out?

**Comment by LukeTowers** [comment]
@alexbom my recommendation would be to either contact your PHP host or switch to a better PHP host. When October upgrades to Laravel 6 the minimum PHP version will be 7.2 and you'll want it to be properly setup to support future updates. Since you're already taking the time to upgrade the legacy project you might as well take it all the way to PHP 7.4 for the maximum amount of longevity.

**Comment by alexbom** [comment]
Thanks, Luke! Change PHP version is not a problem, but is not decision )

**Comment by LukeTowers** [comment]
@alexbom that should do the trick unless you have something else using the old function. What's the full stack trace?

**Comment by alexbom** [comment]
@LukeTowers You can find full stack here: http://cc77564.tmweb.ru

**Comment by LukeTowers** [comment]
@alexbom something's screwed up with your installation, that code was removed in Laravel 5.2. You're not running the latest version of October.

> I've updated October to the last version, but it didn't help.

How did you perform the update? And what version of PHP were you using when you performed the update?

**Comment by alexbom** [comment]
@LukeTowers backend/system/updates shows my current build is 458.
From this page i activated "Check Updates" and then just "Update".
PHP version was 7.0 at those moment.

**Comment by LukeTowers** [comment]
> backend/system/updates shows my current build is 458.

TBH that is useless, all it does is ask the marketplace server what the latest build was when you updated last and say it has that.

If you're comfortable using composer I would recommend using the composer.json file from the main repo in your project and running composer update.

**Comment by alexbom** [comment]
Now there is composer update error:

![image](https://user-images.githubusercontent.com/1853593/72850419-1f9a2200-3cba-11ea-83c3-3bacfdcfd8b3.png)

Do i really need exact 7.1.3 PHP version for this?

**Comment by LukeTowers** [comment]
@alexbom can you show me your composer.json file? You shouldn't be pulling in Laravel 5.8

**Comment by alexbom** [comment]
I've took this one: https://github.com/octobercms/october/blob/master/composer.json

**Comment by bennothommo** [comment]
@alexbom the `master` branch has been updated with a fix to the version constraint for Laravel. If you pull in the changes, that should fix the Composer issues above.

**Comment by alexbom** [comment]
@bennothommo Thanks! But i've got legacy project without initiated Git.
How can i resolve this error without "pull master"?
Maybe i can just copy some directories from the repo?

**Comment by alexbom** [comment]
@bennothommo I've updated files from /modules/ directory, but it didn't help. What files i need to refresh for solving the problem?

**Comment by LukeTowers** [comment]
@alexbom you need to make sure the latest change to the composer file `^` to `~` is present in your composer file (see https://github.com/octobercms/october/blob/develop/composer.json#L41) and then run composer update.

**Comment by alexbom** [comment]
@LukeTowers Thanks, Luke! Now error changed.

![image](https://user-images.githubusercontent.com/1853593/73143039-834f9100-40a6-11ea-8190-86ce591b0487.png)

**Comment by LukeTowers** [comment]
@alexbom now the problem seems to be a plugin or your composer.json that's requiring too low a version of Laravel. Can you post your composer.json file and the list of plugins used and attempt to update them all to the latest versions (manually if possible, if not disable them until you get the site working and re-download the latest versions)?

**Comment by alexbom** [comment]
@LukeTowers I've used current version of composer.json from master, but changed laravel version: "laravel/framework": "~5.5.40" All other rows of composer.json exactly the same. Here list of plugins.
gromit - is plugin for projects & categories management, created by previous programmer. I don't know, if it's possible to update the plugin. So hard... I just tried to move an October project from one server to another...

![image](https://user-images.githubusercontent.com/1853593/73217492-151fd280-4169-11ea-8b27-cccbd2b0fd22.png)

**Comment by LukeTowers** [comment]
remove the idehelper plugin. It shoudn't be on a production site anyways and you can get a newer version later. Once you've removed it run composer update again.

**Comment by alexbom** [comment]
@LukeTowers Thanks! It helped. But now when i'm openning the site, there is 500 error. And the message in error_log:

[Tue Jan 28 02:14:47 2020] [error] [pid 12382] sapi_apache2.c(351): [client 217.66.152.205:59494] PHP Fatal error:  require(): Failed opening required '/vendor/symfony/var-dumper/Symfony/Component/VarDumper/Resources/functions/dump.php' (include_path='.:/opt/php72/share/pear') in /vendor/composer/autoload_real.php on line 55
