### ISSUE TITLE
Build #325 breaks cloud media manager - S3

### ISSUE THREAD

**Issue by rajakhoury** [octobercms/october#1948]
My site updated automatically to the latest build #325 and I can't access anymore the media manager configured with Amazon S3.

Error : Class 'League\Flysystem\AwsS3v3\AwsS3Adapter' not found

Post on Forum : http://octobercms.com/forum/post/octobercms-update-build-325-breaks-media-manager-in-the-backend

I reinstalled the October Drivers and checked all config to S3 and everything seems OK. This happened right after the auto update. I tried to update for the October Drivers package but no success.

Can you please check it out or tell me how to roll back to the previous build ?

**Comment by daftspunk** [comment]
Update to October.Plugins v1.1.1 and it should be fixed.

**Comment by rajakhoury** [comment]
Thank you Samuel! Updating to v.1.1.1 fixed the issue
I like the new UI changes, keep up the good work

**Comment by daftspunk** [comment]
<3
