### ISSUE TITLE
Getting error in 'Settings: Front-end Theme' tab (Build 325)

### ISSUE THREAD

**Issue by oadslug** [octobercms/october#1950]
Getting the following error when clicking on 'Settings -> Front-end Theme' (Build 325 - edge updates):

We're sorry, but an unhandled error occurred. Please see the details below.

A colon cannot be used in an unquoted mapping value at line 2 (near "description: Demo OctoberCMS theme. Demonstrates the basic concepts of the front-end theming: layouts, pages, partials, components, content blocks, AJAX framework.").
/Applications/MAMP/htdocs/pinazangaro.october.dev/october/vendor/symfony/yaml/Parser.php line 507

**Comment by daftspunk** [comment]
I don't think it likes the dash in the description, so edit the theme.yaml file and put quotes around it like this:

```
description: "Demo OctoberCMS theme. Demonstrates the basic concepts of the front-end theming: layouts, pages, partials, components, content blocks, AJAX framework."
```

**Comment by oadslug** [comment]
I just noticed I never reported back... that was the issue. Thank you!
