### ISSUE TITLE
Media manager - can't select item by click - Build #318

### ISSUE THREAD

**Issue by kikobalco** [octobercms/october#1951]
Hi, i got one strange issue with media manager in OctoberCMS... I cant select anything uploaded by simple click. I can make it with selection, but clicks seems to be ignored. Also when im trying to use crop and insert function, its not working. When trying to do this also got this error in Chrome console

> storm-min.js?v318:1620 The select2('destroy') method was called on an element that is not using Select2.$.fn.select2 @ storm-min.js?v318:1620
> storm-min.js?v318:1621 Uncaught TypeError: Cannot read property 'destroy' of undefined

 But funny part is just coming. This bug seems to be present only on my Win10 notebook and also only in Chrome and Firefox browsers (both up to date). In Microsoft Edge and IE it's working normally. I've tested it also on two iMacs, also on Win7 and it's working fine everywhere in all browsers... except Chrome and Firefox in Win10.

Bulid 318. Blog and Pages plugin installed.

**Comment by Eoler** [comment]
> But funny part is just coming. This bug seems to be present only on my Win10 notebook and also only in Chrome and Firefox browsers (both up to date). In Microsoft Edge and IE it's working normally.

Does your Win10 notebook have touch screen?

**Comment by tsioukas** [comment]
I have a similar problem, but it's a "ghost" problem. 

I load the same site  on Windows 7 & 8 & 10 in different machines (real os and virtual) and all browsers, but in some machines click it works and in some it doesn't (i test it on over 10 OS windows and android). The browser version doesn't seems to change anything. The only way to select a file is with keyboard arrows.

There is no extensions that blocks something and I try to close firewall and antivirus.

Also crop and insert button it works, but selection mode is empty and with/height. disabled.

It looks a random problem and I didn't discover any pattern.

**Comment by kikobalco** [comment]
@Eoler Yes, my notebook have touch screen. Yesterday at later time i also tried it on my friends notebook with win10 touch screen and its not working there niether. But its also fun that its working with touch. With touch I can select that item, with click nope.

But crop & insert not woking although. Actually, my crop & insert selection will crop selected image, but then it wont do nothing more. It will not put it it the place and also after that, pure Insert button stop working too :/

But, as you @tsioukas said, its kinda ghost problem. At least I don't see any patterrns except it's messing up on touch Win10 in Chrome & Firefox. But this pattern doesn't make sense to me :/

**Comment by gavinworks** [comment]
Having this issue too. Husband and Wife team who are clients of mine complained about the issue. After digging around in chrome developer tools figured it was a touch issue. Both of them are using touch enabled laptops on windows but not using touch when the error occurs, using mouse via touchpad and external mouse. Only browser affected is chrome. Not tested on firefox. Works fine in IE (which they hate using!).

**Comment by kawhite** [comment]
I've got a client with this issue as well, Windows 10 and Build 318, and I'm betting a touch screen. In their case it's also failing to register a click to select a media item in both Firefox and Chrome. I'm going to dig a bit through the js to see if that's the issue. I'm betting the browser is reporting a touch screen and somewhere in the js it's intercepting both the touch/click events.

**Comment by acasar** [comment]
Same issue here - chrome + touch enabled screen.

**Comment by loic294** [comment]
Same here on a laptop with touch screen. Windows on Chrome and Firefox.

**Comment by loic294** [comment]
One workaround that I found is to use the touchscreen to select a file and then I click 'Insert'. I doesn't seem to work, but now if you click cancel the file changed.

**Comment by acasar** [comment]
Found a bit better wokaround -> just disable touch events in Chrome.

Go to chrome://flags, search for #touch-events and disable the setting. This makes media manager behave as it should.

**Comment by Sennevds** [comment]
#1995 Same problem. Is there any progress on this bug because we have several users with touchscreen laptops who can't select with mouse?

**Comment by daftspunk** [comment]
Duplicate #1995 - Bumped the priority

**Comment by Sennevds** [comment]
If you have a touch screen enabled laptop go to the media manager with Chrome or Firefox and try to select a file( image, sound file, video etc) with the touchpad or mouse. You will notice you can't select anything. The only way to select something is by dragging, using the arrow keys or using the touch screen.
I'm currently  using build 380

**Comment by daftspunk** [comment]
Tested using Chrome, Device emulation: iPad (1024x768)

#### Replication instructions

1. Click "Media" in the back-end navigation
1. Ensure some files are uploaded and folders exist, if not, create them
1. "Touch" on any file (file is selected, file preview opens)
1. "Touch" on a folder (folder is selected, file preview opens)
1. "Double touch" on any item (nothing happens, unable to open folders)

#### Issue found

Unable to open folders on a touch device.

Is this the issue everyone is experiencing?

**Comment by acasar** [comment]
@daftspunk 

The problems I am experiencing are a bit different. You can replicate them on a non touch screen PC like this:

1. Open Chrome and go to chrome://flags
2. Find the setting "Enable touch events" and select "Enabled"
3. Restart Chrome as prompted

When you go to the October media manager, you will see that files and folders cannot be selected with a mouse.

**Comment by gavinworks** [comment]
@daftspunk yes, this is the issue we're experiencing. The issue also exists when the device (in our client's instance a PC) has a touch enabled screen but using mouse/keyboard input methods. In other words, the issue is not limited to devices using touch as the method of input exclusively.

**Comment by Sennevds** [comment]
No it depends on the Touch events enabled or not like @acasar said.
Normally on chrome they default to Automatic so they are enabled if you have a touch screen enabled device. if they are enabeled you experience the problem

**Comment by gavinworks** [comment]
Yes, I took it as a given that touch events would have to be enabled in order to replicate the problem. @Sennevds comments clarify my own.

**Comment by daftspunk** [comment]
There is a lot of noise in this issue, so it has been relogged as #2490.

Thanks all for the assistance with this.
