### ISSUE TITLE
Backend less

### ISSUE THREAD

**Issue by hushulin** [octobercms/october#1952]
when I edit a less file that named october.cms in the backend context, I do not have an best way to build october.css . so , Do I install the node.js and less? un, I want to build it by php (php artisan ...) .

**Comment by hushulin** [comment]
current,I installed less.

**Comment by canthis** [comment]
Check this [Combine backend assets](https://github.com/octobercms/october/issues/828)
I've used `php artisan october:util compile assets`

**Comment by hushulin** [comment]
@canthis thank you,I will try it.
