### ISSUE TITLE
Multiple instances of same placeholder

### ISSUE THREAD

**Issue by jeremymouton** [octobercms/october#1953]
Is it possible to output the placeholder in two different spots in the same layout?

For instance:

```
<!-- First Quote placeholder, only visible on large screens -->
<div class="quote u-hidden-xs">
  {% placeholder quote title="Quote" %}
</div>

<!-- Page content -->
{% page %}

<!-- Second Quote placeholder, only visible on mobile screens -->
<div class="quote u-visible-xs">
  {% placeholder quote %}
</div>
```

The second placeholder is empty. Any ways around this?

**Comment by jeremymouton** [comment]
My takeaway is that this isn't possible at the moment.

A possible workaround would be to store the placeholder content inside of a JS variable, and insert that into the second placeholder - but it's a bit messy.

**Comment by hybridvision** [comment]
You might be able to access the data from the PHP section of the layout and store it in a variable that you can pass to the layout but it seems like a bit of a roundabout way of doing things. Have you tried setting a variable from within twig? I'm not sure exactly how you would capture the content but there's a placeholder() function for checking if it exists so maybe there's more possible.

Probably the easiest is just to duplicate the element in the DOM using JS... You'd also save sending the content twice that way.

**Comment by jeremymouton** [comment]
Thanks for the tip on using Twig.

I solved it by doing: 
```
{% set quote = placeholder('quote') %}
{% placeholder quote title="Quote" %} // first placeholder on layout
{{ quote|raw }} // use for 2nd, 3rd... placeholders
```

**Comment by hybridvision** [comment]
Nice one :) Glad you got it figured out and thanks for the update with the solution!
