### ISSUE TITLE
create:plugin not working correctly on Unix

### ISSUE THREAD

**Issue by trsh** [octobercms/october#1955]
php artisan create:plugin Foo.Bar creates structure:

/plugins/foo/bar/foo/bar$ 

what of course does not work (have to fix manually).

System: Ubuntu 16.04

**Comment by marcoskubis** [comment]
Same problem here. 
System: Windows 10. 
Did you solve this issue?

**Comment by daftspunk** [comment]
Duplicate of #1945

**Comment by samuelmolinski** [comment]
I see lots of referencing of this as a duplicate issue. Where is the original issue and has it been resolved?

**Comment by daftspunk** [comment]
Sure, it was fixed in https://github.com/octobercms/library/commit/9db58ff6d3345855d4539e44960b1afb2314dcd0

**Comment by trsh** [comment]
Thanks
