### ISSUE TITLE
Explore idea of remove author name from backend URLs

### ISSUE THREAD

**Issue by trsh** [octobercms/october#1956]
When I use the command line "php artisan create:plugin darkweider.shop" I get kind of author-egocentric :)) file structure like darkweider/shop, what is I can live with. Probem is with URL's. 

URL's like /admin/darkweider/shop/orders does not make any sense at all (maybe for personal use only). Therefore I'm forced to rename what was tough a AuthorName to something that makes the URL more readable and acceptable for clients, like "/admin/e/shop/orders". This has consequences:  

1) Now author name is "e" what is not logical (it's not authors name) - especially not cool if I decide to publish the Plugin.
2) Unnecessarily longer URL. I think it's enough with the pluginName. 

So, as I think 90% DEV's will put something other in the AuthorName place, maybe it's worth to refactor? My proposal is:

a) Short term - authorName could be renamed to Package name, as it is more often the case... And make authorName for plugins deprecated. 
b) Longer term - remove authorName from plugin architecture (it stays can rest in Plugin.php).

----- UPDATED

In the struggle for PluginName uniqueness:

a) Don't bother - select, select2, e-shop, e-shop-extra is fine, always has been. AuthorName as additional info can help.
b) Let DEVS to customize the URL as they want And still refer to the correct controllers. Nowadays it's should not be rocket science. I see this a lot in other frameworks.

**Comment by tsioukas** [comment]
The logic behind this architecture is to avoid conflict between plugins, not custom plugins but for external. Also if you see how backend routing works, with this feature can easily connect url request with plugins.

But I agree, isn’t pretty for customers to see this kind of url, and creates a mesh in admin logic when custom urls created. For me I use data as author name and the name of plugin for each main feature that I create. So I have a url like cms/data/pluginname/option.

Maybe we should go to an intermediate step. 

One of my ideas is to create a plugin that collects all installed plugins and create a re-route feature. So each admin can control backend SEO appearance without conflicts or changes in real plugin url (this also will solve compatibility problems with old plugins). 

I don’t know if this is possible but it;s a simple solution to have it both.

**Comment by trsh** [comment]
I haven't seen the code. But mostly it's same thing. Server side receives URL, parses it, and then there is some underlying logic that finds the according Controller taking that data into account. What is need to done, is a possibility to inject some piece of logic, that can overrides/determinate those rules.

**Comment by trsh** [comment]
Somewhere in http://localhost/admin/system/updates/details/october-demo a input, named "Rewrite url". The current one as default. Django CMS had suck a feature :), was working well.

**Comment by daftspunk** [comment]
It's an interesting topic, really. If we introduced a feature for this, what is to stop two authors from reserving conflicting URI patterns? The author name is the important key to prevent this, since it acts like a unique domain name.

**Comment by trsh** [comment]
If two routes the same:

1) Priority for Default plugin URL
2) Show warning / exception

It's up to admin to fix that.

**Comment by LukeTowers** [comment]
Honestly, I don't think that 'messy urls' are a problem for most end users. Sure, for us as developers its slightly annoying to see something that looks slightly messy in the URL structure (our author name), but so many users don't even know what the URL bar is for let alone care about what's in that bar. Just look at websites that don't even implement pretty URLs, instead putting state information in the URL. Doesn't seem to affect the users of those sites.

In essence, I don't see this as an issue to continue having the author name in the URL.

**Comment by daftspunk** [comment]
I have given this some more thought, it theoretically is possible to remove the author name from the URL and just use the plugin name. If there is a conflict then the functionality would revert to what we have now. It would involve some URL rewriting in the `Backend::url` which could get messy, but it's worth a shot. We'll leave this open to try it one day.

**Comment by trsh** [comment]
@LukeTowers 

> but so many users don't even know what the URL bar is for let alone care about what's in that bar

Interesting. How they input the address in first place, to start working? You talking a little bananas here.

> Just look at websites that don't even implement pretty URLs, instead putting state information in the URL. Doesn't seem to affect the users of those sites.

Of course. Popular systems can do all kind of things, as there are so much pulled in users, that are used to it. But I think in terms of something new & fresh - we have to set the Bar higher.

> In essence, I don't see this as an issue to continue having the author name in the URL.

In most cases maybe not. Especially if it's some blog, or personal/friends side. In big companies, client has own IT department, that constantly questions the product. And so it was in my case

**Comment by LukeTowers** [comment]
@trsh Good to have your input on the subject. In my case, most of my clients are not very technically inclined (a lot of small business type setups), which is where I'm coming from with my comments.

I can understand your use case differs though. I think @daftspunk's solution should be good, my only concern would be the number of different places where plugin authors can place URLs within their plugin. We could eventually provide support for plugin authors to create their plugin's with the ability to be referenced without the author name in the URL, but I don't see that ever being something that we could enforce on all plugins carte blanche without modification from their authors.

I don't have time to dig further into a solution for this right now, but yeah, leaving it open for future work on the topic is a good idea.

**Comment by barryrld** [comment]
I too would second this as a feature request. In fact, I'm willing to put in some time to try to make this happen with a pull request if @daftspunk can point me in the right direction as to what you were thinking a good solution might be.

FWIW, coming from the Drupal world, it's possible for many module maintainers to arbitrarily define backend paths. In my 10+ years experience in Drupal development, the issue of URL clashes hasn't come up in my travels; that's not to say it's not a concern. If a clash exists for October then perhaps the fallback Samuel suggested to full namespaced URL would be a graceful way of handling the edge cases.

What can I do to progress this issue?

P.S. As I'm still getting familiar with October's internals [and this is my first post on this repo's issue queue] I'd like to say a big thanks to Samuel and Alexey for all your efforts to date in building and fostering this great software. The documentation is extremely succinct helpful. I'm enjoying the simplicity and power October offers when compared to the legacy "behemoths" in town! I hope to become more involved in the October community and helping where I can. Cheers!

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by LukeTowers** [comment]
@barryrld the routing for backend requests happens here: https://github.com/octobercms/october/blob/master/modules/backend/routes.php. It passes any backend request to `\Backend\Classes\BackendController` which then handles the request within the `run()` method where it attempts to route the request to either a module or a plugin to be handled by a controller that extends `\Backend\Classes\Controller`. https://github.com/octobercms/october/blob/master/modules/backend/classes/BackendController.php#L98-L114 is where the controller detection is run, so if you added your detection based on plugin name alone in there; that could work.

**Comment by DanHarrin** [comment]
Hey @LukeTowers, I'm currently working on a PR for this, mind checking it out when I release it? What I'm doing works, but I'm not sure if my solution is the simplest way to implement this or not.

**Comment by LukeTowers** [comment]
@DanHarrin sure, I review every change made to the core so I'll see it when you submit it :)

**Comment by DanHarrin** [comment]
I've pushed some very rough changes in #4538 if anyone is still interested in this issue.

**Comment by LukeTowers** [comment]
Going to archive this request for now. I personally don't really see a benefit from making this change, especially as browsers (for better or for worse, I personally think it's worse but whatever) have started to hide the full URL more and more from end users).
