### ISSUE TITLE
Backend Nested Relations

### ISSUE THREAD

**Issue by ebhoren** [octobercms/october#1959]
I'm looking for a tuto/example on how to build nested relations on backend.
I'm developing a plugin as a learning experience (https://github.com/ebhoren/octobercms-nested-relations) and i need to create nested relations.
## Actual result
1. Select the **Hockey Glove** product. 
2. Go to **Layers** tab. 
3. Click **Finger** layer. A popup form should appear. 

As you can see, each layer can be available in 6 various colors. Each colors is displayed in a checkbox.
## Expected result

The colors relations look good if we have a small number of colors. It would be better if we could **add|remove** color associated with this layer with a complete October back-end list view.  

I usually do this by creating a partial that render relation using:  
<?= $this->relationRender('layers') ?> in a controller.

Which looks like this:  
![alt text](https://www.dropbox.com/s/jw5doc3876yi7jg/Screenshot%202016-04-25%2018.24.41.png?dl=1)
![alt text](https://www.dropbox.com/s/72kqsmissdtolp1/Screenshot%202016-04-25%2018.29.01.png?dl=1)

Anyone know how to do this kind of relations inside another relations?
Thanks

**Comment by Teranode** [comment]
I also have a question relating to nested relations. Is it possible to have a nested partial within a partial relation?

I tried it and what its giving me is the primary nested partial's fields and columns: Screenshot below 
![](http://image.prntscr.com/image/d7087e86db1b469ca1753f25c1cba344.png)

**Comment by o-leary** [comment]
I'm also stuck on this one. At the least it would be good to be able to link to another controller in an embedded list (using a partial to display a relation list, in which records have other hasMany relations). If we can do this and change the selection behavior from showing a form (which will not currently work as the relation in the form belongs to the current controllers models relation, not the current model), to a link with the records id, then we can simply link to plugin/othercontroller/update/:id and work around it.

Any tips on how to do this?

**Comment by ebhoren** [comment]
Any comeback on this?
Can someone take a deeper look into this? I'm stuck on this problem for months.
Any help would be really appreciated.
Thanks

**Comment by Teranode** [comment]
@ebhoren I dont know if it would help but the solution i came up for my plugin is that I had let the primary  controller (shows) use the seasons and the episodes as partials (so they get their individual tabs)

and to gather the raltion within the relation for example a dropdown relation within the relation. I went into the nested relation's model thats requesting another model's relation and did this:

`    
    public function getSeasonOptions()
    {
        return Season::where('show_id', Request::segment(6))->lists('title', 'id');
    }
`

i used Request::segment() to get a specific relation based on the relation to the show. IT's the only solution i have come up with and it works. The segment finds the id within the update url ( so this can only be done within updates.)

**Comment by ebhoren** [comment]
@Teranode could you provide more code about your solution? I'm struggling to understand your solution.
Thanks

**Comment by chesterx** [comment]
is there any progress about this issue?

**Comment by ebhoren** [comment]
@chesterx No progress at all.

**Comment by daftspunk** [comment]
Related issue #2567

**Comment by daftspunk** [comment]
The Relation Controller support does not appear to support nesting. We will look at writing a tutorial on how to address this soon.

**Comment by daftspunk** [comment]
Just a heads up, nested relations probably won't be supported. Behaviors are designed to be helpful in speeding up development, not as the answer to every possible implementation.

We are working on a series of screencast tutorials that describe this in more detail. See the following repo for more details: https://github.com/daftspunk/oc-formist-plugin

Thanks @abstractFlo for providing the basis for this plugin.

**Comment by daftspunk** [comment]
This has been covered in the Beyond Behaviors screencast series:

- http://octobercms.com/support/article/ob-19
- http://octobercms.com/support/article/ob-20
- http://octobercms.com/support/article/ob-21

Enjoy

**Comment by abstractFlo** [comment]
This series open my mind with october. Thats so awesome, after understand the technology behind october magic :D

**Comment by AugmentBLU** [comment]
The Beyond Behaviors series was helpful - just wondering if you able to give a quick example or point in the direction of how we can tackle having a `belongToMany` or `morphToMany` relation in a popup? 

I see we can build out the list the same was as outlined in the series, however - how do we use `add` or `link` existing records which would open in another popup, with a list of available, selectable records. 

Thanks!

**Comment by paishin** [comment]
@AugmentBLU I know this is an old post, but your question is still relevant to me today. As I see no one had replied to you, did you ever happen to find a solution?

Does anyone now have a solution on how to work with nested relationships? Has it been addressed in newer releases?

**Comment by SebastiaanKloos** [comment]
> @AugmentBLU I know this is an old post, but your question is still relevant to me today. As I see no one had replied to you, did you ever happen to find a solution?
> 
> 
> 
> Does anyone now have a solution on how to work with nested relationships? Has it been addressed in newer releases?
> 
> 
Take a look at the following page:

https://octobercms.com/support/article/ob-21
