### ISSUE TITLE
Bug in Resizer crop mode (develop Branch)

### ISSUE THREAD

**Issue by ekrokowski** [octobercms/october#1962]
After #1957 got fixed I noticed another bug in Resizers resize() method when using **crop** mode. 

https://github.com/octobercms/library/blob/develop/src/Database/Attach/Resizer.php#L210

`$offset` is not defined in that method. Inside the crop if block, there should be `$offset = $this->getOption('offset');`

**Steps to reproduce:**
Try to crop an image with the fix of #1957.

**Expected result:**
Cropped image

**Actual result:**
This 200x200 image:
![thumb_17966_75x75_0_0_crop](https://cloud.githubusercontent.com/assets/12029860/14832182/2c78c74c-0bf9-11e6-8773-f81e1871cd50.jpg)

**Comment by daftspunk** [comment]
Thanks for this

**Comment by amdad** [comment]
Thanks for reporting. I just stumble on this problem right now in media manager I says thumbnails for previews cannot be generated.
