### ISSUE TITLE
Sender email doesn't work if different from username, it uses username

### ISSUE THREAD

**Issue by kdoonboli** [octobercms/october#1965]
In Mail configuration, I have a different email address in the sender's email field. 
But the system emails are being sent from the 'username' field.

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by kdoonboli** [comment]
Settings -> Mail configuration 

Sender email is set to: sender@domain.com
Mail method: SMTP
SMTP address: smtp.gmail.com
SMTP port: 587
SMTP encryption protocol: TLS
SMTP authorization required: checked
Username: username@domain.com

Expected: use 'Sender email' field for system emails (user registration, activation emails, etc)
Actual: 'Username' email address is used.

Extra information: my sender email address is different from username email address. The email address I'm using is from gmail apps that has custom domain.

**Comment by gabsource** [comment]
Seems like it's the Gmail SMTP server that rewrites the sender. Try your configuration with mailtrap.io or another "normal" SMTP server. Made a test with a Google Apps account and the sender is rewritten to the main email address with account display name and what is put by PHP in the `From:` is added to the following SMTP header :
```
X-Google-Original-From : OctoberCMS <sender@domain.com>
```

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
