### ISSUE TITLE
How to install package use composer?

### ISSUE THREAD

**Issue by hushulin** [octobercms/october#1966]
I want to install a PHP SOCKET CLIENT , that name's aysheka/socket to octobercms. but I don't have any idea.

**Comment by canthis** [comment]
There's 2 options. First one is more preferable!

1. Initiate composer inside your plugin's folder. Put all required service providers in your composer.json require section. Do composer update. And lastly, register particular service provider in your plugin.php like this - [Example Plugin - Bedard Debugbar](https://github.com/scottbedard/oc-debugbar-plugin/blob/master/Plugin.php#L37)
2. Install october using [Console install](http://octobercms.com/docs/console/commands#console-install), there will be composer.json in your project's root folder, then you can require and use any service provider as you would do it on clean Laravel.

Last thing, always check [Documentation](http://octobercms.com/docs/) before asking, or use [October's IRC chat](http://octobercms.com/chat) / [forum](http://octobercms.com/forum) instead. Good luck.

**Comment by hushulin** [comment]
@canthis Thanks a lot, I get It.

**Comment by ulaskorpe** [comment]
i ve installed october , i ve installed composer and i ve downloaded a package - guzzlehttp/guzzle -  via composer and set it right
i want to use that package in my theme , but how ?  

there s no tutorial or documentation

**Comment by LukeTowers** [comment]
@ulaskorpe Use plugins for that. Themes are not meant for complicated PHP functionality, that is meant to be contained with plugins and their components. 

As a side note, take a read through https://luketowers.ca/blog/how-to-use-laravel-packages-in-october-cms-plugins/ to see the full process of using Laravel Packages in October plugins.

**Comment by daftspunk** [comment]
As above. The concept of "packages" are plugins in October, which subsequently do support composer packages in some limited fashion.

**Comment by iamike** [comment]
there is composer in my root folder is that correct?????

**Comment by iamike** [comment]
there is no composer file in my project root folder. Is that correct? or I deleted it by mistake?

**Comment by LukeTowers** [comment]
@iamike Did you install via the installer or composer?

**Comment by iamike** [comment]
from installer

**Comment by LukeTowers** [comment]
There was an issue I commented on a while back regarding your same issue. The installer installs the "consumer" version, which doesn't include the composer.json file or the tests directory. If you want to use those features, you'll need to copy them from the github into your project.

**Comment by buuug7** [comment]
i installed october via installer,i copy composer.json into my project root , when i install guzzlehttp/guzzle,it installed failed,with the message
```
Installation failed, reverting ./composer.json to its original content.
  [RuntimeException]
  Could not scan for classes inside "tests/TestCase.php" which does not appea
  r to be a file nor a folder
```
![qq 20170516114936](https://cloud.githubusercontent.com/assets/12119289/26089165/282e5ea4-3a2e-11e7-98c8-bd0eb089f105.png)

did where the problems is?

**Comment by LukeTowers** [comment]
Yes, you need to copy the tests folder from the github as well.

**Comment by buuug7** [comment]
@LukeTowers OK
