### ISSUE TITLE
Multi-language support for Carbon, used by models on the front end

### ISSUE THREAD

**Issue by amdad** [octobercms/october#1968]
Here is what I think should be consider http://twig.sensiolabs.org/doc/extensions/intl.html

Global setting for page lang should be taken from October Global setting for Frontend, and overwritten by Translate plugin when language switcher is active.

Relates to: https://github.com/rainlab/blog-plugin/issues/202

**Comment by daftspunk** [comment]
The Twig extension looks interesting. We can't use it though because it requires IntlDateFormatter which is an optional PHP module, afaik.

**Comment by amdad** [comment]
You'll find best way to achieve this. Now you aware of problem. This is very fundamental function. Must be :) 
**Thanks for answer**, now I don't need to waste more time for digging forums and docs anymore for searching solution that doesn't exist yet in October.

**Comment by daftspunk** [comment]
There is this nice looking package that extends Carbon with some localization features.
https://github.com/jenssegers/date

I will look at integrating it, it means the date formats can be
`{{ post.published_at.format('M d, Y') }}` instead of `{{ post.published_at|date('M d, Y') }}`

**Comment by daftspunk** [comment]
@amdad What locale are you needing to use for this?

**Comment by amdad** [comment]
I don't know if I understand your question here. Couse I think it should be universal. But if you mean, what languages... primary Deutsche (German), Polish.

**Comment by amdad** [comment]
It would be nice if 
https://github.com/jenssegers/date#usage 

Date::setLocale('xxl');  should be taken from another setting (than app global). in Translate Plugin we set default frontend  lang, but october itself have only one setting for global app language. It should be different setting for frontend in global settings. Joomla have different setting for front and backend default language.  

I see some coll stuff here. Will `ago` / `diffForHumans`, and the `timespan` also be supported?

**Comment by daftspunk** [comment]
Yes those things are supported.

Translate plugin uses App::setLocale() for the front end and it uses this value. So you can either set it via `app.locale` or use the Translate plugin. I tested it and it works well. I will do some testing with German and Polish today.

**Comment by amdad** [comment]
Thanks very much. Will you push it to new build today?

**Comment by daftspunk** [comment]
Yes Build 331. Please test it out too.

**Comment by amdad** [comment]
Oh happy day!! :) :clap:

**Comment by amdad** [comment]
LOL, I'm can't stop laughing. Who translate this months names?
https://translate.google.pl/#de/en/M%C3%A4rch

You did this translations? Polish is just a mess, but German is even better.

https://translate.google.pl/#de/en/M%C3%A4rch

**Comment by daftspunk** [comment]
You should submit a PR to this repo for the fixes: https://github.com/jenssegers/date

If the support is bad, we can pull the translations inside October.

**Comment by amdad** [comment]
gruember, lisember? What's that language is? Where that names come from? Github search cannot find it in code jenssegers/date

**Comment by daftspunk** [comment]
I assume 

Polish: https://github.com/jenssegers/date/blob/master/src/Lang/pl.php
German: https://github.com/jenssegers/date/blob/master/src/Lang/de.php

**Comment by amdad** [comment]
These translations looks good. But none of those names shows up when I use php date `F` ormatting.

**Comment by daftspunk** [comment]
What code are you running, sorry?

**Comment by amdad** [comment]
```php 
{{ post.published_at|date('M d F, Y') }} <br> {{ post.published_at.format('M d F, Y') }}
```

**Comment by amdad** [comment]
Both show up same result.. Language switcher works,, yes, but show up horrible funny things.
