### ISSUE TITLE
trait SelectableWidget error

### ISSUE THREAD

**Issue by odlex** [octobercms/october#1969]
I found a problem in the trait "SelectableWidget" where isItemSelected method return always FALSE:

when you put in the sessionl.48: 

`$this->putSession('selected', array_merge($currentSelection, $items));
`
and when you check l.56:
`if (!is_array($selectedItems) || !isset($selectedItems[$itemId])) 
`
but 

> array_merge 

don't keep the key value ... 

so i suggest you to use:
`$this->putSession('selected', array_merge($currentSelection, $items));
`

Alex

**Comment by daftspunk** [comment]
Not following you, sorry. How do I replicate this issue?

**Comment by odlex** [comment]
Sorry but i could not respond earlier, I just noticed that I was mislead me :s : 
my suggestion was to use :
```php
$this->putSession('selected', $currentSelection + $items);
```

i will explain me:

I would like to create a widget to place it in the sidebar of my controller (like "TemplateList" in the cms module of October Cms).

I have created a widget which use  "SelectableWidget" trait, to make ability of mass deletion of my list items.

My partial whitch render item contain:
```php
<input
                        id="<?= $cbId ?>"
                        type="checkbox"
                        name="<?= $this->selectionInputName ?>[<?= e($item->id) ?>]"
                <?= $this->isItemSelected($item->id) ? 'checked' : null ?>
                data-request="<?= $this->getEventHandler('onSelectItem') ?>"
                value="<?= e($item->id) ?>">
```
when i select item the onSelect Handler is call but it store data with 
```php
protected function extendSelection()
    {
        $items = Input::get($this->selectionInputName, []);
        $currentSelection = $this->getSelectedItems();

        $this->putSession('selected', array_merge($currentSelection, $items));
    }
```

> but array_merge don't preserve key:


**so first:**

if i select the id 1 > the session datas 'selected' will contains > [0=>1]
if after i also select the id 2 > the session datas 'selected' will contains > [0=>1, 1=>1, 2=>2]

> it duplicate data in array

**and secondly:**
when you check if it's already in session: 
```php
protected function isItemSelected($itemId)
    {
        $selectedItems = $this->getSelectedItems();
        if (!is_array($selectedItems) || !isset($selectedItems[$itemId])) {
            return false;
        }

        return $selectedItems[$itemId];
    }
```
>  store the identifier in the key of this table would add consistency to "!isset($selectedItems[$itemId])" and return $selectedItems[$itemId];

thank by advance.
Alexandre

**Comment by daftspunk** [comment]
I think perhaps your input is defined incorrectly, try this:

    <input
                        id="<?= $cbId ?>"
                        type="checkbox"
                        name="<?= $this->selectionInputName ?>[]"
                <?= $this->isItemSelected($item->id) ? 'checked' : null ?>
                data-request="<?= $this->getEventHandler('onSelectItem') ?>"
                value="<?= e($item->id) ?>">

There is no need to pass `$item->id` in the `name`, since it exists as the `value`?

**Comment by daftspunk** [comment]
Thanks for clarifying. FTFY

**Comment by odlex** [comment]
Thanks
