### ISSUE TITLE
UX: Mouse middle click for closing Tab

### ISSUE THREAD

**Issue by amdad** [octobercms/october#1970]
I always use mouse middle button (wheel click) to close tabs.Would be nice if October have that in core.

**Comment by daftspunk** [comment]
Is it possible to detect 3rd mouse click? I always thought this was controlled by the operating system. i.e not available to the browser.

**Comment by amdad** [comment]
Of course! Very simple. http://jsfiddle.net/7S2SQ/

**Comment by bcinternet** [comment]
I was just about to make proposal like this... More than few times i clicked out of habit on october tab using middle button, just to open new empty browser tab.

**Comment by AxDSan** [comment]
10/2/2017 - Still looking for this feature to be implemented.

**Comment by LukeTowers** [comment]
@AxDSan 
10/2/2017 - Still looking for a PR to be made implementing this feature.

The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by AxDSan** [comment]
FINALLY! this annoyance is over! 8648a49 should get rid of it.

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/d5829c75cf840e64f6a0af5e46e3a67a197024d6
