### ISSUE TITLE
Add option to block backend administrator

### ISSUE THREAD

**Issue by Eoler** [octobercms/october#1972]
Just finished a project for annual event and need to block "helper" temporary administrator from logging into backend. Some metadata (who changed what&when) is still relevant, so coudn't delete user. SSO is enabled so couldn't change her password.
Blocking administrators by superusers would come handy...

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by LukeTowers** [comment]
@Eoler backend users now support being soft-deleted by default which achieves the same end result (preventing logins while retaining meta-data).

**Comment by Eoler** [comment]
> preventing logins while retaining meta-data

Yes, good enough. 
Anyone tracking model changes by backend users should remember to add `withTrashed` scope to relevant relations:
```
    public $belongsTo = [
        'user' => [
            \Backend\Models\User::class,
            'scope' => 'withTrashed',
        ],
    ];
```
