### ISSUE TITLE
[Enhancement] Import process splitted to chunks.

### ISSUE THREAD

**Issue by canthis** [octobercms/october#1973]
Hey @daftspunk ! I've published my test implementation of chunk importer we talked about yesterday.
It could be found on my github [Here](https://github.com/canthis/oc-chunk-import). Take a look when You'll have some time.

There's already a test products table, model and list. In addition there's import log table, list and CSV file for testing purposes.

**Comment by jfoliveira** [comment]
That's great! A real need when importing big files!

**Comment by LukeTowers** [comment]
I agree with @jfoliveira, this is a great enhancement! It may be a while before I can review this but it would be a nice addition to October for sure!

**Comment by codengine-au** [comment]
+1 to this enhancement. Implemented in a current project - works as articulated and delivers very stable for complex big import + processing.

**Comment by LukeTowers** [comment]
@canthis could you please make a PR to bring this functionality to October?

**Comment by canthis** [comment]
@LukeTowers It was over than year ago, when I implemented this. It works, but I'm not happy with code quality and few aspects of it's current implementation. Ideally, it needs some serious refactoring. I will take a look at it as soon as I will complete my current projects.

**Comment by LukeTowers** [comment]
Awesome, thanks @canthis! Just make a PR when you're ready then :)
