### ISSUE TITLE
[Build 332] JS errors when click "new page" on CMS page

### ISSUE THREAD

**Issue by mahony0** [octobercms/october#1976]
For replication, I clicked to "Add page" button. also tried with demo theme and clicked on any page in Pages list.

![screen shot 2016-04-30 at 21 50 14](https://cloud.githubusercontent.com/assets/2674488/14937963/d7c71040-0f1e-11e6-90f4-a05b5526e435.png)

**Comment by pedzed** [comment]
What's your operating system?

**Comment by mahony0** [comment]
os x el capitan, 10.11.4 with chrome canary

**Comment by pedzed** [comment]
Did you grant it write permissions? (`ls -l` in terminal, in the root of the project)

**Comment by mahony0** [comment]
yes, not gave root but project folder has enough permissions recursively for writing

**Comment by mahony0** [comment]
also not opening demo theme's pages which already created before. this is not related with permission issue

**Comment by pedzed** [comment]
@mahony0 What version of OctoberCMS is it? And could you try it with a new (fresh) installation?

**Comment by mahony0** [comment]
It's Build 332 (dev). I went to backend-preferences and saved that page. It solved for now. Idk why, but it seems everything ok.
