### ISSUE TITLE
View not found for text-only emails

### ISSUE THREAD

**Issue by witul** [octobercms/october#1977]
When i try to send text only email using this:

`Mail::send(['text' => 'witul.contact.mail.contact'], $data, $callback);`

It shows this error:
"View [] not found." on line 137 of  .... vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php

When i change sending method to:

`Mail::send('witul.contact.mail.contact', $data, $callback);`

Sending works fine.

**Comment by daftspunk** [comment]
Try this

```
Mail::send('witul.contact.mail.contact', $data, $callback);
```

With content inside the view like this (contact.htm)
```
subject = "Message subject"
==
Text contents here
==
HTML contents here
```

**Comment by witul** [comment]
This works, but i want to send text only, not html content
Regards.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by hlev** [comment]
This still is a bug in build 434

**Comment by LukeTowers** [comment]
@hlev what do you propose as the fix?

**Comment by hlev** [comment]
@LukeTowers Have not looked at it yet, I'm fairly new to OctoberCMS but since it is a legit bug, this issue should be kept open IMHO.

**Comment by hlev** [comment]
I had a look. Here is my PR that fixes the issue. #3479

**Comment by LukeTowers** [comment]
Thanks @hlev. @witul are you able to give #3479 a try to see if it resolves the issue?

**Comment by LukeTowers** [comment]
Closed by https://github.com/octobercms/october/commit/edcc4af68aa70dc4b84b687e34edb90d14191ca0
