### ISSUE TITLE
Backport Collection wildcards and "JSON" database type

### ISSUE THREAD

**Issue by sajjad-ser** [octobercms/october#1978]
Please upgrade laravel to 5.2.
I need to use `Collections Wildcards` and `MySQL JSON Column Types` in my project can you upgrade laravel to 5.2?

**Comment by dshoreman** [comment]
October is updating to the LTS version of Laravel (5.1) with the upcoming stable release, but I doubt there'll be updates to non-LTS versions any time soon. Aside from waiting until the next Laravel LTS, the only option would be cherry-picking individual features from newer versions.

**Comment by ThinkGraphical** [comment]
What's the timeframe on the LTS release?

**Comment by jimibi** [comment]
After the next LTS release of Symfony - 3.4, in 2017.

**Comment by stijntilleman** [comment]
I think he means: When will the current LTS be supported by octobercms?

**Comment by daftspunk** [comment]
@dshoreman do you want to pick this one up?

**Comment by dshoreman** [comment]
@ThinkGraphical LTS is already in use on the develop branch, all you gotta do is enable edgeUpdates in your `config/cms.php`.

@daftspunk I'll take a look when I get some time. JSON type sounds like some grammar work, but not sure what the "Collection wildcards" is. Got a feeling it's to do with wilcard support in `Collection::where()`... @sajjad-ser could you clarify?

**Comment by sajjad-ser** [comment]
thank you for spending time 

**Collections Wildcards**
When using a collection and wanting to pull out data, you can pass a * as a wildcard:
```php
$posts->pluck(‘posts.*.title’);
```
This will return all title’s for all posts.

**Comment by LukeTowers** [comment]
Irrelevant as October now runs Laravel 5.5
