### ISSUE TITLE
set components property with post form-data

### ISSUE THREAD

**Issue by cx-emerge** [octobercms/october#1981]
```ini
title = "文章列表"
url = "/api/articles/:slug/:page?"
is_hidden=0

[blogPosts]
categoryFilter="{{ :slug }}"
pageNumber="{{ :page }}"
sortOrder="created_at desc"
postsPerPage="{{ post('per') }}"
categoryPage="articles"
postPage="article"
noPostsMessage="当前无信息"
==
```
how can i set components property with post form-data
```ini
postsPerPage="{{ post('per') }}"
```

**Comment by daftspunk** [comment]
```
==
function onInit()
{
    $this->blogPosts->setProperty('postsPerPage', post('per'));
}
==
```

**Comment by bmiskoski** [comment]
Hello i know this is a old thread but i had a question about using setProperty but from a component.

I have created a component and methods in the component class. Can i somehow use setProperty from the component methods?

When i use it in the php block in my htm page it works, but i would like to contain all my logic in the Component.

Any help will be appreciated.

Thanks in advance.

**Comment by bennothommo** [comment]
@bmiskoski we're using Discussions for all questions now. Please feel free to start a topic in here: https://github.com/octobercms/october/discussions?discussions_q=category%3AQ%26A
