### ISSUE TITLE
Validating image Dimensions(width and height)

### ISSUE THREAD

**Issue by Deathz0r** [octobercms/october#1984]
Hello, is there a way to validade image dimensions(width and height) in backend, im using fileupload field and an relation ($attachOne = ['image' => 'System\Models\File',];).

**Comment by seanthepottingshed** [comment]
+1

**Comment by nacr-dev** [comment]
+1

**Comment by nacr-dev** [comment]
@daftspunk is this correct? there is no way of validating image width and height when using fileUpload?

**Comment by daftspunk** [comment]
Correct, this feature is not supported today. Consider submitting a Pull Request or Bounty to have it implemented.

> NB: Laravel 5.2/5.3 is adding a validation rule for this very thing, we can probably backport it.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred. Also, https://github.com/octobercms/library/commit/cd59f9d6c80c8bd934974b41fae724045c86b343 probably fixes this.
