### ISSUE TITLE
Crop large images returns error code 500

### ISSUE THREAD

**Issue by marcoskubis** [octobercms/october#1985]
**_The bug ahead do not happens in localhost, only in server_**

I'm using the file upload form widget, and it works fine for small and medium images size (~ 1000x700px).

But, when I choose a image with a large size (~3000x3000px) the crop broken. Returns error code 500 with no messages.

Any ideas?

**Comment by nanohard** [comment]
Go through system logs. Apache, nginx, php, etc. Are you using the same versions of programs on the server that you're using on localhost? Are those programs built from source?

**Comment by hybridvision** [comment]
It is quite likely that you don't have enough memory to process the larger images on the server - what is the PHP memory limit? Check if it is different to your localhost...

Also, as suggested, the logs should tell you what is behind the code 500 errors.

**Comment by marcoskubis** [comment]
Exactly @hybridvision . That was it. Thank you all.
