### ISSUE TITLE
RecordFinder nulls hasOne relationship when re-saving records (Build 332)

### ISSUE THREAD

**Issue by oadslug** [octobercms/october#1986]
RecordFinder seems to be nulling relations when re-saveing records. This is happening when the relation is defined using `hasOne` (haven't tested `belongsTo` and other relation types). 

Can be reproduced in the October Test Plugin:
1. Go to 'people' tab. Select 'Record Finder View' to show RecordFinder field (if not already visible).
2. Add relation (if not already defined) to 'Record Finder' field (i.e. phone number). Save record. Reload page. 
3. Save again. Reload page. (Relation should be null)

This is on edge build 332.

**Comment by Samuell1** [comment]
Same issue +1

**Comment by Galibov** [comment]
I have this problem too

**Comment by daftspunk** [comment]
This will be fixed in Build 383+
