### ISSUE TITLE
The mail driver "log" not outputting anything

### ISSUE THREAD

**Issue by axomat** [octobercms/october#1987]
I can use the mail option "pretend" and this writes to the log file but this option does not write the content of the mail. So the laravel documentation says to use the log file driver instead which should write the content. However I cant make this work.

I am using pretend => false and driver => log.

Maybe it uses a different log file but I cant find another one.

Thanks

**Comment by daftspunk** [comment]
There is no other log that I'm aware of. Although the settings in mail.php can be overridden by the Mail settings in the back-end. This is all I can think of.

As per the contribution guidelines, please provide the exact steps you are taking for peer review.

**Comment by axomat** [comment]
Ah I did not realise that the backend mail settings override the config/mail settings. That explains it.
Thanks for your help,
