### ISSUE TITLE
new Timepicker does not have option for 24HR time

### ISSUE THREAD

**Issue by firemankurt** [octobercms/october#1989]
I need the option to have timepicker show 24HR time instead of AM/PM.  Many organizations including mine use "military time" in the USA.
I also use the timepicker to set duration in several applications and AM/PM does not make sense there.

**Comment by firemankurt** [comment]
Fields of type TIME sometimes use the time picker and the range can be larger than 24HR because this data type is intended for use as duration.

See MySQL manual quote here from http://dev.mysql.com/doc/refman/5.7/en/time.html 
------------------------------
"MySQL retrieves and displays TIME values in 'HH:MM:SS' format (or 'HHH:MM:SS' format for large hours values). TIME values may range from '-838:59:59' to '838:59:59'. The hours part may be so large because the TIME type can be used not only to represent a time of day (which must be less than 24 hours), but also elapsed time or a time interval between two events (which may be much greater than 24 hours, or even negative)."

**Comment by daftspunk** [comment]
After giving this some thought, perhaps we should just disable AM/PM all together. The analogue clock design is pretty good at representing time regardless of the format.
