### ISSUE TITLE
Themes uploaded with mirrored public folder get sent to default themes folder

### ISSUE THREAD

**Issue by siegerhansma** [octobercms/october#1991]
I have a mirrored installation on shared hosting where my public folder is 'public_html'. I install a theme from the backend and it installs it in the root themes folder. It should install in my mirrored themes folder. 

I know I am able to just do mirror again, but for clients who just want to install a different theme, this shouldn't be necessary.

**Comment by daftspunk** [comment]
The mirror command is designed for production environments. The instructions clearly state you need to run this command after updating, installing plugins or themes.
