### ISSUE TITLE
using -  fill(post())) unexpected results

### ISSUE THREAD

**Issue by jamiegrand** [octobercms/october#1992]
I have the following checkbox

`<input type="checkbox" name="is_monday" id="mon" value="1" {{ schedule.is_monday ? 'checked' : ''}}>`

if i use

```
$schedule->fill(post());
$schedule->save();
```

it will save the first time if unchecked but once checked it will not uncheck the fix is to use the following

```
$schedule->fill(post());
$schedule->is_monday = Input::get('is_monday');
$schedule->save();
```

currently using build 322

**Comment by daftspunk** [comment]
When checked post() will likely `return ['is_monday' => 1]`, when unchecked post() will return `[]`. This is the nature of HTML/PHP. Try this as a workaround:

```
<input type="hidden" name="is_monday" value="0">
<input type="checkbox" name="is_monday" id="mon" value="1" {{ schedule.is_monday ? 'checked' : ''}}>
```

This will account for when the input is unchecked and will ensure a value is always passed.

**Comment by jamiegrand** [comment]
thats great thanks and does work , although not sure if its better to pad out the html with hidden fields rather then use Input ::get()

Thanks Jamie

**Comment by daftspunk** [comment]
Choice is yours, really.
