### ISSUE TITLE
How import non CSV files?

### ISSUE THREAD

**Issue by jfoliveira** [octobercms/october#1994]
Could anyone point me at the right direction on how to use the import plugin with non `.csv` file extensions?

The [Import/Export plugin](https://octobercms.com/docs/backend/import-export) is great, but I can't find a way to re-use its infra-structure to process non `.csv` files.

My use case is: I need to upload and process `.txt` files and do whatever I want with each line, still displaying the `Processing` dialog, displaying a summary dialog in the end of the process, etc, everything the plugin offers would serve me if other file extensions were accepted.

Any ideas on how to achieve that?

**Comment by daftspunk** [comment]
I know this might seem trivial, but if the format is CSV, why not rename the `txt` to `csv`?

**Comment by jfoliveira** [comment]
Hey Samuel, thanks for your comment. Let me clarify.
In my case I have `text/plain` files without separators, so I can`t process them by columns as I would do with a `csv`. Actually I have to read each line and extract substrings from the line string.

I was just under the impression that the `Import/Export plugin` would process any file, line by line, and give me the chance to set my own callback to decide what to do with each line.

I read the plugin source and now I realize that it is actually a `CSV Import/Export plugin` so this is not a supported use case.

I ended up attempting to implement my own approach to that - https://octobercms.com/forum/post/how-access-uploaded-file-using-fileupload-widget - unfortunately not as elegant as I would like.

**Comment by daftspunk** [comment]
Yes your own implementation is probably best for this type of scenario.
