### ISSUE TITLE
Media manager buggy with touch screen laptops

### ISSUE THREAD

**Issue by vmdao** [octobercms/october#1995]
Hi Bro,
I was a bug Media
<img width="958" alt="bug" src="https://cloud.githubusercontent.com/assets/15071651/15108397/e6bb2d6a-15ff-11e6-9706-7beffff6d8a3.PNG">

**Comment by daftspunk** [comment]
Do you use a touch screen computer?

**Comment by vmdao** [comment]
Yes, My computer have touch screen, but I use mouse :)

**Comment by daftspunk** [comment]
Ok, I think I might know why it happens. Will take a look, thanks.

**Comment by vmdao** [comment]
:+1:  thanks @daftspunk :)

**Comment by AlecSPB** [comment]
I'm sorry, but how the CMS interacts with the computer hardware? Or in scripts there is some code that should not be present? You work for the Pentagon? @daftspunk   )))

**Comment by daftspunk** [comment]
This should be fixed by d788b7e03f351e960df1b993a52e91e9c0f9f99d
