### ISSUE TITLE
Lists in relation controller giving ambigious warnings

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1997]
https://github.com/octobercms/october/blob/9dc1b4d836c8147f7fc0b3f752efe10d70a491f2/modules/backend/widgets/Lists.php#L462

By using lists with sorting enabled in the relation manager I got the warning about ambigious column name id, beause deferred columns were joined into the table.

I managed to solve it by 

    if(\Schema::hasColumn($this->model->getTable(),$sortColumn)) {
        $query->orderBy($this->model->getTable().'.'.$sortColumn, $this->sortDirection);
    }
    else {
        $query->orderBy($sortColumn, $this->sortDirection);
    }

I'm not sure if this is the best way to go around with it, but with sql server this is really neccesary, it's quite unforgiving for ambigious column names

**Comment by daftspunk** [comment]
Not sure about using `hasColumn`, this could be quite inefficient. This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.
