### ISSUE TITLE
No possibility to use defined routes in Page

### ISSUE THREAD

**Issue by trsh** [octobercms/october#1999]
Would be nice a possibility to use defined routes (like. https://octobercms.com/docs/services/router) in page definition. For example:

> url = url.blog.posts

Then use it anywhere like Url::to('url.blog.posts'). Then if the URL needs to be changed, we can do it in only one place (routes.php for ex.), and all links stay valid and point to same place. This would also make URL localization much easier.

**Comment by daftspunk** [comment]
This is a good suggestion, although it would probably need to look more like

```
url = "/blog/posts"
route = "url.blog.posts"
```

Where the `url` is used as a fallback.

**Comment by LukeTowers** [comment]
You can already accomplish the same affect by using the `|page` filter. http://octobercms.com/docs/markup/filter-page
