### ISSUE TITLE
Register custom mail layout

### ISSUE THREAD

**Issue by prhost** [octobercms/october#2000]
Hello guys,

I would like to know if you have to use email layout through view without having to create the panel, and enjoy and know you have to keep both the template and the layout within the themes and not the plugin.

I know the registerMail Templates, but apparently it only records views from within the plugin.

**Comment by daftspunk** [comment]
You may create Mail Layouts via the `System\Models\MailLayout` model. It is just like any other model.

```
$css = 'a, a:hover {
    text-decoration: none;
    color: #0862A2;
    font-weight: bold;
}

td, tr, th, table {
    padding: 0px;
    margin: 0px;
}

p {
    margin: 10px 0;
}';

$html = '<html>
    <head>
        <style type="text/css" media="screen">
            {{ css|raw }}
        </style>
    </head>
    <body>
        {{ content|raw }}
    </body>
</html>';

$text = '{{ content|raw }}';

        \System\Models\MailLayout::create([
            'is_locked'    => true,
            'name'         => 'Default',
            'code'         => 'default',
            'content_html' => $html,
            'content_css'  => $css,
            'content_text' => $text,
        ]);
```

**Comment by prhost** [comment]
I can only use this in migration, and use the migration to edit. It would be a good feature, register the layout equals is email template, plan it?

**Comment by daftspunk** [comment]
We will keep it as a conceptual feature request for future reference. Thanks.
