### ISSUE TITLE
PDOException when running phpunit to testing plugin

### ISSUE THREAD

**Issue by surahmans** [octobercms/october#2002]
Hi, I'm new in unit testing. But I trying to test every plugin I have made by following [this doc](http://octobercms.com/docs/help/unit-testing). But I got the following error when running `phpunit` in the base plugin directory;

```
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

E

Time: 3.53 seconds, Memory: 23.25Mb

There was 1 error:

1) Rahman\Forum\Tests\Models\TopicTest::testCreateTopic
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such table: users (SQL: select * from "users" where "users"."deleted_at" is null)

...

Caused by
PDOException: SQLSTATE[HY000]: General error: 1 no such table: users

...

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.
```

and my test file code is `TopicTest.php`.
```
<?php  namespace Rahman\Forum\Tests\Models;

use Rahman\Forum\Models\Topic;
use PluginTestCase;

class TopicTest extends PluginTestCase
{

    public function testCreateTopic()
    {
        $topic = Topic::create(['subject' => 'New topic!']);
        $this->assertEquals(1, $topic->id);
    }
}
```

Am I missed something?

Thanks

**Comment by daftspunk** [comment]
If your plugin depends on the `users` table, then it probably depends on the RL.User plugin. So it should be defined as such using [plugin dependencies](http://octobercms.com/docs/plugin/registration#dependency-definitions).

**Comment by surahmans** [comment]
Hi @daftspunk, 

Thank you for answering my question. But the error comes although I have added `public $require = ['RainLab.User'];` in my `plugin.php` before.

**Comment by daftspunk** [comment]
Interesting, it should work in this case. You could try running in your `setUp` method:

```
$this->runPluginRefreshCommand('RainLab.User');
```

**Comment by surahmans** [comment]
Like this?
```
    public function setUp()
    {
        parent::setUp();
        $this->runPluginRefreshCommand('RainLab.User');
    }
```
But still same.

**Comment by daftspunk** [comment]
We may need to see your plugin along with test case to understand what is happening.

**Comment by surahmans** [comment]
I tried to testing RainLab.User plugin and there is no error. You're right! Something happened with my plugin.

Thanks.
