### ISSUE TITLE
Cannot use aliases when importing classes on a CMS page

### ISSUE THREAD

**Issue by ariponce** [octobercms/october#2006]
**Steps to reproduce**

- Open the code section of a CMS page
- Import a namespaced class with an alias, e.g: `use My\Namespace\Models\Event as EventModel`

**Expected result**
The class is imported with the alias

**Actual result**
A syntax error is thrown with the message "syntax error, unexpected 'as' (T_AS), expecting ',' or ';' or '{''

**Comment by daftspunk** [comment]
Fixed by #2032 thanks to @gabsource
