### ISSUE TITLE
Can not remove invalid component from page

### ISSUE THREAD

**Issue by firemankurt** [octobercms/october#2007]
Using Build 333 and I noticed today that if I renamed a component in a plugin ( making it invalid ) then I could not remove it from any pages in CMS section.
If I try delete the page it fails also.

It looks like I can still remove it and save however it doesn't actually remove anything.
This may require refresh and open page again to see behavior.

I removed the unknown component, saved the page, refreshed and loaded the page - component was back on there again
(Bug confirmed with Flynsarmy and spunky )

**Comment by amdad** [comment]
I cannot remove even proper components via Backend editor. Need to do it via local Editor.
