### ISSUE TITLE
[Bug?] Repeater fields not honouring default values

### ISSUE THREAD

**Issue by DanielHitchen** [octobercms/october#2013]
Hi,

When using the repeater widget, if you set a default value for a form field within it, the default value is ignored whenever you add a new item.

Not sure whether this is a bug or whether this functionality just needs adding to the widget, but it would be great if the repeater honoured the default field values/options set.

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by gabsource** [comment]
If I understood the problem, it happens if the _data_ passed to the form contains the _key_ whether the value is `null`, `0` or empty string.

The FormField test looks like this : 
```
if (!array_key_exists($key, $result)) {
    return $default;
}
```

If the form is populated whit a model where the _key_ exists it does not look at the default value : 

```
$model = new MyModel;
$model->myField = null; // if you remove this, the field in populated with the default value
```

**Comment by DanielHitchen** [comment]
@gabsource thanks for your input.

I found where the default field value is set within the backend ```modules/backend/widgets/Form.php``` and changed lines 896-898 from:
```
$defaultValue = !$this->model->exists
    ? $field->getDefaultFromData($this->data)
    : null;
```
to
```
$defaultValue = $field->getDefaultFromData($this->data);
```
for the moment in time until a better solution can be found - but this does what I want for now.

Thanks

**Comment by harmenjanssen** [comment]
I created a Javascript fallback to deal with this problem.
See this gist for details: https://gist.github.com/harmenjanssen/6895778f4b85910ba56452abc98fdc3e

Basically: add a data-attribute to the fields in the repeater containing the default value, which will be picked up by Javascript.

**Comment by haralake** [comment]
Is there a way to solve this issue with repeater default values on theme settings, without hack the core files?

**Comment by LukeTowers** [comment]
Submit a PR to fix it @haralake, hacking the core files is fine as long as you contribute those hacks and they're well thought out so that they stay when you next update :)

**Comment by HammenWS** [comment]
@LukeTowers I have the same issue and created a PR for this #3766

**Comment by bennothommo** [comment]
Fixed by https://github.com/octobercms/october/pull/4098 and https://github.com/octobercms/october/commit/a7bc442df5fb615a1cf044b046ccce0e374aff73.
