### ISSUE TITLE
Don't mark page as modified if component properties were showed but not modified

### ISSUE THREAD

**Issue by bcinternet** [octobercms/october#2015]
1 Open page
2 Highlight properties of some component included to page
3 Close popup without modyfying any properties
4 Page is already marked as modified

I propose for this to change, page shoudl not be mareked as modified in such case.

**Comment by daftspunk** [comment]
Unable to replicate. The proposed behavior already exists. Tested in Build 334.

Peer review needed.

**Comment by alxy** [comment]
I can only replicate that, if I change a value, close the popup und then roll back to the old value. This is not recognized, but I think it shouldnt and is not necessary.

**Comment by dshoreman** [comment]
Also unable to replicate. You can also change a value and revert it to the saved value before closing and it won't mark the page as dirty.

As @alxy mentioned, the only way to get it marked as dirty is by editing a value and closing the modal. This is exactly what should happen.
