### ISSUE TITLE
[Bug?] Mac cmd+s no longer seems to save

### ISSUE THREAD

**Issue by DanielHitchen** [octobercms/october#2018]
Hi,

When using ```cmd+s``` in either Chrome or Firefox on Mac, the October save command no longer seems to work, but instead the browsers "Save As" fires instead. The Windows ```crtl+s``` works as expected, just an inconvenience for us Mac users more than anything.

I'm sure that the browser shortcuts can be altered to accommodate the October shortcut, but it was working a while back, so hopefully we can get this functionality back :)

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by DanielHitchen** [comment]
I have this working again now - is was using the combination of
```
data-hotkey="ctrl+s"
data-hotkey-mac="cmd+s"
```
in my plugins, but in your Rainlab plugins you now seem to using ```data-hotkey="ctrl+s, cmd+s"```, but all working again now
