### ISSUE TITLE
routes:cache

### ISSUE THREAD

**Issue by andriytkachiv** [octobercms/october#2019]
Is it possible to use Laravel command routes:cache?
After doing some magic I make it work and created cached routes file.

But I have no idea how to load it through octobercms instead of default routes.

Any idea?

**Comment by daftspunk** [comment]
October's routing cache is baked in, try enabling it via the config:


    /*
    |--------------------------------------------------------------------------
    | Determines if the routing caching is enabled.
    |--------------------------------------------------------------------------
    |
    | If the caching is enabled, the page URL map is saved in the cache. If a page
    | URL was changed on the disk, the old URL value could be still saved in the cache.
    | To update the cache the back-end Clear Cache feature should be used. It is recommended
    | to disable the caching during the development, and enable it in the production mode.
    |
    */

    'enableRoutesCache' => false,

Although you are free to use Laravel's routes:cache command if you like, although it won't do much since October only implements 2 primary routes (backend and frontend).

**Comment by andriytkachiv** [comment]
Thanks for answering! Yes I am using this cache for frontend & backend, but I also have a lot of custom routes (API) which are not cached.

**Comment by daftspunk** [comment]
This would be something to follow up with the Laravel community and is outside the scope of October. In other words, I'm not sure =)
