### ISSUE TITLE
[feature] 404 header and page from component

### ISSUE THREAD

**Issue by bestxp** [octobercms/october#202]
i've inspected cms code for search  method with return 404 error 

i'm found  `Response::make(View::make('cms::404'), 404);`
but this returns system 404

also exists 

<pre><code>
   if (!$page && !($page = $this->router->findByUrl('/404')))
            return Response::make(View::make('cms::404'), 404);

        $this->page = $page;
</code></pre>

but this code doesn't run from component, first variant is better, but cannot shows my 404 page

**Comment by buckhornmktg** [comment]
I'm experiencing this issue when trying to use a 404 in a component. Any ideas?

```
    public function onRender()
    {
        $this->category = Category::where('slug', $this->param('category'))->get()->first();
		if(!$this->category['id']) {
			$this->setStatusCode(404);
			return $this->controller->run('404');
		}
```
Not only is the header status being displayed, but the entire 404 page is being injected into {% page %}, layout and all. 

```
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title> Missing Page </title>
...
<body>
<div class="main-container">

HTTP/1.0 404 Not Found
Cache-Control: no-cache
Date:          Sun, 10 Sep 2017 22:10:26 GMT

<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title> Missing Page </title>
```

**Comment by LukeTowers** [comment]
That's because you're doing that in `onRender()`. Do that in `onRun()` instead and it will work fine.

**Comment by buckhornmktg** [comment]
Doh! Thanks Luke, that was the problem.

**Comment by LukeTowers** [comment]
Not a problem, happy to help.

**Comment by zakir1929** [comment]
I just need to ask is octobercms has only capable of setting two types of errors ???
1.404 [by creating a page with /404 url ]
2.500 [by creating a page with /error url ]

how can we set 401, 402, 403 etc ??????

**Comment by icanall10** [comment]
return $this
                ->controller
                ->setStatusCode(404)
                ->run(404);
