### ISSUE TITLE
Bug: PropertyContainer setProperties should return properties (develop branch)

### ISSUE THREAD

**Issue by ekrokowski** [octobercms/october#2020]
The PropertyContainer should return the properties in the setProperties method:
https://github.com/octobercms/october/blob/develop/modules/system/traits/PropertyContainer.php#L60

The setProperties method is used (e.g.) when updating report widget properties:
https://github.com/octobercms/october/blob/develop/modules/backend/widgets/ReportContainer.php#L138

Therefore currently properties of report widgets cannot be saved and get reset when saving. `master` branch returns the properties.

**Steps to reproduce:**
Try to save report widget size. **(develop branch)**

**Expected result:**
Widget size should be saved to db and loaded on refresh.

**Actual result:**
Widget properties get reset.

**Comment by daftspunk** [comment]
Well spotted. Thanks!
