### ISSUE TITLE
Crop and insert can produce "Invalid selection data" when a fixed ratio is used

### ISSUE THREAD

**Issue by dzava** [octobercms/october#2021]
Trying to crop an image using a fixed ratio can produce a _Invalid selection data_ message. Since [this commit](https://github.com/tapmodo/Jcrop/commit/3a51e67f8dbced3b4f763cb832f75c0a0750ec72#diff-f93c6ae36034c63a1c3e1d298a9af0d0L656) selection data can contain decimal places, which [prevents](https://github.com/octobercms/october/blob/ab4abb9bc5c42f09028e25206cd6d575fa3b1f31/modules/cms/widgets/MediaManager.php#L1124) images from being created.

##### Expected behavior
A cropped image should be created.

##### Actual behavior
An error for _Invalid selection data_ is shown.

##### Reproduce steps
1. Select crop and insert
2. Set selection mode to fixed ratio
3. Set width and height to 4/3
4. Make a selection with width and/or height that contain decimal places
5. Clip Crop and insert

##### October build
318

**Comment by gabsource** [comment]
Confirmed with build 341. 

At https://github.com/octobercms/october/blob/develop/modules/cms/widgets/MediaManager.php#L1182
`ctype_digit($selectionData[$paramName])` is failing against decimal values sent by the client.

![image](https://cloud.githubusercontent.com/assets/1851314/15636205/dd65dc9e-25f7-11e6-9fee-7d130a9124fb.png)

Maybe the test could be changed to `is_float` and as the values must be an integer, it must be casted to `int` at the end of the `foreach` loop.

**Comment by gabsource** [comment]
I think the client side code should be patch also to reflect the integer value in 
https://github.com/octobercms/october/blob/develop/modules/cms/widgets/mediamanager/assets/js/mediamanager.imagecroppopup.js#L366 
`MediaManagerImageCropPopup.prototype.updateSelectionSizeLabel`

**Comment by daftspunk** [comment]
Fixed by #2071
