### ISSUE TITLE
Crop and insert does not remember options correctly

### ISSUE THREAD

**Issue by dzava** [octobercms/october#2022]
##### Expected behavior
The crop tool options should match the displayed options.

##### Actual behavior
The crop tool uses the default options. 

##### Reproduce steps
1. Select crop and insert
2. Set mode to fixed ratio or fixed size
3. Make a selection
4. Click crop and insert
5. Open crop and insert again
6. UI shows the mode selected on step 2 but the tool uses normal mode

##### October build
318

**Comment by gabsource** [comment]
Confirmed in build 341.

**Comment by daftspunk** [comment]
Fixed by #2070
