### ISSUE TITLE
Menu Background Missing in Settings 

### ISSUE THREAD

**Issue by abass** [octobercms/october#2023]
Ever since updating to the beta builds with the new design, I have been getting some weird graphical issues. For example here in the settings [Build 334]:

![IMG](https://s3.amazonaws.com/f.cl.ly/items/2K0K3Z1Z0Y0q1k392t0x/Image%202016-05-17%20at%208.15.53%20PM.png?v=da770723)

**Comment by daftspunk** [comment]
Try resetting your brand settings. This will occur automatically when the build is released. For now you must do it by hand =)

**Comment by canthis** [comment]
It's more likely because of [Backend Plus plugin](https://github.com/gergo85/oc-backend-plus), cause I'm getting this behavior only when Backend Plus plugin is enabled, so it's plugins issue, not Octobers.

@abass Try disabling it and check if it helps, in case You have installed it, of course.
