### ISSUE TITLE
How to use dropdown in the Pivot?

### ISSUE THREAD

**Issue by ITCorporate** [octobercms/october#2024]

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by ITCorporate** [comment]
Sorry, I created this issue before the description of the problem

I create default models with pivot data. In fields.yaml I wrote
`fields:
    pivot[value_id]:
        label: Value`
Everything works well.

When I write:
`fields:
    pivot[value_id]:
        label: Value
        type: dropdown`

And in Property Model, or any other model:
`public function getValueIdOptions() {
	return DB::table('property_value')
	         ->where('property_id', $this->attributes['id'])
	         ->lists('value', 'id');
}`

I get an error

> The model class October\Rain\Database\Pivot must define a method getValueIdOptions() returning options for the 'pivot[value_id]' form field.

I want put 'id' of dropdown in 'value_id'. How do it?

**Comment by ITCorporate** [comment]
I can rewrite fields.yaml
```
fields:
    pivot[value_id]:
        label: Value
        type: dropdown
        options:
            0: first
            1: second
```
And it works. But how retrun custom method "getValueIdOptions" into "options:"? Can not understand

**Comment by ITCorporate** [comment]
Yes, I found a solution! Yeah!

```
fields:
    pivot[value_id]:
        label: Value
        type: dropdown
        options: getValues
```

```
// Model

public function getValues() {
	return [...];
}
```

Excuse for troubling.
