### ISSUE TITLE
[bug report]: Using conditions or scope not working

### ISSUE THREAD

**Issue by Leadrive** [octobercms/october#2028]
In the model file, WxIssue.php
    public $belongsTo = [
        'priority' => ['Leadrive\Pm\Models\ConfigStatus', 
            'conditions' => 'field_name = "wx_issue_priority"'
            //'scope' => 'isWxIssuePriority'
            ],
    ];

Table leadrive_pm_config_status structure is
id
name
field_name

In the columns.yaml
    priority_name:
        label: 'leadrive.pm::lang.wxissue.priority'
        relation: priority
        select: name

I want to display the priority name in the list, but the conditions did not work, priority relation will get many records, so the list did not show any records.

I debug the source, \cms\modules\backend\widgets\Lists.php from line 432 to 441, did not add the conditions.
//---------------- these source did not work ok, please check. ---------------------
                $relationObj = $this->model->{$column->relation}();
                $countQuery = $relationObj->getRelationCountQuery($relationObj->getRelated()->newQueryWithoutScopes(), $query);
                $joinSql = $this->isColumnRelated($column, true)
                    ? DbDongle::raw("group_concat(" . $sqlSelect . " separator ', ')")
                    : DbDongle::raw($sqlSelect);
                $joinSql = $countQuery->select($joinSql)->toSql();

```
            $selects[] = Db::raw("(".$joinSql.") as ".$alias);
```

//--------------------------------------------------

The reason is $relationObj->getRelationCountQuery did not add the conditions, and the Db::raw did not add the condition value. 

My solution is here, please refer.
            $relationObj = $this->model->{$column->relation}();
            $temp = $relationObj->getRelated()->newQueryWithoutScopes();
            $a = $temp->getQuery()->wheres;
            $b = $relationObj->getQuery()->getQuery()->wheres;
            // delete No.0 condition
            array_splice($b, 0, 1);
            $temp->getQuery()->wheres = array_merge((array) $a, (array) $b);
            $countQuery = $relationObj->getRelationCountQuery($temp, $query);

```
        $joinSql = $this->isColumnRelated($column, true)
            ? DbDongle::raw("group_concat(" . $sqlSelect . " separator ', ')")
            : DbDongle::raw($sqlSelect);
        $joinSql = $countQuery->select($joinSql)->toSql();

        $wheres = $temp->getQuery()->wheres;
        $search = ' ? ';
        foreach ($wheres as $id => $where) {
            if (isset($where['value']) && (!is_object($where['value']))) {
                $replace = ' ' . $where['value'] . ' ';
                $pos = strpos($joinSql, $search);
                if ($pos !== false) {
                    // Nothing found
                    $joinSql = substr_replace($joinSql, $replace, $pos, strlen($search));
                }
            }
        }

        $selects[] = Db::raw("(".$joinSql.") as ".$alias);
```

**Comment by daftspunk** [comment]
I'm having trouble reading this. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by Leadrive** [comment]
Hi, I create a demo to show this bug, please visit:
https://github.com/Leadrive/Test

Thanks.

**Comment by Leadrive** [comment]
Please check it.

**Comment by Leadrive** [comment]
This is a crucial bug, please check it.
    public $belongsTo = [
        'priority' => ['Leadrive\Pm\Models\ConfigStatus', 
            'conditions' => 'field_name = "issue_priority"'
            ],
    ];
If add the conditions or scope, but it did working.
@daftspunk

**Comment by Leadrive** [comment]
http://octobercms.com/forum/post/problem-with-scope

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
