### ISSUE TITLE
October Drivers Plugin Installation Issues

### ISSUE THREAD

**Issue by ant2400** [octobercms/october#2037]
I'm not sure how to use this plugin for sending mail. I've found the plugin, installed it, and on the manage plugins page in the cms, made sure to enable the plugin. After this, there have been no changes to my config/mail.php file and there's no config/services.php to set up the configuration for my Mailgun account. The only option I have if I try to set the mail configuration in the backend is to use the default mail options (SMTP, PHP Mail or Sendmail.) I don't see where to use Mailgun.

Sorry if this is more of a use question and doesn't fit in with normal Issue postings on this github, but I'm unable to find where to post to the October Forum on the October CMS website.

**Comment by ant2400** [comment]
UPDATE: It looks like I don't have these options available because the site I'm working on is using an older version of October. I tested this in a new October site that I set up, and the Mailgun and other options are available. 

Is there a way to integrate Mailgun's API into an older version of October? Or does the site need to be updated?

**Comment by daftspunk** [comment]
Not unless you specify the settings directly in the `mail.php` config file, I'm guessing just the UI is missing. Not sure exactly what version you are running, but only the latest version is supported at this point.
