### ISSUE TITLE
Css bug with the progress bar when doing a plugin install

### ISSUE THREAD

**Issue by gabsource** [octobercms/october#2043]
##### Expected behavior
There should be a padding above the progress bar when doing a plugin install.

##### Actual behavior
The progress bar is stucked on top of the modal when doing a plugin install : 

![image](https://cloud.githubusercontent.com/assets/1851314/15519041/e8354ce6-21ff-11e6-80fd-226bee2e53bb.png)

##### Reproduce steps
Install a plugin and take a look at the modal progress bar. Or simply inject in an existing modal the following code : 
```
<div class="modal-dialog" style="transform: inherit;"><div class="modal-content">
    <div class="modal-body">
                <div class="progress bar-loading-indicator" id="executeLoadingBar">
                    <div class="progress-bar"></div>
                </div>

                <div class="loading-indicator-container">
                    <p>&nbsp;</p>
                    <div class="loading-indicator transparent">
                        <div id="executeMessage"></div>
                        <span></span>
                    </div>
                </div>
                <p>&nbsp;</p>
    </div>
</div></div>
```

##### October build
336

====

Maybe it's juste a temporary glitch due to CSS refactoring for the release. But I don't know what solution you would prefer to fix this. It could be introducing a special CSS class for "body-only" modal to add padding or just adding padding on this page somehow (a container with a class or directly on the progress bar).

**Comment by daftspunk** [comment]
Thanks for reporting this. Fixed in Build 337+
