### ISSUE TITLE
Accessing Tabs in Form Widget

### ISSUE THREAD

**Issue by lenrsmith** [octobercms/october#2047]
I have been working on a small project in order to learn my way around October, and I like what I see. While adding an extension the RainLab.Blog plugin, I ran into an issue managing the tabs on the backend Post form. It's relatively easy to add a couple of additional image fields to the 'Manage' tab, but I would like to move all of the image fields to their own tab. Because `$allTabs` in `modules/backend/widgets/Form.php` is `protected` I cannot access the tabs setup. To test, I set `$allTabs` to `public` so that I could run the following in my plugin's boot() method: 
```
$featured_images = $widget->getField('featured_images');
$widget->allTabs->secondary->removeField('featured_images');
$widget->allTabs->secondary->addField('featured_images', $featured_images, 'Images');
```
The code works nicely, but I would like to do the same without modifying the core code. It looks like I could remove the 'featured_images' field from the form with `$widget->removeField('featured_images')` and re-add it, but I prefer my approach as it seems a little less destructive. So, does it make sense to set `$allTabs` to `public` or should there be some getters and setters in the Form widget for accessing the FormTabs? Or, am I completely missing something obvious? I'm willing to create the getters and setters, but I thought I would ask you guys, first.

**Comment by daftspunk** [comment]
[An API was added for this recently](https://github.com/octobercms/october/commit/0504da41f2d35f12135bb87f3270b536eb018155#diff-d7b489cccf21c7a4400772ca5d6968c6R831), try updating using `cms.edgeUpdates` in the config to get the changes.

**Comment by lenrsmith** [comment]
@daftspunk That was perfect, and I only need to modify two lines :-)  Thank you.
