### ISSUE TITLE
Unable to Edit Within CMS Editor (Build 337)

### ISSUE THREAD

**Issue by abass** [octobercms/october#2048]
Pretty much all of the files within the CMS section aren't editable. Not sure what is going on. I was clicking around a bit and then a couple files became editable all of a sudden, but it's back to acting like this. No idea what to do or how to explain this bug.

Here are a couple screenshots:

![IMG](https://s3.amazonaws.com/f.cl.ly/items/1r0z413N3K290x0W1c2E/Image%202016-05-24%20at%2010.44.39%20PM.png?v=8ed2bfbe)

![IMG](https://s3.amazonaws.com/f.cl.ly/items/2C2p350e2v1S1w170T3T/Image%202016-05-24%20at%2010.55.31%20PM.png?v=63a818b7)

**Comment by daftspunk** [comment]
Looks like an edge build. Try resetting the customise backend settings.

**Comment by abass** [comment]
@daftspunk That seemed to have fixed it - Thanks for the quick reply, you're the best! :+1:
