### ISSUE TITLE
October Drivers plugin - Iron.io issue with PHP7

### ISSUE THREAD

**Issue by duncanClicksco** [octobercms/october#2052]
Using the Iron.io Driver included with the October.Drivers plugin on PHP 7 I received the below error:
`curl_setopt(): Disabling safe uploads is no longer supported`

This is the same issue as reported here: https://github.com/iron-io/iron_mq_php/issues/73

As mentioned in the original ticket the I was able to fix this by running:
`composer update iron-io/iron_core`

within /plugins/october/drivers directory which did the following:

```
Removing iron-io/iron_core (0.2.3)
  - Installing iron-io/iron_core (0.2.5)
```

**Comment by daftspunk** [comment]
I have forced the Drivers plugin to update itself, this should pull down the latest patch version of all packages. Please update the drivers plugin, also by force, there are two ways to do this:

Method 1:
1. Navigate to System \ Updates
1. Perform a complete update
1. Perform an update again
1. Where it says "There are no new updates" click "Force update"

Method 2:
1. Navigate to System \ Updates \ Install new plugins
1. Search for "October.Drivers"
1. Install the plugin again, over the top of itself

Report back and close this issue if fixed. Thanks!

**Comment by duncanClicksco** [comment]
To test the methods above, I did the following:

1. Updated all of October through System \ Updates (Build: 318)
2. Set config/cache to use file caching (cannot use Redis when the removing the October.Drivers plugin)
3. ran:
`php artisan plugin:remove october.drivers`
4. Cleared composer cache:
`composer clear-cache`
5. Installed drivers plugin again (installs v1.0.2):
`php artisan plugin:install october.drivers`

However, the /plugin/october/drivers/composer.lock still references iron-io/iron_core version 0.2.3 (instead of version 0.2.5).

Is the composer.lock file committed as part of the plugin source or generated by composer on our development server? If its generated locally, then this is an issue with our environment.

**Comment by daftspunk** [comment]
You can find the source for the plugin here: https://github.com/octoberrain/drivers-plugin/tree/e79ebae6e3c00ed385eda7c653092b28290b1772

Alternatively you can enable `cms.edgeUpdates` in the config to update to the latest version of October and drivers plugin.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
