### ISSUE TITLE
Missing /snippets/plain_text.js in ACE editor

### ISSUE THREAD

**Issue by side-by-side** [octobercms/october#2059]
Hello.
In October CMS build 336 the file ```/modules/backend/formwidgets/codeeditor/assets/vendor/ace/snippets/plain_text.js``` is missing.

When we are editing ```*.txt``` content file (for example in october demo theme CMS → Content → placeholder → page.txt) there is HTTP request for this ```plain_text.js``` file, that is missing.

Just include it to the bundled ACE package. If it is mandatory.

**Comment by gabsource** [comment]
Can't reproduce this issue with latest build. The `plain_text.js` has always been bundled in the October backend `/modules/backend/formwidgets/codeeditor/assets/js/build.js`.

**Comment by side-by-side** [comment]
Ok, in fresh installation using installer of latest stable 318 build there is no ```/modules/backend/formwidgets/codeeditor/assets/vendor/ace/snippets/``` directory at all but there is no any 404 requests too. I suppose all needed ACE files already merged to some minified file (build.min.js maybe, doesn't matter).

After enablind ```edgeUpdates``` option and updating to latest 340 build, ```/modules/backend/formwidgets/codeeditor/assets/vendor/ace/snippets/``` was created and there is no ```plain_text.js``` inside. I have fully fresh install without any plugins and here is screenshot of newly created folder:
![sc-004](https://cloud.githubusercontent.com/assets/7204866/15626573/424b0b9e-24d0-11e6-80d5-4973586f519c.jpg)

Also there is an exception when you are entering ```Settings → CMS → Front-end theme (/backend/cms/themes)``` settings page:
![sc-005](https://cloud.githubusercontent.com/assets/7204866/15626589/ab9c12be-24d0-11e6-8b87-8baf706f8319.jpg)

This install is fully fresh without touching anything.

**Comment by daftspunk** [comment]
Was able to replicate using the information above.
