### ISSUE TITLE
Exception on entering "Front-end theme" settings page

### ISSUE THREAD

**Issue by side-by-side** [octobercms/october#2061]
In the buld 340 there is an exception when you are entering ```Settings → CMS → Front-end theme (/backend/cms/themes)``` settings page:
![sc-005](https://cloud.githubusercontent.com/assets/7204866/15626589/ab9c12be-24d0-11e6-8b87-8baf706f8319.jpg)

**Comment by daftspunk** [comment]
Please search before posting.

Duplicate #1950
