### ISSUE TITLE
Question: Dynamically change the page title does not work.

### ISSUE THREAD

**Issue by Litvinenko** [octobercms/october#2069]
The code below doesn't produce the desired result.
```
function onEnd()
{
    $this->page->title = 'A different page title';
}
```

**Comment by daftspunk** [comment]
Works over here

```
<title>OctoberCMS - A different page title</title>
```

Inside the layout file

```
<title>OctoberCMS - {{ this.page.title }}</title>
```

What build are you on?

**Comment by Litvinenko** [comment]
@daftspunk current version **341**

Maybe this is an important detail that I I try to get changed title inside the component using ajax framework:
```
$page = Page::load(Theme::getActiveTheme(), $pageFile);
$pageTitle = $page->title;
```
Code above return static string from Configuration Section.

**Comment by daftspunk** [comment]
Changing the page title using AJAX or from a partial code section would occur too late in the page life cycle. This is a known limitation and emphasizes the importance of understanding the page execution life cycle.

However that's not to say you can't update the page title from AJAX, I suppose it would be possible like this:

```
function onUpdatePageTitle() {
    return ['#pageTitle' => 'I am a new title'];
}
==
<head>
    <title id="pageTitle">This is the default page title</title>
</head>
<body>
    <button data-request="onUpdatePageTitle">Update page title</button>
</body>
```
