### ISSUE TITLE
Making relation formwidget handle scopes.

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#2076]
Making formwidget relation render constrainable by a scope defined in the model.

Adding a  `public $constrainByScope` in the main object

adding 'constrainByScope' to fillFromConfig

adding this at 

https://github.com/octobercms/october/blob/9dc1b4d836c8147f7fc0b3f752efe10d70a491f2/modules/backend/formwidgets/Relation.php#L100

                    if(!is_null($this->constrainByScope)) {			
				foreach($this->constrainByScope as $key=>$value) {
					if(is_null($value) && is_string($key)) {
						$query->{$key}();
					}
				}
			}

will make a pull request when I have time, or if someone else wants to do it, be my guest.

**Comment by daftspunk** [comment]
This is pretty simple, add a `scope` to the relationship definition, otherwise you can manually use the `dropdown` or `checkboxlist` form field types. This is probably overkill to include a `scope` constraint to this form widget.

**Comment by tschallacka** [comment]
Yea, but what if you want only the scope to be limited to the form you are presenting to one employee, and the scope to be different to another employee.... I currently have two controllers for the same model, one for an employee with more possibilities, and another for an employee with less possibilities.
I kinda use it to "filter the queues" so it vanishes from the queue of the first rank in the queue and apppears in the next row.

**Comment by daftspunk** [comment]
These are complex requirements. You can either make another relationship definition (and scope), or use the `dropdown`/`checkboxlist` type, `relation` acts as sugar for these basic form fields.

**Comment by LukeTowers** [comment]
Support for the `scope` property was added in #2871

**Comment by tschallacka** [comment]
Woo! Thank you. I've finally conviced my bosses that I could upgrade so I can move from 361 to the most current version :-) with this useful feature in it! awesome!

**Comment by LukeTowers** [comment]
Your bosses need to stay more up to date! 😂
