### ISSUE TITLE
AttachOne relation loads private files in the public folder

### ISSUE THREAD

**Issue by reg2005** [octobercms/october#2079]
I use current develop branch. There is a problem when using private files. I use $attachOne in the model:

```
    public $attachOne = [
        'attachment' => ['System\Models\File', 'public' => false]
    ];
```

When adding the file it remains in storage/app/public directory instead of storage/app/protected. But in the table system_files is_public = FALSE (Here everything is correct).
I assume that a problem in the isPublic method, because is_public key doesn't exist in $this->attributes array

```
// October\Rain\Database\Attach\File

    public function isPublic()
    {
        if (array_key_exists('is_public', $this->attributes))
            return $this->attributes['is_public'];

        if (isset($this->is_public))
            return $this->is_public;

        return true;
    }
```

**Comment by daftspunk** [comment]
This report is functionally identical to #1807

**Comment by reg2005** [comment]
Thanks!
