### ISSUE TITLE
Two bugs in backend template with buttons of switching of language (rainlab-translate)

### ISSUE THREAD

**Issue by reg2005** [octobercms/october#2080]
Hi, I will be short:

![2016-06-01 7 08 52](https://cloud.githubusercontent.com/assets/4133683/15698143/1fdab18e-27ca-11e6-9541-8002d715d1f1.jpg)
**In develop branch**

**Comment by daftspunk** [comment]
I notice you are using v1.0.11 of the Translate plugin. The latest version is v1.0.14. Please make sure you use the latest version before reporting issues.
