### ISSUE TITLE
On dev some plug-ins ceased to work

### ISSUE THREAD

**Issue by reg2005** [octobercms/october#2081]
On develop branch, some plug-ins ceased to work. Gives an error message:

> The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 9 (near "form: @/plugins/raviraj/rjsliders/models/slider/fields.yaml").
/home/vagrant/Code/myapp/vendor/symfony/yaml/Inline.php line 241

The problem is solved by simple changeover of the character @ on ~ in yaml config file. But unfortunately many third-party plug-ins use the character @

**Comment by daftspunk** [comment]
Please contact the authors for support. Also make sure you are using `cms.edgeUpdates` config when performing testing. Thanks!
