### ISSUE TITLE
recordFinder widget should allow specifying "recordsPerPage" value

### ISSUE THREAD

**Issue by jfoliveira** [octobercms/october#2082]
Hi,

Currently the `recordFinder` widget displays a list with `20` records per page, forcing the user to scroll down the page in order to be able to see the page navigator icons and move to the next pages - at least in a 13 inch monitor at a 1366x768 resolution.

It would be nice if we could specify a value for the `recordsPerPage` property on the `recordFinder`, as [we can already do for regular lists](https://octobercms.com/docs/backend/lists#configuring-list).

**Comment by reg2005** [comment]
+1

**Comment by jfoliveira** [comment]
Since this is now marked completed, any plans on making a new build available http://octobercms.com/changelog ?

**Comment by jfoliveira** [comment]
Tested and working fine on `build 346`. Thanks!
