### ISSUE TITLE
Controller list behavior config order bug

### ISSUE THREAD

**Issue by side-by-side** [octobercms/october#2085]
Accordingly to the documentation (https://octobercms.com/docs/backend/lists#multiple-list-definitions) we can use multiple list definitions in a controller. Example:
```php
public $listConfig = [
    'list' => 'config_list.yaml',
    'archived' => 'config_list_archived.yaml',
];
```
```index``` controller action shows a page using ```list``` config and other action — using ```archived``` config:
```php
<?= $this->listRender('list') ?>
```
```php
<?= $this->listRender('archived') ?>
```

In these config files we can specify a page title:
```yaml
# config_list.yaml
title: Objects list
```
```yaml
# config_list_archived.yaml
title: Archived list
```
**The problem is:** when rendering any of these configs the page title is always taken from the first config file in the ```$listConfig``` property.
With
```php
public $listConfig = [
    'list' => 'config_list.yaml',
    'archived' => 'config_list_archived.yaml',
];
```
in all controller actions a title is ```Objects list```.
And with
```php
public $listConfig = [
    'archived' => 'config_list_archived.yaml',
    'list' => 'config_list.yaml'
];
```
in all controller actions a title is ```Archived list```.

**Comment by gabsource** [comment]
The title is read from the controller first, then from the first list config. So if you want to customize the title you set the value of `$controller->pageTitle` to what you want.

```
$this->controller->pageTitle = $this->controller->pageTitle ?: Lang::get($this->getConfig(
            'title',
            'backend::lang.list.default_title'
        ));
```

**Comment by daftspunk** [comment]
Try adding this code to the controller

    public function index()
    {
        $this->pageTitle = 'Wow! My new title';
        $this->asExtension('ListController')->index();
    }

**Comment by side-by-side** [comment]
Thank you for your answers.
I already set ```$pageTitle``` in a controller action, but i think it is looks like some sort of a hack.

So, using more than one config in the ```$listConfig``` property we can't rely on ```title``` key in those configs anymore?
I think the way it should work is:
1. First read a page title from a controller's ```$pageTitle```.
2. If null, second read a title from the appropriate config file ```title``` key. From the config, that is rendering:
```php
<?= $this->listRender('archived') ?>
```

With one config in ```$listConfig``` this scenario works beautiful.

What do you think?

**Comment by daftspunk** [comment]
As @gabsource showed in the logic above, if the title is set to `null` it should move on to the next configuration set until it finds a populated value.

**Comment by side-by-side** [comment]
I think it should relay on specified rendering config via
```php
<?= $this->listRender('archived') ?>
```
and not by first found value in **any** config.

**Comment by daftspunk** [comment]
It's not possible because the layout has already rendered by the time `listRender` is called, it is too late in the page cycle. It is safer to just set the page title manually or try the instructions above.

**Comment by side-by-side** [comment]
Ok, thank you again, i got it.
