### ISSUE TITLE
Is there a way to load a theme from a given path?

### ISSUE THREAD

**Issue by jpruiz114** [octobercms/october#2088]
I want to load a theme from a specific path. When I do it from the web browser, I guess that based on the context, I can get the current theme like this:

$currentTheme = \Cms\Classes\Theme::getEditTheme();

... but then, if I want to do the same from the terminal, let's say with an artisan recipe seems like the context changes.

Is there a way maybe with the ThemeManager class to provide a folder path and then load the theme from that specific path?

Thanks!

**Comment by daftspunk** [comment]
You can load a theme within the themes path using `Theme::load('othertheme')`. Using a custom path outside the themes directory might be possible. I can't say that I've ever tried it.

**Comment by reg2005** [comment]
```
        $site['theme_path'] = '/your_any_path_in_theme_folder/theme-name'


        Config::set('cms.theme.item', $site['theme_path']);
        Config::set('cms.activeTheme', $site['theme_path']);

        /*
         * Присваиваем шаблон из конфига
         */

        Event::listen('cms.theme.getActiveTheme', function () use ($site) {
            return $site['theme_path'];
        });

        Event::listen('cms.activeTheme', function () use ($site) {
            return $site['theme_path'];
        });
```
