### ISSUE TITLE
"Clickable" list setting doesn't work with Relation Manager

### ISSUE THREAD

**Issue by daveachuk** [octobercms/october#2093]
The "clickable" column option allows the inclusion of links or buttons within a list, and allows those links/buttons to operate normally, as the onclick handler for the row is NOT applied to the column with "clickable: false"

This behavior works great in the main lists, but when listing related objects via the Relation Manager on a form, this setting is not respected, and clicking on a link in a column with "clickable: false" pops up the edit window briefly before the browser redirects to the URL included in the text/button.

Just opening this issue up for now, will dig into the code and see if there's an obvious answer later today.

**Comment by daftspunk** [comment]
Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue.

**Comment by daveachuk** [comment]
Apologies -- this was a PBCAK! 
I inverted the logic and was setting "clickable=true" to try to get the onclick handler to stop, not "clickable=false".
