### ISSUE TITLE
Fatal error: Call to undefined method October\Rain\Database\Dongle::disableStrictMode()

### ISSUE THREAD

**Issue by numnine** [octobercms/october#2096]
I got this issue while running `php artisan october:up`:

`root@786a163c3a56:/webapp# php artisan october:up
[Mon Jun  6 03:01:41 2016] [hphp] [215:7f701928cca0:0:000001] [] 
Fatal error: Call to undefined method October\Rain\Database\Dongle::disableStrictMode() in /webapp/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 207`

Anyone experience this issue?

**Comment by gabsource** [comment]
`disableStrictMode` is in the `develop` branch of the library (`october/rain` module).
Looks like your `vendors` are no up-to-date.

**Comment by daftspunk** [comment]
Somehow you have the stable version of October and the RC version of the vendor directory. Try reinstalling using the instructions found in the documentation.
