### ISSUE TITLE
Plugins: Symlinked plugins are not picked up

### ISSUE THREAD

**Issue by codedge** [octobercms/october#2099]
When you have symlinks in your `plugins` directory those plugins do not get picked up by the system are therefore are marked as "Plugin has been removed from the file system." in the backend.

**Example:**
Consider the following `plugins` structure:
```shell
.
├── codedge -> ../../octobercms-plugin/src/codedge
├── feegleweb
├── october
└── rainlab
```

The symlinked plugin vendor, in the example `codedge`, _is not_ picked up by the `PluginManager.php` method `getVendorAndPluginNames()`:

```php
/**
     * Returns a 2 dimensional array of vendors and their plugins.
     */
    public function getVendorAndPluginNames()
    {
        $plugins = [];

        $dirPath = plugins_path();
        if (!File::isDirectory($dirPath)) {
            return $plugins;
        }

        $it = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($dirPath, RecursiveDirectoryIterator::FOLLOW_SYMLINKS)
        );
        $it->setMaxDepth(2);
        $it->rewind();

        while ($it->valid()) {
            if (($it->getDepth() > 1) && $it->isFile() && (strtolower($it->getFilename()) == "plugin.php")) {
                $filePath = dirname($it->getPathname());
                $pluginName = basename($filePath);
                $vendorName = basename(dirname($filePath));
                $plugins[$vendorName][$pluginName] = $filePath;
            }

            $it->next();
        }

        return $plugins;
    }
```

The iterator runs until the symlink is reached but does not list the files and folders _inside_ the symlink,  although the flag `RecursiveDirectoryIterator::FOLLOW_SYMLINKS` is set. As I saw this already has been handled [here](https://github.com/octobercms/october/pull/1552) - unfortunately it does not work with me.

Tested with Ubuntu 14.04, nginx, PHP 7.0.5, OctoberCMS build 344

**Comment by gabsource** [comment]
No problem on OS X : 
```
php artisan create:plugin Acme.Demo
mv plugins/acme ../
cd plugins/ && ln -s ../../acme && cd ..
php artisan plugin:refresh Acme.Demo

# ls plugins
acme -> ../../acme
october/
rainlab/
```

![image](https://cloud.githubusercontent.com/assets/1851314/15829326/91337ab2-2c13-11e6-881c-bd87b5e2a4f2.png)

-----

Permissions issue maybe ?

**Comment by codedge** [comment]
Thanks for the reply - found the issue one minute ago. When using symlinks make sure they are reachable in the VM (homestead) ;-)

Just needed to mount the folder correctly. I'll close the issue as this is solved / my own mistake!
