### ISSUE TITLE
Mediafinder form widget truncates filename

### ISSUE THREAD

**Issue by jBOKA** [octobercms/october#2104]
The mediafinder form widget truncates a character from the filename, when previewing a selected image.
For example if you select a file from the media manager called `example.jpg` it shows `xample.jpg`. There must have been some reason for this couriosity :) but I couldn't find it.
https://github.com/octobercms/october/blob/9dc1b4d836c8147f7fc0b3f752efe10d70a491f2/modules/cms/formwidgets/mediafinder/partials/_image_single.htm#L19

**Comment by daftspunk** [comment]
Interesting, we can only assume this is because the value was `/somefile.jpg` once upon a time? Perhaps it is no longer the case and we can remove it. It appears in both file_single and image_single partials.

**Comment by jBOKA** [comment]
I will check this again, seems like it is not always the case.

**Comment by jBOKA** [comment]
I cecked it again.
The "bug" occurred when seeding the database and specifying the filename manually. Although this didn't provoke any problems so far, the representation of the filename could be corrected by replacing `substr($value, 1)` by `ltrim($value, '/')` in the line mentioned above.

**Comment by daftspunk** [comment]
`ltrim` is a great idea because it solves the underlying issue and makes the intended logic more obvious.
