### ISSUE TITLE
Urgent - Can't login anymore - Error "The Code has already been taken" after upgrade to build 345

### ISSUE THREAD

**Issue by jfoliveira** [octobercms/october#2111]
What I have done:

1) I was running `build 332`

2) I just wanted to attach a project id to my production website to automatically download third party plugins. I attached the project id;

3) The following error message was displayed during the "Finishing update process" step:
```
Update failed

{"#layout-flash-messages":
" <p data-control=\"flash-message\" class=\"flash-message fade error\" 
data-interval=\"5\">The Code has already been taken.<\/p>\n",
"X_OCTOBER_ERROR_FIELDS":{"code":["The Code has already been taken."]}}
```

OctoberCMS now shows `build 345` instead of `build 332` but **I didn't ask for upgrading**, I just wanted to attach a project id.

Now, when I try to log into the backend the same error message is displayed `The Code has already been taken.` and no one can login. :-(

Any ideas on how to fix that?

**Comment by tobias-kuendig** [comment]
What plugins do you have installed? This doesn't look like an October error. Looks like a plugins isn't working as expected.

**Comment by jfoliveira** [comment]
@tobias-kuendig you are absolutely right! It seems after attaching the project id October started and failed to install the plugin https://octobercms.com/plugin/renatio-dynamicpdf 

I removed the plugin and now I can login. :-)
Thanks a lot for your help!

That's the first time I'm using third party plugins in production with OctoberCMS, so I might be messing things up.

I've just tried installing the plugin again from the command line:

```
php artisan plugin:install Renatio.DynamicPDF
```

This throws the exception:
```
 [ErrorException]      
  mkdir(): File exists 
```

After this exception has been raised the same error message `The Code has already been taken.` comes back when I attempt to login to the backend.

I'll try to live without this plugin for now.

Question:
How I can I know if this is an issue with a plugin or with the latest October build? Should I report this error to the plugin developer or is there any way to tell who causes the issue?

**Comment by tobias-kuendig** [comment]
I guess it's best to report it directly to the plugin maintainer:

https://github.com/mplodowski/DynamicPDF/issues

**Comment by jfoliveira** [comment]
Done! https://github.com/mplodowski/DynamicPDF/issues/17 
Thanks again @tobias-kuendig!

**Comment by bkrajendra** [comment]
I'm getting this error on my local server. I installed fresh new clean OCMS, tried to add some plugin and I got this error. Now when again tried to reinstall from scratch im getting error while creating admin account.

**Comment by daftspunk** [comment]
All plugins are tested before being published. Please contact the author of Clake.UserExtended to make sure they are aware of this issue.

**Comment by bkrajendra** [comment]
Yes ive contacted him and informed about the bug and solution to it.
https://github.com/ShawnClake/UserExtended
Actually he was having duplicate entries in seed_basic_user_groups.php
```
class SeedUserGroupsTable extends Seeder
{
    public function run()
    {
        UserGroup::create([
            'name' => 'Admin',
            'code' => 'admin',
            'description' => 'Administrator group'
        ]);

```
These entries are already there because of User plugin.
I just remove duplicate and it started working.
Sorry for bothering you. Basically it's my responsibility  to test and debug any plugin before using it on production environment.
I was just worried about some people who might be trusting codes blindly.
Although the above issue was very simple and small, it lock everything. Nothing was working.

**Comment by daftspunk** [comment]
Aha, I see. This needs a simple check before it

```
if (UserGroup::whereCode('admin')->count() > 0) {
    return;
}
```

**Comment by bkrajendra** [comment]
So is it ok if I put it like this:
```php
class SeedUserGroupsTable extends Seeder
{
    public function run()
    {

        if (UserGroup::whereCode('admin')->count() == 0) {
                UserGroup::create([
                    'name' => 'Admin',
                    'code' => 'admin',
                    'description' => 'Administrator group'
                ]);
         }

        if (UserGroup::whereCode('friend')->count() == 0) {
                UserGroup::create([
                    'name' => 'Friend',
                    'code' => 'friend',
                    'description' => 'Generalized friend group.'
                ]);
         }

        if (UserGroup::whereCode('guest')->count() == 0) {
                UserGroup::create([
                    'name' => 'Guest',
                    'code' => 'guest',
                    'description' => 'Generalized guest group'
                ]);
         }

        if (UserGroup::whereCode('tester')->count() == 0) {
                UserGroup::create([
                    'name' => 'Tester',
                    'code' => 'tester',
                    'description' => 'Access bleeding edge features'
                ]);
         }

        if (UserGroup::whereCode('debugger')->count() == 0) {
                UserGroup::create([
                    'name' => 'Debugger',
                    'code' => 'debugger',
                    'description' => 'Debug text, buttons, and visuals appear on the pages'
                ]);
         }

        if (UserGroup::whereCode('developer')->count() == 0) {
                UserGroup::create([
                    'name' => 'Developer',
                    'code' => 'developer',
                    'description' => 'Access to the dev tools and options'
                ]);
         }

        if (UserGroup::whereCode('banned')->count() == 0) {
                UserGroup::create([
                    'name' => 'Banned',
                    'code' => 'banned',
                    'description' => 'Banned from viewing pages'
                ]);
         }

    }
}
```

**Comment by daftspunk** [comment]
Something like this, yes. You could also try the `firstOrCreate` method which effectively does the same thing with less code.

http://octobercms.com/docs/database/model#mass-assignment
