### ISSUE TITLE
CSS-files of new report widgets (Welcome & Website) are not published to public folder

### ISSUE THREAD

**Issue by side-by-side** [octobercms/october#2113]
From build 340 of October CMS there are introduced two new report widgets: Welcome and Website.

When we are using public folder (https://octobercms.com/docs/setup/configuration#public-folder), after mirroring (`php artisan october:mirror public/`) CSS-files of these widgets are not published and not loaded on the Dashboard (404 Not Found).
The files:
* /modules/backend/reportwidgets/welcome/assets/css/welcome.css
* /modules/cms/reportwidgets/activetheme/assets/css/activetheme.css

**Comment by daftspunk** [comment]
This was fixed recently. Should be fixed next build.

**Comment by side-by-side** [comment]
Thank you very much, I found the commit. Closing.
