### ISSUE TITLE
CodeEditor styles broken after upgrade to 345?

### ISSUE THREAD

**Issue by jfoliveira** [octobercms/october#2118]
Just upgraded to `build 345` on my dev environment and RichEditor styles seem broken and icons duplicated:

<img width="914" alt="screen shot 2016-06-12 at 6 21 40 pm" src="https://cloud.githubusercontent.com/assets/1943318/15993907/b415b3cc-30ca-11e6-9ba0-2b20c2e51984.png">

I already ran `php artisan cache:clear` and went to `backend -> settings -> customize backend -> reset to default`.

Any ideas what is causing that?

**Comment by daftspunk** [comment]
Seems to be working fine over here. Have you cleared your browser cache?

**Comment by jfoliveira** [comment]
I have. Also tried on incognito window, no luck! I'll update if I make any
progress. Ideas are welcome. :-)

Seems to be working fine over here. Have you cleared your browser cache?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/octobercms/october/issues/2118#issuecomment-225469332>,
or mute the thread
<https://github.com/notifications/unsubscribe/AB2nFvHsxWowsMsvQTGV_xc5AT7ENovfks5qLKRGgaJpZM4Iz41c>
.

**Comment by jfoliveira** [comment]
It's now working again, but there is still an issue:

1) I was not exactly running `build 345`. As I had upgraded through `composer update` I was running the latest commit https://github.com/octoberrain/backend/commit/518fec9bb116107b191bb1aab1da42440c8108e9 that is yet to be included in a new build.

Rolled back to https://github.com/octoberrain/backend/commit/bd3d79a, and the code editor works fine again.

Ok, at this point all good!

2) Then I went to `backend -> updates` and the build number displayed was still 345 although I was running an old commit from April. Updating again through October the issue is back, and my third party packages (not October plugins) are removed from vendor folder. If I, again, run `composer update` the code editor broken style issue comes back.

The questions then are:

* How to use/update composer packages with October?
* Every time I update October my non-October packages are removed.
* Every time I update packages through composer my October installation is messed up.
* Is there a recommended balance to use composer packages with October?
* Is this issue happening only because I have `config/cms/edgeUpdates` turned on? How could I workaround it?

**Comment by jfoliveira** [comment]
I added a `composer.json` to my own plugin folder instead of adding the dependencies to the root `composer.json`.

In my deploy script I'm now running
 ```
composer install --working-dir=plugins/my/plugin_name/ --no-interaction --no-dev --prefer-dist
```

Is this the recommended approach?
