### ISSUE TITLE
How to integrate OctoberCMS with my Laravel app?

### ISSUE THREAD

**Issue by fanly** [octobercms/october#2119]
how to integrate october with my laravel app?

**Comment by daftspunk** [comment]
Off the top of my head, something like this:

1. Include the composer packages in composer.json
1. Extend October\Rain bootstrap / foundation classes instead of Laravel (app directory)
1. Introduce the [CMS config file](https://github.com/octobercms/october/blob/master/config/cms.php)
1. Run `php artisan october:up` to migrate the databases

Composer packages:

        "october/rain": "dev-develop",
        "october/system": "dev-develop",
        "october/backend": "dev-develop",
        "october/cms": "dev-develop",


Foundation classes:
```
October\Rain\Foundation\Http\Kernel
October\Rain\Foundation\Console\Kernel
October\Rain\Foundation\Exception\Handler
```

**Comment by Cellular-** [comment]
I'd love to learn how to do this too. I want to get more familiar with plain laravel but also have the power of octobercms.

**Comment by pedzed** [comment]
@daftspunk Adding these lines in the Composer file did not work for me:
````php
"october/rain": "~1.0",
"october/system": "~1.0",
"october/backend": "~1.0",
"october/cms": "~1.0",
```

It gives me these errors when running `composer install` or `composer update`.
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package october/rain ~1.0 is satisfiable by october/rain[1.0.x-dev] but these conflict with your requirements or minimum-stability.
  Problem 2
    - The requested package october/system ~1.0 is satisfiable by october/system[1.0.x-dev] but these conflict with your requirements or minimum-stability.
  Problem 3
    - The requested package october/backend ~1.0 is satisfiable by october/backend[1.0.x-dev] but these conflict with your requirements or minimum-stability.
  Problem 4
    - The requested package october/cms ~1.0 is satisfiable by october/cms[1.0.x-dev] but these conflict with your requirements or minimum-stability.
```

This also related to this issue: https://github.com/octobercms/october/issues/2256

**Comment by daftspunk** [comment]
@pedzed according to the error message it relates to the composer configuration for minimum stability.

> but these conflict with your requirements or minimum-stability

I understand this is to be the root of the problem, let's continue the conversation at #2256.
