### ISSUE TITLE
Error 'Unknown "placeholder" tag' when using Twig {% placeholder %} in backend

### ISSUE THREAD

**Issue by jfoliveira** [octobercms/october#2121]
October `build 345`.

I am trying to use the placeholder tag in a backend view as documented [here](https://octobercms.com/docs/markup/tag-placeholder) and [here](https://octobercms.com/docs/cms/layouts#placeholders).

On my controller, I'm loading the views using the approach [documented here](https://octobercms.com/docs/services/response-view#views) - **Passing a sub-view to a view**

Controller code:
```php
$viewData = ...;
$layoutData = ...;
$layout = View::make('my.plugin::default_layout', $layoutData);
$view = $layout->nest('sub_view_content', 'my.plugin::my_sub_view', $viewData);

return response($view);
```

Exception:
```
Unknown "placeholder" tag in "/plugins/my/plugin/views/layouts/default_layout.htm" at line 4.
```

Here is my relevant view code:
```html
<html>

<head>
{% placeholder info default %}
    <h1>Bajs</h1>
{% endplaceholder %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
```

I also tried using simply:
```html
<html>

<head>
{% placeholder head %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
```

and the same exception is thrown.

Anything that I am missing on the documentation or is this an issue on October `build 345`?

**Comment by gabsource** [comment]
Twig extensions are loaded by the frontend CMS controller class. If you are in the backend environnement you need to load Twig extensions yourself. Backend view/controller handling is different from frontend.

https://github.com/octobercms/october/blob/develop/modules/cms/classes/Controller.php#L497

**Comment by jfoliveira** [comment]
Thanks @gabsource! I'll investigate how to load Twig on the Backend.
