### ISSUE TITLE
UI bug on Forgot your password page

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#2125]
In English, the layout is right:
![ui-en](https://cloud.githubusercontent.com/assets/2959112/16073628/2c76f83a-32e7-11e6-9fac-50d945243c3e.jpg)

If the text of button is too long:
![ui-hu](https://cloud.githubusercontent.com/assets/2959112/16073669/5c1f4858-32e7-11e6-8bcb-b7878cd54890.jpg)

**Comment by daftspunk** [comment]
Fixed by #2513 

This will be available in Build 385+
