### ISSUE TITLE
Laravel version

### ISSUE THREAD

**Issue by ChristianGiupponi** [octobercms/october#2129]
Hi, on which version of Laravel is based the cms? Can't find anything on the site.

**Comment by daftspunk** [comment]
She uses Laravel 5.0 at the moment, it will change to 5.1 on July 2nd. Or you can enable `cms.edgeUpdates` to get the developer copy which uses 5.1 also.

**Comment by jofrysutanto** [comment]
Glad to know we have set the date (and a little bit curious to know how we come about to July 2nd). 
Our team have one project in the works, been eagerly waiting for Stable (L5.1)
