### ISSUE TITLE
Exception on loading blog page

### ISSUE THREAD

**Issue by torsybil** [octobercms/october#2136]
We made an entire blog using [RainLab.blog](https://octobercms.com/plugin/rainlab-blog) but after we were done and opted to get user LDAP interface we get that the rainlab.blog component doesnt exist. The plugin is entirely disabled we cannot enable it unless we just remove it. We removed the plugin and cleared our cache.

When we reinstalled the [RainLab.blog](https://octobercms.com/plugin/rainlab-blog) successfully but it keeps throwing an exception which to us looks like a database issue. What is wrong prior and after?

![exception 2016-06-19 11-23-00](https://cloud.githubusercontent.com/assets/13916761/16176220/60c0ff1e-3611-11e6-9d0d-c154e929516b.png)

**Comment by daftspunk** [comment]
This error suggests the database tables are missing. Possibly because the plugin is not detected and not migrating properly. Logging out and signing back in will trigger the migration to occur.

**Comment by torsybil** [comment]
Logging out and sigining back solved the issue. This was a database - plugin connection problem. For reference purposes this is what we see in error log:
`PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lwpdks_october.rainlab_blog_posts' doesn't exist in /home/lwpdks/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:292`
