### ISSUE TITLE
Media preview by click don't work under Firefox (dev)

### ISSUE THREAD

**Issue by reeslo** [octobercms/october#2143]
![pyrocms-media](https://cloud.githubusercontent.com/assets/2724844/16235401/0f5d0d32-37d5-11e6-95ea-44124399cb20.gif)

**Comment by reeslo** [comment]
When double click ultra fast work (sometimes)

**Comment by daftspunk** [comment]
Unable to replicate this using Firefox v47.0.1. It also appears to be working fine in the screen capture above? Please provide more info

**Comment by reeslo** [comment]
I will check monday at work, perhaps its a FF issue.

**Comment by reeslo** [comment]
I, sorry for late reply, on screen it's not visible, but I double and more click for open, I come back 29/08 for give you more info

**Comment by daftspunk** [comment]
You are supposed to double click to move in to a folder. As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by reeslo** [comment]
Was on media information like in screenshot

**Comment by daftspunk** [comment]
Does it still happen? I can't seem to make it happen.

**Comment by reeslo** [comment]
Perhaps was firefox I have to check at work, I am in vacation
