### ISSUE TITLE
Add BMP image support in the library/src/Database/Attach/Resizer.php class

### ISSUE THREAD

**Issue by robinbonnes** [octobercms/october#2144]
Hello,

When I upload images straight from my camera's sdcard using the RJGallery plugin, it gives the following error:

imagesx() expects parameter 1 to be resource, boolean given
vendor/october/rain/src/Database/Attach/Resizer.php line 80

This happens because the uploaded (jpg) image has the mime type: image/x-ms-bmp

In the 'openImage' function there is no support for that mime type, and createfromjpg is not working because its an bmp image.

What I did to fix this for me:

Add to line 244 of Resizer.php:

case 'image/x-ms-bmp': $img = $this->imagecreatefrombmp($filePath); break;

Add below the openImage function (line 251):

   /**
     \* Create an image from bmp
     \* @param string $fileName
     \* @return resource
     _/
    function imagecreatefrombmp($fileName) {
        $file = fopen($fileName, "rb");
        $read = fread($file, 10);
        while (!feof($file) && ($read <> ""))
            $read .= fread($file, 1024);
        $temp = unpack("H_", $read);
        $hex = $temp[1];
        $header = substr($hex, 0, 108);
        if (substr($header, 0, 4) == "424d") {
            $parts = str_split($header, 2);
            $width = hexdec($parts[19] . $parts[18]);
            $height = hexdec($parts[23] . $parts[22]);
            unset($parts);
        }
        $x = 0;
        $y = 1;
        $image = imagecreatetruecolor($width, $height);
        $body = substr($hex, 108);
        $body_size = (strlen($body) / 2);
        $header_size = ($width \* $height);
        $usePadding = ($body_size > ($header_size \* 3) + 4);
        for ($i = 0; $i < $body_size; $i+=3) {
            if ($x >= $width) {
                if ($usePadding)
                    $i += $width % 4;
                $x = 0;
                $y++;
                if ($y > $height)
                    break;
            }
            $i_pos = $i \* 2;
            $r = hexdec($body[$i_pos + 4] . $body[$i_pos + 5]);
            $g = hexdec($body[$i_pos + 2] . $body[$i_pos + 3]);
            $b = hexdec($body[$i_pos] . $body[$i_pos + 1]);
            $color = imagecolorallocate($image, $r, $g, $b);
            imagesetpixel($image, $x, $height - $y, $color);
            $x++;
        }
        fclose($file);
        unset($body);
        return $image;
    }

Ofcourse this is not a proper fix because it will be gone when I update the core. However what do you guys think, should there be support for this mime type, or should I convert all images first before uploading?
- Robin

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

@robinbonnes if you would still like this support added, then add it in a PR to octobercms/library and we can review it there.
