### ISSUE TITLE
Minor CSS issue on the tabs

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#2147]
When I use the TAB key, a blue border appears around the tab.
![css-issue](https://cloud.githubusercontent.com/assets/2959112/16340131/b2634fca-3a26-11e6-8679-984a6f8d1035.jpg)

**Comment by scvnathan** [comment]
I don't think this is a CSS issue - pretty sure that blue border when tabbing is just a feature of your browser.

**Comment by gergo85** [comment]
Yes, it isn't a typical CSS issue. If the border doesn't appear, probably the tabs look like nicer.

**Comment by Eoler** [comment]
But then they wouldn't be [accessible](http://outlinenone.com/).

**Comment by gergo85** [comment]
You are right. It would be other style (for example different background) instead of blue outline.

**Comment by daftspunk** [comment]
This has likely been inherited from bootstrap. It doesn't look too bad as it is, feel free to submit a PR to improve it.
