### ISSUE TITLE
Feature Request: Artisan command to link Project Id

### ISSUE THREAD

**Issue by jmondragon** [octobercms/october#2149]
I've been working on a Docker image as well as some OpenShift images for both Openshift Online, and Openshift (NextGen) Online.  During deployment, it would be nice to be able to link to the Project ID and have it install themes and plugins from the Marketplace.  I thought an artisan command would be the right place to do this so that I could just run something like:

```
php artisan project:link xyz
```

during deployment.

Thank you

**Comment by jhabdas** [comment]
@jmondragon Would you please link to your Dockerfile?

**Comment by jmondragon** [comment]
Sure!  If you can get it from here:
https://hub.docker.com/r/dragontek/octobercms/

Or the Github repo is here:
https://github.com/dragontek/octobercms

Thank you

**Comment by daftspunk** [comment]
Good idea, perhaps `october:project` would be a better name, seeing as it will have no siblings. Feel free to submit a PR for this.

**Comment by SebastiaanKloos** [comment]
I’ll create a pr next week

**Comment by LukeTowers** [comment]
@SebastiaanKloos could just be under the `october:util` namespace, so `php artisan october:util link project $projectId`

**Comment by SebastiaanKloos** [comment]
It looks like the command is already there. `php artisan october:util set project $projectId`.

Haven’t tested it but found it in the code...

**Comment by LukeTowers** [comment]
@SebastiaanKloos right you are! Added almost a year ago in https://github.com/octobercms/october/commit/cd275554f2a2b91b3d366719b4d71a6a253175ff (#3946). This was fixed with the resolution to #3944
