### ISSUE TITLE
Count relationship display bug

### ISSUE THREAD

**Issue by aurukas** [octobercms/october#2150]
I'm trying to setup the count relationship, but somehow the model relationship is displayed in json (square brackets and {} ), therefore twig is not able to access it with the "dot". I have recreated it in sterile plugin/theme. Model "Sports" has a relationship with "Products" setup: 'products_count' => ['Newcode\Counttest\Models\Product', 'count' => true]

in controller: 
`$this['sports'] = Sports::all();` 
and in twig:`{% for sport in sports %} ({{ sport.products_count }}) {% endfor %}`

The result is 
basketball ([]) football ([{"sports_id":"2","count":"5"}])

but I am not able to access the count variable with a dot as expected. The result is 1 (if exists and 0 if none)

I'm herewith attaching a test template/plugin.

[count_bug.zip](https://github.com/octobercms/october/files/333145/count_bug.zip)

**Comment by aurukas** [comment]
I have noticed just now that same behavior is observed in more relation cases in general

**Comment by aurukas** [comment]
the way to solve it is by putting zero before the variable to be accessed, ie: `{{ sport.products_count.0.count }}`

**Comment by GitJaap** [comment]
I had exactly the same problem, the 0 fixed it

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
