### ISSUE TITLE
Setting up logo of app - crash

### ISSUE THREAD

**Issue by exotickg1** [octobercms/october#2152]
/backend/system/settings/update/october/backend/branding
I'm upload here my Application logo (png, 3820x4122) and it was bad idea :sob: 

![Image of Yaktocat](https://i.gyazo.com/3d57ab51303a2f5b531ab721dcda0b6a.png)

Now i cant load this page, and reset the logo.

UPD: I'm fix the problem and can open the page (deleted file from storage/app/uploads/public)

**Comment by daftspunk** [comment]
Ran out of memory trying to resize it!

**Comment by daftspunk** [comment]
We could limit the size or not attempt to resize...

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
