### ISSUE TITLE
AJAX framework - dynamically setting `Confirm` and `Cancel` button text on swal

### ISSUE THREAD

**Issue by jofrysutanto** [octobercms/october#2153]
At the moment we are using `lang/xx/client.php`file to set button text on the sweet alert implementatio. However, in some cases the default _Ok_ and _Cancel_ (for english) does not sound the right reply to 'Are you sure you want to .....?' (Yes and No would have been better).

An idea will be to have it as part data-\* attribute?

The native confirm implementation should simply ignore these settings.

**Comment by LukeTowers** [comment]
@jofrysutanto as of https://github.com/octobercms/october/commit/88ed5c2c6455bc906cc2679cf8403b3e9e5771aa you should be able to have complete control over your confirmation popup via the extension of the AJAX framework like so:
```js
$(document).on('ajaxSetup', '#my-element', function(event, context) {
    context.options.handleConfirmMessage = function (message) {
        // custom logic here
    };
});
```

**Comment by jofrysutanto** [comment]
Love this!
