### ISSUE TITLE
System Update/Plugin Repository Server 301 Document moved

### ISSUE THREAD

**Issue by Crazymodder** [octobercms/october#2158]
Hi,

I try today to make a system update i ran into the following error:

`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>301 Moved Permanently</title> </head><body> <h1>Moved Permanently</h1> <p>The document has moved <a href="https://octobercms.com/api/core/update">here</a>.</p> <hr> <address>Apache/2.4.7 (Ubuntu) Server at gateway.octobercms.com Port 80</address> </body></html>`

Also plugin installations does not work:
`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>301 Moved Permanently</title> </head><body> <h1>Moved Permanently</h1> <p>The document has moved <a href="https://octobercms.com/api/plugin/details">here</a>.</p> <hr> <address>Apache/2.4.7 (Ubuntu) Server at gateway.octobercms.com Port 80</address> </body></html>`

Regards
Crazymodder

**Comment by abstractFlo** [comment]
Same here!

**Comment by a2thek26** [comment]
Same.

**Comment by scvnathan** [comment]
Hey guys, it just looks like the createServerUrl() method in the UpdateManager class needs to get updated.

I was able to get updating working again by changing:

```$gateway = Config::get('cms.updateServer', 'http://gateway.octobercms.com/api');```
to
```$gateway = Config::get('cms.updateServer', 'http://octobercms.com/api');```

This is apparently already fixed in develop but I guess they just haven't pushed out the update yet.

**Comment by Crazymodder** [comment]
Hi scvnathan,

Great thanks for that info. So simply the best solution is to add this

```
/*
    |--------------------------------------------------------------------------
    | Update server
    |--------------------------------------------------------------------------
    |
    | Specifies the URI used for System Updates 
    |
    */
    'updateServer' => 'http://octobercms.com/api',
```

to config/cms.php

**Comment by a2thek26** [comment]
This fixed it indeed.

**Comment by daftspunk** [comment]
This was a server configuration issue. It has been fixed now. Thanks
