### ISSUE TITLE
Record Finder Bug: Search does not persist across pagination

### ISSUE THREAD

**Issue by jfoliveira** [octobercms/october#2161]
If the user types anything on the `recordFinder` search box and the result set has more than one page, when clicking on the `next page` button the search term is ignored and all records are displayed.

How to reproduce using the [october test playground plugin](https://github.com/daftspunk/oc-test-plugin):
1) Modify the file `/plugins/october/test/models/phone/fields.yaml` setting the `person` field `recordsPerPage` property:
```yaml
    person:
        ...
        type: recordfinder
        recordsPerPage: 2
        ...
```

2) On the backend browse to `Playground -> People -> New Person -> Alternate Views -> Relation Controller -> Create Phone` and then click the `Record Finder` field to display the list of people;
* The list will open displaying only two records.
* Pagination control text will be:
```php
Displayed records: 1-2 of 6 # correct
```

3) Type `jo` to filter only the people whose names contain `jo`.
* The list wil display only two records:
```
Jon Smith
John Smith
```

* Pagination control text will be:
```php
Displayed records: 1-2 of 3 # correct
```

4) Click the `next page` icon on the pagination control.
* The list will display two records instead of one
  * as first page message was telling us `records: 1-2 of 3` there should be only one record to be displayed on page 2.

* Pagination control text will be:
```php

Displayed records: 3-4 of 6 # WRONG!!!! :-(
```

**Comment by jfoliveira** [comment]
Is there any further info I can provide to help reproduce and confirm this bug?

**Comment by daftspunk** [comment]
I was able to replicate this, thanks @jfoliveira
