### ISSUE TITLE
Froala editor doesn't save latest edit when saving with ctrl+s right after typing

### ISSUE THREAD

**Issue by fresswolf** [octobercms/october#2163]
##### Expected behavior
Type something in the richeditor, press Ctrl/Cmd+S -> Text is saved.

##### Actual behavior
If I don't wait two seconds between typing and pressing Ctrl+S, the typed text is lost.

##### Reproduce steps
Type "hello test" into the richeditor, immediately press Ctrl/Cmd+S after. Preview the page or reload the backend page and see how the text gets lost.
It doesn't seem to happen when clicking the "save" button with the mouse.

##### October build
346

**Comment by daftspunk** [comment]
Please test again using the latest build (350+), there was some code implemented that addressed this.
