### ISSUE TITLE
[website] "Marketplace for authors" link on the author's plugin update page is wrong

### ISSUE THREAD

**Issue by tobias-kuendig** [octobercms/october#2167]
On the page `https://octobercms.com/account/plugin/updates/xxx` the `Marketplace for authors` link points to https://octobercms.com/help/site/marketplace#for-authors.

The same link is referenced in the modal after clicking on `Display update url`

The correct url is https://octobercms.com/help/site/authors

**Comment by alekseybobkov** [comment]
Fixed, thanks.
