### ISSUE TITLE
FileUpload configuration form should be rendered using the Form Widget

### ISSUE THREAD

**Issue by jajacobs** [octobercms/october#2168]
I would like to extend the fileupload configuration form by adding new fields to it.

This is currently not possible because the configuration form is a partial.

**Comment by daftspunk** [comment]
What fields would you add to it?

**Comment by jajacobs** [comment]
Right now i wanted to add another text field were a client can add a link. The data itself would be saved in another table by extension using a relation. I know this may be possible by creating a custom model and attaching an image relation to it. But then you loose all the benefits of the fileupload widget like being able to upload many images at the same time and easy sorting etc.

**Comment by yapsr** [comment]
I would like to add a field "count" to be able to track downloads of fileuploads (system files) and add this information in the backend by overriding the partial fileupload/partials/_file_multi.htm

If another solution is already available, I would be grateful if anybody points me in the right direction.

**Comment by LukeTowers** [comment]
This should be taken care of when I implement MediaManager metadata
