### ISSUE TITLE
Pages plugin: issue with multiple snippet instances

### ISSUE THREAD

**Issue by codee** [octobercms/october#2169]
##### Bug summary
As of October build 346 and Pages ver. 1.2.6, when multiple snippet instances are created, they all appear to use the parameter value of the last instance instead of using their own. This was working properly before with October build 318 and Pages ver. 1.1.11.

https://octobercms.com/forum/post/issue-with-multiple-snippet-instances

##### Reproduce steps
Create a plugin, create a component with a dropdown parameter, register it as a snippet, insert multiple instances of it on a page with different parameter values.

##### Expected behavior
Each snippet instance should use its own parameter value instead of that of the last instance.

##### Actual behavior
The last snippet's parameter value is used on all snippet instances instead of those set in the backend.
NOTE: The same component code works as expected with a regular CMS page (without the Pages plugin), so the issue is likely with the Pages plugin, not October itself.

**Comment by hybridvision** [comment]
I think this is the wrong place for this bug report since it relates to the pages plugin, not the core of October CMS.

See here for my bug report of this issue: https://github.com/rainlab/pages-plugin/issues/177

**Comment by daftspunk** [comment]
Duplicate https://github.com/rainlab/pages-plugin/issues/177

**Comment by codee** [comment]
@hybridvision Thanks for pointing that out. I thought about that but couldn't find the Pages repo.

**Comment by hybridvision** [comment]
@codee - you're welcome :) FYI: The repository for plugins is normally linked from the relevant plugin's page on the October CMS site. There's lots of good stuff to be discovered from The Rain Lab.
