### ISSUE TITLE
Outputting rich editor custom styles to page  automatically

### ISSUE THREAD

**Issue by codaha** [octobercms/october#2170]
There should be some way to let components output css of rich editor custom classes to page.
From i learned on forum, right now only way is manually copying this css to your stylesheet.

**Comment by daftspunk** [comment]
This is normal to define your stylesheets on the front end manually. The rich editor stylesheets can be defined by the administrator in Settings > Editor Settings. We may consider adding this feature in future, or you are welcome to submit a PR to add it.
