### ISSUE TITLE
drag-scroll in html tag with direction rtl not working

### ISSUE THREAD

**Issue by cracki** [octobercms/october#2171]
##### Expected behavior

as usual main nav-menu with too many items must drag-scroll  
##### Actual behavior

if apply "direction:rtl" to "html" in backed css drag-scroll not working
##### October build

346 and 318 tested

**Comment by daftspunk** [comment]
The RTL support for October is limited, we need someone to help contribute this functionality using Pull Requests.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
