### ISSUE TITLE
Settings tab can't be disabled for specific user group

### ISSUE THREAD

**Issue by goeroe** [octobercms/october#2175]
##### Expected behavior

I want to be able to disable the settings tab for a specific backend user group.
Not all plugins seem to have the ability to disable them (for example SEO extension and Sitemap)
Some users shouldn't be able to change anything in the settings.
##### Actual behavior

If you disable everything you will be left with everything in the settings tab without permission settings
##### Reproduce steps

Settings  > administrators >  Manage groups > disable all system permissions > login via user from that group
##### October build

346

**Comment by daftspunk** [comment]
The settings tab is not controllable by permissions, per say. We should include some logic to check if there are any visible items under settings, and if not, hide the top level menu item.

**Comment by keiosweb** [comment]
Yes it looks silly, [screen](https://i.keios.eu/jz/issue-161023-150153.png)

**Comment by daftspunk** [comment]
> Yes it looks silly, *screen*

*Screenshot* shows the settings menu active but there are no settings in the side bar.

**Comment by keiosweb** [comment]
ah you are right, I have misread ticket, this is not what OP meant, my screenshot is for another another tune up ticket / [J]

**Comment by daftspunk** [comment]
All good, was merely describing the screenshot in case the image was pulled offline.
