### ISSUE TITLE
Add permission for Dashboard "make default"

### ISSUE THREAD

**Issue by goeroe** [octobercms/october#2176]
##### Expected behavior

If you setup a dashboard with some widgets and click "safe default" I thought this was set as default for all the other users / user groups but it seems that is not the case. 

"safe default" as in "for future new users"?
##### Actual behavior

I don't know what this does...
##### Suggestions

Add permission to disable the "add widget" button. Not all users should be able to edit / mess up their dashboard.
##### October build

346

**Comment by joseph-d** [comment]
I'd like to know if the suggestion @goeroe made will be given any consideration.

Having the ability to modify the dashboard layout and then save a default for backend users created in the future is a very good thing. However, I think that there should be a permission that either hides "Manage Widgets" completely or, preferably, just hides the "Make Default" button from certain users.

In short, letting users mess up their own dashboard is fine by me, but at the moment they have the ability to mess it up for newly-created users, too, which I don't think is desirable for many people.
