### ISSUE TITLE
Should master branch composer json be pointing to `dev-develop`

### ISSUE THREAD

**Issue by jofrysutanto** [octobercms/october#2177]
##### Expected behavior
The current master branch is pointing at `dev-develop`:
        "october/rain": "dev-develop",
        "october/system": "dev-develop",
        "october/backend": "dev-develop",
        "october/cms": "dev-develop",

Is this going to cause users who use composer to update their OctoberCMS to always have bleeding edge update?

##### Actual behavior
Maybe we should have `1.0.*`?
        "october/rain": "1.0.*",
        "october/system":  "1.0.*",
        "october/backend":  "1.0.*",
        "october/cms":  "1.0.*",

**Comment by tonyTacony** [comment]
This is an issue I am running into today, even though I am trying to checkout versions via hash, it is forcing me to have a dev-develop branch on october/rain, breaking changes are big in october

**Comment by daftspunk** [comment]
This was a relic from edge testing, fixed in 5eab01b8bd2294f14b5b294c619f9a449847b783
