### ISSUE TITLE
Back-end Preferences - Locale

### ISSUE THREAD

**Issue by marcoelho97** [octobercms/october#2178]
##### Expected behavior

Well, in my opinion, the locale should have "Portuguese ( Portugal )"
##### Actual behavior

It has "Portuguese ( Brazil )
##### October build

I am using latest october build, 346

**Comment by nacr-dev** [comment]
+1

**Comment by morsaPT** [comment]
+1

**Comment by jareis** [comment]
Maybe some should take the time to translate it.
And, by the way, should it be used PT, with "[acordo ortografico](https://pt.wikipedia.org/wiki/Acordo_Ortográfico_de_1990)", without or both?

**Comment by nacr-dev** [comment]
oh @jareis deixa-te de coisas é logo com os dois! qual é a tua, estas armado em esquisito!

**Comment by daftspunk** [comment]
PR please

**Comment by nacr-dev** [comment]
@daftspunk how much code exactly are we talking about here?

**Comment by jareis** [comment]
@nacr-dev not much the lang/en.php has 316 lines.

**Comment by daftspunk** [comment]
Portuguese ( Brazil ) and Portuguese ( Portugal ), [identical language](https://youtu.be/-GrrrJWkEpM?t=37s)? 

Is there is no difference, simply call it Portuguese and we rename `pt-br` to `pt`.

**Comment by nacr-dev** [comment]
@jareis your opinion on @daftspunk feedback!

**Comment by daftspunk** [comment]
Eg, this file: https://github.com/octobercms/october/blob/master/modules/system/lang/pt-br/lang.php

Pretend it is **pt-pt/lang.php**:

```
$lang = include __DIR__ . '/../pt-br/lang.php';
$lang['app']['name'] = 'Wakka wakka CMS';
return $lang;
```

**Comment by jareis** [comment]
@daftspunk, not really, the difference is the same as the en-UK and en-AU.

The "acordo ortografico" should merge all the PT based languages ( pt-pt, pt-ao, pt-br, etc...) based languages, but is not really implemented, and create a PT language ( something like the comercial english).

I never finished a PT translation, in part because of this mess and because I never needed to.

But it can be easily done with some adjustments to the pt-BR files

**Comment by jareis** [comment]
After analysing the pt-BR file probably is for the best to use en.php file.

@daftspunk can you, please, point all the translation files location ( i can't find them in the documentation )

**Comment by jareis** [comment]
@marcoelho97 @nacr-dev @morsaPT 

I have created crowdin project to help with the translation process
https://crowdin.com/project/octobercms-pt-pt/

Feel free to colaborate

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
