### ISSUE TITLE
Feature Request: Add searching ability to long checkboxlist fields

### ISSUE THREAD

**Issue by graker** [octobercms/october#2179]
Hi

When using [relation widget](https://octobercms.com/docs/backend/forms#widget-relation) with multiple relationships, it will display a checkbox list. But when there are hundreds or thousands of models to reference, it could be hard for a user to look through the list. So it may be handy to add a search box to long lists of checkboxes, performing simple text filtering with Javascript.

For now I have added a simple script to my plugin, to support checkbox search just there. Posting it here for convenience. Off course it is quite straightforward and could be done more elegantly. For example, search box html could be added to widget's partial.
It targets only scrollable lists leaving short lists untouched.

``` JavaScript
/**
 * This script adds input box to do the text search for relation widgets
 * Usable to look through checkboxes when there are thousands of possible relations
 */

+function ($) {

  /**
   *
   * Adds search box and binds events to it
   *
   */
  var attachSearch = function () {
    var searchInput = '<div class="form-group" style="width:70%;padding-top:15px;"><input type="text" placeholder="Search" class="form-control search-checkboxes"></div>';
    var $checkbox = $(this).find('div.checkbox').first();
    $checkbox.before(searchInput);
    $checkbox.parent().find('input.search-checkboxes').on('keyup', searchCheckboxes);
  };


  /**
   *
   * Performs search through checkboxes, hides those not containing query
   *
   * @param e
   */
  var searchCheckboxes = function () {
    var query = this.value.toLocaleLowerCase();
    $(this).parents('div.field-checkboxlist').find('div.checkbox').each(function () {
      var labelText = $(this).find('label').text();
      if (labelText.toLocaleLowerCase().indexOf(query) != -1) {
        $(this).show();
      } else {
        $(this).hide();
      }
    });
  };


  /**
   * Searches for all checkboxlists and attach search box to each one
   */
  var initCheckboxlistSearch = function () {
    // we add only to scrollable lists (non scrollable are short)
    var $widgets = $('div.field-checkboxlist-scrollable');
    $widgets.each(attachSearch);
  };


  /**
   * document.ready callback
   */
  $(document).ready(function () {
    initCheckboxlistSearch();
  });

} (window.jQuery);
```

I use this code in my [MapMarkers](https://github.com/graker/mapmarkers) plugin to attach multiple blog posts to marker models. And there are lots of posts so I've added the search.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

@graker if you would still like to see support for this added, please make a PR implementing this functionality and we'll review it.

**Comment by graker** [comment]
@LukeTowers I'm not sure if I really need this to be in the core, it's all right with this code being a part of my plugin. I just thought maybe it could be useful for others to have the filtering function for their long lists of relationships. Since no one took interest in the issue, I guess it's not so useful at the moment :)

I'd love to make a PR for this but I'm kinda overwhelmed with the work right now (aren't we all). Could try to do it probably next month, but then again if no one thinks it is useful, maybe it's not worth doing.

**Comment by LukeTowers** [comment]
@graker fair enough. I think it sounds like a good idea in theory at least, although I'm unsure of how many use cases have a multiple relationship setup where they are using the relation formwidget. 

Have you looked at using the relation controller for your use case?

**Comment by graker** [comment]
Nope. For my use case, it was about showing the models and link them to the model being edited, with no need to perform any other actions with related models. Relation formwidget seemed like the easiest way to do just that.
