### ISSUE TITLE
formExtendRefreshFields runs too late

### ISSUE THREAD

**Issue by mcustiel** [octobercms/october#2181]
I have a form that I extend programatically with a custom widget. Using `formExtendFields` method. There is a switch in this form, when it is set to false my custom widget is set to hidden, and when the switch is set to true, the custom widget is shown. This is done using `formExtendRefreshFields` method.
This works ok, but if the switch is set to false when the form loads (because it is false in database), I can not save the changes in the custom widget. It seems it is because of this in `line 966` from `modules/backend/widgets/Form.php`:

```
           if ($field->disabled || $field->hidden) {
                continue;
            }
```

That portion of code runs inside `getSaveData()` which is called before the event `form.refreshFIelds` is fired, making it imposible to get the data if the form was changed to be visible.
##### Expected behavior

The changes made through `formExtendRefreshFields` run before getSaveData so if a field was enabled or made visible, it value can be taken.
##### Actual behavior

The changes made in `formExtendRefreshFields` does not affect the form's save data.
##### Reproduce steps
- Add a switch control in the form (boolean value).
- Add a custom field with option hidden = true using `formExtendFields` method in a controller.
- Make the custom field to depend on the switch (dependsOn).
- Use formExtendRefreshFields to hide or show the custom field.
- Print the value returned by getSaveData in formBeforeSave method.
- You will see that the custom data is not present even if it is visible but it is being sent in the ajax request.
##### October build

1.0

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
