### ISSUE TITLE
AJAX Framework does not handle file downloads

### ISSUE THREAD

**Issue by dudheit** [octobercms/october#2182]
##### Expected behavior

If you use ``return Response::download('file.txt');`` in an AJAX Controller method, the browser should download the file.

##### Actual behavior

Nothing happens. No file will be downloaded.

##### Reproduce steps

1) Specify a controller method with Download response:

     public function onAjaxDownloadTest()
     {
        return Response::download('path/to/file.txt');
     }

2) Start an backend AJAX call to the controller function, e.g. using a button 

    <button
        data-request="onAjaxDownloadTest"
        data-stripe-load-indicator>
            Download via AJAX
    </button>

##### October build

October Build 347

**Comment by DMeganoski** [comment]
This is not an October issue. First, the response class is part of Laravel's base. The October developers have no control over this class.

Second, this does not work the way you expect it. The browser does not parse an ajax response as it would a normal one, so the headers that tell the browser that is a file to download are ignored.

You need to figure out an alternative solution. Here is one thread on the subject on stackoverflow:
http://stackoverflow.com/questions/20830309/download-file-using-an-ajax-request

**Comment by dudheit** [comment]
Thanks for your reply! Ok, I see. However, I was thinking there must be an OctoberCMS way to implement an file export. It seems to me a pretty common thing to select some items from a backend list and send a file with the exported items back, isn't it?

**Comment by daftspunk** [comment]
This is an issue addressed in #2003 -- it is awaiting peer review. Although the approach seems too dirty, it may not be accepted.

Take a look at this code for an example on how to download a file from AJAX, simply redirect to a regular URL: https://github.com/octobercms/october/blob/43eb8c49467c44ba4822eb1b287e11dd63d21bff/modules/cms/controllers/Themes.php#L282-L302

**Comment by zakir1929** [comment]
is there any solution available to this issue now @daftspunk @LukeTowers  ???

Thanks

**Comment by zakir1929** [comment]
ok i did the redirect solution which @daftspunk suggested. Thankyou guys
