### ISSUE TITLE
Error after Updating to new Stable release

### ISSUE THREAD

**Issue by bkrajendra** [octobercms/october#2185]
Getting Following error:
This error comes only after a specific user logs in and if we try to view its profile from backend.
Looks like last login date related issue in date difference calculation.
![ocerror](https://cloud.githubusercontent.com/assets/994083/16634271/8c761d56-43ea-11e6-8c04-346a325d55a1.PNG)

**Comment by daftspunk** [comment]
Update to the latest user version that should fix it. Thanks
