### ISSUE TITLE
403 error after wizard installation

### ISSUE THREAD

**Issue by redstrike** [octobercms/october#2189]
##### Expected behavior

Works normally before the stable release.
##### Actual behavior

403 on both backend and front-end. Try to modify the .htaccess, frontend can be accessed but without css / loading assets / 404.
##### Reproduce steps

Windows 10 Pro. Uniform Server. PHP 7.0.8
##### October build

https://octobercms.com/download

**Comment by daftspunk** [comment]
Error 403 suggests a permission problem. Things to check:

- Check the web server has access to execute the files
- Open the web server error log for the exact error message

**Comment by redstrike** [comment]
Apache doesn't log anything related to my 403 access to october. After I moved all of october's files to a sub-folder, the index page cannot see the october folder. When I move away the .htaccess, I can see the october folder again.

With the same setup, I was able to install october before July 2, and also tried the bleeding edge version. But I decided to do a clean install after the stable release instead of using the old bleeding edge version.

![october htaccess](https://cloud.githubusercontent.com/assets/2168227/16679884/51ce4e68-4515-11e6-8d35-d685ee8dc934.png)

**Comment by daftspunk** [comment]
We should find the reason behind the 403 code. Without the error it is stabbing in the dark. I can't offer much more assistance without it I'm afraid.

**Comment by redstrike** [comment]
The latest version works normally on my Linux server. Do you have any Windows PC to test?
The last version that works on my Windows PC is on **June 28**.

**Comment by daftspunk** [comment]
I do use Windows, but XAMPP instead of Uniserver, XAMPP will produce error messages when an error code is displayed. Without the error message there is nothing that can be done on our end. This is definitely a server configuration issue, not related to the October code. Try contacting Uniserver team for support?

http://stackoverflow.com/questions/33227061/enabling-rewriteengine-in-apache-uniserver-causes-403-on-all-files

**Comment by redstrike** [comment]
Added
```
Options +SymLinksIfOwnerMatch
```
or
```
Options +FollowSymlinks
```
to .htaccess file, and it works now.

Here is the note at UniServerZ's wiki: http://wiki.uniformserver.com/index.php/Htaccess:_Preventing_hot_linking#General_note

Should we update the .htaccess of October?

**Comment by daftspunk** [comment]
Great, I'm glad you were able to find the solution. That is a good question. We will need to look at if this is generally a good option to use, or if it relates to UniServer specifically, then we can create a Known Error article about it.

Thanks for sharing your findings.

**Comment by i-bajrai** [comment]
I got this problem because I did the public folder mirror on my host my machine when I was using homestead. Just SSH into the VM and run 

`php artisan october:mirror public/`

happy life.

**Comment by bkrajendra** [comment]
I was getting similar problem after installation of OCMS in my DigitalOcean centOS VPS.
The problem was mod_security.

Solution is to either remove mod_security or add SecRuleRemoveById in global_disabled_rules.conf 
based on your error log.
