### ISSUE TITLE
Why use "backend_users" table for backend users?

### ISSUE THREAD

**Issue by that0n3guy** [octobercms/october#219]
I just started digging into october a little more.  I see that there is a backend users table.   

Since this is a "backend" (ie backend specific) users table it requires plugins like: https://github.com/rainlab/user-plugin to create its own table.   Now you have 2 tables containing user's.... 

This seems inefficient as now there are 2 models/controllers/components doing a lot of the same things (logging users, creating user accounts, sending emails, etc...).  

If I want user groups/roles for the frontend users, I have to create that functionality... even though a lot of this is the backend module: http://octobercms.com/docs/backend/users

Am I thinking about this wrong?  Is there a better way?
### EDIT (causing title change):

I looked at the code a little more and the october default user model (October\Rain\Auth\Models) uses the "users" table.... **so why oh why did backend module use a different table?**

**Comment by WaskiWabit** [comment]
I personally like how they have separated the two. For one, you don't have to worry about ACL/RBAC as much.

**Comment by smkamranqadri** [comment]
My concern is if frontend user have to do some backend stuff then it have to have two user and two password while awkward, is there any way frontend user can be link or something like that?

**Comment by LukeTowers** [comment]
Sure, you could do one of the following:

1. Build frontend components to manage the data that they need to interact with.
2. Just use backend users in the frontend, this would be similar to how WP does it
3. Hook into the frontend user management events and create an identical backend account for the front end user with the necessary permissions.

Which option you choose is determined by how much functionality the user needs to interact with on the front end vs the backend
