### ISSUE TITLE
Assets -> Add sub-menu disappearing 

### ISSUE THREAD

**Issue by WebShapedBiz** [octobercms/october#2190]
##### Expected behavior
One should be able to perform several tasks on "Assets" -> "+ Add" sub-menu

##### Actual behavior
Sub-menu either disappears after a second or two or it disappears when one hovers the pointer to select an action.
EDIT: It works if the menu is pinned.

##### Reproduce steps
Go to "CMS" -> "Assets" -> "+ Add" menu and try to do something with it.

##### October build
347

**Comment by daftspunk** [comment]
Hey, what browser and OS are you running?

**Comment by WebShapedBiz** [comment]
Elementary OS Linux and it's happening on the latest Chrome, Firefox and Min. With the same OS and the same browsers I have no issue with that on several sites I've built with RC version.

Cheers.

**Comment by WebShapedBiz** [comment]
Here is the screen recording of two OctoberCMS, one of which is stable release. Same PC, same OS, same browser at the same time. I hope this will help.
[screencast1468144616.webm.zip](https://github.com/octobercms/october/files/355981/screencast1468144616.webm.zip)

**Comment by daftspunk** [comment]
Confirmed.

1. Navigate to CMS area
1. Collapse sidebar
1. Assets > Create new item
1. Sidebar hides

**Comment by WebShapedBiz** [comment]
Thank you  @daftspunk for your time and effort, it works now nicely.
