### ISSUE TITLE
error on composer update

### ISSUE THREAD

**Issue by nacr-dev** [octobercms/october#2191]
hello,

### Build 347

When I do sudo composer update I get this error,

Your requirements could not be resolved to an installable set of packages.

 

  Problem 1

    - october/cms dev-develop requires october/rain ~1.0 -> satisfiable by october/rain[1.0.x-dev].

    - october/cms dev-develop requires october/rain ~1.0 -> satisfiable by october/rain[1.0.x-dev].

    - Conclusion: don't install october/rain 1.0.x-dev

    - Installation request for october/cms dev-develop -> satisfiable by october/cms[dev-develop]. 

What am I doing wrong?

**Comment by marcoelho97** [comment]
+1
I have the same error:
![image](https://cloud.githubusercontent.com/assets/13586621/16684951/c5af4f28-44ff-11e6-9ec9-adebe51ee7ca.png)

**Comment by daftspunk** [comment]
Open composer.json replace all `october/*` packages from `dev-develop` to `~1.0`

**Comment by nacr-dev** [comment]
ok will give it a go!

**Comment by marcoelho97** [comment]
@daftspunk I have installed the project yesterday, and, those 4 lines still come with "Dev-develop", will I have to change the four of them to "~1.0" every time I install a new october??

Also, thanks for the reply!! c:

**Comment by daftspunk** [comment]
@marcoelho97 The issue was fixed 2 days ago, try install today and see if it still happens, hopefully not.

**Comment by nacr-dev** [comment]
Tks for all the help @daftspunk

**Comment by marcoelho97** [comment]
@daftspunk  Thank you very much! it does, indeed, work :D
