### ISSUE TITLE
Variable injecting (of the customize theme settings) for less / scss

### ISSUE THREAD

**Issue by JumpLink** [octobercms/october#2197]
Hi, is there any interest to make theme setting variables available in less/scss?

This would make it possible for the theme developer to let the user change style colors, sizes and much more (or any bootstrap variable) in the customize theme settings. There are already [different color schemes in october themes](https://github.com/JumpLinkNetwork/viola-theme/tree/master/assets/css), but the developer currently need to create several css files by hand for each color. This would be no longer necessary with theme setting variable injecting for less/scss.

I am also a [shopify](https://www.shopify.com/) theme developer and it's great to have this feature there, but the implementation is another, on shopify you have a style.scss.**liquid** file and you can use your template variables ([liquid](https://shopify.github.io/liquid/) is very similar to twig) in SCSS like this:
```scss
$brand-primary: {{settings.brand-primary}};
```
but with variable injecting (as described above) it would be even more beautiful, isn't?

Thanks!

See also:
- [How to set variables in scss](https://github.com/kriswallsmith/assetic/blob/master/src/Assetic/Filter/ScssphpFilter.php#L64)
- [How to set variables in less](http://leafo.net/lessphp/docs/#setting_variables_from_php)
- https://github.com/octobercms/october/pull/2180
- https://github.com/christianWilling/Scss/issues/8
- https://github.com/kriswallsmith/assetic/issues/808

**Comment by daftspunk** [comment]
[See the documentation](http://octobercms.com/docs/themes/development#combiner-vars) on this. Simply define an `assetVar` option in the form field, where the value is the desired variable name.
