### ISSUE TITLE
Twig code in settings sections of mails not working anymore since stable

### ISSUE THREAD

**Issue by tobias-kuendig** [octobercms/october#2202]
##### Expected behavior

When using Twig syntax in the settings section of an email it should be processed correctly. This was the case up until the stable release.

##### Actual behavior

When using Twig syntax in the settings section of an email an ErrorException is thrown:

> ErrorException: syntax error, unexpected '{' in Unknown on line 1
 in /workdir/vendor/october/rain/src/Mail/MailParser.php:52

##### Reproduce steps

Create an email with the following contents:

```
{% if isAdmin %}
    subject = "This is the subject for admins"
{% else %}
    subject = "This is the subject for everyone else"
{% endif %}
==
Text content
==
HTML content
```

##### October build

348

**Comment by daftspunk** [comment]
I'm not sure how this was possible before the stable release, it was never the intention. The "subject" value is parsed by twig, but not the entire settings area. This example is overcome with:

```
subject = "{{ customSubject }}"
==
Text content
==
HTML content
```

Then push the if statement back in to PHP land, where it belongs, to set the `customSubject` variable.
