### ISSUE TITLE
Custom scrollable backend list widget (responsive)

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#2203]
##### Expected behavior

List can be scrollable with mouse scroll and with mouse drag.

##### Actual behavior

List is scrollable only with mouse scroll. It does not scroll using mouse drag. 

CSS classes "scroll-after", "scroll-before" are not applied on page load. 

They are applied when page loads and I use mouse scroll on `thead`. Than I can even use mouse drag, which is very weird.

##### Reproduce steps

Create custom form widget with adjusted list widget markup. Add `october-list.js` to assets. Use it as a field in backend form. I can provide sample form widget on request.

##### October build

Stable - 347

**Comment by daftspunk** [comment]
The overflow behavior (scrolling / dragging) affects the list `head` only. Perhaps it is a feature seen as a bug? Dragging on the list body makes the list feel too unnatural.

We plan on improving this in the future by adding another scrollable `foot` area, or perhaps making the `head` "sticky" so it follows you down the page.

**Comment by mplodowski** [comment]
Meybe I described this wrong. The issue is not the feature to drag/scroll list head. This is very nice feature.

Here is the problem I have: 

I tried to create responsive list manually with field type `partial`. I have very long `head` so my list should need this drag/scroll functionality. 

It almost works, the issue is when I use mouse drag to scroll the list first. The list is not scrolling. 

But, if I use mouse scroll it magically work. And now I can even use mouse drag to scroll it.

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by geoffbeaumont** [comment]
This is a duplicate of long running bug #1542
