### ISSUE TITLE
Compiling overwritten less files using custom backend skin

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#2204]
##### Expected behavior

Command:

    php artisan october:util compile assets

should take into account overwritten less files by custom backend skin. 

After overwriting less files and compiling assets, the changed styles should be reflected in backend area.

##### Actual behavior

CMS does not check for overwritten less files and compile default assets.

##### Reproduce steps

Using custom backend skin: https://github.com/daftspunk/oc-rtl-plugin

Create `assets/less/core/variables.less` file, copy content from original file and change some colors.

Than compile assets:

    php artisan october:util compile assets

Check backend area for changes.

##### October build

Stable, 347

**Comment by daftspunk** [comment]
This expected behavior is not accurate. Core files should never be affected by a plugin. In this case you may need to register your own combiner bundle and have the output take place in the plugin.

```
        /*
         * Register asset bundles
         */
        CombineAssets::registerCallback(function($combiner) {
            $combiner->registerBundle('~/modules/cms/widgets/mediamanager/assets/js/mediamanager-browser.js');
            $combiner->registerBundle('~/modules/cms/widgets/mediamanager/assets/less/mediamanager.less');
        });
```
