### ISSUE TITLE
Response contents processed too early in Controller->execAjaxHandlers()

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#2208]
##### Expected behavior
I would expect the AJAX handler to have complete control over what is returned to the browser, but that is not the case. Because the results of AJAX handlers are merged into the $responseContents variable on line 425 of Backend\Classes\Controller and then further processing is done on the variable, the AJAX handler itself does not have any control over the additions to the response that are done after the initial merging.

##### Actual behavior
Specifically, the AJAX handler cannot control any partials that are added, the X_OCTOBER_REDIRECT property, any flash methods, or the X_OCTOBER_ASSETS property. The processing of these occur from line 435 right up until it returns the final response on line 460.

##### Rational for change
I would like my AJAX handler to be in complete control of all the response properties being returned to the AJAX framework. My specific handler pulls in new fields for a backend controller which means that I have to implement my own asset loader call to $(document).trigger('render'); instead of the built in asset manager. While I'm not using it right now, I would like the ability to precisely control the flash messages and partials. It would also be awesome if there was an event that one could hook into right before the final response is created that would allow further modification of the $responseContents array after all of the additive content has been attached.

##### October build
347

**Comment by daftspunk** [comment]
Fixed by #2209
