### ISSUE TITLE
[Suggestion] Datetime Mode - Time Seconds

### ISSUE THREAD

**Issue by Teranode** [octobercms/october#2211]
The Datetime mode for time should allow to specify seconds since when it formats it gets formatted like "00:00:00" but you only have the option to specify "00:00" (if not specifying seconds it should be defaulted to 00 )

Also
When i save the time field and go back to it ( eample i set the time to 00:24 - indicating 24 mins) it shows 20:xx instead of 00:xx

**Comment by daftspunk** [comment]
Sounds good, we would happily accept these improvements as a PR. Regarding the "also", I was unable to replicate this, when I set the time to `00:50` it stays as `00:50`.

**Comment by Teranode** [comment]
just a small update to the also -> it doesn't happen automatically, rather over time when i go back to update some records the time format changes, i just don't know when it does (it's random), i don't see it doing it now so maybe it's fixed.
