### ISSUE TITLE
SQL Server Issues

### ISSUE THREAD

**Issue by grafikkaos** [octobercms/october#2213]
##### Expected behavior
Administrator and Customize back-end pages on the CMS backend should be loading.

##### Actual behavior
SQL server errors are being displayed when loading up the Administrator and Customize back-end pages.

##### Reproduce steps
1. Install OctoberCMS on an SQL Server database
2. Login as an Admin
3. Attempt to access the Administrator and Customize back-end.  Both of these pages will return SQL server errors.  

Accessing the Administrator pages will return a GROUP_CONCAT error on SQL Server.  
``SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near 'separator'. (SQL: select top 20 [backend_users].*, (select group_concat(name separator ', ') from [backend_user_groups] inner join [backend_users_groups] on [backend_user_groups].[id] = [backend_users_groups].[user_group_id] where [backend_users_groups].[user_id] = [backend_users].[id]) as [groups] from [backend_users] order by [login] desc)``

Accessing the Customize back-end pages will return an IFNULL error on SQL Server.
``SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]'ifnull' is not a recognized built-in function name. (SQL: select * from [system_files] where (exists (select * from [deferred_bindings] where slave_id = system_files.id and [master_field] = logo and [master_type] = Backend\Models\BrandSetting and [session_key] = b1ehFavapHbNnM37pqTNNHQUK0RhY7mnJoNhPb0a and [is_bind] = 1)) and not exists (select * from [deferred_bindings] where slave_id = system_files.id and [master_field] = logo and [master_type] = Backend\Models\BrandSetting and [session_key] = b1ehFavapHbNnM37pqTNNHQUK0RhY7mnJoNhPb0a and [is_bind] = 0 and id > ifnull((select max(id) from deferred_bindings where slave_id = system_files.id and master_field = logo and master_type = Backend\Models\BrandSetting and session_key = b1ehFavapHbNnM37pqTNNHQUK0RhY7mnJoNhPb0a and is_bind = 1 ), 0)) order by [sort_order] asc)``

##### October build
346

Emmanuel

**Comment by daftspunk** [comment]
@tschallacka is our resident SQL Server expert.  I wonder if this is related to https://github.com/octobercms/library/pull/196? Will make an effort to get this merged soon.

**Comment by tschallacka** [comment]
Yes it is.
Group concatdoes not work on sql server. You can add a custom function that mimics, but it then needs to be accessed by dbo.function_name or something.

https://groupconcat.codeplex.com should be installed for users with sql server. Maybe add that as installation instruction if someone selects sql server as driver. Then if table driver is sql server use the dbo.group concat function. Maybe add a special concat function in the october model.

Also ifnull does not exist in sql server. Needs to be isnull, easiest way to bypass is a str replace on the query before sending it off to the database.

**Comment by daftspunk** [comment]
Thanks @tschallacka! It looks like the function `dbo.GROUP_CONCAT_D` is needed to allow a custom delimiter like the others.

This has been addressed in https://github.com/octobercms/library/commit/8d14ce73a8de28eba36200c04fbd9ae420c0efee. Please ensure the package at https://groupconcat.codeplex.com is installed.

**Comment by daftspunk** [comment]
Added to https://github.com/octobercms/docs/commit/ed6d32762e74ebe474a8a6f278671db1023371ca

> When using the SQL Server database engine, you will need to install the [group concatenation](https://groupconcat.codeplex.com/) user-defined aggregate.

**Comment by tschallacka** [comment]
Looks awesome! Nice work. Cleaner than my patchwork :-).
