### ISSUE TITLE
Datepicker depends on behavior does not match other field behaviors

### ISSUE THREAD

**Issue by firemankurt** [octobercms/october#2214]
##### Expected behavior

Datepicker ( time mode ) field to update value using filterFields() when it has property of dependsOn

```
public function filterFields($fields, $context = null) {
    // This does not update the field value
    $fields->start_at->value = new Carbon();
}
```
##### Actual behavior

Datepicker ( time mode ) field to update value using filterFields() when it has property of dependsOn

```
public function filterFields($fields, $context = null) {
    // This does update the field value but is inconsistent with the way a text field would work 
    $this->start_at = new Carbon();
}
```
##### Reproduce steps

Try both methods shown above.
##### October build

349

Datepicker seems to have a different behavior then other fields in the way that you can set it's value using filterFields() when it has property of dependsOn.

**Comment by firemankurt** [comment]
Datepicker fields also fail to trigger dependsOn events for other fields.
So I can not define a field that dependsOn the value of start_at where start_at uses a datepicker widget.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
