### ISSUE TITLE
How to use develop branch with composer [edge updates]

### ISSUE THREAD

**Issue by kuloed** [octobercms/october#2220]
hello,
in october-cms, october-backend, october-system (all in dev-develop), you are using composer-rain: ~1.0 instead of dev-develop version. Is this intended?
also in develop branch, composer.json is using ~1.0 version not the dev-develop version.

thank you so much for your works.

**Comment by daftspunk** [comment]
This is intended, it said `dev-develop` for the 4 months in between RC and Stable versions while we were conducting testing. The current version value `~1.0` should be used in all normal circumstances.

**Comment by kuloed** [comment]
thank you for your answers.

then how can i use develop branch of october using composer?  the version ~1.0 is reference of master branch right?

**Comment by daftspunk** [comment]
That is a good question. I don't have an answer for you either I'm afraid. If anyone has any ideas on how to solve this, please share!

**Comment by acasar** [comment]
@kuloed @daftspunk This worked for me:

```
"require": {
        "php": ">=5.5.9",
        "october/rain": "dev-develop as 1.0",
        "october/system": "dev-develop as 1.0",
        "october/backend": "dev-develop as 1.0",
        "october/cms": "dev-develop as 1.0",
        "laravel/framework": "5.1.*",
        "wikimedia/composer-merge-plugin": "dev-master",
    }
```

**Comment by kuloed** [comment]
thank you @acasar your solution is a bit tricky but it's work.

**Comment by daftspunk** [comment]
Thanks @acasar!
