### ISSUE TITLE
[Question] why .env is not use in octobercms?

### ISSUE THREAD

**Issue by Modelizer** [octobercms/october#2221]
It's hard to manage config variables while deploying.

Service like Heroku works on environment variables to manage keys. And also it is easier to manage.

Thanks.

**Comment by hybridvision** [comment]
Did you do a search and check the docs? ;-)

http://octobercms.com/docs/setup/configuration#environment-config-extended

It's supported, just not by default.

**Comment by Modelizer** [comment]
Oh thank... my bad :)

Next time I'll keep in my to check doc first ;-)
