### ISSUE TITLE
order of initialization

### ISSUE THREAD

**Issue by enniel** [octobercms/october#2222]
How to change the boot order of plugins in the ioc?

**Comment by daftspunk** [comment]
Plugins are loaded in the order which they are read from the file system. It is intentional in some ways, the load order should not be important to how a plugin operates. Consider using the `App::before` method to defer any logic, like so:

```
function boot()
{
    App::before(function() { /* this will execute after all plugins have loaded */ });
}
```

We could consider improving this, if you wouldn't mind sharing you requirements for needing it? Thanks!

**Comment by enniel** [comment]
Thanks. You can add order parametr in the Plugin.php as in the function registerNavigation.

**Comment by mitjarobic** [comment]
'We could consider improving this, if you wouldn't mind sharing your requirements for needing it? Thanks!'

For example if you want to extend the plugin, that already extends the plugin. The boot methods of dependency plugins should be executed first.

**Comment by daftspunk** [comment]
This is a high level description. We need a low level usage case, a simple example that demonstrates why it is needed. This will be used to see if there is not already a solution that exists.

**Comment by zakir1929** [comment]
+1

**Comment by LukeTowers** [comment]
@zakir1929 plugin's already have the $depends property that is used to determine migration order, what exactly are you "+1"ing? And don't get me started on how useless "+1" comments are to GitHub discussions 😉

**Comment by zakir1929** [comment]
@LukeTowers  Sorry for confusion by "+1"ing. I thought it is a sign for pointing the same issue which someone already experienced. I know about $depends and $require property of Plugin and they use to determine migration order.

so for explaining let me make it more easy.

I have created a plugin **A** which extend another plugin **B** but **B** is also extending a **Plugin (in my case Rainlab.User)**.  so what i want is to control the loading/executing order and want to execute Plugin **B**  before Plugin **A** but right now plugin **A** is executing before plugin **B**.

Thanks !!!

**Comment by zakir1929** [comment]
![screenshot](https://user-images.githubusercontent.com/16069667/44301871-3f4a4f80-a33c-11e8-86ad-bbd0d017e130.png)

**Comment by LukeTowers** [comment]
@zakir1929 then remove all the fields that use that tab, add your fields, and then re-add the original fields; or modify the form config in place dynamically to reorder it as necessary.

**Comment by zakir1929** [comment]
its worked Thanks !!! @LukeTowers  you helped me in 2 issues so thankyou very much.

**Comment by LukeTowers** [comment]
@zakir1929 no problem!
===
Was this helpful? Did it save you time? Then consider becoming a [Patreon supporter](https://www.patreon.com/LukeTowers) so I can keep providing excellent support! Or, add your thoughts to https://github.com/octobercms/october/issues/3683

**Comment by zakir1929** [comment]
Thankyou for the offer @LukeTowers right now I am very new to Octobercms so maybe I will think about it in future.
