### ISSUE TITLE
october cms bug

### ISSUE THREAD

**Issue by enniel** [octobercms/october#2223]
**Bug:**
`Call to a member function getPreviewImageUrl() on null in /home/evgeny/www/october/modules/cms/reportwidgets/activetheme/partials/_widget.htm:6`

**october cms version**: dev-develop 40324c0

this bug may occur if remove the plugin october demo

**Comment by daftspunk** [comment]
It's possible you see this error because the assigned theme no longer exists. We should add exception handling for these cases. Thanks
