### ISSUE TITLE
Error when using dropdown properties on a report widget

### ISSUE THREAD

**Issue by ariponce** [octobercms/october#2229]
##### Expected behavior
The dropdown options are displayed.

##### Actual behavior
An exception is thrown with the following message:
_Missing argument 1 for Backend\Classes\ReportWidgetBase::__construct(), called in /home/ariel/Sites/master/modules/backend/traits/InspectableContainer.php on line 36_

##### Reproduce steps

- Define a dropdown property on a report widget
- Define the property options dynamically with a method (i.e getPropertyOptions)
- Click on the cog icon of the report widget

##### October build
349

The error was likely introduced by this commit ba57dd89937c8f5167b1240afdf025f02630781e , since reverting the line to it's previous state produces the expected behaviour.

**Comment by daftspunk** [comment]
This commit should fix it c7724f7c904fa410ea19a92cf2cca35516d097fd

Please confirm

**Comment by ariponce** [comment]
Confirmed! 
Thanks
