### ISSUE TITLE
October.Drivers plugin update fails

### ISSUE THREAD

**Issue by japomani** [octobercms/october#2234]
##### Expected behavior

Complete install
##### Actual behavior

Throws error
"ZipArchive::extractTo(/var/www/html/live/plugins//october/drivers/vendor/aws/aws-sdk-php/LICENSE.md): failed to open stream: Permission denied" on line 75 of /var/www/html/live/vendor/october/rain/src/Filesystem/Zip.php

notice the double // in the path. The permissions are fine and other installs work, the path name is wrong
##### Reproduce steps

up date drivers
##### October build

350

**Comment by daftspunk** [comment]
The double slash should have no effect, it has located the file successfully but reports it is unable to modify it. Check the permissions are writable by the file server.

**Comment by LukeTowers** [comment]
Closed due to lack of follow up from @japomani
