### ISSUE TITLE
Where is plugin:update ?

### ISSUE THREAD

**Issue by bekerov** [octobercms/october#2238]
##### Expected behavior
I need plugin:update for start migration or update one plugin

##### Actual behavior
I can only plugin:refresh and october:update. First i dont want recreate db, if i stored info, and i dont want update octobercms core at deploy

##### October build
350

**Comment by daftspunk** [comment]
Use `october:up` or `october:update` to migrate or update the system. You cannot easily update individual plugins as it may cause breaking changes. There is a way around it by using `plugin:install` a second time, this will reinstall the files over the top.

**Comment by bekerov** [comment]
plugin store a lot of information. i lost this information on production, when trying update plugin schema. Is it ok ?

**Comment by bekerov** [comment]
Can i manually run migration  plugin ? if i have multiple plugins? How you devops process works?

**Comment by daftspunk** [comment]
Hey @bekerov take a look at #1404 for the reason. The entire platform must be migrated together to prevent breaking changes.

**Comment by phper01** [comment]
in backend/setting ->system  update
