### ISSUE TITLE
[Question] How to change the widget view ?

### ISSUE THREAD

**Issue by kuloed** [octobercms/october#2240]
Let's say i want to alter some view in plugin, like hide some button by permission, or changing the default view of form.
How can i do that in october? this is related to #1398 

Can we introduce some method to do that?
like this.

```
public function prependViewPath($path)
{
    if (!is_array($this->viewPath)) {
        $this->viewPath = [$this->viewPath];
    }

    array_unshift($this->viewPath, $path);
}
```

In the ViewMaker already have this
https://github.com/octobercms/october/blob/master/modules/system/traits/ViewMaker.php#L179-L184

so it will not breaking the october right, because if the extended view not found, it will fallback to default view?
can i make the pull request?

**Comment by daftspunk** [comment]
Please give exact details about what you are doing, or want to do. A solution may already exist, however this specification is too vague to work with.

**Comment by kuloed** [comment]
let's say we are using pages plugin, then i want to introduce another permission like create_pages, delete_pages. I want to remove the add button, or delete button from the pages plugin if the user doesn't have the permission. 
If we can extend or alter the view of pages plugin like the above method, we can easily remove the button from the view with `$this->widget->pageList->prependViewPath('my_custom_path');`
With this method we doesn't have to extend the widget or introduce new widget to only remove the button.
Of course this is not only for removing buttons, we can also insert another feature in the view if we can access the view and change it. And we can do this without change the plugin's code of other author or the default view of core modules, because we can easily change the viewPath and introduce our view.

thanks for your concern

**Comment by daftspunk** [comment]
Thanks @kuloed, so you want the ability to override views in general.

At the moment the solution is to use the `fireViewEvent` method in the controller to extend views, but this is only useful for appending additional markup, not so much for removing markup.

This will need further consideration since it is a major change. It could be seen as too magical to allow entire views to be overridden, it could be confusing to locate where the view is coming from.

**Comment by kuloed** [comment]
thanks @daftspunk, yes i want to override the view without change the core code.
I hope you consider this feature to the core of october.
