### ISSUE TITLE
How to extend form model query without modifying the controller?

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#2244]
I don't see a way to extend a form model query without modifying the controller.

Here is an example from docs how to extend form query: 

https://octobercms.com/docs/backend/forms#extend-model-query

But what if we cannot modify the controller to add `formExtendQuery` method?

I tried to `addDynamicMethod` to controller, but it is not fired.

Lists widget fires an event `backend.list.extendQueryBefore`, so I think we should have similar event for Forms widget, what do you think?

**Comment by daftspunk** [comment]
When would you need this? Please describe in more detail exactly why you need this. Not a hypothetical or anything, please give the real reason why you need it.

**Comment by mplodowski** [comment]
Backend User model can belong to many internal systems (A and B). I extended User model and added the relation and relation widget field. 

Now admin creates new admin account but give him access to only system A.

The new admin can see only users that belongs to system A. I listen for `backend.list.extendQueryBefore` to add this constraint.

Now I need to restrict access for admin A to update users from system B. Admin A can still access user B, by typing his ID in the browser URL. This can be fixed by adding `formExtendQuery` to controller, but I don't want to modify Backend Users Controller.

**Comment by daftspunk** [comment]
Thanks @mplodowski, I understand. Try this

```
\Backend\Controllers\Users::extend(function($controller) {
    $controller->bindEvent('page.beforeDisplay', function($action, $params) {
        $userId = array_get($params, 0);
        $user = \Backend\Models\User::find($userId);
        if ($action == 'update' && $user->cannotDoWhatever()) {
            return Response::make(View::make('backend::access_denied'), 403);
        } 
    });
});
```

**Comment by mplodowski** [comment]
Thanks, I did not think about this way. I agree that this worked.

But I think that it looks like an ugly hack. 

We have event for the `List` so I think that we should have similar event for the `Form`.

**Comment by daftspunk** [comment]
The difference is the `Lists` widget is responsible for managing the query, it's "smart". Whereas the `Form` widget is "dumb" it must be fed the data manually, this occurs in `FormController` and is why the event you want doesn't exist.

I assure you that code is by no means an ugly hack, you are blocking the controller action right at the source. The request doesn't even get a foot in the door. This is what you want, especially for security reasons. To clean it up, you should move the actual checking of the user to a different class.

```
\Backend\Controllers\Users::extend(function($controller) {
    $controller->bindEvent('page.beforeDisplay', function($action, $params) {
        if (in_array($action, ['update', 'create', ...])) {
            MyEventHelper::checkUserId(array_get($params, 0));
        }
    });
});
```

I do see a minor concern here, say for example a new action was added to the Users plugin, this code's integrity would be affected -- the action would need to be added to the `in_array` collection above.

We just need to find some other example where a controller behavior triggers an event (so we have a pattern to reference)... so far I cannot find an example where this occurs. Controllers are usually not extended in this way.

**Comment by mplodowski** [comment]
Ok, I agree. Thanks for this explanation :+1:
