### ISSUE TITLE
Add support for wherePivot 

### ISSUE THREAD

**Issue by dudheit** [octobercms/october#2247]
(I am not quite sure whether that isn't already implemented but following the [Laravel pivot filtering syntax](https://laravel.com/docs/5.2/eloquent-relationships#many-to-many) I get an ``Unknown column 'pivot' in 'where clause'`` error, so ...)

It would be helpful if October supports [Laravels wherePivot](https://laravel.com/docs/5.2/eloquent-relationships#many-to-many) queries.

**Comment by daftspunk** [comment]
It looks like this feature was added in 5.2. We can look at backporting it for now. Thanks

**Comment by scottbedard** [comment]
@daftspunk Has any progress been made on this? And it looks like the wherePivot methods existed all the way back since the Laravel 4 days.

Here they are in 5.1
https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L102-L129

**Comment by daftspunk** [comment]
Great! This feature should be is available now then.

**Comment by daftspunk** [comment]
Confirmed this feature is available and does work.
