### ISSUE TITLE
Model relations don't validate properly

### ISSUE THREAD

**Issue by msimkunas** [octobercms/october#2258]
May be related to: https://github.com/octobercms/october/issues/908

##### Expected behavior
A `Post` model that has many `Category`'ies may have a `$belongsToMany` relation (`$post->categories`). The model has the following validation rules for `categories`: `required|array`

When I output a checkbox list of categories in a backend form of the Edit Post page, I expect the user to receive a validation error if no categories are selected upon saving the model.

##### Actual behavior
If the user tries to save the post without selecting any categories, the validation error gets displayed to the user but the pivot table gets changed either way - the post loses all associated categories.

##### October build
350

**Note**: I'm using the checkbox list widget to display the related categories because I need to filter them.

**Comment by alxy** [comment]
Confirmed. I was able to reproduce this issue on my enviroment.

**Comment by daftspunk** [comment]
Confirmed also. This appears to occur because

```
// This will take immediate effect
$post->categories = null;

// Validation fails here (too late)
$post->save();
```

Obviously a logic error. Will fix. Thanks for reporting @msimkunas and confirming @alxy.
