### ISSUE TITLE
Plugins installable through composer

### ISSUE THREAD

**Issue by cdarken** [octobercms/october#2263]
Do you have a writeup of how this should work? Because after I install a plugin, I don't see it in the backend, in the updates section. I've installed `rainlab/translate-plugin` and after poking around I've found the "Manage languages" section and it didn't work, and I realized I had to execute `artisan october:up`.
Then it appeared, but I'm using another plugin, `vojtasvoboda/oc-twigextensions-plugin` that doesn't show up.

I think we need some clarification on the procedure, and sorry if it's already explained somewhere and I missed it.

**Comment by gabsource** [comment]
Plugins installed through the backend or `php artisan plugin:install` should show up _live_ as _installed_.

For everything else installed manually (by hand, git clone, whatever) you must run the `php artisan october:up` command to scan for new plugins.

For your example this is working : 

```
git clone  https://github.com/vojtasvoboda/oc-twigextensions-plugin.git plugins/vojtasvoboda/twigextensions
php artisan october:up
```

You must see the migrations of your new plugins in the console output.

**Comment by gabsource** [comment]
The path of the plugin in `plugins/` must match the plugin namespace of course.

**Comment by daftspunk** [comment]
As mentioned by @gabsource: The migration `october:up` should be executed after installing any plugin, this is standard procedure. See the docs for more details:

http://octobercms.com/docs/console/commands#console-up-command

**Comment by cdarken** [comment]
Yes, thanks. I solved my problem, I've helped Vojta fix the problem. His plugin was installing under the wrong name and was not detected.
