### ISSUE TITLE
How to contribute to the js code.

### ISSUE THREAD

**Issue by cdarken** [octobercms/october#2265]
Hi. I'm trying to write a patch to allow for romanian characters to be sluggable, I've added my map to the `modules/system/assets/ui/js/input.preset.js`, but how do I build it again to be able to test it?
And after I test it successfully should I also commit my storm.min.js ?

**Comment by gabsource** [comment]
When contributing to the `develop` branch only the source files are required in the pull request. They compile it when merging into the develop branch.

To test your changes while developing you can compile using the built-in commands : https://octobercms.com/docs/console/commands#october-util-command

This builds js and css for most of the core modules : 

    php artisan october:util compile assets

**Comment by cdarken** [comment]
Thanks, @gabsource.
