### ISSUE TITLE
Nested tree query not escaping string

### ISSUE THREAD

**Issue by kuloed** [octobercms/october#2268]
##### Expected behavior

Nested tree model should be able to use uuid as the primary key.
##### Actual behavior

Nested tree model failed to create, update, delete because the primary key is not escaping when using raw query.
##### Reproduce steps

Use uuid in model and implement NestedTree model

see: https://github.com/octobercms/library/blob/master/src/Database/Traits/NestedTree.php#L885-L887

**Comment by daftspunk** [comment]
Can you submit a pull request to fix this?

**Comment by kuloed** [comment]
Sorry for the late response.
I already submit a pull request for this issue.

thanks.

**Comment by daftspunk** [comment]
See https://github.com/octobercms/library/pull/233

**Comment by LukeTowers** [comment]
Fixed by  octobercms/library#233
