### ISSUE TITLE
Asset Deep Hashing causes exceptions when rendering website

### ISSUE THREAD

**Issue by adrenth** [octobercms/october#2270]
##### Expected behavior
Page is rendered as usual and all assets are combined.

##### Actual behavior
Throws an exception when opening a random page.

An exception has been thrown during the rendering of a template ("file_get_contents(/Users/[me]/Sites/[project]/themes/[theme]//~/modules/system/assets/js/framework.js): failed to open stream: No such file or directory").

##### Reproduce steps
Enable 'enableAssetDeepHashing' in config/cms.php

Put something like this in your layout:
````
<script src="{{ [
'assets/javascript/some-javascript.js',
'@framework',
'@framework.extras',
'~/plugins/custom/mycustomplugin/assets/javascript/custom.js'
]|theme }}"></script>
````
The last three items cannot be found when enableAssetDeepHashing = true.

##### October build
350

HTML code in layout template:

**Comment by Beaudinn** [comment]
+1

**Comment by daftspunk** [comment]
That was a slippery one, took a while to replicate it. Fixed in Build 354+
