### ISSUE TITLE
[Settings] Get back to Layout management when closing a mail layout

### ISSUE THREAD

**Issue by sebastienrouget** [octobercms/october#2272]
##### Expected behavior

When you save and close a mail layout, cancel some modifications on one of those, or click on Mail Layouts in the main breadcrumb, you must go back to the _LAYOUTS_ tab.
##### Actual behavior

Doing those things will make you return to the _TEMPLATES_ tab.
##### Reproduce steps
1. Open a mail layout.
2. Click on one of those:
   - _Cancel_
   - _Save and close_
   - _Mail Layouts_ (in the breadcrumb)
##### October build

351

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/261760e4c8ca456e948236f380faf977dc540829#diff-754d5ea77e6684f45ad1ec58fd4dd937
