### ISSUE TITLE
Error reporting in debug mode

### ISSUE THREAD

**Issue by acasar** [octobercms/october#2274]
This one is not urgent, but would really help a lot when developing plugins.

##### Expected behavior
When snippets throw exceptions (i.e. ModelNotFoundException) and debug mode is active (app.debug), a nice error message with stack trace should appear.

##### Actual behavior
![image](https://cloud.githubusercontent.com/assets/6329543/17324958/564f8554-58a9-11e6-84b3-54fe71cca182.png)

##### Reproduce steps
Create a component and register it as a snippet. Throw an Exception in ``onRun()`` method.

##### October build
353

**Comment by daftspunk** [comment]
Fixed by #229
