### ISSUE TITLE
Creating new model and relations using Mass Assign does not save relations (afterSave event not firing).

### ISSUE THREAD

**Issue by Whoisnt** [octobercms/october#2276]
I would post this in Octobercms/Library but I cannot create issues there, so this will have to suffice.
##### Expected behavior

So for instance if I was to set the Rainlab/User groups relation to fillable and was to insert a new Rainlab/User through mass assign (containing an array of group ID's) in the model create method, it would normally create the user and setup the group relations automatically.
##### Actual behavior

After investigation it seems as though the model bind event for afterSave is never called, causing the sync on https://github.com/octobercms/library/blob/master/src/Database/Relations/BelongsToMany.php#L207 to never execute, causing the group relations to not be set up.
##### Reproduce steps
- Install latest build of OctoberCMS (Build 350)
- Install Rainlab.User plugin
- Set the Rainlab User groups relation to be fillable

```
$user= new User;
$data = [
    ...,
    ...,
    'groups' => [
        1
    ]
];
$user->fill($data);
$user->save();

OR

$user->create($data);
```

What is strange is that the relations are setup temporarily, $user->groups does populate when I do $user->fill($data), but because the afterSave method isn't called, syncing the relation isn't called.
##### October build

350

**Comment by daftspunk** [comment]
We need unit tests for the `fill` approach, for now just set the relation directly, [this should work as it has been tested](https://github.com/octobercms/october/blob/master/tests/unit/plugins/database/BelongsToManyModelTest.php#L39):

```
$user->groups = [1];
```

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by achtan** [comment]
hi, any update on this topic?

**Comment by LukeTowers** [comment]
@achtan nope, but feel free to dig into it yourself and see what you can come up with!
