### ISSUE TITLE
The JavaScript API of Ajax framework cannot update partial on Frontend.

### ISSUE THREAD

**Issue by json-wong** [octobercms/october#2278]
##### Expected behavior
To use 
`$('form').request('onHandle', {
    update: {'partialname': '.result'}
})`
will be reflush the `.result` element in the page with `partialname` partial content.

##### Actual behavior
The ajax handle successful return an array of json, but update partial behavior not working.

##### Reproduce steps
**Important** The `Data attributes API` can be working.
such as:
`<form data-request="onHandle" data-request-update="'partialname': '.result'"></form>`
It works, only `Javascript API` has this problem.

##### October build
351-353

**Comment by daftspunk** [comment]
Interesting, the JS API may be expecting an object. Try this as a workaround:

```
$('form').request('onHandle', { update: {'partialname': $('.result') } })
```

Either way a selector should also be supported, as per the docs, so this sounds like a bug.

**Comment by json-wong** [comment]
For a long time, I'm using the following code for ajax request, and it works before I update the october to 351 build.
It also good working on the 350 build.
So, I guess this like a bug.

**Comment by daftspunk** [comment]
Very confusing because framework.js has not been updated since May, and Build 350 was created in July...

**Comment by Asinox** [comment]
+1

**Comment by Asinox** [comment]
Any update here?
Thank you

**Comment by Asinox** [comment]
More about this, this is weird, i have a partial with list elements to update, that is failling the update (i fixed using the returning data), but i have a dropdown that is working fine... and there is another dropdown that is failing the update, the main different about the two dropdown is the name, both are using the same function.

Working Dropdown:

`<select name="province_id" class="form-control required" id="province_id" onchange="getOptionsByField('province_id', 'sector_id')">`

Not working Dropdown:
`<select name="Vehicle[brand_id]" class="form-control" id="brand" onchange="getOptionsByField('brand', 'model')">`


Maybe this can help.

**Comment by daftspunk** [comment]
@Asinox yes boss 👀

**Comment by daftspunk** [comment]
Unable to replicate this. Instructions:

1. Activate the demo theme
1. Create a new page in the theme with contents below
1. Open the page /test in the browser
1. Click the "Click me" button
1. The results are loaded correctly

```
title = "The JavaScript API of Ajax framework cannot update partial on Frontend."
url = "/test"
layout = "default"
==
function onHandle() {}
==

<div class="container">
    <div class="result"></div>

    <hr />

    <form>
        <button type="button" onclick="testCase()">
            Click me!
        </button>
    </form>
</div>

<script>
    function testCase() {
        $('form').request('onHandle', { update: {'calcresult': '.result' } })
    }
</script>
```

**Comment by daftspunk** [comment]
Confirmed my suspicion that there is nothing wrong with framework.js, since it is a sacred library and is rarely touched. It would be unusual for a major problem to appear this late in the game (not noticed for 3 years?)

Be aware there are a couple of red flags with this usage:

- `$('form')` <== Submit the request on EVERY form? If there are multiple <form> tags this will produce undesired results. (I suspect this is the reason the OP example fails)
- `update: {'partialname': '.result'}` <== Update every element with `result` class attached.

Both can be dangerous and should use an identifier instead. Eg: `#form` and `#result`

Good luck

**Comment by zaktwist** [comment]
```
$.request('{{ __SELF__ }}::onAggiornaVar', {
	update: { '{{ __SELF__ }}::my_partial': '#mytag',
                '{{ __SELF__ }}::other_partial': '#other_tag' },
        success: function(data) {
          this.success(data);
    }
});
```
I solved this way. using this: `this.success(data);`
by [https://octobercms.com/forum/post/updating-with-ajax-framework#post-17108](url)

Good luck
