### ISSUE TITLE
How to create Route::get()  in modules/cms/routes.php ?

### ISSUE THREAD

**Issue by phper01** [octobercms/october#2279]
1.example:

    Route::get('test/{id}', function($id) {
        return 'Hello World';
    });

success

2. `Route::get('logout', 'Cms\Classes\CmsController@logout');`   is failed

**Comment by daftspunk** [comment]
I don't see why it wouldn't work, it is Laravel after all. October does not contribute to this functionality in any way (as far as I know).

**Comment by phper01** [comment]
@daftspunk  thank you ,it is solved.
ps:
1.../modules/cms/routes.php  add  Route::get('test','Cms\Controllers\test@test');
2.In ../modules/cms/controllers/test.php    

`<?php

namespace Cms\Controllers;

use Cms\Classes\Controller;

/**
 * Backend user groups controller
 *
 * @package october\backend
 * @author Alexey Bobkov, Samuel Georges
 *
 */
class test extends Controller
{

    public function __construct()
    {
        parent::__construct();
    }

    public function test()
    {
        return 'wef';
    }

    public static function getAfterFilters()
    {
        return [];
    }

    public static function getBeforeFilters()
    {
        return [];
    }

    public static function getMiddleware()
    {
        return [];
    }

    public function callAction($method, $parameters = false)
    {
        return call_user_func_array(array($this, $method), $parameters);
    }

}
`

only example ,this is work.

**Comment by daftspunk** [comment]
Glad to hear it!
