### ISSUE TITLE
Combiner aliases not work with deep hashing

### ISSUE THREAD

**Issue by jan-vince** [octobercms/october#2280]
##### Expected behavior
Combine all given assets without error.

##### Actual behavior
Combiner/Twig throws an Exception when aliases are used.

*Probably introduced with #2180.*

##### Reproduce steps
In `config/cms.php`:

`'enableAssetDeepHashing' => true`

In any layout/page code like:

```
{{ ['@jquery', 'assets/test.js']|theme }}
```

throws an Exception:

``` php
An exception has been thrown during the rendering of a template

("file_get_contents(/Users/jan.vince/web/october.dev.edge/themes/test//~/modules/backend/assets/js/vendor/jquery.min.js): failed to open stream: No such file or directory").

```

##### October build
353 (edge update)

**Comment by daftspunk** [comment]
Dupe #2270
