### ISSUE TITLE
Retain selected records across pagination changes

### ISSUE THREAD

**Issue by jbartoszek** [octobercms/october#2282]
Hi Everybody!
##### Expected behavior

ability to choose items from more than one page of relation manager (if I have 223 items displayed 10 per page I would like to be able choose more that 10 at once.
##### Actual behavior

when I choose item from the actual list (1-10 of 223)
https://www.dropbox.com/s/60ontd98f0ear8m/Zrzut%20ekranu%202016-08-03%2015.50.43.png?dl=0
and then go to next page (11-20 of 223) previously selected items get "unticked" 
##### Reproduce steps

open relation manager with > 10 items
tick at least one of checkboxes
go to next page
go back to previous (they will be unticked)
##### October build

last

**Comment by daftspunk** [comment]
That does sound nice, good suggestion!

**Comment by daftspunk** [comment]
Added this idea to the internal tracker for when the List widget is improved. Thanks!
