### ISSUE TITLE
System files attachment_id column has wrong type.

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#2290]
https://github.com/octobercms/october/blob/develop/modules/system/database/migrations/2013_10_01_000002_Db_System_Files.php#L20

This code creates `attachment_id` column as `string`. This causes an error when you try to use this column under Postgres in queries.

Error can be triggered for example when you try to use this query scope.

    public function scopeHasAttachments($query)
    {
        return $query->has('attachments');
    }

Where `attachments` is relation to `system_files` table.

We need to change this column type to `integer` to resolve this.

**Comment by daftspunk** [comment]
This needs peer review. This forces a relationship to use an integer as a key. Some tables may not use integers, keys can be strings, although it is uncommon. Should we exclude these use cases? Is there another way?

It looks like we are [casting this to an integer](https://github.com/octobercms/library/blob/master/src/Database/Relations/DeferOneOrMany.php#L57) anyway! So you are probably right...

**Comment by daftspunk** [comment]
After some brief discussion, the `attachment_id` or `slave_id` could reference a UUID/GUID and should remain as a string.  The issue needs to be addressed from the Postgres side.

**Comment by daftspunk** [comment]
In future @mplodowski, try to make it a bit easier for the maintainer and provide your bug reports in a simple format with simple replication and full error details. Something like this.

#### Conditions

Using Postgres (`pgsql`) as database type.

#### Reproduce

```
$user = Backend\Models\User::make()->has('avatar')->first();
```

#### Output

    ERROR:  operator does not exist: character varying = integer

    LINE 1: ...ystem_files" where "system_files"."attachment_id" = "backend...
                                                                 ^
    HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

#### SQL

    select * 
        from "backend_users" 
        where (
            select count(*)
                from "system_files"
                where "system_files"."attachment_id" = "backend_users"."id"
                    and "system_files"."attachment_type" = Backend\Models\User
                    and "field" = avatar
        ) >= 1
    limit 1

**Comment by daftspunk** [comment]
At first glance, it appears we have a catch-22 situation on our hands:

- Drop support for UUID/GUID primary keys
- Drop support for Postgres

**Comment by daftspunk** [comment]
**A third solution exists!** Modify the `AttachOneOrMany` base trait to cast the primary key to string. It has been tested with successful results, this is what we will do.

Further to the point above, @mplodowski, this is why it is important to describe and discuss the issue itself and not the solution you have in mind. After some discovery, the solution was completely different and the initial report was a path that we didn't need to travel.

**Comment by mplodowski** [comment]
That's great, thanks :+1:
