### ISSUE TITLE
Relation Controller view (list) mode and scope constraint

### ISSUE THREAD

**Issue by gabsource** [octobercms/october#2292]
##### Expected behavior
The output of `<?= $this->relationRender('relation_with_scope') ?>` should constraints the visible records to the scope definition. Sorting and searching (if enabled) should be done only on the subset of these elements.

##### Actual behavior
All the values from the table are displayed.

Forum related post [https://octobercms.com/forum/post/problem-with-scope](https://octobercms.com/forum/post/problem-with-scope)

##### Reproduce steps
1. Add a relation with a scope on a model
2. Add a RelationController behavior to the backend model controller and render the relation widget for the relation inside the form.

##### October build
355

=====

### Possible fix

Changing [line 637](https://github.com/octobercms/october/blob/develop/modules/backend/behaviors/RelationController.php#L637) of `RelationController` from : 

`$this->relationObject->addConstraints();`

to : 

`$this->relationObject->addDefinedConstraintsToQuery($query);`

seems to fix the problem. Search and sorting are OK. 

The same principle has been applied to the manage mode (list). Is there any reason to not apply the same logic for the view (list) mode ?

**Comment by daftspunk** [comment]
On first impression, it would make sense to apply the defined constraints. I can't think of any circumstance where you would not want this to occur. Even in these circumstances you could simply define another relation definition that omits the constraints.

**Comment by daftspunk** [comment]
Used a slightly more robust implementation than #2296

See 618a03561643b4c24f99bff9838d9ef197bb37dc

Thanks for this!

**Comment by gabsource** [comment]
Great! Thanks.
