### ISSUE TITLE
Relation behavior use tree trait.

### ISSUE THREAD

**Issue by Beaudinn** [octobercms/october#2297]
I wand to use the SimpleTree trait list view inside the relation list view, this is not possible at this time.

It seems sort and tree views are not supported inside the relation behavior.
Is it possible to implement it. or is it already on the list?

October build: 356

**Comment by Beaudinn** [comment]
If it is necessary I would like to place a bounty.

**Comment by daftspunk** [comment]
It's true this feature is not supported. It would be an interesting exercise to add support, although it is not a priority for us. Feel free to submit a bounty to have it escalated.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
