### ISSUE TITLE
Support automatching with model attributes as well as labels in imports

### ISSUE THREAD

**Issue by kratkar** [octobercms/october#2301]
##### Expected behavior

Auto match columns on the import page
##### Actual behavior

Don't auto match
##### Reproduce steps

Load the import file and click "Auto match columns" button.
##### October build

351

I think we need to change 
[name = $.trim($('> span', $this).text())](https://github.com/octobercms/october/blob/master/modules/backend/behaviors/importexportcontroller/assets/js/october.import.js#L118)
to
`name = $this.attr('data-column-name')`

**Comment by kratkar** [comment]
question.
You use the **label** attribute for first row in the CSV? Do not model attribute? I looked export.
If so, then it's my error) I always use the base attributes(model) for first row. Example "name,date,photo". Not "The name of the person,Date publication,Photo of a man"

**Comment by daftspunk** [comment]
Unable to replicate. 

1. Navigate to RainLab.Blog > Export Posts
1. Download the export file
1. Navigate to Import posts area
1. Upload the file
1. Click Auto match columns
1. Columns are matched

**Comment by daftspunk** [comment]
> You use the label attribute for first row in the CSV? Do not model attribute?

Yes, the field label is used, not the attribute name.... because it is nicer for humans. I wonder if we could modify it to support both?

**Comment by kratkar** [comment]
>  I wonder if we could modify it to support both?

it would be good
