### ISSUE TITLE
Media manager vulnerability

### ISSUE THREAD

**Issue by alarstyle** [octobercms/october#2304]
In the media manager there is a restriction to upload `php` files.
But user can rename any uploaded file to `*.php`.

Tested on 351 build.

_PS: And also will be good to have a possibility to enter restricted or allowed file types in the settings section of backend._

**Comment by daftspunk** [comment]
Thanks for the report @alarstyle, this has been fixed.

To override the blocked file types, define this entry in your config `cms.fileDefinitions.blockedExtensions`. Eg in config/cms.php:

```
'fileDefinitions' => [
    'blockedExtensions' => ['asp', 'avfp', 'aspx', 'cshtml', 'cfm', 'go', 'gsp', 'hs', 'jsp', 'ssjs', 'js', 'lasso', 'lp', 'op', 'lua', 'p', 'cgi', 'ipl', 'pl', 'php', 'php3', 'php4', 'phtml', 'py', 'rhtml', 'rb', 'rbw', 'smx', 'tcl', 'dna', 'tpl', 'r', 'w', 'wig']
];
```

> **Note**: Extensions listed above are the defaults.

**Comment by daftspunk** [comment]
We classify this as a minor vulnerability since it requires:
- Administrator access to the backend area
- Poorly configured web server (only index.php should be executable)

Great catch though!
