### ISSUE TITLE
Update core confusing

### ISSUE THREAD

**Issue by bekerov** [octobercms/october#2305]
Hello, im using git for store project files.
Where im update core on localhost, then commit this changes, i go to server and update site on server.

##### Expected behavior
After update site and composer not change core files

##### Actual behavior
after `composer update` i have many files change back and i can see changes in `git status`

##### Reproduce steps
Just install on second encironment site and try update locally

##### October build
351

**Comment by daftspunk** [comment]
The decision to update with composer or the gateway server is mutually exclusive. You can change this decision at any time, but it not advisable to use both at the same time. Check the [composer installation documentation](http://octobercms.com/docs/console/commands#console-install-composer) for more details.

In this case you should set the disableCoreUpdates option to true in your cms.php config file. This will prevent the server from competing with composer.

```
'disableCoreUpdates' => true,
```

**Comment by bekerov** [comment]
Thank but its not helped.
After composer install same error
![image](https://cloud.githubusercontent.com/assets/2405629/17642326/6c3f4068-6149-11e6-89f6-c149181bdf03.png)

**Comment by bekerov** [comment]
I still cant figure out why composer update files after `compser install`

**Comment by mplodowski** [comment]
I am using composer to create all my projects and don't have any issues.

After you create project with composer you need to check following:

1. `disableCodeUpdates` is set to `true`.
2. You don't ignore `composer.lock` file in `.gitignore`.
3. Run `composer update` to update core files.

I use Laravel Forge with DigitalOcean so from now on I just push all my changes and Forge will automatically pull all changes from repo and run `composer update` on server to update October and `vendor` dir.

I think that `composer.lock` file is essential here.

**Comment by bekerov** [comment]
1. already set to true
2. i dont ignore
3. i dont want update, 

I still dont understand why all plugins are update and as core file are in my changes tab

**Comment by bekerov** [comment]
and when im update locally, then git commit changes, then push to server.
On the server afrer composer install i also have changes. and this changes is undo from previous changes.

**Comment by mplodowski** [comment]
Sorry, I run `composer update` only in `dev` environment. In production I use `composer install` like so:

    composer install --no-interaction --no-dev --prefer-dist 

Maybe try to reset your production local repo to the remote version to be in sync before push changes from dev.

    git fetch origin
    git reset --hard origin/master

**Comment by bekerov** [comment]
```
FatalErrorException in ProviderRepository.php line 150:
Class 'Illuminate\Broadcasting\BroadcastServiceProvider' not found
```
after composer update

**Comment by mplodowski** [comment]
Check you have that file in `vendor`. Run

    composer dump-autoload

**Comment by bekerov** [comment]
folder exist. but folder Broadcasting in laravel is not exist

**Comment by mplodowski** [comment]
What you composer require section looks like?

Check that you have the same file as in October repo.

You can also update from dev branch like so:

    "require": {
        "php": ">=5.5.9",
        "october/rain": "dev-develop as 1.0",
        "october/system": "dev-develop as 1.0",
        "october/backend": "dev-develop as 1.0",
        "october/cms": "dev-develop as 1.0",
        "laravel/framework": "5.1.*",
        "wikimedia/composer-merge-plugin": "dev-master"
    },

**Comment by bekerov** [comment]
```
"require": {
        "php": ">=5.4",
        "october/rain": "~1.0",
        "october/system": "~1.0",
        "october/backend": "~1.0",
        "october/cms": "~1.0",
        "laravel/framework": "5.0.*",
        "illuminate/html": "5.0.*"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "phpunit/phpunit-selenium": ">=1.2"
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php",
            "tests/UiTestCase.php",
            "tests/PluginTestCase.php"
        ]
    },
    "scripts": {
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
```

**Comment by mplodowski** [comment]
From version 1.0 Stable October require laravel 5.1.

https://github.com/octobercms/october/blob/master/composer.json

**Comment by bekerov** [comment]
when i do `composer install`
whats mean this 
```

  - Installing october/rain (dev-master 3e580d0)
    Downloading: 100%

  - Installing october/system (dev-master 9c21609)
    Downloading: 100%

  - Installing october/backend (dev-master 2e85ee6)
    Downloading: 100%
```

is it code from current develop branch?

**Comment by mplodowski** [comment]
No this is from master branch. If you want `dev` branch you must use this:

```
"require": {
    "php": ">=5.5.9",
    "october/rain": "dev-develop as 1.0",
    "october/system": "dev-develop as 1.0",
    "october/backend": "dev-develop as 1.0",
    "october/cms": "dev-develop as 1.0",
    "laravel/framework": "5.1.*",
    "wikimedia/composer-merge-plugin": "dev-master"
},
```

**Comment by bekerov** [comment]
yes, now work. thank for your time @mplodowski
