### ISSUE TITLE
Allow AttachOne to attach more than just Files

### ISSUE THREAD

**Issue by piersroberts** [octobercms/october#2306]
I found out almost by accident that it's possible to use AttachOne to add data to other models as if they were MorphOne types, but with named field types.

The AttachOne trait needs a slight modification, to do this https://github.com/octobercms/library/compare/develop...piersroberts:develop

Attach in host model like so,
```
    public $attachOne = [
        'sometext' => 'BuzzwordCompliant\Fragments\Models\Fragment',
        'moretext' => 'BuzzwordCompliant\Fragments\Models\Fragment',
    ];
```

and your foreign model looks like this,

```
<?php namespace BuzzwordCompliant\Fragments\Models;
use Model;

class Fragment extends Model
{
    public $table = 'bc_fragments';
    public $timestamps = false;
    public $morphTo = [
        'attachment' => []
    ];

    public $fillable = ['field','data'];

}
```
and the database looks a bit like this
```
+-----------------+------------------+------+-----+---------+----------------+
| Field           | Type             | Null | Key | Default | Extra          |
+-----------------+------------------+------+-----+---------+----------------+
| id              | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| data            | text             | YES  |     | NULL    |                |
| attachment_id   | int(11)          | YES  |     | NULL    |                |
| attachment_type | varchar(255)     | YES  |     |         |                |
| field           | varchar(255)     | YES  |     |         |                |
| sort_order      | int(11)          | YES  |     | NULL    |                |
+-----------------+------------------+------+-----+---------+----------------+
```
I've used this to be able to dynamically assign fragments of HTML that live in the database to various data models rather than having them in flat files.

**Comment by daftspunk** [comment]
I'm not sure I'm following you, why not just use `morphOne`? The `attachOne` relation is specifically for file attachments... To help with the comprehension, would you mind preparing a prototype plugin that demonstrates why this is important? More interested in the problem you are trying to solve, rather than the solution you have in mind.

**Comment by daftspunk** [comment]
NB: The `attachment_id` field should be a VARCHAR field, this relation is special and will cast values to TEXT when matching these columns (Postgres driver).

```
attachment_id   | varchar(255)          | YES  |     | NULL    |                
```

**Comment by piersroberts** [comment]
Sure, sorry was in a rush when writing. Basically I'm trying to write a plugin that will store blocks of HTML content in the database. Any number of these blocks should be able to be 'attached' to any model, and easily hooked up to the backend UI without having to interfere with the db schema.

I would use morphOne if it could pick up the relationName and set the field value in the database so that I could use more than one of them in a backend form, like you can with attachOne.

I couldn't see an easy way of adding the field value to morphOne without it causing breaking changes. Thanks for having a look, any advice is appreciated.

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by piersroberts** [comment]
no problem, thanks again

**Comment by tschallacka** [comment]
uhm, I don't see what the problem is? I use it all the time for "flexible" form fields like seo data and such 

```
class SomeModel extends Model {
     /**
     * @var array Fillable fields(make these fields in the database in the table that will attachable)
     */
    protected $fillable = [
        'attachment_id',
        'attachment_type',
        'is_public',
        'sort_order',
        'is_public',
        'field'
    ];
   public function getPath() {
        return $this->attachment_type;
    }
    protected $hidden = ['attachment_type', 'attachment_id', 'is_public'];
    public $morphTo = ['attachment'];
}
```

Then you can add it simply 

```
public $attachOne = ['some_model'=>'Foo\Bar\Models\SomeModel'];
```

and it'll work just fine.

Then I also suggest making a form widget:

class SomeModelEditor extends FormWidgetBase
{
protected $defaultAlias = 'some_model_editor';
protected $someModel;
public function render()
    {
        $this->prepareVars();
        return $this->makePartial('somemodeleditor');
    }
    private function getSomeModel()
    {
        $query = $this
        ->getRelationObject()
        ->withDeferred($this->sessionKey)
        ->orderBy('sort_order');
        return $query->take(1)->get()->first();
    }
    public function getSomeModel() {
        if(!$this->someModel) {
            $some= $this->getSomeModel();
            if(!$some){
                $some= new SomeModel();
                $some->save();
                $this->getRelationObject()->add($some,$this->sessionKey);
            }
            $this->someModel= $some;
        }
        return $this->someModel;
    }
    /**
     * Returns the value as a relation object from the model,
     * supports nesting via HTML array.
     * @return Relation
     */
    protected function getRelationObject()
    {
        list($model, $attribute) = $this->resolveModelAttribute($this->valueFrom);

        if (!$model->hasRelation($attribute)) {
            throw new ApplicationException(Lang::get('backend::lang.model.missing_relation', [
                'class' => get_class($model),
                'relation' => $attribute
            ]));
        }

        return $model->{$attribute}();
    }
    protected function getAttachedModel() {
        list($model, $attribute) = $this->resolveModelAttribute($this->valueFrom);
        return $model;
    }

    /**
     * Returns the value as a relation type from the model,
     * supports nesting via HTML array.
     * @return Relation
     */
    protected function getRelationType()
    {
        list($model, $attribute) = $this->resolveModelAttribute($this->valueFrom);
        return $model->getRelationType($attribute);
    }

    /**
     * Removes a file attachment.
     */
    public function onRemoveAttachment()
    {
        //if (($seoid = post('layout_id')) && ($file = SeoCard::find($seoid))) {
          //  $this->getRelationObject()->remove($seoid, $this->sessionKey);
        //}
    }
    /**
     * {@inheritDoc}
     */
    public function getSaveValue($value)
    {
        return FormField::NO_SAVE_DATA;
    }

**Comment by daftspunk** [comment]
@tschallacka makes a good point. It should be possible today without modifications. Try these suggestions.
