### ISSUE TITLE
An exception has been thrown during the rendering of a template ("unserialize(): Error at offset 0 of 152 bytes").

### ISSUE THREAD

**Issue by bekerov** [octobercms/october#2307]
After composer install get this issue.

##### Expected behavior
Process update done well

##### Actual behavior
I get error
##### Reproduce steps
update website and commit this changes. Go to another computer and `git pull` updates. Then run composer install

##### October build
Last current version

![chrome_2016-08-13_11-49-28](https://cloud.githubusercontent.com/assets/2405629/17642378/1bff15e4-614c-11e6-9e79-78d07a2d1f63.png)

**Comment by bekerov** [comment]
when i remove brackets and make string like below works.
```
<link href="{{'assets/css/theme.css'|theme }}" rel="stylesheet">
```
But its not good

**Comment by bekerov** [comment]
at this link this should work https://octobercms.com/docs/markup/filter-theme

**Comment by daftspunk** [comment]
Unable to replicate this. Try running `php artisan cache:clear`

**Comment by bekerov** [comment]
thanks, but this not help.

**Comment by bekerov** [comment]
after some time and updates core cant reproduce

**Comment by longcnn** [comment]
Me too and my problem in firefox

after php artisan cache:clear

try to change another brower for example:chrome ie ...

and the problem is gone...
