### ISSUE TITLE
Missing option in Relationships

### ISSUE THREAD

**Issue by trsh** [octobercms/october#2310]
##### Expected behavior
Besides 'delete' argument in a relationship, there should be also something like 'set_null' argument.

##### Actual behavior
There is only one option that effects model deletion  - 'delete' relation or not.

##### Reproduce steps
For double security add relation constrains to DB. In case of model deletion, I don't want the foreign model to be deleted, but the foreign key should be set to null.  

User case. Album, has lot of templates. When I delete template I don't want the album to be deleted, but I want template_id to be set to null on that album. This actually common practice.

##### October build
Where to check for this?

**Comment by daftspunk** [comment]
This happens if you use the `Relation::remove()` method. Make sure `delete` is not included in the relationship definition. 

```
Album::templates()->remove($template);
```

**Comment by trsh** [comment]
I was hoping this would be Feature Enhancement. 

Like mysql has "CASCADE" (equals to October => delete) and "SET NULL" (would be the new feature).
