### ISSUE TITLE
Improper permissioning for /storage/app/uploads/public subdirectories

### ISSUE THREAD

**Issue by MBRO95** [octobercms/october#2316]
##### Expected behavior
Upload & Access/View uploaded image.
In this particular instance going to settings > customize backend > custom logo upload should upload the logo, produce a preview, and allow the logo to go live on the backend login page.

##### Actual behavior
Upload success
Access fail
View fail

In this particular instance going to settings > customize backend > custom logo upload... uploaded the logo, could not produce a preview, and resulted in no logo on the backend login page. After further research I discovered the subdirectory tree branched from /storage/app/uploads/public has permissions set to 744 and needs to be set to 755. This could also be an issue pulling the image from storage with the user permissions. Either way...we have a permissions bug here.

##### Reproduce steps
Settings > Customize back-end > Logo > Upload Image
No preview will be rendered and logo will not be visible on back-end login screen
Through FTP change subdirectory tree under /storage/app/uploads/public/ permissions to 755 from 744.
Preview rendered now

##### October build
361

**Comment by daftspunk** [comment]
Update this in your `cms.php` config:

    /*
    |--------------------------------------------------------------------------
    | Default permission mask
    |--------------------------------------------------------------------------
    |
    | Specifies a default file and folder permission for newly created objects.
    |
    */

    'defaultMask' => ['file' => '777', 'folder' => '777'],

**Comment by MBRO95** [comment]
Avoiding that fix due to inherent security vulnerabilities with that option.

Best,

Matthew May




On Mon, Aug 15, 2016 at 5:53 PM -0400, "Samuel Georges" <notifications@github.com> wrote:





Update this in your `cms.php` config:

    /*
    |--------------------------------------------------------------------------
    | Default permission mask
    |--------------------------------------------------------------------------
    |
    | Specifies a default file and folder permission for newly created objects.
    |
    */

    'defaultMask' => ['file' => '777', 'folder' => '777'],

**Comment by daftspunk** [comment]
Sorry, use 755 instead of 777.
