### ISSUE TITLE
Unknown bug 'Sortable'

### ISSUE THREAD

**Issue by PopcornPHP** [octobercms/october#2318]
I am creating a website for a company, and I do not have full access to the hosting and the terminal for migration. Therefore, all changes to the database have to do manually. After one of such changes noticed a problem in which the records are not sorted. I recorded a short video about it.

This problem you can see on this video:
https://www.youtube.com/watch?v=cyyopNN3ghY

##### Expected behavior
This records (products) must be sorted

##### Actual behavior
They are not sorted

##### October build
361

**Comment by daftspunk** [comment]
This probably relates to #1923. It's because the `sort_order` column are all set to `0`, so the orders are "corrupt" in this way. Try this:

```
update tablename set sort_order = id;
```

**Comment by dunets** [comment]
@daftspunk can you explain that into the documentation?
`update tablename set sort_order = id;`

**Comment by LukeTowers** [comment]
@dunets I'd hold off on documenting it just yet. Ideally we'll be adding `repairOrdering` methods to both the `Sortable` trait and the `NestedTree` trait that would fix it for you, and then we can document those instead.
