### ISSUE TITLE
2 level validation

### ISSUE THREAD

**Issue by trsh** [octobercms/october#2319]
##### Expected behavior
We could add 2 level $rules - one in forms and second in model.  One is specific for the form, second is global for model (no matter from what form).

##### Actual behavior
I can add rules only in model. Custom validation code is required otherwise.

##### Reproduce steps
Sometimes you want to add validation only on Form level, not entire model. Like 2 different forms could save data to same table/model, and each has few different requirements on mandatory fields.

##### October build
Where to check?

**Comment by daftspunk** [comment]
Thanks for the suggestion.
