### ISSUE TITLE
Fields with attributes like "hidden/disabled" using Builder are not working when you try to save the data

### ISSUE THREAD

**Issue by Asinox** [octobercms/october#2325]
If you are using Builder and you make some fields "hidden or disabled" (to use with a trigger), when you try to save the form, the data of those fields are lost in space.

October build 361

Thank you!

**Comment by daftspunk** [comment]
This is by design, they don't appear in the form because they are hidden or disabled. Perhaps we could introduce a `type: hidden` that will simply use a hidden `<input />`. Just not sure what the use case for this is.

It is possible today using `type: partial` that contains exactly that:


    <input
        type="hidden"
        name="<?= $field->getName() ?>"
        id="<?= $field->getId() ?>"
        value="<?= e($field->value) ?>" />

**Comment by Asinox** [comment]
Thank you!!, good to know
