### ISSUE TITLE
Blacklisting ModSecurity rules

### ISSUE THREAD

**Issue by msimkunas** [octobercms/october#2326]
I believe it would be useful to comprise a blacklist of [ModSecurity rules](http://www.modsecurity.org/rules.html) which trigger false positives because setting up OctoberCMS on an Apache web server with modsecurity enabled can be quite a headache.

I ended up manually blacklisting 12+ rules by trial and error which is tiresome and begs for being properly documented.

There seems to be a [couple](https://octobercms.com/forum/post/insert-html-tags-in-backend-editor-make-saving-fails) of [questions](https://octobercms.com/forum/post/mod-sec-rules-to-whitelist) regarding this already and [disabling modsecurity](https://octobercms.com/forum/post/anytime-i-get-a-flash-message-popup-in-the-backend-it-only-shows-html#post-11175) is not a true solution.

Are there any resources on this? I'm currently on build 361, if it matters.

**Comment by daftspunk** [comment]
This is a known issue as described in KE-1 article: http://octobercms.com/support/article/ke-1

If you can provide further detail and instructions that would be beneficial, we can add them to this article.

Thanks!
