### ISSUE TITLE
Backend list filters fail to trigger the 'oc.beforeRequest' event

### ISSUE THREAD

**Issue by jajacobs** [octobercms/october#2333]
Backend list filters should trigger the 'oc.beforeRequest' when changed.

But this isn't the case because the filter control looks for a parent form element, which does not exist, to send an ajax request and ends up with an empty jQuery object. Then the framework tries to trigger the event on this object and nothing happens.

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.
