### ISSUE TITLE
Backend - checking permissions when logging in

### ISSUE THREAD

**Issue by niko278** [octobercms/october#2340]
When the user logs in, only main menu items permissions are checked to make a redirection.
Isn't it better solution to check firstly side menu items?

In file modules/backend/controllers/Index.php
In function checkPermissionRedirect

`$first = array_first(BackendMenu::listSideMenuItems(), $true) ?: array_first(BackendMenu::listMainMenuItems(), $true)`

**Comment by daftspunk** [comment]
Probably not. If you don't have access to the main, then it is assumed you don't have access to the sub.
