### ISSUE TITLE
ErrorException in PluginManager.php line 446: array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by bkrajendra** [octobercms/october#2341]
##### Expected behavior
october frontend backend not opening. generally it should open as expected.

##### Actual behavior
Suddenly i started getting this error:
![iocare-error](https://cloud.githubusercontent.com/assets/994083/18116087/738752c6-6f62-11e6-8fd0-79f2414d812e.PNG)

PHP artisan also not working.

ive not done any update recently.

##### October build
(October build number)
CMS
350
PHP
5.6.25
GD
2.1

**Comment by daftspunk** [comment]
Looks like your disabled.json file might be corrupt. Will implement a fix for these scenarios.
