### ISSUE TITLE
How to add version to asset files to prevent caching?

### ISSUE THREAD

**Issue by jpruiz114** [octobercms/october#2343]
##### Expected behavior
Be able to add version to every asset (css, js, etc) to prevet caching.

##### Actual behavior
We don't have a versioning feature.

**Comment by daftspunk** [comment]
Is this the feature you are looking for? In config/cms.php

    /*
    |--------------------------------------------------------------------------
    | Determines if the asset caching is enabled.
    |--------------------------------------------------------------------------
    |
    | If the caching is enabled, combined assets are cached. If a asset file
    | is changed on the disk, the old file contents could be still saved in the cache.
    | To update the cache the back-end Clear Cache feature should be used. It is recommended
    | to disable the caching during the development, and enable it in the production mode.
    |
    */

    'enableAssetCache' => false,

**Comment by leoquijano** [comment]
Hi, I think he's actually talking about Cache busting, as explained here?

https://github.com/kriswallsmith/assetic#cache-busting

**Comment by daftspunk** [comment]
Cache busting is implemented already, on the top level of includes. If you want to use it for secondary includes, enable the `cms.enableAssetDeepHashing` option. It supports SCSS and LESS.

    /*
    |--------------------------------------------------------------------------
    | Check import timestamps when combining assets
    |--------------------------------------------------------------------------
    |
    | If deep hashing is enabled, the combiner cache will be reset when a change
    | is detected on imported files, in addition to those referenced directly.
    | This will cause slower page performance. If set to null, assets are
    | minified, when debug mode (app.debug) is disabled.
    |
    */

    'enableAssetDeepHashing' => false,

**Comment by LukeTowers** [comment]
@daftspunk `enableAssetDeepHashing` doesn't seem to bust the cache past the third level, is this a bug or intentional?

**Comment by daftspunk** [comment]
@LukeTowers: The logic isn't recursive afaik, so third level won't get picked up. There might be a way to fix it. I've just been using 2 levels to overcome this and am preferring the simplicity of it.

**Comment by LukeTowers** [comment]
I'll add it to my list of things to look into improving when I have more time then :)
