### ISSUE TITLE
Base64 encoding form data to prevent strict ModSecurity problems.

### ISSUE THREAD

**Issue by joejordanbrown** [octobercms/october#2344]
Is there any reason you are not base64 encoding form data that contains things that ModSecurity may block and cause 403 errors.

The problem is spoke about here #2133

**Comment by daftspunk** [comment]
Simplicity is the main reason. However, the thought has crossed our minds. The ModSecurity issues can and should be addressed by hosting providers for now.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
