### ISSUE TITLE
SCSS compiler not working

### ISSUE THREAD

**Issue by mbaxter91288** [octobercms/october#2345]
##### Expected behavior

After adding a .scss file to the combiner I would expect the scss to be rendered to a .css file.
##### Actual behavior

All I get is `/* preg_match() expects parameter 2 to be string, array given */`
##### Reproduce steps
- create a `themes/mytheme/assets/scss/theme.scss` file. For testing it's only contents is:

```
body {
    background-color: green;
}
```
- added `<link href="{{ ['assets/scss/theme.scss']|theme }}" rel="stylesheet">` to my layout
- created `index.htm` file to use above layout
##### October build

363

Hoping I've missed something stupidly obvious!

Cheers,
Mat

**Comment by daftspunk** [comment]
Crikey! Unable to replicate it

```
<link href="{{ ['assets/test.scss']|theme }}" rel="stylesheet">
```

- themes\demo\assets\test.scss

```
body {
    background-color: green;
}
```

Tested with config and commands

- 'enableAssetDeepHashing' => false,
- 'enableAssetDeepHashing' => true,
- `php artisan cache:clear`

All +OK
Background appears green

**Comment by mbaxter91288** [comment]
Thanks for getting back to me. Shortly after logging this issue I moved onto something else. Just got back to the computer now, fired up Homestead and the bloody thing is work just fine! No idea quite literally nothing has changed :-/

I'll keep an eye on it and let you know, but otherwise not an issue for now. Sorry to have wasted time.

Thanks for the response.

**Comment by mbaxter91288** [comment]
I've noticed since using the SCSS compiler a little more it doesn't seem to be able to parse everything. For example, I am using Foundation 6 Sites and when I include the grid it never outputs any of the grid classes to the final CSS. It also doesn't error on compilation.

I've also just noticed this with Foundation 6's Motion UI.

Is there a version of SASS that the PHP SCSS compiler cannot deal with or something?

@daftspunk any help would be greatly appreciated.

**Comment by LukeTowers** [comment]
I'm not a 100% sure, but I believe there are places in the codebase where the asset filters are set that weren't updated to include scss as a filter. I can't recall where, I'll have to take a look again.

**Comment by daftspunk** [comment]
This feature was a user contribution, we are still using LESS on our side. If anyone finds a solution, feel free to submit a PR. If you can provide a full bug report we can take another look (simple replication steps, expectation vs actual behavior).

**Comment by LukeTowers** [comment]
For anyone looking to work on this, the problem resides with the library used to compile SCSS. See https://github.com/leafo/scssphp/issues/446 for more information on the bug with that library.
