### ISSUE TITLE
Typo in PluginBase

### ISSUE THREAD

**Issue by scottbedard** [octobercms/october#2346]
There appears to be a typo in the PluginBase. Not sure how important this is, or what this setting does, but I figured I'd mention it here and this can be closed if we don't care about it.

https://github.com/octobercms/october/blob/master/modules/system/classes/PluginBase.php#L20

`loadedYamlConfigration` should probably be `loadedYamlConfiguration`

If this is the case, I'll go ahead and submit the PR. I don't know where else this is used though, or if this option is documented anywhere and used by other plugins.

**Comment by daftspunk** [comment]
This should be a PR. Thanks @scottbedard!

**Comment by daftspunk** [comment]
Fixed by #2348
