### ISSUE TITLE
MariaDB problem

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#2347]
I made an October on the MySQL server. When I moved it an another server, I got the following 
error message:

exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1' in /var/www/clients/client2/web12/web/vendor/laravel/framework/src/Illuminate/Database/Connection.php:319

How to solved this problem?

**Comment by daftspunk** [comment]
This error does not give much information. Try a fresh October installation to see if it helps.
