### ISSUE TITLE
Plugin backend lists generated by builder plugin don't show records until filtered

### ISSUE THREAD

**Issue by Cellular-** [octobercms/october#2350]
##### Expected behavior
Go to plugin backend record list. Be able to see all records in table for the corresponding plugin.

##### Actual behavior
Go to plugin backend records list and no records are displayed. I have to check the columns I want to see almost every time I try to look at the list.

##### Reproduce steps
Create records list with builder plugin. Visit the records list page for that plugin's table. 

##### October build
363

**Comment by daftspunk** [comment]
Make sure the columns are not set with `invisible: true`. This will cause the list to appear empty as described here.

**Comment by Cellular-** [comment]
@daftspunk I feel like an idiot. Thanks. Removed invisible: true from the yaml list and it's working. You can close.
