### ISSUE TITLE
strategy to fork abandoned plugins

### ISSUE THREAD

**Issue by skydiver** [octobercms/october#2352]
What can we do when a plugin is abandoned by his author?

Let's put this as example: https://github.com/LaminSanneh/Octobercms-Fantastic-Faq-Plugin/pull/7

It's fixed since April (5 months ago) but the author doesn't make the pull request ...

I think it's important to have an strategy because there is a lot of plugins who doesn't work on the stable release and the solution it's quite simple.

We should fork and publish on the market with a new name?

**Comment by daftspunk** [comment]
Open source dictates that you can fork. Nothing stops you from this. If a plugin is broken, let us know and we'll pull it down. Even if it isn't broken, you are still welcome to publish the fork alongside the original.

**Comment by skydiver** [comment]
People will search for "Plugin A" and because it's more popular, will ignore "Plugin B" which is a fixed and more recent version.

**Comment by daftspunk** [comment]
> If a plugin is broken, let us know and we'll pull it down.

We are also working on the ability for authors to feature plugins to get some traction early on.

**Comment by der-On** [comment]
@daftspunk NPM solved it, by allowing package contributors. This way a plugin can be updated and managed by multiple accounts. Maintainers can therefore ask for help or can be contacted when someone want's to co-maintain a plugin.
