### ISSUE TITLE
SQL server doesn't support combined indexes over 900 bytes

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#2356]
##### Expected behavior

Indexes on deferred_bindings table in sql server 2012r2 and higher
##### Actual behavior

Just a primary key
##### Reproduce steps

Install october on database with sqlserver 2012r2 or higher
##### October build

any

The fix might be in https://github.com/octobercms/october/blob/43eb8c49467c44ba4822eb1b287e11dd63d21bff/modules/system/database/migrations/2013_10_01_000001_Db_Deferred_Bindings.php#L13

By adding index key names to the index statements.

Cobmined they are too big.

Each of the string columns can be combined with is_bind, id, but not with the other string indexes.
Prefably the length of the session id get's limited from 255 to a string length appropriate(40 or so?) so it's under the 900 bytes mark.

string() right now creates nvarchar(255), which is 255*2 + 2 bytes in lenght, 512. By setting string lengths that are appropriate for session keys and the slave_id field, combined indexes can be created that can be picked by the query optimiser.

I modified it to these values

![image](https://cloud.githubusercontent.com/assets/8638425/18343502/ecb744ba-75b3-11e6-8bea-adb05cbcd215.png)

slave_id, master_field and Session_key 49 lenght(most dbms limit key length anyways to below this anyways.)
master_type and slave_type 124(seriously, if your namespace + classname are longer you need to reconsider organising things)

**Comment by LukeTowers** [comment]
@tschallacka is this still an issue on the latest dev build?
