### ISSUE TITLE
500 error on saving backend preferences

### ISSUE THREAD

**Issue by egerheed** [octobercms/october#2358]
When saving backend preferences, specifically setting language to my local Norwegian or setting the time zone to something other than UTC, I would expect the backend to use the Norwegian translation and set the saved time zone.

But when saving backend preferences, I get a 500 internal server error instead, and the only way to get rid of it is to go into the db and delete the backend preferences for the given admin user, and then deleting the persist code to force a new login for the user in the browser. The language is back to English though.

To reproduce, try to set the backend language to Norwegian.

Currently on build 318.

**Comment by egerheed** [comment]
Setting only the time zone does not produce the error, so this seems to be language related only.

**Comment by egerheed** [comment]
I've tracked this issue down to the package **jenssegers/date** that has the language file for Norwegian named as no.php, when in fact October wants nb-no. Simply renaming the file in the jenssegers/date folder solved the problem.

Not sure if this is the problem of October not naming Norwegian Bokmål incorrectly, or Jenssegers/Date not having a proper file name.

**Comment by daftspunk** [comment]
Let's rename to `no`, the safest bet I think

Paging @kalfheim

**Comment by daftspunk** [comment]
The cause of the error 500 has been fixed.

**Comment by egerheed** [comment]
Awesome! :) Thanx!

**Comment by daftspunk** [comment]
[Switch on edge updates](http://octobercms.com/docs/setup/configuration#edge-updates) and update to Build 374+ to get these changes.
