### ISSUE TITLE
Permissions UI Improvements

### ISSUE THREAD

**Issue by alarstyle** [octobercms/october#2359]
It might be nice to have more friendly and more customizable permissions for users and groups.

Recently I came across Sulu CMS and saw this:
![image](https://cloud.githubusercontent.com/assets/1730120/18413330/57a5f96a-77ad-11e6-9052-33c92145d093.png)

So it is possible for example letting users edit, but not delete or create new items.
Maybe you would like to do something similar :)

**Comment by daftspunk** [comment]
It's an interesting idea, at the moment back-end permissions are defined by the plugins that implement them. There is a GUI for defining permissions in the Builder plugin. We would need to find out the complete end-to-end process for needing "dynamic" permissions like this.

**Comment by LukeTowers** [comment]
Furthering on this conversation, @daftspunk and I were discussing adding the ability to "group" permissions together, perhaps along the lines of:

```
'author.plugin.pizzas' => [
    'label' => 'Pizzas',
    'permissions' => [
        'make' => 'Make Pizza',
        'eat'     => 'Eat Pizza',
        'see'    => 'See Pizza',
    ]
]
```
Which would dynamically create the `author.plugin.pizzas.make`, `author.plugin.pizzas.eat`, and `author.plugin.pizzas.see` permissions.

Further on our discussions we were thinking about what hierarchy would look like, implied inheritance, the UI, all things we need to consider further before doing anything else to the existing implementation.
