### ISSUE TITLE
Seed admin user with random password on initial system seed

### ISSUE THREAD

**Issue by mbaxter91288** [octobercms/october#2360]
Hi,

Just wondering if there is a way to not seed the database on initial `php artisan october:up`?

I have found the below in `/modules/system/classes/UpdateManager.php` line 150:

```
public function update()
{

...

if ($firstUp) {
    $modules = Config::get('cms.loadModules', []);
    foreach ($modules as $module) {
        $this->seedModule($module);
    }
}

...
```

I would like this not to run. I can only think to create my own `october:up` command, and my own `UpdateManager` class, extend the original and only modify the `update()` method. Seems like there might be a better way? If not will do that for now.

Thanks,
Mat

**Comment by LukeTowers** [comment]
@daftspunk Would this be something that we could fire an event for to determine whether or not to seed a specific module?

**Comment by mbaxter91288** [comment]
Or perhaps a flag for the command? `php artisan october:up --seed=false`?

**Comment by daftspunk** [comment]
We discussed this recently. It should be solved in two parts, a "no seed" flag in the updater class. Then a new parameter available to commands that use it.

This command syntax might be nicer?

```
october:up --no-seed
october:install --no-seed
```

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by LukeTowers** [comment]
This will be solved by seeding the admin user with a 22 char random password instead of the default hard coded one.
