### ISSUE TITLE
365 build "is_superuser" field issue

### ISSUE THREAD

**Issue by WebShapedBiz** [octobercms/october#2362]
Hi guys.

On the site I've been running after the first stable build, the latest update (11. Sept.) broke my Backend, as you can see it here [http://tinypic.com/r/241k0nq/9]

Since I run several sites on pre-release versions I remembered that at one point there was a similar bug after an update. Then it was the case of `permissions` field in `backend_users` table that was deleted and placing `{"superuser":1}` value in that field resolved the issue then.

With this latest update I've noticed a `is_superuser` filed in the same table. Now I don't know with which build it came but it was set to "0" in the update process thus rendering my Backend useless.
After changing the value to "1" the problem was gone since I was a superuser again.

##### October build
365

**Comment by daftspunk** [comment]
This issue should be fixed by logging out and logging back in again, I think. Can you confirm this?

Ref: https://github.com/octobercms/library/commit/762bb0a048d103db4d659d3749a02ea4877ba48f#diff-7ff76b0696642a77ef1d04092b888a90L130

**Comment by WebShapedBiz** [comment]
I've done that several times before remembering that I've already had a
similar issue and manually change the aforementioned field value with
phpMyAdmin.

Anyhow, thank you for your time and effort.

Cheers.

Sinisa Perovic
WebShaped.biz

Web: http://www.webshaped.biz
E-Mail: sinisaperovic@webshaped.biz
<sinisaperovic@webshaped.biz>SkypeID: sinisaperovic

2016-09-14 11:43 GMT+02:00 Samuel Georges <notifications@github.com>:

**Comment by daftspunk** [comment]
Sounds like an anomaly. There was a migration script that should have screened users with superadmin privilege and enabled the is_superuser flag. Glad you got it sorted!
