### ISSUE TITLE
Unable to display polymorphic relation value as a column field

### ISSUE THREAD

**Issue by pmhou** [octobercms/october#2366]
##### Expected behavior

When I add a list column of type "relation" that refers to a polymorphic many many relationship, I should see a delimiter combined string of values specified by the "select" property.
##### Actual behavior

SQLSTATE[HY000]: General error: 2031 is thrown. The bindings appear to have been lost, thus causing the error.

When dumping $bindings from Connection::runQueryCallback(), an empty array is displayed.
##### Reproduce steps

Create two models that have a polymorphic many many relationship.

Add the relation in columns.yaml for the MorphToMany model

``` yaml
categories:
    label: Categories
    relation: categories
    select: name
```
##### October build

1470
##### Stacktrace

[stacktrace.txt](https://github.com/octobercms/october/files/472130/stacktrace.txt)

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by LukeTowers** [comment]
Closed as there has been no response from @pmhou

**Comment by tdolph** [comment]
I have the exact same problem. Everything worked fine but the server was upgraded to php 7 and then displaying morphToMany column fails with the same error code. Not sure how to proceed.

**Comment by LukeTowers** [comment]
@tdolph create your own issue with as detailed information as you can provide. Also please follow @daftspunk's suggestion and create a PR to the test plugin replicating the issue.
