### ISSUE TITLE
Add .ico to the list of asset extensions

### ISSUE THREAD

**Issue by woganmay** [octobercms/october#2368]
##### Expected behavior

I expect to be able to upload .ico files to the Assets section on the CMS, since it's a common fallback format for shortcut icons.
##### Actual behavior

The editor blocks me and tells me the ico file type is not permitted.
##### Reproduce steps

Try uploading any ico file.
##### October build

unsure? installed via web installer today.

**Comment by leocavalcante** [comment]
For now, you can allow ico extension at CMS config.
At `config/cms.php`, add:
```php
'fileDefinitions' => [
    'assetExtensions' => array_merge(FileDefinitions::get('assetExtensions'), ['ico']),
],
```
October will look for this config before using the default one:
https://github.com/octobercms/library/blob/master/src/Filesystem/Definitions.php#L37
