### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by MaSiBaSu** [octobercms/october#2370]
##### Expected behavior
i get an error on installation

##### Actual behavior
can't install cms - no installation instructions

##### Reproduce steps
i have unpack the installer files to the web directory and i want to navigate to install.php. then i get the error massege: Uncaught Error: Class 'Installer' not found in /html/october/install_files/php/boot.php:74 Stack trace: #0 /html/october/install.php(1): include() #1 {main} thrown

##### October build
latest build

**Comment by daftspunk** [comment]
What version of PHP are you using?

**Comment by MaSiBaSu** [comment]
i use PHP 7.0-latest CGI. But i also get an error with PHP 5.6-latest CGI!

now i have install it with Command-line installation... and it works fine

**Comment by daftspunk** [comment]
Glad you got it sorted. The original message doesn't make a lot of sense unless the files are corrupt

```
require_once 'Installer.php';
try {
    $installer = new Installer();
```

For this to throw an error, the Installer.php file must be empty or not contain the `Installer` class as expected. Will close it for now, leave another comment if you experience this again.
