### ISSUE TITLE
Manage favicon.ico in Settings

### ISSUE THREAD

**Issue by sebastienrouget** [octobercms/october#2371]
##### Expected behavior
You can check, import or delete favicon.ico within the CMS.

##### Actual behavior
You have to use a FTP client to manage the favicon.ico file of your site.
It's a detail, but something useful to go faster while building a website.

##### October build
365

**Comment by leocavalcante** [comment]
Possible duplicate? #2368

**Comment by sebastienrouget** [comment]
Not totally in my opinion because it is a special file. Many browsers try to load it with or without your agreement. I know you can choose any path and link to it in a page header, but can you put it at the root directory with the Media Manager? If you can, this may be a duplicate.
___
Also, why not use it to override the backend favicon?

**Comment by daftspunk** [comment]
Yes, it is a duplicate because the fix is identical.
