### ISSUE TITLE
Site search efficiency.

### ISSUE THREAD

**Issue by poniatowski** [octobercms/october#2375]
Hello there,
##### Expected behavior

Make flexible site search based on database tables.
##### Actual behavior

I have been trying to find the best solution for site search. As we can know October CMS saving all pages content into files instead of database. One of my idea was to saving pages content into database and from there run the  search, so I can easier make site search, but that will cause a lot of redeveloping. My question is, can we change the logic of this and start storing all pages in database tables?

Another an important thing is repository. I have noticed that many developers have same issues with sending pages (*.htm files) to repo.
##### Reproduce steps

I have used offline site search plugin to make the some search on website.
##### October build

Latest version (from September 2016).

**Comment by daftspunk** [comment]
Sounds like a great idea for a plugin! This issue describes a "search index", something October could definitely use. At the moment we use third party service for this, called Algolia, something based on their API would be fantastic.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
