### ISSUE TITLE
Ajax framework skips {files : true} parameter

### ISSUE THREAD

**Issue by GitJaap** [octobercms/october#2376]
I have enjoyed using the ajax framework alot and it works like a charm, but when I have to send a file with my forms, like a small album image I run into problems. 
##### Expected behavior

When you make an ajax form in twig like this basic example
`
    {{form_ajax('onFileUploadAndOtherPostData', { 'files' : true})}}
    {{form_file('album_image')}}
    {{form_text('test')}}
   {{form_close}}
`
And then check for an uploaded file in php like
`
   if(Input::hasFile('album_image'){
   Log::info('cheer');
    }
    else{
        Log::info('sad');
    }
`
You would expect 'cheer' to appear in the info log.

This can be solved by manually using jquery to upload the files or using the responsiv uploader, but I think it should also be supported in the ajax framework for the sake of completeness.
##### Actual behavior

You see only 'sad' appear. The file does not get uploaded. But if you change the form to open instead of ajax
`
   {{form_open({ 'files' : true, 'request' : 'onFileUploadAndOtherPostData'})}
`
The file does get uploaded.
##### Reproduce steps

see Expected behaviour
##### October build

365

**Comment by daftspunk** [comment]
That's probably because file uploads are not supported via AJAX requests, not without complex XHR solutions, this is a common limitation. Take a look at the uploader plugin for a solution:

https://github.com/responsiv/uploader-plugin

**Comment by daftspunk** [comment]
In the working example provided via `form_open`, the upload works because it no longer uses AJAX.
