### ISSUE TITLE
services file bug

### ISSUE THREAD

**Issue by enniel** [octobercms/october#2378]
If there is no file "services", I get this error message:

```
[ErrorException]                                                                                                                      
  file_put_contents(/home/evgeny/enniel/october-crm/storage/framework/services.json): failed to open stream: No such file or directory
```

I think it should be created automatically if it is not.

**Comment by daftspunk** [comment]
This is a Laravel generated file. Can you provide step-by-step instructions on how you arrived here?

As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by LukeTowers** [comment]
Closed as there has been no response from @enniel
