### ISSUE TITLE
issue with Ajax Framework it's duplicated everytime

### ISSUE THREAD

**Issue by MK4Tech** [octobercms/october#2379]
Hello,

I need help, Everything using Ajax Framework is duplicated for Example
if i send message from contact us page it duplicated.

**Comment by mplodowski** [comment]
You are probably attaching `{% framework extras %}` multiple times. Check your layout and page for this.

Note that if you have `{% framework %}` and `{% framework extras %}` than you should remove the first one.

**Comment by daftspunk** [comment]
This seems to be a common pitfall. Should be fairly easy to add a check for this.

**Comment by MK4Tech** [comment]
thanks, guys the issue is fixed.

**Comment by daftspunk** [comment]
Further enhancement incoming:

- Detect when `framework.js` is included twice on the page and halt with either a console warning or an error. Copy logic for logic when jQuery is not included.

**Comment by LukeTowers** [comment]
@daftspunk Since you're working on that stuff right now anyways, I might as well bump this for your review
