### ISSUE TITLE
Cancel 'leave page' confirmation alert,  blocks validation errors

### ISSUE THREAD

**Issue by Yokann** [octobercms/october#2380]
##### Expected behavior

When you trying to leave the page while you edit something (blog, pages, ...) in the backend, and if you decide to cancel. You can try to save your work and **see validation errors**
##### Actual behavior

If you cancel and you try to save your work, if validation errors exist in the response (406 code), nothing happens. 
It works fine if the response is succesful.
##### Reproduce steps

For exemple open a blog post (from Rainlab.Blog),  try to leave the page, click on 'Stay' and try to save with a mistake in your form . This process happened everywhere.
##### Help for the solution

Actually in `framework.js` line 423, `window.ocUnloading` is set to true. But you need to set to false if you cancel the unloading. 
If you don't, `line 119`  (see below) the condition is true, the errors will not display. 

```
        if ((window.ocUnloading !== undefined && window.ocUnloading) || errorThrown == 'abort')
                   return
```
##### October build

365

**Comment by daftspunk** [comment]
Good find. I was able to replicate this.

**Comment by LukeTowers** [comment]
@Yokann is this still an issue?

**Comment by Yokann** [comment]
@LukeTowers I don't know.

**Comment by Samuell1** [comment]
@LukeTowers outdated
