### ISSUE TITLE
How to override component properties?

### ISSUE THREAD

**Issue by poniatowski** [octobercms/october#2381]
##### Expected behavior
I would like in easy and proper way extend component properties `defineProperties()`.

##### Actual behavior
I could find easy way to extend component properties. At this moment is difficult to add or remove properties.

**Comment by LukeTowers** [comment]
Github issues are for reporting actual issues with the code or detailed feature requests. Questions like this are better suited for the forums, IRC channel (#october), or the Slack team.

**Comment by jBOKA** [comment]
Haven't tested, but I guess you can simply extend the component class and override `defineProperties`. But you'd have to use this new component instead in the markup.

```PHP
class ExtendedComponent extends ComponentToExtend
{
    public function defineProperties()
    {
        return parent::defineProperties() + [
            'newProperty' => [
                'title' => 'New property',
                'default' => 'whatever',
                'type' => 'string'
            ]
        ];
    }
}
```

**Comment by poniatowski** [comment]
@jBOKA I have done exactly what you have said, but that not so easy. You have to use new component and all new things like component htm, models etc. Which is crazy for me. You can easy extend model, class, menu, controller, but with component propertis there is not easy way.

**Comment by daftspunk** [comment]
@dshoreman has a solution that perhaps he'd like to share, looks something like this

```
public $definedProperties = [
            'newProperty' => [
                'title' => 'New property',
                'default' => 'whatever',
                'type' => 'string'
            ]
];

public static function addDefinedProperty($prop, $val)
{
    self::extend(function($component) use ($prop, $val) {
        $this->definedProperties[$prop] = $val;
    });
}

public function defineProperties()
{
    return $this->definedProperties;
}
```

Although I recall there were some issues with the inspector.

**Comment by dshoreman** [comment]
Your component should have this added to it for the properties to be extendable:

```php
protected $componentProperties = [
    // default properties go here
];

public function defineProperties()
{
    return $this->componentProperties;
}

public function addProperties(array $properties)
{
    $this->componentProperties = array_replace($this->componentProperties, $properties);

    // This triggers October to set the defaults for injected properties
    return $this->properties = $this->validateProperties([]);
}
```

Then you can use October's usual extension methods to add your properties:

```php
// Plugin.php
public function boot()
{
    MyComponent::extend(function($component) {
        $component->addProperties([
            'my_slug' => [
                'title'       => 'Special Slug',
                'description' => 'The slug for the thing.',
                'type'        => 'string',
                'default'     => '{{ :slug }}',
            ],
        ]);
    });
}
```

There's some other magic involved in setting variables to access the properties, but this should get you started.

@daftspunk, what say ye to a PR that adds this (and the other bits needed) as a trait or something? Could be useful in a few cases, and with traits being optional they'd probably be ideal...
