### ISSUE TITLE
repeater question

### ISSUE THREAD

**Issue by enniel** [octobercms/october#2382]
How to set up repeater default value?

**Comment by LukeTowers** [comment]
Questions like this are better suited for the IRC channel (#october) or the Slack team. http://octobercms.com/chat

**Comment by daftspunk** [comment]
As above. The default value could potentially come from the model.

**Comment by enniel** [comment]
But if there is no model.

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.
