### ISSUE TITLE
Include default toolbar items in editor settings

### ISSUE THREAD

**Issue by daftspunk** [octobercms/october#2384]
##### Expected behavior

The ability to customize rich editor, perhaps markdown and code editor too.
##### Actual behavior

Buttons are fixed and can only be changed be fields.yaml, the site wide default are hard coded.
##### Reproduce steps

N/A
##### October build

365
##### References
- https://github.com/rainlab/pages-plugin/issues/188

**Comment by CptMeatball** [comment]
Are there any updates regarding this?

**Comment by daftspunk** [comment]
Clearly not. The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- Make a [financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by Harti** [comment]
@daftspunk 
> Submit a pull request that introduces this feature and wait for it to be reviewed

You're funny. I'd love to. The thing is, richeditor.js doesn't get included when compiling assets with the artisan command `php artisan october:util compile js` (or `assets` for that matter), hence no debugging is possible without tearing the whole application apart.

**Comment by LukeTowers** [comment]
Added in https://github.com/octobercms/october/commit/dfcf324d008b6c20122a20a2b26b43a22111583f by @Harti
