### ISSUE TITLE
Bust OP cache for CMS template cache files

### ISSUE THREAD

**Issue by daftspunk** [octobercms/october#2385]
Implement Twig's approach to file based cache. See: https://github.com/twigphp/Twig/blob/master/lib/Twig/Cache/Filesystem.php#L67
##### References
- #1250
- #872

**Comment by alxy** [comment]
@daftspunk There appears to be an issue with this implementation on specific systems: http://octobercms.com/forum/post/exception-after-update?page=1#post-18288

I already referenced the relevant drupal discussion, maybe October should take the same approach...

**Comment by daftspunk** [comment]
Can you submit a PR for this?
