### ISSUE TITLE
Adding more Scaffolding commands

### ISSUE THREAD

**Issue by CSNWEB** [octobercms/october#2387]
Hello,

I would like to add more scaffolding commands, I currently thought of the following:
- Creating Migrations: create:migration
- Adding files for behaviours: maybe create:relation, create:importexport or add:relation, add:importexport

May be even add a param to  create:controller command to include those if you already know that you will need them? 

I'm just not sure if you rather would like me to make a pr or add these commands via an plugin?

**Comment by leocavalcante** [comment]
You sure can build your own commands:
http://octobercms.com/docs/console/development

**Comment by CSNWEB** [comment]
Yes I know, but I would consider those commands as part of the core and would prefer to add them here directly.

**Comment by daftspunk** [comment]
Some of these might prove difficult, since October won't be allowed to modified existing PHP files. It can modify YAML files though (eg: updates.yaml). Feel free to submit a PR for each command you want and we can discuss it in more detail there.
