### ISSUE TITLE
Error in october installer

### ISSUE THREAD

**Issue by trsh** [octobercms/october#2389]
##### Expected behavior

Install from installer without errors.
##### Actual behavior

Any ideas on this installer error -> "Parse error: syntax error, unexpected 'pR' (T_STRING), expecting ']'" on line 119 of /home/fotocimparimpa/public_html/install_files/php/InstallerRewrite.php(43) : eval()'d code 
##### Reproduce steps

Install with newest installer and PHP 7

**Comment by trsh** [comment]
Turns out, I can't use high security password like this "]pR@}WTgR.n1".

**Comment by LukeTowers** [comment]
@trsh What are you using this password for? The admin account login password or the Database connection password?

**Comment by trsh** [comment]
Database password. One defined in config.

**Comment by daftspunk** [comment]
Duplicate of #2361
