### ISSUE TITLE
[bug] Pivot table row not deleted when deleting a model item.

### ISSUE THREAD

**Issue by that0n3guy** [octobercms/october#239]
I am using a many-to-many polymorphic relationship.  I can create items via the backend and add relationships using the relation field (in the backend forms) easily.

I noticed that deleting an item will remove it form the main table... but not the reference from the pivot table. 

###How to duplicate:

* Create 2 models: contact, and ocalist... Here are my models (2 files in 1 gist): https://gist.github.com/that0n3guy/e8c25b6146f5b5b896ed

* create databases (2 files in 1 gist): https://gist.github.com/that0n3guy/1dc690374767dceba3cb 

* create your backend forms (contact and list, 2files in 1 gist): https://gist.github.com/that0n3guy/7479972eb4160f9eaf9e

* create a couple lists in the backend
* create a couple contacts in your backend referencing some lists
* delete a contact in your backend
* open phpmyadmin and look at your `oca_blasts_ocalistables` table... you will still have pivot rows for the deleted contacts.

**Comment by daftspunk** [comment]
This is finally fixed in the upcoming build

Ref: https://github.com/octobercms/library/commit/2d29cbc42e7a29d3312493b0b741f92b433606aa#diff-dfa33b774dcd9386d95be910586cc883

**Comment by iboved** [comment]
Does not work for $morphToMany relation.
Pivot table in $morphToMany relation is not cleared. There must be the same logic for the $morphToMany relation. Something like that:
```
            if ($type == 'belongsToMany' || $type == 'morphToMany') {
                foreach ($relations as $name => $options) {
                    $this->{$name}()->detach();
                }
            }
```

**Comment by LukeTowers** [comment]
@iboved feel free to make a pull request to fix it
