### ISSUE TITLE
Backend list number column not aligned properly

### ISSUE THREAD

**Issue by Eoler** [octobercms/october#2396]
It looks like **td.list-cell-type-number** backend style is missing **text-align:right;** CSS property. 

##### Expected behavior
Model attribute defined in columns.yaml as **type: number** should have column right aligned in backend list:
https://octobercms.com/docs/backend/lists#column-number

##### Actual behavior
Backend list column is left aligned.

##### Reproduce steps
Create model with field definition in columns.yaml
```
    id:
        label: ID
        type: number
```
and corresponding backend controller. Observe list in the backend.

##### October build
367

**Comment by axomat** [comment]
Same problem reproduced here.
