### ISSUE TITLE
In richeditor, code view option disables full screen option on toolbar - Richeditor/Froala

### ISSUE THREAD

**Issue by wilirius** [octobercms/october#2397]
##### Expected behavior

Code view option on a rich editor disables only wysiwyg-related buttons.
##### Actual behavior

Code view option on this rich editor disables all buttons, excluding the one to get out of code view, and unfortunately including the ability to switch in an out of full screen mode.
##### Reproduce steps
1. Go to any rich editor.
2. Switch to full screen.
3. Switch to code view while in full screen.
4. Try to switch out of full screen.
##### October build

365

**Comment by LukeTowers** [comment]
@wilirius is this still an issue?

**Comment by wilirius** [comment]
Negative. Closing.
