### ISSUE TITLE
Search in relation

### ISSUE THREAD

**Issue by Perfect7M** [octobercms/october#2401]
It's not an issue but it is a real problem. I have many to many realation and its work fine but on "assignation tab" there are no search. If i will have 3 or 4 records this will be ok but in 150 (and this still grow), it is a big issue because if this 'list' would render in `<ul><li></li></ul>` style i would use list.js or something like that, but no..

**Comment by mplodowski** [comment]
Did you try to set `showSearch` flag to `true` as mentioned in [docs](http://octobercms.com/docs/backend/relations#configuring-relation).

**Comment by Perfect7M** [comment]
Now its worked like a charm :) thanks
