### ISSUE TITLE
GitHub Hacktoberfest : participation of October CMS?

### ISSUE THREAD

**Issue by FelixINX** [octobercms/october#2404]
Hi,

I think that October CMS should participate in GitHub / Digital Ocean Hacktoberfest. If the admin of the October CMS repo's add the `hacktoberfest` label, many person could discover, and solve issue!

Also, October CMS could be add to the [featured projects PHP](https://hacktoberfest.digitalocean.com/#featured-projects-PHP) list!

Thanks

**Comment by LukeTowers** [comment]
Worth looking into at any rate, it's got my +1 for what that's worth!

**Comment by adrenth** [comment]
That is a wonderful idea! +1

**Comment by pratyushpundir** [comment]
+1 for sure!

**Comment by GrCOTE7** [comment]
Yas, of course +1 :-)

**Comment by faustoquaggia** [comment]
+1

**Comment by daftspunk** [comment]
Nice idea, we participated in this last year and it was good to see people help. We are a quite a lot busier this year as the project has doubled in size so it might be a bit harder for us to manage. If you spot an issue you want to work on, let me know on IRC or Slack and I will tag it for you.
