### ISSUE TITLE
Labels wrapped with anchor tag in reporting charts.

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#2406]
##### Expected behavior

I should be able to wrap Label with anchor tag element and see linked Label in chart legend.
##### Actual behavior

Label is not visible. Missing in chart legend source code.
##### Reproduce steps

Create report widget like described in the docs, but wrap labels with anchor tags. 

```
<div
    class="control-chart wrap-legend"
    data-control="chart-bar"
    data-height="100"
    data-full-width="1">
    <ul>
        <li><a href="#">Label 1</a> <span>100</span></li>
        <li><a href="#">Label 2</a> <span>100</span></li>
        <li><a href="#">Label 3</a> <span>100</span></li>
    </ul>
</div>
```
##### October build

Build 365

**Comment by daftspunk** [comment]
Which part are you expecting to be linked? Just the label itself, right? Or the chart itself too?

**Comment by mplodowski** [comment]
Yes, only labels.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
