### ISSUE TITLE
a typo error

### ISSUE THREAD

**Issue by diaa1972** [octobercms/october#2409]
##### Expected behavior
when creating a new list column, one of the types is "**Time Since**".

##### Actual behavior
It shows "**Tine Since**" with an N not M

##### Reproduce steps
- go to "plugins\rainlab\builder\lang\en\lang.php"
- replacde  'Tine since' with 'Time since'

##### October build
(October build number)

**Comment by jundis** [comment]
This is part of the Rainlab Builder plugin, not native October.

**Comment by LukeTowers** [comment]
It's also been fixed in rainlab/builder-plugin#114

**Comment by daftspunk** [comment]
@diaa1972 please don't submit duplicate issues.
