### ISSUE TITLE
Using date filters on a page with multiple lists

### ISSUE THREAD

**Issue by Klaasie** [octobercms/october#2411]
##### Bug summary

For more extensibility we render multiple list views (from different controllers) into a controllers update page. Every list has a separate tab and their own filters. Currently we face an issue with the date filter functionality. Where by adding a second list view the functionality of the date filter reset button results into a error message.
##### Expected behavior

Being able to clear the date filter using the reset button on a second list view on the same page.
##### Actual behavior

Clicking the reset button (clear data-trigger) causes the error message:
`Uncaught TypeError: Cannot read property 'find' of null`

I've pinpointed the issue to the following event listener (lines 94 - 99 filter.dates.js):

```
$(document).on('click', '#controlFilterPopover [data-trigger="clear"]', function (e) {
            e.preventDefault()
            e.stopPropagation()

            self.filterByDate(true)
})

```

In the case of multiple lists views with date filters enabled the event listener seems to lose its self instance and generate a new one without an $scope variable. The function _updateScopeDateSetting_ (line 288 in filter.dates.js) will then try to use function "find" on null.
##### Reproduce steps
1. Create two controllers (& models) with date filters enabled in their filter configs
2. Load those two controller list configs into a third controller.
3. Render the list views into the update page of the third controller (in seperate tabs)
4. Use the date filter on the second tab (selecting dates will work as expecting, the "reset" button will cause the error.
##### October build

365

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by LukeTowers** [comment]
Should be fixed by https://github.com/octobercms/october/commit/a2315624df0406a78d12ff262faac4d8443c05d6#diff-d5530d68aa66cdd0d3bca6bd092da290
