### ISSUE TITLE
Use halting and holder events for extensibility

### ISSUE THREAD

**Issue by enniel** [octobercms/october#2420]
All events used to inherit or override any of the values must be rewritten, because many of them receive values from the listener, which entails the interruption of other listeners.
From the code comments [#L223](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Events/Dispatcher.php#L223):

```
// If a response is returned from the listener and event halting is enabled
// we will just return this response, and not call the rest of the event
// listeners. Otherwise we will add the response on the response list.
```

**Comment by LukeTowers** [comment]
There appear to be 22 global events currently with the `$halt` flag enabled, and 27 local events according to my [list of built-in events](https://docs.google.com/spreadsheets/d/17vv4zn_ezp9iFBgYhYuYsmUG4MXW9uuIw7aOIrVcHiM/edit?usp=sharing)

**Comment by daftspunk** [comment]
This is high level and unactionable. Please provide a specific example of where you have encountered this problem.

**Comment by enniel** [comment]
Example from my code:

```php
Event::listen('backend.list.overrideColumnValue', function ($widget, $record, $column, $value) {
            $columnName = $column->getName();

            if ($this->isMessages($widget)) {
                $value = $this->limit([
                    'text',
                    'description',
                ], $column, $value);
                if ($columnName === 'provider') {
                    if (in_array($value, $providers)) {
                        $value = trans('enniel.ocsms::lang.backend.properties.providers.'.$value);
                    }
                }
            }

            return $value;
 });
```

But in fact it doesn't matter. You just use it for the wrong event dispatcher. I already wrote about this above. You can't return a value inside the listener, because it aborts execution of other listeners.

**Comment by LukeTowers** [comment]
In your particular case, isn't it a good thing that it halts execution? Otherwise, then you'd have to figure out which call to the event is returning the final value if multiple plugins are trying to change the value through that event.

**Comment by enniel** [comment]
@LukeTowers This example works if just one listener, but if several of them will only work the first.

```php
//worked
Event::listen('backend.list.overrideColumnValue', function ($widget, $record, $column, $value) {
            return $value;
 });
//don`t worked
Event::listen('backend.list.overrideColumnValue', function ($widget, $record, $column, $value) {
            return $value;
 });
```

**Comment by daftspunk** [comment]
Still not sure what is supposed to happen here. Please try again.

As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by daftspunk** [comment]
This just clicked, I think I understand now. The "halting event" is no good when you want a "holder event", as [described in the developer guide](http://octobercms.com/help/guidelines/developer#event-naming):

```
// Pass content to events by reference
$dataHolder = (object) ['content' => $content];
$this->fireEvent('cms.processContent', [$dataHolder]);
Event::fire('cms.processContent', [$this, $dataHolder]);
$content = $dataHolder->content;
```

I think ultimately this could be solved using an event helper that would attach a suffix to the event name, creating a new event, that utilizes the holder pattern.

```
$content = $this->fireSystemEvent('cms.processContent');
```

If the suffix is called `ByRef`, this would trigger the following:

```
$this->fireEvent('processContentByRef'); // Holder pattern local event
Event::fire('cms.processContentByRef'); // Holder pattern global event
$this->fireEvent('processContent'); // Halting local event
Event::fire('cms.processContent'); // Halting global event
```

**Comment by daftspunk** [comment]
Found a solution for this, we can pass values by reference on both sides of the event. This will be available in Build 389+

```
Event::listen('backend.list.overrideColumnValue', function ($widget, $record, $column, &$value) {
    $value = $value . 'a';
 });

Event::listen('backend.list.overrideColumnValue', function ($widget, $record, $column, &$value) {
    $value = $value . 'b';
 });
```
