### ISSUE TITLE
Can't Translate October\Rain\Auth Error Message

### ISSUE THREAD

**Issue by cracki** [octobercms/october#2424]
##### Expected behavior
There is no way (or i don't know) to translate Login Error message in !debug mode

##### Actual behavior
use need translate:
'The details you entered did not match our records. Please double-check and try again.'
 
##### Reproduce steps
Add Rainlab User plugin and use login form component  and change app config debug to false and enter false user info

##### October build
359

**Comment by daftspunk** [comment]
Duplicate of #2106
