### ISSUE TITLE
Theme management permission and empty CMS section

### ISSUE THREAD

**Issue by j000** [octobercms/october#2425]
I discovered October recently, this is my first "adventure" with it. So far it's been **amazing**. Thank you very much. Now to the issue...

I'm creating site using static pages, something in lines with client-friendly website example you have. I allowed some personalization in custom theme to allow changing few things. But to do that I need to give permission to _manage themes_ to user. Doing so enables _CMS_ in top menu without any content (user have no other permissions in this category). It also allows to install and change theme, which is not what I want.

I'm guessing I can create plugin to extend something and change all that stuff. That's what I'm trying to do right now (create button in menu to allow to personalize current theme).

---

I really think empty CMS entry in main menu is a bug. If theme management is in backend settings, permissions to do so should be in the same group.

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by j000** [comment]
1. Create user/group with no permissions in cms section. _CMS_ category in top menu is hidden.

2. Enable _manage themes_ permission.

### Result:
_CMS_ category in top menu is shown, but there is nothing in left sidepanel.

### Expected result:
No _CMS_ category in top menu, because option to personalize/change theme is in _settings_ category.
