### ISSUE TITLE
404 when changed directly to localized URL with enableRoutesCache => true

### ISSUE THREAD

**Issue by jan-vince** [octobercms/october#2427]
### Expected behavior

Link to different (localized) URL should render that Page.
### Actual behavior

404 error when trying to go directly to localized URL.
#### 1. Set config/cms.php

enableRoutesCache => true
#### 3. Create two Static pages with titles and URLs:

> [en] Home, [localizedUrl] /
> [cs] Uvod, [localizedUrl] /
> 
> [en] Contact, [localizedUrl] /contact
> [cs] Kontakt, [localizedUrl] /kontakt
#### 4. Create one layout same for both with:

``` (html)
[localePicker]
forceUrl = 1

[staticPage]
==
<ul>
    <li>
        <a href="{{ ''|app }}/cs">Úvod</a>
        <a href="{{ ''|app }}/cs/kontakt">Kontakt</a>
    </li>
</ul>
<ul>
    <li>
        <a href="{{ ''|app }}/en">Home</a>
        <a href="{{ ''|app }}/en/contact">Contact</a>
    </li>
</ul>

<h1>{{ this.page.title }}</h1>

```
#### 5. Try to change directly to URL

Go to `/cs/kontakt` and than click on menu item Contact (`/en/contact`). It throws me 404 error page.

When I flush cache (in backend with Clear Cache plugin or in layout with `\Cache::flush()`) and reload page (without touching URL), page Contact renders.

> I think than cached URL map probably contains only URLs of currently selected locale.
#### 6. Workaround

Set `enableRoutesCache => false` even in production (but this results in very slow response).

Or URL parameter and some PHP logic to invoke cache clearing when changing to different locale.

Non of this is good solution :(
### October build

October: 372
Rainlab.Pages: 1.2.10
Rainlab.Translate: 1.2.4

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
