### ISSUE TITLE
file upload on frontend using ajax

### ISSUE THREAD

**Issue by bbrandtlv** [octobercms/october#2428]
##### Expected behavior

should upload file using AJAX.
AJAX needed, but without any external plugins
##### Actual behavior

Using ajax not working, only regular way (forn_open(), not form_ajax())
##### Reproduce steps

Not working:
{{ form_ajax( 'onCreateConcert', {files: true }) }}
   <input type="file" name="upload">
   <button type="submit" >Send to serve</button>
{{ form_close() }}

Working
{{ form_open({request:  'onCreateConcert', files: true }) }}
   <input type="file" name="upload">
   <button type="submit" >Send to serve</button>
{{ form_close() }}

im getting record without file. file_size and content_type both empty.
##### October build

365

**Comment by daftspunk** [comment]
File uploads do not work with AJAX. Not without complicated XHR implementation, which is not supported by all browsers last time we checked. Try the [Responsiv.Uploader plugin](https://github.com/responsiv/uploader-plugin) as a solution.

**Comment by artras** [comment]
I also need file upload via AJAX... How we can do it?

**Comment by bbrandtlv** [comment]
@artras  you cant!
Or without ajax, or use your own function (JS ajax)

**Comment by artras** [comment]
@bbrandtlv Do you use Responsiv.Uploader plugin?

**Comment by bbrandtlv** [comment]
@artras This is another option.

**Comment by daftspunk** [comment]
Note, support has been added for this in Build 420+ (#2857)

**Comment by meysammahfouzi** [comment]
You can also use this: https://github.com/blueimp/jQuery-File-Upload/wiki/Basic-plugin
