### ISSUE TITLE
Flash only returns first message of each type, and displays last message received

### ISSUE THREAD

**Issue by geoffbeaumont** [octobercms/october#2430]
##### Expected behavior

Adding multiple Flash messages of the same type (error, warning, etc.) should result in all messages being displayed (in this case via the response to an AJAX handler).
##### Actual behavior

Only the first message of each type is returned in the JSON response, and hence is available to be displayed.

This appears to be because although FlashBag itself stores multiple messages, and the underlying MessageBag::all($format = null) method returns all messages, \October\Rain\Flash\FlashBag overrides this with it's own all($format = null) method which takes only the first message of each type (i.e. it appears that the MessageBag functionality has been deliberately degraded). This is compounded by the fact that the FlashBag version of all($format = null) discards the $format, so that it isn't possible to pass in markup to surround the message as it is with the standard MessageBag.

If FlashBag is only going to return one message of each type, it would make sense to return **all** messages of that type conflated together, and to apply format to each one so that they can, for example, be styled as bullet points (as the markup generated embeds them in a paragraph this would have to use styled spans rather than a real list). For this to work it would require that the message was escaped before the format was applied and then the view output the result unescaped. Alternatively...just return all the messages in the first place!

Further, even if there is more than one message returned in the JSON (say a warning and a success), only the **last** of these will be shown as a flash message. This is again presumably a deliberate choice to discard the other information rather than stacking the messages so the user can see them.
##### Reproduce steps

In an AJAX handler method, call Flash repeatedly:

```
public function onTestFlash(){
    Flash::error('First error');
    Flash::error('Second error');
    Flash::warning('First warning');
    Flash::warning('Second warning');
    Flash::success('First success');
    Flash::success('Second success');

    return $this->listRefresh():
}
```

This will return (note that only the first message of each type is present - the rest are silently discarded):
```
{
"#layout-flash-messages":"    <p data-control=\"flash-message\" class=\"flash-message fade error\" data-interval=\"5\">First error<\/p>\n    <p data-control=\"flash-message\" class=\"flash-message fade warning\" data-interval=\"5\">First warning<\/p>\n    <p data-control=\"flash-message\" class=\"flash-message fade success\" data-interval=\"5\">First success<\/p>\n",
**etc**
}
```
Only the success message "First success" (the **first** of its type added but the **last** returned in the JSON) is actually displayed to the user, masking the earlier errors and warnings that did make it as far as the JSON.
##### October build

365

**Comment by LukeTowers** [comment]
@daftspunk Is this still a problem with the most recent changes to the AJAX framework?

**Comment by daftspunk** [comment]
This is semi-by-design, a subsequent Flash call will "overwrite" the previous Flash call of the same type. As described, all messages are captured so they could be used in a more complex scenario. This issue does not detail any such scenario, only that it considers this a bug.

**Comment by priitperna** [comment]
Any plans on doing something about it?

I have a case where I'm deleting multiple rows in a list and some rows wont be deleted by conditionally returning false in the `beforeDelete()` in the model. In that case additional flash messages should be pushed so the user would know why some of the records were not deleted.
