### ISSUE TITLE
Unable to pull partial updates from a widget AJAX call

### ISSUE THREAD

**Issue by sewagolubkow** [octobercms/october#2432]
### Expected behavior

https://octobercms.com/docs/cms/ajax#data-attributes
I wanted to use the AJAX feature "data-request-update" inside my new widget.
Stumbled a second time over this (darn'it).
### SystemException thrown

ViewMaker | Line: 65 | The partial is not / wasn't found
### But, why?

Well, the ViewMaker Trait inside our Widget is looking for files, relative to the Controller.
But our Controllers are all over the place, so he can't find our partial, which lives inside the Widget folder.
### There is already a solution

"Pushing Content Updates" or using your own JavaScript is a great workaround:
https://octobercms.com/docs/cms/ajax#pushing-content-updates
### Then, why the nagging?

There is no information that this function shouldn't work inside a Widget. Either state in the exception text something like _"The partial, relative to Controller '\MyController' wasn't found"_, or add a note to the documentation, that this doesn't work in widgets.

I'm not the only confused one: https://octobercms.com/forum/post/the-partial-is-not-found-viewmaker

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by sewagolubkow** [comment]
Haven't seen that plugin yet... really cool!
Here's the pull: https://github.com/daftspunk/oc-test-plugin/pull/25

Just go to "Playground > People > Edit"
There is a field called "Ajax Test" with three AJAX buttons.
They are quite self-explaining :)

**Comment by daftspunk** [comment]
This should be fixed in Build 378+

Thanks!
