### ISSUE TITLE
Security Issue at the backend

### ISSUE THREAD

**Issue by abhi1693** [octobercms/october#2433]
##### Expected behavior
The users that are not administrators or do not have the appropriate permissions should not be able to access the `Settings` page in the `backend`.

##### Actual behavior
The users who does not have appropriate permissions are able to access a part of the `Settings` page at the `backend`.

##### October build
365

There should be an option to disable/enable access to the `Settings` page to increase security as the unauthorized user will be able to make changes to the website.

**Comment by daftspunk** [comment]
As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by abhi1693** [comment]
Create a group which do not have any permissions except for writing blog posts. Then create a user under this group. When the user will log in, he/she will be able to access some parts of the settings page nonetheless.

![tt](https://cloud.githubusercontent.com/assets/5083532/19540753/2b30e8ea-967f-11e6-8256-9f8ff1488419.png)

The user shown in the image above is able to access the Settings page which should not be allowed to open for him.

**Comment by Eoler** [comment]
> When the user will log in, he/she will be able to access some parts of the settings page nonetheless.

That's because "Backend preferences" and "My account" admin screens are also settings.
On your screenshot only 3rd party plugins that haven't thought about permissions are listed.

**Comment by abhi1693** [comment]
What you are saying is a bit different from my problem. I don't have a problem if the user accesses the "Backend Preferences" or the "My account" page. But should not be able to access the `/backend/system/settings` page. So, is there a way to do that without hard coding it in the cms?

**Comment by daftspunk** [comment]
This is a 2 part problem:

1) The installed plugins you are using do not specify a permission for their settings pages. Contact the authors to have this issue fixed.

2) The settings page is always visible. Duplicate of #2175
