### ISSUE TITLE
Question: get render time

### ISSUE THREAD

**Issue by maxibanki** [octobercms/october#2435]
#### Question:
Is it possible to get the render time of a site and the executed queries on a site? So that I can show them in the footer for example?

##### October build
365

**Comment by sewagolubkow** [comment]
#### There are great plugins for that
Debug Bar: http://octobercms.com/plugin/bedard-debugbar
Clockwork: http://octobercms.com/plugin/qub-clockwork

#### Also, there is a support forum for general questions: 
https://octobercms.com/forum

**Comment by maxibanki** [comment]
Okay, sorry, and thank you :+1:

**Comment by sewagolubkow** [comment]
Hey no prob, but I want to say, I've never trusted the debugbar timeline.
Also, it seems to run faster, when debug mode is deactivated in "config/app.php".

And laravel provided some compilation scripts, which speed up the app, but I don't know if they are working in October. I'm still weeks from publishing my first October site myself...
