### ISSUE TITLE
Error on Software Update

### ISSUE THREAD

**Issue by DanielHitchen** [octobercms/october#2437]
##### Expected behavior
To update the core CMS build to latest release.

##### Actual behavior
Error shown
![error](https://cloud.githubusercontent.com/assets/7501909/19563756/14a5a246-96d9-11e6-94d0-5efa2fd30776.jpg)
Not sure if this is caused by my hosting package or something else as the CMS updates fine locally via MAMP and on other websites I've done on other hosting, but they may have been a later build from install. Never had any issues before.

##### Reproduce steps
Navigate to ```settings > Updates & Plugins > Check for updates```

##### October build
367

**Comment by worldofsmarty** [comment]
This issue has been caused by your cloudflare installation. You need to disable the cloudflare for some time and try to proceed with the installation.

**Comment by DanielHitchen** [comment]
Hi @worldofsmarty, thanks for your response - as far a I know, I don't have cloudflare installed unless my hosting provider has installed it on my behalf - I'm using Vidahost cloud hosting for my site so guess I'll have to contact them to find out what's happening - everything was fine not long ago.

**Comment by worldofsmarty** [comment]
Hi @DanielHitchen, I had faced the same issue while developing the website for our own firm. We had cloudflare installed and on each time we try to save the changes in CMS. This page appears. 

Usually this is the security check recaptcha box trying to verify human. It is an additional security by the cloud flare.

We then stopped cloudflare for some time until the development had been completed and then reverted back the cloud flare settings.

**Comment by daftspunk** [comment]
This is because October is now behind cloudflare. We are still having some teething issues with this. @DanielHitchen, it should be fixed now if you'd like to try it again.

**Comment by DanielHitchen** [comment]
Hi @daftspunk, I can confirm this is now fixed. Thanks for your help.

**Comment by DanielHitchen** [comment]
Hi Vijay, thanks for your response - as far a I know, I don't have cloudflare installed unless my hosting provider has installed it on my behalf - I'm using Vidahost cloud hosting for my site so guess I'll have to contact them to find out what's happening - everything was fine not long ago.
