### ISSUE TITLE
Sass / Scss compiler problem

### ISSUE THREAD

**Issue by maxibanki** [octobercms/october#2441]
##### Expected behavior

right half of the image

##### Actual behavior

left half of the image
The transform property is in quotes.

##### Reproduce steps

`<link href="{{ [
         'assets/sass/main.scss'
         ]|theme }}" rel="stylesheet">`

=> `@include vendor('transform', 'translateX(#{_size(navPanel)})');`
for example
with other compilers like Scout-app for windows, it works fine.
##### October build
365

![image](https://cloud.githubusercontent.com/assets/17984549/19606316/b589a2fa-97c1-11e6-99d1-df6cf5784e17.png)

**Comment by xNok** [comment]
See [scssphp](https://github.com/leafo/scssphp).This is the project used by October to compile scss.

I advise you to post your issue on scssphp repo so they can help to fix this issue.

**Comment by daftspunk** [comment]
As above.
