### ISSUE TITLE
Extending Rainlab\User controller gives error due to Capital letter in getConfig path

### ISSUE THREAD

**Issue by GitJaap** [octobercms/october#2443]
I'm extending the Rainlab\Users controller  so i can have my own partials for the backend view of users. 
I have created a new backend menu item for my own extended user plugin. But I keep receiving the error 
Unable to find configuration file
[root_path]/plugins/Rainlab/user/models/user/columns.yaml defined for Backend\Behaviors\ListController.
in modules/system/traits/ConfigMaker.php line 63

![image](https://cloud.githubusercontent.com/assets/8937555/19626571/5a870d32-9935-11e6-904d-e20e898f9d2e.png)
##### Expected behavior

On windows there is no problem, but linux is case sensitive so I receive this error only in staging. I would expect the "Rainlab" to be lower case rainlab/users/... 
##### Actual behavior

The Rainlab is capitalized in the path so the directory is not found on linux. I fixed it by copying the rainlab folder and renaming it Rainlab. So now two rainlab folders would exists and it could find the columns.yaml file. As you can see this is not the most elegant solution.
##### Reproduce steps

Extend the users.php controller by another controller in another plugin.
##### October build

365

**Comment by daftspunk** [comment]
The reproduce steps are lacking in detail. Please provide the code you are using to arrive at this error.
