### ISSUE TITLE
How to upload (Best way to upload) whole OctoberCMS project from localhost to live server

### ISSUE THREAD

**Issue by mittultechnobrave** [octobercms/october#2444]
I am new to OctoberCMS and currently i am developing one project in the same CMS in my local server . . say it has a url something like http://localhost/october_cms/

Now my question is, how to upload [best way to upload] my whole new project to live server with database with the new url itself .. something like http://www.example.com/ or something like http://www.subdomain.example.com/ or http://www.example.com/octobercms anyway ?

I want the database urls should be changed as well without any hurdle or any issues after i upload on live server.

Any idea or any plugin OctoberCMS provides to deal with this thing ?

Thanks

**Comment by Patroklo** [comment]
You always can use a migration engine for php (like phing) and a database migration engine (like phinx). 

Another way that a lot of people don't like at all  it's using a version system to upload the master files, but that won't upload your database.

[Here's another option](https://octobercms.com/forum/post/the-best-practices-for-deployment-octobercms-from-the-local-environment-to-production)

[Also remember that there are best practises for production deployment](https://octobercms.com/forum/post/deploying-cms)

**Comment by mittultechnobrave** [comment]
oops .. there are lots of things to follow to achieve this .. i dont mind but i was hoping OctoberCMS does have or could have a plugin which can does this thing ? or is there any ? it seems like this one is tricky .. do we have any other straight forward option like wordpress provides .. some plugin or anything will be great you know ..

**Comment by Patroklo** [comment]
Well~  there's this thing for database backups... https://octobercms.com/plugin/renatio-backupmanager

For code, you can make a project and store there all the plugins you use, but your theme won't be saved.

**Comment by mittultechnobrave** [comment]
woww .. thats longgggg process to follow to achieve this .. i hope October find a smooth and straightforward process to achieve this task for the developers just like other CMS already does so developers do not need to bother about all these things and save the time as well.. 
Thank you ..

**Comment by Patroklo** [comment]
Out of pure curiosity... which steps the worpress automatic deployment follows?

**Comment by mittultechnobrave** [comment]
i will tell you but if you can just check my this answer and can help me furthure please https://github.com/octobercms/october/issues/2440

**Comment by Patroklo** [comment]
I think you should also close this issue since there's nothing like you were looking for in this case.

**Comment by mittultechnobrave** [comment]
well .. give me some time please for this question.. i will close it soon .. once i find something, i can or will put something [if there is any] .. if not i will definately close it .. (y)

**Comment by DanielHitchen** [comment]
[October Pond](http://octobercms.com/pond) could be an option once it's up & running, just depends on what type of hosting/live server you have.

I personally only ever use shared/cloud hosting for my projects as my clients don't want to spend a fortune hosting their websites.

The the process I have for my projects is:

1. Work locally via MAMP to develop the website/theme and any plugins etc
2. Create a fresh install of October on their hosting/server
3. Upload any custom plugins & website theme
4. Export any tables from local DB to .SQL files and migrate to the online DB via [this plugin](http://octobercms.com/plugin/martin-adminer)

A bit long-winded but it works for me as the sites I create aren't that large, just small local businesses, and once you've got the initial upload done, I just tend to work online and back up the database from time-to-time - the entire website directory is securely backed up via the hosting provider anyway _(subject to hosting provider)_, so that takes care of the theme & plugins etc.

Like I said, a bit long-winded, but it works for me :)

**Comment by mittultechnobrave** [comment]
Thanks for your reply .. 

My only concerned about this point .. 

**4. Export any tables from local DB to .SQL files and migrate to the online DB via this plugin**

Do i need to change urls while migrating from local to live server ? does OctoberCMS tables saves localhost urls like http://localhost/october_cms/ in their records ?

**Comment by mittultechnobrave** [comment]
ok so i can expect if i just follow the steps like 1) install fresh october on live server, 2) copying all the plugins and paste to live server, 3) copy whole theme and paste it to live server, 4) just export local database and import it to live server .. If i m gonna do this, it will be working fine .. is it so ? 
	
and also as far as my understanding while i m importing, i just need to upload or import plugin tables on live server .. correct ?

**Comment by DanielHitchen** [comment]
Yes, you don't need to migrate the entire DB to the live server, only any tables that are plugin specific where the data may have been entered locally whilst in development and therefore doesn't exist on the live server i.e blog posts etc - just remember to also upload your ```storage/app/uploads``` directory for any images you've uploaded in development along with a migration of the ```system_files``` table for the linkage.

Like I said though, it is long-winded and a lot of things can potentially go wrong as none of it is automated - for the most part, I do try to only build the theme locally and then populate the live site on the live server - just narrows down the possibility of any major errors happening

**Comment by mittultechnobrave** [comment]
Yea that makes sense about `storage `folder and` system_files` table .. 

However, fingers crossed on your points about the possibility of any major errors hapening ;) 

Anyways, thanks for all these .. i will comeback if i stuck :) 

Thanks for all the support .. keep up the great work .. 

Thank you guys.

**Comment by mittultechnobrave** [comment]
As you said **I do try to only build the theme locally and then populate the live site on the live serve**r  , my question is, what about plugins then ? how you deal with plugins ? i guess you also upload plugins with db .. correct ?

**Comment by DanielHitchen** [comment]
Well the plugins whether installed locally or on the live server create the same DB tables regardless, so it's just a matter of exporting the table from your local server, and importing it into the live server - but you'll only need to manually upload custom plugins that aren't served via the October plugins store - if they're in the store, just install them via the ```settings > Updates & Plugins``` page in the live CMS, then migrate the relevant table

**Comment by mittultechnobrave** [comment]
ok .. thank you .. great inputs!!!

**Comment by paddy-sherry** [comment]
There is a lengthy guide on[deploying OctoberCMD from local to production](https://leaderinternet.com/blog/how-to-deploy-octobercms-localhost-to-production)

**Comment by olivedev** [comment]
I know it is close, but I will still go ahead and post my reply here. I have my whole project up on github repo from localhost. I have connected the repo to my live [PHP host](https://www.cloudways.com/en/php-hosting.php) server. I am using Envoyer to connect the github with the live server to make it easier to deploy everytime commit is done.
