### ISSUE TITLE
Unable to install October CMS from Wizard

### ISSUE THREAD

**Issue by naw3l** [octobercms/october#2448]
All goes well until this message pops up "Package files from server are corrupt" during installation.
I'm running on Windows 7, XAMP, and all requirements are fulfilled.
If i check installation log, it shows a hash error, i tried downloading several times, and nothing seems to work.

**Comment by naw3l** [comment]
...

**Comment by daftspunk** [comment]
Would you mind sharing your install.log file? A detailed installation log can be found in the install_files/install.log file.

**Comment by dpencheva** [comment]
@daftspunk 

I have the same settings Windows 7, XAMPP.
The install.log part for the error is:
----------------------------------------
Postback payload: Array
(
    [step] => downloadCore
    [meta] => Array
        (
            [core] => Array
                (
                    [hash] => e62651bcb2388e26a5c1079d467b11df
                    [build] => 382
                    [uhash] => 305de721d2f8e9580ef858a799dea70b
                )

        )

    [handler] => onInstallStep
)

Install step: downloadCore
File hash mismatch: e62651bcb2388e26a5c1079d467b11df (expected) vs 0e6e95f6e162fc7b23ed9eecbbcfcc69 (actual)
Local file size: 7686414
Handler error (onInstallStep): Package files from server are corrupt
Trace log: ...
----------------------------------------

I was able to install OctoberCMS manuallly via console install as described in the documentation.
php -r "eval('?>'.file_get_contents('https://octobercms.com/api/installer'));"

(
But it had two attempts to download - the output in console was:

All settings correct for installing OctoberCMS
Downloading OctoberCMS...
Unable to extract zip file, retrying...
Downloading OctoberCMS...

OctoberCMS successfully installed to: .....\htdocs\octobercms
)

Then I run this in console:
php artisan october:install

And the demo is up and running.

**Comment by daftspunk** [comment]
I can only think this is a temporary issue caused when a new build is published. We will need to do further investigation.

**Comment by GlobalSolutions2018** [comment]
Same error here in windows 7 Laravel5.4.x , no solution yet , not installed

**Comment by LukeTowers** [comment]
What do you mean Laravel 5.4.X? There are no October builds that run Laravel 5.4.x

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
