### ISSUE TITLE
PHP Unit received status code [404] on exists page.

### ISSUE THREAD

**Issue by surahmans** [octobercms/october#2452]
Hi, I'm trying to run a simple test in my project. I'm trying to visit `post` page and ensure the some words is exists on that page.

But, I got the the following error when run this command `./vendor/bin/phpunit tests/ExampleTest.php`;
```
1) ExampleTest::testBasicExample
A request to [http://testing.dev/post] failed. Received status code [404].
```

I know exactly when access that url with browser the page is exists.

Here's my code:

_pages/post.htm_
```
url = "/post"
==
<h1>Welcome to post details page!</h1>
```

_tests/ExampleTest.php_
```
<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class ExampleTest extends TestCase 
{

    protected $baseUrl = 'http://testing.dev';

    public function testBasicExample()
    {
        $this->visit('/post')
             ->see('Welcome to post details page!');
    }
}
```

*OctoberCMS Build 376*

Thanks

**Comment by daftspunk** [comment]
Interesting. We need someone to peer review this to confirm.

**Comment by SaifurRahmanMohsin** [comment]
I tried something similar to unit test plugin routes and got 500 status code with message `Class user.auth does not exist` in file `/Users/Moz/Projects/Current/Acme/vendor/laravel/framework/src/Illuminate/Container/Container.php`.

Testing on OctoberCMS needs more documentation methinks.

**Comment by daftspunk** [comment]
@SaifurRahmanMohsin, help us help you. Please report a new issue instead of hijacking others. Here is how you can report an issue that we can use to help: 

As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Comment by surahmans** [comment]
Finally, I can solve this issue. It because I didn't configure the `config/testing/cms.php` with my existing theme and correct path. Hopefully for the next, testing in OctoberCMS more documented.

Thank you, @daftspunk. I love OctoberCMS!

**Comment by daftspunk** [comment]
You shouldn't need to update this configuration setting, although it is possible. Perhaps using `Config::set('cms.activeTheme', 'mytheme');` before the test runs would be suitable.
