### ISSUE TITLE
Rich Editor Improvements #2005 - can't apply the style on the front-page

### ISSUE THREAD

**Issue by CitrinoDeveloping** [octobercms/october#2456]
##### Expected behavior
Use the rich editor improvement to create standard class fro my froala editor in rainlab.pages

##### Actual behavior
Can see the css style and impementation in the backend editor. Can see modifies in the editor but not in the front. 

##### Reproduce steps
Where octboer load this custom css for froala editor? With firebug, i aware that can't see the code in front. Is like the css is not loaded. 

My example: 
Create this class:
a.oc-link-new-window { 
    content:"\e164"; font-family: 'Glyphicons Halflings'; font-size: 17px; margin-top: 2px;  color: #000;
}
and add to markup classes tab.
Can apply in the editor, the link change and have this class (.fr-view a.oc-link-new-window). 
The style applyed well in the backend editor but the "content rule" don't pubblish nothing.. 
In front-end the word associated with the style is not changed and have no style associated.

I'd like to create a series of standard rules to export to all my websites, so this feature is preciuos and i'd like to use it.

##### October build
3.6.5

Bye

**Comment by daftspunk** [comment]
It's up to you to include these styles in your front-end theme. The rich editor style definitions are for the back-end only. It is possible (and likely) that these styles will need to be represented differently across each environment, so they are treated as separate.

Simple solution is to copy and paste the styles from the backend textarea to the theme stylesheet.

**Comment by CitrinoDeveloping** [comment]
Hi,

thanks! I wanted to understand, we can absolutely think to create a plugin to do so. 
I know your time is precious, thanks for the response. 
Bye!

**Comment by daftspunk** [comment]
After some discovery, including the injection of this CSS as part of the core would affect performance for everyone (even for those who do not want it). Therefore a plugin is the best way to approach this.
