### ISSUE TITLE
Overriding localization strings 

### ISSUE THREAD

**Issue by kuzyk** [octobercms/october#2458]
##### Expected behavior
System users can override localization strings without altering the modules' and plugins' files. This is done by adding localization files to the app/lang directory.

##### Actual behavior
override localization string not work

##### Reproduce steps
1. create new file in project folder: lang/backend/en/lang.php
2. override some localization keys: e.g. auth.title => 'new admin area'
...

##### October build
378

**Comment by Patroklo** [comment]
You have to put your lang files when you are trying to override a october cms text in your main folder.

The behavior it's te same, but it gets the data from there instead, for example, in my case I'd have a change in `backend` texts here:

`/var/www/myoctober/lang/en/backend/lang.php`

Considering that you hold all your october cms installation in `/var/www/myoctober/`

**Comment by daftspunk** [comment]
Unable to replicate.

You may have the file path incorrect... [as per the documentation](http://octobercms.com/docs/plugin/localization#overriding):

#### Incorrect
lang/backend/en/lang.php

#### Correct
lang/en/backend/lang.php

#### Sample file

```
<?php 

return [
    'dashboard' => [
        'manage_widgets' => 'Manage widgets!!',
    ]
];
```

#### Result

Opening the back-end dashboard shows *Manage widgets!!* text at the bottom.

**Comment by kuzyk** [comment]
yes, all works. thanks

maybe you must fix readme in this repo https://github.com/octoberrain/translation

**Comment by daftspunk** [comment]
Thanks, these docs have been updated.
