### ISSUE TITLE
Sortable Trait only works with "sort_order" fieldname

### ISSUE THREAD

**Issue by swt83** [octobercms/october#2462]
##### Expected behavior
When giving a model the Sortable trait, and with proper setup of controllers, etc, I should be able to sort records using the Reorder ability.

##### Actual behavior
When using a custom field name for the order number, instead of the default ``sort_order`` field, the ability doesn't work.  Any new records created will have proper order values set, but any attempt to reorder the records will reset all values to ``0``.

##### Reproduce steps
I renamed the custom field several times, would truncate the table, and add records to test sorting.  It would only work properly if the field name in the table was ``sort_order``.

##### October build
376

**Comment by LukeTowers** [comment]
Did you specify the `SORT_ORDER` constant on your class that's utilizing the trait to override the default value being used for the sort_order column?
https://octobercms.com/docs/database/traits#sortable

ex.
```php
class MyModel extends Model {
    use \October\Rain\Database\Traits\Sortable;
    const SORT_ORDER = 'custom_sort_order_column';
}
```

**Comment by swt83** [comment]
Yes.  I also truncated the table and inserted new data.  New records would have proper order numbers, but attempting to actually sort would fail and make them all ``0``.

**Comment by LukeTowers** [comment]
What are you doing to sort them?

**Comment by swt83** [comment]
List Page
![list](https://cloud.githubusercontent.com/assets/907900/20071556/8f1ee856-a4ea-11e6-9b56-31078ca9daaa.png)

Reorder Page
![reorder](https://cloud.githubusercontent.com/assets/907900/20071561/931b8f22-a4ea-11e6-92b8-d7fce490b8c0.png)

**Comment by LukeTowers** [comment]
Are you able to post the contents of your reorder.htm view?

**Comment by swt83** [comment]
```
<?php Block::put('breadcrumb') ?>
    <ul>
        <li><a href="<?= Backend::url('travis/quotes/collection') ?>">Collection</a></li>
        <li><?= e($this->pageTitle) ?></li>
    </ul>
<?php Block::endPut() ?>

<?= $this->reorderRender() ?>
```

**Comment by LukeTowers** [comment]
Odd, I'll have to give it a try on my local install when I get some time. What are you using for your custom sort_order column name?

**Comment by swt83** [comment]
I was using ``order_id``.  Like I said, in both cases using ``sort_order`` or ``order_id`` everything would work fine on making new records.  But the sorting would fail only in the ``order_id`` test.

**Comment by LukeTowers** [comment]
Ok, thanks for the info. I'll give it a test when I've got some spare time and see what I can find for you

**Comment by swt83** [comment]
Thanks!

**Comment by LukeTowers** [comment]
@swt83 I've found the issue, a hard coded reference to the `$record->sort_order` column in the ReorderController `_records.htm` partial. I've fixed it in https://github.com/octobercms/october/commit/13aef49ebbfd00c73b39286d13323bd777108ff1
Please pull the latest from dev to verify that this fix works for you.

**Comment by swt83** [comment]
Thanks!
