### ISSUE TITLE
Caching in partial onStart() method results in "Serialization of 'Closure' is not allowed" error

### ISSUE THREAD

**Issue by swt83** [octobercms/october#2464]
I am using the following code in a partial to load data and cache it:

```
function onStart()
{
    // cache forever
    $this['quotes'] = Cache::rememberForever('quotes', function()
    {
    	return Quote::orderBy('sort_order', 'asc')->get();
    });
}
```

##### Expected behavior
I'm expecting the returned data to be cached and usable in the partial.

##### Actual behavior
I get an error saying "Serialization of 'Closure' is not allowed".  The solution is to add ``->toArray()`` to the Eloquent class, at which point the caching works just fine.  

I've never encountered this error in Laravel before when caching stuff, so I'm not sure if it is an error to October or not.  Maybe this is normal behavior.

##### October build
376

**Comment by daftspunk** [comment]
Pretty sure this fails in Laravel too, the caching class was simplified to no longer allow this (apparantley the serialization of closures was broken). The current workaround with `toArray` is the recommended solution. Caching should only ever handle data, not logic like closures.

**Comment by swt83** [comment]
The reason it's a problem is because the models include functions that I need in the views.  If I can't cache the database responses, then I am hitting the database every page load.
