### ISSUE TITLE
DataTable event on new rows

### ISSUE THREAD

**Issue by mbaxter91288** [octobercms/october#2466]
Hi,

I've had a situation where I'd like to load the media library from within a table field. Currently I added my own script to loop through all the table rows to add in a button, I then styled the button to fit into the table (similar look to the general 'mediafinder' field).

When adding and removing rows I needed to rerun my script as it seems the table is rebuilt each time. I found the `oc.tableNewRow` event in the code, but the table is rebuilt after this event is triggered. This meant that I couldn't add my 'mediafinder' buttons in. I couldn't find any other event that may help.

For the moment I've added the below to `modules/backend/widgets/table/assets/js/build-min.js` line: 238 (which I obviously do not want to keep ;-) )
```
this.$el.trigger('oc.tableAfterRebuild',[recordData])}
```

Would it be possible to add an event into the core like the above, or perhaps a better solution, create a 'mediafinder' processor perhaps?

Not great at js myself otherwise I would create a PR to try and achieve this.

Feedback would be great, thanks.

**Comment by daftspunk** [comment]
Feel free to create a demo plugin that demonstrates what you want, then publish it somewhere. From here someone should be able to help with it.

**Comment by LukeTowers** [comment]
@mbaxter91288 is this still an issue for you?

**Comment by mbaxter91288** [comment]
@LukeTowers I never got round to creating demo plugin like suggested then completely forgot, sorry. I haven't needed it again personally so, but might be useful to implement at some point. nothing urgent though. Close for now and if I get time in the coming week I may re-open

**Comment by ImadUllah** [comment]
Data-table on data-request-update
`data-request-update="'{{ __SELF__ }}::usertickets': '#usertickets'"` 
it update the partial (having table) but it hides the Data-table, kindly look at the matter.
