### ISSUE TITLE
OctoberCMS NetworkError: 406 Not Acceptable

### ISSUE THREAD

**Issue by mittultechnobrave** [octobercms/october#2478]
I am using OctoberCMS latest version and i have installed Flexi contact plugin https://octobercms.com/index.php/plugin/laminsanneh-flexicontact and i have configured contact form.

But whenever i press **Submit** button, i m keep getting an error message in console saying 
>>NetworkError: 406 Not Acceptable 

However, plugin works fine.. This happens to one of the themes which OctoberCMS provides as well .. So i guess its common issue ..

Can someone guide me how to solve this ? 

Thanks

**Comment by daftspunk** [comment]
AJAX handlers will often [send error 406 Not Acceptable](https://github.com/octobercms/library/blob/master/src/Foundation/Exception/Handler.php#L86-L88). Perhaps the error is not being caught properly.  Either way you should follow this up with the plugin author, instead of the core october repo.
