### ISSUE TITLE
Will there be any support for LetsEncrypt SSL

### ISSUE THREAD

**Issue by bkrajendra** [octobercms/october#2480]
LetsEncrypt https://letsencrypt.org/ offers free ssl certificate for webservers.
Mostly this becomes too complicated on shared server.
I've resolved some issues by changing .htaccess file
```
RewriteRule "^.well-known/acme-challenge" - [L]
# add before White listed folders and files
``` 

Will there be any automation related to LetsEncrypt be added in Octobercms.?
Is it possible to update certificate through PHP or admin interface.?

**Comment by daftspunk** [comment]
This has been added in 0bcf8f47c16e4df2bace24e76b822713c62108cf

Regarding a UI to create and renew certificates, sounds like a great idea for a plugin.

**Comment by bkrajendra** [comment]
@daftspunk 
Ive create a simple GUI for managing Let's Encrypt Certificates
Plugin can be downloaded from here:
http://octobercms.com/plugin/iocare-letsencrypt

Its very simple but eases the process of certificate request. Further I would like to create a cron job process URL so that this can be generated frequently and checked for certificates validity.

I guess this will help many people who are using Let's Encrypt SSL.
