### ISSUE TITLE
Recent fix on the Pages plugin breaks Froala rich editor from loading properly

### ISSUE THREAD

**Issue by manuelbua** [octobercms/october#2484]
##### Expected behavior
The Froala rich editor should load fine.

##### Actual behavior
An error occurs when loading a page: `pages-snippets.js:22 Uncaught TypeError: richeditor.isCodeViewActive is not a function(…)`

##### Reproduce steps
Click on a page within the Pages plugin, the Froala rich editor should load fine.

##### October build
OctoberCMS `build 381`
Pages plugin `build 1.2.12`

[This](https://github.com/rainlab/pages-plugin/commit/a8c66bc048c6be6b1c8edca14d39a70af49970cd) recent commit fixing recursion on saving a page with snippets in code view introduces a bug where the Froala editor can't be loaded due to a missing `isCodeViewActive` function declaration in the `richeditor.js`.

I'm working on a pull request and i'll submit it as soon as i can test the code: since the Froala editor is protected by DRM, i'm going to manually inject a minified patch into my `build-min.js` to ensure it's working fine on my local copy.

**Comment by manuelbua** [comment]
I sent the [pull request](https://github.com/octobercms/october/pull/2485), it looks it's working fine to me!

**Comment by daftspunk** [comment]
Addressed by #2485
