### ISSUE TITLE
customViewPath not work!

### ISSUE THREAD

**Issue by slipgrom** [octobercms/october#2488]
In config_list.yaml customViewPath not work.

I change Lists.php render function to 

    public function render()
    {
        $this->prepareVars();
        return $this->makePartial($this->customViewPath ? $this->customViewPath : 'list-container');
    }

**Comment by daftspunk** [comment]
Works fine over here. Maybe you use it wrong.  

```
# Custom view path
customViewPath: $/october/test/controllers/reviews/list
```

As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by daftspunk** [comment]
This is described in detail in the documentation:
https://octobercms.com/docs/backend/lists#overriding-views

To override the list container:

> you may override by creating a special file named _list_container.htm in your controller directory.

**Comment by daftspunk** [comment]
Added this to the docs:


For example, to modify the list body row markup, create a file called `list/_list_body_row.htm` in your controller directory.

    <tr>
        <?php foreach ($columns as $key => $column): ?>
            <td><?= $this->getColumnValue($record, $column) ?></td>
        <?php endforeach ?>
    </tr>

So you would need to create a file called `list/_list-container.htm` for this.

**Comment by devalexandre** [comment]
I create it, and not work if not input in list folder work

**Comment by LukeTowers** [comment]
@devalexandre 
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.
