### ISSUE TITLE
Media manager ignoring touch devices

### ISSUE THREAD

**Issue by daftspunk** [octobercms/october#2490]
This issue is a summary and continuation of Bug #1951 first reported on 22nd April 2016.

##### Expected behavior

Using a "touch laptop" with mouse and touch screen; the media manager should respond to touch events. Selecting an item should select it, as it does in mouse only environment.

##### Actual behavior

Touch events are ignored, items cannot be selected.

##### Set up

1. Open Chrome and go to `chrome://flags`
2. Find the setting "Enable touch events" and select "Enabled"
3. Restart Chrome as prompted

##### Reproduce steps

1. Click "Media" in the back-end navigation
1. Ensure some files are uploaded and folders exist, if not, create them
1. "Touch" on any file (selection fails)
1. "Touch" on a folder (selection fails)
1. "Double touch" on any item (folder opens successfully)

##### Pack down

1. Reverse steps in "Set up".

##### October build

Build 381+

##### Notes

- Simulation using Chrome device emulation -- eg: iPad (1024x768) -- does not appear to produce the same results. The `chrome://flags` approach must be used.

**Comment by Sennevds** [comment]
Any updates on this issue?

**Comment by alekseybobkov** [comment]
I implemented the fix in e3d864e, but can only test it in Chrome - I don't have a touch laptop. Let me know if it didn't work.

**Comment by Sennevds** [comment]
I have tested it on a touch laptop on:
- Chrome version 55.0.2883.87 m (64-bit)
- IE Version 11.576.14393.0
- Microsoft Edge 38.14393.0.0
- FireFox 50.1.0

October version 382 an can confirm that touch and click are both working

**Comment by daftspunk** [comment]
Thanks. This fix is now available in [Build 392](https://github.com/octobercms/october/releases/tag/v1.0.392).
