### ISSUE TITLE
Create API (Web Service) in OctoberCMS

### ISSUE THREAD

**Issue by mittultechnobrave** [octobercms/october#2493]
I am new to OctoberCMS and i found it very good CMS indeed.

I am creating 2 projects in my local server. One is in Cakephp (http://localhost/5p_group/) and the other is in OctoberCMS (http://localhost/5p_front/) .

I am using [Static Pages](https://octobercms.com/index.php/plugin/rainlab-pages) plugin in my OctoberCMS project (http://localhost/5p_front/) and i have created header and footer menus using **Static Pages Plugin** in it which works fine in my October Project at front end as i am able to display header and footer menus respectively. 

I have also created my own plugin using [builder plugin](http://octobercms.com/plugin/rainlab-builder) and i am also able to display data in my OctoberCMS front end. 

But now my requirement is to get the header, footer menus and also to get data of my plugin to my Cakephp project http://localhost/5p_group/ 

I want to get the data of both (Header footer menus and My plugin data which stored in my database table).

So i wanted to know is OctoberCMS provides any ability to create apis or webservices in OctoberCMS and ability to call it in my Cakephp project using `CURL` or something like this http://localhost/5p_front/getHeaderMenu, http://localhost/5p_front/getFooterMenu,   http://localhost/5p_front/getPluginData and give response either in JSON or XML ? 

 
Any help or suggestions will be highly appreciated.

Thanks

**Comment by riuson** [comment]
Yes, its possible.
You can create plugin, add file 'routes.php' on root of plugin's directory. Then write route handlers like [Laravel](https://laravel.com/docs/5.1/routing).

**Comment by mittultechnobrave** [comment]
so i have to create plugin ? is there any other way to create routes.php instead of creating a plugin ?

**Comment by mittultechnobrave** [comment]
and additionally, where should i (in which folder) i need to create my 'routes.php' file ?

**Comment by riuson** [comment]
> so i have to create plugin ?

It is just a way to isolate your source code from OctoberCMS.

> and additionally, where should i (in which folder) i need to create my 'routes.php' file ? 

In the root of plugin's directory. Near 'Plugin.php' file.

**Comment by mittultechnobrave** [comment]
ok cool .. let me check and will get back to you if any issue or any question .. thanks ...

**Comment by riuson** [comment]
Look at https://octobercms.com/forum/post/routesphp-in-plugin

**Comment by mittultechnobrave** [comment]
yes i am able to see response ... static response as of now .. but my question is .. i have created 2 menus using static pages plugin.. so how can i get those menu lists ? header and footer that is

**Comment by riuson** [comment]
I suppose, you can create [StaticMenu](https://github.com/rainlab/pages-plugin/blob/master/components/StaticMenu.php) instance, initialize it with right parameters.
I am not sure about styles, but content of menu can be available.

**Comment by mittultechnobrave** [comment]
ok i will check this and will get back to you on this .. thanks

**Comment by mittultechnobrave** [comment]
i have opened this page .. i have 2 menu items 'header-menu' and 'footer-menu' now my question is how to get those menus using this link which you provided https://github.com/rainlab/pages-plugin/blob/master/components/StaticMenu.php .. m bit confused in this page

**Comment by riuson** [comment]
Look at code in `public function menuItems()`:
```
$theme = Theme::getActiveTheme();
$menu = PagesMenu::loadCached($theme, $menuCode);
if ($menu) {
    $this->menuItems = $menu->generateReferences($this->page);
}
```

**Comment by mittultechnobrave** [comment]
ok this what i have done so far 

```
use Cms\Classes\ComponentBase;
use RainLab\Pages\Classes\Router;
use Cms\Classes\Theme;
use Request;
use RainLab\Pages\Classes\Menu as PagesMenu;


Route::get('/getHeaderMenu', function () {

    $menuCode = 'header-menu';
    $theme = Theme::getActiveTheme();
    $menu = PagesMenu::loadCached($theme, $menuCode);
    if ($menu) {
        $this->menuItems = $menu->generateReferences($this->page);

        echo '<pre>';
        print_r($this->menuItems);
        exit;
    }
});
```

And when i execute my api like this http://localhost/5p_front/getHeaderMenu 

I m keep getting an error saying 

>>ErrorException in routes.php line 8:
The use statement with non-compound name 'Request' has no effect

what should i do in this ?

**Comment by mittultechnobrave** [comment]
Ok guys .. eventually i have got the menu list using below code .. if anybody stuck or searching the same, then they call use or check this code snippet.

```
/* Code to get menu item starts */ 
use Cms\Classes\ComponentBase;
use RainLab\Pages\Classes\Router;
use Cms\Classes\Theme;
use RainLab\Pages\Classes\Menu as PagesMenu;
/* Code to get menu item ends */ 


Route::post('/getHeaderMenu', function () {


    $menuCode = 'main-menu'; // menu code 
    $theme = Theme::getActiveTheme();


    $menu = PagesMenu::loadCached($theme, $menuCode);

    $header_menu_list = array();
    if ($menu) 
    {
        $menu_list = $menu->attributes['items'];
        if($menu_list)
        {
            $i=0;
            foreach ($menu_list as $current_menu_list) 
            {

                if($current_menu_list->reference == '')
                {
                    $current_menu_list->reference = "#";
                }
                $header_menu_list[$i] = array(
                                            'title'=>$current_menu_list->title,
                                            'url'=>$current_menu_list->reference,
                                        );

                $header_menu_list[$i]['submenu_list'] = array();

                
                if($current_menu_list->items)
                {

                    $sub_menu_list = $current_menu_list->items;
                    foreach ($sub_menu_list as $current_submenu_list) 
                    {
                        if($current_submenu_list->reference == '')
                        {
                            $current_submenu_list->reference = "#";
                        }


                        $header_menu_list[$i]['submenu_list'][] = array(
                                                                'title'=>$current_submenu_list->title,
                                                                'url'=>$current_submenu_list->reference,
                                                            );    
                    }
                    
                }
                $i++;
            }
        }
        
    }    
    return $header_menu_list;

});
```


And to get data records of table from particular plugin, we can code something like this 

```
use technobrave\sociallinks\Models\Pluginmodel;

Route::post('/getSocialLinks', function () {
    
    $social_links_data = Pluginmodel::all();
    
    $arr = array();
    foreach($social_links_data as $current_social_links_data)
    {    	
    	$arr[] = array(
    			'id'=> $current_social_links_data['id'],
    			'social_logo'=> $current_social_links_data->social_logo->getPath()
    			);
    }
    return $arr;
});
```


Hope this helps and thanks for your support guys.

Highly Appreciated.
