### ISSUE TITLE
[feature-request] only start session when necessary

### ISSUE THREAD

**Issue by zerkms** [octobercms/october#2494]
At the moment the session is started for basically every frontend request, even for the sites that don't use it in any way.

So what if we start it only when it really necessary?

Not sure whether this should target laravel or october though, in the simplest case octobercms may just carry its own implementation of the `StartSession` middleware.

**Comment by daftspunk** [comment]
This has come up before, it was an issue in Laravel too last time we looked at it. There was talk of a plugin that introduces a "Start session" checkbox on CMS pages that instructs the page to use sessions or not.

**Comment by zerkms** [comment]
> There was talk of a plugin that introduces a "Start session" checkbox on CMS pages that instructs the page to use sessions or not.

It sounds ugly :-S

**Comment by LukeTowers** [comment]
This is now the default behaviour in Laravel 5.5 (OctoberCMS Build 420+). You now have to manually add the `web` middleware to request handling in order to start session handling.
