### ISSUE TITLE
Filtering form fields in a relation manage form

### ISSUE THREAD

**Issue by alxy** [octobercms/october#2495]
##### Expected behavior
The ``filterFields()`` method is called when the specified ``dependsOn`` field changes AND when the form first loads, as per [docs](http://octobercms.com/docs/backend/forms#filter-form-fields).

##### Actual behavior
The method is only called, when the dependency field changes, but _NOT_ on the initial form load.

##### Reproduce steps
- Create a Model and a Related
- Implement the ``Backend.Behaviors.RelationController`` behavior and configure it as usual. In my case, I am using a ``hasMany`` relation.
- Create a field that ``dependsOn`` another field and implement the ``filterFields()`` in your Model
- Simply fill that method with ``$fields->field_name->hidden = false;`` to display it. It wont display until you actually change the field specified by ``dependsOn``. In my case I am using a dropdown field input.

##### October build
380

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by LukeTowers** [comment]
@alxy Any plans to add the requested PR to the test plugin for further investigation?

**Comment by daftspunk** [comment]
Initial form load should `filterFields`, just need a test to prove otherwise.

**Comment by LukeTowers** [comment]
Closed due to lack of followup from @alxy
