### ISSUE TITLE
Error when attempting to save User model without any permissions set

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#2499]
##### Expected behavior
When a model based on /October/Rain/Auth/Models/User is saved (specifically via the relation controller linking a relationship) it should save correctly even if it doesn't have any permissions specified.

##### Actual behavior
When attempting to add a RainLab.User user model as a belongsTo relationship on a separate model (Appointment in this case), after selecting the User to link the record to an exception is thrown that
`Invalid argument supplied for foreach() on line 559 of vendor/october/rain/src/Auth/Models/User.php`. This refers to the `setPermissionsAttribute()` method on the base User model. The error occurs because the relation controller calls `Backend\Widgets\Form->setFormValues($model->attributes)` which itself calls `forceFill($data)` on the User model. However, when the `setPermissionsAttribute($permissions)` method is called, it assumes that `$permissions` is a valid JSON array which fails on the next line when it attempts to loop through the decoded `$permissions` variable. The problem is, when the user in question doesn't have any permissions set at all (which is the case by default with the RainLab.User User model), the method receives `NULL` as its parameter, throwing the exception when it attempts to loop through `NULL`

##### October build
october/rain dev-master 7325e01

**Comment by daftspunk** [comment]
Fixed by https://github.com/octobercms/library/pull/245
