### ISSUE TITLE
Error when saving pages if theres <iframe>

### ISSUE THREAD

**Issue by nyxzryu** [octobercms/october#2514]
Steps

Hi, whenever i tried to create new or editing the partial page that already exist, if i put <iframe></iframe>, i cant save the file. What i got is error that come like via ajax (see screenshot :  http://imgur.com/a/WDl71 ). 

But when i delete the <iframe> tag, it works fine. 

##### October build
318.

#### Themes : 
Octaskin

**Comment by daftspunk** [comment]
This might have something to do with [known error 1](https://octobercms.com/support/article/ke-1). Which hosting provider are you with?

**Comment by nyxzryu** [comment]
I'm using name.com hosting. So any chance of fixing these or bypass this error ? I really need this iframe to work .-.

**Comment by nyxzryu** [comment]
Also this error comes up when trying to save Layout page. Even i just opened the octaskin layout and resave without modifying anything .-.

**Comment by Eoler** [comment]
You need to contact your hosting provider and tell them to disable mod_security rules...

**Comment by nyxzryu** [comment]
So by disabling the mod_sec ?
Okay i'll try contact them, will report back here asap :v

**Comment by nyxzryu** [comment]
Already contacted namecheap and got ModSec disabled. the <form> syntax is working now, but <iframe> still wont. Also when opening layout, demo layout, still cant saved, same error .-.

**Comment by nyxzryu** [comment]
Already FIXED the error :)
Thanks for @Eoler for pointing me up. What i did is, contact the hosting provider and engage in live chat. Ask for ModSec to be disabled, then asking to whitelist rule for HTML elements that are blocked.
