### ISSUE TITLE
Plugin versions less than 1 are skipped.

### ISSUE THREAD

**Issue by ARH-Digital** [octobercms/october#2516]
##### Expected behavior
During development of a plugin, version 1 is typically the first release with version numbers of 0.x.x being used during development and 1.x.x being the first stable version.
Thus running an 'october:up' or 'plugin:refresh' should install as per normal.

##### Actual behavior
During an 'october:up' or 'plugin:refresh' anything less than 1.x.x is skipped.

##### Reproduce steps
Attempt to install any plugin with a version number of 0.x.x and any migrations within these versions are skipped.

##### October build
All.

**Comment by scottbedard** [comment]
@ARH-Digital I've not been experiencing this problem, my plugin seems to install just fine.

https://github.com/scottbedard/oc-shop-plugin/blob/master/updates/version.yaml

**Comment by jBOKA** [comment]
I can remember that kind of problem with the migrations. I moved to start with 1.x also...

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
