### ISSUE TITLE
Backend user session cookie can be used to gain access, even if user has logged out

### ISSUE THREAD

**Issue by arikw** [octobercms/october#2521]
I logged out from a logged-in backend user account and expected that if the user's cookie, prior to the logout, is somehow available, it will be unusable for making authenticated calls.
I've noticed that I can get logged in again, using the old cookie data.

I would expect that for security reasons the old cookie data would be useless, if the user has logged out.

**Comment by daftspunk** [comment]
Had assumed this was the behavior all along, apparently not. Thanks for pointing this out!
