### ISSUE TITLE
persist_code in backend_users table, isn't recreated

### ISSUE THREAD

**Issue by arikw** [octobercms/october#2522]
I've changed the "persist_code" to NULL for a user's entry in the "backend_users" table, to deal with the situation I've described in issue #2521
Then I went on and logged in that user, and I've noticed that "persist_code" isn't recreated.

Steps:
1. log in user X
2. NULL the "persist_code" field on "backend_users"
3. log out user X
4. log in user X
"persist_code" field stays NULL

System build: 365

**Comment by daftspunk** [comment]
That doesn't sound right, perhaps you have set the persist code to the string "NULL" instead of emptying the database value.

**Comment by arikw** [comment]
I've set the field to NULL and made sure it's not a string.

**Comment by daftspunk** [comment]
I wasn't able to replicate this. Try updating to the latest build of October Build 382 to see if anything changes.

**Comment by daftspunk** [comment]
Fixed by #2521
