### ISSUE TITLE
since build #382 toArray() exception

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#2523]
##### Expected behavior

in a model class, certifications represent a belongToMany relationship

````php
$this->certifications->toArray()
````
expect to return an array as it used to work

##### Actual behavior
return an error exception
````php
exception 'ErrorException' with message 'json_decode() expects parameter 1 to be string, array given' in /site/vendor/october/rain/src/Database/Model.php:1436
````

##### October build
382

**Comment by daftspunk** [comment]
Is it possible that you have `certifications` defined as a `$jsonable` property? Note that an attribute should either be a relation or jsonable, but not both.

**Comment by chrisvidal** [comment]
Thanks @daftspunk 
after checking, the attributes 'certifications' is not in the $jsonable and is only in the 
````php 
public $hasMany = []
````

**Comment by daftspunk** [comment]
Ok, it was a stab in the dark. Would you mind providing your parent and certifications model, also the code that is calling `toArray()` so we can get more visibility across your implementation.

**Comment by daftspunk** [comment]
NB: Wasn't able to replicate this using [the test plugin](https://github.com/daftspunk/oc-test-plugin).

```
October\Test\Models\Post::first()->comments->toArray();
```

**Comment by LukeTowers** [comment]
This is a complex case. Please submit a Pull Request to [the test plugin](https://github.com/daftspunk/oc-test-plugin) for investigation that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it using the test plugin.

**Comment by chrisvidal** [comment]
the error is still there on the backend -now even in the display of a simple list on the backend.
when trying to display a list in the backend
```php
exception 'ErrorException' with message 'json_decode() expects parameter 1 to be string, array given' in /Users/toto/Sites/xxx.yyy/site/vendor/october/rain/src/Database/Model.php:1436
```

**Comment by LukeTowers** [comment]
You're going to have to provide more information on how exactly to replicate the issue. Please submit a PR to [the test plugin](https://github.com/daftspunk/oc-test-plugin) for further investigation demonstrating the issue.

**Comment by chrisvidal** [comment]
ok i have more info, i think i know where it is coming from.
My model is extending a modelbehavior that work through some complicated stuff, taht basically allow to have custom field using a jsonable attribute in the model.
And in the constructor of the model behavior, i transform the json into an array, this is what the model.php is getting during the display of the list.
basically the construc code of the model behavior is like this
````php
class SerializableModel extends ModelBehavior
public function __construct($model)
    {
        parent::__construct($model);

        $jsonable = $this->model->getJsonable();

        foreach ($this->model->serializable as $json_field => $serializable_fields) {
            array_push($jsonable, $json_field);
            array_push($this->serializableKeys, $json_field);
        }

        $this->model->jsonable($jsonable); /* the guilty line */

        $this->model->bindEvent('model.afterFetch', [$this, 'afterModelFetch']);
        $this->model->bindEvent('model.saveInternal', [$this, 'saveModelInternal']);
        $this->model->bindEvent('model.beforeSave', [$this, 'beforeModelSave']);
    }
}
````

So how could i detect the context so this code does not run while in the backend display of a list of this model ?

**Comment by chrisvidal** [comment]
i have the issue as well on a simple, basically all the hasMany relations have the issue for my model Company but it seems to depend on the instance of Company, hence depending on the relations collection itself, i need to investigate further more
````php
$this->awards->toArray();
$this->licenses->toArray()
````

**Comment by daftspunk** [comment]
Feel free to log another issue with clean/simple instructions for us to follow and we can take another look. Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty
