### ISSUE TITLE
if i add some .md file content to the blog plugin, some error happend.

### ISSUE THREAD

**Issue by Honvid** [octobercms/october#2525]
##### Expected behavior
it's going ok for the .md file content.

##### Actual behavior
for example, if i add this [.md](https://github.com/octobercms/docs/blob/master/setup-configuration.md) file to the blog. 

there happend going wrong. 
screenshots:

![22 pic_hd](https://cloud.githubusercontent.com/assets/8649968/20752974/09ee6dc0-b73f-11e6-8f05-9a430ab20279.jpg)
![23 pic_hd](https://cloud.githubusercontent.com/assets/8649968/20753020/42d84458-b73f-11e6-9fd1-4405933db2a2.jpg)

##### October build
Blog version  1.2.14
October CMS version is clone from the new one in this.
PHP 7

t

**Comment by daftspunk** [comment]
Not exactly sure where the problem is here. I have copied the content from this file:

https://raw.githubusercontent.com/octobercms/docs/master/setup-configuration.md

In to a blog post and it loads fine?

**Comment by LukeTowers** [comment]
Closed due to lack of follow up from @Honvid
