### ISSUE TITLE
Enhancement: support of twig import feature

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#2526]
##### Expected behavior
support of twig import feature would be nice

##### Actual behavior
no current support apparently

**Comment by daftspunk** [comment]
This requires more detail. Please provide an example of how you would use this, preferably with support as to why its needed.

**Comment by chrisvidal** [comment]
An example of why it is needed would be simply to reuse defined macros.
In different partials for example, i need to display or scramble data depending on different access right of the current user. 

Instead of defining (copying) the macro in every partials, i could define it in a separate partial and import it using the twig import feature.

**Comment by daftspunk** [comment]
Example/prototype code?

**Comment by daftspunk** [comment]
Please provide some example / prototype code on how someone might use this. This will be used for documentation if the feature is implemented.

**Comment by chrisvidal** [comment]
let me know pleae if this is enough :

this is a twig macro that could be defined in a partial named _macros.htm
````twig
{% macro displayField(label, value) %}
    {% if value %}
    <span class="label">{{ label }}</span><span class="value">{{ value }}</span>
    {% endif %}
{% endmacro %}
````

in all partials, we could import the _macros.htm partials to be used in a theme or in a components:
````twig
{% import '_macros.htm' as _siteMacros %}

{{ _siteMacros.displayField("Estimated Value", project.estimated_value) }}
{{ _siteMacros.displayField("Actual Value", project.value) }}
````

**Comment by oadslug** [comment]
+1 on this. I would love to see full support for Twig, including 'include', 'import', etc. This would allow front-end templates to be built independent of the CMS, and for sharing twig libraries (i.e. form macros) between CMS apps (we use multiple CMS systems depending on client). For our needs this is a deal-breaker in terms of using October to deliver the front-end.  As a result, we have been using October strictly for content management (which it is great for!), and building the front-end using a completely separate Laravel app that bypasses October entirely.

**Comment by daftspunk** [comment]
This will be available in Build 388+ and [documentation can be found here](https://github.com/octobercms/docs/blob/72336222a9ad2fa47f629d5efa48a9cc8a3cd7ae/markup-tag-macro.md).
