### ISSUE TITLE
OctoberCMS strange issue in Users Groups Management (Manage Administrators) section

### ISSUE THREAD

**Issue by mittultechnobrave** [octobercms/october#2530]
I am having strange issue in **OctoberCMS** in Administrators --> Manage Groups section. 

I have created **two** different users (One is **admin user** and the other is **developer user**) and i have created **two** roles (groups) based on it. **Administrator** role(group) having few permissions to access wherease **Developer** role(group) having full permission to access the things which i have checked.

In **Manage Groups** section under **Administrator** role, we have a **CMS** section and i have checked only below two items out of that section.

 - Activate, deactivate and configure CMS themes
 - Upload and manage media contents - images, videos, sounds, documents

Then i logged in as an **admin** user who is having **Administrator** role(group) and in my local server i am unable to see **CMS** tab after i logged in through which admin can add CMS pages and stuff like that as i have not given a permission to do so which is fine and works well.

However, the thing is i have a live server as well and i followed the same things (created roles(groups),users and assigned those groups) to those users but still the strange thing is, i am able to see **CMS** tab and when i click on it, i m not able to see any left sidebar which is good.

But the thing is why am i able to see this page? it should work fine like it does in my **local server**. 

I have checked twice about the **permissions** which i have given on **live server**, it is same as **local server** so there is no issue on this but still i am able to access the page and instead it should tell me **ACCESS DENIED** like it does in my **local server**.

FYI, in my live server, on **Dashboard** page, under **SYSTEM STATUS**, it is saying **Some issues need attention** and when i click on it, its saying this, 

>System configuration tips

>There are issues you need to pay attention to in order to configure the system properly.

 >- The PHP extension fileinfo is not installed. Please install this library and activate the extension.

 >- The PHP extension Zip is not installed. Please install this library and activate the extension.

Does this cause **this** issue? is **this** the issue causing my system to behave in this fashion? 

Can someone guide me what is an issue here ?

**Comment by daftspunk** [comment]
The permissions are pulled from the database so it shouldn't really make much difference. Make sure both environments are set up to be identical. My guess is that they are not.

**Comment by mittultechnobrave** [comment]
How can i check they are identical or not ? i mean i have checked the things same for both the servers and yet i m able to executd CMS page on live server whereas on local server its not happening .. how can i check the differenciation ?

**Comment by daftspunk** [comment]
You could export the database from one and import it to the other.

**Comment by mittultechnobrave** [comment]
@daftspunk  well i still cant understand the theory.. why should i export and import ? as i just want to make it work on live server which is already working in local server... and i m following the steps to achieve this..

**Comment by daftspunk** [comment]
Sorry I can't be of much more help. It is difficult to follow what you are saying. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Comment by LukeTowers** [comment]
Closed due to lack of followup from @mittultechnobrave
