### ISSUE TITLE
List widget: Tree nodes are not expanded for models that have other than id primary key

### ISSUE THREAD

**Issue by ukebako** [octobercms/october#2532]
##### Expected behavior
Expand nodes when click on 'plus' button.
Model has defined method getKey() which returns proper value

##### Actual behavior
Nodes are not expanded, because node_id is not set in data-request-data.

Here is the code of modules/backend/widgets/lists/partials/_list_body_tree.htm
```html
<a
...
data-request-data="node_id: '<?= $record->id ?>', status: <?= $expanded ? 1 : 0 ?>">
```

I think `<?= $record->id ?>` should be changed to `<?= $record->getKey() ?>`

**Comment by daftspunk** [comment]
This should be fixed in Build 389+ (b85c4f9b7b9467fe82b3c0d7d5841d75fe92e2f2)
