### ISSUE TITLE
Not being able to manipulate the partials before they render

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#2533]
##### Expected behavior
Being able to manipulate the partials before they render.

##### Actual behavior
There is no event available. 

##### Reproduce steps
Read the content of the partial and then manipulate it before render.

##### October build
382

Should be fixed by:
https://github.com/octobercms/october/pull/2519

**Comment by daftspunk** [comment]
Waiting on results from #2519

**Comment by daftspunk** [comment]
Events have been added that match the renderContent events. Note you can read the content of any partial using the afterFetch event

```
Partial::extend(function($partial) {
    $partial->bindEvent('model.afterFetch', function() { /*...*/ });
});
```

Then to check if the app is running in the front-end, call the `App::runningInBackend()` method.
