### ISSUE TITLE
Allowing a back-end user to manage all users except super users

### ISSUE THREAD

**Issue by meysammahfouzi** [octobercms/october#2536]
##### Expected behavior
I've granted a backend user permission to manage backend users. But I do not want him to be able to see or manage super users. I also do not want to allow him to create new super users.

##### Actual behavior
Currently anyone with backend user permission can add/remove super users.

##### October build
380

**Comment by leocavalcante** [comment]
I hope this helps: https://octobercms.com/plugin/leocavalcante-backendusertree
Feel free to report any issues: https://github.com/leocavalcante/oc-backendusertree

**Comment by daftspunk** [comment]
This could be fixed as part of #2367

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/fa840d79f6cbd054830d0f4e345bf024da9f18a7

**Comment by leocavalcante** [comment]
Awesome news
