### ISSUE TITLE
I need to update composer.json

### ISSUE THREAD

**Issue by Hatalias** [octobercms/october#2540]
I have a problem, I need to update composer.json to install this "Maatwebsite / Laravel-Excel" library. Can someone help me

> "require": {
        "php": ">=5.5.9",
        "composer/installers": "~1.0",
        "maatwebsite/excel": "~2.0"
    },
    "minimum-stability": "dev"

**Comment by LukeTowers** [comment]
Create a `composer.json` for your plugin including that library, and then run `composer update` from your base project directory. See https://github.com/octobercms/october/issues/1714 for more info.

As a note, GitHub issues are for reporting issues with the project, please use the official forums, stackoverflow, IRC, or Slack to get assistance with problems like this.

**Comment by Hatalias** [comment]
Hello.
Thanks for the help, I would not have installed the packeges by composer.phar.
I put it in the json file and tried to execute the "october: up".
After installing the autoload it worked.

Thank you very much!
