### ISSUE TITLE
Fileupload field crashing browser when many large images are reordered via drag-and-drop

### ISSUE THREAD

**Issue by oadslug** [octobercms/october#2541]
##### Expected behavior
Multiple images in the fileupload field (when using attachMany) should be resized as thumbnails.

##### Actual behavior
Multiple images in the fileupload field (when using attachMany) are loaded at full resolution (even though displayed as thumbnail). This is causing the browser to crash when reordering lot's of very large images (not to mention load very slowly).

##### Use case
I am using a fileupload field to upload product gallery images. On the front-end the images are dynamically resized (via php library) to display at various sizes (including full screen), and thus need to be quite large (i.e. 50 images x 500-1000k each).

##### Reproduce steps
Create a fileupload field using attachMany; upload 50 or so large image (1MB each should do it). Then try drag-reorder — even if the the browser doesn't crash you will notice the browser really struggling.

##### October build
339

**Comment by oadslug** [comment]
Just a thought. I don't think that a 'thumbnail_image' column needs to be defined in the 'system_files' table or anything. There are php plugins that can resize images on the fly using defined transform parameters, and cache results, etc. I'm not sure what image resize library October is using. We are using [League Glide](http://glide.thephpleague.com) on the front-end for example.

**Comment by jBOKA** [comment]
October's attachOne/Many file model already comes with on the fly resizing, caching included. You can use that resizing also on the frontend with `getThumb`. No need for 3rd party for resizing. 

When configuring the form fields yaml, you can even set `imageHeight` and `imageWidth`. Did you try that?

**Comment by oadslug** [comment]
@jBOKA I assumed that the imageHeight imageWidth determined the stored image size (in other words, the original would not be available to the front-end), and not just the size of the displayed thumbnail. Of course I could be wrong - I'll do some tests and double check.

(As far as front-end images, we are bypassing October entirely on the front-end for various reasons (no twig support for import, include, macros, etc), thus we needed our own image manipulation system. We opted for Glide for simplicity.)

**Comment by oadslug** [comment]
The original files are available! Awesome. And it processes images when the edit form is rendered, not just on upload (so the client doesn't have to re-upload images for them to crop properly). I should have tested this. Thank you for pointing this out. Much appreciated!
