### ISSUE TITLE
Javascript error with fileUpload/relationList fields using drag-to-reorder

### ISSUE THREAD

**Issue by oadslug** [octobercms/october#2543]
##### Expected behavior
Should be able to drag-reorder images within a fileUpload field.

##### Actual behavior
When there is a fileUpload field and relationList on the same form, drag-to-reorder images is throwing a javascript error, preventing images from being reordered.

<img width="838" alt="screen shot 2016-12-07 at 11 34 08 am" src="https://cloud.githubusercontent.com/assets/8769174/20984257/59aae566-bc74-11e6-8740-66459a483d5c.png">

##### Reproduce steps
Add relationList. Add fileUpload field. Upload images. Try drag-reorder images.

##### October build
Build 338 (however, also appeared in Build 339 — I just updated hoping that the issue had been fixed).

**Comment by oadslug** [comment]
Before you spend any time on this... I may have found the culprit. I will close this for now and report back.

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by oadslug** [comment]
The problem was a result of custom javascript being injected into the relationList using `relationExtendViewWidget` that conflicted with an October jquery extension of the same name. `jquery-ui.sortable` vs` jquery-sortable.js` I aliased jquery-ui and it worked fine.

Sorry for the alarm. Thanks again!
