### ISSUE TITLE
Large File Upload to S3

### ISSUE THREAD

**Issue by nikalailk** [octobercms/october#2546]
##### Expected behavior
upload video file(file size>200M) to S3

##### Actual behavior
I have updated the php.ini already:
post_max_size = 500M
upload_max_filesize = 500M
max_input_time = 3000
max_execution_time = 3000
memory_limit = 4096M

when i try to upload a file(file size=200M),
error shown: october-min.js?v382:145 net::ERR_CONNECTION_ABORTED

I'm using the latest version of OctoberCMS

**Comment by nikalailk** [comment]
https://youtu.be/Tp5nc4JiNSg
above is the video I record when I uploading
It works when only uploading .jpg which smaller than 7xM

**Comment by daftspunk** [comment]
Video shows upload progresses to about 50% then reverses down to 10% a couple of times., then throws an "Error uploading file" error. It would suggest that the uploader is retrying a couple of times before failing.

This needs to be peer reviewed. Ideally we need to find out at what point the server-side code is failing.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
