### ISSUE TITLE
Test fails on HalcyonModelTest

### ISSUE THREAD

**Issue by lethiandev** [octobercms/october#2547]
##### Expected behavior
PHPUnit tests should run flawless, both on a local machine and a Docker (via Bitbucket Pipelines CI).

##### Actual behavior
Test fails on HalcyonModelTest, on the local machine and the Docker. The `phpunit` output:
```
1) HalcyonModelTest::testPageQueryListFileName
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'about.htm'
-    1 => 'home.htm'
+    0 => 'home.htm'
+    1 => 'about.htm'
 )

/opt/atlassian/pipelines/agent/build/vendor/october/rain/tests/Halcyon/ModelTest.php:331
```
##### Reproduce steps
* Create October project by composer `composer create-project ...`
* Install libraries with the composer using `composer install --dev`
* Run tests `vendor/bin/phpunit`
* Only one test fail \**magic sparkles*\*

##### October build
97b0bc481f948045f96a420bb54ab48628bfdddc

##### Notes
My OS: Ubuntu 16.04.1

To fix this problem only on the local machine, i modify the file `<project_root>/vendor/october/rain/tests/Halcyon/ModelTest.php:331`, as below:
from
331 `$this->assertEquals(['about.htm', 'home.htm'], $files);`
to
331 `$this->assertEquals(['home.htm', 'about.htm'], $files);`

**Comment by daftspunk** [comment]
Hopefully [this should fix it](https://github.com/octobercms/library/commit/6fb81250f710b911c37f4706a7be5c15c2409ac1).
