### ISSUE TITLE
Any plan to support backend controller behaviors in front-end?

### ISSUE THREAD

**Issue by meysammahfouzi** [octobercms/october#2551]
The `Form`, `List` and `Relation` controller behaviors in backend pages are very great features which make model management extremely easy. I wonder though, why these fantastic behaviors are not available in the front-end side? The only helpers currently are the `Record details` and `Record list` components provided by the `builder` plugin which are, as far as I know, only suitable for listing and showing simple models. Are they meant to be used for more complicated model relations as well? If not, is there any plan to provide such behaviors as `Form`, `List` and `Relation` to the front-end?

**Comment by daftspunk** [comment]
Yes, I think eventually the component coupled with Builder will be moved to a "Backpack" style plugin that brings a suite of useful components.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
