### ISSUE TITLE
Add create:theme scaffolding command

### ISSUE THREAD

**Issue by darylteo** [octobercms/october#2552]
EDit: Title previously mentioned scaffolding for Plugins, which already exists.

##### Expected behavior
````
php artisan theme:create # could be create:theme
php artisan plugin:create # already exists as create:plugin
````

 - creates appropriate folder structures in themes or plugins as required
 - puts ".gitkeep" files so that the folder structures can be immediately git committed
 - may support user input to configure theme.yaml and plugin.yaml

Even if this request is rejected, can we at minimum consider adding .gitkeep to the plugin/theme directories when created through the backend? This will allow me to quickly scaffold out a empty theme/plugin, commit, then pulled by my developers for them to work on immediately without worrying about the directory structure. Having this in CLI will allow me to automate parts of this quicker.

##### Actual behavior
None - feature request

##### Reproduce steps
None

##### October build
(October build number)

**Comment by Shantarli** [comment]
Plugin scaffolding already available
https://octobercms.com/docs/console/scaffolding#scaffold-create-plugin

**Comment by darylteo** [comment]
Thanks @Shantarli. 

None for Themes though (I couldn't see one for Theme so assumed there wasn't one for Plugins, my bad).

**Comment by SaifurRahmanMohsin** [comment]
You can generate a theme using the Backend. Login to backend, go to Settings -> CMS -> Front-end theme -> Create a new blank theme. I think adding a create:theme feature would only be redundant. Themes can be easily developed in the backend using CMS section and only plugins are developed from text editors so it makes sense to have a scaffolding command for it.

<img width="1142" alt="screen shot 2016-12-15 at 02 48 48" src="https://cloud.githubusercontent.com/assets/1699753/21201461/0ccf2876-c271-11e6-8c18-04b610258f07.png">

**Comment by darylteo** [comment]
I can't automate if it's not in console command.

Anyway if that's the call I'll just create the structure myself manually.

Thanks anyway.

**Comment by daftspunk** [comment]
Should be easy enough. Someone feel free to submit a PR for a `create:theme` console command.
