### ISSUE TITLE
Multilingual fields from Translate plugin stopped working

### ISSUE THREAD

**Issue by Eoler** [octobercms/october#2554]
After upgrading to latest edge build 389 backend localizations (multilingual form fields replacement, placeholders and variables in static Pages plugin) stopped working. It probably have to do something with rewritten event emitting in the core.

##### Expected behavior
Language indicators with dropdown switching behavior shown on translatable model fields and page variables/placeholders.

##### Actual behavior
They are completeley missing.

##### Reproduce steps
Have two active languages defined in Settings/Translate/Manage Langauges.

##### October build
389 edge, Translate plugin 1.2.7, Pages plugin 1.2.13

**Comment by Kunilt** [comment]
+1

**Comment by CptMeatball** [comment]
I can confirm this problem exists. :(

**Comment by Eoler** [comment]
Fixed in Translate plugin 1.2.8, thanks.
