### ISSUE TITLE
Route Testing using PHPUnit

### ISSUE THREAD

**Issue by hiyahin** [octobercms/october#2555]
##### Expected behavior & Actual Behavior
Using PHPUnit to do route testing on my plugin (using a routes.php file in my plugin), I was expecting a basic route call to return 200. Instead, I get 500 because I needed to change the theme. Even after setting the theme, I get a 404. The page is reachable using a browser.

##### Reproduce steps
1. Created a phpunit.xml file at plugin root directory using the same configuration found here:
https://octobercms.com/docs/help/unit-testing
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="../../../tests/bootstrap.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false"
         syntaxCheck="false"
>
    <testsuites>
        <testsuite name="Plugin Unit Test Suite">
            <directory>./tests</directory>
        </testsuite>
    </testsuites>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
    </php>
</phpunit>
```
2. Created test case in the `tests` folder in my plugin folder
```
<?php
class UserTest extends PluginTestCase {
  function routeTest(){
    Config::set('cms.activeTheme', 'demo');
    $response = $this->call('GET', '/api/users');
    $this->assertResponseOk();
  }
}
```
3. Create `routes.php` in my plugin folder.
```
<?php
Route::group(['prefix' => 'api'], function () {
    Route::get('users', array('as'=> 'users', 'uses' => 'OnionCreative\TaikooGo\Controllers\Users@get'));
```
4. Using Terminal run `cd /path/to/plugin && phpunit`

##### October build
v1.0.389

**Comment by hiyahin** [comment]
On top of this, a lot of the unit testing does not take into account of the variables set in `phpunit.xml`. I would suggest the `/tests/PluginTestCase.php` to respect these variables and add those database configs back into the `/config/testing/database.php`.

**Comment by Herlevsen** [comment]
I have the same problem

**Comment by joelamltc** [comment]
Same here.

**Comment by mberizzo** [comment]
Same here! but if I run that specific test (phpunit --filter=routeTest) or delete the others tests, I get green.

**Comment by daftspunk** [comment]
This is a *moderately* complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by fuzzybaird** [comment]
Is there a solve for this? It'd be good to tests routes inside of plugins.

**Comment by joelamltc** [comment]
Use this instead,
```
$this->action(
    $http_method, 
    $handler, 
    $slug_param, 
    $parameters
);
``` 
Example,
```
$response = $this->action(
    'GET',
    'HomeController@index',
    [],
    [
        'token' => $random_string
    ]
);

 $response_json = json_decode($response->getContent(), true);
```
**$response_json** is your feedback data.

**Comment by fuzzybaird** [comment]
@joelamltc I am sorry but that did not work for me. @daftspunk I have posted a pull request, to demonstrate an example test I have set up.
`https://github.com/daftspunk/oc-test-plugin/pull/38`

**Comment by joelamltc** [comment]
@fuzzybaird 
How is your cms.php inside config/testing
I commented out `// 'pluginsPathLocal' => base_path('tests/fixtures/plugins'),` this line in order to make it works.
And ` $response_json[0]['username'] should contain 'test'`

**Comment by fuzzybaird** [comment]
@joelamltc Thanks for the recommended base path change in the config/testing. I did know about that config, but I was assuming inheriting the `PluginTestCase` was supposed to take care of those configs.

tests/PluginTestCase.php
```php
        /*
         * Modify the plugin path away from the test context
         */
        $app->setPluginsPath(realpath(base_path().Config::get('cms.pluginsPath')));
```

As far as the `$response_json[0]['username'] should contain 'test'`; yes you could be more specific but my current test `$this->assertTrue((bool)$response_json);` simply asserts that the json is in the response.

**Comment by daftspunk** [comment]
Fixed by https://github.com/daftspunk/oc-test-plugin/pull/38

**Comment by scottbedard** [comment]
For anyone who comes across this, the above PR is now at https://github.com/octoberrain/test-plugin/pull/38
