### ISSUE TITLE
Add "has-error" to Bootstrap form elements on Ajax error

### ISSUE THREAD

**Issue by jaycbrf4** [octobercms/october#2556]
The new validation for forms is great however there is no easy way to add the Bootstrap "has-error" class for inputs when there is a validation error.

**Comment by daftspunk** [comment]
Check the [global AJAX events](http://octobercms.com/docs/ajax/javascript-api#global-events) on how you can introduce this functionality with JavaScript.

```
$(window).on('ajaxInvalidField', function(event, fieldElement, fieldName, errorMsg, isFirst) {
    $(fieldElement).addClass('has-error');
});
```

$(document).on('ajaxPromise', '[data-request]', function() {
    $('.has-error').removeClass('has-error');
});

/cc @dshoreman

**Comment by jaycbrf4** [comment]
Thank you very much @daftspunk . That was exactly what I needed. Would be a nice feature to be built into the CMS.
