### ISSUE TITLE
Runaway system_request_log table.

### ISSUE THREAD

**Issue by heathdutton** [octobercms/october#2557]
##### Expected behavior
system_request_log table should have some limits, like a monthly rotation or something. We have many other ways to log errors and count them so for us this table is just superfluous overhead, so perhaps we should have a way (by configuration & environment variable) to configure a limit or disable this feature.

##### Actual behavior
The table (in our case) blew up exponentially after a brief DDoS attack. Blocking the attack didn't renew service because the system_request_log table had hundreds of simultaneous queries trying to get (and increase) the count of the 404 errors on favicon.ico (and similar). This created a complete MySQL gridlock. I couldn't truncate the table due to the lock and had to create a new one matching the schema and swap it out.

##### Reproduce steps
Have about 500 users on the site at once, each one producing an error to be logged to this table. Starting with a table over 8m rows thanks to a a DDoS attack. Yea... not the most likely scenario, but there is is :)

##### October build
~v1.0.389

**Comment by LukeTowers** [comment]
This is a good point to bring up; as a rule of thumb I dislike logging requests to a DB. Causes too many headaches dealing with high traffic combined with misconfigured services or DDOS attacks. Having some configuration options available for changing the default behaviour for logging failed requests would be nice. 

As a note (and temporary fix), you can 
```php
define('OCTOBER_NO_EVENT_LOGGING', 1);
```
to short circuit the `System\Models\EventLog` class from actually logging anything until we have better configuration options implemented.

**Comment by heathdutton** [comment]
Thanks, I didn't notice that constant. 👍

**Comment by adrenth** [comment]
Also, it would be very nice to configure which level events will be logged (e.g. debug, info, warning, error, critial, etc.).

**Comment by daftspunk** [comment]
This has been addressed in 462c9cd4e822cb9193a0b4f89f66a82a126fb53d / Available in Build 398+

There is now a "Log settings" area where logs can be switched on or off. Also, request logging is now disabled by default as this does pose a problem for spam.
