### ISSUE TITLE
Validation 'required' doesn't work on relationController with hasMany

### ISSUE THREAD

**Issue by jBOKA** [octobercms/october#2558]
##### Expected behavior
When `Parent` `hasMany` `Child` models, it should be possible to set `children` to be required and when using `RelationController` to create the parent and the children in one form.

##### Actual behavior
Upon creation of the parent, some children are created by the user with a deferred binding (I suppose) in the RelationController. When trying to save (children are present in the form), the validation fails and says that *children are required*. 

##### Reproduce steps
https://github.com/jBOKA/oc-deferredbindingvalidationtest-plugin
Install plugin, try to create parent.

##### October build
382

PS: It is also not possible to have the inverse relation set to `required`, because then even creation of the children fails the validation.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
