### ISSUE TITLE
Setting relationRender to read only makes toolbar buttons disappear

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#2559]
##### Expected behavior
Make relation popup only view shoud not remove the toolbar buttons like link and unlink.

##### Actual behavior
If you set a relationRender to read only, all the toolbar buttons disappear. 

##### Reproduce steps
 - Make a partial to render in form
 - <?= $this->relationRender('relation', ['readOnly' => true]) ?>

##### October build 
382

**Comment by SebastiaanKloos** [comment]
<?= $this->relationRenderView() ?> does the same thing so it does not fix the problem.

**Comment by daftspunk** [comment]
This doesn't make sense. Link and unlink are not available with `readOnly`. In other words, read only means nothing can change, including linking and unlinking.

**Comment by SebastiaanKloos** [comment]
@daftspunk It would be really nice to just link and unlink relations without the option to edit the relations fields. I guess it is not possible in the current system then. 

I will try to make the logic by myself.

**Comment by daftspunk** [comment]
Ah, so you only want the "manage" widget to be read only, but the "view" widget can still be editable? Might be able to find a way to do this...

This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by kealsera** [comment]
Any news on this issue? I'd really like to be able to edit pivotdata without giving the option of changing the relations

**Comment by LukeTowers** [comment]
@kealsera That sounds like it's beyond the scope of the relationcontroller, you may need to implement such functionality yourself.

**Comment by daftspunk** [comment]
We can reopen this once a PR is submitted to the test plugin for review.
