### ISSUE TITLE
Ability to create many-tomany polymorphic relations

### ISSUE THREAD

**Issue by poniatowski** [octobercms/october#2561]
Hi!

I've been working with October CMS from couple months and I've had so many situation when I've need to use polymorphic relations in admin module that I decided to mention about it here. My colleagues are struggling with same issues. Is it possible in near future to create this polymorphic relations by programmers of October CMS? That can really helps with our job. I'll be appreciated for any information regarding to this topic.

Regards,
Poniatowski

**Comment by daftspunk** [comment]
Can you submit your scenario to the test plugin then we can implement the support for it, or give advice on how to do it.

This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by LukeTowers** [comment]
@poniatowski Did #2275 fix your issues?

**Comment by daftspunk** [comment]
If #2275 doesn't fix it, then [OB-21](http://octobercms.com/support/article/ob-21) can!

**Comment by poniatowski** [comment]
If that's has been sorted out, why there's not documentation to it on the October CMS doc?

https://octobercms.com/docs/backend/relations

How to use it? Similar to many to many behavior?

**Comment by daftspunk** [comment]
@poniatowski Your comment suggests that you may  not have watched the screencast. It is an approach that is currently documented.

**Comment by poniatowski** [comment]
@daftspunk Hi not to worry.

However, I still see last relation which is described in doc is 'Has one' and there is still not '$morphedToMany'. Please, let me know if I'm bind? :)
https://github.com/octobercms/docs/blob/master/backend-relations.md#relation-display

**Comment by LukeTowers** [comment]
@poniatowski You're not blind, it's not on there. @daftspunk was hinting that you should make a PR to the docs repository to add it to the documentation :)

**Comment by MWalid** [comment]
Any hint how to configure `morphMany` relation?

Still can't use it.

**Comment by LukeTowers** [comment]
@MWalid please don't hijack unrelated issues for questions: https://octobercms.com/docs/database/relations#one-to-many-polymorphic-relations
