### ISSUE TITLE
Bug in ListController filters. Filter group skip options with integer key `0`.

### ISSUE THREAD

**Issue by Arekusei** [octobercms/october#2563]
https://github.com/octobercms/october/blob/master/modules/backend/widgets/Filter.php#L738
Comparison(provided by link above) broke filters where `id` is `0`
```php
        foreach ($options as $option) {
            if (!$id = array_get($option, 'id')) {
                continue;
            }
            $processed[$id] = array_get($option, 'name');
        }
```
My available filter values:
```php
    const TYPE_CURRENT = 0;
    const TYPE_PREVIOUS = 1;
    public function getTypeOptions()
    {
        return [
            self::TYPE_CURRENT => 'Default type',
            self::TYPE_PREVIOUS => 'Previous type',
        ];
    }
```
If we check type `Previous type` it's work normal, but if we check `Default type` ~~condition~~ filter not applied.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
