### ISSUE TITLE
OctoberCMS Get plugin's Dropdown values at frontend

### ISSUE THREAD

**Issue by mittultechnobrave** [octobercms/october#2564]
I have created one plugin (call it **Product**) using [Builder Plugin](http://octobercms.com/plugin/rainlab-builder) and inside it, i have a dropdown (call it **product_category** (Product Category)) 

Using **Builder Plugin**, i have added few **Key => Value** (Dropdown Category options) like below.

**Added Dropdown Options**:

[![enter image description here][1]][1]

**Showing Dropdown Options**: 

[![enter image description here][2]][2]

Now i have one **CMS page** (call it **products**) which i am showing in front end, and in which i am showing the list of the products, which works fine using the code like below.

[![enter image description here][3]][3]

  [1]: https://i.stack.imgur.com/fwKfs.png
  [2]: https://i.stack.imgur.com/AUQrz.png
  [3]: https://i.stack.imgur.com/jyHzw.png

Now here comes my question/query, i have a **Product Category Dropdown** in front end as well in a same page and i want to get all the Product Categories which i have added using my Builder Plugin. 

How can i get those ?

**Comment by mittultechnobrave** [comment]
is it not possible ?

**Comment by mittultechnobrave** [comment]
Ok guys, eventually i have found out a solution thanks to [alxy](http://octobercms.com/forum/user/alxy)'s help though and here what i have come up with. 

    $parser = new October\Rain\Parse\Yaml;
    $fields = $parser->ParseFile('/path/to/fields.yaml');
    
    var_dump($fields);

Go [here](http://octobercms.com/forum/post/octobercms-get-plugins-dropdown-values-at-frontend) for more. 

Thank you

**Comment by daftspunk** [comment]
Thanks for the follow up
