### ISSUE TITLE
Can't call "trans()" function on the views (Twig)

### ISSUE THREAD

**Issue by ab192130** [octobercms/october#2568]
##### Expected behavior
I've decided to make texts _**inside views**_ translatable with plugin lang files. So, when I use 
**{{ trans("acme.demo::lang.string.example") }}**, I'm expecting translated string value on the actual view.

##### Actual behavior
But I encounter with "**Unknown trans() function.**" exception instead. Testing "trans()" inside _Models_ or _Components_ is working without any issues.  

##### October build
My current **October build** is: **382**.

**Comment by jBOKA** [comment]
`trans` is only available in PHP. Check out the underscore twig filter from the translate plugin. There are different ways to provide translations. Maybe read up on it first https://octobercms.com/plugin/rainlab-translate

**Comment by LukeTowers** [comment]
As a side note, while you can add a reference to `Lang::get()` (which is effectively the implementation of `trans()` as a twig function / filter to accomplish what you desire, there is one issue with doing it that way. It's going to use your backend language settings on a frontend view; that's not going to have your intended results.

Like @jBOKA said, look into frontend translation via RainLab.Translate.

**Comment by ab192130** [comment]
Thank you so much! It's more clear for me now :) 
I'll try the twig filter of RainLab.Translate as fast as possible.

**Comment by daftspunk** [comment]
`|trans` is a filter in the system

```
{{ "acme.demo::lang.string.example"|trans }}
```
