### ISSUE TITLE
No backend style after instalation

### ISSUE THREAD

**Issue by Eduguimar** [octobercms/october#257]
Hello devs, I would be gratefull if someone can help me (sry about my english)  
My frontend and backend doesn't load the style (assets).  
My mod_rewrite is enabled, I changed to "AllowOverride All" in my virtual host and I uncommented the "RewriteBase / " in my .htaccess.october.  
I need to put /index.php in the end of url to see the frontend style and /index.php/backend to access the backend.  
The problem is that my backend has no frontend(no style) at all, it's like the "http://myexample.dev" without /index.php.

**Comment by FCHAPLIN** [comment]
I'm on EasyPHP Windows 7, october backend can't load any assets. I tried every fix listed here with no success. This is still an issue. Any clue ?
