### ISSUE TITLE
Performance improvement: Create a compiled PHP class map file

### ISSUE THREAD

**Issue by carlosdubus** [octobercms/october#2571]
Hi! this is more a question and not an issue, I'm trying to optimize a website that is running slowly.

According to xhprof, 25% of the time is spent inside this function:

October\Rain\Support\ClassLoader::load

I see that's the Class autoloader. I printed out the classes that it loads during the script and I tried requiring them manually in index.php before the request dispatcher is run. My idea was to create a preloader, so October\Rain\Support\ClassLoader::load is never called.

But I ran into dependencies issues, for example a file that calls:

`use Model;`

Will not work requiring it from index.php because seems like the alias Model is still not created at that point.

Can you recommend where can I add this preloader so all aliases like 'Model' are already loaded?

Also, is my attempt to optimize this function not the right path to speed up the site? Every request takes around 2 seconds. So we are talking about 0.5 second improvement which seems significant.
Thanks!

**Comment by daftspunk** [comment]
You mean compile a file that contains a map to all known classes? It's a great idea and we will implement it eventually. Not sure about the `Model` issue.

**Comment by LukeTowers** [comment]
This should no longer be required as we have switched to requiring PHP7. Previously this would be handled by `php artisan optimize`, however Laravel has officially removed that command as of Laravel 5.5 because of the performance improvements in PHP7. https://laravel-news.com/laravel-5-6-removes-artisan-optimize
