### ISSUE TITLE
Rich Editor custom html tag attributes

### ISSUE THREAD

**Issue by matthew-inamdar** [octobercms/october#2576]
##### Expected behavior
Being able to define and use custom html attributes within the code view of the Rich Editor.

*We can define custom tags in the backend but not custom attributes - Froala editor already supports custom attributes: https://www.froala.com/wysiwyg-editor/v1.2/docs/options#allowedAttrs*

##### Actual behavior
No way to define custom attributes, and the editor automatically strips them out.

##### Reproduce steps
Go into code view of the editor, add a custom attribute. In my case I want to use a Vue.js attribute:
`<div v-if="display"></div>`
Then press save.

##### October build
v1.0.389

**Comment by NickMChambers** [comment]
Could we please have the inlineStyle plugin and option enabled and integrated into the build?

https://www.froala.com/wysiwyg-editor/examples/inline-styles

This should allow the toolbar to be more configurable.

**Comment by LukeTowers** [comment]
@NickMChambers feel free to implement that as a PR.

**Comment by NickMChambers** [comment]
It actually the BlockStyles plugin that we need integrating.

https://www.froala.com/wysiwyg-editor/v1.2/docs/examples/block-styles

**Comment by daftspunk** [comment]
Block styles has been replaced with Paragraph styles, which is integrated currently.

**Comment by iamike** [comment]
I am also a fan of Vuejs, please let me know if there is an update can fix this.

**Comment by LukeTowers** [comment]
In theory you should be able to extend Froala in JS before it gets initialized and set the necessary values. In theory anyways.

Here's an example of some code I use to switch the default emoji mode to using the unicode characters instead of the CDN provided SVG images:
```js
+function ($) { "use strict";
    $(document).render(function() {
        if ($.FroalaEditor) {
            $.FroalaEditor.DEFAULTS = $.extend($.FroalaEditor.DEFAULTS, {
                emoticonsUseImage: false
            });
        }        
    })
}(window.jQuery);
```

Try playing around with something like that to set the necessary options to define your custom attributes.

**Comment by daftspunk** [comment]
We could just fix it with a PR too? Not opposed to any of these technologies, am opposed to something hindering its use.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
