### ISSUE TITLE
Fetaure Request - Alt text on images in media Library

### ISSUE THREAD

**Issue by ARH-Digital** [octobercms/october#2578]
As the title states.

Images are stored in the media library. I would like to be able to assign alt text to the images within the Media Library to be able to pull through on all the pages that image is used on, rather than having to go through all pages and components to find and update alt tag text

**Comment by LukeTowers** [comment]
This is an interesting problem, because images in the media library are stored simply as files within a directory without any associated metadata. Any ideas on how to go about adding this feature to core?

It might be feasible as a plugin that stores metadata records associated to media files, extends the media library manager, and then provides twig methods for accessing / utilizing that data.

**Comment by ARH-Digital** [comment]
That is not a bad idea Luke. I might have to look into an implmentation like that. 
I had also considered the possibility of using something like http://www.sno.phy.queensu.ca/~phil/exiftool/ to read and write the metadata directly into the images, though this is probably less practical than the suggested method, however it then does not require the database to link data to specific files. 

Will have to give this some more thought.

**Comment by daftspunk** [comment]
This should be a plugin for now, if the implementation is useful we can merge it in to the core.

**Comment by ARH-Digital** [comment]
@daftspunk What is the best method to extend a widget? Obviously the Media Manager in this case.

**Comment by daftspunk** [comment]
Using Events in most cases: http://octobercms.com/docs/services/events

**Comment by alxy** [comment]
The problem in this case is that the [Repeater widget](https://github.com/octobercms/october/blob/master/modules/cms/widgets/MediaManager.php) does not use events at all. Even the rename popup for example is static HTML markup and no (extendable) Form widget.

**Comment by daftspunk** [comment]
@alxy, agreed this is not ideal. However there are [view events we can use](http://octobercms.com/docs/plugin/extending#backend-view-events) to overcome this.

**Comment by ChadStrat** [comment]
I as well have a project need for meta data on images via media manager.  Pretty important feature.

**Comment by LukeTowers** [comment]
@ChadStrat Media Library item support for metadata is a feature that I plan on working on in October, ping me again if you haven't heard anything by the end of October.

**Comment by thegirlinthecafe** [comment]
Ping :-) Has this been implemented yet? As we are also desperately waiting for a solution for this.

**Comment by munxar** [comment]
@thegirlinthecafe as a poor mans solution until the full version is up, you could use the rainlab translate plugin and reuse the file name with a pre- or postfix for your 'metadata'. then just translate the path names with your meta data.
twig example:
```html
<img src="{{ 'images/cat.jpg'|media }}" alt="{{ 'images/cat.jpg'|_  }}" title="{{ ('images/cat.jpg' ~ '_title')|_ }}">
```
note: the path could be a variable

**Comment by LukeTowers** [comment]
Thanks @munxar for the workaround. @thegirlinthecafe I'd love to start working on all the MediaManager improvements, just very busy right now. There was someone that was going to sponsor the improvements if they landed a particular client project, but it's not looking like that's going to happen at this point so it will have to get done by balancing it with other (paying) client work.

**Comment by gmonte** [comment]
Don't forget this feature please!!!
