### ISSUE TITLE
Theme layout variables limit

### ISSUE THREAD

**Issue by robinbonnes** [octobercms/october#2579]
##### Expected behavior
When I add variables in my theme layout like this:

`{variable tab="Header" type="mediafinder" mode="image" name="headerimage" label="The header image."}{/variable}`

It should create a new tab called 'Header' in the backend (on Pages), with the specified field. In this case, when I select an image at the specific page, it should show the image in the frontend when I call:

`{{ headerimage|media }}`

##### Actual behavior
The above works fine, **until 32 variables**. When I add more than 32 variables to a page layout, filling them at the page in the backend is no problem. However when I browse to my page in the frontend it gives me an error loading page:

![image](https://cloud.githubusercontent.com/assets/5117166/21449170/aef32f9c-c8ea-11e6-94da-825234a31dd5.png)

I can't find anything in the logs, but maybe it has something to do with caching? (I use the default: file).

##### Reproduce steps
Create a new theme layout with over 32 variables:

`{variable tab="Test 1" type="mediafinder" mode="image" name="test1" label="This is just a test."}{/variable}
            {variable tab="Test 1" type="textarea" name="test2" label="Variable type doesn't matter as far as I tested."}{/variable}`

etc.

Then assign the theme layout to a page and browse to it.

##### October build
382

P.S. The variables feature isn't documented in the docs yet. Placeholders is: http://octobercms.com/docs/markup/tag-placeholder

**Comment by LukeTowers** [comment]
Is this within the default October CMS static pages or the RainLab.Pages plugin?

**Comment by robinbonnes** [comment]
In the RainLab Pages plugin

**Comment by LukeTowers** [comment]
Just as a note, the variables feature is a feature of the RainLab.Pages plugin itself ([repository here](https://github.com/rainlab/pages-plugin)), so that's the reason it's not in the October documentation. It is mentioned in the plugin documentation however.

This issue would be best suited being reported on the [Pages plugin's repository](https://github.com/rainlab/pages-plugin) itself.

**Comment by LukeTowers** [comment]
@robinbonnes: I've moved this issue to rainlab/pages-plugin#223

**Comment by daftspunk** [comment]
See rainlab/pages-plugin#223
