### ISSUE TITLE
setProperties bug

### ISSUE THREAD

**Issue by Leadrive** [octobercms/october#2580]
modules\system\traits\PropertyContainer.php
Line from 53-61
<pre><code>
    /**
     * Sets multiple properties.
     * @param array $properties
     * @return array
     */
    public function setProperties($properties)
    {
        $this->properties = $this->validateProperties($properties);
    }
</code></pre>
##### Actual behavior
<pre><code>
        $this->properties = $this->validateProperties($properties);
</code></pre>

##### Expected behavior
<pre><code>
        return $this->properties = $this->validateProperties($properties);
</code></pre>

##### October build
(October build 382)

**Comment by LukeTowers** [comment]
Is this a behaviour that's reflected elsewhere in the codebase; returning the newly set value from the setter?

**Comment by Leadrive** [comment]
No, I don't think the setter need return value, but the code's note
<pre><code>* @return array</code></pre>
did not match the code.
@LukeTowers

**Comment by LukeTowers** [comment]
Odd. As a side note, the only two places in October (via quick search of octobercms/october) that actually use this trait seem to perform the function of `setProperties()` themselves. 
See the constructors of `Backend\Classes\ReportWidgetBase` and `Cms\Classes\ComponentBase` for the use of the code of this method without actually calling this method. Probably something to look into as general very low priority code cleanup. 

Thanks for pointing it out!
