### ISSUE TITLE
Save attach file name is unreadable code(文件名乱码)

### ISSUE THREAD

**Issue by Leadrive** [octobercms/october#2583]
##### Expected behavior
Media Library save attach file, file name is Chinese.

##### Actual behavior
In IE, if you save the media library file as a attch file, and the file name is Chinese, it will be unreadable code.

##### Reproduce steps
vendor/october/rain/src/Database/Attach/File.php
The originale code is(Line No.153)
<pre><code>    public function output($disposition = 'inline')
    {
        header("Content-type: ".$this->getContentType());
        header('Content-Disposition: '.$disposition.'; filename="'.$this->file_name.'"');</code></pre>
If the $this->file_name is Chinese text, In IE, it will be unreadable code, and the Chrome is OK.
I modify the code as follow, it will work ok, please check it.
<pre><code>    public function output($disposition = 'inline')
    {
        $realname = iconv("UTF-8", "gbk//ignore", $this->file_name);
        if (!$realname) { //convert fail(转换失败)
            $realname = mb_convert_encoding($this->file_name, "gbk", "UTF-8"); //此方法转出来，每个字带_
        }
        header("Content-type: ".$this->getContentType());
        header('Content-Disposition: '.$disposition.'; filename="'.$realname.'"');</code></pre>

##### October build
(October build 382)

**Comment by LukeTowers** [comment]
Please submit a PR with the fix and a unit test to prevent it from breaking again.

**Comment by w20k** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
