### ISSUE TITLE
No option to use filter in relation manager

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#2587]
##### Expected behavior
Option to use filter in relation manager.

##### Actual behavior
No option to use a filter in the relation manager.

##### Reproduce steps
-

##### October build
Latest build

**Comment by LukeTowers** [comment]
This isn't a bug / issue. If you would like this feature to be added to the project, then please put more effort into your request. Tag it as such via including `[featureRequest]` in the title, and add more detailed information about what you would like. Better yet, start working on adding the feature in yourself or pay someone to implement it for you.

Simply opening an issue for requests such as this is not helpful and wastes maintainers time as they have to filter through 'issues' like this which takes time away from dealing with actual project issues.
