### ISSUE TITLE
[But report]Send email, from name or to name is unreadable if it is Chinese(收件人或发件人为中文时乱码)

### ISSUE THREAD

**Issue by Leadrive** [octobercms/october#2589]
##### Expected behavior
(Describe expected behavior here)

##### Actual behavior
In the send email service, if the from name or to name is Chinese, the mail's from name or to name will be unreadable character.

\vendor\october\rain\src\Mail\Mailer.php, add these code:
<pre><code>
    static public function mime_header_encode($string) {
        return "=?UTF-8?B?" . base64_encode($string) . "?=";
    }
    /**
     * Build a formatted e-mail address.
     */
    static public function formatAddress($mail, $name, $encode = TRUE) 
    {
        $name = trim($name);

        // Do not format addres on Windows based PHP systems or when $name is empty.
        return (/*(substr(PHP_OS, 0, 3) == 'WIN') || */empty($name)) ? $mail : '"'. ($encode ? Self::mime_header_encode($name) : $name) .'"';// <'. $mail .'>';
    }
</code></pre>
the function
    public function sendTo($recipients, $view, array $data = [], $callback = null, $queue = false)
<pre><code>
    public function sendTo($recipients, $view, array $data = [], $callback = null, $queue = false)
    {
        if (is_bool($callback))
            $queue = $callback;

        $method = $queue === true ? 'queue' : 'send';
        $recipients = $this->processRecipients($recipients);

        return $this->{$method}($view, $data, function($message) use ($recipients, $callback) {
            foreach ($recipients as $address => $name) {
//==========  add this code here =============
                $name = Self::formatAddress($address, $name);
//========== end add ====================
                $message->to($address, $name);
            }

            if (is_callable($callback)) {
                $callback($message);
            }
        });
    }
</code></pre>
\vendor\october\rain\src\Mail\MailServiceProvider.php
<pre><code>
            if (is_array($from) && isset($from['address'])) {
//==========  add this code here =============
                $from['name'] = Mailer::formatAddress($from['address'], $from['name']);
//========== end add ====================
                $mailer->alwaysFrom($from['address'], $from['name']);
            }
</code></pre>

Also, the subject need:
<pre><code>
$subject = Mailer::mime_header_encode($subject);
</code></pre>
##### Reproduce steps
(Describe the steps to reproduce the problem here)

##### October build
(October build 382)

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
