### ISSUE TITLE
Remove Themes from Projects

### ISSUE THREAD

**Issue by Annobimps** [octobercms/october#2591]
##### Expected behavior
Theme Removed

##### Actual behavior
Theme not removed

##### Reproduce steps
Add a theme to a project, 
Install said theme, 
Remove theme from local CMS.
Run update plugins in local CMS
Removed theme is included in update. 
No option in update window to selectively install/update plugin. 
All plugins in update must be installed.

##### October build
Build 382

**Comment by Annobimps** [comment]
Hello thanks for a Great CMS only one issue I have: 
Seems there is no way to remove a theme from a Project unlike a plugin..
Zoom Slider Theme when installed crashes the cms.. backend pages wont work anymore. 
Please add a remove option for themes similar to plugins or give us an option when adding plugins to select desired plugin to install. 
Currently we are forced to install all plugins that appear in an update.

Thanks and keep up the good work.

**Comment by LukeTowers** [comment]
@Annobimps If you want to prevent a plugin from updating, then go to the plugin management page (/backend/system/updates/manage) and click on the plugin you want to stop updates for; then click on "Enable or Disable" and then click the "Freeze Updates" box and click the "Apply" button to save your changes. That will stop you from being forced to install updates for that plugin along with everything else at the same time.

As far as removing themes from projects goes, you'd have to make a post on the forums asking for @daftspunk to implement that as a feature, the OctoberCMS website isn't a part of this repository and afaik at the moment there's no way to disassociate a theme from a project.

**Comment by Annobimps** [comment]
Hello Luke,

Thank you for your reply.. 

ATB,

 

JR

**Comment by daftspunk** [comment]
This feature is planned.

**Comment by Annobimps** [comment]
Brilliant. Thank You Samuel and thanks to you all for a great product.

Jay
