### ISSUE TITLE
Plugin test can't boot up boot method

### ISSUE THREAD

**Issue by surahmans** [octobercms/october#2592]
##### Expected behavior
I want to test my plugin using `TestCase` instead of `PluginTestCase`. I add dynamic method using `addDynamicMethod` on plugin boot method, and hope it works by calling `$user->subscibe($plan)`

##### Actual behavior
I get this error:
```
1) Indovisual\Membership\Tests\Unit\SubscriptionTest::user_can_subrcribe_a_plan
BadMethodCallException: Call to undefined method October\Rain\Database\QueryBuilder::subscribe()
```

But when I adding the `subscribe` method directly to model it works.

##### Reproduce steps
Here's my code to extend the `User model`:
```
            $model->addDynamicMethod('subscribe', function($plan) use ($model) {
                if ($plan instanceof \Indovisual\Membership\Models\Plan) {
                    return $model->subscribes()->save($plan);
                }
            });
```

##### October build
v350

**Comment by daftspunk** [comment]
You may need to boot the plugin manually, or add the dynamic method as part of your tests.

**Comment by surahmans** [comment]
Thank you, @daftspunk for your great advice! 😄 

I digged into your awesome code and find helpful code to solve my case by adding `PluginManager::instance()->bootAll();` into `setUp` method. Now my tests code looks like;

```
<?php

use RainLab\User\Models\User;
use System\Classes\PluginManager;

class UserTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        PluginManager::instance()->bootAll();
    }

    public function test_call_dynamic_method()
    {
        $user = User::first();

        $this->assertEquals('Hello there!', $user->sayHi());
    }
}
```

**Comment by surahmans** [comment]
I'm sorry, @daftspunk. Why using `PluginManager::instance()->bootAll();` only work for adding dynamic method and it doesn't work for extending relation like this,

```php
            $model->belongsToMany['wishlists'] = [
                'Indovisual\Gallery\Models\Item',
                'table' => 'indovisual_gallery_wishlists'
            ];
```

I know we can add this code to make that work,

```php
    public function setUp()
    {
        parent::setUp();

        User::extend(function($model) {
            $model->belongsToMany['wishlists'] = [
                'Indovisual\Gallery\Models\Item',
                'table' => 'indovisual_gallery_wishlists'
            ];
        });
    }
```

But, Is there another way to make it work like "boot up" our plugins?

Thanks.

**Comment by daftspunk** [comment]
Not sure. You have shown some code that does work, need to see the code that *doesn't* work.

**Comment by surahmans** [comment]
Hi @daftspunk,

Here's my plugin boot code
```php
    public function boot()
    {

        User::extend(function($model) {
            $model->belongsToMany['wishlists'] = [
                'Indovisual\Gallery\Models\Item',
                'table' => 'indovisual_gallery_wishlists'
            ];
       });
    }
```
and my WishlistTest.php
```php
<?php

use RainLab\User\Models\User;
use Indovisual\Gallery\Models\Item;
use System\Classes\PluginManager;

use Illuminate\Foundation\Testing\DatabaseTransactions;

class WishlistTest extends TestCase
{
    use DatabaseTransactions;

    public function setUp()
    {
        parent::setUp();

        PluginManager::instance()->bootAll();
    }

    public function test_user_can_wishlist_photo()
    {
        $item = $this->createItem();
        $user = $this->createUser();

        $item->toggleWishlist($user);

        $this->assertEquals(1, $user->wishlists()->count());
    }

    public function test_user_can_unwishlist_photo()
    {
        $item = $this->createItem();
        $user = $this->createUser();

        $item->toggleWishlist($user);
        $item->toggleWishlist($user);

        $this->assertEquals(0, $user->wishlists()->count());
    }

    protected function createUser() 
    {
        return User::create([
            'email' => 'me@example.com',
            'password' => 'rahasia',
            'password_confirmation' => 'rahasia',
        ]);
    }

    protected function createItem()
    {
        $item = new Item;
        $item->name = 'example';
        $item->type = 'photo';
        $item->price_category_id = 1;
        $item->save();

        return $item;
    }
}
```

I feel strange when I run the `WishlistTest.php` without `test_user_can_unwishlist_photo` or when only one test method it works. But when there is two tests method which means `wishlist` and `unwishlist` test it doesn't work.

The error comes appear is 
```
1) WishlistTest::test_user_can_unwishlist_photo
BadMethodCallException: Call to undefined method October\Rain\Database\QueryBuilder::wishlists()
```

Thanks

**Comment by daftspunk** [comment]
Very interesting, I'm not sure why it should happen because for all intents and purposes the code is identical.

**Comment by daftspunk** [comment]
Found why this happens!

1. The database service provider wipes all the extended classes every cycle (`Model::clearExtendedClasses();`)
1. The PluginManager does not clear it's "booted" flag each cycle, so secondary `bootAll()` calls will not re-extend the class.

Added a `$force` flag to `bootAll` and `registerAll` to overcome this.

**Comment by daftspunk** [comment]
Once you receive this update (Build 398+) this code should be used instead:
```
PluginManager::instance()->bootAll(true);
```

**Comment by harmenjanssen** [comment]
Note that `bootAll(true)` might not be enough in some cases.   
If your plugin specifies a `config/config.php` file, you might also need:

```
PluginManager::instance()->registerAll(true);
```

This will gobble up all plugin configuration files.

Honestly it would be great if there was a way to just wrap all this in a single method.   
It's not that far-fetched to want to replicate a production environment in your unit tests I'd say and having to dig up these separate methods from dumped stack traces did not feel very productive.
