### ISSUE TITLE
Some assets not loading properly when october is installed in subdirectory

### ISSUE THREAD

**Issue by meysammahfouzi** [octobercms/october#2598]
I'v installed october in a subdir like http://example.com/october  
Everything seems to be working fine, except that some assets are not loading properly because they are loading from  `http://example.com` while they should be loaded from `http://example.com/october`. For example awesome fonts in the backend are not loaded correctly:

> http://example.com/modules/system/assets/ui/font/fontawesome-webfont.woff?v=1.0.1 

Also, calling `getAssetPath` in one of my form widgets is returning the path of the asset based on `http://example.com` and not `http://example.com/october`.

How can I solve this?

**Comment by daftspunk** [comment]
I can say the same thing (most of my installs are in subdirectories) and they are working fine. We need a bit more information. Is there anything unusual about your installation or environment? i.e Non standard config?

**Comment by meysammahfouzi** [comment]
@daftspunk No, I don't think I've done anything unusual. I've used the default installer to install the october instance.

**Comment by daftspunk** [comment]
Sorry - I am unable to replicate this.

**Comment by meysammahfouzi** [comment]
@daftspunk  I've got an instance of WordPress installed in the root directory. Could this be affecting the October's installation?

**Comment by daftspunk** [comment]
I don't think the code would interfere, however the web server configuration might be causing it.

**Comment by LukeTowers** [comment]
Closed due to lack of further information from @meysammahfouzi
