### ISSUE TITLE
[featureRequest] Add support for {% switch %} Twig tag from CraftCMS

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#2599]
Just putting this here for now so I can work on it at some point in the future.

I would really like for the `{% switch %}` Twig template tag to be added to OctoberCMS. It's not included in Twig by default, but CraftCMS has a [decent implementation](https://craftcms.com/docs/templating/switch) that we could borrow from.

**Comment by daftspunk** [comment]
We will follow @fabpot on this, see notes from https://github.com/twigphp/Twig/pull/185

> The goal is not to have the same syntax as PHP, but to provide a simple syntax for web designer. Simplicity also means that we need to provide only one way to do things, and the same can be easily accomplish with if statements (I would even say that ifs statements would be easier and more concise).
