### ISSUE TITLE
[featureRequest] Hotkey search field focus

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#2600]
##### Expected behavior
It would be very cool to have a hotkey to focus the search field in list partial.

I was thinking of cmd+b, ctrl+b.

**Comment by alxy** [comment]
This can be perfectly done by a plugin, so I don't think it needs to be in core.

**Comment by LukeTowers** [comment]
@alxy Can it? Can the default search input for lists be extended in that way by a plugin? I personally don't think it's a bad idea to have a hotkey for focusing search input in the core.

I don't have time to look into it right now, so it's best to leave it low priority but I don't mind leaving the issue open.

**Comment by SebastiaanKloos** [comment]
@LukeTowers I can add a shortkey in some Javascript file pointing to the search input field. If there is a way to include a JS from a plugin to all controllers, we can add this feature with a plugin. 

I'll make a PR for a core include.

**Comment by SebastiaanKloos** [comment]
@LukeTowers I build a plugin with a much nicer feature to search. It looks much like the Spotlight search overview of the Mac.

It is toggled with ctrl+space and is autofocused. Maybe I will add this plugin to the market place. If some people find this feature handy, I can add this to the core. 
![screen shot 2017-02-28 at 12 15 21](https://cloud.githubusercontent.com/assets/6506510/23403314/df2a23d8-fdaf-11e6-8523-5b87a7f55972.png)

**Comment by LukeTowers** [comment]
Certainly looks very interesting, let me know where I can get it; I'd love to check out the code :)

**Comment by alxy** [comment]
@LukeTowers It certainly is possible. The former BackendPlus plugin did the same thing, however it autofocused the search on page load.

**Comment by LukeTowers** [comment]
@alxy Good to know, I forgot about the JS API for hotkeys, was thinking just about the data attributes API.

I wouldn't mind seeing it in core though, beyond simply that it's possible to do through a plugin, what other thoughts do you have on the subject?

**Comment by SebastiaanKloos** [comment]
@LukeTowers I will try to add this functionality to the core. When it's ready, I'll make a PR

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
