### ISSUE TITLE
file name problem with media manager

### ISSUE THREAD

**Issue by hareluya** [octobercms/october#2603]
##### Expected behavior
1. upload a Chinese file name in media manager by click on the upload button.
2. upload a file which has the same name file already in the media manager.

##### Actual behavior
1. the file will missing the Chinese word part. but if I use the "featured image" in rainlab/blog plugin it can upload the Chinese name file.
2. The same name file will be replace by the new one.

##### Reproduce steps
1. Media->upload->upload Chinese name file.

[未命名.pptx](https://github.com/octobercms/october/files/695980/default.pptx)

2. use any same name file.

##### October build
1.0.391

**Comment by hareluya** [comment]
Would please help me out whether I can open some option that the media manager can auto generate the file name for the uploading files?

**Comment by itsam** [comment]
I confirm the same behaviour for greek filenames. I assume only latin filenames are allowed which is not very convenient. Thanks in advance

**Comment by LukeTowers** [comment]
@itsam Feel free to look into this yourself and provide a PR for a fix. Otherwise this will have to wait until we have time to look further into it.

**Comment by itsam** [comment]
@LukeTowers my intention was just to confirm the "unconfirmed bug". I am still not quite familiar with OctoberCMS since I discovered this amazing CMS just 2 days ago, but I 'll give it a try. My background is mainly in Joomla!. Thanks for your quick reply.

**Comment by LukeTowers** [comment]
@itsam Not a problem, generally we keep the unconfirmed bug tag until we can personally reproduce it ourselves; although I'm pretty sure from the descriptions this is an actual bug. Just don't have time to look into a fix for it right now unfortunately.

I'm always willing to help out people that are willing to put effort into improving October, so if you're willing, see if you can find a fix and then I'll review it and let you know if we can merge it or what we'd need to change about it to fix it.

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by LukeTowers** [comment]
Discussion continued in #3354
