### ISSUE TITLE
Argument 1 passed to October\Rain\Translation\FileLoader::loadNamespaceOverrides() must be of the type array, integer given

### ISSUE THREAD

**Issue by sozonovalexey** [octobercms/october#2607]
##### Expected behavior
1. Don't show exception.
2. Show flash error message. For example: For some reasons we can not load lang.php file for the next plugins: Xeor.CustomPlugin.
3. Load previous lang.php file or default (may be **en/lang.php**?)

##### Actual behavior
Error:

Argument 1 passed to October\Rain\Translation\FileLoader::loadNamespaceOverrides() must be of the type array, integer given, called in .../vendor/october/rain/src/Translation/FileLoader.php on line 72 and defined

/vendor/october/rain/src/Translation/FileLoader.php line 87

##### Reproduce steps
1. For example - remove all dirs from /plugins/rainlab/blog/lang/ except en
2. Create ru folder and add empty lang.php file
3. Go to backend preferences and select Russian
4. Refresh current page

##### October build
382

**Comment by daftspunk** [comment]
Thanks for this. It has been replicated and fixed.
