### ISSUE TITLE
Default selection for Null and 0 values in backend dropdown

### ISSUE THREAD

**Issue by kermiv** [octobercms/october#2612]
I have a problem with default selection for dropdowns. In my case i use dropdown for nullable boolean field.
```
is_busy:
    label: 'Is Busy'
    type: dropdown
    emptyOption: 'Unknown'
    options:
        0: 'No'
        1: 'Yes'
```
But, when rendering dropdown, options with 0 value get selected also when "null" has been passed (and that's an unwanted behaviour)

##### Expected behavior
Default selection for dropdown must be emptyOption ("Unknow") if NULL value is present
Default selection for dropdown must be 0 ("No") if 0 value is present

##### Actual behavior
Independetly of field value (0 and NULL) dropdown default selection is always the same - 0 ("No")

##### Reproduce steps
1) In Test plugin select Playground > People 
In list we see two new fields: "Is Married" and "Has pets". Thees fields are empty now, because values for these fields in database is NULL.
2)  Go to Playground > People > Edit
In form we see two dropdowns "Is Married" and "Has pets" with selected value 0 ("No"), but default selection must be emptyOption ("Unknown"), because field value in db is NULL.
3) If click Save and return to list Playground > People 
Now we see columns "Is Married"  "Has Pets" is 0. 

##### October build
392

##### Possible solution
I'm not sure how this could affect all possible cases, but maybe it would be reasonable to modify the file _field_dropdown.htm?

row 25:
`<?= $value == $field->value ? 'selected="selected"' : '' ?>`
replace with
`<?= ($value == $field->value && (!$emptyOption || $field->value !== null)) ? 'selected="selected"' : '' ?>`

and maybe also add the following to emptyOption (row 18)
`<?= ($field->value === null) ? 'selected="selected"' : '' ?>`

Of course, i could substitute null value with something else in afterFetch() function and set it back to null in beforeSave(), but that's not an elegant solution.

What would be the best solution, if I nedded to use both the values: null and 0 together?

**Comment by daftspunk** [comment]
You may want to consider using the "Nullable" trait to convert empty strings to null, inside the model:
http://octobercms.com/docs/database/traits#nullable

**Comment by kermiv** [comment]
```
    is_married:
        label: 'Married'
        type: dropdown
        emptyOption: 'Unknown'
        options:
            0: 'No'
            1: 'Yes'
```
Nullable trait just converts empty strings and integers with value 0, boolenas with value false, etc. to null, because it uses php empty() function.

In this way both options - 'Unknown' (emptyOption) and 'No' (value 0) becomes to null. 
But the problem not with saving. I handle it in little different way in model beforeSave function.

The problem is when representing field 'is_married' as dropdown.
Independently of witch value is stored in db - 0 or null, dropdown default selection is always the same - 0 ("No"), and that's an unwanted behaviour.

**Comment by daftspunk** [comment]
This could be a bug, I don't think Nullable should be treating 0 as null...

**Comment by kermiv** [comment]
Nullable trait now works correctly, but there are still problems with the dropdown default selection.

Independently witch of value is stored in db - 0 or null, dropdown default selection is always the same - 0 ("No"), and that's an unwanted behaviour. 

I'm not sure how this could affect all possible cases, but maybe it would be reasonable to modify the file 
`\modules\backend\widgets\form\partials\_field_dropdown.htm`?

row 25:
`<?= $value == $field->value ? 'selected="selected"' : '' ?>`
replace with
`<?= ($value == $field->value && (!$emptyOption || $field->value !== null)) ? 'selected="selected"' : '' ?>`

and maybe also add the following to emptyOption (row 18)
`<?= ($field->value === null) ? 'selected="selected"' : '' ?>`

**Comment by daftspunk** [comment]
This should be fixed in Build 397+
