### ISSUE TITLE
Forum Component not showing after installation

### ISSUE THREAD

**Issue by abhi1693** [octobercms/october#2614]
##### Expected behavior
After updating `OctoberCMS` the forum component from the `component` tab went missing.

##### Actual behavior
Forum component should show up in the `component` tab.

##### Reproduce steps
Updated to the latest build after which it vanished.

##### October build
392

I updated the OctoberCMS to the latest build and my forum component went missing. I tried force update as well but still didn't show up.

![1](https://cloud.githubusercontent.com/assets/5083532/22008684/51a9970a-dca3-11e6-8d4f-3d08c249514c.png)
![2](https://cloud.githubusercontent.com/assets/5083532/22008683/51a62c96-dca3-11e6-936e-410913815fa5.png)

**Comment by alxy** [comment]
The Forum requires ``RainLab.User`` to be installed, which is not the case. This is why it is disabled by the system.

**Comment by daftspunk** [comment]
This keeps coming up, it should be handled as part of #36
