### ISSUE TITLE
"Manage plugins" page not working when install plugin "Simple Contact Us"

### ISSUE THREAD

**Issue by Osnapman** [octobercms/october#2615]
##### Expected behavior
Install Simple Contact Us, build and use contact form on a page of the website.

##### Actual behavior
Does not show up as installed, breaks "manage plugins" page and gives this error https://puu.sh/tqS4G/32aaa37d35.png

##### Reproduce steps
Just installed Simple Contact Us by Zainab, on shared host, went to click the button "manage plugins" and the error showed up.
##### October build
382

**Comment by SebastiaanKloos** [comment]
It is not creating the database table on install. I checked it.

**Comment by seanthepottingshed** [comment]
This issue should be posted in the plugin repo

**Comment by LukeTowers** [comment]
@seanthepottingshed is correct, the plugin is broken in this case, not October. Post in https://github.com/jawainc/simplecontact or http://octobercms.com/plugin/zainab-simplecontact
