### ISSUE TITLE
Improve error handling when attempting to search or sort by unsearchable / unsortable columns

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#2616]
#### Expected behavior
When performing a search on a list widget where a column with a relation defined; the search should proceed as normal. If the relation type is not supported, then it should fail gracefully with an appropriate message.

#### Actual behavior
Searches are unable to be performed on polymorphic relations, specifically the `morphTo` relation. This is because `\October\Rain\Database\Model->makeRelation($name)` returns null for the morphTo relation type. Unfortunately, because the List widget assumes that if a model hasRelation it will also return a valid value from makeRelation (which is not the case when it comes to `morphTo` relations), this causes it to throw an exception when it attempts to call `getTable()` on the null value that it has received from `Model->makeRelation()`. 

#### Reproduce steps
Create a model with a `morphTo` relation. In the columns.yaml for the model, specify a column that utilizes that relation, and then in the list view try searching for anything via the search box.

#### Discussion
@daftspunk Should this be resolved by silently ignoring `morphTo` relations in `Backed\Widgets\List->isColumnRelated()`, or should we provide an exception message to let developers know what's wrong?

**Comment by alxy** [comment]
How about adding ``searchable: false`` to that column?

**Comment by LukeTowers** [comment]
@alxy That's too easy :) 

In all seriousness though, I've already done that. This issue is more to discuss whether it would be a good idea to have better handling for future cases like this to prevent other people running into the same issue I did.

**Comment by daftspunk** [comment]
We should have some early logic that checks if the relationship is supported first and foremost. If not supported, throw a friendly exception. Otherwise we'll be applying #2617 style band-aids everywhere. Does that sound alright?

**Comment by LukeTowers** [comment]
@daftspunk That works for me. Any recommendations on how early to check?

**Comment by daftspunk** [comment]
There are a few exceptions thrown in the `initRelation` method, it could be added here.

**Comment by tschallacka** [comment]
I always do a select in my columns.yaml with relations instead of a valueFrom. It solves so many problems.

    select: name
 
can search, sort, everything \o/

    valueFrom: name
  
fails on so many counts

maybe changing the valueFrom logic into the logic of a select?

**Comment by daftspunk** [comment]
They are both different, `valueFrom` looks at the model attribute, whereas `select` looks at the database column. Take "valueFrom" attribute / "select" value from database.

**Comment by LukeTowers** [comment]
See comment in #2617
