### ISSUE TITLE
Import CSV not working with S3 storage

### ISSUE THREAD

**Issue by goeroe** [octobercms/october#2623]
When using aws s3 storage you will get the following error when trying to upload a csv:

```
"Expected data must be string or stringable" on line 161 of ~/vendor/league/csv/src/AbstractCsv.php
```

##### Reference
Forum post: https://octobercms.com/forum/post/import-csv-not-working-with-s3-storage

##### October build
Build 392

**Comment by daftspunk** [comment]
This method has been completed as part of [this commit](https://github.com/octobercms/library/commit/f23b76256a2cdedc0dca2450c696b5ece5f2cab7).

**Comment by goeroe** [comment]
Is it me or is the error back on the latest build?? 395...

**Comment by goeroe** [comment]
Strange... Forced update and seems to work again now
