### ISSUE TITLE
Corrupt Thumbnail Images

### ISSUE THREAD

**Issue by interworks-morr** [octobercms/october#2624]
##### Expected behavior
Valid thumbnail images which work in all major browsers.

##### Actual behavior
PNG thumbnail images in Firefox will no longer load.  Instead a message, "This image '.../storage/app/uploads/public/588/659/180/thumb_1_400x400_0_0_crop.png' cannot be displayed because it contains errors." is shown.  Slack user luketowers was able to run the image through ImageOptim to correct the issue.

##### Reproduce steps
View any PNG thumbnail created from a working full-size image.

##### October build
382

**Comment by daftspunk** [comment]
Unable to replicate this? Does it only happen on one image, or all images?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
