### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by seanthepottingshed** [octobercms/october#2626]
I would explode with joy if OctoberCMS included native support for the Glide image manipulation Librat:

http://glide.thephpleague.com

**Comment by LukeTowers** [comment]
That's better suited to the realm of plugins :) 

As a note, feature requests generally shouldn't be reported as issues unless you plan on adding the requested functionality yourself and are using it as more of a pre-pullrequest.

**Comment by seanthepottingshed** [comment]
@luketowers I know I'm a very naughty boy ;)

It would be amazing if it was part of the core though, particularly the point of interest when dealing with serving responsive images, that would make me spontaneously combust!

**Comment by daftspunk** [comment]
This would be a cool plugin indeed. Easy enough to do

    public $attachOne = [
        'photo' => 'Acme\MyCustom\Models\GlideFile'
    ];

**Comment by seanthepottingshed** [comment]
;)
