### ISSUE TITLE
form_open() and upload issues

### ISSUE THREAD

**Issue by Asinox** [octobercms/october#2627]
Hello guys, please if anyone can confirm this for me... 

My form can't be submited using `form_open({request: 'onSubmit', files: true})`, but using a `<form ...></form>` eveything works (except uploads).

I dont know if its just me but, in the same way i cant upload files in the frontend... 

Im debuging my form using `Log::info(var_export(Input::all(), true));` inside my page process function (onSubmit), and all data is there but the files data are missing.

October Build: 382

Thanks guys!

**Comment by LukeTowers** [comment]
See https://octobercms.com/forum/post/frontend-file-upload. File uploads are not supported through AJAX, so you'll have to use the backed fileupload widget to upload files through the frontend. There is a handy plugin available for it here: https://octobercms.com/plugin/netsti-uploader

**Comment by Asinox** [comment]
Thank you @LukeTowers , i know that i cant upload file with ajax, but this form is a non-ajax form.

Yeah im using netsti-upload after this issue.

Thanks

**Comment by LukeTowers** [comment]
@Asinox: Uploaded files will not appear in `Input::all()`. In order to reference them, you will need to use `Input::file($nameOfFileUploadElement);`. This of course is under the condition that you aren't making an AJAX request to upload them.

```
{{ form_open({request: 'onSubmit', files: true}) }}

    Select image to upload:
    <input type="file" name="fileToUpload" id="fileToUpload">
    <input type="submit" value="Upload Image" name="submit">

{{ form_close }}
```
and in the component:
```
public function onSubmit()
{
    dump(Input::file('fileToUpload')); // Instance of UploadedFile
    dd(Input::all()); // All other fields submitted with the form
}
```
