### ISSUE TITLE
Sortable Trait issues with over 500 records

### ISSUE THREAD

**Issue by poniatowski** [octobercms/october#2629]
Hello guys,

I have small problem with Sortable traits. In situation when I have a lots of rows to sort, I always get this error below:

  **count of itemIds do not match the count of itemOrders "on line 57 \vendor\october\rain\src\Database\Traits\Sortable.php**

I've checked code and seems to be really weird behavior. In this trait there is condition which check if `record_ids` and `sort_orders` $ _POST arrays contain the same numbers of values. Please, see below:

```
if (count($itemIds) != count($itemOrders)) {
      throw new Exception('Invalid setSortableOrder call - count of itemIds do not match count of itemOrders');
}

```
When I have arround 500 rows appearing my error. There is always different between these both count arrays e.g. `record_ids` = 501, but `sort_orders` = 498. Why? I've checked on the DOM file and there are same numbers of values in both arrays. Also, in AJAX we send same number of values in both arrays. Seems like somewhere in the PHP is something which stoping the script to works properly. 

Thank you for any help in advanced.

**Comment by daftspunk** [comment]
Could it be the `max_input_vars` directive in the php.ini file? I think it defaults to 500.

**Comment by poniatowski** [comment]
I'll check it, but I don't think is because of that. Sortable provides two arrays and one of them include always correct amount. I've tested in arrays bigger than 500. Also, different bettween arrays is different depends of `record_ids` size. Sometimes there is different in 3 items, sometimes 8 items etc. I've revied PHP and JS code and definitely front-end send the correct amounts, that for sure. Issue is somewhere in the backend, but I could find exactly place. I think, the best idea is to create 500-700 items and test it. I'm wondring if you'll get same issue. Thx.

**Comment by poniatowski** [comment]
I've  put 1000 to my `max_input_vars`  in php.ini and I've got still same issue. Also, I thought that maybe is because my plugin, so I've tested it on another plugin and there's same issue where in controller is 500 rows. Also, I've tested it in two different projects with same issue. Could anyone test it, please. You need to create only arround 500 records in you table and update sort_order values e.g.: `update table set sort_order = id` then you can test it on backend.

**Comment by poniatowski** [comment]
I've just tested this with new project and new plugin, event with new environment. Nothing helps, I've still have same an issue.

**Comment by daftspunk** [comment]
Can someone submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. The items under "Trees" support reordering, may just need to increase the number of seeded items and see if this can be replicated beyond a single user issue. Need to determine if this is the platform or the web server causing the discrepancy.

**Comment by poniatowski** [comment]
@daftspunk I've just put over 500 new categories to `trees` and I'm getting this same error. I've installed test component in fresh October CMS installation, so seems to be an issue in October CMS.

`Error:`
"Invalid setSortableOrder call - count of itemIds do not match count of itemOrders" on line 57

**Comment by poniatowski** [comment]
@daftspunk I reckon at least you can change bug status to `confirmed bug` :) It's really there.

**Comment by poniatowski** [comment]
Any updates guys?

**Comment by LukeTowers** [comment]
The `bug` label is applied when either we can personally confirm that it exists or a number of other people can confirm that it exists.

I'll take a look when I have some time, but otherwise if you want it to be looked at faster consider [posting a bounty](https://www.bountysource.com/teams/october)

**Comment by LukeTowers** [comment]
Those numbers are a bit of a clue here. The higher above 500 you get for records, the lower below 500 you get for sort_orders, minus 1.

i.e. records = 500 + x will cause sort_orders = 500 - x - 1

**Comment by daftspunk** [comment]
Needs to be replicated, follow procedure and let us know the PR for the test plugin.

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by trnikon** [comment]
@poniatowski 502 record_ids + 497 sort_orders = 999 + _session_key + _token = **1001 > 1000**. Always leave some room.

I had the same problem and increasing `max_input_vars` fixed it. In my case I increased it from 1000 to 4000.

**Comment by LukeTowers** [comment]
@trnikon couldn't we store the array of ids and the array of sort orders in one variable each? Why does each sort order and each id need to be it's own variable?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by LukeTowers** [comment]
@bennothommo I'm actually still interested in finding a fix to this. What do you think of my last suggestion?

**Comment by bennothommo** [comment]
@LukeTowers I'm not sure I follow where the bug is. By what is described in the OP, it looks like the IDs and orders are already one variable each (both arrays), and it's the arrays that are being clipped by `max_input_vars`. Is that the case?

**Comment by LukeTowers** [comment]
@bennothommo you'd have to inspect a network request, I'm pretty sure they're being sent as HTML arrays which means that each element is it's own input_var. We could fix this by sending them as JSON probably under one input_var
