### ISSUE TITLE
Can't delete plugin out of my account due to it changing over to paid

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#2633]
Hello,

Recently ADRENTH.REDIRECT plugin changed over from free to pay and I have an attached project to my October Plugins.

I have some paid plugins in my October account so I can not unattach this project.

My problem is that I want to delete ADRENTH.REDIRECT plugin from my October Account but I can not delete it now that it has changed over to paid.

I think I need someone manually to go into my October account and remove this plugin.

My October forum username is: asianspaweb20443

My October Project Page is: https://octobercms.com/account/project/preview/18197

Please can someone at October go in and delete this plugin from my account.

p.s. You Need to update your system to allow October Users to be able to delete a plugin if it changes over from FREE to PAID.

**Comment by daftspunk** [comment]
This plugin has been removed from your project. Thanks

**Comment by ayumihamsaki** [comment]
Thank you daftpunk for your quick reply.
