### ISSUE TITLE
Unable to extend JSON property if not initially defined

### ISSUE THREAD

**Issue by seanthepottingshed** [octobercms/october#2636]
@LukeTowers 

##### Expected behavior

Should be able to define JSON property by extending model

##### Actual behavior

Error displayed stating field should be JSONable

##### Reproduce steps

https://github.com/daftspunk/oc-test-plugin/pull/33

##### October build

Latest

**Comment by LukeTowers** [comment]
See https://github.com/daftspunk/oc-test-plugin/pull/33#issuecomment-276070087

**Comment by seanthepottingshed** [comment]
All good with this, thanks for your time and help
