### ISSUE TITLE
[featureRequest] Duplicate query eloquent

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#2640]
Planning to implement this code:

https://laracasts.com/discuss/channels/guides/never-execute-a-duplicate-query-again

Do you think this is useful in the core or should I build a plugin for this?

Does anyone have an idea how to extend the Illuminate\Database\Query\Builder in my plugin?

**Comment by SebastiaanKloos** [comment]
I almost fixt this.

**Comment by SebastiaanKloos** [comment]
It is fully working now as a plugin.

**Comment by LukeTowers** [comment]
@SebastiaanKloos What's the link to the plugin for future reference?

**Comment by SebastiaanKloos** [comment]
@LukeTowers I'll add it to Github very soon!

**Comment by SebastiaanKloos** [comment]
@LukeTowers you can find the plugin here:

https://github.com/SebastiaanKloos/oc-noduplicatequeries/tree/master

**Comment by daftspunk** [comment]
Nice idea... it's like using `remember()` on a query. That cache is going to get hammered!

I've thought about something similar except caching it in memory instead of using the cache driver. So duplicate queries across *the same request* are never performed.

**Comment by SebastiaanKloos** [comment]
@daftspunk that is exactly what I wanted to do. It would really benefit to the framework.
