### ISSUE TITLE
Extending backend login form

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#2641]
##### Expected behavior
Extending the backend login form by instructions in the docs.

##### Actual behavior
The view is not extended.

##### Reproduce steps
Use the instructions in the docs to extend a view:
https://octobercms.com/docs/plugin/extending#backend-view-events

##### October build
393

**Comment by LukeTowers** [comment]
@SebastiaanKloos You may need to add
```
public $elevated = true;
```
to your Plugin.php file.

**Comment by SebastiaanKloos** [comment]
@LukeTowers Thanks you very much. This solved this problem.
