### ISSUE TITLE
`thumb()` method on attachment increases filesize of png files

### ISSUE THREAD

**Issue by tobias-kuendig** [octobercms/october#2644]
##### Expected behavior

I am uploading a png file via `fileupload` widget in the backend. Then I use the following code to generate and display a thumbnail of the image:

```html
<img src="{{ product.image.thumb(600, 'auto') }}" alt=""/>
```

The original image (780x600) has a filesize of 186 KB. The generated thumbnail (600x480) should have a smaller filesize since it has smaller dimensions.

##### Actual behavior

The generated thumbnail (600x480) has a file size of 1 MB. I have experienced the same problem with other images where they got blown up from 900 kb to more than 9 MB.

###### Example 

Original:
https://snipcart.offline.swiss/storage/app/uploads/public/589/791/a0c/589791a0cdfe8713038426.png

Resized: 
https://snipcart.offline.swiss/storage/app/uploads/public/589/791/a0c/thumb_49_600x0_0_0_auto.png

##### Reproduce steps

Resize any png file via `.thumb` method as described above.

##### October build

396

**Comment by daftspunk** [comment]
Could this be related to the quality setting? Currently set pretty high at 95/100.

```
<img src="{{ product.image.thumb(600, 'auto', { quality: 50 }) }}" alt=""/>
```

**Comment by tobias-kuendig** [comment]
This could be it!

Untouched original image is `500 KB`

If I manually specify the quality:

```
100   ->  1.1 MB
 95   ->  1.1 MB
 90   ->  256 KB
 80   ->  248 KB
 70   ->  237 KB
 50   ->  211 KB
 20   ->  193 KB
```

Looks like setting it to 90 % already does most of the compression.

**Comment by LukeTowers** [comment]
@daftspunk might be worth turning it down by 5 if that's the result

**Comment by tobias-kuendig** [comment]
Setting [this](https://github.com/octobercms/library/blob/76ed5ad9b5da5b9390b6d283318a064b9b64f283/src/Database/Attach/File.php#L415) to 90 reduced a page of mine containing 10 PNGs from 2.3 MB to 600 KB total page size.

**Comment by daftspunk** [comment]
Done and done (https://github.com/octobercms/library/commit/10ac482c4c805ba5af09a475406e553ca6c2ce53)

**Comment by tobias-kuendig** [comment]
I've just noticed the setting is present in [Resizer.php](https://github.com/octoberrain/database/blob/28d50ecbdb59c40df6e28bb3c58ca67eea9c2834/Attach/Resizer.php#L137) too. It doesn't affect this particular problem, but I guess it could lead to the same result in other cases...?

**Comment by LukeTowers** [comment]
@tobias-kuendig Good catch, we should be consistent with this at least.
