### ISSUE TITLE
Passing filter options to page / Saving filters

### ISSUE THREAD

**Issue by goeroe** [octobercms/october#2645]
Is there a way to pass filter options to a (list)page? 

Now when you filter a list these options get saved in a cookie (I guess) so when you leave the page and you come back to it, the list is still filtered but it would be nice to be able to define (combinations of) filters that you don't need to replicate them all the time.

**Comment by daftspunk** [comment]
Sure. Take a look at `Cookie::queue` (http://octobercms.com/docs/services/request-input#cookies) and perhaps `Session::put` (http://octobercms.com/docs/services/session#session-usage).

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
