### ISSUE TITLE
Limit the items in backend form repeater

### ISSUE THREAD

**Issue by joelamltc** [octobercms/october#2649]
Is there any way to limit the repeater items?

Let say I use repeater plus media finder to be a image slider, and I only want user to upload maximum 5 images. Is is possible to limit the items in repeater?
Temporary, I just check the items in repeater on Model Event only.

Thank you.

##### October build
v1.0.390

**Comment by seanthepottingshed** [comment]
@joelamltc good question! I would like to know this too ;)

**Comment by SebastiaanKloos** [comment]
I guess this is currently not supported. After you added this, feel free to request a PR.

**Comment by joelamltc** [comment]
Unluckily, my experience is not enough to update the core.

**Comment by SebastiaanKloos** [comment]
@joelamltc I'll give it a try when I have some time.

**Comment by joelamltc** [comment]
@SebastiaanKloos Thank you so much.

**Comment by LukeTowers** [comment]
Duplicate of #1710, fixed by #2723
