### ISSUE TITLE
The OctoSkin doesnt load properly on first load

### ISSUE THREAD

**Issue by SeekAndPwn** [octobercms/october#2650]
##### Expected behavior
Smooth loading of the skin

##### Actual behavior
The octoskin does not display images on Chromium browser 

##### Reproduce steps
Install octobercms choose octoskin. Proceed to main page after the installation.
The images are not displayed. After page reload it works as expected. Might be a problem with delayed image loading or something.

##### October build
Latest.

**Comment by SebastiaanKloos** [comment]
I think this question / report is better placed on the themes support page.

**Comment by daftspunk** [comment]
This looks like it might be caused by a race condition and the time it takes to load jQuery from the CDN? This should be reported to the author.
