### ISSUE TITLE
Improper escaping of html tags in Blog posts added from admin panel

### ISSUE THREAD

**Issue by SeekAndPwn** [octobercms/october#2651]
##### Expected behavior
Escaped <> and other html tags/characters to prevent XSS attacks etc.

##### Actual behavior
After installation of octobercms with Blog plugin and adding a new post with the content of:

This is my test post :)

<script>

A pop up message gets displayed with:

'"Class 'DOMDocument' not found" on line 465 of /var/www/html/octobercms/vendor/erusev/parsedown-extra/ParsedownExtra.php'

This does not seem to be production ready. Html tags should get escaped.

##### Reproduce steps
See above.

##### October build
Latest octobercms / Blog plugin.

**Comment by SebastiaanKloos** [comment]
I think this question / report is better placed on the blog plugin issues.

**Comment by LukeTowers** [comment]
@SeekAndPwn As @SebastiaanKloos said, this is in regards to the blog plugin so it belongs there. As a side note, the blog plugin uses markdown as its content field so there is no XSS vulnerability here.

**Comment by daftspunk** [comment]
Looks like you need to install the DOM extension in PHP. Also HTML is allowed in blog posts, if an admin wants to perform XSS on themselves then it is their prerogative.
