### ISSUE TITLE
Reorder behavior not working when added later

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#2652]
##### Expected behavior
Adding the reordering functionality after you entered some entries to a model should work fine.

##### Actual behavior
When the sort_order column gets populated with 0, the reordering does not work. So it should set it up when it sees 0. 

##### Reproduce steps
- Creating and adding entries to a model. 
- Then add the reorder behavior. 
- Try to reorder. It does not save the new order. 

##### October build
396

##### Temp fix
Change the entries with sort_order 0 manually to 1,2,3 etc.

**Comment by aleshkanet** [comment]
Yes, same problem. Something not working.
Exceptions when i drag element
![screenshot_4](https://cloud.githubusercontent.com/assets/2388747/22826317/dd50ae62-efa2-11e6-89e1-16d0267012d6.png)
and only 0's saved in DB
![screenshot_2](https://cloud.githubusercontent.com/assets/2388747/22826207/42a577e4-efa2-11e6-8b72-7d50af350e46.png)

Another plugin works fine.

**Comment by daftspunk** [comment]
Duplicate #1923
