### ISSUE TITLE
Implementing behavior on component throws BadMethodCallException

### ISSUE THREAD

**Issue by czerwonyd** [octobercms/october#2654]
##### Expected behavior
After implementing behavior in component, the methods from behavior should be accessible in the component using `$this->method();` notation.

##### Actual behavior
When using methods from behavior implemented on component the BadMethodCallException from ComponentBase.php:278 is thrown. The method cannot be found in `$this->controller` using `method_exists` and the exception is thrown. Using the `asExtension()` seems to work as expected.

The funny part in this is that the method in behavior is called in `parent::__call` in ComponentBase.php:270, so I have no idea why there is another checking and running in `$this->controller`. I am just guessing, but it looks like the `if` from line 274 should be placed somewhere in `try catch` block and after successful `parent::call` exception should not be thrown.

##### Reproduce steps

1. Create componentBehavior in a way described in [documentation](https://octobercms.com/docs/services/behaviors)
2. Implement it in any component 
3. Run method in components `onRun()` using `$this->method()`

##### October build
396

**Comment by daftspunk** [comment]
Can you make it easy for us and provide your component and behavior class code. You may paste your code at http://kopy.io or https://gist.github.com.

**Comment by czerwonyd** [comment]
Sure. You can see the example behavior here: https://github.com/initbizlab/oc-cumuluscore/blob/master/behaviors/ComponentBehavior.php

As I wrote earlier, if in `componentMethod()` is `dd()` function it works as expected because its execution is being stopped in `ComponentBase.php:270`.

If we change this to let's say `var_dump()` the exception from `ComponentBase.php:278` is thrown.

I have not pushed code of component that used it, but it was as simple as:
```
public $implement = [
    'InitBiz.CumulusCore.Behaviors.ListComponent'
];
```
in component's code.

**Comment by Nyorai** [comment]
Just come across this bug. I think the `__call` method in `Cms\Classes\ComponentBase` fails to return the parent's result in the first try/catch block

```php
    /**
     * Dynamically handle calls into the controller instance.
     * @param string $method
     * @param array $parameters
     * @return mixed
     */
    public function __call($method, $parameters)
    {
        try {
            parent::__call($method, $parameters);
        }
        catch (BadMethodCallException $ex) {}

        if (method_exists($this->controller, $method)) {
            return call_user_func_array([$this->controller, $method], $parameters);
        }

        throw new BadMethodCallException(Lang::get('cms::lang.component.method_not_found', [
            'name' => get_class($this),
            'method' => $method
        ]));
    }
```

This fixes it for me
```php
    /**
     * Dynamically handle calls into the controller instance.
     * @param string $method
     * @param array $parameters
     * @return mixed
     */
    public function __call($method, $parameters)
    {
        try {
            return parent::__call($method, $parameters);
        }
        catch (BadMethodCallException $ex) {}

        if (method_exists($this->controller, $method)) {
            return call_user_func_array([$this->controller, $method], $parameters);
        }

        throw new BadMethodCallException(Lang::get('cms::lang.component.method_not_found', [
            'name' => get_class($this),
            'method' => $method
        ]));
    }
```

**Comment by LukeTowers** [comment]
@Nyorai Looks reasonable to me, if somebody else can replicate this issue locally and verify this works without breaking anything else then I'd be happy to merge it. As a side note, is there any other base class in October that implements a similar magic __call method that looks at a property of the class to run methods against that might also suffer from this bug?

**Comment by daftspunk** [comment]
Pull request plox!
