### ISSUE TITLE
Add new feature - Development releases

### ISSUE THREAD

**Issue by sozonovalexey** [octobercms/october#2658]
May be it is a good idea to add new feature to Marketplace - Development releases (similar to drupal.org). So developers can test their plugins and users can switch between branches in backend area. Just think about it ;)

![2017-02-06_17-53-11](https://cloud.githubusercontent.com/assets/1676060/22651736/08e65e66-ec95-11e6-9cca-038586461984.png)

**Comment by LukeTowers** [comment]
I believe this already exists in the form of `edgeUpdates` in your config/cms.php file.

**Comment by sozonovalexey** [comment]
Yes! But I think that it would be nice to show available version in Marketplace

![2017-02-06_21-46-22](https://cloud.githubusercontent.com/assets/1676060/22661365/2ab04f4a-ecb6-11e6-9581-2dbe1a2cf2e7.png)

**Comment by LukeTowers** [comment]
I'm not sure I see the use case of showing the available pending update in the sidebar, users can already see it by clicking on the changelog tab.

Closing as it has been over a month since any activity on this occurred.
