### ISSUE TITLE
Richeditor/Markdown editor within MLRepeater doesn't load correct value when switching language

### ISSUE THREAD

**Issue by canthis** [octobercms/october#2662]
Created this issue here, because looks like problem is with Richeditor formwidget itself, not Translate Plugin's MLRepeater widget.

##### Expected behavior
Richeditor within MLRepeater should be populated with corresponding value per language, when switching MLRepeater language to another language and then back to previous language.

##### Actual behavior
Richeditor is not being populated with corresponding language's value at all, or only with default language's value, when switching MLRepeater language.

##### Reproduce steps

1. Install Translate Plugin and create 2 languages.
(Let's assume you have 2 languages -  default: EN and secondary: RU)
2. Install [Test plugin](https://github.com/canthis/mlrepeatertest) I've created to demonstrate this issue to `/plugins/canthis/mlrepeatertest` folder.
3. Go to MLRepeaterTest plugin, and press "Create" button.
4. Fill repeater form fields with content for EN language.
5. Switch language to RU and fill form fields with content for RU language.
6. Now try switching languages and you should see, that Richeditor is not being populated with correct values, although values where successfully saved to DB.

##### Proposed fix
Changing [line 74 in october/modules/backend/formwidgets/RichEditor.php](https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/RichEditor.php#L74) to
```
$this->vars['value'] = $this->formField->value;
```
makes richeditor load values as expected. 

##### October build
398 (Edge updates turned on)

##### Translate Plugin version
1.2.10

Refs: rainlab/translate-plugin#218

**Comment by daftspunk** [comment]
Fixed in https://github.com/octobercms/october/pull/2663
