### ISSUE TITLE
 How to check if a js file has been already included by another widget

### ISSUE THREAD

**Issue by meysammahfouzi** [octobercms/october#2664]
##### Expected behavior
I've got two separate report widget classes, both of which use `highcharts.js` to render a chart. I use the following method to include the js file:

```
public function loadAssets()
{
    $this->addJs('js/highcharts.js');
}
```

If I add one instance of widget A and one instance of widget B to the dashboard page, `highcharts.js` will be included twice in the page and this will break everything! I expect `highcharts.js` to be included once, or there should be a way to find out if another widget (which may not be necessarily developed by me) has already included `highcharts.js` in the page so that I don't do it again.

##### Actual behavior
If I add two instances of the same widget to the dashboard, `highcharts.js` wont be included twice. But if I add one instance of widget A and one instance of widget B to the dashboard page, `highcharts.js` will be included twice in the page and this will break everything!

##### October build
387

**Comment by LukeTowers** [comment]
@meysammahfouzi Add a check to the JS file to prevent initializing it's contents if it detects that they have already been initialized.

**Comment by LukeTowers** [comment]
Misclick on the close button btw

**Comment by meysammahfouzi** [comment]
@LukeTowers I don't think it's a good idea. The javascript file is not developed by me. Third party libraries are most of the time minified and not easy to be altered! Your solution is a hack. There should be an easier way.

**Comment by daftspunk** [comment]
The AssetMaker should be handling duplicates, will need to investigate. Can you provide a working example as a PR to the test plugin?

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by meysammahfouzi** [comment]
@daftspunk Please find the pull request here: https://github.com/daftspunk/oc-test-plugin/pull/35

**Comment by daftspunk** [comment]
See notes in https://github.com/daftspunk/oc-test-plugin/pull/35
