### ISSUE TITLE
Cannot Extend Posts Controller to add formAfterSave method...

### ISSUE THREAD

**Issue by seanthepottingshed** [octobercms/october#2665]
##### Expected behavior

That the `formAfterSave` method would be called.

##### Actual behavior

`formAfterSave` method is not called.

##### Reproduce steps

```php
/**
* Extend Blog.
*/
public function boot()
{
    if (App::runningInBackend()) {
        Posts::extend(function ($controller) {
           $controller->addDynamicMethod('formAfterSave', function ($post) use ($controller) {
               $this->addImageAspectRatio($post->featured_images);
           });
       });
    }
}

/**
 * Add Image Aspect Ratio.
 *
 * @param  File $files 
 *
 * @return File         
 */
protected function addImageAspectRatio($files)
{
    if(!collect($files)->isEmpty()) {
        foreach($files as $file) {
            if(isset($file->id)) {
                $image = File::find($file->id);
                if(is_null($image->aspect_ratio)) {
                    $image->aspect_ratio = $this->calculateImageAspectRatio($image);
                    $image->save();
                }
            }
        }
    }
}

/**
 * Calculate Image Aspect Ratio.
 *
 * @param  File $image
 *
 * @return File
 */
private function calculateImageAspectRatio($image)
{
    list($width, $height) = getimagesize($image->path);
    $aspectRatio          = round( $height / ( $width / 100 ), 2);
    return  $aspectRatio;
}
```
##### October build
Latest

**Comment by daftspunk** [comment]
These methods are not really designed to be used this way, they are for the controller to extend the behavior, not for an external plugin to extend the controller to extend the behavior. This would be quite a fragile implementation, since if the blog plugin were to ever implement this override, the extension would fail.

You probably want to be extending the model directly instead

```
Post::extend(function($model) {
    $model->bindEvent('model.afterSave', function() { /* ... do stuff ... */ });
});
```

**Comment by LukeTowers** [comment]
@daftspunk On a slightly related note, I was wondering if we should allow the `addDynamicMethod` to override any existing methods, that would be nice especially in the case where you want to override methods that are stubs in a connected behaviour by extending the class that implements that behaviour. It would be a simple change, simply switching the order the the Extension base class looks for available methods, placing it's checks for dynamic methods above its check for existing methods. Or could we provide an alternative, like a third parameter to `addDyamicMethod` that enables the method you're adding to override an existing method? I feel like that could be a powerful addition, what are your thoughts on that?

**Comment by daftspunk** [comment]
I don't think it's possible, PHP will ignore `__call` when the method exists so it is impossible to override an existing method this way. Even so, it's an override not an event. Overrides are expected to be linear and easy to comprehend, events can be stacked and much more flexible.

**Comment by seanthepottingshed** [comment]
@daftspunk *cheers ears!*
