### ISSUE TITLE
After latest system update any page opened in CMS or Pages throws Exception

### ISSUE THREAD

**Issue by sNuuFix** [octobercms/october#2666]
##### Expected behavior
Opens up the editor for page

##### Actual behavior
Throws Exception
`'October\Rain\Exception\SystemException' with message 'The partial '_field_mltext.htm' is not found.' in [redacted]/modules/system/traits/ViewMaker.php:65`

##### October build
latest (396 as of writing this issue)

**Comment by LukeTowers** [comment]
Try disabling RainLab.Translate, it appears to be an issue with that plugin

**Comment by daftspunk** [comment]
Unable to replicate this. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by daftspunk** [comment]
Closing as it should also be logged with the Translate plugin repo.

**Comment by virtualLast** [comment]
I am also having this issue

**Comment by LukeTowers** [comment]
@virtualLast do a search for `mltext` and tell me what you find
