### ISSUE TITLE
Zend OPcache 

### ISSUE THREAD

**Issue by m49n** [octobercms/october#2667]
##### Expected behavior
![2](https://cloud.githubusercontent.com/assets/15114737/22854053/aa0bbdd0-f07e-11e6-8156-efd05facb308.PNG)
![1](https://cloud.githubusercontent.com/assets/15114737/22854054/aa249684-f07e-11e6-950a-83f797354949.PNG)

error after install. Zend OPache enable in php.ini

##### Actual behavior
(Describe actual behavior here)

##### Reproduce steps
(Describe the steps to reproduce the problem here)
Install
##### October build
396

**Comment by LukeTowers** [comment]
The error tells you what is wrong, you have `restrict_api` enabled in your Zend OPCache configuration. Disable it by setting it to an empty string: http://php.net/manual/en/opcache.configuration.php#ini.opcache.restrict-api

**Comment by daftspunk** [comment]
This can disabled in its entirety when b2301a8056dfeb63ee6bccde57a86ed7ac98ad97 is released. Simply set `cms.forceBytecodeInvalidation` to false.

Available in Build 398+

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
