### ISSUE TITLE
CMS Plugin Sidebar Nav Missing in Internet Exploder 11

### ISSUE THREAD

**Issue by seanthepottingshed** [octobercms/october#2672]
##### Expected behavior

Should be visible in Exploder 11.096

##### Actual behavior

Is not visible in Exploder 11.096

##### Reproduce steps
View Plugin with Sidebar Nav in Exploder 11.096

##### October build
Latest

**Comment by LukeTowers** [comment]
Which sidebar nav? Please post a screenshot of the working page in Chrome and then it being broken in IE.

**Comment by SebastiaanKloos** [comment]
@LukeTowers this is a real problem. He means the left sidebar. I saw this problem to.

**Comment by seanthepottingshed** [comment]
Sorry off work with man flu at the moment so don't have access to any Internet Exploders.

@SebastiannKloos would you mind posting a screenshot?

**Comment by seanthepottingshed** [comment]
Sorry iPhone autocorrect on your name SK :(

**Comment by LukeTowers** [comment]
@SebastiaanKloos Would you mind helping debug it then? I don't have access to IE 11. Also, there are a couple of different "left sidebars" that exist in October :)

**Comment by seanthepottingshed** [comment]
RainLab.Blog plugin is a prefect example of this ;)

**Comment by SebastiaanKloos** [comment]
@LukeTowers. I will try and install Internet Explorer on my machine. I have seen the problem on a colleagues machine. We are talking about the left sidebar within a plugin. So you have the upper menubar. When you click on a plugin. You will see the left "menubar" / "sidebar" disappear. I will try to add a screenshot.

**Comment by LukeTowers** [comment]
Thanks, that would be helpful @SebastiaanKloos

**Comment by joshgosselin** [comment]
Chrome 
![screen shot 2017-02-14 at 09 11 53](https://cloud.githubusercontent.com/assets/15610536/22922449/bdf85272-f295-11e6-9ca9-385816d655c9.png)

IE 11.096
![df539b7a-ef9d-11e6-9b46-de852a62ad6f](https://cloud.githubusercontent.com/assets/15610536/22922459/cfe40260-f295-11e6-938d-01b5ddbfce0c.jpg)

**Comment by seanthepottingshed** [comment]
@joshgosselin cheers!

**Comment by daftspunk** [comment]
Fixed in Build 404+ (380a71d7b9f6dca566f3daaf2921e8df68626eff)

Need to take a shower after that...

**Comment by seanthepottingshed** [comment]
LEGEND!!

**Comment by seanthepottingshed** [comment]
http://octobercms.com/fundraising
