### ISSUE TITLE
october:util error

### ISSUE THREAD

**Issue by ctf0** [octobercms/october#2673]
##### Actual behavior
```bash
Utility command "" does not exist!
```

##### October build
i believe its v1.0.398

**Comment by LukeTowers** [comment]
What command were you trying to run? It looks like you were trying to run `october:util` by itself which doesn't exist. Read https://octobercms.com/docs/console/commands#utility-commands for more information on the `october:util` sub commands.

**Comment by ctf0** [comment]
okay got it, but maybe the console should give a diff/better error msg, maybe like when using `october:util` without any options it would run `october:util -h` internally ?

however the main reason i ran it was hopping to find a cmnd where i can list all the routes and its corresponding controllers.

**Comment by LukeTowers** [comment]
Feel free to implement the defaulting to -h internally in a PR.

In regards to the routes and the corresponding controllers, I don't believe there is such a command (@daftspunk correct me if I'm wrong). If you've got a more specific question about that I can probably answer it though.

In regards to the build number, it's displayed in the backend updates section. Again, feel free to implement a command for it in a PR.

**Comment by ctf0** [comment]
awesome, many thanx for the quick help.

for the version, i cant find in the backend, i've also tried http://octobercms.com/plugin/indikator-backend which have a widget to show the cms version but again nothing, if u can point me to where the class responsible for displaying the info, i can add a pr with the new cmnd.

**Comment by LukeTowers** [comment]
That's a better question for @daftspunk, sorry. Could try to find it right now but it's late and I need to get some sleep

**Comment by ctf0** [comment]
okay sure, thanx again for ur help 👍

**Comment by daftspunk** [comment]
I don't believe such a command exists, routes are not defined in the back-end per say, the controller is discovered based on the URL pattern. I suppose you could create a command that lists all the controllers (in the /controllers directory of each plugin and module) and then derive the URL and actions from that.

**Comment by ctf0** [comment]
@daftspunk maybe you can add an event for 
> the controller is discovered based on the URL pattern.
and we can listen to it through the console cmnd and list all the routes in a table ?
