### ISSUE TITLE
The new version broke some unit/functional tests on unique validation

### ISSUE THREAD

**Issue by arzola** [octobercms/october#2676]
##### Expected behavior
I have a set of extra unit-functional tests inside of my plugins and i updated the october core via `composer:update` and i am using the **PluginTestCase** all of my tests works fine but not the unique validation

**`@expectedException October\Rain\Database\ModelException` has to be thrown** 

```php
/**
     * @expectedException October\Rain\Database\ModelException
     */
    public function test_slug_has_to_be_unique()
    {
        $post = Model::create([
            'title' => 'This is a new post',
            'slug' => 'post-1',
            'content' => 'Testing...'
        ]);
        $this->assertNotFalse($post);
        $post2 = Model::create([
            'title' => 'this is another post with the same slug',
            'slug' => 'post-1',
            'content' => 'testing....'
        ]);
    }
```

##### Actual behavior

No Exception it's thrown even i am using the Validation trait  

```
Failed asserting that exception of type "October\Rain\Database\ModelException" is thrown.
```

This is my rules array

```php
public $rules = [
        'title' => 'required|min:3|max:255',
        'title_menu' => 'required|min:5|max:255',
        'slug' => ['required', 'regex:/^[a-z0-9\/\:_\-\*\[\]\+\?\|]*$/i', 'unique:arzola_ospages_sitios'],
        'external_url' => ['active_url']
    ];
// i tried to add this new param but does not work :(
public $throwOnValidation = true;
```
##### Reproduce steps

Run my own tests with phpunit

##### October build

i think 399 it's my composer output

```
- Updating october/rain (v1.0.394 => v1.0.399) Downloading: 100%         
  - Updating october/system (v1.0.394 => v1.0.398) Downloading: 100%         
  - Updating october/backend (v1.0.394 => v1.0.398) Downloading: 100%         
  - Updating october/cms (v1.0.394 => v1.0.398) Downloading: 100%         
```

**Comment by daftspunk** [comment]
I have added this test for you (b32176682fe799361fe19f7d32485b58d7fd9dfe), it passes with no issues

    # phpunit --filter=ValidationModelTest
    PHPUnit 4.8.31 by Sebastian Bergmann and contributors.

    .

    Time: 2.18 seconds, Memory: 28.50MB

    OK (1 test, 2 assertions)

Please try updating to the latest build (407+)

**Comment by arzola** [comment]
Thanks bro let me try

**Comment by daftspunk** [comment]
Will assume it went well. Let me know otherwise and we can reopen this.
