### ISSUE TITLE
Include "underline" option in default Richeditor form widget

### ISSUE THREAD

**Issue by CptMeatball** [octobercms/october#2677]
##### Expected behavior
![expected-richeditor-underline](https://cloud.githubusercontent.com/assets/1681727/22968082/570eac9e-f369-11e6-8d34-05ed33f2f936.png)

##### Actual behavior
![actual-richeditor](https://cloud.githubusercontent.com/assets/1681727/22968109/6d46ab74-f369-11e6-9451-98e1b800a7b5.png)

##### Reproduce steps
Include `richeditor` type formwidget in any `fields.yaml`.

##### October build
396 (but any build will suffice)

##### Why
The default setup of buttons is great, but lacks the text underline function that is used quite a lot by users. In the current setup it is missing and needs to be added by duplicating the entire row of default toolbarButtons and adding `underline` to this array. 

Although mostly inconvenient, as you can edit  the `fields.yaml` in custom plugins, there are certain scenarios where you can't edit/extend the `fields.yaml` so easily like `Rainlab.StaticPages`. 

Users have repeatedly asked for this function, which has led us to editing the `fields.yaml` of of the `Page` and `Content` classes found in this plugin.

**Comment by LukeTowers** [comment]
This will be taken care of as a part of #2384. If you'd like to get it looked at sooner, post a bounty :)

**Comment by CptMeatball** [comment]
I know it's being looked at. I just think the decision to _not_ include the underline option was a bit weird.

**Comment by LukeTowers** [comment]
Fair enough, I'll probably change that when taking care of #2384

**Comment by daftspunk** [comment]
Underlining text is usually considered bad practice, since underlined text is commonly used for links.

**Comment by LukeTowers** [comment]
^ We won't include it by default because of that, but once #2384 is complete feel free to override it on your sites.

**Comment by LukeTowers** [comment]
@CptMeatball #2384 is completed by https://github.com/octobercms/october/commit/dfcf324d008b6c20122a20a2b26b43a22111583f
