### ISSUE TITLE
fileds type:number is rendered as text

### ISSUE THREAD

**Issue by webeks** [octobercms/october#2678]
##### Expected behavior
When writing plugins field definition _number_ should be rendered as number so it doesnt allow input other than number.

```
 count:
        label: Some number
        type: number
```

should be

```
<input type="number" name="SearchQuery[count]" id="Form-field-SearchQuery-count" value="1" placeholder="" class="form-control" autocomplete="off" pattern="-?\d+(\.\d+)?" maxlength="255">
```
##### Actual behavior
It is rendered as text. 

```
<input type="text" name="SearchQuery[count]" id="Form-field-SearchQuery-count" value="1" placeholder="" class="form-control" autocomplete="off" pattern="-?\d+(\.\d+)?" maxlength="255">
```
##### Reproduce steps
Add field definition in any plugin model _fields.yaml_ and define it as a number. Open backend page and check html produced.

As far as I remembered this was working fine few builds ago. Now I noticed this problem in a current project that I setup with composer. 

##### October build
v1.0.399

**Comment by webeks** [comment]
it is similar as https://github.com/octobercms/october/issues/2311 however solution is different, I think both changes should be implemented

**Comment by LukeTowers** [comment]
Thanks for pointing this out.

As a note, we may want to implement the min, max, and step attributes as field options as well when we take care of #2311.

**Comment by LukeTowers** [comment]
Fixed in https://github.com/octobercms/october/commit/c836d92f9f04f66f8e0e1b4d9ba8af83fed3e439.

Why I can't just remember to put the issue number in the commit message I have no idea.
