### ISSUE TITLE
Question about post() wrapper and his security 

### ISSUE THREAD

**Issue by AlexMovsesov** [octobercms/october#2682]
What types of security filtration does post() wrapper is provide? Can you advice some classes that provides functionality of checking data for security consistency? Validator or something else?
Thanks!

**Comment by LukeTowers** [comment]
This type of question is better suited to another form of communication, i.e IRC, Slack, or the forums.

To provide some information for you here, the `post()` function comes straight from Laravel, so any input sanitization would occur on that level. 

https://octobercms.com/docs/database/traits#validation has some more information on the Validation trait for database models
