### ISSUE TITLE
Balloon selector field does not push value update to the Trigger API

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [octobercms/october#2684]
##### Expected behavior
On selecting a different item of the balloon-selector field, it should trigger the changed value to any fields that depends on it via the trigger API.

##### Actual behavior
On selecting a different value nothing happens. Only when the form is saved and the page reloaded, the dependent field’s visibility changes.

##### Reproduce steps
1. Create a form with a balloon-selector.
2. Have a field use trigger API to show/hide based on the ballon-selector value.
3. Attempt changing the balloon-selector value.

![balloon-selector-issue](https://cloud.githubusercontent.com/assets/1699753/23065114/de2bee22-f539-11e6-9e10-f4894a8858b0.gif)

##### October build
396

**Comment by LukeTowers** [comment]
Thanks for this report, that GIF is helpful for reproducing this. I can't review it right now as I'm away until March 7th, but perhaps @daftspunk can take a look. Feel free to dig into the code yourself and submit a PR to fix it if you can. If it's super urgent, post a bug bounty and ping the IRC channel and Slack team.

**Comment by LucasZdv** [comment]
Hello, have the same problem... Thanks for this report!

**Comment by daftspunk** [comment]
Fixed in Build 411+

**Comment by SaifurRahmanMohsin** [comment]
Thank you
