### ISSUE TITLE
mtime-mismatch Modal when save page for second time

### ISSUE THREAD

**Issue by lincolnbrito** [octobercms/october#2690]
##### Expected behavior
Show modal with message: "Template saved" and save the template

##### Actual behavior
I'm using October with Docker for Windows.  When I update a static page for second time it show a modal with  message: **mtime-mismatch**. 

##### Reproduce steps
Save a page for second time

##### October build
396

**Comment by neilcarpenter1** [comment]
I got this message when I had a page/layout file changed in sublime, and then tried making some changes on the same file through the browser.

**Comment by robinmalburn** [comment]
I can confirm, I get the same error if I open the page in the backend, then edit and save it in a local editor and try to save additional changes in the backend after that without a page refresh.  It seems like at the very least a more user friendly error message would be useful.

**Comment by daftspunk** [comment]
I was able to replicate this.

**Comment by daftspunk** [comment]
This will be fixed in Build 411+
