### ISSUE TITLE
Add suport to dependency for plugins on themes

### ISSUE THREAD

**Issue by lincolnbrito** [octobercms/october#2700]
##### Expected behavior
Add suport dependecy for plugins and components on themes. It avoid errors when a theme use a component plugin and that is not instaled.

##### Actual behavior
The themes don't use a dependency system

##### Reproduce steps
Install a theme that uses a plugin that is not instaled

##### October build
396

**Comment by LukeTowers** [comment]
Dunno why you immediately closed this.

**Comment by lincolnbrito** [comment]
Sorry! This feature already exists. I don't payed attention

**Comment by LukeTowers** [comment]
Thanks for catching that then :)
