### ISSUE TITLE
SQL Error when relationship count = true and sortable

### ISSUE THREAD

**Issue by lookitsjoel** [octobercms/october#2701]
##### Expected behavior
Using the following plugin: [Flosch Slideshow](https://octobercms.com/plugin/flosch-slideshow)
Has relationships in the SlideShow model:
```
public $hasMany = [
        'slides' => [
            'Flosch\Slideshow\Models\Slide'
        ],
        'slides_count' => [
            'Flosch\Slideshow\Models\Slide',
            'count' => true
        ]
    ];
```
Slide Model uses October\Rain\Database\Traits\Sortable Trait.

##### Actual behavior
When trying to access plugin administration in backend:

```
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'therapy.flosch_slideshow_slides.sort_order' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select `flosch_slideshow_slides`.`slideshow_id`, count(*) as count from `flosch_slideshow_slides` where `flosch_slideshow_slides`.`slideshow_id` in (1) group by `flosch_slideshow_slides`.`slideshow_id` order by `sort_order` asc)
```

It appears that the Sortable trait is adding an ORDER BY clause to the count query, but that doesn't make much sense.

##### Reproduce steps
Install Plugin and access backend admin.

##### October build
latest

**Comment by danielschweiger** [comment]
+1

http://stackoverflow.com/questions/41182801/october-cms-sql-request-incompatible-with-sql-mode-only-full-group-by

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
