### ISSUE TITLE
The overriden "formExtendFields" is called only once in the controller

### ISSUE THREAD

**Issue by meysammahfouzi** [octobercms/october#2702]
There are two ways to extend form fields: 
https://octobercms.com/docs/backend/forms#extend-form-fields

1- Using the `extendFormFields` method (in the `boot()` of plugin)
2- By overriding the `formExtendFields` method inside the controller class

For the same controller that is managing a many-to-many relationship, `extendFormFields` method is called multiple times in the first method (once for the parent and once for the pivot table), but in the seconds approach, `formExtendFields` is called only once.

**Comment by daftspunk** [comment]
We'll take that as a comment, thanks!

**Comment by meysammahfouzi** [comment]
@daftspunk Is it normal? I suppose according to the document the two functions should behave the same.

**Comment by daftspunk** [comment]
It is normal. The `formExtendFields` interacts with the `FormController` behavior, which targets the primary form (usually fired once). The `extendFormFields` interacts with the `Form` widget, which targets any and all forms (can fire many times).

**Comment by meysammahfouzi** [comment]
@daftspunk Thank you. I think that needs to be documented. I will do that for you!
