### ISSUE TITLE
Plugin unit tests failing at first test

### ISSUE THREAD

**Issue by pmhou** [octobercms/october#2704]
##### Expected behavior
Two identical unit tests should return the same result. Also posted [here](https://octobercms.com/forum/post/help-with-basic-testing)

##### Actual behavior
After successfully running the first test, the second test fails. My guess is there's an issue with the tear down method in PluginTestCase.php

##### Reproduce steps
Below are two examples of inconsistent tests.

```php
function testSearchPage()
{
    $this->call('get', '/search')->status(); // 200
}

function testSearchPageAgain()
{
    $this->call('get', '/search')->status(); // 404
}
```

```php
public function testUserAuth()
{
    dump(Auth::getUser()); // null
}

public function testUserAuthAgain()
{
    dump(Auth::getUser()); // Class user.auth does not exist
}
```

##### October build
396

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by daftspunk** [comment]
Adding this example to the test plugin will make it easier for us to replicate and fix this for you, thanks!

**Comment by arzola** [comment]
Yeah, i got the same issue i have to use `process-isolation` to work properly

**Comment by LukeTowers** [comment]
@arzola See @daftspunk's comments, please make a PR to the test plugin so that we can replicate the issue.

**Comment by surahmans** [comment]
Could tell me what process isolation is?

**Comment by LukeTowers** [comment]
This should be fixed by https://github.com/octobercms/october/pull/3156
