### ISSUE TITLE
Visual bugs + others

### ISSUE THREAD

**Issue by dunets** [octobercms/october#2706]
Hello!
There are some bugs/ missing functionality that I found:
![image](https://cloud.githubusercontent.com/assets/6217617/23277869/6926f9a0-fa07-11e6-9ff7-c842e0ed0a9c.png)

So we can create a project... but we can't delete?
![image](https://cloud.githubusercontent.com/assets/6217617/23277902/83e03400-fa07-11e6-9436-a470e44f3bdd.png)

And it's a media finder field:
![image](https://cloud.githubusercontent.com/assets/6217617/23277955/c36fc496-fa07-11e6-8759-d97548858799.png)

Nothing special... but someone need to tell you about that 😄 

One more thing... There are a way to add Portuguese of Portugal to October official languages? I can help with translation...

P.S: October is fuck*ng awesome!

**Comment by LukeTowers** [comment]
Yes, you can add a translation for Portuguese. See https://github.com/octobercms/october/pull/2648/files for an example of what files you will need to create and where you will need to make changes to add a new translation to October.

**Comment by dunets** [comment]
@LukeTowers nice, on the next week I will translate this! Thanks!
