### ISSUE TITLE
Error handler fails to properly respect NotFoundHttpException when not in debug mode

### ISSUE THREAD

**Issue by robinmalburn** [octobercms/october#2707]
##### Expected behavior
As per the [documentation](http://octobercms.com/docs/services/router#throwing-404-errors), raising a `Symfony\Component\HttpKernel\Exception\NotFoundHttpException`, calling `App::abort(404)` or I would imagine (though undocumented on that page) calling `abort(404)` should result in a 404 page being displayed with the relevant headers set.

##### Actual behavior
A standard 500 error page is returned, not the 404 error page.

##### Reproduce steps
Turn off debug mode and either raise a  `Symfony\Component\HttpKernel\Exception\NotFoundHttpException` or call `App::abort(404)` from any point in the system.  The simplest demonstration would be adding `App::abort(404)` into the `onStart()` function of a test page.

##### October build
Latest version installed via composer create-project - unsure where to actually find a build number in the code itself.

---

The issue seems to be caused by a mixture of code in the [ErrorHandler](https://github.com/octobercms/library/blob/master/src/Exception/ErrorHandler.php#L58) that is part of the October/Rain package and the [handleCustomError method](https://github.com/octobercms/october/blob/master/modules/system/classes/ErrorHandler.php#L54) that is part of ErrorHandler in October CMS itself.  The code in `handleCustomError` will almost certainly always return a value if debug mode is disabled and has no sense of allowing certain types of Exceptions to bubble (in fact, even if you don't implement an error route, it'll just make a default error page for you).  In the base ErrorHandler code, though, this code is called before checking if this should be a specially handled exception, and then if there's any type of non-null return value, that just gets returned to the user.

**Comment by daftspunk** [comment]
Feel free to submit a PR that addresses this.

**Comment by LukeTowers** [comment]
@robinmalburn could you submit a PR to fix this?

**Comment by robinmalburn** [comment]
I'm afraid we decided not to use October CMS after completing our initial feasibility study, so I haven't really looked at it since back in February 2017, so I wouldn't really be the best person to look at patching this issue.  Hopefully someone else in your community can pick up correcting the issue if hasn't been coincidentally corrected in an update since last year.

**Comment by LukeTowers** [comment]
@robinmalburn no problem. Do you mind sharing some of the factors that came up in your feasibility study for deciding against going with October?
