### ISSUE TITLE
Component required always triggered

### ISSUE THREAD

**Issue by skydiver** [octobercms/october#2712]
##### Expected behavior
If `'required' => false` is present on a component property, the property doesn't need to be mandatory

##### Actual behavior
When using `'required' => false` on a component property, the "The property is required." message is displayed

##### Reproduce steps
1. Create a component with a single property:
```
public function defineProperties() {
    $properties = [
        'some_property' => [
            'title'             => 'Demo Property',
            'description'       => 'Just a property',
            'default'           => '',
            'type'              => 'string',
            'required'          => false,
            'placeholder'       => 'Insert some text ...',
            'showExternalParam' => false
        ],
    ];
    return $properties;
}
```
2. Insert component on an empty page

3. Open component inspector and close without adding any value

##### October build
396 or 401

**Comment by LukeTowers** [comment]
Thanks for the report, I'll look into it when I have time!

**Comment by daftspunk** [comment]
I was able to replicate this.

**Comment by daftspunk** [comment]
This will be fixed in Build 411+
