### ISSUE TITLE
Hotkey javascript API not working

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#2713]
##### Expected behavior
$('html').hotKey({ hotkey: 'ctrl+s, cmd+s', callback: doSomething }); should work. 

##### Actual behavior
$('html').hotKey({ hotkey: 'ctrl+s, cmd+s', callback: doSomething }); does nothing.

##### Reproduce steps
Add 
```
<script>
$(document).ready(function() {
    $('html').hotKey({ hotkey: 'ctrl+s, cmd+s', callback: doSomething });
});
</script>
```
to your controllers partial. 

##### October build
Latest

**Comment by LukeTowers** [comment]
It may be because `ctrl+s` is a reserved combination by the browser, could you try it with another and let me know how it works?

**Comment by SebastiaanKloos** [comment]
@LukeTowers ctrl+i, ctrl+space are also not working :(

**Comment by SebastiaanKloos** [comment]
@LukeTowers when I use the data-hotkey with the same hotkey, the logic is working fine.

**Comment by LukeTowers** [comment]
@SebastiaanKloos How about targeting something more specific than `html`?

**Comment by SebastiaanKloos** [comment]
@LukeTowers already tried body. That does not work either.

**Comment by SebastiaanKloos** [comment]
@LukeTowers binding it to a span with no content solves the problem. It looks like it is not working with html and body. I'll update the documentation when I find some time.

**Comment by SebastiaanKloos** [comment]
It looks like the Javascript API is not working when there is no other hotkey on the page loaded by the data attributes. 

So the Javascript API requires a button with hotkey function on the page. So far I have not found the fix for this problem.

**Comment by LukeTowers** [comment]
@SebastiaanKloos Thanks for the additional information, keep me updated on when you find out what's causing the problem. Take a look at the JS file for hotkey handling in the modules/system/assets/ui/js/input-hotkey.js to see if you can find out what's causing that.

Does the console throw any errors when calling .hotKey without a hotkey data-api button setup on the page?

**Comment by SebastiaanKloos** [comment]
@LukeTowers thanks for your reply. I already took a look at this file. Could not find the problem. I will try and take a look deeper.

I discovered that the page needs a element with data-hotkey with a valid hotkey as the parameter.

**Comment by SebastiaanKloos** [comment]
@LukeTowers there is no output to the console.

**Comment by LukeTowers** [comment]
Try tossing some debugging statements into storm.min.js (or whatever JS file your backend loads that contains the hotkey plugin) on the call to .hotKey to see if it even gets triggered without the initial data-hotkey being present on the page.

**Comment by SebastiaanKloos** [comment]
Guess the logic is activated on the data-api. I'll try to figure out what is causing this.

**Comment by SebastiaanKloos** [comment]
Think I found the problem. But there is one little problem. I cannot regen the storm.min.js file. I already tried:
`php artisan october:util compile js` 
Is this command broken?

**Comment by SebastiaanKloos** [comment]
@LukeTowers I think this is causing the problem:
```
if (this.testConditions(ev)) {
            if (this.options.hotkeyVisible && !this.$el.is(':visible'))
                return

            if (this.options.callback)
                return this.options.callback(this.$el, ev.currentTarget)
        }
```

**Comment by SebastiaanKloos** [comment]
@LukeTowers My fault. I see what I did wrong now. Added this to the config of the declaration of the hotkey:

`hotkeyVisible: false,`

Everything is working fine now!

I'll update / add documentation about the hotkeys when I have some free time.

**Comment by SebastiaanKloos** [comment]
@LukeTowers already improved the docs. You can find the pull request here:
https://github.com/octobercms/october/pull/2716

**Comment by LukeTowers** [comment]
@SebastiaanKloos Made a comment in the PR, you'll need to resubmit.
