### ISSUE TITLE
Repeater not working properly with images

### ISSUE THREAD

**Issue by mesunil2010** [octobercms/october#2719]
##### Expected behavior
Repeater should create a new image uploader when new row is added

##### Actual behavior
When a new row is added, repeater duplicates the above row with images.

##### Reproduce steps
1.  Go to the backend with image uploader field within the repeater , then upload an image. If you try to create a new row, you will see that it's not blank new upload but has the above image attached with it.

##### October build
396

**Comment by LukeTowers** [comment]
This is a result of how the fileupload widget works. See #2708 for more information on the topic.
