### ISSUE TITLE
Ajax options for backend dropdowns.

### ISSUE THREAD

**Issue by djfrailey** [octobercms/october#2722]
##### Expected behavior
It would be nice if the Dropdown field type had an attribute that directed Select2 to bootstrap itself with the AJAX properties set in order to accomodate large record sets.

Current Use Case:
One of my clients requires the ability to have a Repeater that represents Content Sections. In one of those Content Sections they need to be able to place any number of "related" assets. I haven't had any luck in getting the recordfinder field widget to work inside of a repeater, so I'm using dropdowns (since they're searchable) and pulling the data programmatically from the database. Tests with a thousand records show response times of 4 seconds or greater, every time a new section is added.

##### Actual behavior
Dropdown field types load their data sets on page render, which causes a long load time for large datasets.

##### Reproduce steps
1. Create a backend controller and form
2. Add a repeater field with a dropdown
3. Set the dropdowns options to a function on your backend controller that returns all records in another table.
4. Seed the database with 1000-ish records.
6. Add a few items to the repeater with the dropdown and watch XHR request times.

**Comment by LukeTowers** [comment]
Feel free to add a PR to implement the functionality that you're talking about and I'll be sure to review it.

**Comment by djfrailey** [comment]
@LukeTowers 

Pull request #2735 addresses this functionality.

**Comment by daftspunk** [comment]
Why not use the `recordfinder` form widget?

**Comment by Narkoleptika** [comment]
@daftspunk 

> Why not use the recordfinder form widget?

@djfrailey 

> Tests with a thousand records show response times of 4 seconds or greater, every time a new section is added.

**Comment by daftspunk** [comment]
**Coyote**

> I'm just your memory. I can't give you any new information.

I'm sorry, @Narkoleptika, what?

**Comment by daftspunk** [comment]
This was [recently added to the select.js plugin's API](https://github.com/octobercms/october/commit/376a3b59e2a7bf2738f8c26c8dfdb99df5f568e1) and documented as such:

## AJAX search

Use the `data-handler` attribute to source the select options from an AJAX handler.

```html
<select
    class="form-control custom-select"
    data-handler="onGetOptions"
    data-minimum-input-length="2"
    data-ajax--delay="300"
    data-request-data="foo: 'bar'"
    ></select>
```

The AJAX handler should return results as an array.

```php
public function onGetOptions()
{
    $results = [
        'key' => 'value',
        ...
    ];

    return ['result' => $results];
}
```

This could potentially be added to the `dropdown` form widget as a `handler` option. Possibly it can be "unofficially" added right now using `attributes: data-handler: onGetOptions`.

Just not sure how this is any better than using the superior `recordfinder` form widget?

**Comment by osmanzeki** [comment]
@daftspunk 

I think it might be interesting to have this feature for when you can't cleanly use a recordfinder (like in a repeater for example). Being able to feed dropdowns with a custom Laravel query seems useful to me. This way I could also search for more than one type of Model but still display it in a flat list.

I was thinking about how I could build a feature I've seen on Shopify where you can create dynamic Collections based on rules and I feel like this could allow for a naive implementation.

I will play around with the idea with the "attributes" hack for now but just wanted to give my two cents on why this still makes sense in relation to the existence of the recordfinder field.

**Comment by Darkrogua** [comment]
**Not work**
I tried to use it in my partial plugin, search results are missing

`<label for='Form-field-Order-name'>Dropdown</label>
<select id='Form-field-Order-name' name='Order[product_id]' 
    class='form-control custom-select'
    data-handler='onGetProductName'
    data-minimum-input-length='1'
    data-process-Results='true'
    data-ajax--delay='300'
    ></select>`

**handler**
`
    public function onGetProductName() {
     	$post = $_POST["term"];
      	$results = Product::where('name', 'LIKE', "%$post%")->lists('name','id', 'active');
        return [
        	'**results**' => $results
    	];
    }
`
if I use an example from the documentation, the search will write not found for any values, but if I change to results, then the available values will be just empty, and if the values are not, it will write not found

**Comment by MaxNozhkin** [comment]
> **Not work**
> I tried to use it in my partial plugin, search results are missing
> 
> ```
> <label for='Form-field-Order-name'>Dropdown</label>
> <select id='Form-field-Order-name' name='Order[product_id]' 
>     class='form-control custom-select'
>     data-handler='onGetProductName'
>     data-minimum-input-length='1'
>     data-process-Results='true'
>     data-ajax--delay='300'
>     ></select>
> ```
> **handler**
> 
> ```
>     public function onGetProductName() {
>      	$post = $_POST["term"];
>       	 	$results = Product::where('name', 'LIKE', "%$post%")->lists('name','id');
>         return [
>         	'results' => $results
>     	];
>     }
> ```
> if I use an example from the documentation, the search will write not found for any values, but if I change to results, then the available values will be just empty, and if the values are not, it will write not found
> [The problem is in the video](https://yadi.sk/i/sRPBO0n-kUy2UQ)

Response must be like this, i read it in select2 docs, it works!
{
  "results": [
    {
      "id": 1,
      "text": "Option 1"
    },
    {
      "id": 2,
      "text": "Option 2"
    }
  ],
  "pagination": {
    "more": true
  }
}

**Comment by LarBearrr** [comment]
@MaxNozhkin Did you get this working?

@daftspunk What is it that I am missing here? I have setup a very basic method on my controller to display a custom select, basically just copy and pasting the docs. However, I am not seeing any options in my select dropdown.

controller.php:
```
public function dropdown()
    {

    }

public function onGetOptions()
    {
        $results = [
            'key' => 'value',
            'foo' => 'bar',
            'bar' => 'baz'
        ];

        return ['results' => $results];
    }
```

dropdown.htm:
```
<select
    class="form-control custom-select"
    data-handler="onGetOptions"
    ></select>
```

![image](https://user-images.githubusercontent.com/28734844/57704953-84c84e80-7628-11e9-90be-17fd45869b1b.png)
![image](https://user-images.githubusercontent.com/28734844/57704970-8d208980-7628-11e9-9bf1-abeb946700fb.png)
