### ISSUE TITLE
Preview or read only for form widgets

### ISSUE THREAD

**Issue by joelamltc** [octobercms/october#2724]
Is there any options or configs that can allow form widgets to be read only? 
That's mean cannot be able to edit anymore.
Let's say I want to have a backend user that can only view and not allow to edit any content in the CMS.
Thanks.

##### October build
v1.0.390

**Comment by LukeTowers** [comment]
You could extend the form fields, check what type of user is currently logged in with `BackendAuth` and then set the readonly / disabled property to true

**Comment by joelamltc** [comment]
@LukeTowers
```
/**
     * Set fields to disabled when the user is read only
     * 
     * @param  array  $fields  
     * @param  string $context 
     */
    public function filterFields($fields, $context = null)
    {
        if (request()->read_only_user) {
            foreach ($fields as $key => &$field) {
                $field->disabled = 1;
            }

            unset($field);
        }
    }
```
Currently, I am using the above function in model to filter the fields and set the fields to disabled, but the result is not expected.
For example, Media Finder and Rich Editor. These kind of form element does not respect the `disabled: 1`

**Comment by LukeTowers** [comment]
That would be separate issues. Feel free to see if you can figure out what's causing those widgets to ignore the disabled property and then submit a PR for a fix; unfortunately I don't have time to do that myself right now

**Comment by joelamltc** [comment]
@LukeTowers 
Could you plz mark it as a bug?

**Comment by LukeTowers** [comment]
Submit a separate issue specifically for "Mediafinder & Richeditor formwidgets don't support disabled" and include detailed information on the issue there.

**Comment by LukeTowers** [comment]
Apologies if I seemed rude, you were correct; it was an issue that affected all form widgets. I've fixed it in https://github.com/octobercms/october/commit/84b533454e1c803887adaea88ef2c7d611062d31. If you want to try that change out and let me know if it works for you, that'd be great.

Thanks for reporting this!

**Comment by joelamltc** [comment]
Hello, @LukeTowers. Thanks for the response.
Unfortunately, the fix https://github.com/octobercms/october/commit/84b533454e1c803887adaea88ef2c7d611062d31 does not take any effect on my side.
The form widgets like rich editor, repeater and media finder are visually being edited. Since I disabled the `Save` and `Save and Stay` button to not allow them to modify the content inside the widgets.
I can imagine that because these kind of form widgets is not directly using traditional HTML elements. The OctoberCMS built something else on top of the element, that's why the form widgets cannot be performed disabled attribute.
That what I personally clue in my mind, I don't know it is correct or not.
Thanks again!

**Comment by LukeTowers** [comment]
@joelamltc I think I may have an idea, how are you telling October to disable those fields? Are you doing it in the config or in the `filterFields()` method?

**Comment by joelamltc** [comment]
@LukeTowers 
```
  /**
     * Set fields to disabled when the user is read only
     * 
     * @param  array  $fields  
     * @param  string $context 
     */
    public function filterFields($fields, $context = null)
    {
        if (request()->read_only_user) {
            foreach ($fields as $key => &$field) {
                $field->disabled = 1;
            }

            unset($field);
        }
    }
```

**Comment by LukeTowers** [comment]
To fix it, I'll need to access the FormField object, which is a protected property. I can add an accessor to the FormWidgetBase class to enable access it, but I assume that it's a protected property for a reason. I'll wait for @daftspunk's input on this before making any further changes.

**Comment by joelamltc** [comment]
@LukeTowers Thanks and I am looking forward to it.

**Comment by daftspunk** [comment]
Individual issues created for this:

- Media Finder #2749
- File upload #2750
- Rich Editor #2751

**Comment by joelamltc** [comment]
@daftspunk Repeater widget has same issue i guess?

**Comment by daftspunk** [comment]
Not sure repeater supports a read only mode. Log another issue for it and we can take a look.

**Comment by LukeTowers** [comment]
@joelamltc I've added support for a read only mode to the repeater widget with https://github.com/octobercms/october/issues/2960

**Comment by joelamltc** [comment]
@LukeTowers @daftspunk Thanks for all the hard works and let's make OC better and better. Cheers 🎉🎉🎉

**Comment by romaldyminaya** [comment]
Does this case apply to the drodown readOnly behaviour as well ?

**Comment by iboved** [comment]
Repeater still doesn't support "readOnly" option. It supports the "disabled" option, but not "readOnly".

**Comment by LukeTowers** [comment]
@iboved feel free to submit a PR to add support or sponsor the issue so a core maintainer can fix it for you.
