### ISSUE TITLE
PDOException

### ISSUE THREAD

**Issue by yangzhipeng** [octobercms/october#2728]
What happens to my application occasionally？ What is the situation?
exception 'PDOException' with message 'SQLSTATE[HY000] [2002] ????ϵͳ???????ռ䲻??????????????????ִ???׽????ϵĲ?????
' in F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:55

**Comment by LukeTowers** [comment]
There isn't enough information here to do anything with. Please provide more information on your error and how to replicate it.

**Comment by yangzhipeng** [comment]
@LukeTowers   
exception 'PDOException' with message 'SQLSTATE[HY000] [2002] ????ϵͳ???????ռ䲻??????????????????ִ???׽????ϵĲ?????
' in F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:55
Stack trace:
#0 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(55): PDO->__construct('mysql:host=127....', 'root', 'october', Array)
#1 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(22): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array)
#2 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(60): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(49): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(175): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#5 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(67): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(3224): Illuminate\Database\DatabaseManager->connection(NULL)
#7 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(3190): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#8 F:\xampp\htdocs\october\vendor\october\rain\src\Database\Model.php(427): Illuminate\Database\Eloquent\Model->getConnection()
#9 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1813): October\Rain\Database\Model->newBaseQueryBuilder()
#10 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1787): Illuminate\Database\Eloquent\Model->newQueryWithoutScopes()
#11 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(3442): Illuminate\Database\Eloquent\Model->newQuery()
#12 F:\xampp\htdocs\october\vendor\october\rain\src\Extension\ExtendableTrait.php(380): Illuminate\Database\Eloquent\Model->__call('where', Array)
#13 F:\xampp\htdocs\october\vendor\october\rain\src\Database\Model.php(468): October\Rain\Database\Model->extendableCall('where', Array)
#14 F:\xampp\htdocs\october\plugins\mohsin\carousel\components\Carousel.php(36): October\Rain\Database\Model->__call('where', Array)
#15 F:\xampp\htdocs\october\plugins\mohsin\carousel\components\Carousel.php(36): Mohsin\Carousel\Models\Carousel->where('id', '=', '1')
#16 F:\xampp\htdocs\october\modules\cms\classes\CmsCompoundObject.php(170): Mohsin\Carousel\Components\Carousel->onRun()
#17 F:\xampp\htdocs\october\modules\cms\classes\Controller.php(895): Cms\Classes\CmsCompoundObject->runComponents()
#18 F:\xampp\htdocs\october\modules\cms\twig\Extension.php(117): Cms\Classes\Controller->renderPartial('hz_slide_search', Array)
#19 F:\xampp\htdocs\october\storage\cms\twig\39\39d9dcc3ea6f60e8b8ab7ef5a93475d21d1cdecf27442a84a0394cd85ec6b7a3.php(50): Cms\Twig\Extension->partialFunction('hz_slide_search', Array)
#20 F:\xampp\htdocs\october\vendor\twig\twig\lib\Twig\Template.php(387): __TwigTemplate_5783ddfe81fdeb2e697de7db9a0310593ed6beae7029b79a1f1e67e553ebcb5d->doDisplay(Array, Array)
#21 F:\xampp\htdocs\october\vendor\twig\twig\lib\Twig\Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array)
#22 F:\xampp\htdocs\october\vendor\twig\twig\lib\Twig\Template.php(366): Twig_Template->display(Array)
#23 F:\xampp\htdocs\october\modules\cms\classes\Controller.php(387): Twig_Template->render(Array)
#24 F:\xampp\htdocs\october\modules\cms\classes\Controller.php(215): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#25 F:\xampp\htdocs\october\modules\cms\classes\CmsController.php(48): Cms\Classes\Controller->run('/')
#26 [internal function]: Cms\Classes\CmsController->run('/')
#27 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(256): call_user_func_array(Array, Array)
#28 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('run', Array)
#29 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Cms\Classes\CmsController), Object(Illuminate\Routing\Route), 'run')
#30 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#34 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#35 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Cms\Classes\CmsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'run')
#36 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Cms\\Classes\\Cms...', 'run')
#37 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#38 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#44 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#45 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#46 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#48 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#49 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#52 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#55 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#58 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#61 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#64 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#66 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#67 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#68 F:\xampp\htdocs\october\index.php(44): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#69 {main}
Next exception 'Twig_Error_Runtime' with message 'An exception has been thrown during the rendering of a template ("SQLSTATE[HY000] [2002] ????ϵͳ???????ռ䲻??????????????????ִ???׽????ϵĲ?????
") in "F:\xampp\htdocs\october/themes/rainlab-relax/layouts/firstpage.htm" at line 14.' in F:\xampp\htdocs\october\vendor\twig\twig\lib\Twig\Template.php:402
Stack trace:
#0 F:\xampp\htdocs\october\vendor\twig\twig\lib\Twig\Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array)
#1 F:\xampp\htdocs\october\vendor\twig\twig\lib\Twig\Template.php(366): Twig_Template->display(Array)
#2 F:\xampp\htdocs\october\modules\cms\classes\Controller.php(387): Twig_Template->render(Array)
#3 F:\xampp\htdocs\october\modules\cms\classes\Controller.php(215): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#4 F:\xampp\htdocs\october\modules\cms\classes\CmsController.php(48): Cms\Classes\Controller->run('/')
#5 [internal function]: Cms\Classes\CmsController->run('/')
#6 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(256): call_user_func_array(Array, Array)
#7 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('run', Array)
#8 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Cms\Classes\CmsController), Object(Illuminate\Routing\Route), 'run')
#9 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Cms\Classes\CmsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'run')
#15 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Cms\\Classes\\Cms...', 'run')
#16 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#17 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#24 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Routing\Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#25 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#27 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#31 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#34 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#37 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#40 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#46 F:\xampp\htdocs\october\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#47 F:\xampp\htdocs\october\index.php(44): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#48 {main}

**Comment by LukeTowers** [comment]
Just as a quick suggestion, try changing the `host` setting of your database configuration to `localhost` instead of `127.0.0.1`

**Comment by yangzhipeng** [comment]
@LukeTowers   But before it is localhost will report an error。

**Comment by daftspunk** [comment]
The error message doesn't appear to be in English, but error code SQLSTATE[HY000] [2002] means the connection was refused. Here is the solution for fixing the `localhost` issue: http://anujyadavcse.blogspot.com.au/2014/01/laravel-xampp-mysql-artisan-migrate.html

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
