### ISSUE TITLE
Update Doc's a little unclear

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#2730]
Doc's Found here: https://octobercms.com/docs/backend/widgets#form-widget-save-data

I think you should add this line in the Doc's:

`use Backend\Classes\FormField;`

So my suggestion is to have the Doc's look like this:

# Saving form data

When the time comes to take the user input and store it in the database, the form widget will call the `getSaveValue` internally to request the value. To modify this behavior simply override the method in your form widget class.

```
public function getSaveValue($value)
{
     return $value;
}
```

In some cases you intentionally don't want any value to be given, for example, a form widget that displays information without saving anything. Return the special constant called `FormField::NO_SAVE_DATA` derived from the `Backend\Classes\FormField` class to have the value ignored.

```
use Backend\Classes\FormField;

public function getSaveValue($value)
{
     return \Backend\Classes\FormField::NO_SAVE_DATA;
}
```

**Comment by LukeTowers** [comment]
https://github.com/octobercms/docs is the correct place to post issues and PRs for the October documentation; please post this there instead. Thanks for the report though!

**Comment by ayumihamsaki** [comment]
Ok thanks Luke.
