### ISSUE TITLE
Fresh Install == NetworkError: 406 Not Acceptable

### ISSUE THREAD

**Issue by jawainc** [octobercms/october#2732]
##### Expected behavior
After fresh install, saving installed theme default layout should save.

##### Actual behavior
After Fresh install, re-saving default layout gives error "NetworkError: 406 Not Acceptable" and open a pop up with html

on removing script tags:

```
<script src="{{ 'assets/vendor/jquery.js'|theme }}"></script>
<script src="{{ 'assets/vendor/bootstrap.js'|theme }}"></script>
<script src="{{ 'assets/javascript/app.js'|theme }}"></script>
```

it saves successfully

##### Reproduce steps
As stated above

##### October build
396

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
