### ISSUE TITLE
align attribute slips through after pasting

### ISSUE THREAD

**Issue by marcelkorpel** [octobercms/october#2737]
##### Expected behavior
The rich text editor (or presumably the backend, as I can reproduce this behaviour in different Wysiwyg editors) heavily cleans the HTML markup after pasting text from a Word document (tested with LibreOffice). All unnecessary attributes are removed through white-listing.

##### Actual behavior
After pasting text from a new Word document that has text aligned other than 'left' (default), an `align="(center|right|justify)"` attribute slips through. Adjusting the alignment using the rich text editor just adds a corresponding `style` attribute, but leaves the `align` one untouched.

##### Reproduce steps
1. Open a new text document in LibreOffice (Word will presumably also be sufficient, but untested).
2. Enter some random text, preferable something without formatting, e.g. copied from a text editor.
3. Set alignment to 'justify'.
4. Copy the text.
5. Paste it into a rich text editor and view source. Now an `align="justify"` attribute will be visible. (Some editors like TinyMCE will initially show `style` attributes filled with content like `margin-bottom: 0in; line-height: 100%;`, but after a save and reload that clutter is gone, so there's probably (also) some logic in the back-end that removes those unwanted styles.)

##### Sample code
Open [align-justify.docx](https://github.com/octobercms/october/files/966858/align-justify.docx) in LibreOffice (Word might also do it).

##### Expected cleaned code
```html
<p>Foo bar</p>
```

##### Actual cleaned code
```html
<p align="justify">Foo bar</p>
```

##### October build
396

**Comment by LukeTowers** [comment]
I've been wanting to add in more serverside cleaning of tags to the editor so this could be integrated with that; unless you have a better idea.

**Comment by marcelkorpel** [comment]
No, this sounds like a good idea. Only: by 'the editor', you mean: the backend used by all the editors? I didn't dive into the sources too much, but I think cleaning should be done regardless of which editor (Froala, Redactor, etc.) a user has chosen.

Can you point me to the source where cleaning is done? Perhaps I can amend it myself and make a pull request. Thanks!

**Comment by LukeTowers** [comment]
I mean the richeditor formwidget. I could also integrate it into the codeeditor formwidget as well if that's what you're talking about. Plan is to integrate the serverside sanitization in such a way that other people can integrate into their custom editors as well.

**Comment by marcelkorpel** [comment]
I meant the richeditor formwidget indeed. In the codeeditor people actually see the markup and I assume that anybody who wants to edit raw HTML at least slightly knows what they are doing.

**Comment by daftspunk** [comment]
This really should be directed to the third party who created the WYSIWYG editor used in October CMS. It would appear they have [some support for it already](https://www.froala.com/blog/wysiwyg-editor/paste-from-word-and-excel-to-froala-editor) and these allowable tags and attributes are configurable in the backend.

**Comment by marcelkorpel** [comment]
But the built-in editor which I am using is Redactor, if I'm not mistaken, not Froala (at the moment I didn't install the WYSIWYG Editors plugin, only Static Pages, which uses the built-in editor).

Moreover, I guess this should be covered on the server-side, so no matter which editor one is using, the markup is cleaned (and this is already the case, I think, as the different editors initially allow different tags and attributes, but after saving and re-opening the markup is cleaned more thoroughly).

**Comment by LukeTowers** [comment]
The built in editor is Froala

**Comment by daftspunk** [comment]
We used Redactor originally, then switched to Froala. Build 396 referenced should ship with Froala? Please rephrase this issue with

**Sample code**
<div some="attribute">text</div>

**Expected cleaned code**
...

**Actual cleaned code**
...

This should make it simple.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
