### ISSUE TITLE
Backend list adding switch clickable buttons

### ISSUE THREAD

**Issue by ChVuagniaux** [octobercms/october#2739]
It would be nice if we can have switch buttons in backend list for can switch boolean status of a model.

By example publish unpublish item without need to open the update form.

~My idea is to implement it with a Backend Behaviors (`Backend\Behaviors\SwitchController`) that use the switch column type ( https://octobercms.com/docs/backend/lists#column-switch )~

This is a right way for you ? 

See PR https://github.com/octobercms/october/pull/2748

**Comment by LukeTowers** [comment]
That's a neat idea. You can implement this yourself in your plugin, and then submit a PR for a built-in behavior to integrate it into core.

**Comment by daftspunk** [comment]
Moving discussion to #2748
