### ISSUE TITLE
octobercms.com access problem

### ISSUE THREAD

**Issue by sozonovalexey** [octobercms/october#2740]
##### Expected behavior
Site should work as before.

##### Actual behavior
A lot of people form Russia can't open octobercms.com!

##### Reproduce steps
```
ping octobercms.com
PING octobercms.com (104.24.113.12): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3

```

**Comment by plyusninva** [comment]
+1.
need a dedicated ip-address, which differs from 104.24.112.12 and 104.24.113.12. These addresses were blocked due to banned in Russia online casino.

**Comment by daftspunk** [comment]
This is a known issue since we use CloudFlare to protect from attacks the IPs are shared. Residents of Russia should use a proxy to overcome this limitation. Eventually October will move to different infrastructure and this should resolve itself.  Sorry for any inconvenience.
