### ISSUE TITLE
Add support for path option to MediaFinder

### ISSUE THREAD

**Issue by AugmentBLU** [octobercms/october#2741]
Is there anyway we can specify the default path of a particular mediafinder field? 

I'm using the mediafinder widget in builder and would like to have the media select popup default to a sub-directory. I'm using Rackspace cloud storage and navigating through this can be a little slow - defaulting to a specific directory would be useful and help speed up the process.

**Comment by LukeTowers** [comment]
Not right now, but that's something that we could look at adding in the future.

**Comment by daftspunk** [comment]
Not a bad idea, a Pull Request for this would most likely be accepted.

**Comment by LukeTowers** [comment]
Will probably be implemented during the improvements coming for adding metadata to the Media Library

**Comment by everyx** [comment]
> 
> 
> Will probably be implemented during the improvements coming for adding metadata to the Media Library

Hi, @LukeTowers  It's possible add this default path option to File upload?

**Comment by LukeTowers** [comment]
@everyx what does that even look like / what is the purpose of that?

**Comment by everyx** [comment]
> what does that even look like / what is the purpose of that?

the `path` option should set `file upload` default upload path like this issue's `path` option for `MediaFinder`.

I think it's a easier way than hard code manual  move to organize files from plugin.

**Comment by LukeTowers** [comment]
@everyx probably not, files are stored in the directory that their model class determines, there's no reason to configure that location in multiple locations. If you want to change the place that files get uploaded to then change cms.storage.uploads.folder or extend System\Models\File with your own class and override the getStorageDirectory() method and then use that model in the relationship definition used by the fileuploader.

**Comment by LukeTowers** [comment]
And this proposal is to change the default location the mediafinder widget looks for media instead of always using the root media folder, not really changing the upload path.

**Comment by everyx** [comment]
@LukeTowers  ok, thanks for you comment :)
