### ISSUE TITLE
QUESTION: How to get a property value from from component installed on specific page?

### ISSUE THREAD

**Issue by dunets** [octobercms/october#2744]
I created my component with an option "perPage", that acept an number and set the limit of works displayer per page...

[![enter image description here][1]][1]

    public function defineProperties()
    	{
    		return [
    			'perPage' => [
    				'title' => 'Number os works per page',
    				'description' => 'How many works do you want to display per page?',
    				'default' => 9,
    				'validationPattern' => '^[0-9]+$',
    				'validationMessage' => 'Only numbers allowed'
    			],
    			'sortOrder' => [
    				'title' => 'Order of Works',
    				'description' => 'How do you want to order the actors',
    				'type' => 'dropdown',
    				'default' => 'newest',
    			],
    		];
    	}

It work's great with GET implementation... but on my project I need to implement AJAX everywhere, so I need to load pages via AJAX, and I need to know what the number was setted on a component... How I can get this number?

    //my layout code
    function onOpenWorkList()
    {
        
        $this['works'] = Category::where('slug', input('slug'))->first();
        
        $this['categories'] = Category::all();
        
        $this['active_category'] = input('slug');
        
        $this['perPage'] = "";  // HERE IS THE CODE
        
        return [
            '.home_categories' => $this->renderPartial('work_list_categories_post'),
            '.container' => $this->renderPartial('work_list')
        ];
    }

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/954mF.png
  [2]: https://i.stack.imgur.com/tvbGg.png

**Comment by dunets** [comment]
![image](https://cloud.githubusercontent.com/assets/6217617/23823048/a4446896-0651-11e7-9471-a3d1c2922267.png)
so easy... 😅

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
