### ISSUE TITLE
Call to a member function connection() on null

### ISSUE THREAD

**Issue by graker** [octobercms/october#2746]
Hello

I decided to update my OctoberCMS installation after a while. I updated plugins from the interface, then October itself, using `composer update`. But after the update is finished, I got permanent error:

`FatalErrorException in Model.php line 3146: Call to a member function connection() on null`

It happens when I try to access any site pages or even run php artisan (even without commands). It seems that it has something to do with database but I'm not sure what. I just updated packages with composer and that's it. What is the best course of action to fix it?

Thanks!

**Comment by LukeTowers** [comment]
Which Model.php? What does your composer.json look like?

**Comment by graker** [comment]
This one: `vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php`

And like this:

`{
    "name": "october/october",
    "description": "October CMS",
    "homepage": "http://octobercms.com",
    "keywords": ["october", "cms", "octobercms", "laravel"],
    "license": "MIT",
    "authors": [
        {
            "name": "Alexey Bobkov",
            "email": "aleksey.bobkov@gmail.com",
            "role": "Co-founder"
        },
        {
            "name": "Samuel Georges",
            "email": "daftspunky@gmail.com",
            "role": "Co-founder"
        }
    ],
    "support": {
        "issues": "https://github.com/octobercms/october/issues",
        "forum": "http://octobercms.com/forum/",
        "docs": "http://octobercms.com/docs/",
        "irc": "irc://irc.freenode.net/october",
        "source": "https://github.com/octobercms/october"
    },
    "require": {
        "php": ">=5.4",
        "october/rain": "~1.0",
        "october/system": "~1.0",
        "october/backend": "~1.0",
        "october/cms": "~1.0",
        "laravel/framework": "5.0.*",
        "illuminate/html": "5.0.*"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0",
        "phpunit/phpunit-selenium": ">=1.2"
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php",
            "tests/UiTestCase.php",
            "tests/PluginTestCase.php"
        ]
    },
    "scripts": {
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
`

**Comment by LukeTowers** [comment]
Change `"laravel/framework": "5.0.*",` to `"laravel/framework": "5.1.*",` and run `composer update` again, then let me know if that worked..

**Comment by LukeTowers** [comment]
Better yet, use the current version of the `composer.json` file, yours looks all kinds of messed up. https://github.com/octobercms/october/blob/master/composer.json

**Comment by graker** [comment]
Thanks, @LukeTowers replacing composer.json fixed it. I also had to remove old composer.lock file because it had dependencies composer was unable to resolve.

I guess my build was just too old.
