### ISSUE TITLE
File Upload: Disabled support

### ISSUE THREAD

**Issue by daftspunk** [octobercms/october#2750]
##### Expected behavior
File upload form widget should support disable functionality.

##### Actual behavior
File upload still works when disabled.

##### Reproduce steps

Working with the test plugin
1. Open october\test\models\user\fields.yaml
1. Change fileupload widget definition to add disabled

        photo:
            label: Photo
            span: auto
            type: fileupload
            commentAbove: Single image upload inside a tab.
            mode: image
            imageHeight: 150
            imageWidth: 150
            tab: Single Image
            disabled: true

##### Notes

The widget should detect when disabled or readonly is passed by the configuration and simply activate preview mode.

**Comment by pavelmgn** [comment]
If i disabled fileupload from filterFields, its not work. dump return disabled: true; But widget not disabled;

**Comment by WaskiWabit** [comment]
This does not seem to work when accessing the fields from filterFields() within a model.

```javascript
public function filterFields($fields, $context = null) {
    $fields->photos->disabled = true;
}
```

**Comment by LukeTowers** [comment]
@WaskiWabit I believe there's an issue for that, it's because the filterFields occurs too late in the lifecycle to properly affect the fileupload form widget as it has already loaded it's configuration by that point and no longer looks at the config of the base FormField object that is being modified by filterFields.

**Comment by WaskiWabit** [comment]
Well that's a bummer :( Then how come other form fields can be set to readOnly or disabled? It seems like it should be all or nothing.

**Comment by LukeTowers** [comment]
@WaskiWabit other form fields are just plain FormField classes, it's when it comes to FormWidgets that the problem occurs with the configuration being changed after the FormWidget has already pulled it from the FormField instance that it's attached to. 

It's not something that's going to stay that way forever, it's just a currently open issue that could be addressed. See #3639 for further discussion.
