### ISSUE TITLE
Extending current Lists sort feature

### ISSUE THREAD

**Issue by leocavalcante** [octobercms/october#2752]
##### Expected behavior
I want to be able to override the default behavior of Lists sort feature to make sorts based on something else than a Model column.

##### Actual behavior
Currently, we cannot make sorting on Lists something different than a orderBy on a Model column [widgets/Lists.php#L475](https://github.com/octobercms/october/blob/master/modules/backend/widgets/Lists.php#L475)

##### Reproduce steps
--

##### October build
396

**Comment by LukeTowers** [comment]
Feature requests are not to be posted as issues unless you plan on implementing it yourself and are using the issue as a pre-PR. 

Please post these into http://octobercms.com/forum/chan/feature-requests instead.

**Comment by daftspunk** [comment]
Even as a feature request this lacks detail, specifically what exactly is the expectation. The sorting column must be related to a Model column because the sorting occurs at the database layer.
