### ISSUE TITLE
Framework and Framework Extra files aren't minimized

### ISSUE THREAD

**Issue by lrs** [octobercms/october#2753]
##### Expected behavior
/modules/system/assets/css/framework.extras.css
/modules/system/assets/js/framework.js
/modules/system/assets/js/framework/extras.js

Should be minified/uglified to help with loading speeds.

I can do this myself of course however there's a chance it would be overwritten with a build update.

##### Actual behavior
Above files aren't minifified/uglified

##### Reproduce steps
Install latest build.

##### October build
396

**Comment by SebastiaanKloos** [comment]
Isn't there a minified parameter in the config files?

**Comment by LukeTowers** [comment]
It would depend how you loaded it. If you used the asset combiner:
```twig
<script src="{{ ['@framework', '@framework.extras'] | theme }}"></script>
```
and then set your asset minification config settings, then yes, it should minify it for you. If you're referencing it directly then it won't.

**Comment by lrs** [comment]
Thanks @LukeTowers, @SebastiaanKloos I was using what I thought was the standard way:
 ```
{% framework extras %}
```

Using this and setting `'enableAssetMinify' => true` in config/cms.php combines and minifies!

Closing ticket.

**Comment by lrs** [comment]
Oops, now the AJAX framework is broken for me. Reverting back to `{% framework extras %}` resolves it.

**Comment by daftspunk** [comment]
We could potentially minify it using `october:util compile assets` and toggle between the two based on `cms.enableAssetMinify` for the framework extras tag. That sounds like a great idea.

**Comment by SebastiaanKloos** [comment]
+1 @daftspunk

**Comment by lrs** [comment]
Thanks for keeping this issue open. Have you had any thoughts on how to progress with this?

**Comment by maartenmachiels** [comment]
+1 would be nice!

**Comment by You85** [comment]
+1

**Comment by maartenmachiels** [comment]
Beste,

We zijn op vakantie tot 11 september.
Alvast bedankt voor het begrip en tot dan.

Mvg,

Maarten Machiels

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by LukeTowers** [comment]
@lrs @SebastiaanKloos @maartenmachiels @You85 Support has been added in the latest develop branch thanks to @jimcottrell!

**Comment by BahodurSaidov** [comment]
Any docs for this feature ?

**Comment by LukeTowers** [comment]
@BahodurSaidov it's enabled automatically when `cms.enableAssetMinify` is enabled: https://github.com/octobercms/october/blob/master/config/cms.php#L186-L198
