### ISSUE TITLE
Gets redirected to /favicon.ico upon backend login when not logged in on front end

### ISSUE THREAD

**Issue by Hambern** [octobercms/october#2754]
##### Expected behavior
If I'm not logged in via the Rainlab.User plugin and tries to login to the backend I expect to get redirected to the dashboard upon login.

##### Actual behavior
I get redirected to /favicon.ico instead. But if I first login into the frontend, this all works.

##### Reproduce steps
Install Rainlab.User, do not log in, visit the backend login, login.

##### October build
403

**Comment by SebastiaanKloos** [comment]
Hm not sure if this thing is an OctoberCMS problem. Maybe you could create an issue in the Rainlab.User repo?

**Comment by Hambern** [comment]
True that
