### ISSUE TITLE
Support passing arrays to the SyntaxParser used by RainLab.Pages for field generation

### ISSUE THREAD

**Issue by dunets** [octobercms/october#2758]
Sup!

When I needed to add a color picker to static page, I discovered that that expects to receite an array... and attribute `availableColors=""` didn't work as expected...

My solution can be "noobby" but, why you don't add some code like that, to filter the string? :)

![image](https://cloud.githubusercontent.com/assets/6217617/24008857/de64d4ee-0a6a-11e7-9087-34fd9ac86874.png)

```
public function prepareVars()
    {
        $this->vars['name'] = $this->getFieldName();
        $this->vars['value'] = $value = $this->getLoadValue();
		
		if(!is_array($this->availableColors))
			$this->availableColors = preg_split('/[\ \,]/', $this->availableColors);
		
        $this->vars['availableColors'] = $this->availableColors;
        $this->vars['isCustomColor'] = !in_array($value, $this->availableColors);
    }
```

#tryingtobeuseful

**Comment by LukeTowers** [comment]
I believe this is already supported in the Dropdown and Radio buttons fields through the syntax parser. Support was added for it in https://github.com/octobercms/library/commit/4b27731a30f0abf1646472cf2a8f755a95281b0d, so I think it should be relatively easy to add support for it to the colorpicker widget as well.

When I have the time to review this in more detail I'll take a look at doing that for you.

**Comment by daftspunk** [comment]
```
availableColors="red|yellow|green"
```

**Comment by zaxap83** [comment]
I have the same problem
`availableColors="red|yellow|green"` is not working :(

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone
