### ISSUE TITLE
Snippets bug on saving

### ISSUE THREAD

**Issue by dunets** [octobercms/october#2759]
I did something wrong?

![image](https://cloud.githubusercontent.com/assets/6217617/24013805/7d75f8ec-0a7a-11e7-921c-471ac932f1af.png)

On a static page:
![image](https://cloud.githubusercontent.com/assets/6217617/24013823/8eb91ec2-0a7a-11e7-85de-98fff74c3d08.png)

Result:
![image](https://cloud.githubusercontent.com/assets/6217617/24013838/9b8376fc-0a7a-11e7-84fc-e3f2112020b8.png)

And the same on Static page:
![image](https://cloud.githubusercontent.com/assets/6217617/24013859/af65655e-0a7a-11e7-8370-d6aa256b64f1.png)

**Comment by LukeTowers** [comment]
What is this issue even about?

**Comment by dunets** [comment]
@LukeTowers the result image is what I see on front-end... it's a code from editor... I need to add some code on snippet to make this work?

**Comment by LukeTowers** [comment]
I still have no idea what you are trying to do or how it's going wrong.

**Comment by plyusninva** [comment]
@dunets clear cache after add snippet

**Comment by LukeTowers** [comment]
@dunets Did @plyusninva's suggestion help?

**Comment by dunets** [comment]
@LukeTowers  I have changed the structure of my project... so I don't know, but I will test it tomorrow

**Comment by plyusninva** [comment]
@LukeTowers It helps me.

**Comment by daftspunk** [comment]
[Wrong repo](https://github.com/rainlab/pages-plugin)
