### ISSUE TITLE
Problem integrating October CMS with Laravel App.

### ISSUE THREAD

**Issue by GreenWhiteDev** [octobercms/october#2761]
##### Expected behavior
If I desired just a CMS, I could have opted for just Wordpress or drupal, but the main reason I desire October CMS is to integrate it with my laravel application. I am building a university web portal with laravel, and I will like to have the University website and the School Portal be developed together in a single project. That's the reason I chose laravel, because it is a laravel based CMS

I suggest that we make a version of October that can integrate with a Laravel App, or create a tutorial on how to do so. There are so much issues on this subject, so I think it'll help if we attend to this issue critically. 

##### Actual behavior
I went through a tiring process of integrating the projects together, but it hasn't been successful so far. The controllers keep throwing up errors. Although I was able to get passed the CmsController class, then it didn't go further. 

I could have gone further in trying to make it work, but while searching online for a solution, I found out that this issue has existed for a very long time, and there hasn't been a certain solution. If there is actually a solution, I'll appreciate if you share with me, and the laravel community of users. 

And I think October CMS is one of its kind. It's awesome. 

##### Reproduce steps
Try to make October Cms work with a Laravel app. 
##### October build
It's the latest build as of the date associated with this issue.

**Comment by SebastiaanKloos** [comment]
OctoberCMS is using Laravel, but the system is completely different to Laravel. OctoberCMS is based on plugins you can add to extend some functionality. I think the most people who are using OctoberCMS use it from the start of a project. I think the rewriting of your application uses less time than the conversion of your code. But feel free to write some documentation if you succeed to write some conversion.

**Comment by GreenWhiteDev** [comment]
Yeah.. 

I'll try to see if it'll work, but I think it's an issue that can be looked into.

**Comment by LukeTowers** [comment]
How exactly do you envision October integrating with a Laravel app? If you mean run them concurrently, that doesn't make much sense since October is Laravel, so why wouldn't you just have October run your Laravel app?

Also, what version of Laravel are you using?

**Comment by GreenWhiteDev** [comment]
I'm trying to create a University Portal for student and staff management, that's the app I'm trying to develop. I'm using laravel to develop the app. 

I also desire to develop the University website alongside the portal. I considered designing a CMS from scratch, but I later thought of using an already built CMS based on the Laravel framework, and that's how I came across October CMS. 

If I required October to run my laravel app, I think I will be missing some functionalities given by Laravel. October CMS doesn't make use of the app/ and routes/ directory.

What I mean by integrating October and Laravel, is that a user can be routed to the CMS and the App when required. But how to make this routing possible is a challenge to me. 

I was able to route the users request to the CmsController class. I had issues with the Extendable trait, which was later resolved. The next challenge was to make the controller class. I did a lot modifications to get this far, and  I found out that it could work, but there's gonna be a lot modifications, which is something that I don't have enough time to do, considering the project schedule. 

So I'm only giving a suggestion, if we can see a way to make this work. 

I'm using laravel 5.3,

**Comment by LukeTowers** [comment]
That may be where you're running into issues. October uses 5.1 LTS and will move on to using 5.5 LTS when that is released. 

I'm still not sure what you're trying to accomplish with Laravel that's impossible in October. Everything custom in October is handled via plugins (https://octobercms.com/docs/plugin), and you can define custom routes for your application in a plugin's `routes.php`

**Comment by GreenWhiteDev** [comment]
Thank you for the tip. Maybe that's where I had the  problem. I appreciate your help on this topic, I'll read through the docs on October plugins, I'm sure I'll find what I need there. 

I would really love to work with October CMS. Thanks for the heads up.
