### ISSUE TITLE
SVG version of BrokenImage.php

### ISSUE THREAD

**Issue by Quezler** [octobercms/october#2762]
[https://github.com/octobercms/library/blob/master/src/Database/Attach/BrokenImage.php](https://github.com/octobercms/library/blob/master/src/Database/Attach/BrokenImage.php)

Is the base64 of that image also available in the svg format?

**Comment by daftspunk** [comment]
IIRC that image was created in Photoshop, so no SVG is available sorry. Feel free share it back, if you make one!

**Comment by lrs** [comment]
I think this should be okay:

https://gist.github.com/lrs/47cba2ab7925c4ccdec80deb5ff01f77

**Comment by daftspunk** [comment]
Nicely done @lrs, thanks for that!

**Comment by daftspunk** [comment]
For the archives, SVG contents is as follows:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200"><defs><linearGradient id="0" x1="0" y1="200" x2="200" y2="0" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#e4e4e4"/></linearGradient></defs><path fill="url(#0)" d="m0 0h200v200h-200z"/><path d="m114 0l-41.25 102-72.75-29.5v26l56.5 17.5-12.5 84h26l.25-59.25 43.75-70.75 86 49v-55l-28 5-56-19 24-50" fill="#c84530"/></svg>
```

Now to figure out what we can use it for...

**Comment by lrs** [comment]
"Now to figure out what we can use it for..." Ha ha, SVG icons FTW!

**Comment by Quezler** [comment]
It honestly surprises me how tiny the text is for the svg ✂️

**Comment by lrs** [comment]
The source? Yeah, SVG is very economical and widely supported now. Also, one size fits all!
