### ISSUE TITLE
CMS settings section not affected by cms.convertLineEndings

### ISSUE THREAD

**Issue by ghost** [octobercms/october#2766]
When convertLineEndings=true all line endings should be UNIX \n

Only the code section and the markup section have UNIX \n, the settings section has Windows \r\n which makes working in an external editor annoying as the files have mixed line endings.

**Comment by Nyorai** [comment]
Yes that's correct, and as i said this results in the htm file containing a mixture of line endings.

**Comment by daftspunk** [comment]
Should be easy enough to fix, will take a look soon. Thanks!
