### ISSUE TITLE
the field cannot show the existing data

### ISSUE THREAD

**Issue by Jimiwcy** [octobercms/october#2771]
[](https://octobercms.com/forum/post/cannot-show-the-saved-relation-field-in-backend-form)

please fix

**Comment by Jimiwcy** [comment]
https://octobercms.com/forum/post/cannot-show-the-saved-relation-field-in-backend-form

**Comment by SebastiaanKloos** [comment]
Please use the issue format provided by OctoberCMS in GitHub.

**Comment by LukeTowers** [comment]
There is no description here @Jimiwcy. Please put effort into contributing to October through issues or pull requests, otherwise we're not going to put effort into helping you.

**Comment by LukeTowers** [comment]
Closed due to lack of further explanation from @Jimiwcy

**Comment by daftspunk** [comment]
Come on, Jimmy!

**Comment by daftspunk** [comment]
As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.
