### ISSUE TITLE
Class 'ZipArchive' not found"

### ISSUE THREAD

**Issue by bkrajendra** [octobercms/october#2775]
##### Actual behavior

I've just updated my hosting server to another one.
I'm getting error:
```
Update failed

"Class 'ZipArchive' not found" on line 52 of /home/..../public_html/vendor/october/rain/src/Filesystem/Zip.php
```
I understand it must be due to ZipArchive extension. 
Is there any alternative? or is this error related to some other issue?

##### Reproduce steps
update

##### October build
updating to latest build from 382

**Comment by MRokas** [comment]
You've to install `php-zip` package.

**Comment by LukeTowers** [comment]
@bkrajendra Did installing the php-zip extension solve your problem?

**Comment by bkrajendra** [comment]
I'm on shared linux server. As per docs I guess this library comes in built in Php5.5 above. I'm already on PHP5.6. Not getting what could be the issue.

**Comment by MRokas** [comment]
php-zip isn't a built-in feature. So you've to either request your host to add it, or move over to better one.

**Comment by bkrajendra** [comment]
okk. I'll get back after having chat with my host Admin.

**Comment by daftspunk** [comment]
The `ZipArchive` is a server requirement for running October CMS.

http://octobercms.com/docs/setup/installation#system-requirements

It is a fairly common feature to have activated in most hosting environments. If you need some authority figure to make this statement, let us know. Good luck!

**Comment by bkrajendra** [comment]
Thank you all, got it resolved as hosting admin enabled it from hosting backend.

**Comment by iancwoodward** [comment]
Godaddy has Archive_Zip v.0.1.2 which I've installed from the cPanel pear package installer. This doesn't seem to have fulfilled the requirement. Has anyone else installed October on goDaddy?

It tells me I have to include the module to my script like this:
ini_set("include_path", '/home/[hash]/php:' . ini_get("include_path") );
