### ISSUE TITLE
Problem with required plugins @var array Plugin dependencies

### ISSUE THREAD

**Issue by LucasZdv** [octobercms/october#2778]
Severe error.
When a plugin is installed, the required plugins are being omitted
for example the next plugins require RainLab.Translate y both have the `@var array Plugin dependencies`

https://github.com/jawainc/simplecontact/issues/45 @jawainc

    /**
     * @var array Plugin dependencies
     */
    public $require = ['RainLab.Translate'];

[exaple 1 (ServerPilot)](https://github.com/Awebsome/ServerPilot/blob/master/Plugin.php)
[exaple 2 (SimpleContact)](https://github.com/jawainc/simplecontact/blob/master/Plugin.php) 

[Video with problem reproduction](https://share.viewedit.com/qEAppWKcTu3dZNsDpyMAsP)
==

**Comment by LukeTowers** [comment]
@LucasZdv Are you on the develop version or the stable version? enableEdgeUpdates in config/cms.php as this issue was supposed to be fixed very recently in #36 (which this is a duplicate of by the way).

**Comment by LucasZdv** [comment]
Thanks, I have not noticed this option, it works!
