### ISSUE TITLE
Issues with manifest.json (404 not found)

### ISSUE THREAD

**Issue by zocheyado** [octobercms/october#2782]
So I have not used touched my october install in a while and I am running into an issue. I copied my DB and my entire directory to a new server, everything seems to be working except some of the javascript. I am getting a GET 404 on manifest.json and then it breaks my javascript. Any ideas how this can be fixed? the manifest file is present in the root and has no special permissions.

**Comment by LukeTowers** [comment]
You'll need to add an exception to .htaccess for that file. I'm assuming that your previous server either didn't allow .htaccess files or was using a server that didn't use them at all.

**Comment by zocheyado** [comment]
I ended up fixing this by renaming manifest.json to manifest.text and updating the meta tag to grab accordingly. It seems like this is an issue with apache 2.4 not grabbing json files. (At least that is what I gathered) Anyways thanks!
