### ISSUE TITLE
Backend editor Portuguese vowel characters does not occur without retyping 

### ISSUE THREAD

**Issue by VijayWilson** [octobercms/october#2783]
Hi there, we did a project to one of our client in octobercms. Everything is goes fine. Our client is in portugal and has one issue. We still dont know whether it is an issue or not. What he is facing is, in general text editors or notepad applications  whenever he type the portuguese vowel character such as (ã, ẽ, õ), at first he'l press the back-quote ( ` ) symbol and type the corresponding letter like (a, e, o) then he'l get the corresponding letter, but in october cms backend editor whenever he types the character it does not occur in that way, but when he deletes the character through (backspace key) and when he retypes, it seems to be working. This issue seems to be strange, we have provided as much details as we can, is there any solution for this. My doubt is how does it occurs on the second time in the backend editor and why don't the first time itself.

**Comment by VijayWilson** [comment]
One additional information, the client's OS is MAC which is native portuguese

**Comment by LukeTowers** [comment]
I've never heard of typing unicode characters like that. Macs support holding down the latin letter key and then pressing the number of the character that you want to use, does that work for him?

**Comment by VijayWilson** [comment]
Hi,
It was not working. We tried using "e" letter but dint work out. Also we could not understand which may be  the "latin letter" key. Can you provide a clear explanation. Clients keyboard is based on portuguese

**Comment by LukeTowers** [comment]
For me, using a north american layout on OSX El Capitan, holding down the e key will bring up a popup that lists the variations èéêëēėę which can be selected by also pressing the desired key (1 through 7) at the same time after the popup appears.

**Comment by VijayWilson** [comment]
@LukeTowers  Thanks. It worked for our client.  **Holding down the e key will bring up a popup that lists the variations èéêëēėę**.

**Comment by LukeTowers** [comment]
Happy to have helped!
