### ISSUE TITLE
Upgrading to version 407 killed my October

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#2785]
Everything was working fine and updated. Then today I updated from latest Octobercms 3xx version to 407 and it has killed my October now. See screenshot when I try to log into the dashboard / admin cp:

![qqq](https://cloud.githubusercontent.com/assets/17784082/24514912/cfac9334-156d-11e7-9981-08c11a5ca652.png)

I would be very angry right now! But I saved and backed up everything yesterday!

I think October needs to add a warning message before updating their versions to back everything up before upgrading to it's users.

Anyway, would like to know what is the reason for this error message.

Thanks.

**Comment by LukeTowers** [comment]
The problem was caused by a recent change to the backend navigation code. It was fixed in https://github.com/octobercms/october/commit/d1c9b1a6f1511824cbc74c7cd31926cace58fb9c, which should be included in Build 407. What PHP version are you running on?

**Comment by ayumihamsaki** [comment]
Hi Luke, running: PHP 7.0.17 (though I want to upgrade it to PHP 7.1.3 in a bit). Any advice as I want to try again upgrading when I have re-installed my backup version?! Just wondering if there is a conflict somewhere causing this issue?

**Comment by LukeTowers** [comment]
Not sure, are you able to provide me your backup version so I can try updating from it to see why the fix for that issue wasn't downloaded? 

If you're fine with disabling the NetSTI.Backend plugin, then you will be able to upgrade without any problems, the issue is triggered by that plugin.

**Comment by ayumihamsaki** [comment]
Can I reply back to you in 1 hour, I want to try and remove the NetSTI.Backend plugin and try upgrading again. I have switched to php 7.1.3 now as well. I don't mind to send you my backup also. But let me see if I can upgrade first, will message back in a bit.

**Comment by LukeTowers** [comment]
Sounds good, let me know how that goes for you

**Comment by ayumihamsaki** [comment]
Ok, managed to upgrade now doing a "Force Update" to Version 407 and seems to be ok now.

The plugin that was causing the error might have been this one: NetSTI.Backend plugin

I did not realise at the time it is a Backend Theme Plugin and can be found here:

https://octobercms.com/plugin/netsti-backend

So I guess this is causing the issue.

Thanks Luke for your time and help. See I really like your profile picture of you flying with oxygen brave man!

Anyway will close this issue now.

**Comment by LukeTowers** [comment]
So does it work now with the NetSTI.Backend plugin enabled still?

Thanks for the compliment, flying's pretty awesome :)

**Comment by ayumihamsaki** [comment]
I'm not going to use that plugin now as the author doesn't update it. There were some coding issues with it, as I noticed in Dev Tools it was saying 404 error for a missing image etc. So maybe best just to not use it. Have used another account to leave feedback with regards to that plugin for other October users to know before installing it.

**Comment by LukeTowers** [comment]
Alright. The problem arises when people use the BackendNavigation class to modify existing menus, so if you run into it again, let me know. It should be fixed as of https://github.com/octobercms/october/commit/d1c9b1a6f1511824cbc74c7cd31926cace58fb9c but I don't know why that wasn't included when you updated your October instance.

**Comment by daftspunk** [comment]
Build 408 has been created to address this. Sorry about the fatal error, @LukeTowers' fix missed the release by a hair.

**Comment by LukeTowers** [comment]
A [release note](http://octobercms.com/support/article/rn-6) has been created to document this.
