### ISSUE TITLE
No way for layouts to extend other layouts

### ISSUE THREAD

**Issue by acobster** [octobercms/october#2787]
##### Expected behavior
I expect layouts to be able to extend other layouts.

##### Actual behavior
When I try to use the `extends` tag to extend the default layout from another layout, I get:

> View [default] not found.

Are hierarchical layouts just not supported by design? I can understand that the different anatomy of October views means reworking Twig to some extent, but this seems like a pretty central (and useful!) feature of Twig to give up.

##### Reproduce steps

layouts/default.htm:

```
description = "Default layout"
==
<!DOCTYPE html>
<html>
  <head>
    ...
  </head>
  <body>
    {% block page_container %}
      <div class="container>
        Default content
      </div>
    {% endblock %}
  </body>
</html>
```

layouts/other.htm:

```
description = "Other layout"
==
{% extends 'default' %}

{% block page_container %}
  <nav class="side-nav">...</nav>
  <div class="interior-container>
    {% page %}
  </div>
{% endblock %}
```

pages/interior-page.htm:

```
title = "Example Interior"
url = "/interior"
layout = "other"
==
<p>Interior page content</p>
<p>Lorem ipsum dolor sit amet</p>
```

##### October build
1.0.407

**Comment by LukeTowers** [comment]
See https://stackoverflow.com/questions/42659363/can-templates-be-nested-in-octobercms/42725245#42725245 for how to implement this sort of functionality in October.
