### ISSUE TITLE
Feature Request - Placeholder to appear within a separate tab when editing a CMS page

### ISSUE THREAD

**Issue by KirbyFox** [octobercms/october#2792]
Allow each Placeholder to appear within a separate tab when editing a CMS page.

For example, if a page had a three column layout, the 'Edit CMS Page' would include separate tabs and WYSIWYG editors for managing the content within each column.

Using the Static Pages plugin is not desirable, as it places any new tabs within 'Settings', which is totally confusing for clients.

**Comment by daftspunk** [comment]
- I would think this is solved using content or partials? 
- Placeholder content is defined within the page itself with `{% placeholder %}`.
- The Static Pages plugin [recently had some work done](https://github.com/rainlab/pages-plugin/commit/d402a2d279d0c80756d642f6ef679aa12c01f1c1).

Bit lost as to the problem we're solving.

**Comment by KirbyFox** [comment]
I thought content and partials was for sharing content between multiple pages.

This request was to allow a user to edit each section of a page separately.

It would improve usability if the user could edit each {% placeholder %} section via the backend. 

i.e. if a page had a three column layout, it would allow the user to edit each column separately.

**Comment by LukeTowers** [comment]
Not a bad idea, worthy of some further thought. @KirbyFox are you able to mockup for us what that would look like?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
