### ISSUE TITLE
"Undifined index: updates"

### ISSUE THREAD

**Issue by goeroe** [octobercms/october#2793]
I'm getting the following error when trying to check for updates:
"undefined index: updates" on line 33 of ..\modules\system\controllers\updates\_ update_list.htm

**Comment by NickMChambers** [comment]
Try 'Force update'.

**Comment by goeroe** [comment]
Not getting the "force update" button in the modal...

- Check for updates
- Modal appears "Software update - Loading available updates..." with Cancel button only 
- Error appears
- Close error
- Modal keeps "loading" (indicator)

**Comment by goeroe** [comment]
Is there a command line command for it?

**Comment by goeroe** [comment]
ok "php artisan october:update --force" did the job for now but still getting the error so...

**Comment by daftspunk** [comment]
What build are you using? Make sure all the files are writable (777) when updating.

**Comment by goeroe** [comment]
Build 409

**Comment by daftspunk** [comment]
Thanks for using edge updates and helping with the testing! This will be fixed in Build 410+

**Comment by goeroe** [comment]
The pleasure is all mine :) Almost every day (read build) feels like Christmas. Keep up the awesome work!
