### ISSUE TITLE
UX on missing plugins message from the warning modal

### ISSUE THREAD

**Issue by andrewfenn** [octobercms/october#2794]
I have a few things I would like to point out about making the missing plugins notification easier to understand and use.

For reference I am discussing the following image below..

![auto_install](https://cloud.githubusercontent.com/assets/409265/24638647/71d33f24-1914-11e7-9bdf-fd53d73e9d3b.png)

- This message doesn't tell me what it's a dependency on? OctoberCMS itself? A plugin? I think it would be better if the wording made this clearer to understand.
- Although I can copy and paste the name "RainLab.User" into the plugin install search screen the name on the plugin is different so it's not immediately obvious what the plugin is. This wouldn't be a problem if the search screen only showed one plugin when entering "RainLab.User", however it shows multiple plugins leading to confusion as seen in the screenshot below...

![marketplace](https://cloud.githubusercontent.com/assets/409265/24638845/0830799a-1916-11e7-9718-2d0ab8acab0c.png)

- Is it possible to have some option to either go directly to the plugin to install or a way to auto install all the missing plugins from the warning model message? This would mean less going backwards and forwards

**Comment by LukeTowers** [comment]
All good points that would be excellent improvements. I like the idea of being able to install dependencies from the dialog. Do you have any ideas for how we could handle dependencies on custom (non-marketplace) plugins?

**Comment by daftspunk** [comment]
Agree with all of this. It needs more work. We should probably include a button (or URL flag?) on the updates page to check for dependencies and install them.

**Comment by LukeTowers** [comment]
This has been fixed by #5077 & https://github.com/octobercms/october/commit/e8dca35c15a16dd31ef5b21d80375bbd5eec1c94
