### ISSUE TITLE
[Feature Request] Option to pass interlacing to JPEG thumbnail generation

### ISSUE THREAD

**Issue by Teranode** [octobercms/october#2795]
As the title describes it would be nice to have the option to use interlacing when generating thumbnails.

**Comment by LukeTowers** [comment]
Interesting idea, you planning on making a PR for it?

**Comment by Teranode** [comment]
Im currently looking into it, but i have some other bugs to go through first.

**Comment by LukeTowers** [comment]
Sounds good, I'd welcome the PR if you do implement it.

**Comment by daftspunk** [comment]
Just go straight to PR, no need to keep this open.

**Comment by LukeTowers** [comment]
Related: https://github.com/octobercms/library/pull/267

**Comment by LukeTowers** [comment]
Merged in https://github.com/octobercms/library/commit/e8eb45530149c997c1023c9757e0d60bb1c8fe67
