### ISSUE TITLE
Sorting errors NestedTree using SoftDelete

### ISSUE THREAD

**Issue by PopcornPHP** [octobercms/october#2802]
##### Expected behavior
Deleted records must be involved in sorting

##### Actual behavior
The deleted records do not participate in the sorting, as a result, the field values nest_left, nest_right and nest_deep become incorrect

##### Reproduce steps
You need to create a sorted list of records consisting of several branches, delete some ancestors, re-sort records and restore deleted records. The database will show incorrect the values nest_left, nest_right and nest_deep

##### October build
412

**Comment by alxy** [comment]
I would guess that this is a special (complicated) use case. I'd suggest to implement your own NestedTree trait, that takes SoftDeleted records into account.

**Comment by PopcornPHP** [comment]
Maybe. Only there are already many projects with this functionality. And this problem is not obvious

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by PopcornPHP** [comment]
Hi. Sorry for the long wait. I created the fork, made all the necessary changes.
https://github.com/PopcornPHP/oc-test-plugin

Instructions step by step - you can see on these videos:
https://youtu.be/l83IUJk8JeA
https://youtu.be/qCPbunImS7c

Search for bugs - these are random actions. You can create records, reoder records, remove, restore, reorder and create again and so on. Only random actions. I think that there are more than two bugs

**Comment by LukeTowers** [comment]
@PopcornPHP Create a Pull Request to the base oc-test-plugin repo, we're not going to want to clone your repo to download and test it. Make it easier for us by making the PR to the base repo from your repo :)

**Comment by PopcornPHP** [comment]
@LukeTowers OK, I created :)

You can see it here
https://github.com/daftspunk/oc-test-plugin/pull/39

**Comment by daftspunk** [comment]
Replicated then fixed by https://github.com/octobercms/library/commit/8535756d220db6559781c26433be8fb7b94aeb5e

This will be available in Build 433+
