### ISSUE TITLE
Custom attributes in validation lang files is not working

### ISSUE THREAD

**Issue by mosid** [octobercms/october#2804]
##### Expected behavior
Setting the `attributes` array changes the showing key in validation.

##### Actual behavior
Nothing happens when setting custom attribute

##### Reproduce steps
Change any attribute key in the validation lang file  of any plugin or module as in the following 
```php 
//changing the email attribute in the system validation.php
// the email attribute should be changed to 'Your email'
 attributes=>[
   'email'=>'Your email'
]
```
 

##### October build
latest

**Comment by LukeTowers** [comment]
These reproduction instructions make no sense. Please explain more in depth what the problem is.

**Comment by daftspunk** [comment]
These instructions are not specific enough for anyone to follow. Please try again.

**Comment by HekmatFavid** [comment]
There is no any parameter in user plugin's lang folder,  you can set attributes in Modules\System\Lang in attributes array.
I test, and it's work properly!

**Comment by LukeTowers** [comment]
@HekmatFavid don't change core files (i.e. files under the modules folder), they will be removed in the next update. See http://octobercms.com/docs/plugin/localization#overriding instead
