### ISSUE TITLE
Data-api elements that are updated through renderPartial method are not registered in JS.

### ISSUE THREAD

**Issue by CptMeatball** [octobercms/october#2805]
Ajax Method in Component:

    Author\Namespace\Components\ComponentName.php:

    public function onUpdateMethod(){

        //UpdateMethod logic

        return [
          "#partial" => $this->renderPartial('::partial.htm'),
        ];
    }

Generated Markup

    Author\Namespace\Components\ComponentName\PartialName.htm:

    
    <a href="#" data-request-data="parent_id: {{comment.id}}" data-request="{{ __SELF__ }}::onCreateReply">Reply</a>
    <a href="#" data-request-data="comment_id: {{comment.id}}" data-request="{{ __SELF__ }}::onDeleteComment">Delete</a>

##### Expected behavior
`data-api` elements inside the new partial that are rendered invoke the registered Ajax methods in the `ComponentName.php`.

##### Actual behavior
`data-api` elements inside the new partial that are rendered do not invoke registered Ajax methods in the `ComponentName.php`.

##### Reproduce steps
0. Create new custom plugin and component.
1.  In the Component View create elements that use the `data-api`.
2. Create corresponding method(s) in `ComponentName.php`. 
3. Create a new Component Partial that will be inserted through `$this->renderPartial('::partial.htm')` that also has `data-api' elements.
3. Click the `data-api` elements.

##### October build
412

**Comment by CptMeatball** [comment]
<a href="#" data-request-data="parent_id: {{comment.id}}" data-request="{{ __SELF__ }}::onCreateReply">Reply</a>
    <a href="#" data-request-data="comment_id: {{comment.id}}" data-request="{{ __SELF__ }}::onDeleteComment">Delete</a>

**Comment by CptMeatball** [comment]
Oh darn. Apparently `{{__SELF__}}` isn't  defined in an updated partial. Let me check if this fixes it.

**Comment by LukeTowers** [comment]
Perhaps we should look into supporting __SELF__ in the renderPartial method
of components then.

*Luke Towers*
email: luke@luketowers.ca
mobile: (306) 537 - 1725 <13065371725>
web: LukeTowers.ca <http://luketowers.ca/>

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
