### ISSUE TITLE
OctoberCMS Static Pages plugin Menu with description

### ISSUE THREAD

**Issue by mittultechnobrave** [octobercms/october#2809]
I have a website say something like this http://sellleaseproperty.com.au/ and if you mouse hover on the text ***Click here
to begin your real estate journey***, you will be able to see Menus with description. 

The thing is, I am using [OctoberCMS](https://octobercms.com/), [Static Pages plugin](http://octobercms.com/plugin/rainlab-pages) and while creating a menu, I want to do exactly the same thing for each menu but it seems like I am unable to do so as I can not see there is any option to add description while creating a menu using **Static Pages plugin**. 

Can someone guide me how can I achieve this. 

Thanks

**Comment by jan-vince** [comment]
You will have to extend Pages plugin with your own plugin with extra field like this:

```php
/*
* This should be added to YOUR OWN Plugin.php file!
 */
public function boot() {

Event::listen('backend.form.extendFields', function ($widget) {

	if (
		!$widget->getController() instanceof \RainLab\Pages\Controllers\Index ||
		!$widget->model instanceof \RainLab\Pages\Classes\MenuItem
	) {
		return;
	}

	$widget->addTabFields([
		'viewBag[note]' => [  // I am using viewBag so I don't have to create extra database table or column
			'tab' => 'janvince.smallextensions::lang.static_menu.notes',
			'label' => 'janvince.smallextensions::lang.static_menu.add_note',
			'commentAbove' => 'janvince.smallextensions::lang.static_menu.add_note_comment',
			'type' => 'textarea'
		]
	]);
});

}
```

*Or just [grab my plugin](https://octobercms.com/plugin/janvince-smallextensions) as I needed this on one project and have already added this. Feel free to fork my plugin or just edit it to your needs.*

**Comment by mittultechnobrave** [comment]
Thank you.. Highly Appreciated.
