### ISSUE TITLE
Custom Contact Form in Partials and use in Static Pages plugin

### ISSUE THREAD

**Issue by mittultechnobrave** [octobercms/october#2810]
I have used [OctoberCMS](http://octobercms.com/), [Static Pages](http://octobercms.com/plugin/rainlab-pages) plugin, through which I am creating Static Pages.

The thing is, I have created one contact form in Partial like below. 

*contactform_snippet.htm - **Markup***

[![enter image description here][1]][1]

*contactform_snippet.htm - **Code***

[![enter image description here][2]][2]

And below is the **Static Page** which I have created and used *contactform_snippet.htm* which I just created. 

[![enter image description here][3]][3]

And below is *Preview* how its looking like.

[![enter image description here][4]][4]

  [1]: https://i.stack.imgur.com/Nh9xd.png
  [2]: https://i.stack.imgur.com/IMzCI.png
  [3]: https://i.stack.imgur.com/AIhT7.png
  [4]: https://i.stack.imgur.com/qDjDy.png

The thing is, Even if I click on "Submit" button, it is not doing anything.

I also changed the form code from `data-request="{{ __SELF__ }}::onSendInquiry"` to `data-request="onSendInquiry"`but then I am getting below error saying: 

>AJAX handler 'onSendInquiry' was not found.

The thing here is, similar thing I have created and copied in **CMS Page** instead of **Static Page** and all is working there with validations and email being sent.

So My question is how can make the same thing work in **Static Pages** here using **Snippets**. I know the can be achieved via creating **Components** but I have so many of forms and I want to implement something like this to make it work. Any thoughts what should I need to make this work here ? 

Thanks

**Comment by NickMChambers** [comment]
@mittultechnobrave I generally create a plugin for my contact forms and then reference that within a CMS page. Otherwise, your client is likely to (unwittingly) remove the snippet when editing the Static Pages.

**Comment by mittultechnobrave** [comment]
Yes but we have a role management through which we wont allow him to do so by denying him for this section to add/edit any snippets and allowing him only to drag and drop for cms pages.

**Comment by NickMChambers** [comment]
@mittultechnobrave Still think it's easier to use a CMS page for that.

**Comment by mittultechnobrave** [comment]
May be not sure. But as of now I want to deal with this scenario as I have so many contact forms and creating plugin for all those contact forms should not be an ideal way I guess. 

Do you believe I can solve this issue using the way I am doing right now.

**Comment by mittultechnobrave** [comment]
Ok Guys, Eventually I made it work by putting my doing this `data-request="onSendInquiry"` in my form and putting below code in my **default.htm** layout file.

```
function onSendInquiry()
{
    // Collect input
    $name = post('name');
    $email = post('email');
    $subject = post('subject');
    $msg = post('msg');

    // Form Validation
    $validator = Validator::make(
        [
            'name' => $name,
            'email' => $email,
            'subject' => $subject,
            'msg' => $msg,
        ],
        [
            'name' => 'required',
            'email' => 'required|email',
            'subject' => 'required',
            'msg' => 'required',
        ]
    );

    if ($validator->fails())
    {
        
        $messages = $validator->messages();
        throw new ApplicationException($messages->first());
        //Retrieving all error messages for all fields
        /*foreach ($messages->all() as $message) {
            throw new ApplicationException($message);
        }*/
        //throw new ApplicationException($messages);
    }
    

    // All is well -- Submit form
    $to = System\Models\MailSetting::get('sender_email');
    //$to = System\Models\MailSettings::get('sender_email');
    //$to = config('mail.from.address');
    //$to = 'mittul@technobrave.com';
    //die($to);
    $params = compact('name','email','subject','msg');
    Mail::sendTo($to, 'yourappname.website::mail.contactform', $params);
    return true;
}]
```

Was so close yet so far. Got it in the end. Thanks

**Comment by LukeTowers** [comment]
Future reference, this issue would be better suited to the [RainLab.Pages repository](https://github.com/rainlab/pages-plugin)

**Comment by mittultechnobrave** [comment]
OK Thank you @LukeTowers . Highly Appreciated for reference link.
