### ISSUE TITLE
Theme Information file form fields with validation

### ISSUE THREAD

**Issue by mittultechnobrave** [octobercms/october#2811]
I am just checking this part https://octobercms.com/docs/themes/development#theme-information and it seems like I am able to add form field in my *theme.yaml* file in one of my themes. 

I was just wondering how can I made those fields mandatory or give required and other validations to the fields which I have created ? 

Any idea ?

**Comment by LukeTowers** [comment]
The FormController behaviour that works in the backend to render those fields right now doesn't support configurable validation. You can flag fields with `required: true` but that will only put a visual indicator that it is required. As a side note, I'm not sure how useful required validation would be on a theme settings page - if the user never visits the settings page then they'll be empty just as if they had and not put any values into the fields you mark as required.

If you really wanted to add validation yourself, you would have to write a plugin that would extend the controller that renders theme settings, detect when your theme was enabled, and then hook into available events to perform the validation manually on the submitted data.

**Comment by mittultechnobrave** [comment]
Thank you for Information. However, I would love to see this feature in future version of OctoberCMS .. As we developers always put conditions like if theme users wont add required fields, we will show the default items .. It would be always useful you know .. 
Thanks for conclusion.

**Comment by daftspunk** [comment]
I guess we figured that a theme must exist in a pre-configured state in the first place, so default values are always needed, making required fields redundant.

Please be really specific as to avoid the [XY problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem). i.e we know you need a required field, but why do you need it?

This should help us get a deeper understand of the issue and offer a solution, where a required field may seem like the obvious approach.

**Comment by mittultechnobrave** [comment]
Thanks @daftspunk. 
Appreciated.

**Comment by daftspunk** [comment]
Ok, so we good? Cheers

**Comment by mittultechnobrave** [comment]
Yup indeed sir.. :)
