### ISSUE TITLE
Editor for contents

### ISSUE THREAD

**Issue by Kilgaloon** [octobercms/october#2812]
It would be good to have some kind of a html editor for contents. It will help people that doesn't know any knowledge about html to edit page easily.

**Comment by NickMChambers** [comment]
@Kilgaloon https://octobercms.com/plugin/anandpatel-wysiwygeditors

**Comment by LukeTowers** [comment]
Contents of what? You're going to have to be more specific. For sections of the site that are managed by clients I usually use the [RainLab.Pages plugin](https://octobercms.com/plugin/rainlab-pages).
