### ISSUE TITLE
Can not add new folder in Media Manager

### ISSUE THREAD

**Issue by CHERiPP** [octobercms/october#2814]
##### Expected behavior
The Apply button in the "Add folder" window in the Media Manager should add a new folder

##### Actual behavior
An error occurs: "The file type used is blocked for security reasons."

##### Reproduce steps
Add folder in media manager

##### October build
413

I think this happens after the update "Build 413 - Security fixes for Media Manager and Asset Manager". First, it checks for a valid file type,  but if it's a folder, it doesn't have an extension and is therefore not included in the list of defaultExtensions

**Comment by gregoryloichot** [comment]
Same here !

**Comment by Mubeen-Inamdar** [comment]
Same problem on my end!

**Comment by LukeTowers** [comment]
Problem line: https://github.com/octobercms/october/blob/master/modules/cms/widgets/MediaManager.php#L355

I'll let @daftspunk know about it and we'll probably have a fix by end of day today. Thanks for catching this!

**Comment by Mubeen-Inamdar** [comment]
@LukeTowers thanks for the speedy response!

**Comment by daftspunk** [comment]
Fixed in Build 414+
