### ISSUE TITLE
Backend sub-menu: Not visible on Windows 7 ie10

### ISSUE THREAD

**Issue by wateryoma** [octobercms/october#2817]
##### Expected behavior
Sub-menu visible

##### Actual behavior
Sub-menu not visible

##### Reproduce steps
Make backend sub-menu, check if it's visible on ie10 win7

##### October build
396

wasn't diggin much into this issue, but as workaround if i add
```css
#layout-sidenav{
    position:relative;
}
```
sub-menu visible again

**Comment by SebastiaanKloos** [comment]
Please update to the last version of October. This issue is already fixed.

**Comment by wateryoma** [comment]
October build

415

problem still exists

**Comment by LukeTowers** [comment]
Try refreshing your cache

**Comment by wateryoma** [comment]
yep, cleared both - browser and october, still problem exists, also problem exists on cms settings page (reason same - position: absolute)
![2017-04-26 2 38 28](https://cloud.githubusercontent.com/assets/5065147/25412173/b033a90e-2a29-11e7-957d-1cad924f5416.png)

**Comment by daftspunk** [comment]
Does [this expression](https://github.com/octobercms/october/blob/master/modules/backend/assets/js/backend.js#L221) ring true in your browser?

```
!!window.MSInputMethodContext && !!document.documentMode
```

**Comment by wateryoma** [comment]
false
window.MSInputMethodContext is undefined
document.documentMode is 10
i'm using virtualbox win8 ie10 from here https://github.com/magnetikonline/linuxmicrosoftievirtualmachines

**Comment by daftspunk** [comment]
Please find an equivalent expression that does.

**Comment by wateryoma** [comment]
```js
navigator.userAgent.match(/MSIE\s?(\d+)(?:\.(\d+))?/i)!==null && !!document.documentMode
```
expression
```js
navigator.userAgent.match(/MSIE\s?(\d+)(?:\.(\d+))?/i)[1]
```
can be used to get ie version in case if you might want to apply some version specific fixes [here](https://github.com/octobercms/october/blob/d642605f879bdaa823195558cad560a9e1be9b6e/modules/backend/assets/js/backend.js#L221)

**Comment by wateryoma** [comment]
too tired to make any pr, but 
```js
if(navigator.userAgent.match(/MSIE\s?(\d+)(?:\.(\d+))?/i)!==null && !!document.documentMode){
```
in backend.js line 221 solves my issue

**Comment by daftspunk** [comment]
- Just target IE11 and below
- We don't want to target "Microsoft Edge" or IE12+ if that is such a thing

How does it perform in 10? Any other issues or is it generally OK? It'd be great if we can get a summary of what versions of IE we should actually support. I'm guessing IE10 will be the cut off.

**Comment by wateryoma** [comment]
you may use  
https://github.com/ded/bowser
for more specific detect conditions, like
```js
if (bowser.msie) { // IE <= 11
```

generally october in ie 10 is ok, sub menu issue is only one i've been reported so far, but i'm not using ie for testing or development myself

**Comment by wateryoma** [comment]
and one more thing 
changes at backend.js line 221 for proper ie detection solves only issue with sub-menu, to fix settings menu (/backend/system/settings) i still need
```css
.layout-absolute{
position: relative;
}
```

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
