### ISSUE TITLE
'Required' validation doesn't work correctly on relation fields when creating form

### ISSUE THREAD

**Issue by Jimiwcy** [octobercms/october#2823]
##### Background Description 
I am using this tutorial to make a subform (https://octobercms.com/forum/post/howto-how-to-put-a-subform-to-manage-a-relationship-in-a-backend-form)
For some field,  i also make a custom validation for checking the data on the subform
**Field: required|customValidation**

##### Expected behavior
Empty item on subform -> Show message
Have repeating item on subform-> Show message

##### Actual behavior
Updating form -> work
When the subform is empty-> show message
When the subform has duplicated item-> show message

Creating form -> Fail
When the subform is empty-> still can submit the form
When the subform has duplicated item-> still can submit the form

##### Reproduce steps
 subform:
(https://octobercms.com/forum/post/howto-how-to-put-a-subform-to-manage-a-relationship-in-a-backend-form)

validation:
https://octobercms.com/docs/services/validation
```class CustomValidator extends validate
{

    public function validateLanguageCode($attribute, $value, $parameters)
    {
        $arr = array();

        var_dump($value);

        foreach($value as $item){
            array_push($arr,$item->attributes["language_code"]);
        }

        if(count($arr) !== count(array_unique($arr)))
            return false;

        return true;
    }

}
```

##### October build
396

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by LukeTowers** [comment]
Closing as no further information was provided by @Jimiwcy
