### ISSUE TITLE
CMS/Assets - Create directory error mesage

### ISSUE THREAD

**Issue by tombien** [octobercms/october#2824]
##### Expected behavior
Create new directory

##### Actual behavior
Returns message "Only the following file types are allowed: jpg, jpeg, bmp, png, gif, css, js, woff, svg, ttf, eot, json, md, less, sass, scss"

##### Reproduce steps
Go to CMS modul, to Assets, click on +Add, click Create directory, write some name, click Create.

##### October build
414

**Comment by daftspunk** [comment]
Fixed in Build 415+ (27062ddfa045d8b0a2fcf75326363108ad640f7b)
