### ISSUE TITLE
Calendar files (.ics) are blocked file types

### ISSUE THREAD

**Issue by tillathenun** [octobercms/october#2828]
My clients use the Media Manager to upload content for their marketing e-mails and often they include links to Outlook calendars saved in the **.ics** format.

It seems that's no longer a supported file type?

**Comment by LukeTowers** [comment]
Related #2368

**Comment by daftspunk** [comment]
We will look at adding this. For now, you can allow ics extension at CMS config.
At config/cms.php, add:

```
'fileDefinitions' => [
    'assetExtensions' => array_merge(FileDefinitions::get('assetExtensions'), ['ics']),
],
```

**Comment by LukeTowers** [comment]
The default file extensions also exclude a lot of document related formats (i.e .doc, .docx, .xls, .xlsx, etc. etc.)

**Comment by daftspunk** [comment]
This is solved by a simple PR. Someone find the time and it will be accepted.

**Comment by LukeTowers** [comment]
Fixed in https://github.com/octobercms/library/commit/96583717797a1f0670b6261546733bc28f52f6b0

**Comment by Wittner** [comment]
Trying to add this for .pptx files and getting this error:

FatalThrowableError in cms.php line 333:
Class 'FileDefinitions' not found

Should this not be a configuration somewhere withing the cms itself or at least have the ability to add file types manually through cms.php? It seems odd to be changing the source to allow new file types? Anyway, this is not working for me trying to add .pptx as a file type for upload to the media library.
