### ISSUE TITLE
php artisan down throws uncaught 503 and yields an error page

### ISSUE THREAD

**Issue by Al-Q** [octobercms/october#2830]
##### Expected behavior
`php artisan down` throws `exception HttpException(503)`.  
October should catch that exception and activate *maintenance mode*.

##### Actual behavior
October does not catch the exception.  
Instead, an error page is issued:  
>    We're sorry, but an unhandled error occurred. Please see the details below.
>    .../vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php line 41
>    Type: Undefined
>    Exception: Symfony\Component\HttpKernel\Exception\HttpException
```
\* 
\* @throws \Symfony\Component\HttpKernel\Exception\HttpException 
*/ 
public function handle($request, Closure $next) 
    { 
        if ($this->app->isDownForMaintenance()) { 
            throw new HttpException(503); 
        } 
    return $next($request); 
    } 
```

##### Reproduce steps
1. Load the website in a browser  
1. On the command line in the top directory of the website where the artisan script resides (eg /var/www/website/), issue `php artisan down`  (response is `Application is now in maintenance mode.`)  
1. Reload the website in the browser  (error message is seen)  
1. `php artisan up` successfully reverses the error and the website is back to normal  

##### October build
415 (and previous)

**Comment by daftspunk** [comment]
This should render the view `modules\system\views\maintenance.php` (new file to be created) that can be overriden at the app level as `maintenance.php` in the base directory next to the `index.php` file.

This results in 2 levels of maintenance mode

- Hard mode: App is killed at middleware level, static HTML page is shown
- Soft mode: App is locked out for non-admin users only and CMS maintenance page is shown

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone
