### ISSUE TITLE
OctoberCMS backend main menu having sub menus of different plugins into it

### ISSUE THREAD

**Issue by mittultechnobrave** [octobercms/october#2832]
I have one requirement in OctoberCMS which I want to implement backend (Admin side) and here below what I want to implement. 

I am using [Builder Plugin](http://octobercms.com/plugin/rainlab-builder) and I already have created so many plugins which are showing at the top of header with their respective names and links in admin (backend). And if I click on it, I can do whatever I want (CRUD operation) which works fine for all those plugins.

But now I want only one main menu (Say for example - "**Plugins**") and If I click on it or hover on it, I should weather be able to see all the listed plugins which I will add and can able to add in future if I create more. 

I should be able to see those plugin links on hover or on left side and it should have an ability to add/remove those links. 

Currently I am trying to do this in builder plugin *backend menu* but I am unable to do so as it is keep conflicting with *code* field for those menu tab. Hence I am now looking forward with some other way if I can implement. 

Can someone guide me how can I achieve this ?

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

**Comment by mittultechnobrave** [comment]
@LukeTowers  OK. Thanks.  I will make sure about this next time around. 
I have already raised questions there but no response so far so thought here if I can get some help. No worries.  If you can help me on this. 

Thanks

**Comment by LukeTowers** [comment]
I don't really understand the question, perhaps if you could clarify on StackOverflow what information you have to work with (your input), and what you want it to look like when it's all said and done (your desired output), that would be helpful.

**Comment by mittultechnobrave** [comment]
Actually, currently I have a main menu for my each plugin at backend at header ... but I want to minimize my menu list by appending all my plugin menu links to particular one main menu link.
