### ISSUE TITLE
Repeater content disappears after updating the system

### ISSUE THREAD

**Issue by fresswolf** [octobercms/october#2838]
##### Expected behavior
Repeater content is untouched when updating the system

##### Actual behavior
Text fields in repeater forms show up empty for content entered prior to version 416.
It might be due to the new repeater group functionality? I noticed that the json generated with the current version of october differs from json generated with previous versions. When printing out repeater fields, previous versions created json objects {"1":{"field1":"text", "field2":"text"}}, while the current build produces arrays: [{"field1":"text", "field2":"text", "_index": 1}]

##### Reproduce steps
Add some repeater content with multiple text fields in a version prior to 416. Then update to 416 and try to edit the content. The fields are empty.

##### October build
416

**Comment by LukeTowers** [comment]
Related: https://github.com/rainlab/translate-plugin/issues/252
Fix was applied in https://github.com/octobercms/october/commit/cb56c61e36d3c13505a7be21ebaf5fe8a0370195, will be available in Build 417+

**Comment by brenodouglas** [comment]
i related this issue in 2015 
[1662](https://github.com/octobercms/october/issues/1662)

**Comment by LukeTowers** [comment]
@brenodouglas the index is no longer stored as the key for the array items, it's now merged into the array element object as `_index`

**Comment by daftspunk** [comment]
Sorry for the confusion here guys, this issue has flip flopped.

When group mode is disabled: 

```
{"1":{"field1":"text", "field2":"text"}}
```

When group mode is enabled:

```
[{"field1":"text", "field2":"text", "_index": 1, "_group": "textarea"}]
```

---

Still deciding if we should change it to *When group mode is enabled*:

```
{"1":{"field1":"text", "field2":"text", "_group": "textarea"}}
```

**Comment by daftspunk** [comment]
Try Build 417, just published. The repeater will no longer store indexes, hopefully it has no poor outcomes. There are none we can think of.

When group mode is disabled:

[{"field1":"text", "field2":"text"}]
When group mode is enabled:

[{"field1":"text", "field2":"text", "_group": "textarea"}]
