### ISSUE TITLE
datepicker widget default value

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#2840]
##### Expected behavior
Add default value for datepicker with formExtendFields function.

##### Actual behavior
This adds nothing to the field.

##### Reproduce steps
Extend fields and add a $field->value to the datepicker field. 

##### October build
416

Does anybody know how to add a date to the default value of the field?

**Comment by LukeTowers** [comment]
Default values are only applied in create contexts right now, is that what you're encountering?

**Comment by SebastiaanKloos** [comment]
@LukeTowers this is not working on the create form.

**Comment by daftspunk** [comment]
Seems to work fine here: https://github.com/daftspunk/oc-test-plugin/blob/e0bc2b4aa01303631bfa6e437df6636951c01230/models/post/fields.yaml#L41

Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
