### ISSUE TITLE
Live development server does not work in conjunction with browser-sync

### ISSUE THREAD

**Issue by colthreepv** [octobercms/october#2842]
##### Expected behavior
 * Start `php artisan serve` => server available at `http://localhost:8000`
 * Execute `browser-sync start --proxy=localhost:8000`

I was expecting to have the page opened on localhost:3000 (default browser-sync port) proxying OctoberCMS homepage

##### Actual behavior
The connection stays open indefinitely, nothing gets outputted by php artisan serve

##### October build
v1.0.412 installed via composer

**Comment by daftspunk** [comment]
So `php artisan serve` needs to support a custom port, is that it?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
