### ISSUE TITLE
List formatting is dropping when trying to paste a list from a clipboard

### ISSUE THREAD

**Issue by lautsevich** [octobercms/october#2850]
##### Expected behavior
When you paste formatted list from a clipboard (e.g. copied from MS Word), it should be inserted into Rich Editor while preserving the formatting.

##### Actual behavior
When you paste a one-level list it's pasted as a separated paragraphs. When you paste a multi-level list it's pasted as a separated paragraphs only for the first level, other levels are discarded.

##### Reproduce steps
1. Open any desktop text editor (in my case it's LibreOffice Writer).
2. Make a list.
3. Copy the list.
4. Paste it into Rich Editor.

##### October build
396

**Comment by LukeTowers** [comment]
Did you try updating to the latest build of October? Can't guarantee that will solve your problem, but give it a try.

**Comment by daftspunk** [comment]
This might be something to chase up with Froala, seeing as they are the vendor of the rich editor's underlying UI.

**Comment by lautsevich** [comment]
Thank you guys! I'll check!

**Comment by lautsevich** [comment]
Hi,

i checked. It's reproduced on latest 419 build.

**Comment by LukeTowers** [comment]
@lautsevich you can report this as a bug to Froala, I'm assuming that's where the issue is.

Closing as it has been over a month since any activity on this occurred.
