### ISSUE TITLE
Installer Completes but backend broken when using multiple directories

### ISSUE THREAD

**Issue by andrewfenn** [octobercms/october#2853]
In the installer I changed the option from "/Backend/" to "/foldera/folderb/". Going to the folder shows the login screen.

##### Expected behavior

After login it should show my backend.

##### Actual behavior
Multiple errors about $this->items being null in NavigationManager.php around line 107.

##### Reproduce steps

Simply install, pick start from scratch, and set your backend URL to have multiple folders

##### October build
Fresh install from today.

**Comment by daftspunk** [comment]
Needs peer review, can anyone else replicate this?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
