### ISSUE TITLE
AttachMany doesn't work the same as HasMany with regards to count

### ISSUE THREAD

**Issue by WaskiWabit** [octobercms/october#2854]
When using AttachMany for relating multiple file attachments to a model, count always returns zero. It works fine when using HasMany (for getting the number of related records). But it does not seem to work when attempting to count the number of attachments related to a particular record.
# STEPS TO REPRODUCE
##### Model
    public $attachMany = [
      'images' => ['System\Models\File', 'order' => 'sort_order'],
      'images_count' => ['System\Models\File', 'count' => true]
    ];

##### columns.yaml for above model
    images_count:
        label: Images
        relation: images_count
        valueFrom: count
        default: 0

Of course you will need some related attachments in order to reproduce.

**Comment by LukeTowers** [comment]
I don't think you're supposed to set `valueFrom: count` when you're already pulling the value from a relation that's specifically setup as a count value (`'count' => true`)

**Comment by WaskiWabit** [comment]
The same exact code works though when using `hasMany `on standard models. It just seems to be an issue when using `attachMany `and `System\Models\File`.

**Comment by daftspunk** [comment]
Can this be replicated using the [test plugin](https://github.com/daftspunk/oc-test-plugin)? If so, please provide instructions, if not, please make a PR that does.

**Comment by WaskiWabit** [comment]
1) First make sure current logged in user has files uploaded.
2) Add file count to attachMany in  `oc-test-plugin/models/User.php`

##### User.php
    public $attachMany = [
        'portfolio' => ['System\Models\File'],
        'portfolio_secure' => ['System\Models\File', 'public' => false],
        'files' => ['System\Models\File'],
        'files_count' => ['System\Models\File', 'count' => true]
        'files_secure' => ['System\Models\File', 'public' => false],
    ];

3) Add file count to  `oc-test-plugin/models/user/columns.yaml`

##### columns.yaml
    columns:
        id:
            label: ID
            searchable: true
        username:
            label: Username
            searchable: true
        roles_count:
            label: Roles
            relation: roles_count
            valueFrom: count
            default: 0
        files_count:
            label: Num Files
            relation: files_count
            valueFrom: count
            default: 0

4) Load User backend controller  `oc-test-plugin/controllers/Users.php` and you will see the count for Num Files is always zero. Hope this helps.

**Comment by daftspunk** [comment]
It would appear we have encountered some flawed logic with the 'count' relation argument when used with `AttachMany/One`, since the query looks at the `system_files` table using the `field` as **files_count** instead of **files** or **files_secure** (how should it know?). The result is always 0.

We would need some way to specify which is the target field, perhaps passing the field name to the `count` argument.

```
'files_count' => ['System\Models\File', 'public' => false, 'count' => 'files'],
```

**Comment by WaskiWabit** [comment]
Thank you sir!

**Comment by DevKhater** [comment]
columns:
       number_of_media:
        label: Gallery
        relation: images
        valueFrom: count
        default: 0

    public $attachMany = [
        'images' => ['System\Models\File', 'count' => true],
    ];


it worked for me this way, I can display the number of attached files.

**Comment by DevKhater** [comment]
it could be solved by adding partial column type

    number_of_media:
        label: Gallery
        type: partial
        path: ~/plugins/acme/blog/models/products/_content_column.htm

**Comment by Teranode** [comment]
I've been wondering. Why not use the defined `protected $withCount = []` variable that's available for Laravel? It works with october's array-style methods and it diesplays the count correctly for all relations and even october's attachMany solution.

`protected $withCount = ['wallpaper']` = `wallpaper` relation will appear as `wallpaper_count`;

**Comment by Teranode** [comment]
@LukeTowers is the count boolean needed if that's available already?

**Comment by LukeTowers** [comment]
No idea @Teranode, I'm not familiar with this

**Comment by Teranode** [comment]
well yea, its been available. You can even put in constraints when you use the method form:
```
User::withCount(['posts' => function($q) {
$q->where('id', 1);
}])
```
I believe that the custom count that you guys are implementing for the array methods should just be scrapped if this is available, otherwise you're just gonna add more workload onto your table.
