### ISSUE TITLE
OctoberCMS installation failed on step "Unpacking application files"

### ISSUE THREAD

**Issue by denvist** [octobercms/october#2860]
##### Expected behavior
I want to get fresh October CMS with SQlite as Storage (with or without any theme).

##### Actual behavior
All system requirements - ok

![screen shot 2017-05-05 at 14 27 34](https://cloud.githubusercontent.com/assets/7146527/25743818/0b3a0e66-319f-11e7-8d3f-f4fac47d9a2d.png)

PHP Version: 5.6
PHP Vars:
max_execution_time: 120
max_input_time: -1
max_input_vars: 1000
memory_limit: 256M
post_max_size: 128M
upload_max_filesize: 128M

In a step "Unpacking application files" a saw error "500 Internal Server Error":
![screen shot 2017-05-05 at 14 20 32](https://cloud.githubusercontent.com/assets/7146527/25743662/1af8b47a-319e-11e7-87b8-a9bc97fe1c6c.png)

Installation log - [install.log.zip](https://github.com/octobercms/october/files/978862/install.log.zip)

I tried to switch on "display error" but i cannot get any additional information.

##### Reproduce steps
Download fresh installer, unpack and go to installer.php in your browser.

##### October build
Current build (5 may 2017)

**Comment by denvist** [comment]
I've try to install October to my MacBook - ok.

So i have a question: How can i retrieve (display) additional information about error?

Adding "debug=1" parameter to url not working.

**Comment by KirbyFox** [comment]
Set 'debug' => true within config/app.php

**Comment by denvist** [comment]
@KirbyFox 
There is no such this file in "install-master.zip". Could i create it manually?

**Comment by daftspunk** [comment]
Error 500 is thrown, so additional information about the error is found in your webserver's logs (Apache, Nginx, etc.).

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
