### ISSUE TITLE
`touch` CSS class on `<html>` on non-touch device in Firefox

### ISSUE THREAD

**Issue by gimmixAT** [octobercms/october#2863]
##### Expected behavior
No `touch` class on `<html>` on a non-touch device in Firefox

##### Actual behavior
There is a `touch` class on `<html>` on a non-touch device in Firefox

##### Reproduce steps
Open admin in Firefox

##### October build
415

Firefox 53.0.2

This mainly causes some CSS issues. e.g. on `Pages -> Content` the hover background on list entries is set to transparent.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
