### ISSUE TITLE
Foreign Keys missing

### ISSUE THREAD

**Issue by HACKHERS** [octobercms/october#2865]
Hello, 

I have noticed that there isn't any foreign key in database tables. Is it intentionally or not?  I know it's not a bug but It's not feature too so that's why I'm creating this issue.

Thanks,

**Comment by LukeTowers** [comment]
What do you mean by that?

**Comment by HACKHERS** [comment]
For example in "system_revisions" table; for "user_id" column there is only "key" but it should be a foreign key that references "backend_users" table's "id" column. SQL query for that:
```
ALTER TABLE `system_revisions`
	ADD CONSTRAINT `FK_system_revisions_backend_users` FOREIGN KEY (`user_id`) REFERENCES `backend_users` (`id`) ON UPDATE CASCADE ON DELETE SET NULL;
```

MySQL Reference:
https://dev.mysql.com/doc/refman/5.6/en/create-table-foreign-keys.html

You can check here for how eloquent handles it:
https://laravel.com/docs/5.4/eloquent-relationships

**Comment by daftspunk** [comment]
October doesn't use foreign key constraints or any database functions for that matter. The database is kept "dumb" and most heavy lifting and integrity management is performed using PHP, thanks to Eloquent. That's not to say you can't use FK constraints and DB functions in your own plugins.

**Comment by LukeTowers** [comment]
I agree with @daftspunk. Foreign keys at the database level can be fairly restrictive and their benefits are largely implemented by Eloquent and general indexes.

**Comment by alpapan** [comment]
In the DBA world, ORM is not considered a substitute for secure database design. The only reason why a FK might not be needed is when a column can be null, which can only happen if the DB hasn't been modelled correctly. So restrictive is in the eye of the expert. FKs are exceptionally useful. 

For example, the attached screenshot from SchemaSpy shows that the jobs and failed_jobs table have conflicting schemas. I'm not an October expert to know why is that the case or what are the consequences but if both tables are used then one has a limit for queue of 255 chars and the other doesn't. FKs prevent this from happening.

![image](https://user-images.githubusercontent.com/608484/51116731-087f5380-1860-11e9-8c7e-0152da4af2db.png)

Generally, once you start populating db-driven apps with millions of rows, not having FKs means don't really care about your data. Or your job.

**Comment by LukeTowers** [comment]
@alpapan you're always welcome to submit PRs with explanations for the value of the change. You're also always able to freely change the schema as you need through your own plugins. I will mention that foreign key columns are often able to be null in October with the concept of deferred binding in play (setting relationships on records before they're actually created)
