### ISSUE TITLE
Add check for mod_rewrite in install requirements testing

### ISSUE THREAD

**Issue by mariavilaro** [octobercms/october#2870]
I'd like that, if installation script says all requirements are met, the site works ok after installation. But some requirements (mod_rewrite, and Json I think) are not checked so test says that everything ok but sometimes it's not. It's 2017 and we expect all hostings to have this things but sadly that's not true :(

Could you please add this checks in the installation tests so we can know very quick if it's all ok?

**Comment by mariavilaro** [comment]
I did a PR https://github.com/octobercms/install/pull/88

**Comment by LukeTowers** [comment]
Thanks @mariavilaro, I'll give it a look shortly

**Comment by LukeTowers** [comment]
https://github.com/octobercms/install/pull/88 has been merged, thanks @mariavilaro!
