### ISSUE TITLE
Multiple changes in BrandSetting cause ModelException

### ISSUE THREAD

**Issue by v-bubar** [octobercms/october#2872]
I'm writing a console command that takes color codes and sets them as primary, secondary or accent colors for the Backend view. It goes somehow like that:

```
if (//$primary is a valid color code) {
     BrandSetting::set('primary_color', '#'.$primary);
}
if (//$secondary is a valid color code) {
      BrandSetting::set('secondary_color', '#'.$secondary);
}
if (//$accent is a valid color code) {
       BrandSetting::set('accent_color', '#'.$accent);
}
```
Now, if I set any single one of these three colors, it goes without errors. However, if I try to set several at a time the second one throws a Model Exception.
````
  [October\Rain\Database\ModelException]  
  The app name field is required.  
````
If I try to set several colors at once by adding them to an array and using an array with a single call of `set()` no Exception is being thrown. 

But what is wrong with the first approach?

Thank you in advance for your answer.

**Comment by daftspunk** [comment]
You may need to $model->reload() on your model, after saving the settings behavior is probably trashing the attributes, so the second time fails.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
