### ISSUE TITLE
Override AuthManager in backend

### ISSUE THREAD

**Issue by khoatran** [octobercms/october#2875]
I am going to make a custom LDAP authentication plugin for OctoberCMS backend. One of the approach is overriding the Backend\Classes\AuthManager. I have tried to create an extended class from AuthManager, called LDAPAuthManager. However, it seems that I cannot override the AuthManager in the plugin.

The code that I am using to override is in the boot function as below:
```
App::singleton('backend.auth', function () {
    return LDAPAuthManager::instance();
});
```

However, at the Auth controller, I always receive the old AuthManager class for everywhere that the facade BackendAuth is called. Is this related to the order of plugin loading process in the backend bootstrap? 

Could you please help to enlighten me?

Thanks and best regards,

**Comment by LukeTowers** [comment]
Does your plugin set `$elevated = true;` in your plugin.php?

**Comment by khoatran** [comment]
Yes, I set $elevated = true, but I also try with both true and false, but the result is the same

**Comment by LukeTowers** [comment]
I'm not sure exactly what's going on then, never bothered to dig that deeply into the backend auth manager. There may be some changes coming down to it with the Laravel 5.5 upgrade though, so keep that in mind. @daftspunk would know more about that

**Comment by khoatran** [comment]
Could you give me some suggestions to make the LDAP authentication for backend if I shouldn't touch to AuthManager? 
I also tried to make an override of the Auth Controller following the code in this article: https://octobercms.com/forum/post/authentication-with-custom-ldap-driver?page=1

However, the big problem happens with that code is: the signin_onSubmit method will be called twice: once time for the override by extending + once time later to call to the signin_onSubmit of the Auth controller class. Actually, we cannot replace the signin_onSubmit of the Auth Controller by using extending mechanism of October. 
It seems the only way that I can do now is hacking to the Auth Controller class by putting my implementation at there. However, it's really a very very bad idea. If you can give me an advice, it would be great. Tks a lot

**Comment by LukeTowers** [comment]
@khoatran what did you end up implementing as the solution to this?

**Comment by khoatran** [comment]
@LukeTowers  I created a plugin for this LDAP authentication. I put ideas about solution in my blog here: https://www.learn4.fun/octobercms-ldap-plugin/

What I need to do is just need to extend the backend signin form and replace the submission URL by my own Authentication Controller. The rest of the logic is just specific in working with LDAP.

**Comment by LukeTowers** [comment]
@khoatran for your integration of the Laravel package, I highly recommend that you take a look at my article on doing that, it makes it much easier to integrate Laravel Packages with OctoberCMS plugins.

https://luketowers.ca/blog/how-to-use-laravel-packages-in-october-cms-plugins/

**Comment by Ronnon78** [comment]
I faced the same problem. I tried various ways to connect authorization using LDAP and unfortunately I failed. Maybe someone has already developed a working solution?

**Comment by LukeTowers** [comment]
@LarBearrr any input on this?

**Comment by LarBearrr** [comment]
Sure. Technically you don't need to do anything with the AuthManager to override the sign in behavior. Overriding the AuthManager gives greater control over things like the user class being used, etc. 

Unfortunately, the backend auth flow does not have any events for before/after authentication like the RainLab.User plugin does. Perhaps one of these days I will make a PR to add this functionality.

In the mean time, what you can do is extend the Auth _controller_ and override the signin method:

```
/*
         * Override default sign in behavior
         */
        Event::listen('backend.page.beforeDisplay', function ($controller, $action) {
            if(!$controller instanceof \Backend\Classes\Controller) {
                return;
            }
            if ($action == 'signin') {
                try {
                    if (post('postback')) {
                        return $this->signin_onSubmit();
                    }
                } catch (Exception $ex) {
                    Flash::error($ex->getMessage());
                }
            }
        });
```

Obviously the call `$this->signin_onSubmit()` should reference your custom sign in method, where you can perform whatever type of authentication you like (i.e. LDAP). Typically what I do is create helper functions to handle the different sign on methods:

```
private function handleLDAP()
{
 /* custom ldap authentication goes here */
}
```
