### ISSUE TITLE
System file and deferred_bindings query too slow

### ISSUE THREAD

**Issue by json-wong** [octobercms/october#2877]
##### Actual behavior
I'm developing a store plugin, when added some products(more than one thousand), the system files and deferred bindings query is very slow in backend product update page. see below image:

![1](https://cloud.githubusercontent.com/assets/275036/26231856/6f8c355c-3c84-11e7-9197-ce79935b9d35.png)

Sometimes the query time will be up to a few seconds, I must to run the `DeferredBinding::cleanUp(1);` command, that query time will come down(but query time still very long, as shown in the picture above).

How to optimize this query? it looks very complicated.

##### October build
All build.

**Comment by chesterx** [comment]
i am having this issue for a long time any good news will be appreciated

**Comment by LukeTowers** [comment]
I believe the problem is that the deferred_bindings table uses varchars for foreign keys, if you switch this to use unsigned integers instead it should run better for you. Undetermined at this point whether we will make that a global change or not.

**Comment by Teranode** [comment]
I'll test the performance out, i get this issue too, a lot.

**Comment by Teranode** [comment]
Also in the docs it says that October automatically destroys deferred bindings older than 5 days, this is not the case, as i have bindings that are more than 4 months old.

**Comment by chesterx** [comment]
I tried to change the slave_id column to integer but nearly nothing changed, if the backend form has more then one uploader component this issue occures.

note: I have 8 file uploader on my page. create form (blank form) loads 10+ seconds.

<img width="1325" alt="ekran resmi 2017-06-14 00 39 31" src="https://user-images.githubusercontent.com/533209/27106007-4d44dbbe-509a-11e7-97ae-22ae6cfca7c9.png">

**Comment by LukeTowers** [comment]
@chesterx does your deferred_bindings table need to be cleaned up?

**Comment by chesterx** [comment]
@LukeTowers i saw some expired items so i have created a cron job for cleanup. There is no items on the table, when i posted the query screenshot, despite this the page load takes 10+ seconds.

**Comment by MatheusNaldi** [comment]
Any solutions?

I changed slave_id to unsigned int and it improved, also, create an index for session_key in the deferred_bindings should improve too.

**Comment by LukeTowers** [comment]
@MatheusNaldi so those changes made it better for you?

**Comment by MatheusNaldi** [comment]
@LukeTowers Yes, the problem started with the server processor (8 cores) in 90% of constant use of mysql service, but we still managed to use normal and thought it was because of many accesses to the app (newspaper), after that the server does not pass any of 8 cores above 15% of use, so yes, we had a drastic performance improvement on the whole server. Try on and tell me.
