### ISSUE TITLE
More examples on the main website

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#2880]
Hi guys! 
It's not a bug, just some words about the main website. 
I failed to find any examples of existing sites that use OctoberCms. It would be nice to have such page in order to see the variety and differences between projects. Of course, examples would be featured there only if their owners want to feature them.

**Comment by LukeTowers** [comment]
Hasn't been updated in two years, but https://octobercms.com/blog/category/case-studies exists. I believe we stopped posting those for a reason, I don't know why though, you'd have to ask @daftspunk

**Comment by GinoPane** [comment]
@daftspunk Hi! Can you please comment this?:)

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
