### ISSUE TITLE
Model Validation For Media Manager

### ISSUE THREAD

**Issue by joelamltc** [octobercms/october#2882]
Is there any implemented model validation behaviour for OC Media Manager like dimension and size?
And, showing more information for image like dimension.
Currently, I do the custom validation on model `afterValidate()` event.

**Comment by LukeTowers** [comment]
No, there currently isn't any such validation built in, see http://octobercms.com/docs/backend/forms#widget-mediafinder. The main reason why being that the media manager deals directly with files, it doesn't interface with models at all.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
