### ISSUE TITLE
Add the ability to nest layouts

### ISSUE THREAD

**Issue by Jared-Dev** [octobercms/october#2886]
It would be nice if layouts in October could be nested so that you could pick your injection point! An example would be...

### root-layout.htm
```
description = "Root Layout"
==
<html>
	<head>
		...
		{% styles %}
	</head>
	<body>
		{% page %}
		{% scripts %}
	</body>
</html>
```

### nav-layout.htm
```
description = "Nav Layout"
layout="root-layout"
==
<nav>
	...
</nav>
{% page %}
<footer>
	...
</footer>
```

### titled-layout.htm
```
description = "Title bar layout for non-home pages"
layout = "nav-layout"
==
<title-bar>
	...
</title-bar>
	{% page %}
```

### about.htm
```
description = "The about us page"
layout = "titled-layout"
==
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <!-- about content here -->
        </div>
    </div>
</div>
```

Using this syntax allows you to maintain your tag pairs and pick your injection point for the content of a page. i.e. the homepage would set it's layout to the `nav-layout` whereas the about pages sets its layout to the `titled-layout`

**Comment by LukeTowers** [comment]
The layout's currently get rendered from https://github.com/octobercms/october/blob/master/modules/cms/classes/Controller.php#L373 so use that as a starting point to figure out how to implement nested layouts.

**Comment by daftspunk** [comment]
This is going to need some clear advantage over the following:

### root-layout.htm
```
description = "Root Layout"
==
<html>
    <head>
        {% partial 'site/meta' %}
    </head>
    <body>
        {% page %}
        {% partial 'site/scripts' %}
    </body>
</html>
```

### nav-layout.htm
```
description = "Nav Layout"
layout="root-layout"
==
<html>
    <head>
        {% partial 'site/meta' %}
    </head>
    <body>
        <nav>
            ...
        </nav>
        {% page %}
        <footer>
            ...
        </footer>
        {% partial 'site/scripts' %}
    </body>
</html>
```

### titled-layout.htm
```
description = "Title bar layout for non-home pages"
layout = "nav-layout"
==
<html>
    <head>
        {% partial 'site/meta' %}
    </head>
    <body>
        <title-bar>
            ...
        </title-bar>
        {% page %}
        {% partial 'site/scripts' %}
    </body>
</html>
```

### about.htm
```
description = "The about us page"
layout = "titled-layout"
==
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <!-- about content here -->
        </div>
    </div>
</div>
```

**Comment by InquisitiveDevelopment** [comment]
@daftspunk For the `titled-layout` where is the nav? The point of a chained layout is to keep the markup DRY.

I also can't tell where the `layout = ""` tags do anything for anything but the `about.htm`

**Comment by bennothommo** [comment]
@LukeTowers were you planning on implementing this?

**Comment by LukeTowers** [comment]
@bennothommo yes, at some point

**Comment by daftspunk** [comment]
It is an age-old DRY vs WET debate. This adds significant overhead to the experience of October so as mentioned we'd need to see a clear advantage to justify it. Thanks for the suggestion anyhow!
