### ISSUE TITLE
Cannot extend backend sign in view as the document

### ISSUE THREAD

**Issue by khoatran** [octobercms/october#2887]
Hi everyone,

I am following the document at https://github.com/octobercms/docs/blob/master/plugin-extending.md to extend the sign in view which I want to add some more parts into it. The whole customization needs to be inside my plugin. 

However, I have figured out that the boot method of my plugin cannot be reached until I sign in to the backend.  I have tried with different methods of the PluginBase class to see whether I can catch the event backend.auth.extendSigninView anywhere, but impossible.

It's really really strange. So, I would like to understand how OctoberCMS run the boot process for plugins. Further, is there anyway that I can interfere to the boot process to catch the backend.auth.extendSigninView using my plugin. 

Thanks for your answers and supporting

**Comment by khoatran** [comment]
Hi all,

I have debugged to the module booting process and have figured out the reason.
In the code of the PluginManager shows me that we need to add the variable elevated = true into the plugin to make it registered and loaded in this case.

Below is the code of the PluginManager at that feature:
```
if (!self::$noInit || $plugin->elevated) {
            $plugin->register();
}

```
In the case of the backend Signin page, it's one of the case called PrivilegedActions. You can check more detail about this in the function registerPrivilegedActions in the class System\SystemProvider.
I copied the code here for us to reference:

```

    protected function registerPrivilegedActions()
    {
        $requests = ['/combine', '@/system/updates', '@/system/install', '@/backend/auth'];
        $commands = ['october:up', 'october:update'];

        /*
         * Requests
         */
        $path = RouterHelper::normalizeUrl(Request::path());
        $backendUri = RouterHelper::normalizeUrl(Config::get('cms.backendUri', 'backend'));
        foreach ($requests as $request) {
            if (substr($request, 0, 1) == '@') {
                $request = $backendUri . substr($request, 1);
            }

            if (stripos($path, $request) === 0) {
                PluginManager::$noInit = true;
            }
        }

        /*
         * CLI
         */
        if (App::runningInConsole() && count(array_intersect($commands, Request::server('argv'))) > 0) 
       {
            PluginManager::$noInit = true;
        }
    }

```
That does mean: combine, update, auth, install are one of these actions. You need to put the variable elevated = true into your plugin to make your plugin can interfere into the loading of these pages.

I hope my explanation can help others. 
Just want to put a comment about the documentation of OctoberCMS: I think you guys need to improve it a lot, especially for these small but important feature like this. I don't see any place in the document mentioned about this.

**Comment by LukeTowers** [comment]
It is documented: https://octobercms.com/docs/plugin/registration#elevated-plugin
