### ISSUE TITLE
Turn off asset combing on development level

### ISSUE THREAD

**Issue by adis-io** [octobercms/october#289]
Is it possible turn off asset combing while I'm developing

**Comment by Alex360hd** [comment]
This disable the assets minification, not assets combining. It would be great to add an option in the cms.php config file

    'enableAssetsCombining' => false,

**Comment by LukeTowers** [comment]
@Alex360hd I don't see any way that is even possible. If you want to keep the same markup in your theme but control if it gets combined or not via a configuration, all you're providing October is the input of multiple scripts and the output could only be within the `src` attribute of a script tag. The only way I could see this working would be if October were to perform some sort of HTML tag injection trickery to close the existing tag and then output one new `<script>` tag per included script which sounds hacky af. 

If you don't want them combined while developing then pass the value of `APP_DEBUG` to your view and check that do decide whether to output combined assets or individual assets.
