### ISSUE TITLE
Accent not well on Post

### ISSUE THREAD

**Issue by gravataLonga** [octobercms/october#2891]
##### Expected behavior
When i write "´" + "e" = "é"  

##### Actual behavior
The result is "´é"  

##### Reproduce steps
Backend > Post > New Post > Write a body  

##### October build
419 Build  

Here go a video:

[Video](https://youtu.be/xnlH7Mi1n_o)

**Comment by jan-vince** [comment]
You should probably move this issue to [Blog](https://github.com/rainlab/blog-plugin/issues) repo.

*PS: I use Blog plugin with WYSIWYG so I have never noticed this, but I can confirm, that accented letters cannot be writen this way! Strange.*

**Comment by gravataLonga** [comment]
Sorry, wrong repo. You are right.
