### ISSUE TITLE
$model->validate()  - get errors as string, without error exception.

### ISSUE THREAD

**Issue by LucasZdv** [octobercms/october#2897]
##### Expected behavior
I want to get string message of error
I want this ... [example screen](http://nimb.ws/8MHjIC)

    /**
     * Validation rules in Contact
     */
    protected $rules = [
        'name' => 'required',
        'lastname' => 'required',
        'phone1' => 'required'
    ];   
     
    //Method in controller
    public function test()
    {
      $test = new Contact;
      $test->name = 'lucas';
      $test->lastname = 'test';
      //$test->phone1 = 123123123;
      try {
          if(!$test->validate())
          throw new ValidationException(['error_message'=>'error message...']);

      }
      catch (ValidationException $ex) {
        return $ex->getMessage();
      }
    }

##### Actual behavior
[(Error with exception page)](http://nimb.ws/mvuhNE)

##### October build
419

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
