### ISSUE TITLE
[L5.5] Composer Issues with l5.5 branch + error in backend dealing with pivots

### ISSUE THREAD

**Issue by Teranode** [octobercms/october#2899]
Seeing as you aren't on Slack ill post this here, I get this error when updating composer with the recent l5.5 branch update
![](https://image.prntscr.com/image/420f3b9d392f40279c46a13c1ce6a89e.png)

also this error pops up when deleting a record with a pivot relations (Error occurred May 25th, and continues to occur):
https://slack-files.com/T0985KY2C-F5J4RQV8D-f0d6a00aca

**Comment by daftspunk** [comment]
The first one is fixed. Second one I wasn't able to replicate, can you give instructions using the [test plugin](https://github.com/daftspunk/oc-test-plugin)? Create another issue if it still persists. Thanks!
