### ISSUE TITLE
Subfolder whitelisting does not work on live server.

### ISSUE THREAD

**Issue by rhonz10** [octobercms/october#2901]
I'm having difficulty in white-listing subfolder in OctoberCMS. I have a mail subfolder which contains Roundcube webmail. I am forwarded to 404 page when I try to access /mail.

excerpt from .htaccess file
```
##
## White listed folders
##
...
RewriteCond %{REQUEST_FILENAME} !/modules/.*/(assets|resources)/.*
RewriteCond %{REQUEST_FILENAME} !/mail/.*
RewriteRule !^index.php index.php [L,NC]
```

It works in Homestead vagrant box but does not in Bluehost live server.

Any advice?

**Comment by LukeTowers** [comment]
Does your host support .htaccess files? Are you using the `october:mirror` command?

**Comment by rhonz10** [comment]
I managed to fix my issue after hours of Googling and Stackoverflow. I added this rule right after the RewriteEngine On
```
 ##
 ## Whitelist Webmail Folder
 ##
 RewriteCond %{REQUEST_URI} "/mail/"
 RewriteRule (.*) $1 [L]
 
 ##
 ## Black listed folders
```

**Comment by LukeTowers** [comment]
Glad to hear you got it fixed!
