### ISSUE TITLE
Wrong breadcrumb on the Media

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#2902]
##### Reproduce steps
1. Create a folder something like: 2017 (it contains only numbers)
2. Open this folder
3. In the breadcrumb the folder's name is: 0 (instead of 2017)

##### October build
419

**Comment by daftspunk** [comment]
I was able to replicate this.

**Comment by daftspunk** [comment]
Fixed in Build 420 (https://github.com/octobercms/october/commit/3be6dafa6bd982ec8b0fe4740b1a9cec293134a5#diff-b752a9b7c057ff20c25347db86ede339R790)
