### ISSUE TITLE
Datepicker positioning is not always working

### ISSUE THREAD

**Issue by priitperna** [octobercms/october#2905]
##### Expected behavior
The datepicker calendar should always be in the viewport.

##### Actual behavior
When the date field is the on the left of the screen and the width of the field is small, the calendar div is partly out of the viewport.

##### Reproduce steps
Create a form with a datefield as the first field. Set the following attributes to the field:
```
span: storm
cssClass: col-sm-1
```
 Then click on the datefield to see the calendar div outside of the viewport.
NB. there should not be a sidebar on the left of the screen.

It seems that the problem lies in the datepicker plugins file (datepicker.js) line 112 where the `right` position is set. I'm not sure why its even there as the pikaday plugin can figure out the correct positioning by itself.

##### October build
419

**Comment by LukeTowers** [comment]
Please create a PR to fix this with Gifs demonstrating both the issue and your fix. That would be greatly appreciated!
