### ISSUE TITLE
"Cms\Facades\Cms" extension is not enabled (Fix coming Jul/Aug '17)

### ISSUE THREAD

**Issue by seanthepottingshed** [octobercms/october#2908]
##### Expected behavior
Running the following from the command line:

* `composer create-project october/october TestInstall`
* `cd TestInstall`
* `php artisan october:install`
* The entering responses to prompts

...should create a working install of OctoberCMS

##### Actual behavior

![screen shot 2017-06-06 at 09 51 56](https://cloud.githubusercontent.com/assets/12046965/26821276/ced6c032-4a9d-11e7-99a2-e2cb82658f51.png)

##### Reproduce steps
As above

##### October build
419

**Comment by daftspunk** [comment]
Hmm, looks like your composer is pulling down a "too new" version of Twig. Try specifying an explicit version in your composer.json before composer update.

```
"twig/twig": "~1.23"
```

**Comment by seanthepottingshed** [comment]
@daftspunk **LEGEND** been pulling my hair out for hours

**Comment by seanthepottingshed** [comment]
Excuse my continued ignorance, but which `composer.json` should I be editing? And why has this only just started to occur?

**Comment by daftspunk** [comment]
I thought we fixed this in https://github.com/octobercms/october/issues/2595 so I'm not really sure why its come back.

**Comment by daftspunk** [comment]
Yep so we determined that this is fixed by opening `composer.json` in the root directory, adding to the `require` object this value:

```
"twig/twig": "1.33.*",
```

Then perform `composer update` to rectify the breaking package. This will be fixed in Build 420+ as we move to Twig 2.0. This upgrade won't occur for at least 1-2 months. Leaving this open until then.

**Comment by Harti** [comment]
Just wanted to drop a note that the error vanished for me when I went to `/backend/system/updates`, updated October and set `chmod -R 777` in the october installation folder. 

Unfortunately I tried both at the same time so I'm not sure if the permissions alone fix it already.

**Comment by alexro72** [comment]
Again error
But now text "The "CMS" extension is not enabled."
I try 1.32.*, 1.31.*, 1.30.*, 1.33.* 

At 1.34.* -    "The "Cms\Facades\Cms" extension is not enabled"

**Comment by ametad** [comment]
Set Twig to version 1.34.* does not work in my project, sadly. Does this problem only concern an Octobercms install trough Composer (only)?

**Comment by ametad** [comment]
The installation and updating trough Composer does not seem to work correctly anymore. I cannot get a working installation, after a ```$ composer update``` the October project is not working anymore and gives the error 

> "Cms\Facades\Cms" extension is not enabled

Updating trough the backend does work correctly. But I have to install a lot more with Composer. Therefore I don't want to break my update flow trough Composer. Not cool...

**Comment by seanthepottingshed** [comment]
Should be 1.33.* see above

**Comment by LukeTowers** [comment]
@seanthepottingshed or @ametad have you tried setting it to `~1.33`?

**Comment by seanthepottingshed** [comment]
@LukeTowers It all works for me, I was just pointing out to @ametad that actually @daftspunk stated to set the Twig dependency to `1.33.*` https://github.com/octobercms/october/issues/2908#issuecomment-306431036

**Comment by LukeTowers** [comment]
Ah, gotcha. I would suggest `~1.33` for future support though, but it's moot when 5.5 gets released anyways.

**Comment by seanthepottingshed** [comment]
@LukeTowers Cheers ears!

**Comment by petehalverson** [comment]
@daftspunk @LukeTowers, I don't understand why isn't there going to be a fix in the interim? 1-2 months seems like a long time for this to linger...

**Comment by LukeTowers** [comment]
@petehalverson No more builds are going to be released until the Laravel 5.5 upgrade, but I suppose we could replace https://github.com/octobercms/library/blob/master/composer.json#L25 with `1.33.*` @daftspunk thoughts?

**Comment by ametad** [comment]
Shoot.. I overlooked the correct version being 1.33! Thank you!

**Comment by LukeTowers** [comment]
Testing it now, but this should be fixed for new composer installs of october

**Comment by LukeTowers** [comment]
Not fixed yet, packagist hasn't updated their tag reference to octobercms/library yet, will discuss with @daftspunk https://packagist.org/packages/october/rain#v1.0.419

**Comment by ifnull** [comment]
It looks like dev-master has 1.33.*

**Comment by ifnull** [comment]
https://packagist.org/packages/october/rain#dev-master

**Comment by LukeTowers** [comment]
Yeah, but it goes off the build tag, which theoretically has been updated to point at dev-master's most recent commit

**Comment by petehalverson** [comment]
Thanks @LukeTowers and @daftspunk. Tested it this morning and our docker build is now pulling the corrected Twig version: https://travis-ci.org/aspendigital/docker-octobercms/jobs/232636840#L2257
