### ISSUE TITLE
After composer update I get error The "Cms\Facades\Cms" extension is not enabled.

### ISSUE THREAD

**Issue by getrightnl** [octobercms/october#2909]
##### Expected behavior
After running composer update I get the error message The "Cms\Facades\Cms" extension is not enabled. I saw a reported bug on stackoverflow reported two hours ago.

https://stackoverflow.com/questions/44386021/october-installation

##### Actual behavior
Every page contains this error.

##### Reproduce steps
Run composer update and the error will be displayed on every cms page.

##### October build
419

**Comment by seanthepottingshed** [comment]
@getrightnl 

Literally the issue below this one:

https://github.com/octobercms/october/issues/2908

**Comment by getrightnl** [comment]
A thanks 👍

**Comment by LukeTowers** [comment]
Duplicate of https://github.com/octobercms/october/issues/2908
