### ISSUE TITLE
a.getAllResponseHeaders is not a function

### ISSUE THREAD

**Issue by pjrola** [octobercms/october#2910]
##### Expected behavior
Google tag manager should not impact Ajax requests and display errors in console

##### Actual behavior
Currently when using a Google tag on a fresh install of october it creates a Javascript error in console stating `VM27218:1 Uncaught TypeError: a.getAllResponseHeaders is not a function
    at HTMLDocument.<anonymous> (<anonymous>:1:331)
    at HTMLDocument.dispatch (87485bc…-1496690304:3)
    at HTMLDocument.q.handle (87485bc…-1496690304:3)
    at Object.trigger (87485bc…-1496690304:4)
    at HTMLAnchorElement.<anonymous> (87485bc…-1496690304:4)
    at Function.each (87485bc…-1496690304:2)
    at r.fn.init.each (87485bc…-1496690304:2)
    at r.fn.init.trigger (87485bc…-1496690304:4)
    at Object.complete (framework.js:164)
    at i (87485bc…-1496690304:2)`

##### Reproduce steps

1. Download new copy of October CMS
2. Add a Google Analytics Tag to the `<head> `element on the default.htm layouts page inside of the demo theme.
3. Navigate to http://localhost:8000/demo/ajax and click calculate. 
4. Notice Ajax exception in console. 

##### October build
Latest
![screen shot 2017-06-06 at 10 31 56 am 2](https://cloud.githubusercontent.com/assets/21151298/26834819/6cb00ad8-4aa4-11e7-959a-bb34ea31f5a9.png)
<img width="1433" alt="screen shot 2017-06-06 at 10 31 56 am" src="https://cloud.githubusercontent.com/assets/21151298/26834818/6caf4efe-4aa4-11e7-9d81-e72cef41ba3b.png">

**Comment by pjrola** [comment]
Additionally when I comment out the 

```
complete: function(data, textStatus, jqXHR) {
     $triggerEl.trigger('ajaxComplete', [context, data, textStatus, jqXHR])
     options.evalComplete && eval('(function($el, context, data, textStatus, jqXHR) {'+options.evalComplete+'}.call($el.get(0), $el, context, data, textStatus, jqXHR))')
},
```
section of framework.js starting on line 163 I don't receive the same Ajax exception.

**Comment by pjrola** [comment]
@LukeTowers Were we able to reproduce this?

**Comment by LukeTowers** [comment]
I've never tried to reproduce it, does this issue still exist?

**Comment by pjrola** [comment]
yes still there

**Comment by Samuell1** [comment]
Using GTM js with OCMS ajax without issues.

**Comment by w20k** [comment]
Should be fixed.
