### ISSUE TITLE
Use customer column type in the global

### ISSUE THREAD

**Issue by tim0991** [octobercms/october#2915]
In my case, i want define a column type as formwidget that it can use every list table

**Comment by LukeTowers** [comment]
This already exists: see http://octobercms.com/docs/backend/lists#custom-column-types

**Comment by tim0991** [comment]
@LukeTowers I am looking for a gloabl solution, i mean create once, use every plugin

**Comment by LukeTowers** [comment]
That is global. Create it within a plugin, say Tim.CustomColumn, register it in that plugin's Plugin.php file in the `registerListColumnTypes()`, and then add `Tim.CustomColumn` as a dependency to all of the plugins you want to use that custom column in.

It would look something like this:

**plugins/tim/mycustomcolumn/plugin.php**:
```php
use Twig;
class Plugin extends PluginBase
{
   public function registerListColumnTypes()
   {
        return [
            'mycustomcolumn' => [$this, 'renderMyCustomColumn'],
        ];
    }

    public function renderMyCustomColumn($value, $column, $record)
    {
        return Twig::parse(File::get(plugins_path('tim/mycustomcolumn/partials/column.mycustomcolumn.htm')), [
            'value' => $value,
            'column' => $column,
            'record'  => $record
        ];
    }
}
```

**Comment by tim0991** [comment]
Sorry for my carelessness
