### ISSUE TITLE
Debugbar occurred error

### ISSUE THREAD

**Issue by tim0991** [octobercms/october#2916]
##### Actual behavior
When i submit form, i got below this
>"Undefined property: October\Rain\Database\Connections\MySqlConnection::$connection" on line 351 of /var/www/october/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php

##### Reproduce steps
* Use composer install [debugbar](http://octobercms.com/plugin/bedard-debugbar)
* Into any plugin, submit a form

##### October build
V1.0.419

**Comment by daftspunk** [comment]
Hi @tim0991, please try https://github.com/scottbedard/oc-debugbar-plugin

**Comment by tim0991** [comment]
@daftspunk In fact the debugbar is https://github.com/scottbedard/oc-debugbar-plugin

**Comment by daftspunk** [comment]
You have created an issue in https://github.com/octobercms/october, wrong place dude.

**Comment by tim0991** [comment]
@daftspunk The other issue is about  `backend list type`, it's different
