### ISSUE TITLE
OctoberCMS getThumb breaking image

### ISSUE THREAD

**Issue by mittultechnobrave** [octobercms/october#2918]
We are using getThumb to get image but somehow its breaking the image and html page for few images whereas for few images, it works fine. Here is my img tag looks like.

    <img src=" 

And then the next html content getting broken .. 

We have used below code for thumb images.

    <img src="{{single_consultant.photo.getThumb(750, 359) }}">

This is happening for some images at times. 

We can not use `crop` in this code hence we are not using. 

Can someone guide me what should I do to resolve this issue ? 

Here is a sample Image I am trying to use which is showing error. 

[![enter image description here][1]][1]

Thanks

  [1]: https://i.stack.imgur.com/86JKd.jpg

**Comment by ametad** [comment]
What do you mean with 'We cannot use crop ...'? 

I have never had the problems you describe. We use a slightly different code:

```
<img src="{{ company.logo.thumb('200', '60', {'extension':'png', 'mode':'crop'}) }}" alt="">
```

Perhaps you could try it like that and it will work...

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
