### ISSUE TITLE
[L5.5] Plugins not being registered through plugin manager

### ISSUE THREAD

**Issue by Teranode** [octobercms/october#2920]
Following your recent update to the loading of classes that luke pointed out to me:

https://github.com/octobercms/library/commit/9b4f6586c8071e918c5087b8a75dc645fa0508d7#diff-4f9ca942096bc72da15081bce4df5752R23

Plugins are not able to be loaded through the plugin manager because the System namespaced classes (such as System\Classes\PluginManager) are not able to be loaded by the ClassLoader; rendering October inoperable.

errors like this pop up:

https://slack-files.com/T0985KY2C-F5RVC3Q69-94c8b92982

**Comment by Teranode** [comment]
@LukeTowers @daftspunk 

been fiddling with it and changing:

```
        /*
         * Provide both alternatives
         */
        $lowerClass = strtolower($directory) . '\\' . $file . '.php';
        $upperClass = $directory . '\\' . $file . '.php';
```
to

```

        /*
         * Provide both alternatives
         */
        $lowerClass = strtolower($directory) . '/' . $file . '.php';
        $upperClass = $directory . '/' . $file . '.php';
```

fixes the issue.

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/library/commit/47bf27a0b7be9f982548bf9ee8aae411395eddf1

**Comment by daftspunk** [comment]
Good catch, thanks!
