### ISSUE TITLE
Cant access to octobercms.com from Beeline Internet provider

### ISSUE THREAD

**Issue by mnvx** [octobercms/october#2923]
As said support of internet provider resource was blocked by law court.

IP of octobercms.com:

```bash
$ ping octobercms.com
PING octobercms.com (104.24.112.12) 56(84) bytes of data.
^C
--- octobercms.com ping statistics ---
6 packets transmitted, 0 received, 100% packet loss, time 4999ms

```

http://moskva.beeline.ru/customers/help/safe-beeline/ugrozy-v-internete/zablokirovannye-resursy/

> Заблокирован url  (ip: 104.24.112.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.112.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.112.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.112.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.112.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.112.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.112.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.112.12) 
> Решение: суд от 2013-06-10
> Заблокирован url https://m.bksportfon.org/ (ip: 104.24.112.12) 
> Решение: ФНС от 2016-11-22
> Заблокирован url  (ip: 104.24.113.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.113.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.113.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.113.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.113.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.113.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.113.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.113.12) 
> Решение: суд от 2013-06-10
> Заблокирован url https://m.bksportfon.org/ (ip: 104.24.113.12) 
> Решение: ФНС от 2016-11-22
> Подробности на сайте Единого реестра запрещенной информации: zapret-info.gov.ru.
> Указанные блокировки найдены по ip: 104.24.112.12, 104.24.113.12.

Is it possible to move octobercms to another server?

**Comment by mnvx** [comment]
Second IP was blocked too...

> Заблокирован url  (ip: 104.24.113.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.113.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.113.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.113.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.113.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.113.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.113.12) 
> Решение: суд от 2013-06-10
> Заблокирован url  (ip: 104.24.113.12) 
> Решение: суд от 2013-06-10
> Заблокирован url https://m.bksportfon.org/ (ip: 104.24.113.12) 
> Решение: ФНС от 2016-11-22
> Подробности на сайте Единого реестра запрещенной информации: zapret-info.gov.ru.
> Указанные блокировки найдены по ip: 104.24.113.12.

**Comment by daftspunk** [comment]
This IP address belongs to CloudFlare, a web proxy. It means the IP can be shared with thousands of websites and is blocked by short-sited government policies that don't consider this scenario.

To access the website you should use a proxy, something that should be fairly common because October CMS is not special and a vast majority of websites use CloudFlare. The OctoberCMS installer or update gateway should be unaffected by this.

We hope to move to more robust infrastructure in the coming years. If you have any further trouble, send us an email via hello at octobercms.com
