### ISSUE TITLE
Support url for settings in plugin.yaml

### ISSUE THREAD

**Issue by EugeneBazeliuk** [octobercms/october#2926]
##### Expected behavior
plugin.yaml

settings:
----testname:
--------label: test label
------------url: vendor/plugin/controller

method 'registerSettings()' In PluginBase register url for setting (as method registerNavigation())

##### Actual behavior
method 'registerSettings()' In PluginBase does'nt generate valid url for controller in setting.

##### October build
419

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
