### ISSUE TITLE
Unable to use october:install command

### ISSUE THREAD

**Issue by abr4xas** [octobercms/october#2927]
##### Expected behavior
Create a new data base 

##### Actual behavior
```bash
$ php artisan october:install

// fill only admin data
```
```php
 [Exception]                                                
  Unable to rewrite key "default" in config, does it exist?  
```

```php
            
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  syntax error, unexpected ','   
```

##### Reproduce steps
`php artisan october:up` is OK
`php artisan october:env` is OK
`php artisan october:install` get the error

Im using an `.env` file to fill all data 

##### October build

v1.0.419

**Comment by LukeTowers** [comment]
See #2908, try the fix there, and then let me know if that works

**Comment by abr4xas** [comment]
@LukeTowers nope. That issue is for twig my problem is with an `.env` file

**Comment by LukeTowers** [comment]
Why are you running `install` after `up`?

**Comment by LukeTowers** [comment]
Documented this: https://github.com/octobercms/docs/commit/5d1f8d351f57513e2d478538e688495dedf0d063
