### ISSUE TITLE
Component onRun() not injecting $page assignments

### ISSUE THREAD

**Issue by colthreepv** [octobercms/october#2932]
I have developed a simple component that executes a model::get() based-off a property.

```
    public function onRun() {
        $slug = $this->property('id');
        $data = Team::get($id);

        if (!$data) {
            $this->setStatusCode(404);
            return $this->controller->run('404');
        }

        $this->page['var'] = $data;
    }
```

on the page I'm using

```
title = ""
url = "/someurl/:id"
[componentDetail]
id = "{{ :id }}"
==
<p>{{ this.page.var }}</p>
```

And this will not return anything, if the id is valid. If it's invalid, it correctly sends to a 404 page.

What i have to do in order to render data inside the page is to add another method to the component:
```
    public function get() {
        return $this->page['var'];
    }
```

and editing the page like:

```
title = ""
url = "/someurl/:id"
[componentDetail]
id = "{{ :id }}"
==
{% set data = componentDetail.get %}
<p>{{ data }}</p>
```

It works correctly.

But why my component cannot inject data inside `$this->page[]` as [described in the guide](https://octobercms.com/docs/plugin/components#page-cycle)?

October build:
1.0.419

**Comment by LukeTowers** [comment]
@colthreepv When you set `$this->page['var'] = $data;` in your component, you should be able to just use `{{ var }}` on the page.

**Comment by Teranode** [comment]
in your test case you are stating:
```
        $slug = $this->property('id');
        $data = Team::get($id);
```
isnt `$id` supposed to be `$slug` ?

**Comment by colthreepv** [comment]
@Teranode yes

I just find it inconsistent as written in the previous post

**Comment by Teranode** [comment]
@colthreepv 
from what ive been doing, ive always used:
```
$this->somevar = $this->page['somevar'] = 'blabla';
```

that way i can get access to:
```
{{ somevar }}
```

**Comment by LukeTowers** [comment]
@colthreepv it has to do with the execution order, inline functions are run after the rendering has already started and the base variables passed to Twig which enables them to be used as `{{ someVar }}`. At that point, all we can do is insert additional variables into the `{{ this.page }}` array. 

If you have any suggestions for improving the cohesion between both methods, feel free to make a PR.
