### ISSUE TITLE
CSS and JS combine error

### ISSUE THREAD

**Issue by marcoelho97** [octobercms/october#2934]
It was supposed to combine without problem, but, unfortunately, I often see myself ruining code due to the combines.
Font Load in the CSS vanishing and some other problems.

Sometimes, even when I add the framework to the combine, it breaks my whole code ( js combine ).

##### Reproduce steps
All I do is:

        <link rel="stylesheet" type="text/css" href="{{ 
        ['assets/css/bootstrap.css', 
        'assets/css/font-awesome.css', 
        'assets/css/camera.css', 
        'assets/css/slicknav.css', 
        'assets/css/prettyPhoto.css', 
        'assets/css/font-awesome.min.css']|theme }}">

##### October build
I have noticed this same problem since the Release Candidate version.

**Comment by LukeTowers** [comment]
That sounds like a problem with how you have your CSS structured, not with the asset combiner. Unless you can more specifically define what the problem is, this is of no help to us and we can't help you.
