### ISSUE TITLE
[L5.5] Expired backend session does not return to original page

### ISSUE THREAD

**Issue by Teranode** [octobercms/october#2936]
1. Sign out of the backend
1. Open **config/session.php** and set the `lifetime` option to `1`.
1. Sign in to the backend and open the preferences page `/backend/backend/preferences`
1. Wait 60 seconds
1. Refresh the page
1. You should be signed out automatically and shown the sign in page
1. Sign in again

### Expected result

You should return to the backend preferences page `/backend/backend/preferences`

### Actual result

You are taken to the dashboard

**Comment by daftspunk** [comment]
There is a lot of arm waving going on here. Going to need some clear replication instructions please.

**Comment by Teranode** [comment]
@daftspunk would that work?

**Comment by daftspunk** [comment]
I'm not following you? As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

i.e Do XYZ, expecting A, getting B.

**Comment by Teranode** [comment]
: | - I give up ill just close this and find a solution eventually.

**Comment by daftspunk** [comment]
Ah, I see you edited the main post. Thanks! For the side issue you'll need to create a fresh issue.

**Comment by daftspunk** [comment]
In step 1, I assume you mean the `lifetime` option? Set it to 1 minute?

    /*
    |--------------------------------------------------------------------------
    | Session Lifetime
    |--------------------------------------------------------------------------
    |
    | Here you may specify the number of minutes that you wish the session
    | to be allowed to remain idle for it is expired. If you want them
    | to immediately expire when the browser closes, set it to zero.
    |
    */

    'lifetime' => 1,

What about `expire_on_close`, what do you have it set to? Finer details are important when reporting issues. It saves everyone a lot of time.

**Comment by Teranode** [comment]
the default value for `expire_on_close` is false so i just leave it as is.

**Comment by daftspunk** [comment]
Unable to replicate this

1. Sign out of the backend
1. Open **config/session.php** and set the `lifetime` option to `1`.
1. Sign in to the backend and open the preferences page `/backend/backend/preferences`
1. Wait 60 seconds
1. Refresh the page

The backend preferences page is still shown, so we are getting different results?

**Comment by Teranode** [comment]
yes what im getting is the login page is showing up twice rather than bringing me back to the previous page, I'm not entirely certain whats causing the issue. I also changed the session engine from file to redis and then back to file to see if that was the issue but the same problem occurs on both instances.

**Comment by daftspunk** [comment]
@Teranode, follow the instructions I have given and when the outcome it different, describe the outcome and at which step it occurs.

**Comment by Teranode** [comment]
On step 5, I refreshed the page.
The session expires, and im taken to the sign-in page. I sign-in and then the sign in page shows up again. I sign in again, then im taken to the dashboard

**Comment by daftspunk** [comment]
Ok, updated the main description. I can't replicate it but we'll see if someone else can.

**Comment by daftspunk** [comment]
Looks to be a single user issue.
