### ISSUE TITLE
I find this Icon thumbnail is big than the others

### ISSUE THREAD

**Issue by iamike** [octobercms/october#2941]
##### Expected behavior
please check this screen shot
![2017-06-25 8 00 42](https://user-images.githubusercontent.com/526854/27515937-7b068584-59e1-11e7-9901-b96b4df94ddc.png)
##### Actual behavior

it should be the same size. 

##### Reproduce steps
login back-end , and disable the css

##### October build
(October build number)

**Comment by ifnull** [comment]
What is the asset filename? It looks like an SVG. If that is the case, the size shouldn't matter. Is there another use case where you see this happening?

**Comment by SebastiaanKloos** [comment]
This is from the backend theme plugin. This issue is better placed at the support page of netsi.

**Comment by iamike** [comment]
please check out this plugin. and install it. once finished. login in back-end. that icon will appear extremely large. 
https://octobercms.com/plugin/nocio-formstore

**Comment by LukeTowers** [comment]
@iamike Of course if you disable the CSS, not everything is going to be the same. Why is this an issue that needs to be reported to the October repository? If you care that much about it, then create an issue in the plugin's repository, October is not going to support keeping menu images the same size when all CSS on the page is disabled. I can't even think of a use case where that would happen normally.
