### ISSUE TITLE
'ErrorException' with message 'file_put_contents(/public_html/storage/framework/cache/3e/e9/3ee9018fdc0c5ec39d638b380620cffd): failed to open stream: Permission denied' in /public_html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:81

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#2943]
##### Expected behavior

no exception error

##### Actual behavior

While register a new user programmatically, OC is trying to access a cached file that has a wrong permission 644 and provoke a file permission error.
How come this file has a 644 and all this other one are having a 755 permission for the framework cache ?

How to resolve the situation please ?

##### Trace Log 
[2017-06-27 13:02:51] beta.ERROR: exception 'ErrorException' with message 'file_put_contents(/home/smartbuild/public_html/storage/framework/cache/3e/e9/3ee9018fdc0c5ec39d638b380620cffd): failed to open stream: Permission denied' in /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:81
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/home/smartbuil...', 81, Array)
#1 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(81): file_put_contents('/home/smartbuil...', '1498626171a:1:{...', 0)
#2 /home/smartbuild/public_html/vendor/october/rain/src/Filesystem/Filesystem.php(200): Illuminate\Filesystem\Filesystem->put('/home/smartbuil...', '1498626171a:1:{...', false)
#3 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(102): October\Rain\Filesystem\Filesystem->put('/home/smartbuil...', '1498626171a:1:{...')
#4 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(140): Illuminate\Cache\FileStore->put('system::setting...', Array, 1440)
#5 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(206): Illuminate\Cache\Repository->put('system::setting...', Array, 1440)
#6 [internal function]: Illuminate\Cache\Repository->remember('system::setting...', 1440, Object(Closure))
#7 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(318): call_user_func_array(Array, Array)
#8 /home/smartbuild/public_html/vendor/october/rain/src/Database/QueryBuilder.php(145): Illuminate\Cache\CacheManager->__call('remember', Array)
#9 /home/smartbuild/public_html/vendor/october/rain/src/Database/QueryBuilder.php(145): Illuminate\Cache\CacheManager->remember('system::setting...', 1440, Object(Closure))
#10 /home/smartbuild/public_html/vendor/october/rain/src/Database/QueryBuilder.php(109): October\Rain\Database\QueryBuilder->getCached(Array)
#11 /home/smartbuild/public_html/vendor/october/rain/src/Database/QueryBuilder.php(80): October\Rain\Database\QueryBuilder->getDuplicateCached(Array)
#12 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(477): October\Rain\Database\QueryBuilder->get(Array)
#13 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(234): Illuminate\Database\Eloquent\Builder->getModels(Array)
#14 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(206): Illuminate\Database\Eloquent\Builder->get(Array)
#15 /home/smartbuild/public_html/modules/system/behaviors/SettingsModel.php(112): Illuminate\Database\Eloquent\Builder->first()
#16 /home/smartbuild/public_html/modules/system/behaviors/SettingsModel.php(100): System\Behaviors\SettingsModel->getSettingsRecord()
#17 [internal function]: System\Behaviors\SettingsModel->isConfigured()
#18 /home/smartbuild/public_html/vendor/october/rain/src/Extension/ExtendableTrait.php(371): call_user_func_array(Array, Array)
#19 /home/smartbuild/public_html/vendor/october/rain/src/Database/Model.php(516): October\Rain\Database\Model->extendableCall('isConfigured', Array)
#20 [internal function]: October\Rain\Database\Model->__call('isConfigured', Array)
#21 [internal function]: System\Models\MailSetting->isConfigured()
#22 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3458): call_user_func_array(Array, Array)
#23 /home/smartbuild/public_html/modules/system/ServiceProvider.php(293): Illuminate\Database\Eloquent\Model::__callStatic('isConfigured', Array)
#24 /home/smartbuild/public_html/modules/system/ServiceProvider.php(293): System\Models\MailSetting::isConfigured()
#25 [internal function]: System\ServiceProvider->System\{closure}(Object(October\Rain\Mail\MailServiceProvider))
#26 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#27 /home/smartbuild/public_html/vendor/october/rain/src/Mail/MailServiceProvider.php(24): Illuminate\Events\Dispatcher->fire('mailer.beforeRe...', Array)
#28 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): October\Rain\Mail\MailServiceProvider->October\Rain\Mail\{closure}(Object(October\Rain\Foundation\Application), Array)
#29 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build(Object(Closure), Array)
#30 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('mailer', Array)
#31 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1167): Illuminate\Foundation\Application->make('mailer')
#32 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(151): Illuminate\Container\Container->offsetGet('mailer')
#33 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(120): Illuminate\Support\Facades\Facade::resolveFacadeInstance('mailer')
#34 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(205): Illuminate\Support\Facades\Facade::getFacadeRoot()
#35 /home/smartbuild/public_html/plugins/rainlab/user/models/User.php(82): Illuminate\Support\Facades\Facade::__callStatic('sendTo', Array)
#36 /home/smartbuild/public_html/plugins/rainlab/user/models/User.php(82): Illuminate\Support\Facades\Mail::sendTo(Object(RainLab\User\Models\User), 'rainlab.user::m...', Array)
#37 /home/smartbuild/public_html/vendor/october/rain/src/Auth/Manager.php(86): RainLab\User\Models\User->attemptActivation('MFIpSI2yuGncN8D...')
#38 /home/smartbuild/public_html/plugins/rainlab/user/classes/AuthManager.php(59): October\Rain\Auth\Manager->register(Array, true)
#39 /home/smartbuild/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): RainLab\User\Classes\AuthManager->register(Array, true)

##### October build
419

**Comment by LukeTowers** [comment]
Unless you can provide replication instructions, this is a problem with your server's configuration. Either configure your server so that 644 is sufficient permissions for it to access the files it needs to, or change the permissions of the cache files in question to 755 to resolve your immediate issue. 

As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

If you can't provide replication instructions, then Github issues really isn't the place for a question like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

**Comment by 24sevendevs** [comment]
Did you solve your issue? I experience the same thing. When I run chmod -R 777 storage, the errror is temporarily solved bu after sometime, there comes another user with similar issue. In my case I am using Cache::remember in my app which creates cache files in the storage/framework folder.
My question is, why is it that these files are created without sufficient permissions to the creator (www_data)?

**Comment by daftspunk** [comment]
Hi @24sevendevs, check the default permissions in the configuration directory (cms.php or system.php). The default mask can sometimes prevent the web user from writing or rereading the file.

For support with October CMS: https://octobercms.com/contact
