### ISSUE TITLE
AttachOne relation breaks if parent select doesn't include id field

### ISSUE THREAD

**Issue by bombozama** [octobercms/october#2944]
I've set up a model to use a picture.
```php
public $attachOne = [
        'picture' => 'System\Models\File'
    ];
````
I've properly loaded a picture using the relation. The picture is in the filesystem and correctly refered to in the `system_files` table.

When querying for models, the following should retrieve the model and eagerload the `picture`
```php
$model = MyModel::select('field1', 'field2', ..., 'fieldn')
        ->with('picture')
        ->first();
```

Attempting to get picture path with:
```php
$model->picture->getPath();
```
Getting *Exception: Call to a member function getPath() on null* (instead of the picture path)

After a lot of struggling, I managed to figure out that since the `id` field was not included in the `select` statement, the query that fetches the picture from the `system_files` table fails to relate both models:
```sql
select * from `system_files` where `system_files`.`attachment_type` = 'Acme\Plugin\Models\MyModel' 
and `system_files`.`attachment_id` is null and `field` = 'picture' and 
`system_files`.`attachment_id` is not null order by `sort_order` asc limit 1
```
Note the
```sql
`system_files`.`attachment_id` is null
```
instead of 
```sql
`system_files`.`attachment_id` = 'model-id'
```
I don't know if it is a bug or the expected behavior, but I would like to simply point out that one should be careful to include the `id` field (whatever it's called in your system) in order to ensure that the relation works.

Hope it helps!

**Comment by LukeTowers** [comment]
This is a complex case. 

In order to aid in our understanding of the problem, please submit [a Pull Request to the test plugin](https://github.com/daftspunk/oc-test-plugin) for investigation that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it _using the test plugin_.

**Comment by LukeTowers** [comment]
Documented in https://github.com/octobercms/docs/commit/c47ca9d879a405d2b5db8201b22a54df600b1333, thanks for the report!
