### ISSUE TITLE
PHP error when running trying to refresh plugin via CLI

### ISSUE THREAD

**Issue by maartenmachiels** [octobercms/october#2947]
##### Expected behavior
I was moving my OctoberCMS installation from my local system to my production server. I ran a clean install on my production server and afterwards uploaded my custom plugins and themes. On the backend everything seems fine, database (even the tables related to my plugins) seems to be present, menus are there... But components do not show. I therefore thought I should use the artisan refresh command as stated [here] (https://octobercms.com/docs/console/commands#plugin-refresh-command)

##### Actual behavior
When running `php artisan plugin:refresh Chocolata.VisitorRegistration` via shell, the following error appears:
`-bash-4.2$ PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/vhosts/mydomain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 101`
which seems to indicate that I'm running the wrong version of PHP. I checked and double checked. I'm running 5.6 on my server. I tried switching to version 7.0, but to no avail. I saw somewhere that the php version that shell uses might be different. 

##### October build
October build 419

My question is: how can I get my plugin up and running on my server without the use of the command line interface? My October account is connected to my instance on my server, but no plugins show up. 
As we're outside of local office hours, I cannot contact my hosting company atm and I don't have the right permissions or knowledge of how to change the PHP version of the CLI. Do you know of a workaround please? 

Thank you for looking into this.

**Comment by LukeTowers** [comment]
If everything but the components from your custom plugin are showing up, then something is wrong with how your plugin registers those components.

**Comment by maartenmachiels** [comment]
Hi Luke

Thank you for your response. I've finally gotten word back from my hosting company. They have updated the PHP version and have now run the artisan plugin:refresh command without issue. 

As you predicted however, the issue with components is still persisting. I've uploaded everything from my local development environment (xampp) to my production server. I've checked to see any differences in configuration files but don't find any (the production server is pointing to the right database...).

As far as registering components goes, my components are registered as they are on my local development machine:

```
<?php namespace Chocolata\VisitorRegistration;

use System\Classes\PluginBase;

class Plugin extends PluginBase
{
    public function registerComponents()
    {
        return [
            'Chocolata\VisitorRegistration\Components\SignInForm' => 'signin',
            'Chocolata\VisitorRegistration\Components\SignOutForm' => 'signout',
            'Chocolata\VisitorRegistration\Components\EventForm' => 'event'
        ];
    }

    public function registerSettings()
    {
    }
}
```

What else could I be overlooking? Something about file permissions perhaps?

**Comment by maartenmachiels** [comment]
Hi, after hours and hours of experimenting, I've pinpointed the error to capitalization of folder names. 
In that way, my question is a duplicate of [https://github.com/octobercms/october/issues/1706](url)

It was difficult to find this out. Here is my final folder structure for those who are interested:
![knipsel](https://user-images.githubusercontent.com/3584586/27805965-2026b5dc-6038-11e7-98ed-8ebb85a86733.PNG)

Making the folder names inside the components folder lowercase is enough, no need to change anything else. Filenames can be disregarded.

**Comment by LukeTowers** [comment]
@maartenmachiels Ah, I see. When you said they were not showing up, I thought you meant that they were not appearing as options within the CMS. I see you actually meant that they were not rendering on the frontend. 

I'm glad you were able to figure out the issue.
