### ISSUE TITLE
Improved october:env behaviour

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [octobercms/october#2949]
Running october:env moves the environment values to the .env file but also keeps a copy of that value as default value in the env format i.e. as `env('ENV_VARIABLE_NAME', 'value');`. This isn't good because when I create a new git repo with the files except .env it still has all the database credentials and the application key inside the files as the default values now.

##### Expected behavior
It should remove the values completely and leave the default value as some common default such as 'localhost', 'root', '127.0.0.1', 'defaultKey', etc.

##### Actual behavior
It extracts the value and replaces it with the env function as `env('ENV_VARIABLE_NAME', 'value');`.

##### Reproduce steps
* Create a new OctoberCMS project. Install with any workflow (From project ID, scratch, theme)
* Regardless of the workflow, the installer would generate application key and store DB credentials in various files (database.php, app.php).
* Initialize a git repo with a .gitignore having the .env to prevent credentials going upstream and other stuff such as /uploads, etc.
* Make first commit. The repo is now infested with the application key as well as the database credentials used to setup the project.

##### October build
419

**Comment by daftspunk** [comment]
Feel free to submit a PR that addresses this.

**Comment by LukeTowers** [comment]
https://github.com/octobercms/october/pull/2963 in progress to fix this.

**Comment by LukeTowers** [comment]
Implemented by https://github.com/octobercms/october/commit/0ac7f340be7fb8aba8427b318d62ed9bce189653
