### ISSUE TITLE
No 404 status code set when visiting the /404 page when you aren't logged in

### ISSUE THREAD

**Issue by maxibanki** [octobercms/october#2953]
##### Expected behavior
http 404 status code

##### Actual behavior
http 200 status code

##### Reproduce steps
1. Set content to the 404 page
2. Visit the /404 page

##### October build
419

**Comment by maxibanki** [comment]
Sorry, was my fault. It's working^^

**Comment by maxibanki** [comment]
Sorry for reopening the issue, but I can reproduce the bug. When you are logged in via the backend and have so the cookie set the correct http status code (404) will be shown. When you aren't logged in (removed the cookie) like a anonymous user, a http 200 status code will be returned.
I hope I can help you with these information.

**Comment by maxibanki** [comment]
When you are not logged in, the $response will be recognized as a string. Ref to:
https://github.com/octobercms/october/blob/master/modules/cms/classes/Controller.php#L227-L229

**Comment by LukeTowers** [comment]
Merged #2959
