### ISSUE TITLE
dependsOn - Reset child dropdowns when parent dropdown is changed

### ISSUE THREAD

**Issue by WaskiWabit** [octobercms/october#2962]
When using "dependsOn" on multiple dropdown fields, there should be a way to reset the child dropdowns when the parent dropdown is changed. Currently there is nothing in the documentation regarding this issue. If there is a solution, I would love to hear it.

I <3 October,
Thanks

**Comment by WaskiWabit** [comment]
@LukeTowers , I have been beating myself up for days over this one. Mainly because the issue I'm facing has to do with a relational model in a popup modal. Any advice you have would be greatly appreciated.

**Comment by WaskiWabit** [comment]
Also I'm well aware that this can be accomplished with javascript etc, but I just don't want to implement some hack to accomplish it. Everything else within October is so clean. My thoughts are if you are going to give us the ability to populate child dropdowns based on their parents, then resetting the children when their parents are modified should be core functionality imo.

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by NemoD503** [comment]
As I see it, this is exactly how it works.

**Comment by LukeTowers** [comment]
@WaskiWabit afaik the behaviour described is how it does work, are you saying that it doesn't work?

**Comment by WaskiWabit** [comment]
@LukeTowers no it does not.

**Comment by LukeTowers** [comment]
Could you post your code?

**Comment by WaskiWabit** [comment]
I already did @LukeTowers

**Comment by LukeTowers** [comment]
@WaskiWabit where?
