### ISSUE TITLE
Unable to create multiple dashboards through ReportContainer class

### ISSUE THREAD

**Issue by Klaasie** [octobercms/october#2964]
##### Bug summary
The ReportContainer class currently doesn't allow multiple dashboards. This is because the widget defines the report widgets and binds to the controller before context can be set.

##### Expected behavior
I'm expecting to be able to use the ReportContainer class, setting a different context and have multiple pages load different dashboards based on context.

##### Actual behavior
Currently the context variable defaults to 'dashboard'. Before being able to change the context the defined widgets are stored into a variable through the `defineReportWidgets()` to avoid loading them again.

##### Reproduce steps
Create a backend page and create a report container. Try to have it load and save different set of  report widgets from the default dashboard that is rendered into the /backend page.

##### October build
419

**Comment by tdolph** [comment]
I am also battling with this problem. Trying to create second dashboard but cant figure out how to set report container context.

My temporary solution was to add additional parameter to ReportContainer constructor and set context as third parameter.

Would love to know how to do it "officially" so the cms updates wont mess it up.

**Comment by WWRFresource** [comment]
I too would like to know how to do this. Currently, I have a controller for my plugin called Dashboard. I was able to replicate the Backend Index module to display the dashboard on this controller's index. However, it just duplicates whatever is already on the main dashboard.

I would like to be able to specify my own config_dashboard.yaml to use with this controller.

**Comment by LukeTowers** [comment]
@WWRFresource @Klaasie @tdolph The `$context` property is a public property of the ReportContainer widget, it should be accessible through the widget's configuration.
Try 
```php
$reportContainer = new ReportContainer($controller, ['context' => 'mycontext']);
```
as seen here: https://github.com/octobercms/october/blob/master/modules/backend/controllers/Index.php#L65

**Comment by WWRFresource** [comment]
@LukeTowers Thanks for the update. Quick question though-I tried using my own config_dashboard.yaml as referenced and this does not seem to work. I am really trying to display a specific report widget for this controller so my backend users do not have to add it to the controller themselves. I tried setting the canAddAndDelete property to false. This causes no report widgets to be displayed. So I have to remove that property, and then add the widget for them to be able to see it. 

How can I work around this?

**Comment by LukeTowers** [comment]
The widgets are loaded here: https://github.com/octobercms/october/blob/master/modules/backend/widgets/ReportContainer.php#L302. The `addWidget()` method can't be used in your case because that is where the canAddAndDelete property is checked.

Two options exist here, either we can make a change checking that property only in the AJAX handles, therefore only preventing users from making changes; or you can implement the logic here: https://github.com/octobercms/october/blob/master/modules/backend/widgets/ReportContainer.php#L225-L249 to manually add your widgets to the user's preferences @WWRFresource
