### ISSUE TITLE
Logic mistake on modules/backend/behaviors/ListController.php

### ISSUE THREAD

**Issue by andrepo** [octobercms/october#2965]
##### Expected behavior
While listening to 'list.extendRecords', the listExtendRecords method needs to return the modified $records so that it can be reflected on the widget

##### Actual behavior
https://github.com/octobercms/october/blob/master/modules/backend/behaviors/ListController.php#L178 should be implemented as follows:
```
$widget->bindEvent('list.extendRecords', function ($records) use ($definition) {
    return $this->controller->listExtendRecords($records, $definition);
});
```

##### Reproduce steps
Extend the listExtendRecords() method on a backend controller that implements Backend.Behaviors.ListController to try and alter the records to be displayed on the controller's list view

##### October build
october/backend v1.0.419

**Comment by LukeTowers** [comment]
Are you sure that we need to return the modified records? What if we simply passed the `$records` variable by reference to the controller method since that's how the local event is implemented in the first place (passing the `$records` variable to the event by reference): https://github.com/octobercms/october/blob/master/modules/backend/widgets/Lists.php#L530

**Comment by LukeTowers** [comment]
I ask because I'm not sure of the original rationale behind not returning the value

**Comment by andrepo** [comment]
Hi Luke,

The line you just highlighted explicitly expects the callback to return a
value to $event and if event is not empty it overrides $records with $event.

Assuming that is the rational, when listening to this event, ListController
should return the callback value.

It doesn't make sense to me to have the code that's listening to the event
dictate how the value should be passed but the event emitter and is this
case the emitter is expecting to callback to return something.

Those are my 5 cents.

At any rate the code as it is on ListController doesn't work.

Thanks!

-André

**Comment by datune** [comment]
I can only second @andrepo change request. After struggling myself I finally came to the same conclusion, only to see that this is already reported. After changing as proposed, everything worked as expected.

**Comment by LukeTowers** [comment]
@datune @andrepo somebody please make a PR. Thanks!
