### ISSUE TITLE
Add Events to UpdateManager.php that triggers when plugins and or system files are updated

### ISSUE THREAD

**Issue by firemankurt** [octobercms/october#2966]
Please consider adding update events to October.

Concerning file: october/modules/system/classes/UpdateManager.php

##### Expected behavior
When system or plugins are installed or updated there should be an event that authors can subscribe to for assessing changes and reacting to them. 
- A plugin might want to check Plugin.php files for property changes and perform an action
- A plugin might want to refresh data based on system changes
- A plugin might want to notify other admins that the system was updated
These are just some use case examples.
##### Actual behavior
There are no Events to subscribe to for system or plugin updates.

##### Reproduce steps
Try :

    Event::listen('october.system.update', function ($manager) {  /* Some code */  });

or

    Event::listen('october.plugin.update', function ($manager) {  /* Some code */  });

##### October build
419

Thanks for taking a moment to think about this change.
Kurt Jensen

**Comment by firemankurt** [comment]
To prevent interuption of update process,  maybe there could be an "After Update"" event instead.

**Comment by firemankurt** [comment]
spunky - You mentioned in an irc chat that I should use:
      getRegistrationMethodValues('registerProfilePanels');
It turns out that was what I have been using to get info I need out of the Plugin.php files.  But what I have not been able to solve is when to trigger this.  The info I get from Plugin.php files is inserted into DB table and available for user to make subtle changes.  I only need to check the Plugin.php files again if they change.  Thus is why I would like my code to be aware ( notified ) after an update occurred.  I am not asking for opportunity to interupt or change the update process itself but just have some way of knowing that it happened in recent past.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
