### ISSUE TITLE
[L5.5] Consider adding option to change default variable length to 191 for utf8mb4 charsets

### ISSUE THREAD

**Issue by Teranode** [octobercms/october#2972]
`Illuminate\Database\Schema\Blueprint` uses a default variable charset as 255, considering that @daftspunk recently added roles and im using utf8mb4 ive come up with the error where the value can only be 191 or lower when using that charset. 

So why not make it so that when you specify in the database config that you are using utf8mb4 it will use 191 ?

**Comment by daftspunk** [comment]
Not sure. Perhaps the Laravel community might have an answer?

**Comment by Teranode** [comment]
it seems the issue has come up before but theres not a built in solution other than upgrading mysql :|, which on one hand is a solution, but then there's the issue where people "cant" upgrade due to host restrictions (im not restricted,, but im just generalising things)

**Comment by daftspunk** [comment]
What are the affected versions? We could write a known error article about it.

**Comment by Teranode** [comment]
its not the versions rather, if you are using the utf8mb4 charset, you have to either upgrade to MySQL 5.7 which defaults the config to fix the issue, or have all your migration's strings be 191 in length, or stick with utf8.

**Comment by Teranode** [comment]
its been an ongoing issue with me since L5 in where i would just leave the charset at utf8 and then manually convert to utf8mb4 (i use a lot of asian text so this is needed as some characters does not appear right unless i use this)

**Comment by daftspunk** [comment]
So if I understand this correctly the invalid default of 255 (with this utf8mb4 charset) is provided by MySQL version prior to 5.7?

**Comment by Teranode** [comment]
any version before 5.7, you would have to manually set in your my.cnf
```
innodb_large_prefix=on
innodb_file_format=barracuda
innodb_file_per_table=true
```
and with laravel the row format has to be dynamic or if you dont want to change the row format, you would have to manually set the character limit to 191.

**Comment by daftspunk** [comment]
This is addressed as part of the Laravel documentation: https://laravel.com/docs/5.4/migrations#indexes

It should become available Build 420+
