### ISSUE TITLE
October modules overwritten via composer install

### ISSUE THREAD

**Issue by petehalverson** [octobercms/october#2975]
This seems to have been an oversight. The issue goes wholly unnoticed when the composer/packagist sources are in sync with this repository's `/modules` folders.

Loading a copy of the `modules/` folder via composer seems unnecessary and is [prone](https://github.com/octobercms/october/issues/2608) to [cause](https://github.com/aspendigital/docker-octobercms/issues/1) [issues](https://github.com/aspendigital/docker-octobercms/issues/3). 

##### Expected behavior
`$ composer install` adds dependencies to the `/vendor` folder. 

##### Actual behavior
`$ composer install` unexpectedly replaces the `/modules/system`, `/modules/backend` and `/modules/cms` from other sources. 

##### Reproduce steps

```
$ git clone https://github.com/octobercms/october.git  .
$ composer install
```
> Compare timestamps of the files/folders initially pulled from the repo with the vendor folders and the modules folders that have been overwritten by composer.
```
$ ls -l . modules/
```

The issue is more obvious when checking out the `l55upgrade` branch:

```
$ git clone https://github.com/octobercms/october.git -b l55upgrade .
$ composer install
$ git status
```

##### Suggested Action

I'd suggest  `october/system`, `october/backend` and `october/cms` be removed from the [composer.json](https://github.com/octobercms/october/blob/master/composer.json#L29-L31)

##### Solution test
```
$ git clone https://github.com/octobercms/october.git -b l55upgrade .
$ sed -i '/october\/[system|backend|cms]/,+0 d' composer.json
$ composer install
$ git status
```

This took me a while to wrap my head around, so please follow up if you want me to provide some more detail!

Thanks!

**Comment by daftspunk** [comment]
This doesn't happen when your composer file looks like this

```
        "october/rain": "dev-l55upgrade",
        "october/system": "dev-l55upgrade",
        "october/backend": "dev-l55upgrade",
        "october/cms": "dev-l55upgrade",
        "laravel/framework": "5.5.*@dev"
```

However, I do understand the concern. It means you need a clean workspace before running composer update.

```
# Expect a clean workspace
git status 

# This may spam modules/ with old changes
composer update

# Revert stale changes
git checkout modules/*
```

It's not great, but it isn't an issue generally faced by consumers. The same consumers who want us to use composer.

Hope this helps! =)

**Comment by daftspunk** [comment]
Removing these packages entirely is another valid solution? However it means you must maintain these modules yourself.

**Comment by petehalverson** [comment]
@daftspunk, it does happen when the composer.json references 'dev-l55upgrade'. That branch includes that change: https://github.com/octobercms/october/blob/l55upgrade/composer.json#L30-L33

The [modules are in the repo already](https://github.com/octobercms/october/tree/master/modules), it's not clear why they're being pulled in again via composer.

**Comment by daftspunk** [comment]
It is due to the architecture of the October project. Without going in to too much detail, the vendor folder is too scary a place for modules, which act as foundations to the platform, in both code and comprehension.

This segment of the composer.json file found in modules instructs composer to install it in the modules/ directory. Plugins and themes have a similar `type` definition.

```
"type": "october-module",
```

What you are experiencing is most likely due to the fact that `l55upgrade` is a development branch and does not [get updated daily](https://github.com/octobercms/library/blob/631225e0201ec39b462d846dd71d2c42ef911603/build/rain-split.sh) like the others. As you may notice, the modules that exist in the repo are used as *the source* for the [composer](https://github.com/octoberrain/system) [packages](https://github.com/octoberrain/cms) [themselves](https://github.com/octoberrain/backend). So theoretically they are one and the same, however, it is prone to the aforementioned stale changes.

**Comment by petehalverson** [comment]
Agreed, the issue is noticable on the `l55upgrade` branch, but we've run into issues (albeit infrequently) when the packagist  repos were stale.

Since the current modules are always included with the repository, why are they required in composer.json?

From my tests, removing them from the composer.json has no effect. Am I missing something?

**Comment by daftspunk** [comment]
They are included in composer.json so running `composer update` will deploy the latest code.

1. `create-project october/october` pulls down the app files
1. `composer update` pulls down the latest module files

The october/october files are not included as part of this update process, things like boostrap, config, etc. Only the modules are included in the composer update process.

When you remove from composer.json, delete composer.lock and use composer install.

Perhaps consider the inverse solution, creating your own application repo and add modules/* to `.gitignore`? This should clear up some confusion.

Keep in mind by cloning the application repo directly, you are in the developer workflow right now, a channel for developers who want to contribute code back to the project. Modules are part of the application layer, so it exists in the application repo. There are some gotchas involved here, discussed already.

**Comment by daftspunk** [comment]
I think we may be entering [X Y territory](http://mywiki.wooledge.org/XyProblem) here.

**Comment by daftspunk** [comment]
Sorry, that's not to say you can't still respond to my previous comment @petehalverson. It just means no action will likely come of this.

**Comment by daftspunk** [comment]
Also sorry again because I'm not entire sure what the problem is you are trying to solve. Hence the XY problem (http://xyproblem.info/), otherwise we could talk about this for hours.

**Comment by anatoliyarkhipov** [comment]
Hi guys! Do I correctly understand, that `modules`, `plugins` and `themes` are handled by Composer and it's not a good idea to place them under a version control?

**Comment by LukeTowers** [comment]
Modules is controlled by composer, but plugins and themes are not.

**Comment by anatoliyarkhipov** [comment]
Thanks for the clarification @LukeTowers! Can you also tell something about best practicies of using October with a version control? Or may be you can point me to a document about it? The main concern for me is what should be controlled and what shouldn't.

**Comment by LukeTowers** [comment]
I'll try to remember to post a link to my article on my development processes when working with October here whenever I get around to finding the time to finish it.

**Comment by petehalverson** [comment]
@daftspunk, forgive me for resurrecting the discussion.

While [troubleshooting unit test result discrepancies](https://github.com/octobercms/october/issues/3488), I stumbled upon [your commit](https://github.com/octobercms/october/commit/d397fe71e778221c5a0b7ddaaf761780786cd646) that handles the issue I was referring to earlier in this conversation. 

In the Travis CI build process, the module folders are [pulled in via composer](https://travis-ci.org/octobercms/october/jobs/363327689#L559-L562), then the repo is reset to make sure the [modules contained match those in the repo](https://travis-ci.org/octobercms/october/jobs/363327689#L661).

With that context, I realize you probably understood the issue I complaining, but just believe it's worth forcing contributing developers to work around to accommodate the 'composer only' workflow. Is that correct?

I have since discovered the installer method `curl -s https://octobercms.com/api/installer | php`. It is really well done and quite slick. I would have assumed that install process would be more popular than `create-project october/october`, no?
