### ISSUE TITLE
HasOne relate failed

### ISSUE THREAD

**Issue by tim0991** [octobercms/october#2977]
##### Configuration
`product yaml`
![image](https://user-images.githubusercontent.com/26053904/28253796-d0ae21a0-6ad9-11e7-91ee-97d0d9c35f7e.png)

`model relation`
```php
class Product extends Model
{
    public $hasOne = [
        'detail' => ['\Tim\Shopbase\Models\ProductDetail']
    ];
```
`product controller`
```php
class Products extends Controller
{
    public function formExtendModel($model)
    {
        if (!$model->detail) {
            $model->detail = new \Tim\Shopbase\Models\ProductDetail;
        }

        return $model;
    }
```
##### Expected behavior
When i create a product, detail will be related

##### Actual behavior
Product fields create correctly
Detail fields create correctly, but product_id is null

I installed [test plugin](github.com/daftspunk/oc-test-plugin), and i read the code about `Person` and `Phone`, i found the problem also occurs in the plugin

##### October build
419

**Comment by Jimiwcy** [comment]
try to use
meta_desc:
tab: Seo
label:  Meta Description
span: left
type: relation
relation: detail
select: meta_desc

**Comment by tim0991** [comment]
I want to create a not exists relation data, not select an exists relation

**Comment by LukeTowers** [comment]
@tim0991 Try saving the detail model first, otherwise it won't exist.
```php
    public function formExtendModel($model)
    {
        if (!$model->detail) {
            $model->detail = new \Tim\Shopbase\Models\ProductDetail;
            $model->detail->save();
        }

        return $model;
    }
```

**Comment by tim0991** [comment]
@LukeTowers I tried your suggestion, the key of `detail` table named `product_id` is still null

**Comment by RedMarlin** [comment]
@tim0991 
As a temporary workaround you could add this in your product model:
```
public function afterCreate(){
        $detail = $this->detail;
        $detail->product_id = $this->id;
        $detail->save();
        }
```
This should relate detail to product.
