### ISSUE TITLE
Left align + block display on raweditor doesn't apply block style to an image

### ISSUE THREAD

**Issue by Co-FoundryZA** [octobercms/october#2982]
##### Expected behavior
You click left-align on an image and select the block display and it will be a left aligned block

##### Actual behavior
You do the above and it applies `float: left` and `clear: none` and no block display, causing text to wrap around it or it to run into the next div etc.

##### Reproduce steps
As above

##### October build
338

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

Also, Build 338 is really out of date. Try updating your October instance.
