### ISSUE TITLE
Richeditor image toolbar doesn't work unless there's at least one image markup class set

### ISSUE THREAD

**Issue by ed-jpeg** [octobercms/october#2984]
##### Expected behavior
After inserting an image using the rich editor and clicking on it a toolbar appears containing additional image placement and settings.

##### Actual behavior
If all image markup classes are removed, the aforementioned toolbar doesn't appear. JS error is thrown in console
`Uncaught TypeError: Cannot read property 'title' of null build-min.js?v419:114`

##### Reproduce steps
Remove all image markup classes in editor settings, add an image using the rich editor, observe console when clicking on inserted image.

##### October build
october/backend v1.0.419

**Comment by kharanenka** [comment]
We has this error on site with "https", but error not found on site with "http"

**Comment by jonostanck** [comment]
I also have this problem.
