### ISSUE TITLE
Administrator security issues if SQL injection possible

### ISSUE THREAD

**Issue by dqsully** [octobercms/october#2989]
##### Expected behavior
If for some reason a lazy developer introduces a SQL injection bug or one is otherwise found on an October CMS site, a malicious attacker should not be able to freely read/modify the file system, especially if they can read any secret keys (like payment processor info in a PHP file).

##### Actual behavior
On this theoretical site, however, that attacker could add themselves as an administrator in the backend, giving them access to install plugins like [this](http://octobercms.com/plugin/indikator-devtools), and then access to the filesystem and any secrets contained within. This is because the backend user database table does not contain any sort of signature to validate that each user was created properly, allowing the attacker to add themselves in and take over the site.

##### Reproduce steps
This is only theoretical and I haven't tested it, but the basic steps are laid out above.

##### October build
419

#### How about...
I'm certainly no security expert, so I don't know if this is the right way to go about securing the user database table, but how about this: What if we add a 'signature' column to the user database, containing a hash (HMAC, PBKDF2, or something) of each user's login, password, permissions, activation state, and superuser state (and more?), all salted with a unique private key located somewhere on the filesystem? This unique key would probably be generated randomly during the install process, and therefore be unique to each website. Also, of course, for a user to login, their 'signature' field would have to be valid.

However, even with this signature field in this situation, an attacker could still disable any accounts, locking out the owners. Maybe if a user logs in but their data is somehow corrupted, try sending a reset email to the user (somehow remembering the correct email address), or instead maybe send an email to the site's owner?

I am certainly open to programming this feature in, but if I do, I want to make sure I get it right. So then, **what are your thoughts? Is this even worth all the trouble?**

**Comment by LukeTowers** [comment]
In my mind, it's not worth the effort. If an attacker is able to add themselves as a administrator through a SQL injection (which you as a developer have to actually go out of your way to make possible, Laravel makes it difficult in general for doing that), then they have the ability to install their own plugins which gives them full access to any countermeasures that you could imagine putting in place.

As for the 'unique key' you suggest, just to let you know October already does that, it's called the Application Key and it's generated on installation. If you are using environment files, it'll be in your .env file, if not it should be in your config/app.php. This is what's used when any cryptographic functionality is engaged within October.

**Comment by dqsully** [comment]
Ok, that makes sense. I didn't know it was possible to install a plugin directly through the database, and it makes sense that the Application Key would already exist.

**Comment by LukeTowers** [comment]
It's not, but once somebody has an admin account on the site, they can login and install whatever they want. And through the CMS section they can run arbitrary code in the code section of CMS templates, so they wouldn't even need to install any plugins.

**Comment by dqsully** [comment]
That works too, but I think a signature field like this would prevent an attacker from adding themselves as an admin in the first place, or from replacing the admin's password with their own and logging in that way. It would essentially secure backend access with the secrecy of the Application Key. Even still it might not be worth it.
