### ISSUE TITLE
Backend User Unable To View Site in Maintenance Mode

### ISSUE THREAD

**Issue by AugmentBLU** [octobercms/october#2993]
##### Expected behavior
When site is in maintenance mode, Backend Users should be able to view the site as if live.

##### Actual behavior
Backend User is redirected to 404 page or whatever page is set to maintenance mode. I tried to clear cache via artisan but hasn't helped.

##### Reproduce steps
Stick site in maintenance mode, try to view site as Backend User. 

##### October build
Worked with branch 419 pre Laravel 5.5 update, not working with latest dev 419 build.

**Comment by LukeTowers** [comment]
I've discussed this with @daftspunk before, I believe we landed on the idea that we need to have a couple of different maintenance modes.

A "soft" maintenance mode triggered in the backend for presenting a maintenance mode notice to frontend consumers, and a "hard" maintenance mode that's triggered by `php artisan down` for application updates where you don't want the state of the application being changed or accessed while the updates are in progress.

**Comment by AugmentBLU** [comment]
That would be great to have different modes - however right now this is causing issues when trying to view a website that's on production but not ready to be taken out of maintenance mode. 

Is this a bug or an oversight as it was working before the l55 update I just tested.

**Comment by LukeTowers** [comment]
So are you saying that backend users can't even view the backend?

**Comment by AugmentBLU** [comment]
Backend users cannot view front-end pages while in maintenance mode and are redirected to the selected maintenance mode page. Just as if the user is not logged in to the backend.

**Comment by LukeTowers** [comment]
Isn't that the behaviour that existed before?

**Comment by AugmentBLU** [comment]
No, if the site was put in maintenance mode a Backend User could still view the site. Well for me I could view the site as normal even in maintenance mode. I have a couple sites using the build just before the l55 update and this is the behaviour.

If it's not a bug then close the issue but seems a bit strange that a Backend User cannot view pages.

**Comment by LukeTowers** [comment]
How did you put the site in maintenance mode both ways?

**Comment by AugmentBLU** [comment]
I was using the Maintenance Mode option in the backend. As I said, when using this option and logged in to the backend, I was able to still view the site but non users would be redirected to the maintenance page. 

This was helpful when deploying to a live server but not quite ready to set live - allowing for some final testing.

**Comment by amjadniazi48** [comment]
is there any single tutorial on how to enable Maintenance Mode in octobercms without any plugin, there is Maintenance Mode section in backend when i enable this and add the cms page as a Maintenance page and then logout and after that i open frontend then its shows blank page and  i don't know which page it is

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
