### ISSUE TITLE
[L5.5] Declaration of Mailer must be compatible with MailQueue

### ISSUE THREAD

**Issue by vojtasvoboda** [octobercms/october#2996]
Not sure if RainLab.User plugin problem, or OctoberCMS, but I'm getting this error when trying to activate newly inserted user:

![snimek obrazovky 2017-07-28 v 15 51 50](https://user-images.githubusercontent.com/374917/28720315-19a5b662-73ad-11e7-98dc-087f89207049.png)

##### October build
Build 419 from develop branch.

##### Steps to reproduce
- install OctoberCMS
- install RainLab.User without any additional configuration
- add new user
- click on "Activate this user manually"

**Comment by daftspunk** [comment]
Hey @vojtasvoboda thanks so much for helping with the testing. Confirmed this function is working on my end. It might be an issue with the deployment of the dev build. Let's try pushing this as an edge update so you can request the latest files from the server.

**Comment by daftspunk** [comment]
Install steps taken:

1. Run `php -r "eval('?>'.file_get_contents('https://octobercms.com/api/installer'));"`
1. Run `php artisan october:install`
1. Open `config/cms.php` set edgeUpdates to true
1. Sign in to back end
1. Perform system update
1. Install RainLab.User
1. Create and activate user
1. Tests +OK

**Comment by vojtasvoboda** [comment]
I tried it now with build 420 with `edgeUpdates` on `true` and it works now! Thanks a lot.

**Comment by kdoonboli** [comment]
I'm getting this error and I'm on build 434. What do I need to do? thx
