### ISSUE TITLE
Upgrading to edge php7 caused key length encryption error

### ISSUE THREAD

**Issue by ChadStrat** [octobercms/october#2997]
##### Expected behavior
upgrade is successful

##### Actual behavior
upgrade failed do to below screenshots

##### Reproduce steps
I do not know.  Environment info:

Apache: 2
MySql: 5.6.35
php: 7.0.15

##### October build
from 419 to 420 (I believe, I can't get back in to re-review the edge build # because of the error)

The error on build failure:
<img width="919" alt="screen shot 2017-07-29 at 11 39 44 am" src="https://user-images.githubusercontent.com/852537/28747030-5b3aac30-7453-11e7-971e-8a33ad523529.png">

The error trying to re-review the update:
<img width="1082" alt="screen shot 2017-07-29 at 11 41 20 am" src="https://user-images.githubusercontent.com/852537/28747035-685957ae-7453-11e7-9479-bf1bb76f8b83.png">

Curious if this is fixable or if I have to totally re-install my dev environment?

**Comment by axomat** [comment]
I had the same problem and could only fix it by a re-install. In my case I think it was not helped by a third party plugin that caused the upgrade process to crash mid-install, I got the same error as reported after that.

**Comment by daftspunk** [comment]
Hmm, you should've been stung by this at Build 346. See RN5: http://octobercms.com/support/article/rn-5

**Comment by daftspunk** [comment]
Either way it's an easy fix, you don't have to reinstall. We'll add add a reference to RN5 from RN9 too.
