### ISSUE TITLE
[L5.5] Errors not written to database events log

### ISSUE THREAD

**Issue by axomat** [octobercms/october#2998]
##### Expected behavior
Logs written to system.log should also be written to the database events log for viewing in the back end. 
##### Actual behavior
They are in system.log but not in the database.
##### Reproduce steps
config settings:
app.debug = true
app.log = single

backend log settings all set to on.

##### October build
420
tried on upgraded installation and fresh installation. 

However EventLog::add('mymessage') writes the message successfully to both places.

PS This was only problem found on move to 5.5 which is amazing work thanks.

**Comment by daftspunk** [comment]
Replicated this, my Event Log is empty.

**Comment by Teranode** [comment]
well i guess thats another way to put an issue ive been having since the begininning

**Comment by daftspunk** [comment]
> well i guess thats another way to put an issue ive been having since the begininning

What is the issue number?
