### ISSUE TITLE
Invalid "en" Locale - Symfony\Translation\Translator

### ISSUE THREAD

**Issue by rajakhoury** [octobercms/october#2999]
I keep getting this error between requests and I am not sure what is the triggering this, I just installed a fresh copy of October ( 419 ) without any plugins and this error showed up.

![error](https://user-images.githubusercontent.com/4506434/28750528-c2bfc3e4-74b3-11e7-90ee-2efe7cc7b94b.png)

##### October build
419 & 420

**Comment by daftspunk** [comment]
We're going to need more information to replicate this. Looks like something might be corrupted in your configuration file?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
