### ISSUE TITLE
Reorder of records in relation

### ISSUE THREAD

**Issue by vakopian** [octobercms/october#3010]
From what I can tell from the documentation the [reorder functionality](https://octobercms.com/docs/backend/reorder) is only available for "regular" lists, but not for lists in a relation. Is this correct? Is yes, is it a planned feature? 

Ideally we would just mark the column in the `config_relation.yaml` file as `reorderable` (assuming the model already uses the `Sortable` trait with the `sort_order` column) and the relation list would become drag-n-drop reorder-able in the main list (without the need to go to another page).
If the relation list view was easily customizable (see #2889), I could see implementing this mainly on the client side (using jquery and with the help of the controller `reorder` action)

**Comment by LukeTowers** [comment]
Drag-n-drop reordering isn't supported within a list either, only as it's own custom action. Thus, you can add a button to your relation controller toolbar that would link to a controller action that would handle the reordering for you. I've done this before in a client project, it works fine. Essentially you duplicate the functionality of the reorder behavior within your own plugin.

**Comment by vakopian** [comment]
thanks for your quick reply. I understand that I can implement it with a new page.
But assuming I do want to implement the drag-n-drop reorder on the main list, is there anything you could suggest? The biggest obstacle I see for such a custom implementation is that the relation list view is not easily customizable, as the `customViewPath` is not supported for relation lists.
Is there a different way to proceed without such customization? Or would I have to completely forgo using the `RelationController`?

**Comment by canthis** [comment]
@vakopian It's pretty easy. Here's example plugin how you can achieve this - [scottbedard/draganddrop](https://github.com/scottbedard/draganddrop)

**Comment by vakopian** [comment]
@canthis thank you very much, the references you gave pointed me in the right direction and I was able to implement the full functionality. I'll describe the steps here in case someone else needs it.

Assume the `Parent` model has many `Child` items in it, and we are showing the `children` using [the built-in relation mechanism](https://octobercms.com/docs/backend/relations).
Here are the steps to allow reordering the relation list **in place** (in the Parent's update screen):

1. Add the `sort_order` column and add the `Sortable` trait to `Child` model as per the [Sortable documentation](https://octobercms.com/docs/database/traits#sortable). This will allow us to call the `setSortableOrder` method that the trait provides in the controller (see step 6 below).

2. Add the following column definitions in the `columns.yaml` file that's used by the relation:
```yaml
    sort_order_handle:
        label: " "
        type: partial
        path: $/<author>/<plugin>/models/child/_reroder_handle.htm
        sortable: false
        width: 60px
    sort_order:
        invisible: true
        type: number
```
The first column adds a column for the drag-n-drop handle, using the `_reorder_handle.htm` partial, the second column is there to allow the Parent's view screen to have the proper default sort order (see step 7 below)

3. create the `_reorder_handle.htm` file in the location above with the following contents
```php
<?php
        echo '<div class="drag-handle"><input name="rcd[]" type="hidden" value="'.$record->id.'"/>☰</div>';
```
With this each table row will get the drag handle and a hidden input with the child record id as value

4. Add the [RubaXa/Sortable js library](https://github.com/RubaXa/Sortable) to your assets, for example by adding this line the `Parents` controller constructor:
```php
$this->addJs("https://cdn.rawgit.com/RubaXa/Sortable/1.6.0/Sortable.min.js");
```
5. Add the following javascript in one of your plugin's js files:
```js
function initializeSorting() {
    var $tbody = $('.drag-handle').parents('table.data tbody');
    Sortable.create($tbody[0], {
        handle: '.drag-handle',
        animation: 150,
        onEnd: function (evt) {
            var $inputs = $(evt.srcElement).find('td>div.drag-handle>input');
            var $form = $('<form style="display: none;">');
            $form.append($inputs.clone())
                .request('onReorder', {
                    complete: function () {
                        $form.remove();
                    }
                });
        }
    });
}

$(function () {
    initializeSorting();
});
```
When the drag event finishes, this posts an ajax request to the `onReorder` event handler action in the `Parents` controller.

6. Create the `onReorder` handler in `Parents` controller:
```php
public function onReorder() {
        $records = Request::input('rcd');
        $model = new Child;
        $model->setSortableOrder($records, range(1, count($records)));
}
```
7. Add the following into the `config_relation.yaml` file in the `view` section, to make sure the list is ordered based on the `sort_order` by default:
```
        defaultSort:
            column: sort_order
            direction: asc
```

That's all.
Notes:
- Unlike the built-in reorder functionality for regular lists, no modification was needed in the Child's controller (in fact you don't even have to have a controller for `Child`)
- The instructions above work if the `Parent` is already saved. Some fixes may be needed in case if [Deferred relationship](https://octobercms.com/docs/database/relations#deferred-binding) is used

**Comment by GinoPane** [comment]
Can this be applied for one-to-many relations without cross-reference table? For example, every Parent has child_id column in table. But when I get all parents for a child I want to be able to get Parents in particular order.

**Comment by zindigo** [comment]
Thanks @vakopian! It works perfectly.

I added code to change the cursor when it hovers on the handle to make it more user-friendly. In the .js file, I changed...

```
$(function () {
    initializeSorting();
});
```

to...

```
$(function () {
    initializeSorting();

    /* change cursor on hover */
    $(".drag-handle").hover(function() {
    	$(this).css('cursor','move');
		}, function() {
	    $(this).css('cursor','auto');
     });
});
```

**Comment by danielbidala** [comment]
@vakopian thanks for this solution. This is life-saver for me.

Some toughts:

1. When you add or delete child, the dom changes so sortableJS doesn't work anymore, You have to 'reinit' `initializeSorting()` function. I tried to reinit it from the function's onEnd function with no luck. As a workaround I use:

`$(document).on('ajaxAlways', function(event, context) {
	$(function () {
		initializeSorting();
	});
})`

but this doesn't work when you delete child only for add child. If anybody has a solution for this problem please share!

2. This method works even if the parent record isn't save yet (deferred binding). There is nothing to do with the parent when you sorting child.

**Comment by LukeTowers** [comment]
@bennothommo this might be nice to have in the core. @mjauvin or @daftspunk do you remember what we decided about switching to that Sortable JS library? Played around with it again just now and it seems pretty sweet.

**Comment by bennothommo** [comment]
@LukeTowers agreed. I'd be happy to tackle it after the dust settles with L6.

**Comment by bennothommo** [comment]
The only issue that would need to be considered is how to re-order records over multiple pages - would you need to disable pagination when re-ordering is enabled?

**Comment by mjauvin** [comment]
@LukeTowers didn't pursue this since @daftspunk fixed the issue we had with the current library on mobile.

**Comment by Eoler** [comment]
Great! Take a look how @tobias-kuendig did it in OFFLINE plugins:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/controllers/Categories.php

**Comment by daftspunk** [comment]
Moved to and added in #5298

Documentation can be found here: https://docs.octobercms.com/3.x/extend/lists/structures.html#sorting-related-records
