### ISSUE TITLE
How to get sorted, filtered connected images (system_files) of all records

### ISSUE THREAD

**Issue by maartenmachiels** [octobercms/october#3013]
##### Expected behavior
I've built a plugin using the builder plugin. Each record of my plugin contains several images, handled by the system_files functionality of October CMS. In my model, I've defined the relation of the images as follows:
```
    public $attachMany = [
        'images' => 'System\Models\File'
    ];
```
When I loop over each record (each displayed on a different page), there is no problem showing the attached images. I loop over them in via Twig tags and get the path as follows:

```
{% for image in record.images %}
{{ image.path }}
{% endfor %}
```

I need to have an overview page that displays the 10 most recent connected images regardless of their record. Since this is very specific I tried using the query builder in an `onStart()` function in the PHP section of my page.

```
function onStart() {
    $this['images'] = Db::table('system_files')->where('attachment_type','Chocolata\ProjectViewer\Models\Project')->orderBy('created_at', 'desc')->take(10)->get();
}
```

This does exactly what I want it to do, except that there is no way to get the full path of the images I'm looking for. I tried recreating the system path manually, but I keep running into errors. 

##### Actual behavior
Getting the exact path of the system_files based on `disk_name` seems to be impossible when using the query builder. I am looking for the optimal way to display the last 10 system_images connected to my plugin and am completely lost.

##### Reproduce steps
Tried reproducing the base path like this  `'storage\app\uploads\public\first 3 letters of filename\second 3 letters of filename\3rd 3 letters of filename\filename.jpg'` in Twig aswel as in PHP, but keep running into errors. There has to be a better way.

##### October build
419

Could someone please advise? Is there some mistake in my approach? Thanks in advance.

Related: 
[https://octobercms.com/forum/post/link-to-public-image](https://octobercms.com/forum/post/link-to-public-image)

**Comment by LukeTowers** [comment]
@maartenmachiels:
```php
function onStart() {
    $this['images'] = \System\Models\File::where('attachment_type','Chocolata\ProjectViewer\Models\Project')->orderBy('created_at', 'desc')->take(10)->get();
}
```

**Comment by maartenmachiels** [comment]
It sounds almost too easy :-) Works perfectly Luke, thank you for looking into it.
