### ISSUE TITLE
Please amend the function in querybulider for php 7.1 user

### ISSUE THREAD

**Issue by minggor0415** [octobercms/october#3015]
##### Expected behavior
Show correct page (e.g. categories page for blog post) in php 7.1

##### Actual behavior

Error Page shown 
A non-numeric value encountered
_/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php line 1262_
**TYPE**
PHP Content

**EXCEPTION**
ErrorException
```
 * @param  int  $page     * @param  int  $perPage     * @return \Illuminate\Database\Query\Builder\|static     */    public function forPage($page, $perPage = 15)    {        return $this->skip(($page - 1) * $perPage)->take($perPage);    }      /**     * Add a union statement to the query.     *     * @param  \Illuminate\Database\Query\Builder\|\Closure  $query
-- | --

```

`

##### Reproduce steps
Use Rainblog bug in with blog catergories competent 

##### October build
latest

##### solution 

> New E_WARNING and E_NOTICE errors have been introduced when invalid strings are coerced using operators expecting numbers or their assignment equivalents. An E_NOTICE is emitted when the string begins with a numeric value but contains trailing non-numeric characters, and an E_WARNING is emitted when the string does not contain a numeric value.

Therefore,  the code should be amended to 
```
    public function forPage($page, $perPage = 15)
    {
        return $this->skip(( (int)$page - 1) * (int)$perPage)->take( (int)$perPage);
    }

```

**Comment by Teranode** [comment]
This has been a confirmed bug for me since php 7.0

**Comment by fxfoo1** [comment]
I got this bug with PHP 7.1.6

**Comment by LukeTowers** [comment]
@minggor0415 @Teranode @fxfoo1 I cannot replicate this bug with the RainLab.Blog Posts component correctly configured. I can however replicate when the Posts component is incorrectly setup and it passes `"default"` as the `page` to the `listFrontEnd()` Post model scope.

I'm leery to carte blanche convert input to integers as it debatably should fail on invalid input and not silently accept it.

**Comment by Teranode** [comment]
This happens with the forum plugin also, im guessing they use the same paginator execution pattern

**Comment by LukeTowers** [comment]
As above @Teranode

**Comment by judgej** [comment]
I'm going to guess it's an empty string that is triggering this. A numeric string will get cast automatically, as will a null (to zero). An empty string needs an explicit cast to be interpreted as zero:

```php
php > echo '2' + 2;
4
php > echo '' + 2;
PHP Warning:  A non-numeric value encountered in php shell code on line 1
2
php > echo (int)'' + 2;
2
php > echo null + 2;
2
```

This is PHP 7.1.8

Another way to handle it is a ternary operator. This will at least raise an exception if a non-empty and non-numeric string is provided, which is something you kind of want to know and not try to mask over, so you can get to the source:

```php
php > $page = '';
php > echo ($page ?: 0) + 2;
2
php > $page = 'x';
php > echo ($page ?: 0) + 2;
PHP Warning:  A non-numeric value encountered in php shell code on line 1
2
```

**Comment by LukeTowers** [comment]
@judgej this is a good idea, however I wonder if it should continue to be super strict and require developers to pass valid arguments rather than eat up invalid string inputs?

**Comment by 3309** [comment]
same error on comments section with forum

code amended and works...

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/library/commit/384024082f8425e45c3b308af4a3deb2c5f17aaf

**Comment by jeison24** [comment]
I got this bug with PHP 7.2.0

How I can fixed ?

**Comment by LukeTowers** [comment]
@jeison24 are you using the code in https://github.com/octobercms/library/commit/384024082f8425e45c3b308af4a3deb2c5f17aaf

**Comment by jeison24** [comment]
@LukeTowers Yes, I fixed with that. But there is not other solution from laravel?

**Comment by LukeTowers** [comment]
Not sure what you're looking for @jeison24?

**Comment by Aloha276** [comment]
Same error with PHP 7.2.10, any updates from Laravel for the 5.5 version?
