### ISSUE TITLE
"backend/layouts/_mainmenu.htm" have hard coded language variable

### ISSUE THREAD

**Issue by angelside** [octobercms/october#3017]
"modules/backend/layouts/_mainmenu.htm" have hard coded language variable:

```
<a
    ...
    title="Signed in as <?= e($this->user->full_name) ?>">
```

https://github.com/octobercms/october/blob/develop/modules/backend/layouts/_mainmenu.htm#L54

##### October build
420 and dev branch

----------

I made some preparations, I need just confirmation, then I send PR. Is 'signed_as' variable is okey? Or any  suggestion?

```
<a
    ...
    title="<?= e(trans('backend::lang.account.signed_as', ['full_name' => $this->user->full_name])) ?>">
```

backend::lang.account.signed_as
```
'account' => [
    'signed_as' => 'Signed in as :full_name',
```

**Comment by LukeTowers** [comment]
How about `signed_in_as`?

**Comment by angelside** [comment]
Sounds good, thanks. I send PR with "signed_in_as" in five-ten min.
