### ISSUE TITLE
minDate cannot be set for date or daterange filters

### ISSUE THREAD

**Issue by jasminhassan** [octobercms/october#3019]
##### Expected behavior
you set minDate in your filter scope for a type date/daterange and it overrides the default minDate which is '2000-1-1'
I'm basically trying to set a minDate of something like '1900-1-1' to allow to use as birth date filter.

##### Actual behavior
If you set minDate in your filter scope for a type date/daterange, you get an error
Undefind property: Backend\Classes\FilterScope::$minDate
october/modules/backend/widgets/filter/partials/_scope_date.htm line 8

![screenshot from 2017-08-05 11-13-07](https://user-images.githubusercontent.com/512891/28994872-26335a88-79d9-11e7-86ae-c832e48f58b5.png)

##### Reproduce steps
Just define a filter scope of type date or daterange with minDate also in your config_filter.yaml, or by overriding the listFilterExtendScopes method and adding to the scope a filter with the above.

##### October build
v1.0.419

**Comment by LukeTowers** [comment]
Fixed by #3021
