### ISSUE TITLE
L5.5 changes Mail::queue() to expect Mailable class as first parameter

### ISSUE THREAD

**Issue by firemankurt** [octobercms/october#3025]
##### Old working behavior
Mail::queue('fireunion.mailstuff::mail.order_template', $data, function ($message) use ($recipient) {
			$message->to($recipient['email'], $recipient['name']);
		});

( Causes error about Mail::queue() expecting MAilable class in L5.5 )

##### New working behavior
Mail::to($recipient['email'], $recipient['name'])->queue(
			new OrderMailable($data)
		);

##### Reproduce steps
See sample plugin for illustration:   https://github.com/firemankurt/October-Mailstuff

##### October build
420

**Comment by rajakhoury** [comment]
Has anyone tried SQS or Redis queues on this build ? Im having tons of errors 

Predis Error :
Predis\Response\ServerException: ERR unknown command 'EVAL' in

SQS Error :
exception 'Aws\Sqs\Exception\SqsException' with message 'Error executing "ReceiveMessage" on "https://sqs.us-east-1.amazonaws.com/default.

In the logs I can see SQS is not sending the correct queue URL.. instead should be https://sqs.us-east-1.amazonaws.com/XXXXXX/queuename

Tried to update October Drivers package.json

**Comment by LukeTowers** [comment]
@rajakhoury do not hijack other issues please, make your own issue reports with detailed information on your own issue. SQS or Redis queue issues has nothing to do with the `Mail::queue()` method.

**Comment by rajakhoury** [comment]
@LukeTowers sure, that wasnt my intention. will do next time

**Comment by rajakhoury** [comment]
That seems to work but if I add ` App::before` it doesn't, is this a normal behavior ?

**Comment by LukeTowers** [comment]
@rajakhoury I think you're commenting on the wrong issue again

**Comment by wilirius** [comment]
Head scratching here, not really sure how mail templates are coded, but would taking October's mail-templates and replacing them or have them wrap over Mailables work?

**Comment by firemankurt** [comment]
@wilirius Mailables still use same templates ( view ) as old October.  Mail class where the real change is and it is simply a mater of creating a new class that extends Illuminate\Mail\Mailable to process the view first before passing it to Mail class.

See: https://github.com/firemankurt/October-Mailstuff/blob/master/mailables/OrderMailable.php

And other examples there.

**Comment by wilirius** [comment]
This will require creating a class extending Mailable for each template though, correct?

**Comment by firemankurt** [comment]
@wilirius
Not necessarily.
A single class could be cleverly crafted to serve for several templates.  You would just pass in the data and the template name (i.e. filename or part of if all template lived in same directory ).

Pretty simple actually. Just different that what was done before.

**Comment by daftspunk** [comment]
This should be fixed in Build 421+ both old and new methods should now be accepted.
