### ISSUE TITLE
Interface 'Illuminate\View\Engines\EngineInterface' not found

### ISSUE THREAD

**Issue by mbaxter91288** [octobercms/october#3026]
After running a `composer update` this morning, upon a fresh `php artisan october:up` I get the following error:
```
[Symfony\Component\Debug\Exception\FatalErrorException]        
  Interface 'Illuminate\View\Engines\EngineInterface' not found 
```

##### Reproduce steps
Created a clean fresh project using `composer create-project october/october test` and then ran `php artisan october:up`

Tried looking through some of the latest commits, but couldn't see anything obvious that would cause this.

**Comment by mbaxter91288** [comment]
Done a little more investigation. The `SeedSetupMailLayouts.php` file runs `MailLayout::createLayouts();`, which on line 135 runs `return MailParser::parse(File::get(View::make($code)->getPath()));` at some point. Not sure what this all means, but removing the `MailLayout::createLayouts();` for the time being allows the other migrations and seeds to complete successfully, hopefully this might help root down the issue?

**Comment by intro1987** [comment]
Look at here
/modules/system/Twig/Engine.php line 12
trying to implement EngineInterface

**Comment by mbaxter91288** [comment]
This error also appears when viewing the mail templates backend page.

**Comment by intro1987** [comment]
Try change laravel version to 5.4 in composer.json, then run composer update again.

**Comment by mbaxter91288** [comment]
@intro1987 I am using the latest build for laravel 5.5 though :-/

**Comment by LukeTowers** [comment]
@mbaxter91288 what does your composer.json look like?

**Comment by Teranode** [comment]
@LukeTowers can confirm that this error appears in the mail templates page. Gonna look for the issue.

**Comment by aftabnaveed** [comment]
I just pulled the develop branch, but looks like this problem still exists during installation through command line. 

```
  [Symfony\Component\Debug\Exception\FatalErrorException]        
  Interface 'Illuminate\View\Engines\EngineInterface' not found  
````

**Comment by LukeTowers** [comment]
@aftabnaveed how did you pull it? Are you using composer? If so, what's your composer.json?

**Comment by roulendz** [comment]
I have the same issue when I do october:isntall

But before that, I had when I did composer update

`
 php artisan october:util set build
-
*** You were kicked from #october by Ex: (Database (storage/database.sqlite) does not exist. (SQL: select * from "system_parameters" where "namespace" = system and "group" = project and "item" = id limit 1))
-
Ping? Pong!
-
Ping? Pong!
-
`

What does it mean?

**Comment by LukeTowers** [comment]
@roulendz Exactly what it says: `Ex: (Database (storage/database.sqlite) does not exist.`
One of the post-composer commands that is run is `php artisan october:util set build`. This sets the build number, which utilizes the `System\Models\Parameter` model class, which requires the use of the database; which in your case either does not exist or is setup incorrectly.

Please create a new issue for that so that we can properly support database-less versions of October with that command.
