### ISSUE TITLE
[L5.5] - Auth in Middleware

### ISSUE THREAD

**Issue by rajakhoury** [octobercms/october#3028]
##### Expected behavior
return the logged in user - exact same code on build 419 works fine.

##### Actual behavior
`Auth::getUser()` returns null has no effect

##### Reproduce steps
In Plugin.php

    public function boot()
    {
	    $this->app['Illuminate\Contracts\Http\Kernel']
		    ->prependMiddleware('MyPlugin\Middlewares\MyMiddleware'); // or push

    }

MyMiddleware.php

    class MyMiddleware
	{
	
	    public function handle($request, Closure $next)
	    {
	
	
	        App::before(function () {
	
		        if (App::runningInBackend() || App::runningInConsole()) {
			        return;
		        }
	              
                       $translator = Translator::instance();
	
	                if (!$translator->isConfigured()){
		              return;
	                 }
	
	                if ( $user = Auth::getUser() ) {
	
	                   var_dump($user); // returns null
	
	                    $translator->setLocale($user->getLocale());
	                }
	
	        });
	
	        return $next($request);
	    }
	
	}

##### October build
420

**Comment by munxar** [comment]
As @LukeTowers helped me with this, laravel 5.2(?) changed the default global routes.
To enable the session, add the 'web' middleware. Checkout the laravel docs ->
https://laravel.com/docs/5.4/middleware#registering-middleware

**Comment by rajakhoury** [comment]
@munxar  Thanks. According to the [docs ](https://octobercms.com/docs/plugin/registration#registering-middleware) that's how to add a Middleware from a plugin in October, the link you posted shows how to assign a web or api middleware to routes.

Sorry for my ignorance but how would you achieve this from a plugin ? push a middleware to the web group ?

**Comment by munxar** [comment]
@rajakhoury You're right, the docs link was a little bit misleading. The message is: 'default middle wares changed'.
The Auth facade from the RainLab.User bundle depends on cookies an session, so i'll guess this is not by default enabled in L5.5.
try to add the EncryptCookies middleware before yours:

`$this->app['Illuminate\Contracts\Http\Kernel']
            ->prependMiddleware(\Illuminate\Cookie\Middleware\EncryptCookies::class)
            ->prependMiddleware('MyPlugin\Middlewares\MyMiddleware')
            ;`

**Comment by rajakhoury** [comment]
@munxar No luck so far. 

      $this->app['Illuminate\Contracts\Http\Kernel']
	     ->prependMiddleware( EncryptCookies::class )
         ->prependMiddleware( MyMiddleware::class );

then in Middleware class : 

    public function handle($request, Closure $next)
    {
          App::before(function () {

 	         var_dump( Auth::getUser() );  // null
         });

        return $next($request);
    }

**Comment by munxar** [comment]
than it's more a bug in the RainLab.User plugin, no?

**Comment by LukeTowers** [comment]
@rajakhoury Don't put your middleware directly on the kernel, that's too early for the session handling to initialize correctly. Attach your middleware directly to the CMS controller as described [here](https://octobercms.com/docs/plugin/registration#registering-middleware) and it will work correctly. Attaching it to the CMS controller will attach it to all frontend requests.

**Comment by LukeTowers** [comment]
As a side note about Auth in custom routes:

Add the `web` middleware to your route and it will work. Session handling and other related middleware components are no longer run on every single route by default in Laravel 5.5 so you need to add the `web` middleware to your routes for it to work. There are some related issues to this with the RainLab.Translate plugin. See rainlab/translate-plugin#288

**Comment by daftspunk** [comment]
You need to make sure your middleware comes after `Illuminate\Session\Middleware\StartSession` otherwise you won't be able to access the session. More than likely this is caused by a race condition since Laravel now starts the session as middleware, as opposed to in the bootstrap process, as it was before.

Try appending the middleware, instead of prepending.
