### ISSUE TITLE
cms.linkPolicy=force only force hostname

### ISSUE THREAD

**Issue by adsa95** [octobercms/october#3030]
##### Expected behavior
When using cms.linkPolicy=force all links should start with what's in app.url, forcing both hostname and schema as stated in the default config/cms.php.

##### Actual behavior
When the setting is 'force' it seems to be using the 'detect' mode for schema but 'force' for hostname, if I connect with https then all links are https, when i connect with http then all links are http.

Redirecting admin to https still works (cms.backendForceSecure). I've tried on both my local machine (debug true) and on my host (url for checking [driverzone.se](http://driverzone.se/)), where current settings are cms.linkPolicy=force and app.url=https://driverzone.se/, also run cache:clear and view:clear. Changing linkPolicy to 'secure' works like a charm.

##### Reproduce steps
Set cms.linkPolicy to 'force', use URL::to() or the |page filter.

##### October build
419

**Comment by adsa95** [comment]
Actually, it seems to be forcing the domain but not the schema, as it says it should in config/cms.php.

**Comment by adsa95** [comment]
I think I might have found the cause of this. In `UrlServiceProvider` this is what happens when you use the 'force' mode:
````php
case 'force':
    $appUrl = $this->app['config']->get('app.url');
    $this->app['url']->forceRootUrl($appUrl);
    break;
````
````php
public function forceRootUrl($root)
{
    $this->forcedRoot = rtrim($root, '/');
    $this->cachedRoot = null;
}
````
While the 'secure' mode uses `$this->app['url']->forceSchema('https');`.

Then in `UrlGenerator` in the `to()` method you'll find `$scheme = $this->getScheme();` and `$root = $this->getRootUrl($scheme);` The `getRootUrl()` method looks like this:
````php
protected function getRootUrl($scheme, $root = null)
{
    if (is_null($root)) {
        if (is_null($this->cachedRoot)) {
            $this->cachedRoot = $this->forcedRoot ?: $this->request->root();
        }

        $root = $this->cachedRoot;
    }

    $start = Str::startsWith($root, 'http://') ? 'http://' : 'https://';

    return preg_replace('~'.$start.'~', $scheme, $root, 1);
}
````
As you can see, the scheme section of the forcedRoot variable is overwritten to what's in the $scheme variable, which comes from `getScheme()` which does not look at the `forcedRoot` variable set using `forceRootUrl()` to find the schema.

Changing to this in `UrlServiceProvider.php` seems to fix the problem:
````php
case 'force':
    $appUrl = $this->app['config']->get('app.url');
    $schema = \Str::startsWith($appUrl, 'http://') ? 'http' : 'https';
    $this->app['url']->forceRootUrl($appUrl);
    $this->app['url']->forceSchema($schema);
    break;
````

**Comment by LukeTowers** [comment]
Great work @adsa95, much appreciated!
