### ISSUE TITLE
I can't see Logs on backend

### ISSUE THREAD

**Issue by dunets** [octobercms/october#3031]
The problem is that I can't see any logs on the backend. There are no errors
![image](https://user-images.githubusercontent.com/6217617/29241393-b1e6a070-7f70-11e7-979f-d9518f0dbc80.png)

But the logs are stored on a `/storage/logs/system.log` file...
![image](https://user-images.githubusercontent.com/6217617/29241402-f9f8507a-7f70-11e7-93fc-97c5c427e6c0.png)

I already have the file permissions setted to -777

![image](https://user-images.githubusercontent.com/6217617/29241420-3ecbf17a-7f71-11e7-9c29-64aa4b3013dd.png)
(inc. storage and log folder)

DEVELOPER MODE is ON,
OCTOBER BUILD: 419

**Comment by PopcornPHP** [comment]
Hi @dunets , are you using development branch?, this issue has been solved at the last commit on July 31 https://github.com/octobercms/october/commit/11abddf0b6fca7ab5fa7d22dcc20b3a8ba7ac7fc

Try to update your project

**Comment by dunets** [comment]
@PopcornPHP hello! I confirm that I have different `modules/system/ServiceProvider.php` file... so I'm not using the developmente branch... but I don't understand why... I installed the app normally
