### ISSUE TITLE
Mail style messed up CMS style

### ISSUE THREAD

**Issue by ebashu-on-holidays** [octobercms/october#3032]
Hi! In section of settings 'Mail configuration', I am select 'Mail method' - 'Log file'. When I sent the letter and went into the logs - I saw this:

![untitled-1 copy](https://user-images.githubusercontent.com/20097205/29244096-712380ec-7fb8-11e7-8889-bd1c74f377a6.jpg)

Mail style messed up CMS style. In the bottom of this page - I saw HTML layout of this email with CSS styles

**Comment by LukeTowers** [comment]
Perhaps we need to load the Mail preview in an iframe to isolate it from the main October instance?

**Comment by PopcornPHP** [comment]
I think so, but it's up to you

**Comment by daftspunk** [comment]
@dshoreman introduced this a while back, I knew it would be an issue but haven't gotten around to fixing it yet. We can use shadow DOM for this.

**Comment by LukeTowers** [comment]
@daftspunk I like that idea, using shadow DOM sounds good to me. Don't have time to implement it myself at the moment but my vote's for that route

**Comment by munxar** [comment]
@LukeTowers @daftspunk Be aware that shadow DOM right now just works in chrome, opera and android.
[shadow dom](http://caniuse.com/#feat=shadowdom)
iframes on the other hand, work in every [stupid browser on earth](http://caniuse.com/#feat=iframe-sandbox) . I'm not a fan of windows, but a lot of our customers (backend users) use IE 11 or Edge.

**Comment by daftspunk** [comment]
With regards to @munxar's comments. We either fail gracefully (disable the tab all together) or we should copy the iframe logic found on the Mail Brand Settings page. I'm not in favor of mixing DOM and iframe in the same solution. The iframe logic in Mail Brand Settings is more complex but it is my preferred choice with consideration to older browsers.

**Comment by LukeTowers** [comment]
@daftspunk let's go with the iframe logic. As a note, this is in the preview of a log generated by sending an email while mail settings are set to log.
