### ISSUE TITLE
EngineInterface not found

### ISSUE THREAD

**Issue by AugmentBLU** [octobercms/october#3033]
I'm trying to pull the latest build 420 from git using composer, however it seems to always pull in 419.

##### Expected behavior
Either creating from scratch (clone) or updating an existing build should pull in the latest dev build which is currently 420. 

##### Actual behavior
Downloads successfully and completes install but says it's build 419 and getting ` Interface ‘Illuminate\View\Engines\EngineInterface’ not found` error.

##### Reproduce steps
Either creating from scratch (clone) or updating an existing build does not pull the latest build from git. My composer file is identical to that on the dev branch on git, I even see Laravel 5.5 is in the vendor files but if I check the local Twig Engine files against the latest on Git and it does not match.

It should be this file
https://github.com/octobercms/october/blob/develop/modules/system/twig/Engine.php

But I see this
https://github.com/octobercms/october/blob/master/modules/system/twig/Engine.php

This happens when cloning or updating existing project, locally or on Digital Ocean. I haven't checked for other file mismatches but seems odd that the incorrect build is being pulled.

I have tried to clear the composer cache, cloned a completely fresh install but nothing seems to work.

##### October build
Should be 420 if Cloned but always references 419

**Comment by LukeTowers** [comment]
@AugmentBLU what does your composer.json look like?

**Comment by Teranode** [comment]
@LukeTowers I mentioned this "many" times but the version always defaults to 419 when updating from composer. The modules directory does not update at all.

**Comment by AugmentBLU** [comment]
This is the composer from the fresh git clone. 

```
{
    "name": "october/october",
    "description": "October CMS",
    "homepage": "http://octobercms.com",
    "keywords": [
        "october",
        "cms",
        "octobercms",
        "laravel"
    ],
    "license": "MIT",
    "authors": [
        {
            "name": "Alexey Bobkov",
            "email": "aleksey.bobkov@gmail.com",
            "role": "Co-founder"
        },
        {
            "name": "Samuel Georges",
            "email": "daftspunky@gmail.com",
            "role": "Co-founder"
        }
    ],
    "support": {
        "issues": "https://github.com/octobercms/october/issues",
        "forum": "http://octobercms.com/forum/",
        "docs": "http://octobercms.com/docs/",
        "irc": "irc://irc.freenode.net/october",
        "source": "https://github.com/octobercms/october"
    },
    "require": {
        "php": ">=7.0",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "october/rain": "dev-develop",
        "october/system": "dev-develop",
        "october/backend": "dev-develop",
        "october/cms": "dev-develop",
        "laravel/framework": "5.5.*@dev",
        "wikimedia/composer-merge-plugin": "dev-master"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "phpunit/phpunit": "~5.7",
        "phpunit/phpunit-selenium": "~1.2"
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php",
            "tests/UiTestCase.php",
            "tests/PluginTestCase.php"
        ]
    },
    "scripts": {
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-update-cmd": [
            "php artisan october:util set build"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "merge-plugin": {
            "include": [
                "plugins/*/*/composer.json"
            ],
            "recurse": true,
            "replace": false,
            "merge-dev": false
        }
    }
}
```

This is a composer file from an existing project. There's a couple extra packages here but all seem to work fine since Laravel 5.5 is in the vendor directory.

```
{
    "name": "october/october",
    "description": "October CMS",
    "homepage": "http://octobercms.com",
    "keywords": ["october", "cms", "octobercms", "laravel"],
    "license": "MIT",
    "authors": [
        {
            "name": "Alexey Bobkov",
            "email": "aleksey.bobkov@gmail.com",
            "role": "Co-founder"
        },
        {
            "name": "Samuel Georges",
            "email": "daftspunky@gmail.com",
            "role": "Co-founder"
        }
    ],
    "support": {
        "issues": "https://github.com/octobercms/october/issues",
        "forum": "http://octobercms.com/forum/",
        "docs": "http://octobercms.com/docs/",
        "irc": "irc://irc.freenode.net/october",
        "source": "https://github.com/octobercms/october"
    },
    "require": {
        "php": ">=7.0",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "october/rain": "dev-develop",
        "october/system": "dev-develop",
        "october/backend": "dev-develop",
        "october/cms": "dev-develop",
        "laravel/framework": "5.5.*@dev",
        "wikimedia/composer-merge-plugin": "dev-master",
        "jenssegers/date": "^3.2",
        "league/glide-laravel": "^1.0",
        "roumen/sitemap": "^2.6"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "phpunit/phpunit": "~5.7",
        "phpunit/phpunit-selenium": "~1.2"
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php",
            "tests/UiTestCase.php",
            "tests/PluginTestCase.php"
        ]
    },
    "scripts": {
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-update-cmd": [
            "php artisan october:util set build"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "merge-plugin": {
            "include": [
                "plugins/*/*/composer.json"
            ],
            "recurse": true,
            "replace": false,
            "merge-dev": false
        }
    }
}

```

**Comment by PopcornPHP** [comment]
Hi. This problem was fixed on this commit https://github.com/octobercms/october/commit/928a12379128b8d0a559df6939aa3a5b915011c3

**Comment by AugmentBLU** [comment]
Yes but some of us cannot pull in the new commits or build 420 via composer as explained.

**Comment by munxar** [comment]
This is what composer points to [https://packagist.org/packages/october/system](https://packagist.org/packages/october/system).
As you see it points to this subtree split repo [https://github.com/octoberrain/system](https://github.com/octoberrain/system)
If you check this file [https://github.com/octoberrain/system/blob/master/twig/Engine.php](https://github.com/octoberrain/system/blob/master/twig/Engine.php) you'll see that it doesn't have the fix.
This is why composer doesn't work.

**Comment by AugmentBLU** [comment]
Yeah that looks incorrect, any chance that this can be fixed asap so we can update via composer properly?

**Comment by LukeTowers** [comment]
@AugmentBLU side note, you really shouldn't be pulling in packages via your project's repository. See https://luketowers.ca/blog/how-to-use-laravel-packages-in-october-cms-plugins/ for more indepth on information on how to best manage that.

**Comment by LukeTowers** [comment]
@AugmentBLU @munxar the octoberrain copy has been updated, composer should now work correctly.
