### ISSUE TITLE
After composer create-project instalation a lots of bags

### ISSUE THREAD

**Issue by KonstantinObuhov** [octobercms/october#3034]
##### Actual behavior
**Step 2** 

Installing october/october (v1.0.420)
  - Installing october/october (v1.0.420): Loading from cache
Created project in .
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 81 installs, 0 updates, 0 removals
  - Installing composer/installers (v1.4.0): Loading from cache
  - Installing wikimedia/composer-merge-plugin (dev-master 0e7f98d): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.4.0): Loading from cache
  - Installing twig/twig (v2.4.3): Loading from cache
  - Installing symfony/yaml (v3.3.6): Loading from cache
  - Installing oyejorge/less.php (v1.7.0.14): Loading from cache
  - Installing linkorb/jsmin-php (1.0.0): Loading from cache
  - Installing league/csv (8.2.2): Loading from cache
  - Installing leafo/scssphp (v0.6.7): Loading from cache
  - Installing symfony/var-dumper (v3.3.6): Loading from cache
  - Installing jakub-onderka/php-console-color (0.1): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
  - Installing nikic/php-parser (v3.1.0): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v3.3.6): Loading from cache
  - Installing symfony/console (v3.3.6): Loading from cache
  - Installing psy/psysh (v0.8.11): Loading from cache
  - Installing vlucas/phpdotenv (v2.4.0): Loading from cache
  - Installing symfony/css-selector (v3.3.6): Loading from cache
  - Installing tijsverkoyen/css-to-inline-styles (2.2.0): Loading from cache
  - Installing symfony/routing (v3.3.6): Loading from cache
  - Installing symfony/process (v3.3.6): Loading from cache
  - Installing symfony/http-foundation (v3.3.6): Loading from cache
  - Installing symfony/event-dispatcher (v3.3.6): Loading from cache
  - Installing symfony/http-kernel (v3.3.6): Loading from cache
  - Installing symfony/finder (v3.3.6): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing egulias/email-validator (2.1.2): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.0.1): Loading from cache
  - Installing paragonie/random_compat (v2.0.10): Loading from cache
  - Installing ramsey/uuid (3.7.0): Loading from cache
  - Installing psr/simple-cache (1.0.0): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/translation (v3.3.6): Loading from cache
  - Installing nesbot/carbon (1.22.1): Loading from cache
  - Installing mtdowling/cron-expression (v1.2.0): Loading from cache
  - Installing monolog/monolog (1.23.0): Loading from cache
  - Installing league/flysystem (1.0.41): Loading from cache
  - Installing erusev/parsedown (1.6.3): Loading from cache
  - Installing doctrine/inflector (v1.1.0): Loading from cache
  - Installing laravel/framework (dev-master 4158146): Loading from cache
  - Installing laravel/tinker (v1.0.2): Loading from cache
  - Installing kriswallsmith/assetic (v1.4.0): Loading from cache
  - Installing jenssegers/date (v3.2.12): Loading from cache
  - Installing erusev/parsedown-extra (0.7.1): Loading from cache
  - Installing doctrine/collections (v1.5.0): Loading from cache
  - Installing doctrine/cache (v1.7.0): Loading from cache
  - Installing doctrine/annotations (v1.5.0): Loading from cache
  - Installing doctrine/common (v2.7.3): Loading from cache
  - Installing doctrine/dbal (v2.5.13): Loading from cache
  - Installing october/rain (dev-develop 86ff743): Loading from cache
  - Installing october/system (dev-develop 586f3b4): Loading from cache
  - Installing october/backend (dev-develop 1808b0c): Loading from cache
  - Installing october/cms (dev-develop 77a0b47): Loading from cache
  - Installing fzaninotto/faker (v1.6.0): Loading from cache
  - Installing sebastian/recursion-context (2.0.0): Loading from cache
  - Installing sebastian/exporter (2.0.0): Loading from cache
  - Installing sebastian/diff (1.4.3): Loading from cache
  - Installing sebastian/comparator (1.2.4): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.2): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.0): Loading from cache
  - Installing webmozart/assert (1.2.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0): Loading from cache
  - Installing phpdocumentor/type-resolver (0.3.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (3.2.2): Loading from cache
  - Installing phpspec/prophecy (v1.7.0): Loading from cache
  - Installing myclabs/deep-copy (1.6.1): Loading from cache
  - Installing sebastian/global-state (1.1.1): Loading from cache
  - Installing sebastian/environment (2.0.0): Loading from cache
  - Installing sebastian/object-enumerator (2.0.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (3.4.4): Loading from cache
  - Installing phpunit/php-code-coverage (4.0.8): Loading from cache
  - Installing phpunit/phpunit (5.7.21): Loading from cache
  - Installing phpunit/phpunit-selenium (1.4.1): Loading from cache
symfony/var-dumper suggests installing ext-symfony_debug ()
symfony/console suggests installing symfony/filesystem ()
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install does
n't already support readline or libedit.)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/dependency-injection (For loading routes from a service)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/browser-kit ()
symfony/http-kernel suggests installing symfony/class-loader ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate ran
dom bytes.)
ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenera
tor)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and Pe
clUuidRandomGenerator)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form)
.)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
symfony/translation suggests installing symfony/config ()
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqp
lib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applicat
ions)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (~3.0).)

laravel/framework suggests installing guzzlehttp/guzzle (Required to use the Mailgun and Mandrill mail drivers and the p
ing methods on schedules (~6.0).)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).
)
laravel/framework suggests installing nexmo/client (Required to use the Nexmo transport (~1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (~1.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (~2.0).)
laravel/framework suggests installing symfony/dom-crawler (Required to use most of the crawler integration testing tools
 (~3.3).)
laravel/framework suggests installing symfony/psr-http-message-bridge (Required to psr7 bridging features (0.2.*).)
kriswallsmith/assetic suggests installing leafo/lessphp (Assetic provides the integration with the lessphp LESS compiler
)
kriswallsmith/assetic suggests installing ptachoire/cssembed (Assetic provides the integration with phpcssembed to embed
 data uris)
kriswallsmith/assetic suggests installing leafo/scssphp-compass (Assetic provides the integration with the SCSS compass
plugin)
kriswallsmith/assetic suggests installing patchwork/jsqueeze (Assetic provides the integration with the JSqueeze JavaScr
ipt compressor)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
Writing lock file
Generating autoload files
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 0 removals
Generating autoload files

# Here bug 1
> php artisan october:util set build
*** You were kicked from #october by Ex: (SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using passwo
rd: NO) (SQL: select * from `system_parameters` where `namespace` = system and `group` = project and `item` = id limit 1
))
Ping? Pong!
Ping? Pong!

> php artisan october:util set build
*** You were kicked from #october by Ex: (SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using passwo
rd: NO) (SQL: select * from `system_parameters` where `namespace` = system and `group` = project and `item` = id limit 1
))
Ping? Pong!
Ping? Pong!
> php artisan key:generate
Command Cancelled!

**Step 3**
# Bug 2
PHP Fatal error:  Interface 'Illuminate\View\Engines\EngineInterface' not found in /home/vagrant/Code/testoct/modules/system/twig/Engine.php on line 12

Ок I fixed it with this way[ https://github.com/octobercms/october/blob/develop/modules/system/twig/Engine.php](url)

**Step 4** 

# Bug 3 wrong build set
*** October sets build: 419
-
Ping? Pong!
-
Ping? Pong!
-

##### Reproduce steps
1) Create new homestead site 
2) vagrant@homestead:~/Code/testoct$ composer create-project october/october .
3) php artisan october:install
4) php artisan october:util set build 

##### October build
420

**Comment by daftspunk** [comment]
Wasn't this fixed in 98bc0c097782bd76db90a09104b1ec57bad90d20?

**Comment by daftspunk** [comment]
First issue, your database is rejecting your credentials.

**Comment by KonstantinObuhov** [comment]
I guess source code doesn't updated. I've reproduced bug 2 today.

**Comment by KonstantinObuhov** [comment]
How can i set database before create-project?

**Comment by daftspunk** [comment]
Looks like you may be right, the source file has not updated: https://github.com/octoberrain/system/blob/develop/twig/Engine.php

**Comment by daftspunk** [comment]
> How can I set database before run composer create-project?

I didn't think this code would run for create project... damn. There is no way to set it, perhaps we need the script to fail silently instead.

**Comment by KonstantinObuhov** [comment]
I confirm that 1,2,3 was fixed.
I tried to set correct build number with command **php artisan october:util set build**
but API return 419 instead 420 what may be wrong?

**Comment by LukeTowers** [comment]
@daftspunk fixed that issue in https://github.com/octobercms/october/commit/cf6ca02886423101b8ca4b3cd7a4637f5a553ea6.

@KonstantinObuhov The build number is pulled from the gateway, it merely reports the latest stable build number. I don't think (could be wrong though) that the command currently supports correctly setting the build number for develop versions of October.

**Comment by KonstantinObuhov** [comment]
Thx I get it. Issues above had me confused.
