### ISSUE TITLE
[L5.5] "Call to undefined method" after upgrade to build 420

### ISSUE THREAD

**Issue by jajacobs** [octobercms/october#3035]
After upgrading to build 420 i'm get the following error message:

Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Call to undefined method Illuminate\Support\Facades\Validator::extend()"

**Comment by LukeTowers** [comment]
Going to need more information than that, something is trying to extend the validator. What's the full call stack?

**Comment by daftspunk** [comment]
This looks like 419 modules running with 420 vendor.

420 calls this instead in `System\ServiceProvider@registerValidator`

```
$this->app->resolving('validator', function($validator) {
```

**Comment by jajacobs** [comment]
So i can't use Validator::extend() ?

**Comment by skydiver** [comment]
Hello, got the same problem.

Upgrading to build 420 from 419.

My plugin is using:

```
Use Validator;

...

public function register() {
    Validator::extend('recaptcha', 'Martin\Forms\Classes\ReCaptchaValidator@validateReCaptcha');
}
```

And i get the same error as @jajacobs
