### ISSUE TITLE
`october:util set build` does not support edge

### ISSUE THREAD

**Issue by petehalverson** [octobercms/october#3036]
##### Expected behavior
Expecting *** October sets build: 420

##### Actual behavior
Getting  *** October sets build: 419

##### Reproduce steps
Set `'edgeUpdates' => true` in config/cms.php.
Run `php artisan october:util set build`.

##### Test API via cURL:
```shell
$ curl -X POST http://gateway.octobercms.com/api/ping
# expected result - {"pong":"419"}


$ curl -X POST -F "edge=1" http://gateway.octobercms.com/api/ping
# expected result - {"pong":"420"}
# result delivered - {"pong":"419"}
``` 

##### October build
Build 420 - Commit cf6ca02886423101b8ca4b3cd7a4637f5a553ea6

**Comment by daftspunk** [comment]
Fixed per #3037
