### ISSUE TITLE
[Database,HasMany,L5.5] HasMany relation. method lists does not exists. 

### ISSUE THREAD

**Issue by Samorai** [octobercms/october#3040]
Hi guys!

I'd found some bug, after upgrading to 420 build.

https://github.com/octobercms/library/blob/master/src/Database/Relations/HasMany.php#L84
There are no method `lists` in L5.5, we need to use method pluck().
https://stackoverflow.com/questions/39114249/call-to-undefined-method-illuminate-database-query-builderlists-when-seeding

I've HasMany relation, and I try to render backend form via config_relation.
And I've redeclared method `newCollection` into my model, which return object of `Illuminate\Database\Eloquent\Collection`. 

When I changing `lists` to `pluck` locally - everything works correctly.

Build 419 works correctly.

**Comment by Teranode** [comment]
@LukeTowers @daftspunk should make a PR renaming these to `pluck()` or you wanna handle it?

**Comment by LukeTowers** [comment]
@Teranode @daftspunk I'm wondering if perhaps we should maintain the `lists` method as a wrapper around the `pluck` method for backwards compatibility. If not, then we'll need to document it in the release note. Same as https://github.com/octobercms/docs/pull/249

**Comment by Teranode** [comment]
@LukeTowers I'm more for the side of not keeping the backwards compatibility. It feels like that would have to be maintained on future unprecedented changes that Laravel would happen to make leading to more functions that would need wrappers/references and so on. What's your take on this @daftspunk ?

**Comment by tschallacka** [comment]
I would go with a round with wrappers and @deprecated annotations, and lots of warnings in the error logs when the lists wrapper is used telling people to contact plugin authors to update their code.

Otherwise one risks that a lot of plugins break explosively when the next update comes and people just push update.

**Comment by LukeTowers** [comment]
@tschallacka I tend to agree with you on that, I prefer people's sites not breaking when they update it, while also deprecating code to eventually phase out support.

**Comment by daftspunk** [comment]
You should be extending `October\Rain\Database\Eloquent\Collection` but since this is internal logic we can change it with no issues.

**Comment by Samorai** [comment]
@daftspunk Thanks! <3
