### ISSUE TITLE
Missing use Symfony\Component\Filesystem\Filesystem; ?

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#3044]
##### Expected behavior
https://github.com/octobercms/october/blob/master/modules/system/console/OctoberMirror.php#L7 being able to resolve to a class

##### Actual behavior
It's not there so it throws an error? vender/symfony/console/input does not contain a class FileSystem

##### Reproduce steps
Open october fresh install from installer in eclipse as project

##### October build
419

**Comment by LukeTowers** [comment]
I don't get it, what's the exception?

Yeah, that reference isn't used so it probably shouldn't be there, just like with your last PR.
