### ISSUE TITLE
Ajax Not Found Status Code

### ISSUE THREAD

**Issue by yabasha** [octobercms/october#3056]
##### Expected behavior
The status code must be 404

##### Actual behavior
The status code for not found ajax request is 200 : OK

##### Reproduce steps
1. Make ajax call for a not found html page from a script loaded by the page
```
$.ajax({
          url: "ajax-load/bootstrap-parent-modal.html",
          success: function (data) { $('body').append(data); },
          dataType: 'html'
});
```
2. In browser network console you will find the status code for the ajax call is 200
![image](https://user-images.githubusercontent.com/932321/29607924-56135a7a-87fb-11e7-8974-10bb8ce58e23.png)

##### October build
419

##### Solution
The solution is to remove the check for request type line# 196: `modules/cms/classes/Controller.php`

```
if (!Request::ajax()) {
    $this->setStatusCode(404);
}
```
↓
`
$this->setStatusCode(404);
`

![image](https://user-images.githubusercontent.com/932321/29608362-9545fac6-87fc-11e7-957a-4983d5d3b2c1.png)

**Comment by LukeTowers** [comment]
@daftspunk why does this check exist in the first place?

**Comment by daftspunk** [comment]
This is because the 404 page itself may have AJAX handlers and components used on it. A good solution here would be set the 404 status code in the 404 page and then it will carry over to the AJAX calls.
