### ISSUE TITLE
Cannot create administrator Group - Database error

### ISSUE THREAD

**Issue by romaldyminaya** [octobercms/october#3059]
##### Expected behavior
When the create button is clicked at the usergroups/create controlles. It should save the desired group.
>Note this is a fresh october installation.
##### Actual behavior
Its shows an message specifying that there's an database error.
![image](https://user-images.githubusercontent.com/2809147/29678494-2ef03096-88d5-11e7-9e07-c5c42d797efa.png)
This is the definition of the table.
![image](https://user-images.githubusercontent.com/2809147/29678668-d649d07c-88d5-11e7-84ca-4e0999b3f9e9.png)

##### Reproduce steps
1.Go to backend administrators options 
2.Clic create new group
3.Fill the name, description and desired permissions
4.Clic save or create

##### October build
(419)

**Comment by LukeTowers** [comment]
Your database table is using Build 420's version (where the permissions are moved from groups to roles) but it appears your code files are on Build 419. Try enabling edgeUpdates and then updating your October instance.

**Comment by romaldyminaya** [comment]
Hi @LukeTowers 

Thanks, that's was the problem it worked Just as you specified. 

Here is the screen shot:
---
![image](https://user-images.githubusercontent.com/2809147/29719618-3c421aa8-898d-11e7-8de5-24e88e596d50.png)

And the role created:
---

![image](https://user-images.githubusercontent.com/2809147/29719651-64a31484-898d-11e7-98f0-efafafa4c6bf.png)

> You can close this thread.

**Comment by LukeTowers** [comment]
Glad to hear your problem is solved now!
