### ISSUE TITLE
Render json property in columns.yaml

### ISSUE THREAD

**Issue by Alex360hd** [octobercms/october#3061]
Hello,

October CMS allow to register several fields value in one column in the database (json) thanks to the following declaration :

    fields:
        awesome_object[name]:
            label: name
        awesome_object[awesome_number]:
            label: awesome number.

However, the columns.xml doesn't follow the same logic, if you do something like that :

    columns:
        awesome_object[name]:
            label: name
            type: text

It doesn't output the needed property, the best you can do is to return the whole awesome_object in one column.

It would be great if october could display properties of one json object into separate columns that way.

What do you think about it ?

**Comment by Alex360hd** [comment]
Up, any opinions about that ? Maybe October CMS already allow to render a property of a json to a column, but the documentation don't provide any example about how to do that

**Comment by jan-vince** [comment]
You can define your own [column type](https://octobercms.com/docs/backend/lists#custom-column-types).

It shouldn't be hard to extract and show data you need.

**Comment by Alex360hd** [comment]
Hello,

I'm not sure your answer of custom column type is the solution to my problem, let's see my column.yaml file :

    options:
        label: Name
        type: json
        jsonFrom: name
    options:
        label: Address
        type: json
        jsonFrom: address

Even if I call a custom type json, with a custom property "jsonFrom" to know the property you want to output, I can't define "options" 2 times cause each column key need to be unique.

So I would like to declare something like that :

    options[name]:
        label: Name
        type: json
        jsonFrom: name
    options[address]:
        label: Address
        type: json
        jsonFrom: address

but again, it doesn't work cause october look at the table column options[name] in the database that does not exist. So the $value parameter that is passed to my custom column type function is empty.

So I think there is no solution without modifying the october CMS core. What I suggest is that when you define a column fiels as an array like that :

    options[name]
        label: Name
        etc....

October cms would detect that there are brackets in that column name and so, look in the name property of the option column in the database. I don't think it would be a big deal to change (maybe a well placed regex to detect brackets) and it would bring the column system to a whole new level by allowing to display complex objects to different columns with ease.

Best regards,

Alex

**Comment by LukeTowers** [comment]
@Alex360hd do you have edgeUpdates enabled? I believe support for this was merged in https://github.com/octobercms/october/pull/2995

**Comment by Alex360hd** [comment]
I updated october CMS to 420 but it does not change anything.

However, I manually applied the commit of the issue you linked and it works.

Dont know if I have to close this issue as the edge update didn't fix it.

Best regards,

Alex

**Comment by EdisonLV** [comment]
For some reason october cms with edge update doesn't have the committed changes in the code

**Comment by w20k** [comment]
Should be fixed now, If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
