### ISSUE TITLE
main controller does not use same twig instance

### ISSUE THREAD

**Issue by oleg-andreyev** [octobercms/october#3065]
[Main controller](https://github.com/octobercms/october/blob/master/modules/cms/classes/Controller.php#L504) does not use same instance of [Twig](https://github.com/octobercms/october/blob/master/modules/system/ServiceProvider.php#L270) which does not allow to register custom extensions, in make case it's `\Twig_Extension_StringLoader`

**Comment by LukeTowers** [comment]
This is not enough information to do anything with. Please provide detailed issue reports that actually describe what you are trying to do and why it is not working.

**Comment by oleg-andreyev** [comment]
Trying to register `Twig_Extension_StringLoader` for `template_from_string`, but there is no entry point for this, I've found `twig.enviroment` singleton as entry point, but it's not used in main controller.

**Comment by LukeTowers** [comment]
@oleg-andreyev I'm still not sure what you are trying to do. Does http://octobercms.com/docs/plugin/registration#extending-twig help?

See http://xyproblem.info/

**Comment by oleg-andreyev** [comment]
- I want to use build-in in Twig `template_from_string` function
- To use it I need to register `\Twig_Extension_StringLoader`
- To register any custom extension I need point of entrance and it's `twig.environment` or `\Twig_Environment` class
- I've found `\System\ServiceProvider::registerTwigParser` which registers singleton `twig.environment`
- I'm creating an extend of this singleton with following code
```
App::extend('twig.environment', function (\Twig_Environment $twig, Application $app) {
    $twig->addExtension(new \Twig_Extension_StringLoader());
});
```
- ER: everything to work and `template_from_string` should be available
- AR: `template_from_string` isn't available because `\Cms\Classes\Controller::initTwigEnvironment` (front controller) does not use `twig.environment` singleton and is creating `Twig_Environment` on it's own

Instead of creating new instance of `Twig_Environment`, OctoberCMS should call it from DI by calling `App::make('twig.environment')`

**Comment by oleg-andreyev** [comment]
ping

**Comment by LukeTowers** [comment]
What is it exactly that you are trying to do that requires the template_from_string? I understand how you're running into issues with your approach, what I'm looking for is what you are actually wanting to do with that.

**Comment by oleg-andreyev** [comment]
I have form with prototype element, when I click on button it's adding new field.
To better understand prototypes, I'll refer to Symfony Docs: https://symfony.com/doc/current/form/form_collections.html#allowing-new-tags-with-the-prototype

**Comment by LukeTowers** [comment]
I'm afraid I still have no idea what you're talking about. 

Are you trying to render a Twig template from a string?

**Comment by oleg-andreyev** [comment]
To keep it simple, yes, I need to render template from string.

**Comment by LukeTowers** [comment]
@oleg-andreyev does 
```php
use Twig;

Twig::parse($templateString, $templateVars);
```
not work for some reason?

**Comment by KonstantinObuhov** [comment]
I'm trying to do something like @oleg-andreyev.
For instance it may be rendering some parts of twig template from a data base, but `Twig::parse` doesn't work with october filters and this won't work `{{ 'sertifikatyi'|page }}`. Any suggestions?

**Comment by LukeTowers** [comment]
@KonstantinObuhov Using the Twig facade by itself won't load any CMS extensions, to fix that just register them again in your plugin instead. See modules/cms/ServiceProvider.php

**Comment by oleg-andreyev** [comment]
@LukeTowers imo application should have single instance of Twig (unless there is really specific case), and it should accessible by all plugins via DI and facade should provide access to it.

Case
- customer made registered Twig extension A
- customer installed plugin B
ER:
- extension A work in plugin B
AR:
- extension A does not work in plugin B

Because Twig instances isn't shared
