### ISSUE TITLE
Hi I am using rainlab.user plugin and I want to stop it from taking any updates. How can I 

### ISSUE THREAD

**Issue by zakir1929** [octobercms/october#3069]
Hi,
I am using Rainlab.user plugin and I want to stop it from taking any updates. 
**I will do a lot of changes in it so I don't want it to update.
I am a developer and I don't want my client to update it because then I will lose my all the changes.**
can please someone help me in that

**Comment by LukeTowers** [comment]
In October you don't need to modify a plugin's code to change its behaviour. There is a lot of documentation available on how to extend plugins. If you have questions, try asking on StackOverflow or Slack or the forums.

**Comment by zakir1929** [comment]
thanks and today I have learned how to extend a plugin without changing its code although thanks for the suggestion.
