### ISSUE TITLE
[Suggesion] Data from jsonable field into FilterScope

### ISSUE THREAD

**Issue by ghost** [octobercms/october#3071]
Hello,

This issue follow the same logic than [this one](https://github.com/octobercms/october/issues/2990) that have been fixed in the develop branch.

##### Expected behavior
I have model with jsonable field named options with values {"pagination": true}.
Thanks to the issue linked above, I can now display my pagination property in a column by declaring something like that in my columns.yaml

        'options[pagination]':
            label: Pagination
            type: switch

The next step is to be able to add a pagination filter on that list. to do that, I would like to be able to follow the same logic :

    scopes:
        'options[pagination]':
            label: Pagination
            type: checkbox
            conditions: options[pagination] = true

##### Actual behavior
Actually, doing this does not work, it display the following error :

> "SQLSTATE[HY000]: General error: 1 near "[pagination]": syntax error (SQL: select "author_myplugin_mytable".* from "author_myplugin_mytable" where options[pagination] = true order by "title" asc)" on line 647 of /httpdocs/vendor/laravel/framework/src/Illuminate/Database/Connection.php

##### October build
420

Best regards,

Alex

**Comment by EdisonLV** [comment]
Haven't try this, but what if you do something like this?
~~~
scopes:
    'options[pagination]':
        label: Pagination
        type: checkbox
        conditions: options->"$.pagination" = true
~~~

**Comment by Alex360hd** [comment]
Hello,

Thank you for your answer.

For the possibility to display json property in columns, [it has been fixed recently](https://github.com/octobercms/october/pull/2995). You can directly have a address[pickup] column ID and it will take the "pickup" property of "address" json.

About the filters, your solution doesn't work. It throw the following error :

>"SQLSTATE[HY000]: General error: 1 near "&gt;": syntax error (SQL: select "alex_galleries_sliders".* from >"alex_galleries_sliders" where options-&gt;"$.pagination" = true order by "title" asc)" on line 647 of >/vendor/laravel/framework/src/Illuminate/Database/Connection.php

**Comment by EdisonLV** [comment]
Hi, as mentioned before, my approach adds filter, search option on the **JSON columns type** in DB

**Comment by Alex360hd** [comment]
Ah yes, I created the plugin thanks to the builder and there is no json format for database columns. I will try to edit it manually and see if it works.

**Comment by LukeTowers** [comment]
@Alex360hd what you're asking for is a bit more complicated then you might think. Searching within JSON column type content is an advanced feature that each database engine has to support; probably each with their own syntax.

**Comment by Alex360hd** [comment]
@EdisonLV tested to change my column type to JSON, but I have the same error.

Maybe it's due to the fact that I use SQLite, cause when I browse the table structure, I can notice than the column type is still "text". SQLite does not support JSON column type ?

**Comment by EdisonLV** [comment]
@Alex360hd 
As of MySQL 5.7.8, MySQL supports a native JSON data type.
I don't think SQLite has that feature yet.

**Comment by Alex360hd** [comment]
Do you think it can work with SQLite and the [JSON1 extension](https://sqlite.org/json1.html) ?
