### ISSUE TITLE
enable unit testing with wizard installation

### ISSUE THREAD

**Issue by daniel63dm** [octobercms/october#3073]
##### Expected behavior
Be able to use phpunit when we install october from wizard installer.
I need phpunit to test my plugins.

##### Actual behavior
phpunit is not installed on vendor directory
PluginTestCase.php missing

##### Reproduce steps
Install October with the wizard installer

##### October build
419

#### Remarks
workaround using the composer install method.

**Comment by LukeTowers** [comment]
This isn't going to change. Installing via the installation wizard method installs the "consumer" version of October (i.e. Unit tests, `server.php`, and composer is not included). If you want to use the "developer" version of October, then install via composer instead.
