### ISSUE TITLE
Markdown formatted HTML in controller/preview.htm

### ISSUE THREAD

**Issue by LucasZdv** [octobercms/october#3077]
##### Expected behavior
I need to show the "markdown" code formatted in preview.htm
I want this
example: http://nimb.ws/XxUYmT

##### Actual behavior
I'm trying this in /controllers/mycontroller/preview.htm.

     <div class="field-markdowneditor">
        <div class="editor-preview">
            <?=Markdown::parse($formModel->content)?>
        </div>
     </div>

result: http://nimb.ws/VCceKU 

##### October build
(October build 419)

thanks.

**Comment by LukeTowers** [comment]
There isn't a bug here. Your code is working perfectly. It doesn't look the same because there is different CSS styling in the backend vs. the frontend of your website.
