### ISSUE TITLE
custom plugin form textarea value wont save due to word "having"

### ISSUE THREAD

**Issue by neosin** [octobercms/october#3078]
##### Expected behavior
form should update content when save is clicked

##### Actual behavior
error modal appears showing source code, no actual message displayed and nothing is saved
![invalid_errormsg](https://user-images.githubusercontent.com/76676/29976271-76f76908-8f07-11e7-861d-51f0b99e5e7b.png)

##### Reproduce steps
form field textarea paragraph containing the word "having", click save.
Changing the word from "having" to "waving" and everything works fine.
Conclusion is that for some reason it believes "having" is an SQL command in the content

##### October build
build 419

**Comment by neosin** [comment]
even using "&#104;aving" does not solve the issue

**Comment by LukeTowers** [comment]
As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
