### ISSUE TITLE
[L5.5] HasManyThrough signature incompatible with Laravel's HasManyThrough

### ISSUE THREAD

**Issue by mmvcode** [octobercms/october#3083]
##### Expected behavior
In a ```hasManyThrough``` relation using October's [HasManyThrough](https://github.com/octobercms/library/blob/master/src/Database/Relations/HasManyThrough.php#L24), the constructor calls the parent with 6 arguments. However, the parent class, [Illuminate\Database\Eloquent\Relations\HasManyThrough](https://github.com/illuminate/database/blob/master/Eloquent/Relations/HasManyThrough.php#L67)
requires 7.

##### Actual behavior
```
Type error: 
Too few arguments to function Illuminate\Database\Eloquent\Relations\HasManyThrough::__construct(), 6 passed in
 vendor\october\rain\src\Database\Relations\HasManyThrough.php on line 24 and exactly 7 expected
vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\HasManyThrough.php line 67
```

##### Reproduce steps
Add a ```hasManyThrough``` relation to a model.

##### October build
421

**Comment by KonstantinObuhov** [comment]
The same problem.
I add relation like this.

cities
    id - integer
    name - string
serts
    id - integer
    city_id - integer
    name - string
sert_orders
    id - integer
    sert_id - integer

**Comment by mmvcode** [comment]
Just as a note, this only happens when using the `$hasManyThrough = [];` property, it works fine when defining relations through methods.

**Comment by daftspunk** [comment]
Should be fixed in Build 422+
