### ISSUE TITLE
Templates aren't resolve against $basePath

### ISSUE THREAD

**Issue by oleg-andreyev** [octobercms/october#3089]
##### Expected behavior
templates are resolved against $basePath

##### Actual behavior
templates aren't resolved against $basePath and getting exception that template is missing

##### Reproduce steps
1. create template A

```
{# template A #}
I'm template A
{% include 'themes/themeName/templateBLocation/B.htm' %}
```

2. create template B

```
{# template B #}
I'm template B
```

3. mirror project into public dir
4. Visit page which will use templateA
5. exception `An exception has been thrown during the rendering of a template`

##### October build
v1.0.419

**Comment by LukeTowers** [comment]
OctoberCMS does not support the Twig `{% include %}`. Use `{% content %}` or `{% partial %}` instead. See https://octobercms.com/docs/markup/templating

**Comment by oleg-andreyev** [comment]
@LukeTowers then this should be reflected in documentation, because if cms is using Twig, I as developer expect everything that is build-in into Twig to work

**Comment by LukeTowers** [comment]
It is. Did you read the bottom of the link that I provided?
