### ISSUE TITLE
Provideng custom pivot model for morph to many relationship not working

### ISSUE THREAD

**Issue by tdolph** [octobercms/october#3090]
I have this in my Proposal model:

 public $morphToMany = [
        'tags' => [
            'P\Models\Tag', 
            'name' => 'taggable', 
            'table' => 'p_taggables',
            'timestamps' => true,
            'pivotModel' => 'P\Models\TagPivot',
        ]
    ];

##### Expected behavior
It shhould get all tags of proposal with provided pivot model. 

##### Actual behavior
When i get the collection of tags for this proposal model, the tag has MorphPivot instead of the pivot i provided. I need custom pivot because i want to add user id of the person attaching the tag and to eager load the users who have attached each tag. I made TagPivot extend the MorphPivot class but i think the TagPivot model is not even touched.

##### October build
419

**Comment by tdolph** [comment]
I just tried this. I went to the rainlabs Model class and dumped stuff in the newRelationPivot function but it did not dump anything near the checkbox list i have in a form for this relation. It dumped some other relations but not for morphToMany. So, this function is not even called for this type of relation. I will try to dig deeper but right now i cant find a place where calling for this function is decided. Maybe somebody could help me?

**Comment by tdolph** [comment]
Also, when i dump anything inside Octobers Pivot class constructor, it wont dump anything for this relation. For other relations that have pivot the dump exists. So, the octobers own pivot model is not used for morphToMany. 

Any idea where i could find a place to change for morphToMany to use octobers own pivot class?

**Comment by tdolph** [comment]
Please help. I really need it.

**Comment by LukeTowers** [comment]
Try asking for help on the Slack team: https://octobercms-slack.herokuapp.com/

**Comment by iboved** [comment]
I confirm that. I have the same problem.

**Comment by iboved** [comment]
@tdolph how did you solve this?

**Comment by TimFoerster** [comment]
discussion in #3485
