### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jkathir** [octobercms/october#3093]
1. Google like search engine like https://ambar.cloud/
2. Next, Previous, Go to Option like Folio Views
3. Number of hits found before hitting the actual search like Folio Views
4. Import options from Zim, Treepad or other wikis.
5. Handling huge number of documents by providing quick search via Solr or Apache Lucene
6. Support for tamil language
7. Having tags for each document (Reference: https://collatenotes.com/)
8. Built in web clipper (save webpages locally) - (Reference: https://collatenotes.com/)
9. Support for full text search in huge text nodes - example atleast 10,000 nodes with 100 kb of text each. Most note-taking software couldn't handle such huge content due to missing indexing
10. Quickest search results via indexing through Apache Lucene like docFetcher (http://www.techrepublic.com/blog/linux-and-open-source/portable-desktop-search-make-the-most-of-docfetcher/)
11. 
12. 1.

**Comment by Teranode** [comment]
What you're suggesting here is things that could be implemented yourself, these all seem like bulk ideas that you'd want for a specific personal project.

You can submit a PR for the tamil language.

**Comment by LukeTowers** [comment]
Feature requests as issues are only acceptable if you are using it as a pre-PR communication. If you aren't planning on implementing it yourself, then it would be better suited being asked for on one of these channels:

Forum: http://octobercms.com/forum
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

The support demand for October is increasing, while the available time the founders have to give remains the same. These feature requests are absolute lowest priority for us, they may be gotten to in time. However there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone
