### ISSUE TITLE
Editor: Table formatter popup is hiding behind another popup

### ISSUE THREAD

**Issue by TimFoerster** [octobercms/october#3098]
##### Expected behavior
The table formatter popup should be infront of the popup

##### Actual behavior
The table formatter popup is behind the popup

##### Reproduce steps
Use a plugin with a popup (for example leaflet maps).
Create a table in the popup editor and click on a cell.

##### October build
current

![untitled](https://user-images.githubusercontent.com/7849550/30159620-7bb69dee-93c9-11e7-85cb-eecad36ff628.jpg)
![untitled2](https://user-images.githubusercontent.com/7849550/30159624-7f2f3314-93c9-11e7-904a-88b44393c618.jpg)

**Comment by TimFoerster** [comment]
with the PR i get 
![untitled3](https://user-images.githubusercontent.com/7849550/30161357-71c5c2c2-93d0-11e7-838f-0d3d5f033dd7.jpg)

**Comment by LukeTowers** [comment]
Fixed in https://github.com/octobercms/october/commit/ead70c43f31d65516fc98da92766dc0513d91ec5. Thanks for your help!
