### ISSUE TITLE
Is there any way to update backend UI elements after list filter is applied?

### ISSUE THREAD

**Issue by KonstantinObuhov** [octobercms/october#3103]
I want to update chart ui above list block after list filter is applied. Something like [that ](http://clip2net.com/s/3NEsG4T).
After a little digging, I didn't find the way to update chart with summary information on the filtered of data.

How to do it? Thanks!

**Comment by LukeTowers** [comment]
Look at the RainLab.Blog plugin for examples of how to do that.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
