### ISSUE TITLE
L5.5 Queued Event Listeners not working

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#3104]
##### Expected behavior
Event listener should be queued and ran in background without errors.

##### Actual behavior

There is an error when you run event:

```
ReflectionException: Class Illuminate\Events\CallQueuedHandler does not exist in /home/vagrant/code/*/vendor/laravel/framework/src/Illuminate/Container/Container.php:752
```

##### Reproduce steps
Configure environment to use queue driver like beanstalkd.

Create event class like in Laravel documentation.

https://laravel.com/docs/5.5/events#defining-events

Create listener class like in Laravel documentation.

https://laravel.com/docs/5.5/events#queued-event-listeners

Register listener in plugin `boot()` method or in `init.php` file.

Fire event in your code.

##### October build
422

**Comment by LukeTowers** [comment]
This is a complex case. 

In order to aid in our understanding of the problem, please submit [a Pull Request to the test plugin](https://github.com/daftspunk/oc-test-plugin) for investigation that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it _using the test plugin_.

**Comment by daftspunk** [comment]
It's not a complex case, it lacks detail. Please provide the full stack trace and explicitly the code you are running.

**Comment by computerfr33k** [comment]
I am also experiencing this same issue on build 428.
```php
// Fire event to be queued
Event::queue('form.submitted', new FormSubmitted($this->form, $request));
```
```php
<?php

use Illuminate\Contracts\Queue\ShouldQueue;

class FormSubmissionHandler implements ShouldQueue
{
    public function handle(FormSubmitted $event)
    {
        // do some processing here
    }
}
```

**Comment by LukeTowers** [comment]
@computerfr33k please post a full stack trace.

**Comment by computerfr33k** [comment]
When using `Event::queue`: https://pastebin.com/LuHNysWj

When using `Event::fire`: https://pastebin.com/hzd30ePZ

**Comment by LukeTowers** [comment]
@daftspunk any input on the above?

**Comment by xtremetom** [comment]
This still seems to be an issue

**Comment by LukeTowers** [comment]
@xtremetom please post detailed replication instructions

**Comment by datune** [comment]
@daftspunk  I am experiencing the exact same behaviour when using Event::queue as @computerfr33k

**Comment by LukeTowers** [comment]
@datune please provide as many details as possible.

**Comment by vdomah** [comment]
Faced same issue. Quick search by "CallQueuedHandler" gave the following result:
![screenshot_1](https://user-images.githubusercontent.com/9612735/48604297-0c871600-e982-11e8-86e4-01c9a0fadeba.png)

So error "Class Illuminate\Events\CallQueuedHandler does not exist" appears because it really doesn't exist. But there is October\Rain\Events\CallQueuedHandler.
So after I replaced lines 'Illuminate\Events\CallQueuedHandler@call' in Dispatcher class by 'Illuminate\EventsOctober\Rain\Events\CallQueuedHandler@call' - the issue disappeared

**Comment by LukeTowers** [comment]
@vdomah could you submit that fix in a PR?

**Comment by vdomah** [comment]
@LukeTowers yes, doing

**Comment by vdomah** [comment]
@LukeTowers btw, how to clone october/rain? I can't see that repo?

**Comment by LukeTowers** [comment]
@plehatron thanks, much appreciated!

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/library/commit/e4a0b2150a7f08d43a88bcec38e367b0d0cb9d13. Thanks @plehatron!

**Comment by vdomah** [comment]
Thanks @plehatron!

**Comment by MarkAdell** [comment]
I'm currently facing this issue with Lumen framework version 5.5.*

In which version was this issue fixed?

**Comment by daftspunk** [comment]
This appears to have been fixed in Build 444 and above

**Comment by shoguniphicus** [comment]
I am on build 471, the same issue. Event::queue will yield the same error as above.

`Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method October\Rain\Events\Dispatcher::queue() in /home/vagrant/code/vvibes/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221`

**Comment by daftspunk** [comment]
Please share your implementation. Event queuing is supported, however, I'm not certain it is performed via `Event::queue`, rather via the `Illuminate\Contracts\Queue\ShouldQueue` contract
