### ISSUE TITLE
Dynamically merging relation config

### ISSUE THREAD

**Issue by WWRFresource** [octobercms/october#3105]
##### Expected behavior
When extending controller to use relation config, tried implementing dynamically following this post on Stackoverflow: [https://stackoverflow.com/questions/43348450/how-to-extend-relation-config-october-cms/43436228](https://stackoverflow.com/questions/43348450/how-to-extend-relation-config-october-cms/43436228)

##### Actual behavior
Producing an exception 
`Call to undefined method [mergeConfig]`

##### Reproduce steps
        UsersController::extend(function($controller){
            //$controller->implement[] = 'Backend.Behaviors.RelationController';
            //;

            // Implement behavior if not already implemented
            if (!$controller->isClassExtendedWith('Backend.Behaviors.RelationController')) {
                $controller->implement[] = 'Backend.Behaviors.RelationController';
            }

            // Define property if not already defined
            if (!isset($controller->relationConfig)) {
                $controller->addDynamicProperty('relationConfig');
            }
            
            //$controller->relationConfig = '$/wwrf/profile/controllers/phones/config_relation.yaml';
            
            // Splice in configuration safely
            $myConfigPath = '$/myvendor/myplugin/controllers/users/config_relation.yaml';

            $controller->relationConfig = $this->mergeConfig(
                $controller->relationConfig,
                $myConfigPath
            );
        });

##### October build
419

**Comment by LukeTowers** [comment]
Call mergeConfig on the controller instance, not your plugin $this object
