### ISSUE TITLE
Get image dimensions from file

### ISSUE THREAD

**Issue by marijnhurkens** [octobercms/october#3108]
Is it possible to get the image dimensions from a file object. I'm currently using the Blog plugin from Rainlab and each post returns a `featured_images` array with file objects. If I would like to set the image dimensions as is recommended in an `<img />` tag I would need the dimensions of the image. Is it possible to get these from the file object?

##### October build
419

**Comment by jan-vince** [comment]
As far as I know image dimensions are not saved with fileupload.

You can write a [twig function](https://octobercms.com/docs/markup/templating) to [use](https://stackoverflow.com/questions/25689441/getimagesize-with-laravel-4-blade-template) ````getimagesize()```` function.

**Comment by marijnhurkens** [comment]
I think your approach is the right on but I can't get it to work as the `getimagesize()` function generates a `Maximum execution time of 30 seconds exceeded` error on my local environment... The url I use as input works fine, I tried php 7.0.22 and 7.1.8 on Windows 10. This is unrelated to OctoberCMS but if anyone has an idea why this happens?

**Comment by marijnhurkens** [comment]
Solved by using the disk path:

```php
function onEnd() {
    foreach($this->posts as $pIndex => $post) {
        foreach($post->featured_images as $fIndex => $featuredImage) {
            $path = storage_path('app/'.$featuredImage->getDiskPath());
            list($width, $height) = getimagesize($path);
            $this->posts[$pIndex]->featured_images[$fIndex]->width = $width;
            $this->posts[$pIndex]->featured_images[$fIndex]->height = $height;
        }
    }
}
```

**Comment by jan-vince** [comment]
Little bit different approach:

**Plugin.php** (add Twig function)
````php
    /**
     * Twig extensions
     */
    public function registerMarkupTags()
    {
        return [
            'functions' => [

                'getImageSizeAttributes' => function($value) {

                    if( !empty($value->getDiskPath()) ){

                        $filePath = storage_path('app/' . $value->getDiskPath());

                        if( is_file($filePath) ) {

                            list($width, $height, $type, $attributes) = getimagesize($filePath);

                            return $attributes;

                        }

                    }

                }
            ]
        ];
    }
````

**Page**
````
<img src="{{ recordDetail.preview_image.getPath }}"  {{ getImageSizeAttributes(recordDetail.preview_image) }}>
````
