### ISSUE TITLE
Component onRender

### ISSUE THREAD

**Issue by Samorai** [octobercms/october#3109]
Hi guys!

I'm calling the component into the template, and want that component's partial 'bar' will be displayed with the property 'prop'. 
{% component 'Foo::bar' prop='queue' %}
```

class Foo extends ComponentBase {
    public function onRender() {
        $this->page['propProperty'] = $this->property('prop');
    }
}
```

_../components/foo/bar.htm_

`Property value is {{propProperty}}`

##### Expected behavior
Output: 
Property value is queue

##### Actual behavior
Property value is 

When I'm calling {% component 'Foo' prop='queue' %} and use default.html partial, everything is ok.

https://github.com/octobercms/october/blob/master/modules/cms/classes/Controller.php#L992-L1010

The bud into Cms\Classes\Controller::renderComponent, the $name variable is 'Foo::bar'.
I can create PR with fix it. 
But I'm not sure, fix it into `renderComponent` method or `findComponentByName`

**Comment by LukeTowers** [comment]
I'm not quite sure what you're trying to do or what the problem is here.

In order to aid in our understanding of the problem, please submit [a Pull Request to the test plugin](https://github.com/daftspunk/oc-test-plugin) for investigation that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it _using the test plugin_.

**Comment by Samorai** [comment]
@LukeTowers ok, thanks, I'll do that as soon as possible, maybe in a few days.

**Comment by Samorai** [comment]
@LukeTowers is there any component's test? I don't see any.

**Comment by LukeTowers** [comment]
Create one if necessary

**Comment by Samorai** [comment]
@LukeTowers Hi!
Here the explanation of problem step by step:
1. You need to add oc-test-plugin with my PR into plugins directory;
2. Create page, ./themes/demo/pages/test.htm 
```
title = "Test component property"
url = "/demo/test"
layout = "default"
[oc-test-component]
==
{% component 'oc-test-component::bar' property='test_property' %}
``` 
3. Create partials in `./themes/demo/partials/oc-test-component/bar.htm` and `./themes/demo/partials/oc-test-component/default.htm` with contents:

```Bar {{demoProperty}}```

```Default {{demoProperty}}```
4. Into your test page call the component like `{% component 'oc-test-component' property='test_property' %}`
You'll see the in output ```Default test_property```
6. Into your test page call the component like 
```
{% component 'oc-test-component' property='test_property' %}
{% component 'oc-test-component::bar' property='test_property' %}
```
You'll see the in output 
```
Default test_property
Bar test_property
```
7. Call the component onto your test page like: 
```
{% component 'oc-test-component::bar' property='test_property' %}
```
You'll see in output ```Bar``` without `property` value. 
This is a problem. 
I'll create the PR to fix it in 15 minutes;

Thank you!

**Comment by ametad** [comment]
I am not aware of this syntax in defining a component on a page with adding: ```::bar```, see:

```
{% component 'oc-test-component::bar' property='test_property' %}
```

Normally you would call a partial like that, e.g.:

```
{% partial 'oc-test-component::list' %}
```

Did I missed a change after the upgrade or may this be the problem?

**Comment by Samorai** [comment]
@ametad if I would call 
```
{% partial 'oc-test-component::list' property='test_property' %}
```

I cant use property_value into partial ``list``

**Comment by ametad** [comment]
Try, on a page:

```
[oc-test-component]
property = 'some default'
==

{% partial 'oc-test-component' property='test_property' %}
```

components/oc-test-component/default.htm 
```
{{ property }}
```

Further read: http://octobercms.com/docs/cms/components#external-property-values

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
