### ISSUE TITLE
doesn't work on safari use ssl but work on google chrome

### ISSUE THREAD

**Issue by hushulin** [octobercms/october#3110]
i want to use ssl for  octobercms .  so, i configration linkPolicy with force , and config app.url with https://xxx. it work well on goole chrome, but doesn't work on safari and ie.

![cd02d61e-0128-42db-b290-cb631fb3476b 1](https://user-images.githubusercontent.com/4876973/30410421-8327073e-993d-11e7-8ca3-4da9f7799a31.png)

**Comment by LukeTowers** [comment]
As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by hushulin** [comment]
i get this issue by follow steps:
step 0:
nginx + php-fpm + mysql + linux centos7
step 1:
make nginx support ssl by follow configuration:
`listen 443 ssl; # managed by Certbot
ssl_certificate /etc/letsencrypt/live/coolshell.cn/fullchain.pem; # managed by Certbot
ssl_certificate_key /etc/letsencrypt/live/coolshell.cn/privkey.pem; # managed by Certbot
include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot`
and
`if ($scheme != "https") {
  return 301 https://$host$request_uri;
} # managed by Certbot`

step 2:
make octobercms support ssl by follow configurations:
edit ./config/app.php
`'url' => 'https://test.xxx.cn',`
edit ./config/cms.php
`'linkPolicy' => 'force',`

step 3:
open google chrome
![20170914151850](https://user-images.githubusercontent.com/4876973/30416730-e47d6222-995f-11e7-9618-1e745894c01c.png)

open safari
![cd02d61e-0128-42db-b290-cb631fb3476b 1](https://user-images.githubusercontent.com/4876973/30416856-4f6601d4-9960-11e7-9b9a-0762ee4c7822.png)

**Comment by LukeTowers** [comment]
Could you please translate the error that Safari is giving you?

**Comment by hushulin** [comment]
Safari can not open page.
Safari can not open page "https://xxx" , Because the server unexpectedly interrupted connection. This situation occurs frequently in the server is busy , please wait a few minutes and try again later.

**Comment by hushulin** [comment]
this issue has been resolved by our ops. our ops has removed old nginx configurations and make new configurations. but i still don't know why google chrome can work and that safari can not.

**Comment by ifnull** [comment]
@hushulin I would guess the value of `ssl_ciphers` in the Nginx conf is the problem. Cipher support varies by browser. I suggest comparing the [supported ciphers for those browsers](https://cc.dcsec.uni-hannover.de/). You may also want to [review these recommended SSL configurations for Nginx](https://cipherli.st/). [Qualys SSL Server Test](https://www.ssllabs.com/ssltest/) is also helpful when debugging SSL related issues.

**Comment by hushulin** [comment]
@ifnull ok, i get it. i will try it later. thanks a lot.

**Comment by LukeTowers** [comment]
Closing as this was due to a nginx misconfiguration
