### ISSUE TITLE
Unable to edit twig interpolation snippets inside CMS Editor

### ISSUE THREAD

**Issue by colthreepv** [octobercms/october#3112]
##### Expected behavior
1.Open a Page inside CMS
2.Click on "Code View"
3.Edit or write any twig-specific syntax, like:
```
<img src="{{ 'img/file.jpg' | media }}">
```
4.Save page
5.Works

##### Actual behavior
1.Open a Page inside CMS
2.Click on "Code View"
3.Edit or write any twig-specific syntax, like:
```
<img src="{{ 'img/file.jpg' | media }}">
```
4.Saving produces something like
```
<img src="{{%20'img/file.jpg'%20%7C%20media%20}}">
```
5.Page gives out error

##### Reproduce steps
Specified Above

##### October build
v1.0.419

**Comment by LukeTowers** [comment]
Does this happen if you enable edgeUpdates and update to Build 423?

**Comment by colthreepv** [comment]
Uhm I never tried that because I am using composer install, is that
possible to get that version there?

**Comment by LukeTowers** [comment]
yes, still enable edgeUpdates, but then change your composer october requirements (excluding october/rain) to `dev-develop`

**Comment by colthreepv** [comment]
> yes, still enable edgeUpdates, but then change your composer october requirements (excluding october/rain) to dev-develop

Ok this turned out way more messy than these simple steps.
Installing October from scratch I cannot reproduce the issue.
