### ISSUE TITLE
Problem Richeditor & Window media insert image

### ISSUE THREAD

**Issue by thanglegeo** [octobercms/october#3114]
![oct](https://user-images.githubusercontent.com/31978914/30466335-526edfb6-9a07-11e7-9ada-fbd1ca6604a4.jpg)

##### October build
Build 423

**Comment by LukeTowers** [comment]
This was fixed in https://github.com/octobercms/october/pull/3113. Please apply those changes locally and let me know if it works.

**Comment by thanglegeo** [comment]
I have edited 4 files, but it doesnt work

richeditor.css
richeditor.less
build-min.js
richeditor.js

Thanks

**Comment by LukeTowers** [comment]
@thanglegeo could you please update to the latest build and empty your browser cache (or try in incognito) and let me know if it works now?

**Comment by LukeTowers** [comment]
In theory fixed by #3113 or #3194
