### ISSUE TITLE
Markup filter base64img error 

### ISSUE THREAD

**Issue by Shahiem** [octobercms/october#3118]
##### Actual behavior
When I try to restore my backend password, I get the following error:

An exception has been thrown during the compilation of a template ("The markup filter for base64img is not callable.") in "__string_template__5cbf99e2cd0f56dcc9061b38b602b7481b16faf0115cef92085250b6f0bbc99c".

##### October build
382

Server: Apache

**Comment by LukeTowers** [comment]
Update your October install and then try again.

**Comment by Shahiem** [comment]
I still see this error when I updated my october to the latest build version

**Comment by LukeTowers** [comment]
Build version number? Also, where are you using the base64img Twig filter?

**Comment by w20k** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
