### ISSUE TITLE
Cannot add readOnly attribute to dropdown or switch fields types

### ISSUE THREAD

**Issue by romaldyminaya** [octobercms/october#3119]
##### Expected behavior
When a model is in update mode I'd like to have de posibilities to disable some fields to be modifiables.

##### Actual behavior
The fields ignore the code in the filterFields function provided at Model level. The fields marked in the image below should be readOnly as specified in my code.

![image](https://user-images.githubusercontent.com/2809147/30528934-20d7f0ba-9c0e-11e7-8932-6bf8554410bf.png)

##### Reproduce steps
Try to add readOnly attribute to a model when the scope is update like the code below:

    public function filterFields($fields, $context = null)
    {
        if($this->type == Type::ORGANIZATION_UNIT || $this->type == Type::BANK)
        {
            $fields->is_inbound->readOnly = true;
            $fields->is_outbound->readOnly = true;
            $fields->currency->readOnly = true;

            $fields->is_inbound->value = false;
            $fields->is_outbound->value = false;
        }

        if($context == 'update')
        {
            $fields->type->readOnly = true;
            $fields->currency->readOnly = true;
            $fields->number->readOnly = true;
        }
    }

##### October build
(423)

**Comment by LukeTowers** [comment]
What about `$fields->type->disabled = true;`? Does that accomplish the end goal?

**Comment by romaldyminaya** [comment]
Hi @LukeTowers ,

When I disable the field then the model tryes to validate even when we use the **sometimes** validation rule.

**Comment by yesseniaramos** [comment]
![false](https://user-images.githubusercontent.com/32500067/31153632-e1c21a70-a867-11e7-9273-9c98ba4934e6.PNG)
I've similar problem with date fields and switch fields. I have two types users and I'm trying to block the update option in some fields just for some users using the same list form doing:

$fields->date_sent->readOnly = true; in date fields allows to edit the date, but I resolve it with $fields->date_sent->disabled = true; . 

In the case of the switch type field I configure it  $fields->alert->disabled = true; but when I update some field my user with the switch field blocked, the value is updatedin false, does not hold the value true and  readOnly = true; doesn't work in switch field.

I will try to solve my problem using a list form for each user, because I have not found a solution to this case. 
![datefield](https://user-images.githubusercontent.com/32500067/31153546-60a5e408-a867-11e7-978f-2e3c4e614cb7.PNG)
![true](https://user-images.githubusercontent.com/32500067/31153629-dcaf674a-a867-11e7-80cd-f17a15cb5195.PNG)

regards

**Comment by romaldyminaya** [comment]
Hi @yesseniaramos,

Regarding the problem you have when you disable or enable a field in the filterFields method. Make sure that the field you want to update, depends on the field that trigger the change.

Here is an example of my code:

        currency:
            label: 'cloud.crm::lang.labels.currency'
            tab: 'cloud.crm::lang.tabs.account_header'
            oc.commentPosition: ''
            span: auto
            type: relation
            nameFrom: caption
            emptyOption: 'cloud.crm::lang.labels.select_currency'
            dependsOn: [type, parent_id]

As you can see, my field currency must depends in all the fields that produces any change on it, weather the change is at value level or at field's attributes level.

Hope it helps.

>I see that you speak spanish so try contacting me via email in my profile so we can share solutions to theese issues.

**Comment by romaldyminaya** [comment]
@LukeTowers,

These is the temporal workaround I came until we find an standard solution:

    // Workarround for readonly widget
    $fields->currency->readOnly = true;
    $fields->currency->type = 'text';

This is because, even when I use the **disabled attribute**, and I have the validation to be applied sometimes, it **triggers the validation** T.T

**Comment by LukeTowers** [comment]
@romaldyminaya that sounds like two separate problems:
1. Disabled does not disable validation
2. The relation FormWidget does not support readOnly.

**Comment by romaldyminaya** [comment]
@LukeTowers ,

I'll fix the sourceCode of the relation form widget and the switch form widget so they can support readOnly as well in my project, I'd like then to submit those changes so everybody can have that solutions.

How can I do that ?
What branch should I clone to make those changes and propose them as pull request ?

Thanks in advance.

**Comment by LukeTowers** [comment]
@romaldyminaya clone the develop branch and provide the PR back to the develop branch. Take a look at the other recent changes to some FormWidgets (Richeditor, Repeater?) that added support for disabled / readOnly.

**Comment by romaldyminaya** [comment]
@LukeTowers  I now realized why you tell me that there were not need in closing the pull request, when you create the first one, all the followings commits that refferences the same issue number, refference the first pull request. Thank you luke 👍

**Comment by arustler** [comment]
Can confirm this issue.
I am using the RelationController to display the fields. Setting them in the .yaml file to `readOnly: true` does not work

config_relation.yaml
```
pivot:
    form: $/hubiswelt/hubismanagement/models/tipp/fields_systems.yaml
```

fields_systems.yaml
```
fields:
    pivot[tipp_type]:
        type: dropdown
        options: getTippTypeOptions
tabs:
    fields:
        st_bet_type:
            readOnly: true
            label: hubiswelt.hubismanagement::lang.tipps.bet_type
            type: dropdown
            span: auto
            options: getBetTypeOptions
            tab: hubiswelt.hubismanagement::lang.tipps.safety_tipp
```
