### ISSUE TITLE
October's public path

### ISSUE THREAD

**Issue by kuloed** [octobercms/october#3121]
##### Expected behavior
Change application public path to `public` folder and run october smoothly.

##### Actual behavior
there are issue with october's public path.
in October, public path is actually base path of application path.
see here [Application.php](https://github.com/octobercms/library/blob/master/src/Foundation/Application.php#L41-L44).

My issue is when using existing laravel application public path is `base_path/public` so the assets cannot load because the different of public path.
see,
[Filesystem.php](https://github.com/octobercms/library/blob/master/src/Filesystem/Filesystem.php#L92) [CombineAssets.php](https://github.com/octobercms/october/blob/master/modules/system/classes/CombineAssets.php#L408)

Can we change this to `base_path()` instead ?

##### Reproduce steps
To reproduce this please set public path to `base_path\public`.

##### October build
October as composer package and Any build number if we change application public path to public folder.

**Comment by LukeTowers** [comment]
I'm not sure what you are trying to do. If you want to run October from a public folder on your webserver, then see https://octobercms.com/docs/setup/configuration#public-folder

**Comment by kuloed** [comment]
Yes i'm aware of that `mirror` command. But even so we mirroring to public folder, the application public folder setting is pointing to base folder. So if we use october in existing laravel application, we run some issue with asset not found because laravel public folder is in `base_path/public`.
If we change laravel application public folder, we cannot use the laravel's conventional like `storage:link` `mix()` etc.

**Comment by LukeTowers** [comment]
How are you using October in an existing Laravel installation? That's not officially supported, October is it's own platform that is built on top of Laravel.

**Comment by kuloed** [comment]
I'm using october as composer package, then changing the application foundation according to october's requirement. Everything is working finely (thanks to all october's hard work) except for that public path only.
So i guess my only choice is to use base_path as public_path right?

**Comment by LukeTowers** [comment]
Are you using `october/october` as a package or are you using it's dependencies?
