### ISSUE TITLE
Package files from server are corrupt

### ISSUE THREAD

**Issue by GlobalSolutions2018** [octobercms/october#3122]
##### Expected behavior
Downloading application files

Package files from server are corrupt

Something went wrong during the installation. Please check the log file (install_files/install.log) or see the documentation for more information.

##### Reproduce steps
download october install using install.php

##### October build
(October build number)
Latest

**Comment by LukeTowers** [comment]
This is not enough information. Please post your installation logs.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by AllARTSoftworks** [comment]
Same here. Ubuntu Xenial64 over Vagrant. 

`
[2017/10/20 02:41:58] Install step: downloadCore
[2017/10/20 02:42:01] File hash mismatch: 1fc4f2016fbeaac8d8ab1e772812e978 (expected) vs  (actual)
[2017/10/20 02:42:01] Local file size: 
[2017/10/20 02:42:01] Handler error (onInstallStep): Package files from server are corrupt
[2017/10/20 02:42:01] Trace log:
#0 /vagrant/install-master/install_files/php/Installer.php(312): Installer->requestServerFile('core', '1fc4f2016fbeaac...', 'core/get', Array)
#1 /vagrant/install-master/install_files/php/Installer.php(48): Installer->onInstallStep()
#2 /vagrant/install-master/install_files/php/boot.php(74): Installer->__construct()
#3 /vagrant/install-master/install.php(1): include('/vagrant/instal...')
#4 {main}
`

**Comment by LukeTowers** [comment]
@AllARTSoftworks Do you have anything in your install log? What environment are you trying to install October on?
