### ISSUE TITLE
ContainerInterface not found

### ISSUE THREAD

**Issue by goeroe** [octobercms/october#3123]
Getting the following error when pushing to production... Don't have this issue on my computer (running wamp)

```
Fatal error: Interface 'Psr\Container\ContainerInterface' not found in .../vendor/laravel/framework/src/Illuminate/Contracts/Container/Container.php on line 8
```

##### October build
424

**Comment by LukeTowers** [comment]
Sounds like a dependency mismatch. What's your process for pushing to production?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
