### ISSUE TITLE
Minor issue in the Software update popup

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#3125]
##### Actual behavior
In the Software update popup the code of plugin appears instead of name. Furthermore the default icon appears instead of plugin icon. I remember that, they worked perfectly October build 419 and lower.

##### Reproduce steps
Click on the Check for updates button on the Updates & Plugins page.

##### October build
420+

##### Screenshot
![issue](https://user-images.githubusercontent.com/2959112/30632336-fa8b135c-9de7-11e7-92da-c7b90aebd798.jpg)

**Comment by LukeTowers** [comment]
Please provide a picture of a Build 419 instance displaying the mentioned update popup. I don't recall that being the case personally.

**Comment by gergo85** [comment]
![419](https://user-images.githubusercontent.com/2959112/30664680-d5f5d5d8-9e4e-11e7-96d1-1c35977ae3b1.jpg)

**Comment by LukeTowers** [comment]
Next question, are you sure that it's not just a problem specific to those plugins? Did the author properly specify a plugin name and icon?

**Comment by gergo85** [comment]
Other plugins are affected by this error.
![popup](https://user-images.githubusercontent.com/2959112/30900547-b4e3d4c4-a364-11e7-9026-6285215676df.jpg)

**Comment by LukeTowers** [comment]
I'll need to see an example of the first plugin that was working previously not working now

**Comment by gergo85** [comment]
All plugins do not work for me. What examples do you need?

**Comment by LukeTowers** [comment]
The News and Newsletter plugin from your earlier example.

**Comment by gergo85** [comment]
Do I send sourcecode?

**Comment by LukeTowers** [comment]
No, I need to see an example of the update popup for News and Newsletter having the same behaviour as the Indicator plugins

**Comment by gergo85** [comment]
Install older version of any plugins by manually. After that you check for updates. I use October 428. This is not a fresh installed version, I updated it from 419.
![error](https://user-images.githubusercontent.com/2959112/33167421-c7b1ddc0-d03d-11e7-885d-071db4ff1118.jpg)

**Comment by LukeTowers** [comment]
You still haven't provided an example of the same plugin showing different behaviour in the update popup. Please do that.

**Comment by gergo85** [comment]
It works again on the October build 430.
