### ISSUE TITLE
Class 'Laravel\Tinker\TinkerServiceProvider' not found

### ISSUE THREAD

**Issue by rangrage** [octobercms/october#3126]
##### Expected behavior
Clone repo and install octoberCMS. 

##### Actual behavior
When running october:up I am getting the following error:

[Symfony\Component\Debug\Exception\FatalThrowableError]
 Class 'Laravel\Tinker\TinkerServiceProvider' not found

##### Reproduce steps
1. clone repo from gitlab
2. run composer install 
3. run october:up 

##### October build
(October build number)

**Comment by LukeTowers** [comment]
Are you sure that composer installed of the dependencies? What branch did you use?

**Comment by rangrage** [comment]
I've scrapped the directory and re-pulled the repo and it's all working fine now. Are there any known issues using PHP 7.1?

**Comment by GomatoX** [comment]
The same issue is here, I moved from 7.0.* to 7.1.* PHP and it's happened.

**Comment by keiosweb** [comment]
Have the same if I composer update any project created with `composer create-project` from dev-master.

**Comment by ukebako** [comment]
The root of problem is upgraded foundation framework to Laravel 5.5 since October's build 420.
There are two ways to fix it:
1. Force composer to use build 419 for all ocotber modules **(tested)**:
```
    "require": {
        "php": ">=5.5.9",
        "october/rain": "1.0.419",
        "october/system": "1.0.419",
        "october/backend": "1.0.419",
        "october/cms": "1.0.419",
        "laravel/framework": "5.1.*",
       .....
```
If your create new project, you can force old version with the following command:
```
composer create-project october/october october v1.0.419
```

2. Upgrade to the new framework (not tested)
```
    "require": {
        "php": ">=7.0",
        "october/rain": "~1.0",
        "october/system": "~1.0",
        "october/backend": "~1.0",
        "october/cms": "~1.0",
        "laravel/framework": "5.5.*",
         .......
```
The upgrade was announced by OctoberCMS team but I didn't find any information the it's stable now. So, upgrade on your own risk.

Check the following Release Note for more details:
http://octobercms.com/support/article/rn-9

**Comment by rangrage** [comment]
Here are the steps I've followed to get around this problem. 

1. Edit composer.json to use Laravel 5.5 
```
"require": {
        "php": ">=7.0",
        "october/rain": "~1.0",
        "october/system": "~1.0",
        "october/backend": "~1.0",
        "october/cms": "~1.0",
        "laravel/framework": "5.5.*",
         .......
```
2. Run `composer update `

3. You may get another Media Library error, 

- To fix this edit ***modules/system/twig/Extension.php*** as follows:
`use System\Classes\MediaLibary;`

- Correct the typo: 
`use System\Classes\MediaLibrary;`

4. Run `october:up` 

You should then be all good.

**Comment by MattPurland** [comment]
@rangrage this fixed it for me too, not entirely sure why composer.json didn't have the correct Laravel version. Didn't need to fix the MediaLibrary issue though. Cheers!

**Comment by LukeTowers** [comment]
@MattPurland composer.json does not get updated by composer update, so when you updated via composer you pulled in Build 420+ but you were not using Build 420+'s composer.json

**Comment by rdroe** [comment]
Where is the composer.json where I am supposed to make this change (i.e. Laravel 5.1 => 5.5)? 
The website I'm working on may have been installed with the installer, so it is not in what I presume to be the normal composer.json location (e.g. the root directory of the site or project ).
Thanks for any help.

**Comment by w20k** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
