### ISSUE TITLE
Method not defined 'formatException()' in Exception Handler

### ISSUE THREAD

**Issue by yapsr** [octobercms/october#3127]
The method 'formatException()' is not defined here: https://github.com/octobercms/library/blob/d9a9adcc20b110c5516bc69910e7459dd025aa9d/src/Foundation/Exception/Handler.php#L153

Got this due to this error: "Undefined variable: _SESSION in ..."

**Comment by yapsr** [comment]
Possible duplicate of #3416

**Comment by LukeTowers** [comment]
Duplicate of #3416. (Technically it's a duplicate of this, but the discussion is happening there so I'm closing this one)

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/library/commit/53ef96b69925ed5310581de1608d96b2dbc127e9
