### ISSUE TITLE
Is October under active development?

### ISSUE THREAD

**Issue by JeyKeu** [octobercms/october#3132]
Hi,

We are planning to use OctoberCMS for a long-term project.
is the cms under active development?
My self is a WordPress developer but I found October to be the best CMS as people refer it to in compassion to WordPress because of its architecture and also due to the fact that its based on Laravel.

P.S: I've been toying around with it since yesterday and so far I found it really great and doesn't come in my way. Being familiar with Laravel and TwigI really enjoyed churning out a basic plugin in a very short time.

Please keep up the good work and please don't let this project die, we want to use it.

Regards,

**Comment by LukeTowers** [comment]
Yes, OctoberCMS is under very active development. See https://github.com/octobercms/october/pulse to get a feel for recent happenings, and check out the Slack team for OctoberCMS to talk to other developers working with and on the project.

**Comment by JeyKeu** [comment]
Great, thanks.
I'm learning it and enjoying every moment.
