### ISSUE TITLE
The Lists widget pagination does not count correctly if SoftDelete is used

### ISSUE THREAD

**Issue by alxy** [octobercms/october#3138]
##### Expected behavior
The Lists widget pagination should correctly count the records total and exclude softdeleted records.

##### Actual behavior
Actually, it appears to count all recrods, although it correctly only displays the non-deleted ones:
```
Displayed records: 1-72 of 73
```

##### Reproduce steps
Create a Model that implements ``SoftDelete`` and carefully observe the lists pagination count.

##### October build
422

**Comment by LukeTowers** [comment]
Could you dig into it and see if you could provide a fix for that behaviour?

**Comment by alxy** [comment]
@LukeTowers Provided a fix.

**Comment by LukeTowers** [comment]
@alxy perfect, thanks - will review it now!
