### ISSUE TITLE
Error with upload image

### ISSUE THREAD

**Issue by Vertexadm** [octobercms/october#3141]
Hi, i'm give directly a screen for information and view the problem really 

https://i.imgur.com/fQcjMCA.png

Thanks you for your help

**Comment by alxy** [comment]
It appears your model does not have an $attachOne/$attachMany relation with name "avatar" defined.

**Comment by LukeTowers** [comment]
@alxy is correct @Vertexadm, check out the docs here: octobercms.com/docs/database/attachments
