### ISSUE TITLE
DataFeed behavior

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#3142]
##### Expected behavior
To have the correct items in the datafeed

##### Actual behavior
After adding 2 items (from 2 different model) in a datafeed, the datafeed is containing 6 items.

##### Reproduce steps
````php
$feed = new DataFeed;
        
$tenders = $this->project->tenders;
$opportunities = $this->project->opportunities;

$feed->add('opportunity', $opportunities->first());
$feed->add('tender', $tenders->first());

trace_log(count($feed->limit(1000)->get()));
// return 6 instead of 2

````

##### October build
419

**Comment by LukeTowers** [comment]
@chrisvidal do you mind digging into the internals to figure out why this is the case? I don't really have time to investigate this myself right now.

**Comment by chrisvidal** [comment]
@LukeTowers 
Sure, where do you suggest I look into ? Tks

Another bug, is that when the feed is empty, using the limit() or count() raise an exception

**Comment by LukeTowers** [comment]
Look at the datafeed class, try doing some debugging in there.

**Comment by jimcottrell** [comment]
@chrisvidal Wouldn't the result from count() depend on how many records are in each model's database table? I don't see why the expectation would be that adding two models results in two items in the result set, since the DataFeed isn't a simple collection.

**Comment by Samuell1** [comment]
Its maybe because you need to pass array of objects not a first, then thats why it counts object inside your model thats why it returns 6.
