### ISSUE TITLE
Session & Cookie Auth Mismatch (Mission Auth Session)

### ISSUE THREAD

**Issue by uwascan** [octobercms/october#3144]
##### Expected behavior
I have an Angular 4+ SPA App as part of my October CMS theme. Normally when using a SPA in a Cookie Authenticated Web app, The SPA uses the auth cookie for all request to the backend

##### Actual behavior
I am using RainLab.User plugin for authentication and user management in my october cms app. As stated above, my theme includes an Angular 4+ SPA App which depends on Octobr CMS auth cookie provided by the RainLab.User plugin. After login in from the frontend and accessing the SPA session of my frontend, all API request sent to the October CMS are not authenticated even though the auth cookie is sent along with every request. After debugging I find that the ```check``` method of ```October\Rain\Auth\Manager``` fails to find the session key but it finds the cookie. Authentication fails because of the AND (&&) condition. The offending code is in the check method of ```October\Rain\Auth\Manager``` is shown below:
```
			if (
				!($userArray = Session::get($this->sessionKey)) &&
				!($userArray = Cookie::get($this->sessionKey))
			) {
				return false;
			}
```
I have spent days trying to work around this issue with no success.

##### October build
Build 422

**Comment by LukeTowers** [comment]
That doesn't seem right to me, that will only return false if it fails to find a user after trying both the session and the cookie. Am I wrong?

**Comment by uwascan** [comment]
After some more search online I am beginning to think that this is related to the recent changes made in the code base in moving to Laravel 5.5. The fact that the Session Middleware is not activated for all routes by default. I will test this by following the suggestion made here and post about my findings

**Comment by LukeTowers** [comment]
That would make more sense to me. The general solution to that problem is to add the web middleware to your custom routes. Let me know how it goes!

**Comment by uwascan** [comment]
Adding ```->middleware('web')``` to my routes fixed it for me.

**Comment by LukeTowers** [comment]
Glad to hear it!

**Comment by flyingbaba** [comment]
Please help with that, where should I put ->middleware('web') , I'm simply using auth like in its basic usage and front end fails to keep the session.

**Comment by LukeTowers** [comment]
@flyingbaba that's a separate issue, this only applies to custom routes within plugins.
