### ISSUE TITLE
 [Social Login] Plugin  Permission Issue for the backend user 

### ISSUE THREAD

**Issue by detrojaashish** [octobercms/october#3151]
##### Actual behavior
Display Setting Menu and social Login plugin data   

##### Reproduce steps
I have created the Backend user and set the particular permission for more detail please see the attachment screenshot.

![1](https://user-images.githubusercontent.com/16516381/31168236-41d1070a-a912-11e7-9a74-589d04a69548.png)
![2](https://user-images.githubusercontent.com/16516381/31168235-41573d12-a912-11e7-8dac-8b938ae530d8.png)

**Comment by detrojaashish** [comment]
Plase add the 'permissions' => ['rainlab.users.access_settings'] Under plugins/flynsarmy/sociallogin/Plugin.php -> registerSettings()

**Comment by LukeTowers** [comment]
This issue belongs to the plugin in question, log it there: https://bitbucket.org/flynsarmy/oc-sociallogin-plugin
