### ISSUE TITLE
[Question] Fetch Partials only via AJAX 

### ISSUE THREAD

**Issue by rajakhoury** [octobercms/october#3154]
Hi, I am wondering if is there a way to use the AJAX framework to fetch partials only, in the example below the setup makes sense because I dont need only to fetch a menu partial but also im querying the DB for a record, but in some cases I just need to load a partial via AJAX without fetching any remote data.
 
Is there something / or makes sense to have a feature like `data-request-partial="divToUpdate : partial" ?

Well this helps avoid adding a function to the component to just return a partial.

Thanks
##### Example

**Partials**

    <button>
        data-target="#menu-modal"
        data-request-data="employee: {{Code}}"
        data-request="{{ __SELF__ }}::onGetMenu"
        data-toggle="modal">
    </button>

    <div id="menu-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

**Component**

	public function onGetMenu ()
	{
		return [
			'#menu-modal' => $this->renderPartial('@menu', [
				'employee'  =>  $this->employee
			])
		];
	}

##### October build
419

**Comment by LukeTowers** [comment]
@rajakhoury This already exists, it's the `data-request-update` attribute: https://octobercms.com/docs/ajax/update-partials#pulling-updates
