### ISSUE TITLE
BackendAuth::login($user); not working

### ISSUE THREAD

**Issue by matheusrrocha** [octobercms/october#3162]
##### Expected behavior
When passing a Backend\Model\User instance to the method BackendAuth::login($user);, the user has to be logged into the admin

##### Actual behavior
User is not logging into the admin and the login page shows up

##### Reproduce steps
$user = BackendAuth::findUserByLogin($username);               
BackendAuth::login($user);
return Backend::redirect('backend'); //redirect to login and not to dashboard as a normal logged user

##### October build
425

**Comment by matheusrrocha** [comment]
I was trying to execute inside a Plugin boot method. It works only inside a controller method.

**Comment by LukeTowers** [comment]
@matheusrrocha are you sure that it's not just because you don't have the `$elevated = true` flag on your plugin?

**Comment by briddle** [comment]
For future reference:

I needed to add protected $publicActions = ['index']; to the controller I was redirecting to to allow it to be called when not (yet) logged in :(

**Comment by fanti1** [comment]
Hi guys, I went through this problem today and in my case it was resolved by placing the 'web' middleware in the routes.
Without it, BackendAuth::login($user) simply wouldn't work, as I imagine it needs some internal middleware stuff.
