### ISSUE TITLE
Allow for page url aliases

### ISSUE THREAD

**Issue by yapsr** [octobercms/october#3165]
##### Expected behavior
Allow for extra url patterns in page configuration section:

> 
> `title = "Contact"`
> `url = "/contact"`
> `alias[0] = "/my/section/contact"`
> `alias[1] = "/how-to-contact-me"`
> `alias[2] = "/kontakt"`
>

##### Actual behavior
None existing. Using a redirect, a regex in the url or using the translation plugin is not appropriate in this case.

##### October build
419

##### Suggestion
This probably needs a change to `\Cms\Classes\Router::loadUrlMap`.

**Comment by LukeTowers** [comment]
Please explain why it is not appropriate using those mentioned solutions to this problem. Also:

Feature requests as issues are only acceptable if you are using it as a pre-PR communication. If you aren't planning on implementing it yourself, then it would be better suited being asked for on one of these channels:

Forum: http://octobercms.com/forum
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

The support demand for October is increasing, while the available time the founders have to give remains the same. These feature requests are absolute lowest priority for us, they may be gotten to in time. However there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by justRau** [comment]
@yapsr please see answer here: https://octobercms.com/forum/post/url-aliases?page=1#post-24354

You could extend this example to suit your use case.

**Comment by LukeTowers** [comment]
@yapsr Closing as this could be implemented by a plugin. Thanks for the follow up @justRau!

**Comment by yapsr** [comment]
@justRau @LukeTowers Thank you for mentioning a possible solution.
