### ISSUE TITLE
Extend markdown

### ISSUE THREAD

**Issue by marijnhurkens** [octobercms/october#3167]
What would be the best way to extend the markdown parser? I'm trying to achieve the following.

I want to show some extra info when the user click on a word or sentence in my blog. The syntax could be something like:

```markdown
This is a sentence where I would like to [explain *1] a certain word.

[*1]: 
Multi line footnote placed
here etc. etc. etc.
```

This should expand to:

```html
This is a sentence where I would like to <abbr data-abbr-id="a">explain</abbr><span class="abbr-content" data-abbr-id="a">
Multi line footnote placed here etc. etc. etc.
</span> a certain word.
```

I want to hide the `span.abbr-content` with css and show the span tag on click with js as a `display: block` element.

How can I achieve something like that? If I try this with inline html in the markdown I quickly get in trouble with `p` tags added by the markdown parser.

**Comment by LukeTowers** [comment]
There are `markdown.beforeParse` and `markdown.parse` events that you can listen to and do your own parsing on the data provided. I recommend that you use the `markdown.parse` event as it runs after the parsing by October is complete. See https://github.com/octobercms/library/blob/master/src/Parse/Markdown.php#L94. If you would like to add inline docs for the event, that would be appreciated, look at the https://github.com/octobercms/library/blob/master/src/Parse/Markdown.php#L94 for an example of how to do it.
