### ISSUE TITLE
Undefined property: stdClass::$description 

### ISSUE THREAD

**Issue by Nikl10** [octobercms/october#3168]
I created plagin it work well created component too working not bed the same all plugins in backup menu, but wen i clicking on the icon "Settings" in the same backup menu, I receive - Undefined property: stdClass::$description  ...modules\system\partials\_settings_menu_items.htm line 24
If i delete the component i created all working well

**Comment by LukeTowers** [comment]
You are probably missing the description array key that should be present in your Component.php componentDetails() method.

**Comment by Nikl10** [comment]
Thanks! that is  it.
