### ISSUE TITLE
A table is not created when a Model is created

### ISSUE THREAD

**Issue by VasiliDarozhkin** [octobercms/october#3171]
##### Expected behavior
1) A model is created for a plugin
`php artisan create:model Author.Plugin Model`
2) 1.0.1: Request Model was added
        - A request table was created
        - create_requests_table.php
A lines were added to version.yaml
3)  `php artisan october:up` and `php artisan plugin:refresh Author.Plugin` were executed
4) A database table `author_plugin_model` is created
5) Error logs records are created to display what went wrong

##### Actual behavior
4) A table is not created

##### October build
the most recent

**Comment by LukeTowers** [comment]
Actual code example please.

**Comment by VasiliDarozhkin** [comment]
plugins/vasdor/calc/updates/create_requests_table.php
~~~~
<?php namespace Vasdor\Calc\Updates;

use Schema;
use October\Rain\Database\Schema\Blueprint;
use October\Rain\Database\Updates\Migration;

class CreateRequestsTable extends Migration {
	public function up() {
		Schema::create('vasdor_calc_requests', function (Blueprint $table) {
			$table->engine = 'InnoDB';
			$table->increments('id')->index();
			$table->text('request')->index();
			$table->timestamps();
		});
	}

	public function down() {
		Schema::dropIfExists('vasdor_calc_requests');
	}
}
~~~~

version.yaml
~~~~
1.0.0: First version of Calc
1.0.4: Request Model was added
        - A request table was created
        - create_requests_table.php
~~~~

**Comment by VasiliDarozhkin** [comment]
`october:down` and `october:up` didn't help.

**Comment by VasiliDarozhkin** [comment]
I found the error. Format of the version.yaml update line should be
~~~~
1.0.4:
        - A request table was created
        - create_requests_table.php
~~~~

not 
~~~~
1.0.4: Request Model was added
        - A request table was created
        - create_requests_table.php
~~~~
