### ISSUE TITLE
form helper for number field 

### ISSUE THREAD

**Issue by JeyKeu** [octobercms/october#3173]
`{{ form_text('field_name',
            form_value('field_name'),
            { 'type':'number', 'id':'fieldName' , 'class' :'form-control' }) }}`

Notice `type:number` is specified but still it renders a text field and there is no `form_number` named function. My initial thoughts were it will work as these are available in [Laravel Collective](https://laravelcollective.com/docs/5.4/html#number) but no.

In October's official documentation there is no detail about `form_text` either.
Please help

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
