### ISSUE TITLE
Global has_access permissions helper

### ISSUE THREAD

**Issue by romaldyminaya** [octobercms/october#3175]
##### Expected behavior
It would be nice to have a global helper to could check for current user permissions easly. Something like:

```
   has_access('acme.plugin.update_posts');
```
instead of:

```
   $this->user->hass_access('acme.plugin.update_posts');
```

This is because if you want to check something withing a model, you must refferene the BackendAuth facade. So I came out with this in my project.

##### Suggested Code
```
 if (!function_exists('has_access'))
 {
     /**
      * Check if the current user has the specified access
      *
      * @return string
      */
     function has_access($permission)
     {
        $user = \BackendAuth::getUser();

        if($user)
        {
            return $user->hasAccess($permission);
        }

        return false;
     }
 }
```

##### October build
(424)

**Comment by LukeTowers** [comment]
I do something similar in one of my projects, `AuthService::userHasAccess('permission', $optionalUserObject)`.

I don't see this being implemented in core seeing as it is easily added by plugins, and could lead down a slippery slope of adding helpers for everything.

**Comment by romaldyminaya** [comment]
Good @LukeTowers  then.
