### ISSUE TITLE
504 Gateway Timeout on Install

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#3176]
##### Expected behavior
Tried to install OctoberCms using laradock and web installer.

##### Actual behavior
Got 504 Gateway timeout with broken layout:
![image](https://user-images.githubusercontent.com/3897579/31632856-19feffd4-b2c7-11e7-8fe9-272160dae1b2.png)

The mentioned log file does not contain any errors.

After this I entered the php-fpm docker container directly and installed the CMS using console with no issues.

##### Reproduce steps
Install the latest OctoberCms with the latest Laradock.

**Comment by johnmain** [comment]
I also have this issue on my local dev version.  However, was able to update the production and Staging servers without any issue.

**Comment by Harti** [comment]
For future reference, this seems to happen only on some local development setups due to various timeout or script execution times not being set long enough for the installation to finish, cf. https://octobercms.com/forum/post/504-gateway-time-out-error-on-unpacking-of-application-files

**Comment by GinoPane** [comment]
The same issue when updating through the backend.

**Comment by LukeTowers** [comment]
Is it really @GinoPane?

**Comment by GinoPane** [comment]
@LukeTowers it is! Actually, the environment is the same as for installation issue. It's a clean Laradock installation with a tweak to run OctoberCms on Docker. The image 4 cores and 2 GB of RAM allocated (CPU is i7 7700K). 

The error itself is the same as on the screenshot - 504 timeout on unpacking.

If it can be fixed using PHP's max_execution_time, so maybe it would be better to set this limit automatically in installation script (and set it back after complete)?

**Comment by GinoPane** [comment]
@LukeTowers 
I've investigated it more and fixed it. The reason was in Nginx timeout, not PHP, so it cannot be fixed in runtime through the code. I noticed that all failures were exactly after 60 seconds - the default Nginx timeout. Setting the **fastcgi_read_timeout** to something bigger did the trick. Now installation and update work fine.

As long as it cannot be fixed in code, we still can add a small note for users, probably. Something like "Unpacking of the archive may take some time. Please make sure to increase server timeout".

**Comment by LukeTowers** [comment]
It'd be nice if we could detect a timeout during this process and then display a descriptive error message with links to learn more about how to increase the timeout accordingly

**Comment by GinoPane** [comment]
@LukeTowers I agree, it would be definitely better, but I didn't manage to find a way to do this (just because PHP itself can not control this timeout). I'll try to investigate this more.

**Comment by LukeTowers** [comment]
There would have to be something in the client side that detects the HTTP error code for timeouts and displays the appropriate message. It'd be great if you could make a PR for that!

**Comment by GinoPane** [comment]
@LukeTowers to be honest, I was thinking about splitting of the core archive into parts and extracting them one by one, so the timeout won't be reached at all 😄 
But I like your suggestion too, I'll probably look into that.

**Comment by GinoPane** [comment]
@LukeTowers I ended up with something like this for now:

![image](https://user-images.githubusercontent.com/3897579/36919814-a6b688ac-1e6f-11e8-8780-b4786beee0c2.png)

The links are to the official Apache and Nginx documentation (timeout-specific sections).

If this looks fine, I'll create a PR to octobercms/install then.

**Comment by LukeTowers** [comment]
That works great @GinoPane! Could you change the wording to "The operation timed out. Please increase the server's timeout and try again."

That's a much better way to handle it for the users!

**Comment by mazzzai** [comment]
can you help me with same trouble?

mac high sierra

https://i.stack.imgur.com/KSXmt.png

**Comment by LukeTowers** [comment]
@mazzzai no.

The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.
