### ISSUE TITLE
HasOne relation does not handle Collections during assigining 

### ISSUE THREAD

**Issue by TimFoerster** [octobercms/october#3178]
Edit: I found out the problem, see second comment. 

##### Expected behavior
Form update should be displayed with related HasOne model (works in Build 419).

##### Actual behavior
model is not displayed, $fatalError is set in the view. I just throw the exception again to get the stack trace 
![screen shot 2017-10-17 at 13 34 20](https://user-images.githubusercontent.com/7849550/31663063-0c7a0e42-b341-11e7-9be1-ab45af1ea096.png)

##### Reproduce steps
I have just a extended model with a new HasOne relation. 
Like you can see on the images, the relation is correctly loaded and it is attached (`$instance`).

![screen shot 2017-10-17 at 13 32 43](https://user-images.githubusercontent.com/7849550/31663062-0c58329a-b341-11e7-9734-5e149d2824ca.png)

When calling `$instance->getOriginal(...)` the macro `getOriginal` can't be found by the `$instance` collection.
![screen shot 2017-10-17 at 13 37 30](https://user-images.githubusercontent.com/7849550/31663064-0c955f58-b341-11e7-9962-cc2ad657bc47.png)
##### October build
425

#### Investigating the error

So somehow calling `$instance->getOriginal` on `Collection` does not resolve correctly, the `macros` are empty.
If you get the item and call it, it works `$instance->get(0)->getOriginal()`, see image:
![screen shot 2017-10-17 at 13 50 03](https://user-images.githubusercontent.com/7849550/31663376-220562ba-b342-11e7-8614-628c489124d9.png)

So somehow the `Collection` `macros` are empty in this case and `getOriginal` can not be resolved.

**Comment by TimFoerster** [comment]
I investigated deeper. I found the problem. 
I extended the model in a plugin. I needed to load the relation for update model form (in build < 420). I did it by listen to `Event::listen('backend.form.extendFields', function($widget) {...}` to attach the model with `$widget->model->newsPdf = NewsPdf::byNews($widget->model->id)->get()`

Now `->get()` on Eloquent gives a collection. `$widget->model->newsPdf = ...` tries to set the given collection as relation, which fails.

With Laravel 5.5 its not required anymore to load the relation for the FormController.

If someone got the same problem: `$widget->model->newsPdf = NewsPdf::byNews($widget->model->id)->first();` fixes the problem, but like I mention earlier, it's not required for updating the model anymore.

What is open now:
Add some checks for assigning collections to a relation?

**Comment by LukeTowers** [comment]
@TimFoerster Why do you extend your model in the `backend.forms.extendFields` event instead of extending the model directly? Then you could properly have the relation available everywhere:
```php
NewsModel::extend(function ($model) {
    $model->hasOne['newsPdf' => '\MyAuthor\MyPlugin\Models\NewsPDF'];
});
```

**Comment by TimFoerster** [comment]
I have the following:
```
class Plugin extends PluginBase { ...
    public function boot() { ...
        NewsPosts::extend(function($model) {
            $model->hasOne['newsPdf'] = ['TimFoerster\NewsPdf\Models\NewsPdf', 'key' => 'post_id', 'otherKey' => 'id', 'default' => true];
            $model->attachOne['pdf'] = ['System\Models\File'];

            $model->bindEvent('model.afterCreate', function() use ($model) {
                $model->newsPdf->post_id = $model->id;
            });
      }
      ...
   }
   ...
}
```

and

```
class NewsPdf extends Model
{
    ...

    public $belongsTo = [
        'news' => ['Indikator\News\Models\NewsPosts', 'key' => 'post_id']
    ];
   
   ...
}
```
But sometimes i got some strange behaviour in the <420 builds with the FormController that didn't resolve the relation correctly. 

In the ≥420 builds it works fine so far. That's why I removed that loading.

**Comment by LukeTowers** [comment]
You shouldn't need the `model.afterCreate` event either

**Comment by TimFoerster** [comment]
negative, post_id is null after creating model.

![screen shot 2017-10-17 at 17 20 39](https://user-images.githubusercontent.com/7849550/31673519-b336ce64-b35f-11e7-81ae-d1abbda3f3e4.png)

When updating the model, the id will be set.
![screen shot 2017-10-17 at 17 28 41](https://user-images.githubusercontent.com/7849550/31673914-b1df9d9c-b360-11e7-87e4-f7e1578e416b.png)
