### ISSUE TITLE
Problem with mediafinder effiency

### ISSUE THREAD

**Issue by jbartoszek** [octobercms/october#3179]
Hi i have a problem with mediafinder

**Expected behavior**
We are expecting to support multiple madiafinders onto one view/screen without loosing browser efficiency.  

**Actual behavior**

A few media finders causing huge drop of browser efficiency when implemented (for example into repeater). During second, third image upload browser is freezing (Chrome,FF). Using card/view is impossible. Problem didn’t exist in the built 387

**Reproduce steps**
1. Create form in the CMS
2. Add into fields.yaml a few mediafinders (4-5) or add repeater which include mediafinder
3. Try to upload a few images (bigger file sizes are better). When you try to open mediafinder on the 3-4th object browser is freezing and it is not possible to use it.
**Problem exist only when you upload new element, not editing existing one.** 

**October build**
419.

Best Wishes,
Jacek

**Comment by LukeTowers** [comment]
Could you dig deeper into this using Chrome's profiling tools to find out where the bottleneck is please?

**Comment by jbartoszek** [comment]
Profiling showed me that problem was with my extra js event. It isn't october core problem. I am so sorry for the confusion.
Topic to close and remove.

**Comment by LukeTowers** [comment]
No worries, do you mind explaining your problem here for everyone else to learn from?

**Comment by jbartoszek** [comment]
Yes, of course. When form was a create context i added my own js file to select default checkboxes on checkbox list. The js file had an loop on event. Each launch of 'ajaxUpdateComplete' event added new this same event on delegate. My function attach to the event was a recursive.

For example.
`
var checkboxes = {
    
    init: function () {
        //checking chexkboxes
       $(window).on('ajaxUpdateComplete', function() {
             languagesDropdown.init();
        });
    },
};

$(function () {
    languagesDropdown.init();
});
`
