### ISSUE TITLE
Export using the useList attribute for datetime columns produces HTML output

### ISSUE THREAD

**Issue by mohamedfayez** [octobercms/october#3180]
##### Expected behavior
When using the export feature in a backend controller based on a model that has a column with any of the datetime types, and the config_import_export.yaml contains the export attribute useList:true , the exported csv should contain the datetime value as it should, like: Tue, Apr 25, 2017 3:57 PM

##### Actual behavior
The exported csv contains the datetime values with extra html formatting, like: "<time datetime="2017-04-25 15:57:57" data-datetime-control="1" data-format-alias="dateTimeLongMin">Tue, Apr 25, 2017 3:57 PM</time>

##### Reproduce steps
Have a plugin's model contain a column with any of the datetime column types, like: 
    created_at:
        label: Registration date
        type: datetime
And a controller that implements the ImportExportController, and its config_import_export.yaml contains the export with the useList attribute, like:
    export:
        title: Export Users
        modelClass: plugin\Models\User
        useList: true

##### October build
419

#### Comment
If I am missing something in my configuration that can fix this issue, please assist. Thanks

**Comment by LukeTowers** [comment]
So is the problem that the export contains extra quotes?

**Comment by mohamedfayez** [comment]
I apologize, the markdown syntax here doesn't show the correct Actual behavior because it contains an html element tag.
What it actually produces is like this (I removed the tag brackets at the start and end): 

time datetime="2017-04-25 15:57:57" data-datetime-control="1" data-format-alias="dateTimeLongMin">Tue, Apr 25, 2017 3:57 PM</time
--

**Comment by LukeTowers** [comment]
@mohamedfayez you can use three backticks before and after to mark it as code. I've edited your reply to reflect this.

**Comment by LukeTowers** [comment]
@mohamedfayez See http://octobercms.com/docs/backend/import-export#list-behavior-integration; specifically the `raw` option. Please let me know if that resolved your issue.

**Comment by mohamedfayez** [comment]
Thanks for responding Luke, I already tried the `raw` option and it produced the basic sql format `2017-04-25 15:57:57` , is there a way to keep the datetime format `Tue, Apr 25, 2017 3:57 PM` as produced by the list?

**Comment by LukeTowers** [comment]
@mohamedfayez I see what your problem is now. I've added a new `backend.list.overrideColumnValueRaw` event in https://github.com/octobercms/october/commit/ac2e5937f04396d158f74e8b710c10a0d6f06e9d for you to hook into in order to format the date time as desired. 

You can hook into this event in the `onExport()` method in your controller:
```php
public function onExport()
{
    Event::listen('backend.list.overrideColumnValueRaw', function ($record, $column, $value) {
        // check if the column is the one you want to affect
        // format the date value as you want
     }

    return $this->asExtension('ImportExportController')->onExport();
}
```

**Comment by codengine-au** [comment]
@LukeTowers - I'm struggling to get the onExport() event to fire if I am using the list behavior. I've set out the above:

ImportExport.yaml
`export:
    useList: true`

Controller
`
class Products extends Controller
{
  etc.

    public function onExport()
    {
        Event::listen('backend.list.overrideColumnValue', function ($record, $column, $value) {
            dump($value);
            $value = 'test';
        });

        return $this->asExtension('ImportExportController')->onExport();
    }

}
`

I've even tried added it the data attribute to the export button, but it seems to bypass - no AJAX request / event is firing in the Network tab.

`
    <a
        href="<?= Backend::url('codengine/awardbank/products/export') ?>"
        class="btn btn-primary oc-icon-download"
        data-request="onExport">
        Export entries
    </a>    
`

**Comment by LukeTowers** [comment]
@codengine-au check what the default code looks like and see what's different between that and your implementation.

**Comment by KonstantinObuhov** [comment]
For someone who wants to use the list with export config  should looks like this:
![image](https://user-images.githubusercontent.com/15628982/91046444-1773dd80-e621-11ea-8dbd-3c384eb58ae5.png)
