### ISSUE TITLE
Upgrade bug from 425 to 426

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3189]
I get this error screen when I upgrade from 425 to 426.

![untitled](https://user-images.githubusercontent.com/17784082/31859370-f37fd76c-b702-11e7-91a9-de56cfd05ddf.png)

```
We're sorry, but an unhandled error occurred. Please see the details below.

Class 'System\Twig\MediaLibrary' not found
/home/xxxx/public_html/modules/system/twig/Extension.php line 105
```

Is it me or the beta version of October thanks...?

**Comment by LukeTowers** [comment]
Could you please take a look at the top of `\System\Twig\Extension` and see if it includes this line: https://github.com/octobercms/october/blob/develop/modules/system/twig/Extension.php#L9?

**Comment by ayumihamsaki** [comment]
Hi Luke thanks for replying, I have this line in my Stack Trace:

```
Stack trace:
#0 /home/xxxx/public_html/storage/cms/twig/7e/7e09a9bf83a7be9345088469329266a46184c2b57a85498755f21713fcf40ce3.php(39): System\Twig\Extension->mediaFilter('/primaryimg/xxx...')
```

**Comment by ayumihamsaki** [comment]
Hi Luke, 

Thanks for your reply, yes the file:

`/modules/system/twig/Extension.php`

It was showing:

`use System\Classes\MediaLibary;`

and I manually went in and changed it to:

`use System\Classes\MediaLibrary;`

So when I upgraded it didn't update that file automatically.

**Comment by LukeTowers** [comment]
Ah, right. @ChVuagniaux discovered that and fixed it in a PR: https://github.com/octobercms/october/commit/c7dcd386d1462d70d3aaac098fc271ddbefdc9ad. Good to hear it's working now!

**Comment by JumpLink** [comment]
@ayumihamsaki That's it, thank you!
