### ISSUE TITLE
sometimes|required does't appear to work

### ISSUE THREAD

**Issue by AugmentBLU** [octobercms/october#3191]
##### Expected behavior
I have field that is only required to be validated when updating a record but not on creation. I expect the field, which is not present in the create form, to be skipped while validating due to the `sometimes` rule.

##### Actual behavior
The field is required, even if it's not present in the rendered form, no input is sent in the post array. 

From the Laravel docs, I assume that `sometimes|required` means that if the input is in the array, it will be validated, it's not present it will be skipped.

##### Reproduce steps

I have a very simple model.

Include
```
use October\Rain\Database\Traits\Validation;
```

Rules
```
public $rules = [
   'status'    => 'sometimes|required',
   'name' => 'required|min:10',
];
```

Simple fields.yaml
```
status:
        label: status
        type: text
        context: update
```

When creating a new record, it will error as the status is required - even though it's not on the page and the `sometimes` rule is in place. 

Am I understanding how the sometimes rule works correctly? 

##### October build
425/6

**Comment by jimcottrell** [comment]
It sounds like your understanding of `sometimes` matches mine, though I've never really had a reason to use it in a real project yet. I tried to duplicate this issue, but it seems to work as expected, where my record is created fine, and then an error occurs on update. Maybe post a link to a test repo where this happens?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by filipac** [comment]
@LukeTowers this is still an issue.
Example:
```php
public $rules = [
        'fax' => 'sometimes|phone:US',
    ];
```
This should validate a fax number only if present..

**Comment by Samuell1** [comment]
@filipac it needs to be `sometimes|required|phone:US`

**Comment by filipac** [comment]
@Samuell1 it is not required, just has to be a valid number.

**Comment by filipac** [comment]
I did a hack:
```php
public function getAttributes()
    {
        $att = parent::getAttributes();
        if(array_key_exists('fax', $att) && is_null($att['fax'])) {
            unset($att['fax']);
        }
        return $att;
    }
```
