### ISSUE TITLE
I keep getting this error after upgrading to 426

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3193]
Hi (again),

I keep getting this error in my Stack Event Logs after updating to 426.

`getGroupStatus is deprecated. Please update getCollapseStatus instead. Class: RainLab\Builder\Widgets\ModelList`

Need some help to pin point the error and correct it huhuhu. Thanks to Luke and Daftspunk in advance...

I tried re-installing builder to 1.0.21

**Comment by LukeTowers** [comment]
This is an issue for the Builder plugin, make an issue / pull-request in the builder repository. See https://github.com/rainlab/pages-plugin/pull/290 for reference as to what would need to be changed.
