### ISSUE TITLE
Add a Javacript input to customize the backend

### ISSUE THREAD

**Issue by pvullioud** [octobercms/october#3196]
##### Expected behavior
<img src="https://monosnap.com/file/F7WpvObGv7hWqmAZIheAHbksPkKRzd.png">

##### Actual behavior
We can inject CSS in the backend template but not Javascript
This could be useful to implement tracking code and third party integration.

I can implement it if you agree with the proposal

**Comment by LukeTowers** [comment]
I'm not sure I like adding Javascript to be something easily done. You can always add JS with a custom plugin, it seems a bit dangerous to allow anyone with permissions to manage the backend branding to insert arbitrary JS though.

**Comment by pvullioud** [comment]
You can also break the backend with custom css :)
It make sens to do an external plugin as a start. You can close the issue

**Comment by LukeTowers** [comment]
Break the backend, yes. Enable hidden XSS attacks by malicious backend users? Not quite :)
