### ISSUE TITLE
'Cms\Classes\Controller' does not have a method 'onBeforePageStart'

### ISSUE THREAD

**Issue by frendhisaido** [octobercms/october#3210]
##### Expected behavior
CMS Page successfully rendered

##### Actual behavior
Error thrown:

> call_user_func_array() expects parameter 1 to be a valid callback, class 'Cms\Classes\Controller' does not have a method 'onBeforePageStart'
![screencapture-1509329871216](https://user-images.githubusercontent.com/426018/32151992-a64cf1d0-bd53-11e7-8fbe-b7c42063aeb2.png)

##### Reproduce steps
Steps to reproduce the error is currently unknown. 
I'm using keios multisite plugin. [https://octobercms.com/plugin/voipdeploy-multisite](https://octobercms.com/plugin/voipdeploy-multisite)
Nginx. Redis. MariaDB. Php 7.1 with Opcache enabled.

##### October build
419

**Comment by LukeTowers** [comment]
The error tells you what is wrong, you are trying to call a method named `onBeforePageStart()` that doesn't exist. Post your CMS page's code section that this is happening on.

**Comment by frendhisaido** [comment]
Hi @LukeTowers , thank you very much for your response. 

> you are trying to call a method named onBeforePageStart()

Exactly! I've never used the method onBeforePageStart in any page's code section nor in any components. 

Here is the default layout:
```
description = "main"

[staticPage]

[staticMenu]
code = "main"

[xxxxComponentMultiSite]

[xxxxComponentMultiSiteSlideShow]

[googleTracker]
[searchResults]
apikey = "xxxxxx"
cx = "xxxx"
resultPerPage = 10
sendReferer = 1
==
<!doctype html>
<html class="no-js" lang="en">

<head>
  {% partial "meta" %}
  <title> {{ this.page.title }} | {{ masterweb.title }}</title>
  {% partial "css" %}
</head>

<body>


{% partial 'navbar' %}
{% if this.page.id == 'beranda' %}
    {% partial 'slideshow/default' %}
{% endif %}
  <div class="row" id="content">
    {% page %}
  </div>
{% partial "footer" %}

{% partial "js" %}
{% component 'googleTracker' %}
</body>

</html>
```

It's only 44 lines, but the error said ".. line 108 .."
Maybe the error referenced to the compiled twig file?

**Comment by LukeTowers** [comment]
Did you check those plugin components to see if they were referencing it?

**Comment by frendhisaido** [comment]
I did, none of them (my plugin and installed ones or in any of my theme files) referencing to onBeforePageStart.
It only exists in these files :
https://github.com/octobercms/october/search?utf8=%E2%9C%93&q=onBeforePageStart&type=

Haven't check the compiled twig file though. 
Is it possible that this has something to do with opcache?

**Comment by LukeTowers** [comment]
@frendhisaido you could try disabling opcache, see if that helps. Check the compiled twig file to see if you can determine where it's coming from.

**Comment by frendhisaido** [comment]
Alright, @LukeTowers 
Opcache disabled.. I'll wait for a while. 
```
$ grep -r "onBeforePageStart" --exclude="./storage/logs/system.log" .
./modules/cms/classes/Controller.php:                ($result = $this->layoutObj->onBeforePageStart())
./modules/cms/classes/LayoutCode.php:    public function onBeforePageStart()
./tests/fixtures/themes/test/layouts/cycle-test.htm:function onBeforePageStart() {
```

**Comment by frendhisaido** [comment]
opcache disabled...
redeployed the theme files...
ran artisan cache:clear.. 

Works again for a while, but
the error keep appearing randomly.. 

After I sign in to the backend the error is disappear.
That's the only way to fix the error right now.. 
Any clue, please?

**Comment by LukeTowers** [comment]
Very odd, it would seem like the code object for the layout getting used is not an instance of https://github.com/octobercms/october/blob/master/modules/cms/classes/LayoutCode.php. Could you do some debugging to find out if that is the case? Alternatively, could you using edge builds and update your October instance?

**Comment by frendhisaido** [comment]
Hi @LukeTowers , 
~2days **just a while after disabling opcache**, no reports of errors in event logs.. 
I will wait a couple days just to make sure.

I tried to reproduce the error in development env. But I can't, error never occured in development env. 
If the error reoccurs after opcache disabled, I'll try to update the october to latest update and see if it works (in development env). 

Right now, it seems this error heavily related to opcache , but I'm not 100% sure it is.

**Comment by LukeTowers** [comment]
@frendhisaido thanks for the update! Please post again in a few days to let me know if this issue reoccurs.

**Comment by frendhisaido** [comment]
Hi @LukeTowers , I'm sorry took so long. 
Fortunately, after I disabled the opcache, this issue never reoccurs.. 

Unfortunately.. 
I can't reproduce the error,
just like you've said before..
> Very odd, it would seem like the code object for the layout getting used is not an instance of https://github.com/octobercms/october/blob/master/modules/cms/classes/LayoutCode.php. 

It is very odd.. 
I can't find out why code object is not an instance of LayoutCode.php , 

I did ask the plugin author on their product support page.
http://octobercms.com/plugin/support/voipdeploy-multisite/call-user-func-array-expects-parameter-1-to-be-a-valid-callback-class-cmsclassescontroller-does-not-have-a-method-onbeforepagestart

Thanks for the support @LukeTowers !

**Comment by LukeTowers** [comment]
No problem, glad to hear it's been resolved!
