### ISSUE TITLE
Component Invalid URL Format Error

### ISSUE THREAD

**Issue by ibanks** [octobercms/october#3213]
##### Expected behavior
On the backend administration panel, when I add a component to a page (by dragging), then click save, I expect it to save to the page without error.

##### Actual behavior
Instead, when I hit save, I get this error:
`Invalid URL format. The URL should start with the forward slash symbol and can contain digits, Latin letters and the following symbols: ._-[]:?|/+*^$`

##### Reproduce steps
Create a component, drag it to the page, save it.

##### October build
Version: 1.0.1

##### Additional Notes
I believe that the issue is because application is being built on a windows based file system. In other words, in order for me to access and search certain dirs, I of course have to use backslash. So the namespace for all plugins and components use a backslash. Maybe there is a config that you have for this?

**Comment by LukeTowers** [comment]
URL's cannot contain backslashes. What does the page that you are trying to save look like?

**Comment by ibanks** [comment]
The URL itself does not contain backslashes. What I am saying is that these are namespaces for example:
`namespace ptusa\cart\components;`
...instead of...
`namespace ptusa/cart/components;`

The pages URL is domain.com/backend/cms. Here I can select any of the pages (cart.htm for instance), the markup will show for the page, I can then drag a component to the page and then click save. This is when I get the error. The thing is if I just manually add the component `[cart]` to the actual htm file, it works with no error.

**Comment by LukeTowers** [comment]
That sounds very odd, why would you have forward slashes in your namespaces? Could you paste the code that is causing the problem?

**Comment by ibanks** [comment]
I'm not exactly sure how I would paste the code itself because the error is happening with the backend portion of the cms. It is not something I edited. I attached an image below:

![image](https://user-images.githubusercontent.com/3674972/32199609-b5dd97f8-bda3-11e7-9029-02fe0fa7b122.png)

You can see the component and when I hit save that's when I get the error message.

**Comment by ibanks** [comment]
This the actual url is www.mydomain.com/backend/cms

**Comment by LukeTowers** [comment]
@ibanks the message tells you what's wrong: "The URL should **start with the forward slash symbol**..."

**Comment by ibanks** [comment]
@LukeTowers I believe you are misunderstanding the problem. I am fully aware that URL's do not use backslashes. The application is being developed in a Windows environment. This is the reason for backslashes when referencing folder structure and namespaces. In my work environment, I've created several Laravel applications and had to do the same thing. If I reference a namespace with a forward slash symbol, then I get an error. This is consistent with any application (mvc, cms..etc) created in a Windows environment.

The error message that I posted does not have anything to do with a URL that I am setting or referencing. The plugin and component obviously was created and namespaced correctly because it works. The problem is that you have a backend interface where I am suppose to be able to drag the component onto a page, click save and it still functions the same as if I manually placed the tag on the page itself. However, it is not doing that. Instead when I click save I get the error message above. I didn't not create or modify the code behind the save action..

**Comment by munxar** [comment]
@ibanks make your 'cart' a '/cart' and try save ....

**Comment by LukeTowers** [comment]
@ibanks What's happening here is you're getting caught up on the idea of the project "coming from" a windows environment. That has no impact on namespaces or the URL validation at all. The validation message tells you that the URL must **start** with a forward slash (`/cart`), as @munxar said - it currently starts with `c` (`cart`). 

As a side note, PHP namespaces only support backslashes, irregardless of environment.

**Comment by ibanks** [comment]
@LukeTowers and @munxar Got it. I see what you all are saying now. The issue is with the url value. I added the slash and it worked. I want to say apologize for my misunderstanding, but if I didn't know this I would've gone on to create the entire site like that. :-)

**Comment by LukeTowers** [comment]
@ibanks No worries, glad you've got it solved!
