### ISSUE TITLE
backend auth bug

### ISSUE THREAD

**Issue by tim0991** [octobercms/october#3215]
After sign out, i view the url /backend/backend/userroles/update/1, i get below error 

`Call to a member function isSuperUser() on null modules/backend/controllers/userroles.php line 56`
##### October build
use develop branch
commit 4a6e0e1e0e2c3facebc17e0db38c5b4d4cb05bd0

**Comment by LukeTowers** [comment]
How is this a bug? The backend isn't going to work unless you are signed in

**Comment by munxar** [comment]
how about something like that?
```php
        /*
         * Only super users can access
         */
        $this->bindEvent('page.beforeDisplay', function() {
            if($this->user == null) {
                 // not logged in
                 return Response::make(View::make('backend::not_authorized'), 401);    
            }

            if (!$this->user->isSuperUser()) {
                  return Response::make(View::make('backend::access_denied'), 403);    
            }            
        });
```

**Comment by LukeTowers** [comment]
I would agree with that @munxar, but it should already be handled in here: https://github.com/octobercms/october/blob/develop/modules/backend/classes/Controller.php#L193-L218

**Comment by LukeTowers** [comment]
Ah, I see. This would be a limited case, I think we should move https://github.com/octobercms/october/blob/develop/modules/backend/classes/Controller.php#L186-L191 below https://github.com/octobercms/october/blob/develop/modules/backend/classes/Controller.php#L193-L218

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/c7a3354dfd5fcad9a435dae0f15db4ace80de4ef. Thanks for the work on this @tim0991 @munxar!
