### ISSUE TITLE
Backend admin jquery error

### ISSUE THREAD

**Issue by simonechinaglia** [octobercms/october#3218]
In a new freash installation, when we try to delete a theme, or plugin, or doing something in the cms tab appear this error on consolle. Anyone get this issues?

```
october-min.js?v419:194 Uncaught TypeError: Cannot read property 'querySelector' of null
    at setParameters (october-min.js?v419:194)
    at window.sweetAlert.window.swal (october-min.js?v419:180)
    at window.sweetAlert.window.swal (october-min.js?v419:537)
    at Object.confirm (october-min.js?v419:525)
    at eval (october-min.js?v419:529)
    at dispatch (jquery.min.js?v419:1)
    at r.handle (jquery.min.js?v419:1)
    at Object.trigger (jquery.min.js?v419:1)
    at n.fn.init.triggerHandler (jquery.min.js?v419:1)
    at Object.handleConfirmMessage (framework.js?v419:47) 
```

Environment: php 7.1 mysql 5.7

**Comment by LukeTowers** [comment]
What browser are you using?

**Comment by simonechinaglia** [comment]
This error is caused when i install october on www.mydomain.com i use the cms on mydomain.com, this avail also for the .htaccess redirect.
so the jquery does not respond, even for the nav bar collapse.

**Comment by LukeTowers** [comment]
? That tells me exactly nothing.

**Comment by simonechinaglia** [comment]
okay, let me explain better. 
1) If i install oct on https://www.mydomain.com and use it on www version: the backend and the frontend works good
2) if i install oct on https://www.mydomain.com and use the backend on https://mydomain.com this cause the errors above. The frontend always works but the back don't.

**Comment by LukeTowers** [comment]
@simonechinaglia what other errors are in the console?

**Comment by simonechinaglia** [comment]
Only js errors, for example sidenavbar in the cms tab collaple automatically, also for unable to add plugin, modals in setting tab. 
I am developing a component for oct and last week i migrated the whole site/db on aws, i think it was the custom lamp but I fixed the error using only one versione of the domain. 
perhaps tåhe procedure to have the issues is not common.

**Comment by LukeTowers** [comment]
Are there any 404 errors or missing scripts from this page?

**Comment by simonechinaglia** [comment]
nono

**Comment by LukeTowers** [comment]
Do you have any sort of weird APP_URL or force scheme or forcing of the root URL setup?

**Comment by maxibanki** [comment]
Same error on my installation. In the coding he can't find the `.sweet-alert` modal.

**Comment by simonechinaglia** [comment]
@LukeTowers  My error was coused by cloudflare integration with double minify action on js.

**Comment by maxibanki** [comment]
Oh nice! 
For future users who have problems with this, create a page rule and disable performance:
![image](https://user-images.githubusercontent.com/17984549/34206482-0054d85e-e587-11e7-9189-d300ed4f6d29.png)

@LukeTowers please close this issue, because he wrote that it is resolved.

**Comment by LukeTowers** [comment]
Perfect, thanks for the update @simonechinaglia & @maxibanki!

**Comment by tiipiik** [comment]
Many thanks @mxschmitt I had similar problems with Cloudflare and it just works, great idea :)
