### ISSUE TITLE
Imbedded images in emails does not work anymore ( > 419 ) when queued

### ISSUE THREAD

**Issue by TimFoerster** [octobercms/october#3222]
##### Expected behavior
Send embedded images in emails queued 

##### Actual behavior
It throws
`Swift_IoException: Unable to open file for reading [FILEPATH] in [...]/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php:131`

##### Reproduce steps
1. Create a html email that contains `<img src="{{ message.embed('storage/app/media/file.jpg') }}">`
2. Create a queued email
3. Go to terminal/console
4. Goto a folder that is NOT the root project folder. (for example parent folder: `cd ..`
5. Execute queue command `/usr/bin/php7.1-cli projectFolder/artisan queue:work --queue=mail --once`
6. Exception: `Swift_IoException: Unable to open file for reading ['storage/app/media/file.jpg'] in [...]/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php:131`

##### October build
426

##### Reason
I guess there is an assumption that the current folder should be the root folder of the project and therefore can't find the file. 

Just for test reasons I added the project root folder name to the file `<img src="{{ message.embed('dev/storage/app/media/file.jpg')` and it worked.

##### Hotfix

Change your crontab entry with `crontab -e`
```
* * * * * cd PATH/TO/PROJECT/ROOT/FOLDER && php7.1-cli artisan queue:work --queue=newsletter --once
```

**Comment by LukeTowers** [comment]
Does it work correctly if you use the [storage_path helper](http://octobercms.com/docs/services/helpers#method-storage-path)?

**Comment by TimFoerster** [comment]
```
Twig_Error_Syntax: Unknown "storage_path" function in "__string_template__1164c2f0fafb09fe448d25addaff32276089144da102c305fd700367dd36967d" at line 29. in .../vendor/twig/twig/lib/Twig/ExpressionParser.php:648
```
`<img src="{{ message.embed(storage_path('storage/app/media/file.jpg')) }}">`

**Comment by LukeTowers** [comment]
Ah, right, that's not a Twig function by default.

**Comment by LukeTowers** [comment]
@TimFoerster How about 
```twig
{% set path = 'storage/app/media/file.jpg' | app %}
{{ message.embed(path) }}
```
http://octobercms.com/docs/markup/filter-app

**Comment by TimFoerster** [comment]
works

**Comment by LukeTowers** [comment]
Would you make any improvements to the documentation to clarify this behaviour or is it fine do you think? http://octobercms.com/docs/services/mail#inline-attachments @TimFoerster

**Comment by TimFoerster** [comment]
I can but not know. Have to sleep. Only 4hours left.

**Comment by cregx** [comment]
The problem persists (or recurs) (October System Build 458). 

I have tried to include an image (jpg, png, svg) in a mail template in the way described here: [ https://octobercms.com/docs/services/mail#mail-templates](https://octobercms.com/docs/services/mail#mail-templates) - unfortunately without success. The error message is the same as the first error message:

> Unable to open file for reading [http://dev-sys:8000/storage/app/media/logo.jpg]" on line 131 of /home/vagrant/ProjectsCode/dev-ctobercms/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php

**Comment by LukeTowers** [comment]
@cregx that's a configuration issue. Since your vagrant server is the one actually trying to fetch http://dev-sys:8000/storage/app/media/logo.jpg, you need to make sure that when the server requests that URL it will be responded to. So you'll need to either make sure that your server is available on port 8000 locally within the vagrant VM and that `dev-sys` is setup to point to 127.0.0.1 in the hosts file on your VM or you need to change that URL to one that the server will be able to request (i.e. just 127.0.0.1) right before it does so. In production this shouldn't be an issue because the URL will be available to the world in general which means that your server will be able to access it just fine.
