### ISSUE TITLE
Backend JQuery Version

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3230]
Hi,

Just a quick question the file found here:

`/modules/backend/assets/js/vendor/jquery.min.js?v427`

I notice the backend is using jQuery Version: v2.1.3

Is there any reason for using V2 as I have been using V3 for almost 2 years now.

Is it a good idea to upgrade it to version 3.2.1 and also add jQuery Migrate 3.0.1 for a Fallback.

Thanks.

p.s. I only noticed as I am writing some code for some plugins.

**Comment by LukeTowers** [comment]
What's the benefits of jQuery 3?

**Comment by ayumihamsaki** [comment]
@LukeTowers 

V3 offers faster speed, better security and more features etc. Plus the Migrate extension should make more plugins compatible allowing a wider range of jQuery to be accepted.

See here (article from 2016): https://www.sitepoint.com/whats-new-jquery-use/

**Comment by LukeTowers** [comment]
@ayumihamsaki If you want to make a pull request adding full support for jQuery 3 to October, that would be reviewed

**Comment by ayumihamsaki** [comment]
@LukeTowers Hi, Have given it a go and updated several files in the back-end and written notes. Please see here for the full Pull Request:

https://github.com/octobercms/october/pull/3238

**Comment by ayumihamsaki** [comment]
Notes: The pull request I added the following two versions:

- jQuery v3.3.1 Latest min version
- jQuery Migrate v3.0.1 Lastest version no proper min version (used for backward compatibility)

**Comment by ayumihamsaki** [comment]
I want to close this (to clean up things) and link it to the following PR: https://github.com/octobercms/october/pull/3886

**Comment by ayumihamsaki** [comment]
I read Luke has said "Issues should stay open until the fix is merged into master" so will reopen this and leave it ref the PR.

- Sorry my bad.

**Comment by CptMeatball** [comment]
On updating one of our projects it seems the `@jquery` alias throws some errors. On first glance it looks like it only includes `jquery migrate`. Will investigate further.

**Comment by LukeTowers** [comment]
@ayumihamsaki it hasn't been merged to master, the release of the build is just a pending build, tagged to develop. We'll go stable next week at which point this stuff will be merged to master.
