### ISSUE TITLE
Added classes to body tag in layout dissappears on window resize

### ISSUE THREAD

**Issue by NMorgana** [octobercms/october#3235]
##### Expected behavior
Classes that have been applied to the body not to vanish on window resize.

##### Actual behavior
The value of class applied to the body in the layout gets removed completely when the window is being resized.

##### Reproduce steps
Apply class to body in layout (example: class="destinations" ) and then resize window.

##### October build
426

**Comment by LukeTowers** [comment]
@NMorgana Where is this happening? Frontend or Backend? What theme are you using if it's the frontend?

**Comment by NMorgana** [comment]
@LukeTowers My mistake! It seem to be a bug in my own script, which I happen to find out about it this morning. I apologize for the false alarm and thank you for the fast response :)  This issue can be closed as nothing is wrong with OctoberCMS itself, great work btw!
