### ISSUE TITLE
Refresh button for file explorer in the CMS tab

### ISSUE THREAD

**Issue by ghost** [octobercms/october#3241]
Hello everybody,

I work with october in an every day basis since some times now, and there is one thing that I always found annoying, when dealing with the CMS tab.

It would be **really** great to be able to refresh files on the left sidebar. I often manually add some files, a jquery plugin, a font or a simple page, but using an external FTP transfert. The only way I have to see that new files in october is to refresh the whole page, but I lose all the opened tabs.

That's why I think it would be really great to have a little refresh button for that sidebar that would scan the new files for the current directory, without losing your current work.

Something like the attached screenshot

![refresh](https://user-images.githubusercontent.com/15909570/32772931-ca369e0e-c927-11e7-8960-578f09b46ab0.PNG)

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by realrandal** [comment]
@Alex360hd I usually use search field to refresh list.
