### ISSUE TITLE
Support helpers.php in plugins

### ISSUE THREAD

**Issue by ibanks** [octobercms/october#3242]
I'm not exactly sure how this is done here. In Laravel it's pretty easy.

**Comment by ibanks** [comment]
I'd like the function to be available throughout the environment without having to create or modify a service container. Just like Laravel's helpers.php file.

**Comment by Telegramsrv** [comment]
Also interested in this question

**Comment by LukeTowers** [comment]
What would an ideal solution look like? You can create and register global aliases fairly easily in October plugins already.

**Comment by ibanks** [comment]
I would imagine that the solution would be similar to the process you use to build the current helpers library. Whatever that process is for helpers like post() for instance. I believe that post() is available in any plugin class as well as the php section of pages/partials/layouts..etc. Correct? So if there is a helpers.php or a class of some sort, when the app is bootstrapped is reads the public functions in the file and goes through the same process as the existing helpers.

**Comment by LukeTowers** [comment]
I would accept a pull request that would support a helpers.php file being supported in plugins, how do you feel about working on that @ibanks?

**Comment by ibanks** [comment]
Cool. I'd be willing to do that. This would actually be my first open source project that I've contributed too as I've always wanted to do that. The only issue with me however is the time (stop me if you haven't heard that before ;-) ). I'd try to get it done as soon as I can.

**Comment by LukeTowers** [comment]
@ibanks glad to hear it! Yeah, I hear you on the time, I say it to myself every day. No worries, get it done whenever you have time. I'll leave this issue open as reference.
