### ISSUE TITLE
Backend Log In - ErrorException

### ISSUE THREAD

**Issue by pedrojuntadigital** [octobercms/october#3244]
I have an October instance deployed in a Windows Server 2016 and IIS. It is a auction webapp with lots of images. Every time a backend end user logs in a set of execptions occurs ex:

30700 | Today at 1:10 PM | Symfony\Component\Debug\Exception\FatalErrorException: Uncaught ErrorException: file_put_contents(C:... |  
-- | -- | -- | --
Check | 30699 | Today at 1:10 PM | ErrorException: file_put_contents(C:\inetpub\wwwroot\leilosoc\storage\framework/cache/ec/91/ec912e4b... |  
Check | 30698 | Today at 1:10 PM | ErrorException: file_put_contents(C:\inetpub\wwwroot\leilosoc\storage\framework/cache/ec/91/ec912e4b... |  
Check | 30697 | Today at 1:10 PM | ErrorException: file_put_contents(C:\inetpub\wwwroot\leilosoc\storage\framework/cache/50/bb/50bb2e89...

All related to the cache system. The problem is that after a while the application loses access to  the base files and the server returns an error 500.
ex:

30596 | Today at 12:45 PM | Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Cms5a0c365f00cc3706878485_eadf5309aa3e... |  
-- | -- | -- | --
Check | 30595 | Today at 12:45 PM | Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Cms5a0c365f00cc3706878485_eadf5309aa3e... |  
Check | 30594 | Today at 12:45 PM | Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Cms5a0c363c960c5074005822_d9442079d5d0... |  
Check | 30593 | Today at 12:45 PM | Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Cms5a0c3630c2a85462148597_e1a1912e3293... |  
Check | 30592 | Today at 12:45 PM | Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Cms5a0c3630c2a85462148597_e1a1912e3293... |  
Check | 30591 | Today at 12:45 PM | Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Cms5a0c365f00cc3706878485_eadf5309aa3e... |  
Check | 30590 | Today at 12:45 PM | Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Cms5a0c3630c2a85462148597_e1a1912e3293... |  
Check | 30589 | Today at 12:44 PM | Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Cms5a0c3630c2a85462148597_e1a1912e3293... |  
Check | 30588 | Today at 12:44 PM | Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Cms5a0c3630c2a85462148597_e1a1912e3293... |  
Check | 30587 | Today at 12:44 PM | Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Cms5a0c3630c2a85462148597_e1a1912e3293... |  
Check | 30586 | Today at 12:44 PM | Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Cms5a0c3630c2a85462148597_e1a1912e3293...

The only way to solve the problem is to reset the IIS with iisreset.

Any suggestions what might be?

##### Expected behavior
(Describe expected behavior here)

##### Actual behavior
(Describe actual behavior here)

##### Reproduce steps
(Describe the steps to reproduce the problem here)
Log in to backend;

After multiple log ins the server crashes returning error 500

##### October build
(October build number)
421
using PHP 7.0 for windows

**Comment by Samuell1** [comment]
This should be fixed by this PR https://github.com/octobercms/october/pull/4266

**Comment by w20k** [comment]
If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
