### ISSUE TITLE
How to regenerate keys on a shared server. "The only supported ciphers are..."

### ISSUE THREAD

**Issue by bkrajendra** [octobercms/october#3245]
I'm trying to update to latest update 428
Getting this error while update processes.
```
The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.
```

Now Im on shared server and dont have access to SSH to renew keys. what to do?

**Comment by LukeTowers** [comment]
See http://octobercms.com/support/article/rn-5. Also, make sure that you've followed all of the instructions in http://octobercms.com/support/article/rn-9

**Comment by bkrajendra** [comment]
Sometime little negligence and tiny wrong info can make things really difficult.
I was stuck on this issue from last 5 days...
tried all solutions but nothing was working. 

every one mention about changing key but i did not paid attention to number of exact character required in key value.

Also tried copying exact code from http://octobercms.com/support/article/rn-5
But it did not work. Then finally thought of actually counting exact characters in this code and found that
'key' => 'CHANGE_ME!!!!!!!!!!!!!!!!!!!!!!', has one less character in it - only 31 :) 
Just added one extra and everything started working..

```
'key' => 'CHANGE_ME!!!!!!!!!!!!!!!!!!!!!!!',

'cipher' => 'AES-256-CBC',

```

**Comment by bkrajendra** [comment]
Thank You @LukeTowers !

**Comment by LukeTowers** [comment]
@bkrajendra ... Please don't use the key from the article, use `php artisan key:generate` to regenerate a secure key. If you use the key from the article, then it is a known key and your encryption is rendered useless.

**Comment by bkrajendra** [comment]
I understand that @LukeTowers . 
My issue was I'm on shared sever, and not able to perform any SSH command.
On top of that i was not knowing exact source of error as using exact same code from article was also not solving it.

Although I was just doing copy past only to get my backend working. There was no intention to use same key.

This could have solved earlier if I could have used my own 32 bit string there.!

**Comment by LukeTowers** [comment]
@bkrajendra you can always generate the key locally and then copy it over. My guess is the example key is purposely broken to prevent people from using it.

**Comment by bennothommo** [comment]
Closing as answered.
