### ISSUE TITLE
No Explanation In Docs On What The "Order" Key Is In Plugin Permissions 

### ISSUE THREAD

**Issue by ibanks** [octobercms/october#3247]
Unless I missed something, I do not see any explanation on what the **order** key and it's values mean when setting plugin permissions. I apologize in advance if I am wrong, but I did a string search the word in the permissions and plugin sections of the docs and did not see anything.

```
        'blog' => [
            'label'       => 'Blog',
            'url'         => Backend::url('acme/blog/posts'),
            'icon'        => 'icon-pencil',
            'permissions' => ['acme.blog.*'],
            'order'       => 500,
```

**Comment by LukeTowers** [comment]
The order value is used to assign the menu item's order in the overall navigation menu. Higher numbers mean that the item will be later on in the order of menu items, lower numbers mean that it will be earlier on in the order of menu items. Feel free to make a PR to the [docs repository](https://github.com/octobercms/docs) to document that.

**Comment by ibanks** [comment]
I will get that done soon. Thank you.
