### ISSUE TITLE
[Question] Prod & Dev environments for multiple hosts

### ISSUE THREAD

**Issue by rajakhoury** [octobercms/october#3248]
Not sure I understand correctly how this works in the new Multitenancy, but assuming i want to run the same October installation on my domain and sub-domain, where each host will have a different theme, mail config ect.. 

	'default' => 'dev', 

	'hosts' => [
		'mydomain.com'       =>  'site',
		'sub.mydomain.com'   =>  'app',
	],

I can create two folders named site & app under config/** and add the config files there, no problems so far. 

What I can't get is how to setup a Dev & Prod environment for each host ? Is this possible ?

##### October build
428

**Comment by rajakhoury** [comment]
I think I made it work. I didn't know we could use sub directories in config `ENV\HOST\***`

here's the setup : 

 in **environment.php**

    'default' => 'prod/site' ,

    'hosts' => [

      // Development
      'app.domain.local'    => 'dev/app',
      'domain.local'        => 'dev/site',

      // Production
      'app.domain.com'    => 'prod/app',
      'domain.com'        => 'prod/site',
    ],

Config folder 

    config/
      - dev 
        - app
          - cms.php
          ...
        - site
      - prod
        - app
        - site
    environment.php

All good so far except this issue #3250 ( delete active theme record from db )

Any advise on the above setup is appreciated.

**Comment by LukeTowers** [comment]
Seems fine, is there any changes that you can think of making to the documentation to improve other people's experiences with a similar setup in the future?

**Comment by rajakhoury** [comment]
maybe adding a similar setup example could help new developers. I guess this is more me not understanding well how Laravel works. My first experience with Laravel was through October and not the other way around. 

[Reference S.O](https://stackoverflow.com/questions/17532449/how-to-get-config-data-in-laravel-in-a-subfolder)

**Comment by LukeTowers** [comment]
@rajakhoury if you can think of a good example to put in the documentation and make a PR to the docs repository that would be great!

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
