### ISSUE TITLE
Autoloader for PHPUnit fails after updating to build 420

### ISSUE THREAD

**Issue by HugoWijdeveld** [octobercms/october#3249]
##### Expected behavior
I expect my phpunit test to pass. It did while I was still working in build 419.

##### Actual behavior
PHPUnit throws an error saying "Using $this when not in object context in '[..]\vendor\october\rain\src\Support\ClassLoader.php:144'".

##### Reproduce steps
I updated from build 419 to build 420, then ran my tests.
I have found that the ClassLoader in build 419 had many static functions and properties. The file tests/bootstrap.php still calls the methods statically. When I uncomment the register() and addDirectories methods, this particular phpunit error disappears.

##### October build
Currently using 428

**Comment by HugoWijdeveld** [comment]
I pulled the 'tests' folder the git repository and replaced the existing folder on my system with it. Problem appears to be solved now. Still wondering why this wasn't done during the update.

**Comment by LukeTowers** [comment]
@HugoWijdeveld if you update via the web interface then you aren't receiving the developer version of October, you are receiving the consumer build which does not include the tests directory, `composer.json`, or `server.php`. To receive the developer version, update via composer instead.

**Comment by HugoWijdeveld** [comment]
@LukeTowers thanks for pointing that out; I never realized that.
