### ISSUE TITLE
Backend Theme settings overrides the multiple hosts theme setting

### ISSUE THREAD

**Issue by rajakhoury** [octobercms/october#3250]
##### Expected behavior
Load correct host theme regardless of backend settings

##### Actual behavior
Loads theme set as active in backend and ignores the theme settings for each host

##### Reproduce steps
1) Set your hosts (  `environment.php` )

 		'hosts' => [
			'mydomain.com'       =>  'site',
			'sub.domain.com'   =>  'app',
		],

2) in Config Directory create a site & app folders
3) In **config/site/cms** >> `  'activeTheme' => 'theme-a'
4) In **config/app/cms** >> 'activeTheme' => 'theme-b',
5) Backend Settings >> Themes >> Activate  Theme A
 
Now, regardless of which host domain.com or sub.domain.com, Theme A will load .

If I open the `system_parameters` DB table I can see the cms active theme is "theme-a".
If I delete this record then navigating to domain.com or sub.domain.com will load the correct theme.

As stated in `cms.php` 

> This parameter value can be overridden by the CMS back-end settings.

Does this mean in case we need to have the above setup we should make sure to manually delete the db record ?

##### October build
428

**Comment by LukeTowers** [comment]
@rajakhoury Yes, you would need to delete the DB record for the active theme if you want to use the config files for multiple hosts using the same DB. Can you think of a better way to structure it that retains current functionality and provides better support for multi-site setups?

**Comment by rajakhoury** [comment]
@LukeTowers Thank you Luke.  

What is the difference between a Host & Environment in October ? To my understanding a Host or Site can have multiple environments / configs ( testing, dev .. ) but as I see here the Host can only have one, right ?

Is this feature aimed to create multi sties or just force a predefined environment for a host ?

**Comment by bennothommo** [comment]
Closing as answered.
