### ISSUE TITLE
PHP Unit route testing receiving unexpected response after upgrade to build 420

### ISSUE THREAD

**Issue by HugoWijdeveld** [octobercms/october#3254]
##### Expected behavior
I expect my phpunit route test to return a 200 response

##### Actual behavior
It returns a 404 response when testing, but gives the expected response when using the browser to make the request. 

##### Reproduce steps
I run my tests without changing any settings in 'config/testing/cms.php'.

My test in build 419 looked like this:

    class RouteTest extends PluginTestCase {

        protected $baseUrl = "/";
    
        public function setUp() {
            parent::setUp();
            include plugins_path('hugowijdeveld/mollie/routes.php');
        }

        public function tearDown() {
            parent::tearDown();
        }
    
        /** @test */
        public function test_route_and_return_ok_response(){
            $this->call('GET', '/test-route');
            $this->assertResponseOk();
        }
    }

I left the file 'routes.php' in the plugin untouched, but I had to rewrite the test slightly on account of Laravel 5.5:

    /** @test */
    public function test_route_and_return_ok_response(){

        $response = $this->get('/test-route');

        $response->assertStatus(200);
    }

While using build 419, the test passed. Now the test fails (404).

I tried to run the test using the baseUrl ($this->get('/')), but that also resulted in a 404.

##### October build
428

**Comment by HugoWijdeveld** [comment]
@LukeTowers thanks for your quick reply! 
[composer.json.txt](https://github.com/octobercms/october/files/1495026/composer.json.txt)

first I updated through the backend. After you explained to me that this would not update the developer version, I ran

    composer:update

and

    php artisan october:update

in the terminal.
I am quite positive that my '/tests' directory (the one inside the root folder) is up to date. I compared it to the one on github. Running 'php artisan october:update' again gives me feedback: 'No new updates found'.

In my plugin routes.php I use:
    Route::get('/test-route', ['as' => 'testRoute', 'uses' => 'HugoWijdeveld\Mollie\Controllers\PaymentController@test']);

I tried PHPUnit 5.7 and 6.4 but both failed with the same notifications.

I don't know if it can be any help, but I attached my comopsoer.json file anyway.

**Comment by LukeTowers** [comment]
Hmm, I seem to recall someone else having problems like this before, try searching the issues list for similar issue. As a side note, you shouldn't be changing your composer.json file away from the default one used by this repository. Read https://luketowers.ca/blog/how-to-use-laravel-packages-in-october-cms-plugins/ for including additional dependencies in your OctoberCMS project by using the plugin's composer.json files.

**Comment by HugoWijdeveld** [comment]
@LukeTowers:  I'll make sure to implement your tips on user composer.json files in my plugins. Meanwhile I found one possible solution to my problem.
I'm using an .env-file to store settings. It appears to be the 'APP_URL' that may have caused the problem. It was set to 'http://localhost/public_html', which worked fine in build419.
Now when I change this to 'http://localhost' my tests run fine in build 428. The location of the projectfolder on the drive has NOT been changed though. (I stumbled on this detail because I tried to simulate the problem with a fresh install of October and I happened to notice this difference.)

Could you please tell me if changing the 'APP_URL' is likely to give me problems elsewhere in the cms?

**Comment by LukeTowers** [comment]
It shouldn't, but double check the URLs that get generated on the frontend and check for any console errors in the front or backends.
