### ISSUE TITLE
Datepicker field format selection doesn’t work correctly

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [octobercms/october#3258]
##### Expected behavior
When a form field of datepicker is specified the format identifier it has to be able to allow formatting the time and date separately since it's two fields rather than one. So ideally there should be a dateFormat and timeFormat config fields.

##### Actual behavior
The datepicker allows only a single format field which formats the first field i.e. the date field only.

##### Reproduce steps
1. Create a form with a field of type datepicker and specify the format at `format: j/m/Y h:i A`
2. Now select a date from the form. See that only the first field is rendered with the format specifier.

##### October build
419
<img width="450" alt="october-bug" src="https://user-images.githubusercontent.com/1699753/33130205-8c1fc3c4-cfb8-11e7-9a85-e609cc6803ae.png">

**Comment by LukeTowers** [comment]
@SaifurRahmanMohsin is this issue still present in Build 428?

**Comment by SaifurRahmanMohsin** [comment]
Yep. It does.

**Comment by LukeTowers** [comment]
Could you make a PR to fix this issue?
