### ISSUE TITLE
Outdated validation translation messages

### ISSUE THREAD

**Issue by ametad** [octobercms/october#3259]
##### Expected behavior
Validation message in human language.

##### Actual behavior
Some error messages are not available and therefore the identifier key is shown. Per example:
Validor: file
Upon an invalid file (upload fail) the message shown: "validation.uploaded"

##### Reproduce steps
Set up an controller that expects form post that is validated with:

```
        $validator = Validator::make([
            'cv' => request('cv'),
        ], [
            'cv' => 'file',
        ]);

        if ($validator->fails()) {
            throw new ValidationException($validator);
        }
```
Then upload a file that is greater then set as 'upload_max_file' in php ini config.

The validation fails and is returning a translated message "validation.uploaded". 

The problem is that an outdated translation file of validations is used in OC:
october/modules/system/lang/en/validation.php

Laravel 5.5 has a newer version:
https://github.com/laravel/laravel/blob/593963979a6b6a27966aef9723b8ff08fb480b87/resources/lang/en/validation.php#L88

##### October build
428

**Comment by LukeTowers** [comment]
Feel free to make a Pull Request adding the required information.

**Comment by ametad** [comment]
Merged!
