### ISSUE TITLE
Repeater : Trigger action doesn't work with fields outside the repeater

### ISSUE THREAD

**Issue by Alex360hd** [octobercms/october#3260]
Firstly, I want to say that the issue is not a duplicate [with this one](https://github.com/octobercms/october/issues/2715) as the linked one talk about trigger events between fields **inside** the same repeater.

##### Actual behavior

It seems that fields inside the repeater are not "aware" of the fields outside the repeater in order to create some trigger events.

##### Expected behavior

Fields, even inside the repeater should be "aware" of all the fields in your form, not only the one in the same repeater.

##### Reproduce steps

* Create a field outside the repeater (for example : a checkbox)
* Create a repeater fields with some fields on it
* Create a trigger event for one of the field in your repeater that hide (or do something else) the field depending on the field outside the repeater.
* Test and see that it doesn't work

##### October build
428

**Comment by LukeTowers** [comment]
Please post your code with the issue present. It would be helpful if you create a PR to the [test plugin](https://github.com/daftspunk/oc-test-plugin) demonstrating the issue.

**Comment by Alex360hd** [comment]
Hello,

I starting with git and don't know how it works exactly with forks, pull requests, patch etc... But it's very easy to test as I touch just one file.

I modified the models/person/fields.yaml to add a repeater field, in that repeater there is one field that should be hidden when the "Married" field (just above) value is "Yes".

Here is my fields.yaml to put under models/person/fields.yaml

[fields.zip](https://github.com/octobercms/october/files/1499761/fields.zip)

**Comment by LukeTowers** [comment]
@Alex360hd support added in #3465

**Comment by Alex360hd** [comment]
Excellent ! I assume you forgot to close the issue so I do it. Don't hesitate to reopen if necessary.

**Comment by LukeTowers** [comment]
@Alex360hd When a commit is added that "Fixes #numberOfIssue", GitHub auto closes the related issue when the commit makes it to master, and the tag "Status: Completed" is used to indicate the issue is solved, but not necessarily in master. Hence why I didn't close it immediately. I don't really care one way or the other if a completed issue is closed before making it to master, but that's the way @daftspunk typically does it so I do it as well.
