### ISSUE TITLE
BUILD420 issue: Extended models in relation with pivot fields contain extended fields

### ISSUE THREAD

**Issue by flyingbaba** [octobercms/october#3265]
##### Expected behavior
It was ok before to use an 

```
        self::extend(
            function ($model) {
                $model->implement[] = '@Renatio.SeoManager.Behaviors.SeoModel';
            }
        );
```

on a model and later to have a relation to this model with pivot fields. These extended fields were rendered in a forms models controller not from another models relation. Now together with pivot fields I have a extended fields. How to get rid of them ? 

##### October build
420 and greatere

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by flyingbaba** [comment]
Oh.. I'll try to do this but it will take some time. I was actualy thinking of having something like this before I extend the model: 

    `public static function boot()
    {
        parent::boot();

        if ( !$this->model->CalledFromRelationController ) {
            self::extend(
                function ($model) {
                    $model->implement[] = 'RainLab.Translate.Behaviors.TranslatableModel';
                }
            );
        }
        }`

If it is possible ?

**Comment by flyingbaba** [comment]
https://github.com/daftspunk/oc-test-plugin/issues/47

**Comment by flyingbaba** [comment]
Actualy the pivot data is saved normaly. It is just that seo fields are rendered in the Pivots form. If I leave these fields empty the record is saved, but if I enter some values there then it fails to save record.

**Comment by LukeTowers** [comment]
@flyingbaba how are the SEO fields added?

**Comment by flyingbaba** [comment]
@LukeTowers  `self::extend` extends model, so I guess in renatio/seomanager/classes/seoFields.php we have this function: 

    protected function seoFields()
    {
        $fields = Yaml::parseFile(base_path('plugins/renatio/seomanager/models/seotag/fields.yaml'));

        return Event::fire('seo.extendSeoFields', [$fields], true) ?: $fields;
    }

**Comment by flyingbaba** [comment]
@LukeTowers @daftspunk Please close this issue, it was an error in Renatio.SeoManager model extension. New update is released and it is all fine now.
