### ISSUE TITLE
Undefined language code

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#3267]
When I updated the October 419 to 428, the system use the following undefined language code: system::lang.updates.core_set_build

File:
/modules/system/controllers/Updates.php Line: 611

Screenshot:
![missing-lang-issue](https://user-images.githubusercontent.com/2959112/33311999-d26ed17c-d426-11e7-8670-d5bfc10b462b.jpg)

**Comment by LukeTowers** [comment]
It was added here: https://github.com/octobercms/october/commit/1a365b10b7c7d8e6dcef9e6159969bd3b6a6f230#diff-c30778339ad465dad3ebdbc81b8fd8eb
And then the removal slipped through here: https://github.com/octobercms/october/commit/969eaccf8b8652d904e11f388192d18e583b3402#diff-b728303b9aa353d7f520002ea916771f

A PR to fix that would be merged.
