### ISSUE TITLE
Translatable Content Blocks

### ISSUE THREAD

**Issue by matteodem** [octobercms/october#327]
Didn't see any possible way to translate content blocks? Since it's only pure html without any dynamic variables, I didn't find any solution to this.

Also, are there any use-cases in a multi lingual website for content blocks? Makes not a lot of sense to me as of now.

**Comment by bbrandtlv** [comment]
Getting content file not found. 
Should I add locale somehow?
Thanks

**Comment by daftspunk** [comment]
https://youtu.be/pDr3KAvZY44
