### ISSUE TITLE
Non super users cannot set permission back to inherit

### ISSUE THREAD

**Issue by stevemortimer** [octobercms/october#3274]
##### Expected behavior
I'm encountering a potential issue with PermissionEditor.php's getSaveValueSecure method. When you create a user that is not a super user but give them the ability to manage other administrators they are unable to change user level permissions from "allow" back to "inherit." 

https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/PermissionEditor.php#L106	

Because of line 106, it will automatically exclude any permissions that are being set back to the inherit value of 0. I assume this is an unintended consequence and was instead meant to exclude any permissions that had not changed. Should a non-super user with the "manage other administrators" permission be able to do this?

##### Reproduce steps
- Fresh composer install
- Log into backend as the admin user and create 2 users.
- The first user should be a manager. Give the manager the ability to manage other administrators.
- The second user should just be a plain old user.
- Sign out and sign back in as the manager user.
- Edit user #2 and assign a random permission, such as "manage mail settings." Save the user and reload. Permission is now set to allow. 
- Change "allow" to "inherit" on the user. Permission doesn't save. You cannot set a permission back to inherit, you can only allow or deny.

##### October build
428

**Comment by LukeTowers** [comment]
See http ://github.com/octobercms/october/commit/950c341c49c0462eb2fe8db4d5d75556315f079f#r23022665. I'm fine with removing that line as long as it actually works to set the permissions back to inherit.

**Comment by stevemortimer** [comment]
I'll confirm that and see if I can put together a PR this week

**Comment by LukeTowers** [comment]
Awesome, thanks @stevemortimer

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/7c20e32c47d8c692d670009971bf127740eea291
