### ISSUE TITLE
PHP 7.2.0 each() deprecation

### ISSUE THREAD

**Issue by cory-seatsmart** [octobercms/october#3279]
##### Expected behavior
SCSS Compiles

##### Actual behavior
SCSS compiler gives error: `/* The each() function is deprecated. This message will be suppressed on further calls */`. Even though it claims that the error will be suppressed, it does not disappear after multiple page refreshes.

##### Reproduce steps
- Upgrade server PHP to 7.2.0
- Load a page that uses October's built in SCSS compilation

##### October build
419

Unsure if this has to do with October itself or the SCSS compiler. Close if this is not an October core issue

**Comment by justinbeatz** [comment]
If you upgrade the php version of your server to 7, you must upgrade October to 420+ (right now the build is in 428 I think), check this post about the changes of OctoberCMS with php7:

[Build 420 - Foundation framework upgrade (Laravel 5.5 LTS)](http://octobercms.com/support/article/rn-9)

**Comment by viamage** [comment]
@cory-seatsmart did upgrade help you? If so you can close the issue I guess.
