### ISSUE TITLE
make Search Widget

### ISSUE THREAD

**Issue by immeyti** [octobercms/october#3284]
hi.
i need add search to modules\backend\behaviors\relationcontroller\partials_manage_list.htm
because i have 3000 record, can u help me?
thank you.

**Comment by canthis** [comment]
@immeyti You should not touch october system files. Just follow documentation on [configuring relation behavior](https://octobercms.com/docs/backend/relations#configuring-relation) and use **showSearch** option.

**Comment by LukeTowers** [comment]
Thanks @canthis!

**Comment by immeyti** [comment]
i want add searching in accessories jkshop. but i cant do it.
can u help me?
tank you.

**Comment by LukeTowers** [comment]
@immeyti try contacting the plugin author.
