### ISSUE TITLE
Redirect to https

### ISSUE THREAD

**Issue by vitormicillo** [octobercms/october#3286]
##### Expected behavior
Hi, I do not know if anyone here has had the same problem,
but after performing the installation of the system when accessing the administrative area it redirects the protocol http to https.
I'm testing on a local virtual machine, this redirect does not allow me to use admin

##### October build
Not sure, but it was the last version installed with the composer

**Comment by LukeTowers** [comment]
Check your config/cms.php. If backendForceSecure is true, then that is the problem. If it is null, and config/app.php has debug = false, then backendForceSecure is true.

**Comment by vitormicillo** [comment]
thank you very much @LukeTowers , it was like null i changed it to false
