### ISSUE TITLE
Can't install with message 'Application In Production'

### ISSUE THREAD

**Issue by hackoh** [octobercms/october#3287]
My command was
```composer create-project october/october .```

and got message
```
> php artisan october:util set build
-
No database detected - skipping setting the build number.
> php artisan october:util set build
-
No database detected - skipping setting the build number.
> php artisan key:generate
**************************************
*     Application In Production!     *
**************************************

Command Cancelled!
```

in homestead.

**Comment by LukeTowers** [comment]
Set debug = false in config/app.php and then run php artisan key:generate

**Comment by osmanzeki** [comment]
Had the same problem when creating a brand new project via Composer. It seems like the application config is in production by default which stops the automated "after create-project" commands to fail.

**Comment by LukeTowers** [comment]
@osmanzeki that's odd because https://github.com/octobercms/october/blob/master/config/app.php#L19 is set to true, so it shouldn't be. Could you look deeper into the issue and see if you can find out why that is?

**Comment by osmanzeki** [comment]
@LukeTowers I believe this line here is the culprit. I had to change it to 'development' in order for the `artisan key:generate` command to work.

https://github.com/octobercms/october/blob/master/config/environment.php#L16

**Comment by LukeTowers** [comment]
@osmanzeki could you make a PR with the summary of the issue to fix it?

**Comment by osmanzeki** [comment]
Done. :)
