### ISSUE TITLE
Question: How to add / bind Search to a custom List in Backend

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3290]
Hi,

Have gone through github, stackoverflow and october etc. looking for the solution. So after a few hours have decided to ask the question here (sorry I know you guys are very busy!)

Been trying to learn how to create custom Lists with Controllers. From the Tutorial found here: https://octobercms.com/support/article/ob-20

I have everything working in a custom List, all the fields, can adjust the columns, can add and delete new form data etc.

But the problem I am getting is trying to connect up the search box to a custom List.

The code I got is as follows:

In the index.htm file:

```
<!-- Search Form -->
  <div class="toolbar-item" data-calculate-width>
    <div class="loading-indicator-container size-input-text">
      	<input placeholder="Search..." type="text" name="listToolbarSearch[term]" value="" data-request="listToolbarSearch::onSubmit" data-track-input data-load-indicator data-load-indicator-opaque class="form-control icon search growable" autocomplete="off" />
    </div>
  </div>
```

In the columns.yaml file:

```
toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
```

The error I am getting is: **"A widget with class name 'listToolbarSearch' has not been bound to the controller"**

I have `$index->bindToController();` in the controller php file.

I am guessing I need some extra code...? 

Also there is a Q&A here: https://stackoverflow.com/questions/41999002/custom-html-for-the-search-box-used-by-the-listcontroller-behavior

When I try that way I get an error message saying: **"AJAX handler 'onMyHandler' was not found."**

Look forward to any replies, just want to learn the best way to setup a search box in a custom List.

Thanks.

**Comment by LukeTowers** [comment]
When in doubt, read how october does it: https://github.com/octobercms/october/blob/master/modules/backend/behaviors/ListController.php#L197 :)

**Comment by ayumihamsaki** [comment]
Perfect thanks
