### ISSUE TITLE
Backend-relation

### ISSUE THREAD

**Issue by immeyti** [octobercms/october#3294]
Hi
I'm extending  jkplugin in this way: Extending the User plugin
I'm using the fields with relation type now. It's Ok and i have no problem with it.
plugin.php: 
'book[writer]' => [
                        'label'         => 'Writer',
                        'type'          => 'relation',
                        'nameFrom'      => 'name',
                        'tab'           => 'Books',
                        'span'          => 'auto'
]
But i don't know how to use back-end relation? I did it according to this video and 
plugin.php (new):
'book[seller]' => [
                        'label'         => 'seller',
                        'type'          => 'partial',
                        'path'          => '$/dpco/jkplus/controllers/books/_field_seller.htm',
                        'tab'           => 'Books',
                        'span'          => 'auto'
 ],
in _field_seller.htm file  ==> <?= $this->relationRender('seller') ?>
  
bu i got this error: Relation behavior does not contain a definition for 'seller'.

**Comment by SebastiaanKloos** [comment]
@immeyti Please take a look at the documentation. I think this will may help you.

http://octobercms.com/docs/backend/relations

**Comment by immeyti** [comment]
@SebastiaanKloos Maybe its better to ask my Question in this way
I have 3 Model
Product (jkshop plugin)
Book (my plugin)
Seller (my plugin)
Product hasOne Book
Book belongsToMany Seller
how to use Backend-Relation in Product model for submit a book with Seller relation??

**Comment by LukeTowers** [comment]
@immeyti we aren't going to write your code for you. You need to do several things in order for that to work:
1. Setup the relations in your models
2. Setup the inverse of the relations in the third party plugin's models by extending them dynamically http://octobercms.com/docs/database/model#extending-models
3. Extend the third party plugin's Product form fields to include the field that will render the relationController instance http://octobercms.com/docs/backend/forms#extend-form-fields
4. Extend the third party plugin's Products controller to add a configuration for the relationship that you setup earlier in the models
