### ISSUE TITLE
Question: Disable responsivnes, for specific custom backend page.

### ISSUE THREAD

**Issue by roulendz** [octobercms/october#3295]
##### Expected behavior
Way to disable responsive to specific backend page (custom plugin)
Just to be able to zoom in and zoom out for the page.

##### Actual behavior
I want to be able to zoom in zoom out on the specific custom plugin page.

*Any idea and help would be appreciated!*
##### Reproduce steps
Open admin panel inside a phone or emulate on chrome, and try to zoom in and zoom out with CTRL + Scroll wheel.

##### October build
430

**Comment by LukeTowers** [comment]
I'm not aware of that shortcut working on any other site, it's always been CTRL + or CTRL -, which works fine for me

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
