### ISSUE TITLE
Editing CMS/Assets files on PHONE almost every key stroke deletes previos letter.

### ISSUE THREAD

**Issue by roulendz** [octobercms/october#3297]
##### Expected behavior
On phone when editing file, I except that when I type, text writes and works :D See video, hard to explain

##### Actual behavior

When I type on phone in CMS section -> assets it on almost every key press deletes the previous character and it is impossible to edit some minor things on phone
https://www.youtube.com/watch?v=SIpZopkbVaI

##### Reproduce steps
Open backend panel on a phone and try to edit some .js file in the assets folder. And at least for me almost every key press deletes a previos character.

##### October build
430

**Comment by LukeTowers** [comment]
Have you tried checking the issues for the Code editor that we use?

**Comment by w20k** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
