### ISSUE TITLE
[Market] Connect to private GitHub repos owned by a GitHub organization

### ISSUE THREAD

**Issue by ChVuagniaux** [octobercms/october#3299]
The current behavior (adding user `octoberapp` as a contributor of the repo) work well when the repo is owned by a GitHub user but for organization repos there is an extra cost for each added users. We would be very grateful if we can be avoid this extra cost ;)

There is a way to use GitHub Deploy Keys ? (seems me the more appropriate) instead of adding the `octoberapp` user to the repos.

I don't know how the market build process work. But normally deploy Keys are easy to implement, you only need to generate a SSH key pair with the Linux user you use for build plugins and share the public key. Now when you will try to clone a repo git will automatically try to use the key.

**Comment by LucasZdv** [comment]
I could solve this by creating a user to publish my plugins and use the login via url. https://user:pass@github.com/user/repo.git

**Comment by lunfel** [comment]
As for myself, the `octoberapp` as contributor did not work (I just opened an [issue](https://github.com/octobercms/october/issues/3541) on that).

But I think that this approach with deploy keys would be a more robust way of handling private repositories. Deploy keys also only let's you have read access to the repository. For the collaborator, you have to lower the access rights after the user has accepted the invitation I think.

I would really like to have private repositories working (either with collaborator or deploy keys). I would like to help you guys out fixing this, but this code to build plugins seems to be closed source. Is there anything I could do to help fix this issue.

**Comment by daftspunk** [comment]
There is a seemingly little known feature about GitHub in that you can see just about anyone's public keys, including the `octoberapp` account, simply tack on `.keys` to the end of their profile page:

- https://github.com/octoberapp.keys

Now that you have the accounts public key, you can create a Deploy Key and give it permission to see your repo. So it would seem there are no real changes required to make this work.

Let us know how you go with this.

**Comment by ChVuagniaux** [comment]
Sadly this not works : I get **Key is already in use** when adding the key to my repo. 

I discovered that GitHub deploy keys are only allowed to be used on one repository :'(

>Once a key has been attached to one repository as a deploy key, it cannot be used on another repository. If you're running into this error while setting up deploy keys, see "[Managing deploy keys](https://developer.github.com/guides/managing-deploy-keys)" in the GitHub Developer documentation.
>*https://help.github.com/en/github/authenticating-to-github/error-key-already-in-use#deploy-keys*

>Deploy keys only grant access to a single repository. More complex projects may have many repositories to pull to the same server.
> *https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys*

**Comment by SebastiaanKloos** [comment]
@ChVuagniaux thats right. I experienced the same

**Comment by daftspunk** [comment]
> Sadly this not works : I get Key is already in use when adding the key to my repo.

This sucks, I know. The system was built, then the ecosystem changed around it! Adding the user is a good workaround for the time being. The invitations should be accepted automatically now

Anyhow, this overall issue will be addressed in the next website update. Thanks for your patience with it. Stay tuned
