### ISSUE TITLE
CMS sidebar buttons are not working

### ISSUE THREAD

**Issue by maxibanki** [octobercms/october#3300]
##### Expected behavior

Buttons with links are working

##### Actual behavior

Nothing happens

##### Reproduce steps

Click on a Button.

##### October build

430

![image](https://user-images.githubusercontent.com/17984549/33994532-227a6c6a-e0db-11e7-9f05-14aadebda748.png)

the href of the am element is only `javascript:;`.

**Comment by LukeTowers** [comment]
Did you check the JS console?

**Comment by maxibanki** [comment]
Empty.

I'm also sure, that this is no caching issue. Because I have Cloudflare and they are really annoying with caching. (Chrome Cache and October Cache also disabled / cleared).

**Comment by LukeTowers** [comment]
What do you mean by
>verbose `Violation` messages
?

**Comment by maxibanki** [comment]
![image](https://user-images.githubusercontent.com/17984549/34014463-7944a020-e11b-11e7-8138-c315323a9881.png)

**Comment by LukeTowers** [comment]
What messages appear in the console when the rocket loader is disabled?

**Comment by maxibanki** [comment]
![chrome_2017-12-15_08-22-13](https://user-images.githubusercontent.com/17984549/34031349-2e614580-e171-11e7-863e-b5d6d5a737e0.png)
I don't think that Rocket Loader is the issue, because I've been activating it for the past few months without any problems.

**Comment by LukeTowers** [comment]
Does the browser make any network requests when you click on the menu items?

**Comment by maxibanki** [comment]
Nope

**Comment by LukeTowers** [comment]
Has framework.js loaded? Are there data-request attributes specified on the menu items?

**Comment by maxibanki** [comment]
Nope, there aren't data-request attributes there:
![image](https://user-images.githubusercontent.com/17984549/34070382-93eee732-e265-11e7-8d76-8762f7e379c0.png)

(Also in my plugin the controller the deletion of a data set is not working)

**Comment by maxibanki** [comment]
Solved as described in #3218.
