### ISSUE TITLE
Delete Pivot table rows programmatically

### ISSUE THREAD

**Issue by HekmatFavid** [octobercms/october#3303]
I have Users ,Products and Carts pivot table with user_id ,product_id columns.
i want programmatically delete  product_id by desire user_id and use following command:
```
           $cart = Cart::where('product_id', '=' , post('id'))
                              ->where('user_id' , '=' , Auth::getUser()->id)->first();
           $cart->delete();
           $cart->save();
```
this error message appear :
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: delete from `hb_products_carts` where `id` is null)

how to delete pivot row ?

**Comment by LukeTowers** [comment]
Try debugging the raw SQL statement that gets executed by replacing `->first()` with `->toSql()`

**Comment by HekmatFavid** [comment]
Thank's Luke, i use DB::table Query builder and this works properly.
