### ISSUE TITLE
[UX] Add "Apply Filter" button to filter groups

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#3304]
We should add an "Apply Filter" button to filter groups between the selectable filter options and the selected filters in order to provide a hint to users for how to apply their selected filters. 

The current behaviour is requiring the user to close the filter popup by clicking anywhere else on the page before the selected filters are sent in an AJAX request and the list is filtered appropriately. This proposal would retain the current behaviour but also add a button to close the filter popup and apply the filters.

I ran into this issue with clients that didn't know how to actually apply their chosen filter options, so this button would provide a visual prompt for users unfamiliar with the system.

**Comment by Teranode** [comment]
I'd need a visual representation on what needs to be done.

**Comment by LukeTowers** [comment]
Something like:
<img width="321" alt="screen shot 2018-09-13 at 8 47 00 am" src="https://user-images.githubusercontent.com/7253840/45496001-ba333a00-b731-11e8-92c7-722def13c7ac.png">
Apply would basically close the dialog triggering the application of the filters and clear would clear the active filter data from the dialog. Feel free to play around with the styling of those buttons but that's the general gist of it @Teranode

**Comment by Teranode** [comment]
@LukeTowers https://github.com/octobercms/october/pull/3882/

**Comment by LukeTowers** [comment]
@Teranode what's the reasoning between using that language and no icons?

**Comment by Teranode** [comment]
Just wanted to get something bare bones out and just update as needed (because i would have forgot about this request)

**Comment by LukeTowers** [comment]
Meant language in terms of the words chose :) Looks good, any thoughts on how it functions?

**Comment by Teranode** [comment]
Not really, i had no issues with it before, since this is more of a client issue wouldn't hurt to have buttons.

**Comment by AugmentBLU** [comment]
If you use multiple lists on a single page, only the first filter popover buttons work. The default behavior works fine - clicking outwith the popover for all lists.

```
storm-min.js?v446:formatted:22674 Uncaught TypeError: Cannot read property 'data' of null
```

**Comment by LukeTowers** [comment]
@AugmentBLU could you submit a PR to fix that? Or perhaps @Teranode are you able to look into that?

**Comment by Teranode** [comment]
im not sure where i would be in a position to use multiple lists on the same page, so i cant reproduce the issue.

**Comment by AugmentBLU** [comment]
It's to support an existing feature. If you have multiple lists, say in tabs the filter works but not the apply and clear buttons. 

https://octobercms.com/docs/backend/lists#multiple-list-definitions
