### ISSUE TITLE
Code Cleanup - W3C validator

### ISSUE THREAD

**Issue by prabhu9484** [octobercms/october#3311]
[#####] Expected behavior
Should be 0 errors after passing through https://validator.w3.org/

##### Actual behavior
**Option1 : Validate by URI**

When we passed a core install on
http://pfaorissa.co.in/test/test/ through https://validator.w3.org/
We only got 2 warnings and 1 error

**Option2 : Validate by File Upload**

When we uploaded october/themes/demo/pages/home.htm through https://validator.w3.org/
We got 31 errors (attached is the screen-shot)

Based on the 2 above options, what would be the correct approach for OctoberCMS core code-cleanup ?

##### Reproduce steps
We would like to do a code cleanup of OctoberCMS core.
We would like to follow the directives of https://validator.w3.org/
Is this a valid undertaking ?

**Option1 : Validate by URI**

When we passed a core install on
http://pfaorissa.co.in/test/test/ through https://validator.w3.org/
We only got 2 warnings and 1 error

**Option2 : Validate by File Upload**

When we uploaded october/themes/demo/pages/home.htm through https://validator.w3.org/
We got 31 errors (attached is the screen-shot)
![w3cvalidatorhome](https://user-images.githubusercontent.com/932126/34194865-d933a990-e580-11e7-91c9-c24744d1be2b.png)

Based on the 2 above options, what would be the correct approach for OctoberCMS core code-cleanup ?

##### October build
https://octobercms.com/download

**Comment by munxar** [comment]
1. Click on 'more options' on the w3vaidator form and select 'html 5' as document type.
You'll see that only 2 warnings and one error will remain.
2. By investigating the 'error' I could not find this markup. 
```html 
<p>
    The introductory text used on this page is defined in the <code>content/welcome.htm</code> file.
    Content blocks are defined and rendered with:
    <pre>{% content "content-name.htm" %}</pre>
</p>
```
which is not correct, because a 'pre' block element can not nested inside a 'p' element. so change the p to a 'div' an your good to go.
p.s. the warnings are more or less self explaining

This is not a october 'core' problem, it's just one little markup hick in a demo theme.

**Comment by LukeTowers** [comment]
As above, thanks @munxar!

**Comment by prabhu9484** [comment]
Many thanks @munxar and @LukeTowers  - appreciated - merry Christmas and a Happy New Year !

**Comment by prabhu9484** [comment]
Many thanks @munxar and @LukeTowers  - appreciated - merry Christmas and a Happy New Year !
