### ISSUE TITLE
Problem in use input.preset

### ISSUE THREAD

**Issue by tim0991** [octobercms/october#3312]
When i enter `this is an question`, i hope i can get `this-is-an-question`,but actually it is `question`

I found a `removeList` in input.preset.js, what is the use of this

![image](https://user-images.githubusercontent.com/26053904/34243352-4f0df5b4-e65b-11e7-9d34-3caec9576731.png)

**Comment by LukeTowers** [comment]
@tim0991 the point of this is to remove words that would clutter the slug unnecessarily. See https://kb.yoast.com/kb/list-stop-words/ and http://searchmicroservices.techtarget.com/definition/stop-word

**Comment by tim0991** [comment]
In some cases, we want get the original string, and in wordpress it returns the same thing

![image](https://user-images.githubusercontent.com/26053904/34245032-1f89911a-e663-11e7-8e9c-37d272340999.png)

Can we add an option to control this?

**Comment by LukeTowers** [comment]
Sure, make a PR to add support for toggling this feature.

**Comment by tim0991** [comment]
PR https://github.com/octobercms/october/pull/3320
