### ISSUE TITLE
Problem in richeditor with video

### ISSUE THREAD

**Issue by tim0991** [octobercms/october#3313]
when i insert a video by url，editor create `<video>` tag
![image](https://user-images.githubusercontent.com/26053904/34250317-729e2820-e677-11e7-95a2-6ca668320c7f.png)
![image](https://user-images.githubusercontent.com/26053904/34250342-883acc56-e677-11e7-85fd-0d300164ead9.png)

it can't display in chrome
how can i use `<iframe>` instand of this,
and i test insert video in `froala's wysiwyg-editor` , it looks ok

**Comment by LukeTowers** [comment]
Use an iframe in the code view. The video insert is for linking to actual videos, not to webpages that contain videos (i.e. YouTube).

**Comment by tim0991** [comment]
I didn't fully understand what you mean, did you mean if i want to show video in web page, i need to manually use <iframe> in editor by source code

**Comment by LukeTowers** [comment]
YouTube embeds are not videos, they are embeds of the YouTube webplayer on other pages. So if you want to use those embeds, then you will need to add them manually in the editor source code view.

**Comment by tim0991** [comment]
oh i see~~
* in forala, the editor create `<iframe>` tag
* in october, the editor create `<figure>` tag, front page transform it to `<video>`

```php
    protected function generateMediaTagMarkup($type, $src)
    {
        $partialName = $type == 'audio' ? 'oc-audio-player' : 'oc-video-player';

        if ($this->playerPartialExists($partialName)) {
            return Controller::getController()->renderPartial($partialName, ['src' => $src]);
        }

        return $this->getDefaultPlayerMarkup($type, $src);
    }

    protected function playerPartialExists($name)
    {
        if (array_key_exists($name, $this->playerPartialFlags)) {
            return $this->playerPartialFlags[$name];
        }

        $controller = Controller::getController();
        if (!$controller) {
            throw new ApplicationException('Media tags can only be processed for front-end requests.');
        }

        $partial = Partial::loadCached($controller->getTheme(), $name);

        return $this->playerPartialFlags[$name] = !!$partial;
    }
```

and here support partial to specify custom format

**Comment by tim0991** [comment]
thanks ~

**Comment by LukeTowers** [comment]
@tim0991 Feel free to add support for what you're asking for with a pull request, it will get reviewed and merged when ready :)
