### ISSUE TITLE
Call to a member function isSuperUser() on null 

### ISSUE THREAD

**Issue by maxibanki** [octobercms/october#3315]
##### Expected behavior

No error

##### Actual behavior

Error:
`Call to a member function isSuperUser() on null in modules/backend/controllers/Users.php:53`

Code pointer:
https://github.com/octobercms/october/blob/736188e26fbef08cdefab30c4c5be1bf982decd1/modules/backend/controllers/Users.php#L52-L57

Stacktrace:
![image](https://user-images.githubusercontent.com/17984549/34257925-2f4a125c-e65c-11e7-80c6-b54991fe8b7f.png)

##### Reproduce steps

Change Settings if a user is a superuser

##### October build

430

**Comment by LukeTowers** [comment]
What are the exact steps and pages you are visiting in order to get this @maxibanki?

**Comment by maxibanki** [comment]
I don't know, I'm not 100% sure. I've created a new user and checked and unchecked a few permissions of him. Also, I've added him to a group. Then I logged me in with this user via an Inkognito tab. After that I realized, that i didn't have enough permissions and gave him Superuser privileges. Then I thought about that and came to the result, this is too much and gave him explicit permissions and removed the Superusers one.
Beautiful story right?

**Comment by LukeTowers** [comment]
This should only occur if you are trying to access the Users controller without being logged in.

**Comment by wilirius** [comment]
@LukeTowers Exactly - going to yourwebsite.test/backend/backend/users shouldn't cause an error, but rather 404 or redirect to the authentication screen. So if your login session expires and you open the tab back up, it ideally wouldn't cause an error.

**Comment by LukeTowers** [comment]
Should be fixed by https://github.com/octobercms/october/commit/69e56b0b5b237aaaabfc25f88fc8265c7549f243
