### ISSUE TITLE
install october with CLI issue

### ISSUE THREAD

**Issue by buuug7** [octobercms/october#3321]
I installed october with ` composer create-project --prefer-dist october/october
 chicken-soup`, a exception have accured. failured both in  win10 and osx(10.13) with vagrant homestead.
#### win10(version 1709 build 16299.125)
+ virtualbox 5.1.26
+ Vagrant 2.0.0
+ homstead 5.0.1

#### osx(10.13.2)
+ virtualbox 5.2.2
+ Vagrant 2.0.1
+ homstead 5.0.1

#### win10
![image](https://user-images.githubusercontent.com/12119289/34288217-dcc61eba-e726-11e7-9125-d256aadf7f10.png)
#### osx
<img width="890" alt="35b6ef78-cce1-4fd8-9511-359ee758f599" src="https://user-images.githubusercontent.com/12119289/34288438-3d945f3a-e728-11e7-9770-a16e2fb1a2fb.png">

**Comment by buuug7** [comment]
i know this exception is no matter for use, this exception is not accured before 431 installed with CLI.

**Comment by LukeTowers** [comment]
@buuug7 could you check to see if it's due to this change: https://github.com/octobercms/october/commit/fbf482a3f44eb28076d6df5ee46df30befaa0789

**Comment by Alainy** [comment]
#3288 did cause this. I ran `git clone https://github.com/octobercms/october.git;cd october;git checkout develop` then changed `'default' => 'development'` back to `'default' => 'production'` and then ran `composer create-project`. But now the same bug occurs as in #3287. It seems that that `php artisan key:generate` expects an input from the user to continue the command and the default value is **no**. Since the user can't give any input the command is cancelled.

**Comment by buuug7** [comment]
a normal laravel project need generate the application key for quick start (eg. database is optional config), but the october application need more configurations (not just only generate the application key) unless you run `php artisan october:install` or other ways of installation.  

i think `php artisan key:generate` in the `composer.json` is superfluous ,so remove the `php artisan key:generate` from the `composer.json` is good  a solution. 

```

    "scripts": {
        "post-create-project-cmd": [
           // remove this line
            "php artisan key:generate"
        ],
        "post-update-cmd": [
            "php artisan october:util set build"
        ]
    },
```

**Comment by LukeTowers** [comment]
@buuug7 @Alainy how about if we switch the default environment back to production but make the post-install command `php artisan key:generate --force` instead?

**Comment by buuug7** [comment]
@Luke Towers this will also cause error, because they can not find a file with '.env' name

**Comment by LukeTowers** [comment]
@buuug7 could you make a PR to implement your suggestions and provide a detailed explanation in the PR then please?

**Comment by daftspunk** [comment]
Should be fixed in Build 433+
