### ISSUE TITLE
ScssCompiler Error

### ISSUE THREAD

**Issue by nwilcox93** [octobercms/october#3322]
##### Expected behavior
Attempting to add sass in this manner:
function onStart(){
    $this->addCss(['assets/sass/global.scss']);
}
##### Actual behavior
Exception is thrown:
file_get_contents(/themes/mytheme/assets/sass/global.scss): failed to open stream: No such file or directory

49 | file_get_contents(…) | ~/vendor/october/rain/src/Parse/Assetic/ScssCompiler.php | 74

I believe it is an issue involving using / instead of \ in a windows environment.

##### Reproduce steps
Running Wamp Stack on Windows Machine.
Add function to compile scss to a layout file.

##### October build
430

**Comment by LukeTowers** [comment]
Try the following and let me know if it works:
```php
public function onStart()
    $this->assetPath = base_path('themes/mytheme/');
    $this->addCss(['assets/sass/global.scss']);
}
```

**Comment by nwilcox93** [comment]
I applied the code and it still threw the exception.

using `<link href="{{ ['assets/sass/global.scss']|theme }}" rel="stylesheet">` seems to compile the .scss properly.

**Comment by LukeTowers** [comment]
What's the exception exactly using my above code?

**Comment by nwilcox93** [comment]
file_get_contents(/themes/mytheme/assets/sass/global.scss): failed to open stream: No such file or directory

C:\Websites\MySite\Website\mysite/themes/mytheme/layouts/default.htm line 74

TYPE
PHP Content

EXCEPTION
Cms\Classes\CmsException
![image](https://user-images.githubusercontent.com/34778416/34315119-9f625bd6-e741-11e7-9e57-789e084c40bd.png)


49 | file_get_contents(…) | ~/vendor/october/rain/src/Parse/Assetic/ScssCompiler.php | 74

**Comment by nwilcox93** [comment]
I believe i have a fix for the issue on my end.  May need to be tested on Mac.  I added some code to the prepareCombiner function in CombineAssets.php.  See New Code within the foreach loop.

![image](https://user-images.githubusercontent.com/34778416/34531945-cad50282-f079-11e7-89da-2a62a445b76b.png)


It was an issue when making the FileAsset with Assetic.  I'm not an experienced programmer so I'm not sure if this is viable fix for others.

**Comment by LukeTowers** [comment]
That fix works for you and only you @nwilcox93. What you have to do is to set `$this->assetPath` to the correct location. Try `public_path('themes/mytheme/assets/sass/global.sass')` or someother variation. You need to debug it to find out what exact path you need to pass into `assetPath` to make it work, but your code changes won't be helpful for anyone else because it basically just moves that processing from the the assetPath variable to be internal to the compilation code itself, which is a bad idea.

**Comment by nwilcox93** [comment]
Setting $this->assetPath in the php section of the layout has no effect on the $assetPath Variable within AssetMaker.php.

I changed to function inside AssetMaker to inspect the variable it is passing to CombineAssets:combine();

    public function combineAssets(array $assets, $localPath = '')
    {
        // Short circuit if no assets actually provided
	    if (empty($assets)) {
		    return '';
        }
        throw new \InvalidArgumentException($this->assetPath);
        $assetPath = !empty($localPath) ? $localPath : $this->assetPath;
        
        return Url::to(CombineAssets::combine($assets, $assetPath));
    }

No matter what i set $this->assetPath to in the in the layout php section, assetPath evaluates to /themes/mytheme

**Comment by LukeTowers** [comment]
Ah, I see why. It is because methods are called on the controller object, but properties are set on the page object: https://github.com/octobercms/october/blob/master/modules/cms/classes/CodeBase.php.

Try setting `$this->controller->assetPath` instead @nwilcox93

**Comment by LukeTowers** [comment]
So it should now be
```php
public function onStart()
    $this->controller->assetPath = base_path('themes/mytheme/');
    $this->addCss(['assets/sass/global.scss']);
}
```

**Comment by nwilcox93** [comment]
Way to go.  That fixed it.

**Comment by LukeTowers** [comment]
Glad to hear it :) There's always a simple solution 😂
