### ISSUE TITLE
Frontend RainLab.User fails to keep session 

### ISSUE THREAD

**Issue by flyingbaba** [octobercms/october#3323]
Build 430

RainLab.User Build: 1.4.5. 

Using the simple form for signin: data-request="onSignin" server fails to keep user logged in. This issue happened only on production server, local dev xampp has no issue with what. Sessions are stored as files, file is created but user is logged out right after logging in. 

Backend is keeping me logged in without any troubles. 

Found this thread here: https://github.com/octobercms/october/issues/3144  but I have no idea how to use ->middleware('web') since I have no middleware, I'm using basic example as shown in rainlab.user docs without any middleware. 

Please help with information about this issue. ASAP Please.

**Comment by LukeTowers** [comment]
This is an issue for the RainLab.User repository, not the main october one.
