### ISSUE TITLE
Soft delete scope might not be properly applied globally in Laravel 5.5

### ISSUE THREAD

**Issue by Tetraneon** [octobercms/october#3325]
Hi,

This issue appear after October update from 413 to 430

##### Expected behavior

The pagination navbar is disable when I have less items to show than necessary.

##### Actual behavior

Paginating navbar is visible whereas there's less items than indicated by `->paginate(5);`. October seems take care of the deleted items staying in database.

##### Reproduce steps

In my database, I have 14 records : 
- 11 has been deleted with "soft deleting support" : deleted_at field is not null
- 3 are active : deleted_at field is NULL

In my script, i wrote : 
```
==
<?php
function onStart(){
$this['items'] = myModel::where('id', '=', $id)->paginate(5);
}
?>
==

[...]
<ul class="pagination center-block">{{ items.render|raw }}</ul>
```

The pagination navbar is visible whereas I have only 3 items to show. 
When this line is modify like this :

`$this['items'] = myModel::where('id', '=', $id)->paginate(15);`

The pagination navbar is hidden.

##### October build
413 : it works.
430 : it doesn't work.

**Comment by LukeTowers** [comment]
@Tetraneon could you please dig into the code that renders the pagination navbar and see if you can spot the change that would be causing this issue?

**Comment by Tetraneon** [comment]
Ok... I replace the pagination navbar by the October instruction `{{ items.render }}` and in a second time, by the Laravel one `{{ items.links() }}`

Both gave the same result : 
```
<ul class="pagination">
<li class="disabled"><span>&laquo;</span></li> 
<li class="active"><span>1</span></li> 
<li><a href="https://xxx.fr/items?page=2">2</a></li> 
<li><a href="https://xxx.fr/items?page=2" rel="next">&raquo;</a></li> 
</ul>
```

I have 2 pages when `->paginate(5)` and only 1 when `->paginate(15)`. I think the pagination query doesn't include `"... AND deleted_at IS NOT NULL"`...

**Comment by LukeTowers** [comment]
@Tetraneon could you please post the exact code for your query?

**Comment by Tetraneon** [comment]
Oh! Sorry...

The script : 
```
title = "My Items"
url = "/items"
layout = "default"
is_hidden = 0

[session]
security = "user"
redirect = "signin"

[sweetAlertMessage]
==
<?php
    use MyProject\MyPlugin\Models\Item;
    use Rainlab\User\Models\User; 

    function onStart(){
        $user_id = Auth::getUser()->id;
        $this['items'] = Item::where('user_id', '=', $user_id)->paginate(5);
    }
?>
[...]
             <div class="col-sm-4">
                 <ul class="list-group">
                    {% for item in items %}
                        <li class="list-group-item list-group-item-{% if item.active == 1 %}success{% else %}danger{% endif %}">
                            <a href="/system/view/{{ item.slug }}">{{ item.name }}</a>
                        </li>
                    {% else %}
                        <li class="list-group-item list-group-item-warning">No item...</li>

                    {% endfor %}

                    {% if items %}
                        <center>
                            {{ items.render|raw }}<br>
                        </center>
                    {% endif %}
                </ul>
            </div>  

[...]
```
The model : 
```
<?php namespace MyProject\MyPlugin\Models;

use Model;

/**
 * Model
 */
class Item extends Model
{
    use \October\Rain\Database\Traits\Validation;
    use \October\Rain\Database\Traits\SoftDelete;

    protected $dates = ['deleted_at'];

    /*
     * Validation
     */
    public $rules = [ ];

    /**
     * @var string The database table used by the model.
     */
    public $table = 'myproject_myplugin_items';


    public $belongsTo = [
        'user' => 'RainLab\User\Models\User'   
    ];

    public $hasMany = [
        'hive' => 'MyProject\MyPlugin\Models\Thing'
    ];
    
}
```
Perhaps, `public $timestamps = true;` is now nécessary in model definition ? I try but nothing happened...

**Comment by LukeTowers** [comment]
I'm thinking that the softdelete scope is not being applied to the base `where()` query, try `::where('user_id', $userId)->whereNull('deleted_at')->paginate(5);`

**Comment by Tetraneon** [comment]
It works... 
Do you think it come with Laravel 5.5 ?

**Comment by LukeTowers** [comment]
It might have, there might be a difference in how global scopes (as used by the soft delete trait) get applied. Are you able to try to debug the query object to see if the SoftDeletingScope is applied to it and in what instances it is not?

**Comment by LukeTowers** [comment]
@Tetraneon ping

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
