### ISSUE TITLE
Redirect::back() not working

### ISSUE THREAD

**Issue by fbarrento** [octobercms/october#3327]
##### Expected behavior
After submitting a form and perform the validation. If I got an error I expect that the user is redirect to the current position on the same page. 

##### Actual behavior
The page is refreshed but the page scroll is at the top.

##### Reproduce steps
1. User submits a form
2. Component perform validation
3. Component redirects back the user to the top of the page instead of the form in the middle of the page.

**Comment by LukeTowers** [comment]
How is that an October issue? It sounds more like an issue with your markup. Are you using anchor tags?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
