### ISSUE TITLE
{% if partial(partialname) %} returns false even is the file exists

### ISSUE THREAD

**Issue by zietbukuel** [octobercms/october#3330]
##### Expected behavior
`partial()` should return true if the partial file exists.

##### Actual behavior
But it doesn't.

This is my code:

```
<div id="hero" class="hero-{{ name }}">
  <div class="overlay">
    <div class="container">
      <div class="row">
        <div class="col-sm-7">
          <h1>{{ this.page.title }}</h1>
          {% set hero = name ~ '/hero.htm' %}
          {% if partial(hero) %}
            {% content hero %}
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
```

In my layout or pages I call it like this:

`{% partial 'hero' name='contact' %}`

So, the 'hero' variable inside my partial resolves to `contact/hero.htm`. The file exists, but `partial()` is returning false. When I run `{{ dump(hero) }}` it shows empty, as if the variable doesn't even exists. But if I run `{{ dump() }}` the variable exists and shows the correct value which is `contact/hero.htm`!

Maybe I'm just doing something wrong?

##### October build
431

**Comment by LukeTowers** [comment]
If `dump(hero)` is empty, then something is wrong with how you're assigning it.

**Comment by zietbukuel** [comment]
Well, that's why I described how I assign the variable and how I make use of it. If it's something wrong on my end, please let me know how to fix it, thanks.

**Comment by LukeTowers** [comment]
Is this all of the code you use? If it's getting called more than once on a page there could be race conditions or potentially some other scoping issues causing the variable to be empty.

**Comment by zietbukuel** [comment]
Yes, that's all the code. It's being called once per page only.

**Comment by LukeTowers** [comment]
Where does `name` get set?

**Comment by zietbukuel** [comment]
I call it like this:

`{% partial 'hero' name='contact' %}`

From my pages.

The weird thing is that the variable is visible when I add `dump()` at the bottom, but it's empty for `dump(name)`.

**Comment by LukeTowers** [comment]
How about if you try to just echo the variable itself or its JSON representation? I.e. `{{ hero }}` or `{{ hero | json_encode }}`

**Comment by Samuell1** [comment]
@LukeTowers @zietbukuel was this solved?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
