### ISSUE TITLE
`storage.uploads.disk` in config/cms.php is not effective.

### ISSUE THREAD

**Issue by pikanji** [octobercms/october#3332]
##### Expected behavior
When `storage.uploads.disk` in config/cms.php is set to `s3` (assuming that `s3` is properly configured in config/filesystem.php), the uploaded file from FileUpload widget in backend is uploaded to S3.

##### Actual behavior
The uploaded file is stored in the disk specified by `default` in config/filesystem.php, no matter what is selected in `storage.uploads.disk` in config/cms.php.

##### Reproduce steps

1. Assuming there is a working model and corresponding database table exist, add an attachMany relation to the model as described [here](https://octobercms.com/docs/database/attachments#file-attachments).
2. Add a FileUpload widget to the models backend form for the attacheMany relation added above.
3. Set `storage.uploads.disk` in config/cms.php to `s3` (assuming that `s3` is properly configured in config/filesystem.php, and destination S3 bucket is ready to be uploaded files).
4. Set `default` in config/filesystem.php to `local`.
5. Upload file from the model's create/update page in background. It will be uploaded to local storage.
6. If `default` in config/filesystem.php is changed to `s3`, the uploaded file will be stored on S3, but I guess it is not the expected behavior.

##### October build
431

**Comment by LukeTowers** [comment]
Potentially related: #2917

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/54ab6f080a60526fd9685518c1456bc1b7781187
