### ISSUE TITLE
Where to get Build <318?

### ISSUE THREAD

**Issue by arifnyet** [octobercms/october#3334]
im sorry.... but can anyone tell me where to get build for octobercms 318.... thanks alot

**Comment by LukeTowers** [comment]
@arifnyet why do you need that? You can get the build for 319 and above here: https://github.com/octobercms/october/archive/v1.0.319.zip

**Comment by arifnyet** [comment]
it is just my client refused to upgrade to php5.5 for some unknown reason... if it still available can i have a copy.... thanks a lot

**Comment by LukeTowers** [comment]
Not a clue. Tell you client that they are risking security issues and that PHP 7 is significantly faster as well.

**Comment by arifnyet** [comment]
@LukeTowers oh ok then... i just have to force them to do it by other means
