### ISSUE TITLE
Octobercms media not working after updating.

### ISSUE THREAD

**Issue by ronogrimen** [octobercms/october#3335]
After fixing this problem "Call to undefined method RainLab\Pages\Widgets\PageList::getCollapseStatus()" october cms media now is not working.

**Comment by LukeTowers** [comment]
**Describe the expected answer here.**

**Comment by LukeTowers** [comment]
In all seriousness:
The amount of time spent asking for help is directly related to the amount of time spent putting in effort to answer it. If you want help and / or guidance, then invest as much time as possible in making questions that are detailed and easy to understand. Otherwise, nobody is going to invest their time helping with a question that wasn't even worth the askers time to ask correctly.

**Comment by ronogrimen** [comment]
![untitled](https://user-images.githubusercontent.com/32258387/34475414-ecbc86e4-efc6-11e7-901a-887bb1bdb3e4.png)
It shows like there's no problem but I cant upload delete or view anything.

**Comment by LukeTowers** [comment]
What error do you get? What was your fix? You need to provide more information or I simply can't help you.

**Comment by ronogrimen** [comment]
I cant add, delete or anything in media page. I fixed it by updating my composer but this problem occurs again  "Call to undefined method RainLab\Pages\Widgets\PageList::getCollapseStatus()"

**Comment by LukeTowers** [comment]
Funny how you just said the exact same thing again.

How did you update your composer?

**Comment by ronogrimen** [comment]
Because that is the problem and u still ask what error did i get.

composer update in terminal

**Comment by LukeTowers** [comment]
Are you using a public folder?

**Comment by ronogrimen** [comment]
No

**Comment by LukeTowers** [comment]
Check your filesystem, are they actually missing from the disk or is it that the browser can't connect to them?

**Comment by ronogrimen** [comment]
The file is there. I think the browser cant connect.

**Comment by LukeTowers** [comment]
Are you sure you aren't using a symlinked public directory? http://octobercms.com/docs/setup/configuration#public-folder

**Comment by ronogrimen** [comment]
Wait. I think im using public directory

**Comment by LukeTowers** [comment]
Remove the public directory that you currently have and then run `php artisan october:mirror $nameOfYourPublicDirectory --relative` ($nameOfYourPublicDirectory is usually just `public`).

For future reference the typical script I use when updating October with composer is the following:
```bash
# Install the project dependencies
composer install;

# Enable Maintenance Mode
php artisan down;

# Run any pending migrations (including initial migrations if this is a clean database)
php artisan october:up;

# Clear out the public directory to replace with a freshly generated one
rm -rf public;

# Mirror the whitelisted resources to the public directory with relative symlinks for a whitelist approach to security
php artisan october:mirror public --relative;

# Disable Maintenance Mode
php artisan up;
```

**Comment by ronogrimen** [comment]
It's fine now. But i got another error in rainlab pages plugin "Call to undefined method RainLab\Pages\Widgets\PageList::getCollapseStatus()" My current build is 431 and the version of the pages plugin is 1.2.18.

**Comment by LukeTowers** [comment]
@ronogrimen Try reinstalling build 431, it doesn't sound like you have the current version of https://github.com/octobercms/october/blob/master/modules/backend/traits/CollapsableWidget.php present on your install.

**Comment by ronogrimen** [comment]
Its working now. But I didnt reinstall it, I just overwrite my collapsablewidget.php by the one you gave. Thank you so much but can you please tell me on how to reinstall it properly

**Comment by LukeTowers** [comment]
@ronogrimen what version of PHP are you using on the command line? (`php --version`)

**Comment by ronogrimen** [comment]
7.1.9. Can you please tell me on how to reinstall it properly without deleting any data/content in my website? I fixed all the problems on my backend by using php artisan october:update but the error in media comesback. Its not working.

**Comment by ronogrimen** [comment]
@LukeTowers Thanks!
