### ISSUE TITLE
Any backend's ajax request ends with an error

### ISSUE THREAD

**Issue by EdisonLV** [octobercms/october#3336]
##### Expected behavior
Able to view any file (page/partial) in editor

##### Actual behavior
After choosing the file from the list to view I am getting a popup with error in it (see below) 

##### October build
431

##### PHP version
7.1.12

![screen shot 2018-01-03 at 3 32 41 pm](https://user-images.githubusercontent.com/2999577/34538826-fe2e6d9a-f09b-11e7-8d70-d2bf936678f9.png)

**Comment by LukeTowers** [comment]
@EdisonLV are there any errors in your browser console?

**Comment by EdisonLV** [comment]
Issue can be closed. The problem was identified and fixed. Thnak you

**Comment by LukeTowers** [comment]
@EdisonLV could you post what the issue was and the fix so that future visitors to this issue can have some help debugging their issues?

**Comment by EdisonLV** [comment]
@LukeTowers it has nothing to do with October itself, it was one of my experimental plugins messing thing up.

**Comment by LukeTowers** [comment]
Out of curiosity, have you tested Laravel package discovery with October plugins yet?

**Comment by EdisonLV** [comment]
the library I was using still works without ```App::register('\RenatoMarinho\LaravelPageSpeed\ServiceProvider');``` in my plugin's boot() method

**Comment by LukeTowers** [comment]
I'm referring to the new feature in Laravel 5.5 where composer packages can define an extra property in their config.json to have Laravel register the service providers automatically.

**Comment by EdisonLV** [comment]
As I said before, the package did work without manually registering service provider in boot() method, so I believe package discovery does work with october plugin system.

**Comment by LukeTowers** [comment]
Ah, misread that :) Missed the 
>without
Thanks for the update!
