### ISSUE TITLE
In Str.php line 487: Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by lincolnbrito** [octobercms/october#3337]
PHP 7.1 or 7.2

##### Expected behavior
Show the options to install october

##### Actual behavior
```
.====================================================================.

 .d8888b.   .o8888b.   db  .d8888b.  d8888b. d88888b d8888b.  .d888b.
.8P    Y8. d8P    Y8   88 .8P    Y8. 88  `8D 88'     88  `8D .8P , Y8.
88      88 8P      oooo88 88      88 88oooY' 88oooo  88oobY' 88  |  88
88      88 8b      ~~~~88 88      88 88~~~b. 88~~~~  88`8b   88  |/ 88
`8b    d8' Y8b    d8   88 `8b    d8' 88   8D 88.     88 `88. `8b | d8'
 `Y8888P'   `Y8888P'   YP  `Y8888P'  Y8888P' Y88888P 88   YD  `Y888P'

`=========================== INSTALLATION ==========================='
```

In Str.php line 487:

  Illegal offset type in isset or empty

##### Reproduce steps
> php artisan october:install

##### October build
430

**Comment by LukeTowers** [comment]
Are you able to dig into the command and see what's causing the issue @lincolnbrito?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
