### ISSUE TITLE
`storage.uploads.disk` in config/cms.php is still not effective for some part

### ISSUE THREAD

**Issue by pikanji** [octobercms/october#3346]
My fix for #3332 was not enough. Although the problem I reported there was fixed, I found other functions, such as deletion of uploaded files, are still not working due to the same problem (`System\Models\File` is partially using `default` in config/filesystems.php).
To fix this issue, I suggest to make its base class `October\Rain\Database\Attach\File` a bit more scalable instead of adding more overriding methods to `System\Models\File`.

I have issued PRs for the fix.
* octobercms/library#294
* #3347 

##### Expected/Actual behavior & Reproduce steps
Please see #3332, and deletion of the uploaded file is still not working.

##### October build
431

**Comment by LukeTowers** [comment]
This should theoretically be fixed by https://github.com/octobercms/library/commit/48fed9b7e4c4c22ccc6b3c2e5b1273da3e2c38dd & https://github.com/octobercms/october/commit/aea4857ebaaa132499033014309bd5a6032dd66d

**Comment by pikanji** [comment]
@LukeTowers Yeah, I was just looking at those. Confirmed.
