### ISSUE TITLE
MediaManager quickMode lead to uploaded-files directory more and more big

### ISSUE THREAD

**Issue by buuug7** [octobercms/october#3351]
## description
if uploaded image from richeditor, MediaManager will use quickModel upload all images to a directory named **uploaded-files**, this lead **uploaded-files** directory more and more big, it need several minutes to open it.  

![october-media](https://user-images.githubusercontent.com/12119289/34779689-e763e390-f65b-11e7-8e6d-d45da7df80a2.png)

## suggestion
When the quickMode is enable, it is better if we use time-based organization of files and folders. The files uploaded that day will be stored in a separate folder, named with uuid, which also avoids the problem of repeating the same file name.  

modified the `Backend\Widgets\MediaManager` class `checkUploadPostback` method like this.
```
         if ($quickMode) {

                $basePath = '/uploaded-files';

                $now = Carbon::now();

                $path = $basePath . '/' . $now->year . '/' . $now->month . '/' . $now->day;

                $path = MediaLibrary::validatePath($path);

                $filePath = $path . '/' . File::name(Uuid::uuid1()) . '.' . $extension;

            } else {
                $path = Input::get('path');
                $path = MediaLibrary::validatePath($path);
                $filePath = $path . '/' . $fileName;
            }
```
## expected
![mediamanager-result](https://user-images.githubusercontent.com/12119289/34780373-f1599d66-f65d-11e7-9df4-294e0066368a.png)

**Comment by LukeTowers** [comment]
How about `/uploaded-files/YYYY/MM/$filename-$uuid.$extension` instead?

**Comment by buuug7** [comment]
@LukeTowers it good. However, I am afraid that if the files in this folder grow too fast in a month, for example, 2,000 pictures will be uploaded in one month, which will cause the folder to be too large.Do you have any other ideas?

**Comment by LukeTowers** [comment]
2,000 pictures in a month seems a bit excessive, perhaps this is something that needs to be made configurable with `cms.storage.media.quickModeFolder => 'uploaded-files/{Y}/{m}/{d}/{filename}-{uuid}.{ext}'`

**Comment by buuug7** [comment]
@LukeTowers Your idea is great. When are you going to implement it? I can't wait.

**Comment by LukeTowers** [comment]
You can implement it yourself and make it in this PR, I'll provide feedback on the code you write but it should be fairly straightforward. =

**Comment by buuug7** [comment]
@LukeTowers yes.

**Comment by buuug7** [comment]
@LukeTowers this issue should be suspended for a while until #3354  is solved.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
