### ISSUE TITLE
MediaManager Can not upload filename with Unicode character

### ISSUE THREAD

**Issue by buuug7** [octobercms/october#3354]
##### Description
When upload filename with Unicode characters, MediaManager worked very bizarre. For example, we upload a file with `波比.jpg` name, the MediaMange prompt upload success, but we could not found it in the MediaManage. actually, it upload `波比.jpg`  and rename it with `.jpg` name, only contain the the dot and file extension.

##### Screenshot
![media1](https://user-images.githubusercontent.com/12119289/34824174-62ed0eea-f708-11e7-9660-cb080f15da01.png)
![media2](https://user-images.githubusercontent.com/12119289/34824180-695de308-f708-11e7-8518-f743be653d5b.png)
![media3](https://user-images.githubusercontent.com/12119289/34824192-74167d64-f708-11e7-8d90-11fe71517225.png)

#### suggestion
use the [slug-generator](https://github.com/ausi/slug-generator) library for generate the filename with URL Slug, the library will try to convert characters to ASCII, and then save to the filesystem. this will solve mutiple laguage named filename uploaded problems.
```
// example for use SlugGenerator
$generator = new SlugGenerator;

$generator->generate('Hello Wörld!');  // Output: hello-world
$generator->generate('Καλημέρα');      // Output: kalemera
$generator->generate('фильм');         // Output: film
$generator->generate('富士山');         // Output: fu-shi-shan
$generator->generate('國語');           // Output: guo-yu

// Different valid character set, a specified locale and a delimiter
$generator = new SlugGenerator((new SlugOptions)
    ->setValidChars('a-zA-Z0-9')
    ->setLocale('de')
    ->setDelimiter('_')
);
$generator->generate('Äpfel und Bäume');  // Aepfel_und_Baeume
```
#### my solution
Modified the `Backend\Widgets\MediaManager` `checkUploadPostback()` method as below:  

![media4](https://user-images.githubusercontent.com/12119289/34824744-b1938dd8-f70a-11e7-8be2-87bc84ad7b93.png)

#### result
![media5](https://user-images.githubusercontent.com/12119289/34824819-f861b8a2-f70a-11e7-9b5f-f6ea42438f0e.png)

**Comment by LukeTowers** [comment]
Duplicate of #2603 but this is a better issue report so any discussion will be here instead

**Comment by LukeTowers** [comment]
@buuug7 while your suggestion of the URL generator is appreciated, I want to add extra dependencies only as a last resort. How does Laravel handle unicode file name issues? What can we do with the dependencies that we already have available to us? What are the concerns with saving non-latin characters to the filesystem?

**Comment by Eoler** [comment]
Some of (not so recent) browsers on very popular OS still have trouble displaying images with spaces in URIs so it would be great to at least slugify filenames for uploaded Media Manager files - Laravel's built-in Str::slug works fine for that purpose with all Latin languages.

**Comment by buuug7** [comment]
@Eoler  agree

**Comment by LukeTowers** [comment]
@Eoler @buuug7 what about for non-latin characters? I'm fine with the slugifying, would prefer a solution that keeps the unicode characters present if possible without adding extra dependencies

**Comment by Eoler** [comment]
Don't know how are non-latin characters translated to slugs, maybe @buuug7 can elaborate. Also, not sure I really wan't my CMS users to upload media files with Unicode names...

**Comment by buuug7** [comment]
@LukeTowers @Eoler , Unicode contains more characters than ASCII and Latin, it represent future. For example, Utf8 is the most widely used on the Internet a unicode implementation approach, which is designed for transmission codes, and makes the code without borders, so you can show that the all cultural characters in the world.

**Comment by buuug7** [comment]
@LukeTowers Laravel Str::slug only works with Latin laguage. For brevity, it does not provide additional Unicode support. if a developer needed Unicde support unless he find a solution. this keep laravel framework lighter weight.

**Comment by buuug7** [comment]
@LukeTowers  There is no need to implementation with october. there is no need reinvent the wheel. Besides, it takes extra effort to maintain this feature, and I think it's necessary to use the third-party packages.

**Comment by LukeTowers** [comment]
@buuug7 `Str::ascii()` exists in Laravel, can we use that instead?

**Comment by buuug7** [comment]
@LukeTowers tested with this ,seems it not work.
```
        Str::ascii('Hello Wörld!'); // "Hello World!"
        Str::ascii('Καλημέρα'); // "Kalhmera"
        Str::ascii('фильм'); // "film"
        Str::ascii('富士山'); // ""
        Str::ascii('富士山', 'zh-CN'); // ""
        Str::ascii('國語'); // ""
        Str::ascii('國語','zh-TW'); // ""
```

**Comment by LukeTowers** [comment]
@buuug7 is the dependency you suggested going to introduce new system requirements for October? https://github.com/ausi/slug-generator/blob/master/composer.json? They require:
```
"ext-intl": "*",
"ext-mbstring": "*",
"ext-pcre": "*"
```
Also, would it make more sense to load this dependency into the October Library and then utilize it within October's Str::slug method?

**Comment by buuug7** [comment]
@LukeTowers yes, load this denpendency into October Library and packaged with `Str::slug` method is very good. i try it.

**Comment by SadiqUltra** [comment]
In Backend\Widgets\MediaManager.php file I have change regex with desired Unicode range. And it does work.
`
 protected function validateFileName($name)
    {
        // added our language's unicode in regex
        if (!preg_match('/^[\p{Bengali}0-9a-z@\.\s_\-]+$/i', $name)) {
            return false;
        }

        if (strpos($name, '..') !== false) {
            return false;
        }

        return true;
    }`

**Comment by LukeTowers** [comment]
@SadiqUltra you shouldn't change core files, those changes will be removed next time you update.

**Comment by SadiqUltra** [comment]
@LukeTowers yes, but for now its only option that works, I guess.

**Comment by Johnzero** [comment]
@buuug7 did you fix it?

**Comment by maartenmachiels** [comment]
Any update on this? Some other plugins rely on the paths being a-zA-Z0-9...

**Comment by LukeTowers** [comment]
@maartenmachiels nope. Feel free to propose a change to the regex if you wish, just keep in mind that it won't be accepted unless it solves the original problem (illegal characters allowing for XSS attacks or directory traversal) and works for all of October's user base.

**Comment by anastasiauz** [comment]
It's not only about the filenames - it's possible to create a folder with space in name and then the picture is not displayed in browser, for ex. Chrome 72/October 447, if it is a background - ex.: http://joxi.ru/RmzEMxZfYMPq9r. It will be great if folders are slugified.

**Comment by mjauvin** [comment]
I just tested uploading jpg files with UTF-8 encoded filenames and it works fine on my setup.

Here's the Media Library after the upload

![Screenshot from 2019-11-12 12-22-20](https://user-images.githubusercontent.com/2013630/68694426-22a0c580-0547-11ea-8a0a-d296ce61bf64.png)

**Comment by mjauvin** [comment]
I suspect the problem might be with the Characterset used by the user's Browser that may lead to the problem.

I used a different browser on my system and was able to replicate the issue... so browser configuration definitely has a role... more data to come

**Comment by mjauvin** [comment]
With Firefox, this setting makes it work:
`intl.fallbackCharsetList.ISO-8859-1 = windows-1252`
With Chrome, this extension is needed:
https://www.deep-watch.net/en/blog/bring-character-encoding-menu-back-to-chrome-with-extension

**Comment by LukeTowers** [comment]
@mjauvin is there anything that can be done serverside to fix this? Detect the browser's encoding? Tell the browser what encoding to use? What sort of options do we have?

**Comment by mjauvin** [comment]
That's what I'm trying to find out, so far only client-side changes do the trick.

AFAIK, we already tell the browser which encoding to use in the form tag using: 
`accept-charset="UTF-8"` (ref. `vendor/october/rain/src/Html/FormBuilder.php`)

And also the `<meta charset="utf-8">` in the meta tags (ref. `modules/backend/layouts/_head.htm`)

But there is something I am missing

**Comment by mjauvin** [comment]
What's really odd is that I cannot reproduce at will. I don't know if there is some caching involved or not, but even without changing client-side charset encoding, I SOMETIME get the empty file result.
