### ISSUE TITLE
ListController display can render slowly depending on model's $appends usage.

### ISSUE THREAD

**Issue by jimcottrell** [octobercms/october#3358]
##### Expected behavior
The `ListController` behavior will put together tables of model data with minimal unnecessary data access.

##### Actual behavior
If a list defines a record URL, then rendering each row calls the model's `toArray` function so that any model attribute can be used as a URL parameter. The `toArray` call adds all attributes defined in the model's `$appends` property. If the model appends any attributes that result in a database query, then those queries will run for each record, generally to no real purpose, since there's likely no corresponding parameter in the URL (I've personally not yet had a reason to use anything more than `:id`).

Many models will of course not fit this pattern, but any model that does has backend lists render more slowly than normal and particularly with larger page sizes can become noticeable to the end user.

##### Reproduce steps
- Create a model that uses `$appends` to include extra attributes, and define those attribute getters to query the database (or even just add a call to `sleep`).
- Set up a backend controller using the standard `ListController` behavior to create a list display for the model.
- Add a few records to the model table.
- Make use of a tool that will display queries and execution time (debugbar or equivalent)
- Loading the list index page will result in any appended attribute query (or `sleep`) running for each row.

##### October build
431

There are a couple of possible workarounds, but I think the ideal solution would be to parse URLs for the needed parameter names rather than grabbing all attribute values just in case they're used. I don't see a specific function to do that, though `October\Rain\Router\Helper` could be modified to handle that without too much effort.

As a side note, it's a little strange that setting the list's `recordUrl` results in `toArray` being used to include all attribute values, but `recordOnClick` just makes use of `getAttributes`. So one fix could be to just use `getAttributes` both places, though someone somewhere might depend on the current behavior.

I'd be happy to put together a pull request for this, but I wanted to check if there's something I'm overlooking, and I also want to make sure there's the "will" to add a fix for it, so I don't just add a pull request to the backlog.

**Comment by LukeTowers** [comment]
@jimcottrell What is the difference in values when using `getAttirbutes` vs `toArray`?

**Comment by jimcottrell** [comment]
@LukeTowers `getAttributes` returns the model's `$attributes` property, so just the current attribute values loaded from the database with any changes. The `toArray` function is the full array representation of the model (`toJson` just encodes the results of `toArray`), so `$attributes` plus anything added by `$appends`, any relationships that aren't hidden, any `$appends` and relationships those related models also include, etc. Depending on the model, it can be a lot of data to load just to put an ID in the URL in the general case.

**Comment by LukeTowers** [comment]
@jimcottrell looks like `toArray` was added on purpose by @daftspunk (https://github.com/octobercms/october/commit/ac9df4c0763c12c7e4f19a6bcfe499e397ac6fdf) so it's a use case that we'll have to support.

I think probably the best solution would be to consolidate both sections into a `parseRecordLocation($recordLocation)` that would then look at a config value `includeAppendsInLocation` (or something less wordy) that's true by default to decide whether to use toArray() to getAttributes(). Thoughts?

**Comment by jimcottrell** [comment]
@LukeTowers Fair enough. I'd still prefer parsing the URL for parameter names and having it access only the attributes that are used as parameters. If someone needs to use an appended attribute that does extra work, they could do that and live with the performance hit or work around it with an eager load or whatever, but it would still only be that one needed attribute instead of pulling all appended attributes just in case.

**Comment by LukeTowers** [comment]
@jimcottrell if you can make a PR to parse it go for it :)

**Comment by LukeTowers** [comment]
@jimcottrell could you provide a PR for how the revised list widget would handle the new Router\Helper method?

**Comment by jimcottrell** [comment]
@LukeTowers Ha, was right in the middle of it.
