### ISSUE TITLE
Update phpunit dependency from ~5.7 to ~6.0 to match Laravel 5.5

### ISSUE THREAD

**Issue by jofrysutanto** [octobercms/october#3360]
##### Expected behavior
Writing tests in OctoberCMS is expected to support Laravel TestCase helpers.

##### Actual behavior
Some of Laravel TestCase helper traits such as `assertDatabaseHas()` breaks due to missing expected PHPUnit class dependency:

```
Fatal error: Class 'PHPUnit\Framework\Constraint\Constraint' not found in /acme-project/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Constraints/SoftDeletedInDatabase.php on line 8
```

##### Reproduce steps
Clean installation of October build 420+ (Laravel 5.5)
Create new unit tests that utilises Laravel `InteractsWithDatabase` test helper trait.

##### October build
420+

Updating composer phpunit dependency to ~6.0 seem to fix the issue, which matches Laravel 5.5 dependency: https://github.com/laravel/laravel/blob/v5.5.28/composer.json#L17

**Comment by LukeTowers** [comment]
OctoberCMS uses PHP Unit 6.5 as of https://github.com/octobercms/october/commit/6fb6e5f71ca74d8cad62b4e5816f9ef30192a954#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780
