### ISSUE TITLE
Custom 404 returns 200 OK header

### ISSUE THREAD

**Issue by sunyakun00** [octobercms/october#3362]
##### Expected behavior
when a custom 404 page is set, the http header should return 404 code.
##### Actual behavior
it returns 200 OK code in header.
##### Reproduce steps
create a custom 404.htm, check the status code
##### October build
CMS version 415

**Comment by sunyakun00** [comment]
after tracing the code, I have found the reason.

\modules\cms\classes\Controller.php

        /*
         * Extensibility
         */
        if ($event = $this->fireSystemEvent('cms.page.display', [$url, $page, $result])) {
            return $event;
        }

        if (!is_string($result)) {
            return $result;
        }

        return Response::make($result, $this->statusCode);


when a custom 404 is set, it will run this return

if ($event = $this->fireSystemEvent('cms.page.display', [$url, $page, $result])) {
            return $event;
        }

but not this one

return Response::make($result, $this->statusCode);

and it will lost the 404 status code.

**Comment by sunyakun00** [comment]
here is my fix. I know changing core file is not a good idea, but for the time being, I have to do this.

        if (!$page->exists || $url === '404') {
            return Response::make($result, $this->statusCode);
        }
        /*
         * Extensibility
         */
        if ($event = $this->fireSystemEvent('cms.page.display', [$url, $page, $result])) {
            return $event;
        }

        if (!is_string($result)) {
            return $result;
        }

        return Response::make($result, $this->statusCode);

**Comment by sunyakun00** [comment]
this is my quick fix, even though it's not a good idea to change the core files, but I have to fix it for the time being.

if (!$page->exists || $page->url == "/404/" || $url === '404') {
            return Response::make($result, $this->statusCode);
        }
        /*
         * Extensibility
         */
        if ($event = $this->fireSystemEvent('cms.page.display', [$url, $page, $result])) {
            return $event;
        }

        if (!is_string($result)) {
            return $result;
        }

        return Response::make($result, $this->statusCode);

**Comment by LukeTowers** [comment]
@sunyakun00 you should contact the plugin author and get them to return a properly formed response object with the correct header codes.
