### ISSUE TITLE
 Is there any support for gif tailoring?

### ISSUE THREAD

**Issue by wishxupanpan** [octobercms/october#3366]
Is there any support for gif tailoring?
The type of gif displayed at the foreground is no longer dynamic after the getThumb method,but I need a gif map of the right size

**Comment by LukeTowers** [comment]
?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
