### ISSUE TITLE
Issue installing on PHP 7.2 on Windows

### ISSUE THREAD

**Issue by marijnhurkens** [octobercms/october#3369]
##### Expected behavior
I tried to install OctoberCMS on Windows using PHP 7.1.9, PHP 7.2.0 and PHP 7.2.1. The installation passes the checks but fail when the installation starts  (and I assume it also fails on PHP 7.1.8). Installation works on PHP 7.0.22.

##### Actual behavior
PHP crashes:

`Process finished with exit code -1073741819`

##### Reproduce steps
On windows:

1. Unzip OctoberCMS to folder
2. Run `php.exe -S localhost:80 -t folder`
3. Go to `localhost/install.php`
4. Go through installation steps
5. PHP crashes when install starts

##### October build
v1.0.432

##### Edit:

Database: sqLite

Switching to PHP 7.2.1 after installation seems to work fine.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
