### ISSUE TITLE
Updates only reflecting after adjusting file-case. Docker for Mac issue or October CMS?

### ISSUE THREAD

**Issue by tylerssn** [octobercms/october#3378]
##### Expected behavior
See changes to files reflected immediately if cache has been cleared or disabled

##### Actual behavior
File changes are often not seen until renaming the file with a different letter-case. For example, renaming Contacts.php -> contacts.php and then restoring to Contacts.php

##### Reproduce steps
Setup dev environment with Docker for Mac (more specifically, Lando, which is basically a glorified docker-compose).

##### October build
~1.0

**Comment by LukeTowers** [comment]
Probably Docker for Mac issue, never heard of that happening before.

**Comment by tylerssn** [comment]
I believe this is connected to the container that I am building from changing a Memcached setting.
