### ISSUE TITLE
Meta noindex tag on backend pages

### ISSUE THREAD

**Issue by msimkunas** [octobercms/october#3380]
##### Expected behavior
The backend pages should have the `meta` noindex tag set.

##### Actual behavior
They don't.

##### Reproduce steps
N/A

##### October build
431

Backend pages should have the `<meta name="robots" content="noindex">` tag set in their layout to prevent search engines from indexing them. More info: https://support.google.com/webmasters/answer/93710?hl=en

Using the `robots.txt` file for this is not preferred because it exposes the location of the backend.

It is also possible to use the `X-Robots-Tag` response header. However, I haven't yet found an easy way to set this response header to the entire `backend/*` path in Apache.

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/77ae173c24614b83898f2ac2dd5c7352c643cea4

**Comment by msimkunas** [comment]
Thanks for the quick response!
This only adds the tag to internal backend pages though. The sign in page remains unaffected.

**Comment by LukeTowers** [comment]
@msimkunas Good catch, fixed in https://github.com/octobercms/october/commit/a916d99de4ec98e07b595b3446b413aec5bf107d
