### ISSUE TITLE
Add support for more than one nested folder in the CMS file browser

### ISSUE THREAD

**Issue by SiyuQian** [octobercms/october#3382]
##### Expected behavior
Display the whole folder directory tree in the admin panel

##### Actual behavior
The backend view:
![image](https://user-images.githubusercontent.com/24470452/35805071-4dfc1e5a-0adf-11e8-97c2-55fdde8a4411.png)

My folder structure:
![image](https://user-images.githubusercontent.com/24470452/35805112-77ef8fe4-0adf-11e8-85ff-4736a21bd9f1.png)

##### Discussion
I am not sure did anyone found this issue yet. 
Maybe you did this on purpose?
I found this could make me hard to manage my twig templates, I know that you can name the file like xxx-xxx-xxx.htm but I feel this way is quite ugly. 
 
##### October build
431

**Comment by munxar** [comment]
afaik, you can just have one level of subdirs. so pillar folder is ok, slider is one level to deep.
this is documented somewhere but i couldn't find it right now.

**Comment by LukeTowers** [comment]
@SiyuQian @munxar http://octobercms.com/docs/cms/themes#subdirectories. Personally I'm not opposed if someone wanted to make a PR to add support for infinite subdirectories.

**Comment by SiyuQian** [comment]
Hey Luke,
Thank you for the documentation link. BTW, Luke can you help me to confirm that October Team is agreed on merge the 'add support for infinite subdirectories' to the project. (You know, I just wanted my codes more meaningful) If it is OK, I might do this when I finished all my paid projects.
Cheers,
Siyu Qian

**Comment by LukeTowers** [comment]
@SiyuQian I personally am not opposed to it; and as long as the implementation and user experience can retain simplicity at the core of it all then I don't think any of the other core members will mind either. Be prepared for the potential of lots of review comments on your PR though :)

**Comment by munxar** [comment]
@LukeTowers @SiyuQian I have good news: By just setting this attribute to null, i could use any depth from code.
https://github.com/octobercms/library/blob/4d1418ec5a86c86d4761b8cea00e68bcd8ce523e/src/Halcyon/Model.php#L88
Basically every file based model (static pages, email templates, ...) uses this, the change should be in every subclass. But the backend didn't reflect this change (work needed here).
Now the hard part: UX.
many, many, many CMSs failed with a horrible unusable file tree representations and I could imagine *why* the core team decided to not go deeper than 2 levels.
On the other hand, there are good UX examples for a deep nested folder structure:
- material design (google drive)
- mac os (cover flow mode)

I could think of reusing the existing list, just one level, but add a breadcrumb with 2 levels for this and parent directory.

**Comment by LukeTowers** [comment]
@munxar we'd probably want to focus on one thing at a time, so we would change that variable in https://github.com/octobercms/october/blob/master/modules/cms/classes/Partial.php or perhaps in https://github.com/octobercms/october/blob/master/modules/cms/classes/CmsCompoundObject.php if we changed the UX for all the CMS file listing.

I like the breadcrumb idea @munxar, could you provide a screenshot of what exactly you have in mind?
