### ISSUE TITLE
Notice about reserved words

### ISSUE THREAD

**Issue by brunocascio** [octobercms/october#3383]
##### Expected behavior

Prevent users to use reserved words or handle this properly (?)

##### Actual behavior

I was trying to create a model that contains a column named "rules". Assigning the column into a repeater field make an SQL Exception (maybe it is removed from post data)

##### Reproduce steps

- Create schema with column 'rules' (not null)
- Assign it into a repeater field
- Try to create record (fill repeater field, of course :P)
- Exception saying that 'rules' column cannot be null

##### October build
431

**Comment by LukeTowers** [comment]
What was the exact error?

**Comment by brunocascio** [comment]
Hi @LukeTowers. I've just updated the issue steps in order to improve the description

**Comment by brunocascio** [comment]
NOTE: I changed the name of the column to "some_rules" and it works...

**Comment by LukeTowers** [comment]
What happens if you make the rules column nullable? I usually make any jsonable columns nullable.

**Comment by LukeTowers** [comment]
Are you using the validation trait on your model? @brunocascio 
The validation trait uses the rules property to store the validation rules, so you can't have a rules database column if you already have a rules property on the model being used for other purposes.

**Comment by brunocascio** [comment]
This is my model file: @LukeTowers 

```
<?php namespace Celerative\Sports\Models;

use Model;

/**
 * Model
 */
class Sport extends Model
{
    use \October\Rain\Database\Traits\Validation;
    use \October\Rain\Database\Traits\Sluggable;

    /*
     * Disable timestamps by default.
     * Remove this line if timestamps are defined in the database table.
     */
    public $timestamps = false;

    /*
     * Validation
     */
    public $rules = [
    ];

    /**
     * @var string The database table used by the model.
     */
    public $table = 'myplugin_sports_sports';

    protected $jsonable = [ 'game_rules' ];

    protected $slugs = [ 'slug' => 'title' ];
}
```

Am I missing something? You are right about validations but are not working 🤔 .

**Comment by LukeTowers** [comment]
Remove `use \October\Rain\Database\Traits\Validation;` `public $rules = [];` and add `rules` to the jsonable and it will work. I suggest you just name your column something else though because the validation trait is pretty useful.

**Comment by brunocascio** [comment]
Thanks @LukeTowers! Finally, I used another column name. However, would be great add this in the docs since no error description about this is provided. 😄

**Comment by LukeTowers** [comment]
Feel free to make a PR to the octobercms/docs repository, ping me when you do and I'll review and merge it.
