### ISSUE TITLE
Rich Editor (Froala) misplaces button after horizontal separator

### ISSUE THREAD

**Issue by woeps** [octobercms/october#3385]
##### Expected behavior
Regarding October's Rich Editor (Froala): Displayed horizontal separator (`-` in backend editor settings > toolbar buttons) should take up the whole with, without any button being rendered in the same line. Following buttons should be placed below the separator.
![](https://screenshotscdn.firefoxusercontent.com/images/c9892be0-fff6-4257-8af4-ae81c62ffc5e.png)

##### Actual behavior
When displaying a horizontal separator, the first of the following buttons is rendered on the same line to the most right.
![](https://screenshotscdn.firefoxusercontent.com/images/1a11b733-cb91-479f-b434-0a3a6d422072.png)

I think the behavior is caused by this css rule's width property, which is found in `/modules/backend/formwidgets/richeditor/assets/css/richeditor.css'.
```css
.fr-separator.fr-hs {
	clear: both;
	height: 1px;
	width: calc(96%);
	margin: 0 2px;
}
```
Changing this width-property's value to 100% results in the expected behavior.

##### Reproduce steps

1. Backend > Settings > Editor Settings > Toolbar Buttons: Copy the values written below the textarea into it and save.
`fullscreen, bold, italic, underline, strikeThrough, subscript, superscript, fontFamily, fontSize, |, color, emoticons, inlineStyle, paragraphStyle, |, paragraphFormat, align, formatOL, formatUL, outdent, indent, quote, insertHR, -, insertLink, insertImage, insertVideo, insertAudio, insertFile, insertTable, undo, redo, clearFormatting, selectAll, html`
2. Display October's Backend at a width of at least 1275px. (tested in Firefox 58.0.1 (64-bit))
3. Use the Froala editor - In my case:
    1. Install the [WYSIWYG Plugin](https://octobercms.com/plugin/anandpatel-wysiwygeditors).
    2. Select Froala in the plugin's settings: Backend > Settings > Wysiwyg Editors > Settings Tab
    3. Select Content where to display Froala in the plugin's settings: Backend > Settings > Wysiwyg Editors > Content Tab
    4. Navigate to content, where you activated Froala in the previous step

##### October build
v1.0.432

_Since the stylesheet is provided by October itself and not the plugin, I hope this is the right place to report the issue._

**Comment by LukeTowers** [comment]
@woeps What is the behaviour of changing that rule to 100% below 1275px (especially on mobile)?

**Comment by LukeTowers** [comment]
I've pinged @daftspunk to include this fix when he takes care of #3203

**Comment by LukeTowers** [comment]
@woeps is this fixed on the latest build?

**Comment by daftspunk** [comment]
Looks like there is no response. Let's reopen this if it still an issue.
