### ISSUE TITLE
Upon updating. get the error - Class 'TwitterAPIExchange' not found

### ISSUE THREAD

**Issue by PanikaValecha** [octobercms/october#3387]
##### Expected behavior
Website should open successfully

##### Actual behavior
Below is the screenshot:
![screen shot 2018-02-08 at 1 27 46 pm](https://user-images.githubusercontent.com/21162472/35996504-ea24febe-0cd3-11e8-89b6-17b1af0294e4.png)

![screen shot 2018-02-08 at 1 27 54 pm](https://user-images.githubusercontent.com/21162472/35996509-ed578534-0cd3-11e8-80c0-ea5e818796db.png)

I am quite sure that the exception is because of  the update

##### Reproduce steps
Just updated october cms. Settings>Updates & Plugins>
Upadted from build 419 to 431 (current build)

##### October build
431

How do I fix the error? Please assist upon the same.

**Comment by LukeTowers** [comment]
I am quite sure that the exception is because you are missing the TwitterAPIExchange class. Sounds like a dependency your site has that you've removed. Did you install via composer but then update with the web interface?

**Comment by PanikaValecha** [comment]
I just updated using the cms backend. I didn't install via composer.

**Comment by LukeTowers** [comment]
What's the contents of multi-theme-master/partials/cta2.htm?

**Comment by PanikaValecha** [comment]
<div class="twitter-space">
<h2 class="wow fadeInUp" data-wow-duration="300ms" data-wow-delay="0ms twitter-space2">We are now on TWITTER</h2>
  <div class="twitter-status wow fadeInUp" data-wow-duration="300ms" data-wow-delay="0ms">{{ this.page.status|md }}</div>
  <br/>
  <div class="wow fadeInUp" data-wow-duration="400ms" data-wow-delay="0ms">
  <img class="img img-circle" src="{{ this.page.profile_image_url }}"/><br/>
  <div class="twitter-text">{{ this.page.t_name }}</div>
  <a href="https://twitter.com/{{ this.page.screen_name }}" target="_blank" class="btn btn-primary">Follow @{{ this.page.screen_name }}</a>
  </div>
</div>

**Comment by PanikaValecha** [comment]
<div class="twitter-space">
<h2 class="wow fadeInUp" data-wow-duration="300ms" data-wow-delay="0ms twitter-space2">ECG IS ON TWITTER</h2>
  <div class="twitter-status wow fadeInUp" data-wow-duration="300ms" data-wow-delay="0ms">{{ this.page.status|md }}</div>
  <br/>
  <div class="wow fadeInUp" data-wow-duration="400ms" data-wow-delay="0ms">
  <img class="img img-circle" src="{{ this.page.profile_image_url }}"/><br/>
  <div class="twitter-text">{{ this.page.t_name }}</div>
  <a href="https://twitter.com/{{ this.page.screen_name }}" target="_blank" class="btn btn-primary">Follow @{{ this.page.screen_name }}</a>
  </div>
</div>

**Comment by PanikaValecha** [comment]
![screen shot 2018-02-08 at 2 01 50 pm](https://user-images.githubusercontent.com/21162472/35998022-a458fba6-0cd8-11e8-973f-7ae5141acffa.png)

**Comment by PanikaValecha** [comment]
//More code above this..
$requestMethod = 'GET';

  #   $twitter = new TwitterAPIExchange($settings);
    $response = $twitter->setGetfield($getfield)
            ->buildOauth($url, $requestMethod)
            ->performRequest();
    $tweets = json_decode($response);
    $tweet = $tweets[0];
    //$this->pr($tweet);

    $this->page["status"] = $this->stringToLink($tweet->text);
    $this->page["t_name"] = $tweet->user->name;
    $this->page["screen_name"] = $tweet->user->screen_name;
    $this->page["profile_image_url"] = $tweet->user->profile_image_url;
}

function stringToLink($text) {
    $string = preg_replace("~[[:alpha:]]+://[^<>[:space:]]+[[:alnum:]/]~", "<a href=\"\\0\">\\0</a>", $text);
    return $string;
}

function pr($e) {
    echo '<pre>';
    print_r($e);
    echo '</pre>';
}

the bold line of the code has the issue.

**Comment by LukeTowers** [comment]
Did you make the site? The library you are trying to use doesn't come with October, it must have been added by whoever made the site

**Comment by PanikaValecha** [comment]
@LukeTowers - Yes, I didn't make this website. However. I didn't change anything too. Previously, we had the build 419 and then I updated october cms and the current build is 431. So, if the library worked fine previously, it should work with the current update too.

**Comment by LukeTowers** [comment]
Not if the person who integrated the library tossed it in the vendor or modules directory without going through the correct process. Does your website directory have a composer.json file present?

**Comment by PanikaValecha** [comment]
Yes, it has a composer.json file

**Comment by LukeTowers** [comment]
Post the contents please

**Comment by PanikaValecha** [comment]
![screen shot 2018-02-09 at 11 36 16 am](https://user-images.githubusercontent.com/21162472/36043747-9288c950-0d8d-11e8-9d98-c976bc9e3386.png)

![screen shot 2018-02-09 at 11 36 08 am](https://user-images.githubusercontent.com/21162472/36043759-9c22dc4e-0d8d-11e8-9df8-d3977c81bfd3.png)

**Comment by LukeTowers** [comment]
Are you sure that's what's in the yourwebsite/composer.json file and not what's in the yourwebsite/vendor/october/rain/composer.json file?

**Comment by PanikaValecha** [comment]
This one is the /vendor/october/rain/composer.json file

**Comment by LukeTowers** [comment]
No, I need to know if you have a /composer.json file.

**Comment by PanikaValecha** [comment]
I can find another html/composer.json file that has the october cms information. It is that the one you are asking?

**Comment by PanikaValecha** [comment]
![screen shot 2018-02-09 at 12 59 52 pm](https://user-images.githubusercontent.com/21162472/36047395-363edff2-0d99-11e8-857c-2c9a958b828d.png)
![screen shot 2018-02-09 at 1 00 13 pm](https://user-images.githubusercontent.com/21162472/36047398-380d0548-0d99-11e8-831d-9a86bc028deb.png)

There is just this composer.json file , besides the one that I previously sent.

**Comment by LukeTowers** [comment]
I need to know if the website you are currently having problems with has a composer.json file for the website, which would be in the website_dir/composer.json file. 

The reason I need to know this is because the person who made the site for you should have included the dependency in the project's composer.json. This isn't an issue with October at any rate, it's an issue specific to your website. I suggest that you join the Slack team to continue the conversation there as Github issues aren't well suited to the type of assistance you require.

**Comment by LukeTowers** [comment]
That's what I'm looking for. You need to update the site by running `composer update` in your website root.

**Comment by PanikaValecha** [comment]
The composer file that I just sent is the one in the website directory..

**Comment by PanikaValecha** [comment]
oh..okay. Let me try updating it then. Thanks.

**Comment by PanikaValecha** [comment]
That worked!! thanks a lot for all your help. I really appreciate it. Thanks again!!

**Comment by LukeTowers** [comment]
Not a problem. Since your site is using composer, I highly recommend that you disable admin panel updates by setting `disableCoreUpdates` to true and only updating through composer in the future https://github.com/octobercms/october/blob/master/config/cms.php#L119
