### ISSUE TITLE
Changes made to markdown editor are not reflected on the website

### ISSUE THREAD

**Issue by PanikaValecha** [octobercms/october#3389]
##### Expected behavior
Markdown editor options do not work as expected. I created the following blog:
![screen shot 2018-02-08 at 2 21 40 pm](https://user-images.githubusercontent.com/21162472/35998976-8ab6191a-0cdb-11e8-8c82-250cc76564f7.png)

##### Actual behavior
When I preview the blog on the website, It shows "#" for headings as it is and "**" too. The headings are only shown when I use html header tags. I have been trying to fix this issue since long. I even updated October CMS from build 419 to the latest build - 431. But still the issue persists.

##### Reproduce steps
When I preview, I get the following view:
![screen shot 2018-02-08 at 2 21 49 pm](https://user-images.githubusercontent.com/21162472/35998981-8e3d2434-0cdb-11e8-8f38-4ce4aa251e2a.png)

##### October build
431.(same issue with build 419)

**Comment by LukeTowers** [comment]
How are you rendering the post? @PanikaValecha

**Comment by PanikaValecha** [comment]
@LukeTowers - I have a blog.htm page that displays all the blogs. When I preview the blog.htm page, I get the above attached preview.

**Comment by LukeTowers** [comment]
Can you post the contents of the blog.htm?

**Comment by PanikaValecha** [comment]
![screen shot 2018-02-09 at 11 33 01 am](https://user-images.githubusercontent.com/21162472/36043589-071d3536-0d8d-11e8-8abd-b5c38a1b3d72.png)

The code is linked to the  blog database.

**Comment by LukeTowers** [comment]
I need to see the contents of the blog partial, the partial where your blog post is actually getting rendered. My guess is it's missing the `|md` filter if using the `.content` property or it's not using the `.content_html | raw`

**Comment by PanikaValecha** [comment]
This doesn't involve any partial. I am just using the blog hyperlink in the footer of the website. That link is linked to the blog page and not partial.

**Comment by LukeTowers** [comment]
See line 18 in your screenshot.

**Comment by PanikaValecha** [comment]
![screen shot 2018-02-09 at 1 02 28 pm](https://user-images.githubusercontent.com/21162472/36047496-84e88586-0d99-11e8-944b-2b7acd31fb8d.png)

Oops, sorry..this is the content blog the blog partial.

**Comment by LukeTowers** [comment]
there's your problem. Change `{{ result | raw }}` to `{{ result | md }}`

**Comment by PanikaValecha** [comment]
That worked. Thanks a lot :)

**Comment by LukeTowers** [comment]
You're welcome
