### ISSUE TITLE
Cannot login backend users

### ISSUE THREAD

**Issue by WebShapedBiz** [octobercms/october#3391]
While front end is working fine, I'm getting this error on all of my backend users:

> Call to undefined method October\Rain\Database\Dongle::disableStrictMode()

https://imgur.com/a/0voZi

There was no CMS update recently, this just happened.
I remember a few years back there was a similar issue with the backend_users table but I forgot how I managed to fix it then.

EDIT: Found one backend user who was still logged in and can access CMS backend, all others that were logged out cannot login back again.

**Comment by SebastiaanKloos** [comment]
Looks like you have to take a look at your db settings. Something with the strict mode. I have had this issue before. Had to do with your db

**Comment by WebShapedBiz** [comment]
Thank you @SebastiaanKloos, my thoughts exactly. Maybe the hosting provider changed or updated something in MySQL server that caused this.

**Comment by WebShapedBiz** [comment]
Hi.

My problem continues. The hosting company does not have any sql_mode set:

-------- 
mysql> SELECT @@sql_mode; 
+------------+ 
| @@sql_mode | 
+------------+ 
| | 
+------------+ 
1 row in set (0.00 sec) 
-------- 

Still, I'm unable to log in. Also, I observed unusual data in backend_users columns. Is there a reference how those should look? What would be correct values for these?
- Permissions: one admin has blank and the other not
- is_activated: only one admin has 1, other admins 0

Thank you for your support.

**Comment by LukeTowers** [comment]
Permissions is fine, those are only the per user permission overrides; the rest of the permissions are loaded from the users role or if they're a superuser. Do you have a full stack trace?

**Comment by WebShapedBiz** [comment]
Thank you Luke.

At the moment I'm not having anything. This was my installation two years
ago without my involvement since. I'm trying to get some answers but it
would seem that the system is in half-updated state so this error may be
direct result of this.
However, one admin user's active session is allowing him to get to backend
and the front-end is working fine, even with several plugins using the
database (blog is one of them).

Best regards,

Sinisa Perovic
WebShaped.biz

Web: http://www.webshaped.biz
E-Mail: sinisaperovic@webshaped.biz
SkypeID: sinisaperovic
Telegram: @sinisaperovic

2018-02-12 16:40 GMT+01:00 Luke Towers <notifications@github.com>:

**Comment by LukeTowers** [comment]
Check the logs in storage, or check your server logs to see if you can get a stack trace out of them.

**Comment by LukeTowers** [comment]
Frontend doesn't work by the way

**Comment by WebShapedBiz** [comment]
Will do @LukeTowers, thank you.

**Comment by LukeTowers** [comment]
@WebShapedBiz were you able to solve the problem?

**Comment by WebShapedBiz** [comment]
No, I wasn't. The system was corrupted beyond repair so I couldn't rely on error messages to guide me. I'm already installing the new system.

Thank you for your time and effort.
