### ISSUE TITLE
storm.css : .loading-indicator shouldn't have background property set.

### ISSUE THREAD

**Issue by Alex360hd** [octobercms/october#3393]
Hello,

It's a very, very small thing, but the .loading-indicator css rules in storm.css add have a background:#f9f9f9; property.

I think that the correct behavior for that div is to have the same background than the element where it's displayed. So, you shouldn't write any background rules to that div, or eventually background: transparent;

Best regards,

Alex

**Comment by LukeTowers** [comment]
Submit a PR to the LESS file in question and include a before and after screenshot with both regular usage and usage where the background is causing a problem please.

**Comment by Alex360hd** [comment]
PR created.

First PR, be indulgent ^^

**Comment by LukeTowers** [comment]
Will close when PR merged
