### ISSUE TITLE
[Question] Scope for Relation Widget

### ISSUE THREAD

**Issue by wreighsantos** [octobercms/october#3395]
Is there a work around for this?
Currently, I'm using **Record Finder**, but I find it too much because I am just choosing from up to 10 items at most. What keeps me on using it is it supports `scope`.

Why I need scope? Because, in the relation that I will load, I need to filter it *based* from the currently selected **Model**.

Say, a group can have 4 membership grades, but some may have only 1.
So if I go to a group and add members to it, I should filter the **grade** that will be shown as options depending on the current group I'm in. I hope that it makes sense.

I've already tried using `scope` for my relation, it's messy and seems not to work. I've tried adding a dummy scope that filters the relation to a single item, but the Relation widget still shows all options. (sign that the scope didn't work, but it did run!)

Thank you.

**Comment by LukeTowers** [comment]
This already exists, there is the `scope` property on the relation formwidget just like on the recordfinder. Added in https://github.com/octobercms/october/commit/8ee7d3f5ae0e56b1e332ad18a8e6162365e4e4d7, I've also just added it to the documentation in https://github.com/octobercms/docs/commit/049457276c374e671a693bc831567f94c76a30bb

**Comment by wreighsantos** [comment]
does your answer resolve this issue? [#2076](https://github.com/octobercms/october/issues/2076) Thank you!

**Comment by LukeTowers** [comment]
Yes it does
