### ISSUE TITLE
Trailing data error when saving timestamps using MS SQL

### ISSUE THREAD

**Issue by Naph** [octobercms/october#3399]
##### Expected behavior
Saving timestamps using MS SQL

##### Actual behavior
Saving errors: "The format separator does not match Trailing data"

##### Reproduce steps
Login to backend when using MS SQL. Fails on updating last_login.

##### October build
october/backend:1.0.432
october/cms:1.0.432
october/rain:1.0.433
october/system:1.0.432

Fixed in laravel/framework 5.5.22
https://github.com/laravel/framework/pull/22052

**Comment by LukeTowers** [comment]
Update your Laravel framework version then with the following in your composer.json
`laravel/framework: "5.5@dev"`

**Comment by Naph** [comment]
At time of submitting this issue, my Laravel version was 5.5.33 and have investigated this further.

Referring to the commit log, the asDateTime method in HasAttributes was changed. There is an explicit str_replace for the format when a DateTime is created. This is because the static method DateTime::createFromFormat does not accept 'v' as a valid character. Here's a trace illustrating that October's Model's overridden method isn't reflecting this change.
```
  trace: {
    /var/www/html/vendor/nesbot/carbon/src/Carbon/Carbon.php:582 {}
    /var/www/html/vendor/jenssegers/date/src/Date.php:98 {}
    /var/www/html/vendor/october/rain/src/Database/Model.php:343 {
      › return Argon::createFromFormat(
      ›     $this->getDateFormat(), $value  // These arguments do not match the Laravel commit
      › );
      arguments: {
        $format: "Y-m-d H:i:s.v"
        $time: "2018-02-14 13:06:49.982"
      }
    }
    /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:738 {
      › {
      ›     return empty($value) ? $value : $this->asDateTime($value)->format(
      ›         $this->getDateFormat()
      arguments: {
        $value: "2018-02-14 13:06:49.982"
      }
    }
    /var/www/html/vendor/october/rain/src/Database/Model.php:359 {
      › 
      ›     return parent::fromDateTime($value);
      › }
      arguments: {
        $value: "2018-02-14 13:06:49.982"
      }
    }
    ...
}
```

**Comment by Naph** [comment]
Ah! No worries.
