### ISSUE TITLE
Update Laravel Release 5.6.x

### ISSUE THREAD

**Issue by testdnmedia** [octobercms/october#3400]
how to fix this, i want to upgrade laravel 5.5. * to 5.6. * ?
Problem
- don't install laravel/framework 5.6.x-dev|remove october/october No version set (parsed as 1.0.0)
...
- Can only install one of: laravel/framework[5.7.x-dev, v5.5.34].
- Installation request for laravel/framework ^5.6 -> satisfiable by laravel/framework[5.6.x-dev, 5.7.x-dev, v5.6.0, v5.6.1, v5.6.2, v5.6.3].

**Comment by munxar** [comment]
I't because the core library october/rain has laravel still set as version 5.5 which gives composer an unresolvable conflict because it can't install both version at the same time. I'm not a composer crack, but prop you can override this version in the root composer.json?

**Comment by LukeTowers** [comment]
@testdnmedia why do you want to upgrade Laravel? October will only officially support LTS releases of Laravel; they change and break things far too often to be continually upgrading. If you absolutely must have it and can't for some reason implement what you actually need some other way then you could in theory do `laravel/framework: 5.6 as 5.5` but I **strongly** recommend that you do not go down that route as we will not support it whatsoever.

**Comment by Teranode** [comment]
:V but I usually go down that route for maximum edginess, then again im not managing a large-scale application

**Comment by LukeTowers** [comment]
@Teranode then feel free to use the `as` composer trick to make it work; we're just not going to support it 😉

**Comment by j3rrey** [comment]
stumbling upon the same problem due to this [package](https://github.com/jenssegers/laravel-mongodb) requiring illuminate/events 5.6
I'll check backwards compatibility of the package
