### ISSUE TITLE
/storage/cms/disabled.json owner is root

### ISSUE THREAD

**Issue by ametad** [octobercms/october#3401]
##### Expected behavior
After visiting https://<domain>/backend/system/updates/manage the site is not crashing.

##### Actual behavior
After visiting https://<domain>/backend/system/updates/manage the site is not crashing. With error:

> ErrorException in Filesystem.php line 37:
> file_get_contents(/data/www/storage/cms/disabled.json): failed to open stream: Permission denied

`$ ls -lha`
```
drwxrwxr-x  5 www-data www-data  86 Feb 14 17:47 .
drwxrwxr-x  7 www-data www-data  87 May 16  2017 ..
-rw-rw-r--  1 www-data www-data  14 May 16  2017 .gitignore
drwxrwxr-x 23 www-data www-data 234 Feb 14 17:43 cache
drwxrwxr-x  3 www-data www-data  38 Feb 14 17:32 combiner
-rw-rw----  1 root     root       2 Feb 14 17:47 disabled.json
drwxrwxr-x 24 www-data www-data 244 Feb 14 17:43 twig

```

##### Reproduce steps
Remove the file storage/cms/disabled.json
Then go with browser to https://<domain>/backend/system/updates/manage

##### October build
419

**Comment by ametad** [comment]
Uhm... I am op for suggestions ;-)  Is this some wrong Linux config or indeed an October issue?

**Comment by LukeTowers** [comment]
Wrong linux config, I've never encountered an issue where root owned that process. If you were doing some artisan commands while running as root I could potentially see that happening, but you really shouldn't be doing that in the first place.

**Comment by ametad** [comment]
That is what I thought so too. But I do not use artisan commands with sudo, ever. Also, this behaviour is not triggered by an Artisan command, but by going to a specific page in the backend. When I delete the file and come back to that page, a second later the file torage/cms/disabled.json is appearing there again. All other files written by the system (uploads, cache, etc.) have www-data as owner, as expected. 

Well this is an older version, and in newer versions I don't see this behavior. This is something considered solved then I guess. 

Thanks Luke for your time!

**Comment by LukeTowers** [comment]
No problem; odd behaviour but at least it's not present in current versions!
