### ISSUE TITLE
How do I upload a file from backend (not using the media manager or file uploader)?

### ISSUE THREAD

**Issue by joelamltc** [octobercms/october#3403]
As above. I do want my files/images can be manipulated by myself before moving to server.
I did try to create a traditional file upload widget using html `<input type="file">` but not success. 
I cannot get my file correctly when the form is being submitted.
Any suggestion or ideas can be advised?

Huge Thanks.

**Comment by danhrrn** [comment]
In October, images are stored in a way that they need to be uploaded by the system ideally. Look at what is going on when a file is uploaded natively to an installation, and if you still feel it necessary for you to build this plugin, call the methods defined there.

**Comment by joelamltc** [comment]
Would you like to explain more？

**Comment by LukeTowers** [comment]
@joelamltc a better option if you want to manipulate the file on upload would be to extend the \System\Models\File model with your custom file model class and override the relevant methods to modify the uploaded file accordingly.
