### ISSUE TITLE
Issues installing OctoberCMS

### ISSUE THREAD

**Issue by gaalgergely** [octobercms/october#3406]
##### Expected behavior
I use the installer, the step: Create admin account
SQL: alter table `sessions` add unique `sessions_id_unique`(`id`)

##### Actual behavior
Something went wrong during the installation. Please check the log file (install_files/install.log) or see the documentation for more information.
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `sessions` add unique `sessions_id_unique`(`id`))

10.1.30-MariaDB

![phpinfo](https://user-images.githubusercontent.com/9944882/36357125-a88bfd80-14f9-11e8-9c11-9bfc97c41b73.png)

##### Reproduce steps
Try to install with the octoberCMS installer.

##### October build
Where can I check it? (latest one 2018.02.18 from official site)

**Comment by wintstar** [comment]
Look here:
https://github.com/octobercms/october/issues/3405

https://github.com/octobercms/october/issues/3402

and many more:

https://www.google.de/search?q=laravel+long%3B+max+key+length+is+767&oq=laravel+long%3B+max+key+length+is+767&aqs=chrome..69i57j69i60.6998j0j4&sourceid=chrome&ie=UTF-8

**Comment by LukeTowers** [comment]
See https://github.com/octobercms/october/commit/bd9f88587f5adad66866294d22a598aa195cff4b. The official fix will come in Build 434 when @daftspunk pushes that soon; but if you need it fixed sooner then upgrade MariaDB to 10.2.

**Comment by LukeTowers** [comment]
This should be fixed now!

**Comment by gaalgergely** [comment]
Works fine. Thank you!

**Comment by LukeTowers** [comment]
@gaalgergely Great to hear it!

**Comment by flakerimi** [comment]
It doesn't work when attached project id / paid plugin

**Comment by LukeTowers** [comment]
Sounds like a completed unrelated issue @flakerimi
