### ISSUE TITLE
Add ability to extend casts array on models

### ISSUE THREAD

**Issue by scottbedard** [octobercms/october#3407]
##### Expected behavior
N/A

##### Actual behavior
N/A

##### Reproduce steps
N/A

##### Proposed feature

Currently, there is no way (that I could find) to extend the `casts` array of another plugin's model. The feature I'm proposing would be including an `addCasts` method to live alongside [these helpers](https://github.com/octobercms/library/blob/develop/src/Database/Model.php#L673).

If this is acceptable, I'll get started on a PR.

##### October build
433

**Comment by SebastiaanKloos** [comment]
@scottbedard There are more arrays that could not be extended. It is only possible to override the array on other models

**Comment by LukeTowers** [comment]
Sure, sounds good to me.

**Comment by scottbedard** [comment]
Closed by https://github.com/octobercms/library/pull/306
