### ISSUE TITLE
Backend Tabs and Google Maps issue

### ISSUE THREAD

**Issue by adc91** [octobercms/october#3409]
Hello guys, 

I am having problems implementing a Google Maps map using multiple tabs in October CMS.

Is there any way to detect the TAB change event in the backend and act accordingly to redo the map?

I think it is due to a problem in Google Maps itself with the elements with the property visible in hidden, which is why I need to apply some hack.

## Tab active
![Image Tab 1](https://i.imgur.com/egRNtUy.png)

## Change other tab
![Image Tab 2](https://i.imgur.com/SscExpe.png)

##### October build
433

**Comment by LukeTowers** [comment]
This is due to how Google Maps works, you will need to trigger a rerender on the map element when you switch tabs and make it visible; the map listens for initial render and bases its appearance after its visibility.

**Comment by adc91** [comment]
@LukeTowers yes, it is possible to call a trigger to load the element assigned to the map that is visible.

The problem I have mainly is to detect a change in the october backend tab to execute the trigger.

#### Trigger code
`google.maps.event.trigger (map, 'resize');`

**Comment by LukeTowers** [comment]
Try listening to `oc.updateUi` on the window: https://github.com/octobercms/october/blob/master/modules/system/assets/ui/js/tab.js#L59

**Comment by adc91** [comment]
Thanks @LukeTowers,

I leave the code in case someone else can help.
```
$(window).on('oc.updateUi', function(){
    // code
});
```

**Comment by LukeTowers** [comment]
Not a problem, glad I could point you in the right direction!
