### ISSUE TITLE
Plain text database credentials in config/database.php

### ISSUE THREAD

**Issue by tonylangworthy** [octobercms/october#3410]
Are there any plans to move the database credentials into a .env file upon installation?

**Comment by LukeTowers** [comment]
Yes, it already exists. `php artisan october:env`: http://octobercms.com/docs/console/commands#october-env-command

**Comment by tonylangworthy** [comment]
Very nice! Thank you!

**Comment by LukeTowers** [comment]
Take a look at `php artisan october:mirror public --relative` as well for additional security goodness 😄

**Comment by tonylangworthy** [comment]
Excellent! I just installed this today and have finally read the docs. Very nice system!!
