### ISSUE TITLE
Unknown database type bit requested

### ISSUE THREAD

**Issue by bfloren** [octobercms/october#3413]
##### Expected behavior
Create new table via Builder
##### Actual behavior

table not created.

"Unknown database type bit requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it." on line 423 of /Users/brett/Code/Project11/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php

##### Reproduce steps

![screen shot 2018-02-23 at 3 04 07 pm](https://user-images.githubusercontent.com/2178782/36614614-44820d38-18ab-11e8-8bda-b377478bad1c.png)

##### October build
4.3.3 using mysql 5.7.21

I am just looking for the **recommended method** to address this problem.  I am not sure why I am getting a bit issue with mysql 5.7.21 -- I read about another similar issue here dealing with json type but I can not find anything about bit type.

**Comment by danhrrn** [comment]
Please post this issue on https://github.com/rainlab/builder-plugin/issues instead and close this.
