### ISSUE TITLE
FormatException not found

### ISSUE THREAD

**Issue by papangproduction** [octobercms/october#3416]
Hi

##### Expected behavior

I try to handle the ModelNotFoundException in boot of my **plugin.php** with this code : 

```
App::error(function(\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
     abort(404);
});
```
When i use firstOrFail method, the handler is activated and debug push me in **october\rain\src\Foundation\Exception\Handler.php** line 153 : 

```
try {
     $response = $handler($exception, $code, $fromConsole);
}
catch (Exception $e) {
     $response = $this->formatException($e);
}
```

But the formatException method is not found.

##### October build

Current Build : 434
PHP version : 7.1.12

**Comment by dmeijboom** [comment]
It seems like `formatException` is no longer available Laravel 5> (it looks like it was removed since Laravel 4.2). However this is a bug in: `octobercms/library`, is it an idea to close this issue and create a new issue in the library project?

**Comment by LukeTowers** [comment]
@dmeijboom this is an appropriate place for the issue; octobercms/library doesn't allow issues - any OctoberCMS issue gets tracked in this repository.

I'm not sure what you mean by it was removed; I can see it here: https://laravel.com/api/5.5/Illuminate/Exception/Handler.html#method_formatException

**Comment by dmeijboom** [comment]
@LukeTowers Good to know! I mean that even though this method is shown in the documentation it doesn't seem to exist in their codebase anymore (see: https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Exceptions/Handler.php). That or I can't find it.

**Comment by LukeTowers** [comment]
Odd; seems like their API docs are being generated from 4.2. Do you have any thoughts on a resolution for this issue @dmeijboom?

**Comment by dmeijboom** [comment]
@LukeTowers I can create a pull-request which simply re-implements the `formatException` method in Handler.php?

**Comment by LukeTowers** [comment]
Sure, what exactly is the method supposed to do though?

**Comment by dmeijboom** [comment]
In Laravel the only thing it does is return "Error in exception handler." or a little more information when debug is enabled. It looks like they refactored the handler class in 5.5.

**Comment by LukeTowers** [comment]
@dmeijboom Could you figure out what the point of it being called here in October was and provide some recommendations on a fix for this?

**Comment by MWalid** [comment]
Any updates on this?

**Comment by yapsr** [comment]
Original source code in laravel 4.2 framework for formatException can be found here: https://github.com/laravel/framework/blob/4.2/src/Illuminate/Exception/Handler.php#L328

**Comment by yapsr** [comment]
Fix would be to simply add this method in `\October\Rain\Foundation\Exception\Handler`:

    function formatException($e) {
        if (!empty($this->debug))
        {
            $location = $e->getMessage().' in '.$e->getFile().':'.$e->getLine();
            return 'Error in exception handler: '.$location;
        }
        return 'Error in exception handler.';
    }

**Comment by LukeTowers** [comment]
@yapsr we could add that, but I'm more interested in what's the point of it to begin with and if Laravel removed it should we also look at removing it?

**Comment by Samuell1** [comment]
Was this fixed?

**Comment by coltoneakins** [comment]
I am posting an alternative solution here for a custom error handler because of this issue's visibility on Google.

---
Rather than using October's `App::error` for a custom error handling, try the following:

1. Create a custom error handler that inherit's from October's error handler. For example, create the following class in `plugins/{AUTHOR}/{PLUGIN}/classes/CustomHandler.php` (assuming you are developing a plugin for OctoberCMS). Override the `render` method of the handler.

    ```php
    <?php

    namespace {AUTHOR}\{PLUGIN}\Classes; //<-- CHANGE ME OBVIOUSLY FOR YOUR PLUGIN

    use October\Rain\Foundation\Exception\Handler;
    use Illuminate\Support\Facades\Event;
    use Illuminate\Support\Facades\Response;
    use Exception;
    use Illuminate\Database\Eloquent\ModelNotFoundException; // As an example exception you want to handle ...

    /* Custom error handler which replaces the default error handler for OctoberCMS. */
    class CustomHandler extends Handler
    {
        /**
        * Render an exception into an HTTP response.
        *
        * @param  \Illuminate\Http\Request  $request
        * @param  \Exception  $exception
        * @return \Illuminate\Http\Response
        */
        public function render($request, Exception $exception)
        {
            /* Custom JSON response for ModelNotFoundException exceptions. */
            if($exception instanceof ModelNotFoundException){
                return Response::json(['error' => 'A record was not found for the resource that was requested.'], 404);
            }

            /* The rest of this code is just the 'default' code from OctoberCMS' error handler. */
            /* The only change is the code above this comment where I handle a specific exception in a unique way.*/
            /* i.e. I decided to return JSON for the error rather than an HTML error page (in debug mode). */
            if (!class_exists('Event')) {
                return parent::render($request, $exception);
            }

            $statusCode = $this->getStatusCode($exception);
            $response = $this->callCustomHandlers($exception);

            if (!is_null($response)) {
                return Response::make($response, $statusCode);
            }

            if ($event = Event::fire('exception.beforeRender', [$exception, $statusCode, $request], true)) {
                return Response::make($event, $statusCode);
            }

            return parent::render($request, $exception);
        }
    }
    ```
    
 2. Then, in your plugin registration file `Plugin.php`, add a `boot` method with the following code:
 
     ```php
     
    <?php namespace {AUTHOR}\{PLUGIN};

    use System\Classes\PluginBase;
    use LP\Unvaled\Classes\CustomHandler; //<-- IMPORTANT
    use Illuminate\Contracts\Debug\ExceptionHandler;  //<-- IMPORTANT

    class Plugin extends PluginBase
    {
        /**
        * @var array Plugin dependencies
        */
        public $require = [];


        public function registerComponents()
        {
        }

        public function registerSettings()
        {
        }

        public function boot(){


            /* Replace the default error handler of OctoberCMS to return JSON format responses instead. */
            /* Also, this is used in order to control the responses for certain types of errors/exceptions. */
            /* We are going about it this way because App::error (as mentioned in the documentation for OctoberCMS), */
            /* was not returning the response properly presumably because of a bug. Argh... */
            $this->app->bind(
                ExceptionHandler::class,
                CustomHandler::class
            );


        }


    }
    
     ```
     
Since, the new `CustomHandler.php` was added to the `classes` directory, the new class should already be picked up. No need for `composer dump-autoload -o` or changes to the `composer.json`.

That is it. When the `ModelNotFoundException` occurs, the response given to the web browser will be JSON that you wrote (from the custom error handler we created).

Relevant links:

- https://blog.sarav.co/registering-custom-exception-handler-laravel-5/
- https://laravel.com/docs/5.8/container#binding
- https://octobercms.com/forum/post/is-it-posible-to-bring-back-the-app-directory-for-native-laravel

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/library/commit/53ef96b69925ed5310581de1608d96b2dbc127e9

**Comment by yapsr** [comment]
Excellent!
