### ISSUE TITLE
How to extend/override *.js files from another plugins in my Plugin.php?

### ISSUE THREAD

**Issue by iboved** [octobercms/october#3420]
How to extend/override js files from another plugins?
For example, I want to extend/override [multilingual.js](https://github.com/rainlab/translate-plugin/blob/master/assets/js/multilingual.js) file from [Rainlab.Translate](https://octobercms.com/plugin/rainlab-translate) plugin. I want to change some behavior in this file, but I do not want to edit this file directly.
How can I do it inside my plugin (e.g. in Plugin.php file)?
Thank you in advance.

**Comment by LukeTowers** [comment]
In order to accomplish this you'll need to understand how to extend Javascript in general; and how to load scripts on backend controllers.

**Comment by iboved** [comment]
I know how to load scripts on backend controllers.
Can you write a simple example how to extend Javascript please (or send a link to an example)?
Thanks.

**Comment by LukeTowers** [comment]
To extend something in javascript you would have to have a hook to attach to. You could try to modify the `$.fn.Multilanguage` object directly; or in this specific case you could just attach to the same element that it is `$el = $('ul.ml-dropdown-menu', this.$el)` and attach another event handler to it with `$el.on('click', '[data-switch-locale]', function() {});`
