### ISSUE TITLE
composer update error

### ISSUE THREAD

**Issue by testdnmedia** [octobercms/october#3422]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 3 updates, 0 removals
  - Updating erusev/parsedown (1.6.4 => 1.7.0): Loading from cache
  - Updating nesbot/carbon (1.22.1 => 1.23.0): Loading from cache
  - Updating nikic/php-parser (v3.1.4 => v3.1.5): Loading from cache
Writing lock file
Generating autoload files
> php artisan october:util set build

In Date.php line 10:
                                                                               
  Declaration of Jenssegers\Date\Date::diffForHumans(?Carbon\Carbon $since =   
  NULL, $absolute = false, $short = false) should be compatible with Carbon\C  
  arbon::diffForHumans(?Carbon\Carbon $other = NULL, $absolute = false, $shor  
  t = false, $parts = 1)                                                       
                                                                               

Script php artisan october:util set build handling the post-update-cmd event returned with error code 1
In Date.php line 10:
                                                                                                                                                                               
  Declaration of Jenssegers\Date\Date::diffForHumans(?Carbon\Carbon $since = NULL, $absolute = false, $short = false) should be compatible with Carbon\Carbon::diffForHumans(  
  ?Carbon\Carbon $other = NULL, $absolute = false, $short = false, $parts = 1)

**Comment by LukeTowers** [comment]
What version of Jenssegers\Date do you have installed?

**Comment by testdnmedia** [comment]
Updating jenssegers/date (v3.2.12 => v3.0.0-beta)

**Comment by LukeTowers** [comment]
which one works?

**Comment by Teranode** [comment]
@LukeTowers Carbon recently made an update (1.22.1 => 1.23.0),  Jenssegers does not have that update reflected so it's suggested to stay on 1.22.1 of Carbon til Jessegers update's their code. (though i manually updated it myself not sure when they're gonna do theirs.

**Comment by testdnmedia** [comment]
remove "nesbot / carbon": "^ 1.23" in composer.json file and composer update, now normal again

**Comment by LukeTowers** [comment]
@Teranode could you submit an appropriate PR to jessegers/date?

**Comment by Teranode** [comment]
@LukeTowers as of 6 hours ago, the package has been updated to reflect the update of Carbon, so everything should work fine now.

**Comment by LukeTowers** [comment]
Thanks for the update @Teranode, I'll leave it open a little longer for other people that might come across the issue.
