### ISSUE TITLE
Redis over socket

### ISSUE THREAD

**Issue by PSSGCSim** [octobercms/october#3426]
##### Expected behavior
To connect to redis UNIX socket

##### Actual behavior
Does not work

##### Reproduce steps
Set redis config as follows:
```
'redis' => [

    'cluster' => false,

    'default' => [
        'host'     => '/www/xx.xxxxxxxxxxx/run/redis01.sock',
        'password' => 0,
        'port'     => 0,
        'database' => 0,
    ],
]
```

##### October build
434

**Comment by LukeTowers** [comment]
Definitely not an October issue, possibly related to a misconfiguration? See https://github.com/nrk/predis/issues/277. At any rate, "Does not work" is not enough information to do anything about anything.

**Comment by PSSGCSim** [comment]
Thanks for linking the other project. Sorry, I did not know there is some other plugin in use. It was indeed by using wrong configuration. I have edited the config according to the issue.
