### ISSUE TITLE
Traits not available as behaviours (yet)

### ISSUE THREAD

**Issue by joakimbo** [octobercms/october#3427]
Edit: The functionality requested here is being moved, please see [this octobercms/library PR](https://github.com/octobercms/library/pull/310) for updates.

Traits cannot be used to extend a model (not a bug).

    SomeModel::extend(function ($model)
    {
        $model->implement[] = 'October\Rain\Database\Traits\Purgeable';
        $model->addDynamicProperty('purgeable', ['propertyToPurge']);
    });

The code above wont work since traits cannot be used to extend a model. Instead the traits should get translated to behaviours.

```diff
- $model->implement[] = 'October\Rain\Database\Traits\Purgeable';

+ $model->implement[] = 'Backend\Behaviors\Purgeable';
```

**October build:** 434

**Comment by LukeTowers** [comment]
@JoakimBo what do you think of the method I implemented in https://github.com/CptMeatball/notifiable-user/pull/1 to make integrating model traits as behaviors easier?

**Comment by JoakimBo** [comment]
@LukeTowers If I understand that code correctly that looks like a much smarter thing to do, it would certainly cut down on the code needed by the behaviours but  I have atleast one concern. This isnt a huge problem but the exceptions Traits throw when checking after certain properties identify them as Traits i.e

```
throw new Exception(sprintf(
    'You must define a $purgeable property in %s to use the Purgeable trait.', get_called_class()
));
```

Could you also elaborate on why it rather extends ModelBehaviour than ExtensionBase?

**Comment by LukeTowers** [comment]
@JoakimBo it extends ModelBehavior which extends ExtensionBase. ModelBehavior just does the constructor for us. I'm thinking I'd like to build the proxying with `__call()`, `__get()`, `__set()`, and perhaps `__callStatic()` if required straight into the ModelBehavior base so implementing traits as model behaviors would be as easy as
```php
class Encryptable extends ModelBehavior
{
     use \October\Rain\Database\Traits\Encryptable;
}
```
I'm concerned about side effects of doing the proxying though; do you have any thoughts on that? 

I'm not too worried about the exceptions, we could always override them if absolutely necessary but even just leaving them to say Trait is fine. I'm thinking we would provide these behaviors directly in the October\Rain library itself too, along with the traits.

**Comment by JoakimBo** [comment]
@LukeTowers I tried to do purgeable as proxy (didnt put too much effort into it so might just be that). Didn't really get to a state where it was working like I wanted so I will have to test it more. I can't really foresee the side effects of using the magic methods but it might be wise to more forward carefully with them since they would run at every applicable call. They also invite a layer of abstraction which might make understanding the proxy behaviours a bit difficult.

**Comment by LukeTowers** [comment]
Purgable probably requires proxies for the __set and/or __get methods

**Comment by JoakimBo** [comment]
Most likely, to be honest I haven't used the magic methods before so I don't have much experience with them. I will probably continue translating the traits to behaviours as I have previously started until I can wrap my head around the magic methods.

**Comment by LukeTowers** [comment]
`bootTraits()` could be reimplemented in the base behaviour class so you don't have to manually call the boot method of the applicable trait. 

The issue is in your getter:
```php
public function __get($name)
{
    if (!property_exists($this, $name)) {
        return $this->model->{$name};
    }
}
```
`$this->model` is an object, not an array so you need object notation `->`

**Comment by JoakimBo** [comment]
Hmm, ok will try that soon and update. I was under the impression that it would work in the manner explained in [Example 2](http://php.net/manual/en/sdo.sample.getset.php)

**Comment by LukeTowers** [comment]
The bindEvent happens in the `static::extend` call, which would be extending the behavior, not the model, so we would also need to proxy it (which is definitely getting into tricky territory)
```php
public static function extend($callable)
{
    $modelClass = get_class($this->model); 
    // accessing an instance property of the behavior class in a static method is gross but potentially doable
    return $modelClass::extend($callable);
}
```

And the array syntax isn't as widely used or supported; especially when it comes to all the magic behind the scenes of Laravel

**Comment by JoakimBo** [comment]
Good to know about the array syntax. I havent checked all availible Traits yet but if the only static method is the boot couldnt they be overriden in the behaviour and that way bypass the static?

**Comment by LukeTowers** [comment]
They could, I'm just conducting a thought experiment on how we could setup the base class to be as friendly as possible to model traits. Probably not necessary to do all that magic but it's worth considering.

**Comment by JoakimBo** [comment]
It would certainly be nice to only have to 'Use' any trait and have it work as behaviour :)

**Comment by LukeTowers** [comment]
Indeed :) How about you create a base `ModelTraitBehavior` class that proxies the __call, __get, __set methods extending `ModelBehavior` and then implement the traits as behaviors in a database/behaviors folder in the library and make a PR so we can go from there?

**Comment by JoakimBo** [comment]
Sounds ok, I'll try to get atleast one trait up later as behaviour with magic methods.

**Comment by JoakimBo** [comment]
@LukeTowers Put up the PR in the library repo now, contains the bare minimum as a starting point.

**Comment by daftspunk** [comment]
Traits are designed to be statically implemented behaviors. This was a tough decision to make in the early stages of the design. The core rarely supplies model behaviors since it makes things too complex to debug, especially when you have behaviours trying to override other behaviors. Simply using traits as a primary definition simplify this a lot

In short, the October library/core should only provide traits. Other developers should ship their behaviors in their own plugins. Modules are the exception to the rule

Hope this makes sense. Happy to elaborate further if required @joakimbo
