### ISSUE TITLE
Illuminate Mailer::queue($view, $queue = NULL) must be compatible with MailQueue::queue($view, array $data, $callback, $queue = NULL) 

### ISSUE THREAD

**Issue by kdoonboli** [octobercms/october#3429]
After upgrading to latest version (from pre php7), I can no longer send emails. User registration doesn't work either as it can't send emails.

```
Symfony\Component\Debug\Exception\FatalErrorException: 
Declaration of Illuminate\Mail\Mailer::queue($view, $queue = NULL) 
must be compatible with Illuminate\Contracts\Mail\MailQueue::queue($view, array $data, $callback, $queue = NULL) 
in /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:17
```

##### Reproduce steps
I updated the build and the rest of the plugins through the "Updates and Plugins" menu.

##### October build
4.34

**Comment by kdoonboli** [comment]
Got it to work thanks to #2874 

I searched for "Illuminate\Mail\Mailer" text in my plugins folder and found an outdated plugin having its own vendor folder with copies of old illuminate files. Then I followed the suggestion in #2874 . I deleted the vendor folder, then I ran the "composer update" command inside that plugin folder itself so it would only read its own composer.json

**Comment by bkrajendra** [comment]
For me i got this error due to plugin vdomah/excel
removing this plugin fixed my issue.
Ive reported this issue to developer
[https://github.com/vdomah/octoexcel/issues/10](https://github.com/vdomah/octoexcel/issues/10)

**Comment by bkrajendra** [comment]
recent update resolves all issues.
