### ISSUE TITLE
Publishing Blog Posts in the Future

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#3431]
##### Expected behavior
The system shouldn't allow to set future date for a blog post. Otherwise it should really publish it in the future using scheduling tasks and keep the post hidden until then.

##### Actual behavior
You can create a post with future date and it will be available:

![image](https://user-images.githubusercontent.com/3897579/37027324-ea112f92-2128-11e8-8845-b124e7da0cd6.png)

##### Reproduce steps
Create a new post and set its "published" date to something in the future.

##### October build
434

I'm not so familiar with October conventions, so maybe this behaviour is expected actually.

If no, I think it would be a nice new feature once fixed.

**Comment by JoakimBo** [comment]
@GinoPane Is this refering to the RainLab.Blog plugin? If so this probably belongs to [RainLab Blog Repo](https://github.com/rainlab/blog-plugin)

**Comment by LukeTowers** [comment]
@GinoPane: @JoakimBo is correct, this issue belongs in the RainLab.Blog repository.

**Comment by GinoPane** [comment]
@JoakimBo cool! Thanks for pointing out.

**Comment by nolybom** [comment]
@GinoPane Did you cross a possible solution for that issue?

**Comment by GinoPane** [comment]
@nolybom actually it was not an issue. I was logged in to the backend area as admin at the moment and that's why all posts were displayed on the frontpage.
If you are guest you won't see those posts.
