### ISSUE TITLE
Extend model with addDynamicProperty causes SQL column exception

### ISSUE THREAD

**Issue by JoakimBo** [octobercms/october#3433]
#### Expected behavior
Extend a model that has ExtendableTrait, add dynamic property and create new model that saves to database.

#### Actual behavior
Extend a model that has ExtendableTrait, add dynamic property and create new model, upon save throws SQL error stating column name not found of added property.

#### Reproduce steps
1. Write plugin that extends a model which uses the [ExtendableTrait](https://github.com/octobercms/library/blob/master/src/Extension/ExtendableTrait.php).
 In my case it was extending UserGroup from RainLab.User.
2. Add a dynamic property using the addDynamicProperty function.
```
UserGroupModel::extend(function($model) {
    $model->addDynamicProperty('test');
});
```
3. Open the backend forms and type in info for new model of the same type that has been extended
4. Click create and model saves to database except it will produce an SQL error stating that the column with the name of the added property cant be found.

#### October build
434

Maybe I'm just oblivious to how this is supposed to work, if so please do tell me.   
Would one have to extend the table for the model as well?

**Update:** Okay so I think what is happening is that by extending the model it is also extending it *before* the actual model exists (in the context of create) and therefore tries to push it to the db without guarding the property by default.   
Would appreciate if someone could confirm this, if this is whats happening maybe this could be added to the docs?

**Comment by JoakimBo** [comment]
@LukeTowers So after doing some digging I don't think this is a bug per se. It's more of a consequence of how attributes are handled by both october and laravel.   
First things first, if arrays are added dynamically they will be rejected in the create context by [line 518 of library/Model.php](https://github.com/octobercms/library/blob/master/src/Database/Model.php#L518)
The next thing I think is causing this behaviour is that when Laravel [performs an insert](https://github.com/illuminate/database/blob/master/Eloquent/Model.php#L672) it simply pulls the available attributes and tries to push them to the database. Since our addDynamicProperties function has added this propery in the create context this it will be pushed to db causing an exception.

**Comment by LukeTowers** [comment]
@JoakimBo I'm assuming this is in regards to the implementation of traits as behaviors? If so, you can add a PR to the docs for using the behaviors (i.e. add a file for database-behaviors and link to it from the traits section) and in the general description inform people of the need to purge dynamic properties from the model before saving, and the need to include 'purgeable'  as one of those properties if they're accomplishing that with the purgeable behavior.

**Comment by LukeTowers** [comment]
Additionally, in the implementation of those behaviors, perhaps we should add a check to see if the model already has the trait added to it in code so that we don't try to double add it

**Comment by JoakimBo** [comment]
I haven't had the time to further develop the magic method way (I just used a translated to behavior version). When I do I'll try to remember to implement the check and make a PR for the docs to be updated about them.

**Comment by LukeTowers** [comment]
Okay, sounds good.

**Comment by iboved** [comment]
I have the same problem. I try to implement a translation for an external plugin. I add the following:
```
Product::extend(function ($model) {
    $model->implement[] = '@RainLab.Translate.Behaviors.TranslatableModel';
    $model->addDynamicProperty('translatable', ['description']);
});
```
But when I try to create the Product model, I get the following error:
`Unexpected type of array when attempting to save attribute "translatable", try adding it to the $jsonable property.`

Why `addDynamicProperty()` method adds `translatable` property to the model `attributes`?

**Comment by LukeTowers** [comment]
@iboved because it adds it as a property to the model and Laravel saves all properties that it doesn't know about explicitly. You need to also make sure that the model implements purgeable and add `translatable` to the `purgeable` property.
