### ISSUE TITLE
How can I access current language and default language in my js files?

### ISSUE THREAD

**Issue by iboved** [octobercms/october#3434]
Hi!
I have added my "custom.js" file to my controller.
```
    public function update($recordId, $context = null)
    {
        $this->addJs('/plugins/acme/demo/assets/js/custom.js');

        return $this->asExtension('FormController')->update($recordId, $context);
    }
```
Now I want to make the "Slug" field be generated only when I edit the "Title" field in the default language. For example, I have 2 languages - EN (default) and RU. I want the "Slug" field be generated only when I edit the "Title" field in English (but when I edit the "Title" field in Russian, I don't want the "Slug" be generated).
![screen](https://user-images.githubusercontent.com/9253603/37156511-ef56c4b8-22ee-11e8-828f-9944365b711b.PNG)
To do this, I need to access current language and default language in my "custom.js" file and then make some logic with this data. I can access $.fn.multiLingual variable in my "custom.js" file, but how can I access current language and default language?

Thank you very much for your help.

**Comment by LukeTowers** [comment]
This is a question better suited for the [RainLab.Translate](https://github.com/rainlab/translate-plugin) plugin repository.
