### ISSUE TITLE
Subscribing to backend.user.login event

### ISSUE THREAD

**Issue by EdisonLV** [octobercms/october#3435]
##### Expected behavior
Able to listen for the event in a plugin's boot method

##### Actual behavior
Event listener isn't triggered for ```backend.user.login``` event

##### October build
Latest

~~~
    public function boot()
    {   
        Event::listen('backend.user.login', function($user) 
        {
            dd($user);
        });         
    }
~~~

**Comment by LukeTowers** [comment]
Docs on this here: https://octobercms.com/docs/plugin/registration#elevated-plugin. Feature, not bug.
