### ISSUE TITLE
Declaration of Illuminate\Support\Carbon::__set_state(array $array) should be compatible with Carbon\Carbon::__set_state($state)

### ISSUE THREAD

**Issue by PanikaValecha** [octobercms/october#3436]
##### Expected behavior
The website should load

##### Actual behavior
Declaration of Illuminate\Support\Carbon::__set_state(array $array) should be compatible with Carbon\Carbon::__set_state($state)

![screen shot 2018-03-09 at 10 13 49 am](https://user-images.githubusercontent.com/21162472/37220053-a2ba082e-2382-11e8-8f78-431af377d064.png)

##### Reproduce steps
I ran composer update command and it shows the below message:
*** You were kicked from #october by Ex: (Declaration of Illuminate\Support\Carbon::__set_state(array $array) should be compatible with Carbon\Carbon::__set_state($state))

##### October build
431 may be

**Comment by LukeTowers** [comment]
Full stack trace please.

**Comment by PanikaValecha** [comment]
![screen shot 2018-03-09 at 10 26 37 am](https://user-images.githubusercontent.com/21162472/37220627-6c560e52-2384-11e8-9e4e-57bcd15ac958.png)
![screen shot 2018-03-09 at 10 26 55 am](https://user-images.githubusercontent.com/21162472/37220628-6c6cdec0-2384-11e8-96e9-895764bc772d.png)

**Comment by LukeTowers** [comment]
Error is the fault of Laravel / Carbon: https://github.com/laravel/framework/issues/23465. Hopefully a fix will be backported to Laravel 5.5. Until then, you can manually apply the changes in https://github.com/laravel/framework/commit/4bda20be9f607d776f5cac857550232cd099f82b locally and then run `composer update` again.

**Comment by LukeTowers** [comment]
See also https://github.com/laravel/framework/pull/23464

**Comment by PanikaValecha** [comment]
Thanks!! Can you mention the path of the composer.json file you are referring to?

**Comment by LukeTowers** [comment]
it'd be in vendor/laravel/framework

**Comment by PanikaValecha** [comment]
Thank you. This worked!!

**Comment by LukeTowers** [comment]
Merged into Laravel 5.5.39: https://github.com/laravel/framework/releases/tag/v5.5.39
