### ISSUE TITLE
Register plugin routes in unit testing environment

### ISSUE THREAD

**Issue by scottbedard** [octobercms/october#3437]
I'm opening this issue to discuss auto-loading plugin routes in our unit testing environment. Currently, Laravel's [HTTP testing utilities](https://laravel.com/docs/5.5/http-tests) are not that useful because all plugin routes result in a 404. I was able to remedy this by [extending this method](https://github.com/octobercms/october/blob/master/tests/PluginTestCase.php#L15-L43) to also require in the various `routes.php` files.

```php
public function createApplication()
{
    $app = parent::createApplication();

    require __DIR__.'/../routes.php';

    return $app;
}
```

This works, but in my opinion isn't that pretty. Would October be open to including this in the base test case? Either by default, or with a boolean to toggle the behavior. An API for that might look something like this...

```php
class PluginTestCase extends BasePluginTestCase
{
    public $registerPluginRoutes = true;
}
```

If this feature is acceptable, I'll get started on the PR

**Comment by LukeTowers** [comment]
Sure, I don't see any issues with including it by default, no need for a toggle; unless you can think of a potential issue that could arise from that? As for how you actually include the file, take a look at: https://github.com/octobercms/october/blob/master/modules/system/classes/PluginManager.php#L242-L248

**Comment by scottbedard** [comment]
Hmm, shouldn't the PluginManager's `registerPlugin` plugin method already be getting called as part of the October setup? I wonder why the routes aren't being registered aleady... I'm going to do a bit of digging to better understand how the test environment starts up.

**Comment by LukeTowers** [comment]
@scottbedard I look forward to hearing the results of your digging 😄

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
