### ISSUE TITLE
Allow SVG as a backend logo file type

### ISSUE THREAD

**Issue by wackywired135** [octobercms/october#3442]
The ability to upload an SVG as a backend logo was removed by:  octobercms/library@3bbbbf3da469f457881b5af902eb0b89b95189a2

The reason makes sense to me, however, the option should still be available to site administrators to upload their SVG logos. In fact, the default backend logo is an SVG. Adding `fileTypes: jpg,jpeg,bmp,png,webp,gif,svg` to the logo field in the brand setting [fields.yaml](https://github.com/octobercms/october/blob/8ba63dd428b425a3722fb18c6ce5e58f03be5314/modules/backend/models/brandsetting/fields.yaml) would bring this ability back.

**Comment by LukeTowers** [comment]
I wouldn't be opposed to this, as long as we can guarantee that the only time it's rendered is in the src of an img element.

**Comment by datune** [comment]
@LukeTowers Exactly what do you need reviewed here?
