### ISSUE TITLE
UTF-8 Symbols are not handled correctly

### ISSUE THREAD

**Issue by mxschmitt** [octobercms/october#3443]
##### Expected behavior
UTF8-Symbols will be handled like normal characters.

##### Actual behavior
They are handled as two characters. When you use the left / right arrow key, they are broken, when you are "inside" a utf8 character.

##### Reproduce steps
Use in the editor an UTF8-smiley

##### October build
434

**Comment by LukeTowers** [comment]
PRs always welcome :)

**Comment by mxschmitt** [comment]
I tried to update ace, but I did't understand the dependencies. There won't fetched via npm or bower.
I found a build all command, but that only builds the vendor files. So I need to update these manually?

**Comment by LukeTowers** [comment]
Yes, that's correct. I'm not overly familiar with the update process for those dependencies so I can't help you much with that and I don't have time at the moment to dig into it (and @daftspunk won't either) so if you would like it handled then you'll need to attempt the upgrade locally and then when you're confident it's working well submit a PR for reviewal.

**Comment by mxschmitt** [comment]
I've been trying out a little bit.
We have to update the ace vendor files in `modules/backend/formwidgets/codeeditor/assets/vendor/ace`
And then recompile the assets by running: `php artisan october:util compile assets`

This fixes my issue, but in the console is a new error, which I want to solve: 

![image](https://user-images.githubusercontent.com/17984549/37330426-5ac80a62-26a1-11e8-8efe-33879f6a31c0.png)
