### ISSUE TITLE
Proxy fields don't work if the relation name is the same as the column name in database

### ISSUE THREAD

**Issue by iboved** [octobercms/october#3449]
##### Expected behavior
I have "slugs" table with these columns: id, slug, sluggable_id, sluggable_type.
I have Slug model. This model has:
```
    public $morphTo = [
        'sluggable' => [],
    ];
```
I have Post model. This model has:
```
    public $morphOne = [
        'slug' => ['Acme\Demo\Models\Slug', 'name' => 'sluggable'],
    ];
```
In my Post model fields.yaml I have:
```
    title:
        label: Title
        type: text
    slug[slug]:
        label: Slug
        type: text
```
The "slug[slug]" field should show me the related "slug" value from "slugs" table. But it does not show anything (empty field, although the relation exists).
But when I change the definition of slug field like this, it shown me the "id" value in the input:
```
    slug[id]:
        label: Slug
        type: text
```
And when I change the definition of slug field to this I see the value from "sluggable_type" column:
```
    slug[sluggable_type]:
        label: Slug
        type: text
```
As I understood, the problem is that proxy fields don't work if the name of the relation coincides with a name of a column in a database.

##### Actual behavior
When I add slug definitions in fields.yaml like this, it does not show anything in Slug input field (empty field, although the relation exists). The "slug[slug]" field should show me the related "slug" value from "slugs" table.
```
    slug[slug]:
        label: Slug
        type: text
```

##### October build
October build: 434

**Comment by LukeTowers** [comment]
Hmm, that should work in theory at least. Could you dig deeper into this and see if you can provide a fix?
