### ISSUE TITLE
Add 'Section' permissions

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#345]
Looking at the permissions in the Users section of admin can get confusing when multiple plugins are offering multiple permissions on the same tab. Plugins like OctoMail have gotten around this like so:
```php
public function registerPermissions()
{
    return [
        'octodevel.octomail.access_templates' => ['label' => 'OctoMail - Manage Templates', 'tab' => 'OctoDevel'],
        'octodevel.octomail.access_logs' => ['label' => 'OctoMail - View Logs', 'tab' => 'OctoDevel']
    ];
}
```
He places all his plugins under his Author name then prefixes the labels with the name of his plugin. This still isn't perfect and can quickly get out of hand if Octodevel makes a lot of plugins and assigns them all to that tab.

I propose adding a 'section' array item like so:

```php
public function registerPermissions()
{
    return [
        'octodevel.octomail.access_templates' => ['label' => 'Manage Templates', 'tab' => 'OctoDevel', 'section' => 'OctoMail'],
        'octodevel.octomail.access_logs' => ['label' => 'View Logs', 'tab' => 'OctoDevel', 'section' => 'Octomail']
    ];
}
```

This could allow you to separate permissions by plugin without adding too many tabs to the admin and without cluttering a single tab resulting in a much cleaner output for the admin.

**Comment by daftspunk** [comment]
The UI for permissions has been improved in the latest build. We don't have 2 levels of sections, permissions shouldn't be grouped by author but by function.
