### ISSUE TITLE
S3 storage : Permissions & Signed Urls

### ISSUE THREAD

**Issue by rajakhoury** [octobercms/october#3456]
Maybe this is intentional because it is related only to S3 storage, but if we want to use the available methods on the file model it is not possible with protected files. E.g `getPath()` or `getThumb()`

##### Expected behavior
1. Protected model uploads should have a signed URL to be accessible, because this is specific to S3 maybe : 
  a) check if storage is not local and set to S3
  b) Sign the url 
2. Media files uploaded from the backend should have a default Public-Read Permission ?

##### Actual behavior
1. Protected files do not have an S3 signed URL
2. Media files uploaded from the backend are not public

##### Reproduce steps
Add to a model a non-public attachment

    public $attachOne = [
        // User Avatar
        'avatar' => [
            \System\Models\File::class,
            'public'    => false
        ],
    ];

In the frontend get the file path : 

`{{ user.avatar.getPath() }}` - returns the Url non-signed 

 
As a workaround I Create A Base file model and override the methods, Also a twig filter could do the job..

    	class FileBaseModel extends \System\Models\File
		{
	 
		/**
		 * Amazon S3 Signed URLs
		 * Max allowed 7 days as expiry date
		 */
		 
		public function getPath( $minutesToExpire = 1 )
		{
		    // Maybe add a check if storage is S3
			if ( !$this->isLocalStorage() && !$this->isPublic() )
			{
				return \Storage::disk('s3')->temporaryUrl(
					$this->getDiskPath(), Carbon::now()->addMinutes( $minutesToExpire )
				);
			} 

			return parent::getPath();
		}

		/**  
		 *  Return Signed Url for S3 or Default
		 */
		public function getThumb($width, $height, $options = [], $minutesToExpire = 1 )
		{

			if (!$this->isImage()) {
				return $this->getPath();
			}

			$width = (int) $width;
			$height = (int) $height;

			$options = $this->getDefaultThumbOptions($options);

			$thumbFile = $this->getThumbFilename($width, $height, $options);
			$thumbPath = $this->getStorageDirectory() . $this->getPartitionDirectory() . $thumbFile;
			$thumbPublic = $this->getPublicPath() . $this->getPartitionDirectory() . $thumbFile;

			if (!$this->hasFile($thumbFile)) {

				if ($this->isLocalStorage()) {
					$this->makeThumbLocal($thumbFile, $thumbPath, $width, $height, $options);
				}
				else {
					$this->makeThumbStorage($thumbFile, $thumbPath, $width, $height, $options);
				}

			}

			// Sign URL
			if ( !$this->isLocalStorage() && !$this->isPublic() )
			{
				return \Storage::disk('s3')->temporaryUrl(
					$thumbPath , Carbon::now()->addMinutes( $minutesToExpire )
				);
			}
 
			return $thumbPublic;

		}

	}

##### October build
434

**Comment by LukeTowers** [comment]
This was fixed by https://github.com/octobercms/october/commit/aea4857ebaaa132499033014309bd5a6032dd66d#diff-b0bdb40bd58c081a3a0e7be0b02571a2
