### ISSUE TITLE
open_basedir restriction in effect

### ISSUE THREAD

**Issue by cocodrino** [octobercms/october#3459]
##### Expected behavior
(Describe expected behavior here)

##### Actual behavior
page shows error is_dir(): open_basedir restriction in effect. File(/vendor/pagination) is not within the allowed path(s): (C:/Inetpub/vhosts/<domain>\;C:\Windows\Temp\)

##### Reproduce steps
I was working locally now I'm migrating the site to my plesk area but I get this error

##### October build
latest October

Hi, good day, recently I'm moving my site from locally to the server, which is a windows server running plesk, I´ve migrate the db and files, after run for the first time I get

```php
is_dir(): open_basedir restriction in effect. File(/vendor/pagination) is not within the allowed path(s): (C:/Inetpub/vhosts/<domainx>\;C:\Windows\Temp\)
C:\Inetpub\vhosts\<domain>\httpdocs\october\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php line 86



protected function loadViewsFrom($path, $namespace)    {            

    if (is_array($this->app->config['view']['paths'])) {   
          foreach ($this->app->config['view']['paths'] as $viewPath) {  
//---> here is the error           if (is_dir($appPath = $viewPath.'/vendor/'.$namespace)) {                         
                         $this->app['view']->addNamespace($namespace, $appPath);                      
 



```

I've added the route /vendor/pagination to my plesk following this guide
https://support.plesk.com/hc/en-us/articles/115000278993-A-website-is-not-accessible-open-basedir-restriction-in-effect

but it's not clear for me because this route doesnt exist...inside vendor I don't have nor file named pagination, so this line $viewPath.'/vendor/'.$namespace doesnt have much sense to me

is the issue some related to the open_basedir or could be other problem??? 

thank you so much

**Comment by LukeTowers** [comment]
This has popped up a couple other times in other issues (https://github.com/octobercms/october/issues?utf8=%E2%9C%93&q=is%3Aissue+basedir+is%3Aclosed+open_basedir), the current recommendation is to just disable open_basedir

**Comment by cocodrino** [comment]
thank so much @LukeTowers the issue seems to be than my hosting server wasn't taking the open_basedir configuration applied inside the plesk php area...after open a ticket they were capable to fix the issue...I'll close the ticket, thank you!!!...
