### ISSUE TITLE
Empty admin list

### ISSUE THREAD

**Issue by PopcornPHP** [octobercms/october#3462]
##### Actual behavior
If in the backend admin list (/backend/backend/users) enable column 'Full name' - admin list will be empty. If enable column 'surname' - this list will work

![-1](https://user-images.githubusercontent.com/20097205/37699607-f57a5920-2cf0-11e8-98c1-6ab1c3c0f6c5.jpg)

##### October build
434

**Comment by GinoPane** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/3897579/37706417-6065d182-2cf7-11e8-8766-54e85204aec4.png)

Can you please provide more details?

**Comment by PopcornPHP** [comment]
@GinoPane , yes, work too). But in your list first name and last name are enabled. Disable these for see empty list

**Comment by GinoPane** [comment]
Yes, sorry, the previous screenshot wasn't fully illustrative. Here's hith disabled First Name and Last Name:

![image](https://user-images.githubusercontent.com/3897579/37710010-2538f7c6-2d04-11e8-818d-35ec589e70b7.png)

**Comment by PopcornPHP** [comment]
Very strange. On two of the five projects, this problem was reproduced.  One of two - installed 5 mins ago

**Comment by GinoPane** [comment]
Are you sure that no other filters are enabled?

**Comment by LukeTowers** [comment]
@PopcornPHP are you sure that your users have first and last names? I was unable to replicate this on a fresh install of October.

**Comment by PopcornPHP** [comment]
Ok, I will try find cause this issue
