### ISSUE TITLE
readOnly not working on relation, fileinput widgets

### ISSUE THREAD

**Issue by pavelmgn** [octobercms/october#3464]
I have relation widget required in validation. If i disabled it on update context - validation return error.
readOnly - not worked.

### readOnly 
![default](https://user-images.githubusercontent.com/8817759/37718228-0f79db36-2d44-11e8-9337-e9602d8e6619.JPG)
![2](https://user-images.githubusercontent.com/8817759/37718229-0fdac77a-2d44-11e8-9f76-9d1b0c9851b2.JPG)

### when disabled on save
![3](https://user-images.githubusercontent.com/8817759/37718245-1ab78b10-2d44-11e8-980c-243238b574ba.JPG)
![4](https://user-images.githubusercontent.com/8817759/37718246-1adc074c-2d44-11e8-9122-00455f29835d.JPG)

**Comment by pavelmgn** [comment]
How can i make inaccessibleit by custom class?

**Comment by pavelmgn** [comment]
Added "crutch"
On readOnly = true widgets add class '.disabled_it'
Add styles
```
.disabled_it {z-index: -1;}
.disabled_it .select2-selection {background: #eeeeee;}

**Comment by pavelmgn** [comment]
But I do not have a single project. I would like to see this in global changes.
When will the changes be made?

**Comment by LukeTowers** [comment]
When someone who's affected by this cares enough to do something about it (whether that's submitting a fix for it themselves or paying someone else to do it for them). Personally I'm too busy to handle it right now; so my recommendation would be for you to play around with it yourself and then submit a PR when you've come up with a fix for it. Once a PR has been submitted I'll review and merge it.
