### ISSUE TITLE
Place to find code for next and prev plugin

### ISSUE THREAD

**Issue by PanikaValecha** [octobercms/october#3466]
Where can I find the code for the next and prev plugin? 
I added this plugin for the blogs. I created a blog and blogPost page. The blog page displays the blogs in descending order of the published date and the blogPost page has the next and Prev plugin attached.  This plugin shows the title of the blog and the blog published date. I wanted to know where can I find it's code because I wish not to show the date to the users.

Thanks!!

**Comment by LukeTowers** [comment]
Try contacting the plugin author, this repository is for issues with OctoberCMS itself, not questions about unrelated plugins.
