### ISSUE TITLE
How to disable 'routePersistence' for all project?

### ISSUE THREAD

**Issue by PopcornPHP** [octobercms/october#3472]
Hi! My project has routes:
/article/:slug - single page of article
/galleries/:slug? - all list or category list of gallery

When I'm on page **/article/1-some-news** and trying to go to link **/galleries** ( {{ 'galleries'|page }} ) - I'm go to **/galleries/1-some-news**. It is not right. Because I have't gallery with slug 1-some-news.

How to disable 'routePersistence' for all project?

I can comment strings on file 
https://github.com/octobercms/october/blob/master/modules/cms/classes/Controller.php#L1148

And it will work, but editing system files - it is not right too. How resolve this problem?

**Comment by munxar** [comment]
1. you should have two different pages for list (/galleries) and detail (/galleries/:slug) e.g.
galleries.htm (list) and gallery.htm (detail)
if you reference the right file, the list in your case, there should be no parameter.
2. if you want to route explicit to a different slug use arguments `|page({slug: '123'})` 
3. if this all does not work, use two different parameter names:
`/galleries/:gallery_slug` and `/article/:article_slug` so they will never collide.

**Comment by Eoler** [comment]
> And it will work, but editing system files - it is not right too. How resolve this problem?

If I'm reading registration of `|page` filter correctly, you can try to call it with:
`{{ 'galleries'|page(false) }}`

**Comment by PopcornPHP** [comment]
@munxar , it's not good idea, because I'm using method paramName(), it return name of param, ex:
:slug -> slug
:gallery_slug -> gallery_slug

Then make query, like this:
Category::where($this->paramName('listSlug'), $this->property('listSlug'))->get();

If I do as you say, I'll get this:
Category::where('gallery_slug', 'slug-example')->get();

But in DB I have't field 'gallery_slug', just 'slug'

@Eoler, thank you
