### ISSUE TITLE
Table`s column not save sorted

### ISSUE THREAD

**Issue by pavelmgn** [octobercms/october#3474]
![image](https://user-images.githubusercontent.com/8817759/37976435-f6ab4f34-31fa-11e8-950e-234a0b30b7c1.png)
after sign in to backen from incognito mode under the same user
![image](https://user-images.githubusercontent.com/8817759/37976581-38bea7cc-31fb-11e8-8d58-c45312fb1d34.png)

**Comment by LukeTowers** [comment]
That's because it's stored in the session, not the user preferences. I believe there are some other open issues proposing tying it to the user. PRs welcome.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
