### ISSUE TITLE
How to change some values from "config_list.yaml" file in controller on the fly?

### ISSUE THREAD

**Issue by iboved** [octobercms/october#3475]
Hi!
I want to change some values from "config_list.yaml" file in my controller action? How can I do it?
For example, I want to change the "recordOnClick" value from "config_list.yaml" depending on the user permission. If the user has specific permission, he can click on the record, otherwise he can not.
How can I do it in backend controller "__construct" or "index" method? Thanks.

##### October build
October build: 434

**Comment by munxar** [comment]
In your controller use the `listExtendColumns` to extend the list dynamically like this:
```php
public function listExtendColumns($list) {
        if($myPermission) {
            $list->recordOnClick = 'test123';
        }
}
```
