### ISSUE TITLE
Build - 434 - Plugin boot function not working as expected

### ISSUE THREAD

**Issue by mittultechnobrave** [octobercms/october#3478]
Hello Guys,

I have installed the latest version of OctoberCMS (**Current Build - 434**).

And below is one of my Plugin's `Plugin.php` file.

    <?php namespace Technobrave\Users;
    
    use System\Classes\PluginBase;
    use Backend\Models\User as BackendUserModel;
    use Backend\Controllers\Users as BackendUsersController;
    
    use Event;
    use \Backend\Facades\BackendAuth as BackendAuth;
    use Db;
    use Backend;
    
    class Plugin extends PluginBase
    { 
    
        public function registerNavigation()
        {
            $user = BackendAuth::getUser();
    
            if(!empty($user))
            {
                
                // Adding "Custom Settings" menu of one of our local plugins 
                if($user->role['code'] == 'publisher')
                {  
                     return [
                        'modules' => [
                                        'label'       => 'Settings',
                                        'icon'        => 'icon-cog',
                                        'url'         => Backend::url('technobrave/themesettings/themesettings/update/1'),
                                    ]
                    ];
    
    
    
                }
    
    
            }
        }
    
        public function boot()
        { 
           
    		\App::before(function() {
    
                $user = BackendAuth::getUser();  
    
                
    
                if(!empty($user)){
    
                    
                    if($user->role['code'] == 'publisher')
                    {
                        
                        Event::listen('backend.menu.extendItems', function($navigationManager) 
                        {                                
                        
                              $navigationManager->removeMainMenuItem('October.System', 'system');    // Hiding Settings menu 
                              $navigationManager->removeMainMenuItem('October.Cms', 'cms');   // Hiding CMS menu 
                              $navigationManager->removeMainMenuItem('October.Cms', 'media'); // Hiding Media menu                           
                              $navigationManager->removeMainMenuItem('RainLab.Builder', 'Builder');    // Hiding Builder menu 
                        });
    
                    }               
                    
                }
    
    		});
           
        }
    }

As you can see, here I am simply checking the current logged in user's info and based on that, I am just showing or hiding few menus as per my requirements. 

This code was working perfectly fine until this new OctoberCMS version.

At the moment, my `boot()` function not working properly. 

If I do this,

    \App::before(function() {

            $user = BackendAuth::getUser(); 
            print_r($user);
            exit;
    });

Its not showing any data but the same feature working fine in my `registerNavigation()` function. 

Don't know whether this is new build issue of OctoberCMS or not but it was working perfectly fine until now in my older OctoberCMS versions.

Can someone guide me to solve this.

**Comment by LukeTowers** [comment]
@mittultechnobrave See http://octobercms.com/support/article/rn-9, specifically the section on "Middleware using sessions". The user's session hasn't been made available in `App::before`. Take your code out of the `App::before` statement and just have it in `boot()` and it will work fine.
