### ISSUE TITLE
octobercms.com is down

### ISSUE THREAD

**Issue by mnouryak** [octobercms/october#3481]
##### Expected behavior
(Describe expected behavior here)

##### Actual behavior
(Describe actual behavior here)
![image](https://user-images.githubusercontent.com/29130730/38266703-e13c08e6-3768-11e8-8a9b-937f40d16e71.png)

##### Reproduce steps
(Describe the steps to reproduce the problem here)

##### October build
(October build number)

**Comment by LukeTowers** [comment]
Known, reported to @daftspunk, may take a couple hours to resolve as it's 4am where he lives.

**Comment by danharrin** [comment]
This issue can be safely closed now.
