### ISSUE TITLE
Segmentation fault when deleting a file with a large number of files present

### ISSUE THREAD

**Issue by catthr** [octobercms/october#3482]
I have about 1 million objects in system_files
I was deleting lots of files  like:
```
foreach (File::where('attachment_type', '...')->where('attachment_id', ...)->get() as $file){
    $file->delete();
}
```
and got "Segmentation Fault" on almost each run
I rerun my script and it continues its work till the same error happens again

I believe it happens during the attempt to delete parents empty folders after the file was deleted
[Here](https://github.com/octobercms/library/blob/master/src/Database/Attach/File.php#L691)
There is a check [isDirectoryEmpty](https://github.com/octobercms/library/blob/master/src/Database/Attach/File.php#L708) and it counts _all files_ in dir and compares it to 0
`return count($this->storageCmd('allFiles', $dir)) === 0;`
And since there are lots of files it crashes during counting
At least, after I removed the third level deleting the error has gone.

I think there may be better way to check that directory is not empty, not counting all objects
 

##### Expected behavior
delete 'File' model without an error

##### Actual behavior
sometimes `Segmentation fault' sometimes just exiting script without anything

##### Reproduce steps
you need to about 1 million files in system_files and one directory with lots of directories
you can simulate the same check `isDirectoryEmpty` in console command:
`$this->output->writeln(count(\Storage::allFiles('/uploads/public/5ac')));`

##### October build
n/a (2015 year)

**Comment by LukeTowers** [comment]
@catthr I think the ideal solution would be to change `isDirectoryEmpty()` to check `Storage::directories()` and `Storage::files()` instead of `allFiles()` and then move `deleteEmptyDirectory()` into `deleteFile` and replace the hard coded sequence of three subdirectories into something that gets the partition directory structure from `getPartitionDirectory` instead and loops through that structure to check and delete each directory as needed.

Would you be willing to make a PR to fix that?

**Comment by catthr** [comment]
As I understand correctly, the current behaviuor is like this: remove parent directory if it has no files but it can have other empty subdirectories.
So we should check parent directory for files ( `Storage::files()`) then do the same recursive check for other directories (`Storage::directories()`)
Right?

**Comment by catthr** [comment]
@LukeTowers 
Do you suggest that only total empty dirs were to delete?
Now If we have `123/456/789` and `456` has two empty dirs - `789` and `abc`, we start from `789` and delete it, then check parent dir `456` `Storage::allFiles(456)` return 0 so `456` would be deleted too. If we check `Storage::directories(456)`  we got 1 directory - so, no empty, not deleting?

**Comment by LukeTowers** [comment]
@catthr exactly, because if this approach were taken, you wouldn't ever end up with a storage directory that had two empty directories because as one became empty it would have been removed when it became empty.

**Comment by Samuell1** [comment]
Is this still a issue? @catthr @LukeTowers

**Comment by LukeTowers** [comment]
@Samuell1 I believe so, just not very high priority
