### ISSUE TITLE
edgeUpdates settings in the /config/cms.php does not have any effect

### ISSUE THREAD

**Issue by rabol** [octobercms/october#3487]
##### Expected behavior
This setting should pull code from the dev branch according to the comment in the config file

##### Actual behavior
Nothing happens, no files are pulled

##### Reproduce steps
change the setting from false to true
go to OctoberCMS backend, settings, manage updates and check for updates

##### October build
434

**Comment by LukeTowers** [comment]
"Development copies" in this case does not refer to the dev branch itself, but pending builds on the marketplace site. Pending builds are marked "Pending" on http://octobercms.com/changelog; right now there are none for core or the RainLab plugins. 

If you would like to work from the dev branch directly, then use composer and read the section on Composer dev updates that I just added to the docs: https://github.com/octobercms/docs/blob/master/setup-configuration.md#bleeding-edge-updates
