### ISSUE TITLE
While loading plugins returns error - "Empty response from the server"

### ISSUE THREAD

**Issue by 12evgen** [octobercms/october#3490]
Hi guys! I have a problem loading plugins or updating the system. Returns an error - "Empty response from the server." Picked up the local server through XAMPP. I tried installing through the installer and through the console. The error did not disappear. I also tried to run October CMS through OpenServer, without result. What could be the problem? 
[image with error](https://hsto.org/webt/5a/c7/5a/5ac75af280b34086654994.png)

**Comment by LukeTowers** [comment]
That could have been a temporary issue with the marketplace server, does it happen on other environments?

**Comment by 12evgen** [comment]
no, only in october

**Comment by LukeTowers** [comment]
... I mean does the issue happen on other server environments? Can you replicate this issue in a different hosting environment?

**Comment by 12evgen** [comment]
oh sorry, I misunderstood you. Yes of course. This bug i can reproduce in other local environment. I thought I had issues with the computer, but I checked on another computer, and the bug was repeated.

**Comment by 12evgen** [comment]
Please, can you try to reproduce this bug?

**Comment by LukeTowers** [comment]
I can't reproduce it on my end:

![screen shot 2018-04-09 at 10 53 49 am](https://user-images.githubusercontent.com/7253840/38511164-79cf61e6-3be4-11e8-9c9b-1d54efca474c.png)

Perhaps try throwing debug statements in the core files and seeing if you can narrow down the issue that way.

**Comment by 12evgen** [comment]
this good idea. I'll try.

**Comment by 12evgen** [comment]
I still can not solve this problem. Can anyone tell me how else to check the error?
![default](https://user-images.githubusercontent.com/25562185/38682715-9c2dbb56-3e8d-11e8-9631-16450efcc518.png)

**Comment by LukeTowers** [comment]
@12evgen do you have a public site available that I could test this on to see why it's happening?

**Comment by abnmt** [comment]
If you are located in Russia, your provider may block requests to the server where the marketplace is located because of Roskomnadzor's policy.

**Comment by 12evgen** [comment]
@abnmt I'm in Kazakhstan, but I think you're right, it's blocking something, since recently the other day I can saw a list of plug-ins, but I could not download and install any plug-ins.

**Comment by fredec** [comment]
Guys, I had the same problem, when updating the system or trying to attach some project, I was receiving an "empty response from the server". The problem was the firewall blocking the connection. All I did was open the port 80 to this URLs:

http://octobercms.com

http://gateway.octobercms.com

Voilá, everything started working fine to me! Hope this can help somebody.
