### ISSUE TITLE
OctoberCMS GDPR + ePrivacy Compliance Discussion

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3493]
Hi,

GDPR compliance! All websites in the world need to be GDPR compliance in the E.U. or around the world if an "E.U. Person uses your website"

## About GDPR:

**consent**: the user should be given the ability to opt-in or out, a solo accept button is equivalent to a pre-ticked box (which is non-compliant),

**storage**: You are required to keep an up-to-date record of users preference status and be able to demonstrate that record upon request (local storage in this instance), and

**opt-out**: The user should be able to change their mind with as much ease as they opted in, preferably using the same mechanism (DP by design).

There are a bunch more reasons. It's worth noting that cookies are one of the most ambiguous topics of the GDPR, mentioned one (I recall) but included in the scope without any directions on how to comply. It is the EU's view that much of the data collected using cookies can be used alone or in combination to pinpoint specific users (IP, GA snippet, Zip or postcode) so it is well within scope.

For more information, I add the link: https://www.eugdpr.org/

The Enforcement date: **25 May 2018** - at which time those organizations in non-compliance may face heavy fines. 

So let's say an E.U. person uses the octobercms.com website and you don't have GDPR working after 25th May 2018 then you could get fined for example.

Because this is a major thing and there is no way to stop a person from the E.U. viewing your website I request that a feature is built into October CMS to keep us safe haha.

Some kind of option in the settings to store the record(s) and a few options like the `opt-in` and `opt-out` and the ability to add some more (custom ones). As OctoberCMS uses Cookies, for example, this would be a requirement.

Sorry to write a boring issue, but I feel it's an important one.

There is a plugin found here (in beta): https://github.com/Rebel59/oc-gdpr-user-plugin

However, this plugin only covers the data when installing the `Rainlab.User` plugin. This would NOT protect Octobercms users that don't use the  `Rainlab.User` plugin and also doesn't cover the issue of Cookies etc. It would be best to have a feature built into the cms settings directly.

**Comment by LukeTowers** [comment]
@ayumihamsaki This really should have been two separate issues.

In regards to GDPR, there is no magical solution to it. The responsibility is on each organization to implement policies and procedures to ensure that they are in compliance. Storing an additional flag on a user `opt-in` vs `opt-out` doesn't actually do anything. 

While I agree that OctoberCMS.com itself may need to make some changes to come into full compliance, there isn't really anything concrete I can think of at the moment that can be done to OctoberCMS in general. (Related: [WP Privacy Policy](https://core.trac.wordpress.org/ticket/40794), [WP GDPR system](https://www.gdprwp.com/))

Do you have any actionable proposals for what can be done to bring users of OctoberCMS more in line with the GDPR?


In regards to auto updates, this is something that doesn't currently exist but could be handled by a plugin. Is this something that you would pay for?

**Comment by danharrin** [comment]
@ayumihamsaki I would consider moving this question to the forum so that more people get a chance to contribute their ideas. It's not really suitable for a GitHub issue.

**Comment by LukeTowers** [comment]
@danharrin Forums are mostly dead and tricky to use, I think a GitHub issue is fine for discussing this.

**Comment by ayumihamsaki** [comment]
@DanHarrin Have created a forum page and linked it here, can find it here: https://octobercms.com/forum/post/octobercms-gdpr-compliance

**Comment by Alex360hd** [comment]
Personnaly, to handle this, I added [this plugin](https://opt-out.ferank.eu/en/) to my starter theme.

It's easy to install and support major services. One days, we noticed the author than a service we needed was not listed, it was added few days later.

I use [Magic form](https://github.com/skydiver/october-plugin-forms) plugin to manage my forms and I just created a [PR](https://github.com/skydiver/october-plugin-forms/pull/103) to be able to delete records after a certain time (which to me make it GPRD compatible).

With that 2 things, I think October CMS is GPRD comptible (at least for basic needs).

**Comment by ayumihamsaki** [comment]
@Alex360hd Looks good, thanks for all the info. Will play around with those plugins and test to see if they pass GDPR or need some extra work.

**Comment by ayumihamsaki** [comment]
@Alex360hd I had a look at the Magic form plugin and I don't think that covers GPRD as the data sent, received and stored is not encrypted.

From my understanding, let's say a person fills out some data in the form and adds a wrong contact address. You then reply to the wrong contact address which causes you to send personal data to the wrong recipient. This would be a data breach that might have to be reported and fail GDPR. If the data was encrypted correctly then the data would not be able to reach the wrong person.

So the plugin would need to also add some type of encryption method.

**Comment by ayumihamsaki** [comment]
Below is a Checklist for OctoberCMS Users and Developers to Follow:

# Phase 1: Need to understand

- What personal data and sensitive data we collect/hold?
- How is it collected?
- Where did the data come from?
- Where is it stored?
- Who has access?
- Who do we share the data with?
- How is it used?
- When is it used?
- What are our obligations?
- How are we communicating awareness of GDPR across the business to existing staff and new joiners?

# Phase 2: Assess Risk

- How much is personal data?
- How much is sensitive data?
- Do we need it? – what can we stop collecting, if any and why?
- How are our systems secured?
- Are our policies and procedures adequate? – who will confirm this?
- Is the processing we do legal?
- How would we respond appropriately if a customer triggered their rights?
- Do we have the right contractual relationships with our partners whom we share data with?
- What could go wrong?

# Phase 3: Mitigate Risk / Implement

## Data Breach

- What will we do if there is a breach?
- How would we detect, report and investigate a breach?
- To manage effective & efficient investigation: Assess which types of data are held. The document which types fall within the notification requirement and the process to be followed if there is a breach.

## Individual Rights

- How would we erase an individuals’ data?
- What is our process for correcting individuals’ data?
- Can we manage/remove consent for direct marketing and automated decision making?

## Data Portability

- How would we provide data electronically in a common format?

## Subject Access Requests

- What will we do if a customer exercises their rights?
- How would we handle a request?
- What processes & policies do we have in place should we plan to refuse a request?
- What will our partners whom we share data with the need to do?
- Do we have confidence that these partners are compliant and would not put our subjects data at risk?

## Consent

- How will we seek, obtain and record consent – the record must be auditable?
- What changes are needed to processes to manage consent?
- Do we have any children (under16’s, or 13s, if your member state so determines) if so, how will we seek consent from their parent or guardian?
- What systems will we have in place to verify individuals ages?
- How will we identify when children reach 16, as they will need to provide their own consent?

## Privacy Impact Assessment – PIA

- How would we implement an assessment in our organization?
- Who would carry it out?
- Would it be run centrally or locally?

## Data Protection Officer - DPO

- Do we need to designate a DPO, if not who will the responsible person be?
- Where does that person sit in the governance structure?
- How will this be communicated?

## International

- If we are an international based organization, which supervisory authority do you come under?

## Privacy Notice

- What changes do we need to make to our current privacy notice?
- Who and how will we write, obtain management approval and publish your privacy notice?

## Legal Basis for Processing Data

- Look at the various types of processing we carry out, identify our legal basis for carrying out the processing.
- Document the identified legal basis.
- Be able to explain our legal basis for processing in a subject access request and our privacy notice.
- Use Data Protection Act as guidance for what is a legal basis.

## Data Retention Policy

- Do we have a data retention policy?
- It is down to the board of directors to decide what that retention policy is, when and how will this approval be received? – data must not be kept for any longer than is deemed necessary.

## Change Management

- How will we manage change while honoring our obligations?
- Who is responsible for what?
- Do they understand the risks?
- How could we stop things going wrong?

# Phase 4: Demonstrate

- Can we demonstrate:
- Control over processes that collect and use personal data?
- Appropriate measures?
- Ability to respond?
- Records of what we do?
- A published Privacy Notice
- Consent and individual rights management.

Wishing every OctoberCMS user good luck with their GDPR strategy and operations!

**Comment by LukeTowers** [comment]
@ayumihamsaki thanks for your contributions to this! As a note; there is an easy way to make data encrypted in October, just use the Encryptable trait in your model: http://octobercms.com/docs/database/traits#encryptable

**Comment by roulendz** [comment]
I think, on of approaches could be to build a plugin.
@ayumihamsaki give good reference images + here is [good demo](https://onetrust.com/onetrust-demo/)
We could start from here.



Also good would be to add some trait to models, for automatic old data deletion after a certain period.

**Comment by ayumihamsaki** [comment]
I have looked at close to 100 different cookie plugins now that claim to be GDPR. I can say by far the two best are:

https://opt-out.ferank.eu/en/
https://onetrust.com/onetrust-demo/

However, there seems to be a lot of pointless code with them. For example, let's say you have Google Analytics installed on your website. It will produce 7 cookies and the plugins offer the user to delete each cookie, let's say I delete 5 out of the 7 GA cookies, GA will still be working and so that seems pointless to me. A much better and cleaner solution would be just to create a wrapper around the Javascript and let users turn it off and on.

I understand that GDPR says we need to "organize" and store the data. So I don't understand if it would be a good idea to create a cookie or just attach the saved setting under the users IP address? So would love to know what people think is the best solution to that?

I think building a plugin would be quite easy, needs to be lightweight (to keep website speeds quick) and I really don't like the idea of creating Pop-Ups, Overlays, Modals or Interstitials - Google has already created a penalty with regards to them and they make bad UX. So a much better way would be a tiny banner and a dedicated webpage for the user settings I believe.

**Comment by ayumihamsaki** [comment]
Gonna jump into the deep end and try to code a good GDPR Cookie Plugin, my biggest fear is Cross-Site Scripting (XSS) attacks with regards to cookies. So security and making the plugin code lightweight will be a high priority. I noticed every single cookie plugin out there seems to not take security seriously! I got some kind of idea's how to create the plugin letting webmasters be able to create easy wrappers around things. Also thinking of using more Laravel than Javascript for the cookie side of things.

**Disclaimer:** _I am not a strong coder and so any help would be appreciated._ Will try and create a Github for it in few days time, gonna work on this throughout May because I feel the plugins out there are not very good and don't actually fulfill GDPR conditions.

**Comment by CitrinoDeveloping** [comment]
Hi to all,

in order to be compliant to gdpr we acted as follow:
Extended the eu cookie law madness plugin for octboer cms with using a standard js pop out button to allow users to revoke always cookies. Ipdated and extend oour privacy policy declaring who we are, what do we do with this data and if we collected them. I prefer always to not collect data for a simple form.

Anyway here is an example:
A robust privacy policy with extended explanation, the cookies section and a button to always revoke cookies. 

We disabled all "like" buttons style, i don't think they are necessarily needed, but have always the doubt: these buttons help to create profile for social nwetwork? So we have declared it if we used it. And block.

**So to be compliance to gdpr we think:**
You have to create a strong policy, a button, always available to revoke cookies. This tasks could be reached by a plugin.

Then you have to project by design the database part. 
We use magic forms for our forms. We don't store nothing, but it would be necesseraly i think the author updated the plugin to be compliant with new rules. 

Hava another doubt. For a future project we will have a private area. If we will use rainlab.user, what steps will do to have all as much as ok? @ayumihamsaki which were your technicla solutions?

Bye

**Comment by CptMeatball** [comment]
Quick status update about our plugin. (GDPR User) That was a try out and did not do anything that really matters in the scope of the GDPR. The idea of that was to encrypt all user related data, so in case of a data breach user data would not have been out on the streets directly. 

We've done some more research about the GDPR, and we're convinced that fully encyrpting all user related data fields is **not** the way to go. You are also compliant if you set up the rest of your infrastructure in a common sense way.  Encrrypting everything feels (and to our knowledge) **is** a last stand in case you have a crappy host or don't care about updating your hosting environment. 

Apart from the consent part, you need to keep everything up to date and install some safe practices (using `env` setup and `mirror` the public folder for example). In that way if it goes wrong, you can prove you've done everything with safety in mind. 

The GDPR is not a **ENCRYPT ALL THE THINGS** legislation. However, it does force companies to think about how data is stored and which data is absolutely necessary.

**Comment by ayumihamsaki** [comment]
@CitrinoDeveloping hi

> which were your technicla solutions?

Since creating this post I have come to the solution that we should not just focus on GDPR only. GDPR came out in 2018, but coming in the next few months or in 2019 is ePrivacy which enhances GDPR and is much more complicated. So I have been focusing on creating a solution which ticks both the boxes for GDPR + ePrivacy. I will be honest and say it would be impossible to have a one plugin fit all solution. But the way we have done it was to first re-design the website, letting the users be able to opt-in or opt-out to everything, explaining everything to the users in basic legal pages what the data flow is, also to store all the data in an encrypted method and organized on request. Setting up DPO's and making sure all third-party apps are fully GDPR. There are many other things and everything needs to be listed separately. So to do this we created wrappers around each thing that would need GDPR + ePrivacy consent and turned them all off and let the user opt-in to each thing.

It's a headache but when you get into it you start to understand that GDPR + ePrivacy actually make you do things in good habits.

But my only advice would be that 99.99% of GDPR so-called tools out there clearly don't pass ePrivacy!

@CptMeatball Sorry, my bad I should have stated that it was in beta! But it looked a good idea and so I linked it.

p.s Good luck to everyone, keep safe!

**Comment by ayumihamsaki** [comment]
@CitrinoDeveloping, In the end, our solution was to do a full **GDPR** and **ePrivacy**!

@CptMeatball Sorry about that I should of stated it was in beta but looked a good idea and worth a mention.

Good luck to everyone doing GDPR + ePrivacy!

**Comment by CptMeatball** [comment]
Encrypting everything in the database doesn't have any use, if they already have your cipher. Most likely they already have access to your webserver if they get access to the database. But none the less, it was worth a try. ;)

Have you guys made something of a GDPR cookie compliance popup?

**Comment by tobias-kuendig** [comment]
If anyone is looking for a simple solution or starting point to get GDPR compliant with October and custom plugins we have created a GDPR plugin over at https://github.com/OFFLINE-GmbH/oc-gdpr-plugin

At the moment you can delete old plugin data automatically and include a cookie consent widget via the component system.

If anyone has further ideas on how to extend the plugin we're open for suggestions!

**Comment by ayumihamsaki** [comment]
@tobias-kuendig I got all excited just now, but after playing with that library it seems to not work! Steps I took were:

1. Go to demo website: https://klaro.kiprotect.com/
2. Open up Dev Tools in Chrome and look at the cookies page
3. Click on 'Show Manager' and select all cookies ON, then save. (The cookies display in dev-tools now)
4. Click on 'Show Manager' and select all cookies OFF, then save. (Nothing Happens all the cookies are still there).
5. Click on the 'Reset consent' button and again nothing happens.

Sorry doesn't seem to work.

**Comment by ayumihamsaki** [comment]
Want to add this extra information and update the title.

## ePrivacy and GDPR:

The GDPR came into effect in 25th MAy 2018 which replaces the Data Protection Directive 95/46/EC. It deals with Privacy!

ePrivacy (also known as ePR) came out in 2003 and got updated in 2011, it is currently being updated right now and The Eu hopes to finish the updated new ePrivacy Law at the end of 2018 or in 2019. There is a draft out which can be found here: https://iapp.org/media/pdf/resource_center/ePR_2018-04-13.pdf

A progress report dated June 2018 is found here: https://iapp.org/media/pdf/resource_center/ePR-ST_9079_2018_INIT_EN.pdf

ePrivacy deals with Unsolicited Marketing (SMS, Emails, Web Notifications, Cold Calling etc.), Cookies and Confidentiality. Also, social media sharing, like buttons and widgets are under ePrivacy.

Technically there is no such thing as GDPR Cookies, it would be ePrivacy Cookies!

EU Cookie Requirements (incl. GDPR):

- Disable all cookies by default (only allowed are mandatory cookies),
- Show info transparently (for example: display a banner on the first page view and a small one on other pages),
- Display a panel to allow or deny each cookies one by one,
- Activate cookies on the second page view if not denied,
- Store the consent in a cookie for up to 365 days (after which user needs to give consent again).

Also some things I want to point out that make me think many Cookie Plugins wont pass the new ePR laws.

Section (23) states:

> End-users should be offered a set of privacy setting options, ranging from
> higher (for example, ‘never accept cookies’) to lower (for example, ‘always accept cookies’)
> and intermediate (for example, ‘reject third party cookies’ or ‘only accept first party
> cookies’). Such privacy settings should be presented offered in a an easily visible and
> intelligible manner. 

Therefore cookie settings need to be in a range, not a toggle switch saying on and off. You would need to have the option in a slider range.

Another factor is that Cookie settings need to be on a "second page", so I am really not sure if that would allow a popup modal from a banner for example?

On a personal level, I really don't like the idea of using Javascript cookies for a cookie plugin, this opens up a big array of security issues ranging from XSS, CSRF, Session hijacking, Meltdown and Spectre (Spectre part) and many other problems. Using PHP cookies we can give some proper security things such as HTTPonly, Secure and SameSite.

Methods of Consent:

There are three main ways: (Please note this is before the Settings)

![untitled](https://user-images.githubusercontent.com/17784082/41027387-cef0adf8-696e-11e8-9fed-80c32fb2e8c2.png)

One last thing with ePrivacy, I'm really up for building a proper ePR plugin, that will let the webmaster and developer have control over cookies, social media data sharing, push notifications, sending sms/txt and emails and lastly widgets (for example Twitter timeline embeds etc.) My coding is not so strong so any help would be great at a later stage.

Finally gonna change the title to: OctoberCMS GDPR + ePrivacy compliance Discussion.

**Comment by tobias-kuendig** [comment]
> Another factor is that Cookie settings need to be on a "second page", so I am really not sure if that would allow a popup modal from a banner for example?

This means you'll have to be able to edit your cookie settings after the initial prompt (maybe via a "second page"), right? With a solution like Klaro! you can create a simple link to reopen the overlay again at any time. I really don't see the reasoning to expect a separate page instead of a simple modal. I cannot imagine that such implementation details are being defined.

> On a personal level, I really don't like the idea of using Javascript cookies for a cookie plugin, this opens up a big array of security issues ranging from XSS, CSRF, Session hijacking, Meltdown and Spectre (Spectre part) and many other problems. Using PHP cookies we can give some proper security things such as HTTPonly, Secure and SameSite.

Do you have a concrete example? I don't see how PHP cookies are more secure than JS cookies.

**Comment by ayumihamsaki** [comment]
@tobias-kuendig 

Hi,

I'm really not totally sure about the overlay if it's ok or not with regards to a legal point of view. Can't really say for sure as the ePrivacy is still in draft. However from a UX point of view, many don't work on a lot of Mobile devices so that would be a bigger problem in my eyes.

> Do you have a concrete example? I don't see how PHP cookies are more secure than JS cookies.

A `HttpOnly` cookie means that it's not available to scripting languages like JavaScript.

Note sure about the `secure` flag on Javascript?

The `SameSite` flag is for server-side only as well, so again Javascript cannot use it. For details on Samesite see here: https://www.sjoerdlangkemper.nl/2016/04/14/preventing-csrf-with-samesite-cookie-attribute/

**Comment by ayumihamsaki** [comment]
Going to outline the idea of a good GDPR + ePrivacy Plugin, if someone wants to code it for everyone you are more than welcome. I just don't have enough time to code all my things right now. So sharing my idea hopefully can benefit everyone.

## Part 1

Use a banner consent when a user opens the website for the first time. The banner needs to be at the bottom of the webpage and not at the top due to Google crawling rules. The banner also needs to be small because under Better Ads Standards the total banner height for all things on a webpage is under 30% or you will get a Google Penalty, see image:

![interstitials-28](https://user-images.githubusercontent.com/17784082/41031458-8fc89d34-6978-11e8-883b-aa4695db5252.png)

My idea for a Banner would be to have a short text description of what Cookie's you have and what they are used for. Also, a Cooke Settings button and an Allow All button, plus a close Banner button that would also act as a denied consent option, see example:

![untitled](https://user-images.githubusercontent.com/17784082/41032225-9f5254e6-697a-11e8-962d-e44d97b95e33.png)

The results go to the plugin and save as analytics data in the back end for the webmaster to know what people are selecting. The results also make a PHP cookie which has the flags 'HTTPonly', 'Secure' and 'SameSite'.

## Part 2

We don't use an overlay or modal or another banner or pop-up. Users hate these things and reduce your website conversion rates. So we send the user to a proper Settings Page. Here the user can read what the cookies and other things do and be able to use a normal form to select options in a range.

Things that could go into the contact form are:

- Cookies
- Web Push Notifications
- Widgets
- Social Media Sharing
- etc.

You could also explain to the user when they use the slider what happens when they increase the slider to each thing. For example, Google Analytics uses 7 cookies and I use the PWA version which is called Auto Track, it gives me a dozen plugins for GA, so the user could slider the GA option and turn on each of the plugins etc. Here is an example:

![untitled](https://user-images.githubusercontent.com/17784082/41033402-52722594-697e-11e8-8479-45b961617905.png)

## Part 3

We use Twig PHP Wrappers, OctoberCMS is an amazing tool and we should its powers here. To be able to turn things on and off we create Twig Wrappers an example can be this:

```
  {% if GdprOption1 is not '0' %}
    <div>Widget</div>
  {% endif %}

If GdprOption1 = 0 don't display
If GdprOption1 = 1 do display
```

You can also add CSS and Javascript to OctoberCMS Partials using the header plugin. So I don't have to create a Wrapper to each script tag - like many cookie plugins do. Instead, we could have several Javascript code snippets in one file and be able to turn on and off each bit, for example:

```
<script>
  {% if GdprOption1 is not '0' %}
    JS Code 1
  {% endif %}

JS Code 2

  {% if GdprOption2 is not '0' %}
    JS Code 3
  {% endif %}
</script>
```

## Part 4

We are only going to send ONE cookie via PHP using the flags 'HTTPonly', 'Secure' and 'SameSite'. An example of the backend of the plugin could look something like this:

![untitled](https://user-images.githubusercontent.com/17784082/41033783-9136eb10-697f-11e8-822a-63d3dfeb3eef.png)

For extra security, we could make an array using integers only and use regrex validation to remove any other characters, to prevent hacking! e.g.

If GdprOption1 = 0 don't display
If GdprOption1 = 1 do display
If GdprOption2 = 0 don't display
If GdprOption2 = 1 do display

Would be like:

`"1": "0", "2": "1",... etc.`

Anyway, very simple idea which is very powerful because it uses OctoberCMS Laravel features. If someone want to make it please go ahead, as I am so busy! I don't think I could spend time on it for 2-3 months at least.

**Comment by tobias-kuendig** [comment]
:clap: Very nice write up! I'll try to implement a prototype in our GDPR plugin.

**Comment by ayumihamsaki** [comment]
@tobias-kuendig cool, keep me in the loop.

**Comment by tobias-kuendig** [comment]
A first implementation has been released! :tada:

You can check out what it looks like on our demo website: https://mall.offline.swiss
The code is available over at https://github.com/OFFLINE-GmbH/oc-gdpr-plugin

Currently there are the following components available:

#### cookieBanner

![image](https://user-images.githubusercontent.com/8600029/41365745-803f0ce6-6f3a-11e8-93ff-7dc0f683e241.png)

This component displays the cookie banner. It displays checkboxes for each cookie group that has been defined via the backend settings. This allows the user to quickly enable or disable certain types of cookies. 

If the user accepts the cookies, all relevant scripts will be reloaded via AJAX (optionally a hard reload of the page can be triggered). If the user declines the banner disappears and no cookies are enabled.

If the user clicks on the advanced settings link no cookies are set until a decision is made via the `cookieManager`.

All user specific decisions are stored in a single cookie.

#### cookieManager

![cookie-manager](https://user-images.githubusercontent.com/8600029/41364223-5c58a548-6f36-11e8-9279-2e04217fe645.gif)

This component displays detailed information about all cookies. Note that the table in the GIF is only displayed for debugging purposes.

Cookies can be enabled or disabled. If a cookie has levels defined a slider is shown additionally.

#### Twig helpers

The Twig helpers `gdprCookieAllowed` and `gdprAllowedCookieLevel` make it easy to conditionally include your dependencies.


```twig
{% if gdprCookieAllowed('google-analytics') %}
    <!-- Include Analytics Code here -->
{% endif %}

{% if gdprCookieAllowed('google-analytics', 3) %}
    <!-- Include advanced Level 3 Analytics Code here -->
{% endif %}
```

Feedback and PRs are highly welcome. Thanks again to @ayumihamsaki for the great write up that served as blueprint for this addition.

**Comment by ayumihamsaki** [comment]
@tobias-kuendig It's looking great! Gonna beta-test it on some websites in the coming days! One thing I thought when I was reading your github was the banner, if it's possible I would remove this bit:

![41366716-4775cf78-6f3d-11e8-8995-a311ba052de9](https://user-images.githubusercontent.com/17784082/41503315-2e04b9d6-71c8-11e8-88fa-fb119dce063e.png)

~Not sure if there is an option to show or hide it, that bit. As I haven't played around with the plugin yet.

Really nice looking plugin! tada

**Comment by ayumihamsaki** [comment]
@tobias-kuendig Looks great! Congrats, gonna beta test it and will pass any useful feedback.

**Comment by ayumihamsaki** [comment]
Gonna close this issue, we are busy working on the October CMS GDPR and ePrivacy Plugin, so use this link: https://github.com/OFFLINE-GmbH/oc-gdpr-plugin
