### ISSUE TITLE
Wrong $this value with ajax call when component is embed more than once

### ISSUE THREAD

**Issue by Alex360hd** [octobercms/october#3495]
##### Expected behavior
When you embed the same component twice on a page (with different alias for sure) and that component call an ajax method defined in the component, the value of $this always refer to the first added component.

##### Actual behavior
I added the same component twice on my page "ajaxComponent1" and "ajaxComponent2".

Let's assume you have this method in your component :

    <?php
    public function onRun() {
        trace_log('onRun', $this->alias);
    }
    public function onAjaxTest() {
        trace_log('onAjaxTest', $this->alias);
    }
    ?>

Here is the partial of my component : 

    <a data-request="onAjaxTest" href="return;">trigger onAjaxTest()</a>

When I load the page, I can see in the event log "ajaxComponent1" and "ajaxComponent2" and everything seems to work perfectly.

But if I click on the "onAjaxTest" link of my **second** component (ajaxComponent2), then I go to the eventlog, I can see that the alias is "ajaxComponent1".

##### Reproduce steps 

I quickly made a plugin that demonstrate the problem. To reproduce : 

- Install the attached component I made to demonstrate the problem
- Add 2 instance of that component on the same page
- Display your page : see the event log that display the alias value of your component in the onRun method.
- Now click on both link that is displayed by the component and look at the event log each time. You will see that when you click on the link of the **second** component, the alias of the first one is displayed instead.

##### October build
434
[acme.zip](https://github.com/octobercms/october/files/1902243/acme.zip)

**Comment by LukeTowers** [comment]
@Alex360hd This is why component authors are supposed to use the `{{ __SELF__ }}` variable before AJAX handlers to support multiple components being included on the same page: http://octobercms.com/docs/plugin/components#referencing-self

**Comment by Alex360hd** [comment]
Oh sorry, I missed that point in the documentation. Your suggestion worked like a charm, thank you !
