### ISSUE TITLE
Question: File attachments

### ISSUE THREAD

**Issue by adxlv** [octobercms/october#3496]
Hi.
I have a question regarding the way OctoberCMS saves file attachments in filesystem.
Why do the file path is split into folders of three symbols (e.g. return /ABC/DE1/234 for an name of ABCDE1234) ?

I am asking because it generates lot of inodes and if you have many files you can hit the inode limit for some shared hosting enviroments (the limit mostly is because of backuping).

And as we are in this subject, is it possible to safely disable this functionality, and what (in your opinion) could be the risks if files would be saved in long list in single folder?

**Comment by jimcottrell** [comment]
It's a common tactic to limit the number of files that need to be stored in any one directory, which can impact performance (or even functionality) depending on the filesystem in use. Why specifically the choice was made in OctoberCMS to go three levels deep, I don't know, but that's the general reason. Consider something like https://softwareengineering.stackexchange.com/questions/301400/why-is-the-git-git-objects-folder-subdivided-in-many-sha-prefix-folders for more details.

**Comment by adxlv** [comment]
Tnx guys for explaining! Much appreciated!
