### ISSUE TITLE
Plugin Settings Menu Suggestion

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3497]
Hi Luke + Daftpunk,

Can I give you some feedback on the plugin settings in the backend. I been thinking this for a few years now.

You have the following two screens:

![1](https://user-images.githubusercontent.com/17784082/38675208-d9d0cece-3e4e-11e8-88d3-17ccbf0c4f61.png)

and

![2](https://user-images.githubusercontent.com/17784082/38675213-df562b5a-3e4e-11e8-9acc-fcb0722156d1.png)

Why you can just merge them together to make everything more tidy and less confusing?

![3](https://user-images.githubusercontent.com/17784082/38675295-2a50fea0-3e4f-11e8-8eb3-a4cda1ebd34c.png)

~ See above combined screens.

(It's actually a pain having two different screens with different filenames - Name on 1st screen and Code on 2nd Screen)

**Comment by LukeTowers** [comment]
Too many columns :) Not everyone has a >= 24 inch screen to use.
I'd welcome some suggestions on making the interface more compact and consolidating the two screens @ayumihamsaki

**Comment by ayumihamsaki** [comment]
@LukeTowers What's the min screen size you are thinking? Can try and re-code it and send you the pull request - if it's easy and I got the brain power to achieve it.

**Comment by LukeTowers** [comment]
@ayumihamsaki I mean ideally it would at least be usable on mobile even if it wasn't pretty. Other than that on a desktop how about you aim for 1024px?

**Comment by ayumihamsaki** [comment]
@LukeTowers All my work I aim for 320 - 1920px range. Will play around with it and see if I can come up with a nice menu on a mobile device, I see what you are saying.

**Comment by ayumihamsaki** [comment]
@LukeTowers This is what I have come up with:

Desktop Version:

![1](https://user-images.githubusercontent.com/17784082/38697914-3be97ca0-3e8b-11e8-9aed-22baddd04563.png)

Tablet Version:

![2](https://user-images.githubusercontent.com/17784082/38697925-41c3f240-3e8b-11e8-9bc4-c728ece308ee.png)

Phablet Version:

![3](https://user-images.githubusercontent.com/17784082/38697933-46bcaf44-3e8b-11e8-9409-93b0fdd3c587.png)

Mobile Version:

![4](https://user-images.githubusercontent.com/17784082/38697940-4b3deb96-3e8b-11e8-8643-6ed9f7cdb6c9.png)

**Comment by Teranode** [comment]
How about removing the description and authors, adding the toggle buttons, and add a third button that opens up more information about the plugin that contains the description and author and website, etc

**Comment by ayumihamsaki** [comment]
That sounds a good idea!

**Comment by ayumihamsaki** [comment]
That sounds a good idea! Opening a modal window.

**Comment by ayumihamsaki** [comment]
Closed see here: https://github.com/octobercms/october/issues/4345
