### ISSUE TITLE
Process could not be started [The system cannot find the path specified]

### ISSUE THREAD

**Issue by ronogrimen** [octobercms/october#3499]
I got this error whenever I checked the send invitation by email in creating an admin user.

![image](https://user-images.githubusercontent.com/32258387/38726426-b72e7814-3f3c-11e8-886d-516733f3ce91.png)

434 build.

**Comment by LukeTowers** [comment]
This sounds more like a problem with your environment / swiftmailer. Did you try googling this issue first before posting it here?

**Comment by roulendz** [comment]
@ronogrimen for Windows development I suggest to use [Laragon](https://laragon.org/download/)
*Download Laragon - WAMP (112 MB)*
And all your major environmental issues will be resolved!

Under Menu -> Quick create -> Configurations... add this line
```
OctoberCMS=composer create-project october/october %s
```
And after saving you will have Under Quick Create OctoberCMS

Let us know if it helped!

**Comment by ronogrimen** [comment]
hi @roulendz I'm using sql server.

**Comment by ronogrimen** [comment]
@LukeTowers Yes I did, and I can't find any solution for this.

**Comment by LukeTowers** [comment]
@ronogrimen Well I don't think it's an October specific issue, try googling that error connected to Laravel

**Comment by viamage** [comment]
https://github.com/swiftmailer/swiftmailer/issues/1080 this is reported on Swiftmailer.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
