### ISSUE TITLE
Determine required fields based on the validation rules

### ISSUE THREAD

**Issue by FaZeRs** [octobercms/october#3500]
##### Expected behavior
Using 'Validation' trait function 'isAttributeRequired' it needs to return false if rule is 'required_if' and field is not present

##### Actual behavior
Using 'Validation' trait function 'isAttributeRequired' it returns true if rule is 'required_if' and field is not present

##### Reproduce steps
`    
    public $rules = [
        'discount_value' => 'required_if:discount,1'
    ];
`
`    
    if($this->isAttributeRequired('discount_value')) {
        return 'is required'
    }
`

##### October build
435

**Comment by LukeTowers** [comment]
Feel free to make a PR to change this @FaZeRs. Keep in mind that a simple fix to just only have isAttributeRequired return true for required_if will break the case of the red dot applied to fields that are required since there isn't any support for on the fly assigning of that dot.

**Comment by FaZeRs** [comment]
```
    public function isAttributeRequired($attribute)
    {
        if (!isset($this->rules[$attribute])) {
            return false;
        }

        $ruleset = $this->rules[$attribute];

        if (is_array($ruleset)) {
            $ruleset = implode('|', $ruleset);
        }

        if (strpos($ruleset, 'required:create') !== false && $this->exists) {
            return false;
        }

        if (strpos($ruleset, 'required:update') !== false && !$this->exists) {
            return false;
        }

        if (strpos($ruleset, 'required_with') !== false) {
            $requiredWith = substr($ruleset, strpos($ruleset, 'required_with') + 14);
            $requiredWith = substr($requiredWith, 0, strpos($requiredWith, '|'));
            return $this->isAttributeRequired($requiredWith);
        }

        if (strpos($ruleset, 'required_if') !== false) {
            $data = $this->getValidationAttributes();
            $requiredIf = substr($ruleset, strpos($ruleset, 'required_if') + 12);
            $requiredIf = explode(',', $requiredIf);
            if($data[$requiredIf[0]] == $requiredIf[1]) {
                return true;
            }
            return false;
        }

        return strpos($ruleset, 'required') !== false;
    }
```

Is this good for PR?

**Comment by LukeTowers** [comment]
@FaZeRs what's with the specific character counts of 14 and 12?

**Comment by FaZeRs** [comment]
@LukeTowers required_with ruleset is already implemented, just took that as example for required_if. It's to get value after 'required_if:'

**Comment by LukeTowers** [comment]
@FaZeRs sounds good. Just submit the PR, if there's any discussion that needs to happen on the suggested code it'll be done there instead. Thanks!

**Comment by FaZeRs** [comment]
@LukeTowers yes, I made PR https://github.com/octobercms/library/pull/320 but just have no idea how to write tests for this

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
