### ISSUE TITLE
File Attachments No Longer Default Deferred Binding?

### ISSUE THREAD

**Issue by AugmentBLU** [octobercms/october#3501]
I just updated a site to 435 and it seems that deferred binding is defaulting to false for file uploads, is this intentional? 

Example, if I add an avatar to a backend user, the image is instantly saved against that user, rather than requiring the save action to bind the system file. 

Before updating, the version was 426, uploading an avatar required us to save before the image was bound. 

Is there a setting to put this back as users will be confused that uploading an avatar doesn't require saving but changing text inputs does.

Seems to work with 434 from what I can see.

**Comment by AugmentBLU** [comment]
@LukeTowers I haven't had time to look in to it, seems 434 works fine but not 435. I had to back my OC down to 434 again. It doesn't appear to be a Laravel issue as both installs were pulling the latest 5.5 build in. 

I know you mentioned on Slack that deferred binding can be disabled, I'm not seeing this in the config files.

**Comment by LukeTowers** [comment]
I haven't had time to look into it either 😄

**Comment by Teranode** [comment]
Im not sure if its related, but im getting my files deferred but when i save its not attaching, it just stays in deferred

**Comment by Teranode** [comment]
yea this seems to be critical here :/

**Comment by Teranode** [comment]
@AugmentBLU how did u downgrade, cause this seems to be breaking anything i have with deferred binding

**Comment by LukeTowers** [comment]
@Teranode Looks like https://github.com/octobercms/october/commit/422a99770c32f912e13ed2b4744c6f16a76e1c32 is the one that did it; at least for @AugmentBLU's issue. @AugmentBLU Could you remind me why having it defer on attachment to existing records is preferred behaviour?

@Teranode I'm not sure what's causing your issue, could you apply each of those commits one by one until you find out which one causes your problem?

**Comment by Teranode** [comment]
@LukeTowers see from what i see, when i updated the netsti plugin's deferred binding stopped working even when i was following this example (this used to work):

```
$post = new Post;
$post->title = "First blog post";
$post->save(null, $sessionKey);
```

this also was the same issue on the back end so idk what went wrong there, so now I have to do:
```
    public function afterCreate()
    {
        $this->commitDeferred(post('_session_key'));
    }
```
for all my models that use deffered bindings. The last build i was on was 434 i went to 435 and it started happening, then i went back to 434 and it was still happening so i just gave up and started putting the commit deferred in aftercreate.

**Comment by LukeTowers** [comment]
@Teranode are you able to switch to 434 and then add those three changes one by one manually to find the issue?

**Comment by AugmentBLU** [comment]
@LukeTowers I just think that uploading a file and having it instantly saved against a record is disjointed as you have to click save for any changes to text fields. Why are images being treated differently from text inputs?

**Comment by LukeTowers** [comment]
@AugmentBLU because they technically can be easily, although perhaps that's an opportunity to have that behaviour configurable?

**Comment by AugmentBLU** [comment]
Build 434 requires you to save a user profile before the avatar is linked. 435 just instantly links the avatar. 

I was wondering why that changed and if we had an option to use deferred binding as per previous builds. 

I'm not sure if the instant file bind happens across any plugin or model but I'll assume it does due to the linked file change you mentioned above? Also, does this mean that deferred binding must be explicitly set now, if so where or how do we set that. 

Thanks.

**Comment by LukeTowers** [comment]
@AugmentBLU we should probably add a `attachOnUpload` config to the FileUpload widget that defaults to false (to keep the original behavior) that enables the new behavior when true. If you want to submit a PR for that I'll review and merge it.
