### ISSUE TITLE
Data attribute API : data-request-error not triggered when data-request-validate is set

### ISSUE THREAD

**Issue by Alex360hd** [octobercms/october#3502]
##### Expected behavior
I made some tests on forms and I noticed that the javascript code you set in data-request-error is not triggered when you activate data-request-validate. 

I wonder why this limit ? I think you can find many cases where combining both could be useful (add a popup in addition to inline errors on fields, push an analytics event etc....)

##### Reproduce steps
Create a new CMS page with that code in markup

    <form data-request="onSubmitTest" data-request-validate data-request-success="alert('Success')" data-request-error="alert('Error')">
        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" id="name" name="name" class="form-control">
            <div data-validate-for="name"></div>
        </div>
        <button type="submit">Submit</button>
    </form>

And put that code in PHP code tab

    function onSubmitTest() {
        throw new ValidationException(['name' => 'You must give a name!']);
    }

Now send the form, you will see that the code under data-request-error isn't triggered when I submit the form with error.

##### October build
434

**Comment by LukeTowers** [comment]
Feel free to submit a PR to change this; the relevant code would be in modules/system/assets/js/framework.js

**Comment by Samuell1** [comment]
I dont think data-request-error should be triggered on validation errors because you got your server response back and data-request-error should error only on server errors or network errors etc.

**Comment by LukeTowers** [comment]
@Samuell1 I agree. Closing this issue as abandoned anyways.
