### ISSUE TITLE
Backend form validation order

### ISSUE THREAD

**Issue by juliangums** [octobercms/october#3512]
##### Expected behavior
Would it be a nice feature if the backend form validation is being done in the order of the actual tabs and their fields?

##### Actual behavior
Currently, errors on backend forms are in the order specified in the model's `$rules`. This can make the the validation jump to `Tab 5` and when the error is corrected to `Tab 2` for example, which isn't very user friendly. Sure, you can always manually change the order of `$rules` but I think it would be nice if it would work independently. Thoughts?

##### October build
435

**Comment by LukeTowers** [comment]
@juliangums what would an implementation of that look like?

**Comment by juliangums** [comment]
@LukeTowers like this maybe?
https://github.com/octobercms/library/compare/develop...juliangums:patch-1

btw, I realised this would be on the wrong repo then. Let me know and I'll do some more thorough testing and create a pull request on `october/library`

**Comment by juliangums** [comment]
@LukeTowers tbh I haven't got a lot of experience writing tests and I don't really want to do dump in some shitty code. I started adding this into https://github.com/juliangums/library/blob/3cfc9e101e5d72af404eea7b20ba206c0882708d/tests/Database/Traits/ValidationTest.php
```
    public function testSortOrder()
    {
        /*
         * Sort order of multiple rules
         */
        $rules = [
            'email' => 'email|min:5',
            'name' => 'required|max:2',
            'age' => 'required|integer'
        ];

        $attributeNames = ['age', 'email', 'name'];

        $this->validate($rules, null, $attributeNames);

        $this->assertEquals($attributeNames, $this->validationErrors->keys());
    }
```
But I can't really do that as the `validate()` method needs to access stuff from the model where it's being used as a trait. I'm not quite sure what the right approach is here.

Can anyone help?

**Comment by LukeTowers** [comment]
@juliangums I'm uncertain exactly what you're trying to do that's causing you issues, could you explain in more detail?

**Comment by juliangums** [comment]
This is still relevant I guess. @seanthepottingshed wanna write a test for this? This was the bug that the backend validation would not jump to the first error in the form but the first error according to the order of the `$rules` array. My pull request would reorder it so the backend validates in the correct order.

**Comment by LukeTowers** [comment]
@juliangums you could always just edit your model's rules array yourself. Note also that inline form validation is being worked on, which is just a much better user experience overall so perhaps we should wait for that: https://github.com/octobercms/october/pull/4322

**Comment by juliangums** [comment]
Sure, but it isn't completely obvious that the order of $rules would cause a validation bug on the frontend and takes some time to figure out so I thought a fail-safe way to do this would be great so it still works after rearranging the backend form. 
But given inline form validation will be availible soon I guess we can close the issue and pull request.
