### ISSUE TITLE
Cannot prevent backend SQL errors appear on screen

### ISSUE THREAD

**Issue by endo64** [octobercms/october#3517]
##### Expected behavior

SQL (or any other detailed) errors should be logged to an error file but should not appear on screen, since security scan tools treats them as information leak. Or at least we should be able to enable/disable this feature. 

##### Actual behavior

SQL error pops up on screen (this happens during security scans with modified requests)

SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'test' for column 'published' at row 1 (SQL: update `table` set `published` = test, `updated_at` = 2018-04-19 14:09:45 where `id` = 2)

![image](https://user-images.githubusercontent.com/840604/38988335-7a417cfa-43db-11e8-99ee-a7cfa20539a5.png)

This happens even if `APP_DEBUG` is `false` 

##### Reproduce steps

Modify an update request using Burp/Intruder or similar tool, change or remove some posted values to an invalid values.

##### October build

v1.0.434

**Comment by LukeTowers** [comment]
Feel free to submit a PR to fix this. You'll probably want to catch SQL Exceptions in the response stack and then log or display depending on app_debug.

**Comment by panakour** [comment]
If you create error page this page hould be visible instead of any error.

**Comment by LukeTowers** [comment]
@panakour he's talking about on the backend only, these sorts of messages are already filtered on the frontend accordingly

**Comment by endo64** [comment]
Actually what I want is to show a generic error message like "An error occurred." and not to show any error details on screen AND in HTTP response, because security scan tools see that as a treat.
There are also other security issues like if you change the `sort_column` value in the HTTP request you will get `SQL Error: Invalid column: x` and security tools thinks that there is a possible SQL injection.

**Comment by LukeTowers** [comment]
@endo64 Then setup a handler to catch any exception in the backend and rethrow it as an `\ApplicationException` with the message `An error occurred. Contact an administrator to find out more.`

**Comment by viamage** [comment]
Proper way is: setup validation in your model and provide custom validation messages. Another is what LukeTowers said above. Please kindly don't make any PRs silence unexpected errors, you should catch them, not silence them.

**Comment by LukeTowers** [comment]
@viamage I would agree with it being an architectural error on the developer's side, however I would still accept a PR to minimize the display of complex error messages to end users when debug mode is disabled (providing it stills logs the complex version) as it would be helpful to cover cases where the dev doesn't have the time or knowledge to properly implement for every case. Any thoughts on that?

**Comment by endo64** [comment]
I'm not sure how to fix this issue by writing validation, because the error happens IF a request changed by a tool and it can even insert a non-existing column name into request and SQL error happens like `Invalid column x` and the whole SQL appear on the screen.

There are 2 problem here,
First one is the details of the SQL should not be appear on the screen in any case if not in DEBUG mode (but debug mode is only for frontend not for backend). This should nothing to do with validations but should be general rule.

Second, column names should be used from request itself, like in sort column, or at least that sort column should be white-listed and can be silently ignored if it a non-existing column. My colleague will make a PR for this sort column issue today.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
