### ISSUE TITLE
"count(): Parameter must be an array or an object that implements Countable" on line 304 of /srv/http/estheticentre-octomber/modules/cms/classes/CmsCompoundObject.php  Edit Sitemap Item Type Reference CMS Page  Select the page to use for the URL address. Priority Change frequency

### ISSUE THREAD

**Issue by samanthush** [octobercms/october#3518]
##### Expected behavior
`if (count($nameParts) > 1) {`
  line 304 should change as above

##### Actual behavior
`if (count($nameParts > 1)) {`

##### Reproduce steps
installed rainlab sitemap plugin. From sitemap submenu hit additem button and select blog post from type dropdown.

##### October build
system build 431

**Comment by panakour** [comment]
This issue does not depend on october core and instead should placed into [sitemap-plugin](https://github.com/rainlab/sitemap-plugin)

**Comment by LukeTowers** [comment]
@samanthush @panakour This was already fixed in https://github.com/octobercms/october/pull/3326, please update your October instance before reporting issues in the future. (Available in Build 432, the very next build from yours).
