### ISSUE TITLE
[Help Wanted] General Documentation Improvements

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#3519]
OctoberCMS can always benefit from improvements to the documentation. If you notice a typo, a weirdly structure sentence, or perhaps spent some time figuring out how something worked that could have been explain in the [documentation](https://octobercms.com/docs) I would love for you to submit a PR to the [documentation repository](https://github.com/octobercms/docs).

These improvements are always nice to have and much appreciated!

**Comment by daftspunk** [comment]
K
