### ISSUE TITLE
Make a CLI command available to set, change and delete backend users

### ISSUE THREAD

**Issue by CptMeatball** [octobercms/october#3521]
##### Expected behavior
Add, Change and/or Delete backend users from the command line. In this way you can create users without needing to login to the backend (or if you've locked yourself out of the website for example). 

This could be very useful during development or other scenarios. 

##### Actual behavior
There is no way to create backend users at this moment.

##### October build
All.

##### Proposed Ways
- Using tinker , but not sure that's a great solution as passing commands to tinker might be a problem
- Setting user and password in the `.env` file that is picked up by the inital `october:up`.
- Creating CLI commands like: `october:admin create` `change` or `delete`

**Comment by bennothommo** [comment]
I feel this is a bit of security risk in having the command available. Someone who has CLI access could effectively add themselves with full privileges to any October site accessible through CLI, even if they per se don't have access to the database.

**Comment by SebastiaanKloos** [comment]
You can already using Tinker

**Comment by 36864** [comment]
@SebastiaanKloos Tinker is an optional package. 
That said, if a user can run an october command (php artisan october:etc), they can also run arbitrary php code (php -s), or run php in interactive mode (php -a).
I'm having trouble coming up with a server configuration that would allow a user to run october commands but not open an interactive php prompt, load the config files to get database credentials, and then do whatever they want to do.

**Comment by bennothommo** [comment]
The ability to change the password of a Backend user from the CLI has been added: https://github.com/octobercms/october/pull/4836
