### ISSUE TITLE
Why does BackendAuth::register set the current user?

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [octobercms/october#3525]
This is regarding [this line](https://github.com/octobercms/library/blob/master/src/Auth/Manager.php#L93) which also sets the user while returning the newly registered user object. I came across it while writing a plugin that creates a backend user using `BackendAuth::register()`. Basically my plugin has a Foo model which takes in a username, password and other user fields to create an exclusive user for the Foo object but also sets it's created_by field to the currently logged in user to track who originally created the Foo record. Except that when I called `BackendAuth::getUser` after calling `BackendAuth::register` it returns the newly registered user instead of the currently logged in one.

##### Expected behavior
`BackendAuth::register()` should return the newly created user object without setting the current user as the newly registered user object.

##### Actual behavior
`BackendAuth::register()` returns the newly created user object but also sets it's user property to the newly registered user which causes subsequent calls to BackendAuth::getUser to return this newly registered user object rather than the currently logged in user.

##### Reproduce steps
(These were specific to my user case by the bug is more general, I've written the steps anyway...)
1. Scaffold a plugin with a Foo model having a field created_by.
2. Scaffold a controller and set add two fields _first_name, _last_name, _email, _admin_username and _admin_password to fields.yaml with create context.
3. On the Foo controller's override formAfterCreate to get these fields via post() and then called BackendAuth::register to register the new user.
4. Now set the Foo record ($model) variable's created_by field to BackendAuth::getUser(). Instead of setting the currently logged in user which creates the record it would use the user that was created using BackendUser::register instead.

##### October build
434

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/library/commit/fb7d4e8c63994985696938e3c5994c5830d2ed21

**Comment by SaifurRahmanMohsin** [comment]
Excellent, thank you.
