### ISSUE TITLE
[Question] Backend list with a row number

### ISSUE THREAD

**Issue by EdisonLV** [octobercms/october#3528]
Looking for a way to add a row number to the backend list.

```
+------------+------+--------+--------+
| row_number | id   | name   | salary |
+------------+------+--------+--------+
|          5 |    5 | alex   |    100 |
|          4 |    3 | krik   |    500 |
|          3 |    1 | jon    |   1000 |
|          2 |    4 | rook   |   1500 |
|          1 |    2 | darvin |   3500 |
+------------+------+--------+--------+
```

**Comment by munxar** [comment]
something like that? 
http://octobercms.com/docs/database/traits#sortable

**Comment by LukeTowers** [comment]
@EdisonLV @munxar is right, that's the best option for you most likely

**Comment by EdisonLV** [comment]
Will it reassign row numbers if one of the records get deleted?

**Comment by LukeTowers** [comment]
@EdisonLV I don't believe so, but it will retain the sort order. What exactly do you need the row numbers for?
