### ISSUE TITLE
Same site cookie flag not supported

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3529]
Hi I was looking at the cookies on my website and I notice the `october_session` cookie is set to `HTTP` and `SECURE` but not `SameSite`. See screenshot below:

![1](https://user-images.githubusercontent.com/17784082/39339791-756e5bc0-49c2-11e8-8107-80631249d4f6.png)

The goals of the [SameSite](https://tools.ietf.org/html/draft-west-first-party-cookies-07#section-1.1) flag are:

- prevent cross origin timing attacks (see eg [here](https://www.contextis.com//documents/2/Browser_Timing_Attacks.pdf))
- prevent cross origin script inclusion (see [here](https://stackoverflow.com/questions/8028511/what-is-cross-site-script-inclusion-xssi))
- prevent CSRF: SameSite cookies are only sent if the site the request originated from is in the same origin as the target site (in strict mode for GET and POST, in lax mode only for POST requests).
- limited privacy protection

I actually have `SameSite`, `HTTPonly` and `Secure` turned on in my `.HTaccess` so I guess it needs to be added to Octobercms, so I request it as a Conceptual Enhancement. I am a bit surprised it is not there already.

**Comment by Teranode** [comment]
this is in relation to https://github.com/octobercms/october/pull/3455

**Comment by ayumihamsaki** [comment]
Can I ask is it worth adding this package to the OctoberCMS Vendor List? 

https://github.com/paragonie/PHP-Cookie

I like the fact it uses PHP 7 as default and has the basic security level's straight out of the box:

- Secure is set to TRUE unless you override it.
- HTTP-Only is set to TRUE unless you override it.
- Same-Site is set to Strict unless you override it.

**Comment by nathan-van-der-werf** [comment]
SameSite configuration has been added in https://github.com/octobercms/october/pull/3688

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/80942fa2d7d9bf2776815fcb459fcab5bf129a2f
