### ISSUE TITLE
Installing using a project id / attaching to existing installation does not work

### ISSUE THREAD

**Issue by inyono** [octobercms/october#3538]
##### Expected behavior
Installation is successfully bounds to the project with the specified identifier and installs the corresponding plugins.

##### Actual behavior
On Installation, checking the project identifier leads to:
```
Check the supplied Project ID

Server responded with error: Trying to get property of non-object
```
Similarly, when trying to attach project to an existing installation, the flasher shows:
```
Trying to get property of non-object
```

##### Reproduce steps
see above

##### October build
434

**Comment by LukeTowers** [comment]
@inyono why'd you close this?

**Comment by inyono** [comment]
@LukeTowers someone else is already taking care of the problem and might have initiated contact with support. So as long as this is not a general issue (and only with our project), this issue can be closed IMHO. If you want to investigate this yourself, I can send you the project id via email.
