### ISSUE TITLE
Adding octoberapp to private Github repo takes a while

### ISSUE THREAD

**Issue by lunfel** [octobercms/october#3541]
##### Expected behavior
As an plugin author, I want to create a new plugin from a private repository. As the [docs](https://octobercms.com/help/site/authors) mentions it, I add octobercms user to the private repository on Github. The collaboration invitation should be accepted in the next minute by the octoberapp user.

##### Actual behavior
The collaboration invitation does not seem to be accepted.

##### Reproduce steps
1. Create a private Github Repository
2. Go to settings, collaborators and add octoberapp as a collaborator
3. Wait

##### October build
No relevant to the issue.

##### Suggestion

I don't know how long the invitation should take to be accepted. Though, if it is a cronjob that runs once every day, I think the frequency should be mentioned in the docs. Because if it is the case, It leads people to think that the feature is broken assuming that it is instant.

**Comment by LukeTowers** [comment]
@lunfel I believe the invitation acceptance process is currently manual, which is probably the cause of delay.

**Comment by lunfel** [comment]
My bad, I assumed it was all automated, thus wondering why the delay. I then automatically assumed it was broken.

Though this [idea](https://github.com/octobercms/october/issues/3299) seems pretty legitimate as a solution to manually accepting invites.  Because as of now, if any of the maintainers forget to visit the `octoberapp` account to add invitation, the "building" process will be on hold indefinitely.

**Comment by LucasZdv** [comment]
I solved this problem by creating a user to publish my plugins and I used the authentication via url.

http://user:password@github.com/user/repo.git 

I do not think it's the best, but it's a solution.

**Comment by LukeTowers** [comment]
@lunfel it's not even visiting the octoberapp account, it's the email associated with the account; GitHub doesn't send website notifications for pending invites. I agree with the proposed solution however I don't have any control over the marketplace, that's @daftspunk's realm.
