### ISSUE TITLE
Fix Scrolling bug

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3542]
Will add a Pull Request in a minute, to fix this.

## Problem

The icons overlap the scroll bar on many browsers it is fine if the code is short in the editor, but when you have huge amounts of code then the scrollbar becomes small and its hard to press, plus the icons should not overlap the scrollbar in the first place, see screenshot:

![untitled](https://user-images.githubusercontent.com/17784082/39674537-4d718e8c-5145-11e8-8083-3249b8187c7e.png)

## Solution

The file location:

`https://www.example.com/modules/backend/formwidgets/codeeditor/assets/css/codeeditor.css?v435`

The CSS Code (Error):

```
.field-codeeditor .editor-toolbar {
    position: absolute;
    top: 10px;
    right: 10px;
    z-index: 10;
}
```

The CSS Code (Corrected):

```
.field-codeeditor .editor-toolbar {
    position: absolute;
    top: 10px;
    right: 25px;
    z-index: 10;
}
```

Changed the CSS `right` code.

**Comment by LukeTowers** [comment]
@ayumihamsaki please submit a PR containing only the mentioned change to this repo.

**Comment by ayumihamsaki** [comment]
@LukeTowers How do I add a "No newline at end of file" in Github I have done a search and I can't find anywhere the answer that tells you how to add it, only why we should add it.

**Comment by ayumihamsaki** [comment]
@LukeTowers see attached screenshot:

![untitled](https://user-images.githubusercontent.com/17784082/39882600-274be13c-547c-11e8-8a1b-93440da44d2a.png)

**Comment by ayumihamsaki** [comment]
@LukeTowers Ok I have changed text editor and it seems to have created an ok commit now. Please check the details below:

Pull Request found here: [ac86e01](https://github.com/ayumihamsaki/october/commit/ac86e016b94c4277a521843587fff7f4cbdc8f32)

**Comment by LukeTowers** [comment]
@ayumihamsaki that's just a commit to your fork, you need to make a PR on this repo from your repo for me to review and merge it. Also, that's just a change in the compiled file, you'll need to change it in the source LESS file as well.

**Comment by ayumihamsaki** [comment]
@LukeTowers Sorry about that, have corrected everything and made a pull request found here: [3547](https://github.com/octobercms/october/pull/3547)

**Comment by ayumihamsaki** [comment]
Added for future ref.

![untitled](https://user-images.githubusercontent.com/17784082/39967832-a2361ed6-56ba-11e8-921c-9046e216f938.png)
