### ISSUE TITLE
Config not returning values in Test Cases

### ISSUE THREAD

**Issue by bunnyhugdev** [octobercms/october#3552]
##### Expected behavior
When using the Config facade in a PluginTestCase I would expect it to return values from the config/config.php array in the plugin.

##### Actual behavior
It returns an empty array.

##### Reproduce steps
1. Create a test in a class that extends PluginTestCase that loads a config value via Config::get
2. Run via phpunit plugins/author/plugin

##### October build
v1.0.435

**Comment by bunnyhugdev** [comment]
[ConfigTestPlugin.zip](https://github.com/octobercms/october/files/2010868/ConfigTestPlugin.zip)

Here is a plugin that illustrates the issue.

**Comment by LukeTowers** [comment]
Related: https://github.com/octobercms/october/pull/3156

**Comment by LukeTowers** [comment]
Additional documentation added in https://github.com/octobercms/docs/commit/debe336279c5022056668ff534a530e47024abe4
