### ISSUE TITLE
Bug with Components Close icon gets hidden in FireFox on touch screen

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3554]
I have been using October CMS for years but only just clicked on this bug!

It happens when using Firefox and not in Google Canary so I am guessing it is a pseudo CSS error.

## The Bug

When you hover over the component icons the close icon in the top right will disappear in Firefox, seems to work ok in Chome.

~Maybe problem in Opera, as well as FireFox and Opera share this kind of issue...

(Also I should note I am using the latest version of OctoberCMS (v435) and Browsers)

## Show the problem in the wild

Below shows a screenshot of the problem in Firefox Nightly:

![1](https://user-images.githubusercontent.com/17784082/40280510-9b209d46-5c4c-11e8-9fff-b9f6696f4076.png)

Below shows a screenshot of it working fine in Google Canary:

![2](https://user-images.githubusercontent.com/17784082/40280511-9f2bd27a-5c4c-11e8-8228-23ad4913f92a.png)

## Issue

I had a quick check but I can't seem to find the cause of the conflict? The reason the close icon is hidden is that when you hover the component box it is not making a blue background and so the close button is the same color as the background on hover making it hidden.

**Comment by LukeTowers** [comment]
@ayumihamsaki are you able to determine the difference between Firefox and Chrome that's causing Firefox to not pickup the hover style for the components?

**Comment by ayumihamsaki** [comment]
@LukeTowers Hi I think I have found the problem, but I honestly don't fully understand the CSS code used in October CMS.

The issue is in the following file found here:

https://github.com/octobercms/october/blob/master/modules/cms/assets/css/october.components.css

The hover code part is this:

```
.draggable-component-item:hover,
.component-list .components div.layout-cell:hover,
div.control-componentlist div.components div.layout-cell:hover {
  background: #3498db;
}
```

But it is not working because it seems to be overwritten by this piece of code:

```
.touch div.control-componentlist div.components div.layout-cell > div:hover,
.touch div.control-componentlist div.components div.layout-cell > div:active,
.touch div.control-componentlist div.components div.layout-cell > div:active:focus {
  background: #ffffff;
  color: #475354;
}
```

Logically to me I don't understand why you have a CSS hover and background color white for that section?

The simple solution that works is to do this in the CSS:

```
/*
.touch div.control-componentlist div.components div.layout-cell > div:hover,
.touch div.control-componentlist div.components div.layout-cell > div:active,
.touch div.control-componentlist div.components div.layout-cell > div:active:focus {
  background: #ffffff;
  color: #475354;
}
*/
```

Then it works fine in FireFox and for Google Canary (I tested both in a live production).

But I am not sure if that CSS is needed for something important. So I am not happy to do a PR for it. But that is the problem and solution.

**Comment by Teranode** [comment]
Can confirm this happening too on Firefox responsive workflow with touch emulation:
Here's the fix -> Remove this class:
```
div.control-componentlist div.components div.layout-cell > div:hover a.remove {
    color: fff;
}
```

There's a'ready a class dealing with hiding the `x` when you are focused on the component's details, this class hides it on hover and is redundant.

**Comment by LukeTowers** [comment]
Issues should stay open until the fix is merged into master @ayumihamsaki, but thanks

**Comment by LukeTowers** [comment]
@ayumihamsaki it hasn't been merged to master, the release of the build is just a pending build, tagged to develop. We'll go stable next week at which point this stuff will be merged to master.
