### ISSUE TITLE
[Marketplace] Upload images that don't show in slideshow

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#356]
I'd like to be able to upload images that won't show in the slideshow at the top, but are instead used in the documentation. At the moment we're forced to choose between filling our slideshow with images that don't make sense as promotional material or linking to images hosted on third party sites like imgur.

**Comment by daftspunk** [comment]
This is a stretch, a banner image will be introduced soon and imgur is a suitable way to host ad-hoc images, along with hosting them yourself.
