### ISSUE TITLE
Does debug extension need the controller?

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#3563]
https://github.com/octobercms/october/blob/8ba63dd428b425a3722fb18c6ce5e58f03be5314/modules/cms/twig/DebugExtension.php#L54-L61

The debug extension requires the controller in its constructor but doesn't reference it anywhere. Should this be refactored out?

**Comment by LukeTowers** [comment]
@SeriousKen is it causing any problems to have it there?

**Comment by SeriousKen** [comment]
It's not causing a problem as such, but I noticed it when looking into [this issue](https://github.com/rainlab/pages-plugin/issues/337l) in the Pages plugin. The Twig environment is newed up in the CmsCompoundObject without the DebugExtension, but you can't new up the DebugExtension without a controller instance, which the CmsCompoundObject doesn't have access to.

Also, in the interests of clean code, anything that is redundant should be removed.

**Comment by Samuell1** [comment]
@LukeTowers

**Comment by bennothommo** [comment]
@Samuell1 I'll leave this open. It's something that may need to be looked into in the future.

**Comment by Samuell1** [comment]
@bennothommo it was just ping if this is actual, i can then do PR to remove it

**Comment by bennothommo** [comment]
@Samuell1 by all means, have a go at it if you want to :). Probably is worth having a look at.
