### ISSUE TITLE
Composer require october/* fails due fixed doctrine/dbal version

### ISSUE THREAD

**Issue by stefanbinder** [octobercms/october#3564]
##### Expected behavior
composer require october/system october/backend october/cms
Should install the packages in the laravel package.

doctrine/dbal is installed with version 2.7.1

##### Actual behavior
composer require october/system october/backend october/cms

Fails with errors like:
 - Conclusion: don't install doctrine/dbal v2.5.1
    - Conclusion: remove doctrine/common v2.8.1
    - Installation request for doctrine/dbal 2.5.* -> satisfiable by doctrine/dbal[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.13, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9].
    - Conclusion: don't install doctrine/common v2.8.1
    - doctrine/dbal v2.5.0 requires doctrine/common >=2.4,<2.6-dev -> satisfiable by doctrine/common[v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.5.0, v2.5.1, v2.5.2, v2.5.3].
    - Can only install one of: doctrine/common[v2.4.0, v2.8.1].
    - Installation request for doctrine/common (locked at v2.8.1) -> satisfiable by doctrine/common[v2.8.1].

##### Reproduce steps
Install doctrine/doc package and after install the october/* packages via composer.
Leads to dependency problems.

##### October build
october/rain v1.0.436

**Comment by LukeTowers** [comment]
@stefanbinder please explain the exact steps you are taking to go from nothing to this issue occurring.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
