### ISSUE TITLE
[New feature] More controls on the HTML 5 video/audio player

### ISSUE THREAD

**Issue by pvullioud** [octobercms/october#3565]
##### Expected behavior
I would like to have more control on the HTML video/audio player. Mute, loop, autoplay, controls etc.  
See option details of the options: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

##### Actual behavior
It's hard coded at the moment

https://github.com/octobercms/october/blob/8ba63dd428b425a3722fb18c6ce5e58f03be5314/modules/cms/classes/MediaViewHelper.php#L97

**Comment by LukeTowers** [comment]
@pvullioud please post your solution to posted problems for other people that may have similar problems to learn more in the future.

**Comment by pvullioud** [comment]
I didn't find a easy solution to customize the video dialog of the FroalaEditor. So I have done my changes directly in the HTML code.
