### ISSUE TITLE
MailBrandSetting - CSS body height

### ISSUE THREAD

**Issue by matteotrubini** [octobercms/october#3569]
https://github.com/octobercms/october/blob/4074ad8cc9c20a3196f058e908d98c5efca9ad1b/modules/system/models/mailbrandsetting/custom.less#L11

It create quote style error on Thunderbird replies:

![screen](https://user-images.githubusercontent.com/7964032/40770780-f1f0dfba-64bb-11e8-81e8-7ef4237f8b0d.png)

Maybe your orginal intention was to set `min-height: 100%` ? It solve the error on Thunderbird as well.

**Comment by LukeTowers** [comment]
@matteotrubini please make a PR including your fix along with testing it in all major email clients / web clients.

**Comment by matteotrubini** [comment]
I can make the PR, but I haven't the time to create a complete testing coverage.
Anyway, `min-height: 100%` ensure `height: 100%;`, so a regression is impossible de facto.

**Comment by LukeTowers** [comment]
@matteotrubini at least test it in the mail clients you have access to then please.

**Comment by LukeTowers** [comment]
@matteotrubini ping?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
