### ISSUE TITLE
Error viewing entries in the Request log detail view on PHP 7.2

### ISSUE THREAD

**Issue by Yasu-San** [octobercms/october#3570]
##### Request location
/backend/system/requestlogs/preview/6

##### Expected behavior
See some details about the entry

##### Actual behavior
Get the following Error-Message:
> count(): Parameter must be an array or an object that implements Countable
> ~/modules/system/controllers/requestlogs/_referer_field.htm line 1

Number | Called Code | Document | Line
---|---|---|---
71 | include(…) | ~/modules/system/traits/ViewMaker.php | 244
70 | Backend\Classes\Controller->makeFileContents(…) | ~/modules/system/traits/ViewMaker.php | 98
69 | Backend\Classes\Controller->makePartial(…) | ~/modules/backend/widgets/form/partials/_field_partial.htm | 7
68 | include(…) | ~/modules/system/traits/ViewMaker.php | 244
67 | Backend\Classes\WidgetBase->makeFileContents(…) | ~/modules/system/traits/ViewMaker.php | 98
66 | Backend\Classes\WidgetBase->makePartial(…) | ~/modules/backend/widgets/Form.php | 273
65 | Backend\Widgets\Form->renderFieldElement(…) | ~/modules/backend/widgets/form/partials/_field.htm | 22
64 | include(…) | ~/modules/system/traits/ViewMaker.php | 244
63 | Backend\Classes\WidgetBase->makeFileContents(…) | ~/modules/system/traits/ViewMaker.php | 98
62 | Backend\Classes\WidgetBase->makePartial(…) | ~/modules/backend/widgets/form/partials/_field-container.htm | 8
61 | include(…) | ~/modules/system/traits/ViewMaker.php | 244
60 | Backend\Classes\WidgetBase->makeFileContents(…) | ~/modules/system/traits/ViewMaker.php | 98
59 | Backend\Classes\WidgetBase->makePartial(…) | ~/modules/backend/widgets/form/partials/_form_fields.htm | 2
58 | include(…) | ~/modules/system/traits/ViewMaker.php | 244
57 | Backend\Classes\WidgetBase->makeFileContents(…) | ~/modules/system/traits/ViewMaker.php | 98
56 | Backend\Classes\WidgetBase->makePartial(…) | ~/modules/backend/widgets/form/partials/_section.htm | 17
55 | include(…) | ~/modules/system/traits/ViewMaker.php | 244
54 | Backend\Classes\WidgetBase->makeFileContents(…) | ~/modules/system/traits/ViewMaker.php | 98
53 | Backend\Classes\WidgetBase->makePartial(…) | ~/modules/backend/widgets/form/partials/_form.htm | 3
52 | include(…) | ~/modules/system/traits/ViewMaker.php | 244
51 | Backend\Classes\WidgetBase->makeFileContents(…) | ~/modules/system/traits/ViewMaker.php | 98
50 | Backend\Classes\WidgetBase->makePartial(…) | ~/modules/backend/widgets/form/partials/_form-container.htm | 8
49 | include(…) | ~/modules/system/traits/ViewMaker.php | 244
48 | Backend\Classes\WidgetBase->makeFileContents(…) | ~/modules/system/traits/ViewMaker.php | 98
47 | Backend\Classes\WidgetBase->makePartial(…) | ~/modules/backend/widgets/Form.php | 227
46 | Backend\Widgets\Form->render(…) | ~/modules/backend/behaviors/FormController.php | 404
45 | Backend\Behaviors\FormController->formRender(…) | ~/modules/backend/behaviors/FormController.php | 551
44 | Backend\Behaviors\FormController->formRenderPreview() |   |  
43 | call_user_func_array(…) | ~/vendor/october/rain/src/Extension/ExtendableTrait.php | 379
42 | October\Rain\Extension\Extendable->extendableCall(…) | ~/vendor/october/rain/src/Extension/Extendable.php | 46
41 | October\Rain\Extension\Extendable->__call(…) | ~/modules/system/controllers/requestlogs/preview.htm | 32
40 | include(…) | ~/modules/system/traits/ViewMaker.php | 244
39 | Backend\Classes\Controller->makeFileContents(…) | ~/modules/system/traits/ViewMaker.php | 110
38 | Backend\Classes\Controller->makeView(…) | ~/modules/backend/classes/Controller.php | 365
37 | Backend\Classes\Controller->execPageAction(…) | ~/modules/backend/classes/Controller.php | 247
36 | Backend\Classes\Controller->run(…) | ~/modules/backend/classes/BackendController.php | 95
35 | Backend\Classes\BackendController->run(…) |   |  
34 | call_user_func_array(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Controller.php | 54
33 | Illuminate\Routing\Controller->callAction(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php | 45
32 | Illuminate\Routing\ControllerDispatcher->dispatch(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Route.php | 212
31 | Illuminate\Routing\Route->runController() | ~/vendor/laravel/framework/src/Illuminate/Routing/Route.php | 169
30 | Illuminate\Routing\Route->run() | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 658
29 | Illuminate\Routing\Router->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 30
28 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php | 41
27 | Illuminate\Routing\Middleware\SubstituteBindings->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
26 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
25 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php | 49
24 | Illuminate\View\Middleware\ShareErrorsFromSession->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
23 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
22 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php | 63
21 | Illuminate\Session\Middleware\StartSession->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
20 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
19 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php | 37
18 | Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
17 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
16 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php | 59
15 | Illuminate\Cookie\Middleware\EncryptCookies->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
14 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
13 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 102
12 | Illuminate\Pipeline\Pipeline->then(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 660
11 | Illuminate\Routing\Router->runRouteWithinStack(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 635
10 | Illuminate\Routing\Router->runRoute(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Router.php | 601
9 | Illuminate\Routing\Router->dispatchToRoute(…) | ~/vendor/october/rain/src/Router/CoreRouter.php | 20
8 | October\Rain\Router\CoreRouter->dispatch(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php | 176
7 | Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 30
6 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php | 46
5 | Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 149
4 | Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php | 53
3 | Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(…) | ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php | 102
2 | Illuminate\Pipeline\Pipeline->then(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php | 151
1 | Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(…) | ~/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php | 116
0 | Illuminate\Foundation\Http\Kernel->handle(…) | ~/index.php | 43

##### Reproduce steps
- Login to the Backend
- goto settings and activate request-logs (logs->log settings->Log bad requests)
- create multiple requests (that results in a 404-Error) from different/no refferer-urls
- try to open details of the entries

##### October build
434

**Comment by LukeTowers** [comment]
@Yasu-San What details are you wanting to see? Error logs have stack traces, request logs are just logging requests that resulted in a 404 response.

**Comment by Yasu-San** [comment]
@LukeTowers I opend /backend/system/requestlogs and clicked on an entry in the list, after this, some entries show their details. Some others throw the error.

I've added a screenshot, where you can see the view I try to access:
![detail-view of a working entry](https://user-images.githubusercontent.com/19592790/40799245-55139960-650d-11e8-836d-0bb13f4a296f.png)

**Comment by LukeTowers** [comment]
@Yasu-San Ah, so opening the details page throws the error. What version of PHP are you using? What are you using for your server?

**Comment by Yasu-San** [comment]
I'm using PHP-Version 7.2.5 with the Apache-Webserver (2.4.25)

**Comment by LukeTowers** [comment]
@Yasu-San try changing https://github.com/octobercms/october/blob/master/modules/system/controllers/requestlogs/_referer_field.htm#L1 to `<?php if (!empty($formModel->referer) && count($formModel->referer) > 0): ?>

**Comment by Yasu-San** [comment]
This works:
`<?php if ($formModel->referer && count($formModel->referer) > 0): ?>`

**Comment by LukeTowers** [comment]
@Yasu-San please make a PR to fix it for everyone else too

**Comment by danharrin** [comment]
@Yasu-San I'll do it, don't worry.

**Comment by Yasu-San** [comment]
@danharrin Thank you, too.
