### ISSUE TITLE
Minor Bug: Saving... Appears over buttons etc.

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3571]
I am sure this is not correct.

Everytime I click on the save button in the cms a grey text says "Saving..." 

See below screenshot:

![untitled](https://user-images.githubusercontent.com/17784082/40791335-2aece182-64ef-11e8-90cd-7f1877ca2218.png)

It's like an overkill and I suggest removing it. Having the spinning icon is more than enough! 

So I suggest removing the word "Saving..." in grey that is very hard to read and just looks not very nice. Or at least don't have it overlapping the button. (Either remove it or place it under the buttons)

I see this in both Latest Google Canary and Firefox nightly.

Would it not be better to have it like this:

![untitled](https://user-images.githubusercontent.com/17784082/40794692-d3458e76-64f7-11e8-926e-2856854a8c3b.png)

~October seems to use very old CSS and no flexbox or css grids etc.

**Comment by LukeTowers** [comment]
@ayumihamsaki I've seen this myself too recently, this is due to a change that was made in the CSS for the loading indicator that removed it's background colour because it didn't make sense in a different context. We just need to re-add the background colour, ideally only targeting the button context. The idea behind having it appear over the buttons with a solid background colour is to prevent the user from clicking on any of the other buttons while an action is occurring.

**Comment by LukeTowers** [comment]
Found it: https://github.com/octobercms/october/pull/3394. @ayumihamsaki could you investigate a styling change that would only target the button group loading indicator to apply the `body-bg` background colour?

**Comment by ayumihamsaki** [comment]
@LukeTowers Thanks for the extra info, now makes sense why I have seen this for last few months. Will have a think on some styling, also I think OctoberCMS has very poor CSS, for example it would most likely fail WCAG 2.0 (AA) spec. The light grey background behind a sightly darker grey icon surely must fail and is hard to view! Therefore most likely there would need to be quite a lot of work done to Octobercms CSS to correct many errors.

I feel this fix is not straight forward as October uses many things: saving, updating, creating, deleting etc. all in many places. Will have a think on it, but don't expect a quick solution from my side on this one lol.

**Comment by LukeTowers** [comment]
@ayumihamsaki thanks for looking into this! Is there anyway we can retain the old behaviour of putting the loading indicator directly overtop of the buttons with a solid background colour?

Also, I appreciate the sense of urgency but it's not really that urgent :)
Low: Should be taken care of eventually, whenever someone gets around to caring about it
Medium: Should be taken care of eventually, whether or not someone finds it interesting
High: Needs to get taken care of sooner rather than later
Critical: Needs to get taken care of right now

**Comment by ayumihamsaki** [comment]
@LukeTowers Done some testing and decided to use a CSS wrapper, as I only wanted to modify the form buttons the HTML code looks like this on most things:

```
<div class="form-buttons">
  <div class="loading-indicator-container">
    <div class="loading-indicator"><div>Saving...</div><span></span></div>
    <button type="submit" data-request="onSave" data-request-data="redirect:0" data-hotkey="ctrl+s, cmd+s" data-load-indicator="Saving..." class="btn btn-primary" data-disposable="">Save </button>
    <button type="button" data-request="onSave" data-request-data="close:1" data-hotkey="ctrl+enter, cmd+enter" data-load-indicator="Saving..." class="btn btn-default" data-disposable="">Save and close </button>
    <button type="button" class="oc-icon-trash-o btn-icon danger pull-right" data-request="onDelete" data-load-indicator="Deleting..." data-request-confirm="Delete record?"></button>
    <span class="btn-text">or <a href="https://www.example.com/something">Cancel</a></span>
  </div>
</div>
```

So I used the CSS Wrapper of `class="form-buttons"` then everything else in OctoberCMS won't get moved about and will pass the connected issue: #3394.

The code I came up with is as follows:

```
.form-buttons .loading-indicator-container .loading-indicator {
    position: initial;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    padding-top: 0;
    display: block;
    overflow: hidden;
}
.form-buttons .loading-indicator-container .loading-indicator > div {
    position:initial;
    top: 0;
    margin-top: 0;
}
.form-buttons .loading-indicator > span {
    background: transparent url(images/loader.gif) no-repeat 0 50%;
    position: absolute;
    width: 40px;
    height: 40px;
    top: 0;
    margin-top: -30px;
    left: 0;
    display: block;
}
```

I added it to the file: https://github.com/octobercms/october/blob/master/modules/system/assets/ui/storm.css

It seemed to work fine on many plugins inside OctoberCMS.

Please let me know if this is ok? Also, I am not sure what `.LESS` file to add the code? So let me know and I can create a PR for it.

p.s. Will save the Urgency spec. so will know in future.

**Comment by ayumihamsaki** [comment]
p.s.

> Is there anyway we can retain the old behaviour of putting the loading indicator directly overtop of the buttons with a solid background colour?

I can't remember what that looked like?

**Comment by LukeTowers** [comment]
@ayumihamsaki simply add https://github.com/octobercms/october/pull/3394/files#diff-32cf12182ddb231cba61cc55b18331e2L20 back to loader.less under the selector `.form-controls .loading-indicator`

**Comment by ayumihamsaki** [comment]
@LukeTowers yah just released that too hahaha will create a PR for it.
