### ISSUE TITLE
Markdown header in cms content broken

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#3581]
##### Expected behavior
Create a content item with a header using ==== should work eg

```
Hello World!
========
```

gets rendered as

```
<h1>Hello World!</h1>
```

##### Actual behavior
The ==== gets treated as an October section divider

##### Reproduce steps
Create a Markdown content item with a header
Add it to a page
View the page, anything before and including the ==== is not rendered
Open the content in the backend for editing and anything before and including the ==== is not visible in the code editor.

##### October build
Fresh install of 436

**Comment by LukeTowers** [comment]
The code that does this processing is here: https://github.com/octobercms/library/blob/master/src/Halcyon/Processors/SectionParser.php#L117. Perhaps you can make a PR to improve it and then add some tests to prevent this from happening in the future?

In regards to your immediate issue, why not just use `#` for headers? I.e. `# h1`, `## h2`, etc
