### ISSUE TITLE
Drivers Plugin: Update guzzlehttp/guzzle dependency for PHP 7.2

### ISSUE THREAD

**Issue by jvanremoortere** [octobercms/october#3584]
Please update guzzlehttp/guzzle to avoid error with aws (when using php 7.2)
```
AWS HTTP error: count(): Parameter must be an array or an object that implements Countable
```

**Comment by LukeTowers** [comment]
@goeroe submit a PR to https://github.com/octoberrain/drivers-plugin, unless you installed via the marketplace, in which case first try to install the drivers plugin with Composer instead.

**Comment by TimFoerster** [comment]
I had the same problem, i manually ran `composer update` in the driver plugin, since it is not pulling new versions.

**Comment by Samuell1** [comment]
Looks like guzzle is already updated in drivers-plugin @LukeTowers

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octoberrain/drivers-plugin/commit/40f6a8272738ade54aac7133f783e92818fe45a5
