### ISSUE TITLE
Cannot find any plugin by searching for any text

### ISSUE THREAD

**Issue by cc1683** [octobercms/october#3586]
I try to install plugin via backend, but cannot find any plugin by searching for the text. However, it appear by searching for the unique code. 

![screenshot from 2018-06-07 12-28-51](https://user-images.githubusercontent.com/30225420/41078391-247bcdb2-6a4f-11e8-9c9a-c7e3dac8e0d7.png)
##### October build
(436)

**Comment by LukeTowers** [comment]
@cc1683 and what's the issue here? It says right in the instructions: 

> Name the plugin by **its unique code.** For example, RainLab.Blog

**Comment by cc1683** [comment]
Sorry, I'm new to October. So, where to find the unique code and cant we just searching for the plugin by text?
![screenshot from 2018-06-07 12-42-48](https://user-images.githubusercontent.com/30225420/41078702-e6f94ae4-6a50-11e8-93e8-2a9178f1f9ac.png)

**Comment by LukeTowers** [comment]
@cc1683 the code is just the Author.PluginName. You can see the examples on the right of Lovata.Shopaholic and RainLab.Notify. Another easy way to find the code is look at the URL on the marketplace: https://octobercms.com/plugin/martin-forms. The part before the `-` is the author and the part afterwards is the plugin name. So `Martin.Forms` would be the plugin code.

**Comment by cc1683** [comment]
oh, alright, thanks you so much.

**Comment by LukeTowers** [comment]
Not a problem!
