### ISSUE TITLE
How does the CMS find out in which file the URL is being processed in October?

### ISSUE THREAD

**Issue by koliane** [octobercms/october#3588]
The URL in October cms is processed by default on page pages. But they can also be processed in plug-ins in the routes.php file.
Suppose that the site consists of a large number of pages and plug-ins.
How can I quickly determine where exactly the full URL is processed?

`php artisan route`: the list shows the following:
http://dl4.joxi.net/drive/2018/04/23/0026/0604/1753692/92/51df8de65b.jpg
api / hello is processed in the routes.php file in one of the plugins, but where it is not specifically displayed.
The site is full of pages that are displayed with certain URIs, and there are no pages on the image

**Comment by LukeTowers** [comment]
/backend/* is handled by the backend module, routes registered in routes.php are handled by the plugins that register them, all other urls are handled by cms\classes\controller which in turn looks at CMS\classes\router

**Comment by LukeTowers** [comment]
Specifically in your case you're going to want to look for pages in thrmes/activetheme/pages

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
