### ISSUE TITLE
add sparkpost driver to configuration file MailSetting.php

### ISSUE THREAD

**Issue by perseon** [octobercms/october#3589]
##### Expected behavior
Use sparkpost driver to send emails.

##### Actual behavior
Sparkpost configuration is incomplete. Following documentation steps will result in email being rejected from API with unauthorised. I had to edit MailSetting.php and 
add static::MODE_SPARKPOST=> 'system::lang.mail.sparkpost' on line 78

##### October build
current build

https://github.com/octobercms/october/blob/5ee8ee09170fa52cd6bb5dbb2416345aeea186e5/modules/system/models/MailSetting.php#L78

**Comment by LukeTowers** [comment]
@perseon feel free to make a PR to fix this

**Comment by Samuell1** [comment]
Sparkpost is removed from laravel core in Laravel 6.0.

**Comment by LukeTowers** [comment]
@Samuell1 what packages are recommended for those drivers? We'll have to make sure we bring them back in.

**Comment by Samuell1** [comment]
@LukeTowers none, thats why it was removed because of deprecation?

**Comment by LukeTowers** [comment]
@Samuell1 looks like we just need to revert https://github.com/laravel/framework/commit/e2461f19c3b951f7cbb4b424601cad1f6553774a#diff-c1d5bf1c77457840314f00f3837a2b2a in octobercms/library
