### ISSUE TITLE
Improve developer experience with regard to incorrect plugin migrations

### ISSUE THREAD

**Issue by scottbedard** [octobercms/october#3590]
Hi, I'm assuming this request will be ok, but figured I should double check before poking around in our plugin migration code. I'd like migrations to throw an error / warning when there is a reference to a non-existent migration file. This isn't necessarily a bug, just something that I learned first hand can turn a typo into lots of wasted time.

##### Reproduce steps
1. In a plugin's `versions.yaml` file, add a reference to a migration file that does not exist
2. Refresh / migrate the plugin

##### Expected behavior
October should let me know that the migration didn't run

##### Actual behavior
Everything appears to have worked as expected, even though the migration did not run.

##### October build
436

**Comment by LukeTowers** [comment]
@scottbedard feel free to make a PR

**Comment by scottbedard** [comment]
Awesome, I'll take a crack at it this weekend
