### ISSUE TITLE
Routes with %2F not routing correctly

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#3592]
##### Expected behavior
When a route of `/calendar/:academicYear` is created the URL `/calendar/2018%2F2019` should route to a calendar with the `academicYear` parameter `2018/2019`

##### Actual behavior
This results in a 404 as the routing seems to treat the %2F as an actual slash, presumably it is decoding the URL before splitting

https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters

##### Reproduce steps
Create the following page and try the above route

```
title = "calendar"
url = "/calendar/:academicYear"
is_hidden = 0
==
<?php
function onStart()
{
    $this['academicYear'] = $this->param('academicYear');
}
?>
==
{{ academicYear }}
```

##### October build
Build 436

**Comment by LukeTowers** [comment]
@SeriousKen try throwing some debug statements in https://github.com/octobercms/october/blob/master/modules/cms/classes/Router.php to figure out when the URL gets converted

**Comment by SeriousKen** [comment]
@LukeTowers the URL is decoded before it gets passed to the `run` method of the `CmsController` so it looks like it's the Laravel router itself that's doing the decoding. A search on [Laravel's Gitub issues](https://github.com/laravel/framework/issues/22125) shows this to be the case, but there seems to be disagreement as to whether the current behaviour is correct or not.

**Comment by LukeTowers** [comment]
@seriousken make a PR to octobercms/library implementing a solution along the lines of https://github.com/laravel/framework/pull/4338 but make the behaviour configurable with a config.php entry in octobercms/october and set the default to be the current behaviour

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by LukeTowers** [comment]
@SeriousKen I just ran into this issue myself while working on the image resizer PR. What did you end up doing to get around it?

**Comment by Samuell1** [comment]
@LukeTowers Isnt better to split params to 2 separate and call them and merge them together in code? Like `/calendar/2018/2019` then get firstyear and secondyear

And its not issue in laravel but symfony has this https://symfony.com/doc/current/routing.html#slash-characters-in-route-parameters

Another solution is that replace slashes with for example other character and them in code replace back to slash. Or maybe like said here guy encoded it twice https://github.com/laravel/framework/issues/22125#issuecomment-623747380

**Comment by LukeTowers** [comment]
@Samuell1 in my case I'm trying to pass a URL as a parameter, which would require the use of a slash character. Double encoding it is a good idea though.

**Comment by LukeTowers** [comment]
@Samuell1 also the symfony issue is different I believe, I think if you passed a URL encoded / to a route param in symfony it would work fine because it doesn't try to decode the path before parsing it like Laravel does.

**Comment by LukeTowers** [comment]
Since changing this behaviour could cause breaking changes, we're going to leave it as it is and say that our official recommendation is to double encode any URL params that require slashes in them (note that Laravel's official recommendation is different, see https://github.com/laravel/docs/pull/4785/files).
