### ISSUE TITLE
FIXED ERROR EXCEPTION - Template ("mb_substr_count(): Unknown encoding "0"") - after successful fresh install.

### ISSUE THREAD

**Issue by roulendz** [octobercms/october#3593]
It is definetly not regarding OctoberCMS, but something wrong with server settngs, and I can not figure out what. 
Previously I installed on the same server/hosting, all worked like a charm :)
##### Expected behavior
Expecting to open fresh install of OC.
Deme theme.

##### Actual behavior
Default OC installation with Wizzard installation throws error after installation is successfull and I try to open web page.
```
/themes/demo/pages/home.htm line 3
```
```
An exception has been thrown during the compilation of a template ("mb_substr_count(): Unknown encoding "0"").
/themes/demo/pages/home.htm line 3

TYPE
Twig Template

EXCEPTION
Cms\Classes\CmsException
```
```
1title = "Demonstration"
2url = "/"
3layout = "default"
4==
5<div class="jumbotron">
6    <div class="container">
7        {% content "welcome.htm" %}
8    </div>
9</div>
10  
11<div class="container">
12 
13    <div class="page-header">
```

##### Reproduce steps
Install on shared hosting using Wizard Installation.

**Comment by roulendz** [comment]
All is good!

Needed to disable 
mbstring in PHP settings.

Other option was
in . htaccess
add
```
mbstring.func_overload = 0
```
### Now all works!

**Comment by LukeTowers** [comment]
@roulendz disabling mb_string caused your other issue, find a different solution to this, try the htaccess one
