### ISSUE TITLE
Issues with signing out after modifying the application timezone

### ISSUE THREAD

**Issue by Gamertech** [octobercms/october#3596]
##### Expected behavior
Clicking signout link properly closes session and prevents access to backend.

##### Actual behavior
Signout doesn't clear session and the backend remains accessible.

After clicking signout, you may randomly be redirected to the login page while browsing the backend, but again browsing to the dashboard url will continue the session.

##### Reproduce steps
-Clicking signout either redirects to login page, but browsing to the backend url takes you straight to the dashboard, or
-Clicking signout just redirects you to the dashboard straight away and session continues.

##### October build
436 fresh install

##### Installed Plugins
News and Newsletter
Rainlab Blog
Clear Cache
Flexi Contact
Sitemap
Magnific Gallery

Currently using the default file caching and session driver. Link policy set to secure, site is on Cloudflare but the backend url is exempt from caching.

"Possibly" related to changing the timezone, but can't confirm at this stage. Sessions should be invalidated immediately once the link is clicked.

**Comment by LukeTowers** [comment]
Sounds like there's an issue when attempting to remove the sessions in your environment, I was unable to replicate this on a fresh install of October

**Comment by Gamertech** [comment]
I believe it's linked to changing the timezone, either in the backend or in the config. Sessions logout correctly since I reverted back to UTC.

**Comment by Gamertech** [comment]
Yea, editing the timezone in the config while logged in will prevent normal logout and keep the session live.
It sometimes recognises that the session has ended and kicks you back to the login page when browsing, but continues to allow access if you browse back to the backend page.
It's trying to invalidate the session but is being overridden by something to still allow access. I'm moving time forward, so if the session times are staying the same, then would possibly be caused by the session logout "not having happened yet".
Ideally October should completely dump the session on the server after signout and block the use of any cookies attached to that session even if the times don't line up.

**Comment by LukeTowers** [comment]
@Gamertech feel free to dig deeper and see if you can come up with a PR to fix that

**Comment by LukeTowers** [comment]
@Gamertech could you test this with the latest develop branch of the OctoberRain library: https://github.com/octobercms/library/commit/f73fea160379496d227d867405e5a2b498cd5b27

**Comment by Gamertech** [comment]
No, doesn't affect it at all. Clicking the Sign Out link just refreshes/browses to the dashboard with no errors after changing the app's time forward.

**Comment by Samuell1** [comment]
Best is to have system at UTC to prevent any issues with timezones. I think it even says in config to dont change that value :D

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
