### ISSUE TITLE
AJAX Invalid form token produces no error

### ISSUE THREAD

**Issue by firemankurt** [octobercms/october#3599]
##### Expected behavior
When for token is tampered with, Ajax form submission should result in an error before handler is executed.

##### Actual behavior
Form submission produces no error and handler is executed.  Data is saved as if the token were valid.

##### Reproduce steps
use 

    {{ form_ajax('onEditSave',{ 'data-request-data':'id:'~ __SELF__.model.id }) }} 

to produce the form tag and _token  field.
Load form and Use Chrome browser inspector to modify the "_token" field value to make it invalid.
Submit form.
##### October build
436

##### Possible cause

$this->execAjaxHandlers() triggers $this->runAjaxHandler($handler) before token is checked at line 

https://github.com/octobercms/october/blob/5ee8ee09170fa52cd6bb5dbb2416345aeea186e5/modules/cms/classes/Controller.php#L328

before 

https://github.com/octobercms/october/blob/5ee8ee09170fa52cd6bb5dbb2416345aeea186e5/modules/cms/classes/Controller.php#L338

is executed.

**Comment by Samuell1** [comment]
Is this still issue?

**Comment by firemankurt** [comment]
I can still edit/modify token and I get no error when I submit forms that have a token in backend.
Am I not understanding what tokens are for?

**Comment by Samuell1** [comment]
@firemankurt Token is for validation of request if CSRF is enabled. https://github.com/octobercms/october/blob/master/config/cms.php#L374

**Comment by bennothommo** [comment]
It still needs to be confirmed first.

**Comment by firemankurt** [comment]
OK.  I did not know that I had to add  'enableCsrfProtection' => true, to cms.php

Why is this not the default?

**Comment by LukeTowers** [comment]
@firemankurt it's been the default for a while now, but default config values aren't updated when you update the CMS

**Comment by firemankurt** [comment]
If this is supposed to work on the frontend then there is still an issue.
