### ISSUE TITLE
Plugin required dependencies

### ISSUE THREAD

**Issue by daftspunk** [octobercms/october#36]
A core function of October, interconnected plugins should define their relationships to each other called "required dependencies".

The dependant plugin will require its dependency or dependencies (required plugins). This definition will produce some outcomes:
## Active ideas
- The package server should mimic composer where possible. If a requirement is not found in the system, it will be automatically installed (FREE only).
- Paid plugins cannot be installed automatically, a warning must be displayed to notify the user that this plugin is disabled because it requires a paid plugin and project usage.
- The client needs to tell the server what version it needs. See #785 "locked snapshot".
- The server needs to analyse plugin definitions and save the requirements, for display on the UI and for automatic delivery.
- The `$require` property values should support `@1.0.1` suffix to indicate the minimum version required.
- A special code `Core` is needed to signify a minimum core build. eg: `Core@154` requires core build 154 or later.
## Implemented ideas
- <s>If a dependant plugin is present in the file system but its required plugins are not, the dependant plugin will not be loaded to prevent system errors.</s>
- <s>During database migration, required plugins should have their version history built before dependant plugins.</s>
- <s>In honour of the `$implement` definition for behavior usage, the definition can be stored in the `$require` property, found in the Plugin registration file. The prototype code can look like this:</s>

```
public $require = [
    'October.Blog',
    'October.Demo@1.0.1'
];
```
## Old ideas (won't implement):
- If a dependant plugin is installed or added to a project for the first time, the UI will prompt the user to include the required plugins as well.
- As above, if a required plugin has an associated cost, the dependant plugin will be installed in an incomplete state, not loaded to prevent system errors and the UI will alert the user to consider purchasing it.

Prompt messages:

```
October.Blog requires October.Demo to be installed, click OK to install it.

                              [ Ok | Cancel ]
```

```
October.Blog requires some other plugins to operate:

* Acme.XXX ($9.99)
* Acme.YYY ($4.99)

Consider purchasing the required plugins before using this plugin.

                              [ Ok ]
```

**Comment by daftspunk** [comment]
Refs https://github.com/rainlab/userplus-plugin/issues/9

**Comment by october-fan** [comment]
I've been a huge fan of OctoberCMS since I completed my last project using it. Very nice work, gentlemen.

I could never understand from the get-go why plugins can't just be plain Composer packages (or can they???). I'm pretty sure this was a design decision that you did not make lightly. But I can't help saying that that you probably would not be wrestling with plugin dependency resolution if they were, since that is what Composer does right out of the box.

**Comment by daftspunk** [comment]
Hey there @october-fan! We did spend quite a bit of time exploring this option, the main problem is composer requires git to be installed and it needs ~1GB of RAM to function. In this light, composer is supported as a second class citizen (so you can use it if you want). The update process used by the October gateway simplifies everything and is much faster. Internally October handles the dependencies just fine, it lacks in the UX/UI department, which is what this issue tries to address.

**Comment by valiknet18** [comment]
I've some problem, when i want extend Rainlab.User plugin, and in own plugin use 
```
public $require = [
        'Rainlab.User'
    ];
```
i get error
```
Class name is not registered for the component "RegistrationForm". Check the component plugin.
```
But without this definition, application worked fine

**Comment by jBOKA** [comment]
I guess is has to be `RainLab.User` with a capital `L`.

Give it a try

**Comment by daftspunk** [comment]
We can finally see the back of this issue. The server will now process the `$require` property on plugins and store those relationships. When installing a plugin, the information of those required plugins will also be supplied, the system will check if it has them and if not, it will download the entire bundle for installation.
