### ISSUE TITLE
Backend sidemenu broken with Cloudflare SSL

### ISSUE THREAD

**Issue by joaocosta90** [octobercms/october#3602]
## Expected behavior
Try to use the sidemenu ( Pages, Partials, Layouts,.. ).

## Actual behavior
Doesn't change anything. The href is: javascript:;

## Reproduce steps
Just got cloudflare running on my domain.

## October build
Build number: 436

Any idea why this is happening? Already try some previous solution but didn't manage to fix the issue. Thanks.

![screen shot 2018-06-21 at 17 11 49](https://user-images.githubusercontent.com/10947465/41731652-cf37d02a-7576-11e8-9952-d493845500c8.png)

**Comment by zakir1929** [comment]
Hi
You need to stop cloudflare performance by creating a page rule on cloudflare dashboard.
so login on cloudflare
go to page rule and click create
write this url with your domain name   <domainname>/backend/cms
and choose disable performance option and save it

**Comment by joaocosta90** [comment]
Yes, that works! Thanks for the help.

**Comment by LukeTowers** [comment]
@daftspunk we should add a KE article about this titled "Backend side-menus broken when using CloudFlare"

**Comment by nathan-van-der-werf** [comment]
I can confirm that this is caused by the Cloudflare Rocket Loader.

**Comment by daftspunk** [comment]
Although I suspect this is a problem related to double minification. According to this [CloudFlare article](https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-specific-JavaScripts-) we simply need to tell Rocket Loader to ignore some specific scripts. 

> You can have Rocket Loader ignore individual scripts by adding the data-cfasync="false" attribute to the relevant script tag, for example: 
>
> ```
>      <script data-cfasync="false" src="/javascript.js"></script>      
> ```
> Rocket Loader will still optimise the loading of all other scripts on the page.

Fixed by f068b13851150c6d12f4f2949497e21b980b7f15
Available in Build 443+

**Comment by LukeTowers** [comment]
@joaocosta90 @nathan-van-der-werf  we will use https://github.com/heathdutton/cloudflare/pull/4 & https://github.com/octobercms/october/commit/e246427463ac5edcc6b7115b33838a4367a4f9a9 to fix this issue going forward.
