### ISSUE TITLE
Improve styling on popup inspector for CMS components

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3603]
The components pop-up is not really responsive and makes reading and using the components very hard and almost impossible to read.

## Full screen example:

![1](https://user-images.githubusercontent.com/17784082/41750968-b925f236-75b6-11e8-8ab2-e2418d03dd59.png)

Everything is squeezed and impossible to read.

Not responsive has a fixed width of 400px;

## Tablet Sized screen example:

![2](https://user-images.githubusercontent.com/17784082/41751025-09d13768-75b7-11e8-81d1-9b86089b7acf.png)

Pop-Up hanging out of the screen, really suprised no one has complained on this before?

## Mobile screen example:

![3](https://user-images.githubusercontent.com/17784082/41751107-97b8bde4-75b7-11e8-8f6b-208f54ae3cd8.png)

Please can other people comfirm if this is an issue with their CMS as well. Needs fixing badly to make responsive and easy to read.

(These screenshots were done on Google Chrome V69).

Seems to be these three files:

https://github.com/octobercms/october/blob/master/modules/system/assets/ui/js/popover.js

https://github.com/octobercms/october/blob/master/modules/system/assets/ui/storm.css

https://github.com/octobercms/october/blob/master/modules/system/assets/ui/storm.less

**Comment by ayumihamsaki** [comment]
The code line is:

`<div class="control-popover control-inspector in placement-bottom" style="width: 400px; left: 675px; top: 338px;">`

I'm guessing it is injected using Javascript, as says:

```
element.style {
    width: 400px;
    left: 675px;
    top: 338px;
}
```

Then in Mobile has the following style css media:

```
@media (max-width: 480px)
body.popover-open .control-popover {
    overflow: auto;
    overflow-y: scroll;
    position: fixed;
    margin: 0;
    padding: 10px;
    width: 100% !important;
    z-index: 603;
    top: 0 !important;
    right: 0 !important;
    bottom: 0 !important;
    left: 0 !important;
}
```

That's all the styling I can see at present.

**Comment by ayumihamsaki** [comment]
Request to have the following upgrades would seem better:

### Mobile

![1](https://user-images.githubusercontent.com/17784082/41768822-41db9484-7605-11e8-9b72-1a31f393551c.png)

### Desktop

![2](https://user-images.githubusercontent.com/17784082/41768620-aa031556-7604-11e8-8603-5d058a572542.png)

~If someone could edit it would be grateful. Kind of got too much on my work plate right now and little free time...

**Comment by LukeTowers** [comment]
@ayumihamsaki I don't have any time to make the changes myself, perhaps @BenMahe would like to submit a PR to improve it?

**Comment by Teranode** [comment]
This would essentially be changing all popover content as popup based on size.

**Comment by w20k** [comment]
It's fixed by @Teranode commits, despite mobile. 

I do think it should be done this way for Mobile. It's better to have a label and input field with 100% width (like: 1 line label, 1 line input & etc). It's a part of a different issue/feature request 😉

**Comment by ayumihamsaki** [comment]
@Teranode Thanks for fixing this issue - I totally forgot all about this issue!

**Comment by ayumihamsaki** [comment]
closing as merged to master

**Comment by LukeTowers** [comment]
@ayumihamsaki it hasn't been merged to master, the release of the build is just a pending build, tagged to develop. We'll go stable next week at which point this stuff will be merged to master.

**Comment by ayumihamsaki** [comment]
@LukeTowers Sorry I didn't realize this was a Bleeding edge update and not a stable update - my bad.

**Comment by LukeTowers** [comment]
No problem :)
