### ISSUE TITLE
Delete thumbnails when the associated master image is deleted

### ISSUE THREAD

**Issue by JurekR** [octobercms/october#3605]
##### Expected behavior
If you have a image in your model as file attachment and creating thumbs of it, these related thumbs should be automatically as soon as the file attachment / image was deleted. It makes no sense then to keep them. Even worse, these thumbs will flood the temporary dir, which may result in web space overflow on heavy import scripts.

At least there should be a way to delete all thumbs in the API. But I think it would be much more consistent, if those thumbs were deleted _automatically_ (Maybe a switch to keep them on deletion). That would be very convenient and simple.

##### Actual behavior
Currently the thumbs will be left in the temporary dir, and there seems to be no way thru API to delete them.

##### Reproduce steps
Attach an image to your model, create thumbs of it, now delete the image.

##### October build
All

**Comment by LukeTowers** [comment]
Feel free to submit a PR implementing that functionality

**Comment by Samuell1** [comment]
This already exists: https://github.com/octobercms/library/blob/develop/src/Database/Attach/File.php#L476

**Comment by LukeTowers** [comment]
@Samuell1 can you test and confirm if this is still an issue? If it exists but it's not working then we'll need to fix it.

**Comment by Samuell1** [comment]
Yes, i tested it and it works, thas why it was weird for me to see this issues :D @LukeTowers
