### ISSUE TITLE
Error accessing media folders after security update 437

### ISSUE THREAD

**Issue by jlongo** [octobercms/october#3606]
##### Expected behavior
Access to media library must occur normally

##### Actual behavior
Accessing from link to media library, the route seems to add a aditional folder name for "backend" like ".../backend/backend/media"
and returns page error with template from frontend.

Accessing media folders from editor give the following error with a folder that exists at some time without issues and not modified.

October\Rain\Exception\ApplicationException: Caminho especificado inválido: '/CIS-Segurança'. in /raid0/data/naswebsite/www/gkb/modules/system/classes/MediaLibrary.php:479

##### Reproduce steps
Just access to Media Folder from backend or access media folder from editor

##### October build
After security update (437)

**Comment by jlongo** [comment]
Adding some info on error.

The error appear to be related with special chars on folder names on media folders (çãáíõ... etc)

**Comment by Teranode** [comment]
@LukeTowers confirmed this bug, and got the fix for it, got some visual bug though due to the display of it. The latin names disappears after every other ajax request done for the folder, the path name remain's in-tact but you just get the visual glitch of the latin characters disappearing

**Comment by jlongo** [comment]
@Teranode Your corrections on your pull request has solved the problem with folders. Thanks!
But however i found another problem equal to the one i reported before: in this case i have a filename on a file in media folder with a plus sign (something like on ending "...+.pdf").

How to reproduce:

Create a file with sign plus (+) anywhere on it's name.
Try to access the folder where the file exists from media manager or from media manager on editor.
The error occurs.

Regards

**Comment by Teranode** [comment]
Not really my say in if that character is allowed. The error that popped up gave very specific special characters that are allowed. If we're gonna allow more characters, then we need to come up with a full list of supported characters rather than always creating an issue for a character(s) someone wants to be supported.

**Comment by marcbrouwertue** [comment]
The fix with `preg_match('/^[\p{L}0-9a-z@\.\s_\-\/]+$/iu', $path) ` does not help for files which include a quote (') in the filename itself. In this specific case the exception on line 479 is still thrown

**Comment by Teranode** [comment]
@LukeTowers see? now we're gonna have people wanting specific special characters supported, so we need a list. Im fairly certain these errors pops up because they decide to use the button to create the file  rather than upload. So, what do we do now?

**Comment by LukeTowers** [comment]
@Teranode we need the authoritative list of either blacklisted or whitelisted characters for filenames so that we can fix the regexes in all the appropriate places at once.

**Comment by jlongo** [comment]
I'm gratefull with the work done with this CMS, i don't pretend to start a flame war where it is not needed and must be avoided. The problem arrived with security update. The problems I encountered after this update were with folder and file names inserted in the past without any problem, not allowing to change names on them (can't access the folders or files in this situation). So, the problem is with folder and file names. The list must be all chars allowed by the OS on folders and file names considering the specifics of languages that have special chars on their use. I think we do not want any special char per se, but only the allowed ones by the operating systems. Some source -> https://en.wikipedia.org/wiki/Filename . Thanks!

**Comment by LukeTowers** [comment]
@jlongo if you can come up with a list of characters that we should prevent on all major filesystems then we should be able to make something work with regex.

**Comment by jlongo** [comment]
@LukeTowers  in my previous comment there is a link where are shown the reserved chars and also the allowed ones in the most used OS.
Thanks
