### ISSUE TITLE
Plugin defined artisan commands aren't found when called from a unit test

### ISSUE THREAD

**Issue by pmhou** [octobercms/october#3609]
##### Expected behavior
Calling a plugin-defined console command from a unit test should run that command.

##### Actual behavior
```
Symfony\Component\Console\Exception\CommandNotFoundException
There are no commands defined in the "custom" namespace.
```

##### Reproduce steps
Create the custom command and register it with the plugin.

```php
// plugin.php
public function register()
{
    $this->registerConsoleCommand('custom:command', Command::class);
}
```

Check the command works correctly from the CLI
```bash
vagrant@homestead: php artisan custom:command
Custom command fired!
```

Write a simple unit test that calls the command
```php
// UnitTest.php
public function setUp()
{
    parent::setUp();

    $pluginManager = PluginManager::instance();

    $pluginManager->registerAll(true);
    $pluginManager->bootAll(true);
}

public function test()
{
    $this->artisan('custom:command');    
}
```

##### October build
437

**Comment by LukeTowers** [comment]
@pmhou are you able to do some digging into the registered commands to see what the difference between running in the testing context vs a regular context is? I don't know what would be causing this off of the top of my head and don't have time to look into it in more detail.

**Comment by pmhou** [comment]
@LukeTowers I did have a quick look through the code and traced it to around here
```php
//Illuminate/SupportServiceProvider.php:262
public function commands($commands)
{
    $commands = is_array($commands) ? $commands : func_get_args();

    Artisan::starting(function ($artisan) use ($commands) {
        $artisan->resolveCommands($commands);
    });
}
```

If I dump out $commands outside of the the Artisan::starting closure, I can see my custom command being printed. However, when I dump $commands inside the closure it never appears. Sorry I can't be more helpful, I'm not familiar with the console bootsrapping which appears to be related to the issue.

**Comment by LukeTowers** [comment]
@pmhou very odd. I don't really have time to dig into it further right now but if you find anything else let me know.

**Comment by nanodesu88** [comment]
Same problem

**Comment by nanodesu88** [comment]
Application has bootstrapped in setUp method, while PluginManager trying to register all the plugins after that

**Comment by nanodesu88** [comment]
I found a pretty shit solution. You can add a plugin copy to tests/fixtures directory like plugins/october/tester/Plugin.php and register console command inside.
What?
