### ISSUE TITLE
lastVisitedPage shows incorrect collection on filter

### ISSUE THREAD

**Issue by stevemortimer** [octobercms/october#3610]
Let's say you have a backend list controller with 100 items paginated by 20 and you navigate to the 3rd page, displaying items 41-60. If you use a filter widget while paginated but the resulting set is smaller than your current page, an empty result is returned with no way to return to page 1.

LengthAwarePaginator {
  #total: 12
  #lastPage: 1
  #items: Collection {}
  #perPage: 20
  #**currentPage: 3**
}

##### Expected behavior
Filtered items are shown. currentPage is reset to 1.

##### Actual behavior
Empty list is returned. Pagination Reads:
Displayed records: - of 12 

##### Reproduce steps
See above. 

##### October build
v1.0.437

The culprit is [https://github.com/octobercms/october/blob/master/modules/backend/widgets/Lists.php#L548](https://github.com/octobercms/october/blob/master/modules/backend/widgets/Lists.php#L548). Recently changed filter scopes are not taken into consideration here causing an issue when the filtered model count is smaller than lastVisitedPage. This was changed with #3432.

My proposed solution would be to add a second conditional beneath the tagged line. It would compare the number of records on the filtered model and confirm that it could fall within the current pagination and reset it back to 1 if it doesn't. 

```
if ($model->count() < ($currentPageNumber - 1) * $this->recordsPerPage){
   $currentPageNumber = 1;
}
```

If you agree with my approach I can submit a pull request.

**Comment by LukeTowers** [comment]
@stevemortimer I think the issue is that it's not ignoring the filter being applied from a secondary page in the results. It doesn't need to have that conditional, the correct fix would be to properly ignore session page numbers when any filtering is applied. Or, better yet, the page number stored in the session would be tied to the active search terms so that you could still retain pagination from a specific filter set. 

In addition to that, we should provide a way for the user to get back to the first page from any instance so that we can prevent future issues with data changing leaving the user stuck on a page that no longer exists.

Thoughts on the above?

**Comment by stevemortimer** [comment]
Can you think of a scenario for filtering where we wouldn't want to reset the page to 1? I agree that your idea would be a better solution. 

In Lists.php
```
/** 
 * Event handler for changing the filter 
*/
public function onFilter()
{
    $this->currentPageNumber = 1;
    return $this->onRefresh();
}
```

ListController.php:241
```
$filterWidget->bindEvent('filter.update', function () use ($widget, $filterWidget) {
    return $widget->onFilter();
});
```

**Comment by LukeTowers** [comment]
I'm thinking more so retaining the pagination when you've applied a filter, navigated some of the pages, and then leave and come back in the same session. Thoughts on providing a way for the user to always have a way to go back to the first page?

**Comment by stevemortimer** [comment]
Quick note: I'm going on vacation starting today and won't be able to check back for a week and a half to check any responses.

> I'm thinking more so retaining the pagination when you've applied a filter, navigated some of the pages, and then leave and come back in the same session. 

The filters and pages are already saved when an admin user sets them, navigates off, and returns. This should continue to work as it currently does with whatever ends up being decided here.

> Thoughts on providing a way for the user to always have a way to go back to the first page?

When it comes to UX, my approach is I prefer providing the end user with what they expected instead of telling them there was a mistake and they need to adjust something on their end. 

Relating to this issue, if a user filters to fewer records than their current page supports, the expectation in my eyes is to return to the beginning of the data set and begin browsing. The exception to this would be if somebody was using a date/time range filter and continually extending the query out to get more records. So the question is which scenario do you think is more common? 

The three approaches I see are:
1) Resetting the page counter to 1 when a filter is changed (as I presented in my previous comment.) Based on my personal use cases, there is a lot more filtering by relation than by timestamp. In those cases, page numbers would never be accurate after the filter is applied anyways so resetting to 1 is probably what the end user was expecting anyways. This avoids the issue where somebody needs to click a link to return to the first page.

2) You could always enable the << whenever a stored page number is greater than 1. That would help users avoid getting stuck if they somehow got into this situation. While useful, I consider this more of a workaround than a solution to the problem.

3) Updating the empty error message so that it is clear there are records available, just not on the current page. "There are no records in this view" is not accurate in this situation and one might be tempted to gloss over the item count/page navigation at the bottom. I don't like this because it goes against UX ideals I mentioned above where you're telling the user there is an issue and making them take action instead of just taking said action.

**Comment by LukeTowers** [comment]
@stevemortimer approach #1 sounds good to me, I was misreading your example code; didn't realize that it only runs when a filter is applied for the first time.
