### ISSUE TITLE
isDirty on CmsCompoundObject is true when no changes made

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#3611]
I'm listening to the afterSave event on CmsCompoundObjects and I want to ignore any where there is no actual change so I'm checking isDirty

##### Expected behavior
No changes then isDirty is false

##### Actual behavior
isDirty is sometimes true when it shouldn't be

##### Reproduce steps
Install demo project and create a plugin with the following boot method

``` php
    public function boot()
    {
        CmsCompoundObject::extend(function ($model) {
            $model->bindEvent('model.afterSave', function () use ($model) {
                \Log::info($model->isDirty() ? 'I am dirty' : 'I am clean');
            });
        });
    }
```

Save any page without making any changes and check the log entry.

##### October build
437

I can fix this by adding some extra checks to the `getDirty` method on the `October\Rain\Halcyon\Model` (see below) as it looks like it is treating `null` and empty string as a change, not sure if this is the desired behaviour though. If this is desired I'll submit a PR

``` php
    public function getDirty()
    {
        $dirty = [];

        foreach ($this->attributes as $key => $value) {
            if (!array_key_exists($key, $this->original)) {                
                if (!empty($value)) { // Added check to test for empty $value
                    $dirty[$key] = $value;
                }
            }
            elseif (
                $value !== $this->original[$key] &&
                empty($value) !== empty($this->original[$key]) && // Added test to see if both $value and original are empty
                !$this->originalIsNumericallyEquivalent($key)
            ) {
                $dirty[$key] = $value;
            }
        }

        return $dirty;
    }
```

**Comment by LukeTowers** [comment]
Wouldn't having an empty value present cause the attributes to be updated to that empty value? Also, this may be the core issue behind the problems people have with static pages and safe mode.

**Comment by SeriousKen** [comment]
The problem only shows when submitting from the backend. description, meta_title, and meta_description do not exist and code is NULL but the form submits them as all as empty strings which makes the model think it is dirty as a change has technically taken place (NULL to empty string). When the model is written to disk, it treats the empty string as NULL anyway and removes the value from the INI section.

My logic for testing if both are empty is wrong:

``` php
    public function getDirty()
    {
        $dirty = [];

        foreach ($this->attributes as $key => $value) {
            if (!array_key_exists($key, $this->original)) {
                if (!empty($value)) { // Added test to ignore empty $value
                    $dirty[$key] = $value;
                }
            }
            elseif (
                $value !== $this->original[$key] &&
                !(empty($value) && empty($this->original[$key])) && // Added test to ignore case when both $value and original are empty
                !$this->originalIsNumericallyEquivalent($key)
            ) {
                $dirty[$key] = $value;
            }
        }

        return $dirty;
    }
```

**Comment by LukeTowers** [comment]
@seriousken I feel like the proper fix for this would be in the FormWidget to ignore fields that don't change and not even send it to the model. If we make changes to the model class then that will have effects on lots of other pieces, not just the form usage.

**Comment by SeriousKen** [comment]
@LukeTowers when setting an attribute to an empty string, saving and then reloading the model the value is NULL, so the model effectively converts an empty string to NULL when saving. In fact, it trims the string so a string full of spaces will also be NULL when the model is reloaded. So I feel that the model should not consider itself dirty if its attributes produces no change in the final file.

**Comment by SeriousKen** [comment]
@LukeTowers this is the CmsCompoundObject which is based on the Halcyon model which saves to the filesystem, not a DBMS, so there is no VARCHAR. I still think it is the model's job to understand when it has changed rather than the form. The form's role is to supply data to the model, the model interprets that data.

**Comment by LukeTowers** [comment]
@SeriousKen ah, that's the key difference I was missing. That looks good to me, submit a PR with some tests added for the changes and I'll merge it
