### ISSUE TITLE
Composer.json not downloaded with plugin

### ISSUE THREAD

**Issue by CSNWEB** [octobercms/october#3617]
##### Expected behavior
When I install a plugin its composer.json is downloaded as well so the wikimedia merge plugin can work

##### Actual behavior
For some reason it composer.json (and lock) are missing, at least when I try to install: https://github.com/scottbedard/oc-debugbar-plugin

##### Reproduce steps
Install the debugbar plugin

##### October build
437

**Comment by LukeTowers** [comment]
This is done on purpose for all marketplace plugins. The marketplace build process pulls all composer dependencies into each plugin's /vendor directory and then removes the composer.json and composer.lock files from the plugin. This is done to support both users that don't use composer and users that do. Users that don't use composer need to have those dependencies present in the plugin's vendor directory and users that do use composer will encounter issues with dependencies being loaded twice if they use a plugin that has a composer.json file and the dependencies from that file already present in the /vendor directory of the plugin. 

So, if you want to use composer for managing plugins, then use composer to include them in your project. If you use the marketplace, then you are getting the composer-free version on purpose to prevent those conflicts.
