### ISSUE TITLE
Image file attachments in the model seem to have pretty slow SQL queries

### ISSUE THREAD

**Issue by JurekR** [octobercms/october#3618]
##### Expected behavior
Fast, optimized queries. A way maybe to actually use a field in the models table instead of the octobercms management tables.

##### Actual behavior
Since the attachments itself are then saved in some octobercms internal table, your query will be "fixed" to work then. 

##### Reproduce steps
E.g. you populate a large list of models having a image file attachment inside, the query for those attachments seem to be pretty atom level like and slow.

##### October build
all

**Comment by LukeTowers** [comment]
What exactly is this issue supposed to achieve? You have provided zero information on specifics, this reads like a vague "do better" comment. If you have a specific issue with detailed information then post that, otherwise we don't have time for vague complaints.

**Comment by JurekR** [comment]
Hi, ok will try to catch you in the chat and provide some more details.

**Comment by LukeTowers** [comment]
@JurekR feel free to also post those details here
