### ISSUE TITLE
Add config option cms.restrictBaseDir for relaxing file path restrictions

### ISSUE THREAD

**Issue by lthurston** [octobercms/october#3619]
Per a discussion with @LukeTowers and @daftspunk in Slack, I'm going to add an undocumented config option (for use in dev envs only!) that allows realpath() as alternative path validation.

https://octobercms.slack.com/team/U712K9ZQ9

I'm referencing commit fb2aa1730cc08e8563908b54b70e942bd2988f5e and its removal of realpath() as the places where this change will be made.

I should be able to work on this the first week of July.

**Comment by LukeTowers** [comment]
@lthurston on second thought you can make it documented, have it set to true by default with a strong warning against setting it to false.

**Comment by lthurston** [comment]
@LukeTowers @daftspunk Can you put some eyes on this to confirm I'm doing this correctly? If it looks good, I'll PR it.

https://github.com/lthurston/october/commit/71c165bf34725defc591d251a54dcb79f542be9d

**Comment by lthurston** [comment]
Err, this isn't quite right. I'll circle back tomorrow.

**Comment by LukeTowers** [comment]
@lthurston let me know when it's ready to review. Feel free to submit it as a WIP PR while you work on it
