### ISSUE TITLE
Adding multiple images inside rich text editor with a single drag

### ISSUE THREAD

**Issue by kojaktaha** [octobercms/october#3625]
##### Expected behavior
So the richtext editor froala comes with a nice feature, adding images from the gallery, when I multiselect images and click insert ... all the images I selected should be added to my text. 

##### Actual behavior
Only one image is added

##### Reproduce steps
add a rich text editor to your model, when you are inserting the data try to add multiple images as mentioned in the (Expected behavior).

##### October build
431

![github](https://user-images.githubusercontent.com/19997163/42204595-d5181756-7eaa-11e8-8f53-03c292fb1b1b.PNG)

**Comment by LukeTowers** [comment]
Related to #1658

**Comment by kojaktaha** [comment]
Any possible work around until the enhancement is made?

**Comment by LukeTowers** [comment]
@kojaktaha not really, you'll just have to insert them one by one

**Comment by bennothommo** [comment]
Will be included in the work done in https://github.com/octobercms/october/pull/4325.

**Comment by daftspunk** [comment]
Tested with 1.0 and 1.1, was unable to replicate this. Perhaps it has been fixed elsewhere already

1. Nav to Test Plugin > Posts > Rich Editor
2. Open MM
3. Select multiple images and clicking insert
4. Multiple images are inserted

Just ping my username if this is still an issue using the latest version
