### ISSUE TITLE
Tab behaves erratically with repeater fields when using Trigger API

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [octobercms/october#3627]
When I add a switch (the trigger-er element) and use the trigger API to show a tab with a repeater (the trigger-ed element) when the switch is ON then trigger API fails to hide the tab when the repeater has a value but shows the tab when it doesn't have any items.

##### Expected behavior
The tab should hide whether the repeater has values or not because trigger API allows you to hide/show a field based on the condition of another field--a switch (the trigger-er) in this case (and shouldn't care whether about the value of the field being hidden (the trigger-ed))

##### Actual behavior
The tab remains to appear even when the switch is off i.e. set to not show the repeater field. The difference is that the repeater is indeed hidden but the tab itself isn't. I think the reason is because of [this line](https://github.com/octobercms/october/blob/master/modules/backend/widgets/form/assets/js/october.form.js#L190) because it's checking for the length which returns 0 when the repeater has no values but a positive number otherwise. I don't really understand what the line doesn't exactly very well so I couldn't put a PR for this on my own.

##### Reproduce steps
1. Setup an OctoberCMS project and load [this plugin](https://github.com/SaifurRahmanMohsin/RepeaterBug) into it.
2. Slide the **Show Projects** switch ON and OFF, see that the Projects tab does remain.
3. Now with the which on, click the Projects tab and remove the default value Acme Project.
4. Switch the same **Show Projects** which now. A different behavior is shown.

There is another switch I added below that demonstrates the same for a text field which works perfectly. Whether you type content in the text field or not, the switch is consistent with the behavior. The trigger API isn't supposed to see the value of the trigger-ed element and should merely perform the action (show/hide/enable/empty) based on the condition of the trigger-er field so that's why this is a bug with the case of the repeater field.

##### October build
437

**Comment by LukeTowers** [comment]
@SaifurRahmanMohsin fixed in https://github.com/octobercms/october/commit/c55a7cd2e2fa59457304eecaf8d834e46fd539fe, thanks for your detailed report and reproduction plugin!

**Comment by SaifurRahmanMohsin** [comment]
Thank you for fixing this--I tested the code in the sample plugin and it appears to fix the issue. It's crazy how a single symbol changes an entire system's behavior.

**Comment by iboved** [comment]
I have the same problem. My current build number is 437. For some reason, I don't have your changes (c55a7cd2e2fa59457304eecaf8d834e46fd539fe) in my `/modules/backend/widgets/form/assets/js/october.form.js` file.
