### ISSUE TITLE
Shouldn’t form config's default value take precedence over a non-existential model’s default value?

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [octobercms/october#3631]
This is a different [from this](https://github.com/octobercms/october/issues/3627) but I used the same sample repo to demonstrate the bug so kindly just look at the latest commit to understand what's being done. But before you see it, let me tell you what's happening:

I have a form with a simple field **awesomeness** which has a default value as **Yeah!!** in its form configuration file. However, it's model also has a default value using an accessor as:
```
public function get**FieldName**Attribute($value) {
    if(is_null($value)) {
          return 'Some value';
    }
}
```

##### Expected behavior
* The field should show the config's default value **Yeah!!** in CREATE context of the form.

##### Actual behavior
* The field returns the model's accessor value **Nope!** in CREATE context of the form even thou the model doesn't even exist.

##### Reproduce steps
1. Setup an OctoberCMS project and load [this plugin](https://github.com/SaifurRahmanMohsin/RepeaterBug) into it.
2. Go to the Project tab and see the value is taken from the model's accessor over the config default value.

The primary reason I used the same Repeater bug's repository is that it affects repeater-type field more than other types. Repeaters are defined as jsonable fields in migration file and mySQL doesn't allow default values for jsonable fields in strict mode so the best alternative which I found was to set the field as a nullable one and write an accessor in it's model to do a null check and return empty array value [] if it's null. Since, my project exposes a RESTful API using this field it's supposed to return an empty array or valid array (if there's data) in the JSON response when I fetch this repeater field (it's not standard in RESTful APIs to return a null for an array field when there isn't data). But the problem is that due to this bug, even thou my API works as expected and returns an empty array instead of a NULL, the OctoberCMS form behavior breaks down as the default value is now fetched from this attribute field over the form config's default value.

### My fix ###
I dug thro the OctoberCMS code and found that [these lines](https://github.com/octobercms/october/blob/master/modules/backend/widgets/Form.php#L913-L917) are responsible for the behavior. I wrote a fix to test as:
```
if(($defaultConfigValue = $field->getConfig('default')) !== null)
    return $defaultConfigValue;
else
    return $field->getValueFromData($this->data, $defaultValue);
```
But I haven't made a PR because I suspect this might be a crude fix and might break something else. Kindly take a look and let me know if this is a bad fix or fine and whether this is a valid bug or I'm doing things differently than I should be doing.

##### October build
437

**Comment by LukeTowers** [comment]
If you define an attribute accessor then when the form asks the model for a value it receives one so it will use that instead

**Comment by SaifurRahmanMohsin** [comment]
Yes. I understood that. But is that optimal behavior? Shouldn’t the form config’s default value have the higher precedence than the accessor? Accessor is generally a “getter” which means if there is data you can manipulate it in the low level to mutate it to something else during the retrival from the database. But when in CREATE context of a form, it should ideally ignore the accessor or any default value defined in the database, correct?

**Comment by LukeTowers** [comment]
@SaifurRahmanMohsin I would agree with you, however I'm a bit wary of tying defaults only to the create context. Ideally, I would prefer that defaults are applied over any property that's null / empty, so I'm a bit unsure of tying it to the create context.

In your case specifically you can set the default value within the accessor if you'd like. Any thoughts on that?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
