### ISSUE TITLE
Failed to translate a string which containing a variable.

### ISSUE THREAD

**Issue by chaskayu** [octobercms/october#3635]
##### Expected behavior
Display:
<option>Female</option>
<option>Male</option>
<option>Not Specified</option>

##### Actual behavior
Display:
<option>mym.website::lang.user.gender.Female</option>
<option>mym.website::lang.user.gender.Male</option>
<option>mym.website::lang.user.gender.Not Specified</option>

##### Reproduce steps
Running with below codes on a page:
{% for value in gender %}
    <option>{{ 'mym.website::lang.user.gender.'~value|trans }}</option>
{% endfor %}

gender is an array defined as:
$this['gender'] = [
    'F' => 'female',
    'M' => 'male',
    '' => 'not_specified'
];

Already defined the translation in lang.php:
'user' => [
    'gender' => [
        'female' => 'Female',
        'male' => 'Male',
        'not_specified' => 'Not Specified',
    ],
],

However, it's working fine if I use {{ 'mym.website::lang.user.gender.female'|trans }} instead.

##### October build
437

**Comment by mplodowski** [comment]
Try:

```
{{ ('mym.website::lang.user.gender.' ~ value)|trans }}
```

**Comment by chaskayu** [comment]
@mplodowski It works fine after adding a brackets. Thank you so much for your prompt reply and help!

**Comment by LukeTowers** [comment]
@chaskayu is this for the frontend? Because you shouldn't be using backend translations (which is what those keys are) on the frontend, there is the separate RainLab.Translate plugin for that.
