### ISSUE TITLE
Fileupload in relationcontroller form does not respect disabled option in filterFields method

### ISSUE THREAD

**Issue by joakimbo** [octobercms/october#3639]
##### Expected behavior
Defining a fileupload in fields.yaml for a model and setting ```disabled: true``` in either the fields.yaml or in the models filterFields function makes the widget activate previewMode when used in a relationcontroller form.

##### Actual behavior
Fileupload widget only sets previewMode to true if ```disabled: true``` is set in fields.yaml, setting disabled to true in filterFields does not propagate down to fileupload widget if managed through relationcontroller.

##### Reproduce steps
1. Create a model which manages a relation through a relationcontroller
2. The related model defines a fileupload widget in its fields.yaml
3. Using filterFields function of related model to set the fileupload field to disabled = true has no effect on widget when managed through the relationcontroller form.
4. Setting the fileupload ```disabled: true``` in fields.yaml propagates to the relationcontroller manage form and no upload can be done

##### October build
437

Edit: Did some further quick testing of a fileupload directly in a model (not in a relationcontroller form) and the behavior of setting the disabled value in filterFields does not seem to be supported there either.

Edit 2: One way to achieve this is to listen to the ```backend.form.extendFieldsBefore``` event in the Plugins boot function, I'm unsure if my original approach "should" be supported.

**Comment by joakimbo** [comment]
Related https://github.com/octobercms/october/issues/3444

**Comment by LukeTowers** [comment]
@joakimbo does filterFields give you access to the FileUpload formwidget to be able to set previewMode manually?

**Comment by joakimbo** [comment]
@LukeTowers The ```$fields``` param only contains objects of Backend\Classes\FormField which doesn't seem to have any reference to possible widgets.

**Comment by joakimbo** [comment]
@LukeTowers Could we simply re-run the widgets init func after the filterFields?
https://github.com/octobercms/october/blob/fb2aa1730cc08e8563908b54b70e942bd2988f5e/modules/backend/widgets/Form.php#L1026
i.e
```
/*
 * Allow the model to filter fields.
 */
protected function applyFiltersFromModel()
{
    /*
     * Standard usage
     */
    if (method_exists($this->model, 'filterFields')) {
        $this->model->filterFields((object) $this->allFields, $this->getContext());
        foreach ($this->formWidgets as $widget) {
            $widget->init();
        }
    }
    /*
     * Advanced usage
     */
    if (method_exists($this->model, 'fireEvent')) {
        $this->model->fireEvent('model.form.filterFields', [$this]);
    }
}
```

**Comment by LukeTowers** [comment]
@joakimbo what do you think about adding some information to the documentation that mentions that if you want to affect formwidgets that set internal state (i.e. previewMode based on field disabled value) then you should do that within the `backend.form.extendFieldsBefore` event and provide an example of doing so?

**Comment by joakimbo** [comment]
Sure, does the code altering the formwidgets from field config stay?

**Comment by LukeTowers** [comment]
@joakimbo the reason that you can modify the formwidgets in the config state (and in `backend.form.extendFieldsBefore`) is because you are actually just modifying their pre-boot configuration. After they have been booted (or had `init()` called on them) they no longer look at those configuration values. Does that make more sense as to why you can affect them in those places but not `filterFields()`?

**Comment by joakimbo** [comment]
@LukeTowers I understand that and it's not that it isn't making sense.
The problem I have is that out of 4 ways (that I know of) of how the form fields can be defined/changed any widget that "resides" in these fields only bothers to act on 3 of these (all before init). Why be able to change values of a field with a widget (that the widget would respond to in config) if the widget wont change?

**Comment by LukeTowers** [comment]
@joakimbo To be more clear, I'm not opposed to the code being changed so that filterFields works properly for FormWidgets, I was just providing alternatives. 

What do you propose for a fix?

**Comment by joakimbo** [comment]
@LukeTowers Thank you for clearing that up, unfortunately as of now I don't have any other solution than #3645. I would need to take another look at it, perhaps later this week.
