### ISSUE TITLE
Invalid security token on opening two admin panels of two entirely different projects

### ISSUE THREAD

**Issue by amjadniazi48** [octobercms/october#3640]
##### Expected behavior
(Describe expected behavior here)
October should work with two admin panels at the same  time with entirely diffrent projects with different databases
##### Actual behavior
(Describe actual behavior here)
i m running two october projects, on opening two admin panels at the same time, it will restirct me to use one admin panel at one time and give me invalid security token  issue on using another one.
##### Reproduce steps
(Describe the steps to reproduce the problem here)
just intall two projects of october cms and with two diffrent databases and open admin panel for both but october restrict you to use one admin panel at  one time.
##### October build
(October build number)
437

**Comment by munxar** [comment]
how do the urls look for this two local projects?

**Comment by amjadniazi48** [comment]
i m using wamp server for windows.
following are the urls
http://localhost/amazfit/backend/
and 
http://localhost/nankari11/backend

**Comment by munxar** [comment]
And here is the Problem: You use folders, so both apps are served from
domain 'localhost'.
I'd suggest using something like laragon to get one hostname per october
instance.

Amjad Iqbal Khan <notifications@github.com> schrieb am Mo., 16. Juli 2018,
07:59:

**Comment by munxar** [comment]
Here's the link: https://laragon.org



Sascha Aeppli <sascha.aeppli@liip.ch> schrieb am Mo., 16. Juli 2018, 08:33:

**Comment by amjadniazi48** [comment]
Thanks a lot, i will use it.

**Comment by amjadniazi48** [comment]
Basically making a virtual host is essential to handle this problem, it can be run on wamp as well but virtual host is required to run both instances of two separate projects of octobercms.

**Comment by munxar** [comment]
@amjadniazi48 that's right and laragon does that for you automatically via some scripts.
including some really helpful tools for webdevelopment (nodejs, cmder, etc.).

btw. pls close this issue and join out friendly slack community for this kind of questions:
https://octobercms.slack.com/

**Comment by amjadniazi48** [comment]
ok thanks
