### ISSUE TITLE
Add more Asset File Extensions to October Backend

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3646]
Hi,

Currently Octobercms has the following assets extensions built into it:

- Js
- Css
- Rss

Where you can add assets like this:

```
$this->addCss("/plugins/yourname/plugname/assets/css/custom.css");
$this->addJs("/plugins/yourname/plugname/assets/js/custom.js");
```

Almost all Google Developers are quoting **JavaScript modules** these days, files with the following extension: `.mjs`

I was thinking of suggesting that OctoberCMS add some more file extensions to the backend to keep up with current trends.

I suggest the following to be added if possible:

- Js
- Mjs
- Css
- Rss
- Atom
- Json

p.s. I'm not clever enough to create a PR for this, this issue is an enhancement suggestion only.

**Comment by LukeTowers** [comment]
@ayumihamsaki what would "adding" MJS, Atom, & JSON assets even do? I.e. What would calling `addMjs()`, `addAtom()`, and `addJson` do?

**Comment by ayumihamsaki** [comment]
@LukeTowers adding `addAtom()`, and `addJson()` would allow developers to add **_dynamic sources_** into their plugin(s) - same reason why you already have `addRss()` most likely. Look at AMP-HTML for example they use Mustache Templating system and JSON to create Dynamic things! Some of my plugins I create in October are Dynamic and use JSON etc. As for suggesting `addAtom()` October uses `addRss()` already but Atom is more widespread so it would make sense to have both and not one or the other.

As for `addMjs()` its the direction Javascript is heading and using [Javascript modules](https://developers.google.com/web/fundamentals/primers/modules) makes programming easier and better so October should be fully functional with modern developing techniques and not left behind and become stale. Over time most my Javascript will be using `.mjs` files.

Hopefully that answers your question and my reasons behind the suggestion.

**Comment by ayumihamsaki** [comment]
Here's an example of a dynamic plugin using JSON:

![dyn](https://user-images.githubusercontent.com/17784082/43012533-49b25932-8c3e-11e8-9873-30f4377ec28e.png)

End of the day it's just some space, you can add whatever you like in that space and create fully functional apps...

**Comment by LukeTowers** [comment]
@ayumihamsaki not really, my question is moreso what would those methods functionally do? There's nothing stopping you right now from doing `->addJs('/path/to/mjsfile.mjs')` and having it included in the scripts tag, and I'm not sure what the point of `addAtom` and `addJson` are, where is that stuff getting output?

**Comment by ayumihamsaki** [comment]
@LukeTowers Sorry I see your point.

> There's nothing stopping you right now from doing ->addJs('/path/to/mjsfile.mjs') and having it included in the scripts tag

I thought that would not work as with Javascript modules you have to set a `type="module"` for the browser to understand it is a module JS file and not a normal one. That's why I thought you may need a new `addMjs()`. Plus also add a `nomodule` attribute to the normal `addJs()`.

> I'm not sure what the point of addAtom and addJson are, where is that stuff getting output?

I'm not totally sure to be honest, as I don't fully understand how the `addRss()` is intergrated into October, but as it uses RSS, it should also be able to accept Atom feeds as well.

Lastly the `addJson()` I use JSON to pull in third party data API's and Templating data into some of my plugins, I guess maybe I am suggesting if it was a fixed settings, October could have some built in CORS and other features to help the build process. It would be nice to have more functionality to add JSON data directly into October's backend files.

I just suggested the most common file formats, but my main idea was adding the Modular Javascript extension to October as its a big feature upgrade to JS and makes things a lot better.

**Comment by LukeTowers** [comment]
@ayumihamsaki I've never used MJS so I'm definitely not the person to push through an enhancement to provide specific support for it within October. However, feel free to submit a PR to add any desired functionality yourself. 

With regards to RSS, I don't actually know what October does with it either tbh, perhaps @daftspunk knows why that method exists. 

With regards to JSON what you're asking for isn't really within the realm of the asset manager and is a bit too much "magic" to be something that the core of October supports, although plugins are always free to implement any functionality that they want.

**Comment by ayumihamsaki** [comment]
@LukeTowers ok, understand. Thanks for taking the time to explain things.

**Comment by LukeTowers** [comment]
@ayumihamsaki no problem, any time!
