### ISSUE TITLE
this.page variable causing an exception

### ISSUE THREAD

**Issue by HugoWijdeveld** [octobercms/october#3659]
##### Expected behavior
In the header of a layout, I have the lines:

    <title>MyName | {{ this.page.title }}</title>
    <meta name="description" content="{{ this.page.meta_description }}">

I expect that to parse as 

    <title>MyName | MyTitle</title>
    <meta name="description" content="">
since there is no meta_description.

##### Actual behavior
The system throws an exception:
> An exception has been thrown during the rendering of a template ("Call to undefined method October\Rain\Halcyon\Builder::meta_description()")

The parsing of "this.page.title" is acting like I expected.
These two behaviours are the same for all pages that use this layout.

##### Reproduce steps
I created a theme with pages within a system I installed using composer. The build of this is 437. I created the (cms) pages from the backend. I filled in the 'title' field, but not the 'meta_title', nor the 'meta_description'. This caused NO problem in viewing the files from the frontend.
Then I copied the theme (complete folder with all the files and subfolders) to a system (on the same machine) that was installed using Wizard installation. That's where the problem shows.

When I try to make a new cms page in the new environment, using the layout with the reference to 'meta_description', I get the same problem. It may not have any relation to copying the files after all.

##### October build
437

##### Note
The problem is solved when I explicitly instantiate the variables. In other words I have to write

    meta_title = ""
    meta_description = ""
in the configuration section of the page. I am still wondering why I didn't have to do that when I was developing the theme?

**Comment by LukeTowers** [comment]
Is there a difference in cms.enableTwigStrictVariables` (https://github.com/octobercms/october/blob/master/config/cms.php#L363) between the two instances?

**Comment by HugoWijdeveld** [comment]
Hi Luke, thanks for lighting the torch for me. It was indeed the combination of cms.enableTwigStrictVariables and the env.APP_DEBUG that I had overlooked. So I can confirm it was my mistake and October is behaving as expected after all. I've closed the subject. Thanks again for helping me out.
