### ISSUE TITLE
I Cannot Render an iframe Tag Under a Sidebar Partial for the MDB-Loaded Theme

### ISSUE THREAD

**Issue by JohnB7590** [octobercms/october#3661]
##### Expected behavior
In essence, I was trying to script an iframe tag - hoping that I could hardcode that to the partial, which would be added onto the sidebar partial/template.

##### Actual behavior
However, the iframe failed to work - and there was no embedded video to see or view. I also made sure that the embed directory was used in the url as well (i.e. https://www.youtubeexample.com/embed/asdsdsdsd).

Now, my question is on the matter of whether partials refuse to render iframes within the context of October CMS. And if this is the case, how would I overcome such an issue of mine. Or to state this differently, all I want to know is what would be the nature of the problem or issue at hand.

(* Also, iframes work when coming to the usage of them in posts under the blog plugin folder.)

##### Reproduce steps
To reproduce the steps that I made, create a partial in the partials category located in CMS. Then, hardcode the iframe - contained within all of the other tags - that would be used within the text editor file located in the TEXT EDITOR NOT THE CMS TEXT EDITOR. I just wanted to clarify that. And, run to see if it works.

To reiterate, I'm using the mdb-loaded theme, which problem-solving this will only be useful by installing that said theme. 

##### October build
(1.5.6. - but, that is probably the number for the News and Newsletter Plugin - I got little confused to where that might be located in the proper spot)

If you ask me, I know that I'll have to go to system/admin/updates; however, there is no clear definition where this build number is exactly at.

**Comment by LukeTowers** [comment]
@JohnB7590 Github issues really isn't the place for questions like this as it appears to be an issue with a third party theme. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
