### ISSUE TITLE
How to find information about the current user in October CMS?

### ISSUE THREAD

**Issue by koliane** [octobercms/october#3662]
An authorized user on a particular page presses a button, thereby sending an ajax request that is processed in the plugin in the routes.php file. There I have to get the user data via the `Auth::getUser ();` command, but it issues `NULL`, although the current user is authorized.
How can I get information about the user in my case?

##### Expected behavior
I need to get information about the authorized user.

##### Actual behavior
The `Auth::getUser()` command outputs null

##### October build
437

**Comment by LukeTowers** [comment]
@koliane attach the `web` middleware to the route handling the request, Laravel stopped starting the session middleware automatically on all request routes in 5.5 so now any custom routes that want to use session data (i.e. the auth implementation) needs to attach the `web` middleware.
