### ISSUE TITLE
[Question]Add custom widget to form builder list

### ISSUE THREAD

**Issue by neuberoliveira** [octobercms/october#3666]
I create a widget to use with my models forms, its working as expected, but e can edit, or even add it, from the form builder, need to edit the fields.yaml file. And display the error above in the form builder.
![captura de tela 2018-08-01 as 17 14 35](https://user-images.githubusercontent.com/3378304/43547003-637394a0-95b0-11e8-9722-93893f87dcd1.png)

Is this the expected behavihor? I would like it to appear in the controls list of builder plugin, togheter with the default ones.
![captura de tela 2018-08-01 as 17 18 02](https://user-images.githubusercontent.com/3378304/43546882-18e1b070-95b0-11e8-9549-553d6958bb16.png)

Is possible to do this??

**Comment by LukeTowers** [comment]
You can listen to the `pages.builder.registerControls` event here: https://github.com/rainlab/builder-plugin/blob/master/Plugin.php#L122-L124. Use https://github.com/rainlab/builder-plugin/blob/master/classes/StandardControlsRegistry.php as a reference as how to register your own controls.

**Comment by LukeTowers** [comment]
@neuberoliveira you shouldn't need `new StandardControlsRegistry($controlLibrary); ` at all, that class is just a helper for better organizing the registration of all the default built in controls. If removing that doesn't work then you should investigate if changing the priority of your event handler to attempt to run it either before or after the plugin's built in handler improves the situation.

**Comment by neuberoliveira** [comment]
@LukeTowers remove `new StandardControlsRegistry` do nothing, but i finally made it to work, its a bit tricky but works.

The issue was on the last parameter of [ControlLibrary:: registerControl()](https://github.com/rainlab/builder-plugin/blob/master/classes/ControlLibrary.php#L91-L93) in the exemple you gave me its aways `null` so i keep it that way.

When `$designTimeProviderClass` is  `null` it uses the default implementation, as you can see [here](https://github.com/rainlab/builder-plugin/blob/master/widgets/DefaultControlDesignTimeProvider.php#L15-L37) it have a list of default control types, and of course mine is not on the list, and a bit above in the [renderControlBody](https://github.com/rainlab/builder-plugin/blob/master/widgets/DefaultControlDesignTimeProvider.php#L49-L51) theres the condition that render the `Unknown control type` message.

To fix this i extended the `DefaultControlDesignTimeProvider` and append my custom type on it, need to create a view that renders it, in fact i copy the default dropdown view.

In case someone else was look for this i [created this repo](https://github.com/neuberoliveira/widgets) with the plugin exemple.

**Comment by LukeTowers** [comment]
@neuberoliveira would you be willing to do up a section for the plugin docs explaining how to register custom controls with the builder plugin?

**Comment by neuberoliveira** [comment]
@LukeTowers sure, just point me the right place int the docs to add this.

**Comment by LukeTowers** [comment]
https://github.com/rainlab/builder-plugin/issues/303#issue-506914480 for future reference
