### ISSUE TITLE
NestTree doesn't work on some data (A node cannot be moved to a descendant of itself)

### ISSUE THREAD

**Issue by kojaktaha** [octobercms/october#3667]
##### Expected behavior
Creating or moving a  record in the tree should be possible.

##### Actual behavior
When creating or editing a record I get (A node cannot be moved to a descendant of itself.), I have created the model with all the required fields (nest_left "nullable", nest_right "nullable", nest_depth "nullable", parent_id "nullable") and I made a relationship field that using the (parent_id) column to connect each record to it's parent, the problem that the tree works perfectly with some records and not the others!!

Specifics:- 
![nested](https://user-images.githubusercontent.com/19997163/43662633-449989b6-976f-11e8-8460-87dd81ae16db.PNG)

I have noticed that many records have the same nest_left, nest_right values, and these are the columns that are creating the problem, I can't attach a child to these records.

So I tried to delete the hole data set and started from the beginning, I had the same freaky numbers doing the same freaky shit

![newnested](https://user-images.githubusercontent.com/19997163/43663215-48f97fc8-9771-11e8-84c3-9d0f81767a95.PNG)
 

##### Reproduce steps
create a model with nested relationship, insert data up to three level deep in random order of insertion

##### October build
437

**Comment by LukeTowers** [comment]
This is a complex case. 

In order to aid in our understanding of the problem, please submit [a Pull Request to the test plugin](https://github.com/octoberrain/oc-test-plugin) for investigation that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it _using the test plugin_.

**Comment by kojaktaha** [comment]
I am a real newbie developer, I don't know what to do with the test plugin! any guidelines or a place to start on how it works, what it should do? how can I be useful using it?

**Comment by LukeTowers** [comment]
@kojaktaha basically download the test plugin, make changes in it until you can replicate the issue that you are having, and then submit those changes in the form of a PR to the original repository. There's lots of online guides for how to submit PRs, I don't have any links to anything that describes how to do this in more detail unfortunately.

**Comment by LukeTowers** [comment]
FYI, if you need to implement NestedTree on an existing data set, try using the following code in a seeder to generate the correct index data on the table after running a migration to add the appropriate columns:

```php
<?php namespace MyAuthor\MyPlugin\Updates;

use October\Rain\Database\Updates\Seeder;

class SeedExistingData extends Seeder
{
    public function run()
    {
        // Define the model to operate on
        $modelClass = \MyAuthor\MyPlugin\Models\MyModel::class;

        // Set the attributes used by the NestedTree trait to be ignored
        $ignoreAttributes = ['parent_id', 'nest_left', 'nest_right', 'nest_depth'];

        // Get all existing data in a plain format
        $records = $modelClass::query()->getQuery()->get();

        // Remove all existing data from the db table
        $modelClass::truncate();

        // Loop over existing data and recreate it one by one so that the NestedTree
        // trait can properly generate the internal index attributes
        foreach ($records as $record) {
            $data = (array) $record;
            $modelInstance = new $modelClass();
            foreach (array_keys($data) as $attribute) {
                if (in_array($attribute, $ignoreAttributes)) {
                    continue;
                }
                $modelInstance->{$attribute} = $data[$attribute];
            }
            $modelInstance->save();
        }
    }
}
```

**Comment by sahilofficial671** [comment]
> FYI, if you need to implement NestedTree on an existing data set, try using the following code in a seeder to generate the correct index data on the table after running a migration to add the appropriate columns:
> 
> ```
> <?php namespace MyAuthor\MyPlugin\Updates;
> 
> use October\Rain\Database\Updates\Seeder;
> 
> class SeedExistingData extends Seeder
> {
>     public function run()
>     {
>         // Define the model to operate on
>         $modelClass = \MyAuthor\MyPlugin\Models\MyModel::class;
> 
>         // Set the attributes used by the NestedTree trait to be ignored
>         $ignoreAttributes = ['parent_id', 'nest_left', 'nest_right', 'nest_depth'];
> 
>         // Get all existing data in a plain format
>         $records = $modelClass::query()->getQuery()->get();
> 
>         // Remove all existing data from the db table
>         $modelClass::truncate();
> 
>         // Loop over existing data and recreate it one by one so that the NestedTree
>         // trait can properly generate the internal index attributes
>         foreach ($records as $record) {
>             $data = (array) $record;
>             $modelInstance = new $modelClass();
>             foreach (array_keys($data) as $attribute) {
>                 if (in_array($attribute, $ignoreAttributes)) {
>                     continue;
>                 }
>                 $modelInstance->{$attribute} = $data[$attribute];
>             }
>             $modelInstance->save();
>         }
>     }
> }
> ```

Thanks for this. It helped.

**Comment by daftspunk** [comment]
For anyone that comes across this, use the `resetTreeNesting` method to reset the nested tree values.

```php
(new ModelClass)->resetTreeNesting();
```
