### ISSUE TITLE
Adding attach/detach events for models

### ISSUE THREAD

**Issue by kharanenka** [octobercms/october#3675]
##### Expected behavior
We have model [events](https://octobercms.com/docs/database/model#events).
It will be useful to add events for [Many To Many](https://octobercms.com/docs/database/relations#inserting-many-to-many-relations) relations (attach/detach methods).
This is useful if we need to clear cache or add logic after creating/removing relation.
I tried to create pivot models and use [events](https://octobercms.com/docs/database/model#events) (afterSave, afterDelete) in them, but they do not work in pivot models.

For example:
```php
$obUser->group()->attach($iGroupID);

User::extend(function($obUser) {
    $obUser->bindEvent('relation.afterAttach', function($sRelationName, $iNewGroupID, $arPivotData = []) {
        //$sRelationName == 'group'
        //$iNewGroupID == $iGroupID
    });
});
```
or
```php
$obUser->group()->attach($iGroupID);

Event::listen('relation.afterAttach', function($sRelationName, $obMainModel, $iAttachedElementID, $arPivotData = []) {
        //$sRelationName == 'group'
        //$obMainModel == $obUser
        //$iAttachedElementID == $iGroupID
})
```

**Comment by osmanzeki** [comment]
As an FYI and/or reference, this package and plugin does this:

https://github.com/damianlewis/october-laravel-pivot
https://github.com/damianlewis/oc-sortable-relations-plugin

**Comment by LukeTowers** [comment]
Pull requests welcome ;)

**Comment by kharanenka** [comment]
How did you install these packages in your project? These packages are not published on packagist.org.

**Comment by LukeTowers** [comment]
@kharanenka google composer using github repos as packages.

**Comment by kharanenka** [comment]
Do you understand reasons I created this task? I do not need these functions in project. I am a developer of [Shopaholic](https://octobercms.com/plugins/search?search=shopaholic) plugins and we need to have these functions in OсtoberCMS for development of our plugins. If solution with addition of package is not right for you, why did not you say this first?
Why do we need to figure this out after creating an PR?

If you do not have time to add new features to OctoberCMS, and you are waiting for PR from developers, why do not we discuss the implementation in advance? So that later there would be no problems with her merge?

**Comment by LukeTowers** [comment]
@kharanenka my apologies for the confusion, I thought that you were asking how to include it at the project level. Do you have any questions about how I want to see it implemented in the library?

**Comment by kharanenka** [comment]
Yes, give us recommendations on this task so that we can do issue and you could immediately accept it.

**Comment by LukeTowers** [comment]
What are the events that you need added and where do they need to be fired and with what arguments?

**Comment by LukeTowers** [comment]
@kharanenka please write out all of the events with their names and their parameters

**Comment by kharanenka** [comment]
I create PR in octobercms/library repo ([link](https://github.com/octobercms/library/pull/339))

**Comment by daftspunk** [comment]
Fixed by https://github.com/octobercms/library/pull/339

Thanks
