### ISSUE TITLE
Remove scope of methods and properties from their definition in the API docs

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#3677]
The [API documentation](https://octobercms.com/docs/api/backend/classes/formfield) currently outlines public & protected methods and properties with a header describing the section and then placing the scope in front of the method / property name. This is redundant, if I am looking in the "Public properties" section I know all of the properties listed there are public, same for protected and private.

##### Public Properties
public array **$data**
public string **$type**
public bool **$cluttered**

##### Public Properties
array **$data**
string **$type**
bool **$cluttered**

While on this topic, it would also be ideal if the properties and method definitions were presented as alternating colours table rows to make the visual distinction between a definition and its details separate from the previous and next definitions.

**Comment by daftspunk** [comment]
Leaving this note here, since it is related. We also need a way to document local events as there are some conflicts currently; Halycon + Eloquent events have the same name.
