### ISSUE TITLE
Website: Wrong statistics on the second page of the author's page

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#3678]
First page:
![first](https://user-images.githubusercontent.com/2959112/43884022-49bf974c-9bb5-11e8-8821-2033f6dbd3ab.JPG)

Second page:
![second](https://user-images.githubusercontent.com/2959112/43884032-536665dc-9bb5-11e8-9f96-01e9d0b2be6e.JPG)

**Comment by lautsevich** [comment]
The same problem in LOVATA's profile. Most likely, the number of plugins isn't taken from the DB, but from an object with a list of plugins coming to the page template.

**Comment by LukeTowers** [comment]
This was fixed silently at some point between now and December 2018 by no longer having pagination in that list.
