### ISSUE TITLE
Not compatible with latest Laravel change (5.5.42)

### ISSUE THREAD

**Issue by acasar** [octobercms/october#3680]
It seems that Laravel changed serialization logic a bit in Laravel 5.5.42

https://github.com/laravel/framework/commits/5.5

Since then I can't login into the backend. I get the following error:

```
openssl_encrypt() expects parameter 1 to be string, array given
\vendor\laravel\framework\src\Illuminate\Encryption\Encrypter.php line 91
```

![image](https://user-images.githubusercontent.com/6329543/43891278-319ddac0-9bc9-11e8-853d-d79f40152968.png)

cc @daftspunk @LukeTowers

**Comment by acasar** [comment]
Just a side note, in Laravel 5.5.41 everything works normally.

**Comment by LukeTowers** [comment]
Closing in favour of #3681 because of more activity over there, thanks @acasar! No thanks @taylorotwell 😝
