### ISSUE TITLE
Error after "composer update" or "composer install" [fixed]

### ISSUE THREAD

**Issue by Toxigen** [octobercms/october#3681]
##### Expected behavior
Authorization in backend without errors

##### Actual behavior
There is an error logging in to the backend, but if I again go to the url / backend /, then I will be already authorized
![image](https://user-images.githubusercontent.com/20593987/43890821-d9b9f1e4-9bd8-11e8-9cce-0d3d50de9e6c.png)

##### Reproduce steps
Install October CMS through git and run "composer update" or "composer install".
Or update your vendor files from current project  through  "composer update"

##### October build
October build number - 437

**Comment by Samorai** [comment]
Hi!
Have the same problem.

**Comment by jexme** [comment]
duplicate https://github.com/octobercms/october/issues/3680

**Comment by jexme** [comment]
when rolling back to version 5.5.41 another error
![image](https://user-images.githubusercontent.com/22722008/43892728-d1733f22-9bdd-11e8-9917-0323ea42d69e.png)

**Comment by acasar** [comment]
@jexme when rolling back, just clear cache and cookies. Works fine then.

**Comment by LukeTowers** [comment]
Relevant: https://laravel.com/docs/5.5/upgrade#upgrade-5.6.30 and https://github.com/laravel/framework/compare/a2c54e6e69035111fa2709f9cdac55be811feb6b...c5dc9c870a8a1af6c7e827dd81bd15f0a1561cc4

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/library/commit/c8e2740d974a4409f9990d64f19ef493acf7c0e6, apply manually until change is merged to master and a new build is created. If you have issues with the fix, make sure you clear the cache with `php artisan cache:clear` and delete all your cookies.

**Comment by LukeTowers** [comment]
@shoguniphicus it should only be an issue that requires clearing the cookies under a very narrow set of conditions:

You used composer to update Laravel 5.5.42 in the two days between it's release and the fix being released on October's end. There's not much we can do to help the developer in the case; unless you have a different fix in mind?

**Comment by LukeTowers** [comment]
@shoguniphicus it has been fixed, @daftspunk just needs to push a new build. It's marked complete because https://github.com/octobercms/library/commit/c8e2740d974a4409f9990d64f19ef493acf7c0e6 fixed it.

I'll ping @daftspunk to push a new build so people stop encountering this.

**Comment by HassanIbrahim** [comment]
I applied the fix, now the error is `return $unserialize ? unserialize($decrypted) : $decrypted;`
`/Users/home/Code/klue/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php line 149`

**Comment by LukeTowers** [comment]
@HassanIbrahim did you clear your cookies?

**Comment by HassanIbrahim** [comment]
@LukeTowers yes but solved by upgrading to release v1.0.440

**Comment by WebMago** [comment]
I had this issue on **October CMS 4.6.5 with PHP 7.1**, I solve it using this code found in the URL:

 [https://coderoad.ru/51825844/OctoberCMS-openssl_encrypt-%D0%BE%D0%B6%D0%B8%D0%B4%D0%B0%D0%B5%D1%82-%D1%87%D1%82%D0%BE-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80-1-%D0%B1%D1%83%D0%B4%D0%B5%D1%82-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%BE%D0%B9-%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD](https://coderoad.ru/51825844/OctoberCMS-openssl_encrypt-%D0%BE%D0%B6%D0%B8%D0%B4%D0%B0%D0%B5%D1%82-%D1%87%D1%82%D0%BE-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80-1-%D0%B1%D1%83%D0%B4%D0%B5%D1%82-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%BE%D0%B9-%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD)

path file: `vendor/october/rain/src/Cookie/Middleware/EncryptCookies.php`

```php
class EncryptCookies extends \Illuminate\Cookie\Middleware\EncryptCookies
{
    /**
     * Indicates if cookies should be serialized.
     *
     * @var bool
     */
    protected static $serialize = true;

    public function __construct(EncrypterContract $encrypter)
    {
        parent::__construct($encrypter);
        $except = Config::get('cookie.unencryptedCookies', []);
        $this->disableFor($except);
    }
```

**Comment by LukeTowers** [comment]
@WebMago do not do that. That file will be overwritten the next time you update and by doing that you are leaving yourself vulnerable to the attack that the change was meant to prevent. 

You should not have any issues with Build 465 after clearing your cookies, and if you are try enabling edge updates and updating to Build 467 instead.

**Comment by WebMago** [comment]
> @WebMago do not do that. That file will be overwritten the next time you update and by doing that you are leaving yourself vulnerable to the attack that the change was meant to prevent.
> 
> You should not have any issues with Build 465 after clearing your cookies, and if you are try enabling edge updates and updating to Build 467 instead.

Here the user mention has been cleared the cookies, never confirm this be the solution, 'cause the solution was an upgrade.
https://github.com/octobercms/october/issues/3681#issuecomment-413858563

So I need to clear the cookies of all my "users" this be insane.

Let me try wit 467

**Comment by LukeTowers** [comment]
There should no longer be that requirement, the code is supposed to support both versions and upgrade the old cookies.
