### ISSUE TITLE
openssl_encrypt() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by minhluccode** [octobercms/october#3684]
/Users/leluc/Desktop/www/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php line 91

**Comment by minhluccode** [comment]
<img width="1214" alt="screen shot 2018-08-09 at 10 52 18 am" src="https://user-images.githubusercontent.com/29726422/43962892-0afd90c0-9ce3-11e8-999d-c6fd68ab34af.png">

**Comment by iagoneresb** [comment]
You can find the solution in https://github.com/octobercms/october/issues/3681#issuecomment-411788524 .

**Comment by minhluccode** [comment]
@iagoneresb thank you very much
