### ISSUE TITLE
Question: Is it possible to add css classes to relation manager lists?

### ISSUE THREAD

**Issue by WaskiWabit** [octobercms/october#3685]
##### Expected behavior
I understand how listInjectRowClass() works given that your model has a controller. My model does not have a controller because it is related to another model instead. Is it possible to add listInjectRowClass() without extending the Relation Controller?

I have a WorkOrder model and a WorkOrders controller. The WorkOrders model has a LineItems model related to it. I can't seem to edit relational lists but can edit the top level list just fine. Any help would be greatly appreciated.

##### October build
System Build: 437

Thanks in advance.

**Comment by LukeTowers** [comment]
@WaskiWabit what have you tried so far?

**Comment by WaskiWabit** [comment]
I tried to extend the behavior "Relation Controller" to no avail. The paths to the behaviors seem to be hard coded.

**Comment by LukeTowers** [comment]
@WaskiWabit all `listExtendRowClass` does is provide a shortcut to hooking into the `list.injectRowClass` event on the List widget: https://github.com/octobercms/october/blob/7e6800ea6e00637619a0d10eef3eaa82d5c4b255/modules/backend/behaviors/ListController.php#L182-L184

All you have to do is extend the RelationController's view widget (which in this case is a list widget) to hook directly into the event required by using http://octobercms.com/docs/backend/relations#extend-view-widget in your main controller:
```php
public function relationExtendViewWidget($widget, $field, $model)
{
    // Make sure the model, field, & widget matches those you want to manipulate
    if (!$model instanceof MyModel || $field != 'myField' || !($widget instanceof \Backend\Widgets\Lists)) {
        return;
    }
    $widget->bindEvent('list.extendRowClass', function ($record, $definition) {
        return 'modified-class';
     });
}
```

Whenever you're stuck on something in October, I highly recommend that you just try reading the source code, it's pretty clean and well organized overall; you'll find that you learn a lot about how it works and how to achieve what you need to achieve.

**Comment by WaskiWabit** [comment]
I will give this a shot. Thanks Luke!

**Comment by LukeTowers** [comment]
No problem @WaskiWabit! 

===
Was this helpful? Did it save you time? Then consider becoming a [Patreon supporter](https://www.patreon.com/LukeTowers) so I can keep providing excellent support! Or, add your thoughts to https://github.com/octobercms/october/issues/3683

**Comment by WaskiWabit** [comment]
Hmm, this does nothing. Doesn't throw an error and does not give expected results. I am trying to strikethrough rows that have a status = 0 on the relation "recommendations".  Any help would be greatly appreciated.

**Comment by LukeTowers** [comment]
@WaskiWabit post your code. Controller class and relation_config

**Comment by WaskiWabit** [comment]
It looks like "list.injectRowClass" works for me. Thanks again!

```javascript
public function relationExtendViewWidget($widget, $field, $model) {
        if (!$model instanceof WorkOrder || $field != 'recommendations' || !($widget instanceof \Backend\Widgets\Lists)) {
            return;
        }

        $widget->bindEvent('list.injectRowClass', function ($record) {
            return 'strike';
        });
    }
```

**Comment by WaskiWabit** [comment]
Strange... now I am getting this error when trying to create a "recommendation"

![capture](https://user-images.githubusercontent.com/10679529/43995558-2d30954c-9d75-11e8-97b8-abee929515e6.PNG)

**Comment by WaskiWabit** [comment]
Nevermind. Apparently my vendor directory became corrupt. All is well now.

**Comment by LukeTowers** [comment]
Good to hear!
