### ISSUE TITLE
Relationships: Touching parent timestamps

### ISSUE THREAD

**Issue by WaskiWabit** [octobercms/october#3692]
##### Expected behavior
I have a parent model that has an $attachMany 'System\Models\File' attached to it. I then have a child model that has an $attachMany 'System\Models\File' attached to it. The child model also has protected $touches defined to access the parent models "updated"at". When I add a file or remove a file to the child model, the parent models "updated_at" is not "touched."

##### Actual behavior
Given what is said above, nothing happens. The parent models "updated_at" is not "touched." 

##### October build
437

##### Side note
It appears that the "updated_at" column isn't even updated when attaching files to the parent model. Simple create a model with $attachMany 'System\Models\File' attached to it. Upload a file to the parent model, and it does not update the "updated_at" column.

**Comment by LukeTowers** [comment]
Sounds like the attachMany relationship doesn't do anything with the `touches` property, could you look into that in the library code and see if you can come up with a PR to fix it?

**Comment by WaskiWabit** [comment]
**could you look into that in the library code and see if you can come up with a PR to fix it?**

Which lib?

**Comment by LukeTowers** [comment]
@WaskiWabit [octobercms/library](https://github.com/octobercms/library)

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
