### ISSUE TITLE
Invalid security token and Service Workers

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3707]
I have read all the past issues with regards to the error message "Invalid security token" however none talk about Service Workers causing this issue.

When you add a Service Worker to October CMS you will get the following issues:

(**Please note**: In Firefox and Google Chrome you can turn off the Service Worker however you will still get issues)

1. Login to backend wont work first time and you have to login 2 or 3 times.
2. Saving files, you get constant problems trying to save files in the backend.
3. Having two or more tabs opened at same time while working on the same website will cause issues!

## Solution:

I'm using Google's Workbox - Service Worker Library and I have spoken to some Googler's about this issue. There is a solution to actually turn off the Service Worker's for the admin section. However, there is a security issue that needs to be taken into consideration! If you have setup the backend URL to a custom one to add an extra layer of security, you would not want to list that URL in Javascript and show people. So I would recommend using PHP to block Service Worker from caching the backend URL's.

So I open this issue for a feature request to be coded in php (hiding the backend custom URL) to make October CMS fully supportive of Service Workers and PWA websites by automatically turning off the Service Worker for admin webpages. (Hopefully I make sense?!)

So that's: 
Type: Bug
Type: Conceptual Enhancement

Further information can be found here:

https://github.com/GoogleChrome/workbox/issues/1164
https://github.com/w3c/ServiceWorker/issues/1257

**Comment by w20k** [comment]
Hi, @ayumihamsaki , 

Had the same problem while testing jQuery 3.x, it was a minor bug in the octobercms.min.js file. 
Maybe you had an error in console? 

If not, might give it a try at the end of the week, and post my 'workflow'.

**Comment by ayumihamsaki** [comment]
@w20k hi ya, I have my console dev tools screen open all the time. There is no error displayed. Only error is saying no manifest file can be loaded in the backend. Yah if you could look into it that would be great. It's a highly annoying bug.

**Comment by w20k** [comment]
@ayumihamsaki , Hi, didn't have time to play with a fully PWA ready solution (or close to fully workable solution), but I did small testing, and thought about an idea. Haven't yet digged in the Workbox docs, so this might sounds silly, but Isn't that easier to just specify "white listed routes" ?

**Comment by ayumihamsaki** [comment]
@w20k 

> Isn't that easier to just specify "white listed routes"

Yes and no, because you dont want to write the URL route of your custom October CMS Admin in a Javascript File which hackers can read, if you are saying just to add the route in the service worker code. But if you are saying create a white list via php then I say yes, because then it would be hidden.

**Comment by w20k** [comment]
@ayumihamsaki , That was not exactly my idea :) 

Just use approach that firewalls uses under the hood: specify only those route, that are public, and for all others - deny usage of SW. By default, if route is not specified, just don't use service worker. Hackers won't see your private routes anyhow (only by sniffing ports/routes, in this case), if you really need to use admin/private routes with Services workers, which might sounds strange for me, than - yeah, you have to do it in 'Engine' - php.

**Comment by ayumihamsaki** [comment]
@w20k I got this feeling you not used service workers much? That wont fix the issue in this problem. 

I think the issue is that the service worker is messing up the session cookie and showing october a cached version of the cookie only or something. No admin files are being cached by the way.

**Comment by ayumihamsaki** [comment]
@w20k Cool idea, will create that for the backend and see if it will fix the issue.

**Comment by w20k** [comment]
@ayumihamsaki , you're welcome ;) Hope it helps!

**Comment by ayumihamsaki** [comment]
@w20k Have tested it out, only half works. You also need to delete the pre-cache as well, so if the Service Worker is already cached or you open both the Admin and websites in different tabs in the same browser, you would still get the issue and need to clear the cache as well. 

Doing both things I think will sort out the issue - still coding and testing...

**Comment by ayumihamsaki** [comment]
I think the following three things should be added to October CMS to fix the issue, these are as follows:

1. As w20k has said, give an option in the backend Settings to be able to block the Service Worker Route.

2. OctoberCMS should Clear the Cache on the Admin Login Page, this would cover two main things, the first is clearing the Service Worker Cache or any other Cache that has been instead by the website beforehand. The second would be a security issue such as Web Cache Poisoning. To fix both issues October CMS should use the "Clear Site Data" Header on the admin login screen. For more information can be found here: https://www.w3.org/TR/clear-site-data/

A basic coding example of the header would be like this, for the admin login screen:

`Clear-Site-Data: "cache", "cookies"`

The above Code will remove all the cache and cookies before the User starts the login process - thus giving a clean screen!

3. The third thing follows on from the second point with regards to security and that October CMS when a User Signs out of the Backend, the CMS should really be using the Clear Site Data Cookie. For this I would suggest using the following setup creating a Kill Switch Method that would fully secure the Webmaster / Admin, see Code:

`Clear-Site-Data: "cache", "cookies", "storage", "executionContexts"`

The above Code will remove all data and fully protect October CMS admin Users from leaking any information. Please note to see this working Live you can look at Github, because I know they are doing this process right now with their logins!

This is my conclusion from running some experiments. Maybe a feature enhacement and/or some more discussion on this issue. I hope this comment is useful.

@w20k @LukeTowers

**Comment by LukeTowers** [comment]
@ayumihamsaki if you can submit a separate PR for each of those issues so that we can discuss them further from there that would be appreciated!

**Comment by ayumihamsaki** [comment]
Still trying to get all the answers with regards to this issue.

https://medium.com/@nekrtemplar/self-destroying-serviceworker-73d62921d717

**Comment by ayumihamsaki** [comment]
Ideas (placement positions):

- public function __construct() (Add the Javascript code to turn off Service Workers)

- public function index() (Add middleware header: Clear-Site-Data: "cache", "cookies")

- public function signout() (Add middleware header: Clear-Site-Data: "cache", "cookies", "storage", "executionContexts")

**Comment by ayumihamsaki** [comment]
@LukeTowers 

I would just to try and create a PR for this today, so that this issue can get closed off. I have done my research now and think I can write the code code for it. But I have some questions about the **Middleware**. (The Javascript side of things will be ok).

I will be editing the file location: https://github.com/octobercms/october/blob/master/modules/backend/controllers/Auth.php

The following code snippets:

```
    /**
     * Default route, redirects to signin.
     */
    public function index()
    {
        $this->middleware('\App\Http\Middleware\ClearSiteDataSignIn::class');
        return Backend::redirect('backend/auth/signin');
    }
```

and

```
    /**
     * Logs out a backend user.
     */
    public function signout()
    {
        BackendAuth::logout();
        $this->middleware('\App\Http\Middleware\ClearSiteDataSignOut::class');
        return Backend::redirect('backend');
    }
```

The `index()` I want to use a before middleware and the `signout()` I want to use an after middleware.

## Questions

1. Where do I put the middleware? I can't see any folder like `app/Http/kernel.php` in October CMS. I was just thinking of putting the middleware in this location:

https://github.com/octobercms/october/tree/master/modules/backend/middleware/

2. If I have to create a new location for the middleware and can't add it to somewhere like:

- protected $middleware
- protected $routeMiddleware

Then how to change the above codes to a namespace (to make things tidy) e.g.

```
    /**
     * Logs out a backend user.
     */
    public function signout()
    {
        BackendAuth::logout();
        $this->middleware('ClearSiteDataSignOut');
        return Backend::redirect('backend');
    }
```

(sorry first time I created middleware in October CMS it's different from just creating them in Plugins)

**Comment by ayumihamsaki** [comment]
@LukeTowers 

I would just to try and create a PR for this today, so that this issue can get closed off. I have done my research now and think I can write the code code for it. But I have some questions about the **Middleware**. (The Javascript side of things will be ok).

I will be editing the file location: https://github.com/octobercms/october/blob/master/modules/backend/controllers/Auth.php

The following code snippets:

```
    /**
     * Default route, redirects to signin.
     */
    public function index()
    {
        $this->middleware('\App\Http\Middleware\ClearSiteDataSignIn::class');
        return Backend::redirect('backend/auth/signin');
    }
```

and

```
    /**
     * Logs out a backend user.
     */
    public function signout()
    {
        BackendAuth::logout();
        $this->middleware('\App\Http\Middleware\ClearSiteDataSignOut::class');
        return Backend::redirect('backend');
    }
```

The `index()` I want to use a **_before_** middleware and the `signout()` I want to use an **_after_** middleware.

## Questions

1. Where do I put the middleware? I can't see any folder like `app/Http/kernel.php` in October CMS. I was just thinking of putting the middleware in this location:

https://github.com/octobercms/october/tree/master/modules/backend/middleware/

If so would the namespace become this:

`use namespace Backend\Middleware;`

2. If I have to create a new location for the middleware and can't add it to somewhere like:

- protected $middleware
- protected $routeMiddleware

Then how to change the above codes to a namespace (to make things tidy) e.g.

```
    /**
     * Logs out a backend user.
     */
    public function signout()
    {
        BackendAuth::logout();
        $this->middleware('ClearSiteDataSignOut');
        return Backend::redirect('backend');
    }
```

or is it ok to write something like this:

```
    /**
     * Logs out a backend user.
     */
    public function signout()
    {
        BackendAuth::logout();
        $this->middleware(Backend\Middleware\ClearSiteDataSignOut::class);
        return Backend::redirect('backend');
    }
```



(sorry first time I created middleware in October CMS it's different from just creating them in Plugins)

**Comment by ayumihamsaki** [comment]
@LukeTowers 

I would just to try and create a PR for this today, so that this issue can get closed off. I have done my research now and think I can write the code code for it. But I have some questions about the **Middleware**. (The Javascript side of things will be ok).

I will be editing the file location: https://github.com/octobercms/october/blob/master/modules/backend/controllers/Auth.php

The following code snippets:

```
    /**
     * Default route, redirects to signin.
     */
    public function index()
    {
        $this->middleware('\App\Http\Middleware\ClearSiteDataSignIn::class');
        return Backend::redirect('backend/auth/signin');
    }
```

and

```
    /**
     * Logs out a backend user.
     */
    public function signout()
    {
        BackendAuth::logout();
        $this->middleware('\App\Http\Middleware\ClearSiteDataSignOut::class');
        return Backend::redirect('backend');
    }
```

The `index()` I want to use a **_before_** middleware and the `signout()` I want to use an **_after_** middleware.

## Questions

1. Where do I put the middleware? I can't see any folder like `app/Http/kernel.php` in October CMS. I was just thinking of putting the middleware in this location:

https://github.com/octobercms/october/tree/master/modules/backend/middleware/

If so would the namespace become this:

`use namespace Backend\Middleware;`

2. If I have to create a new location for the middleware and can't add it to somewhere like:

- protected $middleware
- protected $routeMiddleware

Then how to change the above codes to a namespace (to make things tidy) e.g.

```
    /**
     * Logs out a backend user.
     */
    public function signout()
    {
        BackendAuth::logout();
        $this->middleware('ClearSiteDataSignOut');
        return Backend::redirect('backend');
    }
```

or is it ok to write something like this:

```
    /**
     * Logs out a backend user.
     */
    public function signout()
    {
        BackendAuth::logout();
        $this->middleware(\Backend\Middleware\ClearSiteDataSignOut::class);
        return Backend::redirect('backend');
    }
```



(sorry first time I created middleware in October CMS it's different from just creating them in Plugins)

**Comment by adrenth** [comment]
Please, can we try to fix this issue with a proper solution? This code made me cry for about an hour ;-). I don't think we should add middleware like such in the constructor of a framework Base class.

```
    /**
     * Constructor.
     */
    public function __construct()
    {
        parent::__construct();

        $this->middleware(function ($request, $response) {
            // Clear Cache and any previous data to fix Invalid security token issue, see github: #3707
            $response->headers->set('Cache-Control', 'no-cache, no-store, must-revalidate');
        })->only('signin');

        // Only run on HTTPS connections
        if (isset($_SERVER["HTTPS"]) && $_SERVER["HTTPS"] === "on") {
            $this->middleware(function ($request, $response) {
                // Add HTTP Header 'Clear Site Data' to remove all Sensitive Data when signout, see github issue: #3707
                $response->headers->set('Clear-Site-Data', 'cache, cookies, storage, executionContexts');
            })->only('signout');
        }

        // Add JS File to un-install SW to avoid Cookie Cache Issues when Signin, see github issue: #3707
        $this->addJs(url("/modules/backend/assets/js/auth/uninstall-sw.js"));
        $this->layout = 'auth';
    }
```

Also this causes an error in my projects which are extending the base `Auth` controller:

`Closure object cannot have properties`
at modules/backend/Controllers/Auth.php line 38

----

How to reproduce the "Invalid security token" issue? I can look into it to find a different way to solve this.

**Comment by ayumihamsaki** [comment]
@adrenth feel free to create a pr to fix it, I would suggest using something like [call_user_func()](https://php.net/manual/en/function.call-user-func.php)

**Comment by LukeTowers** [comment]
@adrenth why shouldn't middleware go in the constructor? Isn't that where it's supposed to live? How is this causing issues for you?
