### ISSUE TITLE
New mod_rewrite test in installer doesn't work with my server

### ISSUE THREAD

**Issue by leonaze** [octobercms/october#3708]
Hi,

I tried to make a new install like all the times before but today I have a message "mod_rewrite is required"...

I see that installer change last week with a new test for mod_rewrite. My host Webfaction doesn't support SetEnv : https://community.webfaction.com/questions/19408/how-do-i-set-environment-variables-for-php

I remove the test from the installer and I install October.

Maybe it can help someone or you can change the installer for hosting that can't do SetEnv.

Thanks.

**Comment by LukeTowers** [comment]
Thanks @leonaze. Do you have any ideas for alternative ways of detecting if .htaccess is enabled on Apache servers? Will close this and move discussion to #3673 because it's more active.
