### ISSUE TITLE
Can see YAML Backend Files

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3709]
I have a question, why can anyone be able to see the data in YAML files in the plugins and cms backend etc. Surely they should be hidden like php files? It seems to give hackers a bit too much information to use and reverse engineer attacks on things.

Would it be a good idea to have them only be seen server-side only and not be able to read them directly in the browser?

I'm curious to know the reason.

**Comment by LukeTowers** [comment]
@ayumihamsaki what is your server stack and the config file?

**Comment by ayumihamsaki** [comment]
@LukeTowers 

I'm using:

- siteground hosting
- php 7.2.8
- MYSQL Server version: 5.6.40-84.0-log - Percona Server (GPL), Release 84.0, Revision 47234b3

The php ini is quite long which bit would you want to know?

p.s. screenshot of main bit:

![aaa](https://user-images.githubusercontent.com/17784082/44348112-7aaa6280-a491-11e8-9c78-bd116d2f8d9f.png)

I'm guessing you are saying I need to set something server end?

**Comment by ayumihamsaki** [comment]
p.s. While researching this topic I found this: https://www.drupal.org/project/drupal/issues/1956698

**Comment by ayumihamsaki** [comment]
Ok so would it be a good idea to update the .HTaccess file default?

This code is taken from HTML Boilerplate:

```
	# By default, block access to backup and source files that may be
	# left by some text editors and can pose a security risk when anyone
	# has access to them.

	# http://feross.org/cmsploit/

	# (!) Update the '<FilesMatch>' regular expression from below to
	# include any files that might end up on your production server and
	# can expose sensitive information about your website. These files may
	# include: configuration files, files that contain metadata about the
	# project (e.g.: project dependencies), build scripts, etc..

<IfModule mod_authz_core.c>
      <FilesMatch "(^#.*#|\.(bak|conf|dist|fla|in[ci]|log|orig|psd|sh|sql|sw[op])|~)$">
          Require all denied
      </FilesMatch>
</IfModule>
```

The above code protects against an attack detailed more on the link: 	http://feross.org/cmsploit/

Then the code below is taken from Drupal:

```
<IfModule mod_authz_core.c>
      <FilesMatch "\.(engine|inc|install|make|module|profile|po|sh|.*sql|theme|twig|tpl(\.php)?|xtmpl|yml)(~|\.sw[op]|\.bak|\.orig|\.save)?$|^(\..*|Entries.*|Repository|Root|Tag|Template)$|^#.*#$|\.php(~|\.sw[op]|\.bak|\.orig\.save)$">
          Require all denied
      </FilesMatch>
</IfModule>
```

So basically would it be a good idea to merge the two Filematch lists together and then add the code to the OctoberCMS default HTaccess?

Combining the two I write this:

```
<IfModule mod_authz_core.c>
      <FilesMatch "(^#.*#|\.(bak|conf|dist|fla|in[ci]|log|orig|psd|sh|sql|sw[op]|twig|tpl(\.php)?|xtmpl|yml))|~)$">
          Require all denied
      </FilesMatch>
</IfModule>
```

What I have done is to add thw protection to `twig`, `tpl`, `xtmpl` and `yml` to the boilder plate standard.

What do you think?

**Comment by nathan-van-der-werf** [comment]
> why can anyone be able to see the data in YAML files in the plugins and cms backend 

Do you have any example files which are accessible from the website (with the URL's you are calling them from?).

**Comment by ayumihamsaki** [comment]
@nathan-van-der-werf Hi, I dont want to show my websites, so I will find one just like how the hackers would do instead.

First I will search using a Google Dorks, I will use Rainlab blog plugin as its quite popular, see screenshot:

![111111111](https://user-images.githubusercontent.com/17784082/44411878-6df44000-a55f-11e8-9b65-6db0a41ebe5a.png)

I put a box around someone's website, now I click on the link and can see all their data in their YAML File, see screenshot:

![222222222](https://user-images.githubusercontent.com/17784082/44412027-d7744e80-a55f-11e8-8e6c-893899787b50.png)

Now I have added the following code to my .`HTaccess` see below:

```
<IfModule mod_authz_core.c>
      <FilesMatch "(^#.*#|\.(bak|conf|dist|fla|in[ci]|log|orig|psd|sh|sql|sw[op]|twig|tpl(\.php)?|xtmpl|yml|yaml)|~)$">
          Require all denied
      </FilesMatch>
</IfModule>
```

When someone tries to open my YAML files in the broswer they get redirected to the 404 Error webpage. See below my results from testing it out yesterday:

![aaa5](https://user-images.githubusercontent.com/17784082/44412133-11455500-a560-11e8-9e08-ab0c98d0c7d8.png)

Hope that answer's your message.

**Comment by nathan-van-der-werf** [comment]
But this website (http://feruntu.com) isn't secured at all, I don't think it has a .htaccess, when trying the above I'm also getting the 404 so I don't think this is a real issue?

**Comment by ayumihamsaki** [comment]
@nathan-van-der-werf can you just go to your website that uses October CMS and put in a URL for one of your plugins direct to a YAML file and you will see the data appearing! October CMS should by default not be showing source files - see here: http://feross.org/cmsploit/

So yes its an issue.

**Comment by nathan-van-der-werf** [comment]
@ayumihamsaki  I checked my websites and they all show a 404 (like I said already 3 times).

Also analyse the current .htaccess, https://github.com/octobercms/october/blob/master/.htaccess#L34

Did you try to make a clean installation of OctoberCMS and were you still able to access the yaml files in the plugin / modules directories? If so, tell us about your setup configuration (apache / nginx etc.).

**Comment by ayumihamsaki** [comment]
> when trying the above I'm also getting the 404 so I don't think this is a real issue?

Not sure what you are doing but I can read their YAML file data no problem in a Broswer, see video demo'ing it:

https://youtu.be/-v2lwBVa-og

**Comment by nathan-van-der-werf** [comment]
@ayumihamsaki The website in the demo doesn't have a .htaccess file, that's why you can see the directory listing.

Just tested your setup and I am still getting 404's.

![1](https://user-images.githubusercontent.com/1123054/44424711-3949ae00-a58a-11e8-9a71-cd3b3bfc62dd.PNG)
![2](https://user-images.githubusercontent.com/1123054/44424713-39e24480-a58a-11e8-8304-2cef07bbf6a8.PNG)

**Comment by ayumihamsaki** [comment]
@nathan-van-der-werf This is one of our production websites, I hidden the name. 

Here we have the .HTaccess from https://github.com/octobercms/october/blob/master/.htaccess installed:

![part1](https://user-images.githubusercontent.com/17784082/44425993-68115580-a585-11e8-9a93-f8b74a0b495a.png)

Here is the same website with the extra code added to the .HTaccess:

![part2](https://user-images.githubusercontent.com/17784082/44426016-78c1cb80-a585-11e8-827e-3276ec470ab3.png)

Really not sure why we are getting different results???

**Comment by nathan-van-der-werf** [comment]
What happens when you leave out the version.yaml in the url? Do you see a directory listing ?

(So when you go to: https://www.[url]/plugins/rainlab/builder/updates)

**Comment by ayumihamsaki** [comment]
@nathan-van-der-werf 

If I do, what you ask I will get a 404 error screen doing the following URL, for the following URLS:

https://www.[url]/plugins/rainlab/builder/updates
and
https://www.[url]/plugins/rainlab/builder/updates/

404 Error with and without a backslash at the end.

**Comment by nathan-van-der-werf** [comment]
No idea why we are getting different results, I think the issue might be hosting related, since I can in no way reproduce this issue (locally and on multiple servers).

I tried it with apache, apache / nginx proxy and locally (xampp (apache)), on every environment I'm getting the 404  when I'm trying to access the .yaml files so I think it's really an hosting related issue. 

Maybe you can try a setup on your local computer with xampp when using windows or just a webserver when using a mac and try it that way (if you didn't do that already).

**Comment by ayumihamsaki** [comment]
@nathan-van-der-werf I'm thinking it maybe a server level issue, gonna contact the hosting company and get them to have a deeper look, thanks for your time.

**Comment by ayumihamsaki** [comment]
Gonna close this issue the hosting company said there was a issue in the server apache / nginx code nd they have resolved it now.
