### ISSUE TITLE
Plugin Prefix Name

### ISSUE THREAD

**Issue by tripti20** [octobercms/october#3713]
##### Expected behavior
When we create a new Plugin through Builder.First step is to enter name and prefix which is used to create a database table with PluginName_Prefix_TableName.

If I change my mind while creating table name to change Plugin Name is there a way to do that. 

Through Localisation we can change Name but while creating database table .It still take old names. If we try to change them it doesn't allow to create table.

I attached an image to show error .
![image](https://user-images.githubusercontent.com/15129953/44409397-36cf6000-a55a-11e8-8487-442728c46084.png)

**Comment by LukeTowers** [comment]
This is not an issue for the main October repository, this is a question for Slack or perhaps at most an issue for the Builder repository.

That being said, it's easy to just have the builder plugin generate the tables with the prefix as it is and then go in and change the namespace and migration files to actually be what you want them to be in the code directly.
