### ISSUE TITLE
Autoprefixer support

### ISSUE THREAD

**Issue by mariavilaro** [octobercms/october#3715]
Hi! I was investigating a way of integrating autoprefixer and I just found out that the Assetic package that you are using to compile the assets already has a AutoprefixerFilter for that. Do you plan in supporting it soon? Maybe as a new config param in config/cms.php or something?

**Comment by LukeTowers** [comment]
@mariavilaro what would you suggest? Also, could you expand what exactly an "auto prefixer" does? Is that for adding the vendor prefixes to CSS properties? If so, does that filter work with projects that already have vendor prefixed properties?

**Comment by mariavilaro** [comment]
Yes @LukeTowers it's exactly that. Latest Laravel with webpack does it automatically already. https://github.com/postcss/autoprefixer

I'm not exactly an expert, but I think that if you run it with projects that are already prefixed, it will remove and readd the properties as your browsers configuration says.

And yes @Teranode of course autoprefixer needs to be installed in the system as a node module.

I managed to do it and will do a pull request so you can try it now

**Comment by mariavilaro** [comment]
I think I will have to desist. In Win and Mac devel environments I can't make it work, in my linux server it works but when I try to pass a browser list that is not the default, it fails with a timeout. I think it's too much to make it work in runtime.

**Comment by LukeTowers** [comment]
@mariavilaro well thanks for your interest in it anyways!
