### ISSUE TITLE
Question about ExtensionBase code

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#3716]
Looking at the code for ` October\Rain\Extension\ExtensionTrait` I noticed the following code:

``` php
protected $extensionHidden = [
    'fields' => [],
    'methods' => ['extensionIsHiddenField', 'extensionIsHiddenField']
];
```

https://github.com/octobercms/library/blob/c643d02957f5e2bdbccb796e5d03a0ae3342c2b1/src/Extension/ExtensionTrait.php#L27-L30

Should it not be:

``` php
protected $extensionHidden = [
    'fields' => [],
    'methods' => ['extensionIsHiddenField', 'extensionIsHiddenMethod']
];
```

Maybe @LukeTowers can shed some light on this.

**Comment by LukeTowers** [comment]
@SeriousKen you're probably correct, good catch! I'll ping @daftspunk to take care of this just in case he did it on purpose.

**Comment by daftspunk** [comment]
Confirmed typo. PR would be accepted.

**Comment by SeriousKen** [comment]
PR created https://github.com/octobercms/library/pull/340
