### ISSUE TITLE
October Drivers market version is behind upstream (causing errors in PHP7.2 environment)

### ISSUE THREAD

**Issue by viamage** [octobercms/october#3719]
##### Expected behavior
October Drivers installs Guzzle 6.3 when installed with php artisan plugin:install october.drivers

##### Actual behavior
October Drivers installs Guzzle 6.0

##### Reproduce steps
```
php artisan plugin:install october.drivers
```

##### October build
any

#### Details
There are bugs in Guzzle 6.0 affecting all PHP7.2 users, which were resolved in Guzzle 6.3. 
https://github.com/guzzle/guzzle/issues/1750

I see October.Drivers have this version in repository version of composer.json, but Market version is behind. 

Can you please sync Market version of the plugin with the repo?

**Comment by w20k** [comment]
@LukeTowers , should be compatible with version 5.5 or higher("php": ">=5.5").

They fixed the bug where collection wasn't initialised, which somehow was related to many libraries and php 7.2 ([Pull request fix](https://github.com/guzzle/guzzle/pull/1686/files))

**Comment by LukeTowers** [comment]
@daftspunk I don't have access to the October marketplace account to setup auto builds for the Drivers plugin to pull in https://github.com/octoberrain/drivers-plugin/commit/40f6a8272738ade54aac7133f783e92818fe45a5 for a new marketplace build.

**Comment by daftspunk** [comment]
Jobs done:

```
Loading composer repositories with package information
Updating dependencies
- Installing composer/installers (v1.5.0)
- Installing pda/pheanstalk (v3.1.0)
- Installing iron-io/iron_core (0.2.5)
- Installing iron-io/iron_mq (1.5.3)
- Installing predis/predis (v1.1.1)
- Installing mikemccabe/json-patch-php (0.1.0)
- Installing psr/log (1.0.2)
- Installing symfony/event-dispatcher (v2.8.44)
- Installing guzzle/guzzle (v3.9.3)
- Installing rackspace/php-opencloud (v1.16.0)
- Installing league/flysystem (1.0.46)
- Installing league/flysystem-rackspace (1.0.5)
- Installing mtdowling/jmespath.php (2.4.0)
- Installing psr/http-message (1.0.1)
- Installing guzzlehttp/psr7 (1.4.2)
- Installing guzzlehttp/promises (v1.3.1)
- Installing guzzlehttp/guzzle (6.3.3)
- Installing aws/aws-sdk-php (3.66.0)
- Installing league/flysystem-aws-s3-v3 (1.0.19)
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Writing lock file
Generating autoload files
```
