### ISSUE TITLE
Feature request: Artisan schedule:list command

### ISSUE THREAD

**Issue by tamer-hassan** [octobercms/october#3726]
As here: https://github.com/hmazter/laravel-schedule-list
tried to integrate into a OC plugin but cannot get it to work.

**Comment by LukeTowers** [comment]
Please only use GitHub Issues for feature requests if you are using it as a pre-Pull Request collaboration tool. If you aren't planning on implementing it yourself, then it would be better suited being asked for on one of these channels:

Forum: http://octobercms.com/forum
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

The support demand for October is increasing, while the available time the founders have to give remains the same. Feature requests are by default the lowest priority for us, as we don't have time to implement everyone's suggestions by ourselves. However there are ways you can help:

- Submit a pull request that introduces this feature and we'll review it. Please note that the amount of effort making the PR (code quality, rationale for inclusion in the project, explanation of changes) is directly proportional to the likelihood that we will review and merge it.
- [Make a financial contribution to the project](https://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by tamer-hassan** [comment]
I now have a working plugin, which I will publish, hopefully later today.
Could you kindly reopen the issue so I can reference a PR to here?

**Comment by tamer-hassan** [comment]
nevermind, i read this https://octobercms.com/help/site/authors
