### ISSUE TITLE
Should I Keep Publisher/Developer Roles Or Replace Them With My Own?

### ISSUE THREAD

**Issue by ibanks** [octobercms/october#3728]
##### Expected behavior
I expect that when I set the publisher and developer **is_system** flag in the database to false, I will be able to alter the individual permissions in the backend admin panel.

##### Actual behavior
When I alter the permissions and save, the is_system flag in the database is set right back to true each time.

I'm sure this is an elementary question but I haven't put time into changing any permissions or roles until now. So basically, what is the best way to handle being able to override the default system settings for the publisher and developer roles?

##### Reproduce steps
Just update the database and try to save a permission on the backend for a role.

##### October build
October 1.0.1

**Comment by LukeTowers** [comment]
Read http://octobercms.com/docs/backend/users to get a better understanding of how the role system works @ibanks

**Comment by LukeTowers** [comment]
Also don't just make up a build number if you don't know it 😝

**Comment by ibanks** [comment]
@LukeTowers 

> Also don't just make up a build number if you don't know it

Lol. You got me. ;-)
