### ISSUE TITLE
Is setDepth necessary here in NestedTree?

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#3730]
Looking at the NestedTree trait I spotted this:

https://github.com/octobercms/library/blob/c643d02957f5e2bdbccb796e5d03a0ae3342c2b1/src/Database/Traits/NestedTree.php#L112-L115

The work of `moveToNewParent` is done in the `moveTo` method which as one of the last things it does is call `setDepth`. So is it necessary to call it again? I've commenting out the line done some limited testing and it doesn't seem to break anything.

Could it be removed safely?

**Comment by LukeTowers** [comment]
@SeriousKen is it causing any issues the way it is right now?

**Comment by SeriousKen** [comment]
Looks like it is necessary. When moving nodes with children, the depth doesn't get updated on the children without it.
