### ISSUE TITLE
listsNested incorrect order

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#3734]
##### Expected behavior
Calling listsNested should return an indented array that represents the tree

##### Actual behavior
Returns an indented array but in index order rather than ordered by nest_left

##### October build
437

**Comment by SeriousKen** [comment]
Created PR https://github.com/octobercms/library/pull/344

**Comment by SeriousKen** [comment]
Not sure now if this is the correct way to fix this. Looking at the query object that is got from the builder it doesn't seem to have the nested tree global scope applied to it.

**Comment by SeriousKen** [comment]
Replaced getQuery with toBase which returns a query object with all scopes applied. This ensures the global scope is applied and gives the correct ordering.

**Comment by daftspunk** [comment]
@SeriousKen thanks for this report with the pull request and sorry it has been a while for us to respond. In reviewing this today it is determined that this is a complex case that requires a prototype for demonstration.

If this is still an issue for you, please submit a Pull Request to the [test plugin for investigation](https://github.com/octoberrain/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions on how to replicate it *using the test plugin*.

Once you have a prototype prepared that demonstrates the issue, we can proceed to debug and verify the solution. Thanks again 🙏
