### ISSUE TITLE
Cannot make thumbnails of an image without extension

### ISSUE THREAD

**Issue by Fl0Cri** [octobercms/october#3738]
Actually the `getThumb()` method of `October\Rain\Database\Attach\File` relies on `isImage()` which check if the extension is in an array of image extensions.

The problem is that images may not have an extension. For example I tried to download  an image from a Google Drive url, which look like a long token without indication of the extension (and I bet some APIs also do like this).

It would be great if `isImage()` could check the MIME type instead of the extension.

I'll do a PR if you are ok with this, unless I am missing a good reason why not to use mime types.

**Comment by LukeTowers** [comment]
@Fl0Cri I believe it's currently implemented that way to give some level of control over what the system deems an acceptable image. How come you can't do the analysis of the mime types in your own code and then assign an appropriate extension before passing it off to the File->getThumb method?

**Comment by Fl0Cri** [comment]
Yes, that's what I finally did, but it would have been convenient if it could have worked out of the box.

In my case I need to add custom http headers to access the image so of course the provided `fromUrl()` could not suit my needs (I don't blame it, I understand that it's a too specific use case), but in a more common case it could have detected the `Content-Type` response header and internally set things ready for processing.

I hoped that downloading the image and just calling `(new File)->fromData($response, $rawName);` would work. Manually adding an extension to the name just adds a few lines and a types dictionary to my helper, and feels a bit hacky (but fortunately I didn't have to check if an extension was already present in the url).

You can close this issue if you think that it's better to rely on the extension instead of the mime type or if it would be too tricky to implement while keeping retro-compatibility.
If you think that something could be improved somewhere, I'll be happy to propose something.

**Comment by LukeTowers** [comment]
@Fl0Cri I'd accept it in the fromUrl method or perhaps as a flag to the isImage method, but not replacing the existing behaviour.
