### ISSUE TITLE
Plugin refresh fails when other plugins depend on it

### ISSUE THREAD

**Issue by CSNWEB** [octobercms/october#3739]
##### Expected behavior
If I refresh a plugin all plugins that depend on it are refreshed as well (first all rolled back and then all recreated). Otherwise this doesn't work at all with dependent plugins.

Example, you installed the User Plugin and now you add your own House Plugin. 

```PHP
<?php namespace Author\House;
class Plugin extends PluginBase
{
    public $require = ['Rainlab.User'];
}
```

And you have a table `house`
```PHP
class CreateHouseTable extends Migration
{
    public function up()
    {
        Schema::create('house', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->integer('users_id');
            $table->foreign('users_id')->references('id')->on('users');
        });
    }

    public function down()
    {
        Schema::dropIfExists('house');
    }
}
```
Then `php artisan plugin:refresh Rainlab.User` should still work

It would also be nice if it shows you what (at least the plugins) will get deleted and ask if this should be done before executing)

##### Actual behavior
October only tries to refresh the specified plugin and *runs into an error* when the referenced table is deleted so most likely after 90% of the migrations as users table is one of the first created tables.

##### Reproduce steps
Create a table in Plugin A and another table with a foreign key in Plugin B and mark Plugin A as required for Plugin B.

##### October build
437

**Comment by LukeTowers** [comment]
@CSNWEB a PR would be accepted implementing the functionality you speak of (rolling back dependent plugins as well upon confirmation)

**Comment by CSNWEB** [comment]
@LukeTowers great to hear. I digged a bit into it and wonder where the right place to fix this is. There seem to be several rollback functions including one in the version manager.

**Comment by CSNWEB** [comment]
I could imagine updating this: https://github.com/octobercms/october/blob/master/modules/system/classes/UpdateManager.php#L533
and this https://github.com/octobercms/october/blob/master/modules/system/classes/UpdateManager.php#L504
But then I would need to add the stopOnVersion parameter, (so the dependencies don't get updated). Or write all logic in the command.

**Comment by CSNWEB** [comment]
@LukeTowers I would actually do that by default otherwise you end up with a hafly down migrated plugin in the worst case. But a flag is also one. The behaviour you describe is exactly what I would like to have. Although this has to be recursive of course so that the dependencies of the dependencies are `down()`ed first (and `up` at the end of course)

**Comment by LukeTowers** [comment]
@csnweb I disagree with having it be the default behaviour, the issue only becomes a problem when dependents enforce DB level foreign keys so having potentially unintentional data loss result by default is not something I'm comfortable with

**Comment by CSNWEB** [comment]
@LukeTowers That why I actually would list all plugins that will be rolledback and ask if you really want to do that. But a flag is also fine, still would like to add that prompt.

**Comment by LukeTowers** [comment]
I would say that we could have it continue doing the current behaviour, but in the output of the default command list the plugins that would be affected by adding the flag to the command and inform the user how to run it with the flag. 

Feel free to submit a PR that implements this functionality in it's own method and then we can go from there to discuss having changes to existing methods in order to clean it up before merging it in.
