### ISSUE TITLE
Valid file characters too restrictive

### ISSUE THREAD

**Issue by montcroft** [octobercms/october#3741]
Smells like #3606 and #3607, but  is a request for broader general character support. Perhaps you could provide this as a configurable option?

##### Expected behavior
Media library should handle any *existing* and valid filename for the operating system / serving environment.

If it cannot manage a given name, it should elegantly handle this case, and allow continued use of the media library. If it's not "valid", hide it or rename it, flag it etc for the user, don't crash the entire request or lock the user out of the folder.

##### Actual behavior
Any character not within a very strict set list raises an exception, preventing use of the entire library, when focussed on directory containing offending file.

If user tries to navigate into folder, a popup warns of offending file, but disallows navigation into folder, and therefor prevents remedy without access to the file system.

With a large number of legacy files containing special characters, this either means a huge manual cleanup, or a change to the code (or change to the CMS)

This issue is occurring in:
modules/system/classes/MediaLibrary.php:478  on my build (437)

Rather than trying regex validate a good path, why not try matching simply the characters that shouldn't be a allowed: https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words  and start from there.

Also, perhaps only default to the testing of the file name, if it DOESN'T already exist. Which would still help with #3604 

##### Reproduce steps
1) Manually create on disk, in media/ path, a file with name containing characters like:  (  )  [  ] + = ~
2) Navigate to it in the Media manager

##### October build
.  >=437

Keep up the good work!

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Contribute to my Patreon](https://www.patreon.com/LukeTowers) so that I can spend more time on issues like these
- [Make a financial contribution to the project](https://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by montcroft** [comment]
Have just managed to schedule a test for this. Excellent, thanks team. esp @chrisbethelepb

**Comment by montcroft** [comment]
I spoke too soon. The code was in some weird cache state when I tested, and it simply stopped working again at a later time.

We're now stuck on:   '  ' and !    - note that those first two chars are different

I think it's going to be near impossible to catch all allowed characters with a regular expression. I think this code should concentrate on what isn't allowed.

**Comment by LukeTowers** [comment]
@montcroft if you could submit a PR to implement the perfect solution I'd love to review it!

**Comment by montcroft** [comment]
First I will need to gain a better understanding of why this method exists and where it is used. For us it causes a problem when scanning a folder, but I suspect it provides value elsewhere.

I will see what I can cook up.
