### ISSUE TITLE
Dropdowns not working in backend forms with sidebar

### ISSUE THREAD

**Issue by Eoler** [octobercms/october#3745]
List items in dropdown menus (that includes language switcher from RainLab.Translate) are inacessible in backend forms sidebar area - see this video demonstration:

![dropdown-form-with-sidebar](https://user-images.githubusercontent.com/680032/44923943-0a7dc580-ad4a-11e8-9a84-89c1bb6d0a0a.gif)

Reproduced with latest extensionless Chrome/Firefox on Windows 10.

##### October build
442

Possible connection with: #3506

**Comment by LukeTowers** [comment]
@Eoler are you able to investigate the styles that are causing the issue and submit a PR to fix it?

**Comment by Eoler** [comment]
Came as far as concluding that it's connected with independent scrolling for sidebar area (disabling .control-scrollpanel and .control-scrollbar in [form-with-sidebar layout](https://github.com/octobercms/october/blob/master/modules/backend/layouts/form-with-sidebar.htm#L21) fixes it), but too much nested divs and dependencies after that.

Worked around this issue and another one #1698 by overriding FormController behavior with custom view layout `$controller->addViewPath(...)`

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
