### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted (tried to allocate 9796480 bytes) in RainLab User Plugin

### ISSUE THREAD

**Issue by jason-migz** [octobercms/october#3747]
##### Expected behavior
POSSIBLE DUPLICATE: [https://github.com/octobercms/october/issues/2590](url)
- I will redirect to UserPage when Log-in Authentication is valid
##### Actual behavior
- When i try to login this Error is displayed Allowed memory size of 134217728 bytes exhausted (tried to allocate 9796480 bytes)

##### Reproduce steps
- Seed the RainLab.User Plugin for 10000 User
- Log-in with Username and password from the Seeded User Data
![capture](https://user-images.githubusercontent.com/21366028/44974908-9e8e9d80-af93-11e8-97da-11c53653e2dd.JPG)

##### October build
(October build number)
- 442

**Comment by LukeTowers** [comment]
1. This doesn't belong in the main OctoberCMS repo, use the repo for the RainLab.User plugin instead: https://github.com/rainlab/user-plugin
2. This looks like something's wrong in your octobercms-profile-search project. Can you replicate in a fresh install of OctoberCMS on the demo theme?

**Comment by jason-migz** [comment]
This [https://github.com/rainlab/user-plugin](url) Plugin is my currently using here is the picture of my Installed plugin 
![capture](https://user-images.githubusercontent.com/21366028/45007242-7b193080-b02f-11e8-9f29-f9cff12687f0.JPG)
Looks Like this plugin can't handle vast amount of users or just my XAMPP server. but i tried it on Laravel project and seed 1 million user and user there _php artisan make:auth_ and works fine. I am wondering if i can implement standalone laravel authentication in my OctoberCMS Application instead using this Plugin. Thanks
