### ISSUE TITLE
404 page no ajax handlers was found

### ISSUE THREAD

**Issue by Mohmdthabet** [octobercms/october#3749]
Adding on Ajax request using  $.request inside the 404 page returns 

> 
AJAX handler '' was not found. 

Although it is added in the layout and inside the page itself.

You can replicate the issue by adding any ajax request inside the 404 page it always returns the ajax handler is not found.

**Comment by LukeTowers** [comment]
@the-specialist2005 please submit a PR to this repository demonstrating the issue in the demo theme.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
