### ISSUE TITLE
Project list combobox in marketplace looks wrong

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#375]
Related to #146 which has incorrectly been closed, so I'm opening another issue for it.

This is still occurring on OSX retina monitors.

![](https://camo.githubusercontent.com/bdfb2707d7ad78a8adff0d5bbc5fc050ed227e06/687474703a2f2f692e696d6775722e636f6d2f314e4d616477682e706e67)

**Comment by daftspunk** [comment]
Please confirm if this still occurs and reopen.
