### ISSUE TITLE
Meta description inserted but not showing on page itself

### ISSUE THREAD

**Issue by wertykid** [octobercms/october#3751]
##### Expected behavior
(Describe expected behavior here)
Hello,
I have implemented Meta Title and Description at the backend of some static pages. However, when I check the source webpage it does not reflect the meta title and meta description. Can anybody help me with this? Thanks a lot!

![metaissue1](https://user-images.githubusercontent.com/15935795/44997225-644aed80-afdf-11e8-8c67-e3ef33cf7615.png)

![metaissue2](https://user-images.githubusercontent.com/15935795/44997254-8f354180-afdf-11e8-9d5a-389d3f6b0b46.png)

![metaissue3](https://user-images.githubusercontent.com/15935795/44997259-91979b80-afdf-11e8-8854-8a19eb98f02b.png)

**Comment by LukeTowers** [comment]
Yes, you need to do that yourself in your theme. See https://github.com/rainlab/bonjour-theme/blob/master/partials/site/meta.htm#L2-L10
