### ISSUE TITLE
please update laravel 5.5 to 5.7

### ISSUE THREAD

**Issue by testdnmedia** [octobercms/october#3756]
october cms now uses version 5.5, please support laravel version 5.7. judging from the version used now it is far behind

**Comment by Teranode** [comment]
October uses LTS releases. When the next LTS releases it will be upgraded to that.

**Comment by LukeTowers** [comment]
As @Teranode said. Laravel breaks things far too often for us to be constantly upgrading the core version used, OctoberCMS will only ever use LTS releases of Laravel.
