### ISSUE TITLE
Access Twig Variable in Javascript file

### ISSUE THREAD

**Issue by jason-migz** [octobercms/october#3757]
##### Expected behavior
I expected that if i will write variable in my _.htm_ like this `{% set name = 'Juan' %}` and alert it in my _.js_ file like this `var myName = '{{ name }}' alert(myName);` it will alert the `myName` variable.  

##### Actual behavior
Instead alert the `myName` variable it's alerted the whole string like this {{ name }} I hope OctoberCMS developer will notice this because in Laravel Framework which OctoberCMS is based you can do `{{ route('profile')}}` in your AJAX url request.

##### Reproduce steps
set variable in `.htm` file and make variable in `.js` file which value is the value of the variable on your `.htm` file and alert it using javascript.

##### October build
442

**Comment by munxar** [comment]
put that in **one** file:

```twig
{% set name = 'Joan' %}
<h2>{{ name }}</h2>
<script>
alert('{{ name }}')
</script>
```

it works.

**Comment by jason-migz** [comment]
@munxar I got syntax error when i put
```javascript
    {% set name = 'Joan' %}
```
inside the <script></script> tag but it works fine when i put it outside the <script></script> tag inside the _.htm_ file.

**Comment by w20k** [comment]
@jason-migz , could you share your code snippet, probably you have an error in usage. 

This is correct example, and should not rise any errors (tried on my local machine, build version 442):
```
<script>
{% set name = 'Joan' %}
window.myVar = '{{ name }}'
</script>
```

**Comment by jason-migz** [comment]
@w20k your code works fine because you set the variable in global scope. but how about if i am going to use it in jQuery AJAX. for example in Laravel which OctoberCMS based you can do this
```javascript
   $.ajax({
     url : '{{ route('profile') }}',
     method: 'POST',
   });
}
```
How about in OctoberCMS? because nowadays developers uses AJAX all the time especially when form submittion.

**Comment by w20k** [comment]
First, I wouldn't go with route function here, it will throw an error if your route is not defined and twig will bug out. So, your need a wrapper or a custom function, or in case of OctoberCMS I'd use - filter: page ( ```{{ product | page }} ```)
Second, what would I do before doing ajax request, put your 'route('profile')' to a variable and check if it's empty or a valide url.

```
   var url = '{{ route('profile') }}';
   if(url && isValidUrl(url)){
   $.ajax({
     url : url
     method: 'POST',
   });
}
```
