### ISSUE TITLE
Backend controller behavior hidden actions

### ISSUE THREAD

**Issue by kpolicar** [octobercms/october#3762]
##### Expected behavior
Define a variable $hiddenActions on classes extending Backend\Classes\ControllerBehavior which appends these actions to the controller's existing hidden actions.

##### Actual behavior
One can currently hide controller behavior actions by calling the hideAction method for each action in the behavior, or by listing the methods in the controller. Both methods are rather messy and unpractical.

##### Reproduce steps
For instance, when implementing ListController behavior to a backend controller, all public functions (there are quite a few) can be directly accessed using url parameters. Example using the Backend\Controllers\Users controller: _/backend/backend/users/listMakePartial/container_

**I'm ready to develop this myself if approved as a good idea.**

##### October build
436

**Comment by LukeTowers** [comment]
@Naltamer a PR for that would be accepted, also the default controller behaviors that are included in October should make sure that they aren't letting unintentional actions through (i.e. ` /backend/backend/users/listMakePartial/container`)
