### ISSUE TITLE
Filtering backend form data via Laravel middleware

### ISSUE THREAD

**Issue by VoroninWD** [octobercms/october#3767]
In my plugin I defined the boot() method and added middleware from Laravel package.

```php
public function boot()
{
    $this->app[Kernel::class]
        ->prependMiddleware(ConvertEmptyStringsToNull::class);

    $this->app[Kernel::class]
        ->prependMiddleware(TrimStrings::class);
}
```

But all data written to the database - all exactly empty `_`, not `null`.

The reason is in this line:
https://github.com/octobercms/october/blob/2d77565e6cbdc26e91a2c1459bf90da79e70c23a/modules/backend/widgets/Form.php#L1130

The `post()` function receives data from `$_POST`, but middleware requires an `input()` method that receives data from `Input::all()`.

I want to know how the change of function `post()` to `input()` can affect the operation of the system?

**Comment by ebashu-on-holidays** [comment]
@LukeTowers , changing from `$_POST` to `request()->post()` helped to solve the problem

**Comment by LukeTowers** [comment]
@ebashu-on-holidays could you test the related pr fully then to speed up the process of merging it?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
