### ISSUE TITLE
Unable to Upload a file using JavaScript API (Argument 1 of FormData.constructor is not an object)

### ISSUE THREAD

**Issue by kojaktaha** [octobercms/october#3768]
##### Expected behavior
I am Trying to upload a file through Ajax in OctoberCMS, there are 2 ways to upload using Ajax either using the a for like in this [eaxmple ](https://gist.github.com/daftspunk/7491eccdb1986c2435f8fe64d9714921), or by using the JavaScript API as shown on the [Documentation](https://octobercms.com/docs/ajax/javascript-api#javascript-api).

My problem is with using the second method. 

##### Actual behavior
I get a JavaScript Error that Says (Argument 1 of FormData.constructor is not an object) in the console

##### Reproduce steps

```


<div class="form-group">
              <label>Image</label>
                  <input type="file" name="image" id="image" accept="image/*">
               </div>
               <div class="form-group">
                  <button type="submit" class="btn btn-primary" id="submitPictureWithAjaxAPI">Submit</button>
               </div>
               
```
            <script>
               $("body").on('click',"#submitPictureWithAjaxAPI", function() {
                   var formData = new FormData();
                    formData.append('file', $('input[type=file]')[0].files[0]);
                       $.request('onFileUpload', {
                           files: true, 
                           data: formData,
                           success: function(data) {
                               $.oc.flashMsg({
                                   'text': 'Uploaded Successfully!',
                                   'class': 'success',
                                   'interval': 5
                               });
                               location.reload();
                           },
                       });
               });
                
            </script>

##### October build
(437)

**Comment by kojaktaha** [comment]
@LukeTowers How should I go about it?

**Comment by LukeTowers** [comment]
@kojaktaha you should just be able to remove those lines and do the following:
```js
$.request('onFileUpload', {
                       files: true, 
                       form: $('#specific_id_of_container_holding_file_input'),
                       success: function(data) {
                           $.oc.flashMsg({
                               'text': 'Uploaded Successfully!',
                               'class': 'success',
                               'interval': 5
                           });
                           location.reload();
                       },
                   });
```

**Comment by kojaktaha** [comment]
@LukeTowers I got a new Error when I tried it 

Argument 1 of FormData.constructor does not implement interface HTMLFormElement

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
