### ISSUE TITLE
Extending Cms\Classes\Page with Repeater Groups Field displays 'Unknown component` error after page saved

### ISSUE THREAD

**Issue by seanthepottingshed** [octobercms/october#3769]
##### Expected behavior
To be able to extend `Cms\Classes\Page` with Repeater Groups field.

##### Actual behavior
Extending `Cms\Classes\Page` with Repeater Groups field displays **Unknown component** error:

![screen shot 2018-09-09 at 08 59 35](https://user-images.githubusercontent.com/12046965/45262448-b4c2b080-b40e-11e8-824e-b1120addaf5c.png)

...file is updated as follows:

```twig
title = "Page not found (404)"
url = "/404"
layout = "default"
is_hidden = 0

[blocks]
0[text_area] = "Test"
0[_group] = "textarea"
==
<div class="jumbotron">
    <div class="container">
        <h1>Page not found</h1>
        <p>We're sorry, but the page you requested cannot be found.</p>
    </div>
</div>
```

##### Reproduce steps

* https://github.com/octoberrain/test-plugin/pull/53
* Navigate /backend/cms
* Open `Page not found (404)` page
* Click on **Content Blocks** tab
* Add content blocks
* Click **Save** and close page
* Open 'Page not found (404)` page

##### October build
`419` and `442`

**Comment by LukeTowers** [comment]
@seanthepottingshed did https://github.com/octobercms/october/commit/a0ec7652f8e366ca5ad463067569da91dd55bd30 fix it?

**Comment by daftspunk** [comment]
You will want to make sure you extend the `viewBag` component to prevent the unknown component error, this is a dedicated component intended to serve this exact purpose. So the result will end up something like this:

```
[viewBag]
blocks[1][quote_position] = "left"
blocks[1][quote_content] = "Test"
blocks[1][script] = "Test2"
blocks[1][_group] = "quote"
blocks[2][text_area] = "Test 3"
blocks[2][script] = "Test 4"
blocks[2][_group] = "textarea"
```

When extending the CMS object, make sure you extend directly to the `viewBag` array as well (ignore `settings` it is an internal marker):

```
Event::listen('backend.form.extendFields', function ($widget) {
    if ($widget->isNested) {
        return;
    }
    if (!$widget->model instanceof \Cms\Classes\Page) {
        return;
    }

    $widget->addFields([
        'viewBag[blocks]' => [
            'prompt' => 'Add Content Block',
            'type'   => 'repeater',
            'groups' => [
                'textarea' => [
                    'name'        => 'textarea',
                    'description' => 'Basic text field',
                    'icon'        => 'icon-file-text-o',
                    'fields'      => [
                        'text_area' => [
                            'label' => 'Text Content',
                            'type'  => 'textarea',
                            'size'  => 'large',
                        ],
                    ],
                ],
                'quote'    => [
                    'name'        => 'Quote',
                    'description' => 'Quote item',
                    'icon'        => 'icon-quote-right',
                    'fields'      => [
                        'quote_position' => [
                            'span'    => 'auto',
                            'label'   => 'Quote Position',
                            'type'    => 'radio',
                            'options' => [
                                'left'   => 'Left',
                                'center' => 'Center',
                                'right'  => 'Right',
                            ],
                        ],
                        'quote_content'  => [
                            'span'  => 'auto',
                            'label' => 'Details',
                            'type'  => 'textarea',
                        ],
                    ],
                ],
            ],
            'span'   => 'full',
            'tab'    => 'Content Blocks',
        ],
    ], 'primary');
});
```

**Comment by seanthepottingshed** [comment]
@LukeTowers 

Many apologies I've been off work until today, I will have a look shortly.

**Comment by seanthepottingshed** [comment]
@daftspunk @LukeTowers 

Massive apologies for the delay in getting back to you about this. The repeater now renders as expected and data can be saved, however validation isn't possible. I've raised another related issue here:

* https://github.com/octobercms/october/issues/4175

**Comment by w20k** [comment]
@seanthepottingshed could you close this issue then? Or it's better that I add `completed` tag?
