### ISSUE TITLE
Call to undefined method Cms\Widgets\TemplateList::getCollapseStatus() - Build 442

### ISSUE THREAD

**Issue by nozreh** [octobercms/october#3770]
Not really sure what is causing this error, I have updated all the core modules to the latest (Build 442)
But when I tried accessing my backend cms and RainLab.Pages I'm getting this error:

````
(1/1) BadMethodCallExceptionCall to undefined method Cms\Widgets\TemplateList::getCollapseStatus()
--
in ExtendableTrait.php line 398
at Extendable->extendableCall('getCollapseStatus', array('about'))in Extendable.php line 46
at Extendable->__call('getCollapseStatus', array('about'))in _items.htm line 6
at include('/var/www/html/public/modules/cms/widgets/templatelist/partials/_items.htm')in ViewMaker.php line 250
````

##### Expected behavior
Supposed to show all the CMS pages, layouts files etc.

##### Actual behavior
Unable to view CMS and Pages, showing 
`Call to undefined method Cms\Widgets\TemplateList::getCollapseStatus()` error

##### October build
(442)

Hope someone can point me to right direction, because I can't replicate this issue in my local, only showing in my QA server.

**Comment by LukeTowers** [comment]
@nozreh check to make sure that your local copy of https://github.com/octobercms/october/blob/master/modules/cms/widgets/TemplateList.php matches the one on Github.

**Comment by nozreh** [comment]
Hi @LukeTowers,

Thanks for the response.

Yes, it's exactly the same.

Here's the QA test user to see it in action.
url: https://qa.omh.sg/
login: temp_user
password: tempuser

**Comment by Samuell1** [comment]
@LukeTowers

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
