### ISSUE TITLE
/modules/backend/formwidgets/richeditor/assets/js/richeditor.js wrong info in comment

### ISSUE THREAD

**Issue by pavelmgn** [octobercms/october#3771]
##### In richeditor.js:
```
/*
 * Rich text editor form field control (WYSIWYG)
 *
 * Data attributes:
 * - data-control="richeditor" - enables the rich editor plugin
 *
 * JavaScript API:
 * $('textarea').richEditor()
 *
 * Dependancies:
 * - Froala Editor (froala_editor.js)
 */
```

But its not wrong, if i init richEditor on textarea this will not worked.
The minimum constriction should be as follows:
_example_
```
<div class="field-richeditor size-medium"">
	<textarea name=""
                        style="display: none;"></textarea>
	<div class="height-indicator"></div>
</div>
<script>
$('.field-richeditor').richEditor();
</script>
```
Initialization is not on textarea. 
Maybe I'm wrong, but in another way it did not work for me.

##### October build
442

**Comment by LukeTowers** [comment]
@pavelmgn then feel free to update that example :)

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
