### ISSUE TITLE
Error "php artisan october:install" with an error of "Missing vendor files, try running "composer install" or use the Wizard installer."

### ISSUE THREAD

**Issue by Eparrita** [octobercms/october#3774]
##### Expected behavior

Hello, I have a error after running php artisan october:install. The error is "php artisan october:install" with an error of "Missing vendor files, try running "composer install" or use the Wizard installer."

I tried running composer install, composer update but nothing. If I copy and paste the folder vendor of  other project october installed the command line php artisan october:install, it work.

 How do I resolve this?

**Comment by LukeTowers** [comment]
Sounds like you're missing the composer.json file. Make sure that is present before running composer install or composer update and make sure that composer has the right permissions to create and populate the vendor directory.

**Comment by Eparrita** [comment]
Look the folders and files, they have permission 777, my machine use linux (Elemtary OS), the composer folder have permission 755. I tried all, I clone the repository, I used line command composer create-project october/october, but when I running php artisan october:install always the same error. I would like to able to use the line command. I hope you can help me, I like OctoberCMS is powerful and easy to use.

Thanks

![captura realizada el 2018-09-12 11 46 40](https://user-images.githubusercontent.com/34838881/45434123-04f67880-b684-11e8-9f57-1ea776819f98.jpeg)
![captura realizada el 2018-09-12 12 03 26](https://user-images.githubusercontent.com/34838881/45434125-04f67880-b684-11e8-8c99-a0a4525dd044.jpeg)


--

**Comment by LukeTowers** [comment]
@Eparrita what is the output of running `composer install`?

**Comment by Eparrita** [comment]
> @Eparrita what is the output of running `composer install`?

This is the output

![captura realizada el 2018-09-12 14 09 58](https://user-images.githubusercontent.com/34838881/45441571-b8b43400-b695-11e8-93c5-faae01372c01.jpeg)
![captura realizada el 2018-09-12 14 10 40](https://user-images.githubusercontent.com/34838881/45441572-b8b43400-b695-11e8-84a9-a5cb5691ab58.jpeg)

**Comment by LukeTowers** [comment]
Try following composer's instructions: 
```
Problem 1: The requested PHP extension ext-mbstring * is missing from your system. Install or enabled PHP's mbstring extension.
```

**Comment by Eparrita** [comment]
I going to try that!

**Comment by Eparrita** [comment]
> Try following composer's instructions:
> 
> ```
> Problem 1: The requested PHP extension ext-mbstring * is missing from your system. Install or enabled PHP's mbstring extension.
> ```

It's done!!! Thank you so much for you support!

**Comment by LukeTowers** [comment]
No problem @Eparrita 
===
Was this helpful? Did it save you time? Then consider becoming a [Patreon supporter](https://www.patreon.com/LukeTowers) so I can keep providing excellent support! Or, add your thoughts to https://github.com/octobercms/october/issues/3683
