### ISSUE TITLE
Sortable datatable ?

### ISSUE THREAD

**Issue by Alex360hd** [octobercms/october#3775]
##### Expected behavior
The [documentation](https://octobercms.com/docs/api/backend/formwidgets/datatable) mention a $rowSorting option for datatable. I would expect that defining this to "true" add a way to sort your rows in your datatable.

##### Actual behavior
When you set rowSorting: true (also tried sortable: true) to the yaml file describing the datatable, it seems it have no effects.

##### Reproduce steps
- Create a model with a datatable
- Try to make it sortable by defining a "sortable" or "rowSorting" to true in your yaml file

##### October build
442

**Comment by LukeTowers** [comment]
Maybe take a look at the actual code itself before making an issue :)

https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/DataTable.php#L29

**Comment by LukeTowers** [comment]
Feel free to submit a PR implementing it however :)

**Comment by Alex360hd** [comment]
Ah sorry, I looked at others plugins that implement datatables (responsiv.pay for example) to see if I made something wrong. Didn't think to look at the formWidget code directly.

For the PR, will try but I don't feel comfortable enought with october CMS to propose something that could be integrated to core.

**Comment by LukeTowers** [comment]
Doesn't hurt to try @Alex360hd, that's how you learn more about it :)

**Comment by Alex360hd** [comment]
Will try. I looked at the repeater formWidget to see how reordering is done. Seems to be in repeater.js, now I have to understand the code (have some difficulties with your JS syntax, especially Repeater.prototype), will see if I can do something

**Comment by Alex360hd** [comment]
Spent my day trying to understand how it works. I could do some things, and I have some questions for other things.

**What is a success ?**
- I could add a "drag" column to the begining of my datatables
- I can reorder rows with drag & drop of that "drag" column thanks to an external jquery plugin

**What is a fail ?**
- I couldn't add some markup in my "drag" column. Seems there are no "markup" cell type, only input or dropdown, that's why the drag column is empty and behave like a single input
- I can drag & drop and reorder my datatable, but changes are not saved (it's just html change), I don't know where and how I can save that new order

Here is the whole datatable folder as attached file if a good soul want to bring me help, I can't spend a more than one day for this.
[datatable.zip](https://github.com/octobercms/october/files/2379776/datatable.zip)

**Comment by LukeTowers** [comment]
@Alex360hd perhaps you could ask around in the slack? Alternatively is this something you're interested in helping out with @Teranode?
