### ISSUE TITLE
Add ability for plugin authors to redirect to a maintained fork on the marketplace

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#3776]
Plugin developers should have the ability to mark their plugin as obsolete in favour of a forked version. 

In an ideal world, the developer would specify another plugin on the marketplace that is the new canonical version (requiring confirmation from the other plugin's developer, should probably be in the form of an important preset update message for the second part of this, something like "!!! OldVendor.OldPlugin has been replaced by NewVendor.NewPlugin) and that would cause the following:
- The original plugin's page now 301 redirects to the forked plugin's page
- Users of the existing plugin get their plugin to receive an update notification that requires confirmation to smoothly switch them from the original plugin to the new plugin. This would have to tie into plugins connected to projects as well, which could potentially get complicated

**Comment by daftspunk** [comment]
This has been noted. Thanks
