### ISSUE TITLE
Incorrect relationship refreshing

### ISSUE THREAD

**Issue by Synairgis** [octobercms/october#3779]
##### Expected behavior
I created a custom plugin to help my users fill out what they call "Accomplishments". The layouts need a slideshow so I used Peterhegman's slideshow plugin and linked it to my plugin using a relationship. So, what I'd expect when I add an accomplishment is for the slideshow preview to actually mirror the various slides and settings I added when I created said slideshow. Especially if I click on the update button to change something.

##### Actual behavior

If I add one slide, the image of the slide gets completely dropped. If I add more than one slide, the first slide's image gets dropped and the first slide gets pushed down to the last position (i.e. 2nd becomes first, 3rd becomes second and so on). What's more, every setting modification I do doesn't appear in the preview.

What's strange is that if I refresh the page (F5), the slideshow then appears correctly with all the slides in the right order and all of the settings correctly modified (which is what leads me to believe the error lies in the refresh mechanism somewhere). 

##### Reproduce steps

Create a custom plugin (I personally used the "Builder" plugin to do so).
Obviously, your plugin should have a relationship with Peterhegman's slideshow plugin
Next, create a basic interface that'll be used to save whatever your plugin saves
Make sure you have a part that includes Peterhegman's plugin on your interface
Go to your plugin's backend interface and go to create a new record.
Go to the slideshow part of your interface and add a new slideshow
Add three slides and click save
You'll see that the first gets pushed to last with no image and the other two other shift up a position

##### October build
442

**Comment by LukeTowers** [comment]
This is a complex case. 

In order to aid in our understanding of the problem, please submit [a Pull Request to the test plugin](https://github.com/octoberrain/oc-test-plugin) for investigation that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it _using the test plugin_.

**Comment by Synairgis** [comment]
As requested, I created a pull request (#54) and included detailed instructions to reproduce the issue in said request using the test plugin. Of course, if you have any questions don't hesitate to ask.

**Comment by LukeTowers** [comment]
@Synairgis did you get the author of that plugin to look into this? We can't confirm this is a bug with the October core unless you can replicate it using only the October core, not some random person's questionable plugin.
