### ISSUE TITLE
October.Drivers installed files don't match the repo files

### ISSUE THREAD

**Issue by CptMeatball** [octobercms/october#3784]
### Expected
Reinstalling October.Drivers installs the same files when version number don't change.

### Actual
Reinstalling October.Drivers changes the files while the versional number does not.

While checking for some inconsintencies in our mailgun setup, I've reinstalled the `october.drivers` plugin. To my surprise the files of the plugin changed while the version number did not.

- Composer.json removed
- Composer.lock removed
- Homepage added (https://github.com/octoberrain/drivers-plugin)
- License added

The homepage in the `plugin.php` was new according to my Git repo (which has been updates 4 weeks ago), but according to the `Octoberrain.Drivers` repo this was added some 3 months ago. 

Also, the `composer.json` file is still there in the repo but on reinstall the `composer.json` is not includeed in the `october/drivers` directory.

Can someone explain if this is normal behaviour: Why the composer.json has been removed from the plugin but the deps are included in the marketplace build?

_I might be oblivous so some super obvious things here, but I'm just a bit curious / worried this might screw up our production server as the Guzzle library is needed for our Mailgun setup.  (see update)_

#### Update
Okay there were some weird coincidences in this project. It turns out that `plugins/**/vendor` was included the `.gitignore`. Which prevented the upload of the `/plugins/october/drivers/vendor` directory in the first place. Coincedentally there was a package included in the main `composer.json` that included the `guzzlehttp/guzzle` package, which was the reason we did not get any errors while using the Mailgun method for sending mail.

**Comment by CptMeatball** [comment]
I'm also seeing that the vendor folder has been removed from the directory, but I can't see to find the necessary dependencies in the root vendor directory.

**Comment by daftspunk** [comment]
Pushed another build, give it another go.
