### ISSUE TITLE
The layout of tab is crashes when I add a (grouped) repeater item

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#3785]
##### Expected behavior
![good](https://user-images.githubusercontent.com/2959112/45549726-090fcb00-b829-11e8-9ea8-79c712b3a429.jpg)

##### Actual behavior
![issue](https://user-images.githubusercontent.com/2959112/45549210-512dee00-b827-11e8-85bf-30a3de6b7081.gif)

##### Reproduce steps
1. Extend a form with some fields (http://octobercms.com/docs/plugin/extending#extending-backend-form).
2. After that add single or gouped repeater item.

##### October build
442

**Comment by seanthepottingshed** [comment]
```php
Event::listen('backend.form.extendFields', function ($widget) {
    if ($widget->isNested) {
        return;
    }
});
```

**Comment by LukeTowers** [comment]
@gergo85 or @seanthepottingshed could you guys find relevant places in the documentation to add the following:
```
> **Note:** When extending the form, you should check to see if `$formWidget->isNested === false` as the Repeater FormWidget includes nested Form widgets which can cause your changes to be made in unexpected places.
```

**Comment by seanthepottingshed** [comment]
@LukeTowers 

* https://github.com/octobercms/docs/pull/321
