### ISSUE TITLE
Access route() method in jQuery AJAX url option

### ISSUE THREAD

**Issue by jason-migz** [octobercms/october#3790]
##### Expected behavior
It is Good to access route() method of laravel in OctoberCMS, like what laravel did using their templating Engine called Blade like this:
```
$.ajax({
   url: "{{ route('profile') }}",
   method: "POST"

});
```

I know if you create a _routes.php_ inside your plugin directory you can do this:
`Route::post('profile{id}', array('as' => 'profile', 'uses' => 'OCA\Webforms\Classes\Ocaforms@store'));`

##### Actual behavior
but i tried to access my route('profile') in my ajax post request using jquery but it didn't work. any idea on how to deal with this?

##### Reproduce steps
make a HTTP request  using jQuery AJAX and in url option use `{{ route('profile') }}`

##### October build
442

**Comment by LukeTowers** [comment]
If you don't require the parameter filling features of `route()` you can use `| app`: http://octobercms.com/docs/markup/filter-app. If you need to have `route()` accessible within Twig then make a PR to add that functionality and I'll review it.

**Comment by jason-migz** [comment]
Okay. This is Noted. Thank you.
