### ISSUE TITLE
Next button is not working in Plugin Fields table

### ISSUE THREAD

**Issue by jason-migz** [octobercms/october#3791]
##### Expected behavior
I expected when i click the next button in the table, the next column will be show, but i can't click the button. It seems the button is disable. here is the picture

##### Actual behavior
the next button in Column of a Plugin fields is not clickable when the fields is over 12 columns.
![capture](https://user-images.githubusercontent.com/21366028/45606323-d5c27b80-ba76-11e8-8cbe-d98e42744090.JPG)
##### Reproduce steps
Create a plugin and create database table for the plugin and create model and _fields.yaml_ and add 12 columns from the database table you created.

##### October build
442

**Comment by w20k** [comment]
@jason-migz, I think, if menu is too long, it will have the same issue. So, feel free to submit a PR to fix it ;)

**Comment by LukeTowers** [comment]
@jason-migz @w20k see https://github.com/octobercms/october/issues/2820#issuecomment-293979084. Those aren't buttons, they're just visual indicators that it can be scrolled. You're supposed to click and drag the entire panel to scroll it. I do agree that they should be made clickable, further discussion in #2820
