### ISSUE TITLE
Wikipedia article

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#3795]
I my opinion the Wikipedia page of OctoberCMS is very poor. It would be better to have more content.

https://en.wikipedia.org/wiki/October_(CMS)

**Comment by LukeTowers** [comment]
What would you recommend adding to it?

**Comment by gergo85** [comment]
Something like the http://octobercms.com/features page.

The "Features" paragraph would be more information why the October CMS is a good choose to developers.  
Which popular technologies (Laravel 5.5, Twig, YAML, etc.) and own solutions (file-based templates, built-in asset combiner, built-in code editor, etc.) are used.  
The advantages of October are the detailed document and active community too.

**Comment by w20k** [comment]
Wow, looking forward ;) Nice done @gergo85 !

**Comment by gergo85** [comment]
Thank you @w20k ! I added tutorial videos too.
