### ISSUE TITLE
queue class not exist

### ISSUE THREAD

**Issue by mortezaa** [octobercms/october#3801]
I want to push a job in queue but when I writing bottom code in my controller, I got error for class not exist !
I already create my class in classes folder of plugin ...

      ` Queue::push('\Mori\News\Classes\jobs\InstaClass', ['message' => "hello"]);`

The error in failed_jobs table is 

`ReflectionException: Class \Mori\News\Classes\jobs\InstaClass does not exist in D:\xampp\htdocs\project\vendor\laravel\framework\src\Illuminate\Container\Container.php:752
`
how should i do ?!

**Comment by LukeTowers** [comment]
Either `plugins/mori/news/classes/jobs/InstaClass.php` doesn't exist or the namespace at the top of that file is incorrect. 

Please don't make issues for basic PHP questions, save those for the Slack channel or a general google search instead.

**Comment by mortezaa** [comment]
sorry for that but document is not clear on Queues&jobs and no source is availible. Thanks for answer xd

**Comment by LukeTowers** [comment]
No problem, although this has nothing to do with queues or jobs specifically, it's just about class autoloading in PHP :)
