### ISSUE TITLE
[NestedTree][SQLServer] A column has been specified more than once in the order by list. Columns in the order by list must be unique. 

### ISSUE THREAD

**Issue by itpcc** [octobercms/october#3805]
##### Introduction
I use PHP Version 7.2.9 with SQLServer.
I use `use \October\Rain\Database\Traits\NestedTree` with the plugin's model.
I create records and tree using OctoberCMS reorder.
Then, I query children from the record which have children record.

##### Expected behavior
When I ask for record which have children. ( I also call `record.getChildCount` first to make sure that the record have children. ) When I call `record.children`, It should just query:
```log
select * from [<table>] where [<table>].[parent_id] = 1 and [<table>].[parent_id] is not null order by [nest_left] asc;
```

And it should work just fine.

##### Actual behavior
SQL Query adds duplicate ORDER BY field. So, SQLServer throw an error like this:

```log
An exception has been thrown during the rendering of a template ("SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]A column has been specified more than once in the order by list. Columns in the order by list must be unique. (SQL: select * from [<table>] where [<table>].[parent_id] = 1 and [<table>].[parent_id] is not null order by [nest_left] asc, [nest_left] asc)").
```

##### Reproduce steps
0. Use the latest OctoberCMS version with the latest "stable" PHP.
1. Use SQL server as a database
2. Create a plugin's model which `use \October\Rain\Database\Traits\NestedTree`;
3. Create record which has children.
4. Query for children records  using `record.children`

And, there you go! The error is thrown!.

##### My, currently, `monkey` patch

I found out that trait `October\Rain\Database\Traits\NestedTree` and `October\Rain\Database\NestedTreeScope` both call `Order By` statement in the same column. I can't figure out how I can get applied query's statement or query object so I can detect before adding another `Order By` yet. So, for now, I either:

- comment ` 'order' => $model->getLeftColumnName()` (Line 93) in  `trait October\Rain\Database\Traits\NestedTree` out __or__
- comment `$builder->orderBy($model->getLeftColumnName());` (Line 17) in  `October\Rain\Database\NestedTreeScope` out

It'll remove duplicate `Order By` and now the query work again.

##### October build
442

![2561-09-20 08_01_23-exception](https://user-images.githubusercontent.com/3356814/45790446-1573a800-bcaf-11e8-9ec5-e0c13c74a4bc.png)

**Comment by daftspunk** [comment]
Removed the one in the class relationship definition (https://github.com/octobercms/library/commit/8d96a7b239f8b30984ccde8dbfc525558d053197)

This should be available in Build 443

Thanks
