### ISSUE TITLE
TypeError in Firefox 63

### ISSUE THREAD

**Issue by iotch** [octobercms/october#3806]
##### Expected behavior
No errors

##### Actual behavior
In Firefox 63 (and probably other versions), page throws js error `TypeError: previewIframe.contentWindow.document.getElementsByTagName(...)[0] is undefined, can't access property "scrollHeight" of it` at `mailbrandsettings.js:16:35`

##### Reproduce steps
go to `/backend/system/mailbrandsettings`

##### October build
No clue where to find that

**Comment by w20k** [comment]
@iotch, tried with Firefox: 63.0b4 and can't reproduce your error.

![customize_mail_appearance___petro_fit](https://user-images.githubusercontent.com/1053320/45816891-a796a300-bce5-11e8-849a-88d228239a17.png)

**Comment by w20k** [comment]
Hm...strange. you don't have any external plugins or AdBlock enabled? 
Tested with three projects, based on the OctoberCMS, latest build 442 and couldn't reproduce your issue.

**Comment by iotch** [comment]
Will investigate further. I'm closing this for now.
