### ISSUE TITLE
DatePicker problem with Arabic

### ISSUE THREAD

**Issue by mabehiry** [octobercms/october#3808]
##### Expected behavior
In any datepicker for date and time, you should select date and time and click save.

##### Actual behavior
When you save form with date and time, you get this error message:
"A four digit year could not be found
Data missing" on line 909 of D:\xampp\htdocs\sites\dtitest\vendor\nesbot\carbon\src\Carbon\Carbon.php
Also, the time picker doesn't show the time when clicking the icon as shown in this screen:
http://prntscr.com/kwr0j8

##### Reproduce steps
Adjust your backend preferences, select Arabic as Locale language
Open any plugin with a datepicker, in this example I will use rainlab.blog, select a post, click manage, click on the time picker.
Change the time to any value
Click Save

##### October build
442

**Comment by MWalid** [comment]
I fixed my issue above by disabling moment localisation,

at **modules/system/assets/js/lang/lang.ar.js** and just before `var symbolMap = {` I added `return;` statement to disable the Arabic locale.

Now I'm able to save date fields to database

**Comment by LukeTowers** [comment]
@MWalid @mabehiry does https://github.com/octobercms/october/pull/3906 solve the issues for you?

**Comment by mabehiry** [comment]
No, It's the same problem!

**Comment by MWalid** [comment]
@mabehiry Did you try to disable the Arabic symbol mapping?

> at modules/system/assets/js/lang/lang.ar.js and just before var symbolMap = { I added return; statement to disable the Arabic locale.

**Comment by ayumihamsaki** [comment]
@MWalid @mabehiry

Can I ask a quick question. The error message:

> SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '٢٠١٨-١١-٢٨ ٠٢:١٨:٤٤' for column 'birthdate' at row 1 

Is your mysql database field set to UTF-8 and not something like Latin. It needs to be set to:

"utf8_general_ci"

To save in Arabic. Let me know if this is the issue or not as I want to see if this is the library causing the issue or something else?

**Comment by mabehiry** [comment]
@ayumihamsaki 
I don't get this error message, I just get saved! after that I see the field in database like this:
0000-00-00 00:00:00
Also, there is no encoding for the field of type datetime in MySQL

**Comment by ayumihamsaki** [comment]
Sorry, ignore my last comment.

**Comment by ayumihamsaki** [comment]
Sorry, ignore my last comment.

General note I need to update the lang file found here with the new moments locales:

https://github.com/octobercms/october/blob/master/modules/system/assets/js/lang/lang.ar.js

*but I think after doing that it probably won't fix this issue. So will invest further.

**Comment by ayumihamsaki** [comment]
@MWalid Yah that makes sense, I see what you are saying. So use Arab writing for everything except numbers.

@LukeTowers Permission to change the file code at location: https://github.com/octobercms/october/blob/master/modules/system/assets/js/lang/lang.ar.js

And add the commit code I already have done: https://github.com/octobercms/october/blob/21bd7351a2bac1bad0e7a275260c627b250ad88d/modules/system/assets/ui/vendor/moment/locale/ar-ly.js

This should then fix this issue. Can update the PR if you give this the green light.

**Comment by tamer-hassan** [comment]
> @MWalid Yah that makes sense, I see what you are saying. So use Arab writing for everything except numbers.
> 
> @LukeTowers Permission to change the file code at location: https://github.com/octobercms/october/blob/master/modules/system/assets/js/lang/lang.ar.js
> 
> And add the commit code I already have done: https://github.com/octobercms/october/blob/21bd7351a2bac1bad0e7a275260c627b250ad88d/modules/system/assets/ui/vendor/moment/locale/ar-ly.js
> 
> This should then fix this issue. Can update the PR if you give this the green light.
> 
> Please see PR commit: [8c4bd7d](https://github.com/octobercms/october/commit/8c4bd7d3ffc52d339ba83979419c78abdabd2199)

The issue resurfaced with latest release of OctoberCMS, and I had to manually reapply the above mentioned commit changes to fix..

**Comment by zulkufadsiz** [comment]
You can use momentjs like moment(YOURARABICDATE).locale(en).format('MM-DD-YYYY')

**Comment by Ai80-8** [comment]
Delete it all
