### ISSUE TITLE
Unit testing plugin composer packages related plugin not loaded before seeder

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#3810]
##### Expected behavior
When running a unit test on plugin A that requires plugin B that requires plugin C (via `$require = ['Author.PluginB']` and the plugin B has ['Author.PluginC'] in Plugin.php that plugin C's composer is loaded and the classes available.

##### Actual behavior
```
 [Symfony\Component\Debug\Exception\FatalErrorException]
  Interface 'JsonStreamingParser\Listener' not found

Fatal error: Interface 'JsonStreamingParser\Listener' not found in C:\Massweb\office\plugins\tschallacka\pluginb\updates\1.0.1\seed\seed_zipcode_table.php on line 8
```

##### Reproduce steps
Have three plugins. Plugin A and Plugin B.
Have Plugin A require plugin B.
Have Plugin B require plugin C.
Have in plugin C a composer.json some library that is needed by plugin B.
use plugin C's provided library in plugin B's seeder.

##### October build
442

After testing the composer files from plugin C aren't even loaded when doing a `$require = ['Author.PluginC']` in plugin A

**Comment by tschallacka** [comment]
I'm going on my honeymoon now, i can provide test plugins after 3 weeks when needed

**Comment by LukeTowers** [comment]
@tschallacka congrats! Enjoy your time away, just ping me when you're back!

**Comment by tschallacka** [comment]
@LukeTowers https://github.com/tschallacka/thirdpartyload/

I found a solution, but it's quite a handful to implement for all the plugins and such.
Is there a way the default october bootstrap can be modified to autoload the vendor dirs of $required plugins?

**Comment by LukeTowers** [comment]
Probably @tschallacka given that October already supports loading from plugin vendor directories in the first place.

**Comment by tschallacka** [comment]
@LukeTowers I built up the following commands for easy testing reproduction

```
git clone https://github.com/octobercms/october.git
cd october
git fetch origin pull/3804/head:itscomplicated
#                     ^^^^ pull request number here
git checkout itscomplicated
composer install
cd vendor/october/rain
rm -rf *
rm .gitignore
git clone https://github.com/octobercms/library.git .
git fetch origin pull/350/head:itscomplicatedtoo
#                     ^^^ pull request number here
git checkout itscomplicatedtoo
cd ../../..
cd tests/unit
phpunit
```

but for the love of me, if I run it like that I get all kinds of double slash problems. I need to dig a bit in it if it's an encoding issue or that I switched to php 7.2 or something else why I suddenly get unexpected double slashes.
