### ISSUE TITLE
Force HTTPS on octobercms.com

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3814]
The October CMS Website is NOT Secure and even when you login to the sensitive areas on the website it is poorly secure!

See screenshot as evidence!!!

![sssssss](https://user-images.githubusercontent.com/17784082/45931146-5692e300-bf61-11e8-9069-7c0454bbdcec.png)

p.s. I Strongly suggest someone goes and checks the Website Properly! You guys are just asking to get everyone's accounts hacked.

Please make these kind of things High Priority!

## Other Issues with the Website are as Follows:

Both HTTP and HTTPs are running at the same time! There is no proper setup to redirect the website to the secure URL, see screenshot:

![aaaaaaaa](https://user-images.githubusercontent.com/17784082/45931243-3ebc5e80-bf63-11e8-92eb-68b2fd9c9c9e.png)

There are no rel-canonical setup on any URL either:

![bbbbb](https://user-images.githubusercontent.com/17784082/45931256-6dd2d000-bf63-11e8-965e-2d33086960d3.png)

Seriously someone needs to sort that website out!

**Comment by ayumihamsaki** [comment]
@LukeTowers I dont use Slack, but I would be more than happy to update that website to [HTML5 Boilerplate Specs](https://html5boilerplate.com). Normally I would keep quiet on such things but because everyone's cms is connected to that website via plugins and themes it just opens the door to possible hacks and injections from one central location to everyone cms installations.

**Comment by ayumihamsaki** [comment]
Ok will do.

**Comment by LucasZdv** [comment]
The octobercms website already has the certificate for what I see, if it is true that not before.

**Comment by LucasZdv** [comment]
The octobercms website already has the certificate for what I see, if it is true that not before.

**Comment by ayumihamsaki** [comment]
@LukeTowers @LucasZdv Just done a re-check on the website. Can confirm also looks fixed now.

![1](https://user-images.githubusercontent.com/17784082/48665969-6be34400-eab0-11e8-8a71-a4fd45a92e80.png)

Above: Redirects all pass now

![2](https://user-images.githubusercontent.com/17784082/48665974-8ae1d600-eab0-11e8-8e76-9b9d1ad15fff.png)

Above: Cert is correct now and not a hackable Symantec one anymore.

![3](https://user-images.githubusercontent.com/17784082/48666001-64706a80-eab1-11e8-9ac7-55cf3bb49980.png)

Above: SSL Test pass ok

Disclaimer: I would only suggest, someone run a web scraper all over October CMS website to remove any "Mixed Content Issues"

But I would say this issue can be closed now!
