### ISSUE TITLE
Alter backend settings menu

### ISSUE THREAD

**Issue by Alex360hd** [octobercms/october#3817]
##### Expected behavior
October CMS provide a nice way to extend plugins using events. However, it seems there are no events that allow to alter the backend settings menu (I don't mean backend top menu, I mean backend settings left sidebar on the settings page).

##### Actual behavior
Actually, it seems you cannot alter backend settings menu (or I didn't find the event that can do that)

##### October build
All

**Comment by LukeTowers** [comment]
@Alex360hd what exactly are you trying to do?

**Comment by Alex360hd** [comment]
I'm working on an ecommerce plugin. To not reinvent the wheel, this plugin will rely on Responsiv.Currency and Responsiv.Pay plugins to manage currencies and invoices.

These 2 plugins add their own category on backend settings, I would like to regroup all configuration under my own plugin category to avoid to split things.

Best regards,

Alex

**Comment by Alex360hd** [comment]
Thank you, it does the job. I looked at the [doc here](https://docs.google.com/spreadsheets/u/1/d/17vv4zn_ezp9iFBgYhYuYsmUG4MXW9uuIw7aOIrVcHiM/edit#gid=0) and that event wasn't mentionned

**Comment by LukeTowers** [comment]
@Alex360hd yeah unfortunately that doc doesn't cover everything, I'm hoping to get the API docs to 100% when it comes to events but in the mean time your best bet usually ends up being reading the source files to figure things out when you hit a wall in the docs.
