### ISSUE TITLE
Add composer support to the marketplace

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#3819]
It would be great to add composer support to the marketplace so that it could make all marketplace plugins available through a composer interface. There are resources out there for how to create your own packagist clones (composer repositories), and we could have the project IDs provided to composer through an environment variable so that we could even make private plugins available through a composer interface.

**Comment by immersiontravis** [comment]
I would love this. We're trying to get away from Wordpress, and we're thinking about adopting October instead. But one of the *reasons* we dislike Wordpress is its habit of self-updating plugins – which brings the site's filesystem out of sync with version control.

Composer support for all Marketplace plugins would go a long way toward solving this.

**Comment by w20k** [comment]
Hi,

I might be wrong, but if you don't want to have any updates, just disable them, and use composer as your source of updates. OctoberCMS won't update anything, if you don't press "the" button ;) 

From the config, to disable core updates: config/cms -> ```'disableCoreUpdates' => false,```.
And from the Plugins menu:
![screen shot 2018-09-25 at 10 02 32](https://user-images.githubusercontent.com/1053320/45998033-2b67db00-c0aa-11e8-94e6-a304e85875f2.png)

**Comment by ayumihamsaki** [comment]
I like this idea very much! Would it also be a good idea to force people to also use `composer.lock` file and have those plugin packages scanned with https://snyk.io/ thus making OctoberCMS Marketplace safer!

**Comment by LukeTowers** [comment]
@ayumihamsaki neat idea, unfortunately Snyk doesn't support composer / PHP yet: https://support.snyk.io/getting-started/languages-support

**Comment by LukeTowers** [comment]
No clue how I missed that @ayumihamsaki, good catch!

**Comment by LukeTowers** [comment]
With composer 2.0 supporting filtered repositories (see https://php.watch/articles/composer-2), any plugins / themes provided by the marketplace acting as a composer provider should be namespaced under october-plugin/author-plugin and october-theme/author-theme, and then the composer files returned by the packages should take advantage of the [custom installer name property](https://github.com/composer/installers#custom-install-names) to be sure that they are installed in the correct location instead of /plugins/october-plugin/author-plugin

**Comment by daftspunk** [comment]
Composer support has been added and will be available on the next website update. Thanks
