### ISSUE TITLE
Can't change background or text colour on backend lists

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#3821]
I'm trying to use `injectRowClass` to change either the text or the background colour of specific rows in a backend list and it isn't working.

``` php
    public function listInjectRowClass($model, $definition)
    {
        if ($model->isExpired()) {
             return 'text-danger';
        }
    }
```

It works if I use other classes such as `strike`, but I need the rows color coded.

I've tracked it down to `storm.css` setting `color`, and `background-color` on the `th` and `td` elements, which will obviously take precedence over the row class.

https://github.com/octobercms/october/blob/2d77565e6cbdc26e91a2c1459bf90da79e70c23a/modules/system/assets/ui/less/list.less#L91-L98

Is there a way this can be worked around?

**Comment by LukeTowers** [comment]
@SeriousKen you could aways inject your own CSS to the page to override the list styling?
