### ISSUE TITLE
Dashboard make it 12 instead of 10

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3823]
Most CSS Grid systems use 12 because it makes the columns equal sizes, for example:

1 column = 12 spaces
2 columns = 6 spaces
3 columns = 4 spaces
4 columns = 3 spaces

However the Dashboard at the moment is really messy due to it having 10 spaces and giving the following:

1 column = 10 spaces
2 columns = 5 spaces
3 columns = Can't be done as whole number
4 columns = Can't be done as whole number

So I'm asking is it a good idea and would it be possible to change the dashboard to have a 12 column width spacing instead of 10. Then my dashboards would become less messy and not all over the place, which is happening at the moment due to this strange sizing of 10. I am sure a lot of people have noticed this as well.

**Comment by LukeTowers** [comment]
Feel free to make a PR to implement that as an option if it doesn't already exist @ayumihamsaki

**Comment by daftspunk** [comment]
This is merged. Thanks @ayumihamsaki !
