### ISSUE TITLE
Problem with Chinese phonetic symbol

### ISSUE THREAD

**Issue by Hao1995** [octobercms/october#3835]
##### Expected behavior
When I type Chinese phonetic symbol. Like 'ㄔㄨㄤˋ'. 
The normal situation will produce a word '創'. 
And we can press '↓' key to choose which word we want. 
Maybe is '創', '愴' ... these are spell by 'ㄔㄨㄤˋ'.
![tag_edge](https://user-images.githubusercontent.com/25665586/46323501-3a5a0a80-c621-11e8-9aa8-91240d2e05b3.gif)

##### Actual behavior
But here it is wrong. 
When I type the first phonetic symbol '彳'. 
It's normal.
When I type second phonetic symbol 'ㄨ'.  
They will be separate words 'ㄔ','ㄨ'.
I can not type the following phonetic symbol(ex:'ㄤ','ˋ') to produce any words like '創', '愴' ...
![tag_chrome](https://user-images.githubusercontent.com/25665586/46323685-fb788480-c621-11e8-9209-10bd865d8b9e.gif)

##### Reproduce steps

1. install rainlab/blog plugin
2. install bedard/blogtags plugin 
3. go to /backend/rainlab/blog/posts/create, select "Categories" tab and type 'ㄔㄨㄤˋ' on 'tags' field.

##### October build
419

**Comment by LukeTowers** [comment]
@Hao1995 Try upgrading October to the latest build (Note: You will need to read RN-7 and you will need PHP 7).

**Comment by Hao1995** [comment]
My PHP version is 7.1.11. 
Then upgraded the OctoberCMS version to build 443.

The [RN-7](https://octobercms.com/support/article/rn-7) here.
I think it's an issue that is about file path.
Not relate my question.

**Comment by LukeTowers** [comment]
@Hao1995 sorry, I meant [RN-9](https://octobercms.com/support/article/rn-9) for upgrading. Is the issue still present in Build 443?

**Comment by Hao1995** [comment]
@LukeTowers 
Yes! The issue still exists.

**Comment by LukeTowers** [comment]
@Hao1995 Is this an OS / Browser feature? I don't think there's anything special built into October to support this

**Comment by Hao1995** [comment]
@LukeTowers 
I guess the issue is caused by october_proejct\modules\system\assets\ui\storm-min.js.
I search the class "select2-search__field" of tag input element in this file.
Then find the "Search.prototype".
That has a lot of trigger events like 'focus', 'disable', 'keydown' ...etc.
Then I write down many console.log inside.

Finally, I found this function 'Search.prototype.resizeSearch' be trigger two times when I type second phonetic symbol.
 
The situation like the following.
![20181008_165005](https://user-images.githubusercontent.com/25665586/46599797-d51f8100-cb1a-11e8-9942-d16de544d266.gif)

When I type the second phonetic symbol. 
The log 'resizeSearch' that I put in 'Search.prototype.resizeSearch' function be trigger two times.

**Comment by LukeTowers** [comment]
@Hao1995 so are you able to create a PR to fix the issue?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
