### ISSUE TITLE
Model fields defined as "type: number" should be rendered as <input type="number">

### ISSUE THREAD

**Issue by immersiontravis** [octobercms/october#3836]
##### Expected behavior
When a field is defined in a model's fields.yaml as `type: number`, the rendered form control should be `<input type="number">`.

##### Actual behavior
The form control is rendered as `<input type="text" pattern="-?\d+(\.\d+)?">`. On mobile devices, users are presented with the alphanumeric keyboard, rather than a numeric keyboard. On any device, the "pattern" attribute is ignored by the browser – end users can enter illegal characters such as $ or ,. If the value is being saved to a numeric database column, and the value contains illegal characters (_e.g._, "$203,000"), then the database may coerce the value to 0.

##### Reproduce steps
Create a new plugin model. In the model's migration file, add a numeric column – _e.g._, `$table->unsignedInteger('price');` – and run the migration. In the model's `field.yaml` file, add a `price` field with the property `type: number`. Navigate to the model in the October backend, and click the button to create a new instance. Note that the "Price" field accepts illegal characters. Note that if you enter an illegal value such as "$203,000" and save the model, the `price` column in the database has a value of 0.

##### October build
443

**Comment by LukeTowers** [comment]
This is a duplicate of #2311. We've been back and forth on this for a while, but the main issue preventing this from happening is that apparently type=number forces it to be a whole number, no decimals allowed: https://github.com/octobercms/october/commit/c836d92f9f04f66f8e0e1b4d9ba8af83fed3e439

**Comment by immersiontravis** [comment]
Sorry for the dupe – I should've searched harder. Will put any further comments in #2311.

**Comment by LukeTowers** [comment]
No problem, it's kind of hard to find with your search query

**Comment by w20k** [comment]
Why not @LukeTowers? Html5 supports double value (http://w3c.github.io/html-reference/input.number.html#input.number.attrs.step.float). You have to specify step option in html or just make it as any.
```
<input type="number" step="0.01"> //or smaller, if needed or 'any'
//Unsigned 
<input type="number" step="any" min="0">
```

**Comment by LukeTowers** [comment]
@w20k does step any still make it have that scrollable buttons feature?

**Comment by LukeTowers** [comment]
Also does it support negative values?

**Comment by immersiontravis** [comment]
It supports negative values. The spinner buttons can be hidden with CSS (although I believe it requires vendor prefixes for some browsers).

**Comment by w20k** [comment]
@LukeTowers, it does, just by removing min attr..

```
<input type="number" step="any"> 
```

To remove the Spinner, this CSS rule should be used:
```
input[type=number]::-webkit-inner-spin-button, 
input[type=number]::-webkit-outer-spin-button { 
  -webkit-appearance: none; 
  margin: 0; 
}
```

**Comment by LukeTowers** [comment]
If someone would submit a PR (along with a PR in the test plugin for me to verify that it works) I'd accept it.

**Comment by w20k** [comment]
If @immersiontravis won't have time to deal with it, I hope to make it happen on weekends ;)

**Comment by immersiontravis** [comment]
Unfortunately, I don't yet know October well enough to feel comfortable submitting PRs...

**Comment by w20k** [comment]
Could someone open this ticket? :)

**Comment by LukeTowers** [comment]
@immersiontravis just give it a try! I'm not going to yell at you if you get it wrong at all, I'll just let you know what needs changing and how to do that :) This is a relatively easy one to get started with :)

**Comment by w20k** [comment]
@immersiontravis , I could try, I or @LukeTowers would help you with this PR ;) Should be fairly simple!
