### ISSUE TITLE
Cloudflare issue after updating to latest octobercms 443 build.

### ISSUE THREAD

**Issue by zakir1929** [octobercms/october#3839]
I updated my octobercms from 437 to 443 build.
and now the header menu is not showing up in the way it was showing before and flash messages for add/edit/delete of any record is not showing up in backend only.

##### Expected behavior
![image](https://user-images.githubusercontent.com/16069667/46395039-abc0b880-c708-11e8-8062-8087b5b130fb.png)

##### Actual behavior
![image](https://user-images.githubusercontent.com/16069667/46395077-cabf4a80-c708-11e8-9b2f-64e2a082d5df.png)

and in browser console I can see this
![image](https://user-images.githubusercontent.com/16069667/46395101-e4f92880-c708-11e8-92fc-0d40d85d2683.png)

##### Reproduce steps
just update to latest 443 build and have cloudflare installed on it.

##### October build
443

**Comment by LukeTowers** [comment]
Turn off CloudFlare performance settings on your backend: https://github.com/octobercms/october/issues/3602#issuecomment-399692351

**Comment by LukeTowers** [comment]
Actually, I'll try adding onto https://github.com/octobercms/october/commit/f068b13851150c6d12f4f2949497e21b980b7f15

**Comment by LukeTowers** [comment]
@zakir1929 https://github.com/octobercms/october/commit/29541394a3fc773f498c2d6c142302ca2cb927d2 should fix it in theory.

**Comment by zakir1929** [comment]
Thankyou @LukeTowers  this problem has been solved :) .

but there is a new problem now. 
The editor in whole website is not showing up
![image](https://user-images.githubusercontent.com/16069667/46490029-80cb8700-c824-11e8-8a35-fc63c3c90d28.png)

**Comment by LukeTowers** [comment]
@zakir1929 it sounds like CloudFlare just isn't playing nice. I would recommend you just disable the performance on the entire backend now.

**Comment by LukeTowers** [comment]
@zakir1929 we will use https://github.com/heathdutton/cloudflare/pull/4 & https://github.com/octobercms/october/commit/e246427463ac5edcc6b7115b33838a4367a4f9a9 to fix this issue going forward.
