### ISSUE TITLE
Mailgun driver support EU region

### ISSUE THREAD

**Issue by Wachem** [octobercms/october#3846]
##### Expected behavior
Chose your region in the mail (Mailgun) setup (US/EU).

##### Actual behavior
October only calls the US API endpoint instead of the (new) EU API endpoint.

##### Reproduce steps
Use a Mailgun domain in EU region with following API endpoint: https://api.eu.mailgun.net/v3/*

##### October build
443

**Comment by LukeTowers** [comment]
@Wachem feel free to make a PR to add support for this.

**Comment by Wachem** [comment]
> @Wachem feel free to make a PR to add support for this.

I'll look into this soon ;-)

**Comment by Tune389** [comment]
Workaround until fix -> https://github.com/WildSideUK/Laravel-MailgunEu

**Comment by CptMeatball** [comment]
Where's the file located that calls the API? Inside the core or in 'october.drivers'?

**Comment by Wankishh** [comment]
In services.php mailgun just add new entry endpoint => api.eu.mailgun.net

**Comment by LukeTowers** [comment]
@Wankishh that won't work because October uses Laravel 5.5 so the changes I linked are not present in the version of Laravel that we use.

**Comment by DieterHolvoet** [comment]
Any update on this issue? Is the only solution to update laravel/framework, or is there any OctoberCMS specific development to be done?

**Comment by DieterHolvoet** [comment]
Looks like they decided to backport this feature to 5.5, I can confirm this is working correctly using v5.5.45 of laravel/framework.

**Comment by LukeTowers** [comment]
@DieterHolvoet could you submit a PR to the config to document how to enable EU region? Leave it set to the default north america region though.

**Comment by w20k** [comment]
@LukeTowers endpoint was added as a third parameter, so you could change URL.

![screenshot 2019-02-18 at 11 07 18](https://user-images.githubusercontent.com/1053320/52939643-5f9bab00-336d-11e9-961d-8ec38d3595c1.png)

**Comment by LukeTowers** [comment]
Great, just want an example added to the config file so people don't get confused. Basically exactly like https://github.com/laravel/laravel/blob/master/config/services.php#L20 but perhaps with a link to the endpoint docs. Also, that key will need to be added to the `october:env` command.

**Comment by w20k** [comment]
@LukeTowers sure thing, will do it tomorrow, or today ;)

**Comment by w20k** [comment]
What do you think @LukeTowers if `october:env` will generate additional env values, based on the `MAIL_DRIVER` selected?
Example: 
If `MAIL_DRIVER` == mailgun, then add 'MAILGUN_DOMAIN', 'MAILGUN_SECRET', 'MAILGUN_ENDPOINT'

**Comment by LukeTowers** [comment]
@w20k I think you can just always include those regardless of driver selected.

**Comment by LukeTowers** [comment]
Completed in https://github.com/octobercms/october/commit/64d02b77cc973aab437ef70c822527e404b2d224

**Comment by Tetraneon** [comment]
Hi !
Documentation should be updated : https://octobercms.com/docs/services/mail where : 
```
'mailgun' => [
    'domain' => 'your-mailgun-domain',
    'secret' => 'your-mailgun-key',
],
```

would be : 
```
'mailgun' => [
    'domain' => '',
    'secret' => '',
    'endpoint' => 'api.mailgun.net', // api.eu.mailgun.net for EU
],
```

**Comment by bennothommo** [comment]
@Tetraneon Please feel free to submit a PR to the [docs](https://github.com/octobercms/docs) repository.

**Comment by Tetraneon** [comment]
@bennothommo 👍 You're right ! I learn everyday !
It has just been done !

**Comment by bennothommo** [comment]
Nice one @Tetraneon!
