### ISSUE TITLE
Improve Tab UX for large numbers of tabs and smaller screen sizes

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3856]
Using the code from this webpage: https://octobercms.com/docs/ui/tab

I will show the following screenshots and errors:

## Master tabs

![1](https://user-images.githubusercontent.com/17784082/46809999-a5b18400-cd67-11e8-90ea-e2bb50977280.png)

The CSS is NOT broken, however the User Experience seems rather poor to scroll the tabs.

## Primary tabs

![2](https://user-images.githubusercontent.com/17784082/46810182-fcb75900-cd67-11e8-8893-894eddfdb9d1.png)

The CSS is BROKEN (See the border-bottom CSS is not working correctly), also the User Experience seems rather poor to scroll the tabs.

## Secondary tabs

![3](https://user-images.githubusercontent.com/17784082/46810370-70f1fc80-cd68-11e8-8b15-cc5c53cb1a16.png)

The CSS is NOT broken (although I am not a fan of having the text up against the column), however the User Experience seems rather poor to scroll the tabs.

## Content tabs

![4](https://user-images.githubusercontent.com/17784082/46810543-d0e8a300-cd68-11e8-8811-a2ac66f7e23b.png)

The CSS is BROKEN (See the border-bottom CSS is not working correctly), also the User Experience seems rather poor to scroll the tabs.

### Conclusion

The Primary and Content Tabs have broken CSS.

All the Tab Designs seem to have poor UX.

Could we not have a proper tab solution something like this: https://codyhouse.co/demo/responsive-tabbed-navigation/index.html

## Desktop Version:

![5](https://user-images.githubusercontent.com/17784082/46810738-3e94cf00-cd69-11e8-8615-4aa477757ca6.png)

## Tablet Version

![6](https://user-images.githubusercontent.com/17784082/46810754-46547380-cd69-11e8-8631-c82779776316.png)

## Phablet Version

![7](https://user-images.githubusercontent.com/17784082/46810766-4d7b8180-cd69-11e8-806e-6818cc03b396.png)

## Mobile Version

![8](https://user-images.githubusercontent.com/17784082/46810781-54a28f80-cd69-11e8-88ce-06e551edbb74.png)

**Comment by LukeTowers** [comment]
@ayumihamsaki I like the suggestion. Submit a PR and I would be happy to review it.

**Comment by ayumihamsaki** [comment]
@LukeTowers 

Have finished coding something for you to check out, I have tested it inside October CMS as well, so here are some screenshots:

## Desktop Version

![1](https://user-images.githubusercontent.com/17784082/46824718-aa872f80-cd89-11e8-9bef-451cb35a925d.png)

## Tablet Version

![2](https://user-images.githubusercontent.com/17784082/46824727-b1ae3d80-cd89-11e8-84d0-5284c30ab4c3.png)

## Mobile Version

![3](https://user-images.githubusercontent.com/17784082/46824740-b8d54b80-cd89-11e8-9f80-9563598833e5.png)

## Code Location

I have uploaded the code to a github found here: https://github.com/ayumihamsaki/octobercms-tabs

The code will show the same example structures found in the October CMS Documentation notes found here: https://octobercms.com/docs/ui/tab

I thought instead of changing the tabs, it might just be a good idea to add this new tabbing system to the existing tabs for users to choose. That way it won't change their existing code setup's.

Let me know your thoughts and we can go from there.

**Comment by ayumihamsaki** [comment]
# Code Examples for Documentation

I have used the exact same code as October's Tabs the only real difference is using the `**responsive-tabs**`

## Normal Code Example

```
<div class="control-tabs responsive-tabs" data-control="tab">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#contentTabOne">One</a></li>
        <li><a href="#contentTabTwo">Two</a></li>
        <li><a href="#contentTabThree">Three</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active">
            Tab one content
        </div>
        <div class="tab-pane">
            Tab two content
        </div>
        <div class="tab-pane">
            Tab three content
        </div>
    </div>
</div>
```

## October Icon Example

```
<div class="control-tabs responsive-tabs" data-control="tab">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#contentTabOne"><i class="icon-camera-retro"></i><br>One</a></li>
        <li><a href="#contentTabTwo"><i class="icon-diamond"></i><br>Two</a></li>
        <li><a href="#contentTabThree"><i class="icon-crosshairs"></i><br>Three</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active">
            Tab one content
        </div>
        <div class="tab-pane">
            Tab two content
        </div>
        <div class="tab-pane">
            Tab three content
        </div>
    </div>
</div>
```

PR to come will just be CSS and LESS Code only I have used October's already installed Javascript Tab Extension.

**Comment by ayumihamsaki** [comment]
# Code Examples for Documentation

I have used the exact same code as October's Tabs the only real difference is using the `**responsive-tabs**` class attribute:

## Normal Code Example

```
<div class="control-tabs responsive-tabs" data-control="tab">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#contentTabOne">One</a></li>
        <li><a href="#contentTabTwo">Two</a></li>
        <li><a href="#contentTabThree">Three</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active">
            Tab one content
        </div>
        <div class="tab-pane">
            Tab two content
        </div>
        <div class="tab-pane">
            Tab three content
        </div>
    </div>
</div>
```

## October Icon Example

```
<div class="control-tabs responsive-tabs" data-control="tab">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#contentTabOne"><i class="icon-camera-retro"></i><br>One</a></li>
        <li><a href="#contentTabTwo"><i class="icon-diamond"></i><br>Two</a></li>
        <li><a href="#contentTabThree"><i class="icon-crosshairs"></i><br>Three</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active">
            Tab one content
        </div>
        <div class="tab-pane">
            Tab two content
        </div>
        <div class="tab-pane">
            Tab three content
        </div>
    </div>
</div>
```

PR to come will just be CSS and LESS Code only I have used October's already installed Javascript Tab Extension.

**Comment by ayumihamsaki** [comment]
# Code Examples for Documentation

I have used the exact same code as October's Tabs the only real difference is using the `**responsive-tabs**` class attribute, which _I have just created_:

## Normal Code Example

```
<div class="control-tabs responsive-tabs" data-control="tab">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#contentTabOne">One</a></li>
        <li><a href="#contentTabTwo">Two</a></li>
        <li><a href="#contentTabThree">Three</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active">
            Tab one content
        </div>
        <div class="tab-pane">
            Tab two content
        </div>
        <div class="tab-pane">
            Tab three content
        </div>
    </div>
</div>
```

## October Icon Example

```
<div class="control-tabs responsive-tabs" data-control="tab">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#contentTabOne"><i class="icon-camera-retro"></i><br>One</a></li>
        <li><a href="#contentTabTwo"><i class="icon-diamond"></i><br>Two</a></li>
        <li><a href="#contentTabThree"><i class="icon-crosshairs"></i><br>Three</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active">
            Tab one content
        </div>
        <div class="tab-pane">
            Tab two content
        </div>
        <div class="tab-pane">
            Tab three content
        </div>
    </div>
</div>
```

Screenshot of the two code snippets will look like this in October CMS:

![1](https://user-images.githubusercontent.com/17784082/46839008-67d64f00-cdab-11e8-998d-9afbebec5ad1.png)

PR to come will just be CSS and LESS Code only I have used October's already installed Javascript Tab Extension.

**Comment by amdad** [comment]
Did you just replace amazing styled tabs for this 'red ones'? You should rather fix responsiveness of original ones than totally throw them away.

**Comment by amdad** [comment]
Alright, so if it will be as additional style of tabs then very welcome!  

How to use them directly from yaml?

**Comment by LukeTowers** [comment]
@ayumihamsaki could you please update the CSS to make it look more like it belongs in October? The red and pale yellow don't work well with the default styling. Also, there is currently no support for tab icons in October, so how do you plan on implementing that?

**Comment by ayumihamsaki** [comment]
@LukeTowers sure I will try and update the colors to make it more inline with the rest of the OctoberCMS other Tabs (sorry about that).

> Also, there is currently no support for tab icons in October, so how do you plan on implementing that?

Actually I ran several tests and all were successful use October's defalut icons and Font Awesome icons, the above screenshots I used Font Awesome 5.4.1 

Taken from the Doc Notes found here: https://octobercms.com/docs/ui/icon

It says the following:

> Inline icons
> Place icons just about anywhere with the <i> tag or to an existing element using the oc- prefix.
> 
> <i class="icon-camera-retro"></i> icon-camera-retro

So I just did that with the Tabs, what's your thoughts on that?

p.s. Will try to update that PR in the next 24 hours.

**Comment by ayumihamsaki** [comment]
@LukeTowers sure I will try and update the colors to make it more inline with the rest of the OctoberCMS other Tabs (sorry about that).

> Also, there is currently no support for tab icons in October, so how do you plan on implementing that?

Actually I ran several tests and all were successful used October's defalut icons and Font Awesome icons, the above screenshots I used Font Awesome 5.4.1 

Taken from the Doc Notes found here: https://octobercms.com/docs/ui/icon

It says the following:

> Inline icons
> Place icons just about anywhere with the `<i>` tag or to an existing element using the oc- prefix.
> 
> `<i class="icon-camera-retro"></i>` icon-camera-retro

So I just did that with the Tabs, what's your thoughts on that?

p.s. Will try to update that PR in the next 24 hours.

**Comment by ayumihamsaki** [comment]
@LukeTowers Please QC this and say if ok or not before I update the PR - see screenshot:

![tabs-colour](https://user-images.githubusercontent.com/17784082/47037886-a4b99180-d16f-11e8-803c-3a61e76f2175.png)

**Comment by LukeTowers** [comment]
Hover can be the same as active, there's a weird extra top border on the active one, and I don't think the fonts should be bold.

What I meant about the tab icons is how do you plan on defining them in the form fields YAML?

**Comment by ayumihamsaki** [comment]
As per Luke spec updated screenshot of new PR is this for future ref:

![1](https://user-images.githubusercontent.com/17784082/47050021-7bf4c480-d18e-11e8-9435-588ca22e5272.png)

> What I meant about the tab icons is how do you plan on defining them in the form fields YAML?

I think you are talking about this: https://octobercms.com/docs/backend/forms#form-tab-options

To be honest, I coded it in flexbox so it is clever enough to re-size with and without icons (you dont need to add any extra code). So my answer is, I dont think you need to add any extra tab/yaml for the icons to work (in this tab code). Maybe with the other tab designs as they dont use any modern css.

**Comment by ayumihamsaki** [comment]
As per Luke spec updated screenshot of new PR is this for future ref:

![1](https://user-images.githubusercontent.com/17784082/47050021-7bf4c480-d18e-11e8-9435-588ca22e5272.png)

> What I meant about the tab icons is how do you plan on defining them in the form fields YAML?

I think you are talking about this: https://octobercms.com/docs/backend/forms#form-tab-options

To be honest, I coded it in flexbox so it is clever enough to re-size with and without icons (you dont need to add any extra code). So my answer is, I dont think you need to add any extra tab/yaml for the icons to work (in this tab code). Maybe with the other tab designs as they dont use any modern css.

**Comment by LukeTowers** [comment]
@ayumihamsaki so you would need to add another option under that heading that would work like this:
```yaml
tabs:
     icons:
         0: icon-globe
```

**Comment by LukeTowers** [comment]
@ayumihamsaki you'll also have to actually implement it in this PR as well

**Comment by ayumihamsaki** [comment]
@LukeTowers Sorry still dont fully understand, so not sure what to code exctaly logic wise.

**Comment by ayumihamsaki** [comment]
@LukeTowers Sorry still dont fully understand, so not sure what to code excatly logic wise.

**Comment by ayumihamsaki** [comment]
@LukeTowers Any reason this is still open as the PR's have been merged already?
