### ISSUE TITLE
The attributes and containerAttributes field options don't work

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#3858]
##### Actual behavior
The given values don't show in the source code.

##### Reproduce steps
Extend any text fields with "attributes" or "containerAttributes" option.

##### October build
443

**Comment by LukeTowers** [comment]
@gergo85 what field types do they not work on? Please submit a PR to the [test plugin](https://github.com/octoberrain/test-plugin) that demonstrates the issue.

**Comment by gergo85** [comment]
I tried text fields. Alright, I added a PR to the test plugin.

**Comment by gergo85** [comment]
@LukeTowers Is it right PR for test plugin?

**Comment by LukeTowers** [comment]
@gergo85 yes, just haven't looked at it yet. Why did you close this?

**Comment by gergo85** [comment]
It is a false report, sorry.
