### ISSUE TITLE
Do you like October? Vote your favorite CMS!

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#3861]
The CMS Critic Awards started and the voting has begun:  
https://www.cmscritic.com/awards/  
Now the October is third, but I hope it will be the first :)

OpenSourceCMS website user rating:  
https://www.opensourcecms.com/october/

**Comment by LukeTowers** [comment]
@gergo85 that's disappointing that they've labelled OctoberCMS as a flat file CMS. I've sent them a message to see if they'll change the category

**Comment by gergo85** [comment]
@LukeTowers I agree with you.

**Comment by gergo85** [comment]
The new homepage of the official site looks good 👍
