### ISSUE TITLE
Middleware after first request of a session unable to put session values

### ISSUE THREAD

**Issue by reed-josh** [octobercms/october#3862]
##### Expected behavior
If you try to "put" or change session data in a middleware it should update the session, and it should work this way on every request not just the first.

##### Actual behavior
Currently it appears if you set session data in the middleware it will work the first time the code is run, but running the same code again subsequent times in the same session the middleware's alterations of the session will not persist. (been testing with file as the cache driver, though this happening on our server with redis too.)

##### Reproduce steps
I've been trying to create a middleware in a plugin in October CMS, that takes from the input a value and stores it in session to be periodically displayed in a template.

Middleware function:

      public function handle($request, Closure $next)
      {
          session()->put('foo', input('foo'));
          logger('StartSession: foo: ', [session('foo')]);
          return $next($request);
      }

Registering middleware in plugin.php

        public function register()
        {
        $this->app->make('Illuminate\Contracts\Http\Kernel')->prependMiddleware('October\Demo\Middleware\StartSession');
        }

Method in plugin for accessing session

        public function registerMarkupTags()
        {
           return [
               'functions' => [
                   'session' => [Session::class, 'get']
                ]
           ];
        }

Usage in demo theme

    <h1>{{ session('foo') }}</h1>

This works on the first run. If I put foo as query string foo is displayed on the page. However on a second run if I changed the query string to bar, foo persists on the page.

Here is an example of the issue in a fresh installed October Instance

[https://github.com/reed-josh/october-session-issue][1]

  [1]: https://github.com/reed-josh/october-session-issue

##### October build
v1.0.443

**Comment by LukeTowers** [comment]
@w20k do you want to look into this?

**Comment by w20k** [comment]
@LukeTowers , sounds fun, will take a look, but after weekends, I guess ;) Father is celebrating his jubilee (60th birth anniversary).

**Comment by w20k** [comment]
@reed-josh , could check if explicitly calling '\Session::save()', would help :)

**Comment by w20k** [comment]
The question cleared, if you want to use session, you have to process request first, and then your session object will be accessible.

```
public function handle($request, Closure $next)
    {

        // first you process the request and save the response, so your controller is
        // executed before the middleware and the session i populated
        $response = $next($request);

        // now you can access the values shared on this very request
        $store = session();
        $value = input('foo');
        $var   = $store->get('foo');
        $store->put('foo', $value);
        logger('StartSession: foo: ', [session('foo')]);

        return $response; // don't forget to return the response to the user
    }
```

**Comment by LukeTowers** [comment]
@reed-josh does @w20k's answer help?

**Comment by reed-josh** [comment]
So in a fresh install of Laravel 5.7 I am able to create the behavior that I want.

Middleware

    public function handle($request, Closure $next, $guard = null)
    {
        session()->put('foo', request()->get('foo'));
        $response = $next($request);
        return $response;
    }

and in the welcome.blade.php file

            <div class="title m-b-md">
                    Laravel!
                    <?php dd(session()->get('foo')) ?>
                </div>

That is consistently returning input value of foo as expected.

Upon some experimentation it does work this way in October CMS as well if I dump the session before the twig template. Like dumping and exiting the script in the OnStart() function for example.

**Comment by w20k** [comment]
@reed-josh Might take a while, need to test this behaviour with Laravel also. Or if you could help me out, and post your code on github? :) Would be perfect!

**Comment by reed-josh** [comment]
Hey, sorry I haven't been on for a few days. Yes, I would be happy to post it tomorrow, left the code on my work computer.

**Comment by reed-josh** [comment]
Hey, sorry this took me so long. Crazy week.

Here is the example of it working I described

https://github.com/reed-josh/laravel-session-example

**Comment by w20k** [comment]
@reed-josh , thanks a lot!

**Comment by reed-josh** [comment]
@w20k no problem. Is that enough for you to pinpoint the issue?

**Comment by LukeTowers** [comment]
@reed-josh is this still an issue?
