### ISSUE TITLE
Why there are no beforeLogout/afterLogout methods and events?

### ISSUE THREAD

**Issue by kerbylav** [octobercms/october#3864]
Is there any special reason for this? It could be useful to perform some "cleanups" before or after actual logout of user. Especially in case of an backend user.

**Comment by LukeTowers** [comment]
@kerbylav please post an example of how you would use such events. Also there are some events that you can hook into that would achieve similar results, see https://github.com/luketowers/oc-pwnedpasswords-plugin#force-existing-users-to-reset-their-passwords

**Comment by kerbylav** [comment]
Well, for example, when some backend user logs out, I need to stop any possible impersonation he was doing. And now I do something dirty, intercepting backend route of signing out to make it possible. 

But it is just wrong, because of number of reasons, including there is no way to intercept \BackendAuth::logout()

**Comment by LukeTowers** [comment]
@kerbylav feel free to add the necessary PRs to the library repo and the backend user model following the existing naming conventions.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by briddle** [comment]
This works (tested):

```
(...)

use Backend\Controllers\Auth;
class Plugin extends PluginBase
{
    public $elevated = true;// important 
    public function boot()
    { 
        Auth::extend(function ($controller) {
            $controller->bindEvent('page.beforeDisplay', function ($action, $params) use ($controller) {
                if ($action === 'signout') { 
                    Log::info('signing out...');
                }
            });
        });
    }

(...)
```
