### ISSUE TITLE
getSaveValue() after saving model

### ISSUE THREAD

**Issue by Cryden** [octobercms/october#3871]
How to make the formwidget save the data only after the model is saved?

**Comment by LukeTowers** [comment]
How to make the rain fall only after the ground is wet?

**Comment by Cryden** [comment]
How to call a function in formwidget after saving model data?

**Comment by w20k** [comment]
@Cryden, start from reading documentation first: https://octobercms.com/docs/database/model#events

**Comment by Cryden** [comment]
i can use in formWidget this code?
```
public function init()
{
    Event::listen('model.afterSave', function() {
        // My function code run after Save model
    });
}
```

**Comment by LukeTowers** [comment]
@cryden you could, but it would be better to target the specific model being touched by the form. Try something like this:
```php
public function init()
{
    $this->model->bindEvent('model.afterSave', function () use ($model) {
        // your custom code here
    });
}
```

**Comment by Cryden** [comment]
Thanks!
