### ISSUE TITLE
Update server throws 500 "Trying to get property of non-object" response if project has been deleted.

### ISSUE THREAD

**Issue by zmsaunders** [octobercms/october#3873]
##### Expected behavior
Update server should return response indicating that the project supplied does not exist, or allow update to proceed with non-purchased plugins.

##### Actual behavior
Update server returns 500 response with body of "Trying to get Property of Nonobject" when project supplied in payload has been deleted from https://octobercms.com/account/project/dashboard.

##### Reproduce steps
1) Login to https://octobercms.com/account/project/dashboard
2) Create project
3) Attach server to project
4) Delete project
5) Attempt to run update

For reference, here is an ID for a project that has been deleted: `0ZwN2AGLgZGt4ZwRjYGEyBGZ3MJZjMQR4ZGZ5A2Z4BJAxBQEzZzHlZGxjAJEz`

And here is an example of a curl request that returns the error:

```bash
curl --request POST \
  --url http://gateway.octobercms.com/api/core/update \
  --form core=6c3e226b4d4795d518ab341b0824ec29 \
  --form build=443 \
  --form force=false \
  --form server=YToyOntzOjM6InBocCI7ZDo3LjI7czozOiJ1cmwiO3M6MToiLyI7fQ== \
  --form project=0ZwN2AGLgZGt4ZwRjYGEyBGZ3MJZjMQR4ZGZ5A2Z4BJAxBQEzZzHlZGxjAJEz \
  --form 'plugins=a:0:{}'
```

Omitting the  `--form project=...` param will result in a successful post response.

##### October build
443

**Comment by Samuell1** [comment]
@zmsaunders is this still issue?

**Comment by daftspunk** [comment]
I've traced the source of this issue and confirmed it will no longer occur in the new website update we've got coming out soon. If it still happens, just ping me and we can reopen and investigate. Thanks for the report 🙏
