### ISSUE TITLE
Why "Lang::hasForLocale()" method does not exist in OctoberCMS?

### ISSUE THREAD

**Issue by iboved** [octobercms/october#3875]
##### Expected behavior
I want to check if a key is localized in a certain language. There is a `Lang::has()` method which always returns `true`, because it always fallback to the default locale. This issue is fully described [here](https://github.com/laravel/framework/issues/10718). Here is the [Pull request](https://github.com/laravel/framework/pull/10767) where Laravel developers added a new method `Lang::hasForLocale()` to fix this problem. Note, this method was added to Laravel 5.1. Stable OctoberCMS uses Laravel 5.5 at the moment . Why this method does not exist in OctoberCMS? As I understood, when we call `Lang::` facade it returns `October\Rain\Translation\Translator` instance, not Laravel `Illuminate\Translation\Translator`. And for some reason `October\Rain\Translation\Translator` still don't have `hasForLocale()` method. How can I use Laravel `Illuminate\Translation\Translator` and when `hasForLocale()` will be added to OctoberCMS?

##### Actual behavior
When I call the `\Lang::hasForLocale('acme.demo::lang.locations.airport', 'en')` method, I get an error `Call to undefined method October\Rain\Translation\Translator::hasForLocale()`.

##### Reproduce steps
Call the `\Lang::hasForLocale('acme.demo::lang.locations.airport', 'en')` method somewhere in your code.

##### October build
October build: 442

**Comment by Teranode** [comment]
There are also other methods that aren't implemented. Seems like there's a bunch of things that arent added core-wise because they're custom implementations of their contracts. So this is more than just translations.

**Comment by LukeTowers** [comment]
@iboved if you want to see it added feel free to make a PR
