### ISSUE TITLE
Dropdown causing `substr() expects parameter 1 to be string, array given` in RelationController form

### ISSUE THREAD

**Issue by LarBearrr** [octobercms/october#3876]
##### Expected behavior
Display a dropdown of Locale options (similar to `/backend/backend/preferences`) in a form used by the RelationController with a hasOne/belongsTo relationship.

Note: The field is part of a JSONable property.

##### Actual behavior
When selecting the record with the RelationController `Link` button, it throws:
`substr() expects parameter 1 to be string, array given` which is coming from:
https://github.com/octobercms/october/blob/master/modules/backend/widgets/form/partials/_field_dropdown.htm#L8

##### Reproduce steps
1. Create a new "Brand" model with a Locale dropdown:
```
# ===================================
#  Form Field Definitions
# ===================================
        value[locale]:
            tab: 'backend::lang.branding.brand'
            label: 'backend::lang.backend_preferences.locale'
            comment: 'backend::lang.backend_preferences.locale_comment'
            type: dropdown
            options: getLocaleOptions
            span: left
```
and copy the `getLocaleOptions()` method from [Backend\Models\Preference](https://github.com/octobercms/october/blob/edcc4af68aa70dc4b84b687e34edb90d14191ca0/modules/backend/models/Preference.php#L178) then define `public $belongsTo = [Backend\Models\UserGroup::class];`

2. Extend the Backend UserGroup model and controller:
```
\Backend\Models\UserGroup::extend(function ($model) {
            $model->hasOne['brand'] = [
                'Author\Plugins\Models\GroupSetting',
                'table' => 'group_settings',
            ];
        });

        \Backend\Controllers\UserGroups::extend(function($controller) {

            // Implement behavior if not already implemented
            if (!$controller->isClassExtendedWith('Backend.Behaviors.RelationController')) {
                $controller->implement[] = 'Backend.Behaviors.RelationController';
            }
        
            // Define property if not already defined
            if (!isset($controller->relationConfig)) {
                $controller->addDynamicProperty('relationConfig');
            }
    
            // Splice in configuration safely
            $myConfigPath = '$/author/plugin/controllers/usergroups/config_relation.yaml';
        
            $controller->relationConfig = $controller->mergeConfig(
                $controller->relationConfig,
                $myConfigPath
            );
        
        });

        Event::listen('backend.form.extendFields', function ($form) {
            if (!$form->model instanceof \Backend\Models\UserGroup) {
                return;
            }

            $form->addTabFields([
                'brand' => [
                    'tab' => 'Settings',
                    'label' => 'Brand',
                    'type' => 'partial',
                    'path' => '$/author/plugin/models/usergroups/_brand_field.htm'
                ]
            ]);
        });
```
3. Setup the config_relation.yaml and _brand_field.htm files:
```
# ===================================
#  Relation Behavior Config
# ===================================

brand:
    label: Brand
    view:
        form: $/author/plugin/models/groupsetting/fields.yaml
        toolbarButtons: create|link|unlink
    manage:
        form: $/author/plugin/models/groupsetting/fields.yaml
        list: $/author/plugin/models/groupsetting/columns.yaml
```
```
_brand_field.htm
<?= $this->relationRender('brand') ?>
```

4. Create a new "Brand" and select any language.
5. Create a new Backend UserGroup (/backend/backend/usergroups/create) and link the new Brand to the new group.
6. Click `Create` and notice the Exception: `substr() expects parameter 1 to be string, array given`

##### October build
443

**Comment by LukeTowers** [comment]
@LarBearrr reason for close?

**Comment by LarBearrr** [comment]
@LukeTowers Just an old issue that I couldn't remember the problem, and it probably had something to do with my setup at the time. I can reopen but I won't have time to try to re-create the issue right now. Let me know what you'd like me to do.

**Comment by LukeTowers** [comment]
@LarBearrr we'll leave it closed then
