### ISSUE TITLE
Missing Inline Style plugin into froala editor

### ISSUE THREAD

**Issue by Ladylain** [octobercms/october#3883]
Hi,

I was trying to use `Inline Style` function inside Richeditor widget, and it didn't want to work. After many minutes searching, i've found that this plugin is missing from the froala editor js build. 

Is this normal ? could it be possible to add it to the next version ? 

thanks

**Comment by LukeTowers** [comment]
@daftspunk thoughts?

**Comment by w20k** [comment]
It's just outdate, we already had this issue in slack ;) Guess should be fixed by @ayumihamsaki major JS upgrade :)

**Comment by daftspunk** [comment]
The inline_* plugins have been included in the next build. It has no immediate effect on the UI but hopefully, this will introduce the functionality needed.

Should be available in Build 457+
