### ISSUE TITLE
RTL slug.

### ISSUE THREAD

**Issue by uwejan** [octobercms/october#3894]
Hello Guys, Thanks for the awesome CMS.
##### Expected behavior
I am new with October, i am trying to create a blog , where slug url is multilingual, while i try RTL slug it get translated to Latin characters, where i expexted to be the same as the title RTL like, Arabic, Persian characters . http:/site.com/موضوع-جديد

##### Actual behavior
http:/site.com/modoaa-gdyd

##### Reproduce steps
After some googling, i found a plugin called Persian, that did not work, it missed up the admin area, and slug is not fully supported to all alphabets.

##### October build
latest version.

**Comment by LukeTowers** [comment]
@uwejan slugs do not support non-latin characters, in the slug generation function itself it has character maps to map non-latin characters to latin characters.

**Comment by uwejan** [comment]
So. You basically saying there is no way have the slug on non Latin characters?

**Comment by LukeTowers** [comment]
@uwejan It's unexplored territory at least from October's view. You could probably implement it yourself if you tried hard enough but the reality is that unicode URLs are not well or widely supported in numerous applications so the character mapping is regarded as the best current solution.
