### ISSUE TITLE
filterFields function is not working when repeater field is used

### ISSUE THREAD

**Issue by mismaiti** [octobercms/october#3896]
i created a model  and trying to use filterFields() function to set field label dynamic base on username.
by doing this

```
public function filterFields($fields, $context = null)
{
    $nagers = WartaDataProfil::where('backend_users_id',$this->getBackendUserId())->pluck('nager');

    if(Str::startsWith($nagers[0],'GP')){            
                
        $fields->wil->label = "Sektor";

    }   
}  
```

but i got am exception

> **Creating default object from empty value**

from this line 

`$fields->wil->label = "Sektor";`

after hours trying find out what happen since i use the same function on other models with no issue.. 
i discover that if i remove all **repeater field** from the model.. everything works like a charm.. 
so how should we deal with this situation.. i still want to use repeater fields, is it a bug.. ?

**Comment by LukeTowers** [comment]
@mismaiti the repeater field includes nested Forms itself, so you actually need to use the model event instead to check the formwidget attempting to filter the fields: https://octobercms.com/docs/api/model/form/filterfields

Something like this:
```php
public function __constuct()
     parent::__construct(func_get_args()...);
     $this->bindEvent('model.form.filterFields', function ($formWidget, $fields, $context) {
          // Skip nested form widgets (i.e. repeaters)
          if ($formWidget->isNested) { return; }
          
          // do your field filtering here
     });
}
```

**Comment by mismaiti** [comment]
@LukeTowers where should we call this.. i try called from controller and boot() and nothing happened..

**Comment by LukeTowers** [comment]
@mismaiti you'd put that in the model class itself. Hence the `$this->bindEvent` since you're binding your listener to the specific model's `model.form.filterFields` event.
