### ISSUE TITLE
Let's make the world for a better place: OctoberCMS China Friendly Project

### ISSUE THREAD

**Issue by iamike** [octobercms/october#3899]
##### Expected behavior
More plugins are able to adapt China mainland internet environment.

##### Actual behavior
When foreign users are easily follow the document [finishing AWS S3 bucket integration](https://octobercms.com/docs/cms/mediamanager), those Chinese developers still can not find their familiar faces like Aliyun's OSS(Alibaba) or qCloud's COS(Tencent).
Although finally they'll find some solutions like this [plugin](https://octobercms.com/plugin/jc91715-oss). They are still both happy and disappointed. It seems the author has no time to maintain the buggy plugin. It has been almost 6 months, by so far, neither of any improvements nor a single response has been made from the author. I don't think that every developer is senior enough to customize these modules well.

Because of some reasons, China GFW blocks many great things for their developers, users, learners, and clients. OctoberCMS is also one of the victims. It is pity it can not perform so well as we expected it to be. It’s also pity we can not fully or directly demonstrated the OctoberCMS merits to the clients in China.

##### Reproduce steps
At OctoberCms plugin store, you may find there are lack of plugins support China internet’s environment.
Eg.
In China we don't using AWS S3, Rackspace, Dropbox... cloud storage services have been monopolised by 2 digital giants, Alibaba, Tencent.
And main reason for foreign developers can not get a China digital service provider account is this: it needs ICP, sorry, I digression.....

In China we don't using Paypal, we using Alipay and Wechat pay...
In China we won't share things by Facebook or Twitter, we using Wechat , QQ ...

##### October build
OctoberCMS build a better world! I know it, and now, it will also make China a better place to live.
On behave 5.79 millions web developers and 13 billion users. 
I am here request the community. Please help us. 
You can even make tutorial on how to deep customize filesystem, or make suggestion on how correctly integration Ping++/Beecloud(similar like stripe) into e-commence payment gateway...Whatever you do, I appreciated at here.
In return, I believe, with OctoberCMS more and more friendly in China, more and more developers will pay attention on this CMS, and I believe, finally they will join our party as well.

Okay, So can we start it by upgrade our filesystem driver plugin to support OSS and COS？
Once this step has been done, it means a giant leap for those small sites that still using local drive, now, they won't worried about the capacity issues any more. They will enjoy the cloud service and have the potentiality to grow big. Nothing can hamper them to focus on the things that related with their business. So let’s make this butterfly effect happen! Shall we?!

As a community member, I will provide basic infrastructures and API translation works for those who would like response to my advocate. 
I mean I have both Aliyun/qCloud account, and my company domain has legitimate ICP backup license in China.
I trusted every community members. As long as your purpose is developing  OctoberCMS..
I am readily to provide it to you. 
I am happy to take the risk and become the bridge.

Regards

**Comment by Teranode** [comment]
There's already this package (but like 26 issues on it):
https://github.com/jacobcyl/Aliyun-oss-storage

**Comment by iamike** [comment]
Exactly, they outdated and buggy. I suggest we start it by Tencent’s Qcloud. You may find they have better API docs.

**Comment by LukeTowers** [comment]
@iamike feel free to make a laravel filesystem driver yourself. I don't speak any Chinese and don't use those providers myself so I can't produce a driver for them. I can easily make laravel drivers work as OctoberCMS plugins, but as far as actually building / maintaining the specific driver itself, that's not within my realm.

**Comment by iamike** [comment]
Sure, this will be my today’s mission.

**Comment by Teranode** [comment]
I think the best course of action would be to fork your own copy and maintain it from there?
I would like to help but the language barrier is putting me at a disadvantage plus i would need to do testing with the action storage.

**Comment by iamike** [comment]
@Teranode can you give me an email account you usually using? 
Don't worry the about docs issues, I find Tencent has released a pretty well api docs recently,
and I can provide you an environment for you to test it.
https://intl.cloud.tencent.com/document/product/436/7751

**Comment by w20k** [comment]
@iamike Hook me up also ;)

**Comment by ayumihamsaki** [comment]
I'm not an expert but why use Tencent’s Qcloud ? 

Baidu Wangpan is free and has a huge 2 TB of Storage space and its easy for western and chinese people to register and create accounts.

1. Just go here to open a QQ Email: https://en.mail.qq.com/cgi-bin/loginpage

2. Then go here to open the free hosting: https://yun.baidu.com/

Following this issue, would love to see how to get around the China Great Firewall issue.

**Comment by ayumihamsaki** [comment]
I'm not an expert but why use Tencent’s Qcloud ? 

Baidu Wangpan is free and has a huge 2 TB of Storage space and its easy for western and chinese people to register and create accounts.

1. Just go here to open a QQ Email: https://en.mail.qq.com/cgi-bin/loginpage

2. Then go here to open the free storage: https://yun.baidu.com/

Following this issue, would love to see how to get around the China Great Firewall issue. I always thought people just used Hong Kong ISP's to get through the problem.

**Comment by tschallacka** [comment]
You could make a plugin with the working drivers and put it in the plugin store it like this plugin does for google drive.


https://github.com/LukeTowers/oc-gdrivefilesystemdriver-plugin/blob/master/Plugin.php

**Comment by w20k** [comment]
@beysong what CDNs are you looking for?

**Comment by LukeTowers** [comment]
@beysong then implement them.

**Comment by iamike** [comment]
@LukeTowers How can I publish plugin on plugin market?
I made one plugin, and it's work perfect at my website. the speed is good. both international and inside China.

**Comment by iamike** [comment]
Can we make a video on how to publish plugin on community?
