### ISSUE TITLE
Datepicker time positioning different to calendar

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#3903]
The position of the popup for the calendar positions itself for best fit in the viewport but the time popup is _always_ below the time field even if there isn't enough room. This creates an inconsistent experience for our users inputting dates.

**Comment by LukeTowers** [comment]
@SeriousKen pictures please

**Comment by SeriousKen** [comment]
The calendar uses autopositioning, looking at the code in Pikaday which is used for the calendar it uses its own popover code rather than bootstrap.

![calendar](https://user-images.githubusercontent.com/29771532/48052043-c28e7b00-e19e-11e8-85ae-778cb905d08e.jpg)

The timepicker uses the bootstrap popover always aligned to the bottom of the input.

![clock](https://user-images.githubusercontent.com/29771532/48052044-c28e7b00-e19e-11e8-9671-50e18ac39267.jpg)

**Comment by w20k** [comment]
Found the culprit: `placement: 'bottom',` it's by default set to be `bottom` ;)

**Comment by w20k** [comment]
Found a simple solution for now, needs more testing, but guess will work. 
Cheers ;)

**Comment by LukeTowers** [comment]
@SeriousKen @w20k implemented a fix, I've merged it into develop.
