### ISSUE TITLE
Disabled plugin's controllers are still accessible

### ISSUE THREAD

**Issue by alfreedom** [octobercms/october#3905]
##### Expected behavior
The controller pages of a disabled plugin should not be displayed in the backend with the url of the page

##### Actual behavior
If you enter a page of a plugin using your url, show the page, regardless of whether the plugin is disabled

##### Reproduce steps
1. Go to a backend controller page of a plugin.
2. Copy the page url.
3. Disable the plugin in the configuration panel
4. Open the copied url again, the page will be show

##### October build
None

**Comment by w20k** [comment]
@LukeTowers - confirmed.
Sidebar is removed, but with absolute URL it's accessible.

Settings:
![screenshot 2018-11-02 at 14 29 08](https://user-images.githubusercontent.com/1053320/47915516-c921a780-deab-11e8-9a36-9cc3d6f8d808.png)

Plugins Page:
![screenshot 2018-11-02 at 14 29 16](https://user-images.githubusercontent.com/1053320/47915511-c4f58a00-deab-11e8-9647-923a5f750c91.png)

**Comment by w20k** [comment]
@LukeTowers, I will already started debugging ;)

**Comment by w20k** [comment]
@LukeTowers, found the spot, but not yet sure about how plugins $id is generated (is it as simple as ucfirst($author) . '.' . ucfirst($plugin)? ).

It looks up for a plugin controller, but doesn't check if plugin is disabled or not.
https://github.com/octobercms/october/blob/master/modules/backend/classes/BackendController.php#L107

**Comment by LukeTowers** [comment]
@w20k you should be able to use this: https://github.com/octobercms/october/blob/master/modules/system/classes/PluginManager.php#L505

```php
PluginManager::instance()->isDisabled($author . '\\' . $plugin);
```

That could probably go right after the list(author, plugin) call to prevent the further code from running

**Comment by w20k** [comment]
@LukeTowers tried this way while testing. Didn't work. Namespace and pluginId should start with capitalized letter .

This worked like charm, will make a PR either today, or tomorrow.
```
if (!PluginManager::instance()->isDisabled(ucfirst($author) . '.' . ucfirst($plugin))){
....
}
```

**Comment by w20k** [comment]
Found one strange behaviour, looking at it right now.

**Comment by LukeTowers** [comment]
@w20k it should pass the request off to be handled by the CMS 404 page, or however a 404 in the backend typically works

**Comment by w20k** [comment]
Sorry for taking so looong ;) 

[PR Fix](https://github.com/octobercms/october/pull/3923)
