### ISSUE TITLE
Question: Why does October not have CSRF Protection on GET Requests?

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3907]
October has the Twig function:

```{{ form_open() }}```

When used as above it will automatically create a POST request, as below:

```
<form method="POST" action="https://www.example.com" accept-charset="UTF-8">
<input name="_session_key" type="hidden" value="K3UkRZSRAYwm9y6mnTjWSy7nengZVRKOwfPp9KwL">
<input name="_token" type="hidden" value="QAuPSBQGTILkcr1tHuSXgZySgfEKeZ6vXgPCTQrY">
```

To force the Twig Function to create a GET request I write the following:

```{{ form_open({ method: 'GET' }) }}```

The above code gives the following output:

```<form method="GET" action="https://www..example.com" accept-charset="UTF-8">```

Note the session key and token are now not displayed?

From doing some research it seems like Laravel 5 is doing this.

Is there a good reason why there is NO CSRF Protection on GET Requests?

I was king of expecting October's Twig function to produce this (without the need to create some middleware for it):

```
<form method="GET" action="https://www.example.com" accept-charset="UTF-8">
<input name="_session_key" type="hidden" value="K3UkRZSRAYwm9y6mnTjWSy7nengZVRKOwfPp9KwL">
<input name="_token" type="hidden" value="QAuPSBQGTILkcr1tHuSXgZySgfEKeZ6vXgPCTQrY">
```

**Comment by ayumihamsaki** [comment]
For ref: I'm using this doc's page: https://octobercms.com/docs/markup/function-form

**Comment by w20k** [comment]
@ayumihamsaki, The quickest answer would be: only requests that make state change to the system, should have a CSRF protection. GET is not the one.
If you need a protection from repetition use a page generated tokens (not build in, I guess).

**Comment by ayumihamsaki** [comment]
I see, makes sense now, thanks for reply.
