### ISSUE TITLE
CSS or JS only Combiner Aliases

### ISSUE THREAD

**Issue by CptMeatball** [octobercms/october#3909]
##### Expected behavior
Load Framework.Extras specific files only through an alias like `@framework.extras.css` or `@framework.extras.js`.

##### Actual behavior
Framework.Extras CSS can only be loaded when there is another stylesheet present in the Combiner. With JS files this does not cause issues because it defaults to JS files.

##### Reproduce steps
Use `@framework.extras` alias in empty stylesheet combiner.

    <link rel="stylesheet" href="{{ ['@framework.extras'] | theme}}">

##### October build
443

**Comment by w20k** [comment]
A file to look at and line: https://github.com/octobercms/october/blob/master/modules/system/classes/CombineAssets.php#L134
