### ISSUE TITLE
Myanmar / Burma flag is incorrect

### ISSUE THREAD

**Issue by joseph-d** [octobercms/october#3911]
##### Expected behavior

Using `<i class="flag-mm"></i>` in the backend should produce the current Myanmar / Burma flag which looks like this:

![image](https://user-images.githubusercontent.com/1070155/48114117-ad285800-e255-11e8-82f6-41e265b187a7.png)

##### Actual behavior

It actually produces the old Myanmar / Burma flag (which hasn't been used since 2010) which looks like this:

![image](https://user-images.githubusercontent.com/1070155/48114094-97b32e00-e255-11e8-8fc1-236c54bd70ec.png)

##### Reproduce steps

Use `<i class="flag-mm"></i>` in any backend template.

##### October build

All

##### Reference

https://en.wikipedia.org/wiki/Flag_of_Myanmar

**Comment by w20k** [comment]
Feel free to submit a PR here ;)

**Comment by joseph-d** [comment]
Actually, I made the change to the sprite PNG but I couldn't figure out how to do a PR for just an image. Can you give me any pointers?

**Comment by w20k** [comment]
@joseph-d - this fix is already in place, but you have to way for build .444. It's still in progress.

Was a part of this PR:https://github.com/octobercms/october/commit/5b7d9041fde8ccd1ca0d605cd3b413397718a94d

**Comment by joseph-d** [comment]
Ok, that looks much better with SVG etc.. I'll close this issue and wait for that then :-)
