### ISSUE TITLE
linkPolicy: force not respected when generating asset links

### ISSUE THREAD

**Issue by sNuuFix** [octobercms/october#3912]
##### Expected behavior
When deploying OctoberCMS on cloud infrastructure as Docker Swarm, behind reverse proxy/load balancer, asset links should be inlined with hostname and protocol taken from config or fowarded headers. Logging into backend should be possible.

##### Actual behavior
Depending on link policy setting, all assets are either without https or with with wrong hostname. Autodetecting the hostname doesn't work when nodes are deployed as tasks under Docker Swarm using DNS as internal discovery and health check. SSL termination happens at load balancer and internal traffic is raw HTTP, so protocol detection fails too, even `force` setting completely ignores the `https://` set in `app.url`, only outputs correct hostname. (it's the only setting that does) All of the trusted proxy plugins doesn't work by either throwing 500 errors on default installation or just aren't compatible with latest OctoberCMS anymore. In any case, all proxy requests from private IP ranges should be treated as trusted by default. The easiest way how to make OctoberCMS support scalable hosting at this point would be fixing the `force` link policy setting to obey protocol config from `app.url` when generating asset links.

##### Reproduce steps
Deploy any OctoberCMS as Docker service on Docker Swarm with more than one node. Or try any other scalable/cloud hosting solution with load balancer infront.

##### October build
Dragontek/octobercms Docker image that downloads latest stable OctoberCMS from git at the time of deploy - v1.0.443 as of writing this.

**Comment by LukeTowers** [comment]
@sNuuFix sounds like quite the complex deployment of October that you've got going on. Do you mind explaining a bit more what 
>  The easiest way how to make OctoberCMS support scalable hosting at this point would be fixing the force link policy setting to obey protocol config from app.url when generating asset links.

would look like?

**Comment by LukeTowers** [comment]
@sNuuFix if you could submit a PR to respect the force linkPolicy I would be happy to review it. The documentation would lead me to believe that it should do what you're saying it should do so I would consider it a bug if it wasn't.

**Comment by saleksin** [comment]
I can confirm that issue. I have much simpler use case, but effect is the same. My main URL points to one server, that acts like proxy for second one. Requests between proxy server and second one are not secure. Second server has different hostname. When I use link policy "force", all links has proper URL (from app.url), but with http instead of https, that is in app.url.

**Comment by sNuuFix** [comment]
I am now running aspendigital/octobercms container with latest October version under latest nginx-proxy and the issue has gone away by itself for some reason. I tried to dig into sourcecode to find the place that forces http but didn't succeed. This seems like specific edge case that's tied to server's (mis)configuration.
