### ISSUE TITLE
Media Manager error message doesn't render if invalid path contains unknown characters

### ISSUE THREAD

**Issue by Fenn-CS** [octobercms/october#3914]
##### Expected behavior
Open media manager Correctly

##### Actual behavior
Media manager throws exceptions when file names contain certain "invalid" characters e.g `'`. I however wrote a script to remove all invalid characters from file names.

The exception stopped pointing to the files that had invalid file names and just throws a general error which suggest some name is not being accepted but cannot be clearly determined.

![october path error](https://user-images.githubusercontent.com/14317775/48358646-7dd17b00-e69b-11e8-9de9-38afc2a05305.png)

##### Reproduce steps
Put a file in `storage/app/media` with an invalid file name contain like `'` or some other funny character. The second error is not clear so it hard to understand which file names are causing it and how to reproduce the error.

## 443

```
 "october/rain": "~1.0",
 "october/system": "~1.0",
 "october/backend": "~1.0",
 "october/cms": "~1.0",
```

**Comment by Fenn-CS** [comment]
I ended up noticing some path name with following unknown character. `start-of-name-�-end-of-name.jpg`

**Comment by LukeTowers** [comment]
@Fenn-CS I'd like to figure out why the path isn't displaying in the error message though, would you be willing to investigate that and see if you can come up with a fix to show the path in the error message even with unknown characters present?

**Comment by Fenn-CS** [comment]
@LukeTowers ok! I would look into this. However, I noticed the path by trying to access the media manager from the toolbar of a wysiwig. The error path just showed up in the system popup but I would check why this does not happen right in the editor itself.

**Comment by w20k** [comment]
@LukeTowers tried to reproduce error (not showing path) twice, for me it work as sit should. Maybe OS locale or something related with encoding might be a problem... Hm...
