### ISSUE TITLE
Media Manager Unable to Open

### ISSUE THREAD

**Issue by Fenn-CS** [octobercms/october#3915]
##### Expected behavior
Open media manager correctly by paginating files when they are so many

##### Actual behavior
Tries to load all files before opening! Complexity becomes high with thousands of files.

##### Reproduce steps
Put thousands of files in `storage/app/media` in my case 12000 photos and audios! (Migrating a wordpress blog)

**Comment by LukeTowers** [comment]
Duplicate of #3612, feel free to add your comments on the issue there (note: don't just say something like +1 or similar comments, if you need the issue addressed then be willing to contribute to a fix)
