### ISSUE TITLE
@jquery alias only includes jquery migrate

### ISSUE THREAD

**Issue by CptMeatball** [octobercms/october#3917]
##### Expected behavior
Using `@jquery` in the combiner includes the jquery (backend) library that is used in the backend.

##### Actual behavior
Using `@jquery` in the combiner only includes the jquery migrate (backend) library that is used in the backend.

##### Reproduce steps
Put following script on front-end.

    <script src="{{ [
        '@jquery'
    ] | theme }}"></script>

##### October build
443 with composer on on dev-develop
    
    october/backend (dev-develop 2561a78)
    october/cms (dev-develop 125bee0)
    october/system (dev-develop e139e15)

My guess it has to with #3230 and #3886 , which adds a new version of jQuery and adds Migrate to the mix.

**Comment by ayumihamsaki** [comment]
Just to add a quick note, I originally added that line of code to the alias list and Luke told me to remove it because he said he thought it did a double load. So please invest that also.

**Comment by CptMeatball** [comment]
I guess it does not 😅

**Comment by ayumihamsaki** [comment]
@CptMeatball 

Sorry just thought of something else, your PR's have done the same error I thought of at the time. You should not register the alias jQuery Migrate under a separate alias because the whole idea I had was to make backwards compatibility for people's plugin codes. So it's best to force the jQuery Migrate into a single alias of jQuery, then people's code before the CMS update will not need to be updated e.g.

## This is bad

```
$this->registerAlias('jquery', '~/modules/backend/assets/js/vendor/jquery.min.js');
$this->registerAlias('jquery.migrate', '~/modules/backend/assets/js/vendor/jquery-migrate.min.js');
```

## This is good

```
$this->registerAlias('jquery', '~/modules/backend/assets/js/vendor/jquery.min.js');
$this->registerAlias('jquery', '~/modules/backend/assets/js/vendor/jquery-migrate.min.js');
```

Otherwise people will have to change their theme codes for all their website to allow backwards compatibility which would be a problem to many people's websites.

**Comment by CptMeatball** [comment]
I understand the reasoning. The problem is that doesn't work. As my issue states, the alias method does not do a double load with the same extension. And if it should, there's something else wrong. 

Maybe we should combine migrate and jquery altogether?

**Comment by ayumihamsaki** [comment]
yah I was just thinking that merging the two files and creating this:

`$this->registerAlias('jquery', '~/modules/backend/assets/js/vendor/jquery-and-migrate.min.js');`

**Comment by ayumihamsaki** [comment]
You want create the pr or I can do it for you? - up to you.

**Comment by Samuell1** [comment]
Maybe something like this and it can be backwards compatible?

```
$this->registerAlias('jquery', '~/modules/backend/assets/js/vendor/jquery-and-migrate.min.js');
$this->registerAlias('jquery.standalone', '~/modules/backend/assets/js/vendor/jquery.min.js');
$this->registerAlias('jquery.migrate', '~/modules/backend/assets/js/vendor/jquery-migrate.min.js');
```

**Comment by LukeTowers** [comment]
@Samuell1 what makes this not backwards compatible? I think the combined under the jquery alias is fine.
