### ISSUE TITLE
Date in French (day and month) 

### ISSUE THREAD

**Issue by Dreanad** [octobercms/october#3922]
##### Expected behavior
Date in french : Jeudi 15 Novembre 2018, 12:09

##### Actual behavior
Thursday 15 November 2018, 12:09

##### Reproduce steps
fresh install
app.config timezone="Europe/Paris"
```
 setlocale(LC_TIME, 'fr_FR');
 echo strftime('%A %d %B %Y, %H:%M');
```

the time is working, but not the translation of day and month 
i have try lot of solution, but no one working (with DateTime, strfotime, etc) 

##### October build
443

**Comment by w20k** [comment]
@Dreanad could you also post the way you try to use it? Or example (image)?

**Comment by LukeTowers** [comment]
@Dreanad first thing: 

**DO NOT** set `app.timezone` to anything other than UTC. Doing this is just asking for headaches. Instead, use cms.backendTimezone to set the default timezone in the backend. 

Second thing: Use the backend preferences to set your locale (or the config file), don't set the locale in code directly like that, that bypasses all of the tools October has for dates / times.

**Comment by Dreanad** [comment]
@w20k http://www.noelshack.com/2018-46-4-1542311840-capture.jpg
http://www.noelshack.com/2018-46-4-1542312015-capture2.jpg

I think i use DateTime in the wrong way

@LukeTowers Ok, i put in back in UTC, for the setLocale, that was just for test, i use Config to get the values otherwise, and i have set backend timezone, thank you for your advice !

**Comment by LukeTowers** [comment]
@Dreanad if you want to interact with dates directly in PHP then use the Argon class which indirectly extends Carbon: https://github.com/octobercms/library/blob/master/src/Argon/Argon.php

**Comment by Dreanad** [comment]
@LukeTowers I'll look at Argon, thank you, Carbon cant do the job ?

**Comment by LukeTowers** [comment]
Carbon can, Argon just automatically sets the locale defined by OctoberCMS for you.

**Comment by Dreanad** [comment]
Thank you, im trying, but i have a class not found on Argon ( i try to use it in plugin.php) 
`       Argon::setArgonLocale(\Config::get('app.locale'));
`

so i have tested with just Jenssegers\Date\Date; and seems to be ok ! i have date in french when i use the Date class, its ok to used that class rather than carbon or argon ? 

by the way, what is an umbrella class ? I've never heard of it, maybe different name in french ..

**Comment by LukeTowers** [comment]
@Dreanad You don't need to call the setLocale method, Argon does it itself when constructed. Umbrella class just refers to it extending the actual classes doing the work so that if the behind the scenes classes ever needed to be changed out, references to Argon would still work fine, mixed with a bit of initialization / configuration logic based on the application (i.e. setting the locale)

**Comment by w20k** [comment]
@Dreanad ping me, if you still haven an issue, might look at it on weekends! ;) But I guess, should be fine by now!

**Comment by Dreanad** [comment]
@LukeTowers  So how to call Argon construct, i still have the class not found
thanks for your explanation,  It's already clearer to me  

@w20k Yeah, i finally see the end of it ! Thanks you for your help here and on Slack !

**Comment by LukeTowers** [comment]
@Dreanad add `use October\Rain\Argon\Argon;`

**Comment by Dreanad** [comment]
@LukeTowers ok Argon twice, thats working ! thank you a lot for your help
