### ISSUE TITLE
Call to undefined method Cms\Classes\Asset::delete

### ISSUE THREAD

**Issue by Rike-cz** [octobercms/october#3925]
##### Expected behavior
Clicking on "delete" button in CMS > Assets > tab delete opened asset.

##### Actual behavior
Error thrown: "Call to undefined method Cms\Classes\Asset::delete()" on line 398 of C:\...\vendor\october\rain\src\Extension\ExtendableTrait.php

##### Reproduce steps
Watch attached animation.
![ocms](https://user-images.githubusercontent.com/4247582/48617826-c63cb180-e997-11e8-9f6f-a8d9b5c9f60b.gif)

##### October build
443

**Comment by w20k** [comment]
@Rike-cz found issue, might give it a go and make PR, soon ;)
