### ISSUE TITLE
Editor hotkeys

### ISSUE THREAD

**Issue by Patesz** [octobercms/october#393]
Hello Guys,

I have a little but annoying problem with hotkeys of the code editor in OctoberCMS. 
There is a hotkey in the editor (Ctrl+Alt+F) to send the editor to fullscreen what is very userful if you are not hungarian but unfortunately I am. :) 
In hungarian region, in hungarian keybord we can type [ character with Ctrl+Alt+F combination. 
So when I press Ctrl+Alt+F because I want to write a [ character (its quite frequent character in PHP language) the editor just goes to full screen mode (and do not let me to write [ character)

Do you have any solution to this problem? :) 
Thank you

p.s.: sorry for my poor english

**Comment by codebugs** [comment]
hello daftspunk. do you have any news about this issue?
