### ISSUE TITLE
Did not find a way to make work the Ajax-validation mechanism using "JavaScript API"

### ISSUE THREAD

**Issue by termiyanc** [octobercms/october#3935]
Hello.

I would like to use "JavaScript API" to make Ajax-request, and my handler may throw the ValidationException. These exceptions are handling by "Data attributes API". But i did not find a way to use this validation using only "JavaScript API". To make this validation mechanism work i need to add empty "data-request" attribute and "data-request-validate" attribute to my form.

**Comment by w20k** [comment]
Could you also add a code example, how you do a call with JS API?

**Comment by termiyanc** [comment]
This is it:

```javascript
$('.how-to-get-card button.pseudo-link').on('click', () => {
	$.request('onAjax', {
		update: {'how_to_get_card': '#how-to-get-card-modal'},
		complete: (xhr) => {
			if (xhr.status == 200) {
				$('#how-to-get-card-form').on('submit', (event) => {
					$(event.currentTarget).request('feedback::onSendHowToGetCardForm', {
						form: event.currentTarget,
						loading: '#how-to-get-card-modal .ui.dimmer',
						success: (data) => {
							if (data.success) {
								$('#how-to-get-card-form-container').hide();
								$('#how-to-get-card-text').addClass('message').text(data.message);
							} else {
								let $errorMessage = $('#how-to-get-card-error-message');
								$errorMessage.text(data.message);
								$errorMessage.show();
							}
						}
					});
					return false;
				}).on('ajaxPromise', () => {
					$('#how-to-get-card-error-message').hide();
				});
				$('#how-to-get-card-form input[name="phone"]').mask('(999) 999-9999', {autoclear: false});
				$('#how-to-get-card-modal').modal('show');
			}
		}
	});
```

And i did not find a way (i repeat) how to use the Ajax-validation mechanism with this JS-API only. I need to add attributes to my form as if i would use the "Data attributes API":

```html
<form id="how-to-get-card-form" class="ui form"
      data-request
      data-request-validate>
```

I mean that i want the Ajax-validation to automatically work, to automatically handle the "ValidationException"s as it works through theese attributes, but though "JavaScript API". I also noticed that `data-request-validation`-attribute doesn't work without `data-request`-attribute, so the last is in form and it is empty.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
