### ISSUE TITLE
[Feature Request] set Project id from command line

### ISSUE THREAD

**Issue by obuchmann** [octobercms/october#3944]
It would help to script october deployments if there would be an artisan command to set the project id.

Working on an PR.

**Comment by obuchmann** [comment]
I mean to attach a project id, like the System\Controllers\Updates::onAttachProject() method does.

The implementation could be as following:

```
$manager = \System\Model\UpdateManager::instance();
$result = $manager->requestProjectDetails($projectId);

\System\Model\Parameter::set([
   'system::project.id'    => $projectId,
   'system::project.name'  => $result['name'],
   'system::project.owner' => $result['owner'],
]);
```

**Comment by LukeTowers** [comment]
@obuchmann I'm fine with that. If you could make your PR to add it to `october:util` in the form of `php artisan october:util set project=$projectIdHere` that would be accepted.
