### ISSUE TITLE
Backend system assets have versioning set

### ISSUE THREAD

**Issue by CptMeatball** [octobercms/october#3945]
##### Expected behavior
Updating to newest develop-branch changes, also updates the jquery files etc.

##### Actual behavior
After updating to newest develop-branch changes, browser still loads the old files due to a `?v1` parameter that is added to all files.

![image](https://user-images.githubusercontent.com/1681727/49143652-c758d180-f2fb-11e8-9889-cb7544cb7986.png)

##### October build
Latest Develop

**Comment by w20k** [comment]
Hi, 

By default it add coreBuild number. Just try to run october utils for fetching build number.
`php artisan october:util set build`

```
<link href="<?= Url::asset('modules/system/assets/ui/storm.css') ?>?v<?= $coreBuild ?>" rel="stylesheet">
<link href="<?= Backend::skinAsset('assets/css/october.css') ?>?v<?= $coreBuild ?>" rel="stylesheet">

<script data-cfasync="false" src="<?= Backend::skinAsset('assets/js/vendor/jquery.min.js') ?>?v<?= $coreBuild ?>"></script>```

**Comment by CptMeatball** [comment]
ahh. that explains. Thanks!
