### ISSUE TITLE
Improve visibility of code editor buttons in the backend

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3947]
This issue has annoyed me for years and today, I had enough and decide to code the fix.

The issue see screenshot, below:

![1a](https://user-images.githubusercontent.com/17784082/49227605-5ab80280-f3e1-11e8-9b9a-5a8a3f40e234.png)

As you can see, you can not see the buttons in default mode as they are hidden in the code (very annoying!)

The old CSS code:

```
.field-codeeditor .editor-toolbar {
    position: absolute;
    top: 10px;
    right: 25px;
    z-index: 10;
}
```

My suggestion is to re-code it to make it exactly the same as the search box in the same place, therefore see the following screenshot example now:

![2a](https://user-images.githubusercontent.com/17784082/49227750-c4d0a780-f3e1-11e8-95d6-76c1bd5235ee.png)

CSS File Location: modules/backend/formwidgets/codeeditor/assets/css/codeeditor.css?v443

I will try to create a PR in a bit - if others think this is fine.

**Comment by ayumihamsaki** [comment]
Update: Actually I might just move it across to the left a bit so it is not covering the scrollbar like the search box is doing:

```
.field-codeeditor .editor-toolbar {
    border-radius: 0px 0px 5px 5px;
        border-top-left-radius: 0px;
        border-top-right-radius: 0px;
        border-bottom-right-radius: 5px;
        border-bottom-left-radius: 5px;
    right: 25px;
    background-color: #ddd;
    border: 1px solid #cbcbcb;
        border-top-color: rgb(203, 203, 203);
        border-top-style: solid;
        border-top-width: 1px;
        border-right-color: rgb(203, 203, 203);
        border-right-style: solid;
        border-right-width: 1px;
    border-top-color: rgb(203, 203, 203);
    border-top-style: solid;
    border-top-width: 1px;
    border-right-color: rgb(203, 203, 203);
    border-right-style: solid;
    border-right-width: 1px;
    border-right-color: rgb(203, 203, 203);
    border-right-style: solid;
    border-right-width: 1px;
    border-top: 0 none;
    max-width: 125px;
    overflow: hidden;
    margin: 0;
    padding: 4px;
    position: absolute;
    top: 0px;
    z-index: 99;
    white-space: normal;
}
```

Giving the results:

(With Scrollbar)

![3a](https://user-images.githubusercontent.com/17784082/49228939-61944480-f3e4-11e8-9d7e-ad238c1d7f9a.png)

(Without Scrollbar)

![3ab](https://user-images.githubusercontent.com/17784082/49228990-7bce2280-f3e4-11e8-81d9-ba51bb153e80.png)

Let me know what you think...?

**Comment by w20k** [comment]
Hi, @ayumihamsaki looks great to me 😉. Just a minor note, could you test it with different resolutions: tablet, desktop, mobile?

**Comment by ayumihamsaki** [comment]
Closing this as already merged into new October Version - not sure why not closed?

**Comment by LukeTowers** [comment]
@ayumihamsaki it hasn't been merged to master, the release of the build is just a pending build, tagged to develop. We'll go stable next week at which point this stuff will be merged to master.
