### ISSUE TITLE
Unable to edit file with parentheses in its name

### ISSUE THREAD

**Issue by Albert221** [octobercms/october#3954]
Okay, so I uploaded an image to my assets, its name is `Tło1 (1).jpg`. Now, I cannot delete it or rename because:

![image](https://user-images.githubusercontent.com/4085280/49339815-643aa800-f637-11e8-8fc1-4eb37a671031.png)

October version: current buil: 443

**Comment by w20k** [comment]
Used the same fileName (OSX). It worked for me. No errors.
Screenshot:
<img width="948" alt="screenshot 2018-12-03 at 01 31 55" src="https://user-images.githubusercontent.com/1053320/49346444-54ed4600-f69b-11e8-92a3-79f142122a72.png">

@Albert221, could you add steps how to reproduce your bug?

@LukeTowers we already have rule for parenthesis: `preg_quote('(', '/'),preg_quote(')', '/'),`.

**Comment by Albert221** [comment]
@w20k looks like you added it to Media, not Assets (in CMS section). I'll record a short screencast next evening.

**Comment by w20k** [comment]
@Albert221 thanks for a tip. Yeah, found it 😉

**Comment by LukeTowers** [comment]
I'm not sure if we want to put it in the filesystem layer, there's a lot of different stuff that could break if we had it at the filesystem layer. The main reason there's validation in the media library section is to prevent XSS, so as long as we can come up with a solid way to handle that going forwards that isn't quite as brittle as filename validation I'm fine with the solution.

**Comment by Albert221** [comment]
hey don't close the issue
