### ISSUE TITLE
Possible Bug in the Plugins Backend Section

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3955]
## Steps to repeat the bug:

Go to the Settings > Updates & Plugins > Manage Plugins

Then I had for example this row:

```
Code: Plugin X
Version: 1.2.2
Updates Enabled: Turned ON
Plugin Enabled: Turned OFF
```

Then I go to Settings > Updates & Plugins

I click on the "Check for updates" button.

I get the reply:

> Software update
> No new updates were found.

Now I change the Settings to the following:

```
Code: Plugin X
Version: 1.2.2
Updates Enabled: Turned ON
Plugin Enabled: Turned ON
```

Then I go to Settings > Updates & Plugins

I click on the "Check for updates" button.

I get the reply:

> Software update
> Found new updates! Click Update software to begin the update process.

## Expected Process:

I was expecting the plugin X to update with the following settings:

```
Code: Plugin X
Version: 1.2.2
Updates Enabled: Turned ON
Plugin Enabled: Turned OFF
```

**Comment by w20k** [comment]
Hi, @ayumihamsaki can't reproduce it with my local sites.

The only place where `is_frozen` flag is checked is here: 
https://github.com/octobercms/october/blob/edcc4af68aa70dc4b84b687e34edb90d14191ca0/modules/system/classes/UpdateManager.php#L263
Doesn't seem to be a problem here. Needs more testing with specific plugin or version. Maybe server is bugging.

**Comment by ayumihamsaki** [comment]
@w20k Thanks for looking into it, I will run some tests as well. 

I have several paid plugins in the backend switched off at the moment. 

Before I wrote this issue, I was able to repeat the issue several times, going back and forth turning the switches on and off and clicking on the update button! So I don't think it's a one off bug.

The plugin that failed is the following: https://octobercms.com/plugin/indikator-backendelite

Note that is a paid (not free plugin).

Though I think there is nothing wrong with that plugin!

I think the issue is probably caused on October CMS server talking to the CMS maybe?

Need to investigate into where the problem is though, pity you could not reproduce the error.

**Comment by ayumihamsaki** [comment]
@w20k @LukeTowers 

Ok you are in luck, I still have other paid plugins turned off in one of my clients websites. That I have not updated in a while. I will take a video and demo the issue with another paid plugin:

Please watch this video: https://www.youtube.com/watch?v=Sd4ap7JxhcA

That is for the paid plugin: https://octobercms.com/plugin/radiantweb-problog

Again nothing wrong with the plugin. 

Just can demo the bug.

p.s. I not try on a free plugin yet only tested it on turned off paid plugins.

I think server to cms issue.

**Comment by w20k** [comment]
@ayumihamsaki not sure if it's called luck 😄

**Comment by ayumihamsaki** [comment]
@bennothommo @LukeTowers @w20k Why are issues and bugs getting closed and not fixed ?

I can reproduced this issue right now in latest CMS Version! If you do like this we end up with a CMS filled with bugs and it's no good. I understand October CMS is under staffed, but closing bug issues that exist is not good at all.

See here I can reproduce this issue right now:

![october-bug](https://user-images.githubusercontent.com/17784082/58289642-00f02e00-7daf-11e9-8606-0984078ab875.gif)

See above gif in CMS Version 455. Problem still exists for paid plugins!

**Comment by bennothommo** [comment]
@ayumihamsaki my apologies. Your last comment made it seem like there was no issue here, and since there hadn't been any activity for 6 months, I closed it to clear out some stale issues.

**Comment by LukeTowers** [comment]
@ayumihamsaki  stale issues get closed for exactly the reason you've just commented. If the issue is still present, it prompts people that care about it to comment and become engaged with it again. If nobody responds, then clearly it isn't important and can be ignored. If someone does comment, then it's not a problem to reopen the issue.

**Comment by ayumihamsaki** [comment]
Maybe have a rule for the `Type: Unconfirmed Bug` label, if two or more people confirm they can not reproduce it then close it. 

As for commenting, I prefer not to do that, because before I write a comment, I know it will take up your time and you guys are busy people! So I try to comment in the github issues only if it's really needed.

**Comment by bennothommo** [comment]
To go to the issue reported - I'm wondering if this is such a bad thing, preventing updates to disabled plugins. A plugin that is disabled should effectively be non-functioning and have no effect to the site - including migrations added as part of an update. Disabling updates should only be allowed for an enabled plugin, to allow a site administrator to "freeze" on a certain version. Thoughts?

**Comment by ayumihamsaki** [comment]
I agree with your comment, I think it would make it easier to remove the extra switch column and just have a single column that turns the plugin on and off (which also disables the updates).

I will also link these two other issues, I think we could group all three issues together to form a single issue titled: Plugin Section re-design.

https://github.com/octobercms/october/issues/4196
https://github.com/octobercms/october/issues/3497

**Comment by ayumihamsaki** [comment]
If it's ok with everyone I will close these three issues and merge them all into a single issue.

**Comment by bennothommo** [comment]
@ayumihamsaki Go for it :)

**Comment by ayumihamsaki** [comment]
Closed see here: https://github.com/octobercms/october/issues/4345
