### ISSUE TITLE
HTTP 302 error when trying to get backend without debug mode

### ISSUE THREAD

**Issue by greinbold** [octobercms/october#3957]
Hello,

My October instance works fine, but only with debug mode...

As discussed on the IRC channel, I got a HTTP 302 error when I try to get the backend without debug mode.

Apache 2.4 config:

```
<VirtualHost 127.0.0.1:8080>

...

<Directory ... >
    Options Indexes MultiViews FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

...

</VirtualHost>
```

HAProxy 1.8 config:

```

...

frontend http
        bind :443 ssl crt /etc/ssl/haproxy/
        bind :80
        acl example hdr(host) example.com
        redirect scheme https if !{ ssl_fc } example
        default_backend apache

backend apache
        option forwardfor
        option httpchk
        http-request add-header X-Forwarded-Proto https if { ssl_fc }
        http-request set-header X-Forwarded-Port %[dst_port]
        server apache 127.0.0.1:8080

...

```

config/app.php

```
'debug' => true
```

config/cms.php

```
'backendUri' => '/backend',
'backendForceSecure' => null,
'linkPolicy' => 'secure'
```

##### Expected behavior
Can connect to the backend without debug mode with a high availability proxy which handle SSL/TLS layer.

##### Actual behavior
Can connect to the backend only with debug mode.

##### Reproduce steps
1. Install a October instance behind a high availability proxy (like HAProxy) with a simple config (like the one above)
2. Setup October only with the parameters mentioned above, but with debug mode set to `false`
3. Try to connect to the backend
4. You will get a HTTP redirect error
5. Then set debug mode to `true`, retry to connect to the backend, all work perfectly!

##### October build
443

Best regards

**Comment by w20k** [comment]
Hi, @greinbold 

Try setting config/cms.php -> `'backendForceSecure' => false,`. Should work. 
When setting debug to false backend is forced to use HTTPS, and in your case HTTPS protocal for your host is not defined.

```
/*
    |--------------------------------------------------------------------------
    | Back-end force HTTPS security
    |--------------------------------------------------------------------------
    |
    | Use this setting to force a secure protocol when accessing any back-end
    | pages, including the authentication pages. If set to null, this setting
    | is enabled when debug mode (app.debug) is disabled.
    |
    */```

**Comment by greinbold** [comment]
> Hi, @greinbold
> 
> Try setting config/cms.php -> `'backendForceSecure' => false,`. Should work.
> When setting debug to false backend is forced to use HTTPS, and in your case, HTTPS protocol for your host is not defined.
> 
> ```
> /*
>     |--------------------------------------------------------------------------
>     | Back-end force HTTPS security
>     |--------------------------------------------------------------------------
>     |
>     | Use this setting to force a secure protocol when accessing any back-end
>     | pages, including the authentication pages. If set to null, this setting
>     | is enabled when debug mode (app.debug) is disabled.
>     |
>     */
> ```

It works now.

I had not think about that and also don't understand which exactly describe `to force a secure protocol`.

Thanks a lot @w20k

**Comment by w20k** [comment]
What it does it enables HTTPS for your backend (`force a secure protocol`), pretty much that's it 😉

**Comment by w20k** [comment]
@greinbold could you close this issue, if it's resolved, thanks!
