### ISSUE TITLE
How to re-set collapsed folders to default setting in cms editor section

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3962]
This is an issue that has gone on for several months now. A long time ago all the folders in the cms editor section were all **"collapsed" by default** and then after an update to the cms all the folders are now "expanded" by default.

This is really annoying issue for me, due to having on average over 500 partials per website project. It takes me a good 10 minutes everyday closing all the folders, so I can start work on the client websites. Try to imagine, trying to scroll down through over 500 partials, to find the partial you need to work on.

Is it possible to have them all default to "collapsed" ?

I'm talking about the code lines:

```
<div class="control-filelist " data-control="filelist" data-group-status-handler="partialList::onSetCollapseStatus" id="TemplateList-partialList-template-list">
  <ul>
    <li class="group" data-status="collapsed"></li>
    <li class="group" data-status="expanded"></li>
  </ul>
</div>
```

![aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/17784082/49532121-ba1b8400-f8b3-11e8-8cd9-69d37b652351.png)

Is there a setting somewhere to set this by default?

**Comment by ayumihamsaki** [comment]
I believe it went like this after this commit update (but not 100% sure): https://github.com/octobercms/october/commit/a2a7eec4f5df016a9e41ce9698d58f8d69bcccc3

> You could also add the ability for a modifier (command on mac, ctrl on windows) click on one arrow to toggle the expansion / collapse of all items at the same time.

That sounds an amazing idea.

**Comment by LukeTowers** [comment]
@ayumihamsaki thanks. Feel free to submit a PR to add the toggle all functionality on modifier clicks
