### ISSUE TITLE
Proposal: Add format property to columns

### ISSUE THREAD

**Issue by vicrly** [octobercms/october#3967]
modify /modules/backend/widgets/List.php function evalTextTypeValue()
```
protected function evalTextTypeValue($record, $column, $value)
{
    if (is_array($value) && count($value) == count($value, COUNT_RECURSIVE)) {
        $value = implode(', ', $value);
    }

    return htmlentities($value, ENT_QUOTES, 'UTF-8', false);
}
````
**changed to**
```
protected function evalTextTypeValue($record, $column, $value)
{
    if (is_array($value) && count($value) == count($value, COUNT_RECURSIVE)) {
        $value = implode(', ', $value);
    }
   if ($column->format !== null) {
        $value = sprintf($column->format, $value);
    }
    return htmlentities($value, ENT_QUOTES, 'UTF-8', false);
}
```

**Comment by LukeTowers** [comment]
What is the purpose of this?

**Comment by LukeTowers** [comment]
I have no idea what you just said. How about you provide a demonstration of how this would be used in real life?

**Comment by vicrly** [comment]
For example: $100.00, 10 people, 30 years, 5 months, 8-10~9-10
Output control is the core of Lists, so I think formatting is essential

**Comment by LukeTowers** [comment]
Please provide an example of the YAML that the column definitions would look like when using this

**Comment by vicrly** [comment]
YAML column definitions,like this is:
```
price:
        label: price
        type: text
        format: '%s $/people'
```
output:
99 $/people

**Comment by munxar** [comment]
@vicrly I totally like the idea, and did this myself with a custom column about 100 times.
@LukeTowers having this option, would be very useful.

**Comment by vicrly** [comment]
@munxar you're right
@LukeTowers ok. let me try
