### ISSUE TITLE
Backend sideMenu is not displaying even though user has permissions 

### ISSUE THREAD

**Issue by ChadStrat** [octobercms/october#397]
See attached screenshots.
- plugin defines permission
- user has permission
- sidebar doesn't show up

![screen shot 2014-07-05 at 6 49 43 pm](https://cloud.githubusercontent.com/assets/852537/3487684/bc39819e-0496-11e4-839c-25373cd6f3b9.png)

![screen shot 2014-07-05 at 6 47 56 pm](https://cloud.githubusercontent.com/assets/852537/3487685/c1242826-0496-11e4-9710-20446c2169a3.png)

![screen shot 2014-07-05 at 6 48 11 pm](https://cloud.githubusercontent.com/assets/852537/3487686/c3daadf6-0496-11e4-9b9d-8614a6896ac0.png)

![screen shot 2014-07-05 at 6 51 00 pm](https://cloud.githubusercontent.com/assets/852537/3487687/dd10fdc0-0496-11e4-86d8-3f6d1dd372b1.png)

**Comment by tofanelli** [comment]
I liked this plugin and I need something like this... any plans to release it or is a private project?

**Comment by LukeTowers** [comment]
@tofanelli see http://octobercms.com/plugin/renatio-support (for backend users) and http://octobercms.com/plugin/responsiv-support (for frontend users)
