### ISSUE TITLE
Would it be a good idea to add a Javascript dragbar to the backend in various places?

### ISSUE THREAD

**Issue by ghost** [octobercms/october#3971]
I got one final idea for updating the code section in the October backend. I also would like to add it to the builder plugin.

I will show you my idea for the code editor section to add a Javascript dragbar, so users can adjust the size of the column to read the files more easily, or hide them a bit better.

## The Problem

Currently October allows you to either display it in full or hide it. There is no feature to allow you to fine tune the column size.

### Code Editor Section

The column displays the list of files, I would like to make the right side adjustable:

![untitled1](https://user-images.githubusercontent.com/17784082/49687508-c4c85a00-fafb-11e8-81dc-c237652dbcac.png)

and be able to do something like this:

![dragbar](https://user-images.githubusercontent.com/17784082/49687585-d1997d80-fafc-11e8-8fe1-361565e377f8.gif)

### Settings Section

![untitled13333333333](https://user-images.githubusercontent.com/17784082/49687748-6c935700-faff-11e8-911a-fa9b8e2ebbb2.png)

## Builder Plugin

I would like to add it also to here:

![untitled13333333333](https://user-images.githubusercontent.com/17784082/49687601-26d58f00-fafd-11e8-97d7-bcb3e4ae7a5a.png)

I would like to see what others think, to see if this is a good idea or not?

I personally think it would make using the backend a bit easier.

**Comment by SebastiaanKloos** [comment]
That would be really nice. The adjustments should be saved in the session

**Comment by ayumihamsaki** [comment]
Code Example: http://htmlpreview.github.com/?https://github.com/ayumihamsaki/october-drag-bar/blob/master/drag-bar.html

## Code Usage Options

**Global Scope:**
```javascript
$(selector).resizable(options);
```

### Options
The options parameter can be a map of any of these properties (default values are shown):

```javascript
var opt = {
    // optional selector for handle that starts dragging
    handleSelector: null,
    // resize the width
    resizeWidth: true,
    // resize the height
    resizeHeight: true,
    // the side that the width resizing is relative to
    resizeWidthFrom: 'right',
    // the side that the height resizing is relative to
    resizeHeightFrom: 'bottom',            
    // hook into start drag operation (event,$el,opt passed - return false to abort drag)    
    onDragStart: null,
    // hook into stop drag operation (event,$el,opt passed)
    onDragEnd: null,
    // hook into each drag operation (event,$el,opt passed)
    onDrag: null
    // disable touch-action on the $handle
    // prevents browser level actions like forward back gestures
    touchActionNone: true
};
```

**handleSelector**  
A jQuery selector or DOM element that acts as a selector. This can be a string, a DOM object or an existing jQuery selector.

If no selector is passed the element itself becomes resizable. Usually this results in undesirable behavior but you can  limit the drag start location using the `onDragStart` handler.

If the selector is prepended by a `>` the element is searched inside the resized component.

```html
<!-- first instance -->
<div class="box">
  <div class="handle">
  </div>
</div>

<!-- second instance -->
<div class="box">
  <div class="handle">
  </div>
</div>

<script>
$(".box").resizable({
  handleSelector: "> .handle"
});
</script>
```

**resizeWidth, resizeHeight**  
These two boolean values determine whether the width or height are resizable. Both are true by default so disable which ever dimension you don't want to resize.

**resizeWidthFrom,resizeHeightFrom**
Determines which direction the reszing is done from. By default the directions are "right" and "bottom" but they could be "left" and "top". Useful for RTL locales where drag operations are naturally opposite to LTR.

**onDragStart**  
Hook method fired just before you start dragging. You can return an explicit `false` value to abort the drag operation. Gets passed the event, the selected jQuery element and the options object.

```javascript
$(".box").resizable({
    onDragStart: function (e, $el, opt) {
        $el.css("cursor", "nwse-resize");
    },
    onDragEnd: function (e, $el, opt) {
        $el.css("cursor", "");
    }
});
```

**onDrag**  
Hook method fired whenever the mouse cursor moves. 

Receives jQuery event, jquery selected element, newWidth, newHeight and the options object.  Optionally return an explicit value of `false` to indicate you don't want to set the newWidth, newHeight values after `ondrag` completes.

```javascript
 onDrag: function (e, $el, newWidth, newHeight, opt) {
     // limit box size
     if (newWidth > 300)
        newWidth = 300;
     if (newHeight > 200)
        newHeight = 200;        
 
     $el.width(newWidth);
     $el.height(newHeight);

     // explicitly return **false** if you don't want 
     // auto-height computation to occur
     return false;
});
```

**onDragEnd**  
Hook event fired when the drag operation completes and the mouse is released. Receives event, jquery selected element and the options object.

**touchActionNone**  
Sets touch-action: none on the handle element to prevent browser interference to initiating touch drag operations especially on Internet Explorer, Edge and Windows 10 browsers.


### Commands

**destroy**

Should the need arise, you can remove a `resizable` instance with:

```javascript
  $el.resizable('destroy');
```

**Comment by ayumihamsaki** [comment]
Please note if the green light was to add a drag bar to the CMS page I would suggest to remove the highly buggy Code Editor Hover Function and just reply 100% on a drag bar instead, see screenshot what I am talking about:

![50489587-6c9cbd80-0a00-11e9-88ac-99557357eba3](https://user-images.githubusercontent.com/17784082/61876782-8db98400-aee5-11e9-8f22-950d6a904804.png)
