### ISSUE TITLE
Broken pagination on the author page

### ISSUE THREAD

**Issue by lautsevich** [octobercms/october#3978]
##### Expected behavior
Pagination on the author page works.

##### Actual behavior
Pagination on the author page doesn't work.

##### Reproduce steps
Open author page with more than 18 plugins ([LOVATA](https://octobercms.com/author/Lovata), [Vojta Svoboda](https://octobercms.com/author/VojtaSvoboda)) and try to go to the second page.

![image](https://user-images.githubusercontent.com/196445/49865661-a1aceb80-fe16-11e8-9517-27a2685dec6a.png)

**Comment by w20k** [comment]
Should be fixed. The pagination was removed :) 
Could you double check @lautsevich?

**Comment by lautsevich** [comment]
Yep, all's OK now!
