### ISSUE TITLE
Number range filter doesn't work if either 'min' or 'max' is set to 0

### ISSUE THREAD

**Issue by rongself** [octobercms/october#3982]
https://github.com/octobercms/october/blob/826e72d3a969c2307e83e59c28056b26e488723c/modules/backend/widgets/Filter.php#L764

**Comment by w20k** [comment]
@rongself, could you describe how should range work if your 'min&max' values are equal?

**Comment by w20k** [comment]
@munxar why would you use range than? If you're looking only for a single value? 
'0' value is an issue here, for sure, but still, you won't use the range with min=0 & max=0, there is no point 😄

**Comment by munxar** [comment]
@w20k Yes, but if it is something you calculate or derive from something else (a variable) you sometimes don't have control over what you get. Let's say you give the user a range from 0 to the max of some items. What will this range be in the beginning when no records are entered? Yes, 0.
I don't claim it makes sense, but imho the filter must handle that edge case in a predictable way.

**Comment by rongself** [comment]
@w20k @munxar 
sorry,my english is really bad.
for example, min=0 and max=20, the filter will not work

**Comment by bennothommo** [comment]
Fixed by #4789.
