### ISSUE TITLE
Clarify Documentation For Ajax Introduction

### ISSUE THREAD

**Issue by auzadventure** [octobercms/october#3985]
##### Expected behavior
[The documentation ](https://octobercms.com/docs/ajax/introduction)

##### Actual behavior

The onTest handler method accessed the form data using the input helper method and the result is passed to the result page variable.
```
function onTest()
{
    $this->page['result'] = input('value1') + input('value2');
}
```

`$this->page['result']` does not work if the code is inserted in the CODE section of the page. 

##### Reproduce steps
If the PHP code is insert into the CODE section of the page, it should be.

```
function onTest()
{
    $this['result'] = input('value1') + input('value2');
}
```
There should be a link to "updating partials"

**Comment by LukeTowers** [comment]
@auzadventure feel free to submit a PR to https://github.com/octobercms/docs
