### ISSUE TITLE
Add SVG support in Media Manager

### ISSUE THREAD

**Issue by Rike-cz** [octobercms/october#3986]
Idea for Media Manager improvement - add SVG support (as image beside current JPEG, PNG...)

**Comment by LukeTowers** [comment]
Duplicate of #3106. Resubmit that PR with my recommendations implemented if you would like to see this.

**Comment by Rike-cz** [comment]
Sorry, my bad.

**Comment by Rike-cz** [comment]
@datune Are you able to resubmit your PR?

**Comment by w20k** [comment]
@Rike-cz, you could make a revision of his PR and resubmit it with regards to the author.

**Comment by Rike-cz** [comment]
Little question when I am trying to solve SVG problem: Why every thumbnail in Media Manager is PNG, if original image is JPEG? It's purpose or bug?
