### ISSUE TITLE
How to use Condition callback and After match callback in Router Rule

### ISSUE THREAD

**Issue by radist** [octobercms/october#3987]
this is not in the documentation

https://github.com/octobercms/library/blob/master/src/Router/Rule.php#L283-L330

**Comment by w20k** [comment]
Hi, @radist, if you're interested, could make a PR to [docs](https://github.com/octobercms/docs) 😉

**Comment by w20k** [comment]
@radist, It's called from Router.php (https://github.com/octobercms/library/blob/master/src/Router/Router.php#L84). Should work from the code perspective.
Why do you think code ain't ready?

**Comment by radist** [comment]
matchCallback is always null
https://github.com/octobercms/library/blob/master/src/Router/Router.php#L83 

in afterMatch(); No parameters passed
https://github.com/octobercms/library/blob/master/src/Router/Router.php#L82


$callback  is always null
https://github.com/octobercms/library/blob/master/src/Router/Rule.php#L317

always return unset properties afterMatchCallback
https://github.com/octobercms/library/blob/master/src/Router/Rule.php#L329

``
return $this->afterMatchCallback;
``

**Comment by w20k** [comment]
@radist, would you like to make PR to fix it?

**Comment by radist** [comment]
We need a description from the designer how it should work. From the current state of the code it’s not clear.

**Comment by w20k** [comment]
@radist, will have to wait for @LukeTowers input on this one. He might have a clue.

**Comment by gitlog** [comment]
Useful stuff :+1:

**Comment by LukeTowers** [comment]
@daftspunk I have no idea what any of this is for, you mind taking a look?

**Comment by daftspunk** [comment]
This code is the internal router used to route request to the relevant CMS page, using the specific format in the documentation. It's a package that can operate standalone and it was designed to function this way so there are some features that are not used.

The features in question are a basic form of middleware, allowing a before and after callback to be fired before a route rule executes. There isn't enough information provided here, so without knowing the specific use case I'm unsure why this has been raised as an issue.
