### ISSUE TITLE
Error with Backend Administrators options

### ISSUE THREAD

**Issue by Tranest8tion** [octobercms/october#3988]
Expecting to be able to add, delete, update Admins for the backend, however an exception occurs

I get an exception listed in the image attachment

![screen shot 2018-12-17 at 9 32 44 am](https://user-images.githubusercontent.com/13798489/50093526-eb168580-01de-11e9-8790-50fe45abaaa7.png)

Reproduce with: Clean install using MS SQL dB and running the install via October instructions.

build number: 443

Any and all help with this issue is greatly appreciated.

**Comment by w20k** [comment]
@Tranest8tion, if you're using SQL server, you have to apply this script: https://github.com/orlando-colamatteo/ms-sql-server-group-concat-sqlclr

**Comment by Tranest8tion** [comment]
Thank you so much w20k! It worked perfect.

**Comment by LukeTowers** [comment]
@w20k could you add a link to the docs you're talking about? And is there an opportunity to add a section in our documentation for users of MS SQL?

**Comment by w20k** [comment]
@LukeTowers, it's already there. Was a bit easier to post a link 😉 

>When using the SQL Server database engine, you will need to install the group concatenation user-defined aggregate.
https://octobercms.com/docs/setup/installation#system-requirements
