### ISSUE TITLE
Feature Request: Add/Create an IP Address Whitelist in Maintenance Mode

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3989]
## Problem

I work on a website that has October (World's best CMS) and it has over 1 million web pages, we have a small team and we create code updates all the time, on average 1-3 updates per day throughout 2018. It has been found best to tweak things in Live Production Mode, having one Browser open for the Front-end and another Browser open at the same time for the backend. Basically this setup:

Front-end = Google Canary
Back-end = Firefox Nightly

We do this sometimes to get around some of the annoying caching issues October has and it allows us to totally clear the cache on the front-end without getting logged out of the back-end etc.

The issue when doing this, is that the Maintenance Mode will at present only work for Firefox Nightly (the backend session) and not the front-end Google Canary. The developers opening a different browser will only see the maintenance screen.

## Possible Solution

Been having a think on this and I suggest having a textarea box in the Maintenance settings page where webmasters can add some whitelist IP addresses for the developers to be able to view the website behind the Maintenance screen.

I believe there is a plugin that does this for users using the Rainlab User plugin. But I believe there is no feature right now to allow IP addresses.

So I was thinking maybe have a textbox where you can add a single or list of IP addresses per line - which can bypass the maintenance screen.

![exmple](https://user-images.githubusercontent.com/17784082/50120824-b8a47100-024e-11e9-99fb-0348216803ac.png)

## Final words

Would love to hear people's ideas and input into this issue.

Thanks.

**Comment by LukeTowers** [comment]
The reason the site works for the backend browser is because maintenance mode on the frontend is bypassed when logged into the backend. So if your frontend browser also logged into the backend then that would work too. I'm not opposed to the idea in theory, but I don't think it's a good fit for inclusion in the core. It would probably be easily implemented as a separate plugin though, so that's good news.

**Comment by ayumihamsaki** [comment]
@LukeTowers Ok, fair enough. The issue we were getting was doing a full cache reset on the front-end and that logs us out, then the maintenance screen shows up, so I was hoping to be able to get around that. Will push this idea further through a plugin and not into the core files. Thanks for feedback.
