### ISSUE TITLE
Can not bypass errors in installer

### ISSUE THREAD

**Issue by ghost** [octobercms/october#3998]
See screenshot:

![xxxxxxwq](https://user-images.githubusercontent.com/17784082/50292298-a00fa300-0468-11e9-95b3-ec78a11c2fe8.png)

Two issues here:

1. Is with the plugin (not october issue)

2. Issue is that you can not bypass this error - there is no feature! That needs to be fixed in the installer.

**Comment by w20k** [comment]
@ayumihamsaki, could you past install_logs? 
Is it related to any plugin? Or only to a specific one?

**Comment by LukeTowers** [comment]
@w20k are you able to replicate this?

**Comment by w20k** [comment]
@LukeTowers, can't test it with formBuilder - it's a paid plugin. But will do with others, just to be sure.

**Comment by ayumihamsaki** [comment]
+1 To have a 'Skip' button whenever October is trying to install **_third party code_** from plugins and themes.

**Comment by ayumihamsaki** [comment]
Is it possible to add a 'help wanted' tag to this. I'm quite busy right now and the little spare time I got, I want to focus on updating the JS and CSS files in October. Which will take a long time and drag on for many months! lol

**Comment by w20k** [comment]
I'll look at this it @ayumihamsaki, but I've added.

**Comment by ayumihamsaki** [comment]
Thank you

**Comment by SebastiaanKloos** [comment]
Had the same problem. Just retry. The second time was a successfull try

**Comment by ayumihamsaki** [comment]
Thanks SebastiaanKloos, but when I tested it, it kept trying to install the same bit of code over and over again. 

I was actually running a dummy test on the installer to see how it would work on the large update of V445.
