### ISSUE TITLE
Add support for `data-request-url` in the data attributes AJAX API

### ISSUE THREAD

**Issue by Rike-cz** [octobercms/october#4002]
This is only question, by now. Is there any reason for "locking" request URL to this page only? Security reason? I would like to set it like other parameters, e.g. via html data-request-url attribute.
https://github.com/octobercms/october/blob/826e72d3a969c2307e83e59c28056b26e488723c/modules/system/assets/js/framework.js#L115

**Comment by Rike-cz** [comment]
@LukeTowers I know that, but data-* attribute missing in this case (for me). I can send PR, if you want.

**Comment by LukeTowers** [comment]
What is the use case?

**Comment by Rike-cz** [comment]
I use it when I need to call (AJAX) service of non-OctoberCMS Laravel based api.

**Comment by LukeTowers** [comment]
Issues don't get closed until the fix is merged into master, at which point Github automatically closes them.

**Comment by Rike-cz** [comment]
I found the fix in version 447, so I was confused, sorry.

**Comment by LukeTowers** [comment]
Fixed in https://github.com/octobercms/october/pull/4012
