### ISSUE TITLE
Complaint about a paid plugin from the marketplace

### ISSUE THREAD

**Issue by linlan84** [octobercms/october#4003]
I bought a plugin a few weeks ago and around 90% of the plugin does not work at all. I left a support message found here: https://octobercms.com/plugin/support/uxms-sentry/most-of-the-plugin-doesnt-work-in-2018

2 weeks have passed and the author hasn't replied back to confirm if they are going to fix the plugin or not?

Could the admins have words with the author. As I feel it's really bad to sell a plugin where around 90% of it is completely broken and doesn't work at all.

**Comment by LukeTowers** [comment]
Send an email to hello@octobercms.com and they should be able to look into this for you.

**Comment by linlan84** [comment]
Done, have sent an email to that address, please could you ask whoever is meant to check it to look out for my email. Thanks luke.
