### ISSUE TITLE
Declaration of Illuminate\View\Factory::composer($views, $callback) must be compatible with Illuminate\Contracts\View\Factory::composer($views, $callback, $priority = NULL)

### ISSUE THREAD

**Issue by bkrajendra** [octobercms/october#4009]
Just tried Updating my 443 ocms with latest 445 and Im getting error on update screen

```
Update failed
{ "message": "Declaration of Illuminate\\View\\Factory::composer($views, $callback) must be compatible with Illuminate\\Contracts\\View\\Factory::composer($views, $callback, $priority = NULL)", "exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException", "file": "/home/iocarein/public_html/vendor/laravel/framework/src/Illuminate/View/Factory.php", "line": 14, "trace": [] }

```

**Comment by w20k** [comment]
Don't use dev branch before the new bleeding edge fix will be released.

**Comment by LukeTowers** [comment]
@w20k this is unrelated to the other problem. 

@bkrajendra what plugins do you have installed? This is occurring because you have multiple versions of Laravel included in your installation. The specific change that is throwing your error was https://github.com/laravel/framework/commit/19fcecfc782cb7fe0dea6f8a293e167cfb1bf38d and was a part of the 5.5 upgrade. The issue is probably coming from a plugin that has a vendor directory that includes one or more of Laravel's core packages at a version earlier than 5.5

**Comment by pbsmultimedia** [comment]
+1

**Comment by bkrajendra** [comment]
As I have checked this related to few plugin that are using Laravel 5.5 or earlier.
**vdomah-excel** and **eugenetolok-telegram** are the affected plugins

I used simple technique on my production server without disturbing anything.
Moved all plugins to a folder outside octobercms then started copying each plugin folder one by one. and finally got hold of plugin that was throwing exception.

Little old school but solved my issue in few minutes.

**Comment by w20k** [comment]
@bkrajendra, could you post here plugin name for those who might have the same issue. And, I suppose, close this issue.

**Comment by LukeTowers** [comment]
@bkrajendra another person has reported issues with vdomah-excel, will look into solutions

**Comment by setianke** [comment]
@LukeTowers would like to report the issue oocures with nevets-paypalipn as well

**Comment by LukeTowers** [comment]
@setianke report it to the plugin author and if they don't respond, send an email to hello@octobercms.com to have the plugin taken down.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by flyingbaba** [comment]
+ 1

**Comment by LukeTowers** [comment]
@flyingbaba 

- 2

**Comment by flyingbaba** [comment]
Ok, I wanted to just add +1 on that. 
Had this issue, in my case the solution was to update third party service providers. Simply by running `composer update` in my plugin directory solved this issue.
