### ISSUE TITLE
Media Manager creates only PNG thumbnails

### ISSUE THREAD

**Issue by Rike-cz** [octobercms/october#4013]
Each created thumbnail in Media Manager is PNG now.

It's feature or bug? I think for JPEG would be better to have JPEG tumbnails, maybe for BMP too. GIF and PNG would stay as is - PNG thumbnail.

**Comment by Rike-cz** [comment]
@LukeTowers So feature or bug?

**Comment by LukeTowers** [comment]
meh, not really either. If you want to you could propose a PR to retain the file type when creating thumbnails.

**Comment by Rike-cz** [comment]
Fixed in this PR: https://github.com/octobercms/october/pull/4011/commits/a23a3ec80951378239aa365cb7094725e61bae37
