### ISSUE TITLE
Ajax backend partial not found but exist.

### ISSUE THREAD

**Issue by PrestaSafe** [octobercms/october#4024]
Hello i've a problem with the ajax backend partial rendering. 
I've mad a plugin witch rendering partial vues. 
I've a partial vue existing, but october tell me is not found... 

##### Expected behavior
replace partial vue in ajax with AJAX handler

##### Actual behavior
Error: 
```
"The partial '_paiment_tab.htm' is not found." on line 91 of /Users/guillaume/Sites/october/modules/system/Traits/ViewMaker.php
```

##### Reproduce steps
So, in my plugin i do a makePartial like this: 
```
$this->vars['payment_tab'] = $this->makePartial('$/prestasafe/erp/models/invoice/_payment_tab.htm');
```

and place it in a vue:

```
 <div id="paiment-tab" class="tab-pane">
            <?= 
                $payment_tab;
             ?>
        </div>
``` 
It works fine. 

But, when i want to update this partial with ajax:
there is my ajax call: 
```
 <input 
                    type="button" 
                    data-request="onAddPaiment"
 
                    data-request-update="paiment_tab: '#paiment-tab'" 
                    class="btn btn-primary" name="add_paiement" id="add_paiement" value="Ajouter">
```
And the method in my backend controller: 

```
public function onAddPaiment()
    {
        $montant 	= Input::get('montant');
        $montant 	= str_replace(',','.',$montant);
        $type 		= Input::get('paiement_type');
        $date 		= Input::get('date_addpaiement');
        $id_invoice = (int)Input::get('id_invoice');
        $data 		= array('id_invoice' => $id_invoice, 'type' => $type, 'montant' => $montant, 'date' => $date);
        DB::table('prestasafe_erp_invoice_paiements')->insert($data);
        
        $this->vars['invoice'] = InvoiceModel::findOrFail($id_invoice);
        return [
            'paiment_tab' => $this->makePartial('$/prestasafe/erp/models/invoice/_payment_tab.htm')
        ];
    
    }
```

The php works well, but i've this error message: 

```
"The partial '_paiment_tab.htm' is not found." on line 91 of /Users/guillaume/Sites/october/modules/system/Traits/ViewMaker.php
```

When i go into this code and make a dump:
i've modified the code for testing like this:
```
 public function makePartial($partial, $params = [], $throwException = true)
    {
        $notRealPath = realpath($partial) === false || is_dir($partial) === true;
        if (!File::isPathSymbol($partial) && $notRealPath) {
            $folder = strpos($partial, '/') !== false ? dirname($partial) . '/' : '';
            $partial = $folder . '_' . strtolower(basename($partial)).'.htm';
        }

        $partialPath = $this->getViewPath($partial);
        dump($partialPath);

        if (!File::exists($partialPath)) {
            if ($throwException) {
                throw new SystemException(Lang::get('backend::lang.partial.not_found_name', ['name' => $partialPath]));
            }

            return false;
        }
        dump('file exists !');
        die();
        return $this->makeFileContents($partialPath, $params);
    }
```

there is the response: 
<img width="1186" alt="capture d ecran 2018-12-30 a 20 39 54" src="https://user-images.githubusercontent.com/4788787/50550554-1e432500-0c73-11e9-9da0-9cd8a210aff6.png">

I dont really understand. 
 

##### October build
443

Thanks for this really great CMS. Hope my english is not so bad.

**Comment by LukeTowers** [comment]
> "The partial **'_paiment_tab.htm'** is not found."
Your partial is called `_payment_tab.htm`, not `_paiment_tab.htm`

**Comment by PrestaSafe** [comment]
Ok thanks to you but it's not working too. 
The path should be: 
/Users/guillaume/Sites/october/plugins/prestasafe/erp/models/invoice/_payment_tab.htm
but the path is: _payment_tab.htm

<img width="947" alt="capture d ecran 2018-12-30 a 22 51 48" src="https://user-images.githubusercontent.com/4788787/50551720-a7fbee00-0c85-11e9-88a7-9e3cfb188fe2.png">


There is a prefix to put or something else in the data-request-update ? 

```
<input type="button" 
                    data-request="onAddPaiment"
                    data-request-update="{{PREFIF}}payment_tab: '#payment_tab'" 
                    class="btn btn-primary" name="add_paiement" id="add_paiement" value="Ajouter">
```

I precise that i'm in a backend controller.
