### ISSUE TITLE
Laravel artisan command make:job doesn't work as expected 

### ISSUE THREAD

**Issue by alpapan** [octobercms/october#4026]
Hello

When trying to user artisan the laravel way (for example make:job), it complaints 

```
  [RuntimeException]
  Unable to detect application namespace.
```

##### Reproduce steps

You install any official way and the result will be the same

```
curl -s https://octobercms.com/api/installer | php
grab composer.json test and server.php from github
composer install
```
or
```
git clone [...] (from master)
```
or
```
composer create-project october/october myoctober
```
or
```
composer create-project october/october myoctober-dev dev-master
```
**Any of the above and then:**
```
composer update
composer dumpautoload
composer diagnose
```

NB: i'm on cygwin windows, not that should make a difference...

This is not a fatal bug for me but it is a bug nonetheless because it breaks artisan so I'm reporting it... 

FWIW, there are no errant commas (the only reported solution on stackexchange) I can see in the composer.json (and diagnose/validate would report it anyway).

I finally managed to track it down though:

the composer.json needs these psr-4 configuration variables added (including the classmap from the october git).

```
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
      "classmap": [
          "tests/TestCase.php",
          "tests/UiTestCase.php",
          "tests/PluginTestCase.php"
      ],
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
```

I would make a pull request if I knew how but the fix is pretty straightforward...

thank you....
alexie

**Comment by LukeTowers** [comment]
Those laravel scaffolding commands aren't meant to work in October because of the concept of plugins holding the application logic instead of the root application itself holding that logic. See https://octobercms.com/docs/console/scaffolding#scaffold-create-command for a list of scaffolding commands currently supported. The addition of more would be appreciated however.

**Comment by alpapan** [comment]
Yeap I saw that link

Ok, perhaps in meantime

A) we could make a note on the documentation (as per your wording) so that people don't waste time wondering why?

B) suggest that people add their plugin folder instead of /app? If that is a good idea

C) both...

a

**Comment by alpapan** [comment]
(actually B wouldn't work)

**Comment by LukeTowers** [comment]
Feel free to submit a PR to the docs with the note explaining the situation

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
