### ISSUE TITLE
Idea - Separate parts of the core in standalone packages

### ISSUE THREAD

**Issue by prhost** [octobercms/october#4027]
It would be just a suggestion, I could not find another place to talk about.

OctoberCMS goes beyond a simple CMS, there are a lot of good things that make it up, I've tried re-creating/copying it on other projects and it's never been able to do as well as octobercms, it's well organized and almost everything is modular. Think of how symfony components and laravel illuminate work, separate into smaller packages, can be used for other things.

I do not know if this seems a bad thing and if it goes against the ideas of the octoberCMS team, but I see it as something good, octobercms is already opensource, making it easier to get through other paths like that is even better, a classic example is symfony/yaml or symfony/console, how many people in the world do they use? Think about it.

An example of a simple part of october that for me was useful and I ended up separating it into a package https://github.com/prhost/composer-vendor-merge

P.S. Sorry for copying you XD

**Comment by LukeTowers** [comment]
October is already modular to an extent, it's divided into the October\Rain library and the three core "October Modules" (Backend, CMS, & System). Further breaking it down the October\Rain library is split into it's separate packages (like october/auth, etc) although that will be changing shortly and we'll be keeping the October\Rain library all in one piece.

We're not really looking at reorganization of the project, but if you have specific suggestions feel free to make them.

> P.S. Sorry for copying you XD

No worries :) Just don't go ripping the whole thing off and profiting off of it while leaving us with no income ;)

**Comment by prhost** [comment]
> We're not really looking at reorganization of the project, but if you have specific suggestions feel free to make them.
* Ajax request API > https://octobercms.com/docs/ajax/introduction
* Version and migration control system > https://octobercms.com/docs/plugin/updates
* Form rendering via yaml
* Model relations definitions by array and yaml config > https://octobercms.com/docs/backend/relations
* Extraordinary Traits > https://octobercms.com/docs/database/traits
* File Attachments > https://octobercms.com/docs/database/attachments
* Purgeable > https://octobercms.com/docs/database/behaviors#purgeable
* Media Manager similar to Elfinder.
* Parser service > https://octobercms.com/docs/services/parser
* Incredible Form Widgets > https://octobercms.com/docs/backend/widgets#form-widgets
* Twig extensions, there's a lot of good stuff here like `put`, `placeholder`, `content`, `partial`, `flash`, `components` and assets like `scripts` and` styles`
* Combiner assets, I do not even need to explain > https://octobercms.com/docs/api/system/classes/combineassets
* Theme template structure > https://octobercms.com/docs/cms/themes#template-structure
* Organization and modularization system that exists in modules and is similar to plugins, this is very good and has potential to become something great along with composer, similar to Puli.

and there is a lot more to be explored, I see Octobercms as something very big, a development tool not only for website, for big and robust system development, there is an idea of ​​October Enterprise, see https://www.scriptcase.com.br

I know a lot of one depends on the other and that would not be an easy task to separate them, but it would be really cool to see this happen (:

> No worries :) Just do not go ripping the whole thing off and profiting off it while leaving us with no income;)

Stay calm, I'll split in half hehe

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
