### ISSUE TITLE
"Unsupported operand types" on line 449 of /modules/backend/widgets/Form.php

### ISSUE THREAD

**Issue by PubliAlex** [octobercms/october#4028]
Here is my field .yaml :

    fields:
        is_variant:
            label: Is variant
            span: full
            type: switch
        backend_form:
            label: Backend form
            span: auto
            type: dropdown
            dependsOn:
                - is_variant
         
On my model, I have the following function : 

    public function getBackendFormOptions()
    {
        if($this->is_variant == true) {
            $options = [
                'text' => 'Text',
            ];
        } else {
            $options = [
                'dropdown' => 'Dropdown',
                'radio' => 'Radio',
                'checkboxlist' => 'Checkboxes',
            ];
        }
        return $options;
    }

When I change the value of is_variant field, it display the following popup as an ajax error : 

> "Unsupported operand types" on line 449 of /modules/backend/widgets/Form.php

Checked the doc several time, my code seems correct and, in fact, it works when I first enter the form (without ajax refresh) but the ajax refresh trigger the above error.

*Important note* : I'm on the bakend popup provided by the relation manager.

Regards,

Alex

**Comment by LukeTowers** [comment]
What version of PHP are you using? What build of OctoberCMS are you using? The line in question has nothing to do with dependsOn, it's got something to do with something in your install that's hooking to the `backend.form.refresh` event: https://github.com/octobercms/october/blob/master/modules/backend/widgets/Form.php#L449

**Comment by PubliAlex** [comment]
Sry for the lack of informations.

PHP version : 7.0.16
October version : 443

Thank you for the answer, I disabled plugins one by one to see what could make dependsOn to bug, and it was caused by the [OFFLINE.Clockwork](https://octobercms.com/plugin/offline-clockwork) plugin. Disablig it resolve the issue.
