### ISSUE TITLE
Speeding up the loading of web pages using October's AJAX by using rel-preload

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4030]
To speed up October CMS web pages that use October's AJAX code:

```html
{% framework extras %}
{% scripts %}  
```

A developer could add link `rel-preload` which **must be loaded inside the `<head>` tag** to speed up the loading of the web page(s) that use October AJAX by reducing the wait times for the injected files. Below shows the following method:

## Method to Speed up October's AJAX web pages

```html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Correct Method 1</title>

<link rel="preload" href="https://example.com/modules/system/assets/css/framework.extras-min.css" as="style">

<link rel="preload" href="https://example.com/modules/system/assets/js/framework.combined-min.js" as="script">

</head>

<body>

..

{% framework extras %}
{% scripts %} 

</body>
</html>
```

which automatically turns into into:

```html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Correct Method 2</title>

<link rel="preload" href="https://example.com/modules/system/assets/css/framework.extras-min.css" as="style">

<link rel="preload" href="https://example.com/modules/system/assets/js/framework.combined-min.js" as="script">

</head>

<body>

..

<script src="/modules/system/assets/js/framework.combined-min.js"></script>
<link rel="stylesheet" property="stylesheet" href="/modules/system/assets/css/framework.extras-min.css">

</body>
</html>
```

After talking to Luke, he suggests creating a PR and injecting the extra `rel-preload` code lines into the `<head>` section automatically.

Please note Luke said:

> `{% framework %}` is typically supposed to be the head anyways

However I know lots of developers actually adding `{% framework extras %}` and `{% scripts %}` to the bottom of the web page. So needs some extra discussion about that.

The `rel-preload` link tags must be added into the `<head>` section only.

Not sure how to code the pr for this right now, but for now have opened up the github issue for discussions.

**Comment by ayumihamsaki** [comment]
Creating:

```html
{% framework extras preload %}
{% scripts preload %}
```  

Is a good idea, agree does place the burden on the developer.

Another idea is directly injecting the dom:

```html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Test</title>
</head>

<body>

<script>
document.getElementsByTagName("head")[0].innerHTML += "<link rel=\"preload\" href=\"/modules/system/assets/css/framework.extras-min.css\" as=\"style\">";
document.getElementsByTagName("head")[0].innerHTML += "<link rel=\"preload\" href=\"/modules/system/assets/js/framework.combined-min.js\" as=\"script\">";
</script>

</body>
</html>
```

**Comment by ayumihamsaki** [comment]
(Don't close PR's open on this one)
