### ISSUE TITLE
filterFields : red asteric not added to fields that are required dynamically

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4031]
Lets imagine that working base scenario.

**My fields.yaml file**

    myboolean:
        label: My boolean
        type: switch

    myfield:
        label: My field
        type: dropdown
        dependsOn:
            - myboolean

**The filterFields method in my model**

    public function filterFields($fields, $context = null) {
        if($fields->myboolean->value == true) {
            $fields->myfield->hidden = true;
        }
    }

**The field correctly hide dynamically when the value of my boolean is true**

##### Expected behavior

Now, if I replace my filterFields method by this : 

    public function filterFields($fields, $context = null) {
        if($fields->myboolean->value == true) {
            $fields->myfield->required = true;
        }
    }

I expect that the field would display the little red asterix that indicate to the user that the fiel is required. I know it's just for display and will not really make the field really required (have to add some code in beforeValidate in order to alter the $rules array).

##### Actual behavior
Actually, no asterix are displayed at all when the form dynamically refresh (it works on initial state if I edit an already existing model)

##### October build
443

**Comment by LukeTowers** [comment]
For future reference you can add the astrisk in with `cssClass: 'is-required'`
