### ISSUE TITLE
Taglist style regression

### ISSUE THREAD

**Issue by jajacobs** [octobercms/october#4035]
Taglist select element visible after update.

Build 443:

![image](https://user-images.githubusercontent.com/8701133/50689934-f7357c00-1001-11e9-9d45-8d45a342337a.png)

![image](https://user-images.githubusercontent.com/8701133/50690006-34017300-1002-11e9-943b-a294ae99475a.png)

Build 446:
![image](https://user-images.githubusercontent.com/8701133/50689965-16cca480-1002-11e9-80dc-07887325c330.png)

![image](https://user-images.githubusercontent.com/8701133/50690017-3fed3500-1002-11e9-87d4-49c672c0875e.png)

**Comment by w20k** [comment]
@jajacobs, will look at it. Do you have an example despite? Might speed up process 😄Thanks!

**Comment by w20k** [comment]
@jajacobs, paste your taglist from yaml. Couldn't reproduce your bug. Works fine for me.

Screenshot:
<img width="1306" alt="screenshot 2019-01-05 at 20 57 12" src="https://user-images.githubusercontent.com/1053320/50728032-98b8ec80-112c-11e9-920c-1f08b98f0cad.png">

**Comment by LukeTowers** [comment]
@jajacobs also please post your browser & version, as well as the error message in the yellow triangle

**Comment by jajacobs** [comment]
Fixed in #4040
