### ISSUE TITLE
Minor UI bug - tags input field

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#4040]
**Is it custom or core bug?**

Build 443 - Correct
![bug443](https://user-images.githubusercontent.com/2959112/50762764-3a942280-126e-11e9-8f8a-a928a345ef70.JPG)

Build 446 - Incorrect
![bug446](https://user-images.githubusercontent.com/2959112/50762787-50094c80-126e-11e9-94bf-84fcf8e07e68.JPG)

**Comment by w20k** [comment]
@gergo85, it's core. Already seen this one during testing.

**Comment by gergo85** [comment]
Thank you for your idea! I added the "!important" to the "border: 0;" and the problem is solved. Will I create a PR?

**Comment by w20k** [comment]
I did the same @gergo85, but that's not the issue here. Could describe in comments `how & where` to monkey patch it, for now?
Will look at this issue in a few days, hopefully 😄

**Comment by w20k** [comment]
@gergo85, @LukeTowers - found the cause. I think we have to revert `StylesheetMinify.php`. 
Minification rule was an issue here.
```
// Converts all zeros value into short-hand
$css = preg_replace('/0 0 0 0/', '0', $css );
```

@Samuell1  - could you make PR to revert those changes for now?

**Comment by Samuell1** [comment]
@w20k Maybe we can revert just that line?

**Comment by w20k** [comment]
We could @Samuell1, but there is also this issues with recompiled assets, that we currently face: https://github.com/octobercms/october/pull/4038
The newlines 😄

**Comment by Samuell1** [comment]
@w20k revert PR is here i dont know why it added other commits but they are empty, https://github.com/octobercms/library/pull/369

**Comment by w20k** [comment]
@Samuell1, thanks a lot! I think we'll have to deal with minification differently 😿

**Comment by mjauvin** [comment]
I still don't understand why we see all those revert commits.

**Comment by w20k** [comment]
There is only one for asset compiler 😄

**Comment by LukeTowers** [comment]
@Samuell1 @mjauvin @w20k the extra commits are fine, I always just use the squash and merge feature anyways which takes the changes and squashes it into one commit.

**Comment by w20k** [comment]
@gergo85, could you test with the latest assets?

**Comment by gergo85** [comment]
@w20k It works again, thank you! :)
