### ISSUE TITLE
Meta description field switched with settings description field (CMS pages)

### ISSUE THREAD

**Issue by Wachem** [octobercms/october#4042]
- OctoberCMS Build: 446
- PHP Version: 7.1.25

### Description:
After updating from 443 to 446 the 'meta description' field is no longer filled. Instead the 'settings description' field contains the value of the 'meta'. However the value is still available in the TWIG syntax. It seams like the fields are switched? See screenshots below:

![image](https://user-images.githubusercontent.com/6443046/50820924-34fe1180-132e-11e9-9532-0f95da1ac5e8.png)
![image](https://user-images.githubusercontent.com/6443046/50820939-3f201000-132e-11e9-9cb8-5794c9c02ee2.png)
![image](https://user-images.githubusercontent.com/6443046/50821086-94f4b800-132e-11e9-8161-8ae73516c20d.png)

**Comment by w20k** [comment]
@Wachem, could be related to the latest update of translate-plugin. Could you look at those issues: https://github.com/rainlab/translate-plugin/pull/436 & https://github.com/rainlab/translate-plugin/pull/367#issuecomment-451887154

**Comment by Wachem** [comment]
> @Wachem, could be related to the latest update of translate-plugin. Could you look at those PRs:
> 
> * [rainlab/translate-plugin#436](https://github.com/rainlab/translate-plugin/pull/436)
> * [rainlab/translate-plugin#367](https://github.com/rainlab/translate-plugin/pull/367)

I checked and even without the translate plugin, still the same behavior...

**Comment by w20k** [comment]
Tried with a clean install - couldn't reproduce your bug, nor with an upgraded version. Everything works as expected.

**Comment by Wachem** [comment]
Tried also with a clean install. The bug has been resolved. My appologies.
