### ISSUE TITLE
Marketplace: The result of plugin builds should be visible to the author

### ISSUE THREAD

**Issue by tobias-kuendig** [octobercms/october#4043]
When installing the offline.mall plugin via `php artisan plugin:install offline.mall` it's vendor directory is missing.

As I understand the build server removes the `composer.*` files and publishes the `vendor` directory with the plugin.

Obviously something isn't right with [my plugin's composer setup](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/composer.json). 

It seems like this has happened before:

* https://github.com/octobercms/october/issues/3253
* https://github.com/octobercms/october/issues/3617

What can I do to find the problem? If there is a problem during the build process there should be a visible warning on the `Author` page in the marketplace where one can trigger the builds.

**Comment by tobias-kuendig** [comment]
I was able to narrow the problem down to the `"phpunit/phpunit": "^7.2"` dev dependency. As soon as I remove it, the `vendor` folder is included in the resulting build.

I changed the issue title to better reflect the actual problem.

I think the following points would greatly improve the marketplace dev experience:

* [ ] In case of an error, display a warning on the plugin build page
* [ ] Maybe even add an option to be notified about failed builds since most devs will trigger them via GitHub and won't be using the marketplace website very often
* [ ] Save the `stdout` of the build process and display it on the build page so the developer has some insight in what went wrong

**Comment by daftspunk** [comment]
Thanks for the suggestion and for linking up the issues, we will look at adding more feedback to the build process in the future.

**Comment by tobias-kuendig** [comment]
I'm having the same issue again with a plugin that has only one dependency I cannot remove:

https://github.com/OFFLINE-GmbH/oc-opening-hours-plugin/blob/master/composer.json

The build completes without any errors but the marketplace version installed via `php artisan plugin:install offline.openinghours` contains no `vendor` directory.

Do you have any more insight into this issue?

**Comment by tobias-kuendig** [comment]
Any news/ideas on how to debug this problem? I don't have the plugin online in the marketplace because of this bug.

**Comment by LukeTowers** [comment]
@tobias-kuendig only way to do it right now is to use the hello@octobercms.com email address to get direct support.

**Comment by tobias-kuendig** [comment]
It looks like you cannot user `require-dev` directives in your composer.json, even empty ones.

This commit fixed the issue for our plugin:
https://github.com/OFFLINE-GmbH/oc-opening-hours-plugin/commit/f1e8db2c2b2ac0bd2d368da19c7d6c5f1656e53f

**Comment by daftspunk** [comment]
The server only has a few special constraints on composer for security reasons, but generally, if the composer command works for you locally it should work on the server. This type of thing is best to be reported via email so we can investigate on an individual plugin basis. Feel free to send us an email to hello@octobercms.com if it's still a problem!
