### ISSUE TITLE
Problem SoftDelete when extends October\Rain\Auth\Models\User

### ISSUE THREAD

**Issue by prhost** [octobercms/october#4046]
- OctoberCMS Build: ###https://github.com/octobercms/library/commit/d63d368d356b5df19e3b012bbe472028386e3d1d
- PHP Version: 7.2
- Database Engine: Mysql

### Description:
The trait SoftDelete is in the wrong place, it should be in `October\Rain\Auth\Models\User` and not `Backend\Models\User` since the `October\Rain\Auth\Manager` class uses `October\Rain\Auth\Models\User`

### Commit  October\Rain\Auth\Manager using withTrashed():
https://github.com/octobercms/library/commit/d63d368d356b5df19e3b012bbe472028386e3d1d#diff-df60d76a3e7691538d86e90e7049e442R411

**Comment by w20k** [comment]
@prhost, what build version do you use? 446?
Could you provide a simple example?

**Comment by LukeTowers** [comment]
Technically speaking the code in the RainAuthManager should actually exist within the BackendAuthManager class instead. Feel free to make a PR to correct this by reverting the change in the rain AuthManager and adding an overriding `check()` method to the backend AuthManager to handle it. Perhaps @tobias-kuendig could help with this.

**Comment by LukeTowers** [comment]
@tobias-kuendig I'm saying we should keep the trait in the backend auth library and implement the softdelete / not softdelete support in the backend auth class. As a note, I think we'll have to implement it in the other methods too because lots of people are having issues with the 446 upgrade.

**Comment by tobias-kuendig** [comment]
Just to make sure I understand the goal of this: The rain auth manager should be completely unaware of the SoftDelete trait. So no calls to `withTrashed` should be in there. All of these checks should be handled only in the backend auth manager. Is this correct so far?

> As a note, I think we'll have to implement it in the other methods too because lots of people are having issues with the 446 upgrade.

Like the `findUserById` or `findUserByLogin` methods? Are there any bug reports regarding the upgrade issues? What problems are people experiencing exactly?

**Comment by w20k** [comment]
@tobias-kuendig, as far as I know, this is only one issue related to the 446 build problems and `SoftDelete`.
There is a lot of issues were plugins use different Laravel version...that's the top story right now. And minor UI bugs.

**Comment by LukeTowers** [comment]
@tobias-kuendig That's correct. The other issue that happens when upgrading to 446 is if the upgrade fails, they're locked out of their backend because it kicks them back to the login page but the migration hasn't been run yet and they can't run the migration unless they login but they can't login until the migration has been run.

**Comment by w20k** [comment]
@LukeTowers, I think softdelete issue was related to 445 build only.

**Comment by LukeTowers** [comment]
@w20k nope, I've had people upgrading to 446 reporting the issue. We only have the non-softdelete auth support added to the check method, not the login methods.

**Comment by tobias-kuendig** [comment]
I have implemented a fix to the library code that solves the login issues:
https://github.com/octobercms/library/compare/develop...OFFLINE-GmbH:softdeletes-fix

1. Add `withTrashed` to the `createUserModelQuery` method
2. Add `checkDeleted` method
3. Call `checkDeleted` everytime a user was fetched

I'll see that I can move all these checks to the backend auth manager and remove the dependency on the `SoftDelete` trait somehow.

**Comment by tobias-kuendig** [comment]
This would be my proposal:

https://github.com/octobercms/library/pull/371 and https://github.com/octobercms/october/pull/4051

### Library
* Added `validateUserModel` method to reject invalid models
* Removed dependency on `SoftDelete` trait from library code

### Backend 
* Overwrite `createUserModelQuery` to return all models `withTrashed`
* Use the new `validateUserModel` method to perform the `deleted_at` check manually

With this setup...

* I can login when the `deleted_at` column does not exist
* I can browse the backend when the `deleted_at` column does not exist
* I cannot login when the `deleted_at` value is in the past
* I am redirected to the login page when the `deleted_at` value is in the past

**Comment by LukeTowers** [comment]
@tobias-kuendig why do you specify 

> in the past

?

Shouldn't we invalidate them if they've been deleted at all?

**Comment by LukeTowers** [comment]
@tobias-kuendig sure, technically speaking, but why would someone have deleted_at set to a date in the future on purpose? Not to mention it's not possible to intentionally do that by default right now, which means the only way that would happen right now is with a time zone conflict/issue between the app server and the DB server

**Comment by tobias-kuendig** [comment]
In this case we could simply get rid of the [`$user->deleted_at->lt(now())` check](https://github.com/octobercms/october/pull/4051/files#diff-3eed7cb4fbe54b2728183b9259b1ef27R188) and invalidate every user that has something set as `deleted_at`.

Want me to remove it?

**Comment by LukeTowers** [comment]
Sure, lets go with that. I can see the theoretical feature of choosing when a user gets deleted, but I think that would probably be better suited for a more specific column as the vast majority of the time any future deleted_at dates would be due to timezone mismatches between application and database servers.

**Comment by LukeTowers** [comment]
Great! @w20k please test the related PRs
