### ISSUE TITLE
Settings sidebar menu doesn't expand on single click

### ISSUE THREAD

**Issue by rohit-bhati** [octobercms/october#4047]
- OctoberCMS Build: 446 
- PHP Version: 7.1.12
- Database Engine: MySQL
- Plugins Installed: 

### Description:
1. When settings menu is clicked, the sidebar menu items have collapsed sign(>) which should be the opposite. When clicking on them it doesn't collapse instead it collapse and expand.
2. Secondly, when selected any one of the option, it loads the view and all the menu items collapse (except the one expanded in first step). Then if we try to expand it, it doesn't work the way it should.

### Steps To Reproduce:
I think I described the steps in description. Thanks.

**Comment by w20k** [comment]
Confirmed, as a pre-step, you should first collapse single/all settings.

**Comment by w20k** [comment]
Fixed PR: #4080
