### ISSUE TITLE
Top Menu Icons Disappear

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#4052]
- OctoberCMS Build: 446
- PHP Version: 7.2.4
- Database Engine: sqlite
- Plugins Installed:
![image](https://user-images.githubusercontent.com/3897579/51052204-03fc3600-15e7-11e9-8b21-bd5a6cf417e5.png)

Here's the styling issue that appeared on the newest build:

![october_446_bug](https://user-images.githubusercontent.com/3897579/51052241-24c48b80-15e7-11e9-82de-ae58485765e0.gif)

Did anyone experience the same?

**Comment by LukeTowers** [comment]
@GinoPane I've been experiencing that issue too. I don't know what caused it though. @ayumihamsaki @Teranode @w20k could one of you guys look into this? Also @GinoPane could you see if you could find the source of the problem?

**Comment by w20k** [comment]
@GinoPane, @LukeTowers - as a monkey patch:
`.svg-icon-container.svg-active-effects img.svg-icon {-webkit-backface-visibility: hidden;...`

**Comment by ayumihamsaki** [comment]
Hi I have been seeing this issue for a little while, the reason the icons are being hidden is by an Ad-Blocker in my case the svg icons filename is in the blacklist of some ad-blockers. Do you notice it with the svg icons only?

`content-icon.svg`

The `content-icon` is the part being blocked.

Also the folder of the plugin maybe blacklisted as well e.g. 

`/plugins/example/gdpr/assets/images/content-icon.svg`

There is a blacklist of: `gdpr/assets/*`

This maybe some of the reasons why the icon do not display.

Note: Brave, Firefox and Safari have Blocking built into their latest Browsers and then the add-on of ad-blocker plugins.

There maybe other issues with regards to this problem, but for me I just changed the filenames and folders and it fixed the problem.

![untitled](https://user-images.githubusercontent.com/17784082/51078763-acc39780-16b2-11e9-88c5-54f040cda20c.png)

**Comment by ayumihamsaki** [comment]
If you confirm that css will fix it I will add it to this pr: https://github.com/octobercms/october/pull/4038

**Comment by LukeTowers** [comment]
Hmm, I do use an adblocker (uBlock origin), but it always starts working again after hovering over the empty icons.

**Comment by w20k** [comment]
@LukeTowers, @ayumihamsaki, @GinoPane - could you try my fix? If it works.

**Comment by ayumihamsaki** [comment]
Been looking into this and if you keep clicking on the "cms" button October will fail on loading - usually on the third time.

The issue seems to be from the Javascript, it is loading half the bar and then moving it fully. You probably dont see it happening in real-time - but that seems to be how the icons are not getting shown. I got some screenshots of it happening:

![untitled-bug](https://user-images.githubusercontent.com/17784082/51084705-6dcf2980-1726-11e9-90b0-fbff0086101e.png)

Then goes into this:

![untitled-bug-2](https://user-images.githubusercontent.com/17784082/51084720-91926f80-1726-11e9-8450-952e07c9bd2b.png)

Which ends into this:

![untitled-bug-3](https://user-images.githubusercontent.com/17784082/51084742-f8178d80-1726-11e9-803d-81238b51110f.png)

Hard to pin point the error, but this seems to be the reason why you are seeing blank icons.

* With Ad-Blocker turned off (for testing)

**Comment by ayumihamsaki** [comment]
@w20k @LukeTowers I think I have found a solution to this issue:

The file found here: https://github.com/octobercms/october/blob/master/modules/backend/layouts/_mainmenu.htm

Change line 7:

`<div class="toolbar-item toolbar-primary">`

into

`<div class="toolbar-item toolbar-primary" style="width:100%; padding-right:130px;">`

Change line 40:

`<div class="toolbar-item" data-calculate-width>`

into

`<div class="toolbar-item"  style="max-width:130px; display:block; overflow:hidden; right:0; position:absolute;" data-calculate-width>`

If someone can confirm that works, will create a PR and add it properly into the CSS and not add inline styles.

The problem I found was that October CMS was making the `.toolbar-item` into two equal columns.

**Comment by ayumihamsaki** [comment]
Also spotted another issue while trying to fix this one, see here:

Error:

![untitled-bug-4](https://user-images.githubusercontent.com/17784082/51085562-39159f00-1733-11e9-8f9c-cd276a56fbfc.png)

Fix:

![untitled-bug-5](https://user-images.githubusercontent.com/17784082/51085564-3fa41680-1733-11e9-8d7c-3cef7b63a228.png)

Can fix both at same time.

**Comment by ayumihamsaki** [comment]
I want to add an extra issue that is connected to this issue see screenshot:

![untitled](https://user-images.githubusercontent.com/17784082/51086266-88140200-173c-11e9-83f0-d31ba4101bd6.png)

**Comment by ayumihamsaki** [comment]
Going to merge all the above fixes into PR 4038.

**Comment by w20k** [comment]
@ayumihamsaki, I'd do it in a separate one.

**Comment by ayumihamsaki** [comment]
ok thanks.

**Comment by ayumihamsaki** [comment]
@w20k @LukeTowers Whats the status of this issue, I'm seeing this error every single time I do a refresh of the web page while I'm building some plugins (current version 452). I thought this issue was fixed a few months ago, but seems to be still here. Seems to be slowing down the loading of the backend web pages?

**Comment by LukeTowers** [comment]
Which one @ayumihamsaki? There were a lot discussed in this thread. The backface visibility fixes the icons not showing up until hover and that is working AFAIK

**Comment by ayumihamsaki** [comment]
When I do a refesh of the backend I see this screen:

![untitled](https://user-images.githubusercontent.com/17784082/51086266-88140200-173c-11e9-83f0-d31ba4101bd6.png)

The top menu items on the right do not show straight away and the left column is very large. The web page takes around 10 -13 seconds to load and then the web page displays. It does this when I try to refresh the screen (not loading the web page without a refresh - that is fine).

I have done a full browser and server hard refresh and cleared the cached to see if makes a difference but problem still continues.

If I remember correctly w20k was doing a javascript fix on that side of things. I thought his fix got merged a few months ago, but maybe I am wrong.

Anyway, problem seems to happen when you try to do a refresh.

**Comment by ayumihamsaki** [comment]
When I do a refesh of the backend I see this screen:

![untitled](https://user-images.githubusercontent.com/17784082/51086266-88140200-173c-11e9-83f0-d31ba4101bd6.png)

The top menu items on the right do not show straight away and the left column is very large. The web page takes around 10 - 13 seconds to load and then the web page displays. It only does this when I try to refresh the screen. If I try to load the web page or the next web page without a refresh it's fine. This maybe why other Users are not reporting this issue?

I have done a full browser and server hard refresh and cleared the cached to see if makes a difference but problem still continues.

If I remember correctly w20k was doing a javascript fix on that side of things. I thought his fix got merged a few months ago, but maybe I am wrong.

Anyway, problem seems to happen when you try to do a refresh. I'm sure some javascript code is wrong somewhere and creating this issue and blocking the re-render of the web page in the backend - that's my theory.

**Comment by LukeTowers** [comment]
@ayumihamsaki please open a separate issue for that with as much information as you can gather on the problem

**Comment by GinoPane** [comment]
I saw it recently too when I installed a new plugin

**Comment by ayumihamsaki** [comment]
I'm thinking there are two small issues here:

## Sidebar Issue

I think to stop the sidebar from starting an extra large size and then re-sizes down just add the following css code:

```css
.layout-sidenav-container {
    width: 120px;
}
```

into

```css
.layout-sidenav-container {
    width: 120px;
    max-width: 120px;
}
```

Need to double check the max width size if it is `120px` or `150px` I can't remember ?

## Top Menu Bar Issue

I think this is an issue in the javascript code and nothing to do with any css or php code. I'm sure w20k did a pr fix on this but I can't find it? Would like to see his code and investigate further. It seems to load the load side and not the right side, do some kind of dom processing and then re-draw the whole top menu to the full width of the screen. I can't see why we can't just remove this and have the top menu bar load the full width of the screen at the start of the web page load and then do the processing to make it scroll.

There is another issue I opened a long time ago about trying to make the top menu bar scroll and work better, will link these two related issues to this one:

[Bug / Upgrade - Backend Navigation](https://github.com/octobercms/october/issues/2820)
[Can't access all backend menu items](https://github.com/octobercms/october/issues/1542)

Maybe a fix could try and sort out all these issues at the same time!

---

This is my theory to fix this issue it's made up of two separate issues.

**Comment by LukeTowers** [comment]
@ayumihamsaki please submit a separate issue for each issue. This issue was originally only for the SVG icons disappearing.

**Comment by ayumihamsaki** [comment]
@LukeTowers Ok I will open up another github issue. I think the bug I am seeing is not the same as the original problem in this issue.

**Comment by ayumihamsaki** [comment]
Admin's please don't close this issue! This issue I see all the time and I plan on fixing it.

I want to move the top navigation javascript into the following file:

```
modules/backend/assets/js/october-bottom-min.js
```

Then load it via `async` and that should stop this from render blocking the backend pages, when they are being loaded.

The reason I haven't created a PR for this is because I need this PR to be merged first: https://github.com/octobercms/october/pull/4516

Because that PR has created the `october-bottom-min.js` and `october-bottom.js` file set.

**Comment by LukeTowers** [comment]
@ayumihamasaki2019
