### ISSUE TITLE
Placeholder for select dropdown does not work without an empty option

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#4053]
- OctoberCMS Build: 446

Placeholder for select dropdown defined using "form-control custom-select" does not work without an empty option specified in the select options. 

For example, we have such select:

```
<select class = "form-control custom-select" data-placeholder="Select something">
	<option value="1">1<option>
	<option value="2">2<option>
	<option value="3">3<option>
</select>
```

It will initially look like this even when we don't select anything:

![image](https://user-images.githubusercontent.com/3897579/51075291-9578b000-169a-11e9-85f2-6485ffdba0ed.png)

On the other hand if we define it like this:

```
<select class = "form-control custom-select" data-placeholder="Select something">
	<option value=""><option>
	<option value="1">1<option>
	<option value="2">2<option>
	<option value="3">3<option>
</select>
```

It will work as expected:

![image](https://user-images.githubusercontent.com/3897579/51075319-e5f00d80-169a-11e9-9b1a-79e3ca87711f.png)

The reason of the issue is that option `allowClear: true` is missing from select2 initialization.

I'm going to submit a PR for this.

**Comment by GinoPane** [comment]
I've changed option name in description, because I used `allowEmpty` instead of `allowClear`.

**Comment by w20k** [comment]
It miss lead me a bit :)
