### ISSUE TITLE
Optional wildcard parameters are not supported

### ISSUE THREAD

**Issue by mariavilaro** [octobercms/october#4054]
- OctoberCMS Build: v1.0.446
- PHP Version: 7.1.11

### Description:
Optional wildcard parameters are not supported. So if you want to have a page that can accept no parameters (for example domain.com/category to show all categories products), and also a wildcard parameter (for example domain.com/category/subcategory/subsubcategory to show only the products for a category), you are forced to have two pages: something like all-products.htm with url "/category" and another exactly equal page category-products.htm with url "/category/:slug*"

### Steps To Reproduce:
Page category.htm with url = "/category/:slug?*"
attach a component that checks $this->param('slug') on the onRun method

### Expected behavior

with url: domain.com/category
$this->param('slug') = NULL

with url: domain.com/category/category1/subcategory1
$this->param('slug') = 'category1/subcategory1'

### Actual behavior

with url: domain.com/category
$this->param('slug') = NULL
$this->param('slug?') = '*'

with url: domain.com/category/category1/subcategory1
$this->param('slug') = NULL
$this->param('slug?') = 'category1/subcategory1'

### Fix

This is fixed in library PR https://github.com/octobercms/library/pull/363 and test are added for current and fixed behaviours in PR https://github.com/octobercms/october/pull/3964

**Comment by w20k** [comment]
@mariavilaro finally get to test everything once again!
