### ISSUE TITLE
OctoberCMS repeater: How to store index/id inside the json array

### ISSUE THREAD

**Issue by nolyboms** [octobercms/october#4056]
Hello everyone,

after 3 days of researching for a way to accomplish my need i thought its best to ask and hope to get an answer.

In this post 

https://github.com/octobercms/october/issues/2772#issuecomment-296411282

it is exactly described what i am trying to do.

I have a repeater in my backend form and the data gets saved in the database as a json like that:

<code>
"topics": [

	{
	    "topic_title": "timeslot 1",
	    "topic_description": "timeslot 1 descr",
	},
	{
	    "topic_title": "timeslot 2",
	    "topic_description": "timeslot 2 descr",
	},
],
</code>

What i would like to achieve is that the repeater items get indexed like that:

<code>
"topics": [

	{	
		"topic_id": "1",
	    "topic_title": "topic 1",
	    "topic_description": "topic 1 descr",
	},
	{
		"topic_id": "2",
	    "topic_title": "topic 2",
	    "topic_description": "topic 2 descr",
	},
],
</code>

In another github post https://github.com/octobercms/october/issues/2451#issuecomment-259804208 it is stated that this could only be achieved by manipulating the array with 

<code>
formBeforeSave()
</code>

But the information is already available in the code as 

<code>
$indexCount:

input type="hidden" name="___index_topics[]" value="2"
</code>

Can you please tell me how to get index/id into a repeater field so it gets stored inside the json array?

**Comment by LukeTowers** [comment]
@nolyboms could you please provide more information on why you need the index to be stored? It used to be stored (at least, that's what I remember) but it was removed because it made it overly complex to store that information in two ways.

**Comment by nolyboms** [comment]
@LukeTowers thank you for responding.
I am generating an API out of the OctoberCMS Backend which provides all data to be used by an vuejs website.
The API contains all information about different topics.
Each topic in the array needs to be identified with a unique id because the logic of the website allows users to send questions or participate on a survey which are assigned to the topic by its ID.
Hope i explained it well.

**Comment by LukeTowers** [comment]
@nolyboms hmm. If you have a need for a unique ID you should be using unique records with a RelationController, not a Repeater. The reason for this is that the "id" of a repeater is not unique, it's just an integer describing it's position within the array. If you really must have a unique ID then I recommend you look at adding to the data in `formBeforeSave()`, perhaps with a hidden `guid` field instead (and I would recommend a GUID for this if you went that route, not simply an integer).

**Comment by nolyboms** [comment]
@LukeTowers 
If i could get the integer which describes the position to be stored with the array that would be absolutely perfect. 

https://cl.ly/51aa6f2f043a

Since that was possible in a previous OctoberCMS version - do you have an idea on how to get that info and store it in the array? I am using the Builder plugin - is there maybe a way by adding a custom HTML attribute to the field?
I was thinking of something like (Key: value | Value: $indexCount).
But i might be thinking it too easy.

Would you please be able to point me to a starter script? Kind of desperate and brain-blocked after all the done research. -_-

**Comment by LukeTowers** [comment]
That number that you see is just straight CSS, it doesn't exist anywhere else. You'll notice that if you drag and reorder records the numbers stay in the same position even though the item contents are now different. That is why it is a bad idea to use the position of the element as an ID for other purposes.

**Comment by nolyboms** [comment]
@LukeTowers 
I understand. Thank you! It was not clear to me that the number is based on CSS.

We are getting close. :-)

In my controller i am trying to append a value to the json array. But when i add this function to my controller it tries to append the value to a column:

<code>
public function formBeforeSave($model)
    {
        $model->topics= 'x1';
    }
</code>

According to the [docs](https://octobercms.com/docs/database/serialization#appending-values-to-json)  i would have to define a accessor which i think is not necessary in my case.

So the question is now:
How to append a additional value to an existing json array in OctoberCMS?

**Comment by LukeTowers** [comment]
@nolyboms same as you would with any array in general.
```php
public function formBeforeSave($model)
{
    $model->topics = array_map($model->topics, function ($topic) {
         $topic['id'] = uniqid();
    });
}
```

**Comment by LukeTowers** [comment]
Whoops, order of arguments was backwards. array_map(callbackFunction, $inputArray)
do it `array_map(function () {}, $model->topics);`

**Comment by nolyboms** [comment]
My function looks now like this:

<pre><code>
 public function formBeforeSave($model)
    {


        $model->timeslots = array_map(function ($timeslot) {
             $timeslot['id'] = uniqid();
             return $timeslot;
        }, $model->timeslots);

        var_dump($model->timeslots); 
    }
</code></pre>
<br>
The output of var_dump states that the id is been appended but checking the db column and generated API, it seems that the value is not being stored. Very strange. -_-

**Comment by LukeTowers** [comment]
@nolyboms try attaching to the model's beforeSave event.

**Comment by nolyboms** [comment]
Nope. Didn't work. but...

So here is the strange thing which i can not understand:

Repeater Field Name: topics
DB Column: topics

Controller function:
<pre><code>    
$model->topics = array_map(function ($topic) {
    $topic['topic_id'] = uniqid();
	return $topic;
}, $model->topics);
</code></pre>    

NO TOPIC_ID IS STORED!


Now watch this...


Repeater Field Name: no change
DB: Created another column and called it: themes
Changed function to:

<pre><code>     
$model->themes = array_map(function ($topic) {
    $topic['topic_id'] = uniqid();
	return $topic;
}, $model->themes);

</code></pre>    

TOPIC_ID is appended to the column themes!

??????

**Comment by LukeTowers** [comment]
@nolyboms post your model class.

**Comment by nolyboms** [comment]
sidenote: i have changed the column name and all corresponding assets now from "topics" to "timeslots"

model class:

<pre><code>    
<?php namespace Xxx\Xxx\Models;

use Model;

class Events extends Model
{
    use \October\Rain\Database\Traits\Validation;
    
    public $timestamps = false;

    protected $jsonable = [
        'event_manager',
        'event_news',
        'timeslots',
        'apptheme'
    ];

    public $table = 'xxx_xxx_events';

    public $rules = [
    ];

	public $belongsTo = [
        'speaker_id' => [
            'Xxx\Xxx\Models\Speakers',
            'table' => 'acme_xxx_speakers',
        ],
    ];

}    

</code></pre>    


controller:

<pre><code>    
<?php namespace Xxx\Xxx\Controllers;

use Backend\Classes\Controller;
use BackendMenu;

class Events extends Controller
{
    public $implement = [
        'Backend\Behaviors\ListController',
        'Backend\Behaviors\FormController',
        ];
    
    public $listConfig = 'config_list.yaml';
    public $formConfig = 'config_form.yaml';

    public function __construct()
    {
        parent::__construct();
        BackendMenu::setContext('Xxx.Xxx', 'main-menu-item', 'side-menu-item');
    }

    public function formBeforeSave($model)
    {
        $model->timeslots = array_map(function ($meooow) {
             
                $meooow['id'] = uniqid();
                return $meooow;

        }, $model->timeslots);
    }

}    

</code></pre>

**Comment by nolyboms** [comment]
No. :(

**Comment by LukeTowers** [comment]
@nolyboms did you try putting the logic in the `beforeSave()` method on the model? Changing `$model` to `$this` instead of course

**Comment by nolyboms** [comment]
![clap](https://user-images.githubusercontent.com/45102531/51170272-5458e980-18ae-11e9-8517-b9a1687245c5.png)

**Comment by nolyboms** [comment]
And for anyone in the same situation, here is the solution:

<pre><code>    
    public function beforeSave()
{
    $this->_FieldName_ = array_map(function ($miau) {

        $miau['id'] = uniqid();
        return $miau;

    }, $this->_FieldName_);
}    
</pre></code>
