### ISSUE TITLE
Get rid of meta keywords and meta title

### ISSUE THREAD

**Issue by multiwebinc** [octobercms/october#4064]
On the CMS pages `Meta` tab, two of the options are `Meta Title` and `Meta Keywords`. The title is redundant since we already have the actual page's title, and there is [no such thing as an actual `<meta name="title">`](https://gist.github.com/lancejpollard/1978404) meta tag. And SEO experts seem to unanimously agree that the meta keywords tag will give you no benefit. Some have gone as far as to make the case that stuffing this with too many irrelevant keywords is seen by some search engines (e.g. Bing) as a spam tactic and this will actually lower your site's ranking.

**Comment by LukeTowers** [comment]
The meta title field can be used by `og:title`. Also, we're probably not going to remove these as that would break backwards compatibility for people that do utilize those fields. Feel free to make your own plugin to extend the form removing those fields however.
