### ISSUE TITLE
Error after update to 446

### ISSUE THREAD

**Issue by jajacobs** [octobercms/october#4066]
- OctoberCMS Build: 446
- PHP Version: 7.1
- Database Engine: MySQL
- Plugins Installed: none

![image](https://user-images.githubusercontent.com/8701133/51261230-45456a80-1986-11e9-9662-1c9a053dd762.png)

The issue is caused by the setting a default array value for the checkboxlist field.

**Comment by w20k** [comment]
@jajacobs, could you also post your usage example?

**Comment by jajacobs** [comment]
This is the field definition:
![image](https://user-images.githubusercontent.com/8701133/51267716-c146af00-1994-11e9-8a46-bc0c8ecb84b8.png)

**Comment by w20k** [comment]
https://github.com/octobercms/october/pull/4062/files - that was already fixed.

**Comment by jajacobs** [comment]
Fixed in #4062
