### ISSUE TITLE
Reset search in toolbar not implemented correctly everywhere

### ISSUE THREAD

**Issue by Rike-cz** [octobercms/october#4067]
- OctoberCMS Build: 446

### Description:
Reset search (X) in toolbar search input not implemented correctly everywhere (#3425). Implementation in Relation Manager toolbar missing.
![relation-manager](https://user-images.githubusercontent.com/4247582/51263631-ef3beb80-19b4-11e9-8fcf-226acf9da34e.png)

In Relation toolbar and List toolbar it's not perfect too (Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 **OPR/57.0.3098.116**):
![relation](https://user-images.githubusercontent.com/4247582/51264205-43939b00-19b6-11e9-98ca-91761774e5d9.png)
![lists](https://user-images.githubusercontent.com/4247582/51264209-47272200-19b6-11e9-9457-0e251f8bc416.png)

Ping: @vosco88, @w20k

**Comment by w20k** [comment]
@vosco88, Could you look at this issue and provide a PR to fix it? 
Thanks!

**Comment by vosco88** [comment]
@w20k Sure, will look at it.
@Rike-cz The pictures of the list toolbar are from which browser? Because when I run it in Firefox it looks good, in Chrome a bit of padding needs to be added (that I think corresponds to the second picture) . But I am not sure about first picture and where to replicate it.

**Comment by LukeTowers** [comment]
@vosco88 The first picture is a recordfinder widget with showSearch: true

**Comment by Rike-cz** [comment]
@vosco88 My usecase is Relation - View (https://octobercms.com/docs/backend/relations#has-many).

**Comment by vosco88** [comment]
@LukeTowers Sorry I meant the second picture :) I think I have already figured out the first picture and third. I don't know where to replicate the second.

**Comment by vosco88** [comment]
I have created PR for this. 
@w20k maybe also @Rike-cz could you test it please? Seems to be working for me
