### ISSUE TITLE
Request: Add ability to manually specify field names in order to have multiple fields with the same name

### ISSUE THREAD

**Issue by VoroninWD** [octobercms/october#4071]
HI!

I am creating an online store, and I have a need to dynamically form a whole group of form fields.

```php
Event::listen('backend.form.extendFields', function ($widget) {
    if ($widget->model instanceof Product) {
        $filters = ProductFilter::with(['relProductFilterValue'])
            ->get();

        $filters->each(function ($filter) use ($widget) {
            $widget->addFields([
                'relProductFilterValue' => [
                    'tab'      => 'Filters',
                    'label'    => $filter->name,
                    'span'     => 'storm',
                    'cssClass' => 'col-xs-12',
                    'type'     => $filter->type, // checkboxlist OR radio OR dropdown
                    'options'  => $filter->relProductFilterValue
                        ->lists('name', 'id'),
                ],
            ], FormTabs::SECTION_PRIMARY);
        });
    }
});
```

In fact, these fields are one field, which is divided into groups:
![image](https://user-images.githubusercontent.com/20097205/51322050-076f4180-1a6d-11e9-833b-fe935f9f033d.png)

These fields must use the same model relation to store data.

Everything works very well, but only as long as I have one field called "relProductFilterValue". When I have more than one field with the same name, only one field of all is shown. I cannot create multiple fields with the same name.

I see the solution to the problem as follows:
Add to the core of OctoberCMS a field called 'name', from which, if there is one, the field name will be taken. In this case, I can write the following:
```php
Event::listen('backend.form.extendFields', function ($widget) {
    if ($widget->model instanceof Product) {
        $filters = ProductFilter::with(['relProductFilterValue'])
            ->get();

        $filters->each(function ($filter) use ($widget) {
            $widget->addFields([
                'product_filter_' . $filter->id => [ // <- THIS
                    'name'     => 'relProductFilterValue', // <- THIS
                    'tab'      => 'Filters',
                    'label'    => $filter->name,
                    'span'     => 'storm',
                    'cssClass' => 'col-xs-12',
                    'type'     => $filter->type, // checkboxlist OR radio OR dropdown
                    'options'  => $filter->relProductFilterValue
                        ->lists('name', 'id'),
                ],
            ], FormTabs::SECTION_PRIMARY);
        });
    }
});
```

Creating your own FormWidget did not help, because the field name is used not only in the widget, but also in the widget's container.

**Comment by LukeTowers** [comment]
I don't think allowing fields with the same name is a good solution here. You'd be better off storing one of those fields in a temporary property that you mark as `purgeable` and merging the values between the fields in the model's `model.beforeSave` event.

**Comment by VoroninWD** [comment]
@LukeTowers thanks for your reply. I started to do as you say - one question appeared: how to specify the selected checkbox?

```php
$widget->addFields([
    'productFilterValue[' . $filter->id . ']' => [
        'tab'      => 'Filters',
        'label'    => $filter->name,
        'span'     => 'storm',
        'cssClass' => 'col-xs-12',
        'type'     => 'checkboxlist',
        'options'  => $filter->relProductFilterValue->lists('name', 'id'),
        'selected'   => $filter->relProductFilterValue->lists('id'), // <- THIS?
    ],
], FormTabs::SECTION_PRIMARY);
```

**Comment by LukeTowers** [comment]
@VoroninWD `default` (if the model doesn't exist yet) or set the value directly on the model for the field to pull from
