### ISSUE TITLE
Fronend Form validation and Flash messages

### ISSUE THREAD

**Issue by BahodurSaidov** [octobercms/october#4072]
- OctoberCMS Build: ### 446
- PHP Version: 7.1
- Database Engine: mysql
- Plugins Installed: rainlab.user

### Description:
I have seen many examples with form validation messages, even video tutorials, but however, the simple validation is not working for me !
i wanted to customize login and registration page of rainlab.user plugin, and copied the forms/partials from source and edited like this:
```
<form data-request="onSignin" data-request-validate data-request-flash>
    <div class="row">
        <input name="login" type="text" class="form-control my-2 offset-3 col-6" id="userSigninLogin" placeholder="{{ 'Email'|_ }}" required="" />
        <span class="text-danger" data-validate-for="login"></span>
    </div>
    <div class="row">
        <input name="password" type="password" class="form-control my-2 offset-3 col-6" id="userSigninPassword" placeholder="{{ 'Password'|_ }}" required="" />
        <span class="text-danger" data-validate-for="password"></span>
    </div>

    <button type="submit" class="btn btn-success btn-sm my-2" data-attach-loading>{{ "Sign in"|_ }}</button>
</form>
```
### Steps To Reproduce:
Copy partials from rainlab.user plugin to themes/partials and edit.

### Actual Result:
The loading icon in the button is showing up after click, but no validation error message shows for a specific form field. 
Also, i try to get the flash message by setting Flash message, still no error flashes. 
For now, i just came up with a single static error flash message for the user, like this:
```
    public function onSignin()
    {
        try {
            return $this->account->onSignin();
        }
        catch(Exception $e) {
            $m = $e->getMessage();
            $m = "Неправильный email или пароль!"; 
            Flash::error($m);
        }
    }

```
Please, help

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

**Comment by BahodurSaidov** [comment]
Why no updates? I am still stuck, seeing such messages is just security risk ! Here another login sample without any editing to user plugin:
![err](https://user-images.githubusercontent.com/13314276/51593061-fada6580-1f12-11e9-829c-e5b964c35a09.png)

**Comment by BahodurSaidov** [comment]
After searching so many blogs and forums, found the issue!
i run `npm outdated` and got `jquery                           1.9.1  1.12.4   3.3.1 ` then run npm update jquery.
Re-run `npm outdated` and got `jquery                          1.12.4  1.12.4   3.3.1`.

Now works as expected.

**Comment by LukeTowers** [comment]
@BahodurSaidov where do you recommend we include that information? @ayumihamsaki what do you think about listing our dependency versions in the readme?

**Comment by LukeTowers** [comment]
@ayumihamsaki sure, that sounds reasonable. Could you do some research and see how other projects handle similar setups?

**Comment by BahodurSaidov** [comment]
@LukeTowers might be something like md file as mentioned, but as for me, i was searching for package.json and bower.json files, since nobody use a project without package managers nowadays...
You could separate only frontend dependencies with npm or bower... but as per documentation style, md files could go better...

**Comment by ayumihamsaki** [comment]
So I will do two things:

1. Research and see how to best write up the documentation for the dependencies version lists.
2. Research and see how to best to add a dependencies file for October's package manager.

I will open a new issue for this and go from there.
