### ISSUE TITLE
Unable to install new plugins if one of the installed version.yaml files has a syntax error

### ISSUE THREAD

**Issue by multiwebinc** [octobercms/october#4073]
- OctoberCMS Build: 446
- PHP Version: 7.2.10-0ubuntu0.18.04.1
- Database Engine: sqlite
- Related: octobercms/october#3956

### Description:
I was creating my own plugin and it ran perfectly fine on its own, however I had a syntax error in my `version.yaml` file. The file contents was (notice the missing `:`):

```
1.0.1:
    - Initial version of Tours.
    - create_tours_table.php
    - create_categories_table.php
1.0.2
    - Added tour categories component
```

When I went to install a new (different) plugin from the backend, I was then given the error message:

> Update failed
> "Unable to parse at line 6 (near "1.0.2")." on line 411 of /path/to/install/vendor/symfony/yaml/Parser.php

I believe the error message should indicate the actual file being parsed by the yaml parser. Also I don't think an unrelated plugin should be able to prevent the installation of other plugins, but at the same time the admin also needs to be notified that something is wrong.

On a side note, I believe the plugin I was trying to install was actually at least partially installed. The files were downloaded to the project directory, however I am unsure if the migrations (if any) were executed.

**Comment by multiwebinc** [comment]
Also, here's the first few lines of the stack trace:

```
[2019-01-15 19:51:06] development.ERROR: Symfony\Component\Yaml\Exception\ParseException: Unable to parse at line 6 (near "1.0.2"). in /path/to/october/vendor/symfony/yaml/Parser.php:411
Stack trace:
#0 /path/to/october/vendor/symfony/yaml/Parser.php(105): Symfony\Component\Yaml\Parser->doParse(Array, 0)
#1 /path/to/october/vendor/october/rain/src/Parse/Yaml.php(22): Symfony\Component\Yaml\Parser->parse('1.0.1:\n- Initia...')
#2 /path/to/october/vendor/october/rain/src/Parse/Yaml.php(33): October\Rain\Parse\Yaml->parse('1.0.1:\n- Initia...')
#3 /path/to/october/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): October\Rain\Parse\Yaml->parseFile('/home/mike/Seaf...')
#4 /path/to/october/modules/system/classes/VersionManager.php(275): Illuminate\Support\Facades\Facade::__callStatic('parseFile', Array)
```

**Comment by LukeTowers** [comment]
@multiwebinc thanks for the report and submitted improvement! Merged it into develop, should be out in the next build (447) sometime next week.
