### ISSUE TITLE
Invalid security token after install and go to backend dashboard

### ISSUE THREAD

**Issue by patcaulfield** [octobercms/october#4076]
- OctoberCMS Build: ### 
- PHP Version: PHP 7.0.3 / mariaDB 10.0
- Database Engine: 
- Plugins Installed: 

### Description:

I have a problem when I try install. 
After install, Click to the backend link url 
alert message 'Invalid security token' 
localhost install id OK but I'm using web hosting server. tow database name. Is it problem?

**Comment by ayumihamsaki** [comment]
I get the same issue every time, just refresh the screen and will work second time. I did create a PR fix for it found here: https://github.com/octobercms/october/pull/3879 but mod's and admins never did anymore and merge it.

**Comment by patcaulfield** [comment]
Oh, I see. I'm glad you have a same problem and you solved. Good. but me it's too difficult to understand your way to solved way because I don't know well about php. Thank you!

**Comment by ayumihamsaki** [comment]
I've gone through all of the github repo and could only find closed issues relating to this issue, see here:

https://github.com/octobercms/october/issues/3640
https://github.com/octobercms/october/issues/3266

**Comment by alekseyp** [comment]
I was logged in for couple weeks and started getting those errors out of no where.
Only happens on dashboard, if I navigate to any other admin page it loads, but won't let me save anything.

**Comment by reed-josh** [comment]
I see a fix merged possibly there? I updated the octobercms install. Is there anything else we need to do to apply this fix?

**Comment by ayumihamsaki** [comment]
@reed-josh There is two separate PR's fixing this, one to allow the middleware to work for the other PR. So I would say to add both merges and give it a try. p.s. not sure where the other merge is you will need to search for it.
