### ISSUE TITLE
Graphical glitch with taglist after update

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#4081]
In build 443 taglist looks like this

![v443](https://user-images.githubusercontent.com/29771532/51527970-8f6a9800-1e2d-11e9-8a93-a12f194a1817.jpg)

And after update to build 446 looks like this

![v446](https://user-images.githubusercontent.com/29771532/51528021-ad37fd00-1e2d-11e9-8402-de37018b3527.jpg)

**Comment by SeriousKen** [comment]
A quick look at the CSS that is applied it seems that there is an invalid property on the class `select2-hidden-accessible` with `clip: rect(0)` which was `clip: rect(0 0 0 0)` in build 443, I presume this hides the element that is now visible after the update.

**Comment by w20k** [comment]
It's already resolved in dev branch 😉

**Comment by w20k** [comment]
You have the latest dev and lib also? It was fixed in the october/lib.

**Comment by SeriousKen** [comment]
> It's already resolved in dev branch  CSS minifier was changed.
> Ref: #4040

Sorry for the duplicate, I did a search to see if it had already been reported but this one didn't come up.
