### ISSUE TITLE
Manage October's Dependency Versions for Developers

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4084]
Following on from this github Issue: https://github.com/octobercms/october/issues/4072

So I will do two things:

1. Research and see how to best write up the documentation for the dependencies version lists.

> I would be happier to suggest creating a new `.md` file for all the dependency versions something like: `dependencies.md` and mentioning this new file in the `readme.md` under a small section. This way keeps everything tidy and organized and makes it easier for future updating. Maybe store the `dependencies.md` in the repo `octobercms/docs` to have it in a single place - which makes it easier to updating and maintaining.

2. Research and see how to best to add a dependencies file for October's package manager.

> I was searching for `package.json` and `bower.json` files, since nobody use a project without package managers nowadays. You could separate only frontend dependencies with npm or bower... but as per documentation style, md files could go better.

**Comment by ayumihamsaki** [comment]
Also link this Github (List of Updated Dependencies): https://github.com/octobercms/october/issues/3867

**Comment by ayumihamsaki** [comment]
Totally open to input and ideas from everyone on this.

**Comment by ayumihamsaki** [comment]
Totally open to input and ideas from everyone on this.

(Might be best to have a small Discussion first).

**Comment by LukeTowers** [comment]
Just to clarify, this would be for dependencies directly included in OctoberCMS, not those that are tracked by Composer already. We could probably have a blurb in there on our stance on LTS Laravel releases but otherwise just the JS side of things

**Comment by LukeTowers** [comment]
@ayumihamasaki2019
