### ISSUE TITLE
Image Upload Preview Limitation

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#4086]
- OctoberCMS Build: 446
- PHP Version: 7.0.18

When you upload images via `fileupload` with `imageHeight` and `imageWidth` set you get a cropped image when you click on the uploaded image to preview it and set title/description:

 
![image](https://user-images.githubusercontent.com/3897579/51732896-a3a1d580-2077-11e9-9247-ea42f2a8391f.png)

And there's no way to see the full image.

There's no such issue when `imageHeight` and `imageWidth` are not set.

**Comment by w20k** [comment]
@GinoPane is it only related to preview area?

**Comment by GinoPane** [comment]
@w20k the screenshot shows the issue I wanted to point out. When you click on the image to edit it the modal opens a small thumbnail instead of the image itself.

**Comment by LukeTowers** [comment]
@GinoPane you can always click on the Attachment URL link in the bottom left to view the full file.

**Comment by GinoPane** [comment]
@LukeTowers yes, but it is not convenient and not expected, whilst you the user expects to see a full image instead of thumbnail when he clicks on it

**Comment by w20k** [comment]
@GinoPane why not expected? If you crop an image, shouldn't you get a cropped version first? And then if you want to see a full version just click on `Attachment URL`.

**Comment by GinoPane** [comment]
@w20k because, first of all, it is not clear that you get a cropped version, it is written in config only and you have to remember that, secondly, attachment URL does not state as "Open full image" or something like that, it is perceived as a simple like to a file that you can use for whatever reason.

And actually, regarding crop itself, it would be good to have JS crop logic in that preview modal, but it is a matter of enhancement.

**Comment by w20k** [comment]
@GinoPane if you state it this way, then it's more likely a feature request (UX improvement request), not a bug :)

**Comment by GinoPane** [comment]
To be honest, the title and description do not contain "bug" :) So yes, it more like improvement for this area.

**Comment by w20k** [comment]
@GinoPane added `help wanted` ;)

**Comment by w20k** [comment]
@GinoPane could you try out a fix? Should be easy.
Change a single line (`backend/formwidgets/fileupload/partials/_config_form.htm -> line 11`): from `src="<?= $file->thumbUrl ?>"` -> `src="<?= $file->pathUrl ?>"`

**Comment by GinoPane** [comment]
@w20k it may help, but the default style for the image must be updated as well:

![image](https://user-images.githubusercontent.com/3897579/56488247-c8baae80-64d5-11e9-9bbe-372bc70f57bb.png)

**Comment by w20k** [comment]
@GinoPane -> remove this line as well :) Should be a fix for your case!
` style="<?= $cssDimensions ?>"`

**Comment by GinoPane** [comment]
@w20k let me get this clear, do you want me to submit a PR for this? 😄 

Anyway, removing of style won't fix the issue in general, because you can easily end up with something like this, when the whole modal does not fit the screen:

![image](https://user-images.githubusercontent.com/3897579/56489466-b2aeed00-64d9-11e9-8573-3e1b189965cf.png)

So the style for image must be fixed as well. I'm not sure why it was implemented via getCssDimensions and with server code, because everything can be handled with CSS only. Simple setting of both `max-width` and `max-height` with relative units (`vh`, `vw`) is probably the easiest one.

**Comment by w20k** [comment]
@GinoPane if you want this fix to be added :D Better to add a PR ;) Don't have time right now to deal with that.
