### ISSUE TITLE
Local and Global events exhibit different behavior 

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#4089]
There's an issue here https://github.com/OFFLINE-GmbH/oc-clockwork-plugin/issues/1 that seems to be related to the way local and global events are handled in `\System\Traits\EventEmitter` and `\October\Rain\Events\Dispatcher`. With the following class I did some tests.

``` php
class EventTest
{
    use \System\Traits\EventEmitter;
}
```

If I run the following code

``` php
// @return void
Event::listen('eventtest.event', function () {
    
});

// @return string
Event::listen('eventtest.event', function () {
    return 'Global event';
});

$test = new \October\Demo\Classes\EventTest();

// @return void
$test->bindEvent('event', function () {
        
});

// @return string
$test->bindEvent('event', function () {
    return 'Local event';
});

$response = $test->fireSystemEvent('eventtest.event', [], false);
dump($response);
```

I get

``` php
array:3 [
  0 => "Local event"
  1 => null
  2 => "Global event"
]
```

It seems that the null comes from the global event, but the processing of local events ignores any null responses and they don't end up in the result.

There also seems to be a discrepency between `fireSystemEvent` and `fireEvent` when halt is `true` and all of the event handlers return `null`.

For `fireEvent` you get `null` but for `fireSystemEvent` you get and empty array. I would expect `fireSystemEvent` when halting to return a single value ie `null` the same as `fireEvent`.

**Comment by tobias-kuendig** [comment]
See https://github.com/octobercms/october/pull/4105
