### ISSUE TITLE
Trigger action doesn't work for text area and file-uploader

### ISSUE THREAD

**Issue by shkhaksar** [octobercms/october#4091]
- OctoberCMS Build: 446
- PHP Version: 7.2.7

I set up a form with 3 widgets including a "Radio List" selector, File-Uploader and Text Area. The radio list had 3 options with keys 1,2,3 respectively. Then I specify for File-Uploader and Text area to become disabled and hidden when the option 2 is selected (in other word when value[2]). But these behaviours didn't work for upload and preview pages in order or I have to say the action trigger didn't work properly. I guess this is an implementation bug in form widget YAML parser

**Comment by w20k** [comment]
@shkhaksar could you post your yaml file with an example?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
