### ISSUE TITLE
why so many thumbs files are created?

### ISSUE THREAD

**Issue by FlorinMarina** [octobercms/october#4099]
Why so many thumbs files are created?

I mean I see this as a very big bug. Example when I deployed first time the blog was around 1.5 Gb ...
But now it has 20Gb and it freeze the server ...

So I have to clean up all thumb files every week.

... please help ...

**Comment by w20k** [comment]
Never had the same issue. Could you add more details about this bug? 

Plugins that you use or how do you call getThumb()?

**Comment by FlorinMarina** [comment]
Raideer.Thumbnail 

<a href="{{ post.url }}"><img alt="{{ post.title }}" srcset="{{ humbnail(cropHeight2X,cropWidth2X, {'mode': 'crop'}  }} 2x" src="{{ |thumbnail(cropHeight, cropWidth, {'mode': 'crop'} }}" /></a>

**Comment by FlorinMarina** [comment]
this is my complete code for the image render ... just because I imported older images from a old wordpress blog 

`{% if post.excerpt and not image %}
        <div class="listing-thumbnail">
            {% if postNo < 2 %}
                {% set cropHeight = "482" %}
                {% set cropWidth =  "351" %}
            {% else %}
                {% set cropHeight = "405" %}
                {% set cropWidth = "215" %}
            {% endif %}
            {% set cropHeight2X = cropHeight*2 %}
            {% set cropWidth2X = cropWidth*2 %}
            
            <a href="{{ post.url }}"><img alt="{{ post.title }}" srcset="{{ ("storage/app/media/blog/uploads/" ~ post.excerpt)|thumbnail(cropHeight2X,cropWidth2X, {'mode': 'crop'}) }} 2x" src="{{ ("storage/app/media/blog/uploads/" ~ post.excerpt)|thumbnail(cropHeight, cropWidth, {'mode': 'crop'}) }}" /></a>
        </div>
    {% elseif image %}
        <div class="listing-thumbnail">
            {% if postNo < 2 %}
                {% set cropHeight = "482" %}
                {% set cropWidth =  "351" %}
            {% else %}
                {% set cropHeight = "405" %}
                {% set cropWidth = "215" %}
            {% endif %}
            {% set cropHeight2X = cropHeight*2 %}
            {% set cropWidth2X = cropWidth*2 %}
            <a href="{{ post.url }}"><img alt="{{ post.title }}" srcset="{{ image.thumb(cropHeight2X,cropWidth2X, {'mode': 'crop'}) }} 2x" src="{{ image.thumb(cropHeight,cropWidth, {'mode': 'crop'}) }}" /></a>

        </div>
    {% else %}`

**Comment by w20k** [comment]
@FlorinMarina have you tried removing code blocks, to see which block copies thumbs?

**Comment by FlorinMarina** [comment]
I removed Raideer.Thumbnail ... but the issue persist ... my storage/app/uploads folder has 7.5 Mb ... anyone with the same issue ???

**Comment by w20k** [comment]
@FlorinMarina it's really hard to tell where the issue is. Thumbs don't regenerate files if not needed.

7.5 ain't big - I've storage with 100k image and the same amount of thumbs. Don't have any issues with thumbs being cloned/copied.

Try debugging this part, add `Log:error('thumb_' . $this->id . '_' . $width . '_' . $height . '_' . $options['offset'][0] . '_' . $options['offset'][1] . '_' . $options['mode'] . '.' . $options['extension'])`:
_vendor/october/rain/src/Dtabase/Attach/File.php_ (if I'm not mistaken).
```
   protected function getThumbFilename($width, $height, $options)
    {

        return 'thumb_' . $this->id . '_' . $width . '_' . $height . '_' . $options['offset'][0] . '_' . $options['offset'][1] . '_' . $options['mode'] . '.' . $options['extension'];
    }
```

**Comment by FlorinMarina** [comment]
Sorry **7.5 Gb ...**

[2019-04-08 14:21:32] dev.ERROR: thumb_18_482_351_0_0_crop.png  
[2019-04-08 14:21:32] dev.ERROR: thumb_17_405_215_0_0_crop.png  
[2019-04-08 14:21:32] dev.ERROR: thumb_21_405_215_0_0_crop.png  

reload the page ... 
 
[2019-04-08 14:21:03] dev.ERROR: thumb_18_482_351_0_0_crop.png  
[2019-04-08 14:21:03] dev.ERROR: thumb_17_405_215_0_0_crop.png  
[2019-04-08 14:21:03] dev.ERROR: thumb_21_405_215_0_0_crop.png  

is that OK?

**Comment by w20k** [comment]
Could you also look for this thumb (`thumb_18_482_351_0_0_crop.png`) and how many you have in your project?

From a code perspective, it creates a file if it does not exist. Might be a huge bug somewhere or misconfiguration:
```
        $thumbFile = $this->getThumbFilename($width, $height, $options);

        if (!$this->hasFile($thumbFile)) {
```

**Comment by FlorinMarina** [comment]
only once storage/app/uploads/public/5c3/5d6/5b1/thumb_21_405_215_0_0_crop.png

**Comment by w20k** [comment]
Then there is no issue, I guess. Three images and three thumbnails :) 
Maybe thumbs aren't optimized? That could be an issue 😄

**Comment by FlorinMarina** [comment]
I think is an issue ... and I think we found it ... 

```
├── 5c3
│   ├── 352
│   │   ├── b93
│   │   │   ├── 5c3352b9372f4373885869.jpg
│   │   │   └── thumb__964_702_0_0_crop.jpg
│   │   ├── b97
│   │   │   ├── 5c3352b978caa012586867.jpg
│   │   │   └── thumb__482_351_0_0_crop.jpg
```

as you can see the post id is missing

**Comment by w20k** [comment]
Maybe because of the plugin that you've used previously? Not sure, could you re-test it with a clean install, just to be sure @FlorinMarina ?

**Comment by FlorinMarina** [comment]
```
/**
     * Define the public address for the storage path.
     */
    public function getPublicPath()
    {
        if ($this->isPublic()) {
            return 'http://localhost/uploads/public/';
        }

        return 'http://localhost/uploads/protected/';
    }
```

.. this might be the issue ... testing the method ... and if this is the cause is a bug , very big bug ...

**Comment by w20k** [comment]
@FlorinMarina it's just a path :) And you have an ID issue, it's should be a different story...

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
