### ISSUE TITLE
Adding middlewere gives an error Class path.storage does not exist

### ISSUE THREAD

**Issue by o0alexela0o** [octobercms/october#4100]
- OctoberCMS Build: ### 
- PHP Version: 7.2.1
- Database Engine:  Mysql 5.6.38
- Plugins Installed: Alexei Bobkov pages 1.2.20, translate 1.4.5, user 1.4.6

### Description:
trying to add middlewere
even the example from docs gives me an error:
`PHP Fatal error: Uncaught ReflectionException: Class path.storage does not exist in /Applications/MAMP/htdocs/israplanet.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:752 Stack trace:`

I have checked app object and it does have this instance.

update: same thing on fresh instalation

### Steps To Reproduce:
once i register in my plugin the middlewere even like this
```php
public function boot()
{
    // Add a new middleware to end of the stack.
    $this->app['Illuminate\Contracts\Http\Kernel']
         ->pushMiddleware('Mishai\Test\Middlewere\Midle');
}

```
update:
middlewere file (example)
```php
<?php namespace Mishai\Test\Middlewere;

use Closure;
use Request;
use Illuminate\Foundation\Application;
use Illuminate\Contracts\Routing\Middleware;
use Illuminate\Http\Response;
use October\Rain\Exception\AjaxException;
use Symfony\Component\HttpKernel\Exception\HttpExceptionInterface;

class Midle 
{
/**
     * The Laravel Application
     *
     * @var Application
     */
    protected $app;

    /**
     * Create a new middleware instance.
     *
     * @param  Application $app
     * @return void
     */
    public function __construct(Application $app)
    {
        $this->app = $app;
    }
    
    public function handle($request, Closure $next)
    {
        // dd($this->app);
    }
}
```

**Comment by LukeTowers** [comment]
```php
// Add a new middleware to beginning of the stack.
    $this->app['Illuminate\Contracts\Http\Kernel']
         ->prependMiddleware('Path\To\Custom\Middleware');
```
^ Why is that in your boot() method?

**Comment by LukeTowers** [comment]
@o0alexela0o that's just an example of how you would prepend middleware. If you're literally using that code then it's not going to work because `Path\To\Custom\Middleware` doesn't exist in your project.

**Comment by o0alexela0o** [comment]
I know, i changed the path, otherwise i would get another error.
I updated my code for real one. please see above

**Comment by w20k** [comment]
Have you tried like this, just an option:
https://github.com/reed-josh/october-session-issue/blob/master/plugins/october/demo/Plugin.php#L21

**Comment by o0alexela0o** [comment]
@w20k yes, same result

**Comment by o0alexela0o** [comment]
@bennothommo can you please post your middlewere also?
i did tried both - prepeand and push. same result.

**Comment by o0alexela0o** [comment]
The problem is Application. If i remove it, works ok.

**Comment by Samuell1** [comment]
@LukeTowers this was solved looks like
