### ISSUE TITLE
Add CMS Release Versions Information Directly into the Backend of the CMS

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4101]
Take the following screenshot:

![version](https://user-images.githubusercontent.com/17784082/52068371-7b810d80-2574-11e9-86d2-4b011a194841.png)

It would be useful to have a button there, where we can click on to get the CMS Version information and be able to see all the changes in each Version Release, e.g.

This information directly in the backend to view: https://github.com/octoberrain/meta/blob/master/release-notes/build-447.md

Maybe add something like this:

![version2](https://user-images.githubusercontent.com/17784082/52069123-01518880-2576-11e9-869e-5b2219d86550.png)

(Helps to check track of things and useful info to know).

**Comment by LukeTowers** [comment]
The changelog link should probably go to the official changelog: https://octobercms.com/changelog, although that isn't very useful.

**Comment by ayumihamsaki** [comment]
Also it may be a good idea, to have extra info when a release is messed up and needs extra work to be able to update, for example this info I put in this github issue: https://github.com/octobercms/october/issues/3999

I think if that was also there it would save Users having to look around the Internet for a solution. Future proofs October and Safe Guards any forthcoming issues in Releases.

Maybe the link goes to two Tabs:

- Changelog
- Update Notes

**Comment by LukeTowers** [comment]
@ayumihamsaki ideally that doesn't happen, and when it does, the issue gets fixed and a new build pushed so people updating will just skip straight to the working build.

**Comment by ayumihamsaki** [comment]
@LukeTowers

Good point - No need Update Notes.

Should I create a PR for the Link to https://octobercms.com/changelog or wait for Daftspunk to review?

**Comment by drmzio** [comment]
@LukeTowers Is it possible to output the official changelog as JSON? I'd like to implement this into my project but currently there's no way to pull the changelog data. Perhaps appending `.json` to `https://octobercms.com/changelog.json` would output to JSON format?

**Comment by LukeTowers** [comment]
@drmzio you'd have to speak to @daftspunk or @alekseybobkov about that, I don't have control over the website. There's also https://github.com/octoberrain/meta/tree/master/release-notes that you could access with the GitHub API if you so desired.

**Comment by daftspunk** [comment]
This feature is added and will be available in Build 449+

Note the JSON format can be found at https://octobercms.com/changelog?json
