### ISSUE TITLE
moment(...).tz is not a function in repeater

### ISSUE THREAD

**Issue by moxetiale** [octobercms/october#4104]
datepicker in repeater not working 
![image](https://user-images.githubusercontent.com/17551744/52120251-26590080-2635-11e9-8d4c-909c3ac19407.png)

**Comment by w20k** [comment]
@moxetiale add more information: build version, repeater yaml part for testing & etc.

**Comment by moxetiale** [comment]
yaml

![image](https://user-images.githubusercontent.com/17551744/52141303-b36c7b80-266e-11e9-885b-04a93b4ceb94.png)


version 443

when i click add new item in repeater then i got this error and datepicker not working. but if i insert json manualy in mysql table and try to click datepicker its working

![image](https://user-images.githubusercontent.com/17551744/52141550-879dc580-266f-11e9-9e36-ae7b2ffaac1e.png)

**Comment by moxetiale** [comment]
![image](https://user-images.githubusercontent.com/17551744/52141582-a13f0d00-266f-11e9-8ad6-ddab2bbfe8b0.png)

**Comment by CptMeatball** [comment]
I **can not** replicate this issue on develop.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
