### ISSUE TITLE
Relation dropdown field with redundant padding in preview mode

### ISSUE THREAD

**Issue by Rike-cz** [octobercms/october#4107]
- OctoberCMS Build: 447

Displaying relation dropdown field is ok, tree list is needed:
![dd-relation-update](https://user-images.githubusercontent.com/4247582/52135320-d2a2e300-2645-11e9-9b91-1aaec7c660d8.png)

But in the case of 1:N relation preview is field filled with redundant left padding:
![dd-relation-preview](https://user-images.githubusercontent.com/4247582/52135016-2d880a80-2645-11e9-8a3f-0d458b64a03f.png)

And it not look good in form previews.

If it is not intentional behavior, removing left padding in dropdown field preview mode will help.

**Comment by LukeTowers** [comment]
@Rike-cz I would be fine with removing the left padding even from an update context, as long as it's left there for the dropdown options themselves.

**Comment by Rike-cz** [comment]
@LukeTowers I think Select2 plugin used for dropdown is not able to show tree any other way. I sent an information to @w20k, he will take a look on it too.

**Comment by LukeTowers** [comment]
I'm fine with how it displays the tree in the dropdown right now, I was just saying that the selected option doesn't have to have left padding after it's been chosen and the dropdown has been closed.

**Comment by w20k** [comment]
@Rike-cz - I don't think it will be fixed. Because it's not padding but `nbsp;`, which makes it difficult to handle. 
The only option I see here is to hock up `setValue` method or on change and remove those redundant values. 

Here is an example: 
```
<span class="select2-selection__rendered" id="select2-Form-field-Product-category-container" title="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;For Kids">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;For Kids</span>
```

**Comment by Rike-cz** [comment]
That's pity. I took a look on [Select2 plugin](https://select2.org) and there is no default way to hook this process. `templateResult` and `templateSelection` looked as solution but they do not work as we need. Maybe some custom hook can help as you wrote...

Solving preview mode is easy, but @LukeTowers want to solve all modes.

**Comment by w20k** [comment]
@Rike-cz this might help to hook into the matcher: https://stackoverflow.com/questions/51491048/select2-option-space-not-searching

**Comment by w20k** [comment]
@Rike-cz try this one, should work in your case: https://github.com/harvesthq/chosen/issues/2274#issuecomment-125152849
