### ISSUE TITLE
nested form is not working properly

### ISSUE THREAD

**Issue by ColetteContreras** [octobercms/october#4108]
- OctoberCMS Build: ### 
v1.0.447

- PHP Version:
7.1.16

- Database Engine: 
MySQL

- Plugins Installed: 
rainlab.User

### Description:

I added a plugin to extend the rainlab.user plugin that which have a field named `payout`. the type of the field is `json`. i would like to use `nestedform` to add/update my payout. when i used nestedform, i got a overflow error:

```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 69632 bytes) in 
 myproject/vendor/october/rain/src/Html/Helper.php on line 45
```

### Steps To Reproduce:

```php
<?php namespace NoOne\Profile;

use System\Classes\PluginBase;
use Rainlab\User\Controllers\Users as UsersController;
use RainLab\User\Models\User as UserModel;

class Plugin extends PluginBase
{
    public function registerComponents()
    {
    }

    public function registerSettings()
    {
    }

    public function boot() {
      UserModel::extend(function ($model) {
        $model->jsonable = [ 'payout'];
      });

      UsersController::extendFormFields(function ($form, $model, $context) {
        $form->addFields([
          'payout' => [
            'type' => 'nestedform',
            'form' => [
              'fields' => [
                'method' => [
                  'label' => 'Method',
                ],
              ],
            ],
          ],
        ]);
      });
    }
}
```

**Comment by LukeTowers** [comment]
@ColetteContreras it's not a bug, you've created an infinite loop. The NestedForm widget itself contains a Form widget, which would then get extended by your code again causing an infinite loop. To solve that, just check for `$form->isNested` and return when it's true:
```php
if ($form->isNested) {
    return;
}
```
