### ISSUE TITLE
Plugins: Please add "last updated" time stamp on overview

### ISSUE THREAD

**Issue by ghost** [octobercms/october#411]
Hi, as many Plugins recieve lots of valuable feedback and are mainted very well, I would appreciate if you raise useabillity for website visitors by adding "last updated" as time stamp to the plugin overview on the left of the plugin detail page. 

That way users gets an idea when a plugin was last updated much faster - without jumping between tabs.

**Comment by daftspunk** [comment]
The date should be extracted from the changelog last date. It may need a new column, code_updated_at or something, so the last updated date cannot be manipulated by updating the description.
