### ISSUE TITLE
Minor display issue on the deleted user's page

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#4114]
- OctoberCMS Build: 447

### Description:
The bottom margin of the red alert box is not constant.

### Steps To Reproduce:
- Delete an administrator
- Go to administrator's page
- Navigate between tabs

### Screenshots:
![1](https://user-images.githubusercontent.com/2959112/52265536-9bc61900-2934-11e9-9f1a-1e11c8da97a2.JPG)

![2](https://user-images.githubusercontent.com/2959112/52265547-a2ed2700-2934-11e9-9fc7-1001637236e1.JPG)

![3](https://user-images.githubusercontent.com/2959112/52265557-a680ae00-2934-11e9-84e3-1a8c3acddd13.JPG)

**Comment by bennothommo** [comment]
It appears to be fine on my browser (Chrome 72). @gergo85 would you be able to let us know which browser you are using?

**Comment by gergo85** [comment]
@bennothommo Indeed, it works in Chrome. This is a Firefox issue.

**Comment by bennothommo** [comment]
Thanks @gergo85. PR here: #4171

**Comment by w20k** [comment]
@gergo85 issues will be closed automatically after merge to master 😄

**Comment by gergo85** [comment]
@w20k Alright :)
