### ISSUE TITLE
Media List and Internet Explorer

### ISSUE THREAD

**Issue by Ladylain** [octobercms/october#4115]
- OctoberCMS Build: 446
- PHP Version: 7.2
- Database Engine:  MYSQL
- Plugins Installed: Builder, StaticPages, Redirects

### Description:
I've noticed an issue on Internet Explorer (Edge) with the media library.
When i opened the media library, the `control-scrollpad` is empty and in the inspector, i can see that it has no height. 

if i change the css of `div[data-control='media-manager'] .control-scrollpad` to remove `position: absolute` i can see the media list. 

I haven't search further where and how this issue could be solved. If someone has an idea, please share :) 

I think this is an issue that already existed in 2015 related to https://github.com/octobercms/october/issues/1198

Best,

**Comment by w20k** [comment]
@Ladylain If I'd have IE could look at it in more details, should be a minor bug.

**Comment by Ladylain** [comment]
@w20k I’ve lots of work at the moment, I’ll take a look as soon as I have time for it! As you just said , it’s probably a minor bug 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iboved** [comment]
I have the same problem. MediaManager doesn't work in Internet Explorer 11.

**Comment by LukeTowers** [comment]
Possibly related to #4601
