### ISSUE TITLE
Color picker value cannot be changed manually when it is displayed inside a modal

### ISSUE THREAD

**Issue by tobias-kuendig** [octobercms/october#4117]
When the colorpicker form widget is placed inside a modal it is not possible to change the hex value manually:

![colorpicker](https://user-images.githubusercontent.com/8600029/52296317-575f6b00-297e-11e9-8cdc-835364b4aff3.gif)

1. Changing the value normally
2. Trying to change (or even select) the value inside the modal does not work

This fork of the test plugin shows the problem:
https://github.com/OFFLINE-GmbH/test-plugin

Navigate to Playground -> Posts -> Create Comment and try to change the color of the colorpicker.

**Comment by w20k** [comment]
Confirmed - bug. Added to my Todo list.

**Comment by artistro08** [comment]
Is there a way I can test this to see if it works?

**Comment by tobias-kuendig** [comment]
https://mall.offline.swiss/backend/offline/mall/products/update/6

Click on one of the variants, then try to change the color via the text input.

Alternatively you can install this plugin locally and test it out as mentioned in the first comment:
https://github.com/OFFLINE-GmbH/test-plugin
