### ISSUE TITLE
Built-in loading stripe has performance issues.

### ISSUE THREAD

**Issue by Josniii** [octobercms/october#4118]
- OctoberCMS Build: 443

### Description:
While performance profiling our website I came across a few performance issues with the stripe-loading-indicator built into October. The following is a profiling screenshot from my local dev environment on a very simple page with the loading stripe included, based on just a 5 second profiler run.
![image](https://user-images.githubusercontent.com/13622443/52328532-43ece800-29f0-11e9-9219-9db6d65ddf7e.png)
Note the many tiny green and purple green stripe on the main window. These are all style recalculations leading to layout and ultimately repainting parts of the page.
Looking at the [source](https://github.com/octobercms/october/blob/fb2aa1730cc08e8563908b54b70e942bd2988f5e/modules/system/assets/less/framework.extras.less#L206) for the loading stripe, I see several things we can do to optimize this:

1. Even when loading is complete, the animation continues in the background. We can pause the animation when it's not used. This is probably the biggest performance optimization, and the following two are mostly for when the animation is actually used.
2. The animation currently animates the `width` of the loading bars. This is a performance issue because changing the width of an element means that other elements around it may have changed position, meaning that layout has to be recalculated. Instead, we could create the animation with properties that don't require layout recalculation, like `transform: translateX()` or `scaleX`. 
3. My browser currently puts the stripe on it's own layout layer, which is good, but not much is being done to ensure that this happens generally and not just on my site. We can use `will-change` (or for better browser compatibility, `transform: translateZ(0)`) to ensure that the browser knows to put these on their own layers.

I reimplemented the loading animation with `transform: translateX` on my site and reran the profiler:
![image](https://user-images.githubusercontent.com/13622443/52329575-79df9b80-29f3-11e9-923f-4f903c2b24b5.png)
No more tiny style recalculations. Layout/Paint times went from about 100ms per 5 seconds to 0 basically. That's actually a lot of room when we're aiming for high framerates on our pages, If you're aiming for 60 FPS when browsing, this fix frees up 0.3ms in your 16.66667ms/frame budget.

Now, I'd like to make a PR with these changes, but first I'd like opinions. Are there any problems/browser compatibility issues with my proposed changes that I'm not seeing? Are there even better solutions we could implement?

### Steps To Reproduce:
Visit any OctoberCMS page with the stripe-loading-indicatior included, like this one provided by a community member:
https://mall.offline.swiss/en/category/bikes
Run Chrome's built in performance profiler, no matter if it's active or not. Notice the timeline is full of tiny style recalculations leading to paints.

**Comment by w20k** [comment]
@Josniii make a PR and we could test it out 👍

**Comment by Josniii** [comment]
Done. :+1: 

Something related: How are you actually supposed to generate these files? `php artisan october:util compile assets` does not include the LESS file here. I had to edit this line to compile it:
https://github.com/octobercms/october/blob/master/modules/system/ServiceProvider.php#L518

**Comment by w20k** [comment]
@Josniii feel like it's a bug, have to change it to `.less`. Good catch!
