### ISSUE TITLE
PHP 7.2 create_function() deprecation

### ISSUE THREAD

**Issue by rizhenkov** [octobercms/october#4119]
- OctoberCMS Build: 446
- PHP Version: 7.2.10

### Description:
When trying to define own function or filther for templating engine in Plugin.php after upgrading to PHP 7.2 I have error:

An exception has been thrown during the rendering of a template ("Function create_function() is deprecated").

### Steps To Reproduce:
1. Install PHP 7.2
2. Define own filter in Plugin.php
```php
public function registerMarkupTags()
{
   return [
     'filters' => [
          'autop' => function($pee, $br = true) {
             // some code
           }
      ]
   ];
}
```
3. Try to use that filter in template:
```twig
<div>
    {{ profile.text | autop }}
</div>
```

![image](https://user-images.githubusercontent.com/987517/52349938-981bba80-2a38-11e9-9f88-3a178046ac54.png)

**Comment by Samuell1** [comment]
Hey, if you use it normal way do you get same error, because iam running on php 7.3 and without issues.

`'atop' => ['Path\To\Class\Helper', 'atop']`

**Comment by Samuell1** [comment]
I tested it out and it works without issues on OCMS 447 and PHP 7.3.4. Maybe you using old Twig version that is not supporting  PHP 7.2+

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
