### ISSUE TITLE
Do not save data from settings if use partial

### ISSUE THREAD

**Issue by toxigennn** [octobercms/october#4120]
- OctoberCMS Build: 446
- PHP Version: 7.2
- Database Engine: MySQL 5.7
- Plugins Installed: -//-

### Description:
Created site settings, everything works and saves to the database, except for partial.
In the partial I call the fields as basic, for example: Settings[email]. There are no errors when saving, these fields are included in the post, but not saved.
I remember working in the settings before

### Steps To Reproduce:
1. Create settings by https://octobercms.com/docs/plugin/settings#database-settings
2. Use new filed type partial, exapmle:
        content:
            type: partial
            path: plugins/autor/my_plugin/models/settings/_contacts_partial.htm
3. Create from partial input with name="Settings[test]"

**Comment by Ladylain** [comment]
@sh-easy Have you well configured your fields.yaml in your setting model ?!  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sh-easy** [comment]
@Ladylain yes, Yes, everything works for me and is saved, except for those fields that are in the partial

**Comment by Ladylain** [comment]
@sh-easy I will check on my side this evening and try to find something

**Comment by LukeTowers** [comment]
@toxigennn please post your fields.yaml. I believe your field name has to be the same as the name you're using in the partial for it to save.

**Comment by toxigennn** [comment]
@LukeTowers They do not match, because in the partial I have many different fields (a kind of layout in this partial)

**Comment by LukeTowers** [comment]
Then I don't think it will work. Look at the Form widget's getSaveData method to figure out how this works internally, but I don't think partials were ever meant to be "custom field types", more so just raw HTML content. You should probably look into building a FormWidget for your purposes.

**Comment by Ladylain** [comment]
@toxigennn @LukeTowers i've jsut tried it on my side and all works perfectly with some fix.

content of my partial is : 
```php
<input type="text" name="Settings[content]" value="<?= $model->content ?>">
```
and my field is : 
```yaml
content:
    type: partial
    path: plugins/autor/my_plugin/models/settings/_contacts_partial.htm
```
So , you need to get the good field name in your partial, and if you want to add more than one field into it, you can change your inputs name like this `Settings[content]['field-1]` and you can retrieve them by using  `$model->content->field-1` for example. 

hope it could help you. :)

**Comment by Samuell1** [comment]
@LukeTowers Looks like solved.
