### ISSUE TITLE
Contributing Guidelines in the README are no longer available

### ISSUE THREAD

**Issue by tobias-kuendig** [octobercms/october#4122]
The link to CONTRIBUTING.md in the readme returns a 404 error. 

Where are current guidelines hosted?

**Comment by w20k** [comment]
Hi, @tobias-kuendig -> https://github.com/octobercms/october/blob/master/.github/CONTRIBUTING.md
The link changed a bit ;)

**Comment by tobias-kuendig** [comment]
Thanks! See PR #4123
