### ISSUE TITLE
Pagination broken when on page n>1 and setting list limit to m>count(entries)

### ISSUE THREAD

**Issue by kosmonowt** [octobercms/october#4125]
Backend:
1. I have a set of items with ±100items.
2. Default list items setting in my list is 20 entries.
3. I navigate to page 5 (now showing item 81-100)
4. Now I set my list view to 120 items.
5. As there is only one page that should be shown now I have no paginator displayed anymore, but also the page does not show any entries. Also on reload there won't be any entries on the page anymore.

Suggestion: Reset paginator in session when selecting another item limit.

![bildschirmfoto 2019-02-07 um 18 22 23](https://user-images.githubusercontent.com/1159594/52429974-5c025b80-2b05-11e9-8dec-ceffc86a8bdd.png)

![bildschirmfoto 2019-02-07 um 18 22 37](https://user-images.githubusercontent.com/1159594/52429988-60c70f80-2b05-11e9-91d3-e2f12ee05919.png)

**Comment by LukeTowers** [comment]
Your suggestion sounds good to me @kosmonowt, feel free to submit a PR to do that.

**Comment by Rike-cz** [comment]
Similar problem as #4008

**Comment by bennothommo** [comment]
Hi @kosmonowt, this should be resolved as per this PR: https://github.com/octobercms/october/pull/4020
I don't believe the fix as been added to an October build yet, but should be very soon.

**Comment by w20k** [comment]
@Rike-cz could you test the fix from @bennothommo, and comment? Thanks ;)

**Comment by Rike-cz** [comment]
@bennothommo fix was released in version 447 definitely, thanks @bennothommo, it works great! I tried what @kosmonowt wrote with ver. 447 and his bug looks to be solved too. @bennothommo solution killed all bugs, where user was send out of the pagination interval.
Can @kosmonowt confirm this with version 447?

**Comment by bennothommo** [comment]
This was fixed by https://github.com/octobercms/october/pull/4020.
