### ISSUE TITLE
Tab Icons are not supported in Theme Data Model

### ISSUE THREAD

**Issue by seanthepottingshed** [octobercms/october#4131]
- OctoberCMS Build: 447
- PHP Version: 7.1.17
- Database Engine: mysql
- Plugins Installed: n/a

### Description:
Extending Theme model with tab icon definitions don't display in page.

### Steps To Reproduce:

Either add the following to a plugin `Plugin.php`:

```php
public function boot()
{
     Event::listen('cms.theme.extendFormConfig', function ($themeCode, &$config) {
        $config['tabs'] = [
            'icons' => [
                'Global'  => 'icon-globe',
            ],
        ];
        array_set($config, 'tabs.fields.test_asset_var', [
            'label'    => 'Test Asset Var',
            'type'     => 'text',
            'assetVar' => 'testAssetVar'
            'span'     => 'left',
            'tab'      => 'Global',
        ]);
        return $config;
    });
}
```

or use the following:

* https://github.com/octoberrain/test-plugin/pull/62

**Comment by w20k** [comment]
@seanthepottingshed seems like it wasn't support even from `.yaml` :)

**Comment by seanthepottingshed** [comment]
@w20k 

Yeah, sorry I should've mentioned that as well, noticed after I submitted this issue.

**Comment by w20k** [comment]
For now, it's not possible to dynamically add icons.

**Comment by LukeTowers** [comment]
I don't know why that wouldn't work, are you sure you don't have something else listening to that event overriding the value of `$config['tabs'];`?
