### ISSUE TITLE
Sluggable trait and utf8mb4 character set

### ISSUE THREAD

**Issue by Nai4rus** [octobercms/october#4133]
- OctoberCMS Build: 446
- PHP Version: 7.2
- Database Engine: MySql

### Description:
After this https://github.com/octobercms/october/issues/2972 the fields in the database are 191 characters by default. The Sluggable maximum length for the slug is 240. Therefore, when the incoming line is longer than 191, the october throw exception SQLSTATE "too long for column 'slug'".

Also the substr function is used In https://github.com/octobercms/library/blob/master/src/Database/Traits/Sluggable.php#L69, which incorrectly works with russian charters. Here code example:
```
$slug = 'тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест тест ';

echo mb_strlen($slug); // returns 255
echo mb_strlen(substr($slug, 0, 190)); // returns 106
echo mb_substr($slug, 0, 190); // returns 190
```

**Comment by LukeTowers** [comment]
@Nai4rus please submit a PR with your proposed fixes.

**Comment by Nai4rus** [comment]
https://github.com/octobercms/library/pull/378

**Comment by Samuell1** [comment]
Hey, i think it will be better if we use laravel helper function called str_limit. What you think?

**Comment by Nai4rus** [comment]
I think this is not necessary
