### ISSUE TITLE
Data-table on data-request-update

### ISSUE THREAD

**Issue by ImadUllah** [octobercms/october#4134]
Data-table on data-request-update
`data-request-update="'{{ __SELF__ }}::usertickets': '#usertickets'"`
@LukeTowers it update the partial (having table) but it hides the Data-table, kindly look at the matter.
rest all the work is ok... just datatable not working

**Comment by w20k** [comment]
@bennothommo could you look at this `bug`, if you have a minute 😄

**Comment by bennothommo** [comment]
@w20k will do :)

**Comment by bennothommo** [comment]
@ImadUllah Could you please provide some more info on how you using the `data-request` AJAX functionality? Is this a partial inside a form or in a preview?

**Comment by ImadUllah** [comment]
no it is a partial having a table(bootstrap data-table) when i create or delete or update a record and update that partial it doesn't shows data table...

**Comment by ImadUllah** [comment]
it update the records but hides the data-table

**Comment by ImadUllah** [comment]
when i hide the edit form partial and shows the updated records in table partial but it hide the bootstrap data-table

**Comment by bennothommo** [comment]
@ImadUllah You will need to check what your component's `usertickets()` method is returning. That is what is inserted into the `#usertickets` element.

**Comment by ImadUllah** [comment]
it gives the records correctly but hides the data-table, 
`$this->page['created']=Ticket::where('users_id',Auth::getUser()->id)->get();`
![records in data-table](https://user-images.githubusercontent.com/35524866/52771682-57cfc400-3058-11e9-8039-a4e5458c894c.PNG)
![with out data-table](https://user-images.githubusercontent.com/35524866/52771690-5bfbe180-3058-11e9-871a-edf9f366bee4.PNG)

**Comment by bennothommo** [comment]
@ImadUllah I'm not sure which data table plugin you are using, but I would say that if you needed to call a jQuery function to enable the data-table feature on the original table, you would need to call that same function again to enable the feature on the new table as the content of the <div> would've changed after the AJAX request executed. You can use the [data-request-success](https://octobercms.com/docs/ajax/attributes-api) attribute to specify JavaScript that runs after the AJAX call completes.

Also, please note that GitHub is not the best place for support - I would recommend asking for support on the October forums or Slack. Please see this page: https://octobercms.com/support

@w20k This is not a bug, in case you need to change the labels :)

**Comment by w20k** [comment]
@bennothommo Thanks a lot for your time ;) Changed!

@ImadUllah guess this issue could be closed?
