### ISSUE TITLE
taglist style bug

### ISSUE THREAD

**Issue by Nai4rus** [octobercms/october#4137]
- OctoberCMS Build: 446

### Description:
![image](https://user-images.githubusercontent.com/33084287/52783141-69ba6280-306a-11e9-9bab-ea67fcf312cd.png)

Seems to be the source of the problem here modules/system/assets/ui/less/form.base.less:73

**Comment by w20k** [comment]
@Nai4rus if you're talking about the `border` - it should be fixed in dev a long time ago.

Related issue: https://github.com/octobercms/october/issues/4040

**Comment by Nai4rus** [comment]
Strange, I discovered this on a new project. Tomorrow I will try to reproduce it again.

**Comment by Nai4rus** [comment]
I get this problem after the October update in the backend, both after receiving the new updates and after the forced update. After composer update the problem disappears.

**Comment by LukeTowers** [comment]
@Nai4rus so can this issue be closed?

**Comment by Nai4rus** [comment]
@LukeTowers I think not, the problem was solved a month ago, but I still have it after these steps:

1) cloning from git https://github.com/octobercms/october.git
2) composer update
3) configuring database, install test plugin

> at this moment all ok

4) update october in admin panel

> border came again

5) composer update

> all ok

I consider step 5 a temporary solution, not everyone knows or can perform this step. The system was supposed to get a fix a month ago after the update?

**Comment by w20k** [comment]
@Nai4rus do you have edge updates enabled?

**Comment by Nai4rus** [comment]
@w20k no

**Comment by w20k** [comment]
Fixed in latest build!
