### ISSUE TITLE
fileupload popup bug

### ISSUE THREAD

**Issue by Nai4rus** [octobercms/october#4141]
- OctoberCMS Build: 446
- Chromium  72.0.3626.96

### Description:
What i have (Chromium 72.0.3626.96)
![image](https://user-images.githubusercontent.com/33084287/52856541-216c7480-313e-11e9-8bae-b6e93c01cebf.png)
What expected (firefox 65.0)
![image](https://user-images.githubusercontent.com/33084287/52856632-62fd1f80-313e-11e9-8795-382500d83021.png)

### Steps To Reproduce:
try to load a file larger than the maximum allowed in nginx

**Comment by w20k** [comment]
Fixed by https://github.com/octobercms/october/pull/4077
