### ISSUE TITLE
|media filter incorrect path generated when installation is in sub directory

### ISSUE THREAD

**Issue by Caraz1** [octobercms/october#4143]
- OctoberCMS Build: 446
- PHP Version: 7.0
- Database Engine: mysql
- Plugins Installed: October.Demo-v1.0.1

### Description:
There is an issue with the |media filter when installation is in a sub directory. It uses the sub directory name twice.

example: http://localhost/compunix/compunix/storage/app/media/Compunix-gradient.png

The compunix sub directory is used twice

### Steps To Reproduce:
Upload an image using the media manager. 
Try to access using the media manager link on right hand side under the thumbnail " URL    Click here"
Or
In an existing page add the following html. Change the image name to the image name you uploaded.

<img src="{{ 'Compunix-gradient.png'|media }}" alt="">

Change the image name to the image name you uploaded. Image will not load on the page.

**Comment by w20k** [comment]
Already solved in the latest edge build.
Duplicate of: https://github.com/octobercms/october/issues/4065

**Comment by Caraz1** [comment]
upgraded to build 447. Issue resolved.
Many thanks.
