### ISSUE TITLE
Aliases and Service Providers are not registered by Package Discovery when installing a Laravel package

### ISSUE THREAD

**Issue by iboved** [octobercms/october#4149]
- OctoberCMS Build: 446
- PHP Version: 7.1.9

### Description:
I am trying to use this Laravel [package](https://github.com/Crinsane/LaravelShoppingcart) in my plugin. OctoberCMS [documentation](https://octobercms.com/docs/plugin/composer#laravel-aliases-service-providers) says that Aliases and Service Providers will be registered automatically if Laravel package use [Package Discovery](https://laravel.com/docs/5.5/packages#package-discovery). LaravelShoppingcart package uses Package Discovery in its [composer.json](https://github.com/Crinsane/LaravelShoppingcart/blob/master/composer.json). So, I added composer.json to my plugin with one dependency and run `composer update` command. This command has installed the necessary dependencies in the `vendor` root directory. But I get an error - `Class cart does not exist`. So, Aliases and Service Providers have not been registered automatically by Package Discovery. It is only working if I register Aliases and Service Providers manually in `boot` method in Plugin.php. But following the [documentation](https://octobercms.com/docs/plugin/composer#laravel-aliases-service-providers) they should be registered automatically. It seems that OctoberCMS [composer.json](https://github.com/octobercms/october/blob/master/composer.json) doesn't have `php artisan package:discover` script.

### Steps To Reproduce:
Add composer.json file to your own plugin. Add [LaravelShoppingcart](https://github.com/Crinsane/LaravelShoppingcart) as dependency to it. Run `composer update`. Try to use `Cart` facade somewhere in your code.

**Comment by LukeTowers** [comment]
@iboved are you running `composer update` in the plugin directory or the root project directory?

**Comment by iboved** [comment]
@LukeTowers I run `composer update` in the root project directory.

**Comment by LukeTowers** [comment]
@iboved does adding the `package:discover` script to the composer.json solve the problem?

**Comment by filipac** [comment]
@iboved you have to add the commands to your composer.json file:
```json
"scripts": {
        "post-create-project-cmd": [
            "php artisan key:generate",
            "php artisan package:discover"
        ],
        "post-update-cmd": [
            "php artisan october:util set build",
            "php artisan package:discover"
        ]
    },
```

**Comment by iboved** [comment]
@filipac thanks)
@LukeTowers if I add `php artisan package:discover` to composer.json in root project directory (as @filipac showed), it will work. But there is no information in the documentation about this step. The documentation says that it will work out of the box.

**Comment by w20k** [comment]
@iboved you could provide a PR to docs to fix that 😉

**Comment by iboved** [comment]
It is not entirely clear, the documentation should be edited or, possibly, composer.json in OctoberCMS root. Maybe composer.json should have `php artisan package:discover` out of the box?

**Comment by w20k** [comment]
@iboved I'd leave it the way it is for now (composer.json in the root), but changed docs with provided by @filipac solution and minor corrections.

**Comment by LukeTowers** [comment]
@iboved @w20k I'm fine with a PR to the default composer.json to add the support.

**Comment by w20k** [comment]
@LukeTowers @iboved - Done ;)

**Comment by LukeTowers** [comment]
@w20k did you test it?

**Comment by w20k** [comment]
@LukeTowers nope, it's not tested yet. Only made PR, while had a spare minute.
