### ISSUE TITLE
When having two lists with filters, the second one does not work

### ISSUE THREAD

**Issue by filipac** [octobercms/october#4153]
- OctoberCMS Build: b39eb03336faf4c30ddb059e1973eb313dbd68f6 (dev-develop)
- PHP Version: 7.2
- Database Engine: mysql
- Plugins Installed: None

### Description:
If you have two lists on the same page (say in two different tabs or one in modal and one in page) and both have filters, the second one has errors when applying the filters:
```
storm-min.js?v446:3205 Uncaught TypeError: Cannot read property 'data' of null
    at FilterWidget.filterScope (storm-min.js?v446:3205)
    at HTMLButtonElement.<anonymous> (storm-min.js?v446:3113)
    at HTMLDocument.dispatch (jquery.min.js?v446:2)
    at HTMLDocument.y.handle (jquery.min.js?v446:2)
```

### Steps To Reproduce:
1. Install a fresh october installation
2. Download october test plugin ( https://github.com/octoberrain/test-plugin )
3. To the post and comments tables add one filter for each. (https://github.com/filipac/oc-filters-reproduce-bug-plugin/commit/db81810f60883356f2a55a9d6eb578f6f214791c)
4. Try to apply filter for first table (posts tab) works ✅
5. Try to apply or reset fitlers for second (comments) ‼️ fail with the above error

The error occurs only when having more lists on page and is triggered because ```self.$activeScope``` and ```self.activeScopeName``` seems to be null.

I will make a new PR to check the solution I used on my project to make this work, and you can review it.

**Comment by linhtc** [comment]
Same issue

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/a2315624df0406a78d12ff262faac4d8443c05d6
