### ISSUE TITLE
Console install: choosing to install October.Drivers and/or RainLab.Builder fails

### ISSUE THREAD

**Issue by filipac** [octobercms/october#4155]
- OctoberCMS Build: b39eb03336faf4c30ddb059e1973eb313dbd68f6 (dev-develop)
- PHP Version: 7.2
- Database Engine: mysql
- Plugins Installed: None

### Description:
When installing via CLI command, if you choose yes to `Configure advanced options? (yes/no)` there are two questions that allows you to install Rainlab.Builder and October.Drivers in the process. This was made by me (https://github.com/octobercms/october/pull/2974) in 2017 and merged in 2018. But maybe in the meantime something changed, because if you choose yes to any of those, the command fails instantly:

```  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fresh.system_settings' doesn't exist (
  SQL: select * from `system_settings` where `item` = system_log_settings limit 1)



  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fresh.system_settings' doesn't exist



  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fresh.system_settings' doesn't exist
```

### Steps To Reproduce:
1. Download a fresh october repo
2. Run ```php artisan october install```
3. When asked `Configure advanced options? (yes/no)` choose yes (`y`)
4. When asked `Install the October.Drivers plugin? (yes/no) [no]:` choose yes
5. Command fails.

**Comment by filipac** [comment]
Closing since it's fixed now :)! Thank you.

**Comment by LukeTowers** [comment]
We keep issues open until the fix is merged into master @filipac

**Comment by filipac** [comment]
got it 👍
