### ISSUE TITLE
Translate plugin error on php 7.2

### ISSUE THREAD

**Issue by cruachan** [octobercms/october#4161]
- OctoberCMS Build: 446
- PHP Version: 7.2.15
- Database Engine: MySQL
- Plugins Installed: Translate

### Description:
Invalid argument supplied for foreach()

    public function getModelAttributes()
    {
        $attributes = [];
  
        foreach ($this->model->translatable as $attr) {
            $attributes[$attr] = $this->model[$attr];
        }
  
        return $attributes;
    }

PHP throws a warning because it considers $this->model->translatable not to be countable, and Laravel escalates this to an Exception and crashes.

### Steps To Reproduce:
Install translate plugin, open CMS section.  Above error.  

Temporary workaround: disable updates and add
error_reporting(E_ERROR);
to file TranslateablePage.php

**Comment by LukeTowers** [comment]
This belongs in the translate plugin's repo, not the main one.
