### ISSUE TITLE
Error "Something went wrong" when insert an image in rich text editor

### ISSUE THREAD

**Issue by docu30** [octobercms/october#4164]
Hello. I'm using October CMS and I created a plugin with articles and categories. I used the rich text editor field to describe the article but when I want to add a picture I get the message "something went wrong" and the path to the image is wrong. 
Example: 
http://localhost:8888/oct_text/oct_text/storage/app/media/uploaded-files/image.png

The error is in the path of the image file. As can be seen, occurs twice " oct_text/ " . 

And in the console I received the following error:
GET http://localhost:8888/oct_text/oct_text/storage/app/media/uploaded-files/image.png 404 (Not Found)

I mention that the image file is uploaded correctly.
Can you help me, please!

**Comment by w20k** [comment]
Could you test those PR if they fix your issue: https://github.com/octobercms/october/pull/4055 & https://github.com/octobercms/october/pull/4055

**Comment by docu30** [comment]
It's working. Thank you !
