### ISSUE TITLE
Bug in string_agg() for PostgreSQL

### ISSUE THREAD

**Issue by briddle** [octobercms/october#4167]
- OctoberCMS Build: 446
- PHP Version: 7.3.2
- Database Engine: PostgreSQL
- Plugins Installed: Briddle.Crm

### Description:
When joining on multiple fields for many to many relations it adds ", ', '" to the function. This gives an error.

Please see: 
https://octobercms.com/forum/post/supporting-db-postgresql?page=1#post-26378

### Steps To Reproduce:
Just install on PostgreSQL and open the CRM :)

**Comment by w20k** [comment]
Hi @briddle, you could provide a PR to fix that 👍 I'll review it and test!
