### ISSUE TITLE
Class name resolution usage breaks script parser script.

### ISSUE THREAD

**Issue by iulianwebdev** [octobercms/october#4176]
- OctoberCMS Build: 446
- PHP Version: 7.2.15
### Description:
The October\Rain\Database\Updater.php causes an issue with migrations if a second 'class' keyword is present in the file that is being parsed, usually the class name resolution keyword. 

E.g.
```
ClassName::class
```

### Steps To Reproduce:
Created a new plugin or any new migration file. Use class name resolution keyword.
Concrete example:

```php
class AddFeaturedColumnToPostsTable extends Migration
{
    
    public function __construct()
    {
        if (!class_exists(Post::class)) {
            return;
        }
    }
}

```

So here we have 2 class keyword occurrences and it will break if it finds more than one.

The migration attempt breaks with the error message:
```
[ErrorException]                
  Uninitialized string offset: 1 
```

The code breaks because it doesn't account for more than one class keyword occurrence in the parsed file tokens.

The issue seems to be in this file: **October\Rain\Database\Updater.php**

**Comment by LukeTowers** [comment]
@iulianwebdev are you able to submit a PR to fix it?

**Comment by iulianwebdev** [comment]
Yes, I'll try and fix the problem and submit a PR today.

**Comment by adrenth** [comment]
I can confirm this issue is still present in latest build.

For example, if you use the `resolve` method to get some container binding in you migration, it will break immediately with `Uninitialized string offset: 1`.

```
$connection = resolve(ConnectionInterface::class);
$connection->beginTransaction();
// ...
```

**Comment by Samuell1** [comment]
@LukeTowers there is already pending pr: https://github.com/octobercms/library/pull/384

**Comment by bennothommo** [comment]
Fixed by https://github.com/octobercms/library/commit/a2296fe279a97440711d1ea60669784fb583eb09 (#384).
