### ISSUE TITLE
Http.php: Array to string conversion

### ISSUE THREAD

**Issue by Rike-cz** [octobercms/october#4180]
- OctoberCMS Build: 448
- PHP Version: 7.2

### Description:
Clicking on Updates & Plugins > Install plugins throws exception: `"Array to string conversion" on line 282 of C:\dev\web\www\icestudio\brancoreality\vendor\october\rain\src\Network\Http.php`

**Comment by w20k** [comment]
Hi @Rike-cz, know issue, just change - `curl_setopt($curl, CURLOPT_POSTFIELDS, $this->requestData);` -> `curl_setopt($curl, CURLOPT_POSTFIELDS, $requestDataQuery);`.
Trying to fix it ASAP.

**Comment by Rike-cz** [comment]
Thanks @w20k, it helps!

**Comment by bennothommo** [comment]
I believe https://github.com/octobercms/library/pull/431 will fix this issue.

**Comment by bennothommo** [comment]
Should be resolved by https://github.com/octobercms/library/pull/431. Please re-open if this is not the case.
