### ISSUE TITLE
Overriding platform in composer.json

### ISSUE THREAD

**Issue by czerwonyd** [octobercms/october#4181]
- OctoberCMS Build: 440 - 448
- PHP Version: >=7.1

### Description:
While installing packages that requires PHP >=7.1 the installation fails, because of 

```
    "config": {
        "preferred-install": "dist",
        "platform": {
            "php": "7.0"
        }
    },
```
in `composer.json`. 

Example package: [Brick/Money](https://github.com/brick/money).

Despite the installation I guess PHP 7.0 should not be used any longer since it's support has ended in [the January 2019](http://php.net/supported-versions.php).

**Comment by w20k** [comment]
@czerwonyd take a look at the @daftspunk comment https://github.com/octobercms/october/commit/f12f3af37f491f26fe101c3a01458fa467455df0

**Comment by czerwonyd** [comment]
Oh you're right, I have missed it. But still I think, the PHP 7.0 compatibility is no longer needed when it's support has ended, don't you think?

**Comment by w20k** [comment]
I might agree with you or not, but I understand why @daftspunk freeze version because there would be even more issues related to dep hell (.dll).

**Comment by frthjf** [comment]
@w20k Does that mean one cannot create a marketplace plugin with a package dependency that requires PHP 7.1? That would be problematic as more and more packages make 7.1 a minimum requirement as 7.0 is EOL.

**Comment by w20k** [comment]
@frthjf pretty much, OCMS has it's own rules. When new LTS version will come to Laravel we will switch, I guess.

**Comment by czerwonyd** [comment]
@frthjf It is problematic especially for users of our plugins. I have added a note in [documentation of my plugin](https://octobercms.com/plugin/initbiz-money) and link to this issue so that more technical users can understand why installation of our plugin does not work.

**Comment by frthjf** [comment]
@czerwonyd Thanks, does that mean that I can publish through the marketplace but the users will have to modify their composer.json? Also, what happens if there is no composer.json because you used the wizard?

**Comment by czerwonyd** [comment]
@frthjf I probably have not tested all the possibilities, but generally speaking, yes - it will work for both of cases as long as you have the required PHP version installed of course.
