### ISSUE TITLE
Remove jenssegers/data and move for Carbon 2

### ISSUE THREAD

**Issue by rluders** [octobercms/october#4182]
Hello.

So, this week I got an issue reported at my [JWTAuth Plugin](https://github.com/rluders/oc-jwtauth-plugin/issues/22), and so I was investigating what could cause the issue. And I noticed that my plugin, has a dependency that uses Carbon 2, while OctoberCMS Library is using [jessegers/date](https://github.com/jenssegers/date/issues/310) that uses Carbon 1 as it's dependency. So, both packages are colliding, causing one error. Since Carbon is a very popular library, I think that is almost a bad ideia to keep it outdate inside the OctoberCMS core library.

So far, I noticed that *jensseger* don't have any plans to move his library to Carbon 2. So... I would like to propouse to us to remove his package as a dependency and uses only Carbon 2.

Searching into the code, I found 3 places where his dependency is being used, all of them inside the OctoberCMS Library:

https://github.com/octobercms/library/blob/master/src/Argon/Argon.php
https://github.com/octobercms/library/blob/master/src/Argon/ArgonServiceProvider.php
https://github.com/octobercms/library/blob/master/src/Database/Model.php

I could work on this if everybody agree with this change.

Hope to hear your thoughts about it.

**Comment by LukeTowers** [comment]
Go for it @rluders, as long as you can smoothly upgrade the dependency I don't have an issue with it. Are there big changes between Carbon 1 and Carbon 2? Carbon gets used a fair bit within OctoberCMS plugins both public and private.

**Comment by rluders** [comment]
@LukeTowers there's some differences between Carbon 1 and Carbon 2. I will run some tests, but I'm pretty sure that some things could break.

For now I'll just leave the [migrate document](https://carbon.nesbot.com/docs/#api-carbon-2) to Carbon 2 here.

**Comment by rluders** [comment]
Let me just add a small note here:

Maybe [this fix](https://github.com/jenssegers/date/issues/310) could help for now, but still, I think that we can use only Carbon 2.

**Comment by rluders** [comment]
Just to update the progress so far, if someone decide to try the same or if I die.

I did spent some time testing the things here and at this point I found 2 problems to use Carbon 2. Here we go:

**PHP 7.0**

The PHP version is locked to *7.0* in the *composer.json* file. It is not something compicated to change, but we need to discuss if we want to (I vote for yes). Also, if we move forward with it, is important to check the [migration guide](http://php.net/manual/en/migration71.php) first. 

**Laravel 5.5**

The OctoberCMS still using the Laravel 5.5, in this case, we have one problem here, since looks like it depends of Carbon 1. As you can see:

```
  Problem 1
    - laravel/framework v5.5.45 requires nesbot/carbon ^1.26.0 -> satisfiable by nesbot/carbon[1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2] but these conflict with your requirements or minimum-stability.
    - laravel/framework v5.5.45 requires nesbot/carbon ^1.26.0 -> satisfiable by nesbot/carbon[1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2] but these conflict with your requirements or minimum-stability.
    - laravel/framework v5.5.45 requires nesbot/carbon ^1.26.0 -> satisfiable by nesbot/carbon[1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2] but these conflict with your requirements or minimum-stability.
    - Installation request for laravel/framework (locked at v5.5.45, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.45].
```

It is possible that [this workaroud](https://stackoverflow.com/questions/53202646/how-to-use-carbon-2-in-laravel-5-5) works for us.

That's all for now. I'm very busy this week, but I'll try to explore more.

**Comment by TimFoerster** [comment]
Another alternative would be to wait 4 months for the new lts version, since laravel 5.8 moved to Carbon2.

**Comment by bennothommo** [comment]
Note that this is no longer necessary - jessengers/date now supports Carbon 2 as of [release 3.5.0](https://github.com/jenssegers/date/releases/tag/v3.5.0).
