### ISSUE TITLE
Method diffInRealSeconds does not exist.

### ISSUE THREAD

**Issue by skynett81** [octobercms/october#4184]
- OctoberCMS Build: ### 
- PHP Version: 7.1
- Database Engine: 
- Plugins Installed: 

### Description:
i did install some plugins (Discord) but after that i did get this error.

"Method diffInRealSeconds does not exist." on line 96 of /home/geektech/public_html/demo/october/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php

### Steps To Reproduce:
install Discord Plugin

**Comment by LukeTowers** [comment]
How did you install the plugin?

**Comment by skynett81** [comment]
Thru the backend Admin panel.


Den tor. 7. mar. 2019, 04:22 skrev Luke Towers <notifications@github.com>:

**Comment by LukeTowers** [comment]
What's the full stack trace?

**Comment by skynett81** [comment]
Its on a subdir on a cpanel server. I can check more when im home from work.


Den tor. 7. mar. 2019, 05:10 skrev Luke Towers <notifications@github.com>:

**Comment by alxy** [comment]
I've had this issue as well. It is due to some version clash in a plugin's vendor files - specifically it uses an older [Carbon](https://github.com/briannesbitt/Carbon) version.

Disabling the plugin should fix the issue. This needs to be fixed by the plugin author.

**Comment by kojaktaha** [comment]
I have the same Error when trying to install JWTAuth from Vdomah 

`"Method diffInRealSeconds does not exist." on line 96 of /home/codere5/gtd.coderepublic.net/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php`

I cant install any other plugin after that unless I delete this plugin cuz i get this error when ever I access the market from the backend 

It is really unique to this one project, I used it before and it was just fine

CMS Build 
447
Plugin Version
1.0.6 
PHP 
7.0.33

**Comment by LukeTowers** [comment]
@kojaktaha see
> This needs to be fixed by the plugin author.

**Comment by flyingbaba** [comment]
Might happen in some build. I had this issue after update to 458, had to open vendor/laravel/framework/src/Illuminate/Cache/Repository.php and on line 555 change function to the older method: $duration = Carbon::now()->diffInSeconds($duration, false) / 60;
