### ISSUE TITLE
File model query is very slow with large data

### ISSUE THREAD

**Issue by mabehiry** [octobercms/october#4188]
The file model query is very slow.  This is an example of a query used, it takes about 580 ms to execute. I'm viewing about 100 images in the page, so it takes a long time for the page to render.

SELECT * 
FROM   system_files 
WHERE  system_files.attachment_type = 'Me\Articles\Models\Article' 
       AND system_files.attachment_id = '235017' 
       AND field = 'image' 
       AND system_files.attachment_id IS NOT NULL 
ORDER  BY sort_order ASC 
LIMIT  1 

The table has about 220,000 records.

### Steps To Reproduce:
Insert a lot of records to a model and attach files to each one. Then try to get around 100 record with files in a page.
This is how I call the attachment:

echo $model->image->getPath();

### Suggestions:
I suggest these actions:
1- To remove this check:
AND system_files.attachment_id IS NOT NULL 

2- And to remove this also:
ORDER  BY sort_order ASC 

3- And to make this field int instead of varchar:
attachment_id

**Comment by w20k** [comment]
@mabehiry why not to add an index? Pretty sure it should solve your performance issue.

**Comment by mabehiry** [comment]
> @mabehiry why not to add an index? Pretty sure it should solve your performance issue.

There are already 3 indexes:
field
attachment_id
attachment_type

I added sort_order index also

**Comment by Teranode** [comment]
sometimes `attachment_id` isn't an integer (for instance I use uuids instead of ids)

I completely agree that `ORDER BY sort_order ASC` should be removed, it slows it down significantly, so instead i had to manually create the query without the sort order (on in some cases create my own sort after its been queried)

**Comment by w20k** [comment]
@Teranode could you provide a code analyze why it's generated there, I think it's something related to the QueryBuilder.

**Comment by Teranode** [comment]
It uses the sortable trait: 
https://github.com/octobercms/library/blob/develop/src/Database/Traits/Sortable.php

So what "could" be done is to set a variable for if you want sorting to be enabled from the trait, while also keeping the sortable train there so if you need to use it in the future you can just set the variable for sort to true when defining the relationship

**Comment by mabehiry** [comment]
When I run the query in MySql console, it takes only 0.0032 seconds. But in the CMS it takes 0.637 seconds.

This is the query:
select * from `system_files` where `system_files`.`attachment_type` = 'Sunsoft\Articles\Models\Article' and `system_files`.`attachment_id` = '143555' and `field` = 'image' and `system_files`.`attachment_id` is not null order by `sort_order` asc limit 1

![Screenshot_1](https://user-images.githubusercontent.com/33180080/54887074-eedc3700-4eb4-11e9-9e8e-d14e2f41218d.png)
![Screenshot_2](https://user-images.githubusercontent.com/33180080/54887075-eedc3700-4eb4-11e9-8263-0c83de1bf4c1.png)
And attached here the screenshot of query in CMS and in SQL console (the CMS debug is by Bedard.Debugbar)

**Comment by w20k** [comment]
@mabehiry Pure SQL will always be faster, no doubt!

**Comment by bennothommo** [comment]
I think a better optimisation would be to retrieve all the attached images in one query as opposed to doing a single query for each file. Even if the query is slow, it would be one slow query and not 100.

**Comment by w20k** [comment]
@bennothommo I was thinking the same, but my concern is to write tests, before breaking things 😄

**Comment by bennothommo** [comment]
@mabehiry Are you using an `attachOne` file association for this scenario?

**Comment by mabehiry** [comment]
@bennothommo  Yes I'm using attachOne

**Comment by bennothommo** [comment]
@mabehiry Thanks, I presume then that what you have set up is a page where you can view 100 articles in a single page, and each one has a single file upload for an image or some other file, is that correct?

If so, and if you want to avoid the loading delay right now, you could use the `mediafinder` widget instead of a `fileupload` widget to pick the image, as the `mediafinder` widget saves the URL of the media item into the database as a string, instead of using a separate model. This would drop the extra SQL query for each file upload.

**Comment by mabehiry** [comment]
@bennothommo Yes, it's a good idea. Thank you. But you know, when using fileupload I can crop the image and use various sizes. I use it for the thumb images.
Anyway, I used caching for images so that I don't need to call it every time. But I think if this is a better way to optimize SQL query, it will be good.
Thank you

**Comment by Teranode** [comment]
@LukeTowers I noticed that the SortableScope has this already: 
https://github.com/octobercms/library/blob/develop/src/Database/SortableScope.php#L20

Is that how it's suppose to be in that method?

**Comment by Samuell1** [comment]
> 1- To remove this check:
> AND system_files.attachment_id IS NOT NULL

This cant be removed or it will break relations. Tested it and if you remove that check it will automatically attach other file that is null.

**Comment by Samuell1** [comment]
This should be reopen

**Comment by bennothommo** [comment]
@Samuell1 Is this being worked on?

**Comment by w20k** [comment]
Don't think that anyone is dealing with it currently.

**Comment by bennothommo** [comment]
@Samuell1 no worries, I have re-opened it pending your PR.

**Comment by Samuell1** [comment]
@bennothommo thanks!

Another thing is that why file relation has sortable trait added on it that is maybe second big performance hit.

**Comment by mabehiry** [comment]
Any update about this issue? I am still suffering from very slow file queries.
Also, are there any advices about creating indexes to speed up the query?

**Comment by mabehiry** [comment]
I am getting this query in slow queries log:
select * from `system_files` where 
(
    `system_files`.`attachment_type` = 'Plugin\\Articles\\Models\\Article' and `system_files`.`attachment_id` = 243142 and `field` = 'image' and `system_files`.`attachment_id` is not null or system_files.id in 
    (
        select `slave_id` from `deferred_bindings` where `master_field` = 'image' and `master_type` = 		 
        'Plugin\\Articles\\Models\\Article' and `session_key` = 'tZj3TeXfwBIfQ05ZcdnNd3RFriWU77depifMy9a7' 
        and `is_bind` = 1
    )
) 
and system_files.id not in 
(
    select `slave_id` from `deferred_bindings` where `master_field` = 'image' and `master_type` = 'Plugin\\Articles\\Models\\Article' and `session_key` = 'tZj3TeXfwBIfQ05ZcdnNd3RFriWU77depifMy9a7' and `is_bind` = 0 and id > ifnull
    (
        (
            select max(id) from deferred_bindings where
            slave_id = system_files.id and
            master_field = 'image' and
            master_type = 'Plugin\\Articles\\Models\\Article' and
            session_key = 'tZj3TeXfwBIfQ05ZcdnNd3RFriWU77depifMy9a7' and
            is_bind = 1
        ), 0
    )
)
order by `sort_order` asc

**Comment by Samuell1** [comment]
@mabehiry Hey, check this https://octobercms.com/support/article/rn-13#section-database maybe it helps if you using old table scheme.

**Comment by daftspunk** [comment]
> @mabehiry Hey, check this https://octobercms.com/support/article/rn-13#section-database maybe it helps if you using old table scheme.

Yes, this has been addressed in v2.0 and above, with a significant increase in performance.
