### ISSUE TITLE
upgrade to 448 causing install plugins breakage

### ISSUE THREAD

**Issue by Caraz1** [octobercms/october#4189]
- OctoberCMS Build: 1.0.448
- PHP Version: 7.3.3
- Database Engine: mysql
- Plugins Installed: 
October Demo  | 1.0.1 | Alexey Bobkov, Samuel Georges
Sitemap |1.0.8 | Alexey Bobkov, Samuel Georges
Toolbox | 1.22.0 | Lovata
Shopaholic | 1.21.1 | Lovata
Blog | 1.3.1 | Alexey Bobkov, Samuel Georges
Wysiwyg Editors | 1.2.9 | Anand Patel
Blog Video Extension| 1.1.2 | Alexey Bobkov, Samuel Georges
Blog RSS Feed | 1.1.0 | Josh Hall
User | 1.4.6 | Alexey Bobkov, Samuel Georges
Forum | 1.2.0 | Alexey Bobkov, Samuel Georges
Piwik Free/Libre Analytics | 1.0.2 | Stage Right Labs
wiki | 1.0.4 | octoplus
Txt | 1.1.2 | Saifur Rahman Mohsin
Clear Cache | 1.3.0 | Alexander Romanov
Backend Plus | 1.6.8 | Gergő Szabó
Orders for Shopaholic | 1.19.0 | Lovata
Buddies | 1.7.1 | Lovata
Multisite || 1.1.1 | Keios
FAQs | 1.1.1 | piersroberts@gmail.com
Pages | 1.2.20 | Alexey Bobkov, Samuel Georges
Twig Extensions | 1.2.4 | Vojta Svoboda
Translate | 1.4.5 | Alexey Bobkov, Samuel Georges

### Description:
After upgrading from 1.0.447 to 1.0.448  the "Settings -> Updates & Plugins -> Install products" produces the following error:
"Array to string conversion" on line 282 of ../../../vendor/october/rain/src/Network/Http.php"

The first part of the path has been removed for privacy reasons. Only point of note here is that it is a sub directory install. Unrelated at a guess.

**Comment by w20k** [comment]
@Caraz1 Please upgrade to the latest edge version change, it was already fixed/reverted. Thank you!
By @LukeTowers here https://github.com/octobercms/library/commit/21b00902c8bf1265b643374f0a54e88074242acf
