### ISSUE TITLE
Relations should support "delete" for cascading

### ISSUE THREAD

**Issue by daftspunk** [octobercms/october#419]
Related: https://github.com/laravel/framework/issues/1612

Instead of declaring it in a cascadeDelete property, it could be simply declared in the relation.

```
[..., 'delete' => true, ...]
```

**Comment by damarisz** [comment]
I have been trying to get the cascading delete behavior by adding a "delete" setting in the relationship. According to the docs if  delete is set to true, the related model will be deleted if the relationship is destroyed.
My relationship is as follows:
 One MODULE has many MODULE_ITEMS


public $hasMany = [
            'module_items' => ['Delphinium\Core\Models\ModuleItem', 
            'foreignKey' => 'module_item_id',
            'delete'=>'true']
    ];

In my other model I have:

public $belongsTo = [
        'module' => ['Delphinium\Core\Models\Module', 
        'foreignKey' => 'module_id',
        'delete'=>'true']
    ];

But when I delete a Module, the module items are not being deleted automatically. 
What am I missing?
