### ISSUE TITLE
CMS page editor cannot correctly expand relative partials

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#4195]
- OctoberCMS Build: 448 (irrelevant)
- PHP Version: no matter

### Description:

For example, when defining a component template, we can use partials. I included them this way:

    <ul id="{{ __SELF__.alias }}-list">
        {% partial "@list" %}
    </ul>

    <nav id="{{ __SELF__.alias }}-pagination">
        {% partial "@pagination" %}
    </nav>

And it worked fine until I tried to expand my template in CMS page editor:

![image](https://user-images.githubusercontent.com/3897579/54340080-795ba580-462e-11e9-8f5e-80c37cbf66d8.png)

So the system still uses "@" and therefore it tries to find a partial relative to the theme, which obviously results in error:

![image](https://user-images.githubusercontent.com/3897579/54340166-b2941580-462e-11e9-97f5-6bfa8fe0ef39.png)

On the contrary, if I include the same partials like this:

    <ul id="{{ __SELF__.alias }}-list">
        {% partial __SELF__ ~ "::list" %}
    </ul>

    <nav id="{{ __SELF__.alias }}-pagination">
        {% partial __SELF__ ~ "::pagination" %}
    </nav>

It works fine and looks for a partial relative to the plugin, not the theme:

![image](https://user-images.githubusercontent.com/3897579/54340317-069efa00-462f-11e9-9671-eb2f914686e0.png)

But this one has another possible enhancement. Partials cannot be further expanded, though it would be useful to make them further expandable:

![image](https://user-images.githubusercontent.com/3897579/54340429-3fd76a00-462f-11e9-865e-0060f23a7e68.png)

**Comment by w20k** [comment]
@GinoPane I don't think it's a bug, but more likely not `well-documented` feature.

**Comment by GinoPane** [comment]
Maybe, but I didn't find anything that could me restrict from using partials like that, and if we can use them like that the expand should cover thit case as well 😄

**Comment by LukeTowers** [comment]
> OctoberCMS Build: 448 (irrelevant)
PHP Version: no matter

Those are there for a reason, no need to be snarky 😜 

Also, this is documented, albeit not in the themes section: https://octobercms.com/docs/plugin/components#component-partials

**Comment by GinoPane** [comment]
@LukeTowers 😄 Yes, but in the context of the question I thought it would be not so important info.
Regrading docs - yes, using of partials in component context is documented and that's why I know how to use those partials differently, but still, the expanding logic is not described.

**Comment by LukeTowers** [comment]
@GinoPane feel free to make a PR to clarify that further, I'm always happy to get improvements to the docs!

**Comment by GinoPane** [comment]
But why do you both think that it is the docs that need to be fixed, and not the expanding logic? 😄 I opened one more issue in that area (#4197).
Btw, no response from hello@octobercms.com and plugin still cannot be updated. I wonder if I the only one who experience this.

**Comment by LukeTowers** [comment]
@GinoPane I'm not sure I know what you mean by 'expanding logic'

**Comment by GinoPane** [comment]
@LukeTowers the logic behind the button which expands component template into theme's template.

**Comment by alxy** [comment]
@GinoPane Would you expect the @-sign to be replaced by the component alias as well? However, even that might not work in every case, namely in the case of a shared partial. That makes it extremely complex to find a solution here I would say.

**Comment by GinoPane** [comment]
@alxy do you mean it works after additional replacement in that method?

**Comment by alxy** [comment]
@GinoPane No, it just works with the current build.

**Comment by GinoPane** [comment]
@alxy Hm, that's strange. Maybe you have necessary partial somewhere in a theme folder so it can be discovered?
