### ISSUE TITLE
Allow Updates and Plugins List to be Sortable

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4196]
I would like to request a feature where the Plugins Update list be able to make each column sortable. For example it would make life easier if we could have the **_list of plugins in alphabetical order_** - thus finding the plugins easier!

Current Screenshot:

![1](https://user-images.githubusercontent.com/17784082/54370262-3a9a0f80-466f-11e9-8fea-9481d48349cd.png)

Proposed Idea Screenshot:

![2](https://user-images.githubusercontent.com/17784082/54370488-9b294c80-466f-11e9-9058-aa7657561fae.png)

To add the normal October CMS functionality to sort the column lists in the list view.

**Comment by ayumihamsaki** [comment]
Did a quick research and found the file location: https://github.com/octobercms/october/blob/master/modules/system/models/pluginversion/columns.yaml

Any reason to turn off the sortable function ?

**Comment by LukeTowers** [comment]
@ayumihamsaki feel free to do that, it should be as easy as setting `sortable: true` on those columns.

**Comment by ayumihamsaki** [comment]
If only life was that easy - I would go and fix every issue under the octobercms repo for you in a day lol.

I added `sortable: true` to the first column and ran a test and see there is no database connected to the list, see error:

![qqq](https://user-images.githubusercontent.com/17784082/54381936-d7b47280-4686-11e9-9c2d-f6e264c0e75d.png)

File Location: https://github.com/octobercms/october/blob/master/modules/system/models/pluginversion/columns.yaml

**Comment by LukeTowers** [comment]
There is a database table associated, it's just that only the code and version columns are present. We could have it sort by the code and display the name, but it'd be sorting by author at that point basically. https://github.com/octobercms/october/blob/master/modules/system/models/PluginVersion.php#L16

**Comment by ayumihamsaki** [comment]
I was just looking at the database table and the name column and I think they wont match due to it getting sorted by alphabetical order on the author name and not the plugin name. Would it be better just to add a new column called `name` to the `system_plugin_versions` table and create a seeder file?

Maybe it's just me but I rather search for the Plugin Name and not the author Name.

Will save this issue, as busy right now with a few plugins. If someone wants to fix this issue in the mean time, please go ahead. Otherwise I will have a go on this in a few months time (when I finished all my work).

**Comment by ayumihamsaki** [comment]
Closed see here: https://github.com/octobercms/october/issues/4345
