### ISSUE TITLE
Error while trying to install by update & plugin setting

### ISSUE THREAD

**Issue by fabriciorabelo** [octobercms/october#4205]
- OctoberCMS Build: 448 
- PHP Version: 7.1.26
- Database Engine: InnoDB
- Plugins Installed: October.Drives, RainLab.Location, RainLab.Builder, RainLab.User

**Comment by w20k** [comment]
It was already fixed in the 448, or should be.
Try updating via composer, or manually correct this line:
https://github.com/octobercms/library/commit/21b00902c8bf1265b643374f0a54e88074242acf
