### ISSUE TITLE
Broken media image link after adding an image in a repeater in backend settings tab

### ISSUE THREAD

**Issue by Mohmdthabet** [octobercms/october#4206]
- OctoberCMS Build: 446
- PHP Version: 7.0
- Database Engine: MySQL

### Description:
When uploading an image to a repeater inside the back end settings, the link includes the theme folder twice.

### Steps To Reproduce:
add a repeater to settings 
add an image inside the repeater
upload any media image

**Comment by w20k** [comment]
Should be fixed in 447 build.
Both are related:
https://github.com/octobercms/october/pull/4055
https://github.com/octobercms/october/pull/3536

Reopen if the bug still persists.

**Comment by Mohmdthabet** [comment]
Thanks it is now fixed
