### ISSUE TITLE
Twig 2.7.4 breaks OctoberCMS w/ RainLab.Pages

### ISSUE THREAD

**Issue by adrenth** [octobercms/october#4209]
- OctoberCMS Build: 447
- PHP Version: 7.2.16
- Plugin: RainLab.Pages

### Description:

The Twig loader causes OctoberCMS to generate a fatal error:
modules/cms/twig/Loader.php:64

```
Type error: Argument 1 passed to Twig\Source::__construct() must be of the type string, null given, called in ../modules/cms/Twig/Loader.php on line 63
```

The use of `Twig_Source` is deprecated as of Twig v2.7, it should be replaced with:

old:
```
return new Twig_Source($dataHolder->content, $name);
```

new (suggested fix):
```
return new Twig\Source((string) $dataHolder->content, $name);
```

Mention the cast to a string. Obviously the `$content` some lines above can be `NULL` and will trigger the error. This is just an example, I think we have to make sure the $dataHolder->content must be a string at all time.

### Steps To Reproduce:

- Perform a composer update which will install `twig/twig:2.7.4`.
- Create a page using Static Pages plugin
- Visit the page

**Comment by Balex70** [comment]
Facing the same problem after composer update (Twig 7.2.2 -> 7.2.4).
OctoberCMS Build: 447
PHP Version: 7.1.17

**Comment by w20k** [comment]
@adrenth  shouldn't it be as a part of Rainlab.Pages issues or may be linked?

**Comment by adrenth** [comment]
This is linked to the Pages plugin I found out. But... the return value of `getTwigContent()` in this particular function should always be a `string`. 

Since OC is not that strict with PHP data types this issues should be resolved by making sure the correct types are provided. Do not make assumptions, but make sure the correct datatype is used.

In this case a cast-to-string solution may fix a lot of future problems.

**Comment by seanthepottingshed** [comment]
@adrenth Thanks so much!!!!

**Comment by tobias-kuendig** [comment]
Using a cast on `(string) $dataHolder->content` is fixing the issue for our projects as well.

**Comment by tobias-kuendig** [comment]
https://github.com/octobercms/october/pull/4215

Please test and report if it needs any additions.

**Comment by w20k** [comment]
@adrenth , @seanthepottingshed  @Balex70  - could you guys re-test PR from @tobias-kuendig ?

**Comment by Balex70** [comment]
For me it works on fresh new installation!

**Comment by seanthepottingshed** [comment]
@w20k 

Tested works for me on the project I'm currently working on.

**Comment by nizzac** [comment]
@tobias-kuendig Fix working for me on an October install updated from 443 to 447.

**Comment by tobias-kuendig** [comment]
Don't want to be pushy but can we get this merged and released then? We're having more and more customers who trigger updates and break their websites. :sweat_smile: 

Also, if I'm not mistaking, this bug also affects all new installations.

**Comment by adrenth** [comment]
@tobias-kuendig @w20k @LukeTowers Reviewed the PR and it's good to go.

**Comment by LukeTowers** [comment]
Please test #4218

**Comment by w20k** [comment]
Bump, guys @adrenth, @seanthepottingshed, @Balex70, if you have a minute, please re-test @LukeTowers PR and will be merged! 

Neat trick to get PR patch: https://patch-diff.githubusercontent.com/raw/octobercms/october/pull/4218.patch

**Comment by adrenth** [comment]
Applied the patch on a fresh project:

- Fetched the latest packages using `composer update`
- Installed latest `Rainlab.Pages` plugin.
- Created a page '/test' with some content
- Navigated to page; no error.
