### ISSUE TITLE
VersionManager update caused migration files with dots in filename to be treated as messages

### ISSUE THREAD

**Issue by slowpokefarm** [octobercms/october#4210]
- OctoberCMS Build: ### 448
- PHP Version: 7.2
- Database Engine: Mysql 8
- Plugins Installed: -

### Description:
Migrations files with dots in filenames are not executed in update cycle.

### Steps To Reproduce:
- In versions.yml create a version:

```
1.0.2:
- Example migration
- 1.0.2_update_tables.php
```

- Create a migration  file named 1.0.2_update_tables.php
- execute command `php artisan october:up`

Migration will not be executed, but migration file name will appear as a message

**Comment by w20k** [comment]
@GinoPane could you look at this issue :) Sounds like a regexp issue.

Related PR: https://github.com/octobercms/october/commit/9581b23d1e85ccfdc283946894afa2df177b304f

**Comment by GinoPane** [comment]
@w20k it is!

**Comment by w20k** [comment]
@GinoPane could you provide a fix for that?

**Comment by w20k** [comment]
@slowpokefarm - could your test this PR from @GinoPane if it helped?

**Comment by slowpokefarm** [comment]
@w20k @GinoPane Works now, thanks!
