### ISSUE TITLE
Error 500 after trying update to 447

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#4213]
- OctoberCMS Build: ### 444 (from memory)
- PHP Version: 7.2.14
- Database Engine: MySQL5.5
- Plugins Installed: 
Rainlab.user
Rainlab.translate
VojtaSvoboda.TwigExtensions
offline.cors
Indikator.Backend
Ideas.Shop

### Description:

no more access to anything after trying to update to 447 (or to 448 dont remember well)

[26-Mar-2019 16:08:04 Asia/Singapore] PHP Fatal error:  Class Illuminate\Database\Eloquent\Collection contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Queue\QueueableCollection::getQueueableRelations) in /Users/christophevidal/Sites/oc-scheduler/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php on line 11
[26-Mar-2019 16:08:04 Asia/Singapore] PHP Fatal error:  Uncaught Error: Class 'October\Rain\Database\Collection' not found in /Users/christophevidal/Sites/oc-scheduler/vendor/october/rain/src/Database/Model.php:608
Stack trace:
#0 /Users/christophevidal/Sites/oc-scheduler/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(261): October\Rain\Database\Model->newCollection(Array)
#1 /Users/christophevidal/Sites/oc-scheduler/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1477): Illuminate\Database\Eloquent\Builder->hydrate(Array)
#2 /Users/christophevidal/Sites/oc-scheduler/vendor/october/rain/src/Extension/ExtendableTrait.php(423): Illuminate\Database\Eloquent\Model->__call('hydrate', Array)
#3 /Users/christophevidal/Sites/oc-scheduler/vendor/october/rain/src/Database/Model.php(635): October\Rain\Database\Model->extendableCall('hydrate', Array)
#4 /Users/christophevidal/Sites/oc-scheduler/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(481): October\Rain\Database\Model->__call('hydrate', Array)
#5 /Users/c in /Users/christophevidal/Sites/oc-scheduler/vendor/october/rain/src/Database/Model.php on line 608

### Steps To Reproduce:
running the updates process from backend

**Comment by LukeTowers** [comment]
@chrisvidal this is a laravel version conflict caused by one of your plugins that is incorrectly including a version of laravel within it's own vendor directory. See https://octobercms.com/docs/plugin/composer for more information on how you should be using composer with your plugins.

**Comment by chrisvidal** [comment]
Hmmm Thanks Luke, so it is probably coming from a composer from one of my plugins then. 
not sure how to look at this.

```json
"require": {
        "php": ">=7.0",
        "guzzlehttp/guzzle": "^6.3",
        "league/fractal": "^0.17.0",
        "tymon/jwt-auth": "0.5.*",
        "brexis/laravel-workflow": "^1.2"
    },
```

**Comment by chrisvidal** [comment]
I found the culprit, Thanks @LukeTowers 

```json
        "brexis/laravel-workflow": "1.1.2"
```

**Comment by chrisvidal** [comment]
Hmm except that now, the System Update button is not triggered anymore after clicking from the backend

**Comment by LukeTowers** [comment]
What do you mean it's not triggered anymore? Any error messages in the console?

**Comment by chrisvidal** [comment]
When I click the 'update plugins' button, nothing is happening.

I had to remove my composer folder first, then the button works again, then
install my vendor files after.


Christophe Vidal
C.T.O. at  Voilaah
A  29B Mosque Street, Singapore 059507
W  http://voilaah.com  <http://voilaah.com>

Create your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>

**Comment by LukeTowers** [comment]
Weird.
