### ISSUE TITLE
cms.page.beforeRenderPartial does not work as documented

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#4214]
The documentation for cms.page.beforeRenderPartial seems to indicate you can change the path to a partial, but this generates an exception `Type error: Argument 1 passed to Cms\Twig\Loader::setObject() must implement interface Cms\Contracts\CmsObject, string given` at line 1088 in the `Cms\Classes\Controller`. If the event handler returns a `Cms\Classes\Partial` then it works. Which is correct, the documentation or the implementation?

**Comment by seanthepottingshed** [comment]
Would it be related to this? https://github.com/octobercms/october/issues/4209

**Comment by SeriousKen** [comment]
@seanthepottingshed not sure its related. It seems to be when returning a string from the event handler as documented it sets `$partial` to the result.

https://github.com/octobercms/october/blob/3118660d834f161d513da08477be92281a2eb96a/modules/cms/classes/Controller.php#L944-L963

When it hits line 1088 then setObject expects `$partial` to be a  `Cms\Contracts\CmsObject` and throws the exception.

https://github.com/octobercms/october/blob/3118660d834f161d513da08477be92281a2eb96a/modules/cms/classes/Controller.php#L1084-L1091

I could submit a fix, but what is the expected behaviour? Do we make it work as documented or do we change the documentation?

**Comment by LukeTowers** [comment]
@SeriousKen change the documentation.

**Comment by LukeTowers** [comment]
Fixed
