### ISSUE TITLE
Backend can not create Admin

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#4219]
- OctoberCMS Build: ### 447
- PHP Version: 7.1
- Database Engine:mysql 5.5
- Plugins Installed: Rainlab.user, Rainlab.page

### Description:
i create a new backend user role, then I try to create a new admin and get this error:

```
"SQLSTATE[HY000]: General error: 1364 Field 'version_id' doesn't have a default value (SQL: insert into `backend_users` (`is_superuser`, `login`, `email`, `first_name`, `last_name`, `password`, `persist_code`, `role_id`, `permissions`, `updated_at`, `created_at`) values (0, toto@a.org.sg, titi@a.org.sg, Admin, ASME, $2y$10$fsdfdsX12fsdkZ8gdfJhogdfX6GYXLJFzSs4jXjt5gRYF5YD2, , 3, , 2019-03-29 14:50:29, 2019-03-29 14:50:29))" on line 664 of /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php
```

### Steps To Reproduce:
create a new backend user and try to save

**Comment by LukeTowers** [comment]
This was an issue with one of the old plugin migrations you ran when you initialized your database, not an issue.
