### ISSUE TITLE
Error with datepicker form widget, invalid date format

### ISSUE THREAD

**Issue by fabriciorabelo** [octobercms/october#4222]
- OctoberCMS Build: 447 
- PHP Version: 7.1.26
- Database Engine: InnoDB 
- Plugins Installed: RainLab.User, Rabelo.UserPlus

### Description: 
I'm getting an error while trying to save user record, invalid date format.

### Steps To Reproduce:

 I'm extending RainLab.User with my plugin but while editing user record, without change the current date of birthday (the extended field) already saved , i got the error. Take a look:

The hidden field get the formatted value instead database saved value:
![image1](https://fabricioprabelo.com.br/storage/app/media/error_while_save_datepiker.jpg)

![image2](https://fabricioprabelo.com.br/storage/app/media/error_while_save_datepiker2.jpg)

![image2](https://fabricioprabelo.com.br/storage/app/media/error_while_save_datepiker3.jpg)

**Comment by LukeTowers** [comment]
@fabriciorabelo You need to add your field to the `$dates` property of the model you're modifying.
```php
public function boot()
{
    \RainLab\User\Models\User::extend(function ($model) {
        $model->dates = array_merge($model->dates, ['dob']);
    });
});
```
