### ISSUE TITLE
RecordFinder Is Broken v450

### ISSUE THREAD

**Issue by AugmentBLU** [octobercms/october#4223]
- OctoberCMS Build: 450
- PHP Version: 7.3
- Database Engine: MySQL
- Plugins Installed: Test Plugin

### Description:
Using a fresh install of 450 and OC official test plugin, the record finder is not working. You can see the popup to select a record but on selecting, the input is empty. 

### Steps To Reproduce:
On a fresh install of 450, using OC test plugin - go to `october/test/people/update/6`
With the default Record Finder field, click to select a record
Select a record from the popup, after selection the field remains empty

This is happening on another 2 sites that use edge updates and have been updated to 450. 

No JS errors are appearing in the console and I'm not seeing any other errors in the OC log.

Tested in Chrome 73 and FireFox 66 on Windows 10 

Tested on Samsung S9 Chrome

*** UPDATE ***

Something real weird is going on here. I've tried to roll back an install, edge updates are now off and it's pulling 450 but on completing composer update it says build 447. I tried deleting the modules and vendor folder, I ran composer update again and it's saying OC 450 is being downloaded but on completion it sets the build to 447. From what I see, 447 is the latest master build but it's pulling 450 through. 

I forced 447 and 449 through composer and it's working again so something in 450 is causing an issue. Without any errors, I have no idea what it is.

**Comment by LukeTowers** [comment]
The build number in the backend is very misleading, especially when using composer. It's just the latest stable build number (unless you have edgeUpdates enabled), in which case it's the latest edge build number. 

It would have to be one of the following changes:
https://github.com/octobercms/october/commit/288d9543afb5f856a03f03b68dca96e4ed1f410a
https://github.com/octobercms/october/commit/c5bc804d7398522783fbd76b2764f9541747867d
https://github.com/octobercms/october/commit/5190c8177bbb6531836ad8fa8458111361a35608

**Comment by w20k** [comment]
@LukeTowers will retest tomorrow with the latest build. Js/Css shouldn't be a problem here :)

**Comment by reinarudo** [comment]
I'm not sure if this is related, as I'm still learning october cms, and please excuse my English. I was following wacth and learn (Ivan)'s tutorial on youtube about Backend Filters. However the conditions on the filter yaml file are not being executed. The only filter that was working was the switch filter. 

After some digging on the codes on modules\backend\widgets\Filter.php, it seems like all the filters are not passing on line 683 except for the switch filter.

I have tried using a fresh installation via wizard installation and it's working properly. It seems like a problem with the latest repo releases.

**Comment by rajakhoury** [comment]
Same issue

**Comment by LukeTowers** [comment]
@reinarudo please post a new issue with what you have found, include as much detail as possible.

@rajakhoury "same issue" or "+1" comments are not helpful, especially when someone else has just posted a completely unrelated issue above. Please keep those comments just as reactions to the initial comment, i.e. as a thumbs up on the first comment posted.

**Comment by w20k** [comment]
Will be fixed as a part of stable 450 build ;)
