### ISSUE TITLE
Migration files in sub directories treated as comment

### ISSUE THREAD

**Issue by rajakhoury** [octobercms/october#4224]
OctoberCMS Build: 450
PHP Version: 7.3.2 

**Description:**

I have my plugin migration files organized into sub-directories but since last updates these are treated as comment. Is this intentional ?

**Steps To Reproduce:**

Create multiple folders inside your `plugin/updates` folder and add any migration files / seeds.

    1.0.1:
        - First version of Plugin
        - user/create_user_table.php
        - seeds/seed_users.php

Looking at `system_plugin_history` table `user/create_user_table.php` and `seeds/seed_users.php` are added as comment.

**Comment by w20k** [comment]
@GinoPane could you look at this one as well 😄
