### ISSUE TITLE
Backend Filters not working (Composer installation)

### ISSUE THREAD

**Issue by reinarudo** [octobercms/october#4226]
- OctoberCMS Build: v1.0.450  (commit: cca64db)
- PHP Version: 7.1.7
- Database Engine: MySQL 5.7.19
- Plugins Installed: Rainlab.Builder-v1.0.23 

### Description:
All scope types when creating custom List filter not working as well (except for Switch) 

Fresh install via wizard installation (working)
![image 1](https://content.screencast.com/users/reynald.tolentin/folders/Jing/media/f5384e1a-6422-44f5-b7ce-5176b851ef48/2019-03-31_2203.png "image 1")

Fresh install via composer (not working)
![image 2](https://content.screencast.com/users/reynald.tolentin/folders/Jing/media/2c2507d2-50ca-42e1-a553-f3b3f4f0da17/2019-03-31_2208.png "")

### Steps To Reproduce:
Install Rainlab.Builder plugin and create a basic CRUD app then try filtering from the list.

**Comment by alxy** [comment]
This is not a filter, but the list search.

**Comment by reinarudo** [comment]
Pardon with the terminology since I just started learning about this cms 2 days ago.

It happens with List Filters as well. I'm following this doc: https://octobercms.com/docs/backend/lists#adding-filters

**Comment by LukeTowers** [comment]
Issue will be fixed in the next build
