### ISSUE TITLE
Repeater Form Widget

### ISSUE THREAD

**Issue by fashakra** [octobercms/october#4228]
- OctoberCMS Build: 450 
- PHP Version: 7.1
- Database Engine: MySQL
- Plugins Installed: 

### Description:

The repeater fields are being saved as blank

### Steps To Reproduce:

The hidden field in the repeater widget that has a prefix defined as const INDEX_PREFIX = '___index_';  is being replaced in the page with an extra prefix before the underscores. This is making the form save the fields as blank. I dont know the reason why this is happening, my application is hosted on Bluehost.
When i added an extra character at the begginning of the prefix 
INDEX_PREFIX = 'p___index_';    (for example)
This solved the problem.

**Comment by LukeTowers** [comment]
What build number are you on?

**Comment by w20k** [comment]
@LukeTowers I think it's the same bug: https://github.com/octobercms/october/issues/4223

**Comment by fashakra** [comment]
build 450

**Comment by LukeTowers** [comment]
@w20k might be. @fashakra can you confirm that your local copy of that file is the same as https://github.com/octobercms/october/blob/develop/modules/backend/formwidgets/Repeater.php#L112, specifically the `$this->alias.self::INDEX_PREFIX.$fieldName;` part?

**Comment by fashakra** [comment]
$this->indexInputName = $this->alias.self::INDEX_PREFIX.$fieldName;
$this->groupInputName = $this->alias.self::GROUP_PREFIX.$fieldName;

$this->alias are missing from my version!
