### ISSUE TITLE
Repeater field did not save data

### ISSUE THREAD

**Issue by huynhnamegal** [octobercms/october#4229]
- OctoberCMS Build: 447
- PHP Version: 7.0.26
- Database Engine: MySQL

### Description:
In morning, I try to run command "composer update" and composer update modules of OctoberCMS, it change some files. After updating, all of my repeater fields did not save any data.
I rollbacked to before updating and my repeater fileds still working. But now, I tried "composer update" again, no changes in modules folders. Is Build 450 changes?

**Comment by cheb60** [comment]
I can confirm this bug. It only saves an JSON string containing empty arrays.

**Comment by LukeTowers** [comment]
Duplicate of #4223 and #4226. Fixed in the latest library dev branch, fix will be available in build 451.

**Comment by tfprado** [comment]
@LukeTowers When will build 451 be available?

**Comment by w20k** [comment]
Should be fixed soon ;)

**Comment by LukeTowers** [comment]
Already out @tfprado https://packagist.org/packages/october/backend#v1.0.451, https://octobercms.com/changelog.
