### ISSUE TITLE
Add method/event after sorting

### ISSUE THREAD

**Issue by jexme** [octobercms/october#4243]
It may be worth adding an event, or a method in the model, after the records are sorted (ReorderController, onReoder method).

As an example, this would be very useful if the model data is cached and you need to clear the cache after a change in sorting.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
