### ISSUE TITLE
Branded emails: incorrect word-break in Outlook clients

### ISSUE THREAD

**Issue by vevers** [octobercms/october#4251]
- OctoberCMS Build: 451
- PHP Version: 7.1
- Database Engine: n.a. (5.7.19)
- Plugins Installed: n.a.

### Description:
All emails using the default branded css do seem to have word-break issues in Outlook clients. Words are broken at random points due to the "word-break: all" css setting.

See the following link for example renders: [https://litmus.com/checklist/emails/public/15ff7f9](https://litmus.com/checklist/emails/public/15ff7f9)

### Steps To Reproduce:
1. Create a mail-template containing large sentences.
2. Send out a (test) mail
3. Open mail in any Outlook client.

### Possible solution:
The corresponding CSS is located in:
`modules/system/models/mailbrandsetting/custom.less`

> body {
>     background-color: @body-bg;
>     color: @text-color;
>     height: 100%;
>     hyphens: auto;
>     line-height: 1.4;
>     margin: 0;
>     -moz-hyphens: auto;
>     **-ms-word-break: break-all;**
>     width: 100% !important;
>     -webkit-hyphens: auto;
>     -webkit-text-size-adjust: none;
>     **word-break: break-all;**
>     word-break: break-word;
> }
> 

Changing "break-all" to "break-word" fixes the problem. I'm unsure however why "word-break: break-all;" was used in the first place.

**Comment by w20k** [comment]
@vevers can't you override this option on your own? 
It was maybe to cover really long words, like -> API keys, or something similar.
```
word-break: break-all;
word-break: break-word;
```
that's definitely a small bug :)

**Comment by vevers** [comment]
We've tried overwriting the CSS in multiple ways (head, body, inline, different selectors, etc.), but without any luck. If "word-break: break-all" is applied to the body it somehow seems to be impossible to overwrite this in Outlook. Might be an Outlook bug.

And although it might seem like a small bug, it results in corrupted emails for all Outlook users (mostly business users) when using the default OctoberCMS settings.

**Comment by LukeTowers** [comment]
@vevers feel free to submit a PR to fix it
