### ISSUE TITLE
Add dependsOn support to Filters

### ISSUE THREAD

**Issue by huynhnamegal** [octobercms/october#4254]
How can I filter the list base on other filter's?
Example, I want to choose province to get list of districts for filter list.

I tried  $this->widget->listFilter->getScopeValue({scope_name});, but it did not work.
I tried to set some default value for array and it worked.

![image](https://user-images.githubusercontent.com/20609668/56016839-bb5c3200-5d27-11e9-9280-0bc2e9618de7.png)

![image](https://user-images.githubusercontent.com/20609668/56017005-39203d80-5d28-11e9-9d9e-9544d8b58094.png)

My English is not good, so hope you sympathize.
Thanks!

**Comment by LukeTowers** [comment]
It's not currently possible without some fairly ridiculous hacking (sample of something I've done before below, very brittle though)

Controller class: (abuse `Config::set()` as a temporary in-request key-value store)
```php
    /**
     * Get the Service ID list from the service filter, and stored it in the memory cache
     * The getSubLocationOptions (In Asset Model) can get this value from the Config
     *
     * @param Filter $filter
     * @return void
     */
    public function listFilterExtendScopes($filter)
    {
        $locationFilter = $filter->getScopes()["default_location"]->value ?? [];
        $recordIds = array_keys($locationFilter);
        Config::set('captive.Assets.controllers.assets.filter.location.active', $recordIds);
    }
```

Model class:
```php
    public function getSubLocationOptions()
    {
        $locationIDs = Config::get('captive.Assets.controllers.assets.filter.location.active', []);
        $query = SubLocation::select('id', 'name', 'abbreviation');
        if (count($locationIDs) > 0) {
            $query = $query->whereIn("location_id", $locationIDs);
        }
        $sublocations = $query->get();
        $results = [];
        foreach ($sublocations as $sublocation) {
            $results[$sublocation->id] = $sublocation->name . ' - ' . $sublocation->abbreviation;
        }
        return $results;
    }
```

It would be nice to support `dependsOn` in the filter configs though like we can with fields, but I don't have time to look into adding that functionality right now.

**Comment by LukeTowers** [comment]
This will be completed at some point this month as @LarBearrr's company has offered to sponsor it.

**Comment by LarBearrr** [comment]
Thanks @LukeTowers, can we get placed on the Sponsors page 😆

**Comment by LukeTowers** [comment]
@LarBearrr if your company signs up as a partner or makes a donation :) Otherwise paid feature requests are just that 😝

**Comment by LukeTowers** [comment]
Completed in #4764
