### ISSUE TITLE
Intercept posted data using the Javascript API  ( Ajax forms )

### ISSUE THREAD

**Issue by rajakhoury** [octobercms/october#4257]
- OctoberCMS Build: 451
- PHP Version: 7.3.2  

### Description:
I am working on JS plugin that displays some data and updates it using ajax. So basically I have a couple elements ( forms, buttons..) that trigger those ajax request. What I am trying to achieve is intercept the posted data and save it in memory for some other usage.

Looking at the [docs](https://octobercms.com/docs/ajax/javascript-api) there are 2 useful events the `ajaxDone` and `ajaxSuccess` that I can hook into and get the post data from the `context` object but this isn't working with elements of a type `form`. The `context.options.data` is always empty on the other hand if the triggering element is a button I can successfully get the posted data. The data is always correctly submitted and processed server side so I am wondering why this isn't working with ajax Forms? Is this a bug?

### Steps To Reproduce:
	
	<a href="javascript:void(0)" data-request-data="'_filters[sort]':'name asc'" data-request="{{__SELF__~'::onFilter'}}">Sort ASC</a>

No problem here : `context.options.data` = `_filters[sort]: "name asc"`

	
	{{ form_ajax( __SELF__~'::onFilter')}}
	    <input name="_filters[name]" type="text">
	    <button type="submit">Filter</button>
	{{ form_close() }}

`context.options.data` always empty

What I tried is : 

	$elements.on("ajaxDone", function(event,context,data,textStatus,jqXHR) {
	    console.log(context.options.data );
	});

	$elements.on("ajaxSuccess", function(event,context,data,textStatus,jqXHR) {
	    console.log(context.options.data );
	});
 

Form data always submitted :

![fil1](https://user-images.githubusercontent.com/4506434/56084842-0e54e880-5dff-11e9-9cf0-f9918633ea70.png)

Context always empty :

![fil2](https://user-images.githubusercontent.com/4506434/56084843-0e54e880-5dff-11e9-828f-1a206e5139d1.png)

**Comment by bennothommo** [comment]
@rajakhoury The docs state that the `data-request-data` property contains "data to be sent to the server *along with the form data*". This means that the form data is separate to this extra data. It might be contained in the `context` somewhere else, but `context.options.data` will *only* contain this extra data.

You can look to using the [FormData API](https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData) to getting the form data in an AJAX callback.
