### ISSUE TITLE
Placeholder Existence Check Does Not Work

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#4261]
- OctoberCMS Build: 451
- PHP Version: 7.1.23

### Description:
The [function](https://octobercms.com/docs/markup/tag-placeholder#checking-placeholder-exits) to check if placeholder exists seems to be broken. It is always false though the placeholder exists.

### Steps To Reproduce:
I have a placeholder called "theme_sidebar". 
If I put in it using ```{% if ... %}``` I get nothing. Though it works without the check.

```
{% if placeholder('theme_sidebar') %}
    {% put theme_sidebar %}
        {% default %}

        HELLO FROM IF
    {% endput %}
{% endif %}

{% put theme_sidebar %}
    {% default %}

    HELLO WITHOUT IF
{% endput %}
```

![image](https://user-images.githubusercontent.com/3897579/56203615-814ba280-603d-11e9-9603-1951f504f413.png)

**Comment by LukeTowers** [comment]
That's because at the moment your check is run, it doesn't exist. Just because you populate it later on doesn't mean that it knows about that before hand.

**Comment by GinoPane** [comment]
@LukeTowers what is the point of the check then? It is useless.

**Comment by LukeTowers** [comment]
@GinoPane it is not useless, you're just using it wrong 😜 

You tell me how it's supposed to know the placeholder content exists when at the time that it executes, that content does not exist. In your example the placeholder content doesn't exist until after that conditional check is run.

**Comment by GinoPane** [comment]
@LukeTowers hm, but how to use it then? :) What I did is almost 100% the same that documentation tells: `check -> put if exists`

**Comment by LukeTowers** [comment]
@GinoPane I think what you're getting confused by is you think that function checks for the existence of the placeholder itself. It doesn't, it checks to see if the placeholder has any content assigned to it yet:
> if a placeholder **content** exists

You shouldn't need to check if the placeholder itself exists, you can add content to a non-existent placeholder without anything breaking

**Comment by GinoPane** [comment]
Ah, ok, thanks. That makes sense but still it is really confusing. Probably it would be useful to update docs.

**Comment by LukeTowers** [comment]
Feel free to submit your suggested improvements as a PR
