### ISSUE TITLE
Active theme config is not cached

### ISSUE THREAD

**Issue by Samuell1** [octobercms/october#4265]
- OctoberCMS Build: 447
- PHP Version: 7.3.3

### Description:
Theme config is not cached and that means its calling Yaml parse on every request, more testing shows that it takes around **20ms** to parse _theme.yaml_.

![obrázok](https://user-images.githubusercontent.com/3110002/56285878-8e898f80-6118-11e9-94e1-891217d8758a.png)

### Steps To Reproduce:
This can be reproduced by using {{ this.theme }} variable in templates.

**Comment by LukeTowers** [comment]
Feel free to submit a PR to improve this.
