### ISSUE TITLE
Enhancement Idea: Adding Priority Hints API to October CMS

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4277]
## Introduction

I am about to start work on adding a new API to my October CMS websites. The API has been in the making for around 2 years now by Google and now can be used in a "production" website environment.

## About the API

When the browser loads assets they are given a Priority for the loading, see below an example:

![1](https://user-images.githubusercontent.com/17784082/56428699-2d98bd80-62b8-11e9-83f6-d9626e438930.png)

A developer can add an attribute to fine tune the loading of these assets to enhance the performance of the loading of the web page.

The API is made up of the following attributes:

The importance attribute accepts one of three values:

- **high**: The resource may be prioritized, if the browser's own heuristics don't prevent that from happening.
- **low**: The resource may be _de_prioritized, if the browser's heuristics permit.
- **auto**: Let the browser decide what priority is appropriate for a resource. This is the default value.

## Why I am filing an Issue here

The following places I have assets in October CMS are in three main locations:

1. Inside the `<head>` section.
2. Near the bottom of the web page code after the `<footer>` section.
3. Adding the October CMS AJAX code snippet (again at the bottom).

This gives us the following code example:

```html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Example</title>

<!-- Position 1 -->
<script src="example-1.js"></script>
</head>
<body>

<!-- Position 2 -->
<script async src="example-2.js"></script>

<!-- Position 3 -->
{% framework extras %}
{% scripts %}  
</body>
</html>
```

For Positions 1 and 2 this is down to the developer and will be different on every website and that side of things is not part of this issue.

For Position 3 (the October CMS AJAX), this is the thing I want to discuss in this issue.

## Adding the new attributes to the October CMS AJAX by default

I want to add the new attributes to the October CMS AJAX by default.

An example of the new API would look like this:

```html
<script src="/js/app.js" defer importance="high"></script>
```

Please see the new attribute called `importance` which is set to `high`.

## Discussion

I would like to know first, what would be the best setting to give the October CMS AJAX, `low`, `high` or `auto` ?

## Creating a PR

When the discussion is over, I would like to inject this new attribute into the code snippet:

```html
{% framework extras %}
{% scripts %}  
```

Then October CMS will automatically add the new attributes into the code and the develop[er won't need to do anything!

## Another Github Issue (Ongoing)

I would also like to add the preload attribute to the October CMS Ajax as well, I have opened a Github Issue already which can be found here: https://github.com/octobercms/october/issues/4030

## Example of output

Something like this:

```html
<script async src="/modules/system/assets/js/framework.combined-min.js" importance="low"></script>
<link rel="preload" href="/modules/system/assets/js/framework.combined-min.js" as="script" importance="low">

<link rel="stylesheet" property="stylesheet" href="/modules/system/assets/css/framework.extras-min.css" importance="low">
<link rel="preload" href="/modules/system/assets/css/framework.extras-min.css" as="style" importance="low">
```

**Note**: I added `async` to the script and a `low importance` because I feel the important assets should be loaded before these files and won't affect the rendering of the web page.

I am thinking something like this maybe?

So adding three things:

1. async
2. preload
3. priority hints

**Comment by ayumihamsaki** [comment]
Look forward to feedback and ideas...

**Comment by ayumihamsaki** [comment]
The above comment talks about the front-end only. The back-end could also be updated with this API.

Look forward to feedback and ideas...

**Comment by ayumihamsaki** [comment]
Need to wait for this pr https://github.com/octobercms/october/pull/4272 to be added to the next version before can start coding a pr for this issue.

**Comment by ayumihamsaki** [comment]
(Don't close PR's open on this one)

**Comment by LukeTowers** [comment]
@ayumihamasaki2019
