### ISSUE TITLE
backend link broken

### ISSUE THREAD

**Issue by sebalaini** [octobercms/october#4286]
- OctoberCMS Build: 447
- PHP Version: 7.3.4
- Database Engine: pgsql

### Description:
when I type `localhost/october/backend` in my MacOS X I'm redirected to `http://localhost/october/backend/backend/auth` it doesn't add `signin` to the end of the URL, I add `signing`, I hit enter to load and nothing still same error, I refresh and it works

`This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE`

I'm using Apache on MacOS X 10.14.4 with PHP 7.3.4, I'm using these steps to set up my MAC 

https://github.com/sebalaini/mac_os_web_server

**Comment by Samuell1** [comment]
https://www.drivereasy.com/knowledge/fix-err-empty-response-on-google-chrome/

**Comment by LukeTowers** [comment]
@sebalaini you can also try using the built-in webserver by running `php artisan serve` on the command line in your project root.
