### ISSUE TITLE
OctoberCMS DynamicPDF plugin page wise dynamic header content

### ISSUE THREAD

**Issue by mittultechnobrave** [octobercms/october#4288]
I am using OctoberCMS [DynamicPDF][1] Plugin and its working as per my expectations. 

However, I have a PDF brochure in which I want to generate my header text dynamically based on each page I generate. Here is my sample of PDF Brochure. 

[![enter image description here][2]][2]

[![enter image description here][3]][3]

As you can clearly see my dynamic header text **CAPABILITIES** and **OUR TEAM** and I want to somehow pass in my **Layout** dynamically. 

I am trying to pass using below code from my **template** file to my **layout** file something like this. 

**Template File**

    {% set dynami = 'CAPABILITIES' %}
    {% put dynamicHeader %}
    {{ dynami }}
    {% endput %}
    
    
    
    
    <body style="background-color: #fff;">
       <div id="content">
       Capabilities content
       </div>
    </body>
    
    
    
    
    
    
    
    
    {% set dynami = 'OUR TEAM' %}
    {% put dynamicHeader %}
    {{ dynami }}
    {% endput %}
    <body style="background-color: #fff;">
       <div id="content">
        Our Team Content 
       </div>
    </body>
    
    
    

**Layout File**

    <html>
        <head>
            <style type="text/css" media="screen">
                {{ css|raw }}
            </style>
            <title>Regency Brochure</title>
        </head>
        
       <div id="header">   
          <div style="text-align: right; font-size: 20px; color: #b49132; text-transform: uppercase; font-family: 'Montserrat-Bold'; position: absolute; right: 3.5%; top: 25px;">
            {% placeholder dynamicHeader %}
            </div> 
        </div> 
        <div id="footer">    
        </div>      
            {{ content_html|raw }}    
    </html>

As you can see, I am using `{% placeholder dynamicHeader %}` to get my dynamic header which I am sending dynamically from my **Template File** using below code. 

    {% set dynami = 'CAPABILITIES' %}
    {% put dynamicHeader %}
    {{ dynami }}
    {% endput %}

But the thing is, its always overriding the last value which I am sending. In this case, its using `OUR TEAM` for all the pages. 

I have read through [Plugin's Documentation][1] Tab. And they are saying...

>Plugin supports using CMS partials and filters inside template and layout markup. 

But I am getting no idea so far how to utilize **CMS Partials** here inside my layout as per my scenario because I cant check my page number and put number static because my content is dynamic so I cant put page number condition anywhere.

Only thing I can do is to somehow pass it. 

Can someone guide me to implement this please. 

  [1]: https://octobercms.com/plugin/renatio-dynamicpdf
  [2]: https://i.stack.imgur.com/hPaJ4.png
  [3]: https://i.stack.imgur.com/1KORM.png

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

**Comment by LukeTowers** [comment]
@mittultechnobrave how do you expect two body tags to exist in the same document??? Are you trying to have both pages display in the same PDF file?

**Comment by mittultechnobrave** [comment]
Yes .. in same PDF file .. Two body tags or multiple body tags I have based on my structure .. it will generate a new page in the same PDF.

**Comment by LukeTowers** [comment]
Two body tags is not valid HTML. Put them both in divs, then put your header into a partial and pass the text content as a partial property and render the partial twice, once for each page with the appropriate text property value passed.

**Comment by mittultechnobrave** [comment]
OK this is I have done .. I have set multiple `body' tags inside my respected `div` in my template file. 
[
{% set dynami = 'CAPABILITIES' %}
{% put dynamicHeader %}
{{ dynami }}
{% endput %}




<div>
<body style="background-color: #fff;">
   <div id="content">
   Capabilities content
   </div>
</body>
</div>








{% set dynami = 'OUR TEAM' %}
{% put dynamicHeader %}
{{ dynami }}
{% endput %}
<div>
<body style="background-color: #fff;">
   <div id="content">
    Our Team Content 
   </div>
</body>
</div>


](url)

**Comment by mittultechnobrave** [comment]
Do I need to add my `partial` inside my `layout` file or `template` file ?

**Comment by Samuell1** [comment]
If you want header on every page use `position: fixed;` on it.

**Comment by mittultechnobrave** [comment]
I do that but I have dynamic content for each page .. Hence In next page I am able to see both the content in header.

**Comment by Samuell1** [comment]
I think you can use partials from your CMS theme. @mittultechnobrave

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
