### ISSUE TITLE
OC updates

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#4289]
- OctoberCMS Build: 443

- PHP Version: 7.1.x
- Database Engine: Mysql 5.5

### Description:

hit the system updates button to upgrade OC version from 443 to 447.
It didnt go through due to a permission file denied error.
And now, I cant connect to the backend anymore because of this error:

```
Call to undefined method October\Rain\Router\Helper::replaceParameters()
in /var/www/html/scheduler/modules/backend/widgets/Lists.php line 667
```

### Steps To Reproduce:
upgrade from 443 to latest version

**Comment by w20k** [comment]
Use composer to upgrade - should solve your issue.

**Comment by chrisvidal** [comment]
I tried the command

```
php artisan october:update
```

but still the same error.

I dont have a composer.json at the root of the installation

**Comment by w20k** [comment]
Copy composer.json from the GitHub and run `php composer update`.

**Comment by chrisvidal** [comment]
I got this error

```
mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 594550784) (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php on line 126
```

**Comment by w20k** [comment]
@chrisvidal allocate more memory? :)

**Comment by chrisvidal** [comment]
I am on DigitalOcean.
I had to create a swap file memory, and install missing php-ext
it seems to be working now
thanks
