### ISSUE TITLE
Artisan::call() doesn't work

### ISSUE THREAD

**Issue by adisos** [octobercms/october#429]
It seems to me there is a bug with Artisan::call(). I don't know is it related to laravel or october.

![image](https://cloud.githubusercontent.com/assets/592907/3570867/675a74a0-0b56-11e4-8d69-92652292cb03.png)

I have solved this problem by removing these lines from services.json:
```
"cache": "Illuminate\\Cache\\CacheServiceProvider",
"cache.store": "Illuminate\\Cache\\CacheServiceProvider",
"memcached.connector": "Illuminate\\Cache\\CacheServiceProvider",
```

**Comment by daftspunk** [comment]
This is fixed in the RC build. Using Laravel 5.
