### ISSUE TITLE
Cannot upload image with rich editor

### ISSUE THREAD

**Issue by huynhnamegal** [octobercms/october#4294]
- OctoberCMS Build: v452

I have uploaded images to blog with rich editor, but it did not work. But I can select any image in media strorage.

I tried to upload image in my PC. 
![image](https://user-images.githubusercontent.com/20609668/56705682-2819f800-673c-11e9-8017-61b3d2fdf940.png)

Sometimes, it's 'uploading...'
![image](https://user-images.githubusercontent.com/20609668/56705723-5ef00e00-673c-11e9-9065-9d10dc9d2b48.png)

**Comment by Samuell1** [comment]
This looks like upload size limit issue.

**Comment by huynhnamegal** [comment]
Nope, I just upload a image with 8KB. And my server did not log this wrong

**Comment by cheb60** [comment]
Duplicate of #4264
