### ISSUE TITLE
Themes page shows non-relevant data sometimes

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#4295]
- OctoberCMS Build: 452 
- PHP Version: 7.1

Running under Docker on MacOS.

### Description:
The latest release has this update:

> Cached the parsed theme configuration to improve performance on subsequent page loads

via https://github.com/octobercms/october/pull/4270

And it seems to me that it causes this:

![image](https://user-images.githubusercontent.com/3897579/56803231-0727d480-681a-11e9-963b-b7691f82c56d.png)

Different themes installed, but all listed under the same name, description, etc.

### Steps To Reproduce:

Run october using Docker on MacOS, containers should be running for a day at least without restart. After restart the themes page is fine.

**Comment by Samuell1** [comment]
Its fixed later https://github.com/octobercms/october/commit/0fdd3c32cb5feaf71e8202d9ebf776169e2110b4

**Comment by GinoPane** [comment]
@Samuell1 cool, let's see if it helps

**Comment by LukeTowers** [comment]
@GinoPane can you report back after testing that commit?

**Comment by GinoPane** [comment]
@LukeTowers  will do

**Comment by GinoPane** [comment]
@LukeTowers though I'm not 100% confident with this, but it looks like that the issue was fixed.
