### ISSUE TITLE
Top menu loading issue when doing a refresh in the backend

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4298]
- OctoberCMS Build: 452
- PHP Version: 7.3.4
- Database Engine: Mysql
- Plugins Installed: Many over 100

### Description:

When I do a refesh of the backend I see this screen:

![issue](https://user-images.githubusercontent.com/17784082/56840347-007f7880-687f-11e9-879e-f23a98ea5d0e.png)

The top menu items on the right do not show straight away and the left column is very large. The web page takes around 10 - 13 seconds to load and then the web page displays. It only does this when I try to refresh the screen. If I try to load the web page or the next web page without a refresh it's fine. This maybe why other Users are not reporting this issue?

I have done a full browser and server hard refresh and cleared the cached to see if makes a difference but problem still continues.

If I remember correctly w20k was doing a javascript fix on that side of things. I thought his fix got merged a few months ago, but maybe I am wrong.

Anyway, problem seems to happen when you try to do a refresh. I'm sure some javascript code is wrong somewhere and creating this issue and blocking the re-render of the web page in the backend - that's my theory.

I'm thinking there are two small issues here:

## Sidebar Issue **(Added for ref)**

I think to stop the sidebar from starting an extra large size and then re-sizes down just add the following css code:

```css
.layout-sidenav-container {
    width: 120px;
}
```

into

```css
.layout-sidenav-container {
    width: 120px;
    max-width: 120px;
}
```

Note: The CSS fix PR is found here: https://github.com/octobercms/october/pull/4293

## Top Menu Bar Issue **(I've opened this issue for this part only)**

I think this is an issue in the javascript code and nothing to do with any css or php code. I'm sure w20k did a pr fix on this but I can't find it? Would like to see his code and investigate further. It seems to load the load side and not the right side, do some kind of dom processing and then re-draw the whole top menu to the full width of the screen. I can't see why we can't just remove this and have the top menu bar load the full width of the screen at the start of the web page load and then do the processing to make it scroll.

### Steps To Reproduce:

Do a soft or hard refresh in the backend and you will see slow loading of the web page via `storm.js` and the top menu and sidebar issue when you are in the `cms` menu section (code editor).

**Comment by ayumihamsaki** [comment]
As per comment: https://github.com/octobercms/october/issues/4052#issuecomment-487150143

**Comment by LukeTowers** [comment]
@ayumihamasaki2019
