### ISSUE TITLE
Scrolling lists not possible from list area on mobile

### ISSUE THREAD

**Issue by joseph-d** [octobercms/october#4303]
As per the discussion https://github.com/octobercms/october/commit/ec2a0d5fb04088abb9c488d9593a9394420971b0#r33356776 here are two GIFs that illustrate the issue occurring on mobile Chrome and Firefox. The GIF itself has been made on Desktop Chrome in mobile debug mode but is faithful to what is actually happening on mobile Chrome:

Build 447

**Unable to scroll by touching and dragging in the main list area, but touching and dragging on the blue side menu works**

![Peek 2019-04-30 10-28](https://user-images.githubusercontent.com/1070155/56954355-811bce80-6b36-11e9-9d8c-fd1802cf92b2.gif)

**With `.list-scrollable-container` changed to remove `touch-action:none;` _or_ changed to be `touch-action:auto;` the problem is solved:**

![Peek 2019-04-30 10-30](https://user-images.githubusercontent.com/1070155/56954463-be805c00-6b36-11e9-8c47-7b82ef933e53.gif)

I cannot see any adverse effects on either mobile or desktop when changing `touch-action` to `auto` but if there is anything in-particular I should be looking for then please let me know and I will test it.

**Comment by w20k** [comment]
@joseph-d could you create a PR (compile assets as well), please ;) And will do the merging!

**Comment by joseph-d** [comment]
Sure, I'll give it a go. I've never done a PR for LESS/CSS files before so can you tell me how I should proceed? Can I just edit `less/list.less` and `storm.css` within GitHub and create the PR from that, or do I need to clone the whole repo to my local machine, physically recompile less and then push and submit the PR?

If it's the latter, is there any guidance about the version of LESS and the compile options I have to use?

**Comment by w20k** [comment]
@joseph-d let's do a GitHub approach. Just edit the .less file and make a PR out of it. Storm.css shouldn't be directly changed anyhow.

And if you have free time :)  
1. Clone a dev branch
2 Make your changes for `less/list.less`
3. Run artisan command (`php artisan october:util compile less`) 
4. Push those changes to your forked repo, then create a PR for Dev branch

**Comment by joseph-d** [comment]
@w20k Ok, thank you for your guidance. I did it the hard way as a learning exercise. I think it's correct but please let me know if I did anything wrong. :-)

**Comment by w20k** [comment]
@joseph-d thanks a lot for your contribution! ;) All good!

**Comment by joseph-d** [comment]
Glad to hear it :-) Thank you again for your patience and guidance.
