### ISSUE TITLE
Make theme translations available under the themes.themecode::lang namespace in the backend translation system

### ISSUE THREAD

**Issue by lautsevich** [octobercms/october#4308]
October CMS doesn't support the themes internationalization at the moment. I mean that you can't add more than one (default) language to the theme settings screens. It's an unsolvable issue for the development of the themes for the international market.

We at LOVATA just started to develop themes for our Shopaholic. And we plan to add a huge amount of themes to the marketplace in the near future. And we want to make themes using more easy for the non-English speaking users. Not only we faced this problem, please, look at this [tweet](https://twitter.com/MateThemes/status/1069862295373799424).

**Comment by w20k** [comment]
I don't think theme by itself would ever have more than one default language, but the setting page should be translatable, somehow.

**Comment by lautsevich** [comment]
@w20k, in this issue I've opened the discussion only regarding the theme settings screens in the backend (admin dashboard). It's very strange to set up language settings in the backend to Arabic, for example, and see theme settings screens on English.

**Comment by lautsevich** [comment]
As for theme localization, it's another issue and it can be managed with the current functionality.

**Comment by GinoPane** [comment]
> As for theme localization, it's another issue and it can be managed with the current functionality.

It can, but it is rather painful. 

I think that theme internationalization is doable. To be honest, I was looking for lang files in themes directories before, because I was sure they should be there :)

**Comment by LukeTowers** [comment]
Theme language files exist: https://github.com/rainlab/translate-plugin#message-translation

And you can easily add language files to an accompanying file to have translations for the settings items.

**Comment by lautsevich** [comment]
@bennothommo, @LukeTowers, @w20k, is there any news regarding my request?

**Comment by LukeTowers** [comment]
@lautsevich not sure what you're asking for beyond what I've already said:

> Theme language files exist: https://github.com/rainlab/translate-plugin#message-translation

> And you can easily add language files to an accompanying plugin to have translations for the settings items.

**Comment by lautsevich** [comment]
@LukeTowers, if I understood you right message translation is appropriate for the front-end strings. My request is regarding a translation of the theme settings page in the backend.

**Comment by LukeTowers** [comment]
@lautsevich which would be covered by 

>And you can easily add language files to an accompanying plugin to have translations for the settings items.

**Comment by lautsevich** [comment]
IMO, themes translation way should be identic to the plugins. OK, the Translate plugin provides the requested functionality. But it's just a fallback at the moment.

**Comment by lautsevich** [comment]
@LukeTowers, I mean field labels on theme settings page.

**Comment by LukeTowers** [comment]
Hmm, perhaps we could have the backend translation system load any translations found in `themes/theme/lang/` under the `themes.theme::lang` namespace, or perhaps we could even have it pull from the `translate` config item in the theme.yaml. Thoughts @lautsevich @GinoPane @w20k @bennothommo?

**Comment by lautsevich** [comment]
@LukeTowers, as I said before we at LOVATA think that themes as an independent should have their own translation system similar to plugins.

**Comment by LukeTowers** [comment]
@lautsevich which option are you in favour of then? Using the keys provided for the translate plugin or having an entirely separate language system just for use in the backend?

**Comment by lautsevich** [comment]
@LukeTowers, we need a separate language system for themes for use in the backend (field labels). As for the translate plugin, we use it for the translations in the theme frontend (UI text).

**Comment by lautsevich** [comment]
IMO, it would be better to get an answer to this question from @kharanenka. What do you think, Andrey?

**Comment by lautsevich** [comment]
Reopen it, pls, folks! =)

**Comment by w20k** [comment]
Not closed, yet :) Just marked for `closing`.

**Comment by lautsevich** [comment]
Thx! =)

**Comment by kharanenka** [comment]
> @lautsevich I'm leaning more towards just making the frontend keys available in the backend under the `themes.themecode::lang` namespace, what's your thoughts on that?

I think this is a great idea.

**Comment by lautsevich** [comment]
@kharanenka, great!

@LukeTowers, so, it would be great to see it in some nearest release. We have huge plans on themes development for several markets (EU, Asia) next year. This functionality will be helpful for it!

Thx in advance!

**Comment by LukeTowers** [comment]
@lautsevich if you'd like this issue bumped up in priority, you could sponsor it 😉

**Comment by lautsevich** [comment]
@LukeTowers, got it. We'll think about it! ;)

**Comment by lautsevich** [comment]
Hi @LukeTowers! Just found your [article](https://octobertricks.com/tricks/make-plugin-translation-keys-available-as-theme-messages-for-rainlabtranslate) is that a fallback solution for my request?

**Comment by LukeTowers** [comment]
@lautsevich that article is actually the reverse, since it makes translations provided by plugins meant for the backend available to the frontend & RainLab.Translate.

**Comment by LukeTowers** [comment]
In addition to sponsoring this issue, you could also join the Premium Support program to have this request bumped up in priority: https://octobercms.com/premium-support

**Comment by lautsevich** [comment]
Thx for the clarification!

**Comment by lautsevich** [comment]
Up!

**Comment by LukeTowers** [comment]
@lautsevich reminder you can join the Premium Support program to have this request bumped up in priority: https://octobercms.com/premium-support 😉

**Comment by lautsevich** [comment]
I suppose the Premium Support has a different purpose. As for this issue, we can wait at the moment.

**Comment by GinoPane** [comment]
Hm, just wondering, is this issue also about the case when we have theme settings that cannot be translated?
 
For example, we could have "website_title" setting and currently it can get only one value (e.g. English). And we won't be able to translate it on the frontend (even using "|_", because dynamic labels are not picked up by the translator).

**Comment by bennothommo** [comment]
@GinoPane I believe this issue is just for the lack of translation support for the field labels and settings in the Theme Customisation form.

> For example, we could have "website_title" setting and currently it can get only one value (e.g. English). And we won't be able to translate it on the frontend (even using "|_", because dynamic labels are not picked up by the translator).

I would suggest not using settings for that - you can already use translation strings for that type of customisation.

**Comment by lautsevich** [comment]
@GinoPane, nope. It's for the theme customization UI in the backend.

**Comment by GinoPane** [comment]
@bennothommo thanks for confirmation.

To be honest there are a few design flaws with it:
> I would suggest not using settings for that - you can already use translation strings for that type of customisation.

We don't have a general website settings tab in October. Those settings belong to the theme. And usually such stuff as website name, website author, description etc are put there. And if we are going to use basic translator capabilities via translator key, those settings become useless (because they are not usable for multilingual case).

**Comment by GinoPane** [comment]
Guys, please check out the PR ^^

**Comment by lautsevich** [comment]
Done!

**Comment by GinoPane** [comment]
Hey, it shouldn't be closed! The MR is ready for it 😄 @bennothommo could you please remove the "archived" label?

**Comment by bennothommo** [comment]
Thanks @GinoPane and @w20k. It's just our monthly reminder to revisit this :)

**Comment by lautsevich** [comment]
Good job! Thx 2 all!
