### ISSUE TITLE
Add ID's to the block headers on the plugin/theme/bundle pages in the marketplace

### ISSUE THREAD

**Issue by lautsevich** [octobercms/october#4310]
It will be useful to refer to the required plugins, supported themes, etc. in the product description by adding anchor links to these blocks headers.

![image](https://user-images.githubusercontent.com/196445/57073013-68531a80-6ce8-11e9-8422-f5feda20b475.png)

![image](https://user-images.githubusercontent.com/196445/57073021-71dc8280-6ce8-11e9-9841-bba2a136aaa5.png)

![image](https://user-images.githubusercontent.com/196445/57073062-90427e00-6ce8-11e9-8f6e-af48e6eab56e.png)

![image](https://user-images.githubusercontent.com/196445/57073065-959fc880-6ce8-11e9-861b-bf69136f221a.png)

![image](https://user-images.githubusercontent.com/196445/57073075-9df80380-6ce8-11e9-9cdc-f379c1c24cf4.png)

![image](https://user-images.githubusercontent.com/196445/57073082-a2bcb780-6ce8-11e9-96b2-ea202ec31cba.png)

![image](https://user-images.githubusercontent.com/196445/57073138-d7307380-6ce8-11e9-9c71-7691eea534f8.png)

![image](https://user-images.githubusercontent.com/196445/57073145-dd265480-6ce8-11e9-8093-936e360aac4e.png)

**Comment by lautsevich** [comment]
Is there any update regarding my request?

**Comment by lautsevich** [comment]
It's not important thing, but it would be nice to add it. =)

**Comment by daftspunk** [comment]
Thanks for the suggestion @lautsevich. I have passed on this feedback!
