### ISSUE TITLE
Postgres - Builder exception on auto-increment integer fields

### ISSUE THREAD

**Issue by corepay** [octobercms/october#4312]
- OctoberCMS Build: 447 
- PHP Version: 7.34
- Database Engine:  PostgresSQL 11
- Plugins Installed: Builder

### Description:

![image](https://user-images.githubusercontent.com/48992923/57117777-ad00a500-6d2c-11e9-952a-c960e2631559.png)

CLICK SAVE

![image](https://user-images.githubusercontent.com/48992923/57117834-f224d700-6d2c-11e9-857f-8e6f8a14c57e.png)

### Steps To Reproduce:

Fresh install localhost.  

First Builder Plugin, 

First table

First row add `id` as integer, auto-increment and pk then save.

RELATED:  I did complete reinstall (new composer create - new db table) after building a table structure and getting this error on save.  When receiving an error after building a table (30 minutes) and pressing save, - clicking through the error (OK) the spinner just spins and control is not given back to the page to fix whatever it was complaining about.  Have to reload the page to do anything and of course lose all the work performed...

![image](https://user-images.githubusercontent.com/48992923/57117702-2ea40300-6d2c-11e9-8498-a654279727cd.png)

**Comment by corepay** [comment]
UPDATE:  I tried to workaround by just adding a string field and not selecting auto-increment or pk planning on fixing the migration file by hand to suit my requirements and still get the same error

![image](https://user-images.githubusercontent.com/48992923/57117939-ae7e9d00-6d2d-11e9-8328-3da454f53096.png)

**Comment by bennothommo** [comment]
@corepay This is a known issue. See: https://github.com/rainlab/builder-plugin/issues/212
