### ISSUE TITLE
BOOLEAN requires an integer - does not accept true/false default values

### ISSUE THREAD

**Issue by corepay** [octobercms/october#4313]
- OctoberCMS Build: 447 
- PHP Version: 7.32
- Database Engine: MySQL 5.7
- Plugins Installed: Builder

### Description:

Error when adding default value of false or FALSE as default value

![image](https://user-images.githubusercontent.com/48992923/57118358-b3911b80-6d30-11e9-81a3-4fe883de6854.png)

Boolean fields require an integer when they should accept values as per SQL standard  – TRUE, FALSE, and UNKNOWN.

**Comment by bennothommo** [comment]
@corepay In MySQL, the `boolean` is a synonym for `tinyint(1)`, so the default has to be specified as either `0` or `1` to fit the data type.

**Comment by LukeTowers** [comment]
@BennoThommo I believe laravel handles that when you pass true vs false into the default() method so the builder plugin should probably support that too

**Comment by bennothommo** [comment]
@LukeTowers You're correct, however, currently the Builder plugin adds `true` and `false` as strings if entered in as the default value in the datatable. It would be an improvement if it could handle those values correctly - I'll add it as a "good first issue" for the Builder plugin.

**Comment by bennothommo** [comment]
@corepay If you're interested in allowing true and false as a default value in the database builder of the Builder plugin, please feel free to contribute a PR to the following issue: https://github.com/rainlab/builder-plugin/issues/280

**Comment by corepay** [comment]
Thank you for the attention.  Cant help with a PR however, not a developer...just an architect that knows just enough about coding to be annoying.  

Very much appreciate your hard work though.

**Comment by bennothommo** [comment]
@corepay Not a problem. Thank you for the report! :)
