### ISSUE TITLE
Add Telegram Channels information to the OctoberCMS Support web page

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4315]
Add the following info to the right hand sidebar menu:

- **Telegram**: https://t.me/octobercms_rus - Russian speaking community.

- **Telegram**: https://t.me/octobercms - English and Portuguese speaking community.

At the following web page: https://octobercms.com/support

See screenshot:

![Untitled](https://user-images.githubusercontent.com/17784082/57134314-b0804480-6d9d-11e9-9411-fffc5ff48dda.png)

As per comment: https://github.com/octobercms/october/issues/4297#issuecomment-488798866

**Comment by LukeTowers** [comment]
Not going to be added to the website because none of the core team uses those channels.
