### ISSUE TITLE
Question: Good idea to merge Forms and emails plugins together?

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4318]
This is a question, just been using the plugins section on the website and trying to find a "Newsletter Email Form" plugin.

It's a bit of a pain having two sections:

- Contact Form
- Email

Would it not just better to merge them together under the one heading:

- Email & Forms

It would make it easy to search.

I am talking about the website: 

https://octobercms.com/plugins/contact-form
https://octobercms.com/plugins/email

Pretty much the plugins under each of those headers are under the same category. 

Create this instead:

https://octobercms.com/plugins/email-forms

Just a question and a thought.

**Comment by LukeTowers** [comment]
It's already easy to search, just search using the search bar. Email related plugins are not always related to forms and vice versa.
