### ISSUE TITLE
Email smtp return 503 error that need  RCPT command

### ISSUE THREAD

**Issue by sidealice** [octobercms/october#4319]
- OctoberCMS Build: 4.4.7
- PHP Version: 7.1

if config with qq mail server with smtp return error:
Email smtp return 503 error that need  RCPT command

exmail.qq.com is the biggest email provider in China, suggest to check if we need to fix it.

**Comment by w20k** [comment]
@sidealice either you could provide a PR to implemment/fix this, or help and support someone who is willing to help you out :) Not enough Chinese speakers here)

**Comment by bennothommo** [comment]
I believe SMTP 503 is an authentication error. @sidealice would you be able to double check your mail config and ensure its using the correct username and password?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
