### ISSUE TITLE
Backend Forms Enhancement Idea: Character Counts Feature

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4326]
## Background

I have been adding the following jQuery compatible code to the `textarea` and `text` fields in October's backend, see gif screenshot:

![oct](https://user-images.githubusercontent.com/17784082/57303929-41288e80-70d6-11e9-84e0-5cad99a62f43.gif)

In the above animated gif, the `textarea` has a character limit of 300 characters. 

## Benefits

The reason I add this feature to some of the backend fields makes it easier for Users to fill in the data and know the right amount of characters for the Validation.

## Making this feature become a Core feature

Having previously added a new type of tab feature in October CMS backend I know it's not just a simple straight forward method to add these features and needs some discussion.

I believe that the easiest method would be to allow developers to just add a simple YAML line of code and October CMS do all the rest, for example:

`characterLimit: 285, 300`

The above line of code in the YAML would turn the character limit feature on and set the character limit to a max of 300 characters. The number characters in the textrea between 1 - 285 would be in font color green and number of characters between 286 - 300 would be in color red to signal the user getting close to their limit.

If the developer didn't add this line in their YAML file then October CMS would by default not display the character limit feature.

Taking the above gif, the following YAML code may look something like this:

```
summary:
    label: 'Description / Summary'
    type: textarea
    size: large
    characterLimit: 285, 300
```

 ## Discussion

I open this issue up for discussion and further ideas. I feel this is a useful feature to have in October CMS and I am always coding this feature into many of my custom plugins. It would be nice to have this feature built into the core as a Native feature in the cms.

**Comment by LukeTowers** [comment]
This could be implemented as a plugin

**Comment by ayumihamsaki** [comment]
@LukeTowers Please can you open this issue and tag me and I will re-close this. Github it saying it's still open my side.

**Comment by LukeTowers** [comment]
@ayumihamsaki

**Comment by ayumihamsaki** [comment]
thanks that's fixed it
