### ISSUE TITLE
Taglist form widget does not have preview context

### ISSUE THREAD

**Issue by Rike-cz** [octobercms/october#4330]
- OctoberCMS Build: 454
- PHP Version: 7.2

### Description:
Taglist form widget behavior is the same in create/update context and in preview context. Select box can be dropdowned and new item selected in preview context.
![tablist](https://user-images.githubusercontent.com/4247582/57570569-b3b1ab00-7403-11e9-8b7b-c46853f20be4.png)

### Expected behavior:
No dropdown, only list of saved tags are expected.

**Comment by LukeTowers** [comment]
Feel free to make a PR to add support for this (would include readOnly & disabled support too)

**Comment by bennothommo** [comment]
Fixed in build 447 (https://github.com/octobercms/october/commit/acf45772551150402139f7cb9bfcd740fc0da5a1)

**Comment by petehalverson** [comment]
This fails when the field is read only or disabled and value is an array (e.g. belongsToMany relationship).
