### ISSUE TITLE
Date plicker pl language version

### ISSUE THREAD

**Issue by mkinternet** [octobercms/october#4338]
- OctoberCMS Build: ### 7590dfd30fb08242c6c8e111115659d38ac4aeb8
- PHP Version: 7.2
- Database Engine: 10.1.37-MariaDB

### Description:
Date picker doesnt work under pl version language. Tested succesfull under english version, us version, spanish version

### Steps To Reproduce:
Add date picker to backend form or list filter. Change language version to polish.

**Comment by w20k** [comment]
Works fine for me. Could you provide steps to reproduce @mkinternet ? Or maybe you need to re-compile assets just in case.

**Comment by mkinternet** [comment]
I got error 500 when loaded /modules/system/assets/js/lang/lang.pl.js?v=455
xampp server response was: AH01222: don't know how to spawn child process.

I had to comment "AddHandler cgi-script .cgi .pl .asp" in httpd.conf

Problem solved but. The bug appeared only for this language file. Other language files didnt produce error 500.

**Comment by w20k** [comment]
@mkinternet because Xampp thinks it's a Perl script 😄 Your solution is the only way to handle it.
