### ISSUE TITLE
How to send ajax request to other controller

### ISSUE THREAD

**Issue by PrestaSafe** [octobercms/october#4339]
Hi everyone, i want to do a simple things:
I want to use the create form of one of my controller in popup, and use it, in an other controller. 

Exemple, in my plugin i've a Customers controller, and an Invoices controller,  i list my items, create and update them. 
But, i want to create a customer from the Invoice view if the user doesn't exist, i want to call the form of Customer create form in a popup

My form in well displayed but, when i submit the form, it's create me a empty Customer.

There is my codes:
so, in my Invoices controller i've put this code: 
```
public function OnLoadContent()
    {
        $config = $this->makeConfig('$/prestasafe/erp/models/customer/fields.yaml');
        
        $config->model = new Customer;
        $config->recordUrl = 'prestasafe/erp/customers/create/';
        
        $widget = $this->makeWidget('Backend\Widgets\Form', $config);
        
        $widget->bindToController();
        $this->vars['widget'] = $widget;
        return $this->makePartial('$/prestasafe/erp/models/customer/_add_customer_form.htm');
    } 
```
I call the popup with this button: 
```
<a data-control="popup" data-handler="onLoadContent" href="javascript:;" class="btn btn-primary btn-lg"> Add user </a>
```
It works fine. 
<img width="1075" alt="Capture d’écran 2019-05-16 à 21 27 08" src="https://user-images.githubusercontent.com/4788787/57881422-8a3cb900-7821-11e9-9d33-1fe3c9dded8b.png">
There is my popup view: 
```
<?= Form::open(); ?>
    <?= $widget->render() ?>
    <!-- <button type="submit" class="btn btn-primary">
        Add user
    </button> -->
    <button data-request="onAddUser" class="btn btn-primary">
        Add user
    </button>
<?= Form::close() ?>
```
<img width="869" alt="Capture d’écran 2019-05-16 à 21 27 15" src="https://user-images.githubusercontent.com/4788787/57881436-96c11180-7821-11e9-8408-4e52e3d5807e.png">

But now, i want to call the create action of the CustomersController,
so i've tried this: 
```
public function onAddUser()
{
         $ct = new CtrlCustomer;
         $ct->asExtension('FormController')->create_onSave('create');
}
```
It seems to work, but it create an empty Customer. 
<img width="1316" alt="Capture d’écran 2019-05-16 à 21 31 22" src="https://user-images.githubusercontent.com/4788787/57881594-ff0ff300-7821-11e9-8d5b-5808e027c240.png">

So i try this: 
```
public function onAddUser()
    {
        $data = collect(post());
        
        $data->forget('_session_key');
        $data->forget('_token');
        \trace_log($data->toArray());
        $c = Customer::create($data->toArray());
        \trace_log($c);
        \Flash::success('Success!!!');
    } 
```
Sorry for my really bad english.
Same probleme. Someone have an idea ?

Thanks

**Comment by bennothommo** [comment]
@PrestaSafe You should look into using the RelationController behavior, as that provides pretty much the exact functionality you are looking to do here.

The docs for implementing this in your plugin are here: https://octobercms.com/docs/backend/relations
