### ISSUE TITLE
get_class() expects parameter 1 to be object, null given

### ISSUE THREAD

**Issue by Samuell1** [octobercms/october#4342]
- OctoberCMS Build: 455
- PHP Version: 7.3

### Description:
Error getting after clicking on editing hasMany relation manager in backend edit page

```
"get_class() expects parameter 1 to be object, null given" on line 907 of ...modules\backend\behaviors\RelationController.php
```

Trying to log issue it looks like relation edit form is initialized 3x
```
[2019-05-22 07:58:29] dev.INFO: hit ["3"]
[2019-05-22 07:58:29] dev.INFO: hit ["3"]
[2019-05-22 07:58:29] dev.ERROR: ErrorException: get_class() expects parameter 1 to be object, null given in...
```
(number 3 is ID of model that i want to edit)

**Removing belongsToMany relations from fields issue dissapears.**

### Steps To Reproduce:
Creating hasMany relation on model and then using relation manager after clicking to edit returns this error message.

**Comment by w20k** [comment]
Related: https://github.com/octobercms/library/pull/376

**Comment by Samuell1** [comment]
@w20k tested that nothing changes.

**Comment by Teranode** [comment]
PHP 7.3:
```
Disallow passing NULL to get_class():

Previously, passing NULL to the get_class() function would output the name of the enclosing class. This behaviour has now been removed, where an E_WARNING will be output instead. To achieve the same behaviour as before, the argument should simply be omitted.
```

**Comment by LukeTowers** [comment]
@Teranode could you propose a PR to https://github.com/octobercms/october/blob/master/modules/backend/behaviors/RelationController.php#L907 to fix this issue? I'm not even sure how the original code was supposed to work tbh...

**Comment by Teranode** [comment]
Not sure how i would do this. On one occasion you could do:
```
(new \ReflectionClass($config->model))->getName();
```
Can I get someone to test? @Samuell1 @w20k | Don't have a local setup of October atm.

**Comment by LukeTowers** [comment]
@Teranode actually we could probably do something like
```
$model = $config->model->find($id);
if ($model) {
    $config->model = $model;
} else {
    throw new \Exception(get_class($config->model);
}
```

**Comment by Teranode** [comment]
> @Teranode actually we could probably do something like
> 
> ```
> $model = $config->model->find($id);
> if ($model) {
>     $config->model = $model;
> } else {
>     throw new \Exception(get_class($config->model);
> }
> ```

Hmmm, that feels off somehow.

**Comment by LukeTowers** [comment]
well the problem is that `$config->model` is being overwritten by `$config->model->find()` without verifying that the value is an object first (which leads to a non-object being passed to get_class), so it seems right to me.

**Comment by Samuell1** [comment]
But still issue is that why it runs 3x

**Comment by LukeTowers** [comment]
@Samuell1 that's a separate issue
