### ISSUE TITLE
When Model after Save, The Relation can not update

### ISSUE THREAD

**Issue by lnmput** [octobercms/october#4343]
- OctoberCMS Build:  454
- PHP Version: 7.2
- Database Engine:  mysql 5.7
- Plugins Installed: rainlab.user

### Description:
In my order nodel
` public $belongsTo = [
        'status' => ['Jshop\Order\Models\Status', 'key' => 'status_id']
    ];`
When I update `status_id` from `1` to `2` from  backend form, I try get `$this->status` in `afterSave()`  method， But the print data is before value, not change.

**Comment by LukeTowers** [comment]
@lnmput what about the value of `$this->status_id`?

**Comment by lnmput** [comment]
`$this->status_id` value is update, But `$this->status` in not

**Comment by LukeTowers** [comment]
@lnmput call `$this->load('status');` first to force the relationship to reload: https://stackoverflow.com/a/23364277/6652884

**Comment by lnmput** [comment]
Isn't this a new bug?  OctoberCMS Build: 419 is ok， but 454 is error。

**Comment by LukeTowers** [comment]
Possibly, please provide detailed replication instructions using the [test plugin](https://github.com/octoberrain/oc-test-plugin) and a description of the behaviour in 419 vs 455 and we can look into it further.
