### ISSUE TITLE
Revamp Plugin Management UX

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4345]
## Intro

This issue is several issues merged together, which relate to updating the design of the plugin section in the backend.

## Update 1 - Two web pages into a single page

This is from issue: https://github.com/octobercms/october/issues/3497

Currently, the plugin section is a little bit confusing on two web pages and can be merged into a single web page.

As Teranode said:

> How about removing the description and authors, adding the toggle buttons, and add a third button that opens up more information about the plugin that contains the description and author and website, etc

## Update 2 - Have one Single Column to turn Plugins on/off and update

This is from issue: https://github.com/octobercms/october/issues/3955

The following setup:

```
Updates Enabled: Turned ON
Plugin Enabled: Turned OFF
```

Paid plugins do not update.

As bennothommo suggested:

> I'm wondering if this is such a bad thing, preventing updates to disabled plugins. A plugin that is disabled should effectively be non-functioning and have no effect to the site - including migrations added as part of an update. Disabling updates should only be allowed for an enabled plugin, to allow a site administrator to "freeze" on a certain version. 

## Update 3 - Make columns sortable

This is from issue: https://github.com/octobercms/october/issues/4196

As I said:

> For example it would make life easier if we could have the **list of plugins in alphabetical order** - thus finding the plugins easier!

## Summary of ideas so far

Below is a rough idea of a screenshot with regards to the above feature ideas:

![desktop-screen](https://user-images.githubusercontent.com/17784082/58343525-26cb1080-7e4b-11e9-916e-4caf6790b911.png)

## Feedback

Please feel free to add input and ideas.

**Comment by LukeTowers** [comment]
Why did you merge them into one issue instead of keeping them separate?

**Comment by ayumihamsaki** [comment]
I realized they are all talking about the same thing and can be grouped under the header "Revamp Plugin Management UX"

**Comment by bennothommo** [comment]
@ayumihamsaki I had a thought that maybe the plugin list could be displayed as a grid, with small "cards" representing each plugin. Whilst it would be introducing a new UI format to October (albeit one that is kinda already implemented with the Dashboard), the big benefit is that it could be responsive - it could perhaps display 4 columns on desktop, and scale down to 2 columns and 1 column as the viewport shrinks. Thoughts on that?

**Comment by ayumihamsaki** [comment]
@bennothommo  I actually have that coded in several of my custom plugins. In each of my cards I use a title at the top in the middle I have an svg image and at the bottom a short description - probably less than 100 characters. It's all responsive using flexbox. It makes October more modern. The down side is when you have a large list of objects you use a large amount of screen space so makes searching a little bit harder. But overall I like it. Though I am sure many other people would prefer a list. It might be best to have an option to switch between the two.

**Comment by ayumihamsaki** [comment]
@bennothommo  I actually have that coded in several of my custom plugins. In each of my cards I use a title at the top in the middle I have an svg image and at the bottom a short description - probably less than 100 characters. It's all responsive using flexbox. It makes October more modern. The down side is when you have a large list of objects you use a large amount of screen space so makes searching a little bit harder. But overall I like it. Though I am sure many other people would prefer a list. It might be best to have an option to switch between the two.

Here's an example what I have running in one of my plugins (to give you an idea):

![carsd](https://user-images.githubusercontent.com/17784082/58371022-576f8080-7f05-11e9-80ef-62740127620a.png)

Above shows two cards from a long list.

**Comment by ayumihamsaki** [comment]
@bennothommo  I actually have that coded in several of my custom plugins. In each of my cards I use a svg image at the top in the middle I have a title and at the bottom a short description - probably less than 100 characters. It's all responsive using flexbox. It makes October more modern. The down side is when you have a large list of objects you use a large amount of screen space so makes searching a little bit harder. But overall I like it. Though I am sure many other people would prefer a list. It might be best to have an option to switch between the two.

Here's an example what I have running in one of my plugins (to give you an idea):

![carsd](https://user-images.githubusercontent.com/17784082/58371022-576f8080-7f05-11e9-80ef-62740127620a.png)

Above shows two cards from a long list.

Maybe adjust the cards to have the following info:

- SVG Image Icon of Plugin
- Title of Plugin
- Version Number of Plugin
- Short Description (100 Character Limit) of Plugin
- Website URL to Marketplace of Plugin

**Comment by ayumihamsaki** [comment]
Cool idea, reminds me of this plugin: https://octobercms.com/plugin/sewa-tileable

**Comment by LukeTowers** [comment]
@bennothommo are you envisioning an official UI widget interface "TileList" similar to the plugin (except a lot more polished and incorporated in the core?)

**Comment by bennothommo** [comment]
@LukeTowers Yeah, I think that would be a useful widget to make available :)

**Comment by LukeTowers** [comment]
Go for it, that would be pretty neat!

**Comment by bennothommo** [comment]
I have started a pre-merge discussion for the Grid widget here: #4350. Please feel free to add any ideas or discussion in there. :)

**Comment by ayumihamsaki** [comment]
@bennothommo Good luck building it. I just want to ask and say, I would expect 50% of people to be happy with a grid and 50% want a list. If there could be an option to choose between the two that would be great. 

(Having over 100 plugins a list is easy to search through than a grid).

**Comment by LukeTowers** [comment]
@ayumihamsaki could you add those comments to the issue @bennothommo created

**Comment by ayumihamsaki** [comment]
Will, do just updating another pr for october right now...

**Comment by ayumihamsaki** [comment]
done

**Comment by LukeTowers** [comment]
@ayumihamasaki2019
