### ISSUE TITLE
getThumb needs $options array since build 447

### ISSUE THREAD

**Issue by RedMarlin** [octobercms/october#4351]
- OctoberCMS Build: 447 or newer
- PHP Version: 7

### Description:
when using getThumb method for private images, you need to provide $options array with 'mode' and 'extension' keys. Previously you could just provide thumb size and default options were applied.

### Solution:
In theory providing default options for getThumb like it is done in October\Rain\Database\Attach\File should do the trick, but I didnt have time to test it.

in modules/system/models/file.php we should change the getThumb method to:
```php
    public function getThumb($width, $height, $options = [])
    {
        $url = '';
        if (!$this->isPublic() && class_exists(Files::class)) {
           // THE ONLY CHANGE NEEDED 
          // Provide default options settings if necessary
             $options = $this->getDefaultThumbOptions($options);

            // Ensure that the thumb exists first
            parent::getThumb($width, $height, $options);

            // Return the Files controller handler for the URL
           $url = Files::getThumbUrl($this, $width, $height, $options);
        } else {
            $url = parent::getThumb($width, $height, $options);
        }   
```

**Comment by LukeTowers** [comment]
@w20k could you test the provided fix and make a PR?

**Comment by w20k** [comment]
@LukeTowers will do!
