### ISSUE TITLE
Link the Github Issues to the Release Update Notes to learn more info

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4361]
Hi,

## The issue

I just updated the cms to the latest version V456 and in the description it says '**Added support for database-driven theme templates.** ' I was interested and wanted to find out more about this new feature. So I clicked the '**View Changelog**' button and then clicked on the '**View details**' link which goes to this web page: https://github.com/octoberrain/meta/blob/master/release-notes/build-456.md

This web page gives me a brief list of things that have been added to the cms version.

However, here's my issue now.

It still doesn't answer my simple question which is: Where can I find some info about the new feature  '**Added support for database-driven theme templates.** '?

Let me show two examples of Update Logs in Github:

## October CMS

![1](https://user-images.githubusercontent.com/17784082/58753701-7f3d8600-84bb-11e9-9d92-079f0377543a.png)

Above we can see single sentences about each feature, no links to view more info.

## A different repo

![2](https://user-images.githubusercontent.com/17784082/58753714-adbb6100-84bb-11e9-9217-70e137c2aa1a.png)

Above we can see a repo by Google, here we again see single sentences about each feature, but more importantly **_the Github Issue is linked to each issue_**.

This is important as then I can click on each Github Issue and see the code and comments about each feature.

Here, we are not giving this info to the October users and it's harder to learn the new features because of that.

---

I hope I make sense in what I'm saying...

**Comment by LukeTowers** [comment]
It would be a nice feature to have, but it's a lot of work to keep up with, unless you know of some automated tool that would make it easier.

**Comment by Samuell1** [comment]
@LukeTowers You can make it automated with: https://www.conventionalcommits.org/en/v1.0.0-beta.4/ But with this commits names needs to be changed.

**Comment by ayumihamsaki** [comment]
I would think Samuell1 suggestion is a good idea, all I could suggest is this tool: https://octobox.io/

**Comment by ayumihamsaki** [comment]
I would think Samuell1 suggestion is probably the way too go.

I would also suggest this tool as well, to manage the repo and make things easier: https://octobox.io/

**Comment by ayumihamsaki** [comment]
There's also this: https://github.com/NYTimes/Chronicler

**Comment by ayumihamsaki** [comment]
Try this: https://github.com/NYTimes/Chronicler

Also you could setup an automated way to send out the new release updates to Social Media platforms like Twitter and Facebook, plus also updating a blog web page in the ocobercms.com main website using this tool: https://ifttt.com/

Then we don't need to ask you questions about these features and reduce the amount of question issues (saving you guys time to answer people's questions).

Sending out notifications automated would:

1. Keep people in the loop about October Release Updates.
2. Just click on the github issues to learn more about the new features.
3. Keep the Social accounts updated with new content.

**Comment by SebastiaanKloos** [comment]
Maybe someone could create a oc plugin to do this😂

**Comment by ayumihamsaki** [comment]
No comment 😂

![Untitled](https://user-images.githubusercontent.com/17784082/58766117-dd797000-8572-11e9-9fd3-af2047aaf92f.png)

**Comment by LukeTowers** [comment]
@ayumihamasaki2019
