### ISSUE TITLE
Random SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected

### ISSUE THREAD

**Issue by Jc-30** [octobercms/october#4365]
My octobercms is installed in windows version, Apache/2.4.39 (Win64), PHP/7.1.29. 
Getting SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error.
I have tried method below, 
1. change .env from localhost to 127.0.0.1
2. php artisan cache:clear
3. php artisan config:cache
NONE of it works.
This issue seems just happen in Windows because Linux is working fine.

**Comment by bennothommo** [comment]
@Jc-30 I presume you have filled in the `[connections.mysql.database](https://github.com/octobercms/october/blob/7590dfd30fb08242c6c8e111115659d38ac4aeb8/config/database.php#L59)` config value as well. Are you using MySQL on Windows?

**Comment by Nai4rus** [comment]
I also had a problem with "No database selected", helped to transfer a dump of the base from linux...

**Comment by bennothommo** [comment]
@Nai4rus Are you using Windows as well? Which database server were you using?

**Comment by Nai4rus** [comment]
@bennothommo I'm on linux, my colleague uses windows. His configuration is:
openserver
mysql 5.7x64
php 7.2x64
apache-php 7.2

**Comment by w20k** [comment]
Want to add up my 50cents. 
Had a problem today with MySQL connection, when I thought it's a good idea to upgrade a driver to the latest (😄). Might be related.

**Comment by Jc-30** [comment]
> @Nai4rus Are you using Windows as well? Which database server were you using?

**Comment by Jc-30** [comment]
> @Nai4rus Are you using Windows as well? Which database server were you using?

Hi bennothommo, thanks for checking. My vendor has installed XAMPP for us. 
After much troubleshooting, it turns out XAMPP wasn't stable and caused this issue.
We have uninstalled XAMPP and reinstall mysql and php separately.
The issue has resolved now.

**Comment by bennothommo** [comment]
@Jc-30 Thanks for letting us know!

**Comment by Samuell1** [comment]
@Jc-30 if you using windows i recommend using https://laragon.org for server
