### ISSUE TITLE
Error while installing via composer

### ISSUE THREAD

**Issue by yaroslawww** [octobercms/october#4366]
- OctoberCMS Build: 1.0
- PHP Version: 7.3

### Description:

> composer create-project october/october .
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 87 installs, 0 updates, 0 removals
  - Installing wikimedia/composer-merge-plugin (dev-master 73e4ed4): Loading from cache
Plugin installation failed, rolling back
  - Removing wikimedia/composer-merge-plugin (dev-master 73e4ed4)                                                                   
  [RuntimeException]                                                           
  Could not delete /home/vagrant/october.home/vendor/wikimedia/composer-merge  
  -plugin   /src/Merge:  
  
```

![Screenshot from 2019-06-04 19-38-42](https://user-images.githubusercontent.com/23663794/58897172-61149780-8700-11e9-9a94-e5011da5679a.png)

**Comment by bennothommo** [comment]
@yaroslawww You may need to reset the permissions of your `vendor` folder, and make sure that all folders and files within are owned by your user.

**Comment by Fenn-CS** [comment]
Runing `chmod 777 -R` did not solve this problem! I don't think it is a permission issue, and someone should try reproducing this issue. This only happens with `composer create-project`

**Comment by bennothommo** [comment]
@Fenn-CS I use `composer create-project` and `composer update` on Octobe several times a week, even just yesterday, and I have seen the `wikimedia/composer-merge-plugin` being installed, so I can vouch that it is working.

**Comment by Fenn-CS** [comment]
Alright! I would take a closer look. I used the alternative installer.

**Comment by tineklancar** [comment]
I have the exact same issue. (Also have PHP 7.3)

![octobercms-install-error](https://user-images.githubusercontent.com/2991202/79698454-4c45e180-8289-11ea-9691-7b941a426765.PNG)

**Comment by LukeTowers** [comment]
@tineklancar that doesn't look like the same problem. Try removing your vendor directory and composer.lock and running composer update

**Comment by tineklancar** [comment]
Thanks for getting back to me unfortunately removing both and rerunning composer update has no effect. I still get the same error message.

**Comment by LukeTowers** [comment]
try composer dump-autoload too

**Comment by tineklancar** [comment]
unfortunately that has no effect either either. I'm left with only wikimedia/composer-merge-plugin in my vendors folder where as the error message says there is no MergePlugin.php file (there are some others). I've tried deleting it, re-running upload and install, clearing composer cache ... nothing seems to work :/

**Comment by LukeTowers** [comment]
You should be able to use composer @tineklancar. 

What are the exact steps you're taking from scratch?

**Comment by bennothommo** [comment]
I wonder if it's something to do with Vagrant - both cases reported in here are using that.

**Comment by tineklancar** [comment]
Hi Luke,Ben,

I've updated both vagrant and Homestead to latest versions (2.2.7 and 9.5.1 respectively) and now the installation works fine. Thanks for the help!

**Comment by timfurry** [comment]
I had the same problem doing "composer install" on a pristine Homestead VM setting up October. I hit this error while running "composer install" from inside the VM. Running it on the local host in the mapped folder root (**not** in the VM) worked fine. There seems to be some sort of permissions problem in the VM as stated above.
