### ISSUE TITLE
how to deploy octobercms projects on subdomain

### ISSUE THREAD

**Issue by mortezaa** [octobercms/october#4367]
I want to upload octobercms project to my subdomain on my site but it gives me 500 or 404 errors

I change .htaccess file multiple times but it didn't work.
for example I add these lines to the .htaccess file according to https://github.com/octobercms/october/issues/1447 but it didn't work.

`
RewriteEngine on 
RewriteCond %{REQUEST_URI} !^cms 
RewriteRule ^(.*)$ cms/$1 [L]
`

how should I to solve this?

**Comment by LukeTowers** [comment]
Check the logs of your server application to figure out what is causing the issues. October supports running on subdomains just fine so it's an error with how you've configured your server most likely.
