### ISSUE TITLE
Halcyon issue on dev branch

### ISSUE THREAD

**Issue by acasar** [octobercms/october#4369]
- OctoberCMS Build: dev-develop
- PHP Version: 7.1
- Database Engine: MySQL
- Plugins Installed: ---

### Description:
After recent updates to Halcyon models, I am getting the following error after running a simple find statement on my custom Halcyon datasource:

![image](https://user-images.githubusercontent.com/6329543/58949080-e09b7880-878b-11e9-977a-e92724fff491.png)

### Steps To Reproduce:
1. Create a new model with a custom datasource:

```php
class MyCustomModel extends October\Rain\Halcyon\Model
{
    protected $datasource = 'customdatasource';

    public static function boot()
    {
        static::getDatasourceResolver()->addDatasource(
            'customdatasource', new FileDatasource(base_path('custom/path'), new Filesystem)
        );
        parent::boot();
    }
}
```

2. Run a simple find statement:

```php
MyCustomModel::find('filename');
```

3. An error is thrown

cc @LukeTowers

**Comment by acasar** [comment]
When researching the issue I noticed that I can fix the error by updating ``October\Rain\Halcyon\Builder``, making a small modification to ``runSelect`` method where I replaced all ``$this->from`` references to ``$this->from ?: ''`` basically preventing null to be passed as a parameter. This is just a dirty patch but it shows the issue - if we don't set a subfolder, the selects don't work.

```php
    protected function runSelect()
    {
        if ($this->selectSingle) {
            list($name, $extension) = $this->selectSingle;
            return $this->datasource->selectOne($this->from ?: '', $name, $extension);
        }

        return $this->datasource->select($this->from ?: '', [
            'columns' => $this->columns,
            'extensions' => $this->extensions
        ]);
    }
```

**Comment by LukeTowers** [comment]
@acasar I'm not sure not having a `dirName` set is something that's officially supported by October. This could be fixed a couple of different ways, probably the easiest for everyone is if you just set
```php
protected $dirName = '';
```
on your model class to indicate a conscious decision to not use subdirectories. I've "fixed" it in the core by making the error message more clear on what needs to happen to resolve the issue.
