### ISSUE TITLE
Trouble Implementing Character Count Froala Editor

### ISSUE THREAD

**Issue by DanNicolau** [octobercms/october#4370]
Apologies if my question is misplaced or vague; I am new to posting on github and octobercms.

I recently began working on a project where the froala editor in october was extended. I am aware that you can add buttons and this works fine but I am having difficulty implementing a character count.

I included the .js and .css for the character count available from [here](https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.9.5/js/plugins/char_counter.min.js) and [here](https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.9.5/css/plugins/char_counter.min.css) and inserted them into their assets/js and assets/css folders. I have referenced these folders in the Plugin.php file using this statement: 
`$controller->addJs('../assets/js/char_counter.js');`
and the same for the css. I am getting a console error which says TypeError: a.FE is undefined. I have tried playing around with the js after unminifying it and I don't seem to be having any luck. I have also put an
`if (a.FE) { ... }`
around everything which silences the error but doesn't add functionality.

How should I proceed to add a character count to the froala editor?

**Comment by seanthepottingshed** [comment]
@DanNicolau

I can help you when I return to work tomorrow, don’t have access to files at the moment

**Comment by DanNicolau** [comment]
Hi, I found [this](https://github.com/alexey-v-paramonov/froala-word-counter-plugin/blob/master/word_counter.js) implementation of a word counter. I extended the froala defaults to include the js from the link. Thank you for offering your time.

**Comment by rominronin** [comment]
@DanNicolau Can you please outline how you extended the defaults. I'm trying to extend the froala plugin to add a character limit (using the character count plugin), but I get 'Cannot read property DEFAULTS of undefined' errors.

**Comment by LukeTowers** [comment]
@rominronin I've used the following in the past:
```js
+function ($) { "use strict";
    $(document).render(function() {
        if ($.FroalaEditor) {
            $.FroalaEditor.DEFAULTS = $.extend($.FroalaEditor.DEFAULTS, {
                emoticonsUseImage: false
            });
        }        
    })
}(window.jQuery);
```
