### ISSUE TITLE
Main menu counter set to false shows empty red tag

### ISSUE THREAD

**Issue by LarBearrr** [octobercms/october#4371]
- OctoberCMS Build: ### 
- PHP Version: 7.3

### Description:
Per the [documentation for adding a counter to navigation items](https://octobercms.com/docs/plugin/registration#navigation-menus), setting the main menu item counter attribute to false shows a empty red box on the main menu item:

![image](https://user-images.githubusercontent.com/28734844/58971088-4e41a780-8780-11e9-9b68-5ce75142d1f0.png)

### Steps To Reproduce:

1. Register a main menu item

2. Set the counter property to false
3. Register a sub menu item
4. Assign an arbitrary counter value
5. Notice the empty badge at the main menu level

```
public function registerNavigation()
    {
        return [
            'adaptorguide' => [
                'label'       => 'Adaptor Guide',
                'url'         => Backend::url(''),
                'icon'        => 'icon-wrench',
                'permissions' => ['*'],
                'order'       => 500,
                'counter'     => false,
                'counterLabel'=> '',
                'sideMenu' => [
                    'fuel' => [
                        'label'       => 'Fuel Systems',
                        'icon'        => 'icon-rocket',
                        'url'         => Backend::url(''),
                        'permissions' => [
                            'bgprod.adaptorguide.access_fuel_systems'
                        ],
                        'counter'      => FuelSystem::where('is_approved', 0)->count(),
                        'counterLabel' => 'Pending',
                ]
            ]
        ];
```

**Comment by LukeTowers** [comment]
@LarBearrr can you test changing https://github.com/octobercms/october/blob/master/modules/backend/layouts/_mainmenu.htm#L37 to `<?= !$item->counter ? 'empty' : null ?>"`

**Comment by LarBearrr** [comment]
Bingo! I'll work on the PR. Thanks @LukeTowers
