### ISSUE TITLE
Change of label for the backend

### ISSUE THREAD

**Issue by andreacelery** [octobercms/october#4375]
If you go to change your back-end user settings there is a field Password and Confirm Password. 
![image](https://user-images.githubusercontent.com/48524123/59104099-9f77a580-88fe-11e9-8b15-d8a7af9af11e.png)

This could cause confusion since the user might take it as if he needs to enter is password in order to save his settings when he is really changing his password. So my suggestion is to change this from Password to New password or something of that nature. I have changed it in my local lang files but then when I update October it will go back to its original message.

**Comment by LukeTowers** [comment]
Feel free to make a PR with your suggested changes. Note that the language used would have to be different in the create context vs the update context. Also, you can always use local language overrides in your project and they will persist between October updates: https://octobercms.com/docs/plugin/localization#overriding
