### ISSUE TITLE
Dotfiles are missing after the uploading archive to the marketplace

### ISSUE THREAD

**Issue by lautsevich** [octobercms/october#4382]
We at [Shopaholic](http://shopaholic.one) provide a lot of devtools with our products. In particular, we provide front-end tooling for our [Sneakers](https://octobercms.com/theme/lovata-shopaholic-sneakers) theme. There's a `build` folder with the following content:

```
build/
build/.local.eslintrc
build/.stylelintignore
build/webpack.mix.js
build/.babelrc
build/package.json
build/.stylelintrc.yaml
build/.editorconfig
build/.browserslistrc
build/.eslintrc
build/.stylelintrc
build/.eslintignore

```
The uploading theme archive contains all these files. But the downloaded archive contains only these:

```
build/
build/package.json
build/webpack.mix.js
```

What the reason to repack archives? Is the cutting of hidden files a bug?

**Comment by LukeTowers** [comment]
@lautsevich @daftspunk will be adding support for a `.octoberinclude` file that will follow `.gitignore` syntax, except just for dotfiles inclusion in the marketplace build packages and ignoring everything by default. So, in this case you would add a `.octoberinclude` file to `/build` that would contain the following entries:

```
.local.eslintrc
.stylelintignore
.babelrc
.stylelintrc.yaml
.editorconfig
.browserslistrc
.eslintrc
.stylelintrc
.eslintignore
```

**Comment by kharanenka** [comment]
Hi! We added .octoberinclude file to /build folder. When will edits be added to make it work?

**Comment by lautsevich** [comment]
@LukeTowers, hi! Is there any news regarding implementing the support for `.octoberinclude` file? Our customers are [suffering](https://github.com/octobercms/october/issues/4382).

**Comment by daftspunk** [comment]
Please create a file in the root directory of your plugin or theme called `.octoberinclude` (lower case) with the contents:

```
*
```

This should include all hidden files recursively throughout the next build run.

Don't forget to report back your findings so we can close this ticket.

Thanks!

**Comment by kharanenka** [comment]
I moved .octoberinclude file to theme root folder and set '*' content for it. We still haven't got hidden files in build folder

**Comment by daftspunk** [comment]
Apologies there was a deployment issue, please retry.

**Comment by kharanenka** [comment]
Now everything works! Thanks

**Comment by lautsevich** [comment]
Great! Thx @LukeTowers @daftspunk!
