### ISSUE TITLE
Minify the Framework Assets

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4383]
Minify the Framework Assets. As requested by lots of people over the years. To enhance performance in production environment websites.

## Pros:

- Reduce File size to increase loading speed
- Reduce File size to Save Data (most people are using Mobile Data Plans)

## Minify the following Files

- framework.combined-min.js
- framework.extras-min.css

**Comment by LukeTowers** [comment]
Please only use GitHub Issues for feature requests if you are using it as a pre-Pull Request collaboration tool. If you aren't planning on implementing it yourself, then it would be better suited being asked for on one of these channels:

Forum: http://octobercms.com/forum
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

The support demand for October is increasing, while the available time the founders have to give remains the same. Feature requests are by default the lowest priority for us, as we don't have time to implement everyone's suggestions by ourselves. However there are ways you can help:

- Submit a pull request that introduces this feature and we'll review it. Please note that the amount of effort making the PR (code quality, rationale for inclusion in the project, explanation of changes) is directly proportional to the likelihood that we will review and merge it.
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by ayumihamsaki** [comment]
@LukeTowers Sorry I misunderstood your comment in the other Github Discussion, I thought you meant have a discussion on performance ideas and then the ones that are good ideas, to open them as separate Github issues and then create pull requests on them.

What's the best way forward on moving things from discussion to code?

**Comment by ayumihamsaki** [comment]
Github issue linked to discussion found here: https://github.com/octobercms/october/issues/4379

**Comment by LukeTowers** [comment]
@ayumihamsaki you tend to open a lot of different issues purely for discussion purposes. I would prefer that we keep those sorts of issues to a minimum and instead open PRs for specific change requests to be discussed and keep the discussion issues only for overarching architectural level discussions. Having a bunch of issues open for abstract discussions is less productive (in my opinion) then simply proposing changes for specific issues and discussing those proposed changes and the related problem in the PR itself.

**Comment by ayumihamsaki** [comment]
Ok understand.
