### ISSUE TITLE
Update scssphp

### ISSUE THREAD

**Issue by blakej115** [octobercms/october#4393]
I noticed that the built in scss compiler runs into issues when trying to import Bootstrap, giving the following error: /* expecting color: line: 104 */

Is it possible for the core to update to the latest version of scssphp which has fixed some issues? https://github.com/scssphp/scssphp

Thanks!

**Comment by bennothommo** [comment]
See https://github.com/octobercms/library/pull/409#issuecomment-501151171.

October CMS brings in the scssphp library through the Assetic library. We won't be able to upgrade scssphp until they merge this PR: https://github.com/kriswallsmith/assetic/pull/892

**Comment by LukeTowers** [comment]
Now resolved in the L6 upgrade of October as we bring in Assetic directly.
