### ISSUE TITLE
`fields.yaml` defaultTab declaration doesn't work

### ISSUE THREAD

**Issue by seanthepottingshed** [octobercms/october#4397]
- OctoberCMS Build: `v455`
- PHP Version: `7.1.17`
- Database Engine: `mysql`
- Plugins Installed: https://github.com/octoberrain/test-plugin/pull/74

### Description:
Defining `defaultTab` does not make tab active / focused.

### Steps To Reproduce:
- Install https://github.com/octoberrain/test-plugin/pull/74
- Navigate to `backend/october/test/users/update/2`
- **Pivot data** tab should be active / focused _not_ **Standard** tab

**Comment by LukeTowers** [comment]
@seanthepottingshed feel free to dig into the source and see if you can make a PR to fix the issue. Failing that, perhaps @Teranode or @ayumihamsaki have time to look into this?

**Comment by seanthepottingshed** [comment]
@LukeTowers it's scary in there! I will have a look and see what I can determine.

**Comment by bennothommo** [comment]
Confirmed bug.

**Comment by bennothommo** [comment]
@seanthepottingshed Sorry, this may break your heart, but I have to rescind that confirmation.

The [docs for `defaultTab`](https://octobercms.com/docs/backend/forms#form-tab-options) state:
```
the default tab to assign fields to. Default: Misc.
```
It's not used to set which tab is active by default, it's simply specifies which tab will receive fields that have no tab specified.

**Comment by seanthepottingshed** [comment]
@bennothommo 

Ahhhh, sorry my bad, will close this then. Sorry for not understanding the functionality.

**Comment by ayumihamsaki** [comment]
You got me thinking about the default tabs in October and I was suddenly wondering if they have ARIA on them, checking October there is no ARIA setup in any tabs in October. Maybe worth adding some?

See example here of what I am talking about: http://accessibility.athena-ict.com/aria/examples/tabpanel2.shtml

**Comment by Samuell1** [comment]
@ayumihamsaki Ithink aria is pretty useless in backend.

**Comment by ayumihamsaki** [comment]
@Samuell1 So people with disabilities can't use the backend now?

**Comment by Samuell1** [comment]
@ayumihamsaki 

From MDN docs:
> Many of these widgets were later incorporated into HTML5, and developers should prefer using the correct semantic HTML element over using ARIA, if such an element exists. For instance, native elements have built-in keyboard accessibility, roles and states. However, if you choose to use ARIA, you are responsible for mimicking (the equivalent) browser behaviour in script.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA

**Comment by ayumihamsaki** [comment]
@Samuell1 Those are HTML5 elements such as the following:

- <article>
- <aside>
- <audio>
- <bdi>
- <canvas>
- <datalist>
- <details>
- <dialog>
- <embed>
- <figcaption>
- <figure>
- <footer>
- <header>
- <main>
- <mark>
- <menuitem>
- <meter>
- <nav>
- <output>
- <progress>
- <rp>
- <rt>
- <ruby>
- <section>
- <source>
- <summary>
- <svg>
- <time>
- <track>
- <video>
- <wbr>

That doesn't cover complex things like tabs.

**Comment by Samuell1** [comment]
@ayumihamsaki yes it cover but looking right now at it i see tabs buttons are not a buttons but a links, if they are buttons they should work without aria etc but they are not.

**Comment by ayumihamsaki** [comment]
@Samuell1 the way I see ARIA, let's say you have an image on a web page. If I didn't mark it up with ARIA and just replied on HTML schema. How is a blind person meant to know if the image is a logo or a photo or a picture or an icon etc. That's the reason why I personally go the extra mile.

If you got some free time, watch this video it's an eye opener on this subject, see here: https://www.youtube.com/watch?v=OUDV1gqs9GA

**Comment by Samuell1** [comment]
@ayumihamsaki yes, but you looking at backend as website but its mostly for advanced users, not normal website that is mean to be used by users. Yes that video is good but still its example for website that isnt backend administration with many interactive things at once. But still if it can be easy implemented then its fine 👍

**Comment by ayumihamsaki** [comment]
Just coding up the tabs in October ...

Relating to this issue, the `default` tab will be `tabindex="0"` and the rest of the tabs will be `tabindex="-1"`.

Does anyone know the variable of the default tab in October, so I can connected up both together?

Thanks.
