### ISSUE TITLE
Dashboard page won't load when using Object list editor type

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#4398]
- OctoberCMS Build: 456
- PHP Version: 7.3.6

### Description:
The dashboard page won't load after using a reportwidget with a property which uses the object list type. You get the message: ErrorException: substr() expects parameter 1 to be string, array given.

### Steps To Reproduce:
1. Use a reportwidget with a property which uses the object list type
2. Fill in the reportwidget properties
3. Reload the dashboard page

**Comment by LukeTowers** [comment]
@SebastiaanKloos code example of the report widget that doesn't work please.

**Comment by SebastiaanKloos** [comment]
@LukeTowers You can add this property to the report widget
```
'filter' => [
                'title'             => 'Where',
                'type'              => 'objectList',
                'titleProperty'     => 'column',
                'itemProperties'    => [
                    [
                        'property'  => 'column',
                        'title'     => 'Column',
                        'type'      => 'string',
                    ],
                    [
                        'property'  => 'type',
                        'title'     => 'Type',
                        'type'      => 'dropdown',
                        'default'   => '=',
                        'options'   => [
                            '='     => '=',
                            '!='    => '!=',
                            'null' => 'is null',
                            'notNull' => 'is not null',
                        ],
                    ],
                    [
                        'property'  => 'value',
                        'title'     => 'Value',
                        'type'      => 'string',
                    ],
                ],
            ],
```

**Comment by LukeTowers** [comment]
@SebastiaanKloos could you add an example to the test plugin?

**Comment by SebastiaanKloos** [comment]
@LukeTowers, No problem. I’ll add an example tomorrow

**Comment by SebastiaanKloos** [comment]
@LukeTowers I have added it to the test plugin

**Comment by LukeTowers** [comment]
@w20k could you take a look when able?

**Comment by w20k** [comment]
@LukeTowers sure! Added to my Todo's

**Comment by w20k** [comment]
@LukeTowers found the cause:
https://github.com/octobercms/october/blob/4e92686c1a7de662840fa160b7348003f5ba817d/modules/backend/widgets/ReportContainer.php#L453

`$widget->property` return an `array` and `Lang::get` is waiting for a string.

**Comment by LukeTowers** [comment]
@w20k out of curiosity can you post a screenshot of what the widget's inspector looks like? I don't think I've used the objectList type before.

**Comment by w20k** [comment]
@LukeTowers was the first time for me to test this functionality. Haven't seen it yet.
Do you know is there an option to make Algolia on `octobercms.com` to parse those doc files as well - `modules/system/assets/ui/docs`? Or they're not visible at all? Not sure yet, how our `docs` system works)

Here you go:
![Screenshot 2019-07-10 at 10 38 03](https://user-images.githubusercontent.com/1053320/60949966-ed693a00-a2fe-11e9-8919-b0f7283e9330.png)
![Screenshot 2019-07-10 at 10 43 17](https://user-images.githubusercontent.com/1053320/60950306-92841280-a2ff-11e9-8c51-aa1eb15dfc18.png)

**Comment by LukeTowers** [comment]
@w20k not sure about algolia, you'd have to talk to @daftspunk about it.
