### ISSUE TITLE
Ability to override Component partials (Cherry pick method II)

### ISSUE THREAD

**Issue by daftspunk** [octobercms/october#44]
The current solution (#41) is a bit flakey. After some careful consideration, the following approach should be used instead.

---
### Components referencing partials

Components can reference their partials in two ways. First is an explicit method:

```
{% partial __SELF__ ~ "::title" %}
```

The second is a relaxed method:

```
{% partial "@title" %}
```

The relaxed method is contextual:
1. If called inside a component partial, it will directly refer to itself.
2. If called inside a theme partial, it will scan all components used on the page/layout for a matching partial name and use that. Then will continue as per 1. for nested partials.
### Overriding component partials

_All_ component partials can be overridden using the theme partials. Following from the previous example, if our component called **channel** uses the **title.htm** partial.

```
url = "mypage"

[channel]
==
{% component "channel" %}
```

We can override the partial by creating a file in our theme called **partials/channel/title.htm**.

The file path is broken down like this:
- **partials** - the theme partials directory
- **channel** - the component alias (a partial subdirectory)
- **title.htm** - the component partial to override

We can choose our own name for the partial subdirectory by giving the component a different alias. For example:

```
[channel foobar]
==
{% component "foobar" %}
```

Now we can override the partial by creating a file in our theme called **partials/foobar/title.htm**.

**Comment by drFabio** [comment]
Quick doubt. This would work with the default.htm partial as well?  i don't seem to be getting to override the blog plugin, posts component default.htm with that approach
