### ISSUE TITLE
pagination heavy loading for +1million rows 

### ISSUE THREAD

**Issue by bogandix** [octobercms/october#4403]
- OctoberCMS Build: 455
- PHP Version: 7
- Database Engine: mysql

### Description:
The ListController view has a loading issue on a entity with many rows in the database, like more than one million. The change page dropdown generates a 11 Mb response

### Steps To Reproduce:
Generate a list view with more than 1 million items
![Screenshot 2019-06-21 at 15 46 32](https://user-images.githubusercontent.com/4972194/59923519-4a7a7a00-943c-11e9-9271-3a5723769f8e.png)

**Comment by LukeTowers** [comment]
@bogandix for lists with large numbers of records we recommend setting the `showPageNumbers` property for the list widget to false.
