### ISSUE TITLE
Gif image upload cannot generate thumbnails

### ISSUE THREAD

**Issue by lnmput** [octobercms/october#4404]
- OctoberCMS Build: 455
- PHP Version: 7.2
- Database Engine: MySQL 5.7
- Plugins Installed:  No plugin install

### Description:
Gif image upload cannot generate thumbnails
![Snipaste_2019-06-22_09-00-59](https://user-images.githubusercontent.com/7955415/59957579-4ac25600-94cc-11e9-936f-d269c0dd61b1.png)

**Comment by LukeTowers** [comment]
@lnmput feel free to make a PR to fix this

**Comment by bennothommo** [comment]
@lnmput I've tested this with a fresh install of October and .gif files are supported just fine as far as I can tell. Could you provide us with some more info on how you are inserting the .gif image, and if there's any error messages in your logs after uploading?

**Comment by lnmput** [comment]
![001](https://user-images.githubusercontent.com/7955415/60009372-54a0b080-96a8-11e9-9076-7df030f637fb.png)
![002](https://user-images.githubusercontent.com/7955415/60009374-579ba100-96a8-11e9-9be7-c82c580f22d8.png)

**Comment by lnmput** [comment]
@bennothommo js is error
![003](https://user-images.githubusercontent.com/7955415/60009539-a34e4a80-96a8-11e9-8484-1071ca7fae31.png)

**Comment by bennothommo** [comment]
@lnmput I don't believe the issue falls within the JS - the error you posted above seems to be something to do with the debug bar. The thumbnail image itself is one used as a fallback if the upload of your image has failed, so I believe the issue lies in a plugin, or perhaps the server.

Would you be able to look into it further for us?

**Comment by lnmput** [comment]
There is no error on the server， This is the picture I uploaded the error.  https://imgur.com/Z1EDsyz， You can try

**Comment by bennothommo** [comment]
@lnmput Thanks for that - so the issue is that the `.gif` file you have provided is animated. I believe the resizer is unable to resize animated `.gif` files, and it would be likely that even if it could, it would not be able to keep the animation. If you have any suggested fixes, please feel free to provide a PR.

**Comment by lnmput** [comment]
@bennothommo Maybe you are right, but in earlier versions of octobercms, gif-formatted images were thumbnail-generated. such as 419
![hhh](https://user-images.githubusercontent.com/7955415/60062780-2f09ba80-972d-11e9-8284-17a0ba89a4f7.png)
![ttt](https://user-images.githubusercontent.com/7955415/60062784-3630c880-972d-11e9-9feb-0d9537664455.png)

**Comment by bennothommo** [comment]
@lnmput was the animation kept in the thumbnail as well?

**Comment by lnmput** [comment]
@bennothommo  The 419 version, the animation kept in the thumbnail as well

**Comment by bennothommo** [comment]
Thanks @lnmput - it's likely that the [recent changes to the Resizer class](https://github.com/octobercms/library/pull/396) to fix issues with transparency might be the culprit here. Would you be interested in providing a fix for us?

**Comment by mjauvin** [comment]
@bennothommo I wonder if the call to retainImageTransparency() I specifically removed in openImage() for GIF mime type would be responsible for this. I don't recall the reason I removed this, though.

ref. https://github.com/octobercms/library/pull/396/files#diff-1d9e82bad48159f95033f8ddd7320df8L488

**Comment by bennothommo** [comment]
@mjauvin It's possible - but I'm of the opinion that image quality trumps animation (I may be a little biased against animated GIFs).

**Comment by LukeTowers** [comment]
@bennothommo @mjauvin could we detect when the image is animated and just accept having a poorer quality end result under those cases?

**Comment by mjauvin** [comment]
In the user comments of this page, there are some methods to do so, although they require reading through part of the file data... not sure how efficient that is:

https://www.php.net/manual/en/function.imagecreatefromgif.php

This one looks clean:

```
function is_animated_gif($file)
{
    $fp = null;

    if (is_string($file)) {
        $fp = fopen($file, "rb");
    } else {
        $fp = $file;

        /* Make sure that we are at the beginning of the file */
        fseek($fp, 0);
    }

    if (fread($fp, 3) !== "GIF") {
        fclose($fp);

        return false;
    }

    $frames = 0;

    while (!feof($fp) && $frames < 2) {
        if (fread($fp, 1) === "\x00") {
            /* Some of the animated GIFs do not contain graphic control extension (starts with 21 f9) */
            if (fread($fp, 1) === "\x21" || fread($fp, 2) === "\x21\xf9") {
                $frames++;
            }
        }
    }

    fclose($fp);

    return $frames > 1;
}
```

**Comment by mjauvin** [comment]
Do you think it's worth implementing this function in Resizer to decide which quality to use?

**Comment by mjauvin** [comment]
For what it's worth, I reverted to 65ce89399df8bd81180776cb47293cc60fcf3b1d of october/library and the generated thumbs for animated gifs did NOT retain the animation.

I also went back to v1.0.419 (ece4341a6be4e28d4d1dbf773200b0b7140a156f) and could not get animated thumbs either.

**Comment by LukeTowers** [comment]
@lnmput please provide the file that you're using to test that works

**Comment by bennothommo** [comment]
@LukeTowers I believe this is the image that @lnmput used that previously worked but does not now: https://imgur.com/Z1EDsyz

**Comment by lnmput** [comment]
It seems this problem is difficult to solve

**Comment by mjauvin** [comment]
So far, I have not been able to confirm this used to generate animated thumbnails.

**Comment by mjauvin** [comment]
@lnmput can you confirm that this PR (https://github.com/octobercms/library/pull/448) does generate a thumbnail for your GIFs.

Note: I was not able to keep the animaton in the thumbnail so far.

**Comment by daftspunk** [comment]
Resizing animated gifs was never supported. Showing a broken image is not good, so the underlying issue has been fixed for the next release. Thanks
