### ISSUE TITLE
Scrollbar in Code Editor screen jumpy and flickers in Edge Browser

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4417]
See youtube video: https://youtu.be/buVGNnG0Q5c

It's pretty much unusable when using the Edge browser.

That was on Edge 18. Chrome, Firefox and Opera are ok. I didn't bother to test Safari, because I think that browser is pure junk!

Looks like some bad scrolling jank - http://jankfree.org/

Seems to be coming from the `.ace_scrollbar`

See here code example for ace editor: http://jsfiddle.net/wna8h21d/

You can test out the y-axis scrollbar and it is smooth. Definitely jank coming from October.

It's probably an event listener not being set to passive messing it about.

**Comment by LukeTowers** [comment]
@ayumihamsaki feel free to make a PR.

**Comment by ayumihamsaki** [comment]
I need to spend some time, trying to find the cause of the issue first, then will be happy to create a pr for it.

**Comment by ayumihamsaki** [comment]
Link this for now: here: https://github.com/octobercms/october/issues/4437

**Comment by ayumihamsaki** [comment]
Possible fix for this issue is in this pull request I did a while back: https://github.com/octobercms/october/pull/3951

**Comment by ayumihamsaki** [comment]
@LukeTowers I'm going to close this issue - the reason being that Microsoft Edge now uses Chromium open source project and so in the coming weeks this issue will auto fix itself, see here as proof:

![image](https://user-images.githubusercontent.com/17784082/62959529-f020e880-bdf0-11e9-9196-d935b5df44db.png)
