### ISSUE TITLE
Add Thai translation

### ISSUE THREAD

**Issue by anurat** [octobercms/october#4419]
Hi,

I would like to contribute by adding a new language, namely Thai language, to October backend.
So far I am able to translate some of the text in the following:

update modules/backend/models/Preference.php
	function getLocaleOptions()
		add 'th' => [Lang::get('system::lang.locale.th'), 'flag-th'],

create modules/backend/lang/th/lang.php
	update text
create modules/cms/lang/th/lang.php
	update text
create modules/system/lang/th/lang.php
	'locale' add 'th' => 'ไทย',
	update text
create modules/system/lang/th/client.php
	update text
create modules/system/lang/th/validation.php
	update text

However there is an issue that prevents the text to show.
![alert cancel_button_text](https://user-images.githubusercontent.com/2355534/60237425-fc022b00-98d4-11e9-9cf2-1da5c03affd3.png)

I found that it is related to modules/system/lang/th/client.php that may not get loaded.
I'm wondering what I should do to fix the issue.

Best Regards,

**Comment by LukeTowers** [comment]
@anurat after updating client.php you have to run `php artisan october:util compile lang` to recompile the JS language files.

**Comment by anurat** [comment]
Thank you LukeTowers, it works!

**Comment by LukeTowers** [comment]
No problem @anurat! I'll leave this open until you've made a PR to add the language and it's been merged

**Comment by anurat** [comment]
Hi @LukeTowers ,

I've translated most of the text in lang and client files but some of them I couldn't find where they are used so I do not understand or not sure how I should translate them.

Here are the text I couldn't translate. If you could point out where they are used or explain what these mean, I'd really appreciate it.

modules/system/lang/th/lang.php

```php
    'combiner' => [
        'not_found' => "The combiner file ':name' is not found.",
    ],
    'mail_templates' => [
        // I know where to find this but not sure what it does
        'disable_auto_inline_css' => 'Disable automatic inline CSS',
    ],
```

modules/cms/lang/th/lang.php

```php
    'editor' => [
        // why is it commit instead of save/update?
        'commit_confirm' => 'Are you sure you want to commit your changes to this file to the filesystem? This will overwrite the existing file on the filesystem',
        'committing' => 'Committing',
        'commit_success' => 'The :type has been committed to the filesystem',
        'reset_success' => 'The :type has been reset to the filesystem version',
    ],
```

modules/backend/lang/th/lang.php

```php
    'field' => [
        'options_method_invalid_model' => "ฟิลด์ ':field' ไม่ตรงกับโมเดล Try specifying the options method for model class :model explicitly.",
        'options_method_not_exists' => "The model class :model must define a method :method() returning options for the ':field' form field.",
        'colors_method_not_exists' => "The model class :model must define a method :method() returning html color HEX codes for the ':field' form field.",
    ],
    'dashboard' => [
        'status' => [
            'update_available' => '{0} updates available!|{1} update available!|[2,Inf] updates available!',
        ],
    ],
    'list' => [
        'missing_model' => 'List behavior used in :class does not have a model defined.',
        'missing_columns' => 'List used in :class has no list columns defined.',
        'missing_definition' => "List behavior does not contain a column for ':field'.",
        'missing_parent_definition' => "List behavior does not contain a definition for ':definition'.",
        'behavior_not_ready' => 'List behavior has not been initialized, check that you have called makeLists() in your controller.',
        'invalid_column_datetime' => "Column value ':column' is not a DateTime object, are you missing a \$dates reference in the Model?",
    ],
    'repeater' => [
        'min_items_failed' => ':name requires a minimum of :min items, only :items were provided',
        'max_items_failed' => ':name only allows up to :max items, :items were provided',
    ],
    'form' => [
        'missing_id' => 'Form record ID has not been specified.',
        'missing_model' => 'Form behavior used in :class does not have a model defined.',
        'missing_definition' => "Form behavior does not contain a field for ':field'.",
        'not_found' => 'Form record with an ID of :id could not be found.',
        'behavior_not_ready' => 'Form behavior has not been initialized, check that you have called initForm() in your controller.',
        'preview_no_record_message' => 'There is no record selected.',
    ],
    'recordfinder' => [
        'find_record' => 'Find Record',
        'invalid_model_class' => 'The provided model class ":modelClass" for the recordfinder is invalid',
    ],
    'relation' => [
        'missing_config' => "Relation behavior does not have any configuration for ':config'.",
        'missing_definition' => "Relation behavior does not contain a definition for ':field'.",
        'missing_model' => 'Relation behavior used in :class does not have a model defined.',
        'invalid_action_single' => 'This action cannot be performed on a singular relationship.',
        'invalid_action_multi' => 'This action cannot be performed on a multiple relationship.',
        'help' => 'Click on an item to add',
        'related_data' => 'Related :name data',
   ],
    'reorder' => [
        'default_title' => 'Reorder records',
        'no_records' => 'There are no records available to sort.',
    ],
    'model' => [
        'name' => 'Model',
        'not_found' => "Model ':class' with an ID of :id could not be found",
        'missing_id' => 'There is no ID specified for looking up the model record.',
        'missing_relation' => "Model ':class' does not contain a definition for ':relation'.",
        'missing_method' => "Model ':class' does not contain a method ':method'.",
        'invalid_class' => "Model :model used in :class is not valid, it must inherit the \Model class.",
        'mass_assignment_failed' => "Mass assignment failed for Model attribute ':attribute'.",
    ],
    'filter' => [
        'options_method_not_exists' => "The model class :model must define a method :method() returning options for the ':filter' filter.",
    ],
    // where are these import/export pages?
    'import_export' => [
        'import_file' => 'Import file',
        'row' => 'Row :row',
        'first_row_contains_titles' => 'First row contains column titles',
    ],
```

modules/system/lang/th/client.php

```php
    'eventlog' => [
        'editor' => [
            'description' => 'Your operating system should be configured to listen to one of these URL schemes.',
        ],
    ],
```

**Comment by LukeTowers** [comment]
> ```
>     'combiner' => [
>         'not_found' => "The combiner file ':name' is not found.",
>     ],
> ```
This is an error message that is shown in the combiner under certain conditions: https://github.com/octobercms/october/blob/4e92686c1a7de662840fa160b7348003f5ba817d/modules/system/classes/SystemController.php#L28.
>```
>     'mail_templates' => [
>         // I know where to find this but not sure what it does
>         'disable_auto_inline_css' => 'Disable automatic inline CSS',
> ```
By default, October will automatically "inline" mail template CSS for better support in mail clients (this means instead of having a style tag with all your CSS rules, it analyzes your rules and applies them as inline style attributes on the elements they target.

> ```
>     'editor' => [
>         // why is it commit instead of save/update?
>         'commit_confirm' => 'Are you sure you want to commit your changes to this file to the filesystem? This will overwrite the existing file on the filesystem',
>         'committing' => 'Committing',
>         'commit_success' => 'The :type has been committed to the filesystem',
>         'reset_success' => 'The :type has been reset to the filesystem version',
>     ],
> ```
Because this is a special operation with a special purpose, you're not just saving your file (because normally under the conditions this message would be seen you're using the DB layer and saving it there without touching the filesystem, however this action means that your DB content will get pushed to the filesystem, overwriting what was there previously (and also removing the file from the DB but that's just for performance, not a huge deal).


> 
> modules/backend/lang/th/lang.php
> 
> ```
>     'field' => [
>         'options_method_invalid_model' => "ฟิลด์ ':field' ไม่ตรงกับโมเดล Try specifying the options method for model class :model explicitly.",
>         'options_method_not_exists' => "The model class :model must define a method :method() returning options for the ':field' form field.",
>         'colors_method_not_exists' => "The model class :model must define a method :method() returning html color HEX codes for the ':field' form field.",
>     ],
>     'dashboard' => [
>         'status' => [
>             'update_available' => '{0} updates available!|{1} update available!|[2,Inf] updates available!',
>         ],
>     ],
>     'list' => [
>         'missing_model' => 'List behavior used in :class does not have a model defined.',
>         'missing_columns' => 'List used in :class has no list columns defined.',
>         'missing_definition' => "List behavior does not contain a column for ':field'.",
>         'missing_parent_definition' => "List behavior does not contain a definition for ':definition'.",
>         'behavior_not_ready' => 'List behavior has not been initialized, check that you have called makeLists() in your controller.',
>         'invalid_column_datetime' => "Column value ':column' is not a DateTime object, are you missing a \$dates reference in the Model?",
>     ],
>     'repeater' => [
>         'min_items_failed' => ':name requires a minimum of :min items, only :items were provided',
>         'max_items_failed' => ':name only allows up to :max items, :items were provided',
>     ],
>     'form' => [
>         'missing_id' => 'Form record ID has not been specified.',
>         'missing_model' => 'Form behavior used in :class does not have a model defined.',
>         'missing_definition' => "Form behavior does not contain a field for ':field'.",
>         'not_found' => 'Form record with an ID of :id could not be found.',
>         'behavior_not_ready' => 'Form behavior has not been initialized, check that you have called initForm() in your controller.',
>         'preview_no_record_message' => 'There is no record selected.',
>     ],
>     'recordfinder' => [
>         'find_record' => 'Find Record',
>         'invalid_model_class' => 'The provided model class ":modelClass" for the recordfinder is invalid',
>     ],
>     'relation' => [
>         'missing_config' => "Relation behavior does not have any configuration for ':config'.",
>         'missing_definition' => "Relation behavior does not contain a definition for ':field'.",
>         'missing_model' => 'Relation behavior used in :class does not have a model defined.',
>         'invalid_action_single' => 'This action cannot be performed on a singular relationship.',
>         'invalid_action_multi' => 'This action cannot be performed on a multiple relationship.',
>         'help' => 'Click on an item to add',
>         'related_data' => 'Related :name data',
>    ],
>     'reorder' => [
>         'default_title' => 'Reorder records',
>         'no_records' => 'There are no records available to sort.',
>     ],
>     'model' => [
>         'name' => 'Model',
>         'not_found' => "Model ':class' with an ID of :id could not be found",
>         'missing_id' => 'There is no ID specified for looking up the model record.',
>         'missing_relation' => "Model ':class' does not contain a definition for ':relation'.",
>         'missing_method' => "Model ':class' does not contain a method ':method'.",
>         'invalid_class' => "Model :model used in :class is not valid, it must inherit the \Model class.",
>         'mass_assignment_failed' => "Mass assignment failed for Model attribute ':attribute'.",
>     ],
>     'filter' => [
>         'options_method_not_exists' => "The model class :model must define a method :method() returning options for the ':filter' filter.",
>     ],
> ```
These are all error messages that occur under specific conditions.

> ```
>     // where are these import/export pages?
>     'import_export' => [
>         'import_file' => 'Import file',
>         'row' => 'Row :row',
>         'first_row_contains_titles' => 'First row contains column titles',
>     ],
> ```
This is used when a plugin implements the ImportExportController behavior: https://octobercms.com/docs/backend/import-export

> modules/system/lang/th/client.php
> 
> ```
>     'eventlog' => [
>         'editor' => [
>             'description' => 'Your operating system should be configured to listen to one of these URL schemes.',
>         ],
>     ],
> ```
This is an undocumented feature of October that I didn't even realize existed until I looked into it right now: https://github.com/octobercms/october/pull/2035

**Comment by anurat** [comment]
Thanks a lot @LukeTowers,
I think I will leave some of those without translating and do a Pull Request.


I'm still new to Pull Request so I'm not sure whether I'm doing it right.
Please let me know if you have preferred way of doing this.

1. Generally should I fork october to my account, commit changes and then do a pull request?
2. I found that modules/backend/models/Preference.php has changed a lot more than I edited due to phpfmt formatting the file. How do you do file formatting for october?
3. After I run composer install, thousand files got changed, how do you prevent these changed files from committing to github?

Best Regards,

**Comment by LukeTowers** [comment]
@anurat:
> Generally should I fork october to my account, commit changes and then do a pull request?
Yes, but make sure you base it off of the develop branch and make the PR with the develop branch.

> I found that modules/backend/models/Preference.php has changed a lot more than I edited due to phpfmt formatting the file. How do you do file formatting for october?
Leave the existing format of the file alone, there will be some automated style checking when the PR is submitted, just make sure you aren't making any changes to the style / formatting and if the style checker asks for changes make them.

> After I run composer install, thousand files got changed, how do you prevent these changed files from committing to github?
Modify the composer.json to use the develop branch instead of the tagged releases: https://octobercms.com/docs/console/commands#console-install-composer

**Comment by anurat** [comment]
@LukeTowers ,

Thank you very much for your patience and the answers.

> Modify the composer.json to use the develop branch instead of the tagged releases: https://octobercms.com/docs/console/commands#console-install-composer

I modified composer.json as the following:
```
        "october/rain": "dev-develop as 1.0",
        "october/system": "dev-develop",
        "october/backend": "dev-develop",
        "october/cms": "dev-develop",
        "laravel/framework": "5.5.*@dev",
```
but I still got >2000 modified files after running `composer install`, which will be a problem when doing pull request. I probably miss something.

**Comment by w20k** [comment]
@anurat do you have `.gitignore`?

**Comment by anurat** [comment]
@w20k I do have `.gitignore`
The modified files are source code but I don't see any changes inside the file.
Just smartgit reporting them being modified.

![smartgit](https://user-images.githubusercontent.com/2355534/61777925-08bc6500-ae28-11e9-8819-c6a88722743a.png)

**Comment by LukeTowers** [comment]
@anurat try running composer update instead. Also see https://stackoverflow.com/questions/14564946/git-status-shows-changed-files-but-git-diff-doesnt
