### ISSUE TITLE
Add support for scope to the TagList relation mode

### ISSUE THREAD

**Issue by huynhnamegal** [octobercms/october#4420]
- OctoberCMS Build: 4456
- PHP Version: 7.0.26

### Description:
I want to show some records via relation which used scope query for taglist type. And it did not work, it return all records and ignore the scope query. But it worked with relation type.

**Comment by LukeTowers** [comment]
That's not a supported option, see https://octobercms.com/docs/backend/forms#widget-taglist for a list of the supported options. You could always add support for it yourself in a PR though.
