### ISSUE TITLE
List child rows (show extra / detailed information)

### ISSUE THREAD

**Issue by prhost** [octobercms/october#4421]
I am developing this functionality as a matter of necessity, I can send you a PR if you are interested, I believe it is very complicated to create a plugin for it due to many changes in `Lists Widget` and partials of the list.

I am based on the functionality of Tree Node that already has in the list.
I created an attribute in `config_list.yaml` called `rowDetailsPartial` which passes the partial path, being able to create what you want.

I also put an icon on the table head to be able to expand or contract all at once.

I accept suggestions of icons, behaviors, extra config and visual.

The idea I based on [datatables row details](https://datatables.net/examples/api/row_details.html).

![Untitled](https://user-images.githubusercontent.com/3984760/60268625-3367dc00-98c3-11e9-8d39-ed0c5788304e.gif)

**Comment by LukeTowers** [comment]
This plugin seems similar to what you're looking for: https://octobercms.com/plugin/linkonoid-backendpopup

**Comment by prhost** [comment]
> This plugin seems similar to what you're looking for: https://octobercms.com/plugin/linkonoid-backendpopup

Quite different, in this plugin you can not customize anything, only configure to show the main actions of the Form, and have no preview. My idea is to personalize anything, display a graph, more information, and allows you to see more than one simultaneously to compare data for example.

**Comment by LukeTowers** [comment]
Well I'm not opposed to the idea in theory, but the API for it would have to be well designed. I would also like it to be focused on improving the mobile experience of lists, I think this could be a good way of minimizing the columns used on mobile while still retaining the amount of data displayed. Thoughts?
