### ISSUE TITLE
create new plugin can't create table

### ISSUE THREAD

**Issue by yinglau** [octobercms/october#4425]
When I create a new plugin `php artisan create:plugin Winson.Test`, after that I create a model with `php artisan create:model Winson.Test posts`, and run `php artisan plugin:refresh Winson.Test`, mysql can't see the table `winson_test_posts`.
How can I create the table?

**Comment by jexme** [comment]
First, it is better to create models in the singular, in your case Post
Secondly, in order for the migrations to work, you need to add them to `updates/version.yml`:
```
1.0.1:
   - Run table migrations
   - create_posts_table.php
```

procedure:
1. php artisan create: plugin Winson.Test
2. php artisan create: model Winson.Test Post
3. add your table to the migration file
4. Raise the version of the plugin `php artisan october:up` or update it `php artisan plugin:refresh Winson.Test`

**Comment by LukeTowers** [comment]
@yinglau creating the model doesn't automatically add its migration file to the version.yaml file (required for the migration to be run). See https://octobercms.com/docs/plugin/updates#migration-seed-files

As a side note, models should always be named with a singular name (i.e. Post) and tables and controllers with the plural form of that name.

**Comment by yinglau** [comment]
> First, it is better to create models in the singular, in your case Post
> Secondly, in order for the migrations to work, you need to add them to `updates/version.yml`:
> 
> ```
> 1.0.1:
>    - Run table migrations
>    - create_posts_table.php
> ```
> 
> procedure:
> 
> 1. php artisan create: plugin Winson.Test
> 2. php artisan create: model Winson.Test Post
> 3. add your table to the migration file
> 4. Raise the version of the plugin `php artisan october:up` or update it `php artisan plugin:refresh Winson.Test`

Thanks guy, cool.
