### ISSUE TITLE
Create relative links while mirroring

### ISSUE THREAD

**Issue by p5ych0** [octobercms/october#4429]
currently all symlinks are being created with absolute paths while mirroring. it seems to be much robust to have relative paths instead. please consider

**Comment by bennothommo** [comment]
@p5ych0 Would you be willing to provide a PR that adds an argument to the `artisan october:mirror` command which would allow someone to specify that they want relative symlinks?

**Comment by LukeTowers** [comment]
@p5ych0 @bennothommo this already exists, see the `--relative` flag for the `october:mirror` command. I'll add a note to the docs.

**Comment by LukeTowers** [comment]
Documented here: https://github.com/octobercms/docs/commit/f6e3eef7a69aae4daf0ae2d27f004a1fa993a008
