### ISSUE TITLE
Problem for using the Backend.Behaviors.ImportExportController

### ISSUE THREAD

**Issue by yinglau** [octobercms/october#4431]
Here some problems to use export behaviors.
I follow the [https://octobercms.com/docs/backend/import-export#export-page](https://octobercms.com/docs/backend/import-export#export-page) to develop the plugin

**step 1. add the import export behaviors to my controller class**

```php
public $implement = [
        'Backend.Behaviors.ImportExportController',
];
public $importExportConfig = 'config_import_export.yaml';
```

**step 2. Configuring the behavior**

here is my `config_import_export.yaml`

```php
# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: Import
    modelClass: Author\PluginName\Models\SubscriberImport
    list: $/acme/campaign/models/subscriber/columns.yaml

export:
    title: Export
    modelClass: Acme\PluginName\Models\SubscriberExport
    list: $/Author/PluginName/models/subscriber/columns.yaml
```

And finnally, I call the `export` action in backend, it redirects to `backend/[Author]/[PluginName]/[ControllerName]/download/oc5d1dadf3858ed/[filename]`, here a error see the picture bellow.

![image](https://user-images.githubusercontent.com/16402665/60648625-dd6ed780-9e72-11e9-8304-085315df449e.png)

sorry, My plugin error picture forget to intercept , this picture above is use the plugin `RainLab\Blog\Posts` , the problem same with me.

Somebody help me!! Thanks.

**Comment by LukeTowers** [comment]
Your server is misconfigured, it's attempting to serve the requested URL without touching October at all. Configure your server so that all requests (excluding known asset files such as image, fonts, scripts, and stylesheet extensions) go through October's entry point (index.php) so that October can process this request.

**Comment by yinglau** [comment]
> Your server is misconfigured, it's attempting to serve the requested URL without touching October at all. Configure your server so that all requests (excluding known asset files such as image, fonts, scripts, and stylesheet extensions) go through October's entry point (index.php) so that October can process this request.

How to configure, which file? @LukeTowers

**Comment by LukeTowers** [comment]
@yinglau Depends on the server you're using. What server software are you using? Apache? IIS? Nginx?

**Comment by yinglau** [comment]
> @yinglau Depends on the server you're using. What server software are you using? Apache? IIS? Nginx?

@LukeTowers Local environment development， In my mac, and start the application use `php -S 0.0.0.0:8000`, not use `Apache` or `Nginx`

**Comment by yinglau** [comment]
@LukeTowers In my server host , it's succesful, my server host is use `Nginx` to run it, but my local host just use `php -S 0.0.0.0:8000` to run, it doesn't work.

**Comment by w20k** [comment]
@yinglau try using MAMP on Mac, would be much easier. You'd have to somehow configure your php server to server files properly: like nginx config or apache (docs:https://www.cvedetails.com/product/156/Apple-Mac-Os-X.html?vendor_id=49).

There is an option to do it with build in the php server, but it feels like you'd have to write your own `router.php` for that. Which sounds like a pain... and run it `php -S localhost -S 0.0.0.0: 8000 router.php`

**Comment by seanthepottingshed** [comment]
@yinglau I find Laravel Valet works really well

**Comment by LukeTowers** [comment]
@yinglau you could also try running `php artisan serve` instead and see if that's better setup
