### ISSUE TITLE
Move Storm UI to its own repo

### ISSUE THREAD

**Issue by DanHarrin** [octobercms/october#4436]
I was having a chat with @daftspunk about the possibility of the [Storm UI](https://github.com/octobercms/october/tree/master/modules/system/assets/ui) having its own repo, as well as its docs living in [OctoberCMS/Docs](https://github.com/octobercms/docs). On each October build, it would then be pulled in from this repo and would live in the same place as it does currently. There are two aims to this - to maintain a consistent separation of the UI assets from October, and to consolidate the [October docs](https://github.com/octobercms/docs) and the [UI docs](https://github.com/octobercms/october/tree/master/modules/system/assets/ui/docs).

This issue is for the discussion of this move, please contribute with your ideas / possible problems that this move may cause.

**Comment by LukeTowers** [comment]
If we're keeping the UI assets & docs where they are anyways then I don't see any reason to duplicate that content in separate repositories. The Storm UI library is pretty tightly tied to OctoberCMS in general and unlikely to be used on its own. The only problem with the current setup that I see is that it's harder for newcomers to understand where the UI docs are coming from on the website. (system/assets/ui/docs)

**Comment by DanHarrin** [comment]
@LukeTowers okay I see where you're coming from, so would a move of just the [UI docs](https://github.com/octobercms/october/tree/master/modules/system/assets/ui/docs) so that they reside in [OctoberCMS/Docs](OctoberCMS/Docs) _instead_ of the [`ui` folder](https://github.com/octobercms/october/tree/master/modules/system/assets/ui) would suffice in this case?

**Comment by LukeTowers** [comment]
@DanHarrin if @daftspunk is fine with moving it to a ui/ folder under the docs repo then I'm fine with that. He has to update the website to make it work in the first place so without his agreement it's not going to happen.

**Comment by LukeTowers** [comment]
@daftspunk while we're talking docs it would be nice if the generated API docs were pushed to a readonly repo automatically (say octoberrain/api-docs) for local replication.

**Comment by daftspunk** [comment]
The docs live with the library because the two are closely connected, the JS files are needed or the docs don't really make sense. It's also useful to access the docs while working with the JS. The current set up is similar to a [Storybook](https://storybook.js.org/)
