### ISSUE TITLE
How to handle http 'OPTIONS' request

### ISSUE THREAD

**Issue by yinglau** [octobercms/october#4440]
I write a `POST` method http request , there is a `OPTIONS` request got `404`
![image](https://user-images.githubusercontent.com/16402665/60812492-3072c280-a1c4-11e9-9786-ba5549123545.png)

How to handle the `OPTIONS` method request?

Thanks!

**Comment by LukeTowers** [comment]
See https://medium.com/@neo/handling-xmlhttprequest-options-pre-flight-request-in-laravel-a4c4322051b9 or just use the wonderful plugin by @tobias-kuendig: https://octobercms.com/plugin/offline-cors

**Comment by yinglau** [comment]
@LukeTowers Hey guys, thanks for your help, it's finally work.
