### ISSUE TITLE
Column not found: 1054 Unknown column 'any_template' in 'order clause'

### ISSUE THREAD

**Issue by plyusninva** [octobercms/october#4441]
- OctoberCMS Build: 455
- PHP Version: 7
- Database Engine: MySQL

### Description & steps: 
1) Log settings -> Log theme changes ENABLED
2) LOGS -> Theme log (/backend/cms/themelogs)
3) Try sort column "Template"
![image](https://user-images.githubusercontent.com/25381948/60875486-67dc8000-a253-11e9-938b-4e8adcfaaf01.png)
4) Result error:
![image](https://user-images.githubusercontent.com/25381948/60870886-1b8d4200-a24b-11e9-97d9-1ea08c47e899.png)

p.s.: 
list setup
![image](https://user-images.githubusercontent.com/25381948/60875601-a5410d80-a253-11e9-90de-91b68a325944.png)

**Comment by NathanBastiaans** [comment]
> How to cancel the sorting settings? I can't get into theme logs anymore.

You can log out with your back-end user to restore sorting to defaults.

**Comment by plyusninva** [comment]
> > How to cancel the sorting settings? I can't get into theme logs anymore.
> 
> You can log out with your back-end user to restore sorting to defaults.

Thank you very much! :-)

**Comment by LukeTowers** [comment]
@NathanBastiaans @plyusninva Note that in Build 457 that will no longer work as sorting will be saved as a user preference instead of a session variable. To fix it in the future temporarily (before an official fix is released) just add `sortable: false` to the offending column definition.
