### ISSUE TITLE
Auth::id() has an undefined variable

### ISSUE THREAD

**Issue by laetificat** [octobercms/october#4442]
- OctoberCMS Build: v1.0.456
- PHP Version: 7.3.3
- Database Engine: MySQL

~~**Note: I'm currently in the process of creating a pull request to fix this.**~~

### Description:
When calling `RainLab\User\Facades\Auth::id()` the system throws an unhandled error with the message `Undefined variable: user`.

### Steps To Reproduce:
Call `RainLab\User\Facades\Auth::id()` anywhere in your code where available.

**Comment by NathanBastiaans** [comment]
I can recreate the issue by calling the `Auth::id()` method in an existing component. The given pull request seems to fix this issue. 👍
