### ISSUE TITLE
Fix the die and dump debugging widget

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4446]
Just come across this piece of code when reading the source code.

When you create a dump box it creates the following code:

```html
<th colspan="3" colspan="100" style="font-size: 18px; font-weight: normal; margin: 0; padding: 10px; background-color: #7B8892; color: #FFF">
```

Basically, the Browser is auto fixing the coding mistake so maybe people don't notice it.

The above code line seems to have a double `colspan`

See code in October:

https://github.com/octobercms/october/blob/217d52bc776eb19b5642ad8344955535c930f5fe/modules/cms/twig/DebugExtension.php#L190

I'm pretty sure the `colspan="100"` should not be there.

**Comment by ayumihamsaki** [comment]
Just spotted some other strange things going on, it seems like there is no matching `<td>` and `<th>`.

Also missing `<tbody>` and `<thead>` tags.

This is what I am seeing:

```html
<table>
    <tr>
        <th colspan="3" style="font-size: 18px; font-weight: normal; margin: 0; padding: 10px; background-color: #7B8892; color: #FFF">
        Component variables
        <div style="font-size: 12px; font-weight: normal; font-style: italic; margin: 0; padding: 0; background-color: #7B8892; color: #FFF">Example\Plugin\Something</div>
        </td>
    </tr>
<tr>
    <td style="padding: 7px; background-color: #FFF; color: #405261;cursor:pointer" onclick="var d=this.parentElement.nextElementSibling.getElementsByTagName('div')[0];d.style.display=='none'?d.style.display='block':d.style.display='none'">init()</td>
    <td style="padding: 7px; background-color: #FFF; color: #405261">method</td>
    <td style="padding: 7px; background-color: #FFF; color: #405261"></td>
</tr>
..
</table>
```

**Comment by ayumihamsaki** [comment]
Just spotted some other strange things going on, it seems like there is no matching `<td>` and `<th>`.

Also missing `<tbody>` and `<thead>` tags.

This is what I am seeing:

```html
<table>
    <tr>
        <!-- No closing </th> -->
        <th colspan="3" style="font-size: 18px; font-weight: normal; margin: 0; padding: 10px; background-color: #7B8892; color: #FFF">
        Component variables
        <div style="font-size: 12px; font-weight: normal; font-style: italic; margin: 0; padding: 0; background-color: #7B8892; color: #FFF">Example\Plugin\Something</div>
        <!-- No opening <td> -->
        </td>
    </tr>
    <tr>
        <td style="padding: 7px; background-color: #FFF; color: #405261;cursor:pointer" onclick="var d=this.parentElement.nextElementSibling.getElementsByTagName('div')[0];d.style.display=='none'?d.style.display='block':d.style.display='none'">init()</td>
        <td style="padding: 7px; background-color: #FFF; color: #405261">method</td>
        <td style="padding: 7px; background-color: #FFF; color: #405261"></td>
    </tr>
..
</table>
```

Maybe the code should be like this:

```html
<table>
    <thead>
        <tr>
            <th colspan="3" style="font-size: 18px; font-weight: normal; margin: 0; padding: 10px; background-color: #7B8892; color: #FFF">
                Component variables
                <div style="font-size: 12px; font-weight: normal; font-style: italic; margin: 0; padding: 0; background-color: #7B8892; color: #FFF">Example\Plugin\Something</div>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding: 7px; background-color: #FFF; color: #405261;cursor:pointer" onclick="var d=this.parentElement.nextElementSibling.getElementsByTagName('div')[0];d.style.display=='none'?d.style.display='block':d.style.display='none'">init()</td>
            <td style="padding: 7px; background-color: #FFF; color: #405261">method</td>
            <td style="padding: 7px; background-color: #FFF; color: #405261"></td>
        </tr>
    </tbody>
..
</table>
```

**Comment by ayumihamsaki** [comment]
Just spotted some other strange things going on, it seems like there is no matching `<td>` and `<th>`.

Also missing `<tbody>` and `<thead>` tags.

This is what I am seeing:

```html
<table>
    <tr>
        <!-- No closing </th> -->
        <th colspan="3" style="font-size: 18px; font-weight: normal; margin: 0; padding: 10px; background-color: #7B8892; color: #FFF">
        Component variables
        <div style="font-size: 12px; font-weight: normal; font-style: italic; margin: 0; padding: 0; background-color: #7B8892; color: #FFF">Example\Plugin\Something</div>
        <!-- No opening <td> -->
        </td>
    </tr>
    <tr>
        <td style="padding: 7px; background-color: #FFF; color: #405261;cursor:pointer" onclick="var d=this.parentElement.nextElementSibling.getElementsByTagName('div')[0];d.style.display=='none'?d.style.display='block':d.style.display='none'">init()</td>
        <td style="padding: 7px; background-color: #FFF; color: #405261">method</td>
        <td style="padding: 7px; background-color: #FFF; color: #405261"></td>
    </tr>
..
</table>
```

Maybe the code should be like this:

```html
<table>
    <thead>
        <tr>
            <th colspan="3" style="font-size: 18px; font-weight: normal; margin: 0; padding: 10px; background-color: #7B8892; color: #FFF">
                Component variables
                <div style="font-size: 12px; font-weight: normal; font-style: italic; margin: 0; padding: 0; background-color: #7B8892; color: #FFF">Example\Plugin\Something</div>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding: 7px; background-color: #FFF; color: #405261;cursor:pointer" onclick="var d=this.parentElement.nextElementSibling.getElementsByTagName('div')[0];d.style.display=='none'?d.style.display='block':d.style.display='none'">init()</td>
            <td style="padding: 7px; background-color: #FFF; color: #405261">method</td>
            <td style="padding: 7px; background-color: #FFF; color: #405261"></td>
        </tr>
        ..
    </tbody>
</table>
```

**Comment by ayumihamsaki** [comment]
Their seems to be more weird things going on ?

```html
<pre class=sf-dump id=sf-dump-618539834 data-indent-pad="  ">"<span class=sf-dump-str title="19 characters">___METHOD___|init()</span>"
</pre>
```

There's no double quotes on the `class` and `id` attributes ?

**Comment by ayumihamsaki** [comment]
This is not escaped ?

```html
<span class=sf-dump-index>0</span> => "<span class=sf-dump-str title="46 characters">@RainLab.Translate.Behaviors.TranslatableModel</span>"
```

Needs to be:

```html
<span class=sf-dump-index>0</span> =&gt; "<span class=sf-dump-str title="46 characters">@RainLab.Translate.Behaviors.TranslatableModel</span>"
```

More missing double quotes ?

```html
<a class=sf-dump-ref href=#sf-dump-323239636-ref24308 title="3 occurrences">#4308</a>
```

On the `class` and `href`.

**Comment by ayumihamsaki** [comment]
That's all the errors I see, just repeated several thousand times over.

**Comment by w20k** [comment]
Will look at it @ayumihamsaki, when I have a minute. Thanks!)

**Comment by ayumihamsaki** [comment]
Thanks.

Also why does it use three columns and not two, that also makes no sense to me?

![eg](https://user-images.githubusercontent.com/17784082/61055066-a0619280-a3e8-11e9-9529-6a8a7e4bc911.png)

**Comment by ayumihamsaki** [comment]
Another error:

![eg](https://user-images.githubusercontent.com/17784082/61056587-8a090600-a3eb-11e9-83cc-5e98d9cef22e.png)

**Comment by LukeTowers** [comment]
@ayumihamsaki I would imagine that it is hard coded for the same reason exception messages and code comments are not translated. The development language of the project is English, and this is an development tool. If it's not something that should be displayed to end users, only developers, then it should be in English.

**Comment by ayumihamsaki** [comment]
Cool, that makes sense.

**Comment by ayumihamsaki** [comment]
## Summary of fixes

1. HTML table elements

2. Add missing double quotes

3. Escape characters

**Comment by w20k** [comment]
@ayumihamsaki few notes:

1. It think it's ment to be width="100", just a misstype ;)  - `$output[] = '<th colspan="3" width="100" style="'.$this->getHeaderCss().'">'; `
2. Tbody/Thead was introduce with the release of HTML 3.2 standard, but added only in HTML 4.0  (in 1999). Wasn't that popular before the strike of the HTML5 and era of clean code and strict tags :) Sort of an old school approach. 
3. Could not find examples of tags without double/single quotes, despite the `vendor/symfony/http-kernal/Tests/DataCollector/DumpDataCollectorTest.php` - please don't fix vendor files, and inside a `Bedard\DebugBar` plugin.

**Comment by ayumihamsaki** [comment]
Just gonna go through your points - for my notes and what I plan to do to fix the issues:

> 1. I think it's meant to be `width="100"`, just a misstype ;) - `$output[] = '<th colspan="3" width="100" style="'.$this->getHeaderCss().'">'; `

I think you are right, **I will delete it out**. The Widget width seems to be adjustable and when I tested it with these two things:

### Test 1

```twig
{{ dump() }}
```

We get the following width results:

![oct-1](https://user-images.githubusercontent.com/17784082/61135164-0289c880-a4b9-11e9-96ce-14b91dc46b9c.png)

### Test 2

```twig
{{ dump(alternateHrefLangElements) }}
```

We get the following width results:

![oct-2](https://user-images.githubusercontent.com/17784082/61135351-52688f80-a4b9-11e9-91a2-bfe316088cfc.png)

### Conclusion

We get different widths so **best not to add a fixed width**.

Link: https://octobercms.com/docs/markup/function-dump

> 2. Tbody/Thead was introduce with the release of HTML 3.2 standard, but added only in HTML 4.0 (in 1999). Wasn't that popular before the strike of the HTML5 and era of clean code and strict tags :) Sort of an old school approach.

Interesting, going to add the `<thead>`, `</thead>`, `<tbody>` and `</tbody>` into the code. With HTML5 it's all about telling machines about **Semantic** values, for example:

### Example 1

For HTML layout code in HTML5 we use:

```html
<header>
<main>
<footer>
```

### Example 2

For HTML table code in HTML5 we use:

```html
<thead>
<tbody>
<tfoot>
```

### Conclusion

An interesting thing I learnt yesterday, all web pages are required now to have the following three things:

- `lang` in `html` e.g. `<html lang="en">`

- `main` area selected e.g. `<main role="main">`

- `h1` main title e.g. `<h1>...</h1>`

These three things are now required for every web page to allow accessibility. My point is that everything is moving towards semantic features more and more. So it's good practises to add these things.

So going to add the `<thead>`, `</thead>`, `<tbody>` and `</tbody>` into the code. 

> 3. Could not find examples of tags without double/single quotes, despite the vendor/symfony/http-kernal/Tests/DataCollector/DumpDataCollectorTest.php - please don't fix vendor files, and inside a Bedard\DebugBar plugin.

This is the hard one. The first thing I think of, is that the vendor files have a major bug and the test file doesn't work correctly!

So let's try this method, steps to repeat errors:

### Step 1

Create this test page.

![oct-3](https://user-images.githubusercontent.com/17784082/61136189-0880a900-a4bb-11e9-86de-f05e782335cd.png)

### Step 2

We get the following results.

![oct-4](https://user-images.githubusercontent.com/17784082/61136237-28b06800-a4bb-11e9-8773-2d464b1d72e1.png)

### Step 3

Go to the source code, in this example I am using Firefox Nightly, we see the following source code:

![oct-5](https://user-images.githubusercontent.com/17784082/61136435-8e9cef80-a4bb-11e9-821c-d3042ee92cf0.png)

We also get:

![oct-6](https://user-images.githubusercontent.com/17784082/61136751-0d922800-a4bc-11e9-8c59-463f75e9f7e4.png)

### Conclusion

We need to update this vendor file and/or create an issue with that vendor repo to fix the double quote and escaping issue.

## Final words

I'm pretty sure this is all basic info to you guys, I just wrote it anyway for future reference. Let me know ideas how to fix this vendor package seems highly buggy to me.

**Comment by ayumihamsaki** [comment]
Thinking of doing two separate PR's for this issue:

1. Fix the styling HTML issues with the widget.

2. Update the vendor file(s) (I don't know what vendor package we are using?) and connect them to this github issue for updating: https://github.com/octobercms/october/issues/3867
