### ISSUE TITLE
Alert twice when csrftoken invalid in backend

### ISSUE THREAD

**Issue by wenlong-date** [octobercms/october#4451]
- OctoberCMS Build: 456
- PHP Version: 7.2
- Database Engine: 5.5
- Plugins Installed: none
- testing base on Chrome(version 74.0.3729.108) and Edge

### Description:
In backend ,when page csrf token expired, the invalid_token info will alert twice

### Steps To Reproduce:
1. open OctoberCMS backend
2. for test the bug ,we comment out the code of file `modules/backend/classes/Controller.php` on line 214 and 217.
![image](https://user-images.githubusercontent.com/20298832/61101499-900aef80-a49c-11e9-92ee-923885c02a7e.png)
3. open one page, the bug will show as below
![double_alert](https://user-images.githubusercontent.com/20298832/61103170-88027e00-a4a3-11e9-89e5-7c9d898aad02.gif)
![edgeAlert](https://user-images.githubusercontent.com/20298832/61103365-43c3ad80-a4a4-11e9-98e1-95bbb4c2717b.png)

### Expected behavior
The browser's alert event will not be triggered.

**Comment by w20k** [comment]
Bug - confirmed.

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/df81ea182b8d759a80cff146cd3982753e17553c
