### ISSUE TITLE
"Call to undefined function October\Rain\Database\Attach\imagecreatefromjpeg()" on line 498 of /var/www/html/vendor/october/rain/src/Database/Attach/Resizer.php

### ISSUE THREAD

**Issue by rodrigosaraiva** [octobercms/october#4456]
- OctoberCMS Build: 455 
- PHP Version: 7.3
- Database Engine: MariaDB
- Plugins Installed: 

- Frozendo.PagePreview	1.2.1
- Indikator.Backend	1.6.9
- OFFLINE.SiteSearch	1.3.22
- PanaKour.Backup	1.0.9	
- RainLab.Builder	1.0.25	
- ToughDeveloper.ImageResizer	1.3.6	
- Martin.Forms	1.4.14	
- Romanov.ClearCacheWidget	1.3.0
- October.Drivers	1.1.2	
- Guc.Melkan	1.0.18
- RainLab.Blog	1.3.3
- RainLab.BlogVideo	1.1.2	
- Hariadi.Share	1.1.0
- Code200.Eucookielawmadness	1.0.2

### Description:
Using the resizer plugin, when you click over a image at media this error pops:
"Call to undefined function October\Rain\Database\Attach\imagecreatefromjpeg()" on line 498 of /var/www/html/vendor/october/rain/src/Database/Attach/Resizer.php

### Steps To Reproduce:
Click on a media using the media management.

**Comment by Rike-cz** [comment]
It's more about your PHP setting than about OctoberCMS. See: https://stackoverflow.com/questions/13338339/imagecreatefromjpeg-and-similar-functions-are-not-working-in-php

**Comment by rodrigosaraiva** [comment]
I don't think so.
![Screenshot from 2019-07-16 16-16-18](https://user-images.githubusercontent.com/5757716/61306872-303a7e80-a7e5-11e9-88da-8aa510f8c8c3.png)

**Comment by rodrigosaraiva** [comment]
I don't think so. I have the GD library, docker packages, and PHP configuration ok.
![Screenshot from 2019-07-16 16-22-11](https://user-images.githubusercontent.com/5757716/61307347-13eb1180-a7e6-11e9-80c0-ca152d9db250.png)
![Screenshot from 2019-07-16 16-21-53](https://user-images.githubusercontent.com/5757716/61307348-13eb1180-a7e6-11e9-92e0-f0e52a591da3.png)

**Comment by bennothommo** [comment]
@rodrigosaraiva You have not got JPEG support installed with your GD extension. You need to build the extension with an attached JPEG library.
