### ISSUE TITLE
October shows the :url? webpage

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4458]
Take the following example:

```html
https://www.example/widgets/:url?
```

Which gives me the following etc.

```html
https://www.example/widgets/blue
https://www.example/widgets/red
https://www.example/widgets/green
etc.
```

The trouble is when you put the following in the browser address bar is actually shows that junk web page:

```html
https://www.example/widgets/:url?
```

This is no good for Search engine crawler bots that will index this junk web page.

Can't it route to a 404 error page by default.

**Comment by Samuell1** [comment]
What you mean junk web page? Hope you dont running production website with debug enabled.

**Comment by ayumihamsaki** [comment]
@Samuell1 Thanks for your comment, I double checked my config files, it was because my enviroment was set to `development` instead of `production`.

Gonna close this issue.
