### ISSUE TITLE
Dev tagged as stable

### ISSUE THREAD

**Issue by acasar** [octobercms/october#4465]
Release v1.0.457 was tagged on a dev branch, pointing to commit https://github.com/octobercms/october/commit/a59d3b83ebeba501e092995be033943e9cfdcb21

Seems like that's a mistake? Shouldn't tagged releases always point to master?

**Comment by LukeTowers** [comment]
@acasar that is intentional. If you would like to use Composer and only receive builds marked as stable then please use https://github.com/octoberrain/meta/blob/master/build-process.md#stable-composer-usage as your OctoberCMS requirements.

**Comment by acasar** [comment]
Thanks for clarification 👍

**Comment by LukeTowers** [comment]
@acasar no problem, I documented the process so that in the future it'll be more transparent to the users. Let me know if you have any other questions!
