### ISSUE TITLE
Ajax component in snippet not working

### ISSUE THREAD

**Issue by PrestaSafe** [octobercms/october#4467]
- OctoberCMS Build: 455 
- PHP Version: 7.2
- Database Engine: MariaDB 
- Plugins Installed: RainLab.Builder 1pilot RainLab.pages

### Description:
Hi, i think i've found a mistake with partial inside a snippet. 

I've made a partial, inside this partial i've put a component. 
This partial is a snippet. 

If i put this snippet  inside a page (RainLab.Pages)
my component is displayed, but the ajax not working. 

I've tried to put prefix on it, but still not working. 
It's working well inside a page: 

### Steps To Reproduce:
Partial code: 
```twig
<!-- Left Content -->
        	<div class="col-md-9">
                <div class="pastobit-list">	

                    {{ form_ajax('AvisDeces::onSearch') }}
                        <input type="text" name="search" class="" placeholder="Rechercher par nom et/ou prénom">
                        <p></p>
                        <button type="submit" class="default-button">Rechercher</button>
                    {{form_close()}}
                <h2 id="h2_deces_en_cours" class="main-heading marbot20">Avis de deces en cours</h2>
                <br>
            
                {% component 'AvisDeces' %}
            </div>
        </div>
```

Screenshot of my partial CMS page: 
![Capture d’écran 2019-07-23 à 20 17 46](https://user-images.githubusercontent.com/4788787/61736744-0c4bdf80-ad87-11e9-994b-ad741f9cc896.png)

Inside the CMS Page, it's working fine. 

Now, inside a page (RainLab.Pages plugin)

![Capture d’écran 2019-07-23 à 20 19 33](https://user-images.githubusercontent.com/4788787/61736812-369d9d00-ad87-11e9-878f-8af6097c41a3.png)

My request not working: 

![Capture d’écran 2019-07-23 à 20 20 22](https://user-images.githubusercontent.com/4788787/61736863-52a13e80-ad87-11e9-996b-484766722630.png)

Thanks to you !

**Comment by alxy** [comment]
Snippets, which is a sepcial kind of a partial, do not support AJAX handlers. This is documented [here](https://octobercms.com/docs/cms/partials#life-cycle-limitations). Please note:
> In general, component usage in partials is designed for basic components that render simple markup without much processing, such as a Like or Tweet button.

If you need more flexibility, consider registering a[ component as snippet](https://github.com/rainlab/pages-plugin#snippets-created-from-components). That should allow you to define ajax handlers.

**Comment by PrestaSafe** [comment]
Thanks for this answers. 
I've registered a page snippet an modify my component view. It's now working.
