### ISSUE TITLE
Nestedform and Datatable field types cant be Translated

### ISSUE THREAD

**Issue by FirestarterUA** [octobercms/october#4468]
Hi.
I have a two database(text type) fields in filds.yaml: 
```
equipment:
        type: datatable
```

and

```
stages:
        type: nestedform
```

in my model:

```
protected $jsonable = ['features', 'videos', 'equipment', 'stages'];
public $implement = ['@RainLab.Translate.Behaviors.TranslatableModel'];
public $translatable = ['title', 'feature', 'features', 'equipment', 'stages'];
```

Any other type work as expected (can be transalted), **but datatable and nestedform does not**.

**Comment by alxy** [comment]
This issue concerns the [Translate plugin](https://github.com/rainlab/translate-plugin), not the core. However, you are right. These complex and very rarely used FormWidgets are not supported, as you can easily [check here](https://github.com/rainlab/translate-plugin/tree/master/formwidgets). Go ahead and implement these if you need them ;)
