### ISSUE TITLE
Visual glitches while navigating backend forms with keyboard

### ISSUE THREAD

**Issue by Eoler** [octobercms/october#4473]
- OctoberCMS Build: 457
- PHP Version: 7.2

### Description:
Fantastic work for keyboard users in #4454 but there are visual glitches in certain form widgets:
- switch
- record finder

### Steps To Reproduce:
Just tab around the form with switches and record finder:
![OctoCMS-form-with-sidebar](https://user-images.githubusercontent.com/680032/61879328-1db1fa80-aef3-11e9-98bd-2bfa645c7032.gif)

**Comment by LukeTowers** [comment]
@ayumihamsaki could you look at this and make a PR that we could include in 458? @Eoler or perhaps you could make a PR to fix it?

**Comment by ayumihamsaki** [comment]
@Eoler @LukeTowers 

Will investigate this further.

I understand the '**switch**' issue, but what do you mean by '**record finder**'

**Comment by LukeTowers** [comment]
@ayumihamsaki it's the bottom two fields, selecting them makes them expand vertically and moves the popup triggering button from the right to the left

**Comment by ayumihamsaki** [comment]
Issue with switch, below is working solution:

```html
<div class="form-group  switch-field span-right   " data-field-name="something" id="Form-field-Something-group">
    <div class="field-switch">
    <label>Example</label>
    <p class="help-block">bla bla</p>
</div>
<input type="hidden" name="Index[Test]" value="0">
    <label class="custom-switch">
        <input tabindex="-1" type="checkbox" id="Form-field-Banner-settingsBorderBtn" name="Banner[settingsBorderBtn]" value="1" checked="checked" class="">
        <span tabindex="0" class="">
            <span>On</span>
            <span>Off</span>
        </span>
        <a class="slide-button"></a>
    </label>
</div>
```

**Comment by ayumihamsaki** [comment]
I think the styling of the button on the record finder is not right, see here:

![image](https://user-images.githubusercontent.com/17784082/61899132-b60ba780-af12-11e9-893f-4ae924b0ab97.png)

This try and fix that.

---

Also I might as well add my other commit here as well, as I found another bad coding error in October, see screenshot:

![image](https://user-images.githubusercontent.com/17784082/61899416-4e099100-af13-11e9-8866-33ea79eef3ef.png)

**Comment by ayumihamsaki** [comment]
Anyway fixed, see results:

![image](https://user-images.githubusercontent.com/17784082/61899785-236c0800-af14-11e9-9d48-8789acd5e90f.png)

**Comment by daftspunk** [comment]
I have been unable to replicate this in the latest `develop` branch. I regret to inform that a lot of these changes were poorly implemented and had to be rolled back. The contributor of these features will need to make another attempt, perhaps in a more organised fashion where it is possible to review each enhancement independently or propose the changes incrementally

**Comment by Eoler** [comment]
> I have been unable to replicate this in the latest `develop` branch. 

It was reverted in: https://github.com/octobercms/october/commit/199407f1a05da2bf4f1f7df8bb03b92cde34bd89

> I regret to inform that a lot of these changes were poorly implemented and had to be rolled back. The contributor of these features will need to make another attempt, perhaps in a more organised fashion where it is possible to review each enhancement independently or propose the changes incrementally

Changes were mostly working but repositories/author(s) misteriously vanished. 
I have one forked OctoberCMS installation where customer manages ~300K records and backend keyboard entry is critical for their success. Guess I'll try to reimplement it with a plugin + form behavior, already handling focusing first form field with injected JS...

**Comment by LukeTowers** [comment]
@Eoler @ayumi-cloud we're open to having those enhancements in core, we had to revert them because they weren't stable enough for 458. I'd love to see them resubmitted so that we can get it added into a future build after some more in depth testing.
