### ISSUE TITLE
Method to overwrite methods of a component of an external plugin?

### ISSUE THREAD

**Issue by zimudec** [octobercms/october#4476]
Hi, how are you?

What is the best practice for overwriting methods of a component of an external plugin?

I need to overwrite all the functionality of the "onRun" method of the component.

It occurred to me to create my own component that inherits from that component, and to overwrite the onRun method in the new class, but I realized that the "onRun" method of the father also runs automatically, without telling it by code "parent :: onRun ( ) ". This seems to me to be out of the standard.

Now my question. What is the correct way to overwrite methods of an external component?

This information does not exist on the internet

**Comment by seanthepottingshed** [comment]
@zimudec this would be more suited for discussion within the OctoberCMS Slack channel
