### ISSUE TITLE
InvalidArgumentException: No hint path defined for plugin name

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4490]
This took me several hours to go through the stack trace to find the solution and the problem.

Basically the problem is like this:

1. You install a plugin (Acme.Something) - in this case it installed some mail templates into the system.

2. You install a different plugin - in this case (form builder plugin).

3. I delete the first plugin (Acme.Something) out of October CMS.

4. I open the form builder plugin that loads the list of email templates.

5. The error appears:

```
InvalidArgumentException: No hint path defined for [Acme.Something]
```

The error is caused because the mail templates for (Acme.Something) are still in the MySQL database even though I have deleted the plugin.

I had no choice but to open MySQL and delete the mail templates out of the location: `system_mail_templates`

## A possible fix

The obvious solution would be for October CMS to do the following:

- **When you delete a plugin, it also deletes that plugins mail templates at the same time!**

I'm not an expert in that section, so I leave it to the admins feedback.

**Comment by bennothommo** [comment]
@ayumihamsaki This looks to be an issue with the Form Builder plugin (I'm presuming this a third-party one, if not, please let me know). We would need to know which method is being used to retrieve the email templates before we can investigate the bug further. Please re-open this if you can source more info for us.

**Comment by ayumihamsaki** [comment]
ok will investigate further.
