### ISSUE TITLE
Hide plugins in the top navigation that only contain sidemenu

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4491]
I feel like I'm having one of those days where errors are following me about.

I installed two plugins from the marketplace.

1st plugin (main plugin) can be found here: https://octobercms.com/plugin/jorgeandrade-subscribe

2nd plugin (plugin extras) can be found here: https://octobercms.com/plugin/jorgeandrade-subscribeplus

When installing both the plugins I get the following error in the top navigation, see screenshot:

![nobe-end](https://user-images.githubusercontent.com/17784082/61997749-57733480-b09e-11e9-8d50-db3c3a74cd7e.png)

Looking at their authors code we have the following:

Plugin 1:

```php
    public function registerNavigation()
    {
        return [
            'subscribe' => [
                'label' => 'Subscribers',
                'url' => \Backend::url('jorgeandrade/subscribe/subscribers'),
                'icon' => 'icon-rss',
                'permissions' => ['jorgeandrade.subscribe.*'],
                'order' => 500,

                'sideMenu' => [
                    'subscribers' => [
                        'label' => 'Subscribers',
                        'icon' => 'icon-rss',
                        'url' => \Backend::url('jorgeandrade/subscribe/subscribers'),
                        'permissions' => ['jorgeandrade.subscribe.access_subscribers'],
                    ],
                ],

            ],
        ];
    }
```

Plugin 2:

```php
    public function registerNavigation()
    {
        return [
            'subscribeplus' => [
                'sideMenu' => [
                    'subscribers' => [
                        'label'       => 'Subscribers',
                        'icon'        => 'icon-rss',
                        'url'         => \Backend::url('jorgeandrade/subscribe/subscribers'),
                        'permissions' => ['jorgeandrade.subscribe.access_subscribers'],
                    ],
                    'lists' => [
                        'label'       => 'Subscribers Lists',
                        'icon'        => 'icon-list',
                        'url'         => \Backend::url('jorgeandrade/subscribeplus/lists'),
                        'permissions' => ['jorgeandrade.subscribeplus.lists'],
                    ],
                    'campaigns' => [
                        'label'       => 'Campaigns',
                        'icon'        => 'icon-newspaper-o',
                        'url'         => \Backend::url('jorgeandrade/subscribeplus/campaigns'),
                        'permissions' => ['jorgeandrade.subscribeplus.campaigns'],
                    ],
                    'templates' => [
                        'label'       => 'Templates',
                        'icon'        => 'icon-file-code-o',
                        'url'         => \Backend::url('jorgeandrade/subscribeplus/templates'),
                        'permissions' => ['jorgeandrade.subscribeplus.templates'],
                    ]
                ]

            ]
        ];
    }
```

Ripping out the HTML code from October we have this:

```html
<li class=" svg-icon-container svg-active-effects" role="listitem">
    <a href="">
        <span class="nav-icon">
            <i class=" "></i>
        </span>
        <span class="nav-label">
        </span>
    </a>
    <span class="counter empty" data-menu-id="subscribeplus">
    </span>
</li>
```

We can see the issue is with the `<a href="">`

This got me thinking and I came up with this code:

```html
<script>
$(function() {
    $('.mainmenu-nav a').each(function(){    
        if (!$(this).attr('href')) {
            $(this).parent().css("display", "none");
        }
    });
});
</script>
```

The above javascript will hide any blank plugins in the top navigation menu, helping to keep the top navigation cleaner.

**Comment by bennothommo** [comment]
@ayumihamsaki The original scenario you specified with the two plugins has a faulty implementation of the `registerNavigation` event in the second plugin. I believe plugins currently must specify a top-level navigation item when using this method, or alternatively, they can extend via the `backend.menu.extendItems` event to add navigation items for other plugins.

However, we should have some validation for the main menu items if they are missing required attributes. This should be done in the PHP side - the [`registerMenuItems`](https://github.com/octobercms/october/blob/d8cd45163d9cd6f3a43fa0d5c3b334f284174f09/modules/backend/classes/NavigationManager.php#L192) method in `Backend\Classes\NavigationManager` handles the loading of main menu items from plugins. Above that, the required attributes are specified - so if any of these are missing, we should be either logging or throwing an error.

**Comment by ayumihamsaki** [comment]
Interesting, thanks.

**Comment by bennothommo** [comment]
Fixed by https://github.com/octobercms/october/pull/4497.
