### ISSUE TITLE
Please can you remove this plugin or contact the owner

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4493]
This plugin has killed my backend and all I see is this error message when I try to login:

![dead](https://user-images.githubusercontent.com/17784082/61999139-d5413b00-b0b2-11e9-9353-6fa9711c3594.png)

The plugin web page in october is found here: https://octobercms.com/plugin/jorgeandrade-subscribeplus

The reason I am writing an issue here is because of the following:

1. **Product support** link: https://github.com/andradedev/Subscribe-Form-Plus/issues

2. **Public repository** link: https://github.com/andradedev/Subscribe-Form-Plus

Both are 404.

No way to sort this out my side, so I need the admins to step and remove it or contact the owner thanks.

**Comment by ayumihamsaki** [comment]
Sorry can you remove all his plugins they are all dead 404 links, his profile is here: https://octobercms.com/author/JorgeAndrade

You can check all of his plugins to confirm.

**Comment by bennothommo** [comment]
@ayumihamsaki Try emailing hello@octobercms.com with these details. That's generally the better place for marketplace enquiries.

**Comment by ayumihamsaki** [comment]
@bennothommo thanks, trouble is I never get a reply, when I email that address, likewise when I email luke's email as well, but I will give it a go anyway. 😄

**Comment by ayumihamsaki** [comment]
@bennothommo Is it possible for you to change this screenshot, see here:

![email](https://user-images.githubusercontent.com/17784082/62010535-0a599600-b164-11e9-8f08-bba0f11a6418.png)

What I'm suggesting is to remove the website link and replace it with the email address of `hello@octobercms.com`

**Comment by bennothommo** [comment]
@ayumihamsaki that's probably a question for @LukeTowers or @daftspunk

**Comment by w20k** [comment]
@bennothommo I think it's a part of this template: https://github.com/octobercms/october/blob/master/.github/ISSUE_TEMPLATE/2_SUPPORT_QUESTION.md
But, yeah, I agree better to ask @LukeTowers if he agrees.

**Comment by ayumihamsaki** [comment]
Cool thanks, will wait for Luke's decision. 👀

**Comment by LukeTowers** [comment]
@ayumihamsaki I would recommend just adding another issue template for "Marketplace Support" that recommends emailing hello@octobercms.com. Support in general for OctoberCMS can be found at that link so we'll keep that option as it is right now but another option could definitely be added.

**Comment by ayumihamsaki** [comment]
@LukeTowers I put it in this pr (I can't create new branches for some strange reason right now?)

https://github.com/octobercms/october/pull/4494/commits/66b774b424e3760910c616db6b4388052e4067b0

**Comment by bennothommo** [comment]
Link added: https://github.com/octobercms/october/commit/216a54fca4fd02d3fb75a2152f4c583261506b94

**Comment by ayumihamsaki** [comment]
Thanks
