### ISSUE TITLE
Backend richeditor is not loading plugin in 455 build.

### ISSUE THREAD

**Issue by zakir1929** [octobercms/october#4495]
- OctoberCMS Build: ### 455
- PHP Version: 7.1
- Database Engine: Mysql

### Description:
I have added a new toolbar button in backend richeditor but when i click on that button a callback function runs and there I added my plugin code(plugin of richeditor like a insertLink) to run but it's not working. I checked the console and it shows undefined for plugin object.

The code is not working in 455 build while it's working perfectly in 454 build so definitely this issue is in new version

	+function ($) { "use strict";

		$(document).on('render',function(){

		    if ($.FroalaEditor) {
		  
			  	$.FroalaEditor.PLUGINS.myPlugin = function (editor) {
				    function publicMethod () {
				    	alert("my plugin worked");
				    }

				    function _init () {

				    }
				    return {
				      _init: _init,
				      publicMethod: publicMethod
				    }
				}

			    $.FroalaEditor.DefineIcon('inserttwitter', {
			        NAME: 'twitter'
			    });
				
			    $.FroalaEditor.RegisterCommand('inserttwitter', {
			        title: 'Insert inserttwitter',
			        undo: false,
			        focus: true,
			        refreshOnCallback: false,
			        popup: true,
			        plugin: 'myPlugin',
			        callback: function() {
			        	this.myPlugin.publicMethod();
			        },
			    })
			    $.oc.richEditorButtons.push('inserttwitter');

		    }  
		});

	}(window.jQuery);

**Comment by w20k** [comment]
@zakir1929 it was fixed in this commit by @mjauvin https://github.com/octobercms/october/commit/30f4d4c5af180efb21a6e53f023b3b01b76fa891

**Comment by zakir1929** [comment]
I am not able to update from 455 to 457 build. How i can do that.

**Comment by zakir1929** [comment]
yep it is solved in 457 Thanks
