### ISSUE TITLE
Builder plugin has a display error in firefox

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4507]
When running tests on some other pr's I came across this small error, this github issue just shows the error for future ref and will connect a pr for it.

The issue seems to be in firefox only - chrome works fine.

### Problem

![er1](https://user-images.githubusercontent.com/17784082/62283887-711fcd80-b44a-11e9-9b57-b4dbf3fd13a6.png)

### Solution

![er2](https://user-images.githubusercontent.com/17784082/62283905-79780880-b44a-11e9-8a47-8e020f866d75.png)

### Error

There is a single line of CSS code missing in the files - pr just adds the missing code back into october. May result in error with other plugins as well.

**Comment by bennothommo** [comment]
Fixed in 8219f19e8d902670cddcad3dfc6ef28516418cc0.
