### ISSUE TITLE
Top Navigation and sidebar issues

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4510]
This github issue outlines some of the bugs in the top navigation and sidebar. I have a pr done for this issue, but it's only 50% done so far and I needing to finish it off and further tests things.

For now, I want to create this as a future ref for all the fixes done in the pr.

## Bugs

1. Top navigation switched to flexbox, fixed the sizes issues and right account-avatar image sizing.

![61581579-187e3580-ab18-11e9-8935-8254fb56ace7](https://user-images.githubusercontent.com/17784082/62288390-31f67a00-b454-11e9-98dd-21d194ef644d.png)

2. CMS page sidebar, has down sizing issues, web standards say to use font-size 16px or greater, October is using `font-size 11px` on mobile devices with a `width of 80px`. This will be removed and set to have `font-size 16px` and `width 120px`, so people on mobile devices can read the sidebar.

![61581565-ed93e180-ab17-11e9-8121-ca476e8275df](https://user-images.githubusercontent.com/17784082/62288545-8dc10300-b454-11e9-8b15-8ca5ae1bbc22.png)

3. CMS Page Pin button has a gap at top. On large screens there is a `2px` gap with a top nav fixed at `60px` and on smaller screens there is a `17px` gap on `45px` with a top nav fixed at 45px - github issue: https://github.com/octobercms/october/issues/4005

![wwww](https://user-images.githubusercontent.com/17784082/61581589-4cf1f180-ab18-11e9-8f64-8fe816de78ff.png)

4. Has a stupid height limit, that doesn't work on all settings:

![vsefverf](https://user-images.githubusercontent.com/17784082/62292626-be0d9f00-b45e-11e9-9339-427384a55af6.png)

5. Has a gap error:

![vfdgvfdgvfdgvdfrgbvdfgv](https://user-images.githubusercontent.com/17784082/62294349-a46e5680-b462-11e9-8f35-b11a83d3222e.png)

6. There are various other small CSS issues going on which I will try to correct in the pr.

**Comment by ayumihamsaki** [comment]
@LukeTowers 

Avatar image sizes are now fixed to the following sizes: 45px, 60px and 78px.

Want to mention something like min-size for account avatar's should be at least 78px in size and in a square format.

Not sure where to add this info into the doc's ?

**Comment by ayumihamsaki** [comment]
This github issue is now finished see the connected PR.
