### ISSUE TITLE
Improve mobile responsiveness of pages with sidebar elements (Builder plugin, CMS Pages)

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4515]
While working on a pr, I have found the following big bug.

**You can't use the CMS page at all on screensizes below 768px.**

There is a CSS setup of:

```css
@media (max-width: 768px)
.layout .hide-on-small {
    display: none;
}
```

This then totally hides the sidebar from the screen rendering the CMS page totally useless.

![a1](https://user-images.githubusercontent.com/17784082/62416815-8ad33780-b639-11e9-9f59-97421cc59619.png)

and here

![a2](https://user-images.githubusercontent.com/17784082/62416817-90308200-b639-11e9-8dad-8871cae2e413.png)

---

This issue is to document this **major issue**! I'm trying to build a solution into my dragbar pr - I'm working on at the moment.

p.s. please ignore the grey dragbar line in the screenshots.

**Comment by ayumihamsaki** [comment]
Also builder plugin doesn't work at all under 768px screensizes exactly same problem.

No sidebar at all.

![stupid](https://user-images.githubusercontent.com/17784082/62417317-75173f80-b644-11e9-9121-d72143cb2b7e.png)

**Comment by ayumihamsaki** [comment]
My idea of a solution:

![idea](https://user-images.githubusercontent.com/17784082/62418772-a0605580-b669-11e9-9390-b01e02cb3572.png)

But need a discussion to see what people think.

**Comment by bennothommo** [comment]
@ayumihamsaki I can't say I'm a fan of that. The main issue, as I [mentioned here](https://github.com/octobercms/october/pull/4516#issuecomment-517967204), is that mobile devices give us only a small viewport to work with. With this in mind, the entire screen should be taken up by the form being viewed, as it's the most important element on the page.

How I would tackle mobile responsiveness for those screens would be:
- Implement some way of the sub-navigation and sidebar elements (such as the page list) being brought out like a "drawer" - off screen until the menu button is pressed, and then shown on the left side. This matches the general idea for mobile apps. Currently, this happens with the main nav, but it's not happening with the sub-nav or sidebar AFAIK.
- Present the actual form across the entire viewport, except for the black bar at the top, as it is in your screenshot just above.

**Comment by ayumihamsaki** [comment]
@bennothommo I agree with your ideas.

Btw, my above image is not totally clear - sorry I drew it at 4am. Maybe this will explain it a bit better:

![62418772-a0605580-b669-11e9-9390-b01e02cb3572](https://user-images.githubusercontent.com/17784082/62423969-17283d80-b6c0-11e9-82f4-d8bcacc8f602.png)

Above: Has a horizontal dragbar to adjust sub-menu size.

and

![img2](https://user-images.githubusercontent.com/17784082/62423979-2a3b0d80-b6c0-11e9-9bf2-54c0c7f393ad.png)

Above: Has a pinbar to hide/show the sub-menu allowing full screen of the code editor.

Hopefully that shows my idea a bit clearer.

**Comment by ayumihamsaki** [comment]
@bennothommo I agree with your ideas.

Btw, my above image is not totally clear - sorry I drew it at 4am. Maybe this will explain it a bit better:

![62418772-a0605580-b669-11e9-9390-b01e02cb3572](https://user-images.githubusercontent.com/17784082/62424031-e98fc400-b6c0-11e9-86c7-f8d2c6e16739.png)

Above: Has a Vertical dragbar to adjust sub-menu size.

and

![img2](https://user-images.githubusercontent.com/17784082/62423979-2a3b0d80-b6c0-11e9-9bf2-54c0c7f393ad.png)

Above: Has a pinbar to hide/show the sub-menu allowing full screen of the code editor.

Hopefully that shows my idea a bit clearer.

**Comment by LukeTowers** [comment]
@ayumihamasaki2019
