### ISSUE TITLE
Update Failed For ZipArchive::extractTo

### ISSUE THREAD

**Issue by martingg88** [octobercms/october#4519]
I still facing the ZipArchive::extractTo Permission denied while doing the upgrading after configured as follows: 

chown -R apache:apache {{project path}}

chmod -R 777 {{project path}}

Any idea how to solve this issue?

**Comment by w20k** [comment]
I think it's mostly `www-data` user not `apache`, but depends on the server configuration I guess.

**Comment by martingg88** [comment]
Thanks. I think the issue related to Centos Selinux Policy.
