### ISSUE TITLE
LessCompiler variables with color

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#4523]
- OctoberCMS Build: 457 
- PHP Version: 7.2.19

### Description:
![CleanShot 2019-08-05 at 21 30 52](https://user-images.githubusercontent.com/6506510/62490084-c3ede200-b7c8-11e9-8a3b-a19a5ea40141.png)

Is converted by the LessCompiler to the following:

![CleanShot 2019-08-05 at 21 31 00](https://user-images.githubusercontent.com/6506510/62490166-f3045380-b7c8-11e9-8567-ba25d114ada6.png)

### Steps To Reproduce:
Create a theme with options to add a font. Use the variable in your less file.

**Comment by SebastiaanKloos** [comment]
OctoberCMS uses the oyejorge/less.php library. I found out the core of the issue. I've created a new issues here https://github.com/oyejorge/less.php/issues/376. I will report back when fixed.

**Comment by Samuell1** [comment]
@SebastiaanKloos https://github.com/oyejorge/less.php/issues/371

**Comment by LukeTowers** [comment]
There's also https://github.com/leafo/lessphp, which I think Assetic uses. As far as I was aware that was the library we were using, but I guess not?

**Comment by LukeTowers** [comment]
Plus October will be taking over Assetic FYI

**Comment by LukeTowers** [comment]
@jaxwilko can you take a look at this? How can we fix this with our Assetic takeover?

**Comment by JaxWilko** [comment]
@LukeTowers I shall take a look and see what's possible

**Comment by LukeTowers** [comment]
@SebastiaanKloos can you verify that this is still an issue in the Laravel 6 branch of October?

**Comment by SebastiaanKloos** [comment]
@LukeTowers I'll add it to my tasklist for this week

**Comment by SebastiaanKloos** [comment]
@LukeTowers Nope still the same:

```
li {
  font-family: #ff0000 Hat Display;
}
```

**Comment by bennothommo** [comment]
@SebastiaanKloos how have you defined the asset variable in the LESS file?

**Comment by multiwebinc** [comment]
Just FYI, the [Less.php repo](https://github.com/oyejorge/less.php) has now been archived, and the author recommends Wikimedia's fork:

> Less.php
> This project is no longer being updated. See [Wikimedia's](https://github.com/wikimedia/less.php) repo for a well-maintained fork.

**Comment by LukeTowers** [comment]
@multiwebinc we are using the wikimedia fork in the L6 branch

**Comment by SebastiaanKloos** [comment]
> @SebastiaanKloos how have you defined the asset variable in the LESS file?

‘’’

li {
  font-family: @primary-font;
}

‘’’

**Comment by LukeTowers** [comment]
@SebastiaanKloos FYI, it's ` (a backtick) not ' (a single quote) for code formatting on github.

**Comment by bennothommo** [comment]
@SebastiaanKloos have you tried using one of the escaping functions in LESS? http://lesscss.org/functions/#string-functions

**Comment by SebastiaanKloos** [comment]
> @SebastiaanKloos FYI, it's ` (a backtick) not ' (a single quote) for code formatting on github.

@LukeTowers Yeah I know. Couldn’t find it on my iOS keyboard... 🙈

**Comment by SebastiaanKloos** [comment]
> @SebastiaanKloos have you tried using one of the escaping functions in LESS? http://lesscss.org/functions/#string-functions

I’ll try the escaping functions!

**Comment by SebastiaanKloos** [comment]
Nope didn't work @bennothommo... I think it has to do with it being a variable.

**Comment by LukeTowers** [comment]
@SebastiaanKloos did you submit an issue to the wikimedia Less library that the Laravel 6 branch is now using?

**Comment by SebastiaanKloos** [comment]
@LukeTowers Not yet. I will submit an issue to the wikimedia Less library soon.

**Comment by daftspunk** [comment]
Yes, please take this up with the https://github.com/wikimedia/less.php team as it is nothing to do with October CMS. You'll need to ask for some way to escape the "color name to hex" conversion. In the meantime, you could always just rename your font. Hope this helps!
