### ISSUE TITLE
When you search in the CMS page it forces you to save the file

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4532]
I feel this is an error and it's quite annoying!

Steps to repeat.

1. Go to the CMS page in the backend.
2. Open any file to load it into the code editor screen.
3. On PC click on the code editor and then press crtl + f to open the search box.
4. Do a search - type anything and press enter.
5. You will now see on the left hand side of the screen the file is asking to be saved before you close the file - yet you have done no modifications to the file in the code editor.

This is annoying and results in a pointless box getting displayed for no reason saying: "Close the tab? Unsaved changes will be lost."

Any suggestions how to stop this? I would like to do a search and not be forced to save the file with no modifications done to it.

See gif example:

![ezgif-2-e25477f8087d](https://user-images.githubusercontent.com/17784082/62793690-129dc380-baca-11e9-82da-b3d074182877.gif)

**Comment by ayumihamsaki** [comment]
As per ace:

> Hi, this doesn't look like an issue related to code in ace, most likely octobercms uses keypress to detect change instead of using change event emitted by ace.

**Comment by LukeTowers** [comment]
Duplicate of #946. Please verify that you have https://github.com/octobercms/october/commit/daf3a5c7cdccfa4302ac829144df59c2693be680 applied in your local copy, this should be fixed as of a while ago.

**Comment by ayumihamsaki** [comment]
@LukeTowers 

I just tested that commit and checked I have that commit installed to the exact character and still getting this issue - so that commit doesn't fix this problem.

**Comment by LukeTowers** [comment]
@ayumihamsaki Feel free to see if you can come up with a fix for this. @w20k could you also take a look?

**Comment by w20k** [comment]
@LukeTowers yep, can't reproduce with the latest build.

@ayumihamsaki 
Gif:
![Aug-10-2019 22-08-56](https://user-images.githubusercontent.com/1053320/62825892-88358c80-bbbb-11e9-8382-8a1a2087a8e1.gif)

**Comment by ayumihamsaki** [comment]
Done a fresh install of my localhost testing enviroment and I can confirm same as w20k - (finally I can get same result as you guys) lol.

**Comment by ayumihamsaki** [comment]
Tested on build V455 for ref.
