### ISSUE TITLE
Active theme is not found

### ISSUE THREAD

**Issue by pavelmgn** [octobercms/october#4540]
Hello. Every 15 seconds the topic becomes inactive.

![theme1](https://user-images.githubusercontent.com/8817759/62847449-d481e900-bcef-11e9-8a02-9bcc044ecae8.jpg)
![theme2](https://user-images.githubusercontent.com/8817759/62847451-d64bac80-bcef-11e9-8da2-160e9aac090b.jpg)
![theme3](https://user-images.githubusercontent.com/8817759/62847453-d8157000-bcef-11e9-97bb-669a4c8344dc.jpg)
![theme4](https://user-images.githubusercontent.com/8817759/62847455-d9469d00-bcef-11e9-9c4f-3f21500cba79.jpg)
![theme5](https://user-images.githubusercontent.com/8817759/62847457-dba8f700-bcef-11e9-9ca2-d3f3cd6d5b35.jpg)

In database record is set. Every time you have to press activate in the backend. Theme one.

**Comment by bennothommo** [comment]
@pavelmgn Please provide more information for us to determine what is happening here.

- Which build of October CMS are you running?
- Which plugins do you have installed on your October CMS instance?
- What steps have you been taking in order to encounter the error?

**Comment by pavelmgn** [comment]
Sorry. @bennothommo This problem was related to the memcached. 2 octobercms were found, and if, for some reason, we activated the theme at 1 cms, then on the second it became inactive. and vice versa.

**Comment by bennothommo** [comment]
@pavelmgn Thanks for letting us know - glad you got it fixed. Make sure to have a different prefix for your cache on each install of a system - that will avoid the issue in the future ;)
