### ISSUE TITLE
Add the ace editor code select feature to the CMS page

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4545]
I'm probably going to get in trouble for not asking about this in Slack first. But I'm really sure this is a needed feature and most of the code should be set inside October already - so it begs the question why it's not turned on in the first place?

Take this screenshot:

![image](https://user-images.githubusercontent.com/17784082/62968414-e43e2200-be02-11e9-8c5b-d9c3a011bea7.png)

It has javascript in a partial - there is a plugin that allows me to write javascript and other languages direct into October.

The issue I have is that the code editor is displaying the javascript as plain white.

Ace editor allows you to change the code, right now it's hard-coded and set to `data-language="twig"` can we just add an option an the top of the code to select and change the data-language.

In the screenshot I have drawn a rough idea.

I'm really sure this can't be too hard to add in as most of the code is there already.

Info: https://stackoverflow.com/questions/9154183/cant-set-language-mode-for-ace-editor

---

### File locations

https://github.com/octobercms/october/blob/develop/modules/backend/formwidgets/codeeditor/assets/js/codeeditor.js

https://github.com/octobercms/october/blob/develop/modules/backend/controllers/preferences/_field_editor_preview.htm

https://github.com/octobercms/october/blob/develop/modules/backend/formwidgets/codeeditor/partials/_codeeditor.htm

---

List October contains already:

https://github.com/octobercms/october/blob/0f0cd9e32f210da48944b58f82f6ae8758f96538/modules/backend/formwidgets/codeeditor/assets/js/codeeditor.js#L420-L430

**Comment by bennothommo** [comment]
@ayumihamsaki I would presume it is locked to Twig because 99% of the time, that is what is being edited, and it was hidden to not confuse casual users. I think a setting to make it available to the user in the **Backend Preferences -> Code Editor** section might be a good idea, if someone wants to provide a PR for it.

**Comment by Samuell1** [comment]
@ayumihamsaki @bennothommo I had idea to remove ace editor and use monaco editor, what vscode is using.

**Comment by SebastiaanKloos** [comment]
> @ayumihamsaki @bennothommo I had idea to remove ace editor and use monaco editor, what vscode is using.

That looks really great. On my mac I use alt + arrow keys all the time. Somehow Ace editor does not support it as my cursor is going up and down like a rollercoaster

**Comment by bennothommo** [comment]
It definitely looks good, but it's also new and in beta, so I'd be wary of sending out to all the October users.

**Comment by ayumihamsaki** [comment]
@LukeTowers @daftspunk 

That editor looks amazing, it says it doesn't work on mobile devices. However, I tested it on an ipad 2 running IOS 9.3.5 and it works fine the only issue I had was the right scrolling you could slide instead you just press the location and it worked. I managed to write code and do everything I needed on the ipad - so it works for mobile devices fine!

With regards to ace editor, @w20k and myself tried to do an update to that editor back in dec 2018 found here: https://github.com/octobercms/october/pull/3951

We had nothing but problems trying to update it and in the end we still didn't find a solution. Ace editor is quite buggy!

With regards to this new editor I think it needs several things to pass:

1. Search function.
2. Full screen mode.
3. License - can October use it?

> I would like to close this issue and open a new issue where people can vote to have this new editor or not?

A side note: All main stream CMS are PWA compatible nowadays. October CMS needs to become PWA compatible. So we need a code editor to work in various modes like:

- PHP/Twig for main.
- JSON for manifest file.
- Javascript for Service worker files.
etc.

**Comment by ayumihamsaki** [comment]
@bennothommo 

> I think a setting to make it available to the user in the Backend Preferences -> Code Editor section might be a good idea, if someone wants to provide a PR for it.

I think that would be quite annoying. For example, I open the first partial and it's HTML code. I open the second partial and it's javascript, I then have to close out of the cms page and go to the **Backend Preferences -> Code Editor** section to set javascript and go back to the cms page to carry on working with the second partial (js file).

That's why I thought of having the dropdown menu above the code editor (on the cms page) so we could change the coding mode **on-the-fly**.

That's my thoughts.

**Comment by Samuell1** [comment]
@ayumihamsaki Monaco editor is used in VSCode and yes it has search.

**Comment by ayumihamsaki** [comment]
+1 I'm really up for using Monaco editor - great find.

**Comment by bennothommo** [comment]
@ayumihamsaki I'm not saying move the Language selector to the user preferences, I'm saying adding a toggle to enable or disable seeing the language selector on the editor.

**Comment by ayumihamsaki** [comment]
@bennothommo sorry my mis-understanding.

**Comment by SaifurRahmanMohsin** [comment]
@bennothommo I’m still wondering if it’s worth adding the setting to enable/disable it. When you said “casual users”, I wondered if non-developers actually use the CMS section i.e. ace editor. It would make better sense to enable it by default in this section but allow developers to disable it within the code editor form widget alone using a yaml setting for it since I think that is where a casual user is more likely to use it.

**Comment by bennothommo** [comment]
@SaifurRahmanMohsin I personally don't think it's needed at all. I believe the editor already detects the file type and uses the appropriate language. In @ayumihamsaki's case, I think it's only coming up as plain-text because they're adding raw JavaScript into a HTML file and not surrounding it with a `<script>` tag, so Ace is assuming its HTML at the moment.

Nevertheless, if it's something that people want, I'm happy to review and accept a PR for it.

**Comment by ayumihamsaki** [comment]
@bennothommo

> I think it's only coming up as plain-text because they're adding raw JavaScript into a HTML file and not surrounding it with a <script> tag, so Ace is assuming it's HTML at the moment.

That's true.

But I also have a JSON file for my manifest and that's pure white - Ace is assuming that's HTML as well.

Personally I'm not a fan of having it off by default, it reminds me of the hamburger menu UX. Hiding menu options is very bad and most people don't click those hidden menu options. That's why you see platforms like Facebook using tabs at the bottom of their app - so the options are not hidden.

However, I'm willing to go along with bennothommo's idea due to the amount of people that probably don't use the CMS editor for more than HTML code.

Though the question could be does adding that dropdown make the area cluttered or not? If not then there is no point in hidding the menu option.

**Comment by bennothommo** [comment]
@ayumihamsaki It's all subjective, at the end of the day. I err on the side of keeping things simple when it comes to the Backend, as that's always been my interpretation of the overall goal of October. I figure since most people who do extensive development on October use an IDE, there's not many people who would benefit from having it there.

**Comment by ayumihamsaki** [comment]
@bennothommo 

>It's all subjective

Yah that's why I leave it up to you to decide.

**Comment by LukeTowers** [comment]
If a setting is added I think I would prefer it gets added to the newly created config/develop.php configuration. @bennothommo what are your thoughts on that?

**Comment by bennothommo** [comment]
@LukeTowers I wasn't sure if it was something that should be pushed on all users, as opposed to allowing say a developer to have access to it, but a client or content writer to not have access to it. Maybe it could be a permission?

**Comment by ayumihamsaki** [comment]
I pictured bennothommo's idea as the same setup as the:

**One setup for developers and one setup for client's with little techie knowledge.**

**Comment by ayumihamsaki** [comment]
Sorry wanted to ask, would it be a good idea to load the ace editor extension mode files `async` as per this stackoverflow comment got me thinking: https://stackoverflow.com/questions/9154183/cant-set-language-mode-for-ace-editor

**Comment by LukeTowers** [comment]
@bennothommo hmm, not sure about that. Permissions aren't really meant to toggle off parts of the interface for cleanlinesses sake alone. I don't see why you'd have a user allowed to edit code but not allowed to change the formatting language for the code editor.

**Comment by ayumihamsaki** [comment]
My updated comment about swtiching from Ace to Monaco:

Upgrading to Monaco will be very, very, very **_difficult_**. You will have to change many files in October and many widgets. Their are many custom ace editor files in October. The change-over will not be easy, you will be looking at roughly 450 - 500 files, needed to be changed or removed. For example you will have to completely re-write the Markdown editor, the Code editor, the Rich editor etc. the list goes on and on. Don't forget that October has many API functions and some of them directly use Ace e.g. the `grow` and `stretch` features I'm currently working on, then you got the layout files and styling that are need to be completely changed, e.g. the code editor on the `cms` page is not the same as the code editor in the `plugin` form area. Finally you got all the custom coding between the `normal` field size and the `fullscreen` modes. Probably closer to 1000 file changes.

We are using Ace version 1.2.6 right now. Looking at Ace version 1.4.5 it's almost the same as Monaco and there are some plugins out there which make ace editor even more like Monaco.

Lastly, backwards compatibility, I was even thinking of having both of them running in October and having an option in the config file to be able to choose which editor you want to use.

**Comment by ayumihamsaki** [comment]
p.s. before statring this issue, probably best to finish off this PR first: [Update Ace Editor from 1.2.6 to 1.4.5 and emmet.js](https://github.com/octobercms/october/pull/4585)

**Comment by Samuell1** [comment]
@ayumihamsaki You dont need to change anything just to make another formwidget called monacoeditor and make editor working from there then make swap. I mean for now will be to best to make ace stable.

**Comment by ayumihamsaki** [comment]
@Samuell1 yah that's a good idea.

**Comment by LukeTowers** [comment]
@ayumihamasaki2019

**Comment by ayumi-cloud** [comment]
Just working on monaco editor, thought I'd add some notes:

Ace Editor (unpacked) size: 44.1Mb

Monaco Editor (unpacked) size: 68.2Mb

The above ace package contains 120 languages, monaco contains about 6, there is another repo allowing me to add more languages - adds more code size.

Ripping out lots of things from Monaco and including now 67 languages in total I get the file size down to: 20.4Mb in total.

Just thought I'd post the file size information.

(still in middle of coding it).

**Comment by Samuell1** [comment]
@ayumi-cloud Its MB size of repository with all devs stuff or just compiled code?

**Comment by ayumi-cloud** [comment]
@Samuell1 complied code - removed all the dev stuff etc.

Got a gif now to demo:

![ezgif-6-19ac5cb06fa1](https://user-images.githubusercontent.com/57409060/73226307-76df3d00-4167-11ea-8d20-3467099b9512.gif)

**Comment by ayumi-cloud** [comment]
YAML:

```
toolbar = true | false
```

Default: Set to false

### True

![image](https://user-images.githubusercontent.com/57409060/73270558-d0328500-41d6-11ea-83ce-249e38641275.png)

### False

![image](https://user-images.githubusercontent.com/57409060/73270421-89448f80-41d6-11ea-9fa2-4408ac91da9d.png)

**Comment by ayumi-cloud** [comment]
YAML options:

```markdown
toolbar: false, // true or false (default)
language: "php", // default php
fontSize: "13", // default 13
lineNumbers: "on", // off or on (default)
roundedSelection: false, // true or false (default)
scrollBeyondLastLine: false, // true or false (default)
readOnly: false, // true or false (default)
theme: "vs-dark", // vs or hc-black or vs-dark (default)
minimap: { enabled: true }, // false or true (default)
wordWrap: 'wordWrapColumn', // off (default)
wordWrapColumn: 40, // 80 (default)
wordWrapMinified: true, // false or true (default)
wrappingIndent: "indent", // "same", "none" or "indent" (default)
useShadows: true, // Subtle shadows to the left & top. Defaults to true.
verticalHasArrows: true, // Render vertical arrows. Defaults to false.     
horizontalHasArrows: true, // Render horizontal arrows. Defaults to false.
vertical: 'visible', // Accepted values: 'auto', 'visible', 'hidden'. Defaults to 'auto'
horizontal: 'auto', // Accepted values: 'auto', 'visible', 'hidden'. Defaults to 'auto'           
verticalScrollbarSize: 17, // Width in pixels for the vertical scrollbar. Defaults to 10 (px).
horizontalScrollbarSize: 17, // Width in pixels for the horizontal scrollbar. Defaults to 10 (px).
arrowSize: 30, // The size of arrows (if displayed). Defaults to 11.
sampleURI: 'acme/example/resources/something.txt', // file location, to load default or placeholder code inside the widget.

size: huge, // Options: tiny, small, large, huge, giant.             
span: full, //  auto, left, right, storm, full. Default: full.            
commentAbove: 'example', //	places a comment above the field.
commentHtml: 'example', // allow HTML markup inside the comment. Options: true, false.                 
label: 'example', // a name when displaying the form field to the user.
tab: 'example', // assigns the field to a tab.
required: 1, // laces a red asterisk next to the field label to indicate it is required (make sure to setup validation on the model as this is not enforced by the form controller).

type: monacoeditor // fixed widget name.
```

**Comment by ayumi-cloud** [comment]
YAML options:

Currently setup and working with the widget.

```markdown
toolbar: false, // true or false (default)
language: 'php', // default php
fontSize: '13', // default 13
lineNumbers: 'on', // off or on (default)
roundedSelection: false, // true or false (default)
scrollBeyondLastLine: false, // true or false (default)
readOnly: false, // true or false (default)
theme: 'vs-dark', // vs or hc-black or vs-dark (default)
minimap: 'true', // false or true (default)
wordWrap: 'wordWrapColumn', // off (default)
wordWrapColumn: 40, // 80 (default)
wordWrapMinified: true, // false or true (default)
wrappingIndent: 'indent', // 'same', 'none' or 'indent' (default)
useShadows: true, // Subtle shadows to the left & top. Defaults to true.
verticalHasArrows: true, // Render vertical arrows. Defaults to false.     
horizontalHasArrows: true, // Render horizontal arrows. Defaults to false.
vertical: 'visible', // Accepted values: 'auto', 'visible', 'hidden'. Defaults to 'auto'
horizontal: 'auto', // Accepted values: 'auto', 'visible', 'hidden'. Defaults to 'auto'           
verticalScrollbarSize: 17, // Width in pixels for the vertical scrollbar. Defaults to 10 (px).
horizontalScrollbarSize: 17, // Width in pixels for the horizontal scrollbar. Defaults to 10 (px).
arrowSize: 30, // The size of arrows (if displayed). Defaults to 11.
sampleURI: 'acme/example/resources/something.txt', // file location, to load default or placeholder code inside the widget.

size: huge, // Options: tiny, small, large, huge, giant.             
span: full, //  auto, left, right, storm, full. Default: full.            
commentAbove: 'example', //	places a comment above the field.
commentHtml: 'example', // allow HTML markup inside the comment. Options: true, false.                 
label: 'example', // a name when displaying the form field to the user.
tab: 'example', // assigns the field to a tab.
required: 1, // laces a red asterisk next to the field label to indicate it is required (make sure to setup validation on the model as this is not enforced by the form controller).

type: monacoeditor // fixed widget name.
```

**Comment by ayumi-cloud** [comment]
Automatic error handling looks like this:

![image](https://user-images.githubusercontent.com/57409060/73272835-f22e0680-41da-11ea-95e5-ae7c4fee2294.png)

**Comment by ayumi-cloud** [comment]
October handling errors and bugs:

![image](https://user-images.githubusercontent.com/57409060/73277023-7daa9600-41e1-11ea-95c5-bb865a082e36.png)

**Comment by LukeTowers** [comment]
@ayumi-cloud is all that stuff in the folder you sent me?

**Comment by ayumi-cloud** [comment]
@LukeTowers 

Yes. But I'm working on some extra things today such as:

YAML:

```
saveMethod: file | database (default database)
```

**Comment by ayumi-cloud** [comment]
@LukeTowers 

Yes, all the above is.

Yesterday I added a YAML for the default file location:

```
sampleURI: '/plugins/ayumi/test/resources/acme-sample.txt'
```

Also I'm working on some extra things today such as:

YAML:

```
saveMethod: file | database (default database)
```

**Comment by ayumi-cloud** [comment]
@LukeTowers 

Yes, all the above is.

Yesterday I added a YAML for the default file location:

```
sampleURI: '/plugins/ayumi/test/resources/acme-sample.txt'
```

Also I'm working on some extra things today such as:

YAML:

```
saveMethod: file | database (default database)
```

For the widget to load from either the `file` or `database`.

**Comment by ayumi-cloud** [comment]
Old vs new:

![image](https://user-images.githubusercontent.com/57409060/73394421-81b7e000-42d5-11ea-8640-946a569d0c4a.png)

**Comment by ayumi-cloud** [comment]
https://github.com/ayumi-cloud/oc-security-module/blob/master/to_do_list.md

**Comment by ayumi-cloud** [comment]
Ok, found a very negative feature with Monaco Editor !

If you try to add multiple widgets on the same page you can't have different themes for each one !

Link: https://github.com/microsoft/monaco-editor/issues/1446

Link: https://github.com/microsoft/monaco-editor/issues/338

Microsoft engineers kind of suck, hence why they gave up on Edge and switched to Chromium.

Gonna rip that out of the yaml and into the settings.

**Comment by LukeTowers** [comment]
@ayumi-cloud tbh my thoughts for that widget is that most of those settings would be managed through user preferences anyways, not individual YAML level config.

**Comment by ayumi-cloud** [comment]
@LukeTowers 

### Settings

![image](https://user-images.githubusercontent.com/57409060/73564209-f9f9df00-4456-11ea-9339-211b56b1dd33.png)

### YAML options:

```
saveMethod: database | file
fontSize: number (default 13)
language: code language, for example, php, css, js, html. Default: php.
span: tiny | small | large | huge | giant
label: string
comment: string
```

**Comment by ayumi-cloud** [comment]
@LukeTowers 

### Settings

![image](https://user-images.githubusercontent.com/57409060/73564997-a8525400-4458-11ea-8281-c56ab5f801e6.png)

### YAML options

```
saveMethod: database | file
fontSize: number (default 13)
language: code language, for example, php, css, js, html. Default: php.
size: tiny | small | large | huge | giant
label: string
comment: string
```

**Comment by ayumi-cloud** [comment]
@LukeTowers 

### Settings

![image](https://user-images.githubusercontent.com/57409060/73564997-a8525400-4458-11ea-8281-c56ab5f801e6.png)

### YAML options

```
type: monacoeditor
saveMethod: database | file
fontSize: number (default 13)
language: code language, for example, php, css, js, html. Default: php.
size: tiny | small | large | huge | giant
label: string
comment: string
```

**Comment by LukeTowers** [comment]
@ayumi-cloud Hmm, some of those should be switched around but I'll take care of that when I review it and turn it into a plugin. Btw, `saveMethod` shouldn't be something that should be setup on the field config level, it's an implementation detail of how you handle saving the data. 

Are you envisioning something like a code editor for all the files on the site from the backend like WP's theme editor with the `saveMethod` option? It'd help if you could give me an example of how you see that working / what you see it being used for.

**Comment by ayumi-cloud** [comment]
@LukeTowers 

I need to check wordpress and see what you mean.

So far I done it like this:

```yaml
    acme-sample:
        span: full
        type: monacoeditor
        saveMethod: 'file'
        sampleURI: '/plugins/ayumi/test/resources/acme-sample.txt'
```

- I forgot to add the `sampleURI` to my previous comment.

```php
    public function getSaveValue($value)
    {
        // Save to file
        if ($this->config->saveMethod === 'file') {
            // Luke to do
            
            // ..
        }
        // Save to database
        else {
            return ($value);
        }
    }
```

**Comment by LukeTowers** [comment]
@ayumi-cloud sounds good.

**Comment by ayumi-cloud** [comment]
@LukeTowers Think I'm ready to send you an update, below is a screenshot showing all the features etc.

![image](https://user-images.githubusercontent.com/57409060/73596650-efede400-451b-11ea-8714-00a53582c848.png)

**Comment by ayumi-cloud** [comment]
p.s. We've changed the monaco widget to work with our October 2 proposal, which means a breaking change.

In testing 100 tabs in a single plugin on a single page and each tab has a 1gig file being loaded through monaco, the monaco widget only gets loaded when a user opens that tab. Also October 2 only saves the widgets that have had code changes and ignores all the rest and not save every field like in October 1 - this has increased performance.

**Comment by summercms** [comment]
Been using Monaco editor for almost a year now in October.

Two main issues with the editor:

1. When loading the Monaco editor widget in a tab it doesn't show up. To bypass this using a hack method, added some custom javascript to the tabs that run the resize function, to force the widget to get displayed when a user clicks on a tab.

2. Saving the code in the editor, the editor only saves code that has been updated. If you don't update the code in a widget then that data doesn't get saved. Another hack was added to only save the **updated** code and **bypass** the code that hasn't been changed.

Would like to open an issue with the Microsoft github repo on the tabs issue - but the repo has over 400 open issues with little to no comments (so looks like a dead repo to me).

Later, when get some time will try and contact some Microsoft team members to talk about the tabs issue more.

Anyway, upgraded their code to 0.21.2 today.

Thinking of switching the `cms` page to using a split screen to preview the code output for several code languages. For example, let's say a user is using `json` they can write the code in the editor on the left hand side of the screen and on the right hand side preview the output.

**Comment by LukeTowers** [comment]
If you add a split screen feature I'd definitely make it a button to toggle between showing and hiding that tab.

**Comment by bennothommo** [comment]
@ayumi-cloud I had a look at their repo and, yeah I agree, they've gone really quiet with it. I think this might make it the case where this could be provided as a plugin, but we'll probably keep it out of core as there's not enough support for it. To be fair though, Ace is showing similar activity :man_shrugging:.

Maybe the web-based code editor industry is drying up...
