### ISSUE TITLE
Image cropping when uploading

### ISSUE THREAD

**Issue by pavelmgn** [octobercms/october#4547]
I would like to crop all the images when loading in all form widgets and further store only the cropped version. How can this be done without rewriting all forms of widgets, including the richeditor.
? Thx.

**Comment by LukeTowers** [comment]
@pavelmgn use events. If you're uploading to the medialibrary there's https://octobercms.com/docs/api/media/file/upload and if you're dealing with File model uploads there's 
```php
System\Models\File::extend(function ($model) {
    $model->bindEvent('model.afterCreate', function () use ($model) {
        // do stuff here
    });
});
```

**Comment by SaifurRahmanMohsin** [comment]
@pavelmgn If I'm not mistaken there is a [thumbs option](https://octobercms.com/docs/backend/forms#widget-fileupload) field where you can specify the file type widgets to crop on upload so it does it automatically and stores the cropped version internally. Check the documentation!

**Comment by LukeTowers** [comment]
@SaifurRahmanMohsin he was looking for a more global setting, also I don't think the richeditor supports a thumbs option for the files that are uploaded through it.

**Comment by pavelmgn** [comment]
@LikeTowers thank you.
if i use the cloud by s3 api as storage no problems should happen?

**Comment by LukeTowers** [comment]
@pavelmgn it's web development, I'm not going to guarantee you that no problems will happen, but yes, S3 storage is a supported storage driver so you shouldn't have any issues that are October's fault.

**Comment by Samuell1** [comment]
@pavelmgn I am using S3 with OCMS and without issues.

**Comment by pavelmgn** [comment]
@Samuell1 i also use s3 with OCMS, without issues.
@LukeTowers thank you and great respect. I will try this.
