### ISSUE TITLE
AJAX request errors not reported correctly when in maintenance mode

### ISSUE THREAD

**Issue by nathan-van-der-werf** [octobercms/october#4552]
- OctoberCMS Build: 1.0.457
- PHP Version: 7.3.7
- Database Engine: Not relevant
- Plugins Installed: Not relevant

### Description:
When firing AJAX requests when the OctoberCMS application is in maintenance mode you will not get a "good error", see screenshot for a backend example:

![image (2)](https://user-images.githubusercontent.com/1123054/63150565-66973380-c007-11e9-97e7-ec431d3d7392.png)

### Steps To Reproduce:

1) Put OctoberCMS in maintenance mode
2) Try to fire an AJAX request (without refreshing the webpage before you do this)
3) You'll see an "ugly" error

The issue is not only in the backend, it's also in the frontend.

### Possible solution

The middleware responsible for doing this is:
`vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php`.

It's loaded from the kernel:
`vendor/october/rain/src/Foundation/Http/Kernel.php:30`

The middleware will need an additional check for AJAX requests, we could put some code in the catch clause like:

```
if ($request->ajax()) {
    throw new SomeExceptionWhichGetsRenderedBetter('A better message');
}
```

Another good feature would be the possibility to disable or override the middleware, the only way to do this at the moment is by creating your own `kernel.php` and registering it in the `bootstrap/app.php`.

**Comment by w20k** [comment]
@nathan-van-der-werf thanks for reporting! I've seen it already :)

**Comment by Samuell1** [comment]
Ajax should be allowed on Maintenance mode. Like it was disscussed here: https://github.com/octobercms/october/issues/4258

**Comment by nathan-van-der-werf** [comment]
> Ajax should be allowed on Maintenance mode. Like it was disscussed here: #4258
> 
> Or this is that maintenance mode that puts down everything?

It's the `php artisan down` (so the one putting the application / website "offline")

**Comment by LukeTowers** [comment]
@nathan-van-der-werf an ApplicationException gets handled nicely by the backend, you could give that a try and make a PR
