### ISSUE TITLE
Issue trying to install third party laravel packages

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4553]
I keep getting the same error with almost every third party laravel package I try to install, the error says the following:

```
[16-Aug-2019 13:01:13 UTC] PHP Fatal error:  Declaration of Illuminate\Cache\Repository::add($key, $value, $minutes) must be compatible with Illuminate\Contracts\Cache\Repository::add($key, $value, $ttl = NULL) in /home/ache/public_html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php on line 23
```

Doing a search in Laravel finds the error and a fix can be found here: https://github.com/laravel/framework/pull/22011

Not sure what to do?

**Comment by Samuell1** [comment]
Its mostly issue that your laravel package works only with new laravel versions not 5.5.

**Comment by ayumihamsaki** [comment]
Yah that's what I was thinking.

The trouble is the packages that are compatible with October's Laravel version I'm seeing this error:

```
Method addMinutes does not exist.

/home/annoying/public_html/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php line 96
```

Which is basically the same issue.

**Comment by ayumihamsaki** [comment]
@Samuell1 Thanks, I forgot to edit the `composer.json` for the right version - stupid me! 👍
