### ISSUE TITLE
Add import and export options to dashboard area

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4556]
### Intro

It would be useful to people to add a feature that allows the dashboard layout to be imported and exported.

Currently October has a database table already setup! Just go to the following location:

```html
system_parameters > (namespace) backend > value
```

You will see something like this:

```json
{"welcome":{"class":"Backend\\ReportWidgets\\Welcome","sortOrder":50,"configuration":{"ocWidgetWidth":7}},"systemStatus":{"class":"System\\ReportWidgets\\Status","sortOrder":60,"configuration":{"ocWidgetWidth":7}},"activeTheme":{"class":"Cms\\ReportWidgets\\ActiveTheme","sortOrder":70,"configuration":{"ocWidgetWidth":5}}}
```

### Reason why it would be useful

Say I want to copy the dashboard from Website A into Website B. The only way to do this right now is to go into MySQL and copy the database table manually.

There should be a feature on the dashboard web page to export the file (maybe as a .csv or json file etc) and an import.

Then it helps to speed up creating lots of October websites and cover the internet in the world of October CMS.

### Proposal idea

Create something like this:

![image](https://user-images.githubusercontent.com/17784082/63267221-7625af00-c289-11e9-83fd-bee6342a5d10.png)

**Comment by LukeTowers** [comment]
@ayumihamasaki2019
