### ISSUE TITLE
Log output is parsed, not raw

### ISSUE THREAD

**Issue by dasilvacontin** [octobercms/october#4558]
If I do `Log::info('&amp;')`, I expect to see `&amp;` in `/admin/system/eventlogs`. However, I see `&`. Even if I look in the 'Raw' tab.

**Comment by dasilvacontin** [comment]
The `/storage/logs` file does have `&amp` stored.

**Comment by bennothommo** [comment]
@dasilvacontin The logs are run through the [`e()`](https://octobercms.com/docs/services/helpers#method-e) helper function to encode them for display on the web. By default, this method will allow already-encoded characters like `&amp;` to display as the character. This is correct for the "Formatted" tab, however, I agree it should be double-encoded for the "Raw" tab.

**Comment by bennothommo** [comment]
@dasilvacontin My apologies - it is actually run through an exception beautifier widget which runs the logs through the [$.oc.escapeHtmlString](https://github.com/octobercms/october/blob/develop/modules/backend/assets/js/backend.js#L170) function. Since this widget uses a textarea as the base and replaces it with the widget, it appears that the textarea decodes the ampersand before it is  re-encoded by the function above.

**Comment by bennothommo** [comment]
@LukeTowers @w20k Should this behaviour in the log viewer be changed?

**Comment by w20k** [comment]
There is a `raw` output tab inside the log input. 
We could add a configurable property to `config/develop`, something like - `showRawLogs` to show logs in raw format, by default.

Screenshot:
![Screenshot 2019-08-21 at 17 54 34](https://user-images.githubusercontent.com/1053320/63443185-05bf8f00-c43d-11e9-9bc4-4bdae4bba57b.png)

**Comment by LukeTowers** [comment]
@bennothommo nothing should change about the formatted, but I agree, if `Log::info('&amp;')` is called then `&amp;` should be seen in the **raw** tab (so long as we make sure it's still preventing XSS opportunities.

**Comment by bennothommo** [comment]
@dasilvacontin would you be up for giving #4566 a test and let us know if that works for you?

**Comment by dasilvacontin** [comment]
@bennothommo What steps should I take in order to give it a test?

**Comment by w20k** [comment]
If you're using git, just use https://patch-diff.githubusercontent.com/raw/octobercms/october/pull/4566.patch and apply. If not,
manually copy @bennothommo changes from PR (https://github.com/octobercms/october/pull/4566/files) to your local env.

**Comment by bennothommo** [comment]
Fixed by #4566.
