### ISSUE TITLE
Freeze web page after incorrect DEFAULT value on a new field table

### ISSUE THREAD

**Issue by Zio3D** [octobercms/october#4559]
- OctoberCMS Build: 455
- Apache 2.4.37
- PHP Version: 7.2.14
- Database Engine: MySQL 5.7.24
- Plugins Installed: RainLab.Builder-v1.0.25
- Windows 10 Pro 64 bit (1809 17763.615)
- Browser: Mozilla Firefox Quantum 68.0.1 64 bit

**### Description:**
Inserting an incorrect DEFAULT value in a new field of a table, the web page freeze after the message _"Invalid default value for the boolean column 'b_enabled'. The allowed values are '0' and '1'."_ losing all the changes.

**### Steps To Reproduce:**
- In the back-end, go to the "Database" command and create a new table.
- Insert a new boolean field (for example 'b_enabled') and insert in DEFAULT the 'false' value instead of '0' and then save the table.
- After the message _"Invalid default value for the boolean column 'b_enabled'. The allowed values are '0' and '1'."_, the web page freezes and I need to refresh it to enable it again losing all the changes made in the meantime.

Thanks
Davide.

**Comment by bennothommo** [comment]
@Zio3D This has been resolved by https://github.com/rainlab/builder-plugin/pull/291 - a new version of the Builder plugin with these changes will hopefully be out today or tomorrow.

**Comment by Zio3D** [comment]
Ok, perfect! Thank you for your answer 😃
