### ISSUE TITLE
Handle congestion errors better

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4563]
I'm not sure if someone created an issue about this or not? If so please close this.

Basically October shows escaped HTML code when handling congestion / server errors, e.g.

![image](https://user-images.githubusercontent.com/17784082/63543207-33c6d100-c51a-11e9-920b-f5dcb72cc4a5.png)

I just want to bring it to your attention that maybe October could handle them a bit better and display something nicer looking.

### Possible solution

1. Why can't October just display the error and use HTML Purifier and allow HTML4 elements only.

2. Why is the modal window so small? So hard to read and no good. Could we use `80vw` and `80vh` instead.

### Modern techniques

A more modern approach would be to use **background sync api**. If there is no network and the user has selected to try and save their work, October could instead of showing a spinner between 1 - 120 seconds or longer. Just display a message saying:

"**No network connection**"
"**_Try again_** or **_Save later_**"

Then a user could carry on working and save the web page at a later date when the network congession has passed. This way, less wasted time for a developer - watching a useless spinner icon and make October a bit more productive allowing the developer to carry on working while waiting.

Or just test the network connection before saving and do the following logic:

Network connection good - save data.

Network connection bad - don't try and save data and display an error message.

and

Localhost - no need test network connection.

**Comment by ayumihamsaki** [comment]
Ok found another issue with this setup, see screenshot:

![image](https://user-images.githubusercontent.com/17784082/63596423-23166980-c5b3-11e9-936e-561498fd777d.png)

1. Keyboard navigation doesn't work and the screen is totally locked up! 

- You can't select the error message to read it
- You can't scroll
- You can't press the ok button to exit

2. Doesn't work at all with a screen reader you would be totally screwed up, if this happened.

**Comment by LukeTowers** [comment]
@ayumihamsaki this would be handled in framework.js to add additional handlers for the various 5xx error codes to display them the same as an ApplicationException is currently.

**Comment by ayumihamsaki** [comment]
### Solutions

Seems to be four things needed to be fixed here:

1. Update sweet-alert lib from v1 to v2.

2. Add WAI-ARIA so you can close the alert using keyboard navigation, e.g. on the `cancel` and `confirm` buttons.

3. Use HTML Purifier to display a readable message.

4. Be able to select the message with a screen reader that can read the message to a person with poor vision.

**Comment by ayumihamsaki** [comment]
### Solutions

Seems to be five things needed to be fixed here:

1. Update sweet-alert lib from v1 to v2.

https://sweetalert.js.org/guides/#upgrading-from-1x

2. Add WAI-ARIA so you can close the alert using keyboard navigation, e.g. on the `cancel` and `confirm` buttons.

3. Use HTML Purifier to display a readable message.

4. Be able to select the message with a screen reader that can read the message to a person with poor vision.

5. Most important thing! Add a timeout function, when testing I turned off the internet and clicked save and the loading spinner showed even after an hour! October needs to have a timeout function of 2 mins max I think and then do something! Not get stuck on a loading spinner forever!

**Comment by ayumihamsaki** [comment]
@LukeTowers is it ok to ask to add the labels: `hacktoberfest` and `help wanted` to this github issue. Basically most of these problems are coming from the vendor file `sweet-alert` and I'm a bit stuck on upgrading it from v1 to v2. I would be happy to code the rest, once that's been upgraded.

The `sweet-alert` version is injecting the wrong html code etc and causing the errors to points 1, 2 and 4 in my previous comment. So that would leave the **HTML Purifier** issue in the `framework.js` and adding a **timeout function** to connection errors to stop an **infinite loading spinner**.

**Comment by LukeTowers** [comment]
@ayumihamasaki2019
