### ISSUE TITLE
Declaration of System\Models\File::getPath() should be compatible with October\Rain\Database\Attach\File::getPath($fileName = NULL)

### ISSUE THREAD

**Issue by gorny-dev** [octobercms/october#4565]
(1/1) ErrorExceptionDeclaration of System\Models\File::getPath() should be compatible with October\Rain\Database\Attach\File::getPath($fileName = NULL)
--

(1/1) ErrorExceptionDeclaration of System\Models\File::getPath() should be compatible with October\Rain\Database\Attach\File::getPath($fileName = NULL)

i get that error every time right after installing my project from repo 

screen:
![october-error](https://user-images.githubusercontent.com/54044073/63638696-fe41f500-c68b-11e9-9d97-91f08bdf11b7.png)

cant find any solutions in google, wth is this plz halp

**Comment by LukeTowers** [comment]
@gorny-dev how did you install the project? This is because you're using the latest version of the library repo but not the latest version of the octoberrain/system module.

**Comment by gorny-dev** [comment]
ty m8 i got this 
just delete vendor directory than run "composer install" and its working fine

**Comment by frthjf** [comment]
I've run into the same issue. For me, the solution was to remove the cache files under `storage/framework/*.php`.
