### ISSUE TITLE
ApplicationException is logged unexpectedly

### ISSUE THREAD

**Issue by pikanji** [octobercms/october#4568]
- OctoberCMS Build: 458
- PHP Version: 7.2.17

#### Expected behavior
`ApplicationException` should not be logged as stated in [its comment](https://github.com/octobercms/library/blob/master/src/Exception/ApplicationException.php#L5).
Also, `ApplicationException` is in [the list](https://github.com/octobercms/library/blob/master/src/Foundation/Exception/Handler.php#L23) of exceptions not to be logged.

#### Actual behavior
`ApplicationException` is logged.

### Steps To Reproduce:
Create a page that throws an `ApplicationException` like below, and check the log file.

```
url = "/test"

==
function onStart() {
	throw new \October\Rain\Exception\ApplicationException('application exception');
}

==
hello
```

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/70e57120d0e65d7b40bf6b89ebe42afeeaa1fbf3
