### ISSUE TITLE
Backend list setup doesn't save after logout

### ISSUE THREAD

**Issue by mkinternet** [octobercms/october#4570]
- OctoberCMS Build: 455

### Description:
In backend list setup i can show /hide particular columns. When i logout and login default list setup shows (all column are visible). This setup should be saved for user account.

### Steps To Reproduce:
Install october
Install test plugin.
Choose playground -> people.
In list setup hide some  columns.
Log out account.
Log in account ant open playground -> people.
All columns are visible.

**Comment by bennothommo** [comment]
@mkinternet This was fixed by #4360 and released with build 457 of October CMS. You will need to enable edge updates to get this build.
