### ISSUE TITLE
Is it Possible to Host OctoberCMS on AWS Lambda?

### ISSUE THREAD

**Issue by maliksajid** [octobercms/october#4571]
Hi, 
I'm trying to host October cms on AWS lambda by using Bref(http://bref.sh). But I'm unable to upload. Even though I uploaded Laravel 5.8 successfully through this package.

Anybody knows how to  October to AWS Lambda?

Thank you

**Comment by maliksajid** [comment]
@LukeTowers @LarBearrr thanks for your answer. I'm not using Vapor. I'm using https://bref.sh/. Bref is a good package for building laravel serverless apps. I got the Laracon EU presentation slides from somewhere and found it there. 

`VIEW_COMPILED_PATH=/tmp/storage/framework/views

# We cannot store sessions to disk: if you don't need sessions (e.g. API)
# then use `array`, else store sessions in database or cookies
SESSION_DRIVER=array

# Logging to stderr allows the logs to end up in Cloudwatch
LOG_CHANNEL=stderr`

I used these 3 variables in my configuration files that reside in the config directory. **I'm not sure the OctoberCMS supports _stderr_ log Channel or not**

**Comment by maliksajid** [comment]
![Untitled](https://user-images.githubusercontent.com/32770676/63852807-9274ca80-c9b2-11e9-9572-b60f63906541.png)

**Comment by maliksajid** [comment]
When I uploaded the OctoberCMS to lambda without altering the default configuration.  I got the below error screen.
![Untitled](https://user-images.githubusercontent.com/32770676/63852881-c51ec300-c9b2-11e9-9231-0e9575f74b1b.png)

**Comment by maliksajid** [comment]
@LarBearrr I did. I follow the below steps one by once:

1. Since the filesystem is read-only except for /tmp. So, we need to customize where the cache files are stored. Added this line in bootstrap/app.php after $app = new Illuminate\Foundation\Application
`$app->useStoragePath($_ENV['APP_STORAGE'] ?? $app->storagePath());`

2. Created .env file and stored 2 variables in it.
`VIEW_COMPILED_PATH=/tmp/storage/framework/views
SESSION_DRIVER=array`

**Comment by idpsycho** [comment]
you just have to change this file, and then october will look for storage in /storage2:

`october/vendor/laravel/framework/src/Illuminate/Foundation/Application.php`
```
    public function storagePath()
    {
        $this->useStoragePath( $this->basePath.DIRECTORY_SEPARATOR.'storage2' );

        return $this->storagePath ?: $this->basePath.DIRECTORY_SEPARATOR.'storage';
    }
```

**Comment by LarBearrr** [comment]
@idpsycho We don't want to modify the Laravel framwork tho. We have to figure out another way to do it.

**Comment by Samuell1** [comment]
@maliksajid you need to set permissions per every of that storage folders, look at this:

https://medium.com/artisanhost/hosting-a-laravel-application-on-aws-lamdba-90b7133c8578

**Comment by LukeTowers** [comment]
@LarBearrr @idpsycho there should be some way to dynamically set that value

**Comment by LarBearrr** [comment]
@Samuell1 Very good post there. In the original error, it says the `bootstrap/cache` directory must be present and writable. Does october even use this directory?

**Comment by junjettrasmonte** [comment]
With AWS EFS now supported in lambda. I guess this is now possible as you can now mount a filesystem that is shared between lambda instances. Before EFS, you can only write to the tmp folder but tmp is not shared.
