### ISSUE TITLE
Fix Checkbox and Checkbox list fields and add the missing example code in the doc's

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4573]
According to the W3c there are two types of checkboxes these are:

### 1. (Two State) Checkbox

Here we have a single checkbox example:

![ezgif-2-6fb0fa627d42](https://user-images.githubusercontent.com/17784082/63714262-59651a80-c839-11e9-9af2-818ca3f0166b.gif)

The doc's can be found here: https://octobercms.com/docs/backend/forms#field-checkbox

A working example can be found here: https://octobercms.com/docs/ui/checkbox

### 2. (Tri State) Checkbox List

Here we have a checkbox list example:

![ezgif-2-fe59d9a75021](https://user-images.githubusercontent.com/17784082/63714641-148db380-c83a-11e9-9a4a-04fa7765a02a.gif)

The doc's can be found here: https://octobercms.com/docs/backend/forms#field-checkboxlist

A working example can be found here: **_DOES NOT EXIST!_**

### Problems with October's Checkbox List

The problem is that October CMS for it's Checkbox List is actually using a (Two State) and not a (Tri State) method I tricked you in the above example!

Let's now show you a proper (Tri State) method:

![ezgif-2-b2c6c24e7347](https://user-images.githubusercontent.com/17784082/63714952-b0b7ba80-c83a-11e9-901b-af61b0571781.gif)

Did you spot the difference?

Let me explain, let's say there are 50 checkbox's in the Checkbox list how long would it take your Users/Clients before they finished selecting all the checkbox's in the checkbox list? Even more important, how long would it take before they started to get annoyed?

A (Tri State) method allows your Users/Clients to be able to select all the checkbox's, de-select all the checkbox's and allow their custom selection.

### Solutions

October CMS needs to do three things:

1. Add a working Checkbox list example to their doc's.

2. Change the Checkbox list from a (Two State) into a (Tri State) method.

3. Add WAI-ARIA to the checkbox and Checkbox list fields.

**Comment by 36864** [comment]
Just a side note, checkbox list already allows selecting/deselecting all entries by setting `quickselect` to true. `quickselect` is true by default on lists larger than 10 elements. It's not as fancy as your example, but it gets the job done:

![image](https://user-images.githubusercontent.com/7127588/63763932-9ecb2b80-c8bd-11e9-9cbc-c495d240865a.png)

One thing I would like to see added is filters for larger lists. I currently use https://octobercms.com/plugin/tschallacka-formtools to have a checkboxlist with a search bar:
![image](https://user-images.githubusercontent.com/7127588/63764079-f1a4e300-c8bd-11e9-8366-ed6093071de4.png)

**Comment by ayumihamsaki** [comment]
@36864 Cool, thanks for the info, very useful. 👍 

Need to discuss things with the admins on changes.

### Simple features

1. Set the `quickselect` to `true` by default for **all checkbox list sizes**.

2. Allow the three states:

- unchecked (none)
- checked (all)
- indeterminate (also known as mixed)

### Advanced features

3. Decide if you want to add a search into the core?

4. Nested Checkbox lists

![ezgif-2-8dd22d154bdc](https://user-images.githubusercontent.com/17784082/63780970-e9aa6a80-c8e0-11e9-900e-e4fee8009b6b.gif)

**Comment by bennothommo** [comment]
@ayumihamsaki Definitely on board with an indeterminate state (1) and nested checkbox lists (4), if you can provide an idea as to the format that the data will be returned in POST.

**Comment by ayumihamsaki** [comment]
@LukeTowers @bennothommo 

With regards to the nested checkbox list my main issue is trying to find a way to make it **easy for people to create the nested lists**?

> if you can provide an idea as to the format that the data will be returned in POST.

Yah I need to look deeper into that, still researching and going to code some tests in October to find out.

**Comment by ayumihamsaki** [comment]
Ok the normal checkbox doc's seem to be confusing and stupid, link here: https://octobercms.com/docs/backend/forms#field-checkbox

We have a YAML example here:

```markdown
show_content:
    label: Display content
    type: checkbox
    default: true
```

I want to focus on the property `default` so please ignore all the rest.

Now let's create some examples to show you why I think this is confusing and stupid the current setup:

### Example 1

```markdown
show_content:
    label: Display content
    type: checkbox
    default: true
```

Setting `default: true` makes the checkbox unchecked.

### Example 2

```markdown
show_content:
    label: Display content
    type: checkbox
    default: false
```

Setting `default: false` makes the checkbox unchecked. So it does exactly the same as `true` ?

### Example 3

```markdown
show_content:
    label: Display content
    type: checkbox
    default: 0
```

Setting `default: 0` makes the checkbox unchecked.

### Example 4

```markdown
show_content:
    label: Display content
    type: checkbox
    default: 1
```

Finally setting `default: 1` SHOULD make the checkbox checked. **DOESN'T SEEM TO WORK CORRECTLY AT ALL. I CAN SET IT IN BUILDER BUT IF I WRITE IT IN THE YAML FILE - IT DOESN'T WORK AT ALL - TESTED IT ON A FRESH INSTALL.**

## Doc's

1. Could we update the doc's to show people how to set a checkbox to `checked`.

2. Could we have the following:

- `default: true` - makes the checkbox checked.

- `default: false` - makes the checkbox unchecked.

- `default: 0` - makes the checkbox checked.

- `default: 1` - makes the checkbox unchecked.

## Code in Core

3. Need to fix checkbox's to work properly when trying to set `checked` - so far I can't setup a baseline to even run some tests for checkbox's. Because I'm stuck get only `unchecked` checkbox's.

**Comment by bennothommo** [comment]
@ayumihamsaki does `checked: true` make it checked by default?

**Comment by ayumihamsaki** [comment]
@bennothommo no doesn't seem to do anything.

Here's my test code:

```yaml
fields:
    show_content1:
        label: Display content
        type: checkbox
        default: true
    show_content2:
        label: Display content
        type: checkbox
        default: false
    show_content3:
        label: Display content
        type: checkbox
        default: 0
    show_content4:
        label: Display content
        type: checkbox
        default: 1
    show_content5:
        label: Display content
        type: checkbox
        checked: true
```

Result:

![image](https://user-images.githubusercontent.com/17784082/63864131-3f494a80-c9a7-11e9-9d3f-bd457fbdeb31.png)

**Comment by bennothommo** [comment]
@ayumihamsaki *sadface.jpg*. That's possibly a bug with the default attribute then.

**Comment by ayumihamsaki** [comment]
@bennothommo No worries I might try and re-code it now. Are you happy with the following:

- `default: true` - makes the checkbox checked.

- `default: false` - makes the checkbox unchecked.

- `default: 0` - makes the checkbox checked.

- `default: 1` - makes the checkbox unchecked.

- `default: null` - makes the checkbox unchecked.

**Comment by bennothommo** [comment]
@ayumihamsaki yep all good, as long as it uses the POST data or model data first before using the default value :)

**Comment by ayumihamsaki** [comment]
@bennothommo I think the `$field->isSelected()` and `$field->default` is mixed up here? Need to investigate further and then code a solution.

**Comment by bennothommo** [comment]
@ayumihamsaki it is possible that `$field->isSelected()` is used for checkbox lists and relation fields, so be careful with changing that one.

**Comment by ayumihamsaki** [comment]
@bennothommo 

Sorry keep tagging you. I've done some testing it just seems like `default` doesn't exist at all. I would like to create a new attribute and call it `checked` as it makes more sense. 

> it is possible that $field->isSelected() is used for checkbox lists and relation fields, so be careful with changing that one.

Seems like **checkbox list** is using:

```php
<?= in_array($value, $checkedValues) ? 'checked="checked"' : '' ?>
```

Also **checkbox list** you can't set any `checked` checkbox's at all. Unless you know of some special YAML code or it's done via php.

For now I just get the **checkbox** (not checkbox list) working and do this:

- `checked: true` - makes the checkbox checked.

- `checked: false` - makes the checkbox unchecked.

- `checked: 0` - makes the checkbox unchecked.

- `checked: 1` - makes the checkbox checked.

- `checked: null` - makes the checkbox unchecked.

(I prefer your suggestion attribute name).

**Comment by ayumihamsaki** [comment]
Fixed.

**Comment by ayumihamsaki** [comment]
@LukeTowers 

I was running the stable release v455 on a fresh install. Just updated to v458 and same issue. Have checked and have that commit installed via the update.

What to do now?

**Comment by ayumihamsaki** [comment]
@LukeTowers Just want confirm I'm going to do the right thing (getting tired done quite a few pr's today).

You are happy with the following:

1. modules/backend/widgets/form/partials/_field_checkbox.htm 

https://github.com/octobercms/october/blob/95d2891cfeed957b03c81b727009d9b24b156862/modules/backend/widgets/form/partials/_field_checkbox.htm#L14

2. modules/backend/widgets/form/partials/_field_checkboxlist.htm

https://github.com/octobercms/october/blob/5afb1ee04f3bcd0ae5b04b042eeb9bce80b92ce5/modules/backend/widgets/form/partials/_field_checkboxlist.htm#L72

3. Update the https://github.com/octoberrain/test-plugin

**Comment by LukeTowers** [comment]
Not sure what those code changes are for. You mentioned that `default` doesn't work for the checkbox / checkboxlist fields right now; what I'm looking for is a PR to the test plugin demonstrating that as I can't replicate it locally.

**Comment by ayumihamsaki** [comment]
@bennothommo @LukeTowers 

Going to try and create a PR for the test plugin today, was thinking of adding a test for checkbox, checkbox lists, the new form fields, grow and stretch tests.

I did some tests yesterday and can share the results:

### Checkbox (not checkbox lists)

Testing: `$field->isSelected()` (current method)

YAML Code | Result
-- | ---
default: true | EMPTY
default: false | EMPTY
default: 0 | EMPTY
default: 1 | EMPTY
default: null | MPTY

Testing: `$field->defaults` (in pr submitted)

YAML Code | Result
-- | ---
default: true | 1
default: false | EMPTY
default: 0 | 0
default: 1 | 1
default: null | EMPTY

As you can see the `defaults` method worked better however, I was a bit sad to see two results saying empty.

Was hoping to see this:

YAML Code | Result
-- | ---
default: true | 1
default: false | 0
default: 0 | 0
default: 1 | 1
default: null | 0

**Comment by bennothommo** [comment]
@ayumihamsaki Checkboxes that are unchecked do not have a value, I believe. Like normal checkboxes, they are not supposed to contribute any POST data if they are unchecked, so if default `false` and `null` make it unchecked, then the result being empty is correct. I'm curious as to how `default: 0` worked though.

**Comment by ayumihamsaki** [comment]
@bennothommo interesting, will have to compare that to a tri-state method, in my mind I was thinking a `tri-state` would be like this for the POST data:

- unchecked (value = 1)
- checked (value = 0)
- indeterminate (value = null)

Will do some testing and see or not if that is true?

**Comment by ayumihamsaki** [comment]
@LukeTowers Done!

PR is found here: https://github.com/octoberrain/test-plugin/pull/77

Screenshot is here:

![image](https://user-images.githubusercontent.com/17784082/64068447-269f9580-cc30-11e9-93b7-fce7efae767b.png)

**Comment by ayumihamsaki** [comment]
Going to work on this issue and create some PR's - but I will be using the `$field->defaults` to have the checked feature working.

**Comment by ayumihamsaki** [comment]
## Solutions and PR's

1. Allow checkbox's to have **checked state**, see here: https://github.com/octobercms/october/pull/4578

2. Add **keyboard navigation and focus ring styling** to checkboxes and checkbox lists, see here: ---

3. Add **Tri-State** to checkbox lists, see here: ---

4. Add **Nested** checkboxes to checkbox lists, see here: ---

**Comment by ayumihamsaki** [comment]
## Solutions and PR's

1. Allow checkbox's to have **checked state**, see here: https://github.com/octobercms/october/pull/4578

2. Add **keyboard navigation and focus ring styling** to checkboxes and checkbox lists, see here: https://github.com/octobercms/october/pull/4588

3. Add **Tri-State** to checkbox lists, see here: ---

4. Add **Nested** checkboxes to checkbox lists, see here: ---

5. Add **checkbox list example code** to the doc's, see here: ---

**Comment by ayumihamsaki** [comment]
### Tri-State tests

![ezgif-2-9f365a36efd1](https://user-images.githubusercontent.com/17784082/64116894-85c5ed00-cd8b-11e9-8c16-30a81e1c2da9.gif)

**Comment by ayumihamsaki** [comment]
## Solutions and PR's

1. Allow checkbox's to have **checked state**, see here: https://github.com/octobercms/october/pull/4578

2. Add **keyboard navigation and focus ring styling** to checkboxes and checkbox lists, see here: https://github.com/octobercms/october/pull/4588

3. Add **Tri-State** to checkbox lists, see here: ---

4. Add **Nested** checkboxes to checkbox lists, see here: ---

5. Add **checkbox list example code** to the doc's, see here: ---

**Comment by ayumihamsaki** [comment]
Notes:

Checkbox list function code:

https://github.com/octobercms/october/blob/61af6384d2a350e1b6ddfdf04e3afb17bb2a08a1/modules/backend/widgets/form/assets/js/october.form.js#L55-L75

and

https://github.com/octobercms/october/blob/61af6384d2a350e1b6ddfdf04e3afb17bb2a08a1/modules/backend/widgets/form/partials/_field_checkboxlist.htm#L41-L48

**Comment by ayumihamsaki** [comment]
@LukeTowers @bennothommo 

I would like to get some feedback with a fresh new re-design of the checkbox lists:

### Old design

![image](https://user-images.githubusercontent.com/17784082/64290984-130d6b00-cf5f-11e9-9a94-99e5713f4f01.png)

### New design (normal)

![image](https://user-images.githubusercontent.com/17784082/64291076-3cc69200-cf5f-11e9-83b8-764ce1b07444.png)

### New design (nested)

![image](https://user-images.githubusercontent.com/17784082/64291391-f6256780-cf5f-11e9-93a6-8983769b6a41.png)

I hope you can see that the theme is then the same throughout the new design.

I'm also thinking of creating a new widget that deals with the nested checkboxes to support backwards compatibility etc.

**Comment by ayumihamsaki** [comment]
## Solutions and PR's

1. **Create a checkbox and checkbox list test set** for the test plugin, see here: https://github.com/octoberrain/test-plugin/pull/77

2. Allow checkbox's to have **checked state**, see here: https://github.com/octobercms/october/pull/4578

3. Add **keyboard navigation and focus ring styling** to checkboxes and checkbox lists, see here: https://github.com/octobercms/october/pull/4588

4. **Cleanup checkbox lists**, see here: https://github.com/octobercms/october/pull/4599

5. Add **checkbox list example code** to the doc's, see here: https://github.com/octobercms/october/pull/4600

6. Add **Tri-State Nested** checkbox list widget, see here: ---

### Bonus

Updated builder plugin to give a better user experience: https://github.com/rainlab/builder-plugin/pull/299

**Comment by Samuell1** [comment]
I am not sure but i dont like that big buttons just for selecting and unselecting, can be that 2 buttons made a little byt smaller?

**Comment by seanthepottingshed** [comment]
Maybe the selection buttons should be in the secondary colour ( same as the **Save and Close** button )

**Comment by ayumihamsaki** [comment]
Please note the old method completely doesn't work on touch screens and you need to consider tap target rules.

![image](https://user-images.githubusercontent.com/17784082/64409439-ce79f080-d080-11e9-945a-85ae3ee2e84d.png)

I'm up for suggestions that pass touch screen usage.

**Comment by ayumihamsaki** [comment]
> Maybe the selection buttons should be in the secondary colour ( same as the Save and Close button )

Gonna do that.

**Comment by ayumihamsaki** [comment]
Changed buttons to default now look like this:

![image](https://user-images.githubusercontent.com/17784082/64410912-f585f180-d083-11e9-8e7f-374ed8f7efba.png)

**Comment by Samuell1** [comment]
That only goes with buttons not for other elements that are not that priority to user click every time. 

If there is multiple items in that list that means it will be scrolling with that buttons too?

There is my example how it should look:

![obrázok](https://user-images.githubusercontent.com/3110002/64411657-ff145700-d08d-11e9-9c5e-f12c21834445.png)

**Comment by ayumihamsaki** [comment]
@Samuell1 got a link to that code, or do I need to write it fresh.

**Comment by seanthepottingshed** [comment]
@ayumihamsaki 

In retrospect I much prefer @Samuell1 suggestion

**Comment by Samuell1** [comment]
@ayumihamsaki i just designed it in figma (https://www.figma.com/file/0AOvSzfDgpvYNZJbiCnSeX/OCMS-Multi-Checkbox?node-id=0%3A1)

**Comment by ayumihamsaki** [comment]
@Samuell1 are you willing to share the html, css code?

**Comment by Samuell1** [comment]
@ayumihamsaki iam not sure how i should say it but its just image designed in figma :D

**Comment by ayumihamsaki** [comment]
@Samuell1 ok no worries I will code the design, just will take longer.

**Comment by Samuell1** [comment]
@ayumihamsaki you can reuse code from datatable widget it looks similair to mine layout

datatable:
![obrázok](https://user-images.githubusercontent.com/3110002/64412293-5d8e0500-d08f-11e9-963a-d8044c126959.png)

**Comment by ayumihamsaki** [comment]
@Samuell1 cool thanks 👍

**Comment by ayumihamsaki** [comment]
Ok updated code:

### Old design

![image](https://user-images.githubusercontent.com/17784082/64290984-130d6b00-cf5f-11e9-9a94-99e5713f4f01.png)

Completely doesn't work on touch screens and fails the tap-target rules.

### New design (normal)

![image](https://user-images.githubusercontent.com/17784082/64418751-7dbfc300-d093-11e9-92af-646c7f3aca73.png)

and mobile:

![image](https://user-images.githubusercontent.com/17784082/64418783-8ca67580-d093-11e9-85bf-cfb455b40320.png)

### New design (nested)

![image](https://user-images.githubusercontent.com/17784082/64418834-9f20af00-d093-11e9-9a0c-4f2d29fa2542.png)

and mobile:

![image](https://user-images.githubusercontent.com/17784082/64418924-c37c8b80-d093-11e9-9a2f-4ce6bdd3afeb.png)

### Test plugin screenshot

![image](https://user-images.githubusercontent.com/17784082/64419025-f161d000-d093-11e9-8e63-08951a99b8d3.png)

@Samuell1 Thanks for feedback.

**Comment by Samuell1** [comment]
Its there a way to make that bar a litte bit smaller? Best will be to make it same height as datatable has.

**Comment by ayumihamsaki** [comment]
@Samuell1 

> Its there a way to make that bar a litte bit smaller? Best will be to make it same height as datatable has.

Sorry I can't make it any smaller, otherwise the outer margin will start looking wrong and the tap targets margins will not be enough as they are set at min requirements right now. If you look really carefully you will see that the top icons are slightly indented to the left against the checkbox icons, because I added the smallest amount of spacing.

As for the search box example the spacing seems bigger as it has a flexbox vertical centering added to it.

**Comment by Samuell1** [comment]
I dont agree. You can use just padding like datatable does.

And if you look at your examples last has different height maybe its becase search bar.

**Comment by ayumihamsaki** [comment]
> And if you look at your examples last has different height maybe its becase search bar.

I alreadly said:

> As for the search box example the spacing seems bigger as it has a flexbox vertical centering added to it.

See nested without the search bar added:

![image](https://user-images.githubusercontent.com/17784082/64421382-55d35e00-d099-11e9-9a97-14da5cc3316f.png)

Sorry but I like to have websites working with touch devices over looks!

**Comment by Samuell1** [comment]
And they stop working if you make it smaller by 5-10 px?

Look at datatable i dont see issue with this on mobile.
![obrázok](https://user-images.githubusercontent.com/3110002/64421624-49073800-d0a2-11e9-8284-cdcd236e11e4.png)

**Comment by ayumihamsaki** [comment]
> And they stop working if you make it smaller by 5-10 px?

I think you need read the Tap target spec! Try tagging with your finger those two buttons will activate at the same time! You need to make the spacing the correct gap! It's there for a reason.

**Comment by Samuell1** [comment]
Then make it different depending if user is on mobile and desktop? Dont waste 80px for just 2 buttons and dont forget this is Backend administration, not a frontend of website that needs to go trough some specs that are maded for real websites.

**Comment by ayumihamsaki** [comment]
Now you are talking rubbish! It's not 80px height on desktop. The total height is 51px!

![image](https://user-images.githubusercontent.com/17784082/64422598-59b4af80-d09c-11e9-86ea-a77d2a22232b.png)

With a gapping of 15px margin and 1px border thus meeting the spec of 16px spacing.

If you don't want make websites touchscreen working that's your decision. Sorry but it's not gonna happen my side.

**Comment by Samuell1** [comment]
Maybe its less i dont measured it.

Why is there a padding from parent container not a buttons? Like this
![obrázok](https://user-images.githubusercontent.com/3110002/64422948-8faa6180-d0a5-11e9-927c-1e280beb65fa.png)

I make "website" touchscreen working i dont care too much about backend because i know nobody uses backend trough mobile.

**Comment by ayumihamsaki** [comment]
@Samuell1 read this:

![image](https://user-images.githubusercontent.com/17784082/64423080-8d440980-d09d-11e9-8dd8-943e200cec32.png)

**Comment by Samuell1** [comment]
@ayumihamsaki yes i know about about this but thats "recommended". I wanted say by this that mobile isnt first in backend because you dont have many people using it at once like websites have big traffic etc.

**Comment by ayumihamsaki** [comment]
@Samuell1 I got a few clients that use the backend on their ipads.

**Comment by ayumihamsaki** [comment]
To be honest the checkboxes need to be spaced out correctly as well. They have margin-bottom of 10px and I'm going to change them to 16px. My clients feedback told me this is annoying as well.

**Comment by ayumihamsaki** [comment]
This is the final styling (pixel perfect) - for touch screens - ignore the rest.

![image](https://user-images.githubusercontent.com/17784082/64428593-00547c80-d0ac-11e9-90e0-35a2abfb6fcb.png)

**Comment by ayumihamsaki** [comment]
Notes:

There are no instuctions showing people how to add a hint to the checkbox list fields.

https://octobercms.com/docs/backend/forms#field-checkboxlist

e.g.

```markdown
permissions:
    label: Permissions
    type: checkboxlist
    # set to true to explicitly enable the "Select All", "Select None" options
    # on lists that have <=10 items (>10 automatically enables it)
    quickselect: true 
    options:
        open_account: Open account
        close_account: Close account
        modify_account: Modify account
```

Can be done like this:

```markdown
permissions:
    label: Permissions
    type: checkboxlist
    # set to true to explicitly enable the "Select All", "Select None" options
    # on lists that have <=10 items (>10 automatically enables it)
    quickselect: true 
    options:
        open_account: [ 'Open account', 'This is a hint']
        close_account: Close account
        modify_account: Modify account
```

**Comment by ayumihamsaki** [comment]
### Add height property to YAML

e.g.

```json
height: <number>
```

example

```markdown
permissions:
    label: Permissions
    type: checkboxlist
    quickselect: true
    height: 400
    options:
        open_account: Open account
        close_account: Close account
        modify_account: Modify account
```

![image](https://user-images.githubusercontent.com/17784082/64443678-5fc18500-d0ca-11e9-8b92-c719ba890f65.png)

The above example shows a fixed height of 400px and an overflow-y: scroll. If no height is set the widget can be any height.

**Comment by ayumihamsaki** [comment]
I don't understand why but Daftspunk has added a checkbox list in the form examples with the HTML code:

```html
<p class="help-block before-field">What cars would you like in your garage?</p>
```

Yet there is no matching YAML code?

Very strange!

This PR adds the missing code and allows a user to add a `before` and `after` hint to their Checklist widgets. No styling has been added as the code is already in October.

Here is an example screenshot:

![image](https://user-images.githubusercontent.com/17784082/64447195-b5019480-d0d2-11e9-9b41-908703e74327.png)

YAML API code is as follows:

```json
hintBefore: 'hint displayed at the top'
hintAfter: 'hint displayed at the bottom'
```

PR here: https://github.com/octobercms/october/pull/4606

**Comment by ayumihamsaki** [comment]
## Solutions and PR's

1. **Create a checkbox and checkbox list test set** for the test plugin, see here: https://github.com/octoberrain/test-plugin/pull/77

2. Allow checkbox's to have **checked state**, see here: https://github.com/octobercms/october/pull/4578

3. Add **keyboard navigation and focus ring styling** to checkboxes and checkbox lists, see here: https://github.com/octobercms/october/pull/4588

4. **Cleanup checkbox lists**, see here: https://github.com/octobercms/october/pull/4599

5. Add **checkbox list example code** to the doc's, see here: https://github.com/octobercms/october/pull/4600

6. Add missing `hintBefore` and `hintAfter` API to YAML into the checkbox lists widget: https://github.com/octobercms/october/pull/4606

7. Add **Tri-State Nested** checkbox list widget, see here: ---

### Bonus

Updated builder plugin to give a better user experience: https://github.com/rainlab/builder-plugin/pull/299

**Comment by ayumihamsaki** [comment]
### Nested checkbox list api

#### Code example

```markdown
checkbox:
    label: 'Checkbox nested list example'
    type: checkboxlistnested
    quickselect: true
    span: full
    options:
        account: 'Accounts'
        open_account: '-Open an account'
        close_account: '-Close an account'
        modify_account: '-Modify account details'
```

#### Result

![image](https://user-images.githubusercontent.com/17784082/64454395-c6eb3380-d0e2-11e9-800d-2425a38524c9.png)

#### Syntax

```
Hash nested level - label name - hint
```

e.g.

```
['---Welcome', 'this is a Test']
```

Nested level: --- (3 levels depth)
Label: Welcome
Hint: This is a test

**Comment by daftspunk** [comment]
This has become too bloated to process effectively. Please consider chunking down issues and pull requests instead of discussing multiple topics in a single issue, otherwise, one bad idea/change will sink the remainder of the good ideas.

This has been [partially] implemented here: https://github.com/octobercms/october/pull/4599
