### ISSUE TITLE
Is it possible to shift all the contents of /storage directory into another directory.

### ISSUE THREAD

**Issue by maliksajid** [octobercms/october#4580]
Is it possible to shift all the contents of /storage directory into another directory lets say /tmp and configure October accordingly?

I want to upload October to lambda and the only writable folder in aws lambda is /tmp.

thank you

**Comment by maliksajid** [comment]
Can admin mark this question/issue with high priority? 
I need to fix it as soon as possible.

thanks in advance

**Comment by bennothommo** [comment]
@maliksajid Unfortunately this is not high priority, as it's a very specific use case.

You can edit `bootstrap/app.php` and add the following before `return $app` to change the storage directory to one of your choosing:
```
$app->useStoragePath('/tmp');
```

Note that the `/tmp` folder is temporary and will be cleared regularly.

**Comment by Samuell1** [comment]
Shouldnt you connect lambda to AWS S3 for storage?

**Comment by maliksajid** [comment]
@bennothommo  Please look to the changes. I did as you told and to the console error.
![Untitled](https://user-images.githubusercontent.com/32770676/64021084-93416400-cb4c-11e9-8a99-8832226f98d1.png)

**Comment by Samuell1** [comment]
@maliksajid if you move storage folder you need to move content of it too.

**Comment by maliksajid** [comment]
I did so. But still same error. My requirement is to move all the contents of the storage directory to another directory lets say /tmp.
