### ISSUE TITLE
Storage::url returns wrong path with default configuration

### ISSUE THREAD

**Issue by aurelien-roy** [octobercms/october#4581]
- OctoberCMS Build: 458
- PHP Version: 7.3.6
- Plugins Installed: None (completely fresh install)

### Description:
With the default configuration provided by OctoberCMS, the Storage facade returns the wrong path when using the local driver. Here is a minimal example :

```php
// Stores a file in /storage/app/media/file.txt
$file = Storage::put('media/file.txt', 'content');

// Expected URL is : /storage/app/media/file.txt
// Returned URL is : /storage/media/file.txt
Storage::url('media/file.txt');
```

It seems some methods of the Storage facade is not aware that the default file location has been moved to /storage/app (instead of /storage).

This problem can be simply solved by updating the default configuration provided by October. The update consists of adding the 'url' parameter in the local driver configuration in filesystems.php (as shown below), however I'm not sure this is a right way to do it.

**This is the default configuration :**

```
'local' => [
            'driver' => 'local',
            'root'   => storage_path('app'),
        ],
```

**Using this configuration solves the issue (Storage::url returns the expected url) :**

```
'local' => [
            'driver' => 'local',
            'root'   => storage_path('app'),
            'url' => '/storage/app'
        ],
```

### Steps To Reproduce:
1. Fresh install October
2. Put the following code in the demo plugin (Plugin.php)

```php
public function boot(){
        // Stores a file in /storage/app/media/file.txt
        $file = Storage::put('media/file.txt', 'content');

        // Expected URL is : /storage/app/media/file.txt
        // Returned URL is : /storage/media/file.txt
        exit(Storage::url('media/file.txt'));

    }
```

**Comment by LukeTowers** [comment]
@aurelien-roy we should probably do that in the main repo so that new installs can be fixed going forwards but we might have to look into a way we can dynamically set it for installations that haven't done so yet.

**Comment by LukeTowers** [comment]
@aurelien-roy fixed in https://github.com/octobercms/october/commit/02d894f52ba667ae858f0197f2a64b6c9d8eec4a, thanks for the report!
