### ISSUE TITLE
$.request is not a function

### ISSUE THREAD

**Issue by gorny-dev** [octobercms/october#4582]
I got a problem with with AJAX request inside file 'dist/app.js' (created by webpack).

app.js file: 
---------------------------
import 'popper.js'; 
import 'bootstrap';

$(function () {
    $.request('Cart::onAdd', {
        'update': {'cart-items': '.cart-item-wrapper'}
    });
});

that throws an error:
-----
jQuery.Deferred exception: $.request is not a function TypeError: $.request is not a function
    at HTMLDocument.<anonymous> (http://localhost/dental/combine/b71d14df8c4d4ddba2c49a7f4750930f-1567079039.js:1232:5)
    at mightThrow (http://localhost/dental/combine/b71d14df8c4d4ddba2c49a7f4750930f-1567079039.js:9406:29)
    at process (http://localhost/dental/combine/b71d14df8c4d4ddba2c49a7f4750930f-1567079039.js:9474:12) undefined

when i put this in html file (layout.htm)
-----
        <script type="text/javascript" src="{{ [
            '@jquery',
            '@framework',
            '@framework.extras',
            'assets/dist/js/app.js',
            ]|theme }}.js">
        </script>
        {% scripts %}
        <script>
            $(function () {
                $.request('Cart::onAdd', {
                    'update': {'cart-items': '.cart-item-wrapper'}
                });
            });
        </script>
it works correct

{% put script %} also works correct

The problem is with the file generated by webpack
Jquery in webpack is fine

**Comment by LukeTowers** [comment]
What's throwing the error? The browser?

**Comment by Samuell1** [comment]
This is because you need to import framework scripts inside your webpack project too. Webpack doesnt have access to outside imported scripts.

**Comment by bennothommo** [comment]
@gorny-dev `$.request` is provided by our framework JS file, which I believe cannot be loaded as a JS module, so it cannot be imported. You would still need to load jQuery and the framework file like you have in the `layout.htm` example, and then use Webpack for the other scripts you would like to run.
