### ISSUE TITLE
Discussion adding some features and plugins to Markdown editor and Code editor

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4584]
I'm currently trying to update the Markdown editor and Code editor in October. I would like to open this issue to discuss some features and plugins that can be used to enhance these widgets. Plus some discussion on some on-going issues with the ace editor.

### Adding grow function to these widgets

![ezgif-2-d9a731d8b37d](https://user-images.githubusercontent.com/17784082/64035006-9e45c580-cb47-11e9-97ea-fedef7d81c45.gif)

Having a lot of issues trying to get this to work in October, right now it's very buggy! This may well be because of the current version of ace editor and produces a poor result. Hard to explain you can expand the field area pressing 'Enter' and when you press 'Delete' to remove the rows it doesn't do anything until you press 'Enter' again.

> I have set a grow limit of 250 rows this covers all screen sizes and up to a 8K tv screen size. The more rows the worse the browser experience according to ace - however testing 250 code lines was fine. Admins can adjust it if not happy.

@w20k Just wondering if the current version is stopping me from getting this to work, see here pr (not yet merged) https://github.com/octobercms/october/pull/3951

**I believe that is the reason holding me back and I really need to update ACE EDITOR to make Markdown editor and Code editor work.**

An updated PR is found here: [Update Ace Editor from 1.2.6 to 1.4.5 and emmet.js](https://github.com/octobercms/october/pull/4585)

### Overflow feature

Currently October CMS looks like this in testing:

![image](https://user-images.githubusercontent.com/17784082/64035228-26c46600-cb48-11e9-835b-a620c87cbf9c.png)

What you can't see in this screenshot is that in the code editor I have created 500 rows! There is no overflow set up!

I want to turn this on:

![image](https://user-images.githubusercontent.com/17784082/64035384-8458b280-cb48-11e9-8e68-d29b35e813d0.png)

### Dragbar feature

A picture tells a thousand words e.g.

![image](https://user-images.githubusercontent.com/17784082/64035792-925b0300-cb49-11e9-84e9-699535b32f71.png)

In this picture it shows a few interesting things:

1. Dragbar.

2. Nice overflow scrollbar.

3. Allow fullscreen of left or right sections (see the two arrow icons).

![ezgif-2-0fe1fc480a1d](https://user-images.githubusercontent.com/17784082/64036673-a7d12c80-cb4b-11e9-8fd2-e0a77cb2eab4.gif)

### Plugins and features

I believe these features are created with ace editor plugins to extend it. The reason I opened this issue is to discuss these features and see if I'm allowed to add them etc.

(Still need research in how to add them to October)

### This discussion is linked to the PR

This issue is holding up this PR in getting it finished, found here: https://github.com/octobercms/october/pull/4509

### File locations

https://github.com/octobercms/october/blob/develop/modules/backend/formwidgets/markdowneditor/assets/js/markdowneditor.js

https://github.com/octobercms/october/blob/develop/modules/backend/formwidgets/codeeditor/assets/js/codeeditor.js

Note: Rich editor and Code editor are using the `build-min.js` versions:

https://github.com/octobercms/october/blob/develop/modules/backend/formwidgets/codeeditor/assets/js/build-min.js

### Config Ace Editor options

https://github.com/ajaxorg/ace/wiki/Configuring-Ace

### Extensions and plugins

https://github.com/ajaxorg/ace/wiki/Extensions

### Research notes

Grow: https://ace.c9.io/demo/autoresize.html

**Comment by drmzio** [comment]
Speaking of code editors, I've been planning out a complete replacement of ace editor with Monaco Editor (https://microsoft.github.io/monaco-editor/).

The only downside is that it isn't supported on mobile. But that doesn't concern me as much since October CMS isn't optimized for mobile anyway.

**Comment by Samuell1** [comment]
@drmzio Yep and aditing code on mobile is pain to do soo it should be fine.

**Comment by bennothommo** [comment]
@drmzio I made a comment about Monaco in [another issue](https://github.com/octobercms/october/issues/4545#issuecomment-521130015) - basically, I like it (and VSCode as well), but given it's still in version 0, it's implied it's still in beta and could change wildly in the foreseeable future so I was personally wary of using in October currently. I'm also trying to save @ayumihamsaki from having yet another JS plugin that goes out-of-date quickly :P

**Comment by ayumihamsaki** [comment]
About replacing Ace editor with Monaco, in the other github issue I gave a +1 for the idea of changing over to Monaco.

BUT

Upgrading to Monaco will be very, very, very **_difficult_**. You will have to change many files in October and many widgets. Their are many custom ace editor files in October. The change-over will not be easy, you will be looking at roughly 450 - 500 files, needed to be changed or removed. For example you will have to completely re-write the Markdown editor, the Code editor, the Rich editor etc. the list goes on and on.

We are using Ace version 1.2.6 right now. Looking at Ace version 1.4.5 it's almost the same as Monaco and there are some plugins out there which make ace editor even more like Monaco.

Lastly, backwards compatibility, I was even thinking of haveing noth of them running in October and having an option in the config files to be able to choose which editor you want to use.

**Comment by ayumihamsaki** [comment]
### Notes

Grow feature has been added to PR: https://github.com/octobercms/october/pull/4509

When that PR and the Ace Editor PR https://github.com/octobercms/october/pull/4585 are merged, can think about sorting out the overflow issues, dragbar and any other enhancements.

**Comment by LukeTowers** [comment]
@ayumihamasaki2019
