### ISSUE TITLE
Backend list filter group apply record outside list problem

### ISSUE THREAD

**Issue by mkinternet** [octobercms/october#4592]
- OctoberCMS Build: 458
- PHP Version: 7.2
- Database Engine: 
- Plugins Installed: playground

### Description:
If am i right gourp filter field returns 500 records: https://github.com/octobercms/october/blob/477502d3335044d29dcc978a9cf10cc344b29e39/modules/backend/widgets/Filter.php#L372

If i want to apply record wchich is not in group list i can find it but i cannot apply it

### Steps To Reproduce:
1. Create model (eg: cities int id , varchar city)
3. Seed with over 500 records. (i had 2000).
4. Add gropup filter type.

scopes:
    cities:
        label       : City
        type        : group
        modelClass  : Mkinternet\Cities\Models\Cities
        nameFrom    : city
        conditions  : id IN (:filtered)    

4. Pick first element. Buttons "Apply" and "Clear" appear. Records are filter by picked element.
5. Find element form outside list. Element is found. Pick it and click "Apply".
6. Records are still picked by one element picked first.

**Comment by LarBearrr** [comment]
This issue has been raised a few times already. See #2602, #3202.

**Comment by LukeTowers** [comment]
@bennothommo have we fixed the stale actions markdown formatting yet? Those are supposed to be two separate bullet points AFAIK

**Comment by bennothommo** [comment]
@LukeTowers I had fixed it a few weeks ago in `master`, but I think Sam reverted my change when he fixed the branch up. I'll add it to `develop` and then it can be brought in with the next stable release.

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/517c588ef7224941af761ba4df4f329dd0a442db
