### ISSUE TITLE
Help me guide to use Laravel package in OctoberCMS, please?

### ISSUE THREAD

**Issue by 2jiwon** [octobercms/october#4593]
Hello, again.

Thank you for your supports, I was able to install [yajra/laravel-datatables](https://github.com/yajra/laravel-datatables) package. 

I also read [this article](https://luketowers.ca/blog/how-to-use-laravel-packages-in-october-cms-plugins/) by Luke Towers and I tried my best as he wrote. 
So far there are no errors, so I believe everything is good to go further.

Now, I'm on the next step using it, but I'm completely lost here.

[The document of the package](https://datatables.yajrabox.com/starter) says I should make controller but it doesn't work.
So I tried to make controller inside of my plugin, then so far no errors.
However, I'm not sure this is the right way to do.

The document of the package also says I have to make methods like below inside of the controller.
```php
public function getIndex()
    {
        return view('datatables.index');
    }

    /**
     * Process datatables ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function anyData()
    {
        return Datatables::of(User::query())->make(true);
    }
```
But it return the 'view' which means blade template as I understand, so I don't know how to deal with this. 
I'm using this datatable package to display data in the frontend. 
What should I do here? I'm a novice developer and not familiar with neither Laravel nor OctoberCMS. 

Please, help me get me through this?
I'm so sorry if this place is not for these kinds of questions, but I'm really lost.

**Comment by bennothommo** [comment]
@2jiwon I would recommend joining us on Slack if you're looking for support like the above - https://octobercms-slack.herokuapp.com/. There's a lot more people who may be available to assist there. :)

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

**Comment by 2jiwon** [comment]
Okay, I joined slack channel. I'm sorry.

**Comment by daftspunk** [comment]
This is described in the documentation: https://octobercms.com/docs/help/publishing-packages#laravel-packages
