### ISSUE TITLE
Error if session expired

### ISSUE THREAD

**Issue by Trysystems** [octobercms/october#4595]
- OctoberCMS Build: 458
- PHP Version: 7.2
- Database Engine: mysql

### Description:
If the login page opened a long time, and session expired, there is error 
ErrorException: hash_equals(): Expected known_string to be a string, null given in /modules/backend/classes/Controller.php:795

**Comment by LukeTowers** [comment]
Fixed in https://github.com/octobercms/october/commit/0240c21af6e999742c49bf00c57e3c6f5548eebd
