### ISSUE TITLE
Incompatible Declaration when Exporting Themes

### ISSUE THREAD

**Issue by drmzio** [octobercms/october#4597]
- OctoberCMS Build: 458 
- PHP Version: 7.2

### Description:

An error when trying to import/export themes appears. This happens on all October 458 versions. See screenshot below for more details.
![](https://cl.ly/00c2bfaec196/%255Bdf1c97e70ae43e07f061230cce1143ff%255D_Image%2525202019-09-04%252520at%2525204.57.45%252520PM.png)

### Steps To Reproduce:

1. Install October
2. Navigate to "Front-end theme"
3. Try exporting any theme

**Comment by bennothommo** [comment]
Thanks for the report @drmzio. Fixed as of https://github.com/octobercms/october/commit/5723cd4b2ae1b216518da8da42ca78b3d0aef766.

**Comment by cdreier** [comment]
Hi, how can i update to this fix? 
I just did a fresh install of october and i am on build-number 458 with the exact same bug with no updated available :(

**Comment by LukeTowers** [comment]
@cdreier set enableEdgeUpdates = true in config/cms.php and update to build 459.

**Comment by cdreier** [comment]
@LukeTowers thanks a lot for that fast help!

**Comment by LukeTowers** [comment]
@cdreier no problem!
