### ISSUE TITLE
Relation behavior in popup form view does not work as expected

### ISSUE THREAD

**Issue by danielbidala** [octobercms/october#4602]
I have **Orders** and **Orderitems** models. (Order hasMany Orderitem)

In Orders list view I override the the recordOnClick and call the below controller method:

```
	public function onListPreview() {
		
		$this->preview(post('id'));
		return $this->makePartial('partials/preview');

	}
```
This works just fine. When I click on list row, the popup open with preview of the Order and I see the relation manager too.
The problem is that, when I click on row in relation manager I get the following error:

**Relation behavior used in Author\Plugin\Controllers\Orders does not have a model defined.**

If I don't use popup I can manage orderitems as expected. (the relation config is OK) Any suggestion?

**Comment by w20k** [comment]
@danielbruni relation manager doesn't work in popups. You should make a custom implementation.
An article that could help you out: https://octobercms.com/support/article/ob-21

Simple example (_in constructor_):
```
if (Request::ajax()) {
            $this->asExtension('FormController')->create();
}
```

**Comment by danielbidala** [comment]
Thank's @w20k , your suggestion helped me to solve my problem.
