### ISSUE TITLE
Ayumi Hamasaki please contact us via email

### ISSUE THREAD

**Issue by daftspunk** [octobercms/october#4610]
To the person named *Ayumi Hamasaki*, who has now disappeared, please contact October CMS via email address hello@octobercms.com

Thank you

**Comment by ayumihamasaki2019** [comment]
Hi, I sent you an email. This is my new account. Sorry our company got hit with some ransomware attack and we didn't pay it. I also noticed my github accounts and our company social media accounts got deleted. My backup social passwords were on a thumb drive that has ransomware on it. Totally sucks!

Let me know how I can help in anyway, with my pr's and old account data.

**Comment by LukeTowers** [comment]
@ayumihamasaki2019 you should be able to get in touch with Github support and see if they can restore your old accounts.

**Comment by ayumihamasaki2019** [comment]
Just waiting for github support ..

![image](https://user-images.githubusercontent.com/55155131/64727923-db0fa600-d4d1-11e9-8761-28ec459ce6a1.png)

**Comment by ayumihamasaki2019** [comment]
@LukeTowers not getting any help from Github, pretty rubbish company! Let me know if any of the PR's need updating or more work, I will manually just move those ones to this account. Can't be bothered to wait for the famous Github support (they probably tell me to press crtl + alt and delete to reset my account).
