### ISSUE TITLE
October Assets Not loading

### ISSUE THREAD

**Issue by iamsajidjaved** [octobercms/october#4619]
I created a simple PHP application having only 2 files. Index.php and style.css. I zipped both files and uploaded to lambda directly without using s3. I saw that php is working fine but style.css is not loading. Style.css throws 403 error in the console.

I thought its permission related issue because 403 means unauthorized. So, I gave full administrative access to my lambda. Giving full access is not realistic but I was finding that its permission related issue or not. But unfortunately I got the same 403 error.

Then I found on Google that I should upload style.css to s3. I did so. I uploaded my style.css to s3 and copied the absolute exact file url and used in my index.php. I saw that style.css loaded and worked fine.

**My question is can we upload all our October js/css to s3 and link easily?**

I think it's very easy to do so with a theme but what about the assets of the modules of October . As you know in October we have different modules like backend, cms & system that are placed inside the modules directory.

My goal is to host October on aws lambda

thank you

**Comment by maliksajid** [comment]
@LukeTowers  thank you for your reply. 

Now my OctoberCMS project is here on lambda https://d2l3j8q25qk4ii.cloudfront.net.
But I'm facing an issue. When I visit https://d2l3j8q25qk4ii.cloudfront.net/backend it always says **Database missing**. I'm using RDS MySQL which is publically accessible and October is working fine locally with it.

So, can you tell me why I'm getting this error message on lambda?
@LarBearrr @LukeTowers 

Thank You
