### ISSUE TITLE
Add new argument to filterFields method to decide if it's called by field onChange or formRender

### ISSUE THREAD

**Issue by danielbidala** [octobercms/october#4620]
Maybe there is a simple solution to my problem but I'dont find it. Anyway it would be nice if we could know which "event" called the filterFields method.

Imagine you have a `product`, an `order` and an `orderitem` model. Orderitem is added with relationManager to `order`.

When add `orderitem` you can select the product with recordFinder. Once you selected, the price field (amount & currency) is updated in orderitem based on product price (with filterFields method) but you can modify the updated price field according to you needs. Next time when you edit `orderitem` your custom price is overrode with product price.

As a workaround I use the below filterFields method but it has some limitations:

```
public function filterFields($fields, $context = null)
{
	if($context === 'create')
	{
		$product_id = $fields->product_id->value;
		$product = Product::find($product_id);

		$fields->price->value['amount'] = $product ? $product->amount : 0;
		$fields->price->value['currency'] = $product ? Currency::find($product->currency_id)->currency_code : 'HUF';

	}

	if($context === 'update')
	{
		if ($this->product_id != $this->original['product_id'])
		{
			$product_id = $fields->product_id->value;
			$product = Product::find($product_id);

			$fields->price->value['amount'] = $product ? $product->amount : 0;
			$fields->price->value['currency'] = $product ? Currency::find($product->currency_id)->currency_code : 'HUF';

		}

		if ($this->product_id == $this->original['product_id'])
		{
			$product_id = $fields->product_id->value;
			$product = Product::find($product_id);

			$fields->price->value['amount'] = $this->original['amount'];
			$fields->price->value['currency'] =  Currency::find($this->original['currency_id'])->currency_code;
		}
	}
}
```

**Comment by LukeTowers** [comment]
What are the limitations you're running into with the method you currently have? Also note, there is a local model event that you could dynamically listen to based on the context you're in: https://octobercms.com/docs/api/model/form/filterfields.
Example:

```php
public function relationExtendManageWidget($widget, $field, $model) {
    $model->bindEvent('model.form.filterFields', function ($form, $fields, $context) use ($model) {
        // do your stuff meant for this relationship manage context
    });
});
```

**Comment by danielbidala** [comment]
Thanks for your interest @LukeTowers. The limitation is that, if you edit `orderitem` you can't get the product price if you've previously overridden that.

At the moment I have no idea how can I use the suggested model event to achieve what I want. I'm a beginner :(
