### ISSUE TITLE
Sending JSON Payload with Http Library Issue

### ISSUE THREAD

**Issue by mahony0** [octobercms/october#4624]
- OctoberCMS Build: 458
- PHP Version: 7.3.9
- Database Engine: MySql
- Plugins Installed: RainLab.User-v1.5.0

### Description:
I want to send JSON data with curl using Http lib PUT method (October\Rain\Network\Http).
On this line: https://github.com/octobercms/library/blob/4bda08c826fc3ac1efba32fa8799d25ced14191f/src/Network/Http.php#L279 it's immediately using http_build_query function on $this->requestData.

### Steps To Reproduce:
I want to send curl like:
```curl
curl -H 'Accept: application/vnd.twitchtv.v5+json' \
-H 'Authorization: OAuth xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
-H 'Content-Type: application/json' \
-d '{"channel": {"status": "The Finalest of Fantasies", "game": "Grand Theft Auto V"}}' \
-X PUT 'https://api.twitch.tv/v5/channels/11122233'
```
and using Http lib:
```php
$updateChannel = Http::put('https://api.twitch.tv/v5/channels/'.$channelId, function($http) {
    $http->header('Accept', 'application/vnd.twitchtv.v5+json');
    $http->header('Client-ID', $this->clientId);
    $http->header('Authorization', 'OAuth '.$this->oauth);
    $http->header('Content-Type', 'application/json');

    $payload = [
        'channel' => [
            'status' => $this->newTitle,
            'game' => $this->newGame,
        ]
    ];

    // like this: value is null
    $http->data(json_encode($payload));

    // or like this, JSON malformed: 0=%7B%22channel%22%3A%7B%22status%22%3A%22The+Finalest+of+Fantasies%22%2C%22game%22%3A%22Grand+Theft+Auto+V%22%7D%7D
    $http->data([json_encode($payload)]);

    $http->setOption(CURLOPT_RETURNTRANSFER, true);
});
```
I'm using Http Lib for all GET requests and don't want to write another curl method for just PUT and POST requests. I don't know is this a bug or there's a workaround for this.

If this is a bug, I think we can check header for **Content-Type** and respectively use http_build_query or not.

**Comment by mahony0** [comment]
Ok, I got a simple "hack" which is effective only with PUT requests. This is really a temporary solution and not working with POST.

You can set JSON string as postdata like this:
```php
$http->setOption(CURLOPT_POSTFIELDS, json_encode($payload));
```
but you should never assign something to data with $http->data() because of https://github.com/octobercms/library/blob/4bda08c826fc3ac1efba32fa8799d25ced14191f/src/Network/Http.php#L282 is immediately changing CURLOPT_POSTFIELDS data if there's something assigned to **$this->requestData**

**Comment by LukeTowers** [comment]
@mahony0 I'd probably recommend you just use Guzzle unless you're able to fix this issue yourself in a well written PR. The included Http library in October isn't really meant to be super widely used or robust, it's more of an included shortcut for some core functionality. As soon as you get into more advanced use cases it's usually better to just use Guzzle.

**Comment by mahony0** [comment]
Ok, I'll go with that way. Thanks.

**Comment by Samuell1** [comment]
@mahony0 @LukeTowers Looks like there will be in core of laravel new Http library thats uses Guzzle as base https://laravel-news.com/zttp-is-coming-to-laravel-7

**Comment by LukeTowers** [comment]
@Samuell1 interesting, so we should see that in October in another three years then 😂

**Comment by Samuell1** [comment]
@LukeTowers maybe yes 😄 but i think there is little changes between 6 and 7 then you can simply just update it and use that new lib
