### ISSUE TITLE
Media Upload File Size Limiter

### ISSUE THREAD

**Issue by b8ne** [octobercms/october#4631]
I have read an issue on the Forum about this, but adding it here so it can be tracked.
The original solution was to update the Dropzone limit under modules/ however that would be lost under any updates.
Would be great to have a config available in the back-end settings.  Even better would be having the ability to fine tune the value based on file size. i.e. Some client's may need to upload large PDF's, however I want to limit png/jpg upload to 2mb.
I understand this can be done in PHP config, but it is difficult to do in shared instances.

**Comment by LukeTowers** [comment]
@b8ne could you link to the forum discussion?

**Comment by b8ne** [comment]
@LukeTowers https://octobercms.com/forum/post/increase-upload-limit-in-backend?page=1

**Comment by LukeTowers** [comment]
Support for this was added in https://github.com/octobercms/october/commit/cc7d595fffdb719504b91c2c6b7da629aaad2788 to the FileUpload form widget, although I don't believe it applies to the MediaManager as of yet.

**Comment by b8ne** [comment]
Any ideas on what you'd be looking for to get it working with MediaManager?  I need this for clients so would be happy to work on it and submit a PR.

**Comment by LukeTowers** [comment]
> fine tune the value based on file size. i.e. Some client's may need to upload large PDF's, however I want to limit png/jpg upload to 2mb

Are you actually trying to prevent the user from using really large pictures that then get used on the frontend slowing down the site? If so, I recommend you just use https://github.com/toughdeveloper/oc-imageresizer-plugin
