### ISSUE TITLE
500 error when setting memcached as the default cache store

### ISSUE THREAD

**Issue by maartenmachiels** [octobercms/october#4636]
- OctoberCMS Build: 458
- PHP Version: 7.3.9
- Database Engine: MySQL
- Plugins Installed: n/a

### Description:
When setting `memcached` as the default cache store in `config/cache.php`, a 500 error is thrown. The logs state the following error message:

```
mod_fcgid: stderr: PHP Fatal error: Uncaught Error: Class 'Memcached' not found in /var/www/vhosts/xxxx.com/subdomains/testcase/vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php:69

mod_fcgid: stderr: #0 /var/www/vhosts/xxxx.com/subdomains/testcase/vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php(48): Illuminate\\Cache\\MemcachedConnector->createMemcachedInstance(NULL)

mod_fcgid: stderr: #1 /var/www/vhosts/xxxx.com/subdomains/testcase/vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php(21): Illuminate\\Cache\\MemcachedConnector->getMemcached(NULL, Array, Array)

mod_fcgid: stderr: #2 /var/www/vhosts/xxxx.com/subdomains/testcase/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(171): Illuminate\\Cache\\MemcachedConnector->connect(Array, NULL, Array, Array)

mod_fcgid: stderr: #3 /var/www/vhosts/xxxx.com/subdomains/testcase/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(105): Illuminate\\Cache\\CacheManager->createMemcachedDriver(Array)

mod_fcgid: stderr: #4 /var/www/vhosts/xxxx.com/subdomains/testcase/vendor/laravel/f in /var/www/vhosts/xxxx.com/subdomains/testcase/vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php on line 69
```

My system admin tells me the Memcached PECL package is installed as [per the documentation](https://octobercms.com/docs/services/cache) 

Is this a software issue in October CMS? Is there an additional library that needs to be installed? Or does this error imply that there is something wrong with my installation of Memcached? Please advise.

### Steps To Reproduce:
1. Install Memcached
2. Set memcached as the default cache store in cache.php
3. See error

Thanks in advance.

**Comment by Samuell1** [comment]
Maybe this is issue? https://stackoverflow.com/a/2659060

**Comment by maartenmachiels** [comment]
Thanks, I'll investigate and report back asap.

**Comment by dhcmega** [comment]
Hi @maartenmachiels 
Have you found a solution for this problem?
Thanks!

**Comment by maartenmachiels** [comment]
Hi @dhcmega , unfortunately I've never found the answer. I talked it over with our hosting provider, but it has been put off... Are you experiencing the same issue?

**Comment by dhcmega** [comment]
Hi, yes, thanks for getting back to me.
In my case, it works ok for web requests, but I have that exact error for api requests, mystery...

This is how I test it in case you ever need it. There are 3 commands `new`, `connect` and `get`. Despite of the getOption() error, it works ok.

```
$ rlwrap php artisan tinker
Psy Shell v0.9.12 (PHP 7.3.11 — cli) by Justin Hileman
>>> $cache = new \Memcached();
=> Memcached {#4320
     ⚠: Symfony\Component\VarDumper\Exception\ThrowingCasterException {#4322
       #message: "Unexpected ErrorException thrown from a caster: Memcached::getOption(): no servers defined",
     },
   }
>>> $cache->addServer('/home/vpssigesedev/run/memcached/memcached.sock', '0');
=> true
>>> $cache->getAllKeys();
=> []
```

**Comment by zanderwar** [comment]
If `Memcached` isn't found, there is no other explanation other than it isn't installed, or isn't enabled.
