### ISSUE TITLE
Exception in blog post

### ISSUE THREAD

**Issue by alancunnane** [octobercms/october#4638]
We have just begun to have issues with our blog; when clicking on the link from the main blog page, it returns the message 

Type error: Argument 2 passed to RainLab\Blog\Classes\ComponentAbstract::getComponent() must be of the type string, null given, called in /var/www/html/plugins/rainlab/blog/components/Post.php on line 108
/var/www/html/plugins/rainlab/blog/classes/ComponentAbstract.php line 28

This has only happened in the past day or so; I updated October and plugins using the dashboard settings panel last week, but it seems to have happened a few days after that, in any case.

Apparently the categoryPage value being passed through is null, although I can't see how that can be the case.  Changing category hasn't helped.

Any assistance will be greatly appreciated - thanks!

Alan Cunnane

**Comment by LukeTowers** [comment]
This needs to be posted on https://github.com/rainlab/blog-plugin.

**Comment by alancunnane** [comment]
Apologies!
