### ISSUE TITLE
UpdateManager throwing CURLOPT error from plugin's controller

### ISSUE THREAD

**Issue by LarBearrr** [octobercms/october#4639]
- OctoberCMS Build: 459
- PHP Version: 7.3
- Database Engine: MySQL

### Description:
I'm creating this issue per @LukeTowers request in advance of the 460 release. 

When navigating to Settings > Updates & Plugins > Install Plugins, a CURLOPT error is thrown.

### Steps To Reproduce:
1. Install October with composer
2. Use the develop branches
3. Run composer update

I'm actually getting this error from the command line now as well:
![image](https://user-images.githubusercontent.com/28734844/65650325-01ecd280-dfd0-11e9-9205-dbc5be07fc9b.png)

However, I have been unable to reproduce again through the backend since I was originally notified by a colleague this morning of the error. 

The official error is: `52 parameter must be a CURLOPT constant or equivalent integer`

I traced it back some to the UpdateManager, and then to the Http facade [L#182](https://github.com/octobercms/library/blob/4bda08c826fc3ac1efba32fa8799d25ced14191f/src/Network/Http.php#L182) in the Rain library.

When I was debugging this morning, I set `$options = [];` and it stopped throwing the error. For some reason though, when I removed this line and refreshed the page, the error went away.

**Comment by bennothommo** [comment]
@LarBearrr I know what it is - I will be rolling out a fix very shortly. :)

**Comment by LarBearrr** [comment]
@bennothommo Thank you sir, just wanted to log it for the record. Want me to close or will you do that when you push the fix?

**Comment by bennothommo** [comment]
@LarBearrr I'll close this once the commit is made.

**Comment by bennothommo** [comment]
@LarBearrr This should now be fixed by https://github.com/octobercms/library/commit/ad7afd5e750d3aadcc1a4f2104378a8987654e77. Please let me know if there's any further issues.
