### ISSUE TITLE
Issue with new JSON parser / bulk actions on the plugin update manager

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#4647]
- OctoberCMS Build: 459
- PHP Version: 7.0
- Database Engine: MySQL

### Description:
The new JSON parser does not allow for JS to be run as a part of the parsing process which causes all existing "list bulk action type" AJAX requests using the `data-request-data` attribute to break entirely. See https://github.com/octobercms/october/search?l=HTML&q=listWidget%28%27getChecked%27%29 for all existing cases in the OctoberCMS core, and know that this is an established pattern that may exist in third party plugins. 

Specifically the line of code that is now broken under the new parser is as follows:
```htm
data-request-data="checked: $('.control-list').listWidget('getChecked')"
```

>**Note**: The more established process as shown below is not affected as it does the data processing in an attribute that's specifically designed to have the JS within it run:

```html
onclick="$(this).data('request-data', { 
    checked: $('#<?= $this->relationGetId('view') ?> .control-list').listWidget('getChecked')
})"
```

### Possible Fixes
We basically have two separate fixes that we could apply: 

1. Fix the Update Manager to use onclick instead of relying on JS execution of data-request-data.
2. Change the JSON parser to allow for JS execution. This is not as desirable as it defeats the purpose of having a custom JSON parser in the first place, although not doing it _could_ have backwards compatibility implications.

**Comment by bennothommo** [comment]
@LukeTowers I prefer option 1. I think if you need to use JavaScript to populate the data, you should be using the JavaScript AJAX framework as well, and keep the HTML attributes framework for simple JSON content.

**Comment by w20k** [comment]
@LukeTowers I do feel like option 1 is better in the long run. Otherwise, there was no point in having an external JSON parser library.

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/479fa0960693a7c375f4d73ea2bf4e01121a9312
