### ISSUE TITLE
Missing relatioship type 'HasOneThrough'

### ISSUE THREAD

**Issue by paishin** [octobercms/october#4649]
Laravel provides HasOneThrough relationship ([](https://laravel.com/docs/5.8/eloquent-relationships#has-one-through)) types to connect two models via a pivot table in a one-to-one relationship.
October seems to support hasManyThrough relationships but not hasOneThrough.

Are there plans to support this in october or was it omitted deliberately?

**Comment by paishin** [comment]
This feature was introduced in 5.8
https://laravel.com/docs/5.8/eloquent-relationships#has-one-through

**Comment by LukeTowers** [comment]
We'll deal with this as a part of #4381 then.

**Comment by paishin** [comment]
Thank you so much for the quick reply

**Comment by bennothommo** [comment]
Implemented as part of https://github.com/octobercms/october/pull/4893.
