### ISSUE TITLE
PHP 7.0 compatibility issue

### ISSUE THREAD

**Issue by acasar** [octobercms/october#4659]
- OctoberCMS Build: ### 459
- PHP Version: 7.0

### Description:
In theory PHP 7.0 is still supported. I noticed some compatibility issue here: https://github.com/octobercms/october/blob/master/modules/backend/traits/PreferenceMaker.php#L27

Void return types were only added in PHP 7.1, so in PHP 7.0 we get this exception:

![image](https://user-images.githubusercontent.com/6329543/66124789-a16c1f80-e5e5-11e9-8beb-9dde35c92e9a.png)

### Steps To Reproduce:
- Open any list (using ListController)
- Change list preferences (e.g. "Records per page")
- Click "Apply"

**Comment by bennothommo** [comment]
Fixed in https://github.com/octobercms/october/commit/c3d99b2acf0a65e7af5198c219003eba8f0b7800. Will be released with build 460.
