### ISSUE TITLE
Grid widget needs autocomplete option

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#466]
I'd love to see `autocomplete: auto|always` option added to the grid widget. This is useful, for example, when displaying a list of countries or states that won't be too long. When autocomplete is set to `always`, cells become combobox/dropdown fields, only allowing you to select from the list. This also means you don't need to type into the list first before the autocomplete list appears.

**Comment by amdad** [comment]
Was this implemented?

**Comment by Flynsarmy** [comment]
I don't believe so. Would have been super handy though.

**Comment by amdad** [comment]
It would, It would.
