### ISSUE TITLE
Roadrunner PSR-7 workers

### ISSUE THREAD

**Issue by InfernalRabbit** [octobercms/october#4681]
Is there a valid solution for using October behind Roadrunner appserver? Laravel enabled solutions works but not at all cases - there are a lot of bugs and undeclared features when using as RR's service

**Comment by LukeTowers** [comment]
@InfernalRabbit does it work with Laravel? October is on 5.5 right now but will be upgrading to 6 in the near future.

**Comment by InfernalRabbit** [comment]
@LukeTowers Yes, it works! But i have some troubles with functiuonality. For example i tried to log in into admin panel and some of workers notify me that i logged in (worker, which push me into panel), and another one says that i tryed to log in and my password is incorrect. That happens every time when my hit been processed by "errored" worker
