### ISSUE TITLE
How to make images uploaded via S3 public

### ISSUE THREAD

**Issue by BlackOnix** [octobercms/october#4688]
I connected S3 to my october project.
```
s3' => [
    'driver' => 's3',
    'key'    => 'key',
    'secret' => 'secret',
    'region' => 'us-east-1',
    'bucket' => 'www.domain'
],

```
```
storage' => [
        'uploads' => [
            'disk'   => 's3',
            'folder' => 'uploads',
            'path'   => 'https://cdn.domain/uploads',
        ],
        'media' => [
            'disk'   => 's3',
            'folder' => 'media',
            'path'   => 'https://cdn.domain/media',
        ],
    ],
```

All worked. But how do I automatically make images public in s3 when loading.

**Comment by LukeTowers** [comment]
I think it's a config item that you add to the storage driver config? Google how to do it in Laravel and the answer should work for October

**Comment by BlackOnix** [comment]
I tried to do it like this:
         'visibility' => 'public',
But I get error 403 from amazon

**Comment by LukeTowers** [comment]
it might be under `attributes => visibility => public`. Google around for the specific error you're having.

**Comment by Samuell1** [comment]
I recommend to check your file if is really public and if its then you have incorrect ACLs for your bucket.

**Comment by drmzio** [comment]
Are you uploading files using the Storage facade or via Media Manager?

**Comment by Samuell1** [comment]
@drmzio issue is that S3 from default now block every public access ACLs he needs to allow it i posted link to it.
