### ISSUE TITLE
Would october consider switching to use Google custom search instead

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4692]
The october cms website currently uses algolia for it's search in the doc's.

Personally I think algolia is rubbish! For years I have had really poor search results from it and have to do my searching of the doc's in Google search engine and then go back into the website via the SERP result.

Below are two examples of how bad algolia search results are:

### Example 1

![image](https://user-images.githubusercontent.com/55155131/66719830-9a66bd80-edec-11e9-95f8-e554b178f055.png)

Above: We have results from the same web page and not different web pages (five results pointing to the `|page` doc's web page). This is annoying as the results are displaying not even the correct web page.

![image](https://user-images.githubusercontent.com/55155131/66719850-c4b87b00-edec-11e9-81ed-81fc6654cceb.png)

Above: Same search in Google, here we get different web pages (one result pointing to the `|page` doc's web page and three other pointing to different web pages). The `Router` (first result in Google) is actually the correct result.

### Example 2

![image](https://user-images.githubusercontent.com/55155131/66774276-23e3c180-eeb9-11e9-8c04-a7baa4a3d0b8.png)

Above: We don't get any results at all.

![image](https://user-images.githubusercontent.com/55155131/66774319-3f4ecc80-eeb9-11e9-9d59-bb83715d59c2.png)

Above: We get lots of results, note I wrote on purpose the search query "**checklist**" instead of "**checkbox list**". Google is clever enough to still find the correct web page result.

---

My point to this github issue is to ask the admin's to remove algolia search and switch to Google Custom Search.

Maybe people can **+1** this post to switch over to Google Custom Search and we can get some better results.

Google Custom Search: https://cse.google.com/cse/

Honestly, algolia search is completely useless for **_code related_** searches!

**Comment by amdad** [comment]
Not to mention it does not cover [docs/api](https://octobercms.com/docs/api)

I don't know if google CSE is best replacement. I just agree Algolia current implementation here (widget) sucks. When I think about how it limits results to **5**❗️❓   I really feel I'm gonna 🤢

**Comment by drmzio** [comment]
I think octobercms.com uses an older version of Algolia. It could definitely use an update.

**Comment by daftspunk** [comment]
It is true Google is a superior search engine and you can always use both. Will look at what is involved next time we revisit the website documentation. Thanks for the suggestion!
