### ISSUE TITLE
Introduce Marketplace Annual Fee for Paid Products

### ISSUE THREAD

**Issue by drmzio** [octobercms/october#4695]
As of the time of writing, anybody can create and publish a plugin on the Marketplace, but what's stopping crooks from copying other (possibly free) plugins and selling them for profit? Not too long ago, I found a duplicate plugin on the Marketplace and it somehow passed the quality guidelines?

## Why the annual fee
Currently, paid plugins are listed on the Marketplace indefinitely, regardless of whether it works on the current version of OctoberCMS or not. There is a paid plugin for $100 USD that hasn't had an update since **last year** and it worries me that I may throw away those $100 on a plugin that does not work on the latest version of OctoberCMS. The only way to find out is to either buy the plugin and try it out myself - OR - sending a message to the author.

According to the [refund policy](https://octobercms.com/help/terms/refund):

> In the unfortunate event that you purchase an item that is intentionally misleading, we will ensure the prompt removal of the item and will do our best to assist you with the return of the purchase amount from the author.

The keywords here are **intentionally** and **misleading**. A plugin can be 100% legit but can also be YEARS OLD. There is no guarantee that you will receive your refund amount, even if the plugin is incompatible with latest version of OctoberCMS.

At least with the annual fee, October can use this fee to invest in a screening process (similar to [Apple's App Store review process](https://developer.apple.com/app-store/review/)) and have every paid plugin go through this quality check every year, which tests if the plugin still works on the latest version of October.

## Solution

Plugin | Annual Fee
------------ | -------------
Free | $0
Paid | $2 per listing, per year

- Free plugins are exempt from the annual fee to publish and distribute on the Marketplace.
- Paid plugins should require authors to pay an annual fee to publish, distribute, and sell their plugins on the Marketplace.
  - Authors that fail to pay the annual fee with be given a grace period of 30 days to pay the fee or have the plugin be de-listed from the Marketplace.
  - October can either charge Authors a flat fee or per plugin (For example: Author has 5 paid plugins, each plugin is a $2 listing fee, 5 x $2 = $10 USD per year)
  - October still receives a 30% cut for every plugin sold OR reduced cut of 15% for every plugin sold.

I know this just seems like a headache, but I want October to succeed in the long run. October has a responsibility to ensure that the Marketplace does not become a wasteland with millions of plugins, dead or alive, with little or no review process. This annual fee may also be applied to paid themes as well.

**Comment by 36864** [comment]
I touched on the subject of abandoned plugins briefly as part of the discussion on bringing paid subscription models for plugins at https://github.com/octobercms/october/issues/4662#issuecomment-541586831

A fee like this would be a barrier to entry for some devs, while any scam worth pulling would surely be worth more than $2 a year. A neglectful dev getting $100 every couple months for an old plugin also won't mind the $2 fee.

I believe automatically disabling purchases on old plugins, and a system for reporting broken / duplicate / malicious plugins would be best, at least while the october ecosystem is still relatively small.

**Comment by bennothommo** [comment]
I personally wouldn't like to see a listing fee precisely because the October ecosystem is quite small - the barrier needs to be as low as possible to encourage the marketplace to grow.

While the visibility of this email could be made more apparent in the marketplace, we do already have a way of reporting plugins that are broken, duplicate or malicious - just send an email to hello@octobercms.com. This lets @daftspunk and @alekseybobkov know to re-investigate the plugin if the plugin has been abandoned and no longer works, or looks to be a scam.

There's also nothing inherently wrong with a plugin being years old too - some plugins simply don't need any additional work and still continue to work with October CMS to this day. The maintainers of October CMS are always aiming to keep updates backwards-compatible in order to ensure plugins made years ago still work.

**Comment by drmzio** [comment]
I'm going to close this issue as some of you have brought up some good points. The Marketplace is still relatively small and the annual fee could deter new developers.

**Comment by SebastiaanKloos** [comment]
I think you should be able to report a plugin right on the Marketplace. You can add a message why you think the plugin should be removed
