### ISSUE TITLE
[Question] Connection Error 522 on an AJAX POST request method

### ISSUE THREAD

**Issue by ayumihamasaki2019** [octobercms/october#4705]
Want to ask some advice from the clever October community.

We are in the middle of building an Anti-Virus and Firewall application for October CMS, which will run inside October in the backend.

Everything was going ok and when a user clicks on a button to start the scan of their October website the scan starts running using the October AJAX post request method.

When I started coding, I used a small virus definitions file - this all worked fine.

Now I have upgraded the application to using a full sized virus definitions file the scan takes longer. However, testing on a Cloudflare server we soon discovered that they limit the AJAX post requests up to 60 seconds now (in the past it was 90 seconds).

![image](https://user-images.githubusercontent.com/55155131/67161300-08f9cd00-f351-11e9-901c-0fceca540e0c.png)

As we are thinking of making the virus scanning take somewhere between 5 - 10 minutes to scan every single byte on the users October website server, this creates a big issue, that we did not foresee.

We are just wondering how best to get around this or is there any other method we should use instead of October's native ajax system.

Thanks.

**Comment by LukeTowers** [comment]
@ayumihamasaki2019 this is exactly what Queues are meant for: https://octobercms.com/docs/services/queues

**Comment by ayumihamasaki2019** [comment]
@LukeTowers Thanks for pointing me in the right direction 👍
