### ISSUE TITLE
Mail::queue ignores the email in the htm view

### ISSUE THREAD

**Issue by filipac** [octobercms/october#4713]
- OctoberCMS Build: dev-master
- PHP Version: 7.3

### Description:
The commit https://github.com/octobercms/library/commit/819981708b8f89e2cef818905deb85fca4d630b4#diff-3d7fe2e4a5a9b1b3c8cb69d6097fcff0 introduced a new bug with mail subjects. When using Mail::queue, if you do not send a subject in the callback or do not have a callback at all, it gets the default Mailable subject.

### Steps To Reproduce:
1. Send any email with Mail::queue. Do not set any subject on the callback, instead rely on subject from htm view
2. Subject is Mailable not the one in the view.

I think we can add the htm subject in the following function somewhere.

```php
protected function buildSubject($message)
    {
        // If a custom subject was set, then set it as the message subject
        // Otherwise attempt to set the subject if the message doesn't already have one set
        if ($this->subject) {
            $message->subject($this->subject);
        } elseif (empty($message->getSubject())) {
            parent::buildSubject($message);
        }
        return $this;
    }
```

**Comment by filipac** [comment]
Although it's weird, moving the callback to the old spot is fixing the wrong email subject ALTHOUGH i am not calling ::send but ::queue... htmm

**Comment by filipac** [comment]
If everyone else is affected (those who run on dev-develop or beta builds), i managed to fix this temporary by doing this hook:
```php
\Event::listen('mailer.prepareSend', function ($mailer, $view, Message $message) {
            $v = view($view);
            $v = $v->render();
            $parsed = MailParser::parse($v);
            if (isset($parsed['settings']['subject']) && $message->getSubject() == 'Mailable') {
                $message->setSubject($parsed['settings']['subject']);
            }
            return null;
        });
```

**Comment by daftspunk** [comment]
Hey @filipac! Thanks for the bug report

This has been fixed in https://github.com/octobercms/library/commit/b96ca2682c4fc9c19885bef246244b1bc7160298
