### ISSUE TITLE
Settings model unable to work with images 

### ISSUE THREAD

**Issue by aniket-magadum** [octobercms/october#4716]
- OctoberCMS Build: 458
- PHP Version: 7.2.19
- Database Engine: mysql

### Description:
I am creating a plugin which will render a manifest.json for converting my application to pwa. I have provided some configuration settings for the plugin using the settings model.
Inside the settings I have provided a option for attaching icons using fields.yml. The settings seem to fine and also the image shows attached in the backend.

#### Problem
But the problem I have is while accessing the icon inside of my own code to generate the manifest.json file.
```php
public function generate()
    {
        $settings = Settings::instance();
        $storedIcon= $settings->icon; // This line errors
    }
```
I get a exception like this

![image](https://user-images.githubusercontent.com/48653948/67543763-82f2d300-f710-11e9-8ebe-8a239a443591.png)

After a bit discussion with @tobias-kuendig  . I thought that was a problem specific to windows and laragon for retrieving environment configuration

So I tried running the below command to cache my env
`php artisan cache:config`

But still I get this error. And also this error is not frequent like sometimes it seems to work and sometimes it does not

### Steps To Reproduce:

1) Create a sample plugin
2) Create a settings model with images  attached to it 
3) Try to access the images saved inside of your code

**Comment by LukeTowers** [comment]
This is a complex case. 

In order to aid in our understanding of the problem, please submit [a Pull Request to the test plugin](https://github.com/octoberrain/oc-test-plugin) for investigation that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it _using the test plugin_.

**Comment by aniket-magadum** [comment]
Hi @LukeTowers  I have created a PR with the test plugin [here](https://github.com/octoberrain/test-plugin/pull/80). 

Steps to reproduce the issue.
1) Install the plugin inside of octobercms (build 458).
2) In the backend settings search for sample settings and upload an image.
3) Insert this line in your layouts file to be able to access your manifest file
`<link rel="manifest" href="manifest.json" />`
4)With your network tab open try to refresh the page multiple times . Sometimes you will be able to  get the image and some times you will get this  screen.
![image](https://user-images.githubusercontent.com/48653948/67617791-751e7a00-f804-11e9-8fe2-2ee28216dc6a.png)

I am using Windows 10 + Laragon may be @Samuell1 would be able to help with this.

**Comment by Samuell1** [comment]
@aniket-magadum Using images in settings model without issues on build 458.

**Comment by aniket-magadum** [comment]
Don't know why it only happens on this machine even it worked on another setup of mine. 
Sometimes I even get errors like no active theme found

**Comment by Samuell1** [comment]
Maybe your database is randomly crashing or something like that?

**Comment by aniket-magadum** [comment]
Might be, I don't think it's something related to October now . I will close this issue and maybe switch to Linux anytime soon.

**Comment by Samuell1** [comment]
@aniket-magadum Or maybe other softwares are using same port and its switching db.
