### ISSUE TITLE
RelationController remove single relation UI

### ISSUE THREAD

**Issue by madmicrowave** [octobercms/october#4718]
- OctoberCMS Build: 458
- PHP Version: >=7.1
- Database Engine: >= MySql 5.7

So I have following problem so relation type belonsTo and use RelationController view, with toolbar buttons "create|add|remove" after click on remove relation is detached on db properly but ajax request still show that user data.

### Steps To Reproduce:
1. Setup bolongsTo relation ans build simple form
2. Link relation any type  create|add
3. Click remove, form still show attached relation data, if i reload page user data is not filled, double click on remove data is also removed

**Comment by LukeTowers** [comment]
What? I don't understand what the issue is. Could you provide a step by step of what you're trying to do along with screenshots / gifs?

**Comment by MaksimsGee** [comment]
So basically has following relation: Order -> belongsTo|hasOne -> User

And happens following:
1. attach relation
2. delete|remove relation(and it actually removed from first click)
3. form don`t refresh relation after update and respond form with filled fields

![our-zzzzz-1](https://user-images.githubusercontent.com/11761923/67851989-49f19e80-fb14-11e9-9549-276819ef980e.gif)

**Comment by LukeTowers** [comment]
Could be related to #3470 and #3476

**Comment by LukeTowers** [comment]
@paishin is this the same issue as #3476?

**Comment by DanHarrin** [comment]
I'm having this same issue, I'll have a look and see if I can PR a fix.

**Comment by w20k** [comment]
@DanHarrin could you double-check if PR:https://github.com/octobercms/october/pull/3476 fix your issue?

**Comment by DanHarrin** [comment]
@w20k thanks for that, it does fix the issue on "unlink", but it's still present on "delete".

**Comment by w20k** [comment]
@DanHarrin if you'd have time to make a PR for the. Ping me. Will review and test ;)

**Comment by DanHarrin** [comment]
All done @w20k 😄

**Comment by w20k** [comment]
Omg, your crazyy fast 😄 Thanks, @DanHarrin!

**Comment by bennothommo** [comment]
Confirmed bug. Fixed by #4741, thanks to @DanHarrin.
