### ISSUE TITLE
Update or Save button does not lock in modal window on submit.

### ISSUE THREAD

**Issue by sarahjabado** [octobercms/october#4729]
- OctoberCMS Build: 458
- PHP Version: 7.2
- Database Engine: MySQL
- Plugins Installed: BradieTilley.Forms-v1.3.0, AlexeyBobkov.Pages-v1.3.1

### Description:
During a modal window a user can accidentally submit the form multiple times by double-clicking the save or update button. This subsequently results in a double submission of data which leads to duplicate data entries.

### Steps To Reproduce:
Open a modal window displaying a form while having the document inspector open on the network tab.
Populate the form with data (this works for inserts and updates)
Double click the save button.
Note the number of post requests generated by click actions.

**Comment by bennothommo** [comment]
Confirmed. (@sarahjabado is a colleague and demonstrated it to me)

**Comment by sarahjabado** [comment]
Just bumping regarding the auto-bot. :)

**Comment by bennothommo** [comment]
@sjabado Already done :)

**Comment by sarahjabado** [comment]
> @sjabado Already done :)

Chur Cuzzy!!!!

**Comment by daftspunk** [comment]
Good catch! This should be fixed in Build 463+
