### ISSUE TITLE
create:controller name pluralisation

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#473]
When I do a `php artisan create:controller My.Plugin TaxClass` the *config_form.yaml, config_list.yaml* files title fields all say **TaxClasses**. They should say **Tax Class** - CapCase words should be separated, and it should be the singular version - for example *Edit Tax Class, Preview Tax Class* etc.

**Comment by daftspunk** [comment]
Duplicate of [or fixed by] #472
