### ISSUE TITLE
Field FileUpload via relation in form does not work

### ISSUE THREAD

**Issue by patriknemecek** [octobercms/october#4739]
- OctoberCMS Build: 458
- PHP Version: 7.2
- Database Engine: MySQL

### Description:
Field FileUpload via relation in form does not work.  It throws `Model 'System\Models\File' does not contain a definition for 'customer[image]'.` error

### Steps To Reproduce:
1. Create model with name Customer
2. Make relation Customer `attachOne` File with name `image`
3. Make relation User `hasOne` Customer
4. Extend User fields with this
```
'customer[image]' => [
	'label' => 'Image',
	'type' => 'fileupload',
	'imageHeight' => 320,
	'span' => 'right',
]
```
5. Visit Users controller

**Comment by SebastiaanKloos** [comment]
It is because the image is also a relation. Nested relations are not supported right now

**Comment by patriknemecek** [comment]
@SebastiaanKloos In older build it worked

**Comment by LukeTowers** [comment]
@patriknemecek what build did it work in? This will help us narrow down what change caused the issue.

**Comment by patriknemecek** [comment]
I figured out the last working version is `"october/backend": "1.0.451"`

**Comment by LukeTowers** [comment]
@w20k are you able to test and confirm that this was working as described in 451 but broken in 452+?

**Comment by w20k** [comment]
@LukeTowers sure will try with the latest build.

**Comment by LukeTowers** [comment]
@w20k it would be great if you could specifically test the difference between 451 & 452, then we can narrow down what changed between them to find the cause.

**Comment by w20k** [comment]
@LukeTowers sure will do, but probably on weekends!

**Comment by patriknemecek** [comment]
@w20k ping

**Comment by w20k** [comment]
@patriknemecek sorry had a short vacation :) Will get it done today!

**Comment by daftspunk** [comment]
I can confirm this functionality is currently working as expected. See the following example as an alternative method of replication and proof of this assertion:

https://github.com/octoberrain/test-plugin/blob/fe2182f2ac48119b2c76f1493d9327bcde8b6fe0/models/person/fields.yaml#L71-L79

There may be something else wrong with your code @patriknemecek. Perhaps you can perform your own testing with the test plugin, or provide us with a complete code example for further testing

**Comment by patriknemecek** [comment]
@daftspunk I can confirm functionality via fields.yaml. I figured out the problem is in fileupload added from `backend.form.extendFields` event . I try this code in Plugin boot method in fresh OctoberCMS project and got this error `Model 'System\Models\File' does not contain a definition for 'image'.`

```
\Backend\Models\UserGroup::extend(function ($model) {
    $model->attachOne['image'] = 'System\Models\File';
});

Event::listen('backend.form.extendFields', function ($formWidget) {
    if (!$formWidget->getController() instanceof \Backend\Controllers\UserGroups) {
        return;
    }

    $formWidget->addFields([
        'image' => [
            'label' => 'image',
            'type' => 'fileupload',
            'filetypes' => 'jpg,jpeg,bmp,png,webp,gif,svg',
            'imageheight' => 320,
            'span' => 'left',
        ]
    ]);
});
```

**Comment by mjauvin** [comment]
@patriknemecek make sure you check the $formWidget Model before calling the addFields.... in your case it should be an instance of `\Backend\Models\UserGroup` f I'm not mistaken

**Comment by mjauvin** [comment]
i.e.
 ```
if (!$formWidget->model instanceof  \Backend\Models\UserGroup) {
   return;
}
```

**Comment by patriknemecek** [comment]
@mjauvin Yes, this solve the problem with fileupload. Another fields work fine in create, update action without $formWidget model check, only the fileupload throws exception. Thank you
