### ISSUE TITLE
Plugin logos do not appear in Projects area if project itself does not have a logo

### ISSUE THREAD

**Issue by bennothommo** [octobercms/october#4742]
Very minor issue, but figured I'd make it known.

In the **Projects** area when logged in to https://octobercms.com, if you create a project and leave it with no logo, the logos of the plugins attached to the project are also shown as having no logo.

![Screenshot from 2019-11-06 17-26-32](https://user-images.githubusercontent.com/15900351/68285920-23ef6f80-00bb-11ea-9c72-61c274d86bd8.png)

Once the project is given a logo, the logos of the plugins are all correctly shown:

![Screenshot from 2019-11-06 17-26-53](https://user-images.githubusercontent.com/15900351/68286031-54cfa480-00bb-11ea-9386-5e4c4e66bb77.png)

**Comment by daftspunk** [comment]
This should be fixed now, thanks!
