### ISSUE TITLE
Error in list columns setup

### ISSUE THREAD

**Issue by huynhnamegal** [octobercms/october#4747]
- OctoberCMS Build: 459
- PHP Version: 7.0.33

### Description:
I have some problems when I tried to set up some columns in list page.
I tried to hide  currently columns or adding new columns to show, it show the error popup and loading progress bar still run slowly.
But when I refreshed that page, it show the columns which I wanted to see.

![image](https://user-images.githubusercontent.com/20609668/68375361-4c3da380-0179-11ea-977c-bf5211f0fc32.png)

![image](https://user-images.githubusercontent.com/20609668/68375380-552e7500-0179-11ea-835d-416a4d811846.png)

**Comment by bennothommo** [comment]
@huynhnamegal This will be fixed in build 460 (https://github.com/octobercms/october/commit/c3d99b2acf0a65e7af5198c219003eba8f0b7800).
