### ISSUE TITLE
Improvements to the design and ux for the email section in the backend

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4749]
### Introduction

This github issue discusses some ideas to improve the email section and also allow developers to add future enhancements.

Three main things to improve are as follows:

- Allow deleting of templates, layouts and partials. (currently can't delete email templates in the list).

- Allow previewing of templates, layouts and partials. (to make email design easier).

- Allow dynamic content support by allowing components. (can be added later on, but for now to focus on better ux, deleting and preview support).

### Issues

Though the UX design is being discussed to change, the basic fields will be the same and so a focus on not creating a breaking change.

### Current UX Design

![old-1](https://user-images.githubusercontent.com/57409060/68417877-1d322c80-018f-11ea-87a6-b7277974535c.png)

Above: No option to delete.

![old-2](https://user-images.githubusercontent.com/57409060/68417893-27ecc180-018f-11ea-91f9-c3a69f8552b9.png)

### New UX Design

Below is a mockup of a proposal for a new UX design:

![template](https://user-images.githubusercontent.com/57409060/68417969-42269f80-018f-11ea-977a-91fabce7fc45.png)

![68417977-4652bd00-018f-11ea-8df5-6180fd4466e3](https://user-images.githubusercontent.com/57409060/68420717-d1828180-0194-11ea-8652-e8c0c27a25c6.png)

You can see this design matches the same as the CMS section. Please note there are plugins out there that enhance the CMS section and with this new UX design, developers could create plugins in the future to enhance emails even more such as SEO options and AMP-HTML for Emails etc.

### Feedback

Would love to hear people's thoughts and ideas on this.

**Comment by LukeTowers** [comment]
@ayumi-cloud still interested in this?
