### ISSUE TITLE
[Marketplace] Support for social link previews

### ISSUE THREAD

**Issue by drmzio** [octobercms/october#4756]
Social link previews appear when you paste a link to Twitter, Facebook, etc.. and shows a preview of the link (Image, Title, Description, Url, etc). As you can see from the first image, pasting a link to the Blog plugin page shows nothing.

No link preview | Example of a link preview
--- | ---
![](https://cl.ly/c5b727988dd9/%255B014c8b9d6584ef3972cd063cd765e98b%255D_Image%2525202019-11-09%252520at%2525209.55.22%252520PM.png) | ![](https://cl.ly/2f168bddb36e/Image%2525202019-11-09%252520at%2525209.56.06%252520PM.png)

This addition could also be applied to the theme pages as well. You could look at the [octobercmsjobs.com](https://octobercmsjobs.com) meta tags to see how they've done it. Below is an example link preview I would like to see when sharing a plugin page (or something similar to it).

Plugin page with link preview |
--- |
![](https://cl.ly/1e82c599dc76/Image%2525202019-11-09%252520at%25252010.11.26%252520PM.png) |

For now, I've only prioritized this for Twitter. There's other meta tags that are required for other social networks, but Twitter is the easiest one so far.

**Comment by ayumi-cloud** [comment]
Just gonna add a comment as I got experience with all this.

What you are describing is using Facebook Open Graph tags, which will enhance Facebook, Twitter and Pinterest (for Pinterest you should turn on the enchanced pins as well via a meta-tag).

As you are linking to October CMS plugins, to correctly mark up the right schema, you should use Facebook Open Graph "Products" the link for the code is found here: https://developers.facebook.com/docs/payments/product/

This will add extra things such as `price` and `currency` with that schema which will enhance the paid plugins!

Peace.

**Comment by daftspunk** [comment]
This should be implemented now, thanks!
