### ISSUE TITLE
Media Manager / Markdown Editor - [Uncaught TypeError: $.oc.mediaManager.popup]

### ISSUE THREAD

**Issue by rajakhoury** [octobercms/october#4759]
- OctoberCMS Build: 458
- PHP Version: 7.3.6
- Database Engine:  InnoDB
- Plugins Installed: RainLab.User / RainLab.Blog / RainLab.Translate / Custom..

### Description:
The markdown editor throws the following JS error only when `decompileBackendAssets`  is enabled .

    Uncaught TypeError: $.oc.mediaManager.popup is not a constructor

![media-error](https://user-images.githubusercontent.com/4506434/68610465-6fb86500-047d-11ea-83d9-0fe6642f8d52.png)

The source files appear to be included in the correct order but I didn't have time to check the content of each one.

![media-error2](https://user-images.githubusercontent.com/4506434/68610447-65966680-047d-11ea-8830-d3bb82c965bb.png)

I usually install and update October through composer.
I deleted all `vendor` / `modules` directories, cleared composer cache and run `composer update` without success. I am mentioning this because I read on the forums that this is due to files not being updated.

Here is the composer ;

    "require": {
        "php": ">=7.0",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "october/rain": "dev-develop as 1.0",
        "october/system": "dev-develop",
        "october/backend": "dev-develop",
        "october/cms": "dev-develop",
        "laravel/framework": "5.5.*",
        "wikimedia/composer-merge-plugin": "dev-master"
    }

Any advise would be appreciated.

### Steps To Reproduce:

- Set `decompileBackendAssets => true` 
- Launch any plugin that has the markdown editor
- Click on `Insert Media Image`

**Comment by bennothommo** [comment]
@rajakhoury I did encounter that same issue recently when working on #4325 - I ended up fixing it in the commits for that PR (https://github.com/octobercms/october/pull/4325/commits/1f6ba25ee576dd25825ffa19303c2e420107507e).

**Comment by rajakhoury** [comment]
@bennothommo Thank you Ben.
