### ISSUE TITLE
selectRaw() in filter scope not working on backend lists

### ISSUE THREAD

**Issue by nizzac** [octobercms/october#4768]
- OctoberCMS Build: 458
- PHP Version: 7.2
- Database Engine: MySQL

### Description:
I've added a scope for a backend filter that looks like this...

```
public function scopeMeetsRequirements($query)
{
    return $query->selectRaw('COUNT(bkg_dlg.attendee_id) >= MIN(courses.minimum_requirements) as meets_attendee_requirements')
                 ->join('courses', 'courses.id', '=', 'course_instances.course_id')
                 ->join('bookings', 'bookings.course_instance_id', '=', 'course_instances.id')
                 ->join('bkg_dlg', 'bkg_dlg.booking_id', '=', 'bookings.id')
                 ->where('bookings.status', '<>', 'cancelled')
                 ->where('bookings.terms_agreed', true)
                 ->where('bookings.is_paid', true)
                 ->groupBy('course_instances.id')
                 ->having('meets_attendee_requirements', true);
}
```

If I do `$query->toSql()` in the course instances controller's listExtendQuery() method, the results SQL looks like this...
```
select COUNT(bkg_dlg.attendee_id) >= MIN(courses.minimum_requirements) as meets_attendee_requirements,
    `course_instances`.*,
        (select title from `courses`
            where `course_instances`.`course_id` = `courses`.`id`) as `course`,
        (select city from `venues`
            where `course_instances`.`venue_id` = `venues`.`id`) as `location`,
        (select name from `venues`
            where `course_instances`.`venue_id` = `venues`.`id`) as `venue`,
        (select name from `trainers`
            where `course_instances`.`trainer_id` = `trainers`.`id`) as `trainer`
        from `course_instances`
            inner join `courses` on `courses`.`id` = `course_instances`.`course_id`
            inner join `bookings` on `bookings`.`course_instance_id` = `course_instances`.`id`
            inner join `bkg_dlg` on `bkg_dlg`.`booking_id` = `bookings`.`id`
                where `bookings`.`status` <> ?
                and `bookings`.`terms_agreed` = ?
                and `bookings`.`is_paid` = ?
                group by `course_instances`.`id`
                having `meets_attendee_requirements` = ?
                order by `start_date` asc
```

If I run this query directly on my database, I get the desired result and everything's cool.

However, when I try and use the filter on a backend list I get this error...

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'meets_attendee_requirements' in 'having clause' (SQL: select count(*) as aggregate from `course_instances` inner join `courses` on `courses`.`id` = `course_instances`.`course_id` inner join `bookings` on `bookings`.`course_instance_id` = `course_instances`.`id` inner join `bkg_dlg` on `bkg_dlg`.`booking_id` = `bookings`.`id` where `bookings`.`status` <> cancelled and `bookings`.`terms_agreed` = 1 and `bookings`.`is_paid` = 1 group by `course_instances`.`id` having `meets_attendee_requirements` = 1)

Looking at this, the sql in the errors seems to show that the `selectRaw()` from the code in my scope is being ignored.

If I run the following in tinker...
`CourseInstance::meetsRequirements()->get();` then everything works also.

Looking at the stack trace in the error, i think it's something to do with the paginations count query.

**Comment by daftspunk** [comment]
Easy to see if it relates to pagination, set `showPagination` to false in your list configuration. Does it help?

**Comment by nizzac** [comment]
> 
> 
> Easy to see if it relates to pagination, set `recordsPerPage: null` in your list configuration. Does it help?

I did this and I no longer see the error so I do believe it is related to the pagination call.

**Comment by nizzac** [comment]
Seems this issue was raised on the laravel github last year
https://github.com/laravel/framework/issues/16320

Solutions on there seem to say that you should build your own pagination query rather than relying on the Query builder.

Is there a way to override the backend lists pagination queries within October?
