### ISSUE TITLE
Missing getFromJson method in Translator

### ISSUE THREAD

**Issue by multiwebinc** [octobercms/october#4774]
This is a bug for https://github.com/octobercms/library, however it looks like issues are disabled for that repository.

I am trying to use [Laravel's `__()`](https://laravel.com/docs/5.5/localization#replacing-parameters-in-translation-strings) function to replace parameters in translation strings. For example:

```
__(
    'Please :contact_us for more details', 
    ['contact_us' => "<a href='$contact'>contact us</a>"]
);
```

However I get the error:

> Call to undefined method October\Rain\Translation\Translator::getFromJson()
vendor/laravel/framework/src/Illuminate/Foundation/helpers.php line 941

The above line executes:

```
return app('translator')->getFromJson($key, $replace, $locale);
```

`app('translator')` returns an instance of `October\Rain\Translation\Translator`, which is missing the `getFromJson()` method:

```
array:19 [▼
  0 => "__construct"
  1 => "has"
  2 => "get"
  3 => "choice"
  4 => "trans"
  5 => "transChoice"
  6 => "load"
  7 => "addNamespace"
  8 => "getSelector"
  9 => "setSelector"
  10 => "getLoader"
  11 => "locale"
  12 => "getLocale"
  13 => "setLocale"
  14 => "getFallback"
  15 => "setFallback"
  16 => "setEventDispatcher"
  17 => "setParsedKey"
  18 => "parseKey"
]
```

Copying the `getFromJson()` method from `\Illuminate\Translation\Translator` to `\October\Rain\Translation\Translator` appears to do the trick, however I'm not sure if there is another October-specific way to do this already.

**Comment by bennothommo** [comment]
@multiwebinc The method we generally use is the `trans()` method - see here for more info: https://octobercms.com/docs/services/helpers#method-trans

It also supports parameters via the second argument as well.

**Comment by multiwebinc** [comment]
@bennothommo The page above does not document the fact that `trans()` takes more than one argument, which is why I assumed it didn't. It wasn't working for me when I tried it, which is why I then tried using the `__()` function. However I got it working with this PR: https://github.com/octobercms/library/pull/444.

**Comment by LukeTowers** [comment]
Issues are left open until a solution is merged or a conclusion is otherwise reached

**Comment by multiwebinc** [comment]
@LukeTowers I assumed a conclusion was reached.

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/library/pull/444
