### ISSUE TITLE
RelationController manage filters throws error when the search inside the popover is used

### ISSUE THREAD

**Issue by kOld** [octobercms/october#4775]
- OctoberCMS Build: 459
- PHP Version: 7.2.23
- Database Engine: MySQL
- Plugins Installed: Rainlab.Users

### Description:
RelationController manage filters throws the following error when the search inside the popover is used:
`"A widget with class name 'relationCommentsManageFilter' has not been bound to the controller" on line 597 of /var/www/modules/backend/Classes/Controller.php`

### Steps To Reproduce:
- Install my test plugin: https://github.com/kOld/test-plugin
- Navigate to Playground -> Posts -> New Post
- In the first tab "Comments", click Add Comment
- Click on "Users: All"
- Type something in the filter

### Possible correction:
https://github.com/kOld/october/commit/76b776848cd95a848eec57325d49176bd95cdfee

This seams to happen because the data-request-data="" parameter is lost when the popover is created inside the modal, creating the popover inside the div that has the data-request-data="" seems to fix the issue

**Comment by LukeTowers** [comment]
@kOld can you submit your test plugin changes as a PR to the test plugin and your fix as a PR to this repo (the develop branch).

**Comment by kOld** [comment]
Sure, I will do it later today. Just found that on this PR they encounter the same issue: https://github.com/octobercms/october/pull/4373#issuecomment-500104040

**Comment by LukeTowers** [comment]
@bennothommo are you able to look into this?

**Comment by bennothommo** [comment]
Fixed by https://github.com/octobercms/october/commit/9155e7de7e1035dc3d6bd51288f909268c240a76.
