### ISSUE TITLE
Model relation order breaking the toolbarButton: add functionality

### ISSUE THREAD

**Issue by woshj** [octobercms/october#4781]
**Overview:**
Not sure if this is a bug or something i'm doing wrong but if you create a $belongsToMany relation and order it with the pivot data, when you setup the renderRelation partial and click the Add button you get an SQL error about there being a lack of your pivot column within the table you're trying to read from.

The error makes sense but why is this order field still referenced when you're not even displaying it on screen within the relevant columns.yaml?

**Reproduction**
1. Using plugin builder create base plugin with 3 tables and 2 pivot tables an order column
2. Within the models setup the $belongsToMany on each table and order by pivot order column
3. Create a relationship manager that utilises create|add|remove toolbarbuttons
4. Display the relation on the backend within your columns.yaml
5. Edit your columns.yaml to include the order field to display within the relation list
5. Load the backend form and click add within your new relation partial
6. Error stating pivot order column can not be found

**Error Message**
``"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c_order' in 'order clause' (SQL: select `wordshop_faq_cats`.* from `wordshop_faq_cats` where `wordshop_faq_cats`.`id` not in (22, 20, 21) order by `c_order` asc, `name` desc)" on line 664 of C:\xampp\htdocs\octoberdev\vendor\laravel\framework\src\Illuminate\Database\Connection.php"``

``order by `c_order` asc`` is what's causing the issue here, the query string that's being created is trying to `select records from table 1 order by table2.order_column`

**Comment by woshj** [comment]
Looking at the docs again it seems the `manage: list:` set within the `config_relation.yaml` is what's messing it up. I order the relation within my model and it works perfect when being displayed on the front end and within the backend (correct order) but when it tries to display this `manage: list:` after you click `Add` it tries to display the list ordered by the pivot data when it shouldn't be.

I'm not displaying the pivot data in my columns.yaml so I don't think this is completely my fault but I can't figure out how to get round this.

**Comment by woshj** [comment]
Does anyone know if this is something out of my control, I can't really justify spending too much more time looking at this without knowing if it's something I can fix or not.

Anything useful is greatly appreciated

**Comment by bennothommo** [comment]
@woshj Would you mind providing us with a full stack trace of the issue, if it is in your logs? Also, do you have a copy of the plugin you have created that you might be able to share, so I can replicate it exactly? If it's proprietary, please feel free to either take out the proprietary stuff or send it through as a private message on Slack.

**Comment by woshj** [comment]
@bennothommo First of thanks for the response. Secondly I'm not sure how to access the full stack trace log this is an SQL error in the back end that gets caught by the error modal instead of going to the red 404 type error page.

I'll add that this sounds a lot like issue #4335 @adamo made a comment at the bottom that explains my problem in less words if that helps at all.

I can't share the plugin I'm working on but I'll quickly recreate it without all the important stuff it shouldn't take too long.
