### ISSUE TITLE
When using Rule objects, the error message is not used

### ISSUE THREAD

**Issue by multiwebinc** [octobercms/october#4783]
I am trying to add a rule to validate a reCAPTCHA response, and I copied the code under the section "Using Rule objects" from https://octobercms.com/docs/services/validation#custom-validation-rules. I can tell that the `validate()` and `passes()` methods are being executed because when I do `dd()` inside these messages, it works. However this is not so with the `message()` method in that class, which is not being executed at all. In the ajax response, it has a generic error message:

    g-recaptcha-response: ["validation.recaptcha"]

instead of using the custom error message.

**Comment by bennothommo** [comment]
@multiwebinc I believe the `message()` method is required purely for ensuring that the custom Rule classes include all required methods of the `Illuminate\Contracts\Validation\Rule` interface. We don't actually use the message specified there though.

It's something we can look at down the track, but in the mean time, you'll have to use the other methods for specifying messages.

**Comment by multiwebinc** [comment]
@bennothommo Thanks for the reply. I did it another way, but it is a bit uglier since I put a lot of logic in my Plugin.php file instead of it being a separate class. If you could maybe point me in the right direction, I might be able to get a PR for this.

**Comment by bennothommo** [comment]
@multiwebinc Sure thing, will be happy to take a look at a PR.

The main file handling model validation is this one:
https://github.com/octobercms/library/blob/master/src/Database/Traits/Validation.php

That's where you'll want to look if you want to bring in support for the `message()` method.

**Comment by ayumi-cloud** [comment]
I get the same error, see screenshot:

![image](https://user-images.githubusercontent.com/57409060/69564454-fbb4ab80-0faa-11ea-9639-6d408cc8509b.png)

Even though my `rules` file says this:

```php
    public function message()
    {
        return 'The :attribute must be a valid array.';
    }
```

**Comment by multiwebinc** [comment]
I looked into this, and the file @bennothommo mentions above is actually not used at all in my case. I'm assuming it's because the rule is not related to database queries. However everything else to do with validation appears to be just stock Laravel, so comparing the [Laravel docs](https://laravel.com/docs/5.5/validation#using-rule-objects) with the [October docs](https://octobercms.com/docs/services/validation#custom-validation-rules), we can see that custom rule objects are loaded differently; Laravel recommends passing an instance of the rule object directly in the rules parameter of `Validator::make()` whereas October recommends extending the validator with the class name of the custom rule.

Doing it the Laravel way in October, actually works just as intended and calls the Rule object's `message()` method to get the custom message:

    $rules = [
        'g-recaptcha-response' => [new RecaptchaValidator],
    ];
    $validation = Validator::make(Input::all(), $rules);

So perhaps it's just something we could add to the October documentation.

**Comment by multiwebinc** [comment]
@ayumi-cloud The Laravel pull request you mention has already been merged into October.

**Comment by ayumi-cloud** [comment]
@multiwebinc 

It seems like October's trait is missing the logic found in Laravel.

See code lines here: https://github.com/laravel/framework/blob/14a03bd977f662a0ff8165fbdb6992680379db49/src/Illuminate/Validation/ClosureValidationRule.php#L61-L69

I can't see any mention of `public function message()` in the https://github.com/octobercms/library/blob/master/src/Database/Traits/Validation.php

To me is seems like the trait is not processing the message function.

**Comment by multiwebinc** [comment]
@ayumi-cloud In my case, https://github.com/octobercms/library/blob/master/src/Database/Traits/Validation.php is not being executed. I literally saved this as the entire file, and it has no effect, I would assume because I am not validating database values:

```
<?php namespace October\Rain\Database\Traits;

trait Validation
{
    protected static function makeValidator($data, $rules, $customMessages, $attributeNames, $connection = null) { }
}
```

> You should not need to use the `Validator::make()` if everything is working correctly.

I'm not sure what you mean here. You have to validate the input *somehow*. Either by doing `Request::validate()` as in the Youtube video you linked, or by doing `Validator::make()`. I have a hunch that one of these methods probably just calls the other one anyway.

**Comment by ayumi-cloud** [comment]
@multiwebinc I meant you only need call it once.

Going to share my code:

Plugin.php file

```php
use Validator;
use Acme\Example\Rules\Uppercase;

class Plugin extends PluginBase
{
    public function boot()
    {
        Validator::extend('uppercase', Uppercase::class);
    }
}
```

Models File:

```php
class Example extends Model
{
    use \October\Rain\Database\Traits\Validation;

    public $rules = [
        'something' => 'uppercase'
    ]
}
```

The Trait is not passing the $message, instead its passing: `validation.$attribute` or in the above example code it would say: `validation.uppercase`

**Comment by bennothommo** [comment]
@ayumi-cloud Thanks for the assistance, but I believe he is talking about running a Validator instance manually - ie. not saving to a database.

@multiwebinc My comment was in reference to the Database trait, so if you are running your own instance of Validator, then yes, you should be able to do it the Laravel way and it should work fine as I believe the Validator that October uses is completely untouched Laravel code.

The Database trait is missing the ability to extract the message from the `message()` method. As I said, it could be added down the track.

I will look into improving the docs to highlight the difference between using the Trait and using your own Validator instance.

**Comment by ayumi-cloud** [comment]
@bennothommo I'm saying the saving to database method is also broken, unless my code in my previous comment is wrong. Any suggestions are always welcome 👍 

Also the doc's need updating to add this users request see their forum post: https://octobercms.com/forum/post/custom-validation-messages

**Comment by bennothommo** [comment]
@ayumi-cloud Ah right - yeah, the Database trait doesn't read the `message()` method of a `Rule` class, however, you can use `$customMessages` in the model to specify a custom message. I'll update the docs now if that's not the case.

**Comment by ayumi-cloud** [comment]
@bennothommo @LukeTowers 

By the way, I tried doing this also, but October won't allow `$customMessages` when using a `Rules` file. So right now there seems to be no way to display the custom message using a `rules` file using October's `Trait`, by either `$message` or `$customMessages` out of the box.

Models File:

```php
class Example extends Model
{
    use \October\Rain\Database\Traits\Validation;

    public $customMessages = [
        'something' => 'The field needs to be uppercase.',
    ];

    public $rules = [
        'something' => 'uppercase'
    ]
}
```

- Needs more invesigating.

**Comment by bennothommo** [comment]
@ayumi-cloud there is a way - it may not be the most elegant way, but I used a Rule class and custom translatable message for the Builder plugin. See the files edited in this PR: https://github.com/rainlab/builder-plugin/pull/269

**Comment by LukeTowers** [comment]
@ayumi-cloud try `'something.uppercase' => 'The field needs to be uppercase.',`

**Comment by ayumi-cloud** [comment]
Perfect thanks.

@LukeTowers suggestion didn't work for me.

@bennothommo event listener method worked for me.

**Comment by ayumi-cloud** [comment]
@bennothommo 

Want to ask you something about your code line here: https://github.com/rainlab/builder-plugin/blob/8a0d6789501cae5fb5d27fb571de049c28559d46/Plugin.php#L135

You're written: `translator.beforeResolve` 

Would I be correct in thinking that uses the `Rainlab.Translator` plugin?

If so would the `Builder Plugin` then require the `Rainlab.Translator` to work.

e.g.

```php
public $require = [
        'RainLab.Translate'
];
```

**Comment by LukeTowers** [comment]
@ayumi-cloud the translator event is provided by the Translator class in October\Rain. https://octobercms.com/docs/api/translator/beforeresolve

**Comment by ayumi-cloud** [comment]
@LukeTowers Thanks, I thought I'd double check. 👍

**Comment by LukeTowers** [comment]
@ayumi-cloud I pinged you on slack, take a look please

**Comment by ayumi-cloud** [comment]
@LukeTowers Ok will open slack in a bit.

p.s. The website search didn't work for me (this is why I asked here), see screenshot:

![image](https://user-images.githubusercontent.com/57409060/69748834-0ef97f80-1141-11ea-8404-5f7d32d2b80a.png)

**Comment by bennothommo** [comment]
@ayumi-cloud I've never had much luck searching events through it as well, unfortunately. Unless those events are mentioned in a page in the normal docs.

**Comment by ayumi-cloud** [comment]
@bennothommo @LukeTowers 

I'm seeing an issue with the method bennothommo shared with the update to the `RainLab.Translate`

Please could you give some advice and look into this issue / bug.

1. My plugin I added bennothommo's code.

2. I create a fresh new October CMS install.

3. My plugin has several `required` plugins, one being `RainLab.Translate`.

4. If I upload my plugin or try to install my plugin **BEFORE** the `RainLab.Translate` plugin I always seeing the same error related to the `rules` code.

Trace Stack:

```
BadMethodCallException: Method [validateValidJsonable] does not exist. in C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Validation\Validator.php:1140
#0
C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(359):
Illuminate\Validation\Validator->__call('validateValidJs...', Array)
#1
C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(268):
Illuminate\Validation\Validator->validateAttribute('frontendFileExt', 'ValidJsonable')
#2
C:\xampp\htdocs\vendor\october\rain\src\Database\Traits\Validation.php(306):
Illuminate\Validation\Validator->passes()
#3
C:\xampp\htdocs\vendor\october\rain\src\Database\Traits\Validation.php(74):
Acme\Models\Something->validate()
#4
[internal function]:
Acme\Models\Something::October\Rain\Database\Traits\{closure}(Array, Array)
```

I believe the exact same issue would happen with the `Rainlab.Builder` plugin now as well.

5. I cancel the error screen and the `RainLab.Translate` plugin is installed.

6. I then install my plugin to latest version number as now have **REQUIRED** plugins.

I'm thinking there needs some extra code to address this loading order issue.

p.s. Should I post this here or in the: https://github.com/rainlab/builder-plugin/pull/269

~Will wait for your suggestions.

**Comment by goldmont** [comment]
Hi,

any news about this? I have the same problem.

**Comment by bennothommo** [comment]
@goldmont There is a [PR here](https://github.com/octobercms/library/pull/455) to improve Rule object handling, but it is targeting our Laravel 6 upgrade. We'll hopefully have the L6 upgrade out shortly.

**Comment by dimti** [comment]
Thank you @bennothommo, @summercms yous save my day

If you not use language files you might be define constant and also support getting messages both for database validation and custom validation things:

in the your extend/boot:
```php
Validator::extend('seo_url', SeoUrl::class);
Event::listen('translator.beforeResolve', fn ($key) => $key === 'validation.seo_url' ? SeoUrl::MESSAGE : null);
```

Or if you use language files you don't need class constant and you no needed use `message()` in Rule object class
```php
Validator::extend('seo_url', SeoUrl::class);
Event::listen('translator.beforeResolve', fn ($key) => $key === 'validation.seo_url' ? Lang::get('dimti.myplug::lang.validation.seo_url') : null);
```
Based on: https://github.com/rainlab/builder-plugin/blob/8a0d6789501cae5fb5d27fb571de049c28559d46/Plugin.php#L135

Your language file need named: `lang.php` - not `validation.php` how in docs
https://laravel.com/docs/6.x/validation#localization
https://octobercms.com/docs/services/validation#localization

Your language file `plugins/dimti/myplug/lang/{en,ru}/lang.php`
```php
<?php

return [
    'validation' => [
        'seo_url' => 'The :attribute must be seo url.',
    ]
];
```


Rule object:
```php
<?php namespace Dimti\MyPlug\Rules;

use Illuminate\Contracts\Validation\Rule;

class SeoUrl implements Rule
{
    const MESSAGE = 'The :attribute must be seo url.';

    /**
     * Determine if the validation rule passes.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @return bool
     */
    public function passes($attribute, $value)
    {
        if (! is_string($value)) {
            return false;
        }

        /**
         * @see \Illuminate\Validation\Concerns\ValidatesAttributes::validateUrl
         */
        $pattern = '~^
            (https)://                                 # protocol
            (
                ([\pL\pN\pS\-\_\.])+(\.?([\pL\pN]|xn\-\-[\pL\pN-]+)+\.?) # a domain name
            )
            (?:/ (?:[\pL\pN\-._\~!$&\'()*+,;=:@]|%[0-9A-Fa-f]{2})* )*          # a path
        $~ixu';

        return preg_match($pattern, $value) > 0;
    }

    /**
     * Validation callback method.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @param  array  $params
     * @return bool
     */
    public function validate($attribute, $value, $params)
    {
        return $this->passes($attribute, $value);
    }

    /**
     * Get the validation error message.
     *
     * @return string
     */
    public function message()
    {
        return SeoUrl::MESSAGE;
    }
}
```

**Comment by bennothommo** [comment]
@dimti it'll be easier if you just use the language string for `message()`. It's already run through the translator.

```php
    /**
     * Get the validation error message.
     *
     * @return string
     */
    public function message()
    {
        return 'dimti.myplug::lang.validation.seo_url';
    }
```
