### ISSUE TITLE
Upload image by drop it to Froala editor content

### ISSUE THREAD

**Issue by tombien** [octobercms/october#4786]
- OctoberCMS Build: 458
- PHP Version: 7.1

### Description:
Dropping Image to Froala editor contetn does not upload them.

### Steps To Reproduce:
Drag image from your computer (File manager, Finder,...) drop it to Froala contetn. There is neverending "Uploading" progress bar.

Javascript console has this error:
Uncaught TypeError: Cannot read property 'title' of null

**Comment by tombien** [comment]
I made some research about this and in my another installations of build 458 it works. Maybe it is only "something" with this particular installation.

**Comment by maartenmachiels** [comment]
Hi, I can confirm that I'm encountering this bug aswel, both on my localhost development environment and in a staging environment. I'm running version 458 and PHP version 7.1 and 7.3 respectively.

Adding an image into a Froala Wysiwyg field either by dragging or dropping or by clicking on the insert image button and then clicking to browse and upload from your pc results in an image with a slight fade over it. When you click on code view, the image is deleted. The Javascript error appears in the console:

```
build-min.js?v458:1795 Uncaught TypeError: Cannot read property 'title' of null
    at FE.html (build-min.js?v458:1795)
    at _content (build-min.js?v458:1428)
    at _build (build-min.js?v458:1440)
    at Object.buildList (build-min.js?v458:1443)
    at U (build-min.js?v458:1795)
    at n (build-min.js?v458:1795)
    at HTMLImageElement.ne (build-min.js?v458:1795)
    at k (build-min.js?v458:1795)
    at HTMLImageElement.n (build-min.js?v458:1795)
    at HTMLImageElement.dispatch (jquery.min.js?v=458:2)
```
Strangely, adding an image via the media library doesn't throw the error and does seem to work. Can this please be investigated?

Here's a video recreating the issue:
[https://www.dropbox.com/s/erthhymdghu21a4/screencast.webm?dl=0](url)

**Comment by tombien** [comment]
@maartenmachiels, please, can you check #4785
It has same JS error like this. May be it is related with this. Thanks.

**Comment by maartenmachiels** [comment]
Please keep this issue open as it is an essential part of October CMS and needs to be addressed.

**Comment by bennothommo** [comment]
@tombien @maartenmachiels I have just tested this with build 464 and have not found any issue with drag-and-drop, nor with the uploader by clicking on "Add an Image" and selecting from my files.

Would you be able to test with the latest build and let us know if the issue still persists?

**Comment by tombien** [comment]
Hi @bennothommo, I can confirm that everything is OK now in build 464. I can upload image by drag-and-drop, also by uploader. And I can see image toolbar on image in editor content  (#4785).
I tested it on same installation (updated to 464), wich made errors before.
