### ISSUE TITLE
The line chart demo code doesn't work

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4792]
The code example found here: https://octobercms.com/docs/ui/chart

Gives me two errors.

![image](https://user-images.githubusercontent.com/57409060/69765886-9826ab80-116d-11ea-8392-7e34db59d793.png)

When I check the github repo: https://github.com/rainlab/googleanalytics-plugin/blob/master/reportwidgets/trafficoverview/partials/_widget.htm

Which I know is working, will use that to rewrite the demo code and run some tests then create a pr.

**Comment by daftspunk** [comment]
Fixed in ee4078ac44afb61848ed5973694282719ee6826e

Thanks!
