### ISSUE TITLE
Missing settings for InlineStyle button in Froala editor

### ISSUE THREAD

**Issue by tombien** [octobercms/october#4794]
If I use "inlineStyle" button in Froala, there is "Big red" and "Small blue" css class to select in editor toolbar. 

I think, setting for "inlineStyle" button is missing in "Settings > Editor settings > Markup classes"

**Comment by bennothommo** [comment]
@tombien Please feel free to provide a PR for this if you would like.

**Comment by tombien** [comment]
For clarify. It should be "inlineClass" button, not "inlineStyle" - [Froala doc of this](https://www.froala.com/wysiwyg-editor/docs/options#inlineClasses)

Goal is to be able to add some classes to selected word(s) with a `span` element. Like you can do it for paragraph, table, etc. for now.
