### ISSUE TITLE
invalid security token issue

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4798]
I see this issue everyday, when I try to login to the backend.

Step to reproduce:

1. Day 1: Login to the backend.

2. Don't bother to logout, instead just close the computer down for the day.

3. Day 2: Login to the backend and enter your details, after that the cms tries to log you in and redirects to a blank screen saying "invalid security token".

4. Do a screen refresh and can log back in (because you have forced october to create a new session cookie).

----

Yesterday I cleared all my service worker and caches on purpose ! I have completely blank:

- Local Storage
- Session Storage
- IndexedDb
- Web SQL
- Cache Storage

So I know the issue isn't from there now.

It seems like October CMS is the problem and needs to be set to generate a brand new session cookie every time you open the backend login web page. I'm not sure how it's setup ? But for me I'm using a custom URL for my backend. I can clearly see that October CMS was trying to use yesterday's session cookie value, as I wrote it down before I turned off the computer from yesterday. So that is most likely why I see this error all the time!

[edit] Forgot to mention, I'm having this issue in the Chrome browser.

**Comment by LukeTowers** [comment]
@ayumi-cloud the CSRF token is tied to the session and is stored in a hidden field on the login page. If your browser has a CSRF token loaded that doesn't match your current session (usually happens if your configuration is setup with a short session lifetime or has errors in configuration that mean that sessions don't persist at all)

**Comment by ayumi-cloud** [comment]
After reading your comment I went to check the source code of the auth.htm and it seems I set the backend service worker to true by mistake and the service worker was displaying an old version every time.
