### ISSUE TITLE
Recordfinder's remove not sending correct value

### ISSUE THREAD

**Issue by TheFehr** [octobercms/october#4800]
- OctoberCMS Build: 458
- PHP Version: 7.3.8
- Database Engine: SQlite
- Plugins Installed: Luke Towers.Snappy-v1.0.5
Alexey Bobkov, Samuel Georges.Builder-v1.0.26

### Description:
I have a recordfinder on a form and a dropdown list which is dependsOn that recordfinder.
Now when I remove the selected record via the "X" remove button in the recordfinder, the xhr call to update all dependsOn fields the recordfinder sends the old id from the last selected record instead of nothing. Which makes it impossible for my getDropdownOptions method to return an empty array on no record.

### Steps To Reproduce:
Add a recordfinder.
Add a dropdown. Add the recordfinder field as a dependsOn for the dropdown.
Write a method that return some value when there is a value in the recordfinder field or return empty array if there is no value in the recordfinder field.

#### After selecting a record
![image](https://user-images.githubusercontent.com/12525476/70062354-27a4e200-15e6-11ea-8158-393fc93e8406.png)
#### After removing it
![image](https://user-images.githubusercontent.com/12525476/70062459-57ec8080-15e6-11ea-989f-77836a784ddc.png)

I also tried the solution to #3591 but it doesn't solve it.

**Comment by LukeTowers** [comment]
@TheFehr Sounds like a race condition to me. Try changing `data-request-success` to `data-request-success="$locker = $('#<?= $field->getId() ?>'); $locker.val(''); $locker.trigger('change')"`

**Comment by TheFehr** [comment]
@LukeTowers I added `data-request-success="var $locker = $('#<?= $field->getId() ?>'); $locker.val(''); $locker.trigger('change')"` and now it's working like a charm.
Thank you very much for the quick reply. Should I do a PR for this real quick?

**Comment by LukeTowers** [comment]
Go for it @TheFehr

**Comment by LukeTowers** [comment]
Fixed by #4802
