### ISSUE TITLE
Repeater: Collapse all by default and accordion style

### ISSUE THREAD

**Issue by robinbonnes** [octobercms/october#4801]
# Feature request

My client requested two features for the repeater formwidget and I would like to know if there is a bigger demand for this.

1. Collapse all repeater items by default. This is needed for the pages plugin, to give more overview to a static page with a lot of sections (repeater items) active. Example:

![image](https://user-images.githubusercontent.com/5117166/70124554-5918be80-1675-11ea-9f04-efa9794180a2.png)

2.  Collapse other repeater items when opening one of them. Just like in Bootstrap accordions (https://getbootstrap.com/docs/4.1/components/collapse/#accordion-example), when you open a repeater item it should collapse any other open repeater item.

# Proposal

Add two options to the repeater formwidget:

- `collapsedByDefault`: Collapse all repeater items in the same formwidget by default. Type: boolean, default: false.
- `accordionStyle`: Collapse other repeater items in the same formwidget when opening an item. Type: boolean, default: false.

# References

- https://github.com/rainlab/builder-plugin/issues/165
- https://github.com/octobercms/october/issues/2631

**Comment by LukeTowers** [comment]
That sounds like a good idea to me @robinbonnes. Not sure about the config names but that's a minor detail that could be improved on later.

**Comment by robinbonnes** [comment]
For now I can live with this quick-and-dirty fix to collapse repeaters by default on static pages:

```
$(document).ready(function() {
    $('form[data-object-type="page"] [data-control="fieldrepeater"]').data('oc.repeater').collapseAll();
});
```

**Comment by SebastiaanKloos** [comment]
@robinbonnes Sounds like a good improvement. Do you need any help for creating a PR?

**Comment by roojai** [comment]
> $(document).render(function() {
>     $('form[data-object-type="page"] [data-control="fieldrepeater"]').each(function() { 
>         $(this).fieldRepeater().data('oc.repeater').collapseAll(); 
>     });
> });

Hi there, was wondering where you put this code. Thanks

**Comment by bennothommo** [comment]
Added in https://github.com/octobercms/october/pull/4877.

**Comment by daslicht** [comment]
So this is added inteh current version ? How to use it please?

**Comment by mightyhaggis** [comment]
@daslicht Somehow I missed this update! And a great one it is.
Looking through the Issues and having just tested to find it works  :)

`{repeater name="" tab="" prompt="" style="accordion"} ... {/repeater}`
Options for style: https://github.com/octobercms/october/pull/4877#issue-362492258

**Comment by LukeTowers** [comment]
@mightyhaggis @daslicht docs are updated here: https://github.com/octobercms/docs/blob/master/backend-forms.md#repeater. They'll be updated on the main site as soon as 467 becomes stable.
