### ISSUE TITLE
Method addSeconds does not exist.

### ISSUE THREAD

**Issue by xf039** [octobercms/october#4813]
```Method addSeconds does not exist.```
```vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php line 96```

https://github.com/briannesbitt/Carbon/issues/1709

OctoberCMS is depending on Laravel 5.4, which is using a broken Carbon package.

I tried updating the Carbon package but unfortunately the error is still occurring.

**Comment by LukeTowers** [comment]
@xf039 why'd you close this? Also the current Laravel version October uses is 5.5 and we're working on updating to L6 which also includes an update to Carbon 2. See #4381 for more info
