### ISSUE TITLE
Relation form field preview visual glitch

### ISSUE THREAD

**Issue by Eoler** [octobercms/october#4817]
- OctoberCMS Build: 460
- PHP Version: 7.3
- Plugins Installed: October.Test

### Description:
Relation checkboxes are shown without margins in backend form preview mode:
![RelationField-preview](https://user-images.githubusercontent.com/680032/70520589-13a93500-1b3e-11ea-885a-f90b3e2201bc.png)

### Steps To Reproduce:
Open the following backend URL with Test Users Preview:
`/{backend}/october/test/users/preview/1/relation`

**Comment by Eoler** [comment]
Related to bigger issue: https://github.com/octobercms/october/issues/4823

**Comment by LukeTowers** [comment]
@Eoler going to close this in favour of #4823, thanks!
