### ISSUE TITLE
Create new list filter to show number of records found

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4821]
### Example of enhancement idea

Currently at the bottom of the lists it says: "Displayed records: 1-50 of 1334".

I was thinking at trying to add a new filter that says: "Filtered records: 33" in the filter section (at the top of the web page).

Saves me having to scroll all the way to the bottom of the web page, to find out the number of results each time.

### Mockup Screenshot

![image](https://user-images.githubusercontent.com/57409060/70645820-99f87080-1c3d-11ea-977c-746f03e1a823.png)

For LTR users this will be displayed on the right hand side and for RTL it will be displayed on the left hand side.

### YAML

Make it an option for the filterwidget, to allow people to choose whether they want to add it or not.

(as per discussion with Luke).

e.g. in `config_list.yaml` file:

```yaml
filter: config_filter.yaml
    filterCount: true
```

Would turn this feature on (default set to off).

---

Notes:

`Lists` and `Filters` found here: https://github.com/octobercms/october/tree/master/modules/backend/widgets

(Use the pagination from `lists` to create a new `filter` in `filters`).

**Comment by ayumi-cloud** [comment]
I've added this to my do list, I plan to start working on this in the coming days, when I've got free time.

Would love to get some insights and thoughts from @LukeTowers and @bennothommo on this before I start. With regards to the exact position and adding it to yaml or not etc. or anything else you feel maybe important.

**Comment by mjauvin** [comment]
Wouldn't it be better to add an option to the List Widget to also show the `1-50 of 1234` at the top of the list widget ?

**Comment by mjauvin** [comment]
ref. modules/backend/widgets/lists/partials/_list,htm
ref. modules/backend/widgets/lists/partials/_list_head_row.htm
ref. modules/backend/widgets/lists/partials/_list_pagination.htm

**Comment by mjauvin** [comment]
All that's required to show top pagination:
```
diff --git a/modules/backend/behaviors/ListController.php b/modules/backend/behaviors/ListController.php
index df01b63e..558002b0 100644
--- a/modules/backend/behaviors/ListController.php
+++ b/modules/backend/behaviors/ListController.php
@@ -145,6 +145,8 @@ class ListController extends ControllerBehavior
             'recordUrl',
             'recordOnClick',
             'recordsPerPage',
+            'showPagination',
+            'showTopPagination',
             'showPageNumbers',
             'noRecordsMessage',
             'defaultSort',
diff --git a/modules/backend/widgets/Lists.php b/modules/backend/widgets/Lists.php
index 4389b13e..9a23e5c8 100644
--- a/modules/backend/widgets/Lists.php
+++ b/modules/backend/widgets/Lists.php
@@ -95,6 +95,7 @@ class Lists extends WidgetBase
      * @var bool|string Display pagination when limiting records per page.
      */
     public $showPagination = 'auto';
+    public $showTopPagination = false;
 
     /**
      * @var bool Display page numbers with pagination, disable to improve performance.
@@ -204,6 +205,7 @@ class Lists extends WidgetBase
             'showTree',
             'treeExpanded',
             'showPagination',
+            'showTopPagination',
             'customViewPath',
         ]);
 
@@ -256,6 +258,7 @@ class Lists extends WidgetBase
         $this->vars['showCheckboxes'] = $this->showCheckboxes;
         $this->vars['showSetup'] = $this->showSetup;
         $this->vars['showPagination'] = $this->showPagination;
+        $this->vars['showTopPagination'] = $this->showTopPagination;
         $this->vars['showPageNumbers'] = $this->showPageNumbers;
         $this->vars['showSorting'] = $this->showSorting;
         $this->vars['sortColumn'] = $this->getSortColumn();
@@ -263,7 +266,7 @@ class Lists extends WidgetBase
         $this->vars['showTree'] = $this->showTree;
         $this->vars['treeLevel'] = 0;
 
-        if ($this->showPagination) {
+        if ($this->showPagination || $this->showTopPagination) {
             $this->vars['pageCurrent'] = $this->records->currentPage();
             // Store the currently visited page number in the session so the same
             // data can be displayed when the user returns to this list.
@@ -596,7 +599,7 @@ class Lists extends WidgetBase
         if ($this->showTree) {
             $records = $query->getNested();
         }
-        elseif ($this->showPagination) {
+        elseif ($this->showPagination || $this->showTopPagination) {
             $method            = $this->showPageNumbers ? 'paginate' : 'simplePaginate';
             $currentPageNumber = $this->getCurrentPageNumber($query);
             $records = $query->{$method}($this->recordsPerPage, $currentPageNumber);
diff --git a/modules/backend/widgets/lists/partials/_list.htm b/modules/backend/widgets/lists/partials/_list.htm
index 5b3e50e6..b34d0b34 100644
--- a/modules/backend/widgets/lists/partials/_list.htm
+++ b/modules/backend/widgets/lists/partials/_list.htm
@@ -1,4 +1,15 @@
 <div class="control-list list-scrollable" data-control="listwidget">
+    <?php if ($showTopPagination): ?>
+        <div class="list-header">
+            <div class="list-pagination">
+                <?php if ($showPageNumbers): ?>
+                    <?= $this->makePartial('list_pagination') ?>
+                <?php else: ?>
+                    <?= $this->makePartial('list_pagination_simple') ?>
+                <?php endif ?>
+            </div>
+        </div>
+    <?php endif ?>
     <table class="table data" data-control="rowlink">
         <thead>
             <?= $this->makePartial('list_head_row') ?>
```

And add `showTopPagination: true` to your List Widget config_list.yaml

**Comment by ayumi-cloud** [comment]
@mjauvin Yah that sounds a good idea, will do that. Thanks for your suggestion!

**Comment by ayumi-cloud** [comment]
Reminder: To update doc's as well, with the new yaml code.

**Comment by ayumi-cloud** [comment]
In testing I see this issue:

![image](https://user-images.githubusercontent.com/57409060/74286551-e3d60380-4d1f-11ea-8944-87f3c335df80.png)

Just going to move the code above the filters.

**Comment by bennothommo** [comment]
@ayumi-cloud I feel the filtered count should be somehow added to the pagination at the bottom that is already available. It might be a case of adjusting the verbage a bit:

ie. without filters:

`Displayed records: 1-5 of 1134`

and with filtered records:

`Displayed filtered records: 1-5 of 70 (1134 total)`

**Comment by LukeTowers** [comment]
@bennothommo @ayumi-cloud's issue is using lists with more than 50 records per page (i.e. 100) means that they have scroll down to the bottom to get the number of records returned every time. I do like your suggestion as a more generic change we could make though.

**Comment by ayumi-cloud** [comment]
@mjauvin @bennothommo @LukeTowers 

Thanks, I got a pretty good idea of what to do and will merge everyone's ideas.

To summarise:

1. Users can add `showTopPagination: true | false` to your List Widget `config_list.yaml`

2. If user is not displaying filters we show this: `Displayed records: 1-5 of 1134`

3. If user is using filters we show this: `Displayed filtered records: 1-5 of 70 (1134 total)`

4. Pages with big pagination lists e.g. 100 or bigger can bypass the yaml and just display the data results at the top and bottom.

**Comment by LukeTowers** [comment]
> Users can add showTopPagination: true | false to your List Widget config_list.yaml. Default will be false for pagination under 100 records on a single page.

`showPagination` will not be configured in config_list.yaml, that's what `recordsPerPage: 0` or `false` is for.

**Comment by ayumi-cloud** [comment]
@LukeTowers 

So `if (recordsPerPage >= 100 )` show point 2 and 3 automatically.
