### ISSUE TITLE
Checkbox lists are not displayed correctly in builds 460 - 461

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4823]
Link: https://github.com/octobercms/october/issues/4573#issuecomment-528940494

Should look like this:

![image](https://user-images.githubusercontent.com/57409060/70741021-5d4a7900-1d12-11ea-93f3-9dce0e4d8772.png)

They look like this:

![image](https://user-images.githubusercontent.com/57409060/70741002-5459a780-1d12-11ea-90a2-5f0072585ee9.png)

My PR: https://github.com/octobercms/october/pull/4599

Altered commit afterwards: https://github.com/octobercms/october/commit/6daea258b95e307f669efd38170c2a57dd0fbba5

Will try and re-fix things (when I get some free time).

**Comment by ayumi-cloud** [comment]
Code that fixes the above is taken directly from my pr:

```
.checkbox {display:block;min-height:20px;margin-top:10px;margin-bottom:15px;padding-left:20px}
.field-checkboxlist:not(.is-scrollable) {-webkit-border-radius:3px;-moz-border-radius:3px;border-radius:3px;background:#fff;border:1px solid #e2e2e2}
.field-checkboxlist .checkboxlist-controls {padding:15px 15px 0;border-bottom:1px solid #e2e2e2;color:#2a3e51;display:-webkit-box;display:-ms-flexbox;display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-box-align:baseline;-ms-flex-align:baseline;align-items:baseline}
.field-checkboxlist .checkboxlist-controls a {margin-right:15px;margin-bottom:15px;text-decoration:none;color:#2a3e51}
.field-checkboxlist .checkboxlist-controls > div {padding-right:15px;padding-bottom:15px}
.field-checkboxlist .checkboxlist-controls .search-input-wrap {margin-left: auto}
.field-checkboxlist-container:not(.is-scrollable) {padding: 20px 20px 2px 20px}
```

Add the above PR code and you get this screenshot:

![image](https://user-images.githubusercontent.com/57409060/70751930-74489580-1d29-11ea-8105-160cc58b421e.png)

Extra code to fix an extra issue:

![image](https://user-images.githubusercontent.com/57409060/70751999-9b9f6280-1d29-11ea-89d2-065fc16bb50c.png)

into this:

![image](https://user-images.githubusercontent.com/57409060/70752034-afe35f80-1d29-11ea-8558-3ee941994434.png)

Also add this code:

```css
.field-checkboxlist-scrollable .control-scrollbar.drag-scrollbar.vertical {
    padding-left: 5px;
}
```

- Screenshots were done in build 460.

(Wait for admins to review as @daftspunk  changed my pr code)

But at least this is a working solution in this comment.

**Comment by LukeTowers** [comment]
@ayumi-cloud could you submit a PR with this information with a screenshot of the demo page that you have as it is in 461 right now with how it should look and the code to make it look that way?

**Comment by ayumi-cloud** [comment]
https://github.com/octoberrain/test-plugin/pull/82

**Comment by ayumi-cloud** [comment]
Sure, will try and get a pr done in next few hours and test it on v461.

**Comment by daftspunk** [comment]
This occurs due to the introduction of the `quickselect` option. The feature requires a reconstruction of the form field's markup and styles. The current implemented used a "hacked" approach that did not include this reconstruction, therefore the rendering appears inconsistent according to the conditions

The issue has been accepted and will be processed soon. If you require this feature to be expedited, consider [purchasing a premium support subscription](https://octobercms.com/premium-support)

Note a PR that includes any additional hacks to fix this is unlikely to be accepted

**Comment by daftspunk** [comment]
Please be advised this is the intended appearance of this UI

![image](https://user-images.githubusercontent.com/1392869/71301801-13d7e900-23f8-11ea-81e8-8df875dbc578.png)

Fixed by 21f8c5f
Refs #4827

**Comment by Eoler** [comment]
> Fixed by [21f8c5f](https://github.com/octobercms/october/commit/21f8c5f272e0ab9a7acbccaf08feeb9e707d494a)
> Refs #4827

Is preview mode #4817 fixed by this too?

**Comment by ayumi-cloud** [comment]
I take it October is not meant to be touch screen friendly as per my comment here: https://github.com/octobercms/october/pull/4827#issuecomment-568266307

**Comment by ayumi-cloud** [comment]
Have updated daftspunk commit here to allow support for tap-targets on touch screen devices, see here for the pr: https://github.com/octobercms/october/pull/4841
