### ISSUE TITLE
RelationController issue when also using afterSave model event

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#4825]
I have a model called activity and a model called Achievement. They are related by a belongsToMany relation. 

When creating an Achievement from the Activity controller by using the RelationController, it writes two times the same relation to the pivot table. This is caused by my script in the afterSave event where I want to automatically create a relation between Achievement and Activities by using data from repeater field in Achievement. 

### Fix for the issue
Checking if relation between two models exist before creating a new relation in the RelationController. I've created a pull request for the fix.

https://github.com/octobercms/october/pull/4824

**Comment by Samuell1** [comment]
Isnt this same issue? https://github.com/octobercms/october/issues/4246

**Comment by SebastiaanKloos** [comment]
@Samuell1 No I think it is different. My afterSave method creates new links to the other model with the sync method. The RelationController then assumes it needs to be linked because there are no checks for duplicate links

**Comment by SebastiaanKloos** [comment]
I have a workaround which bypasses the contains method
