### ISSUE TITLE
Expand the character limit of the error message shown in the list view of system errors

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4828]
Currently event logs look like this:

![image](https://user-images.githubusercontent.com/57409060/70855512-cde4c780-1ec3-11ea-883d-1f07a4dbe412.png)

The problem I find is that, I can't read the whole message and have to open the error log, just to be able to read the message everytime!

So is the same annoying thing Google Search does! They cut the search result and stop you from hovering a mouse to read the full title or description.

This bug is creating an extra click for users which is not needed.

So I click to read this:

![image](https://user-images.githubusercontent.com/57409060/70855539-52374a80-1ec4-11ea-9277-934bf25ba633.png)

When really all I need is the cms to do this:

![image](https://user-images.githubusercontent.com/57409060/70855559-a6422f00-1ec4-11ea-936b-f4681f3a4da7.png)

I just want to see the first error line in full.

I take it this is the code line that's annoying me:

https://github.com/octobercms/october/blob/56eab502606c2c1bb2e64f08e27db1467d211b4f/modules/system/models/EventLog.php#L82-L89

Please, please, please can we remove this character limit.

**Comment by LukeTowers** [comment]
@ayumi-cloud try looking at the error log page on a smaller screen, say 1200px wide and you'll see why it's required.

**Comment by ayumi-cloud** [comment]
@LukeTowers I don't get what you mean?

Here's a width 1200px:

![image](https://user-images.githubusercontent.com/57409060/70870165-d1418700-1f87-11ea-9df8-7da774047b73.png)

- Seems fine to me.

iPad example:

![image](https://user-images.githubusercontent.com/57409060/70870199-1e255d80-1f88-11ea-9e4d-ebc50f976865.png)

- Seems fine to me.

Smart phone example:

![image](https://user-images.githubusercontent.com/57409060/70870212-3eedb300-1f88-11ea-9c3e-91f973282b1a.png)

- I only issue an issue with the list not being responsive, but this issue would be the same if we cut the character limit to 100 anyway.

Is there any other issue and reason?

I would like to give full error summary and screen sizes under 756px make the list widget responsive and allow user to scroll left and right.

**Comment by LukeTowers** [comment]
Fair enough @ayumi-cloud, it was probably just an arbitrary number chosen to prevent the whole thing from being displayed which would definitely cause problems. Your regex change seems fine to me, just needs to get tested.

**Comment by bennothommo** [comment]
Fixed by #4830.
