### ISSUE TITLE
Enhanced List widget searching

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4829]
### Explainer

Currently October always you to do a search in the list widget for all fields.

However, sometimes a user may require a more in-depth search of the column data.

### Example

Let's take the following example list data:

Color | Quantity | Brand Name
---|---|---
yellow | 10 | Bob's Secret Sauce
blue | 12 | Best Widgets Company
orange | 30 | James Ever-Green Company
red | 26 | Big Yellow Company

### Search One Example

For the first search example we search for the keyword `blue` this gives us the following results:

Color | Quantity | Brand Name
---|---|---
blue | 12 | Best Widgets Company

### Search Two Example

For the second search example we search for the keyword `yellow` this gives us the following results:

Color | Quantity | Brand Name
---|---|---
yellow | 10 | Bob's Secret Sauce
red | 26 | Big Yellow Company

This is where things start to go wrong, very quickly!

Maybe the user just wanted to search for the `Color` and not the `Brand Name`.

### Solution

Allowing two search options.

- `All` - this allows a user to search all the columns in the list widget.

- `Custom` - this allows the user to select the columns they want to receive the search results.

Taking the above example let's do a third example.

### Search Three Example

A user selects the `custom` search and selects the checkbox `Color` then again searches for the keyword `yellow` this gives the following results:

Color | Quantity | Brand Name
---|---|---
yellow | 10 | Bob's Secret Sauce

### Conclusion

Pretty common sense, hopefully this could get added to the cms.

**Comment by LukeTowers** [comment]
@ayumi-cloud this already exists in the form of the text filter

**Comment by ayumi-cloud** [comment]
@LukeTowers very sorry, I totally wrote this incorrectly, let me try to write what I mean.

### First issue

Let's say I set the following columns, to view `Color` and `Quantity` - but make `Brand Name` invisible, e.g.

![image](https://user-images.githubusercontent.com/57409060/70870955-baa02d80-1f91-11ea-900f-5b852cc219e2.png)

When I do a search **October will search all three columns**.

I think this is a bug and **_October show only search visible column data_** (not invisible column data).

### Second issue

We were thinking more about setting up two different filters on the same web page.

The normal filter row we setup granular filters e.g. show a list of `colors` to select, e.g.

![image](https://user-images.githubusercontent.com/57409060/70871036-c6402400-1f92-11ea-9e88-f66b73be635e.png)

But also have a second filter being displayed in the search box area, where a user can turn on/off columns.

![image](https://user-images.githubusercontent.com/57409060/70871169-2e433a00-1f94-11ea-9194-6a325d06abe4.png)

Above: Search box (not selected)

![image](https://user-images.githubusercontent.com/57409060/70871184-5b8fe800-1f94-11ea-8ae7-a9e1d1fb308f.png)

Above: Search box (selected - opened)

![image](https://user-images.githubusercontent.com/57409060/70871209-9003a400-1f94-11ea-898f-e1490214a0c0.png)

Above: User clicks on the button to open a sub-menu in the search box to pick which columns to search on).

This is what we were thinking of coding...

Is it possible to connect up two or more filter files via YAML? 

e.g.

```
filter: [ 'config_filter.yaml', 'search_filter.yaml' ]
```

**Comment by bennothommo** [comment]
@ayumi-cloud Limiting the scope of searched columns can be achieved by the `searchable` option that is defined in the [column definition](https://octobercms.com/docs/backend/lists#column-options) in the `columns.yaml` file for your list. The column being hidden has no bearing on the search.

**Comment by LukeTowers** [comment]
> I think this is a bug and October should only search visible column data (not invisible column data).

I disagree with that. There is the separate `searchable` property as @bennothommo said which is what you should use if you want a column excluded from search. I occasionally find it useful to include hidden columns in my search.

**Comment by ayumi-cloud** [comment]
@bennothommo @LukeTowers thanks, I think I'm mixing things up with `sortable` as well.

I set my hidden columns to this:

```yaml
sortable: true
searchable: false
```

Going to close this issue, thanks for your feedbacks. 👍
