### ISSUE TITLE
Scoreboard pie chart treats 'empty' values as 'empty' and not as 'zero'

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4833]
When using the scoreboard pie chart widget and putting an `empty` variable into it, currently October treats it as `empty` and not `zero`.

As the value should be a `number only`, October should treat an `empty` field as `zero` and not as `empty`.

Here is an example demoing the issue:

```html
<div class="scoreboard">
    <div data-control="toolbar">
        <div class="scoreboard-item control-chart" data-control="chart-pie">
            <ul>
                <li data-color="#95b753">Passed <span>100</span></li>
                <li data-color="#cc3300">Failed <span></span></li>
            </ul>
        </div>
    </div>
</div>
```

In the above example we can see `Passed` having `100%` and `Failed` having `0%` (Blank). The expected output should be a `green full circle` (green being passed and red being failed). However, we get a `full grey circle` instead.

![image](https://user-images.githubusercontent.com/57409060/71129113-a0ab5880-21e6-11ea-85a6-150d1940c873.png)

The expected output should be this instead:

![image](https://user-images.githubusercontent.com/57409060/71133355-34ceed00-21f2-11ea-91a2-2236304e8b2b.png)

into this:

![image](https://user-images.githubusercontent.com/57409060/71129219-e0724000-21e6-11ea-9f35-8c9728079697.png)

> When you count something and it's not there - it's classed as zero.
>
> When you code something and it's not there - it's classed as null.
>
> Here we are counting a percentage score.

Below is the code to force the outcome:

```html
<div class="scoreboard">
    <div data-control="toolbar">
        <div class="scoreboard-item control-chart" data-control="chart-pie">
            <ul>
                <li data-color="#95b753">Passed <span>100</span></li>
                <li data-color="#cc3300">Failed <span>0</span></li>
            </ul>
        </div>
    </div>
</div>
```

or hacking October and doing this:

```html
<div class="scoreboard">
    <div data-control="toolbar">
        <div class="scoreboard-item control-chart" data-control="chart-pie">
            <ul>
                <li data-color="#95b753">Passed <span><?php ($pass > 0) ? e($pass) : '0' ?></span></li>
                <li data-color="#cc3300">Failed <span><?php ($fail > 0) ? e($fail) : '0' ?></span></li>
            </ul>
        </div>
    </div>
</div>
```

This shouldn't be needed as October should treat any `empty` variables in that location as `zero` and not as `empty`.

This may effect the other charts as well ?

File location: https://github.com/octobercms/october/blob/develop/modules/system/assets/ui/js/chart.pie.js

**Comment by ayumi-cloud** [comment]
Likewise the grey area can't count either, see example:

```html
<div class="scoreboard">
    <div data-control="toolbar">
        <div class="scoreboard-item control-chart" data-control="chart-pie">
            <ul>
                <li data-color="#95b753">Passed <span>60</span></li>
                <li data-color="#cc3300">Failed <span>0</span></li>
            </ul>
        </div>
    </div>
</div>
```

We get this result:

![image](https://user-images.githubusercontent.com/57409060/71132708-30a1d000-21f0-11ea-9422-2c3d461d4e4e.png)

Expected result should see 40% of the pie chart being grey.

So we should see this for inverse counting:

![image](https://user-images.githubusercontent.com/57409060/71133012-2a602380-21f1-11ea-8798-05cac4d6f05f.png)

**Comment by daftspunk** [comment]
You are welcome to submit a pull request to address this.
