### ISSUE TITLE
"Skip this update (always/once)" for plugins - do not work

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4842]
Got a few errors to report from our company...

Screenshot:

![71361672-90e79780-258b-11ea-9bdc-9ee0c729f28f](https://user-images.githubusercontent.com/57409060/71371733-0b271480-25aa-11ea-8259-d19d435c4af9.png)

These functions do not work at all and will continue showing an update message in the dashboard, even after being selected.

Screenshot:

![image](https://user-images.githubusercontent.com/57409060/71361788-ee7be400-258b-11ea-8bc8-ea5f2fbabf56.png)

The dashboard says build 462 now yet, those two plugins being `Skip this update` still make the dashboard say `Pending software updates`

Also widget is not responsive and hangs out of the box.

Screenshot:

![image](https://user-images.githubusercontent.com/57409060/71361898-4dd9f400-258c-11ea-988c-4a6f394db663.png)

**Comment by LukeTowers** [comment]
Consider signing up for Premium Support if you have urgent support needs: https://octobercms.com/premium-support

**Comment by bennothommo** [comment]
@ayumi-cloud I've looked into this, and everything seems to be working as expected. The **Skip update (once only)** option means it will skip the update *this time* - it's intention is to be used if you wish to update, say, all other plugins with minor updates and leave a major update on a plugin until you've had time to ascertain that it will be compatible with your installation. If you were to check for new updates again immediately afterwards, the update will reappear.

The **Skip update (always)** option simply disable any further updates for that plugin and would be used, for example, if a plugin update requires a PHP version or library that is totally incompatible with your hosting or October CMS installation.

If you can demonstrate a scenario where either of these options do not work as stated, please feel free to provide the info and we will re-open this.
