### ISSUE TITLE
Make it more obvious why plugins missing dependencies have not been loaded

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4843]
Got a few errors to report from our company...

A few days ago our internet went down in Tokyo so we moved one of our plugins we were building to `localhost` from our `server backup zip file`.

The plugin "**required**" other plugins to be installed as per it's `Plugin.php` file:

```php
    public $require = [
        'RainLab.User',
        'RainLab.Location',
        'RainLab.Translate'
    ];
```

When we opened the `Settings > Updates & Plugins` the **plugin did not show up**!

When we opened up the `Builder` plugin and did a `plugin search` the **plugin did not show up**!

We thought that we installed the plugin incorrectly or there was an error. 

So before we started hunting for the error, we uploaded the `required` plugins.

After installing the `required` plugins **our plugin showed up**!

We checked the `event logs` page and **no error message(s)**!

This is no good! This is a pure guessing game!

It would be much better if the plugin showed up and displayed an error message saying "_**it can not run due to needing the required plugins!**_" Having it become invisible just created a huge amount of issues to us!

For our dependencies, we have our own checking, where if a user for some strange reason doesn't install one of the dependencies the plugin shows the following message:

![cvsdcvsdx](https://user-images.githubusercontent.com/57409060/71362523-3d2a7d80-258e-11ea-9b44-90c2d3e022ec.png)

This message is shown at the top of all the web pages in the plugin to indicate to the user the correct action needed to run the plugin!

This same action style should be added to the core to check both `required` plugins and `dependencies` instead of just making the plugin invisible.

**Comment by bennothommo** [comment]
@ayumi-cloud Currently any missing dependencies come up as a warning that "needs attention" in the dashboard:

![Screen Shot 2019-12-27 at 00 19 34-fullpage](https://user-images.githubusercontent.com/15900351/71482667-d089da00-283e-11ea-9bd0-862742e45ada.png)

I agree, however, that any plugins that are missing dependencies should appear in the Plugin list however, with a message indicating that they are missing dependencies.
