### ISSUE TITLE
Missing validation translation for "extensions" rule

### ISSUE THREAD

**Issue by iotch** [octobercms/october#4844]
OctoberCMS Build: v1.0.462

[validation.php](https://github.com/octobercms/october/blob/master/modules/system/lang/en/validation.php) lacks translation for the "extensions" rule which is used by FileUpload widget:

https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/FileUpload.php#L435

I'm not good in English, so it's better to have it fixed by someone else. Thanks.

**Comment by daftspunk** [comment]
I have made a note to address this ourselves in a future release. Thanks for the report @iotch
