### ISSUE TITLE
Dynamic importExportConfig in same controller

### ISSUE THREAD

**Issue by rashedshaon** [octobercms/october#4847]
I want to implement two different import procedure in same controller. As October CMS configuration I created two import_export config file and two different Import Model Class. But it always point the Initial config file model class which I defined in `public $importExportConfig = 'config_import_export.yaml';` controller property.

My implementation code is given bellow, 

    public $importExportConfig = 'config_import_export.yaml';
    
    public function __construct()
    {
    ...
    }
    
    public function import($context = null)
    {
        $this->asExtension('ImportExportController')->setConfig('config_import_export.yaml');
        $this->asExtension('ImportExportController')->import($context);
    }
    
    public function system_import($context = null)
    {
        $this->asExtension('ImportExportController')->setConfig('config_system_import_export.yaml');
        $this->asExtension('ImportExportController')->import($context);
        return $this->makePartial('system_import');
    }
Code in config file,

    import:
        title: 'Import Phone Numbers'
        modelClass: Bol\PhoneManager\Models\SimImport
        list: $/bol/phonemanager/models/sim/export_import_columns.yaml
        redirect: bol/phonemanager/sim/import

If I initially `public $importExportConfig = '';` make the property blank then its points the proper Model Class as config file but then throw an error like bellow,

[![enter image description here][1]][1] 

  [1]: https://i.stack.imgur.com/TK7XF.png

I am trying to solve in many ways but I can't found any solution. If there any other solution please help.

**Comment by LukeTowers** [comment]
@rashedshaon typically the way that I handle this sort of dynamic config replacement is to override the values in the controller constructor before calling the parent constructor method. As a note, you have access to the current action in the constructor, so you can do the following:

```php
public function __construct()
{
    $config = \Backend\Classes\BackendController::$action === 'system_import' ? 'system_' : '';
    $this->importExportConfig = $this->makeConfig("config_$config_import_export");
    parent::__construct();
}
```
Note that I haven't tested the above, but that's roughly what you'd need to do.

**Comment by rashedshaon** [comment]
Dear @LukeTowers , Thanks for your reply. I tried in this way before but the problem is before execute `parent::__construct() $this->action` value is null. How I obtain which action is called?

**Comment by LukeTowers** [comment]
@rashedshaon hmm, in that case you could also try looking at the value of the current url with `url()->current()`

**Comment by rashedshaon** [comment]
@LukeTowers  thanks for the idea. now I solves this like bellow,
```
    public function __construct()
    {

        $action = last(explode('sim/', url()->current()));
        $this->importExportConfig = "config_".$action."_export.yaml";

        parent::__construct();
        ...
    }
```
But my question is why ` ->setConfig('config_system_import_export.yaml'); ` is not working properly? is it bug or others?

**Comment by LukeTowers** [comment]
@rashedshaon my guess is that it's too late in the request cycle, anything that pulls from the config value has probably already done so as a part of the initialization process before `setConfig()` gets called in your example.
