### ISSUE TITLE
Flag and/or remove plugins from marketplace where their github repo has been deleted

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4848]
I would like to suggest the idea of adding some automatic quality control checks in the marketplace!

For example, if a user deletes all their github plugin repo's this would be a strong indicator that the plugins are no longer maintained and carry a risk of many bugs and errors!

It would be useful to users to warn them and/or prevent them from downloading such plugins.

Here are a few examples:

Marketplace link: https://octobercms.com/plugin/linkonoid-shortcodesengine
Github repo: https://github.com/linkonoid/shortcodesengine

![image](https://user-images.githubusercontent.com/57409060/71412754-fc426f80-2646-11ea-8985-7194e7b5e672.png)

Marketplace link: https://octobercms.com/plugin/linkonoid-scpincludecontent
Github repo: https://github.com/linkonoid/scpincludecontent

![image](https://user-images.githubusercontent.com/57409060/71412754-fc426f80-2646-11ea-8985-7194e7b5e672.png)

etc.

Clearly, it would be a waste of time for people to download and use any of these plugins.

It would be helpful if the marketplace did some automatic checks and flagged any github plugin pages that get deleted.

> Create a cron job and check using the github api or git command if the repo exists or not once a day. If fails then flag or remove the plugin in the marketplace.

**Comment by bennothommo** [comment]
@ayumi-cloud FWIW, the repos above were renamed to https://github.com/linkonoid/octobercms-shortcodesengine and https://github.com/linkonoid/octobercms-scpincludecontent. The Shortcode Plugin was last updated on Sep 25, 2019 as well, which leads me to believe that they are using a manual method of pushing updates to the marketplace.

This would be evidence as to why we can't simply assume that a plugin is abandoned simply because their public repository link is out of date.

If you believe a marketplace plugin is abandoned, and you've tried contacting the author through the marketplace and had no response, then you always have the recourse of email hello@octobercms.com and getting the team to look into it.

**Comment by ayumi-cloud** [comment]
@bennothommo 

Yah it seems you are right, about the renamed repos.

Though I still believe October should add an automatic check to make sure the repo's are not moved, renamed or deleted. If the automatic cron job github api check brings up a 404 then the code can send an email to the author, letting them know of this issue and if no reply from the author happens in a month period then an email should signal to the website managers etc.

Very simple to setup and automatics the process, making the website more efficient and less work for the managers to keep track of things.

That's my reason for keeping this issue still open.

**Comment by LukeTowers** [comment]
@ayumi-cloud automation follows process, so if this becomes a big enough issue that dealing with it manually becomes too cumbersome, I'm sure we'll develop automation to handle it. In the meantime, feel free to report this sort of thing to hello@octobercms.com.

**Comment by ayumi-cloud** [comment]
Maybe one of the girls in the office can code a bot to scrape the october website and check all the plugins, then will email a mass list of issues.

**Comment by ayumi-cloud** [comment]
@LukeTowers I will message you later in Slack with the results of the scrape, looking at some of the results coming in there are quite a few issues going on.

**Comment by ayumi-cloud** [comment]
Oh dear,

![image](https://user-images.githubusercontent.com/57409060/71544834-8fe3ab00-297b-11ea-8f2e-6bba9b37016d.png)

Check out what I just spotted.

**Comment by ayumi-cloud** [comment]
+1 for automation.

**Comment by ayumi-cloud** [comment]
Sally has finished crawling the october website and I'm manually processing the data right now.

I can safely say there are hundreds of 404's in the plugin section and quite a lot in the theme section as well.

My conclusion, which I will discuss in private is that you definitely need some automation! There's a big issue going on behind the scenes.

**Comment by ayumi-cloud** [comment]
Hello everyone, our company today ran a bot through the whole october cms website. If you are a plugin or theme author, please can you check out this list of errors and correct them if they belong to you!

https://htmlpreview.github.io/?https://github.com/ayumi-cloud/oc-marketplaces-issues/blob/master/October%20Plugins%20and%20Themes%20Issues.html

Let's keep the marketplace clean and high quality.

That is a list of broken links and assets to all plugins and themes in the marketplace.

p.s. Full list of october website issues will be discussed in private.

**Comment by 36864** [comment]
That list includes obvious example links used in documentation (including `example.com` and `localhost` links) as well as links posted in reviews by users.

I suggest ignoring common test domains and ignoring the reviews tab when looking for dead links.

**Comment by ayumi-cloud** [comment]
@36864 Or the authors could write the code properly and use the correct HTML5 tags. Instead of creating a link, they should wrap them in a `<code>` or `<mark>` tag, e.g.

```html
<a href="http://localhost/project">http://localhost/project</a>
```

should be

```html
<code>http://localhost/project</code>
```
