### ISSUE TITLE
Bug with changed query builder paginate signature

### ISSUE THREAD

**Issue by Malezha** [octobercms/october#4849]
- OctoberCMS Build: 461
- PHP Version: 7.3.13
- Database Engine: mysql

### Description:
When used Laravel pagination signature for parameters current page will be [reseted](https://github.com/octobercms/library/blob/dfd85ebb48922c2abe49b5834c30d9d3e6ef15b5/src/Database/Builder.php#L119).

### Steps To Reproduce:

```php
$model = new class () extends \October\Rain\Database\Model {
    protected $table = 'some_table';
};

$perPage = 10;
$currentPage = 2;
$result = $model->query()->paginate($perPage, ['*'], 'page', $currentPage);

dd($result->currentPage(), $currentPage);
```

**Comment by bennothommo** [comment]
@Malezha Unless I'm mistaken, `$model->query()` in the example above should return an instance of `Illuminate\Database\Eloquent\Builder`, which uses the same signature as above.

Would you be able to double-check if this is the case?

**Comment by Malezha** [comment]
@bennothommo nope, it's returned `October\Rain\Database\Builder`
You can reproduce it:
```php
$model = new class () extends \October\Rain\Database\Model {
    protected $table = 'some_table';
};
get_class($model->query()); // "October\Rain\Database\Builder"
```

**Comment by Malezha** [comment]
OctoberCMS version was updated to 462.

**Comment by bennothommo** [comment]
@Malezha You should be able to statically call `paginate` on the model which will use the same signature as Laravel.

Example:
```
use Backend\Models\User;

$rows = User::paginate($perPage, ['*'], 'page', $currentPage);
```

**Comment by Malezha** [comment]
@bennothommo are you kidding me? Any query builder method returned October builder. 
```
use Backend\Models\User;
get_class(User::where('email', 'mail@example.com')); // October\Rain\Database\Builder
get_class(User::orderByDesc('created_at')); // October\Rain\Database\Builder
```
If `October\Rain\Database\Builder` inherit `Illuminate\Database\Eloquent\Builder` so method paginate must work exactly same.
@daftspunk when you decide to [simplify api](https://github.com/octobercms/library/commit/9d6fa05a3d3ee6e0e3b0807cd9ff6d3c5a488245#diff-b26ff3bbb0e6a36c3a09242b56a270e2) no need violation [LSP](https://en.wikipedia.org/wiki/Liskov_substitution_principle).

**Comment by bennothommo** [comment]
@Malezha I apologise - you are right. However, it looks like it was an intentional (and justified) change, and given the [docs](https://octobercms.com/docs/services/pagination#paginating-eloquent-results) already specify that the second argument in the method is for defining the current page, it's likely not going to change any time soon.

**Comment by LukeTowers** [comment]
Hmm, this seems like a problem to me. 

Our signature: `$perPage = 15, $currentPage = null, $columns = ['*'], $pageName = 'page')`
https://github.com/octobercms/library/blob/dfd85ebb48922c2abe49b5834c30d9d3e6ef15b5/src/Database/Builder.php#L115

Laravel's signature: `$perPage = null, $columns = ['*'], $pageName = 'page', $page = null)`
https://github.com/laravel/framework/blob/6.x/src/Illuminate/Database/Eloquent/Builder.php#L698

Note that there is already an initial attempt at supporting Laravel's signature here: https://github.com/octobercms/library/blob/dfd85ebb48922c2abe49b5834c30d9d3e6ef15b5/src/Database/Builder.php#L117-L120
```php
        if (is_array($currentPage)) {
            $columns = $currentPage;
            $currentPage = null;
        }
```
so I think the appropriate thing to do here would be to support both fully.

Thoughts @bennothommo @daftspunk @Malezha?

**Comment by daftspunk** [comment]
> @daftspunk when you decide to simplify api no need violation LSP.

@Malezha, to give some history on this, this is an artefact from a time when Laravel only supported passing the page parameter via `$_POST['page']`, you couldn't even customise the variable name. It was unacceptable so we added it ourselves. Eventually, they caught up to our thinking and added it themselves.

**Comment by Malezha** [comment]
@daftspunk thank you and I apologize for rudeness in statements.

**Comment by mjauvin** [comment]
Isn't that a breaking change?

**Comment by LukeTowers** [comment]
@mjauvin no, the commit adds support for both October's signature & Laravel's signature. There is a breaking change to the simplePaginate() method, but given that the current signature didn't even line up with our own signature present in paginate() let alone Laravel's and that it's a pretty obscure and rarely used aspect of the API we're thinking it's going to be fine. It will be mentioned as a change to the API in the changelog however.
