### ISSUE TITLE
Fix duplicate content issues with octobercms website

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4853]
The octobercms website has thousands of duplicate content issues.

Here is an example:

URL: https://octobercms.com/plugins/pkurg-visitors?p=8

Which is the exact same as:

URL: https://octobercms.com/plugins/pkurg-visitors

Source code error:

![image](https://user-images.githubusercontent.com/57409060/71545605-118c0680-2985-11ea-944c-39ed890cedfa.png)

First the `rel="canonical"` has a query string which is a pure no-no to do!

Second the `rel="canonical"` is pointing to:

URL: https://octobercms.com/plugins/pkurg-visitors?p=8

Which is the exact same as:

URL: https://octobercms.com/plugins/pkurg-visitors

Which is the exact same as:

URL: https://octobercms.com/plugins/

and so on...

(I pity the search engines)

### Solution

URL: https://octobercms.com/plugins/pkurg-visitors?p=8
Canonical URL: https://octobercms.com/plugins

Forum has issues as well:

URL Example: https://octobercms.com/forum/post/i-need-to-use-a-lib-on-my-plugin-how-to-add-it-by-composer?page=1

![image](https://user-images.githubusercontent.com/57409060/71546073-d1c81d80-298a-11ea-8e30-816cc5ad1631.png)

### Solution

URL: https://octobercms.com/forum/post/i-need-to-use-a-lib-on-my-plugin-how-to-add-it-by-composer?page=1

Canonical URL: https://octobercms.com/forum/post/i-need-to-use-a-lib-on-my-plugin-how-to-add-it-by-composer

**Comment by ayumi-cloud** [comment]
Forum has issues as well:

URL Example: https://octobercms.com/forum/post/i-need-to-use-a-lib-on-my-plugin-how-to-add-it-by-composer?page=1

![image](https://user-images.githubusercontent.com/57409060/71546073-d1c81d80-298a-11ea-8e30-816cc5ad1631.png)

### Solution

URL: https://octobercms.com/forum/post/i-need-to-use-a-lib-on-my-plugin-how-to-add-it-by-composer?page=1

Canonical URL: https://octobercms.com/forum/post/i-need-to-use-a-lib-on-my-plugin-how-to-add-it-by-composer

**Comment by ayumi-cloud** [comment]
Forum has issues as well:

URL Example: https://octobercms.com/forum/post/i-need-to-use-a-lib-on-my-plugin-how-to-add-it-by-composer?page=1

![image](https://user-images.githubusercontent.com/57409060/71546073-d1c81d80-298a-11ea-8e30-816cc5ad1631.png)

### Solution

URL: https://octobercms.com/forum/post/i-need-to-use-a-lib-on-my-plugin-how-to-add-it-by-composer?page=1

Canonical URL: https://octobercms.com/forum/post/i-need-to-use-a-lib-on-my-plugin-how-to-add-it-by-composer

---

URL: https://octobercms.com/forum/chan/october-best-practices?page=9

Points to:

https://octobercms.com/forum/post/i-need-to-use-a-lib-on-my-plugin-how-to-add-it-by-composer?page=1

and 

https://octobercms.com/forum/chan/october-best-practices?page=9

### Solution

URL: https://octobercms.com/forum/chan/october-best-practices?page=9

Points to:

https://octobercms.com/forum/post/i-need-to-use-a-lib-on-my-plugin-how-to-add-it-by-composer

and 

Canonical URL: https://octobercms.com/forum/chan/october-best-practices

---

URL: https://octobercms.com/forum/user/fadyalkhateeb17601

Points to: https://octobercms.com/forum/post/i-need-to-use-a-lib-on-my-plugin-how-to-add-it-by-composer?page=last#post-14929

### Solution

URL: https://octobercms.com/forum/user/fadyalkhateeb17601
Canonical URL: https://octobercms.com/forum/user/fadyalkhateeb17601

Points to: https://octobercms.com/forum/post/i-need-to-use-a-lib-on-my-plugin-how-to-add-it-by-composer?page=last#post-14929
Canonical URL: https://octobercms.com/forum/post/i-need-to-use-a-lib-on-my-plugin-how-to-add-it-by-composer

---

As you can see one URL has turned into several.

**Comment by 36864** [comment]
>Here is an example:
>
>URL: https://octobercms.com/plugins/pkurg-visitors?p=8
>
>Which is the exact same as:
>
>URL: https://octobercms.com/plugins/pkurg-visitors

The first one links to page 8 of the plugins page, while the second one links to page 1.

**Comment by ayumi-cloud** [comment]
@36864 I suggest you read here about canonicalization: https://support.google.com/webmasters/answer/139066
