### ISSUE TITLE
Broken links in the main website

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4855]
Will go through each one.

URL: https://octobercms.com/about

![image](https://user-images.githubusercontent.com/57409060/71560992-563c9e00-2a68-11ea-8cc4-92313bdcb52d.png)

404 to their LinkedIn web pages (bad luck Stalkers)

---

URL: http://octobercms.com/beta
URL: https://octobercms.com/beta

No such page has been deleted, someone linked it from this web page: https://octobercms.com/forum/post/update-from-beta-to-rc

Redirect that location back to home page maybe?

---

URL: http://octobercms.com/fundraising
URL: https://octobercms.com/fundraising

Coming from several pages:

- https://octobercms.com/blog/post/how-october-pond-will-simplify-development-and-deployments

![image](https://user-images.githubusercontent.com/57409060/71561031-1924db80-2a69-11ea-829c-217f1c767a41.png)

- https://octobercms.com/blog/post/mid-year-update-2017

![image](https://user-images.githubusercontent.com/57409060/71561044-3659aa00-2a69-11ea-9f6a-9d7501d0816f.png)

- https://octobercms.com/blog/post/marketplace-algorithm-update-and-deleting-projects

![image](https://user-images.githubusercontent.com/57409060/71561052-538e7880-2a69-11ea-8d33-73a8080b2808.png)

---

URL: http://octobercms.com/gallery
URL: https://octobercms.com/gallery

Coming from:

- https://octobercms.com/blog/post/octobercms-website-gallery

![image](https://user-images.githubusercontent.com/57409060/71561065-8a648e80-2a69-11ea-88db-52b83ffb1562.png)

---

URL: http://octobercms.com/resources
URL: https://octobercms.com/resources

Coming from several pages:

- https://octobercms.com/forum/post/tutorial-request?page=1
- https://octobercms.com/forum/post/tutorial-request

![image](https://user-images.githubusercontent.com/57409060/71561072-ba139680-2a69-11ea-97b0-11b373a80a19.png)

- https://octobercms.com/forum/user/frankwikstrom

![image](https://user-images.githubusercontent.com/57409060/71561078-ce579380-2a69-11ea-8b48-44e5e0dd8569.png)

- https://octobercms.com/forum/post/where-to-start-coding?page=1
- https://octobercms.com/forum/post/where-to-start-coding

![image](https://user-images.githubusercontent.com/57409060/71561093-e4fdea80-2a69-11ea-9103-921dc5f20d9b.png)

Redirect them to the doc's getting started section

---

URL: http://octobercms.com/terms/quality-guidelines
URL: https://octobercms.com/terms/quality-guidelines

![image](https://user-images.githubusercontent.com/57409060/71561147-9dc42980-2a6a-11ea-84af-c5e39b20491c.png)

Coming from: https://octobercms.com/blog/post/lets-build-a-perfect-marketplace

---

URL: http://octobercms.com/thefamily/october/market
URL: https://octobercms.com/thefamily/october/market

![image](https://user-images.githubusercontent.com/57409060/71561186-2216ac80-2a6b-11ea-9b72-4fdfa00332ce.png)

Coming from: https://octobercms.com/plugin/mirjan-vklogin

---

URL: https://octobercms.com/help/site/marketplace

![image](https://user-images.githubusercontent.com/57409060/71561207-63a75780-2a6b-11ea-9263-e4e0325d4c76.png)

Those two links

---

URL: https://octobercms.com/partners/profile/digital-wizards

![image](https://user-images.githubusercontent.com/57409060/71561223-a6692f80-2a6b-11ea-94fb-75a886e4568b.png)

https://digitalwizards.biz
error code: 12029 (no connection)

mailto:hello@digitalwizards.biz
error code: 12007 (no such host)

---

URL: https://octobercms.com/partners/profile/lanthopusx

![image](https://user-images.githubusercontent.com/57409060/71561249-ee885200-2a6b-11ea-8488-e3e2cf335e7c.png)

https://www.mbwebstudios.co.uk/contact
error code: 404 (not found)

---

Thanks.

**Comment by daftspunk** [comment]
Thanks @ayumi-cloud ! This was a very useful report, all the links have been repaired
