### ISSUE TITLE
Broken links in Blog section of main website

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4856]
Will try and show these in great detail as well.

URL: https://octobercms.com/blog/post/advanced-content-marketing-and-analytics

![image](https://user-images.githubusercontent.com/57409060/71561289-6c4c5d80-2a6c-11ea-9074-c7ceb0d9555c.png)

---

URL: https://octobercms.com/blog/post/getting-started-october-cms-static-pages-v2

![image](https://user-images.githubusercontent.com/57409060/71561305-a9b0eb00-2a6c-11ea-9189-c9e28ef9897c.png)

---

URL: https://octobercms.com/blog/post/how-october-pond-will-simplify-development-and-deployments

![image](https://user-images.githubusercontent.com/57409060/71561315-c2b99c00-2a6c-11ea-963c-0a3f53b93a86.png)

---

URL: https://octobercms.com/blog/post/marketplace-algorithm-update-and-deleting-projects

![image](https://user-images.githubusercontent.com/57409060/71561325-e5e44b80-2a6c-11ea-9a4c-af365cd16626.png)

---

URL: https://octobercms.com/blog/post/mid-year-update-2017

![image](https://user-images.githubusercontent.com/57409060/71561334-00b6c000-2a6d-11ea-8046-f3f1801603e7.png)

---

URL: https://octobercms.com/blog/post/october-stable-release

![image](https://user-images.githubusercontent.com/57409060/71561341-204de880-2a6d-11ea-906d-b4ab8369c528.png)

(404 Linkedin pages probably gone into hiding from too many developers asking for help!)

---

URL: https://octobercms.com/blog/post/octobercms-website-gallery

![image](https://user-images.githubusercontent.com/57409060/71561350-44a9c500-2a6d-11ea-9b7c-ada3976afc20.png)

---

URL: https://octobercms.com/blog/post/partner-program-and-plugin-promotions

![image](https://user-images.githubusercontent.com/57409060/71561358-5f7c3980-2a6d-11ea-9d41-c2e60166eb69.png)

![image](https://user-images.githubusercontent.com/57409060/71561365-79b61780-2a6d-11ea-8c86-9b18f08fc422.png)

---

URL: https://octobercms.com/blog/post/running-october-aws-part-2

![image](https://user-images.githubusercontent.com/57409060/71561376-a5d19880-2a6d-11ea-82c0-bccba139042a.png)

This should not be linked - use correct HTML5 code either `<code>` or `<mark>`

---

URL: https://octobercms.com/blog/post/setting-local-october-cms-environment-vagrant-configuration-tutorial

![image](https://user-images.githubusercontent.com/57409060/71561397-d0bbec80-2a6d-11ea-997a-5dce7da2bb3a.png)

and

![image](https://user-images.githubusercontent.com/57409060/71561401-de717200-2a6d-11ea-8f10-9aa80e4f78b0.png)

This should not be linked - use correct HTML5 code either `<code>` or `<mark>`

---

Thanks

**Comment by daftspunk** [comment]
Thanks @ayumi-cloud ! This was a very useful report, all the links have been repaired
