### ISSUE TITLE
Lang::choice() is not working properly

### ISSUE THREAD

**Issue by Zollerboy1** [octobercms/october#4858]
- OctoberCMS Build: 462
- PHP Version: 7.4
- Database Engine: mysql
- Plugins Installed: Flynsarmy.IdeHelper-v1.0.9

### Description:
The `choice()` function of the `October\Rain\Translation\Translator` class (accessed through the `Lang` facade) is not working properly for languages with a language-code containing a dash (like `en-uk` or `es-ar`).

It calls the `Symfony\Component\Translation\MessageSelector::choose()` function to choose the correct plural form for a localization string. This function does in turn call the `Symfony\Component\Translation\PluralizationRules::get()` function, which chooses the correct plural position for the given locale. When it detects a locale code with more than 3 characters like `en-uk`, it tries to strip it down to just `en`, but it just searches for underscores, not dashes.  
So the Symfony classes expect locales like `en_UK` instead. The october backend localization system does therefore not work properly with pluralization, when a locale like `en-uk` is selected. It just prints the singular version every time.

### Steps To Reproduce:
- Create a plugin with a navigation where the label is set as `Lang::choice('author.plugin::lang.navigation.foo', 2)`.
- Create a language file for English, where the `navigation.foo` string is set to `'Bar|Bars'`.
- Set the locale 'English (United Kingdom)' in the user back-end preferences.

**Comment by bennothommo** [comment]
Fixed by https://github.com/octobercms/library/commit/64be2b64a235f35332d0062531a7ac34c7f9a1f6.
