### ISSUE TITLE
Need an image verification code feature to prevent spam

### ISSUE THREAD

**Issue by alanhwi** [octobercms/october#4859]
Octobercms is a very good CMS with high customization, modularity and speed. Thank you very much! But in the process of my actual use, there is a problem that always bothers me, that is, the Contact form function that the website must use. The Contact function often leads to a lot of spam, because there are still many regions in the world that can't use Google, and can't use Google reCAPTCHA. I need a similar “captcha for laravel”  - The image verification code is used to prevent the rampant spam.
（"Captcha for Laravel"  URL: https://github.com/mewebstudio/captcha）

I searched all the plugins on the Octobercms website and did not provide this function, and then I also wrote to multiple authors of Contact form plugins, hoping to add this function, but it seems that they have not added, I hope to get the developer's help, whether you can consider adding a plugin with a picture verification code function, because the message function is really very important for a website, without which the website cannot get valuable feedback.

Thank you very much! I hope that Octobermcs is getting better and better! and it will benefit more people.

**Comment by LukeTowers** [comment]
Please only use GitHub Issues for feature requests if you are using it as a pre-Pull Request collaboration tool. If you aren't planning on implementing it yourself, then it would be better suited being asked for on one of these channels:

Forum: https://octobercms.com/forum
Discord: https://discord.gg/gEKgwSZ

As a side note, if you would like to purchase my form building plugin, https://octobercms.com/plugin/luketowers-easyforms I would be willing to add a simplecaptcha field type in the plugin that you could use on your forms.

**Comment by bennothommo** [comment]
@alanhwi Just out of curiosity, which regions cannot use Google reCaptcha? I was of the understanding that v3 (the invisible captcha) may not be supported in some countries, but v2 was in very widespread usage.

**Comment by alanhwi** [comment]
@bennothommo Mainly some countries in Asia and Arab. it is impossible to access Google websites, and of course, it is impossible to use tools provided by Google. Even if developers use Google tools, such as Google reCaptcha（Also includes V2）, visitors(user) will not be able to load Google code. So that the Contact form also cannot be submitted.

**Comment by bennothommo** [comment]
@alanhwi Thanks for the further info. Given that the Captcha you linked to is a Laravel plugin, it should theoretically be able to be used in October, however, you may need to make slight adjustments to make it work. You would need to hook it into a Contact form plugin though, or roll out your own plugin in order to make use of it.
