### ISSUE TITLE
Sortable trait on model causes “ambiguous sort_order” error in belongsToMany relation 

### ISSUE THREAD

**Issue by tillathenun** [octobercms/october#4860]
I have a form with a relation widget showing a belongsTo relation.

```
public $belongsToMany = [
        'pages' => [
            ‘Company\Client\Models\CdmProjectPage',
            'table' => 'cdm_project_page_types',
            'key' => 'type_id',
            'otherKey' => 'page_id',
            'timestamps' => true
        ]
    ];
```
The **CdmProjectPage** model the relation returns has the _sortable_ trait and obviously a _sort_order_ column.

When I try to use the form that contains the relation widget in the backend, I get this error message:

> "SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'sort_order' in order clause is ambiguous (SQL: select `cdm_project_pages`.`id` from `cdm_project_pages` inner join `cdm_project_page_types` on `cdm_project_pages`.`id` = `cdm_project_page_types`.`page_id` where `cdm_project_page_types`.`type_id` = 3 and `cdm_project_pages`.`deleted_at` is null order by `sort_order` asc)" on line 664 of /Users/me/Sites/project/vendor/laravel/framework/src/Illuminate/Database/Connection.php

Removing the sortable trait makes it work again.

Have I missed something obvious or could I have stumbled upon a bug?

**Comment by mjauvin** [comment]
Can you share both DB tables schema? My guess is you have the sort_order field in both related tables, which creates the ambiguity.

**Comment by mjauvin** [comment]
It *might* be possible to explicitly specify the table in the `order by` clause by adding:

`'order' => 'table_name.sort_order asc'` to the $belongsToMany relation definition.
(ref. https://octobercms.com/docs/database/relations#detailed-relationships)

**Comment by tillathenun** [comment]
Your first guess was absolutely right: I had `sort_order` on the pivot table as well. Doh. Specifying the table name in the `order by` clause doesn’t work unfortunately.

Thank you very much for your replies.
