### ISSUE TITLE
Assets Combiner: custom asset filters support

### ISSUE THREAD

**Issue by BATCOH** [octobercms/october#4865]
- OctoberCMS Build: 462
- PHP Version: 7.3.13

### Description:
I try to add custom assets filter with my plugin and use `cms.combiner.beforePrepare` event as [described in examlle](https://github.com/octobercms/october/blob/72a763a9fa49b197eef59edb8ed18c026acb090e/modules/system/classes/CombineAssets.php#L414).

But filter never applies.

My local workaround is to put my filter registration directly to /modules/system/classes/CombineAssets.php.

### Steps To Reproduce:
* Check, that cms.enableAssetMinify is false or app.debug is enabled (we will use StylesheetMinify as example).
* Add this code in your plugin:
```php
public function boot()
{
    Event::listen('cms.combiner.beforePrepare', function ($assetCombiner, $assets) {
        $assetCombiner->registerFilter(['css', 'less', 'scss'], new \October\Rain\Parse\Assetic\StylesheetMinify);
    });
}
```
* Change some css.
* Check that combined css are not minified.

**Comment by SebastiaanKloos** [comment]
Did you elevate your plugin? I think combiner events need your plugin to be elevated

**Comment by LukeTowers** [comment]
@SebastiaanKloos is correct, they do require plugin elevation: https://octobercms.com/docs/plugin/registration#elevated-plugin. I had forgotten about that.
