### ISSUE TITLE
Wysiwyg pargraph drop down appears under on/off switch

### ISSUE THREAD

**Issue by wordshop-git** [octobercms/october#4868]
- OctoberCMS Build: 462

### Description:
![image](https://user-images.githubusercontent.com/58780682/71832902-c15b2580-30a3-11ea-840e-1c91d2a64e0e.png)
_This is how the issue will look to everyone_

![image](https://user-images.githubusercontent.com/58780682/71885553-7f2cf500-3132-11ea-8946-135954bf9556.png)
_This has a background colour within dev tools so not custom styling just making it easier to see/ avoid further confusion_

As above Wysiwyg drop down appears behind the button and text of the on/off switch within the backend. Happens when switch is set to either ON or OFF.

Assuming this is Froala and the switches styling clashing but couldn't seem to fix it in chrome devtools

You can toggle the switch whilst the drop down is open but you can still select the drop down option that's behind the switch so this doesn't break anything, I can simply move the switch further down the page so this isn't a massive issue but worth noting.

**Comment by w20k** [comment]
Looks good to me, couldn't reproduce, with the latest build of OCMS and test-plugin (gif). Maybe you have some custom css included? Or try rebuilding assets:

![Jan-07-2020 11-12-33](https://user-images.githubusercontent.com/1053320/71883263-bbfee900-313e-11ea-8c6a-6f2be85b3598.gif)

**Comment by bennothommo** [comment]
@w20k I think @wordshop-git is talking about the Slider checkbox (https://octobercms.com/docs/ui/checkbox). It appears to be underneath the menu just behind the "Heading 3" in the top screenshot.

**Comment by wordshop-git** [comment]
@w20k Definitely don't have custom css wouldn't know where to begin with that in the back end.

Mines also a pill on/off slider `type: switch` maybe yours is a `type: checkbox`?

This is my code

```
alert_button_text:
  label: 'Alert Button Text'
  span: auto
  type: text

active:
  label: 'Is Active'
  span: left
  default: 1
  type: switch
```

**Comment by w20k** [comment]
Thanks @bennothommo for clarification. Then it's a bit different problem, not style but the event is propagated underneath the Froala plugin. Need to take a look, how it's done there, or maybe it's our code ;) Second.

**Comment by w20k** [comment]
Found it -> z-index should be removed :) Not, sure why it's needed there, maybe @daftspunk do remember `why?`.

https://github.com/octobercms/october/blob/master/modules/system/assets/ui/less/checkbox.less#L232
https://github.com/octobercms/october/blob/master/modules/system/assets/ui/less/checkbox.less#L297

**Comment by Eoler** [comment]
> Found it -> z-index should be removed :) Not, sure why it's needed there, maybe @daftspunk do remember `why?`.

It's not only switch (checkbox) form fields, Froala dropdowns are also partially falling behind backend tab widgets.

**Comment by w20k** [comment]
@Eoler could you provide an example? It might be a `z-index` issue again.

**Comment by Eoler** [comment]
Yes, it probably is:
![Froala-dropdown-zindex](https://user-images.githubusercontent.com/680032/73306733-1b6f8680-421d-11ea-9f79-58ee2b00fd94.png)
