### ISSUE TITLE
Dropzone timeout issue

### ISSUE THREAD

**Issue by shiftaltd** [octobercms/october#4869]
- OctoberCMS Build: 462
- PHP Version: 7.2
- Database Engine: Mysql
- Plugins Installed: ---

### Description:
Dropzone timeout is set to default in media library. So people can't make upload more than 30s.
https://www.dropzonejs.com/#configuration

### Steps To Reproduce:
go to backend > media - upload a big file

**Comment by w20k** [comment]
It's not there in the FileUpload dropzone options in the init section. Feel free to submit a PR to fix that! 

Hint:
https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/fileupload/assets/js/fileupload.js#L100

**Comment by shiftaltd** [comment]
it should inherit the php.ini upload_max_filesize. i'll check how to do that

**Comment by w20k** [comment]
Maxfilesize is already there, timeout is left to be default.

**Comment by daftspunk** [comment]
This could also fail due to your web server configuration, PHP by default is set to 60 seconds. It seems unnecessary and unusual for dropzone to be implementing any kind of restriction here.

**Comment by Teranode** [comment]
Dropzone's default timeout is 30000 milliseconds
I've had to create my own formwidget to change the timeout to 0. This would then just leave the server side to handle. But this can also be easily be solved if an option was presented for the system form widget.

**Comment by bennothommo** [comment]
@daftspunk Dropzone implemented a timeout for XHR requests in version 4.4.0, which we upgraded to in build 460 (https://github.com/octobercms/october/commit/401b7419eef5929371f8202fe46f0c11768b3c1f). I suppose we'll probably have to set our own default, or remove the timeout completely and let server-side handle it.

**Comment by LukeTowers** [comment]
Fixed by #4878
