### ISSUE TITLE
When adding First Tab or Only Tab to Lazy array in `fields.yaml` they don't load

### ISSUE THREAD

**Issue by seanthepottingshed** [octobercms/october#4879]
- OctoberCMS Build: `464`
- PHP Version: `7.2`
- Database Engine: `mysql`
- Plugins Installed: `n/a`

### Description:

If you inadvertently add the first tab of many, or the only tab to the lazy load array the tab doesn't actually load. This obviously makes sense logically but may trip up new users. This applies to both prImary and secondary tabs.

### Steps To Reproduce:

- Download and install test plugin with following PR https://github.com/octoberrain/test-plugin/pull/83
- Navigate to `admin/october/test/people/update/6`

**Comment by LukeTowers** [comment]
@seanthepottingshed what would you say the solution should be? Should we be attempting to detect if the first tab actually shown (including trigger hidden / shown tabs) and force that not to be lazy loaded or should we trigger the load of a lazy loaded tab if it is the open tab when the JS initializes?

**Comment by seanthepottingshed** [comment]
@LukeTowers I think for consistency lazy loading of the tab in question when the JS initialises would make sense. I suspect this may be easier to implement when dealing with cases where a tab should be hidden due to trigger options as raised in: https://github.com/octobercms/october/issues/4880

**Comment by seanthepottingshed** [comment]
Bumpity bump

**Comment by bennothommo** [comment]
Cheers @seanthepottingshed. Fixed by https://github.com/octobercms/october/commit/f8634e07574d4d68eccb0a5fafdac69b9a7270ce.
