### ISSUE TITLE
Using 'combined' as first part of slug goes to 'Page Not Found'

### ISSUE THREAD

**Issue by rejuvenatedigital** [octobercms/october#4886]
**Summary**
I am having a problem when I try and visit a url that starts with 'combined' as part of a url it goes to the October's 'Page Not Found' page. 
For example http://www.hillardstrust.org/combined-ioq
I have tested this on several different ocotber installations and can confirm that it's still an issue in version 464.

**Reproduce steps**
To reproduce install october and go to a url such as /combined-ioq

**Expected Behaviour**
Using the example http://www.hillardstrust.org/combined-ioq I expect to go the custom 404 page I built.

**Actual Behaviour**
Url goes to octobers 'page not found' page

**Comment by mjauvin** [comment]
I cannot reproduce this. How did you define your custom 404 page? Mine is shown below:
```
title = "Page not found (404)"
url = "/404"
layout = "default"
==
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Page not found</h1>
        <p class="lead">We're sorry, but the page you requested cannot be found.</p>
    </div>
</div>
```

Note the `url = "/404"` line

**Comment by ayumi-cloud** [comment]
I'm seeing this error with one of our twig plugins, it seems when you start a uri with `combined` it causes a twig parsing error, we're trying to work out the reason ?

But we see it one a few of our servers as well, using the same twig plugins.

Do you get a stack trace, we could compare.

**Comment by ayumi-cloud** [comment]
I'm seeing this error with one of our twig plugins, it seems when you start a uri with `combined` it causes a twig parsing error, we're trying to work out the reason ?

We see it with a few of our servers, using the same twig plugins.

Do you get a stack trace, we could compare.

```
https://www.hillardstrust.org/com2bined-ioq <-- goes to 404

https://www.hillardstrust.org/combined-ioq <-- produces this error

https://www.hillardstrust.org/combine-ioq <-- produces this error

https://www.hillardstrust.org/test/combine-ioq <-- goes to 404
```

Exactly same as our servers.

[edit] It seems to be a problem using the word `combine` not `combined` digging deeper.

My theory is maybe it's coming from the server, to prevent a Mysql attack, I was looking at the Mod Security repo, but can't see it in their rules. I think this maybe a server side issue?

It looks like a block on the `/^combine` from a regex pattern.

**Comment by ayumi-cloud** [comment]
Hi, we had exactly the same issue, after spending a couple of hours reversing the stack trace, we discovered it was being caused by one of our plugins. In our case a twig plugin from the marketplace.

Not sure if this will help you out or not, but we had exactly the same issue with the `combine` word at the beginning of the uri's resulting in server code errors instead of returning to a 404 web page.

After fixing their plugin code (which used a vendor file), the problem was fixed.

**Comment by LukeTowers** [comment]
@rejuvenatedigital what plugins are you using?

**Comment by rejuvenatedigital** [comment]
@LukeTowers I had tested this on a blank install of october without any plugins.

**Comment by rejuvenatedigital** [comment]
@mjauvin @LukeTowers The only plugin I have installed is RainLab Pages and the 404 page is set as a Static Page.

**Comment by rejuvenatedigital** [comment]
@mjauvin it works as a CMS page, however I need this to work off the static page version. 

From what I can tell it seems it isn't loading any plugins as it isn't running any code in register or boot methods in the registration files.

**Comment by LukeTowers** [comment]
@rejuvenatedigital I have an idea

**Comment by LukeTowers** [comment]
@rejuvenatedigital thanks for the report and the very helpful comment!

> From what I can tell it seems it isn't loading any plugins as it isn't running any code in register or boot methods in the registration files.

I've fixed it in https://github.com/octobercms/october/commit/2b5d811180f08127b061fa7e6844437cfa90c842, will be available in Build 465+

**Comment by rejuvenatedigital** [comment]
@LukeTowers great thanks luke
