### ISSUE TITLE
Theme:sync --target=database not working

### ISSUE THREAD

**Issue by hackolein** [octobercms/october#4887]
- OctoberCMS Build: 458
- PHP Version: 7.2
- Database Engine: MySQL 5.7.26
- Plugins Installed: 
Indikator.Backend	1.6.11
RainLab.Pages	1.3.2
RainLab.Builder	1.0.26

### Description:
I save the templates in database (databaseTemplates is true in config). This works fine, but when I changed some layout files on filesystem and sync this files to database, this doesn't work as expected.

### Steps To Reproduce:
 For example I use the command:
`artisan theme:sync --target=database --force --paths=layouts/about.htm`

But the changes are not in database, although the message shows `The theme mytheme has been successfully synced from the filesystem to the database.`

I have debug the process and I think the source is not the correct one. When I change some content in database and look at the variable `$content` in [modules/cms/classes/AutoDatasource.php#L156](https://github.com/octobercms/october/blob/882ca6019c9c1b124e6e3f052b6aec02b6fa826b/modules/cms/classes/AutoDatasource.php#L156) , I see the content from database and not from filesystem.

What's going wrong?

**Comment by LukeTowers** [comment]
@bennothommo could you take a look?

**Comment by bennothommo** [comment]
@LukeTowers will do.

**Comment by LukeTowers** [comment]
@hackolein can you test out #5017 and let me know if that fixes the issue for you?

**Comment by hackolein** [comment]
Yes, works as expected. Thank you!
