### ISSUE TITLE
Unable to update plugins/october in backend

### ISSUE THREAD

**Issue by rvolyar** [octobercms/october#489]
Hosting on digital ocean on LAMP.  Getting this error when updating projects through backend. `Update failed "ZipArchive::extractTo(): Permission denied" on line 71 of /var/www/html/vendor/october/rain/src/Filesystem/Zip.php`
I should note that I installed through the cli and attached a project through the backend.

**Comment by qoalu** [comment]
@jbh you wrote 755 in the command and 775 in the text. Is it safe to chmod everything to 775? I am having issue upgrading to the new version of october

**Comment by jbh** [comment]
@qoalu In the previous user's case, they also needed file permissions in order for it to work. In your case, just making sure the correct owner was applied did the trick.

In the end, this has to do with making sure the correct user has the correct permissions. Whether to use 755, 775, etc is up to the user and how secure they would like to be. 755 should be sufficient. Either way, this is off topic as it has to do with Apache permissions and not the plugin source code itself.
