### ISSUE TITLE
Lang files dont work when using a dropdown widget in a hidden primary tab

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4890]
Hard to explain but this seems to be a bug in October, we are using v464

So we created a dropdown widget in the form field and the options are linked to the lang files.

Everything is working fine with the dropdown form widget being displayed in the first tab.

When moving the dropdown widget to a hidden inner tab in the **Primary tab**, the options are now not working with the lang files.

We have tested this on several servers and websites all showing the exact same issue,.

Hopefully admins can confirm this bug.

(fingers crossed)

We are 99.9999999999999999999% sure it's a bug in October.

p.s. Seems to only effecting the dropdown widget and not the other widgets, as far as we can tell.

This bug seems to have appear between versions 460 - 464.

----

Some cut and paste examples, showing what we are seeing:

Example on first tab:

![image](https://user-images.githubusercontent.com/57409060/72568784-d0668280-38b0-11ea-902b-dcbdd45d3bac.png)

Example on second tab:

![image](https://user-images.githubusercontent.com/57409060/72568700-a1501100-38b0-11ea-95bd-d0d4fd85fc72.png)

- Note: Exactly the same code in both picture examples, the only thing we changed was the `tab` yaml line.

**Comment by LukeTowers** [comment]
@ayumi-cloud can you create a PR to the test plugin to replicate the issue?

**Comment by ayumi-cloud** [comment]
ok good idea.

**Comment by ayumi-cloud** [comment]
Closing this, we had a deeper look at the lang file and discovered the following error:

```yaml
        'eyeColor' => [
            'blue'   => 'blue',
            'red'   => 'red',
            'green' => 'green',
            'yellow'  => 'yellow',
        ],
        'something' => [
            'label'    => 'Widgets',
            'comment'  => 'We use widgets to give code examples.',
        ],

        .
        .

        'eyeColor' => [
            'tab' => 'Eyes',
        ],
```

We didn't notice the repeated `eyeColor` field at the bottom of a very long lang file, being repeated.

Our bad.
