### ISSUE TITLE
Chrome 81 has some updated styling features

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4892]
Just to let the admins know and do some A-B testing with October CMS.

Google Chrome 81 have updated many styling features, a few months ago they did a full video on the features, I think this was the video I watched: https://www.youtube.com/watch?v=-oyeaIirVC0

Basically, in October CMS you get a very heavy black line around things when you select objects now.

It's actually a little bit annoying!

See example:

![image](https://user-images.githubusercontent.com/57409060/72667282-066f4800-3a12-11ea-917f-b7861ead09aa.png)

Also another thing is the checkboxes are different in the new chrome but that's actually a nice thing and looks much better in github.

I thought I'd let the admins know and they can decide if they want it to look like this or fix some different cross-browser styling.

Firefox looks like this in Nightly:

![image](https://user-images.githubusercontent.com/57409060/72667302-56e6a580-3a12-11ea-87e0-df3f62ec77c0.png)

As per github issue: https://github.com/octobercms/october/issues/4819

Thought it best to tell you (before people start using Chrome 81 stable).

**Comment by ayumi-cloud** [comment]
p.s. Not going to create a pr until the admins give me feedback. Doing styling pr's is hard because one person says one thing and another person says another thing. So best to wait for a decision to be made first and then I be happy to code the pr.

Note: Google Chrome for many years added a soft blue line around things! Now it's a hard black line (which kind of looks ugly) I would guess it's to make developers a bit more pro-active in addressing accessibility coding issues.

**Comment by ayumi-cloud** [comment]
One idea could be to create a new config file called: `accessibility` and have various options users can select, for example one user may want to turn this feature off, another user may want to style it blue etc. Then the config file could connect to a `dynamic` css file to style the backend, instead of the current setup which is hard-coded.

**Comment by Samuell1** [comment]
@ayumi-cloud I think best will be to remove this it looks ugly and if somebody wants it he is free to overwrite css by his custom backend styles.

**Comment by ayumi-cloud** [comment]
@Samuell1 yah I agree with you. Will wait for confirmation from the admins.

**Comment by LukeTowers** [comment]
Personally I don't mind the dotted line, it does make the default styling more accessible. I'll leave this one up to @daftspunk though.

**Comment by bennothommo** [comment]
My two cents: Dotted-line looks fine to me in the nav, the big black line looks gross 🤢. Whoever thought that would improve accessibility should be [insert awful event here].

**Comment by ayumi-cloud** [comment]
p.s. By the way, I don't have an issue with firefox - it's the chrome black line I hate.

```
:focus {
    outline: none;
}
```

removes it.

**Comment by Samuell1** [comment]
@ayumi-cloud i think it should be removed to be consistent with chrome.

**Comment by LukeTowers** [comment]
Personally I don't think we should remove any accessibility features added by browsers unless we're amping up our own accessibility game in turn to replace them. Just because it "looks bad" isn't a great reason to worsen the experience for someone else with a harder time using the interface.

**Comment by Samuell1** [comment]
@LukeTowers Yeah thats true.
@ayumi-cloud I think it should be added to `:hover` to prevent it appearing on desktops without pressing tab.

**Comment by ayumi-cloud** [comment]
@LukeTowers @Samuell1 

Can we just copy github's code, the old chrome used a soft blue line and the new chrome uses a hard black line.

Ripping github's code example, we get the following solution:

```css
:focus {
    outline: none;
    -webkit-box-shadow: inset 0 1px 2px rgba(27,31,35,.075), 0 0 0 0.2em rgba(3,102,214,.3);
            box-shadow: inset 0 1px 2px rgba(27,31,35,.075), 0 0 0 0.2em rgba(3,102,214,.3);
}
```

Screenshot is here:

![image](https://user-images.githubusercontent.com/57409060/72749313-97305a00-3bb1-11ea-8179-73d5082d0719.png)

**Comment by Samuell1** [comment]
@ayumi-cloud But thats for input elements no? What you getting on chrome for non input elements like links for example?

**Comment by LukeTowers** [comment]
Sure, I don't mind that @ayumi-cloud

**Comment by ayumi-cloud** [comment]
@Samuell1 

> What you getting on chrome for non input elements like links for example?

Nothing - no black border on links.

Let me show you an example:

![image](https://user-images.githubusercontent.com/57409060/72760057-8c84bd80-3bcf-11ea-9ae1-8ba9776aa6b8.png)

@LukeTowers sure I will create a pr for that.

**Comment by LukeTowers** [comment]
Fixed by #4895

**Comment by Samuell1** [comment]
@ayumi-cloud @LukeTowers  Not sure why but in firefox it shows new box-shadow focus and even outline.

![obrázok](https://user-images.githubusercontent.com/3110002/74129556-301a2a00-4be0-11ea-8235-4754dfcf1107.png)

**Comment by bennothommo** [comment]
@Samuell1 I've noticed that too.

**Comment by LukeTowers** [comment]
Sigh. You can never win. Personally I'm fine with that for now, it's not absolutely horrendous in that example.

**Comment by Samuell1** [comment]
@LukeTowers and i forgot to mention on some elements new focus is trigger even on desktop on mouse click
