### ISSUE TITLE
Add the author name to the plugin search list

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4907]
I open this request to cover a few issues, take the following screenshot:

![image](https://user-images.githubusercontent.com/57409060/72993801-e95dbf00-3ded-11ea-9fa3-0dd221924da3.png)

I've created a fake **_second entry_** by the way!

The following issues are:

1. If two plugins with the same name appear, it's hard to know which one to choose, e.g. I want the official RainLab plugin and not a `User` plugin created by someone else.

2. Security, there is nothing to stop me cloning official plugins and trying to spoof them and trying to do a phishing attack, e.g. Copy a RainLab plugin name and upload a plugin with Malware inside it. Then just create a bot to bump up the number of installs.

3. As time goes on more and more plugins get created all doing the exact same thing, e.g. there are several CORS plugins in the marketplace (with the same name).

### Solution

The solution is pretty simple just add a "By Author" tag, for example:

![image](https://user-images.githubusercontent.com/57409060/72994310-ca136180-3dee-11ea-9708-b88444d17824.png)

In the above example, now I know exactly what plugin I'm getting and there is no more guessing going on!

**Comment by mjauvin** [comment]
I agree, this has been bugging me as well.

**Comment by LukeTowers** [comment]
@ayumi-cloud note that all plugin submissions to the marketplace are reviewed by @alekseybobkov, so they'd have to make it past him. But yes, I'd agree that the author name would be a good inclusion here.

**Comment by LukeTowers** [comment]
Implemented in https://github.com/octobercms/october/commit/e8dca35c15a16dd31ef5b21d80375bbd5eec1c94

**Comment by ayumi-cloud** [comment]
Thank you, for quick fix.

No problem, I will message Alxy for `marketplace` related issues from now on.

**Comment by mjauvin** [comment]
@ayumi-cloud note that @alxy and @alekseybobkov are different people...
