### ISSUE TITLE
How to add froala plugin to extend backend richeditor?

### ISSUE THREAD

**Issue by vdomah** [octobercms/october#4910]
Hello, found issue about extending froala in backend. https://github.com/octobercms/october/issues/1743 But that's not enough for my case, as I need to load additional froala plugin char_counter.min.js. But I can't figure out how to do this. Just including plugin source with addJs not helping: it gives error. It seems that the source needs to be compiled, according to froala docs: https://github.com/froala/wysiwyg-editor/blob/master/js/plugins/char_counter.min.js
Is there a way to do that?

**Comment by bennothommo** [comment]
@vdomah How are you adding it to the scripts on the page? Are you able to confirm that the char_counter.min.js file is loaded after the Froala files?

**Comment by vdomah** [comment]
> @vdomah How are you adding it to the scripts on the page? Are you able to confirm that the char_counter.min.js file is loaded after the Froala files?

Yes, I've tried both loading char_counter before and after the froala script. Using addJs it loads the plugin before froala and using this:
````
\Block::append('head', '<script src="assets/js/char_counter.min.js"></script>');
````
it loads after froala.

Both ways I receive error: can't access DEFAULTS of undefined.

The way they load plugins in froala docs is using require: https://github.com/froala/wysiwyg-editor#load-from-cdn-as-an-amd-module

I also found require approach in OctoberCMS backend like here: /modules/backend/widgets/table/assets/js/build.js and it seems somehow related to the command 
````
 php artisan october:util compile assets
````
which I haven't used and don't understand completely how should be used. That's why I'm interested in from start to end instruction on how to add froala plugins. Thanks for helping!

**Comment by bennothommo** [comment]
@vdomah As long as the JS file is loaded after the Froala file, it should work. Just to note - we are not using the latest version of Froala (our current version is 2.9.3), so you would need to use this version of the Character Counter plugin: https://github.com/froala/wysiwyg-editor/blob/v2.9.3/js/plugins/char_counter.min.js. If you load the version 3 plugin, it will likely throw the undefined error you are referring to.
