### ISSUE TITLE
List pagination is reseted to first page if search is filled on refresh

### ISSUE THREAD

**Issue by Samuell1** [octobercms/october#4914]
- OctoberCMS Build: 458
- PHP Version: 7.3
- Database Engine: MySQL

### Description:
List pagination is set to first page if search is already filled and page is refreshed. Looks like its because this line https://github.com/octobercms/october/blob/develop/modules/backend/widgets/Lists.php#L308
Shouldnt this reset pagination only if you search for first time?

### Steps To Reproduce:
Just fill something in search then move to second page and then refresh.

**Comment by bennothommo** [comment]
@Samuell1 this is because the search results might only span a single page. Say you're on page 3 and you only have 1 page of results, would you want to see the (non-existent) 3rd page?

It's easier to just reset the pagination on any filtering in order to ensure that the user always sees results if they are available.

**Comment by Samuell1** [comment]
@bennothommo Yes, but issue is that you search result, then you refresh page and it resets you on first page.

**Comment by LukeTowers** [comment]
@Samuell1 if you could post a gif screencapture of the issue that would help us visualize it.

**Comment by Samuell1** [comment]
Here is short gif, as you can see after refresh of page it resets current page to 1.

![2020-01-28_19-11-46](https://user-images.githubusercontent.com/3110002/73292350-341e7300-4202-11ea-8e99-620dd5c56a04.gif)

**Comment by bennothommo** [comment]
@Samuell1 Does that also happen when no filters or search are applied?

**Comment by Samuell1** [comment]
@bennothommo No, it only happens when search is applied.
