### ISSUE TITLE
Relation controller update form - Parent model data isn't in Request

### ISSUE THREAD

**Issue by danielbidala** [octobercms/october#4925]
I have two models: Order and Orderitems. I add Orderitems to Order with relation manager. When I add new orderitem I get all field's value of parent Order in the Request. 

For example, in my Orderitem model's FilterFields method I can use:
`Request::input('Order.order_type')`

But if I update an orderitem with the relation manager, the parent model (Order) data is not in the Request.

Create Form Request:
![create_request](https://user-images.githubusercontent.com/16636699/73615599-9237c580-4609-11ea-9c4e-d5e513505e1d.png)

Update Form Request:
![update_request](https://user-images.githubusercontent.com/16636699/73615602-a54a9580-4609-11ea-8e9d-011b16a64bd0.png)

What is the reason for this? Can we send the parent data with the request always?

(my October CMS version = 464)

**Comment by LukeTowers** [comment]
Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms

To answer your question however, the parent record information is required to create the related record, but only the record's own identifier is required after it has been created. What are you trying to do with that information? I can guarantee you there's a better way to get access to it then pulling it directly from the request.

**Comment by danielbidala** [comment]
@LukeTowers, yes I know this isn't the best place for questions but on the forum there is not too much activity. (There is tons of unanswered questions)

My use case: I need the parent record's data in the filterfield method of the child form **also when the parent record isn't saved yet**. I have to manipulate the child form based on the parent's data. Thanks for all the help in advance.

**Comment by vortechron** [comment]
@danielbidala if i remember correctly, i was able to access relation data by using _session_key.

something like this:
` $this->formWidget->model->some_relationship()->withDeferred(post('_session_key'))->get()`

**Comment by danielbidala** [comment]
@vortechron thanks for help but i think you can't query the unsaved parent model.

@LukeTowers what if in `modules\backend\behaviors\relationcontroller\assets\js\october.relation.js`
we add somthing like:

```
        function serializeParentForm(form) {
            var parentFormData = [];
            $.each($(form).serializeArray(), function() {
                if(this.name != '_session_key' && this.name != '_token') {
                        parentFormData[this.name] = this.value;
                }
            });
            return parentFormData;
        }
```
and than extend `clickViewListRecord` function in same file:

```
        this.clickViewListRecord = function(recordId, relationId, sessionKey) {

            var newPopup = $('<a />'),
                $container = $('#'+relationId),
                requestData = paramToObj('data-request-data', $container.data('request-data')),
                /*ADDED*/ 
                requestParentFormData = serializeParentForm('form.layout')
                /*END ADDED*/

            newPopup.popup({
                handler: 'onRelationClickViewList',
                size: 'huge',
                extraData: $.extend({}, requestData, /*ADDED*/ requestParentFormData,/*END ADDED*/ {
                    'manage_id': recordId,
                    '_session_key': sessionKey
                })
            })
        }
```

**Comment by LukeTowers** [comment]
@danielbidala 

> you can't query the unsaved parent model

That's your issue then, not that you can't access parent record data period. I'm not sure what the best solution would be. You could submit your proposed code changes in a PR for us to review

**Comment by danielbidala** [comment]
@LukeTowers 
>  I'm not sure what the best solution would be.

As I see the best solution is using the Request to transmit the unsaved parent model's data to the child form. (also we could use Session but it's not straightforward) This way at controller level we can get the Request if we need and use it in relationExtendManageWidget method to manipulate the child form.

The above `modules\backend\behaviors\relationcontroller\assets\js\october.relation.js` modification works for me. (need some fine tuning)

Someone has another idea?

**Comment by LukeTowers** [comment]
@danielbidala something somewhat similar is being worked on in #5136, feel free to add your thoughts there.
