### ISSUE TITLE
Add model relationship retrieval method to HasRelationships

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#4930]
October's HasRelationships trait currently loops through its relationTypes arrays directly when retrieving a relation type. Here's an example:
https://github.com/octobercms/library/blob/d00a3fb7b956bcf5d3eaa1d7e8591a99ae18ef84/src/Database/Concerns/HasRelationships.php#L173-L176
but I'd like to have relationships defined in there based on data in the model. I'd like relation information to be retrieved through a new method rather than directly from the arrays.

## Use Case

I'd like relations dynamically placed onto my model instance based on data loaded into it.

Say you have a two-way polymorphic relation. WordPress is a great example of where something like this exists. You have Posts (of type _post, page, product_ etc) in a many to many polymorphic relationship with taxonomies (_category, tag_ etc).

Normally you'd extend your Post model to add the polymorphic relation like so:
```php
Post::extend(function (\Model $model) {
    $model->hasMany['taxonomy_category'] = [
        'My\Plugin\Models\TaxonomyTerm',
        'name' => 'taxonomable',
        'table' => 'my_plugin_taxonomables'
    ];
});
```

However this would add categories to every post type. I only want it to be added to the 'product' post type.

I propose adding two methods:
```php
public function getRelationTypeDefinitions($type)
{
    if (in_array($type, static::relationTypes)) {
        return $this->{$type};
    }

    return [];
}

public function getRelationTypeDefinition($type, $name)
{
    $definitions = $this->getRelationTypeDefinitions($type);

    if (isset($definitions[$type])) {
        return $definitions[$type];
    }

    return null;
}
```

So for example instead of the following in your code
```php
if (isset($this->{$type}[$name])) {
```
you'd call
```php
$definition = $this->getRelationTypeDefinition($type, $name);
if ($definition) {
```

These functions would then be overrideable in a plugin model like so:
```php
public function getRelationTypeDefinitions($type)
{
    if ($this->post_type == 'product') {
        return ['my_custom_definitions'];
    }

    return parent::getRelationTypeDefinitions($type);
}
```

If this is acceptable I can submit a PR. This change would be entirely backwards compatible with no breaking changes.

**Comment by mjauvin** [comment]
Why not dynamically add those methods in the base model when you need this?

**Comment by Flynsarmy** [comment]
Because the other HasRelations methods wouldn't be using them. That's the point. See my PR.

**Comment by mjauvin** [comment]
right I see that now.

--
Marc

**Comment by Flynsarmy** [comment]
Up. PR still open

**Comment by LukeTowers** [comment]
@Flynsarmy bot's just acting up
