### ISSUE TITLE
Auth validate not support localization

### ISSUE THREAD

**Issue by prhost** [octobercms/october#4932]
Hi everyone,

Is there any reason why this part of October is not implementing the localization system?
Could I implement and send a PR?

https://github.com/octobercms/library/blob/master/src/Auth/Manager.php

**Comment by daftspunk** [comment]
The messages don't matter too much because, with debug mode disabled (production mode), these messages are never shown to anyone.

**Comment by LukeTowers** [comment]
@prhost we've had this discussion a few times before in the GitHub issues, take a look at https://github.com/octobercms/october/issues/2106#issuecomment-471387405 for the most recent decision on it.
