### ISSUE TITLE
Add an unique identifier for tabs

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4941]
## Problem explained

We have some form widgets being loaded inside some tabs. To increase performance, these new widgets are not loaded when the web page is loaded. Instead these new widgets get loaded when a user clicks on the tab where the widget is located and then gets loaded.

Below is a code example been ripped out of October's DOM:

```html
<div id="Form-primaryTabs" class="control-tabs primary-tabs layout scroll-after has-tabs" data-control="tab">
    <div class="layout-row min-size">
        <ul class="nav nav-tabs" data-disposable="">
            <li class=""> <a href="#primarytab-1" data-target="#tabs14932-tab-01581624569108" data-toggle="tab" title="Tab One"> <span class="title"> <span> Tab One </span> </span> </a> <span class="tab-close"><i>×</i></span></li>
            <li class="active"> <a href="#primarytab-2" data-target="#tabs14932-tab-11581624569110" data-toggle="tab" title="Tab Two"> <span class="title"> <span> Tab Two </span> </span> </a> <span class="tab-close"><i>×</i></span></li>
            <li class=" "> <a href="#primarytab-3" data-target="#tabs14932-tab-21581624569111" data-toggle="tab" title="Tab Three"> <span class="title"> <span> Tab Three </span> </span> </a> <span class="tab-close"><i>×</i></span></li>
        </ul>
    </div>
</div>
```

The important code line is as follows:

```html
<a href="#primarytab-1" data-target="#tabs14932-tab-01581624569108" data-toggle="tab" title="Tab One"> <span class="title"> <span> Tab One </span> </span> </a>
```

When we refresh the same web page we get the following code:

```html
<a href="#primarytab-1" data-target="#tabs14932-tab-71581624569117" data-toggle="tab" title="Tab One"> <span class="title"> <span> Tab One </span> </span> </a>
```

The `data-target` changes everytime the web page is loaded, therefore can't be used as an unique identifier.

### Solution

To end up with a cleaner code, we suggest adding an unique identifier for the tabs.

For example, something like this:

```html
<li id="unique-identifier">
    <a href="#primarytab-1" data-target="#tabs14932-tab-0158146536546108" data-toggle="tab" title="Tab One"> <span class="title"> <span> Tab One </span> </span> </a>
</li>
```

In the above code we added an `id` attribute, to the `li` element, which is acting as a container for the anchor links.

### Discussion

Admins to `accept` or `reject` idea. Also best method to generate the unique identifier for the tabs.

[edit] Also to decide whether to add the unique identifier to the `<li>` or `<a>` element.

**Comment by bennothommo** [comment]
@ayumi-cloud Can't you just use the `href` attribute as the selector for CSS/JS?

**Comment by ayumi-cloud** [comment]
@bennothommo 

I think that won't work, I just tested your suggestion out.

On this page: https://octobercms.com/docs/ui/tab

![image](https://user-images.githubusercontent.com/57409060/74548272-70add680-4f45-11ea-8d75-03e248b24893.png)

They are both using the exact same `href` so there's nothing to safe guard using two or more tabs on the same page to create an unique identifier using `href`.

**Comment by LukeTowers** [comment]
@ayumi-cloud try replicating that example inside of a form widget, I don't believe you can.

**Comment by ayumi-cloud** [comment]
@bennothommo @LukeTowers 

Yah I think you're right, I had a long think about possible combinations in my head and think it would be impossible to get an issue. As you can't create the same yaml class name in a single file and multi-level containers with tabs inside them, you could get an unique identifier by also connecting it to the container.

Sorry to waste both your time! Feel free to close this issue - will use bennothommo's `href` method.
