### ISSUE TITLE
Inconsistent and bugged component dropdown behavior

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#4947]
- OctoberCMS Build: ### 464
- PHP Version: 7.4.2

### Description:
A component has two dropdown properties: *foo* and *bar* with *bar* depending on *foo*.

* If *foo* retrieves its options through a `get*Options` method, the dropdown will appear blank by default when opening the component (See *Options Method* component below).
* If *foo* sets its options within the `defineProperties` property array using the `options` key, the dropdown will have its first option populated by default (See *Options Array* component below).
* If *foo* sets its options within the `defineProperties` property array using the `options` key, the *bar* dropdown will fail to populate even though an option is selected in *foo*.
  * If you change *foo* option then change it back, *bar* will populate correctly
  * If you close and re-open the component, *bar* will populate correctly
  * If *foo* only has 1 option and *bar* is set to `required`, there is no way to close and re-open the component and your only option is to reload the page (See *Single Options Method* component below).

### Steps To Reproduce:
* `git clone https://github.com/Flynsarmy/oc-badcompdep-plugin.git` to */plugins/flynsarmy/badcompdep*
* `php artisan plugin:refresh Flynsarmy.Badcompdep`
* Open any page in Backend - CMS
* Add this plugins *Options Method* and *Options Array* and *Single Option Method* components to the page and witness the inconsistent (and in the case of *Single Options Method* broken) behavior.

**Comment by LukeTowers** [comment]
@Flynsarmy is this still an issue?

**Comment by Flynsarmy** [comment]
Still broken on latest dev build.

**Comment by LukeTowers** [comment]
What are your thoughts on this @daftspunk? Is this intentional or should we push a fix to make the behaviour consistent?

**Comment by bennothommo** [comment]
@Flynsarmy I've just done a test using your instructions and I'm seeing something slightly different:

- Scenario 1 (Options Method) shows me the first option `foo` selected on load, however it does not populate options for the `post` field. If I specify `foo` as `default` for the `category` field, the `post` field is populated.
- Scenario 2 (Options Array) shows me no option selected for `category` on load, and the `post` field is not populated. If I specify `foo` as `default` for the `category` field, again, the `post` field is populated.
- Scenario 3 (Single Option Method) is showing me what you have suggested. Again, if I specify `foo` as `default`, the `post` field is populated.

I think the best course of action to make this all consistent is to make the Inspector dropdown fields follow the behaviour of the normal backend dropdown fields, namely:

- Introduce an `emptyOption` parameter to provide text if no default or previous value is provided.
- If `emptyOption` does not exist and `default` is specified, pre-select the default option.
- If `emptyOption` does not exist and `default` is not specified, pre-select the first option available.
- Ensure that the `depends` fields are triggered after this has all taken place.

**Comment by bennothommo** [comment]
@LukeTowers any thoughts on the above?

**Comment by bennothommo** [comment]
I've just realised there is a `placeholder` parameter for the Inspector fields, which the dropdown uses. I wonder if this should either be renamed to `emptyOption`, or allow both terms to be used (with `placeholder` given priority to maintain backwards compatibility).

**Comment by LukeTowers** [comment]
@bennothommo both terms should be supported

**Comment by LukeTowers** [comment]
@Flynsarmy can you test #5071 and verify that it fixes your issue?
