### ISSUE TITLE
RelationController Bug

### ISSUE THREAD

**Issue by moxetiale** [octobercms/october#4951]
Hello. I have 3 models : Product, Attribute and Option. Product hasMany Attribute and Options. Also Attribute hasMany Option.  Im using backend RelationController and creating Attribute and Options inside Product form 

![image](https://user-images.githubusercontent.com/17551744/74913402-fd3f1580-53d9-11ea-9653-4a00f0e8a253.png)

I want to create Attribute options inside Product form but when i click attribute inside product form got error 

![image](https://user-images.githubusercontent.com/17551744/74913504-38d9df80-53da-11ea-8f55-b96f2ed237c0.png)

**Comment by LarBearrr** [comment]
@moxetiale Can you post your `config_relation.yaml` for your `Product` model?

**Comment by moxetiale** [comment]
@LarBearrr 
![image](https://user-images.githubusercontent.com/17551744/75135244-61274e00-56fa-11ea-9fe9-49635cd64c50.png)
