### ISSUE TITLE
Relation conditions aren't being applied when saving models

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#4952]
- OctoberCMS Build: 464
- PHP Version: 7.4.2

### Description:
If you have two belongsToMany relations on the same table with a `conditions` 
value set, record retrieval (`$record->myRelation`) works correctly and applies 
the specified conditions, however saving `$record` wiil result in the first 
relation being wiped and only the second relation will save.

`newPivotQuery()` isn't applying constraints as it should.

### Steps To Reproduce:
* `git clone https://github.com/Flynsarmy/oc-relationtest-plugin.git` to */plugins/flynsarmy/relationtest*
* `php artisan plugin:refresh Flynsarmy.RelationTest`
* Go to */backend/flynsarmy/relationtest/posts/update/1*
* Notice we have two categories in our *category* relation and two tags in our *tags* relation. Both relations connect to the same table but use a `conditions` option in our model.
* Hit Save
* Refresh
* *Categories* has been wiped but *Tags* saved.

### Issue in Depth

In our `Post` model we have two relations defined:
```php
    public $belongsToMany = [
        'tags' => [
            'Flynsarmy\RelationTest\Models\Term',
            'table' => 'flynsarmy_relationtest_posts_terms',
            'key'        => 'post_id',
            'otherKey'   => 'term_id',
            'conditions' => 'type = "tag"'
        ],
        'categories' => [
            'Flynsarmy\RelationTest\Models\Term',
            'table' => 'flynsarmy_relationtest_posts_terms',
            'key'        => 'post_id',
            'otherKey'   => 'term_id',
            'conditions' => 'type = "category"'
        ],
    ];
```
These link to the same table but retrieval and display on our form works as 
expected thanks to our `conditions` statement. This can be further be confirmed 
with
```bash
php artisan tinker
Flynsarmy\RelationTest\Models\Post::first()->tags
Flynsarmy\RelationTest\Models\Post::first()->categories
```

When saving the model, `October\Rain\Database\Relations\BelongsToMany::setSimpleValue()` 
calls `$this->sync($value);`.
The `sync` method defined in */vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php*
has the lines
```php
    $current = $this->newPivotQuery()->pluck(
        $this->relatedPivotKey
    )->all();
```
to determine which records need to be saved for the current relation. The problem is
`newPivotQuery()` doesn't apply our `conditions`, so the query 
```sql
select * from `flynsarmy_relationtest_posts_terms` where `post_id` = ?
```
is executed and ALL records in this table are returned instead of just the ones
relevent to the current relation.
The next lines in this class:
```php
$detach = array_diff($current, array_keys(
    $records = $this->formatRecordsList($this->parseIds($ids))
));
```
detect which records weren't selected on our form and lists them for removal.

Because our form has the *Categories* field first, it marks the tag records for removal.
Removal occurs, and we move on to the *Tags* field. The same thing happens and our
categories are marked for removal.

The end result is only the tags are saved and all categories are removed.

**Comment by Flynsarmy** [comment]
Ping

**Comment by Flynsarmy** [comment]
Ping

**Comment by Flynsarmy** [comment]
Ping

**Comment by mjauvin** [comment]
@Flynsarmy I was able to reproduce this using your relationtest plugin.

Two questions:

1. did you try the same with a scope instead of a condition ([see here](https://octobercms.com/docs/database/relations#detailed-relationships))?
2. should you not use [polymorphic relations](https://octobercms.com/docs/database/relations#polymorphic-relations) to achive this?

_Note: I'm not saying this is not a bug, just exploring alternate options in the mean time._

**Comment by mjauvin** [comment]
Update: I tried using scopes as following (same behavior as with conditions):
```
    public $belongsToMany = [
        'tags' => [
            'Flynsarmy\RelationTest\Models\Term',
            'table' => 'flynsarmy_relationtest_posts_terms',
            'key'        => 'post_id',
            'otherKey'   => 'term_id',
            'scope' => 'isType'
        ],
        'categories' => [
            'Flynsarmy\RelationTest\Models\Term',
            'table' => 'flynsarmy_relationtest_posts_terms',
            'key'        => 'post_id',
            'otherKey'   => 'term_id',
            'scope' => 'isCategory'
        ],
    ];
```
And adding the scopes to the Term class:
```
public function scopeIsCategory($query)
{
   $query->where('type', 'category');
}

public function scopeIsTag($query)
{
   $query->where('type', 'tag');
}
```

**Comment by mjauvin** [comment]
related: https://stackoverflow.com/questions/34788435/laravel-5-conditional-many-to-many-sync

**Comment by mjauvin** [comment]
@LukeTowers I confirm this IS a bug, please update the ~~status~~ type.

Thanks.
