### ISSUE TITLE
Promote October CMS and give the community a useful tool by adding the CMS to the Lighthouse tool

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4959]
@daftspunk @LukeTowers 

Been thinking about this for a while and I contacted Google a few weeks ago. Today they sent me an update saying we can go ahead now.

What I'm talking about is called "Stack Packs" - you can learn more here: https://developers.google.com/web/updates/2019/01/lighthouse-platform-packs

Creating and adding a Lighthouse Stack pack gives the following two advantages:

1. Gives the October community an extra free tool to test their October websites.

2. Spreads the word about the October CMS and people will see this CMS listed with the big boys and will then investigate further.

### What does a stack pack look like?

![image](https://user-images.githubusercontent.com/57409060/75545595-a9a67a80-5a1e-11ea-8cf8-56328ed30f45.png)

# How to Contribute

We'd love to accept your contributions to this project to improve how we provide stack-specific guidance in Lighthouse. Please read through the following before contributing however.

## Contributor License Agreement

Contributions to this project must be accompanied by a Contributor License
Agreement. You (or your employer) retain the copyright to your contribution;
this simply gives us permission to use and redistribute your contributions as
part of the project. Head over to <https://cla.developers.google.com/> to see
your current agreements on file or to sign a new one.

You generally only need to submit a CLA once, so if you've already submitted one
(even if it was for a different project), you probably don't need to do it
again.

## Submitting a new stack pack

Want to submit a brand new stack pack? Awesome! In order for a stack pack to be considered however, the following must be met:

* There should be a simple way to detect the stack via JS/DOM properties
* At least 6 of the performance audits should have stack-specific recommendations
* A significant number of websites (~ in the 10's of thousands) should be using the stack. Consider using [HTTP Archive](https://discuss.httparchive.org/t/javascript-library-detection/955/2) to detect the number sites used by the particular tool.
* There must be a minimum of two maintainers for each stack from the community who can help review and provide suggestions. We (Google) should not be the ones to decide what the audit recommendations should be.

If all of these are met, submit a PR for review! Copy the `general.json` file into the `packs/` directory and change each audit string to a specific recommendation regarding your stack. If you can't provide a recommendation for a particular audit, change it to an empty string. However, you will need to provide at least 6 audit strings as mentioned earlier.

## Submitting changes to audit strings

Do you notice a specific audit string for a particular pack that is wrong or could be a little better? Please submit a PR! 

### Stack Pack Release Cycle

To ensure that all audit suggestions for stack packs are properly localized in time, there will be a cut-off at least twice a year (in Q2 and Q4) where all changes to audit descriptions for any stack will be sent to the Google translation teams. This means that there will be at least 2 stack pack releases every year.

### When will more than just performance audits be supported?

Stack pack suggestions for audits will need to stay in-line with [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/). Performance audits are the only types of audits surfaced there which means they will be the only audits supported by stack packs in the near future.

### Handling different versions of stacks

For most stacks, audit advice will be provided for the latest stable version. If developers are using an older version where they cannot include a particular suggestion that we provide, they will have to upgrade. We do **not** currently support providing different types of suggestions for multiple versions of the same tool in a single stack pack, but we may include this functionality in the future.

**For example:** We tell developers to use React’s [Suspense](https://reactjs.org/docs/code-splitting.html#reactlazy) feature in the React stack pack to code-split their bundles. This feature is only supported in version 16.6 but the developer is using an older version of React. By providing links to all relevant documentation, they should understand that they would have to upgrade their version.

#### What if two versions of a tool are completely different where suggestions for one might not work for another?

These two different versions will be treated as two separate stacks entirely for the meantime, each with their own feature detection (for example: Stack v2 and stack v3)

**Comment by ayumi-cloud** [comment]
# How to Contribute

We'd love to accept your contributions to this project to improve how we provide stack-specific guidance in Lighthouse. Please read through the following before contributing however.

## Contributor License Agreement

Contributions to this project must be accompanied by a Contributor License
Agreement. You (or your employer) retain the copyright to your contribution;
this simply gives us permission to use and redistribute your contributions as
part of the project. Head over to <https://cla.developers.google.com/> to see
your current agreements on file or to sign a new one.

You generally only need to submit a CLA once, so if you've already submitted one
(even if it was for a different project), you probably don't need to do it
again.

## Submitting a new stack pack

Want to submit a brand new stack pack? Awesome! In order for a stack pack to be considered however, the following must be met:

* There should be a simple way to detect the stack via JS/DOM properties
* At least 6 of the performance audits should have stack-specific recommendations
* A significant number of websites (~ in the 10's of thousands) should be using the stack. Consider using [HTTP Archive](https://discuss.httparchive.org/t/javascript-library-detection/955/2) to detect the number sites used by the particular tool.
* There must be a minimum of two maintainers for each stack from the community who can help review and provide suggestions. We (Google) should not be the ones to decide what the audit recommendations should be.

If all of these are met, submit a PR for review! Copy the `general.json` file into the `packs/` directory and change each audit string to a specific recommendation regarding your stack. If you can't provide a recommendation for a particular audit, change it to an empty string. However, you will need to provide at least 6 audit strings as mentioned earlier.

## Submitting changes to audit strings

Do you notice a specific audit string for a particular pack that is wrong or could be a little better? Please submit a PR! 

## FAQ

### Stack Pack Release Cycle

To ensure that all audit suggestions for stack packs are properly localized in time, there will be a cut-off at least twice a year (in Q2 and Q4) where all changes to audit descriptions for any stack will be sent to the Google translation teams. This means that there will be at least 2 stack pack releases every year.

### When will more than just performance audits be supported?

Stack pack suggestions for audits will need to stay in-line with [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/). Performance audits are the only types of audits surfaced there which means they will be the only audits supported by stack packs in the near future.

### Handling different versions of stacks

For most stacks, audit advice will be provided for the latest stable version. If developers are using an older version where they cannot include a particular suggestion that we provide, they will have to upgrade. We do **not** currently support providing different types of suggestions for multiple versions of the same tool in a single stack pack, but we may include this functionality in the future.

**For example:** We tell developers to use React’s [Suspense](https://reactjs.org/docs/code-splitting.html#reactlazy) feature in the React stack pack to code-split their bundles. This feature is only supported in version 16.6 but the developer is using an older version of React. By providing links to all relevant documentation, they should understand that they would have to upgrade their version.

#### What if two versions of a tool are completely different where suggestions for one might not work for another?

These two different versions will be treated as two separate stacks entirely for the meantime, each with their own feature detection (for example: Stack v2 and stack v3)

**Comment by LukeTowers** [comment]
@ayumi-cloud since you seem to work with Google a fair amount and probably already have a CLA with them, would you be willing to put together the code for it and post it here for our review and then submit the PR yourself?

**Comment by ayumi-cloud** [comment]
@LukeTowers I don't mind doing that for you - I will it it to my to-do list.

I was thinking of creating a spreadsheet with the various messages and sending it to you in Slack for review. If you happy with that I will start trying to do the research in the coming days (when I'm free) and try to find plugins and libraries (**_that are properly maintained_** to link into the descriptions).

**Comment by LukeTowers** [comment]
@ayumi-cloud thanks!

Probably no need for a spreadsheet, just the JSON in a comment on this issue should be good enough.

**Comment by lautsevich** [comment]
Such a cool idea! Is there any news?

**Comment by LukeTowers** [comment]
Haven't heard from @ayumi-cloud for a while, not sure what's up with them.

**Comment by lautsevich** [comment]
Ouch. Hope he's (she?) safe and well these challenging days!

**Comment by bennothommo** [comment]
I wouldn't mind giving this a try in the future, but it's extremely low priority at the moment.

**Comment by RomainMazB** [comment]
Again, just my thoughts about that (a thing I may not understand perfectly):
It's a great feature, even if it's just a customization since theses message will already be shown when using lighthouse with PageSpeed insight.

Watching at some of the WP error message/link in it's stack pack (which is not exhaustive I suppose), what shouldn't be reproduce is the kind of the one for AMP: it definitely promote a specific plugin. Even if the plugin is great and probably the best one, October shouldn't promote any plugin by any possible way.

That said, this feature is a good one.

**Comment by ayumi-cloud** [comment]
Sorry been sick for a while (still taking medicines). Hospitals and doctors seem to only treat covid-19 and ignore all other illnesses! Which has only made things worse!

I got a back log of work to start doing this month and this issue would be low priority on my list. 

Also there has been some changes at Google camp with this area of development such as the core vitals see here:

![image](https://user-images.githubusercontent.com/57409060/83630169-484cf500-a593-11ea-9144-a194619aac6e.png)

Three exciting API's I want to add to this issue and talk with Google are:

- Largest Contentful Paint (LCP) <-- How long it takes the page to render the critical content.
- Cumulative Layout Shift (CLS) <-- Does the page move around when rendering.
- Total Blocking Time (TBT) <-- Server side rendering.

I not forget this issue - it's just push down my to do list.

**Comment by ayumi-cloud** [comment]
I forgot to also add a couple of things:

1. I don't really want to link to people's plugins in the descriptions if they are not maintained or have coding/security issues etc. It puts people's websites at risk who would reply on trusting this tool.

2. Another issues is with some core features, a perfect example is Luke's issue here: https://github.com/octobercms/october/issues/5059 I don't want to link or suggest to some image plugins - when they are going to be redundant and added to a core feature.

**Comment by lautsevich** [comment]
@ayumi-cloud, welcome back!

I believe it would be great not to suggest a specific plugin but saved search results in the marketplace "image optomization" etc.

**Comment by ayumi-cloud** [comment]
Hi @lautsevich yah that's a good idea.

I was just thinking ahead and maybe in the future people would ask for their plugin(s) to be added to the descriptions. Then I would think **the admins need to set some sort of criteria to only allow good plugins to be added**. 

I'm trying to avoid something like this:

1. I add Plugin X.
2. Later people add reviews saying it's bad or pointless (or);
3. The plugin is found to contain a XSS issue.
4. We then can't reach the plugin author to get a quick fix or update.
5. We are still linking to that plugin and putting people's websites at risk!

(I write down what I was thinking - just as notes for anyone reading this issue in the future) 

....

**Comment by LukeTowers** [comment]
@ayumi-cloud I would say only first party plugins should be specifically recommended (i.e. RainLab plugins), everything else should be a marketplace search term recommendation.

**Comment by RomainMazB** [comment]
There's where I wanted to come, of course.

Promote third party plugins is not fair for the others concurrent plugins, and in some sort engages the cms responsibility if there is major issue in the plugin.

The next time I will make it shorter to not beat around the bush :+1:

**Comment by bennothommo** [comment]
@ayumi-cloud 

> Sorry been sick for a while (still taking medicines). Hospitals and doctors seem to only treat covid-19 and ignore all other illnesses! Which has only made things worse!

Sorry to hear about your troubles. All the best for a speedy recovery.

**Comment by ayumi-cloud** [comment]
@bennothommo thanks for your kind words, wish you all the best.

**Comment by ayumi-cloud** [comment]
To make our Lighthouse pack more useful to developers - I plan to link to external useful developer tools, as October's marketplace plugins do not cover everything developers need to build websites.

I can give an example of this, Responsive Image Breakpoints Generator Tool can be found here: https://www.responsivebreakpoints.com/

The tool makes it easy to work out the break points for responsive images. A useful tool when flagging a responsive image issue / suggestion.

---

> If anyone wants to suggest a good developer tool or October plugin that will be useful in the list - please message in this issue and I will add it into the spreadsheet.

I strongly feel a combination of useful third party developer tools and October plugins is the way to go! 

The October community is a professional developer based community - whereas the Wordpress community is a marketing community saying "You can built this in a few minutes and do everything with our plugins and don't need to write any code at all" ... yah right 😆

Therefore, I want to actually make this pack useful to developers and add tools and plugins that will enhance their work load and website creation.

**Comment by ayumi-cloud** [comment]
```
        {id: 'first-contentful-paint', weight: 15, group: 'metrics'},
        {id: 'speed-index', weight: 15, group: 'metrics'},
        {id: 'largest-contentful-paint', weight: 25, group: 'metrics'},
        {id: 'interactive', weight: 15, group: 'metrics'},
        {id: 'total-blocking-time', weight: 25, group: 'metrics'},
        {id: 'cumulative-layout-shift', weight: 5, group: 'metrics'},
        // intentionally left out of metrics group so they won't be displayed
        {id: 'first-cpu-idle', weight: 0},
        {id: 'max-potential-fid', weight: 0},
        {id: 'first-meaningful-paint', weight: 0},
        {id: 'estimated-input-latency', weight: 0},

        {id: 'render-blocking-resources', weight: 0, group: 'load-opportunities'},
        {id: 'uses-responsive-images', weight: 0, group: 'load-opportunities'},
        {id: 'offscreen-images', weight: 0, group: 'load-opportunities'},
        {id: 'unminified-css', weight: 0, group: 'load-opportunities'},
        {id: 'unminified-javascript', weight: 0, group: 'load-opportunities'},
        {id: 'unused-css-rules', weight: 0, group: 'load-opportunities'},
        {id: 'unused-javascript', weight: 0, group: 'load-opportunities'},
        {id: 'uses-optimized-images', weight: 0, group: 'load-opportunities'},
        {id: 'uses-webp-images', weight: 0, group: 'load-opportunities'},
        {id: 'uses-text-compression', weight: 0, group: 'load-opportunities'},
        {id: 'uses-rel-preconnect', weight: 0, group: 'load-opportunities'},
        {id: 'server-response-time', weight: 0, group: 'load-opportunities'},
        {id: 'redirects', weight: 0, group: 'load-opportunities'},
        {id: 'uses-rel-preload', weight: 0, group: 'load-opportunities'},
        {id: 'efficient-animated-content', weight: 0, group: 'load-opportunities'},
        {id: 'total-byte-weight', weight: 0, group: 'diagnostics'},
        {id: 'uses-long-cache-ttl', weight: 0, group: 'diagnostics'},
        {id: 'dom-size', weight: 0, group: 'diagnostics'},
        {id: 'critical-request-chains', weight: 0, group: 'diagnostics'},
        {id: 'user-timings', weight: 0, group: 'diagnostics'},
        {id: 'bootup-time', weight: 0, group: 'diagnostics'},
        {id: 'mainthread-work-breakdown', weight: 0, group: 'diagnostics'},
        {id: 'font-display', weight: 0, group: 'diagnostics'},
        {id: 'performance-budget', weight: 0, group: 'budgets'},
        {id: 'timing-budget', weight: 0, group: 'budgets'},
        {id: 'resource-summary', weight: 0, group: 'diagnostics'},
        {id: 'third-party-summary', weight: 0, group: 'diagnostics'},
        {id: 'largest-contentful-paint-element', weight: 0, group: 'diagnostics'},
        {id: 'layout-shift-elements', weight: 0, group: 'diagnostics'},
        {id: 'uses-http2', weight: 0, group: 'diagnostics'},
        {id: 'uses-passive-event-listeners', weight: 0, group: 'diagnostics'},
        {id: 'no-document-write', weight: 0, group: 'diagnostics'},
        {id: 'long-tasks', weight: 0, group: 'diagnostics'},
```

**Comment by ayumi-cloud** [comment]
@LukeTowers @bennothommo 

Please review: https://github.com/ayumi-cloud/oc_stack_pack/blob/main/october.js

**Comment by ayumi-cloud** [comment]
Submitted here: https://github.com/GoogleChrome/lighthouse-stack-packs/pull/56

**Comment by summercms** [comment]
Submitted here: 

Stack pack pr: https://github.com/GoogleChrome/lighthouse-stack-packs/pull/58

Detection pr: https://github.com/johnmichel/Library-Detector-for-Chrome/pull/187

**Comment by ayumi-cloud** [comment]
Talking to a Googler, need to add detection in their other repo, file found here:
https://github.com/johnmichel/Library-Detector-for-Chrome/blob/master/library/libraries.js

From looking at programs on the internet they use the following things:

Popular software programs detect October using various methods such as:

Meta-tag (generator): "OctoberCMS"
Cookie Name: "october_session"
Javascript Framework Detection:

/modules/system/assets/css/framework.extras-min.css
/modules/system/assets/js/framework.combined-min.js
/modules/system/assets/css/framework.extras-min.css
/modules/system/assets/js/framework.combined-min.js
Finding one of these files.

etc.

~Any suggestions would be great.

**Comment by ayumi-cloud** [comment]
Talking to a Googler, need to add detection in their other repo, file found here:

https://github.com/johnmichel/Library-Detector-for-Chrome/blob/master/library/libraries.js

Jumped into the deep end and gave it a go, my pr is here:

https://github.com/johnmichel/Library-Detector-for-Chrome/pull/187

**Comment by ayumi-cloud** [comment]
Been talking to a Googler, need to add detection in their other repo, file found here:

https://github.com/johnmichel/Library-Detector-for-Chrome/blob/master/library/libraries.js

Jumped into the deep end and gave it a go, my pr is here:

https://github.com/johnmichel/Library-Detector-for-Chrome/pull/187

**Comment by summercms** [comment]
Both pr's have been merged, Google side!

> **This will be live on the next Lighthouse Update!**

@LukeTowers Please close this issue now.

**Comment by SebastiaanKloos** [comment]
Awesome!

**Comment by lautsevich** [comment]
Great! Thx, @ayumi-cloud!

**Comment by seanthepottingshed** [comment]
@ayumi-cloud 

Champion the wonderhorse!

* https://www.youtube.com/watch?v=qsQwBNMFWfI

**Comment by ayumi-cloud** [comment]
Google asked me to add some extra info in the doc's on a few points, pr created here: 
https://github.com/octobercms/docs/pull/501
