### ISSUE TITLE
Cannot install a theme through the command line when cms.databaseTemplates is enabled

### ISSUE THREAD

**Issue by laurentbardin** [octobercms/october#4962]
- OctoberCMS Build: 1.0.464 (also tested on the `develop` branch currently at aff120fcec390309e93eae8f195f253623a5ea12)
- PHP Version: `PHP 7.2.26 (cli) (built: Dec 21 2019 23:33:26) ( NTS )`
- Database Engine: MySQL
- Plugins Installed: October.Demo

### Description:
Installing a theme through the command line fails when the `databaseTemplates` setting is set to `true`.

### Steps To Reproduce:
1. Install October CMS
2. Set the `databaseTemplates` option to `true` in `config/cms.php`
3. Install a free theme from the marketplace (I used Mehedi.MegaKit) with `php artisan theme:install Mehedi.MegaKit`. You should get the following error message: `RecursiveDirectoryIterator::__construct(/path/to/october/themes/Mehedi.megakit): failed to open dir: No such file or directory`
4. Trying to install the theme in a custom directory produces the same message in a slightly different context:
```shell
$ php artisan theme:install Mehedi.MegaKit megakit

In FileDatasource.php line 367:
                                                                                                                                     
  RecursiveDirectoryIterator::__construct(/path/to/october/themes/megakit): failed to open dir: No such file or directory
```
5. Setting the `cms.databaseTemplates` back to `false` allows the theme to be installed (though without its dependencies, as per #4728)
6. Despite what the error message is saying, creating the destination directory beforehand does not circumvent the issue, but produces the `A theme named megakit already exists.` error message.

### Discussion
Installing a theme via the backend interface while `cms.databaseTemplates` is set to `true` works fine, so I believe this should be the case when using the command line as well. This can be worked around during development by toggling the feature as needed, but the system should be working in the same manner no matter the method used.

Thanks.

**Comment by bennothommo** [comment]
Fixed by https://github.com/octobercms/library/commit/e616ff50d7fe58644de32c356f6a022303bd9b7b.
