### ISSUE TITLE
Package files from server are corrupt

### ISSUE THREAD

**Issue by inaRQuokka** [octobercms/october#4963]
I just installed October, and got this problem. Can anyone help me?

![image](https://user-images.githubusercontent.com/61745625/75785608-faabcb00-5d9e-11ea-90fb-8f670dc228e1.png)

**Comment by bennothommo** [comment]
@inaRQuokka are the package files still being reported as corrupt?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
