### ISSUE TITLE
Component aliases validation

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#4976]
Hi!

Are there any particular reasons why component aliases cannot have dashes inside?

![image](https://user-images.githubusercontent.com/3897579/76408132-646e3b00-6384-11ea-9cc0-388cebf2d543.png)

Dashes could be used to separate parts of the string along with underscores when one is used for logical separation and another one as white space substitution. 

**Proposal**

Allow dashes inside alias names.

**Comment by bennothommo** [comment]
@GinoPane I assume it has something to do with the INI-style formatting of the configuration at the top of a CMS object, but truth be told, I'm not sure. Perhaps @LukeTowers or @daftspunk might know the reason.

**Comment by GinoPane** [comment]
Up

**Comment by bennothommo** [comment]
@GinoPane I think I know the reason - it's to allow for overriding the partial templates for aliased components (by using the component's alias as a filename in specific location in the theme). It's likely the validation was purposely made conservative to prevent issues with dashes in filenames.

It's likely not an issue anymore as most OS's allow dashes in filenames, so if you want to submit a PR that allows dashes, go ahead - just beware that we'll want to see some unit tests that cover this (including overriding the partial).

**Comment by GinoPane** [comment]
Please don't close

**Comment by GinoPane** [comment]
Up
