### ISSUE TITLE
Tree view does not work for deep nesting levels

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#4980]
- OctoberCMS Build: 465
- PHP Version: 7.2.4
- Database Engine: SQLite

### Description:
It looks like list tree view does not work for nesting levels deeper than 3. Here's the gif:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3897579/76557563-dd68b200-64ac-11ea-8549-14619328eb4a.gif)

Catefory 6 is a parent for Category 5, so it is expected to see that category there:

![image](https://user-images.githubusercontent.com/3897579/76557642-ff623480-64ac-11ea-8710-a66f0a6c88a7.png)

### Steps To Reproduce:

Just put tree a item to the 3 level and deeper.

**Comment by bennothommo** [comment]
@GinoPane There must be something else at work here - I cannot replicate the issue.

![Screenshot_2020-03-13 https 6bbcbba428dc octodock com(1)](https://user-images.githubusercontent.com/15900351/76579768-6234e980-6508-11ea-948e-77d93e1df96c.png)
![Screenshot_2020-03-13 https 6bbcbba428dc octodock com](https://user-images.githubusercontent.com/15900351/76579775-63fead00-6508-11ea-943a-a408c9a4591b.png)

Would you mind doing something investigation and see if there's perhaps an error being thrown by the JS, or if it's not saving something correctly? (my understanding is that the tree list view uses some form of session variable to record which tree branches are open).

**Comment by GinoPane** [comment]
Ok, I'll play around with it

**Comment by Eoler** [comment]
Maybe its SQLite? It works flawlessly with MariaDB.

**Comment by GinoPane** [comment]
@Eoler yep, I think about it too, because the issue persists with cookies cleared and no JS errors:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3897579/76598243-62c68380-64fa-11ea-8912-9870a1198cd2.gif)

Will dig into it.

**Comment by GinoPane** [comment]
@bennothommo @Eoler wow, it turned out the reason was in session driver.

I used file-based sessions for this setup and `framework/sessions` directory was missing, so sessions were not actually stored. When I switched to a cookie-based setup or created `sessions` directory for file sessions everything worked as expected.

**Comment by bennothommo** [comment]
@GinoPane thanks for letting us know. Curious as to how you remained logged in to the Backend though? :P

**Comment by GinoPane** [comment]
![image](https://user-images.githubusercontent.com/3897579/76608799-2ac93b80-650e-11ea-8ff1-80ebdb0dd846.png)
