### ISSUE TITLE
Defer a relation unbinding

### ISSUE THREAD

**Issue by hackolein** [octobercms/october#4981]
In the doc [Defer a relation unbinding](https://octobercms.com/docs/database/relations#defer-unbinding) is written, that there is a method called delete with deffered binding.  But this doesn't work, the item will delete directly and I can't find the method in 

> vendor/october/rain/src/Database/Relations/HasOneOrMany.php
Is that a bug in the code or a doc issue?

**Comment by bennothommo** [comment]
@hackolein The issue is the method should be `remove`, not `delete`. I've resolved this in the docs.
