### ISSUE TITLE
Unable to create new layout templates.

### ISSUE THREAD

**Issue by Kirutian** [octobercms/october#4985]
Anyone have a quick fix for not being able to edit or create new page templates ?

I get the following error:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /backend/cms
on this server.<br />
</p>
</body></html>

**Comment by LukeTowers** [comment]
Sounds like permission issues with your server.
