### ISSUE TITLE
Base Table or View not found

### ISSUE THREAD

**Issue by Mitchbird** [octobercms/october#4994]
I created my project locally using Xaamp and after hosting the website I had some problems with connecting to the database. Whenever I pull up the website I get a notification saying "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'October.system_settings' doesn't exist (SQL: select * from `system_settings` where `item` = system_log_settings limit 1)". I've been trying to fix this for awhile with no results. Below is a picture of the error and some additional info.
![problem](https://user-images.githubusercontent.com/61341680/77132414-62177b00-6a2d-11ea-8de7-4073003cb161.PNG)

**Comment by LukeTowers** [comment]
Looks like you haven't transferred the database over or updated the database connection settings in config/database.php
