### ISSUE TITLE
Can´t login on Backend´s - Page Loops on Login

### ISSUE THREAD

**Issue by az-vm** [octobercms/october#5016]
Hello,

I have october installed and working for long time,  but today i want to login on backend, and just can´t, i enter the credentials, and the page simple loops, no error show, nothing...

Any one have this issue ?

Thank you,
Vitor

**Comment by daftspunk** [comment]
Check this config, set it to `false` and try again

```
    /*
    |--------------------------------------------------------------------------
    | Back-end force HTTPS security
    |--------------------------------------------------------------------------
    |
    | Use this setting to force a secure protocol when accessing any back-end
    | pages, including the authentication pages. If set to null, this setting
    | is enabled when debug mode (app.debug) is disabled.
    |
    */

    'backendForceSecure' => null,
```

**Comment by az-vm** [comment]
Hello!

Thank you daftspunk, i have change as you told, but got the same problem.

Thank you!

**Comment by az-vm** [comment]
I have moved all the content to another host, and it worked fine.

On this particular host, i try to do a fresh install, and i got this error:

Zend OPcache API is restricted by "restrict_api" configuration directive

Could this tell something ?

Thank you!

**Comment by az-vm** [comment]
Host PHP info:

https://phpfpm-72.cloudweb-infos.hosting.ovh.net/

**Comment by LukeTowers** [comment]
@az-vm set `forceBytecodeInvalidation` to false in `config/cms.php`

**Comment by az-vm** [comment]
Thank you @LukeTowers for the comment.

As you told, i try it, but the same... login loop... it does not enter admin...


Thank you,

**Comment by az-vm** [comment]
The issue was detected.

On the host i facing this issue, i try to do some tests:

- SQL Source;

On OVH they have local and "Private-SQL", in this issue the sites was using the "Private-SQL", and i upload the SQL data to the "Local" SQL, and it worked.

At this moment i have detected were the issue is coming... 

So this is not a problem of OctoberCMS, it´s a Hosting issue, so it´s closed.

Thank you to all!
Vitor

**Comment by az-vm** [comment]
Just to people know: 

- The SQL ->  autocommit, Commit, and Rollback, was turned OFF, turining it ON, all worked normal, and login worked normal.

Thank you
