### ISSUE TITLE
October CMS unable to connect to the database

### ISSUE THREAD

**Issue by shailendracool433** [octobercms/october#5021]
I'm struggling to connect mysql database named 'dbsg_october' to the OCTOBER CMS.
ALL my credentials are exactly same but this error.

![image](https://user-images.githubusercontent.com/30532636/78223686-05b16280-74e7-11ea-8c3a-049044f899f4.png)

![image](https://user-images.githubusercontent.com/30532636/78223790-31344d00-74e7-11ea-8c30-3bbd29bccdb1.png)

**Comment by 4nik3t** [comment]
I think this is a problem for mysql 8+. Not sure if octobercms is tested on it

**Comment by LukeTowers** [comment]
@4nik3t what version of PHP are you using? See https://www.php.net/manual/en/ref.pdo-mysql.php, when using MySQL > 8.0.4 you have to use PHP 7.2 at least when using MySQL 8.0.4's new default authentication method (https://mysqlserverteam.com/mysql-8-0-4-new-default-authentication-plugin-caching_sha2_password/).

You can also switch MySQL to using the legacy authenticator as recommended here: https://github.com/laradock/laradock/issues/1390#issuecomment-419562297, but theoretically as long as you're running >= PHP 7.2 it should work fine. If it doesn't, you might need to switch to using the L6 branch of October (until it gets merged in a couple weeks) which would include the Laravel specific fixes for MySQL 8.0 here: https://github.com/laravel/framework/pull/23948

**Comment by 4nik3t** [comment]
@LukeTowers thanks for the info

**Comment by LukeTowers** [comment]
@shailendracool433 see above comment.
