### ISSUE TITLE
OctoberCMS installation does not work with composer create-project

### ISSUE THREAD

**Issue by norotaro** [octobercms/october#5024]
The installation with `composer create-project october/october myoctober` is not working.
This is the error:

**Your requirements could not be resolved to an installable set of packages.**
Problem 1
    - Installation request for wikimedia/composer-merge-plugin dev-master -> satisfiable by wikimedia/composer-merge-plugin[dev-master].
    - **wikimedia/composer-merge-plugin dev-master requires php >=7.2.0 -> your PHP version (7.4.4) overridden by "config.platform.php" version (7.0.8) does not satisfy that requirement.**

![imagen](https://user-images.githubusercontent.com/1774870/78273293-a4849180-74dc-11ea-8023-bfc855864455.png)

I think it's because this line https://github.com/octobercms/october/blob/ccb2c372bb1fb3980c1240ffb2f7aeef5e786dae/composer.json#L74

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/3a577cbbbb29b513072d5f18ab71d13d436779b4, was already fixed in the develop and L6 branches but composer create-project works off of the master branch.
