### ISSUE TITLE
PDF attachments don't show up in Windows 10 mail

### ISSUE THREAD

**Issue by maartenmachiels** [octobercms/october#5034]
- OctoberCMS Build: 465
- PHP Version: 7.3
- Database Engine: MySQL

### Description:
When sending an e-mail with a PDF attachment, the attachment doesn't show up in Windows 10 Mail. It does show up in Outlook, Gmail, Outlook Online... but for some reason it never shows up in the native Windows 10 Mail client. When sending the original e-mail to Gmail for example (where the PDF does show up without issue), and then forwarding it to Windows 10 Mail, the attachment does show up. This gives me the impression something might be wrong in the internals of the mail system.

Please be advised that there are multiple users that state that they can not receive any PDF attachments in Windows 10 Mail from any sender; but this isn't the case for me. I am receiving PDF attachments from other senders - but things only go wrong when the mail originates from an October CMS install. The issue persists on multiple computers, so it's not limited to my install.

Might there be something wrong in the way I'm including the attachment? Please note that the PDF file does exist and is accessible.

Example:
```
Mail::send('chocolata.estimator::mail.introduction', $vars, function($message) use ($vars) {
	$message->to('hank@kingofthehill.com', 'Hank Hill');
	$message->subject('Your propane quote');
	$message->attach('storage/app/media/estimate.pdf', ['as' => 'estimate.pdf', 'mime' => 'application/pdf']);
});
```
### Steps To Reproduce:
Send a mail with a script along the lines of described above. Try to open in Windows 10 Mail. See no enclosed PDF.

**Comment by LukeTowers** [comment]
@maartenmachiels are you able to find any related issues when searching this issue with SwiftMailer & Laravel itself? October doesn't really customize the logic provided by those libraries when it comes to attaching files.

**Comment by maartenmachiels** [comment]
Thanks Luke. I can't seem to find any related issues by searching for SwiftMailer & Laravel. I'll do some more investigation.
