### ISSUE TITLE
UI - Linking rows doesn't work in frontend

### ISSUE THREAD

**Issue by pablorq** [octobercms/october#5036]
- OctoberCMS Build: 464
- PHP Version:
- Database Engine: SQLITE
- Plugins Installed: builder-v1.0.26, User-v1.5.3, Debugbar-v3.0.1v1.2.0 -->

### Description:
The 'linking row' functionality isn't working. A simple table is shown with the anchor on the text instead of the row hover.

### Steps To Reproduce:

Based on the documentation: [Linking rows](https://octobercms.com/docs/ui/list#linking-rows).

Step to reproduce the issue:

- Create a new page
- Add the example code from the documentation
```
<div class="control-list">
    <table class="table data" data-control="rowlink">
        <tbody>
            <tr>
                <td>
                    <a href="http://octobercms.com">Link to this</a>
                </td>
                <td>Row will be linked</td>
                <td>This will also be linked</td>
                <td class="nolink">No link applied here</td>
            </tr>
        </tbody>
    </table>
</div>
```
- Open the page

As a result you have a table with a link on the text of the 1st column, but now a link on the entire row.

**Comment by pablorq** [comment]
I also tried the List 'Complete example' and doesn't behaves as the online demo, using the code from the documentation page.

**Comment by LukeTowers** [comment]
@pablorq where are you creating these pages? This is for the backend UI framework, if you aren't including the required styles / scripts in your frontend then they're not going to work there.

**Comment by pablorq** [comment]
Ah! Ok!

I thought it was for frontend also.

Thank you!
