### ISSUE TITLE
CMS Content Markdown not rendered as expected

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#5037]
- OctoberCMS Build: 465

### Description:
I am creating some content using the CMS content with the mardown editor.
My content files are named like this `program/week1.md`

My content is typed in like this in the editor

```md
Welcome guys,
to week 1
```

but it is rendered like this in the frontend using the twig `{% content 'file' %}`

`Welcome guys, to week 1`

I am expecting 2 paragraphs to be rendered.
Does it make sense?

**Comment by chrisvidal** [comment]
Not sure if this is documented somewhere, but adding 2 spaces at the end of a sentence forces a line return.

**Comment by mjauvin** [comment]
This is how markdown works. If you want to force a paragraph, just add an empty line between your paragraphs,like below:

paragraph 1

paragraph 2

**Comment by chrisvidal** [comment]
Y, I actually don't want force a paragraph but a line return.
2 space characters seems to be effective

**Comment by mjauvin** [comment]
Right, I've seen the two spaces documented but I find it not very easy to spot. I think it's better/more obvious to use a <br> at the end of the line you want to break.

**Comment by LukeTowers** [comment]
@chrisvidal you should also be able to run it through `|nl2br` using the following: `{% content('file') | nl2br %}`

**Comment by chrisvidal** [comment]
thanks
@LukeTowers `nl2br` does not prevent the needs of the 2 space characters apparently

in this 2 previous line, there is a line return at then end `thanks` and it appears correctly when rendered even though I didn't put 2 space characters. So I feel like there is something to look at here from github markdown rendering

**Comment by chrisvidal** [comment]
Just read about Markdown rendering that could use GFM line breaks, so there's no need to use MD's two-space line breaks.

**Comment by mjauvin** [comment]
> Just read about Markdown rendering that could use GFM line breaks, so there's no need to use MD's two-space line breaks.

what do you mean by GFM rendering?

**Comment by chrisvidal** [comment]
it is apparently a way of rendering line break depending on the markdown library used.
Not sure what library OC is using

**Comment by bennothommo** [comment]
@chrisvidal We use Parsedown (https://github.com/erusev/parsedown) which I'm fairly sure supports GFM.

**Comment by chrisvidal** [comment]
cool! 
I guess what matters is the parameter used to perform the markdown rendering by the TWIG command `content`

**Comment by chrisvidal** [comment]
I check their code and this parser does not support GFM rendering unfortunately.
there is no options of such.

**Comment by bennothommo** [comment]
@chrisvidal They list "GitHub-flavored" as a feature on their README, so that's rather surprising. Have you tested it to make sure?

**Comment by chrisvidal** [comment]
they are not mentioning this GFM rendering anywhere. and I tested on their test website.
and indeed, the line break is not happening.

**Comment by chrisvidal** [comment]
their demo to test is here: https://parsedown.org/demo
