### ISSUE TITLE
League\Csv incompatibility

### ISSUE THREAD

**Issue by rajakhoury** [octobercms/october#5041]
October Build 465 (wip/laravel-6)
Plugin: RainLab Blog
Steps to reproduce: Import any file..

The `Backend\Models\ImportModel` throws an exception during CSV imports.
Message: `Call to undefined method League\Csv\Reader::addFilter()`

The package changelog / website docs says that these methods have been deprecated in v9.

>   The CSV records filtering methods are removed in favor of the `League\Csv\Statement` class:
    - `League\Csv\AbstractCsv::addFilter`,
    - `League\Csv\AbstractCsv::addSortBy`,
    - `League\Csv\AbstractCsv::setOffset`,
    - `League\Csv\AbstractCsv::setLimit`;

This version seems to be added to the L6 upgrade branch.

**Comment by bennothommo** [comment]
Thanks for letting us know @rajakhoury - fixed as of https://github.com/octobercms/october/commit/3720af4c02fae89815bd982f2ef6fc920dd8e1d1.
