### ISSUE TITLE
Composer install stuck: "Something's changed, looking at all rules again (pass #789)"

### ISSUE THREAD

**Issue by idpsycho** [octobercms/october#5043]
- OctoberCMS Build: new installation from 2020 (googled and read 10 pages, cant find how to find ocms version from console)
- PHP Version: PHP 7.3.11 
- Plugins Installed: none

### Description:
`composer install` gets stuck on:
```
Updating dependencies (including require-dev)
```

When run with `composer i -vvv` i get this:
```Reading /Users/psycho/.composer/cache/repo/https---repo.packagist.org/provider-symfony$filesystem.json from cache
Reading /Users/psycho/.composer/cache/repo/https---repo.packagist.org/provider-marc-mabe$php-enum.json from cache
Reading /Users/psycho/.composer/cache/repo/https---repo.packagist.org/provider-icecave$parity.json from cache
Reading /Users/psycho/.composer/cache/repo/https---repo.packagist.org/provider-icecave$repr.json from cache
Resolving dependencies through SAT
Looking at all rules.
Something's changed, looking at all rules again (pass #2944)
```

### Steps To Reproduce:
Happens in two different projects by two different people, roughly both got created about 2 months ago, so starting 2020. RIght now, i tried to install those for the first time ever, and my composer install is getting stuck. What solves the problem is to create a new project and copy config+plugins+themes there.

I googled for this problem, it has happened to others, but the solutions didnt match october environment, so I think this is new bug.

I have cloned and installed like 20 october projects in last week, so this is either very recent (today), or must be related to a very specific build from around 2020-03-01.

Update: it started happening on a project that worked just few hours ago. Possibly some very fresh issue.

**Comment by bennothommo** [comment]
@idpsycho Just to clarify, are you saying that you were able to install these projects 2 months ago when they started, but you cannot now - ie. you're moving the projects to a different environment?

**Comment by idpsycho** [comment]
Okay, so the issue is that the developer changed his platform php dependency from 7.0.8 to 7.2.0 after he encountered the wikimedia issue. If I just change the platorm php back to 7.0.8, it doesnt break (it breaks on the old wikimedia bug)

```
Reading /Users/psycho/.composer/cache/repo/https---repo.packagist.org/provider-icecave$repr.json from cache
Resolving dependencies through SAT
Looking at all rules.
Something's changed, looking at all rules again (pass #4)
Dependency resolution completed in 1.625 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for wikimedia/composer-merge-plugin dev-master -> satisfiable by wikimedia/composer-merge-plugin[dev-master].
    - wikimedia/composer-merge-plugin dev-master requires php >=7.2.0 -> your PHP version (7.3.11) overridden by "config.platform.php" version (7.0.8) does not satisfy that requirement.
```

Okay, so the solution is to NOT DO THIS:
```
    "config": {
        "preferred-install": "dist",
        "platform": {
            "php": "7.2.0"
        }
    },
```

put it back to original value of
```
            "php": "7.0.8"
```

SOLUTION
and if you have old project, the only thing needed to fix it is to change require from:
```
"wikimedia/composer-merge-plugin": "dev-master"
```
to the value that is being used in latest october installations:
```
"wikimedia/composer-merge-plugin": "1.4.1"
```

**Comment by bennothommo** [comment]
@idpsycho Thanks for the clarification. You are indeed correct - we have fixed this in `develop` and `master` already, but some installs may have already been done before the fix was in place.
