### ISSUE TITLE
Subtree split repos out of sync?

### ISSUE THREAD

**Issue by aurelien-roy** [octobercms/october#5044]
Was wondering, are the subtree repos (like [octoberrain/system](https://github.com/octoberrain/system)) synced automatically with this one,  or is the sync is triggered by a manuel actuoin?

Because I just noticed they are out of sync.
Last commit on october/develop was 3 days ago and affected all 3 modules.

But the submodules repos (like https://github.com/octoberrain/system/tree/develop) have their last commit dated from 13 days ago.

So when I set my composer.json to get the "dev-develop" versions of the October modules, the versions I get are not exactly the latest. Is there a workaround to get the same one than october/develop?

**Comment by bennothommo** [comment]
@aurelien-roy At this stage, it's a manual process. We're looking to make it automated through GitHub Actions at some point, but we are working against some restrictions that are in place with that service (ie. it won't work cross-repo).

I'll run the task now though so the submodules are up-to-date.
