### ISSUE TITLE
Standardize the User model

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [octobercms/october#5050]
I've been using OctoberCMS to build a few mobile applications and I wrote a plugin as well for [my convenience](https://octobercms.com/plugin/mohsin-user) to re-use code. However, some projects require multi-level auth i.e. backend user / frontend user which is already supported by OctoberCMS. However, I found there **are inconsistencies in the field names**.

For example, [the frontend User model](https://github.com/rainlab/user-plugin/blob/master/models/User.php#L48-L53) has: **_email, name, surname, login, password_** as the fields names.

Whereas, [the backend User model](https://github.com/octobercms/october/blob/develop/modules/backend/database/migrations/2013_10_01_000001_Db_Backend_Users.php#L13-L17) has: **_first_name, last_name, login, email, password_** as the field names.

I am happy with login, email and password fields since they have the same name. However, I do not understand why the name fields differ. This hinders me from writing a single User class in my mobile apps (Kotlin/Swift) and I so create FrontendUser and BackendUser. Is there any point to it and are you achieving something doing so??

**Comment by daftspunk** [comment]
first_name and last_name indicate both are required fields

name and surname indicate that surname is optional

name could be used for the full name (name: Adam Person)
name and surname could be broken apart (name: Adam, surname: Person)

**Comment by SaifurRahmanMohsin** [comment]
So you want the surname to be optional for backend users and that is why you chose it over a more consistent first_name and last_name across both rainlab’s user model and october’s user model?
