### ISSUE TITLE
Stay logged in checkbox appears twice on backend login form. 

### ISSUE THREAD

**Issue by mjauvin** [octobercms/october#5054]
When cms.backendForceRemember is set to null, the "stay logged in" checkbox appears twice (see attached screenshot)

![Screenshot_20200428-092351](https://user-images.githubusercontent.com/2013630/80492959-b79b4d80-8932-11ea-99c5-df7ec4644f56.jpg)

**Comment by mjauvin** [comment]
@LukeTowers this does not fix the problem because on mobile, it's overriden by the following media query:
```
@media (max-width: 768px)
body.outer .layout >.layout-row >.layout-cell .outer-form-container .horizontal-form input {
    display: block;
    width: 100% !important;
    margin-bottom: 20px;
}
```

**Comment by LukeTowers** [comment]
It fixed it when I tested it, but that was in chrome's inspector so the CSS was probably slightly prioritized. Just add an !important and PR it.
