### ISSUE TITLE
AJAX loading indicator does not properly stop after receiving a redirect response to a file download

### ISSUE THREAD

**Issue by datune** [octobercms/october#5055]

**Comment by bennothommo** [comment]
@datune If you have time, would you mind providing us with a test case to the [Test plugin](https://github.com/octoberrain/test-plugin) demonstrating this issue?

**Comment by mjauvin** [comment]
I do confirm this behavior.

**Comment by bennothommo** [comment]
@mjauvin Do you have a test case I can review for it?

**Comment by mjauvin** [comment]
No, I don't.

**Comment by LukeTowers** [comment]
@bennothommo 

```php
public function onTestRedirect()
{
    return redirect()->to('path/to/file/to/be/downloaded/by/the/browser.csv');
}
```

**Comment by bennothommo** [comment]
Thanks @LukeTowers, but I do know how to do a redirect ;). I was simply asking if someone might've set up a link or action with an AJAX handler and the necessary attributes to show the loader, ie. `data-load-indicator`.

**Comment by LukeTowers** [comment]
Oh, sorry about that @bennothommo, thought you were confused about the exact implementation of the handler. I believe all AJAX requests in the backend trigger the stripe loading indicator though don't they?

**Comment by cosminbosutar** [comment]
I have the same behavior.

I have the download page as follows:
`title = "Download"
url = "/download"
layout = "default"
is_hidden = 0
==
    function onStart()
    {
        $pathToFile = storage_path('static/download-file.xlsx');
        $fileName = 'download-file.xlsx';
        $headers = [
            'Content-Type' => 'application/xlsx'
        ];

        return Response::download($pathToFile, $fileName, $headers);
    }
==
`

I have an ajax handler that redirects to this page:
`public function onDownloadImportTemplate(){
        return Redirect::to('download');
    }`

The steps are the following:

1. I click the download button
2. The "onDownloadImportTemplate" ajax handler is executed
3. I am redirected to the download page
4. The download prompt is displayed 

Everything works as expected until here.

After I finish the download, as mentioned in the title, the AJAX loading indicators (from the top of the page and the loading circle that replaces the mouse pointer) reappear.

The only way to bring the page back to normal is to do a manual refresh.

**Comment by adrenth** [comment]
The addition of this specific code has nasty side-effects:

```php
handleRedirectResponse: function(url) {
    window.location.assign(url)
    // Indicate that the AJAX request is finished if we're still on the current page
    // so that the loading indicator for redirects that cause a browser to download 
    // a file instead of leave the page will properly stop.
    // @see https://github.com/octobercms/october/issues/5055
    $el.trigger('ajaxDone')
},
```

In quite a lot of our projects we have a following situation as such:

```html
<form data-handler="onPlaceOrder">
    <button type="submit" data-attach-loading>Place Order Now!</button>
</form>
```

```php
public function onPlaceOrder(): RedirectResponse
{
  $this->placeOrder(...);

  return redirect()->to('/thank-you');
}
```

Now when the **Place Order Now!** is clicked, the button will be disabled (because of the `data-attach-loading`) while processing the request.

When a redirect response has been detected, it will point the browser to the new URL and immediately after that it will trigger the `ajaxDone` and de disabled-state of all form elements (which have `data-attach-loading`) will be discarded. Which enables the user to press the button **Place Order Now!** again during the redirection process. Which results in a form which is submissed twice (or more).
