### ISSUE TITLE
Relation view filter widget has not been bound to the controller

### ISSUE THREAD

**Issue by Rike-cz** [octobercms/october#5056]
- OctoberCMS Build: 465
- PHP Version: 7.3

### Description:
![tags](https://user-images.githubusercontent.com/4247582/80518770-38843480-8987-11ea-9eee-3aa7f494a026.gif)

### Steps To Reproduce:
- relation Category hasMany Articles
- render relation view widget in category preview page with custom filter scopes.
- type something to search fields of any group type scope.

**Comment by LukeTowers** [comment]
@alxy is this related to the stuff you did?

**Comment by alxy** [comment]
Probably yes, but does the filtering work, just the search doesn't?
@Rike-cz Maybe you can look into it, I have started a new job and don't have too much time now.

**Comment by LukeTowers** [comment]
@Rike-cz my guess is that since the popover DOM nodes are technically at the root of the document and not inside the parent form element the required `relation` POST variable is not being sent with the search AJAX request which means that the relationcontroller isn't initializing the required widgets.

**Comment by Rike-cz** [comment]
> Probably yes, but does the filtering work, just the search doesn't?
@alxy Yes, filtering works only search does not.
It looked like simple one line missing problem but what I inspected and @LukeTowers wrote, it is not so simple...

**Comment by LukeTowers** [comment]
It shouldn't be too difficult, you just need to be able to provide the relation field in the AJAX requests sent by the filters.

**Comment by alxy** [comment]
I can confirm the issue.

**Comment by alxy** [comment]
While trying to fix this, I have realized that it is actually a duplicate of https://github.com/octobercms/october/issues/4775 , which has already been fixed by @bennothommo . Nice work there! It works for me in view and manage mode.

**Comment by bennothommo** [comment]
@alxy Thanks for letting us know about the duplication.

This issue is fixed by 9155e7d.
