### ISSUE TITLE
Hide password value in Mail Configuration

### ISSUE THREAD

**Issue by adrian-zawada** [octobercms/october#5061]
In Mail Configuration in CMS Backend field of password input type shoulb be set to password now is text. After logging in the user should not see the password, often many people work on one CMS this is dangerous.

### In short, what should you do?
- change the password input from type="name" to type="password"

**Comment by bennothommo** [comment]
@adrian-zawada Thanks for your submission, but we are not going to change the password field. There needs to be an ability for admins to be able to review the password entered, in case of debugging issues with connecting to SMTP. Just remember that the password is in plaintext in `config/mail.php` as well.

If you don't want people to be able to see the password, assign them user accounts where the "System > Manage mail settings" permission is disabled.

**Comment by LukeTowers** [comment]
Additionally, the password field as implemented in October does not retain the value from the model which means that if the record is saved again a blank value for the password field is inserted instead overwriting the password configuration.

**Comment by tomaszstrojny** [comment]
Just as a side note, what do you think about changing the field to the password but with the "show" button next to it?

It's not about security but just other people that may see it on my screen.

**Comment by LukeTowers** [comment]
@tomaszstrojny I'm not necessarily opposed to it, but the field type would have to be different from `password`, perhaps `credential`, or `hidden-value`, or `sensitive`. Not really a huge fan of any of those ideas, ideas welcome.

**Comment by bennothommo** [comment]
@tomaszstrojny Wouldn't the same problem occur with the password being visible in `config/mail.php` too?

**Comment by adrian-zawada** [comment]
> @adrian-zawada Thanks for your submission, but we are not going to change the password field. There needs to be an ability for admins to be able to review the password entered, in case of debugging issues with connecting to SMTP. Just remember that the password is in plaintext in `config/mail.php` as well.
> 
> If you don't want people to be able to see the password, assign them user accounts where the "System > Manage mail settings" permission is disabled.

Okey, I understend but leaving the password field with the text type is not very secure. Someone sitting next to them can easily see them etc. It would be nice if this field was a password and there was a show password button somewhere nearby. I know this not very nessesery but would be helpful for everyone :-)

Have a nice day!

**Comment by bennothommo** [comment]
@adrian-zawada I can appreciate that it might not *seem* secure, but as I've stated, it's no less secure than the password being available on your editor if you were to open `config/mail.php`.

If you are worried about colleagues or other people looking over your shoulder and stealing passwords, I would suggest one of these:

![image](https://user-images.githubusercontent.com/15900351/80944464-3c4b0780-8e1c-11ea-8cc2-eee7a668800a.png)

**Comment by tomaszstrojny** [comment]
Ha, good one @bennothommo :)

I would be worried more about the client's administrator who I often give access to backend so that they can change mail settings without my help.

I think that for showing any sensitive data we should have something like the field. Whether it's mail password or any encrypted data like API tokens, passwords to third-party services etc. I am not a big fan of displaying any credentials in plain text, that's why I have decided to join the conversation.

I will make a PR in a minute that introduces the feature if you're okay with it. We can talk about the idea there.

**Comment by bennothommo** [comment]
@tomaszstrojny

> I would be worried more about the client's administrator who I often give access to backend so that they can change mail settings without my help.

Not to argue a point to death, but they would be trusted with the mail settings though? That's what the permissions are for ;).

Nonetheless, if you do happen to PR a new feature to have *revealable* passwords, I'm sure that'll be a useful addition. Let us know how you go :)

**Comment by bennothommo** [comment]
Fixed by #5201.
