### ISSUE TITLE
Laravel 6: Email validation filter is too permissive

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#5070]
Originally reported by @datune.

Laravel introduced fancier email validation in 5.8 (https://github.com/laravel/framework/pull/26503), but made it too permissive by default, supposedly following the RFC exactly (although there are inconsistencies reported). This has caused breaking changes in emails reported as valid even though they may not be: https://github.com/laravel/framework/issues/28233, https://github.com/laravel/framework/issues/27875.

We need to make sure that October overrides Laravel's email validator to make the default filter used `email:filter`, which uses PHP's built in email validator, instead of `email:rfc` which isn't even technically accurate to the RFC (reportedly).

We should still support the other filters used, we just need to change the default filter used: https://laravel.com/docs/6.x/validation#rule-email.

**Comment by LukeTowers** [comment]
@bennothommo could you take a stab at this?

**Comment by bennothommo** [comment]
Will do!

**Comment by bennothommo** [comment]
Fixed by https://github.com/octobercms/library/commit/97d4163041f68c23f6deb28832d860463bb233ee and https://github.com/octobercms/october/commit/c3a5780d37996f14fefacd7ba5af4703f53b14db.
