### ISSUE TITLE
Backend datepicker widget always sends datetime strings to the server

### ISSUE THREAD

**Issue by multiwebinc** [octobercms/october#5072]
The [datepicker](https://octobercms.com/docs/api/backend/formwidgets/datepicker) form widget can be configured with 3 modes, `datetime`, `date`, or `time`. However if using either `date`, or `time`, a full timestamp string is always sent to the server.

![image](https://user-images.githubusercontent.com/901732/82020168-dba2a280-9645-11ea-9815-e9bde2585dbd.png)

The timestamp is also converted to UTC, so it is not necessarily even the correct value. For example, if I am using a date-only picker, and I select today's date, the server might get a timestamp value that's yesterday, today, or tomorrow, depending on my timezone offset. Likewise when using the time-only picker, it will be modified by my current timezone offset.

I would expect that if `time` mode is used, only the time would be sent to the server, or if `date` is used, only the date would be sent to the server, and in both of these cases, the timezone offset should not modify them.

Note, when using the datepicker in datetime mode, it makes perfect sense to convert it to UTC since this is how it should be stored in a database. It doesn't make sense for a single date (which should be stored in a `DATE` column) or single time.

**Comment by bennothommo** [comment]
@multiwebinc We've been discussing this issue as a part of https://github.com/octobercms/october/pull/4111#issuecomment-628069893. I agree that only the actual part of the date string being requested should be sent, and when it comes to `date`, timezones should not play a part. With `datetime` and `time`, they should, but I think it needs to be optional for `time`.

**Comment by multiwebinc** [comment]
I edited my post slightly to explain my reasoning, which is that it should be sent to the server in the same format that it will be stored in a database.

A single time cannot have a timezone in and of itself, because the UTC offset is dependent on the date. For timezones that have daylight savings time, UTC offset will vary throughout the year, so if you're only selecting the time, how do you know what date to use for converting it to UTC?

I don't think there is **that** much of a use case for time only because it almost always depends on a date, but one example I can think of would be if someone wants to save their business hours in the database. Business hours don't depend on daylight savings time.

**Comment by tomaszstrojny** [comment]
Just as a side note, I was struggling with the time in the [Let's Rent](https://octobercms.com/plugin/initbiz-letsrent) plugin. Users can enter the opening hours of the rental office. I came up with using `ignoreTimezone` attribute and then parsing every single hour by `Carbon` to get just the hour from the date. Did the trick.

**Comment by LukeTowers** [comment]
I think I would agree with @multiwebinc that if it's being used in `mode: date` or `mode: time`, then only those values should be sent back to the server without any timezone processing on it, however we also have the ignoreTimezone property to factor in, and all of this gets very complicated quite quickly when considering changing the existing behaviour which could affect any workarounds people have in place for this right now. I also don't really have time to dedicate to solving this in a robust way more than the five minutes I'm spending formulating this response right now, so I'm open to suggestions.

@multiwebinc does using ignoreTimezone solve your problems?

**Comment by bennothommo** [comment]
@LukeTowers @multiwebinc given your comments, the proposed solution would be the following:

- When mode `date` is used, only the date part of the value is posted, `ignoreTimezone` is implicitly enabled, the dev is encouraged to use the DATE field type in the DB.
- When mode `time` is used, only the time part of the value is posted, `ignoreTimezone` is implicitly enabled, the dev is encouraged to use the TIME field type in the DB.
- When mode `datetime` is used, the entire value is posted, `ignoreTimezone` can be enabled or disabled by the dev's choice, the dev is encouraged to use the DATETIME field type in the DB.

You're right in that, realistically, only `datetime` is in any way affected by timezones. We already handle this by saving the date/time in UTC (unless someone enables `ignoreTimezone`).

**Comment by multiwebinc** [comment]
@LukeTowers If I set ignoreTimezone, then date and time fields are not affected by timezones. Time fields are sent to the server with the user's current date at the selected time. Date fields are sent with the selected date at "00:00:00" time.

I was going to take a quick stab at it to see how easy or difficult it would be to modify the JS, and I notice that it's using minfied JS (storm-min.js). Is there any sort of setting somewhere that would allow it to use the source JS files instead of minified versions?

**Comment by multiwebinc** [comment]
I'm wondering what the best way to accomplish this would be since it would be a breaking change. I know other plugins rely on the current behavior. For example, [Vdlp.Redirect](https://octobercms.com/plugin/vdlp-redirect) with almost 12000 installs explicitly relies on the format currently being used for the "date" mode ([see here](https://github.com/vdlp/oc-redirect-plugin/blob/5424ac646cb6e288e997cf696a7ef4c33e4eb9ff/classes/RedirectRule.php#L112)). I'm thinking possibly adding a new attribute, even though that does not seem ideal to me, since it's extra bloat. Or at least, change this when the Laravel 6 version is released.

**Comment by bennothommo** [comment]
@multiwebinc VDLP's Redirect plugin is safe - their implementation is using a `substr` call to extract just the date portion anyway, so it would still be safe if it's just the date. You are, however, right in the sense that it's a breaking change if people were parsing the date-time string in some special way, but on the other hand, it is fixing up an actual issue where the date is sometimes incorrect when it's being converted to UTC.

My vote is to change the behaviour, but I might get the other maintainers to weigh in too - what do you reckon @LukeTowers, @daftspunk?

**Comment by multiwebinc** [comment]
@bennothommo You're right. I missed the substr part.

**Comment by LukeTowers** [comment]
@multiwebinc there is a setting to decompile the backend assets, see https://github.com/octobercms/october/blob/develop/config/develop.php#L22.

@bennothommo I would think that it would be an acceptable change to make, but I would want to see automated tests added for the future, and I can't dedicate any time to reviewing this in depth until a PR is submitted (definitely not going to be a part of 466, and maybe not even L6).

**Comment by multiwebinc** [comment]
@LukeTowers Take a look.

**Comment by daftspunk** [comment]
Moved to #5080
