### ISSUE TITLE
Package files from server are corrupt

### ISSUE THREAD

**Issue by GoldenScrew** [octobercms/october#5073]
Hello, I am newby in OctoberCMS, and I first time try to install thie smc on my hosting, but I had an error every time.

> [2020/05/15 07:26:01] Host: Linux pkz12.hoster.kz 3.10.0-962.3.2.lve1.5.26.2.el7.x86_64 #1 SMP Tue Jul 23 08:31:06 EDT 2019 x86_64
> [2020/05/15 07:26:01] PHP version: 7.2.28
> [2020/05/15 07:26:01] Server software: Apache
> [2020/05/15 07:26:01] Operating system: Linux
> [2020/05/15 07:26:01] Memory limit: 512M
> [2020/05/15 07:26:01] Max execution time: 3600

> The operation timed out. Please increase the server's timeout and try again.
Everytime it was stopped on [2020/05/15 07:26:54] Install step: downloadCore
 
Then I changed time of execution for php in .htaccess
```
php_value max_execution_time 6000
php_value max_input_time 6000
```
and now I have this error:
> .============================ POST REQUEST ==========================.
> [2020/05/15 07:41:38] Postback payload: Array
> (
>     [step] => downloadCore
>     [meta] => Array
>         (
>             [core] => Array
>                 (
>                     [hash] => 93c923f8dc1f83da345a11f087c3c352
>                     [build] => 465
>                     [uhash] => a8da883ce43bd326c082338dec1e006b
>                 )
> 
>         )
> 
>     [handler] => onInstallStep
> )
> 
> [2020/05/15 07:41:38] Install step: downloadCore
> [2020/05/15 07:41:41] File hash mismatch: 93c923f8dc1f83da345a11f087c3c352 (expected) vs 34780adc28d4e1567d9637dbd645ffca (actual)
> [2020/05/15 07:41:41] Local file size: 16384
> [2020/05/15 07:41:41] Handler error (onInstallStep): Package files from server are corrupt
> [2020/05/15 07:41:41] Trace log:
> #0 /var/www/vhosts/goldenscrew.net/httpdocs/octobercms/install_files/php/Installer.php(312): Installer->requestServerFile('core', '93c923f8dc1f83d...', 'core/get', Array)
> #1 /var/www/vhosts/goldenscrew.net/httpdocs/octobercms/install_files/php/Installer.php(48): Installer->onInstallStep()
> #2 /var/www/vhosts/goldenscrew.net/httpdocs/octobercms/install_files/php/boot.php(91): Installer->__construct()
> #3 /var/www/vhosts/goldenscrew.net/httpdocs/octobercms/install.php(1): include('/var/www/vhosts...')
> #4 {main}

I see tat you had similiar problems past years and these problems just was closed. What should I do?

**Comment by LukeTowers** [comment]
Try installing on a different server or locally. It's possible that your host is firewalling connections to the download server. That is usually what those other issue were caused by.

**Comment by GoldenScrew** [comment]
> Try installing on a different server or locally. It's possible that your host is firewalling connections to the download server. That is usually what those other issue were caused by.

Which server IP should I tracert?

**Comment by LukeTowers** [comment]
Not sure, you'd have to send an email to hello@octobercms.com
