### ISSUE TITLE
for..of is not supported in IE11

### ISSUE THREAD

**Issue by tobias-kuendig** [octobercms/october#5078]
What is the current IE version October supports?

[The service worker removal in the backend](https://github.com/octobercms/october/search?q=navigator.serviceWorker.getRegistrations%28%29.&unscoped_q=navigator.serviceWorker.getRegistrations%28%29.) currently fails as it uses a `for..of` loop that is not supported in IE11.

```js
if (location.protocol === 'https:') {
    navigator.serviceWorker.getRegistrations().then(
        function(registrations) {
            for (let registration of registrations) {
                registration.unregister();
            }
        });
}
```

IE11 compatible:

```js
// Untested!
if (location.protocol === 'https:') {
    navigator.serviceWorker.getRegistrations().then(
        function(registrations) {
            registrations.forEach(function (registration) {
                registration.unregister();
            });
        });
}
```

**Comment by bennothommo** [comment]
@tobias-kuendig we still target IE11 at the moment. I'll switch this up shortly.
