### ISSUE TITLE
Can't get class with params from container

### ISSUE THREAD

**Issue by KonstantinObuhov** [octobercms/october#5081]
- OctoberCMS Build: 465 
- PHP Version: 7.x

### Description:
According to the Laravel API we have the ability to resolve a class instance out of the container with passing params to its constructor.

[the-make-method](https://laravel.com/docs/5.6/container#the-make-method)

### Steps To Reproduce:

1) Create a TServiceProvider
```
<?php Vendor/Plugin/Providers;

use October\Rain\Support\ServiceProvider;
use TestService;

class TServiceProvider extends ServiceProvider
{
    /**
     * Boot the service provider.
     */
    public function register()
    {
        $this->app->bind('test', TestService::class);
    }
}
```

2) Create a TestService class
```
<?php namespace Vendor/Plugin/Providers;

class TestService
{
    public $mode;

    /**
     * TestService constructor.
     */
    public function __construct($mode = 123)
    {
        $this->mode = $mode;
    }
}
```

3) Register the TServiceProvider

```
<?php Vendor/Plugin;

use System\Classes\PluginBase;
use App;

class Plugin extends PluginBase
{
    public function boot()
    {
          App::register('Vendor/Plugin/Prividers/TServiceProvider');
    }
}
```

4)Try to make the TestService class with params in routes.php file

```
Route::get('/test', function () {
    // this code throws an exception
    dd(App::make('test', ['mode' =>321]));
    dd(app()->make('test',  ['mode' => 321]));
    // this code works well
    dd(app()->make('test'));
    dd(App::make('test'));
});
```

You will get an exception if make methods calls with params
ReflectionException: Class test does not exist in /Users/konstantin/Sites/test/vendor/october/rain/src/Foundation/Maker.php:64

I've tested this approach with pure Laravel 7.x and it works.

**Comment by LukeTowers** [comment]
@KonstantinObuhov try testing it with Laravel 5.5, or switch to the L6 branch of October and try it there instead: https://github.com/octoberrain/meta/blob/master/l6-upgrade-notes.md

October only uses LTS releases of Laravel. If you can replicate the desired functionality in 5.5 or 6 (and can't replicate in the L6 branch of October) then we can proceed.

**Comment by LukeTowers** [comment]
Also, try accessing the class with App::make() later in the request lifecycle (i.e. not in a custom route) and see if that has anything to do with it.
