### ISSUE TITLE
css is broken for (auto-complete) drop-down inside inspector 

### ISSUE THREAD

**Issue by hardik-satasiya** [octobercms/october#5085]
![Screenshot 2020-05-22 at 3 55 52 PM](https://user-images.githubusercontent.com/2410795/82658818-4e62dd80-9c45-11ea-91b9-9c205e6f0e54.png)

It seems css is broken for drop-downs inside inspector 

step to reproduce
-----
just open any inspector and try to type on auto-complete dropdown.

**Comment by bennothommo** [comment]
@hardik-satasiya Would you mind providing us with the build of October you are running? Also, it looks like you are running the Builder plugin in your screenshot, would you mind providing us the version of that plugin you are running as well?

**Comment by hardik-satasiya** [comment]
Sorry for not posting that information.

```
-> OctoberCMS Build => 465
-> RainLab.Builder =>  1.0.26
```

**Comment by bennothommo** [comment]
@hardik-satasiya Thanks a lot - we'll take at it soon. :)

**Comment by LukeTowers** [comment]
@hardik-satasiya Fixed by https://github.com/octobercms/october/commit/1b8fae0ef0ac219c3a82e781954c31343304d12f
