### ISSUE TITLE
Relation manage filter with Many-to-many relationship

### ISSUE THREAD

**Issue by huynhnamegal** [octobercms/october#5089]
I have read #4241, and I've tried to use filter to scope data for many-to-many relationships (with Pivot), but it's just work in view, not in manage.
![image](https://user-images.githubusercontent.com/20609668/82816456-5fba1d00-9ec5-11ea-85f7-0d644c0f1532.png)
My relation_config.yaml
![image](https://user-images.githubusercontent.com/20609668/82816530-8415f980-9ec5-11ea-829d-bfd91e42f094.png)
![image](https://user-images.githubusercontent.com/20609668/82816554-8e37f800-9ec5-11ea-90a4-3c8ad209ebfd.png)
And filter just work on view.
I don't know this is bug or maybe a future feature. Can I have another way to filter that (Because I  have more than 2000 records)

**Comment by LukeTowers** [comment]
@alxy did you implement list filters on the pivot manage widget or does that still need to happen?

**Comment by alxy** [comment]
I thought it would work on all manage list, no matter if they included pivot fields or not. Does it work if you do not have pivot fields in your columns, @huynhnamegal ?
In any case, please provide a reproducable example of the bug at the [test plugin](https://github.com/octoberrain/test-plugin) ?

**Comment by alxy** [comment]
@huynhnamegal I realised the filter view for the pivot manage list has not been updated accordingly. Maybe this resolved your issue: https://github.com/octobercms/october/pull/5099
