### ISSUE TITLE
Allow multiple subdirectory levels in FileDatasource "select" method

### ISSUE THREAD

**Issue by bennothommo** [octobercms/october#5093]
Related:
- https://github.com/octobercms/october/pull/5087
- https://github.com/octobercms/library/pull/315

The `select` method in the `October\Rain\Halcyon\Datasource\FileDatasource` class currently limits its search to allow only a single level of subdirectories. Since this method is used to load up the asset list for the CMS module, this effectively means that people may only store one level of subdirectories for pages, partials, layouts, etc.

This pre-PR issue proposes that we allow the `select` method to search a specified number of subdirectory levels (say 3 levels for CMS assets), with an option to go to any number of levels which will be useful for https://github.com/octobercms/october/pull/5087.

There is also a UI factor, in that we need to ensure that the tree list for CMS assets still correctly displays with more levels of subdirectories being allowed.

**Comment by SebastiaanKloos** [comment]
@bennothommo I know the Developer Tools plugin uses the same kind of UI with multiple levels of subdirectory

**Comment by bennothommo** [comment]
@SebastiaanKloos you're right - I haven't looked into how that's setup yet, but I'll definitely use that if it works.

**Comment by daftspunk** [comment]
This feature is coming as part of the new editor coming soon
