### ISSUE TITLE
Author's free plugin installation mail alert is still sending when unwanted

### ISSUE THREAD

**Issue by RomainMazB** [octobercms/october#5095]
I'm receiving mails everyday when the free plugins I've created are added to a project.

I've unchecked the checkbox in author's settings to not receive them and I thought for a while it was working but then I've submitted some new plugins and now I'm receiving them again.

Don't know (why it would be) if the submission of new plugin is related but I suspect it is.

**Comment by LukeTowers** [comment]
Please send an email to hello@octobercms.com
