### ISSUE TITLE
"success is not a function" in branch "wip/laravel-6"

### ISSUE THREAD

**Issue by RodrigoGalter** [octobercms/october#5096]
- OctoberCMS Build: wip/laravel-6
- PHP Version: 7.4

### Description
When uploading a csv the system stop, and the console displays this error message.

### Message error
Uncaught TypeError: formEl.request(...).success is not a function at october.form.js?v465:153

### Steps To Reproduce:
Upload file csv.

**Comment by LukeTowers** [comment]
@RodrigoGalter can you check to see if you have https://github.com/octobercms/october/commit/655c8011b964367949cc76a4caf93e17502eda9e applied locally?

**Comment by RodrigoGalter** [comment]
@LukeTowers won't exists this implementation yet.

![image](https://user-images.githubusercontent.com/2292422/83059139-cfe4b200-a02f-11ea-9064-3e27fc741362.png)

**Comment by LukeTowers** [comment]
@RodrigoGalter I've just merged the changes into the Laravel 6 branch, building the release right now, will post another comment when it's ready for you to run composer update to pull the fix in.

**Comment by LukeTowers** [comment]
@RodrigoGalter you should be good to run `composer update` now to get the latest fixes.
