### ISSUE TITLE
Difficulties finding the backend

### ISSUE THREAD

**Issue by philip** [octobercms/october#5098]
I struggled to find the backend UI. Here's what I did:

1. curl -s https://octobercms.com/api/installer | php
2. php artisan october:install
3. Opened it in browser (using Valet service)
4. See an 'October Demo' site; w/ 3 pages

But I could not find the backend admin UI; and I saw no indication of one (e.g., no login) in the demo.

IMHO this should be simpler/clearer to find. I ended up guessing by appending '/backend' to the URL and finding it while typing this issue. I tried '/admin' initially.

Proposed solution: reference (link to) it from the October Demo; and also clarify its location in the documentation. Perhaps the latter already exists as I'm only 10 minutes into this; but figured this feedback is potentially useful anyways.

**Comment by LukeTowers** [comment]
I appreciate the feedback @philip, be sure to keep an eye out for any other rough spots in the learning experience / documentation. PRs are always greatly appreciated!

**Comment by RomainMazB** [comment]
@LukeTowers I'll do the job.

Already done in my [AdminBar plugin](https://github.com/RomainMazB/octobercms-adminbar/blob/eaf9cb0c1d24c95a85d91be36e2dc0da370b3f3e/components/adminbar/default.htm#L6), guess the same stuff will be ok for you?

**Comment by LukeTowers** [comment]
Works for me

**Comment by RomainMazB** [comment]
@LukeTowers as said on slack, I've been "forced" to do a slightly different way to not be dependent to Twig Extension plugin.
It may exists a better way to do it, let me know if you have a better idea. Let me know!

**Comment by LukeTowers** [comment]
Posted my review @RomainMazB

**Comment by RomainMazB** [comment]
@LukeTowers Done.

**Comment by philip** [comment]
Nice! That was quick :)

**Comment by RomainMazB** [comment]
@philip Welcome to October: the CMS which get you back to the basic quickly :rocket: :smile: 

Feel free to add your idea about [how this link should be named](https://github.com/octobercms/october/pull/5100#issuecomment-636850618).
