### ISSUE TITLE
mediafinder can't upload when present on the CMS controller

### ISSUE THREAD

**Issue by mjauvin** [octobercms/october#5104]
- OctoberCMS Build: 466
- PHP Version: 7.3.18
- Database Engine: MySQL

After upgrading to build 466, when trying to upload a file using the popup created when clicking a field of type mediafinder, the file does not get uploaded:

- click the field to open the media manager
- click on "Upload" button in the top left handside corner of the media manager popup
- select a file to upload
- file does not appear in the uploaded files and cannot be added to the field

On the same installation, if I revert to build 465 everything works as expected.

**Comment by bennothommo** [comment]
@mjauvin Is there any JS errors appearing in console after the upload? Any errors thrown by the AJAX request for uploading the file?

**Comment by LukeTowers** [comment]
Just tested it on Octodock and can't reproduce it: https://a3756e7ed8b7.octodock.com:8443/backend/october/test/countries/update/2#primarytab-content.

**Comment by mjauvin** [comment]
Hey @LukeTowers, I added the following code to October.Test plugin in your octodock instance directly in Plugin.php's boot() method and that triggers the problem:
```
Event::listen('backend.form.extendFields', function ($widget) {
    if (!($widget->getController() instanceof \Cms\Controllers\Index && $widget->model instanceof \Cms\Classes\Page)) {
        return;
    }
    $widget->addTabFields([
        'settings[featured_image]' => [
            'label' => 'Featured Image',
            'type' => 'mediafinder',
            'mode' => 'image',
            'tab' => 'Images',
            'imageWidth' => '400',
            'imageHeight' => '300',
        ],
    ]);
});
```
To reproduce:

- Just open any Cms page (or create a new one)
- click on the "images" tab
- click on "featured_image" field
- click on "upload"

You'll see the file doesn't get added as it does in the Playground Users controller.

**Comment by mjauvin** [comment]
> @mjauvin are there any JS errors appearing in console after the upload? Any errors thrown by the AJAX request for uploading the file?

@bennothommo no errors in JS console, no errors in system.log

**Comment by mjauvin** [comment]
Interesting, the image actually uploads but ends up under the active theme's assets/images folder... how is that even possible?

**Comment by mjauvin** [comment]
Actually, that's in my local install... on the octodock instance reference above, it ends up under the theme's assets folder.

**Comment by LukeTowers** [comment]
@mjauvin thanks for the added info, I've been losing my mind digging deep into the internals for Symfony's UploadedFile. I think I know what the issue is now.
