### ISSUE TITLE
Add support for Coveralls.io

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#5105]
I'm currently working on some big repo's in github and they use the following:

- `Travis`

- `Testrunner`

- `Coveralls`

I find it really useful using these things when submitting pull requests as the pr's get fully tested in real-time!

Each thing does a different task (by the way).

These tools then allow the admins to do LESS WORK - as they don't need to check so much!

It would be really great to add them to this repo! Which would help me writing some future pr's for this project.

I tag some admins to do some research and hopefully add these things to this repo.

@LukeTowers @bennothommo @daftspunk

**Comment by Samuell1** [comment]
Already replaced by github actions, that is faster and better. https://github.com/octobercms/october/pull/4633

**Comment by LukeTowers** [comment]
@ayumi-cloud we already use GitHub Actions to run our automated testing and quality check suite, see https://github.com/octobercms/october/actions?query=workflow%3ATests. We've found that it's much better than Travis for our needs. Testrunner seems specific to a different kind of testing suite, we already have plans to do more functional / UI tests using Laravel Dusk. 

I'm not sure I see the value of Coveralls tbh.

**Comment by bennothommo** [comment]
We've actually tried out a similar app already, Codecov, for coverage reports when we were using Travis. https://codecov.io/gh/octobercms/october

It's a bit out of date now as I haven't ported it across to Actions yet, but shouldn't be too difficult to revive it.

**Comment by ayumi-cloud** [comment]
I give an example:

I create a pr for the new jquery 3.5.1 and upload it to this repo, the following would happen:

- Travis = Test for syntax errors etc.

- Testrunner = Would display any conflicts with the current code in the Travis screen and shows the correct code changes needed in the other files.

- Coveralls = Tests the package size and makes sure I am not making October too large in size etc.

**Comment by ayumi-cloud** [comment]
I really like the `Testrunner` script - it's super useful.

**Comment by ayumi-cloud** [comment]
@LukeTowers 

Sure no problem.

So taking my example of creating an updated jQuery PR. Test Runner would scan the repo for any conflicts and show the following:

![image](https://user-images.githubusercontent.com/57409060/83777777-b66fe580-a681-11ea-8195-cf9e93631028.png)

In the above example it's saying it found a conflict and shows it in the `base` and then shows the correct code change in the `Calculated` section.

Pretty cool stuff and really helps to create the pull requests.

**Comment by LukeTowers** [comment]
@ayumi-cloud 😕 I don't quite understand what it's doing? What does "base" vs "calculated" mean in that context?

**Comment by ayumi-cloud** [comment]
@LukeTowers 

`Base` would mean the original code in the repo.

`Calculated` would mean the suggested code change in the repo.

---

I've been looking deeper into the test runner and I think it only works on test yml files. So maybe can't be added in a nice way into the October repo - I'm kind of in two minds about it.

As you said:

> Testrunner seems specific to a different kind of testing suite, we already have plans to do more functional / UI tests using Laravel Dusk.

Laravel Dusk would be best for the laravel. I was just thinking it would be nice to have something for the `vendor` packages as well.

I can't find much info on Test Runner and a direct link though?

**Comment by ayumi-cloud** [comment]
Maybe my idea is no good, I leave you to decide if you want to close this issue or not?
