### ISSUE TITLE
Backend styles parse CSS calc()

### ISSUE THREAD

**Issue by sqwk** [octobercms/october#5106]
- OctoberCMS Build: 465
- PHP version: 7.2 (Scotchbox Pro 1.5)

### Description:

Using `calc()` as part of the CSS backend styles calculates the value instead of leaving the CSS alone: For example, using `.fr-view { padding-right: calc(100% - 944px); }` to limit the width of the froala editor while keeping the scrollbar at the right ends up as  `.fr-view { padding-right: -844%; }`.

### Steps To Reproduce:
Use the css function `calc()` inside the backend styles over at `Settings > Customise back-end > Styles`.

**Comment by LukeTowers** [comment]
@sqwk this is because the backend styles are parsed with LESS. See https://stackoverflow.com/a/17904128/6652884 for how you can use calc() in LESS without calculating the value instead.
