### ISSUE TITLE
Send button value in AJAX requests

### ISSUE THREAD

**Issue by multiwebinc** [octobercms/october#5107]
I have the following HTML for one of my components:

``` html
<form data-request="onAjaxRequest">
    <button type="submit" name="direction" value="forward">Continue</button>
    <button type="submit" name="direction" value="back">Go back</button>
</form>
```

In the component's `onAjaxRequest() method, I do:

``` php
public function onAjaxRequest()
{
    var_dump(Input::all());
    exit;
}
```
This outputs an empty array:

```
array(0) {
}
```

According to the [`<button>` spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button):

> **value**
Defines the value associated with the button’s name when it’s submitted with the form data. This value is passed to the server in params when the form is submitted.

**Comment by Samuell1** [comment]
Isnt issue that your buttons type is submit but they need to be type `button` ?

**Comment by multiwebinc** [comment]
@Samuell1 Maybe I didn't explain the issue well enough. The issue is that the name/value pair of the submit button are _not_ being sent to the server, but they _should_ be. A `<button type="button">` should not have its value sent to the server, and in fact wouldn't even submit the form at all if pressed.

Here's a quote from the [PR I submitted](https://github.com/octobercms/october/pull/5109):

> For regular, non-AJAX form submissions, if the form is submitted by clicking on a specific submit button, the name/value attributes of that button are sent along with the form data. If the form is submitted without clicking on a submit button (e.g. by pushing enter on an `<input type="text">` field), the name/value pair of the **first** submit button to appear in the DOM are sent. In either case, if there is no `name` attribute, then nothing is added to the form data that sent. 

Currently this is not the behavior in the OctoberCMS AJAX framework.

**Comment by LukeTowers** [comment]
I'm going to mark this as a pending enhancement since the AJAX framework has never behaved this way and we're focusing on getting 466 as stable as possible and then launching the L6 upgrade. Once those are done we can review and implement this.

**Comment by bennothommo** [comment]
Please see https://github.com/octobercms/october/pull/5109#issuecomment-731489631 for the reason we won't implement this at this stage.
