### ISSUE TITLE
Unable to generate links to asset files with twig 

### ISSUE THREAD

**Issue by rvolyar** [octobercms/october#511]
In my assets folder I have a ton of other directories with lots of word docs, pptx's and such.  I could not generate links to those files using the twig `` href="{{ 'assets/~/file.doc' | theme }}" `` filter.  Any ways to fix this?

**Comment by daftspunk** [comment]
Content blocks are deemed for static content only, so Twig is not supported, there is a basic [templating system recently added](http://octobercms.com/docs/cms/content#variables) that may be of assistance.
