### ISSUE TITLE
Usability issues with persisted backend list state

### ISSUE THREAD

**Issue by tobias-kuendig** [octobercms/october#5119]
We often get feedback from customers, that the persisted backend list state is confusing to them. 

I do understand the use-case for it: If you navigate to page 3 of a list and edit a record, you should get back to page 3 of the list after saving.

The confusion arises if you navigate to another Plugin's list and return some minutes later and expect a "fresh list view" but you somehow are still on page 3. Sometimes a user is looking for a recent record and only notices the "old state" of the list after a few moments.

This issue is meant to discuss this. Does anyone else have any feedback on this?

The solution I would like to propose is that the list state gets cleared once the user navigates to a completely different controller in the backend.

**Comment by LukeTowers** [comment]
@tobias-kuendig I think probably a better solution would be making it more obvious to the user that they are not on a clean list state, perhaps some sort of visual indicator or an obvious "reset" button?

**Comment by bennothommo** [comment]
I prefer the state to remain as is, even jumping to different sections, but I'd be up for an option that allows developers to set a list to not keep its state if its likely that people will always want the first page (like, say, a log viewer).

**Comment by daftspunk** [comment]
It seems like this will have to be something configurable in the future. Where the list pager state can either be stored in the session or it can use #hashbangs on the URL where navigating back and forth would retain the state, but traversing through the app would reset back to normal

I agree that the current logic is a bit too sticky and I've been caught out by it a few times. Honestly, I think just using a solid #hashbang/GET var schema will fix the issues. I've made a note to implement this in the platform. If you have any other ideas on how to approach this, let me know and we can revisit

**Comment by linyiman** [comment]
is okd

**Comment by linyiman** [comment]
> We often get feedback from customers, that the persisted backend list state is confusing to them.
> 
> I do understand the use-case for it: If you navigate to page 3 of a list and edit a record, you should get back to page 3 of the list after saving.
> 
> The confusion arises if you navigate to another Plugin's list and return some minutes later and expect a "fresh list view" but you somehow are still on page 3. Sometimes a user is looking for a recent record and only notices the "old state" of the list after a few moments.
> 
> This issue is meant to discuss this. Does anyone else have any feedback on this?
> 
> The solution I would like to propose is that the list state gets cleared once the user navigates to a completely different controller in the backend.

isod

**Comment by daftspunk** [comment]
Reopened this internally, @linyiman. Thanks
