### ISSUE TITLE
Add some UI customizations options to checkboxlist

### ISSUE THREAD

**Issue by RomainMazB** [octobercms/october#5123]
Hi everyone, I've just used widely the checkboxlist widget in a project and faced some "annoying" behaviors which I've fixed locally in my project.

I feel like it could be good to share my work as a PR, but wanted to discuss about it before:

IMHO checkboxlist need some basics "improvements" like the PR I've made previously for the default checked state: #5122 

Today I've faced another example: the checkboxlist actually forces the scrollable state without a regard the inline-options presence when there is more than 10 items in it, this is annoying when used with a many to many relationship: It suddenly renders the list in a different way when added just one item to the list.

What I propose as improvements:

1. Easy set of default state with a "default" option
2. Don't automatically add is-scrollable class when inline-options is present
3. Add limitToScroll option to precise when we want the list to switch to a scrollable behavior

A screenshot where the behavior can be annoying: the two list are rendered with a relationship. The client add 10 items to the first, and 12 to the second and ask me why the list blewed up.
![image](https://user-images.githubusercontent.com/53976837/84290805-79559880-ab44-11ea-82e9-dcd5157083cc.png)

More can be added, such a `liClass` option to set some class to each items.
Example use case: Render in the first list all items with a w-md class so all items would be correctly aligned, even in a `inline-options` list or other list item specific style.

I agree: This kind of little stuff is not useful in most of case and could be done overriding the checkboxlist partial, but it don't cost so much and others field type provide so much options to customize easily which is node feasible with the checkboxlist.

As an example to set a default checked state to all the checkboxes in a many-yo-many checkboxlist: you will need to listen to the form `backend.form.extendFieldsBefore` event to check them dynamically when other fields type just provide a "default" option...

Let me know what's your thoughts :)

EDIT: the talk have started on slack, here is where we've been for now:
![image](https://user-images.githubusercontent.com/53976837/84293453-1960f100-ab48-11ea-8f90-7b7d137e4b2a.png)

**Comment by RomainMazB** [comment]
No answer in 6 months :) I suppose the discussion is closed :)

**Comment by bennothommo** [comment]
@RomainMazB feel free to submit a PR with your suggested changes.
