### ISSUE TITLE
Backend user throttling IPs

### ISSUE THREAD

**Issue by Eoler** [octobercms/october#5128]
- OctoberCMS Build: 466
- PHP Version: 7.3
- Database Engine: MariaDB 10.2
- Apache Apache 2.4.29 on Ubuntu 18.04 LTS

### Description:
Noticed while migrating (diffing) DB from development version on edge build 466 that every new entry in `backend_user_throttle` table has IP value of `0.0.0.0` (a single new entry for each backend user). OctoberCMS build 465 logs backend user's IPs correctly on same server and (sub)domain.

Config.Auth settings:
```
    'throttle' => [
        'enabled' => true,
        'attemptLimit' => 3,
        'suspensionTime' => 30,
    ],
```

**Comment by bennothommo** [comment]
@Eoler are you using a hosting setup that doesn't pass IP addresses through (like through a proxy)? The only time throttle attempts should be recorded is when the data is saved through October, not if you migrate data to the database directly.

**Comment by Eoler** [comment]
> @Eoler are you using a hosting setup that doesn't pass IP addresses through (like through a proxy)? 

No, build 465 on same VPS/domain (production subdomain) regularly writes IP addresses to `backend_user_throttle` table.

> The only time throttle attempts should be recorded is when the data is saved through October, not if you migrate data to the database directly.

Of course. Tested by upgrading another installation on same VPS from 465 to 466 edge build and it started writing zero IPv4s for backend user throttling. I know you're all running on composer installations, but it's very probable that the problem started with this change:  
`Added auth.throttle.* configuration options to configure the login throttling for the backend.`

**Comment by LukeTowers** [comment]
@Eoler can you `dd(Request::ip())` in one of those installs and tell us if you're getting the IP address? I'm not seeing the behavior on any of my sites running the L6 build (which includes the latest develop changes). The change you're talking about didn't touch anything to do with the IP address: https://github.com/octobercms/october/commit/6c391b5e82f7040d67032dc911df5eef0e2bda42

**Comment by Eoler** [comment]
> can you `dd(Request::ip())` in one of those installs and tell us if you're getting the IP address? 

@LukeTowers works fine, writes IPv4 to `backend_access_log`
A true mystery...

**Comment by LukeTowers** [comment]
I don't understand. Is it working in 466 now?

**Comment by Eoler** [comment]
> I don't understand. Is it working in 466 now?

Access log works, user throttle saves `0.0.0.0` IPv4:
![BackendUsers-throttle](https://user-images.githubusercontent.com/680032/84871140-7137b480-b080-11ea-9ae7-08cf08466564.png)

**Comment by LukeTowers** [comment]
@Eoler if you dd() here: https://github.com/octobercms/library/blob/develop/src/Auth/Manager.php#L75 what does that get? Perhaps something changed in the Laravel internals that breaks it if it's called too early in request?

**Comment by Eoler** [comment]
> if you dd() here: https://github.com/octobercms/library/blob/develop/src/Auth/Manager.php#L75 what does that get? 

@LukeTowers  is this in `/vendor/october/rain/src/Auth/Manager.php` ?
Not getting any hits for that line (even after clearing framework and other caches) on backend login.

**Comment by Samuell1** [comment]
@Eoler Did you run composer again after migrating?

**Comment by Eoler** [comment]
> Did you run composer again after migrating?

@Samuell1 I'm not on a composer installation, running 466 edge build.

**Comment by Samuell1** [comment]
@Eoler then something didnt update when you have this old file.

**Comment by LukeTowers** [comment]
@Eoler are you using any plugins that replace the default backend authentication mechanism?

**Comment by Eoler** [comment]
> are you using any plugins that replace the default backend authentication mechanism?

No @LukeTowers , I've tried 466 build on third installation (completely different server) without common plugins - problem stays the same.
