### ISSUE TITLE
User avatar is not right aligned after upgrading OctoberCMS to version 465

### ISSUE THREAD

**Issue by goldmont** [octobercms/october#5130]
- OctoberCMS Build: 465 (php artisan october:util set build)
- PHP Version: 7.2
- Database Engine: MySQL
- Plugins Installed: RainLab.Builder

### Description:
Hi,

after upgrading to version 465, User avatar CSS is not working properly. As you can see from the screenshot attached below, the avatar is not right-aligned; instead, the dropdown, appears exactly where it should be. Is there a solution? Thanks.

<img width="1680" alt="Screenshot 2020-06-16 at 23 20 11" src="https://user-images.githubusercontent.com/6855692/84829635-5d606400-b028-11ea-9a0f-06dfb8604eff.png">

**Comment by LukeTowers** [comment]
@goldmont you need to clear your browser cache / any CDN cache if present, there was a change that made the alignment happen through CSS instead of JS which improved the rendering of that, but only takes affect if you actually get the updated CSS files in your browser.

**Comment by goldmont** [comment]
Solved. Thank you man.
