### ISSUE TITLE
List filter type group doesn't work with large amounts

### ISSUE THREAD

**Issue by Klaasie** [octobercms/october#5140]
- OctoberCMS Build: 466
- PHP Version: ^7.2
- Database Engine: Mysql MariaDB 10.3.23

### Description:
The issue is that when using the list filter group the filter might actually not work (silently fail) when dealing with more than 500 records.

This happens because: `max_input_vars` defaults to 1000
And: available options are being posted to the filter widget along with the selected data.

For every option 2 values are posted (id and name). so 500 options results into 1000 variables being posted.
When looking into the method handling the post data `onFilterUpdate` I don't see a reason why the available options are posted in first place.

I'm aware that one fix would be to up the amount of `max_input_vars` but that might not turn out to be a permanent solution.

On the other hand I think it's rather unlikely a user decides to select 500+ options from the filter. So my proposed solution would be to leave the available options out of the post data. Unless there is another reason for them to be there?

P.s. I'm aware that this issue has been raised multiple times (https://github.com/octobercms/october/issues/4592, https://github.com/octobercms/october/issues/2602, https://github.com/octobercms/october/issues/3202)

### Steps To Reproduce:
Create a model with list view
Seed 500 records
use the model in a group filter type

**Comment by LukeTowers** [comment]
Closing in favour of #3202. This is a known issue and one we plan on addressing at some point, we're just busy with other things at the moment. If you'd like to take a stab at implementing a fix in a PR I'd be happy to review it.

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/517c588ef7224941af761ba4df4f329dd0a442db
