### ISSUE TITLE
Can not fork any component anymore as controller/index.php line 406 is null

### ISSUE THREAD

**Issue by qroft** [octobercms/october#5142]
**Summary**
When i drag and drop a component onto a page and want to fork said component, an error alert pops up.

**Reproduce steps**
Drag a component onto a page. Click on component and then the fork icon.

**Expected behavior**
OctoberCMS should convert the twig tag into html code.

**Actual behavior**
"Call to a member function getContent() on null" on line 406 of /mnt/webxxxxxxx/htdocs/octobercms_shop/modules/cms/controllers/Index.php

I found an entry on the web mentioning that component folders should not have capital letters in them.
I checked the plugin folder and went to every plugin - they are not capitalized.

**Comment by LukeTowers** [comment]
@qroft what version of October are you running?

**Comment by 4nik3t** [comment]
Hello @LukeTowers  I had this same issue when using the forum plugin rainlab/forum-plugin/#141. It happens when the components do not have any template files (i.e without default.htm)

**Comment by LukeTowers** [comment]
I see the problem, will push a fix.

**Comment by qroft** [comment]
Thanks Luke.
One question about these procedure: i am playing around with Shopaholic and at the moment can not use it due to this bug at the current version that i am using.

I am sure that a solution for me would be to download the proper branch from Github and upload it to my server.
I also know that this can have certain risks.

But is there any other waz that allows me to use the component or to find out what component is causing the problem?
I checked the Log files from within the backend and could not find out the culpid component.

**Comment by LukeTowers** [comment]
@qroft the problem only happens when you try to fork a specific component correct? The problem is with that specific component. The "forking" feature only automatically works with components that supply a `default` partial. If they don't then it doesn't work because there's nothing to pull from.

**Comment by qroft** [comment]
> @qroft the problem only happens when you try to fork a specific component correct? The problem is with that specific component. The "forking" feature only automatically works with components that supply a `default` partial. If they don't then it doesn't work because there's nothing to pull from.

Unfortunately no. I simply undeleted the Lovata Shopaholic plugin as i thought that it caused the problem.
But even now, it does not matter what component i pull over, i get the same information of a default partial not set up.

I will download now the DEV branch and upload it to my server to see if it works afterwards.

**Comment by qroft** [comment]
So i uploaded the DEV branch to my server and it does not matter what component i try to fork, i get this info:
"This component does not have a 'default' partial"

**Comment by LukeTowers** [comment]
@qroft it sounds like it might be a permissions error, does the PHP server have access to the relevant partial file?
