### ISSUE TITLE
HtmlBuilder::limit fails with umlauts

### ISSUE THREAD

**Issue by tobias-kuendig** [octobercms/october#5153]
When passing a string to HtmlBuilder::limit that includes umlauts, the string encoding somehow gets messed up. The following test case fails: https://github.com/OFFLINE-GmbH/library/commit/dbaff8e164f5b081e03b72e1e12c4b9f4c72cb36

``` php
public function testLimitEncoding()
{
    $result = with(new HtmlBuilder)->limit('<p>Er hörte leise Schritte hinter sich. Das bedeutete nichts Gutes.</p>', 10);
    $this->assertEquals('<p>Er hörte l...</p>', $result);
}
```

Expected output is 

```
<p>Er hörte l...</p>
```

Received output is

```
<p>Er hö�te l...</p>
```

**Comment by LukeTowers** [comment]
@tobias-kuendig did this ever get fixed?

**Comment by tobias-kuendig** [comment]
It did not! I might find some time next week and see if I can still reproduce this issue and implement a fix.

**Comment by tobias-kuendig** [comment]
It looks like this issue is no longer present. The test passes now without any changes. Let me know if you want a PR with the test:

https://github.com/OFFLINE-GmbH/library/commit/9fb0730579a2df0629cb6d3fe803466eb0d0311e

**Comment by LukeTowers** [comment]
@tobias-kuendig sure, can't hurt
