### ISSUE TITLE
October stops working after cache clear from backend - restrict-api / opcache

### ISSUE THREAD

**Issue by jostos** [octobercms/october#5194]
Looks like that i was also lucky one experiencing the issue with OPCache and restric_api 

This issue is coming together with all of this looks like 

After i do some edit or change in the files (in the backend) and save it - sometimes it goes trough and sometimes not 

The only solution to see the changes is to clear the cache from backend widget - 
After i do it - page and October is not reachable and I'm attaching screenshot what is the error/issue image - > 
![iss](https://user-images.githubusercontent.com/6843110/86286817-76037900-bbe7-11ea-9293-e80c8d718b44.jpg)

Most of the time when im doing changes to page 
1. cache is not showing the change 
2. im getting restrict_api error window 
3. it goes trough and i can see the change 
4. i need to clear the cache from backend 

so in nutshell - 
1. i dont have http cache in provider enabled - it is disabled 
2. im always editing files or code via october and then saving it - reloading page 
3. i already tried and visited this other issues - > 
> Duplicate of #3468, #3438, #3664.
4. and also tried to change the code - 
> https://github.com/octobercms/october/pull/3468/commits/2aa7bea23df570505afcf39492606eb01bff1c0e""

**Comment by jostos** [comment]
Also after i do some change to code i need to go trough couple of page refreshes with errors like this - > 
![iss2](https://user-images.githubusercontent.com/6843110/86287309-46a13c00-bbe8-11ea-8902-02e3bad07de0.jpg)

**Comment by LukeTowers** [comment]
Sounds like problems with server permissions. Do those files exist when you browse the filesystem?

**Comment by jostos** [comment]
Im not sure if i understand, the permissions on files on FTP are 755 for everything looks like 
The files that im editing are on the FTP as well and im able to reach them and edit them via October backend 
Sorry looks like i might be wrong or no idea what you are asking :D

**Comment by LukeTowers** [comment]
@jostos does this happen on any other server you use? Or locally? Without more information and the ability to replicate the issue there's not much we can do.

**Comment by jostos** [comment]
There are couple circumstances that it happens which im not familar with 
for now it is like this - 
1. i edit code -save it 
2. i get issue in my 2nd comment 
3. wait OR refrsh page till i go trough all errors from restric/opcache i dont know 
4. change is on the server 

5. or the change goes trough - 1 from 10 tries 

so i dont know what is wrong

**Comment by bennothommo** [comment]
@jostos What are your `opcache` settings in your `php.ini` config?

**Comment by jostos** [comment]
I'm a little bit lost in this stuff - where i can find php.ini?

**Comment by bennothommo** [comment]
@jostos might be easier to just do a `<?php phpinfo(); ?>` in a file on your webhost somewhere and access that via your browser - that'll show the `opcache` configuration.

**Comment by jostos** [comment]
Opcode Caching | Up and Running
-- | --
Optimization | Enabled
SHM Cache | Enabled
File Cache | Disabled
Startup | OK
Shared memory model | mmap
Cache hits | 1325830153
Cache misses | 167841
Used memory | 3944096024
Free memory | 6314066600
Wasted memory | 479255616
Interned Strings Used memory | 133278552
Interned Strings Free memory | 202265344
Cached scripts | 145045
Cached keys | 145045
Max keys | 524521
OOM restarts | 0
Hash keys restarts | 0
Manual restarts | 0


Directive | Local Value | Master Value
-- | -- | --
opcache.blacklist_filename | /etc/opcache_blacklist | /etc/opcache_blacklist
opcache.consistency_checks | 0 | 0
opcache.dups_fix | Off | Off
opcache.enable | On | On
opcache.enable_cli | Off | Off
opcache.enable_file_override | On | On
opcache.error_log | /var/log/opcache_log | /var/log/opcache_log
opcache.file_cache | no value | no value
opcache.file_cache_consistency_checks | 1 | 1
opcache.file_cache_only | 0 | 0
opcache.file_update_protection | 2 | 2
opcache.force_restart_timeout | 60 | 60
opcache.huge_code_pages | Off | Off
opcache.interned_strings_buffer | 384 | 384
opcache.lockfile_path | /tmp | /tmp
opcache.log_verbosity_level | 2 | 2
opcache.max_accelerated_files | 450000 | 450000
opcache.max_file_size | 131072 | 131072
opcache.max_wasted_percentage | 50 | 50
opcache.memory_consumption | 10240 | 10240
opcache.opt_debug_level | 0 | 0
opcache.optimization_level | 0x7FFEBFFF | 0x7FFEBFFF
opcache.preferred_memory_model | no value | no value
opcache.protect_memory | 0 | 0
opcache.restrict_api | /data/web/nonexist | /data/web/nonexist
opcache.revalidate_freq | 30 | 30
opcache.revalidate_path | On | On
opcache.save_comments | 1 | 1
opcache.use_cwd | On | On
opcache.validate_permission | On | On
opcache.validate_root | Off | Off
opcache.validate_timestamps | On | On

**Comment by Samuell1** [comment]
https://github.com/octobercms/october/issues/1250 Similar issue before somewhere in code is missing some statement to skip cache if doesnt exists

**Comment by bennothommo** [comment]
There's two potential sources for this issue:

- You have `opcache.revalidate_freq` set to 30, which means there's 30 seconds where the OPCache will not revalidate a file and check if it's updated, which could potentially cause said issue. You can try setting this to `2` in your `php.ini` settings.
- It appears you are using an NFS drive, which could be introducing delays between when the cache is written and when it is available. You could potentially use an external cache for this, although I believe CMS cache files are still stored locally.

Have a try at either of those suggestions and see if that alleviates the issue.
