### ISSUE TITLE
Backend Date/DateRange list filter 'ignoreTimezone' does not work

### ISSUE THREAD

**Issue by rgsone** [octobercms/october#5197]
- OctoberCMS Build: 466
- PHP Version: 7.2+

### Description:
When i set `ignoreTimezone: true` with date type scope in my filter definition, the `ignoreTimezone` is not applied.
After digging in OC modules i found incorrect php opening tag in `modules/backend/widgets/filter/partials/_scope_date.htm` and `modules/backend/widgets/filter/partials/_scope_daterange.htm`.
The tag is `<?php` instead of `<?=`.
After correcting this in my local installation, evering works correctly.

Thank you.

**Comment by LukeTowers** [comment]
@rgsone could you submit a PR? @LarryBarker could you confirm this?
