### ISSUE TITLE
Problem if combine letter "a" with single other character in slug

### ISSUE THREAD

**Issue by RodrigoGalter** [octobercms/october#5203]
- OctoberCMS Build: 467
- PHP Version: 7.3.19

### Description:
When trying to use a letter "a" the slug is not formed, and the next following letter of "a" is also not considered for the slug, only after the third letter that the slug begins to be formed.

### Steps To Reproduce:
Configure the slug to use the preset of the field that will mirror, and use the letter "a" alone or followed by another letter, add a third to work correctly.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2292422/86959604-798d8780-c134-11ea-9408-417d98c12d10.gif)

**Comment by LukeTowers** [comment]
This is done on purpose, the concept is called "stop words". See https://github.com/octobercms/october/blob/develop/modules/system/assets/ui/js/input.preset.js#L163 for the full list of words removed by default.

**Comment by RodrigoGalter** [comment]
but there are situations that I need the combination "AT", is there a way to remove some letters from the list as my need?
In my case in portuguese I have a title "Alta tensão (AT)", in this case I can not generate a complete slug for this title.

**Comment by LukeTowers** [comment]
@RodrigoGalter you should be able to use the `data-input-preset-remove-words="false"` option to prevent it from removing stop words:

```
slug:
    label: slug
    preset:
        field: title
        type: slug
    attributes:
        'data-input-preset-remove-words': 'false'
```
