### ISSUE TITLE
Problems with mediafinder generated links on October installed on subfolder after update to build 467

### ISSUE THREAD

**Issue by fgschafer** [octobercms/october#5204]
I noticed that after updating to build 467, the mediafinder generated links don't work unless the link policy is set to "force" if October is installed in a subfolder.  It would be nice to have proper support for relative links in this situation too.

**Comment by LukeTowers** [comment]
@fgschafer I've added a note to the config file about how to properly handle this: https://github.com/octobercms/october/commit/5a5208bd0b75c411840d4246bd5b3df427005ced

**Comment by adrian-stein** [comment]
I second this. Any word on a permanent fix?

**Comment by bennothommo** [comment]
@adrian-stein you'll need to follow @LukeTowers notes and adjust your configuration accordingly.

**Comment by LukeTowers** [comment]
@fgschafer @adrian-stein does it work if you set your app.url to correctly include the subfolder and leave the uploads and media URLs unchanged?

**Comment by fgschafer** [comment]
Indeed the initial issue that motivated that comment in the documentation was that the thumbnail previews on the backend mediafinder widget were not working WITH the app_url set WITH the subfolder and link policy left on the default (detect).  The subfolder was missing in the url of the image preview.

**Comment by bennothommo** [comment]
@fgschafer Thanks for clarifying, but I did not encounter that issue in the scenario you stated. The image preview appeared just fine for me.

**Comment by fgschafer** [comment]
@bennothommo thenks for your answer.  The one is not working is this:
In a custom plugin:
`public function boot()
    {
        // Extend all backend form usage
        Event::listen('backend.form.extendFields', function ($form) {

            // Only for the CMS Index controller
            if (!$form->getController() instanceof \Cms\Controllers\Index) {
                return;
            }

            // Only for the Page model
            if (!$form->model instanceof \Cms\Classes\Page) {
                return;
            }

            // Add custom fields...
            $form->addTabFields([
                'settings[featured_image]' => [
                    'label'   => 'Imagen Predefinida',
                    'type'    => 'Backend\FormWidgets\mediafinder',
                    'mode'    => 'image',
                    'imageWidth' => '200',
                    'tab'     => 'cms::lang.editor.meta'
                ]
               
            ]);
        });
    }`

**Comment by fgschafer** [comment]
@bennothommo Thanks.  The issue is for example here.  
In a custom plugin boot method:

```
           Event::listen(\'backend.form.extendFields', function ($form) {

            if (!$form->getController() instanceof \Cms\Controllers\Index) {
                return;
            }
        
            if (!$form->model instanceof \Cms\Classes\Page) {
                return;
            }

            $form->addTabFields([
                'settings[featured_image]' => [
                    'label'   => 'Imagen Predefinida',
                    'type'    => 'Backend\FormWidgets\mediafinder',
                    'mode'    => 'image',
                    'imageWidth' => '200',
                    'tab'     => 'cms::lang.editor.meta'
                ]
               
            ]);
        });
```

**Comment by adrian-stein** [comment]
I have changed the 'linkPolicy' to be 'force' and left the media_path and uploads_path and app.url untouched and it works.
