### ISSUE TITLE
Soft deleting relations does not soft delete records from the pivot table

### ISSUE THREAD

**Issue by igor-tv** [octobercms/october#5207]
- OctoberCMS Build: 465
- PHP Version: 7.4.6
- Database Engine: MySQL

### Description:
If I delete a model record that has belongsToMany relationship, the related records in the pivot table are not marked deleted.

### Steps To Reproduce:

1. Create model witch belongsToMany relation:
```
class MyModel extends Model
{
    use \October\Rain\Database\Traits\SoftDelete;
    public $table = 'myvendor_myplugin_mymodel';
    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    public $belongsToMany = [
        'users' => [
            User::class,
            'table' => 'vendor_plugin_mymodels_users',
            'timestamps' => true,
            'order' => 'name',
            'softDelete' => true
        ],
    ];
}
```
table 'vendor_plugin_mymodels_users'
`id | name | reated_at | updated_at | deleted_at
`
```
class MyModelUser extends Model
{
    use \October\Rain\Database\Traits\SoftDelete;
    public $table = 'myvendor_myplugin_mymodels_users';
    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    public $belongsTo = [
        'mymodel' => MyModel::class,
    ];
}
```
pivot table 'myvendor_myplugin_mymodels_users'
`id | mymodel_id | user_id | created_at | updated_at | deleted_at
`

2. Set up a Relation Behavior Config to manage users in MyModel.
3. Create new MyModel record.
4. Attach user to created record.
5. Delete created record from backend.
6. Check `myvendor_myplugin_mymodels_users` table, record which deleted `mymodel_id` has null value in `deleted_at` instead of date.

**Comment by bennothommo** [comment]
@igor-tv What is the `User` model that the `MyModel` model in your example is related to? Is that supposed to be `MyModelUser` to match your example?

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.
