### ISSUE TITLE
CMS section loading blank code editor and can't close the tab bug

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#5211]
- OctoberCMS Build: 467
- PHP Version: 7.3.19
- Database Engine: MySQL
- Plugins Installed: n/a

### Description:
When opening several files in the cms section, we have seen the cms crash and display a white screen. The file then can not be deleted and the page needs to be refreshed. This has happen a dozen times today from different computers in the office and this only started after updating the cms from 466 to 467.

See screenshot:

![image](https://user-images.githubusercontent.com/57409060/87477045-56c10e80-c61f-11ea-8ca1-413a819e25a2.png)

### Steps To Reproduce:

We been discussing this all day in the office and have no idea what to suggest to reproduce this error! Hopefully other people will start having the same issue!

We are getting this error in the following browser: Google Canary Version 86.0.4197.0 (Official Build) canary (64-bit)

Though it might happen in other browsers as we haven't tested the cms out.

Reporting this bug as we've seen it a dozen times since updating cms today!

> Bug is intermittent!

**Comment by LukeTowers** [comment]
Please post the error log and stack trace from your browser's developer console.

**Comment by ayumi-cloud** [comment]
The error log in the settings section in the cms and the dev tools console log screen were both not showing any errors, every time the error occured.

**Comment by LukeTowers** [comment]
There should definitely be something in the browser dev tools when the issue occurs, whether that's a failed network request or a breaking error in JS

**Comment by ayumi-cloud** [comment]
@LukeTowers we were not seeing any notification of an issue at all. Since updating Google Canary, all of yesterday we didn't see this issue. There may a chance it was a bug in the browser? If we come across this again we will investigate and update this post - sorry to not be able to add some error log or stack trace right now.

**Comment by ayumi-cloud** [comment]
@LukeTowers going to close this issue hasn't come up in the office - we strongly believe it was a rendering issue with the canary browser.
