### ISSUE TITLE
Switch ar locale to use ar-ly for moment.js localization

### ISSUE THREAD

**Issue by tamer-hassan** [octobercms/october#5213]
Briefly, asset js localizes arabic numbers to indic numbers, causing issue with DateTime helper and SQL when submitting dates in forms.

To quote from 7 Nov. 2018 comment by Ghost: 
https://github.com/octobercms/october/issues/3808#issuecomment-436427220

> @MWalid Yah that makes sense, I see what you are saying. So use Arab writing for everything except numbers.
> 
> @LukeTowers Permission to change the file code at location: https://github.com/octobercms/october/blob/master/modules/system/assets/js/lang/lang.ar.js
> 
> And add the commit code I already have done: https://github.com/octobercms/october/blob/21bd7351a2bac1bad0e7a275260c627b250ad88d/modules/system/assets/ui/vendor/moment/locale/ar-ly.js
> 
> This should then fix this issue. Can update the PR if you give this the green light.
> 
> Please see PR commit: [8c4bd7d](https://github.com/octobercms/october/commit/8c4bd7d3ffc52d339ba83979419c78abdabd2199)

I had to manually reapply the above mentioned commit changes to fix..

**Comment by LukeTowers** [comment]
Need to swap out https://github.com/octobercms/october/blob/develop/modules/system/assets/ui/vendor/moment/locale/ar.js symbolMap section with https://github.com/octobercms/october/blob/develop/modules/system/assets/ui/vendor/moment/locale/ar-ly.js and then run `php artisan october:util compile lang`
