### ISSUE TITLE
How to prevent line endings from changing?

### ISSUE THREAD

**Issue by xitara** [octobercms/october#5216]
- OctoberCMS Build: 465
- PHP Version: 7.3.20 fpm (debian/buster)
- Database Engine: mariadb
- Plugins Installed: demo

### Description:
if I edit a file in backend/cms, it will be saved with windows-line endings
on edit just one line in an external editor (sublime text 3 in my case) the full file will be marked as changed in git (sublime merge)

I think, the backend-editor should be use the system-lineendings or, even better, unix-lineendings 'cause most of websites runs on non-windows

perfekt: an option to chose the lineendings I want.

![Bildschirmfoto_2020-07-16_15-45-49](https://user-images.githubusercontent.com/26457767/87678897-c9df9780-c77b-11ea-86e2-120201129614.png)

**Comment by LukeTowers** [comment]
@xitara see `cms.convertLineEndings` in config/cms.php. I believe it's actually you using a browser on Windows that causes the problem, so just enable that setting and you should be good to go.

**Comment by xitara** [comment]
My browser runs on linux (chrome) but I test this option.

October is the best CMS I ever used :)
Thank you
