### ISSUE TITLE
Model firstOrFail does not fail

### ISSUE THREAD

**Issue by marcbrouwertue** [octobercms/october#5218]
When calling Model::where('someVarChar', false)->firstOrFail() returns the first item rather than failing, also the use of ->first() leads to incorrect results if the item does not exist

**Comment by LukeTowers** [comment]
What version are you using? I do not experience that happening.

**Comment by marcbrouwertue** [comment]
It works fine on build 465, but after the update to 467 it does not work correctly anymore so the issue is either in 466 or 467

**Comment by LukeTowers** [comment]
Just tested it on https://09fee74e8a4f.octodock.com/backend and it worked perfectly fine. Please show your exact code and the database table in question.

**Comment by marcbrouwertue** [comment]
@LukeTowers as far as I can see, your model is not found. Could you try this on an existing model with an existing column?

**Comment by LukeTowers** [comment]
What database driver are you using @marcbrouwertue?

**Comment by marcbrouwertue** [comment]
@LukeTowers 

        'mysql' => [
            'driver'    => 'mysql',
            'host'      => 'localhost',
            'port'      => 3306,
            'database'  => '*****',
            'username'  => '*****',
            'password'  => '*****',
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => '',
        ],

**Comment by LukeTowers** [comment]
This is a complex case. 

In order to aid in our understanding of the problem, please submit [a Pull Request to the test plugin](https://github.com/octoberrain/oc-test-plugin) for investigation that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it _using the test plugin_.
