### ISSUE TITLE
How to remove theme dependencies on the market page?

### ISSUE THREAD

**Issue by pkurg** [octobercms/october#5219]
https://octobercms.com/theme/pkurg-appco-october

The theme was originally loaded with this theme.yaml

```
name: 'October Appco'
description: 'Simple Responsive Bootstrap 4 HTML5 Theme'
author: Vladimir
code: appco-october
require:
    - Pkurg.BootstrapPageBuilder

```
But the dependence turned out to be unnecessary.

I updated my theme with new theme.yaml

```
name: 'October Appco'
description: 'Simple Responsive Bootstrap 4 HTML5 Theme'
author: Vladimir
code: appco-october

```
But the dependence remained on the theme page . https://octobercms.com/theme/pkurg-appco-october

How to remove it?

pkurg@pkurg.ru

**Comment by LukeTowers** [comment]
Send an email to hello@octobercms.com
