### ISSUE TITLE
Session put doesn't work in Ajax handlers

### ISSUE THREAD

**Issue by mabehiry** [octobercms/october#5221]
- OctoberCMS Build: ### 467
- PHP Version: 7.2
- Database Engine: MySQL
- Plugins Installed: 

### Description:
I cannot write session values in Ajax handlers, although I can read the values.

### Steps To Reproduce:
public function onSend()
{
    Session::put('item', 'value');
}

public function test()
{
    echo Session::get('item'); // doesn't get any result
}

**Comment by LukeTowers** [comment]
@mabehiry I was unable to replicate this. Where are these AJAX handlers located, and are you absolutely sure they're actually being called?

```
title = "test"
url = "/test"
layout="default"
is_hidden = 0
==
<?php
function onStart() {
    if (!empty(Session::get('item'))) {
        dd(Session::get('item'));
    }
}
function onSearch()
{
    Session::put('item', input('query'));
    return Redirect::refresh();
}
?>
==
<form>
    <input name="query">
    <button data-request="onSearch">Search</button>
</form>
```

**Comment by mabehiry** [comment]
You're right. It was a bug in my code! 
Sorry for that
