### ISSUE TITLE
Site Breaking Bug affecting "stringList" and "text" properties

### ISSUE THREAD

**Issue by SplicedWeb** [octobercms/october#5222]
- OctoberCMS Build: 467 
- PHP Version: 7.1 & 7.3.1
- Database Engine: mySQL
- Plugins Installed: October.Demo, Martin.Forms

### Description:
Upgrading from Build 465 to 467 caused some components to no longer allow saving settings when the property type is "stringList" or "text".

In the magic forms plugin for example, when editing "Security" > "Allowed Fields" when values already existed, you can see the values but cannot remove/change and save. (ok and cancel buttons missing from modal).
[Screenshot](https://www.screencast.com/t/ECV8q76e)

If the field was empty, you can now see html in the modal - but you cannot remove it and save correct values.
[Screenshot](https://www.screencast.com/t/6ijEdQXGejg)

This has happened on two different sites so far, on two different servers
One running php 7.1 another running php 7.3.11

This effectively breaks a sites functionality as forms are potentially disabled/broken/cannot be set up and has the potential to break thousands of sites with magicForms showing 24247 installations as of today

### Steps To Reproduce:
Install octobercms build 467
Install magic forms plugin 
Create new theme and activate it.
Create cms layout 
Insert magic forms component "genericForm" to layout and begin to modify settings.
Properties with type "text" or "stringList" will be broken, not allowing for modal to be saved and should contain some html (essentially the bottom of the modal is showing within the input).
eg. "Notifications Settings > Recipients", "Notifications Settings > BCC" are stringList type
"More Settings > Js on Success" is a text type.

**Comment by bennothommo** [comment]
Thanks for letting us know @SplicedWeb - seems to be some broken HTML at work. Having a look now.
