### ISSUE TITLE
EncryptCookies middleware bug: ErrorException: substr() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by robinbonnes** [octobercms/october#5226]
- OctoberCMS Build: 468
- PHP Version: 7.3.17
- Database Engine: 5.5.41-MariaDB

### Description:
After executing the edge update, it runs into the following issue when signing in into the backend:

```
ErrorException: substr() expects parameter 1 to be string, array given in /public_html/website/vendor/laravel/framework/src/Illuminate/Support/Str.php:469
#0
[internal function]:
Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'substr() expect...', '/...', 469, Array)
#1
/public_html/website/vendor/laravel/framework/src/Illuminate/Support/Str.php(469):
substr(Array, 0, 41)
#2
/public_html/website/vendor/laravel/framework/src/Illuminate/Support/helpers.php(806):
Illuminate\Support\Str::startsWith(Array, 'aff311533bf11c2...')
#3
/public_html/website/vendor/october/rain/src/Cookie/CookieValuePrefix.php(42):
starts_with(Array, 'aff311533bf11c2...')
#4
/public_html/website/vendor/october/rain/src/Cookie/Middleware/EncryptCookies.php(84):
October\Rain\Cookie\CookieValuePrefix::getVerifiedValue('admin_auth', Array, 'CMy5qL9cabHNXJr...')
#5
/public_html/website/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66):
October\Rain\Cookie\Middleware\EncryptCookies->decrypt(Object(Illuminate\Http\Request))
#6
/public_html/website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149):
Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#7
/public_html/website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8
/public_html/website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9
/public_html/website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660):
Illuminate\Pipeline\Pipeline->then(Object(Closure))
#10
/public_html/website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635):
Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#11
/public_html/website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601):
Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#12
/public_html/website/vendor/october/rain/src/Router/CoreRouter.php(20):
Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13
/public_html/website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176):
October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#14
/public_html/website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30):
Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#15
/public_html/website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149):
RobinsCMS\Hours\Middleware\MultiTenancy->handle(Object(Illuminate\Http\Request), Object(Closure))
#16
/public_html/website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17
/public_html/website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18
/public_html/website/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(25):
Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#19
/public_html/website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149):
October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#20
/public_html/website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21
/public_html/website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22
/public_html/website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151):
Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23
/public_html/website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116):
Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#24
/public_html/website/index.php(43):
Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#25
{main}
```

### Steps To Reproduce:
It's hard to reproduce myself, because I didn't had any cookies set for this backend. However it seems once you have cookies set and try to sign in after the update, the error occurs.

**Comment by bennothommo** [comment]
@robinbonnes Would you mind clearing the cookies for the site again and give it another try? It seems strange as it appears the cookie has already been decrypted and parsed before it hits our value check.

Does your `RobinsCMS\Hours\Middleware\MultiTenancy` middleware interact with the cookies at all?

**Comment by robinbonnes** [comment]
I just checked, it can't be the middleware because most of that code gets skipped. I suggested the client to clear the cookies. Probably it will work, because it doesn't happen when I login. Will let you know.

However, sooner or later I have to update about 40+ installs, so it would be a no-go to suggest all clients to delete their cookies after the update. Will try to reproduce myself.

Thanks for your help! 👍

**Comment by LukeTowers** [comment]
@robinbonnes what version of October did you upgrade from?

**Comment by bennothommo** [comment]
@robinbonnes The security fix is supposed to invalidate all previous cookies, so realistically, the clients shouldn't have to delete the cookies. If you are able to provide some reproducible steps when you can, that would be awesome.

**Comment by robinbonnes** [comment]
> @robinbonnes what version of October did you upgrade from?

467

> @robinbonnes The security fix is supposed to invalidate all previous cookies, so realistically, the clients shouldn't have to delete the cookies. If you are able to provide some reproducible steps when you can, that would be awesome.

This is how to reproduce the update failure:
1. Sign in to the backend.
2. Hit Settings -> Update (467 -> 468).
3. It gives error:
![image](https://user-images.githubusercontent.com/5117166/88900420-a45c8e80-d24f-11ea-8807-47f45dc35319.png)
(Update failed, access denied)
4. Try again doesn't work. When I refresh the page, I have to login.
5. Once logged in again, Settings -> Update still says version 467.
6. When I retry the update it is successful (468).

I think my cookies do get reset, however from other backend users maybe not?

**Comment by LukeTowers** [comment]
@bennothommo i think he might have cookies from before the last fix that stopped serializing the cookies.

**Comment by LukeTowers** [comment]
Hmm, that's very odd. What session driver are you using?

**Comment by robinbonnes** [comment]
> Hmm, that's very odd. What session driver are you using?

Just the default one, `file`? 

I wonder if you guys, or maybe someone else, has to do the same steps when updating from 467 -> 468. And if they get the same login error.

Will try the following:
PC 1 + backend user 1: Login on 467 backend (set cookies)
PC 2 + backend user 2: Login on 467 backend (set cookies)
PC 1 + backend user 1: Update to 468.
PC 2 + backend user 2: Try to login on 468 without error

**Comment by LukeTowers** [comment]
Another thing to check is if you have manually overridden `October\Rain\Cookie\Middleware\EncryptCookies::$serialize` or `Illuminate\Cookie\Middleware\EncryptCookies::$serialize` to force allow serialization of cookies, which would also cause this behaviour.

**Comment by LukeTowers** [comment]
https://github.com/octobercms/library/commit/09896978bd8b09aac20a8da70ac93c2617afa03c should fix this issue for you, although I was entirely unable to replicate your original issue, even after I tried manually force the middleware to generate serialized cookies.

**Comment by Teranode** [comment]
@LukeTowers try to push this for wip-laravel6 cause im getting this error for that branch but instead of `substr()` it's `strpos()` and this fixes it.

**Comment by LukeTowers** [comment]
@Teranode will do, thanks for the ping

**Comment by robinbonnes** [comment]
> [octobercms/library@0989697](https://github.com/octobercms/library/commit/09896978bd8b09aac20a8da70ac93c2617afa03c) should fix this issue for you, although I was entirely unable to replicate your original issue, even after I tried manually force the middleware to generate serialized cookies.

This fixes it. I disabled `cms.edgeUpdates` for all backends. However because update 468 is moved out of `pending`, I have to manually patch all backends after update. Anyone else got the same issue? Is there an easier way to fix? :)

**Comment by acasar** [comment]
@LukeTowers Can this fix be merged to master asap? I had to change the composer dependency for ``october/rain`` to ``dev-develop`` to solve this issue and I'd prefer to run a stable version in production.

**Comment by LukeTowers** [comment]
@acasar @robinbonnes merged the fix into master, will talk to @daftspunk about retagging / rebuilding the marketplace update version.

**Comment by jan-vince** [comment]
Hi @LukeTowers, I have the very same problem on many sites when updated to 468.

Everyone that has been logged in to backend before this update is now unable to view any page getting the `substr()` error.

Only (user) way was to clear cookie `admin_auth`.

Unfortunatelly your fix didn't solved this for me so I tried to find the cause of a problem.

I had to add string check to `decrypt()` function of `EncryptCookies.php` file like this:

```
...
    protected function decrypt(Request $request)
    {

        foreach ($request->cookies as $key => $cookie) {
            if ($this->isDisabled($key)) {
                continue;
            }

            try {
                // Decrypt the request-provided cookie
                $decryptedValue = $this->decryptCookie($key, $cookie);
                // Verify that the decrypted value belongs to this cookie key, use null if it fails

+                if (!is_string($decryptedValue)) {
+                   $decryptedValue = json_encode($decryptedValue);
+                }

                $value = CookieValuePrefix::getVerifiedValue($key, $decryptedValue, $this->encrypter->getKey());


...
```
In my case, `$decryptedValue` was an array.

Is this worth a new commit? Looks like only a few of us have this problem.

*I have saved an `admin_auth` cookie value that caused this problem so this can be easily replicated. I can PM the value to you if you want.*

**Comment by LukeTowers** [comment]
@jan-vince it's already been added, we're just not going to release a new build for it, it'll be included in the L6 update: https://github.com/octobercms/library/commit/09896978bd8b09aac20a8da70ac93c2617afa03c
