### ISSUE TITLE
Lack of button with data-attach-loading attribute

### ISSUE THREAD

**Issue by igor-tv** [octobercms/october#5232]
- OctoberCMS Build: **467**

### Description:
A submit button with the data-attach-loading attribute does not show the spinner during the request if it is placed outside the form.

### Steps To Reproduce:
```
<form id="exampleForm" data-request="onSubmit">
    ...
</form>

<button type="submit" form="exampleForm" data-attach-loading>
        Submit
</button>
```

**Comment by bennothommo** [comment]
@igor-tv This is by design. A submit button needs to be within a form to properly submit it too as per the HTML5 spec.

**Comment by igor-tv** [comment]
> @igor-tv This is by design. A submit button needs to be within a form to properly submit it too as per the HTML5 spec.

<img width="967" alt="Снимок экрана 2020-08-05 в 11 17 02" src="https://user-images.githubusercontent.com/6777469/89388865-49261280-d70d-11ea-872c-746779f23f0f.png">

[https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button](https://developer.mozilla.org/)

**Comment by bennothommo** [comment]
@igor-tv Interesting, didn't realise that made the spec. Nonetheless, we technically still support IE11 with the AJAX framework, and [that doesn't support the `form` attribute](https://caniuse.com/#feat=form-attribute) for buttons, so if you wish to use buttons outside of the form with the AJAX framework, you'll need to use the JavaScript API.

**Comment by igor-tv** [comment]
@bennothommo Thank you for your reply.
