### ISSUE TITLE
Theme directory paths are incorrect on Windows

### ISSUE THREAD

**Issue by Samuell1** [octobercms/october#5236]
- OctoberCMS Build: 469 (develop branch)
- PHP Version: 7.3.4
- Database Engine: mysql
- Plugins Installed: demo plugin

### Description:
First issue is that this statement (https://github.com/octobercms/october/blob/develop/modules/cms/classes/CmsObject.php#L235) like returns false but shouldnt because it fails in next array checks that allow only integer or string 

`array_key_exists(): The first argument should be either a string or an integer`

Second issue is that $resolvedPath, $directory are totally different, slashes doesnt match and resolved_path method returns slash on start but it shouldnt.

resolvedPath: `/E:/laragon/www/october/themes/demo/layouts/default.htm`
directory: `E:\laragon\www\october/themes/demo/layouts/`

### Steps To Reproduce:
Forking develop and trying to load demo theme.

**Comment by bennothommo** [comment]
@Samuell1 would you mind trying to changes to the `resolve_path` helper made as part of this PR: https://github.com/octobercms/library/pull/512 and see if that resolves the issue?

**Comment by bennothommo** [comment]
@Samuell1 https://github.com/octobercms/october/commit/3a1f547adb0bef8245691fc5df0612cf865d90d7 should fix this issue once and for all, hopefully. Would you mind giving it a test and letting us know?

**Comment by Samuell1** [comment]
@bennothommo tested it and it works!

**Comment by bennothommo** [comment]
Fixed by https://github.com/octobercms/october/commit/3a1f547adb0bef8245691fc5df0612cf865d90d7.
