### ISSUE TITLE
Issues with Windows Hibernate

### ISSUE THREAD

**Issue by summercms** [octobercms/october#5244]
From day one we always had this issue and kind of swept it under the carpet.

It goes like this ...

- Install October CMS.

- Use it to develop and update some plugins etc.

- Then one day some strange errors appear ? Either plugins don't install properly or you run one of your plugins and some strange results happen etc.

- Let's just say we already know the solution (which is to clear the cache).

- You clear the cache at server and cdn level etc. - BUT the problem still continues and you know it's a caching issue as your code is correct and the cms is acting strange.

- So you install one of the clear cache plugins from the marketplace (we got a few and tested them all out).

e.g.

https://octobercms.com/plugin/romanov-clearcachewidget

https://octobercms.com/plugin/indikator-backend

https://octobercms.com/plugin/indikator-backendelite

etc.

- So you clear the cache and refresh to check your website now.

- Arrrrrr now we are logged out!

- Log back in to the backend.

- Yes the problem is fixed now.

PAIN.

This pain surely could be removed and a proper solution created.

p.s. In the opposite direction of clearing the cache. Windows Hibernate and October CMS also doesn't work together. For example, you are in the middle of some work on the cms and want to come back later to finish it off. You set the computer to sleep mode and then come back in a few hours time and the cms doesn't want to continue. It's showing the backend page, but nothing is working and you can't navigate the backend (the cms is locked up in some weird state). You press browser refresh and then you get the `"Invalid security token"` error message. So you press refresh again and you get the same error message and go around in circles! The only way to get out of this is to either close the tab or do a hard refresh. Which forces the cms to go to the backend login screen and then many times you still get the `"Invalid security token"` error message and again another hard refresh or new tab is in order. This we have seen in Chrome and Firefox over the years and continues to be a pain. At which point you have lost your space where you were working on and it's killed your work flow. The cms is not developer friendly is this regard!

### Wish list solutions

1. CMS to run some kind of "official" caching plan - which allows users to set a caching and clear caching method they require.

2. When you clear the cache you are **not logged out of the backend** every time!

3. The CMS to have a proper store state where it can work with `Sleep` and `Hibernate` modes in Windows, e.g. can allow the user to return to the cms page they were working on.

4. If the CMS crashes and you have to log back in. The CMS loads the current page the user was last looking at. E.g. 

```
https://example.com/backend/widgets
```

CMS crashes and you need to re-login. CMS returns you to the following page:

```
https://example.com/backend/widgets
```

and not something like:

```
https://example.com/backend/dashboard
```

Look forward to hearing people's views on this subject - this issue has been going on for years in our camp.

**Comment by LukeTowers** [comment]
These are a bunch of separate issues, and none of them are actionable without more detailed replication instructions. I've never encountered any of the issues that you list here. 

If you can provide detailed replication instructions for these issues starting from downloading the installer and going to the issue being present 100% of the time then we can look at doing something about them, otherwise we're flying blind and can't do anything.

**Comment by summercms** [comment]
@LukeTowers Sure, understand. Does October keep any record of error messages shown, e.g. when the plugins failed to install due to the cache we kept seeing the same error message - but we never thought of writing it down. Just wondered if it gets stored in the database etc.

**Comment by LukeTowers** [comment]
Only place would be in the event log, if it's not there then no.

**Comment by summercms** [comment]
Ah ok, yah I checked that and nothing there in the event log section. Ok we will keep a look out for this problem and update this issue with more information to investigate further. Sorry for lack of info right now - hopefully can gather some info in the near future on this.

**Comment by summercms** [comment]
If anyone from the October community has a caching problem which maybe part of this issue - please comment below.

**Comment by Samuell1** [comment]
If you loosing session after clearing cache then you need to separate cache for session.

**Comment by LukeTowers** [comment]
Ah, yes. If you're using redis for session and for cache then you need to make sure you're using a separate redis connection for your sessions.

**Comment by summercms** [comment]
Ah perfect, that's the problem we are facing, didn't realise we needed to separate the connection with redis. Thanks 😆
