### ISSUE TITLE
Mailtemplate views fails on seeding.

### ISSUE THREAD

**Issue by TheJackMachine** [octobercms/october#5245]
- OctoberCMS Build: 468
- PHP Version: 7.3
- Database Engine: MySql 5.7
- Plugins Installed: Rainlab.Translate + Personal Plugins + Renatio Frombuilder

### Description:
Mail tempalte can’t be registered.

If a plugin is no elevated, the plugins views is not registered.

But when it come the seeding part, internaly, the systeme try to find mail view, call the FileViewFinder, but the views are not registered in the hint array. So, the install fail with an the error : No Hint Path defined for [ XXX.XXX ]

To avoid this, the plugin must be elevated with public $elevated in the plugin.php

The problem is when you tried to seed.

I think, in PluginManager.php, it’s maybe a good idea to change the place of the block at line 261 ( Register view Path ), before the line 240 ( Disable plugin registration for restricted pages, unless elevated )

I havn’t this problem before, but i can’t find the version of October were this work correctly.

Thank for your attention to this problem !
Have a nice day !

### Steps To Reproduce:
1 - make mail templates in a plugin
2 - make a seed in your database
3 - php artisan october:up --verbose

**Comment by LukeTowers** [comment]
Fixed in https://github.com/octobercms/october/commit/3864e5b1c6e720e103f35a0aaddd25fb3142e605 @TheJackMachine, thanks for your report!
