### ISSUE TITLE
PathResolver::resolve breaks with open_basedir

### ISSUE THREAD

**Issue by freddy38510** [octobercms/october#5248]
- OctoberCMS Build: [#f708754f079bcbcf876cb245e794671b453fe36b](https://github.com/octobercms/october/commit/f708754f079bcbcf876cb245e794671b453fe36b)
- PHP Version: 7.4

### Description:
The new [`PathResolver`](https://github.com/octobercms/library/blob/develop/src/Filesystem/PathResolver.php) introduced recently is not working with open_basedir restrictions.

This happens in the `resolve` method when [looping](https://github.com/octobercms/library/blob/48e7a23e25dc3ee9165299b16e5c1d7150bafda3/src/Filesystem/PathResolver.php#L35) through all segments of the given path, and calling `is_link` or `is_file` on a segment which is not contained in the open_basedir allowed paths.

**Comment by bennothommo** [comment]
Thanks @freddy38510 - totally forgot about basedir restrictions. Will deploy a fix for this shortly.

**Comment by bennothommo** [comment]
@freddy38510 Would you mind testing PR https://github.com/octobercms/library/pull/516 and let us know if that stops the "open_basedir" warnings from being shown?

**Comment by freddy38510** [comment]
@bennothommo 

I was just testing this PR, there is no more warnings about open_basedir.

Thanks for your reactivity, great job !
