### ISSUE TITLE
Relation manager widget inconsistent with different field name.

### ISSUE THREAD

**Issue by ericp-mrel** [octobercms/october#5252]
- OctoberCMS Build: 468
- PHP Version: 7.4
- Database Engine: MariaDB 10.3
- Plugins Installed:
  - October.Demo
  - October.Test
  - RainLab.Builder

### Description:
I'm trying to create a JS component that listens to the `change.oc.formwidget` event on a relation manager widget, but I've noticed some inconsistent behavior with this event not triggering when the field name is different than the relation name on the model.

For instance, looking at the October.Test plugin posts form, the expected behavior works on the posts comments relation widget because the field name matches the actual relation name. https://github.com/octoberrain/test-plugin/blob/master/models/post/fields.yaml#L48-L52 But if you were to rename that field to something such as `comments_relation` the JS event will not trigger consistantly compared to when the field name matches the relation name.

Looking through the backend module code, it seems this issue comes from the `data-field-name` attribute is different than the actual relation name which the `october.relation.js` actually uses to lookup the element to trigger the change event. The problem is this script uses the `relationId` param which is the actual relation name instead of matching the field name and so if the field name doesn't match the relation name the event is never triggered.

See: https://github.com/octobercms/october/blob/develop/modules/backend/behaviors/relationcontroller/assets/js/october.relation.js#L68

It looks like the `data-field-name` attribute is coming from the actual `_field_container.htm` partial and is set based on the actual field name, which makes sense.  https://github.com/octobercms/october/blob/develop/modules/backend/widgets/form/partials/_field-container.htm

It seems as if there should be a way for the relation controller to be able to render the widget while knowing what the actual field name is if it is different than the relation name. After looking through some of the code for the RelationController I can see why it isn't exactly that simple of a solution and I think there would need to be some sort of a config option passed where you can tell it the field name if it doesn't match the relation name.

Example of fields.yaml where it doesn't work properly:
```yaml
tabs:
    fields:
        comments_relation:
            span: full
            cssClass: js-sortable
            path: comments
            type: partial
            tab: Comments
```

Here's an example of the JS snippet I'm am using:
```js
$(function () {
    let $sortableWidgets = $('.js-sortable');

    $sortableWidgets.each(function () {
        let $widget = $(this);
        let $tbody = $widget.find('table.data tbody');

        if ($tbody.length === 0) {
            return;
        }

        $widget.on('change.oc.formwidget', (e) => {
            alert('form widget changed!!!')
        });
    });
});

```

Screenshot which shows which element the event is bound to:
![Screenshot from 2020-08-26 12-22-01](https://user-images.githubusercontent.com/63664924/91335965-d00f5d80-e796-11ea-99f3-c3dbc301c2c6.png)

### Steps To Reproduce:
1. change the partial field name to something that doesn't match the model's relation name.
2. Add/remove an item from the relation using the relation manager widget.

I hope this all makes sense and I wonder if this is even worth trying to address/fix since I suppose you could just easily change the field name to match your relation name in order for this to continue working as intended.

**Comment by bennothommo** [comment]
@ericp-mrel Is the partial that you're targeting dynamically loaded or refreshed at all (for example, if it's within a lazy tab or has trigger rules)? It is possible in this instance that the element you originally targeted with the event is not the element that you see at a later stage, and is in fact a separate element in the DOM.

You could try using a "delegated" event listener like the following:

```
$('body').on('change.oc.formwidget', '.js-sortable table.data tbody', (e) => {
    alert('form widget changed!!!')
});
```

That may have more luck in capturing the event.

**Comment by ericp-mrel** [comment]
I am not using any type of dynamically loaded element or lazy tabs. I was even using the [Test Plugin](https://github.com/octoberrain/test-plugin) to test this functionality out and it happens in that plugin as well.

It just seems that the partial field name MUST match the name of the relation because of how the `october.relation.js` script references the field based on the relation name.

I was pretty detailed in my original comment so I hope that was explained well enough.

**Comment by bennothommo** [comment]
@ericp-mrel I recognise that you were very thorough in your original post, and I appreciate that. I had simply misinterpreted what you had said about the Test Plugin and thought that the event was firing on the wrong element, and not that you had actually meant it's not firing at all.

We'll take a look into it.

**Comment by ericp-mrel** [comment]
No worries, I was typing it as I was deep diving into the OctoberCMS backend code and figuring out how it all works. If I remember right, I believe when using the checkbox to select an item in the relation manager widget list, it will actually fire a change event, but when adding/removing an item the event isn't fired due to the relation.js script not being able to find the element in the DOM due to the selector its using based on the relation name instead of the form field name.

Hope that helps makes things a little more clear. And I was using the test plugin just as an easy way to demonstrate the issue where someone can test it out easily.

**Comment by daftspunk** [comment]
> It just seems that the partial field name MUST match the name of the relation because of how the october.relation.js script references the field based on the relation name.

Correct ^  In future, we could be able to take a more in-depth look at your issue with premium support hours. If this is still an issue for you. Thanks!
