### ISSUE TITLE
Can't override existing methods with addDynamicMethod()

### ISSUE THREAD

**Issue by aniket-magadum** [octobercms/october#5254]
- OctoberCMS Build: 468
- PHP Version: 7.2.19
- Database Engine:  InnoDB
- Plugins Installed: Rainlab.User

### Description:
I am trying to add a dynamic method to a backend controller with the following code.

```PHP
Candidates::extend(function ($controller) {
    $controller->addDynamicMethod('listExtendQuery', function ($query) {
             dd($query);
     });
});
```
The problem is that this callback function does not fire. Upon further investigation, I found that the Controller called the listExtendQuery method in the ListController class

https://github.com/octobercms/october/blob/d49266ad90246fcf90565de8ccdcdbad492de0fe/modules/backend/behaviors/ListController.php#L506

If I do a `dd($query)` inside this function it is getting triggered

My question is how can I extend the Candidate controller so that the callback function fires.

### Steps To Reproduce:

Inside of the boot method of your plugin add the above code and just change the controller to any other controller and try to add the listExtendQuery dynamic method. Then load the index page of the controller the expected behavior is that it should display a dump of $query but it does not display a dump.

**Comment by LukeTowers** [comment]
You cannot override an existing method with `addDynamicMethod()`. Instead, extend the List widget directly by doing the following:

```php
\Backend\Widgets\Lists::extend(function ($widget) {
    if (!($widget->getController() instanceof \MyAuthor\MyPlugin\Controllers\MyController)) {
        return;
    }

    $widget->bindEvent('list.extendQuery', function ($query) {
        return $query;
    });
});
```

**Comment by aniket-magadum** [comment]
@LukeTowers Thanks

**Comment by aniket-magadum** [comment]
This is the corrected code. Changed this
>     if (!($widget instanceof \MyAuthor\MyPlugin\Controllers\MyController)) {

to this 

```PHP
if (!($widget->getController() instanceof \MyAuthor\MyPlugin\Controllers\MyController)) {
```
