### ISSUE TITLE
Sluggable field no longer works after form refresh

### ISSUE THREAD

**Issue by bennothommo** [octobercms/october#5256]
- OctoberCMS Build: 468 (and `develop`)
- PHP Version: 7.4
- Database Engine: MySQL
- Plugins Installed: RainLab.Pages

### Description:
Sluggable fields appear to stop working as soon as a form is refreshed. This happens even if the form context is in `create` and the sluggable field itself has not been modified, so theoretically, the slug should still be tracking the trigger field value.

### Steps To Reproduce:
- Install RainLab.Pages
- Set up two or more layouts and make them available to the Pages plugin (through the `StaticPage` component)
- Create a new page in the Pages plugin
- Add a title (say "Home"), the URL field should automatically change to `/home`
- Switch the layout of the page - this triggers a form refresh.
- Modify the title (say "Welcome"), the URL field no longer automatically updates the slug - it should still remain as `/home`. At this point, we would expect the slug to be `/welcome`.

**Comment by LukeTowers** [comment]
@bennothommo do you know if this ever worked?

**Comment by bennothommo** [comment]
@LukeTowers I hadn't noticed it working or not working before. I submitted this more as a note for myself to have a look at it at a later stage.

**Comment by daftspunk** [comment]
Good bot

As long as it gets populated with something, this is fine. When the fields refresh, the plugin no longer treats it as a new field
