### ISSUE TITLE
Protected attachments are not loading correctly

### ISSUE THREAD

**Issue by digitreadmedia** [octobercms/october#5267]
- OctoberCMS Build: 468
- PHP Version: 7.4
- Database Engine: mySQL/MariaDb

### Description:
Protected attachments saved with the method below get's saved to the public folder instead of the protected storage folder, resulting in 404 errors when trying to load / output the files.

**Relation**:
`    public $attachMany = [
        'docs' => ['System\Models\File' , 'public' => false],
        'pdfs' => ['System\Models\File', 'public' => false],
    ];`

**Code:**
`	    $pdf = new \System\Models\File;
            $pdf->fromFile($file);
            $pdf->is_public = false;
            $pdf->save(); 
            $model->pdfs()->add($pdf);`

I have also tried $pdf->fromUrl and $pdf->data;  Attachments are uploaded and saved successfully and flagged as protected, but it is saved into the public storage directory instead of the protected storage directory.

**Comment by LukeTowers** [comment]
What plugins do you have installed? I just tried this on 1.1.0, but was unable to replicate. I was able to find and fix a related issue for displaying thumbnails for protected files though.

**Comment by digitreadmedia** [comment]
Hi,

Only plugins I have installed is Rainlab/Pages, Rainlab/User, Rainlab/Builder, Developer Tools and my plugin.

**Comment by LukeTowers** [comment]
Are you able to reproduce this on a fresh install of October CMS from composer `composer create-project october/october testUploadsIssue`?

**Comment by digitreadmedia** [comment]
Hi, yes - I'm able to reproduce the issue on a clean install with testUploadsIssue.

The plugin merges data from the database to a Word docx document and then uses an external API to merge the Word doc to PDF.  Both files are then saved to storage/temp, from where it is attached to the model.  But instead of saving the files to storage/app/uploads/protected it saves to storage/app/uploads/public.

**Model:**
`    public $attachMany = [
        'docs' => ['System\Models\File', 'public' => false ],
        'pdfs' => ['System\Models\File', 'public' => false ],
    ];`

**Controller:**
`    public function test($recordId) 
    {
        $application = Application::find($recordId);
               
        try {
            $d = temp_path('test.docx');
            $p = temp_path('test.pdf');

	    $docx = new \System\Models\File;
            $docx->fromFile($d);
            $docx->is_public = false;
            $docx->save();
            
	    $pdf = new \System\Models\File;
            $pdf->fromFile($p);
            $pdf->is_public = false;
            $pdf->save();            

            $application->docs()->add($docx);
            $application->pdfs()->add($pdf);
            
        } catch (Exception $e) {
            $error = $e->getMessage();
        }        
    }`

**Comment by LukeTowers** [comment]
@digitreadmedia ah, there's your problem. You can't set is_public after `fromFile()` because `fromFile()` creates the file on the disk: https://github.com/octobercms/library/blob/develop/src/Database/Attach/File.php#L125.

Do this instead:

```php
    public function test($recordId) 
    {
        $application = Application::find($recordId);
               
        try {
            $d = temp_path('test.docx');
            $p = temp_path('test.pdf');

	    $docx = new \System\Models\File;
            $docx->is_public = false;
            $docx->fromFile($d);
            $docx->save();
            
	    $pdf = new \System\Models\File;
            $pdf->is_public = false;
            $pdf->fromFile($p);
            $pdf->save();            

            $application->docs()->add($docx);
            $application->pdfs()->add($pdf);
            
        } catch (Exception $e) {
            $error = $e->getMessage();
        }        
    }
```
