### ISSUE TITLE
Site breaking bug - Martin.Forms rendered useless if RainLab.Mailchimp plugin installed in Build 469

### ISSUE THREAD

**Issue by SplicedWeb** [octobercms/october#5272]
- OctoberCMS Build: 469 
- PHP Version: 7.49
- Database Engine: mySQL
- Plugins Installed: 
October.Demo-v1.0.1
Martin.Forms-v1.4.20
RainLab.MailChimp-v1.0.4
SureSoftware.Maillog-v2.1.0
### Description:
Error when submitting form: "The specified file extension [js] is invalid." on line 520 of /vendor/october/rain/src/Halcyon/Builder.php

### Steps To Reproduce:
Install OctoberCMS latest Build 469
Install Martin.Forms
Install RainLab.MailChimp
Install SureSoftware.MailLog
In CMS > Layouts > Default layout, insert component Magic Forms > Generic AJAX Form
In CMS > Layouts > Default layout, insert component Mailchimp > Signup form
Save
Navigate to front end and attempt to submit the form.

**Comment by LukeTowers** [comment]
This is a bug in the forms plugin.

**Comment by SplicedWeb** [comment]
Thanks @LukeTowers I wasn't sure if it was the plugin since the Forms plugin works prior to adding Mailchimp plugin.
