### ISSUE TITLE
Minify framework js code

### ISSUE THREAD

**Issue by mkinternet** [octobercms/october#5277]
Can framework js code be minified?
https://www.octobercms.com/modules/system/assets/js/framework.js
https://www.octobercms.com/modules/system/assets/js/framework.extras.js

Google insigt or gtmetrix alerts that this code is not compressed

**Comment by alxy** [comment]
Yes, pass them to an array and use the theme filter. Something like this should work:

```
<script src="{{ [
            '@jquery',
            '@framework',
            '@framework.extras'
        ]|theme }}"></script>
```

Reference is also in[ the docs](https://octobercms.com/docs/markup/filter-theme#combiner-aliases).

**Comment by mkinternet** [comment]
This code only combine assets.

**Comment by alxy** [comment]
From the docs:

> Note: You can enable the assets minification with the enableAssetMinify parameter in the config/cms.php script. By default the minification is disabled.

**Comment by bennothommo** [comment]
@alxy is correct - `cms.enableAssetMinify` will minify scripts that are run through the combiner, using the code he mentioned above.
