### ISSUE TITLE
File doesn't save from request

### ISSUE THREAD

**Issue by sjsadeghi** [octobercms/october#5278]
OctoberCMS Build: 469

### Description:
It was working fine in previous cms versions. Now is not working.
when I want to assign file from request, the file is empty!

![Screenshot from 2020-09-15 15-13-27](https://user-images.githubusercontent.com/18641071/93201828-f48fa180-f766-11ea-9fda-e6b0b65e26c0.png)

### Steps To Reproduce:

- create a model that has file field (image)
- create an api to assign file to the model's object 
- send request
- file saved empty!

**Comment by LukeTowers** [comment]
@sjsadeghi please post your code. Also, it's likely that https://github.com/octobercms/library/commit/425b9f54d0ffb858b9bbe319538a14fa488ac58c fixes that issue for you.
