### ISSUE TITLE
Have an option to not allow blank entries in repeater fields when there is another repeater entry filled in

### ISSUE THREAD

**Issue by summercms** [octobercms/october#5280]
Take the following examples:

### Example 1

![image](https://user-images.githubusercontent.com/57409060/93665909-07112000-fa72-11ea-991a-4d84ed7f3010.png)

Above: 2 `<li>` entries, with all 4 fields filled in - this is fine.

### Example 2

![image](https://user-images.githubusercontent.com/57409060/93665926-260fb200-fa72-11ea-9489-8abe3b7116ae.png)

Above: 2 `<li>` entries, with 3 fields filled in and one blank field - this is fine.

### Example 3

![image](https://user-images.githubusercontent.com/57409060/93665943-3e7fcc80-fa72-11ea-931c-cda49ef1f20c.png)

Above: 2 `<li>` entries, with the 1st repeater field with 2 fields filled and in and the 2nd repeater field completely blank - this is not fine.

### Example 4

![image](https://user-images.githubusercontent.com/57409060/93665971-6a9b4d80-fa72-11ea-8f65-7a120399fd89.png)

Above: 2 `<li>` entries, with the 1st repeater field with 2 fields completely blank and in and the 2nd repeater field filled in - this is not fine.

## Why not use `required` on each repeater entry?

In the examples, you will see that all the fields in each repeater entry are not `required` and therefore you couldn't add a `required` to each repeater entry. 

This is because we also want to allow an option, where the user can select nothing, giving the result of `[ ]`

### Example 5

![image](https://user-images.githubusercontent.com/57409060/93666190-feb9e480-fa73-11ea-8c17-9a2e3bc2db72.png)

Above: Allows the user to not select any values, giving the result of `[ ]`

### Example 6

![image](https://user-images.githubusercontent.com/57409060/93666372-a1269780-fa75-11ea-8d89-30b6bcef6fec.png)

Above: Allows the user to not select any values, but still allow the developer to set `minItems: 1`, giving the result of `[ ]`

### Summary

The first entry can be ignored **if it is on it's own** and can be blank.

However, if there are **two or more repeater fields**, then there can not be a completely blank repeater `<li>` entry.

This feature to be **optional** and given via a `yaml` command, if the developer doesn't want to make the fields or entries `required` and wants to turn this option on whenever needed.

(*) Hope I explained the concept ok.

p.s. For now we are going to code a custom validation rule, to achieve this - but long-term we were hoping just to create a yaml function to achieve the same rule.

**Comment by Samuell1** [comment]
I think you can use array validators something like `myrepeater.*.name` Should work.

**Comment by summercms** [comment]
@Samuell1 I forgot about that, thanks will test that out.
