### ISSUE TITLE
Repeater field deletes all data when adding another entry

### ISSUE THREAD

**Issue by summercms** [octobercms/october#5282]
Latest version of october.

The bug goes like this:

1. Have two fields in each repeater entry, the first being an `input` and the second being a `select / dropdown` field.

2. I write some data in the `input` field.

3. I don't click save.

4. I add another repeater entry.

5. The data I wrote in the first repeater entry `input` field gets deleted.

Gif of the bug in action:

![bug](https://user-images.githubusercontent.com/57409060/94030613-ef110780-fdb5-11ea-868d-6df2e90023f2.gif)

As I said we tested lots of field combinations and doesn't happen to every single combination. We think this is because the field is using an array validator custom rule maybe? Something like `myrepeater.*.name` - just a guess? Not sure why October is deleting the data when adding another repeater entry?

Like I say, some form field combinations the data is not deleted and some field combinations the data is deleted.

**Comment by LukeTowers** [comment]
This is a complex case. 

In order to aid in our understanding of the problem, please submit [a Pull Request to the test plugin](https://github.com/octoberrain/oc-test-plugin) for investigation that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it _using the test plugin_.

**Comment by summercms** [comment]
No problem, will try and create a pr to recreate this bug in the test plugin, sometime this week.

**Comment by summercms** [comment]
@LukeTowers Sorry this is embracing, was coding the test plugin and noticed that we had our October II machine learning widget connected to that input field and there seems to be a conflict between that code and the repeater javascript.

Will have to be more careful as we are using October II full-time in the office to speed up development.

Have tested the normal `input` field in the repeater setup and works fine.

Sorry about that, I didn't see the machine learning was turned on.

Going to close this issue as there isn't an issue with v1.0.0
