### ISSUE TITLE
403 Forbidden: You don't have permission to access this resource.

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#5286]
- OctoberCMS Build: 469
- PHP Version: 7.3.9
- Database Engine: MySQL 5.x
- Plugins Installed: 
RainLab.Blog
MailLog
RanLab.MailChimp
Backup
OFFLINE.SiteSearch

### Description:
Can't update any backend settings, like the Mail Configuration for example, but not only.
Receiving this "403 Forbidden" error
My plugin settings page is working fine, and other plugin settings are working fine as well.
It seems like only the October CMS Settings are not updatable.

### Steps To Reproduce:
OC Fresh install on a Digital Ocean instance.

<img width="1066" alt="Screenshot 2020-09-26 at 2 22 12 PM" src="https://user-images.githubusercontent.com/2263496/94332094-9daa8780-0004-11eb-9870-0a54402292a6.png">

**Comment by LukeTowers** [comment]
Possibly related to https://octobercms.com/support/article/ke-1, if you have weird ModSecurity rules enabled it could be blocking that request specifically.

**Comment by chrisvidal** [comment]
thanks @LukeTowers 

I had to disabled entirely ModSecurity to make the backend settings works.
