### ISSUE TITLE
File upload and repeater widget

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#5287]
I use the File upload widget in the Repeater widget. I added more different files and saved the form. When I refreshed the page, the all File upload widget contain same file.

Before save:
![01](https://user-images.githubusercontent.com/2959112/94447999-b9e82900-01aa-11eb-8feb-61b4ac5b886c.jpg)

After save:
![02](https://user-images.githubusercontent.com/2959112/94448012-bce31980-01aa-11eb-81d3-44c47db73561.jpg)

Is it a bug or am I doing something wrong?

**Comment by LukeTowers** [comment]
You're doing something wrong, fileupload widgets use model relationships, so by their very nature they're not going to work with the repeater widget out of the box which stores its data in JSON and can have an arbitrary number of rows. Use a mediafinder instead.

**Comment by gergo85** [comment]
All right. Are there any solution to add user permission to folders of Media? I need to users view own folder, not all folders.

**Comment by LukeTowers** [comment]
@gergo85 yes it's pretty simple, just use the ability to dynamically change the config along with event handlers and you can do that relatively easily. See my FileLocker and EasyFiles plugins for an example

**Comment by gergo85** [comment]
Thank you for your help! :)
