### ISSUE TITLE
Email events do not pass parameter by reference

### ISSUE THREAD

**Issue by prhost** [octobercms/october#5290]
Hi,

Currently I was needing to reverse the email content before it fires, I saw that there are several events in the mail with `beforeSend`, `prepareSend`, but none of them is possible to change the `$data` or `$view`, or anything that is not just return false to stop sending.
I found this @LukeTowers conversation about it in https://github.com/octobercms/october/pull/4651#issuecomment-537548865 . If I send a PR changing the events with reference, do you think it is valid?

**Comment by LukeTowers** [comment]
Did you try requesting it by reference first @prhost?

**Comment by prhost** [comment]
yes, for some reason when i put reference on Event::listen, he doesn't even enter the event.

**Comment by LukeTowers** [comment]
A PR should be fine then, we can review it further when it's submitted
