### ISSUE TITLE
Theme URL's are case-insensitive

### ISSUE THREAD

**Issue by mahony0** [octobercms/october#5297]
- OctoberCMS Build: 469
- PHP Version: 7.4
- Plugins Installed: RainLab.Translate-v1.7.2

### Description:
I thought this is an url interpretation bug. Both https://domain.tld/contact and https://domain.tld/ConTacT opening the same page is kinda weird and not SEO friendly.

### Steps To Reproduce:
* Create a page in theme with url like: /contact
* Try to reach the /contact page via every capitalized and non-capitalized forms of contact

**Comment by LukeTowers** [comment]
While URLs are technically case sensitive, it’s rarely a good idea to treat them as such in a cms environment, see https://www.searchenginejournal.com/url-capitalization-seo/343369/. Additionally, IIS does not support case sensitive URLs by default. Why should we encourage people to be using case sensitive urls when they can cause so many problems?

**Comment by mahony0** [comment]
I couldn't find any relevant info in docs. about case-insensitive handling of urls so need to ask if that's intended or not. Also if that's problematic for IIS which I never used, surely it's logical to keep it that way.

Maybe putting a word in docs about this will be useful for clarifying

**Comment by LukeTowers** [comment]
@mahony0 sure, where would it make sense to you for a note about it to be? Perhaps you can submit a PR?

**Comment by mahony0** [comment]
Sure @LukeTowers here it is: [Docs Update](https://github.com/octobercms/docs/pull/486)

**Comment by LukeTowers** [comment]
Resolved by https://github.com/octobercms/docs/commit/f54a27eb39fada746be26a817d3f266c97bf65c9. Thanks for the contribution @mahony0 :)
