### ISSUE TITLE
Wrong var type

### ISSUE THREAD

**Issue by davodsaraei** [octobercms/october#5300]
In this line, The `$config` variable defined as an array but used as an object

https://github.com/octobercms/october/blob/af6db51b7978aae874844e79e0103b0952d7b762/modules/backend/classes/ControllerBehavior.php#L26

**Comment by LukeTowers** [comment]
@davodsaraei feel free to submit a PR, make the change here too please: https://github.com/octobercms/october/blob/af6db51b79/modules/system/traits/ConfigMaker.php#L30

**Comment by SaidiAli** [comment]
@davodsaraei I think it's intended to be used as an object. The array is turned into an object in this method; https://github.com/octobercms/october/blob/af6db51b79/modules/system/traits/ConfigMaker.php#L30

**Comment by davodsaraei** [comment]
@SaidiAli @LukeTowers It will be changed to object but I have another issue when I run the `composer install`.
https://github.com/octobercms/october/issues/5302#issuecomment-705536788

**Comment by LukeTowers** [comment]
@davodsaraei see my comment on that.
