### ISSUE TITLE
Issue with october:update when using composer

### ISSUE THREAD

**Issue by davodsaraei** [octobercms/october#5302]
- OctoberCMS version 1.1
- PHP Version: 7.4
- Database Engine: MYSQL

### Description:
Difference between the OctoberCMS update in the admin panel or command line and composer update.

### Steps To Reproduce:
1. I create a new plugin and add composer.json to add new packages.
2. I update from the admin panel or command line with the `php artisan october:update --force`.
3. I get the following err.

<img width="1440" alt="Screenshot 2020-10-08 at 14 03 41" src="https://user-images.githubusercontent.com/15808829/95447764-1c8db180-096f-11eb-84e9-5ea484ed90c5.png">

But if I use `composer update` some files in modules will be changed and everything is good.

**Comment by davodsaraei** [comment]
**Note:** If I clone the git repo and run the `composer install` command. some files in modules dir will be changed and I don't know why.

<img width="1440" alt="Screenshot 2020-10-08 at 16 01 12" src="https://user-images.githubusercontent.com/15808829/95458783-86ae5280-097f-11eb-82a2-55eba6ac64cb.png">

**Comment by LukeTowers** [comment]
@davodsaraei do not use `october:update` when you're using composer without setting `cms.disableCoreUpdates` to true.

**Comment by LukeTowers** [comment]
See https://github.com/octobercms/docs/commit/1b6cb3f054efb3637f3beba13f63eefe386a7f97
