### ISSUE TITLE
How to use data-request-flash

### ISSUE THREAD

**Issue by sstifler** [octobercms/october#5303]
- OctoberCMS Build: 469
- PHP Version: PHP 7.2.22
- Database Engine: mysql

I found an error: css Flash message styles don't work in data-request-flash. An example from the documentation: https://octobercms.com/docs/ajax/extras#ajax-flash

```

function onSuccess()
{
    Flash::success('You did it!');
}
?>
==

<form
    data-request="onSuccess"
    data-request-flash>
    <button>send</button>
</form>


{% flash %}
    <p
        data-control="flash-message"
        class="hello world {{ type }}"
        data-interval="5">
        {{ message }}
    </p>
{% endflash %}

```

code in my page was not applied in the html code:
`<p class="success flash-message fade in">You did it!<button type="button" class="close" aria-hidden="true">×</button></p>`

**Comment by LukeTowers** [comment]
@fatklass you're confusing two separate things. The `{% flash %}` tag is for flash messages that are displayed when the page is rendered, not displayed on AJAX requests. The `data-request-flash` attribute tells the AJAX framework that the flash message will be handled on AJAX requests, but in order for it to actually work you need to make sure you're including `framework.extras.js` on your page.

**Comment by sstifler** [comment]
> @fatklass you're confusing two separate things. The `{% flash %}` tag is for flash messages that are displayed when the page is rendered, not displayed on AJAX requests. The `data-request-flash` attribute tells the AJAX framework that the flash message will be handled on AJAX requests, but in order for it to actually work you need to make sure you're including `framework.extras.js` on your page.

I use framework.extras.js. ajax Flash messages work. http://prntscr.com/uvnhtd
But my css classes don't work.
Because the ones that are used by default are used framework.extras.js.

http://prntscr.com/uvnm8e
http://prntscr.com/uvnljj

**or so**

```
{% flash %}
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            $.oc.flashMsg({text: '{{ message }}', 'class': 'MY CSS CLASS success fade in', 'interval': 5})
        }, false);
    </script>
{% endflash %}
```

does not work https://prnt.sc/uvnljj

**Comment by LukeTowers** [comment]
@fatklass see https://github.com/luketowers/oc-blank-theme/blob/master/assets/js/app.js#L9-L28 for an example of how you can set global handling for all frontend AJAX requests with flash messages with custom classes.

**Comment by sstifler** [comment]
> @fatklass see https://github.com/luketowers/oc-blank-theme/blob/master/assets/js/app.js#L9-L28 for an example of how you can set global handling for all frontend AJAX requests with flash messages with custom classes.

Thank you for helping me. But it doesn't work. Installed the demo theme October CMS. And did as you said does not work.
default.htm
```
description = "Default layout"
==
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>October CMS - {{ this.page.title }}</title>
        <meta name="description" content="{{ this.page.meta_description }}">
        <meta name="title" content="{{ this.page.meta_title }}">
        <meta name="author" content="OctoberCMS">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="generator" content="OctoberCMS">
        <link rel="icon" type="image/png" href="{{ 'assets/images/october.png'|theme }}">
        <link href="{{ 'assets/css/vendor.css'|theme }}" rel="stylesheet">
        <link href="{{ 'assets/css/theme.css'|theme }}" rel="stylesheet">
        {% styles %}
    </head>
    <body>

        <!-- Header -->
        <header id="layout-header">
            {% partial 'site/header' %}
        </header>

        <!-- Content -->
        <section id="layout-content">
            {% page %}
        </section>

        <!-- Footer -->
        <footer id="layout-footer">
            {% partial 'site/footer' %}
        </footer>

        <!-- Scripts -->
        <script src="{{ 'assets/vendor/jquery.js'|theme }}"></script>
        <script src="{{ 'assets/vendor/bootstrap.js'|theme }}"></script>
        {% framework extras %}
        <script>    
            $(document).ready(function($) {
                /*-------------------------------
                OCTOBERCMS FLASH MESSAGE HANDLING
                ---------------------------------*/
                $(document).on('ajaxSetup', function(event, context) {
                    // Enable AJAX handling of Flash messages on all AJAX requests
                    context.options.flash = true;

                    // Enable the StripeLoadIndicator on all AJAX requests
                    context.options.loading = $.oc.stripeLoadIndicator;

                    // Handle Flash Messages
                    context.options.handleFlashMessage = function(message, type) {
                        $.oc.flashMsg({ text: message, class: type });
                    };

                    // Handle Error Messages
                    context.options.handleErrorMessage = function(message) {
                        $.oc.flashMsg({ text: message, class: 'error' });
                    };
                });
            });
        </script>
        {% scripts %}


        {% flash %}
            <p data-control="flash-message" data-interval="7" class="MY CASTOM STYLE {{ type }}">
                {{ message }}
            </p>
        {% endflash %}
    </body>
</html>

```
test.htm page
```
title = "test"
url = "/test"
layout = "default"
is_hidden = 0
==
<?php

function onSuccess()
{
    Flash::success('You did it!');
}
?>
==



<form
    data-request="onSuccess"
    data-request-flash>
    <button>send</button>
</form>
```

http://prntscr.com/uvyz13

`<p class="success flash-message fade in">You did it!<button type="button" class="close" aria-hidden="true" wfd-id="27">×</button></p>`

**Comment by LukeTowers** [comment]
The `{% flash %}` tag has nothing to do with AJAX requests. Anything you put in there is not going to be affect flash messages displayed by AJAX requests.

Put your customizations in the section of the JS that handles AJAX requests flashing:
```
// Handle Flash Messages
                    context.options.handleFlashMessage = function(message, type) {
                        $.oc.flashMsg({ text: message, class: type });
                    };
```

**Comment by PubliAlex** [comment]
I have the same problem and the answer is not clear.

If I read the doc here : https://octobercms.com/docs/ajax/extras#ajax-flash

You should be able to customize the flash message by putting {% flash %} {% endflash %} tags, even with an ajax call made with data-request.

But it does not work, it always load the default october HTML for flash messages instead of the code you put under {% flash %} and {% endflash %}

**Comment by PubliAlex** [comment]
> The `{% flash %}` tag has nothing to do with AJAX requests. Anything you put in there is not going to be affect flash messages displayed by AJAX requests.
> 
> Put your customizations in the section of the JS that handles AJAX requests flashing:
> 
> ```
> // Handle Flash Messages
>                     context.options.handleFlashMessage = function(message, type) {
>                         $.oc.flashMsg({ text: message, class: type });
>                     };
> ```

How to customize it when you use data-attribute and not js to handle your ajax request ?

**Comment by LukeTowers** [comment]
Personally I recommend using this snippet of JS from my Blank theme to enable flash messages for all AJAX requests in the theme (https://github.com/luketowers/oc-blank-theme/blob/master/assets/js/app.js#L9-L28)

**Comment by PubliAlex** [comment]
If I understand well, it allow to globaly parameter ajax message (type, duration etc....) but there is no way to customize the html of the flash message ? For example if I want to add "alert" class instead of "flash-message" class (I mean flash from ajax request, already know how to customize flash message on page reload)

**Comment by LukeTowers** [comment]
@PubliAlex if you would rather use your own custom flash handler entirely just change this line (https://github.com/luketowers/oc-blank-theme/blob/master/assets/js/app.js#L21) to be whatever you want to appear instead when a flash message needs to be handled. If you just want to change the class, then keep that line but add your class that you want added to the `class` property of the options sent to $.oc.flashMsg()

**Comment by PubliAlex** [comment]
@LukeTowers crystal clear, thank you Luke ! 👍
