### ISSUE TITLE
Scssphp v0.8.4 compiler gives error "expecting list, null received:..."

### ISSUE THREAD

**Issue by haralake** [octobercms/october#5304]
- OctoberCMS Build: ### 469
- PHP Version: 7.3
- Database Engine: mySQL
- Plugins Installed: 

### Description:
I use Octobercms and bootstrap 5 Alpha2. I try to compile bootstrap 5 scss files with build in octobercms scssphp v0.8.4 compiler like this:
`<link href="{ ['assets/vendor/bootstrap/scss/bootstrap.scss']|theme }}" rel="stylesheet">`
but on frontend i get error:

`expecting list, null received: /.../.../.../themes/octobercms/assets/vendor/bootstrap/scss/mixins/_utilities.scss on line 8, at column 5 Call Stack: #0 mixin generate-utility /.../.../.../themes/octobercms/assets/vendor/bootstrap/scss/utilities/_api.scss on line 13 #1 function breakpoint-min.......`

If i disable bootstrap 5 utilities/_api.scss, compiler works ok, but then i don't get any utilities classes.

_api.scss file data:

```
// Loop over each breakpoint
@each $breakpoint in map-keys($grid-breakpoints) {

  // Generate media query if needed
  @include media-breakpoint-up($breakpoint) {
    $infix: breakpoint-infix($breakpoint, $grid-breakpoints);

    // Loop over each utility property
    @each $key, $utility in $utilities {
      // The utility can be disabled with `false`, thus check if the utility is a map first
      // Only proceed if responsive media queries are enabled or if it's the base media query
      @if type-of($utility) == "map" and (map-get($utility, responsive) or $infix == "") {
        @include generate-utility($utility, $infix);
      }
    }
  }
}

// RFS rescaling
@media (min-width: $rfs-mq-value) {
  @each $breakpoint in map-keys($grid-breakpoints) {
    $infix: breakpoint-infix($breakpoint, $grid-breakpoints);

    @if (map-get($grid-breakpoints, $breakpoint) < $rfs-breakpoint) {
      // Loop over each utility property
      @each $key, $utility in $utilities {
        // The utility can be disabled with `false`, thus check if the utility is a map first
        // Only proceed if responsive media queries are enabled or if it's the base media query
        @if type-of($utility) == "map" and map-get($utility, rfs) {
          @include generate-utility($utility, $infix, true);
        }
      }
    }
  }
}


// Print utilities
@media print {
  @each $key, $utility in $utilities {
    // The utility can be disabled with `false`, thus check if the utility is a map first
    // Then check if the utility needs print styles
    @if type-of($utility) == "map" and map-get($utility, print) == true {
      @include generate-utility($utility, "-print");
    }
  }
}
```

I updated Leafo/scssphp to version 1.2.1 and the problem solved! Compiler now doesn't give any error, but if i enable "debug mode" i get error:
`An exception has been thrown during the rendering of a template ("`vendor/rfs` file not found for @import: line: , column: ").
`

Any suggestions how to fix this error?

I thing Leafo/scssphp compiler should be updated to the latest version to fix any compatibility issues like this on upcoming 
Bootstrap 5.

**Comment by LukeTowers** [comment]
@haralake are you using composer?

**Comment by haralake** [comment]
No i don't use composer

**Comment by LukeTowers** [comment]
@haralake I would recommend you switch to using composer. The marketplace update to v1.1 is coming, but it's faster to just switch to using composer now.

**Comment by haralake** [comment]
The error: `An exception has been thrown during the rendering of a template ("vendor/rfsfile not found for @import: line: , column: "). ` was just from my installation. So the updated Leafo/scssphp v1.2.1 works just fine without any problems. Marketplace v1.1 will solve this issue?

**Comment by LukeTowers** [comment]
@haralake we've switched to using scssphp/scssphp, so it will probably solve your problem. I highly recommend you just switch to using composer now so you can test it against your site now instead of waiting for the marketplace release to be available and maybe still having the issue.

**Comment by haralake** [comment]
Ok thank you @LukeTowers , i would do that
