### ISSUE TITLE
BackendAuth::register usage

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#5313]
I use the example code:
```
$user = BackendAuth::register([
    'name' => 'Some User',
    'login' => 'someuser',
    'email' => 'some@website.tld',
    'password' => 'changeme',
    'password_confirmation' => 'changeme'
]);
```
Location: https://octobercms.com/docs/backend/users#backend-auth-facade

I got the following error:
![error](https://user-images.githubusercontent.com/2959112/95964087-bb4f5d80-0e08-11eb-9987-654d1acf665b.jpg)

**Comment by LukeTowers** [comment]
It's first_name & last_name not name, was recently updated in the docs on github: https://github.com/octobercms/docs/blob/master/backend-users.md#backend-user-helper

**Comment by gergo85** [comment]
I changed the code, but the error message is same.  
October version: 1.0.469

**Comment by gergo85** [comment]
I use it in the beforeSave() method of my plugin. If I put it in the boot() method of Plugin.php I get the following error:

![error](https://user-images.githubusercontent.com/2959112/96087219-d03cf700-0ec3-11eb-8438-2730b4ac9133.jpg)

**Comment by LukeTowers** [comment]
@gergo85 try using v1.1.0 via composer instead.

**Comment by bhargavy** [comment]
> @gergo85 try using v1.1.0 via composer instead.

Updating via composer is throwing incompatible error

```
[InvalidArgumentException]
Package october/october at version 1.1.0 has a PHP requirement incompatible with your PHP version (7.0)
```
PHP Version 7.4.6

**Comment by gergo85** [comment]
How to update the website to v1.1.0 from v1.0.469?

**Comment by bennothommo** [comment]
@bhargavy @gergo85 you'll need to copy the updated `composer.json` file from [here](https://github.com/octobercms/october/blob/develop/composer.json) and apply that to your project - making sure to bring across any additional requirements you may have for your project (within `require` or `require-dev`). You should then be able to run `composer update` and get the necessary updates.

**Comment by LukeTowers** [comment]
@bhargavy sounds like your composer install or PHP CLI is running an older version of PHP than your web server.

**Comment by gergo85** [comment]
I did it and I got the following error message:

Warning: require(C:\xampp\htdocs\vendor\composer/../october/rain/src/Parse/Assetic/Less/lessc.inc.php): failed to open stream: No such file or directory in C:\xampp\htdocs\vendor\composer\autoload_real.php on line 66

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\vendor\composer/../october/rain/src/Parse/Assetic/Less/lessc.inc.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\vendor\composer\autoload_real.php on line 66

**Comment by LukeTowers** [comment]
delete vendor, modules, & composer.lock, then run composer install using the proper version of PHP and the updated composer.json.

**Comment by gergo85** [comment]
I deleted the folders and run the run composer install. The vendor/autoload.php file not generated.

![error](https://user-images.githubusercontent.com/2959112/96559242-0f50bb00-12bd-11eb-9d3c-2784f42b4cee.jpg)

**Comment by LukeTowers** [comment]
if you're not using the tests folder then remove the require-dev dependencies and the references to the test cases from your composer file.

**Comment by gergo85** [comment]
It works! Thank you very much!  
How to update the database?

**Comment by gergo85** [comment]
Unfortunately the issues are still there :(

**Comment by LukeTowers** [comment]
@bennothommo are you able to take a look at the original issue report with the register method failing?

**Comment by bennothommo** [comment]
@LukeTowers found the issue - it's that "guarded" attributes change that Laravel added recently. The `password_confirmation` field is being dropped from the data before validation because it doesn't correlate to a column in the users table, which causes validation to fail. We had to convert the `File` model to use [fillable attributes](https://github.com/octobercms/library/commit/6cd6af6940ca15598ad1bab64e2db4a005d9d38f) as opposed to guarded, but I'm not sure if we can do the same here because there's more likelihood that people are overwriting or extending the User model.

**Comment by LukeTowers** [comment]
@bennothommo would that affect them though if they weren't overriding the guarded / fillable attributes?

**Comment by gergo85** [comment]
Is there any quick solution to solve this issue? I need it for an active project.

**Comment by Samuell1** [comment]
@bennothommo shouldnt be `password_confirmation` defined with purgeable? https://octobercms.com/docs/database/traits#purgeable

**Comment by LukeTowers** [comment]
@bennothommo I haven't heard anything from @taylorotwell or @driesvints on our request for the original security report, so I'd say revert their final fix and replace it with the arrow fix instead.

**Comment by taylorotwell** [comment]
@LukeTowers just emailed you the original report.

**Comment by LukeTowers** [comment]
@gergo85 @bennothommo can you guys test https://github.com/octobercms/library/pull/533 and let me know if that resolves the issue?

**Comment by gergo85** [comment]
I replaced the vendor/october/rain foldet to new version, but the issues are still there.

**Comment by LukeTowers** [comment]
> I replaced the vendor/october/rain foldet to new version, but the issues are still there.

What did you do exactly?

**Comment by gergo85** [comment]
I deleted the files of vendor/october/rain folder and I copied the new version (github.com/octobercms/library) to this folder.

**Comment by LukeTowers** [comment]
You should check the files changed in https://github.com/octobercms/library/pull/533 manually and verify that they contain the changes from that PR.

**Comment by gergo85** [comment]
I use the fix/5313 branche, but the issue is same.

**Comment by mjauvin** [comment]
@LukeTowers I tested this PR and it's working as advertized!

**Comment by LukeTowers** [comment]
It seems to be working for @RomainMazB

**Comment by bennothommo** [comment]
Fixed by https://github.com/octobercms/library/pull/533.
