### ISSUE TITLE
Big backend menu

### ISSUE THREAD

**Issue by PrestaSafe** [octobercms/october#5315]
Hi ! 

The backend is very great, but, a lot of plugins generate item menu, and, the menu in back can be a mess really faster. 
The `collapsed` navigation is nice but not very efficiant. 

I think an other backend menu should be proposed with small entries and possibilities to collapse sub items. 
For exemple (PrestaShop backend menu)
<img width="229" alt="Capture d’écran 2020-10-15 à 14 17 07" src="https://user-images.githubusercontent.com/4788787/96122138-59b6ee00-0ef1-11eb-9e45-c42f1610780d.png">

Thanks to all the team for building and support Octobercms like you do !

**Comment by LukeTowers** [comment]
Feel free to submit a PR with screenshots

**Comment by xitara** [comment]
In the meantime you can take a look on my core-plugin, I use on nearly each october-projekt:

https://github.com/xitara/oc-plugin-core

there is a collapsable sidemenu for multiple plugins, seperate dashboard, custom-menus, sortable menus, optional icons and some more.
it's not perfekt but I think it can helps a lot on bigger projects

![Unbenannt](https://user-images.githubusercontent.com/26457767/96348577-279cbc00-10aa-11eb-89d9-afe5cf6a477e.png)

**Comment by PrestaSafe** [comment]
I'll try it, but it looks like to do the things i want ! 
Thanks
