### ISSUE TITLE
After upgrading to  build 469, can not log into backend, it  always redirects back to the login page

### ISSUE THREAD

**Issue by Brovtsin** [octobercms/october#5316]
After upgrading to build 469, when I try to log into the backend, it always redirects back to the login page. But if I enter the wrong credentials, an error occurs that the credentials are not valid.

**Comment by LukeTowers** [comment]
@Brovtsin what happens if you login with correct credentials, and then go straight to /backend in your browser?

**Comment by bennothommo** [comment]
@Brovtsin in addition to @LukeTowers comment above, do any errors regarding the cookie or redirection occur in your web developer toolbar in Chrome or Firefox?

**Comment by Brovtsin** [comment]
Thank you, for the reply!

> @Brovtsin what happens if you login with correct credentials, and then go straight to /backend in your browser?

If I go straight to the /backend, after login with correct credentials, it redirects me to /backend/backend/auth/signin.

If it's important I run my development under docker.




> @Brovtsin in addition to @LukeTowers comment above, do any errors regarding the cookie or redirection occur in your web developer toolbar in Chrome or Firefox?

No errors, only 302 redirects -

![image](https://user-images.githubusercontent.com/69000783/96216129-3ab76b00-0f88-11eb-9044-8320c2a06309.png)

**Comment by Brovtsin** [comment]
I can dump User from signin_onSubmit method of Auth controller

![image](https://user-images.githubusercontent.com/69000783/96218940-75bc9d00-0f8e-11eb-84da-e1451b6467c3.png)

and here is RedirectResponse dump

![image](https://user-images.githubusercontent.com/69000783/96220569-9d613480-0f91-11eb-9a50-3f0c990acb07.png)

**Comment by Brovtsin** [comment]
And then after $redirect->setRequest($this->generator->getRequest());
this is at line 189 of vendor/laravel/framework/src/Illuminate/Routing/Redirector.php
we have as result from $this->generator->getRequest() -
![image](https://user-images.githubusercontent.com/69000783/96221275-f8475b80-0f92-11eb-9733-6b041f7280d8.png)

**Comment by Brovtsin** [comment]
And finally if dd(Backend::redirectIntended('backend')); in modules/backend/controllers/Auth.php 

![image](https://user-images.githubusercontent.com/69000783/96222115-54f74600-0f94-11eb-8f6f-ca32a69c5997.png)

**Comment by Brovtsin** [comment]
I tried with fresh october cms  installation, and the same problem occurs. 
It seems, that problem in plugin, I created. Because if I delete the folder with my plugin, I can login to backend. But before upgrade to build 469 it was working good.

**Comment by Brovtsin** [comment]
So, the error occurred because of this line of code in my Plugin boot method - 
error_reporting(E_ALL & ~E_NOTICE);

**Comment by Brovtsin** [comment]
Had to reopen the issue, because unfortunately , removing  my plugin didn't work for docker environment . It still redirects me to log in page.
