### ISSUE TITLE
Validation stack errors not passing to events in settings section

### ISSUE THREAD

**Issue by summercms** [octobercms/october#5319]
I've noticed this over the years and to be honest, was a bit lazy to report it.

Basically add some regex validation rule to the models file and then pass an invalid regex combination through the rules validation.

October CMS then displays an error on the frontend web page.

BUT for some strange reason it never displays it in the backend event errors section?

This is a little bit of a pain in the ass, because I have to go into config/apps and turn on debugging to get the error message - not an idea situation when you have a `production` mode website.

Here is some screenshots:

### Debug turned off

![image](https://user-images.githubusercontent.com/57409060/96346415-a3d7d500-1093-11eb-8ee0-218356f4594f.png)

### Error Events Section

![image](https://user-images.githubusercontent.com/57409060/96346432-bce08600-1093-11eb-87dc-408587582bcf.png)

> Above: The issue opened here is because there is nothing being displayed in the backend event error section.

### Debug turned on

![image](https://user-images.githubusercontent.com/57409060/96346487-fd400400-1093-11eb-80ae-467ffcfc5f76.png)

As you can see from the above example, the error only shows on the frontend and the ideal situation is for October to show the error in both the frontend and backend.

Maybe this is an October error,
Maybe it's a Laravel error,
...who knows?

To be a bit more useful here is an example validation code (to repeat the following bug):

```php
public $rules = [
    'example' => [ 'regex:/([a-zA-Z0-9]+)/', 'max:50' ],
];
```

**Comment by LukeTowers** [comment]
Please post the frontend code you use to trigger the error

**Comment by summercms** [comment]
Will try and code a test plugin, to demo the error.

Have a question, how do we track `validation` errors in October? Right now they seem to not show up. I was thinking that it might be useful to create another section to track and monitor validation errors, something like this:

![image](https://user-images.githubusercontent.com/57409060/96367189-228c4b00-1144-11eb-8044-e1f352afcc39.png)

**Comment by LukeTowers** [comment]
Validation errors shouldn't be tracked, they're tools for informing the user that something they provided wasn't able to be processed by the system and how to fix it. Just like we explicitly do not log ApplicationExceptions, which are essentially just a way to manually trigger a validation error based on complex business logic. 

I would say probably the real issue here is in how your code is handling those errors, not that October isn't logging them.

**Comment by summercms** [comment]
Yah I think you're right, I need to invest deeper, thanks for the advise!
