### ISSUE TITLE
Twig function for `Form::number('name', 'value')` does not exist

### ISSUE THREAD

**Issue by zigi05** [octobercms/october#5320]
- OctoberCMS Build: 469 

### Description:
The https://octobercms.com/docs/services/html states that

> in Twig all functions prefixed with form_ will bind directly to the Form facade and provide access to the methods using snake_case

However, `{{ form_number('name', 'value') }}` for `Form::number('name', 'value')` facade method throws the following error:

> An exception has been thrown during the rendering of a template ("Method number does not exist.").

**Comment by bennothommo** [comment]
@zigi05 The `Form` facade is linked to the [`October\Rain\Html\FormBuilder`](https://github.com/octobercms/library/blob/develop/src/Html/FormBuilder.php) class, which does not have a number method. You could instead use `form_input` and use `number` as the first attribute (ie. `{{ form_input('number', 'fieldName', 'fieldValue') }}`)
