### ISSUE TITLE
Mail Configuration and .env file

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#5332]
- OctoberCMS Build: 469
- PHP Version: 7.4

### Description:

I setup an .env file with the corresponding command and I can't seem to be able to send any email from the `send test email` inside a `mail template`, here is the smtp mail config in the .env file:
as you can see there is no encryption, no user, no pwd, as my client is running his own smtp server internally.
are those values correct?

```
MAIL_DRIVER=SMTP
MAIL_HOST=10.100.0.5
MAIL_PORT=25
MAIL_ENCRYPTION=
MAIL_USERNAME=null
MAIL_PASSWORD=null
```

**Comment by bennothommo** [comment]
@chrisvidal Are there any settings specified in the **Mail Configuration** section of the Settings area in October CMS? It may be the case that these settings are being used instead.

**Comment by chrisvidal** [comment]
yes we have set the exact same settings.

actually we find the cause of the error, but I cant explain what is happening.

We revert back to the config without using any .env file, and now the mail is working. Also, this .env file seems to be related to some 403 forbidden access error.

**Comment by bennothommo** [comment]
@chrisvidal is this on Windows? If it's something that you think we can help mitigate in the future, it might be helpful to give us some idea of the cause, in case we can do something about it.

**Comment by chrisvidal** [comment]
yes on Windows Azure 2019 with SQLServer 2019. 
digging into the IIS config right now...
