### ISSUE TITLE
Custom search scope throws error

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#5333]
1. Add scope configuration option to config list.

```
    search:
        prompt: backend::lang.list.search_prompt
        scope: myScope
```

2. Define method in list model class `scopeMyScope($query, $term, $columns)`.

```
    public function scopeMyScope($query, $searchTerm, $columns)
    {
        return $query;
    }

```
3. Go to list and type something in list search form. This will throw error: `"Call to undefined method October\Rain\Database\QueryBuilder::myScope()"`

`dd($term)` goes inside my scope, so the scope is fired.

October version 469.

**Comment by danielbidala** [comment]
@mplodowski try to modify "myScope" to "MyScope" in config_list.yaml. Also I think there is only 2 arguments you can use, first is $query and second is $term.

I use custom search scopes all over in my app with v469 and it works as excepted!

**Comment by mplodowski** [comment]
I found more into this today. It works if a model specified in config_list is in the same namespace as controller (in the same plugin).

But I have situation that I want to use model from different plugin inside a config_list and the result is as I mentioned before.

@danielbidala There is no difference for scope name if it begins with lower or capital letter. 

You can use third parameter if you wish: https://github.com/octobercms/october/blob/develop/modules/backend/widgets/Lists.php#L1509

**Comment by LukeTowers** [comment]
@mplodowski please provide your more detailed configuration details with the model difference so we can attempt to replicate the issue.

**Comment by danielbidala** [comment]
@mplodowski yes you're right, the documentation doesn"t mention the third argument.
