### ISSUE TITLE
Child theme

### ISSUE THREAD

**Issue by PrestaSafe** [octobercms/october#5336]
Hi, 

Do you predict to implement a child / parent theme heritage ? (like wordpress or other cms)

This could be a really helpfull feature, mostly for updating theme. 
All of components params are written in the .htm files, if we update the theme, we loose that. 

It also great for overriden fonctionnality of default theme. 

Thanks to you.

**Comment by bennothommo** [comment]
@PrestaSafe it's been discussed before (for example, here: https://github.com/octobercms/october/issues/4309 and here: https://github.com/rainlab/pages-plugin/issues/237#issuecomment-282614908) - the main takeaway is that it's not going to change in core, but this feature could be implemented through a plugin. (@SebastiaanKloos is [working on one](https://github.com/kloos-dev/oc-themeupdate-plugin) right now)
