### ISSUE TITLE
Composer 2.0 is not compatible with the composer-merge-plugin

### ISSUE THREAD

**Issue by prhost** [octobercms/october#5339]
- OctoberCMS Build: ### 469
- PHP Version: 7.4

### Description:
I updated my composer and ran `composer update` I came across the error in print.
![Screen Shot 2020-10-29 at 15 32 40](https://user-images.githubusercontent.com/3984760/97617406-7cbac500-19fc-11eb-8999-d189f56d8447.png)

### Steps To Reproduce:
`composer self-update`
`composer update`

**Comment by LukeTowers** [comment]
Duplicate of https://github.com/wikimedia/composer-merge-plugin/issues/184

**Comment by LukeTowers** [comment]
Please test https://github.com/wikimedia/composer-merge-plugin/pull/189 with October and verify that it works so that it can be merged in and we can update

**Comment by prhost** [comment]
Hello @LukeTowers, thanks for the feedback. I tested it here with the branch `dev-composer20` and post on this issue (https://github.com/octobercms/october/issues/5033) duplicate that I found here in october the test result.
