### ISSUE TITLE
Idea : Permission to just manage meta on CMS > Page

### ISSUE THREAD

**Issue by Zmove** [octobercms/october#5341]
Hello,

I developped many websites using october and it's a fantastic tool, thanks to the whole team (core developpers and maintainers of the project).

I post this idea because this is something that come back with each project.

Actually, you just have one permission that give access to the whold CMS > Page system (allowing to create new pages, touch markup or code tabs etc....). It would be very interesting to give more granularity here.

Basically, the only reason I would give access to CMS > Page to the end user is to manage Meta title and description. But, as I don't want to offer him the possibility to break things, actually, I ask him to send me the meta he wants by email and change them for him.

It's a small thing, but a little annoying, and the customer generally don't understand, as all the rest of the website is just awesome, why he just can't change the meta by himself.

I precise that I don't use the static page plugin (don't really like the philosophy behind this), I prefer to setup page with CMS > page system, and give access to the customer to a frontend editor like [content editor](https://octobercms.com/plugin/samuell-contenteditor).

That's why I think it would be really useful to have some more permission here, one to give the possibility to create new page (without that, only editing is allowed), one to give access to the markup tab, one to give access to the code tab, and one for the metas.

What do you think about it ?

Best regards,

**Comment by xitara** [comment]
Why you don't use Static Pages Plugin that gives your customers a WYSIWYG editor without needs to change anything in "CMS"

Every of my customers has only access to "Pages" and on a proper planned projekt there is no need to change anything in "CMS" by the customer

**Comment by LukeTowers** [comment]
> I precise that I don't use the static page plugin (don't really like the philosophy behind this)

What's wrong with the "philosophy" of the RainLab.Pages plugin? The "CMS" section is primarily for developers, I don't recommend giving non-technical clients access to it, that's what the RainLab.Pages plugin is for.

You're always free to build whatever interface your heart desires in a custom plugin though, including locking down access to the CMS section or just having a completely custom way to modify that data.
