### ISSUE TITLE
Error executing "SendRawEmail" ... AWS HTTP error: count()

### ISSUE THREAD

**Issue by bkrajendra** [octobercms/october#5343]
- OctoberCMS Build: ### 469
- PHP Version: 7.4

### Description:
I am trying to use the SES option in Mail Configuration for sending emails.
I have configured my  Amazon SES and have got production access.

When I try to use SES SMTP credentials everything works fine.
But If tried using SES key, SES secret, I am getting the following error when sending the test email:

```
Error executing "SendRawEmail" on "https://email.ap-south-1.amazonaws.com"; AWS HTTP error: count(): Parameter must be an array or an object that implements Countable 
```

I am using **Access key ID** and **Secret access key** at SES key, SES secret in Mail Configuration
Hope this is correct 👆

### Steps To Reproduce:

Try sending an email by setting **SES** Mail Method in Mail configuration.

**Comment by LukeTowers** [comment]
Update to October v1.1 / Laravel 6 via composer.

**Comment by bkrajendra** [comment]
@LukeTowers , thanks for the quick reply. My website is live and doing it on a production instance is a bit risky.
I will try updating on some other instance.

Any idea we can get it in the upcoming Octobercms official release update?

**Comment by LukeTowers** [comment]
It's being worked on by @daftspunk @bkrajendra, the marketplace server needs some updates before it can be released via that channel.

**Comment by iPankajrai** [comment]
I'm also getting the same error, using AsgardCMS framework
"php": "=5.6.4",
"laravel/framework": "5.3.19"

Please someone help me to fix this issue.
