### ISSUE TITLE
Error Class Faker\Factory not found after updating website

### ISSUE THREAD

**Issue by aniket-magadum** [octobercms/october#5345]
- OctoberCMS Build: 465
- PHP Version: 7.3

### Description:
We ran an update for the website from the backend by visiting the Settings > Updates & Plugins Page. After the update, all pages display the following error.

![ocms-error](https://user-images.githubusercontent.com/48653948/97965946-23c6a480-1de1-11eb-98f7-f1e758d20473.png)

**Comment by LukeTowers** [comment]
Do you use Composer at all? What plugins do you have installed? Try disabling all your plugins and re-enabling them one-by-one until you figure out which one is causing the problems.

**Comment by bennothommo** [comment]
@LukeTowers the Faker library has been deprecated recently - that wouldn't have any effect on the marketplace build would it?

**Comment by aniket-magadum** [comment]
@LukeTowers Yes I found a plugin which was internally making use of faker library and it's now working

**Comment by LukeTowers** [comment]
@bennothommo no, the marketplace version just doesn't install any of the dev-dependencies. As I thought it was a misbehaving plugin.
