### ISSUE TITLE
Supported PHP version

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#5351]
Hi guys!

I noticed that in the docs we have:

![image](https://user-images.githubusercontent.com/3897579/98783197-3ad14c00-240a-11eb-96c2-619964af3a6d.png)

But in the `composer.json` we have:

![image](https://user-images.githubusercontent.com/3897579/98783222-47ee3b00-240a-11eb-8645-1cf570069f35.png)

So which one is correct here? When I started to use PHP 7.2 stuff in my plugins I got complains from users because their PHP version was too old.

**Comment by GinoPane** [comment]
Ah, it looks like that PHP 7.2 composer.json is not live yet.

**Comment by bennothommo** [comment]
@GinoPane we have updated the docs already (https://github.com/octobercms/docs/blob/master/setup-installation.md), but they won't go live on octobercms.com until October CMS 1.1 goes stable on the marketplace.

**Comment by GinoPane** [comment]
@bennothommo  Cool, thanks!
Yeah, I noticed this later. 
Do you maybe have any links (blog posts) showing the expected roadmap or what to expect from 1.1?

**Comment by bennothommo** [comment]
@GinoPane sure thing - here's the release notes for 1.1.0, which you can get via Composer now:
https://github.com/octoberrain/meta/blob/master/release-notes/build-1.1.0.md.

The release notes for 1.1.1, which is not yet released, can be found here:
https://github.com/octoberrain/meta/blob/master/release-notes/build-1.1.1.md.
