### ISSUE TITLE
Enable site admins to override plugin localization strings in the backend or via rainlab.translate?

### ISSUE THREAD

**Issue by lieszkol** [octobercms/october#5354]
Plugin localization strings stored in the lang subdirectory of a plugin directory can be overridden by devs by adding localization files to the app lang directory as [described in the docs](https://octobercms.com/docs/plugin/localization#overriding). 

However, this is of little use to site owners/admins (who aren't devs). I've tried to find any posts on this without success, even though I would think many owners of translated sites would want to provide localized translations for strings used by plugins without having to learn ftp etc. I did find [one similar question on StackOverflow](https://stackoverflow.com/questions/49054407/october-cms-translate-backend-with-rainlab-translate-plugin).

Here is my use case: On one of my client's sites we are using the awesome offline.mall plugin. This plugin sends out many emails (order received, confirmed, payment failed etc.). The text for these emails makes use of strings stored in the plugins language files, for example the language file for hungarian is at: `\plugins\offline\mall\lang\hu\mail.php`

As a dev, I can override this file by copying it into this directory (in the site's web root dir): `\lang\hu\offline\mall\mail.php`

Ideally the rainlab.translate plugin could be expanded with functionality to scan for messages in a given plugin's language files and enable the backend user to override these strings in the "Translate messages" backend page. Or, if we don't want to overload the user with too many translatable strings, another option would be to expand rainlab.translate to scan for (and override) messages already translated by the site admin which are stored in the site root `/lang/` subdirectory?

Or is there some other solution that I'm missing?

Thanks for considering my request.

Note: another option I considered was using the awesome [Developer Tools](https://octobercms.com/plugin/indikator-devtools) or the [Quick Edit](https://octobercms.com/plugin/indikator-qedit) plugins for this, but currently it's not possible either. I've [created an issue](https://github.com/gergo85/oc-devtools/issues/4) to ask INDIKATOR if he'd be open to expanding his plugin in this direction.

**Comment by mjauvin** [comment]
The `RainLab.Builder` plugin does this for plugin developed with it. You could reuse this functionality in a custom plugin I guess.

**Comment by mjauvin** [comment]
Actually, RainLab.Builder is perfect for this. You can acually manage localization files for all installed plugins, I thought this was only for plugins developed with it, but no.

**Comment by mjauvin** [comment]
Well, you can modify the plugin localization strings, but this is not an override... it's actually overwriting the original values in the plugin lang folder.

**Comment by lieszkol** [comment]
Thanks mjauvin for the ideas - yes, RainLab.Builder would be great if it would be possible to edit files stored in the site root /lang/ subdirectory, since then a dev could just copy any plugin language files there that the client wants access to.

**Comment by mjauvin** [comment]
I'm working on a new plugin that will do this. Will let you know when I have something working.

**Comment by lieszkol** [comment]
Well alrighty then! Looking forward to it :-)

**Comment by mjauvin** [comment]
@lieszkol here is the new plugin:

https://github.com/mjauvin/oc-localize-plugin

Just install this under `/plugins/r4l/localize` and run `php artisan october:up` to activate

Note: you need to install `RainLab.Builder` plugin first.

**Comment by lieszkol** [comment]
That's fantastic Marc, thanks a million! It doesn't cover my use case 100%, but I've created [an issue](https://github.com/mjauvin/oc-localize-plugin/issues/1) about that in your repo.
