### ISSUE TITLE
[Marketplace] Support for theme link previews

### ISSUE THREAD

**Issue by drmzio** [octobercms/october#5362]
On top of issue #4756, which was already implemented for plugin pages, could we have social link previews for theme pages as well? The sample code below should work for all open-graph supported sites and Twitter's image preview.

```html
<meta name="twitter:card" content="summary_large_image" />
<meta property="og:type" content="og:product" />
<meta property="og:title" content="Clean Blog" />
<meta property="og:image" content="https://assets.codepen.io/960508/Image+2020-11-23+at+4.42.54+PM.png" /> 
<meta property="og:description" content="Clean blogger theme." />
```

![](https://p193.p3.n0.cdn.getcloudapp.com/items/Wnul1kgo/Image%202020-11-23%20at%204.50.51%20PM.png?v=ff498d0fed475c1f59ca275ae5dd0cd2)

Thanks!

**Comment by daftspunk** [comment]
Done. It will appear in the next website update. Thanks!
