### ISSUE TITLE
Unexpected result when compiling Sass files

### ISSUE THREAD

**Issue by PictureElement** [octobercms/october#5364]
1. I use `<link href="{{['assets/sass/rapido.scss']|theme}}" rel="stylesheet">`
2. rapido.scss (master stylesheet) imports all required styles:
```
@import "settings";
@import "overrides";
@import "../vendor/rfs/scss";
@import "../vendor/bootstrap/scss/bootstrap";
@import "fonts";
...
@import "footer";
@import "keyframes";
```
3. I've set `'enableAssetDeepHashing' => true in config/cms.php`
4. The structure of my assets directory is:
```
sass
  ├── _header.scss
  ├── _footer.scss
  ├── ...
  └── rapido.scss
vendor
   ├── bootstrap
  	       ├── scss
  	             ├── mixins
  	             ├── utilities
  	             ├── vendor
                 ├── _grid.scss
                 ├── _toasts.scss
                 ├── ...
                 ├── bootstrap.scss
   ├── rfs
        ├── scss.scss
```

**Issues**
1. Looking at the compiled CSS, the `.container` class, has no `max-width` set to it, at each responsive breakpoint. I don't have this problem when using `gulp-sass` on my static implementation.
2. The responsive font sizes (rfs/scss.scss) mixins don't work.
The following:
```
.space-py-8 {
    @include padding-top(8rem);
    @include padding-bottom(8rem);
}
```
Compiles to:
```
.space-py-8 {
    padding-top: if(type-of($values) != list, ($values,), $values);
    padding-bottom: if(type-of($values) != list, ($values,), $values);
}
```
And this:
```
body {
    @include font-size(1rem);
}
```
Compiles to:
```
body {
    font-size: if(type-of($values) != list, ($values,), $values);
}
```
Again, I don't have this problem when using `gulp-sass` on my static implementation.

**Comment by LukeTowers** [comment]
Are you using the latest version of October? Currently v1.1.1 available through composer.

**Comment by PictureElement** [comment]
I use Build 469. Is there any command I can use to check the October version?

**Comment by LukeTowers** [comment]
There is, but it doesn't support v1.1 right now unfortunately :) If you're not using Composer then you don't have the latest version as it's currently only available through composer.
