### ISSUE TITLE
Need Help: Composer Install on Local Environment (XAMPP + Windows 10)

### ISSUE THREAD

**Issue by PictureElement** [octobercms/october#5373]
I am facing an issue while installing October on local machine. I followed these steps:

1. Download the source code in `xampp/htdocs` using `composer create-project october/october myoctober`
2. Disable core updates: `disableCoreUpdates' => true`
3. Use `php artisan october:install`

By the end of step 3 I get the following error:
```
Migrating application and plugins...
SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = myoctober and table_name = migrations and table_type = 'BASE TABLE')1
```

My configuration is:
```
MySQL Host: 127.0.0.1
MySQL Port: 3306
Database Name: myoctober
MySQL Login: root
MySQL Password: 12345678
Application URL: http://localhost/myoctober/
```

I tried the following:
1. Uncomment `RewriteBase /` in `.htaccess` and set it to `RewriteBase /myoctober/`
2. Enable mod rewrite module in `httpd.conf`: `LoadModule rewrite_module modules/mod_rewrite.so`
3. Switch on Allow override option in  `httpd.conf`:
```
<Directory />
    AllowOverride All
    Require all denied
</Directory>
```

Do I miss something. Any help would be greatly appreciated.

**Comment by LukeTowers** [comment]
You'll need to verify that your MySQL server is up and running and that the credentials you provided are correct. The error you are receiving is saying that it can't connect to MySQL. You could also try using SQLite instead.

**Comment by LukeTowers** [comment]
As a side note, GitHub issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Discord: https://discord.gg/gEKgwSZ
Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
