### ISSUE TITLE
Extending a controller with RelationController twice will throw `has already been extended`

### ISSUE THREAD

**Issue by TimFoerster** [octobercms/october#5376]
- OctoberCMS: 1.1.x
- PHP Version: 7.4
- Plugins Installed: Rainlab.User

### Description/Problem:
When two or more plugins extends a controller with the `RelationController` via
```php 
            if (!$controller->isClassExtendedWith('Backend\Behaviors\RelationController')) {
                $controller->extendClassWith(\Backend\Behaviors\RelationController::class);
            }
```
 only the first `$relationConfig` will be available. 

The documented approach throws an `Class RainLab\User\Controllers\Users has already been extended with Backend\Behaviors\RelationController` Exception
```php 
            if (!$controller->isClassExtendedWith('Backend\Behaviors\RelationController')) {
                $controller->implement[] = 'Backend\Behaviors\RelationController';
            }
```

### Alternative approach:
Instead of checking with `isClassExtendedWith` validate if `$implement[]` holds `RelationController` already

```php
            if (!in_array( 'Backend\Behaviors\RelationController', $controller->implement)) {
                $controller->implement[] = 'Backend\Behaviors\RelationController';
            }
```

Unfortunately I never saw this approach.

### Steps To Reproduce:

1. Create two plugins, or use existing ones and and extend the Users controller.
```php
class PluginA extends PluginBase {

    public function boot() {

        \RainLab\User\Controllers\Users::extend(function($controller) {

            // Define property if not already defined
            if (!isset($controller->relationConfig)) {
                $controller->addDynamicProperty('relationConfig');
            }

            // Splice in configuration safely
            $myConfigPath = '$/test/plugina/controllers/users/config_relation.yaml';

            $controller->relationConfig = $controller->mergeConfig(
                $controller->relationConfig,
                $myConfigPath
            );

            // Implement behavior if not already implemented
            if (!$controller->isClassExtendedWith('Backend\Behaviors\RelationController')) {
                $controller->implement[] = 'Backend\Behaviors\RelationController';
            }
        });

        User::extend(function ($model) {
            $model->hasMany['rela'] = [User::class,
                'key' => 'user_id'
            ];
        });

        
        Event::listen('backend.form.extendFields', function($widget) {
            if (!$widget->getController() instanceof \RainLab\User\Controllers\Users) {
                return;
            }
            if (!$widget->model instanceof \RainLab\User\Models\User) {
                return;
            }
            $widget->addTabFields([
                'rela' => [
                    'label' => 'Rela',
                    'tab' => 'rela',
                    'type' => 'partial',
                    'path' => '~/plugins/test/plugina/controllers/users/_rela.htm'
                ]
            ]);
        });
   }
}
```

```php
class PluginB extends PluginBase {

    public function boot() {

        \RainLab\User\Controllers\Users::extend(function($controller) {

            // Define property if not already defined
            if (!isset($controller->relationConfig)) {
                $controller->addDynamicProperty('relationConfig');
            }

            // Splice in configuration safely
            $myConfigPath = '$/test/pluginb/controllers/users/config_relation.yaml';

            $controller->relationConfig = $controller->mergeConfig(
                $controller->relationConfig,
                $myConfigPath
            );

            // Implement behavior if not already implemented
            if (!$controller->isClassExtendedWith('Backend\Behaviors\RelationController')) {
                $controller->implement[] = 'Backend\Behaviors\RelationController';
            }
        });

        User::extend(function ($model) {
            $model->hasMany['relb'] = [User::class,
                'key' => 'user_id'
            ];
        });
        Event::listen('backend.form.extendFields', function($widget) {
            if (!$widget->getController() instanceof \RainLab\User\Controllers\Users) {
                return;
            }
            if (!$widget->model instanceof \RainLab\User\Models\User) {
                return;
            }
            $widget->addTabFields([
                'relb' => [
                    'label' => 'Relb',
                    'tab' => 'relb',
                    'type' => 'partial',
                    'path' => '~/plugins/test/pluginb/controllers/users/_relb.htm'
                ]
            ]);
        });
   }
}
```

2. Example configs:
```yaml
relationA:
  label: RelationA
  view:
    list: $/test/plugina/models/r/columns.yaml
    recordUrl: $/foo
  manage:
    list: $/test/plugina/models/r/columns.yaml
    preview: $/test/plugina/models/r/fields.yaml
```

```yaml
relationB:
  label: RelationB
  view:
    list: $/test/pluginb/models/r/columns.yaml
    recordUrl: $/foo
  manage:
    list: $/test/pluginb/models/r/columns.yaml
    preview: $/test/pluginb/models/r/fields.yaml
```

3. partial `/plugins/test/plugina/controllers/users/_rela.htm`
```php
<?= $this->relationRender('rela') ?>
```
4. partial `/plugins/test/pluginb/controllers/users/_relb.htm`
```php
<?= $this->relationRender('relb') ?>
```
5. Render user preview:  `Class RainLab\User\Controllers\Users has already been extended with Backend\Behaviors\RelationController`

**Comment by bennothommo** [comment]
@TimFoerster hmmm, this is a tricky situation, in the sense that it could cause clashes with both plugins if they share the same relation name (however unlikely that may be, given that ostensibly the two plugins would be working with different sets of related data).

My view is that you shouldn't use two plugins that affect the same controller in this manner, but I realise that this may be unavoidable if you're working with third-party plugins.

I don't have an answer for this right now - I'll have to give it some thought. Perhaps @LukeTowers might be able to offer an additional opinion towards this.

**Comment by LukeTowers** [comment]
> Unfortunately I never saw this approach.

@TimFoerster that's the documented way to dynamically add behaviours, see https://octobercms.com/docs/services/behaviors. `extendClassWith()` isn't even documented in the Behaviors documentation, where did you come across it / what made you go with that approach?

**Comment by TimFoerster** [comment]
@LukeTowers
Basically in Mall:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/e795eef5ce59e94acc59a9477163a17ba01d9ffe/classes/registration/BootExtensions.php#L73-L75

I found also another plugin
https://github.com/octoshop/addressbook/blob/3150adb67336dcf352e31bde3eb89f7a7968bd34/Plugin.php#L73


The documented approach throws an exception with more than one plugin.
`Class RainLab\User\Controllers\Users has already been extended with Backend\Behaviors\RelationController`
because `isClassExtendedWith('Backend.Behaviors.RelationController')`  is false when extending the controller with `$controller->implement[] = 'Backend\Behaviors\RelationController';`

So when the controller is booted up, `$controller->implement` has two `'Backend\Behaviors\RelationController'` entries.

This is the only way that i found to extend the controller without getting an exception (`1.1.x-dev branch`, php7.4), didn't tested 1.0
```
            if (!in_array( 'Backend\Behaviors\RelationController', $controller->implement)) {
                $controller->implement[] = 'Backend\Behaviors\RelationController';
            }
```

Edit: I updated the initial post.

**Comment by daftspunk** [comment]
What might be the issue here is that is conflating 'extend now' with 'extend later'

- Manipulating $implement will extend later - use a check on the array to see if its there already
- Manipulating via `extendClassWith` will extend now - use `isClassExtendedWith` to see if its there already

Therefore this code will not work

            if (!$controller->isClassExtendedWith('Backend\Behaviors\RelationController')) {
                $controller->implement[] = 'Backend\Behaviors\RelationController';
            }

Since it suggests 

- if class is not extended now, extend it later

Whereas it may already be extended by this same class later and throw an error. All plugins should be using `extendClassWith` and `isClassExtendedWith`, they should not be manipulating the `$implement` object.

That will resolve a lot of these issues. Ping me on this issue if anything requires further elaboration. Thanks 🙏

**Comment by iboved** [comment]
@daftspunk the isClassExtendedWith() method always returns **false** for controllers. It works only for models.

Just for test, add this to your Plugin.php boot() method:
```
        \RainLab\User\Controllers\Users::extend(function ($controller) {
            $check = $controller->isClassExtendedWith('Backend.Behaviors.FormController');
        });
```

Users controller implements Backend.Behaviors.FormController, but this code always returns **false**.

**Comment by daftspunk** [comment]
@iboved It should work the same for models and controllers. However, it returns false because the class hasn't been extended yet, the `extend` method occurs before any implemented extensions.

We will address this in the v2.2 release, thanks 🙏
