### ISSUE TITLE
Changes not applied from htm or css

### ISSUE THREAD

**Issue by abdufarag** [octobercms/october#5378]
- OctoberCMS Build: ### 
- PHP Version: 7.3
- Database Engine: mysql
- Plugins Installed: spot/shipment vdomah roles 
- theme: spotlayer

### Description:
when I make changes to htm page I cant see the changes even if iI have disabled totally the page for testing it still work as no updates made , I update the htm changes of the theme under theme/pages/dashboard . even tried the same under vendor but stil the changes not affected.
Some times it works fine and other times nothing working on the same page!

### Steps To Reproduce:
1. open page: themes/spotlayer/pages/dashboard/settings.htm
added fields and removed other fields

2. refresh the front end page /dashborad/settings
Expected behaviour: should see the changes (actually some times it works)
Result: No changes to the page

**Comment by LukeTowers** [comment]
Sounds like a caching issue. Do you have any caching plugins installed? Are you using a CDN or other caching layer on your network or server stack? Did you try running `php artisan cache:clear`?

**Comment by abdufarag** [comment]
I have found the issue , it was due to the following:
before I made any changes I have copied the template file for example settings.htm to settings-backup.htm 
this made the system took the first alphabetical file first and ignored th rest of files since the are the same view 
So what I have seen is settings-backup.htm 
I have solved this issue by taking backup files outside and keep only the working files in the system

**Comment by mjauvin** [comment]
best way to do this @abdufarag is to copy to `settings.htm.bak` then it shouldn't be picked-up as a template file

**Comment by abdufarag** [comment]
> best way to do this @abdufarag is to copy to `settings.htm.bak` then it shouldn't be picked-up as a template file
