### ISSUE TITLE
Backend throws error when no theme is installed

### ISSUE THREAD

**Issue by aniket-magadum** [octobercms/october#5381]
I just set up a new October cms instance via composer on my computer. The installation was successful. But when I removed the demo theme and plugin through the `php artisan october:fresh` command. I get this error while accessing the backend

![image](https://user-images.githubusercontent.com/48653948/101139276-50b3e480-3637-11eb-933d-a4c60ee8dfec.png)

Possible Fix
Replace modules\cms\ServiceProvider.php: 317 
From

```php
$langPath = $theme->getPath() . '/lang';
```

To

```php
$langPath = isset($theme) ? $theme->getPath() . '/lang' : null;
```

**Comment by bennothommo** [comment]
Thanks for the report @4nik3t
