### ISSUE TITLE
Wrong week numbers in datepicker

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#5388]
- OctoberCMS Build: 471
- PHP Version: 7.4
- Database Engine: MySQL 8.0

### Description:

Datepicker shows wrong week numbers.

The issue is described here and it was fixed in latest version: https://github.com/Pikaday/Pikaday/issues/878

**Comment by LukeTowers** [comment]
Feel free to submit a PR to update the included version of pikaday.

**Comment by robinbonnes** [comment]
Same issue. Did test the PR, and it seems fixed. Can we merge this?
