### ISSUE TITLE
Update beyond #469?

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#5389]
I can't seem to be able to update any my website beyond OC#469?

did I miss any announcement or new requirement?

**Comment by Eoler** [comment]
> I can't seem to be able to update any my website beyond OC#469?

Build 471 is available with edge updates: https://octobercms.com/changelog
Laravel 6+ builds are composer only at the moment, (not so?) patiently waiting for marketplace version...

**Comment by chrisvidal** [comment]
got it, thanks @Eoler
