### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by al-sultani** [octobercms/october#5392]
Hey there, 

I reported a security issue in OctoberCMS a week ago and I haven't heard back from your side. 
Can you please check it out. 

Best, 

Abdullah Hussam

**Comment by summercms** [comment]
@ahussam 

The best method I find to report security issues is to:

1. Join https://octobercms.slack.com/

2. Contact @LukeTowers in that group

- When I use the emails in https://github.com/octobercms/october/blob/develop/SECURITY.md I often don't get a reply.

Maybe Luke might consider updating the security page to mention this option?

**Comment by mjauvin** [comment]
@ayumi-cloud slack is now reserved for premium support. He should use Discord listed on the Support Page.

**Comment by LukeTowers** [comment]
If you submitted a security report according to our security policy then you will always get a response. I did not receive any emails from you, so I don't know anything about your report.

Please resend it to octobercms@luketowers.ca

**Comment by al-sultani** [comment]
@LukeTowers done! check your email

**Comment by LukeTowers** [comment]
@ahussam got it thanks, reviewing it and I'll get back to you.
