### ISSUE TITLE
Allow users to turn php safe mode on/off in the cms editor and not need to edit the config files everytime

### ISSUE THREAD

**Issue by summercms** [octobercms/october#5407]
I find this feature highly annoying!

![image](https://user-images.githubusercontent.com/57409060/102254680-dfaae180-3f00-11eb-946b-6965aff42f9c.png)

Currently I have to then stop what I'm doing, open the `cms` config file change the value to `false` then go back to the cms page and do a refresh and start again!

Is there anyway we could change it to something like this:

![image](https://user-images.githubusercontent.com/57409060/102255191-9eff9800-3f01-11eb-838f-63458e30236f.png)

I'm not saying the exact styling as it looks horrible in the example screenshot. But where we can just turn it on/off directly in the cms screen.

A cleaner suggestion:

![image](https://user-images.githubusercontent.com/57409060/102259091-952c6380-3f06-11eb-8ca5-af015f29d72d.png)

and

![image](https://user-images.githubusercontent.com/57409060/102259312-d91f6880-3f06-11eb-8f01-09f827c72c67.png)

Then click the `Safe Mode` to toggle the selection on/off.

**Comment by mjauvin** [comment]
@ayumi-cloud that would kind of defeat the purpose...

**Comment by ayumi-cloud** [comment]
@mjauvin 

>
>    | Safe mode
>    |--------------------------------------------------------------------------
>    
>    If safe mode is enabled, the PHP code section is disabled in the CMS
>    for security reasons. If set to null, safe mode is enabled when
>    debug mode (app.debug) is disabled.

So if I read this correctly? Why not display the `Safe Mode` button to certain admin types.

For example:

Admin 1 is a core developer sees this:

![image](https://user-images.githubusercontent.com/57409060/102259091-952c6380-3f06-11eb-8ca5-af015f29d72d.png)

Admin 2 is a third-party developer sees this:

![image](https://user-images.githubusercontent.com/57409060/102261116-213f8a80-3f09-11eb-9e37-f690443317d6.png)

Have an option in the `Administrators` section to allow privileges for `Safe Mode`.

**Comment by ayumi-cloud** [comment]
@mjauvin 

>
>    | Safe mode
>    |--------------------------------------------------------------------------
>    
>    If safe mode is enabled, the PHP code section is disabled in the CMS
>    for security reasons. If set to null, safe mode is enabled when
>    debug mode (app.debug) is disabled.

So if I read this correctly? Why not display the `Safe Mode` button to certain admin types.

For example:

Admin 1 is a core developer sees this:

![image](https://user-images.githubusercontent.com/57409060/102259312-d91f6880-3f06-11eb-8f01-09f827c72c67.png)

Admin 2 is a third-party developer sees this:

![image](https://user-images.githubusercontent.com/57409060/102259091-952c6380-3f06-11eb-8ca5-af015f29d72d.png)

When the admin 2 hovers the mouse over the `Safe Mode (ON)` it displays a help tip saying:

```
PHP code section is disabled to gain access update privileges!
```

Have an option in the `Administrators` section to allow privileges for `Safe Mode`.

**Comment by summercms** [comment]
@mjauvin 

Going to close this issue, though I've been reading this issue: https://github.com/octobercms/october/issues/1756

I need to spend some time looking deeper into it. To me it doesn't seem right, if someone did breach the backend you could easily get around `Safe Mode` just by downloading and installing a plugin to allow you to inject php etc. I'm sure there are loads of ways getting round this.

**Comment by mjauvin** [comment]
It's not so much as to prevent problems with a hacked website as to prevent a problem with a dumb customer with admin access to break the CMS page code part which he probably should not play with in the first place.

**Comment by LukeTowers** [comment]
@ayumi-cloud it's entirely possible to give a backend user access to the CMS section without giving access to manage plugins.
