### ISSUE TITLE
[Dirvers plugin] Upgrade dependent to make Dirvers plugin compatible with php7.4

### ISSUE THREAD

**Issue by everyx** [octobercms/october#5409]
- OctoberCMS Build: v1.1.1
- PHP Version: 7.4
- Database Engine: MySQL
- Plugins Installed: 
Ompmega.MixHelper,
Martin.Forms,
Mohsin.txt,
VojtaSvoboda.TwigExtensions,
October.Drivers,
Zaxbux.DOStorageDriver

### Description:
We need upgrade dependent version of aws/aws-sdk-php version to 3.128.1 or later.
![image](https://user-images.githubusercontent.com/1665522/102299153-6f966d00-3f8d-11eb-8004-b628b286787c.png)

### Steps To Reproduce:
install plugin and user digitalocean storage filesystem disk.

**Comment by LukeTowers** [comment]
@everyx please submit a PR to the Drivers plugin here: https://github.com/octoberrain/drivers-plugin including a bump to the version.yaml and the composer requirements.

**Comment by everyx** [comment]
> @everyx please submit a PR to the Drivers plugin here: https://github.com/octoberrain/drivers-plugin including a bump to the version.yaml and the composer requirements.

@LukeTowers PR just created, please review and merge. :)

**Comment by LukeTowers** [comment]
@everyx done! Thanks very much.
