### ISSUE TITLE
October AJAX doesn't work because it's still getting blocked due to using `EVAL`

### ISSUE THREAD

**Issue by summercms** [octobercms/october#5425]
This issue was first raised way back in 2018 and 2 years later still not fixed! People have been reporting this issue as not fixed for the last 6 months!

See here: https://github.com/octobercms/october/issues/3608

Error message (NOT WARNING MESSAGE)

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src .."
```

### framework.combined-min.js

Code line: 

https://github.com/octobercms/october/blob/develop/modules/system/assets/js/framework.combined-min.js#L38

![image](https://user-images.githubusercontent.com/57409060/103000898-d7b3f880-4523-11eb-9e3c-eb7742431d72.png)

### framework.js

Code line: 

https://github.com/octobercms/october/blob/develop/modules/system/assets/js/framework.js#L168

![image](https://user-images.githubusercontent.com/57409060/103001323-aee03300-4524-11eb-9a94-f44cd1116ecd.png)

### Problematic Code Lines

https://github.com/octobercms/october/blob/5591e3fa945ad3c181ccedd9b759e12127b09f3e/modules/system/assets/js/framework.js#L146

https://github.com/octobercms/october/blob/5591e3fa945ad3c181ccedd9b759e12127b09f3e/modules/system/assets/js/framework.js#L168

https://github.com/octobercms/october/blob/5591e3fa945ad3c181ccedd9b759e12127b09f3e/modules/system/assets/js/framework.js#L215

https://github.com/octobercms/october/blob/5591e3fa945ad3c181ccedd9b759e12127b09f3e/modules/system/assets/js/framework.js#L225

### Reasons to Avoid Using `eval()`

Unless you are doing really high-level JavaScript the risks usually outweigh the benefits of using `eval()`. Here’s some of the reasons to avoid using it:

- **Malicious code**: invoking `eval` can crash a computer. For example: if you use `eval` server-side and a mischievous user decides to use an **infinite loop** as their username.

- **Terribly slow**: the JavaScript language is designed to use the full gamut of JavaScript types (numbers, functions, objects, etc). Not just strings! Using `eval` is orders of magnitude **slower than normal JavaScript code**.

Please can we remove using `eval()`.

### Useful Links

- [MDN eval()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval)

**Comment by mjauvin** [comment]
@ayumi-cloud can you link the non-combined source instead?

**Comment by ayumi-cloud** [comment]
Sure, let me add both locations, going to run a new test for the non-combined version as well.

**Comment by summercms** [comment]
Ok done 👍

**Comment by mjauvin** [comment]
what do you suggest we use instead?

**Comment by ayumi-cloud** [comment]
> what do you suggest we use instead?

Not sure we did test a few things just now in the office and all failed so far. We were also talking about `framework` having two kinds of builds:

- A modern build (for up-to-date browsers), which is not transpiled with Babel and without any included polyfills.
- A ES5-compatible build (can be used e.g. with IE11), which is transpiled with Babel and includes all necessary polyfills.

**Comment by ayumi-cloud** [comment]
Also should block off `Flash`

https://github.com/octobercms/october/blob/5591e3fa945ad3c181ccedd9b759e12127b09f3e/modules/system/assets/js/framework.js#L78-L80

See here: https://docs.microsoft.com/en-us/lifecycle/announcements/adobe-flash-end-of-support

**Comment by summercms** [comment]
> what do you suggest we use instead?

Not sure we did test a few things just now in the office and all failed so far...

Up for any suggestions. 🙂

**Comment by LukeTowers** [comment]
Closing because the original issue contains our proposed fix (i.e. don't use the data-request API if you need CSP support and refactor the internals that use the data-request API to use the JS API instead).
