### ISSUE TITLE
The Contributing to OctoberCMS file is missing the artisan complier commands

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#5427]
The file found here: https://github.com/octobercms/october/blob/develop/.github/CONTRIBUTING.md

I need to know two things, which that document is missing:

1. The artisan complier command for LESS
2. The artisan complier command for Javascript

Please update the doc's so we can submit pr's correctly.

**Comment by seanthepottingshed** [comment]
`php artisan october:util compile js`
`php artisan october:util compile less`

**Comment by ayumi-cloud** [comment]
@seanthepottingshed seanthepottingshed

Thanks lol - can finish my pr now 🥇

**Comment by seanthepottingshed** [comment]
@ayumi-cloud 

No worries, if you run `php artisan` it will list all available commands ;)

**Comment by ayumi-cloud** [comment]
Thanks, I added it to the wiki anyway.

https://github.com/octobercms/october/wiki/Artisan-compiler-commands

**Comment by LukeTowers** [comment]
This should have been a discussion probably, and these commands are already documented here: https://octobercms.com/docs/console/commands#october-util-command
