### ISSUE TITLE
Extending form fields in rainlab.user using repeater rendering whole fieldset from widget instead of only required form.fields from addFields

### ISSUE THREAD

**Issue by snipiba** [octobercms/october#5441]
- OctoberCMS Build: 470 
- PHP Version: 7.4
- Database Engine: Mysql 8.0
- Plugins Installed: 
RainLab.User, Drivers, Builder, Translation, RainLab.Blog...

### Description:

When i updated (extending) form fields and using repeater type field, then rendered form contains whole (repeating) fields from addFields, not from only main setup of form.fields.

### Steps To Reproduce:

See https://github.com/rainlab/user-plugin/issues/462

**Comment by snipiba** [comment]
Probably less documented funcionality 
```
if($widget->isNested === false) { 
/**
 add fields only in primary row of fields
**/
}
```

**Comment by LukeTowers** [comment]
@snipiba I'm pretty sure that's documented, but do you have any recommendations on where it could be emphasized?

**Comment by snipiba** [comment]
@LukeTowers i found it @ https://octobercms.com/docs/plugin/extending ... in "note box"... probably better calling was **important**. I found solution only with luck @ discussion https://octobercms.com/forum/post/extending-a-form-with-a-repeater-widget-using-addfields-or-addtabfields-includes-all-fields-of-the-parent-form ...

**Comment by LukeTowers** [comment]
@snipiba made some changes in https://github.com/octobercms/docs/commit/ccfe60f4f2aecf23982dcba15fa51a633449cf7b, take a look and let me know if that helps make it more clear.

**Comment by snipiba** [comment]
@LukeTowers perfect.. good job
