### ISSUE TITLE
Assetic FileAsset doesn't respect cms.restrictBaseDir

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#5450]
- october/rain: ~1.1.0
- PHP Version: 7.4

### Description:
The FileAsset class does not respect the option to set `cms.restrictBaseDir` to false. It returns an exception with message `The source "..." is not in the root directory "..."`.

### Steps To Reproduce:
- Create a new component in a plugin which is symlinked to `/plugins`
- Add the following code to the component and replace with your paths:
``` php
public function prepareAssets()
    {
        $css = $this->combineAssets([
            'component.css',
        ], plugins_path('your-component-css-directory-path'));

        $js = $this->combineAssets([
            'component.js',
        ], plugins_path('your-component-js-directory-path'));

        $this->addCss($css);
        $this->addJs($js);
    }
```

Code responsible for the exception:
https://github.com/octobercms/library/blob/026d4bb511f4b4ce4162363937f1d28c9af359f8/src/Assetic/Asset/FileAsset.php#L44

**Comment by SebastiaanKloos** [comment]
Possible fix would be to change:

``` php
0 !== strpos($source, $sourceRoot)
```

to 

``` php
0 !== strpos($source, $sourceRoot) && Config::get('cms.restrictBaseDir', true)
```

What do you think?

**Comment by LukeTowers** [comment]
@SebastiaanKloos did you try just doing the following instead:

```php
$this->addCss(['css/component.css']);
$this->addJs(['js/component.js']);
```

**Comment by daftspunk** [comment]
@SebastiaanKloos yes, give it a try what is suggested here and it should work. If that doesn't work just ping me in this ticket and we can look at it again
