### ISSUE TITLE
Target [Illuminate\Contracts\Auth\Access\Gate] is not instantiable.

### ISSUE THREAD

**Issue by loreberti89** [octobercms/october#5455]
Hello I'm trying to build a plugin for manage Telescope on my app, but when I use the Gate facade I have this error:
`Target [Illuminate\Contracts\Auth\Access\Gate] is not instantiable.
`
In my Plugin I'm trying simply this:

```
class Plugin extends PluginBase
{

    public function boot(){

        Gate::define('viewTelescope', function ($user) {
            return in_array($user->email, [
                //
            ]);
        });
    }
    public function registerComponents()
    {
    }

    public function registerSettings()
    {
    }
}
```

Initially I have tried to put 

`App::register(TelescopeServiceProvider::class);`

But the error was same.

**Comment by Rike-cz** [comment]
Hello, I think you need to use `\Illuminate\Auth\Access\Gate`. Your `\Illuminate\Contracts\Auth\Access\Gate` is interface only.

**Comment by loreberti89** [comment]
Nope, I found, I had to add    `$this->app->register(\Illuminate\Auth\AuthServiceProvider::class);` before.
ThankYou
