### ISSUE TITLE
Breaking change in getParameter method

### ISSUE THREAD

**Issue by marcbrouwer** [octobercms/october#5457]
- OctoberCMS Build: 470 / v1.1.1 (behaviour changed compared to build 469)

### Description:
The getParameter method in modules/cms/classes/Router.php has a breaking change. See the discussion in https://github.com/octobercms/october/pull/4908

If an optional parameter is not set it always results into 0 (false). In the case of an optional parameter :param?, which is not set, the results are always 0/false for the following cases:

```
$this->param('param')
$this->param('param', 'Some default value')
```

Not setting a default parameter value resulted into null in build 469, whereas after the change it results into false. The code below simulates the behaviour:

```
<?php

// simulating call to getParameter(string $name, string $default = null)
$parameters = [ 'param' => false ]; // simulating $this->parameters
$name = 'param';
$default = null;

// code before change
if (isset($parameters[$name]) && ($parameters[$name] === '0' || !empty($parameters[$name]))) {
	var_dump($parameters[$name]);
}

var_dump($default);
```
The above results into null and the below results into false

```
<?php

// simulating call to getParameter(string $name, string $default = null)
$parameters = [ 'param' => false ]; // simulating $this->parameters
$name = 'param';
$default = null;

// code after change
$value = $parameters[$name] ?? '';
var_dump($value !== '' ? $value : $default);
```
The code after the change also will never return the default value as the parameter is set to false by default

**Comment by daftspunk** [comment]
Rolled it back c9c58d2858668a1d78b8c3f7955dd8851b4c8c9c
