### ISSUE TITLE
Allow disabling the auto group_concat behaviour on list column select properties for multi relations

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#5461]
In https://github.com/octobercms/october/blob/develop/modules/backend/widgets/Lists.php#L502-L504 the `select` property of a column that references a `relation` with multiple associated record is automatically wrapped in a `group_concat()` call to automatically concatenate all of the results of the select query into a comma separated string. 

This is fine behaviour by default, but a problem arises when attempting to use a DB engine that doesn't support group_concat (i.e. Postgres or SQL Server) or when attempting to do more complex `select` queries, such as summing a column on all the related records.

A new property, `selectAutoConcat`(open to suggestions for better names) should so that the current behaviour can be disabled by the developer when they want to handle those more advanced use cases.

**Comment by Rike-cz** [comment]
@LukeTowers What about sorting inside `group_concat`? https://github.com/octobercms/october/pull/5424

**Comment by LukeTowers** [comment]
Hmm, I would probably say that once this is implemented #5424 would become unnecessary since you could just write out that SQL yourself. Seems like it might be a bit too magical to implement #5424. @bennothommo any thoughts?

**Comment by Rike-cz** [comment]
If you think using `ORDER `inside `GROUP_CONCAT`(), it's [standard](https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_group-concat) I think. But @bennothommo can have different opinion.

**Comment by daftspunk** [comment]
For complex scenarios like this, it should be handled by a custom column select using the list extension feature. It's basically the same thing and `select` acts as a defacto helper for this

**Comment by Rike-cz** [comment]
@daftspunk It could, but I think some ordering inside October's native `group_concat` feature is required. Now it shows items in [random order](https://github.com/octobercms/october/pull/5424#issuecomment-750027843).
