### ISSUE TITLE
Proposal: October to start using cookie prefix on it's session cookie to prevent smuggle cookie

### ISSUE THREAD

**Issue by summercms** [octobercms/october#5462]
When a user has the following settings:

- Cookie `Secure` set to `true`
- Using `https` scheme
- Hasn't add a hard-coded security cookie prefix already

October CMS then changes the config `session.cookie` and inject the following `__Secure-` prefix to the front of the session cookie as an enhanced security measure!

For example:

```
    'cookie' => 'october_session',
```

Would turn into:

```
    'cookie' => '__Secure-october_session',
```

Also add in the `config_session.php` file an option to choose between `Secure` and `Host` - if people want to go the extra mile.

Code line:
https://github.com/octobercms/october/blob/47b2aa0f15fb44d8902c17d5150bc19e2eecdbe0/config/session.php#L112

For more information read here: https://tools.ietf.org/html/draft-ietf-httpbis-cookie-prefixes-00#section-3.1

Most software platforms have been doing this for a long time now! October needs to play catch up and add this.

**Comment by LukeTowers** [comment]
I don't understand what the point of doing that is. 

> an enhanced security measure!

What exactly makes this an improvement to security? What does this accomplish?

**Comment by ayumi-cloud** [comment]
@LukeTowers 

It is desirable to make secure cookies writable only from secure origins. However, changing this at once will break sites that use this functionality.

Cookie prefixes make it possible to flag your cookies to have different behaviour, in a backward compatible way. It uses a dirty trick to put a flag in the name of the cookie. When a cookie name starts with this flag, it triggers additional browser policy on the cookie in supporting browsers.

- The `__Secure-` prefix makes a cookie accessible from HTTPS sites only. A HTTP site can not read or update a cookie if the name starts with `__Secure-`. This protects against the cookie smuggling attack, where an attacker uses a forged insecure site to overwrite a secure cookie.

- The `__Host-` prefix does the same as the `__Secure-` prefix and more. A `__Host-` prefixed cookie is only accessible by the same domain it is set on. This means that a **subdomain can no longer overwrite the cookie value.**

Demo Page: https://googlechrome.github.io/samples/cookie-prefixes/

---

1. I'm proposing to make the `__Secure-` prefix the `default` in October.

2. I'm proposing that October automatically adds a security cookie prefix as a fallback if the user doesn't add one themselves.

3. I'm also proposing adding a section in the `session.php` config file to allow users to choose between `__Secure-` and `__Host-` again this will be set to `__Secure-` as default.

4. The cookie prefix will only be applied to `https` websites and `session.secure` set to true.

5. Backwards compatibility, as many October websites have not set their cookies to include prefixes, this will automatically upgrade their cookies, while they don't need to do anything.

6. This has been shipped in `Chrome`, `Edge` and `Firefox` a long time ago.

7. Browsers that don't understand cookie prefixes will ignore them.

**Comment by summercms** [comment]
@LukeTowers 

It is desirable to make secure cookies writable only from **secure origins**. However, changing this at once will break sites that use this functionality.

Cookie prefixes make it possible to flag your cookies to have different behaviour, in a backward compatible way. It uses a dirty trick to put a flag in the name of the cookie. When a cookie name starts with this flag, it triggers additional browser policies on the cookie in supporting browsers.

- The `__Secure-` prefix makes a cookie accessible from HTTPS sites only. A HTTP site can not read or update a cookie if the name starts with `__Secure-`. This protects against the cookie smuggling attack, where an attacker uses a forged insecure site to overwrite a secure cookie.

- The `__Host-` prefix does the same as the `__Secure-` prefix and more. A `__Host-` prefixed cookie is only accessible by the same domain it is set on. This means that a **subdomain can no longer overwrite the cookie value.**

Demo Page: https://googlechrome.github.io/samples/cookie-prefixes/

---

1. I'm proposing to make the `__Secure-` prefix the `default` in October.

2. I'm proposing that October automatically adds a security cookie prefix as a fallback if the user doesn't add one themselves.

3. I'm also proposing adding a section in the `session.php` config file to allow users to choose between `Secure` and `Host` again this will be set to `__Secure-` as default.

4. The cookie prefix will only be applied to `https` websites and `session.secure` set to `true`.

5. Backwards compatibility, as many October websites have not set their cookies to include prefixes, this will automatically upgrade their cookies, while they don't need to do anything.

6. This has been shipped in `Chrome`, `Edge` and `Firefox` a long time ago.

7. Browsers that don't understand cookie prefixes will ignore them, e.g. IE11

8. When a user selects `Host` setting in the config file the attribute `Path=/` will get added to the end of the cookie.

Let me know your thoughts - gathering feedback, before doing a pr.

**Comment by LukeTowers** [comment]
What browsers support these values but don't support the related settings / flags they correspond to? I don't really understand the difference between this and `session.secure`.

**Comment by summercms** [comment]
@LukeTowers done some digging for you and found this from the past (2015).

Link: https://groups.google.com/a/chromium.org/g/blink-dev/c/IU5t6eLuS2Y/m/Uq-7Kat9BwAJ

> # Summary
> This feature adds a set of restrictions upon the names which may be used for cookies with specific properties. These restrictions enable user agents to smuggle cookie state to the server within the confines of the existing "Cookie" request header syntax, and limits the ways in which cookies may be abused.
> 
> In a nutshell: `$Secure-*` cookies have to have the `Secure` flag, and `$Origin-*` cookies have to have `Path=/`, can't have `Domain`, and might require `Secure` (depending on the setter).
> 
> This seems like the simplest thing that might possibly work.
> 
> # Motivation
> Cookies are terrible. This proposal _might_ make them slightly less terrible, by addressing the "Weak Confidentiality" and "Weak Integrity" concerns spelled out in RFC 6265.
> 
> The syntax is fairly hideous, but practical: 
> 
> * No new behavior is defined; the spec is predicated upon enforcement of existing flags.
> 
> * No new syntax is defined; the spec is completely backwards compatible.
> 
> * No server needs to change anything other than the name of the cookie it sets. Browsers that support the feature will enforce existing flags, browsers that don't support the feature won't.
> 
> * The client-side changes to perform the validation checks are fairly small.

Got this conversation as well:

```
Cookies are a bit of a rough edge on the web's security model. They don't
respect the same origin policy, and the disconnect between their
persistence model and that of the rest of the platform causes no end of
teeth-gnashing and hair-pulling among developers and auditors alike. We're
planning a few changes to bring things into something more closely
resembling alignment:

1.  `secure` ought to mean "secure": Though it's well-known that cookies
cross back and forth over protocol boundaries, recent research
<https://www.usenix.org/system/files/conference/usenixsecurity15/sec15-paper-zheng.pdf>
from
Zheng, et al. has highlighted the fact that this behavior remains
surprising to developers, and also that there's little practical recourse
without changes in the browser.

We intend to make it more difficult for non-secure origins to influence the
state of secure origins by preventing non-secure origins from writing
cookies with a 'secure' flag and overwriting cookies whose 'secure' flag is
set. We're also planning to tweak the eviction rules to ensure that a
host's non-secure cookies are removed before its secure cookies. These
changes are spelled out in more technical detail in an Internet Draft
<https://tools.ietf.org/html/draft-west-leave-secure-cookies-alone> we've
submitted to the IETF for consideration.

The metrics we've gathered show impact to about 0.02% of `Set-Cookie`
operations. Those numbers exclude deletions. Mozilla's metrics
<https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2015-11-19&keys=__none__!__none__!__none__&max_channel_version=release%252F42&measure=COOKIE_SCHEME_SECURITY&min_channel_version=null&product=Firefox!Fennec&sanitize=1&sort_keys=submissions&start_date=2015-10-29&table=0&trim=1&use_submission_date=0>
show similar impact (and include deletions). We don't have metrics

2.  "secureness" should be verifiable from the server-side: We've
implemented Eric Lawrence's clever Cookie Prefixes proposal
<http://textslashplain.com/2015/10/09/duct-tape-and-baling-wirecookie-prefixes/>
as a lightweight mechanism which gives servers the ability to assert
certain properties about cookies they set and receive.

In short, cookies whose names begin with `$Secure-` may only be set from
secure origins, and must have the `secure` flag. Cookies whose names begin
with `$Host-` have the same restrictions, and must additionally have a path
of `/` and no `domain` attribute. This brings them as close to the
same-origin policy as we can get with existing attributes. These changes
are likewise spelled out in more technical detail in the Internet Draft
<https://tools.ietf.org/html/draft-west-cookie-prefixes> we've submitted.

3. Ambient authority should have an opt-out: We're looking at ways to deal
with the CSRF risks that cookies' ambient authority present. We have a
mostly-complete implementation of First-Party-Only cookies
<https://tools.ietf.org/html/draft-west-first-party-cookies>, which gives
servers the ability to assert that a particular cookie ought only be sent
in a "first-party" context by appending a `first-party-only` flag to the
`Set-Cookie` operation. The hope is that this will make certain kinds of
attacks significantly more difficult by preventing `third-party.com` from
making authenticated requests against `first-party.com`'s endpoints. Again,
details are in the Internet Draft
<https://tools.ietf.org/html/draft-west-first-party-cookies>.
```

Lastly, here's the code in Chrome to view what they are doing: https://codereview.chromium.org/1485763003

**Comment by summercms** [comment]
The info I gave you in the previous comment, explains the reasons why cookie-prefixes are used and suggests to use:

```
$Secure-
```

When it was in Chrome 49 under a flag, it was discovered that the `$` gave an issue even though the spec said it was ok to use. So they changed the `$` to a `__` which fixed the issue.

```
__Secure-
```

Just to make you aware.

**Comment by LukeTowers** [comment]
Any chance you can clarify it further? I'm having a hard time understanding the actual practical benefits of prefixing a cookie name over just setting the appropriate flags when creating the cookie, and I don't have time to dig through a ton of material to try to understand it for myself. I'm currently sitting in the hospital with my wife and second kid after an emergency c-section, I've got a crapload of client work (no less than 4 separate client projects all of which are overdue, and 4 entirely separate commitments to Cadets Canada) to take care of while also having to take care of my first kid that's a toddler while my wife recovers over the next few months.

All of that to say, if it's not easy for me to understand the practical benefits of something and any potential future maintenance requirements, I simply don't have the time or energy to process it anytime in the next six months. Hence, if you want to push through changes faster you'll need to invest more time and energy up front making it easy for me to make those decisions under these conditions

**Comment by summercms** [comment]
@LukeTowers You should let the other admins look after this repo (more), while you are so busy! Focus more of your time with your personal stuff and split the work load between the other admins. I'm sure they will be happy to help and they are all very good at running this repo.

A quick summary to this issue, cookie prefixes protect https (secure) cookies from `non same-site's` and from `other http websites`. Developers think `secure` gives them full protection with the https, but in truth it doesn't and the prefix fully protects the cookie by adding extra flags in the browser which adds an extra layer of protection - by blocking cookies from non same-site's. Hope that makes sense as a really brief overview.

p.s. Good luck and I wish your wife a speedy recovery!

**Comment by LukeTowers** [comment]
> You should let the other admins look after this repo (more), while you are so busy! 

That's not the problem, @bennothommo and @mjauvin already help out a tremendous amount. Non-trivial changes like this simply aren't going to be merged in without the core team fully understanding it because they (i.e. me in this case) have to maintain it going forward. We've been bitten too many times by just rushing in a merge that someone wants when we don't fully understand it only to later have to spend time to rip it out and revert it or work around the issue to implement a proper fix. Far easier for everyone involved if we take the time up front to fully understand everything that is being done with the platform.

**Comment by ayumi-cloud** [comment]
@LukeTowers Sure totally understand, do you get the concept with this now or can the `Status: Response Needed` label be removed now and I got a green light to code a pr some time in the near future.

**Comment by summercms** [comment]
@LukeTowers Sure totally understand, do you get the concept with this now and the `Status: Response Needed` label can be removed now?
