### ISSUE TITLE
Too Many Attempts

### ISSUE THREAD

**Issue by pavelmgn** [octobercms/october#5467]
Hello, I have problem
![image](https://user-images.githubusercontent.com/8817759/105148808-9dd71180-5b24-11eb-9bc8-236e9c4427d2.png)

```
'middleware' => ['throttle:3600,1', Auth::class, ConvertEmptyStringsToNull::class, 'api']
```

how can i increase the limit? If i write in routes.php in my plugin middleware with throttle:3000,1 - not working, but x-rate-limit in header wrote me 3000, with error on screenshot. Thx.

**Comment by bennothommo** [comment]
@pavelmgn please post this in the [Discussions](https://github.com/octobercms/october/discussions) or try one of the following avenues for help.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Discord: https://discord.gg/6S777kh
