### ISSUE TITLE
Mail HTML content gets trimmed when top-level text-node is found 

### ISSUE THREAD

**Issue by bradietilley** [octobercms/october#5469]
- OctoberCMS Build: 470 
- PHP Version: 7.4, 7.3

### Description:

If you have an HTML mail template that contains a top-level text-node, the HTML content after (and including) the text-node are stripped from the rendered email template.

For example, the following mail template content would be stripped:

```twig
subject = "Test email"
==
<p>Should I stay?</p> or <p>Should I go now?</p>
```

Instead of `<p>Should I stay?</p> or <p>Should I go now?</p>` it would be stripped to `<p>Should I stay?</p>`.

### Workaround

The issue seems to be easily worked around by performing one of the following actions:

Remove text-node or wrap it in an element, such as `<p>`

```twig
subject = "Test email"
==
<p>Should I stay?</p> <p>or</p> <p>Should I go now?</p>
```

Wrap all top-level nodes in parent element

```twig
subject = "Test email"
==
<div>
    <p>Should I stay?</p> or <p>Should I go now?</p>
</div>
```

### Steps To Reproduce:

1. Create new mail template with 2x top-level elements and a top-level text-node in between (e.g. example above)
2. Register this mail template (e.g. `acme.test::mail.test`)
3. Send an email using this template (e.g. `Mail::send('acme.test::mail.test')`)

You should then receive the email containing only the first HTML element.

### Deeper look

The message goes through various classes with the correct template then it reaches the `Parsedown` class:

`MailManager.php#143:`             `$html = $this->renderTemplate($template, $data);`
`MailManager.php#189:`             `$html = $this->render($template->content_html, $data);`
`MailManager.php#180:`             `$html = Markdown::parseSafe($html);`
`Markdown.php#74:`                 `$result = $this->parse($text);`
`Markdown.php#46:`                 `return $this->parseInternal($text);`
`Markdown.php#103:`                `$result = $this->getParser()->$method($result);`
`ParsedownExtra.php#46:`           `$markup = parent::text($text);`
`Parsedown.php#39:`                `$markup = $this->lines($lines);`

It appears that `Parsedown->lines()` is modifying the HTML content and stripping the text-node and content after.

I don't imagine this would be intentional as it's still technically valid HTML. A quick fix (although a bit hacky) would be to wrap the content in a `<div>` element before passing it down for parsing, then unwrap the div on the way back up.

**Comment by LukeTowers** [comment]
> I don't imagine this would be intentional as it's still technically valid HTML

Are unwrapped text nodes actually valid HTML? Just because a browser will render them doesn't necessarily mean they're valid HTML.

**Comment by bradietilley** [comment]
I understand what you mean, although I would say the nodes inside these partials should [almost] never be treated as top level nodes as they're always nested within some other form of HTML. If these partials were dispatched on their own (i.e. no layout) then I would for sure understand them being stripped, but all mail partials have a parent layout (and layouts are [probably] never empty).

The issue at hand is LIKE the following example: You have a top level `<td>` element in a mail template that is a child partial to a layout that contains: `<tr>{partial-here}</tr>`. Yes, the `<td>` element(s) on their own are definitely invalid, but not in the context used.

Another example would be an alert component/partial that has the following content: `<div class="alert alert-{{type}}">{% partial 'alert-content' message=message %}</div>`, and then the 'alert-content.htm' partial contains the following: `Your account has been suspended`. The HTML content inside `alert-content.htm` is invalid, but it's not valid within the parent div.

While I understand this is definitely low priority, it's likely people run into this issue every now and then. For me I came across this because there was a stray semi-colon that I accidentally had floating around in my mail template, and half of the email was missing. Thankfully the project is still in development and the email had nothing important (codes, reset links, etc) so no harm no foul.

In my opinion, provided it doesn't affect others negatively, the following should be changed:

```php
$html = Markdown::parseSafe($html);
```
to
```php
$html = substr(Markdown::parseSafe('<div>' . $html . '</div>'), 5, -6); // or something a little more stable
```

Just a thought anyway :)

**Comment by LukeTowers** [comment]
Your suggested fix seems pretty decent to me, any thoughts on the above @bennothommo?

**Comment by bennothommo** [comment]
@LukeTowers I agree (fair disclosure: @bradietilley is my colleague, and we've been discussing this in-house) :P

**Comment by LukeTowers** [comment]
Oh ho, an undercover agent eh? 😂 As long as we include some unit tests for it I'm fine with having that fix made into a PR @bradietilley

**Comment by daftspunk** [comment]
I was unable to replicate this using 1.0 or 1.1 branches

```
Message-ID: <b325487a05021ffe0deaa28c863f3837@octoberdev.test>
Date: Mon, 08 Mar 2021 08:03:56 +0000
Subject: test
From: October CMS <noreply@octobercms.tld>
To: Admin Person <admin@domain.tld>
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="_=_swift_1615190636_6a5deeb76b1df48401c64c37df2615c7_=_"

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body style="font-family: Avenir,Helvetica,sans-serif; box-sizing: border-box; background-color: #f5f8fa; color: #74787e; height: 100%; hyphens: auto; line-height: 1.4; margin: 0; -moz-hyphens: auto; -ms-word-break: break-word; width: 100% !important; -webkit-hyphens: auto; -webkit-text-size-adjust: none; word-break: break-word;"><p style="font-family: Avenir,Helvetica,sans-serif; box-sizing: border-box; color: #74787e; font-size: 16px; line-height: 1.5em; margin-top: 0; text-align: left;">Should I stay?</p></body></html>

Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<p>Should I stay?</p> or <p>Should I go now?</p>  
```

**Comment by daftspunk** [comment]
Turns out this is an issue in the Markdown parser, not with October CMS. Take care gentlemen 🙏

**Comment by chocolata** [comment]
Hi guys...  Just stumbled upon this... When I try to inject some HTML in an order confirmation mail, this exact scenario happens.

The HTML that I'm trying to inject is:

```
<p>Don't forget about your hotel!</p>
<p>Be sure to book your hotel with our event hotel partners at a great discount and within walking distance of the venue.<br>Book your hotel here: <a href="https://hotel.com" target="_blank">hotel.com</a></p>
```

I'm injecting it into a mail template as follows:

```
{% for product in order.products %}
    {% if product.item.confirmation_mail_content_enabled %}
	{% partial 'panel' body %}
	    {{ product.item.confirmation_mail_content|raw }}
	{% endpartial %}
    {% endif %}
{% endfor %}
```

Doesn't matter what I do, I always end up with only the first sentence:
![image](https://github.com/octobercms/october/assets/3584586/52a8ce61-28fb-460a-b66f-4f9634de9d58)

I understand that this is an issue regarding an external library, but does anyone have a quick solution for this usecase? 

Please note that the html comes from a database table and differs from product to product... Thanks for helping out.

**Comment by chocolata** [comment]
For anyone experiencing the same issue, the solution was as simple as removing the `| md_indent` filter from `{{ body | md_indent }}` inside the panel partial... As @daftspunk stated it has to do with the MarkDown processing - something that I thankfully can omit in my usecase.

**Comment by daftspunk** [comment]
Hey @chocolata 

It's a known issue with the parser with a relatively simple fix. The solution is documented here: 
https://docs.octobercms.com/3.x/extend/services/parser.html#using-html-in-markdown
