### ISSUE TITLE
october_session: A 'set-cookie' has an invalid 'expires' date format.

### ISSUE THREAD

**Issue by 0hra** [octobercms/october#5471]
- OctoberCMS Build: 470 / v1.1.1
- PHP Version: 7.4
- Database Engine: MySQL
- Plugins Installed: Builder/User/Drivers

### Description:
Did a scan of my application in Firefox with the webhint addon (https://addons.mozilla.org/nb-NO/firefox/addon/webhint/)
A security warning shows up for the october_session cookie:
> A 'set-cookie' has an invalid 'expires' date format. The recommended format is: Fri, 26 Jan -2021 05:48:19 GMT

The invalid date format in question: 
> Tue, 26-Jan-2021 05:48:19

**The same can be reproduced in Microsoft Edge with no third party addons.**

### Steps To Reproduce in Firefox with addon:
1. Open october website in Firefox with the webhint addon installed (https://addons.mozilla.org/nb-NO/firefox/addon/webhint/)
2. Inspect and open "Hints" tab.
3. Do a scan and look for the warning under "security"

### Steps To Reproduce in Edge:
1. Open webpage in Edge and inspect it.
2. Go to 'Console' tab and then choose "view issues".
3. Refresh page, open the "Security" dropdown.

**Comment by LukeTowers** [comment]
This sounds like an issue for Laravel or Symfony, not October. Try asking there first and then report back with what you find.
