### ISSUE TITLE
Calling sync() twice on many-to-many relationship fails in the dev branch, works in 1.0

### ISSUE THREAD

**Issue by cjkpl** [octobercms/october#5479]
- OctoberCMS Build: Develop branch; tested with laravel 6.18.43 or 6.20.15
- PHP Version: 7.4.8
- Database Engine: MySql (also fails in SqLite)
- Plugins Installed: https://github.com/cjkpl/oc-sync-plugin (contains the test case)

### Description:
Having two models, e.g. Student and Lesson, and many to many relationship between them, calling sync() second time fails:
```
        $s = Student::first();
        $l = Lesson::first();

        $s->lessons()->sync([$l->id]);
        $s->lessons()->sync([$l->id]);
```

### Steps To Reproduce:
1. Install a test plugin prepared to demonstrate the issue: https://github.com/cjkpl/oc-sync-plugin.git
2. Run unit test on the plugin.
3. Observed behavior: will work on the 1.0 branch (with Laravel 5.x); will throw and error on dev branch (with Laravel 6.x).

**Comment by LukeTowers** [comment]
What's the error message @cjkpl?

**Comment by cjkpl** [comment]
@LukeTowers 
```
Cjkpl\Sync\Tests\Models\PivotTest::testPivot
Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: cjkpl_sync_lessons_students.lesson_id, cjkpl_sync_lessons_students.student_id (SQL: insert into "cjkpl_sync_lessons_students" ("created_at", "lesson_id", "student_id", "updated_at") values (2021-01-28 18:34:17, 1, 1, 2021-01-28 18:34:17))
```
The 2nd call does not see the 1st call executed, and attempts to re-insert with the same keys. 
IMHO [the pivot table is constructed properly](https://github.com/cjkpl/oc-sync-plugin/blob/main/updates/create_ls_pivot_table.php), so it is not an issue of missing composite key.

I have also described it on the [OctoberCMS forum](https://octobercms.com/forum/post/calling-sync-twice-on-many-to-many-fails).

Thanks for looking into it.

**Comment by LukeTowers** [comment]
This sounds like it could be an issue with the relationship or the in-request DB query cache not being reloaded after the sync write action completes. @mjauvin would this have been caused by any of your recent changes?

**Comment by mjauvin** [comment]
possibly. @cjkpl, can you check if https://github.com/octobercms/library/pull/550 fixes this for you?

**Comment by cjkpl** [comment]
Hi @LukeTowers , hi @mjauvin ,

I confirm that using the two files from [#550](https://github.com/octobercms/library/pull/550) (BelongsToMany.php, DefinedConstraints.php) fixed the "unique constraint" issue.

However, after writing additional tests, I have discovered a new issue, which is also present in branch 1.0. 
Namely, after updating the contents of the pivot table (by any means: detach+attach, sync, or updateExistingPivot) there is no way to retrieve the new data: $model->fresh(), $model->refresh(), $model->load('relation') all fail. Even creating a new instance of the model fails to see the updated content. 
Since the relation is many-to-many, I can retrieve the new pivot content "from the other end", which confirms that the data is correctly written to the intermediary table. I have updated tests in my test plugin, and here is the code of the failing test:
```php
        // create one lesson and one student
        $s = Student::create([]);
        $l = Lesson::create([]);

        $sid = $s->id;

        $s->lessons()->sync([$l->id => ['visits' => 1]]);
        $v = $s->lessons()->where('id',$l->id)->first()->pivot->visits;

        // increase a value on intermediary table
        $new_v = intval($v) + 1;

        // update value on intermediary table
        $s->lessons()->sync([$l->id => ['visits' => $new_v]]);

        // when we access the relationship from the "other end", it works
        $v = $l->students()->where('id',$s->id)->first()->pivot->visits;
        self::assertEquals($new_v, $v, 'expect \'visits\' column contain 2'); //all good

        // ... but when we try to re-use the original model, it fails
        // this fails $s->fresh('lessons');
        // this also fails $s = Student::find($sid);

        $v = $s->lessons()->where('id',$l->id)->first()->pivot->visits;
        self::assertEquals($new_v, $v, 'expect \'visits\' column contain 2'); //still contains 1
```

**Comment by LukeTowers** [comment]
@cjkpl try running `Student::flushDuplicateCache()` before attempting to access the new data.

**Comment by LukeTowers** [comment]
or Teacher, it's a shared cache that can be flushed from any model class.

**Comment by cjkpl** [comment]
Wow, it works - both in 1.0 and in dev. 
And I totally missed that in the docs, even though it actually is there.

@LukeTowers - huge thanks for your help. 
I hope that [PR550](https://github.com/octobercms/library/pull/550) will be merged into dev very soon, so that the 'unique constraint' problem goes away permanently.

**Comment by LukeTowers** [comment]
@mjauvin could we work clearing that cache into the syncing method or any other methods that write to the DB?

**Comment by mjauvin** [comment]
@cjkpl could you test if the following change solves the issue with sync?
```
diff --git a/src/Database/Relations/BelongsToMany.php b/src/Database/Relations/BelongsToMany.php
index 373f3fc..ddeb50e 100644
--- a/src/Database/Relations/BelongsToMany.php
+++ b/src/Database/Relations/BelongsToMany.php
@@ -333,6 +333,7 @@ class BelongsToMany extends BelongsToManyBase
         // Perform sync when the model is saved
         $this->parent->bindEventOnce('model.afterSave', function () use ($value) {
             $this->sync($value);
+            $this::flushDuplicateCache();
         });
     }

```

**Comment by mjauvin** [comment]
Or this:
```
diff --git a/src/Database/Relations/BelongsToMany.php b/src/Database/Relations/BelongsToMany.php
index 373f3fc..2f21a0b 100644
--- a/src/Database/Relations/BelongsToMany.php
+++ b/src/Database/Relations/BelongsToMany.php
@@ -333,6 +333,7 @@ class BelongsToMany extends BelongsToManyBase
         // Perform sync when the model is saved
         $this->parent->bindEventOnce('model.afterSave', function () use ($value) {
             $this->sync($value);
+            $this->flushDuplicateCache();
         });
     }
```

**Comment by cjkpl** [comment]
Hi @mjauvin,

I'm sorry, but none of these two works.

Please see this [simple plugin](https://github.com/cjkpl/oc-sync-plugin.git) I prepared - it contains two unittests. 
In both dev and 1.0 one of the assertions fails - the one involving flushDuplicateCache(). If you use dev without your earlier correction (#550), two assertions will fail.

**Comment by mjauvin** [comment]
Thanks for providing a plugin to reproduce the problem @cjkpl, I'll look into this.

**Comment by mjauvin** [comment]
@cjkpl try this patch, I verified it resolved the tests failing in your plugin:
```
diff --git a/src/Database/Relations/BelongsToMany.php b/src/Database/Relations/BelongsToMany.php
index 373f3fc..7c4bfdc 100644
--- a/src/Database/Relations/BelongsToMany.php
+++ b/src/Database/Relations/BelongsToMany.php
@@ -88,6 +88,18 @@ class BelongsToMany extends BelongsToManyBase
         return $model;
     }
 
+    /**
+     * Override sync() method of BelongToMany relation in order to flush the query cache.
+     * @param array $ids
+     * @param bool $detaching
+     * @return array
+     */
+    public function sync($ids, $detaching = true)
+    {
+        parent::sync($ids, $detaching);
+        $this->flushDuplicateCache();
+    }
+
     /**
      * Create a new instance of this related model with deferred binding support.
      */
```

**Comment by cjkpl** [comment]
Hi @mjauvin,

Thank you, I can see from the code above that it will resolve the issue - I'm looking forward to seeing this and #550 integrated into DEV :-)

**Comment by cjkpl** [comment]
Hi @mjauvin,

Sadly, the pivot trouble continues ;-(

While the changes so far and the tests work fine (in SQLite), updating the pivot thing crashes with MySQL, when the pivot contains any column names overlapping those of the relation table. I have updated my test plugin (cjkpl.sync) to illustrate this - it passes all tests in SQLite, fails in MySQL. I also added a component "syncMe" - if you put it on any page with MySQL database, it will raise an exception with a message:

```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in field list is ambiguous (SQL: update `cjkpl_sync_lessons_students` inner join `cjkpl_sync_lessons` on `cjkpl_sync_lessons`.`id` = `cjkpl_sync_lessons_students`.`lesson_id` set `student_id` = 1, `lesson_id` = 1, `visits` = 0, `created_at` = 2021-02-28 17:31:23, `updated_at` = 2021-02-28 17:31:23 where `student_id` = 1 and `lesson_id` in (1))
```

The same happens whether we define ```'timestamps' => true``` in $belongsToMany, or we add timestamps as custom columns via ```'pivot' => ['created_at','updated_at'],```, and it affects any columns with names identical as in the relation table.

**Comment by bennothommo** [comment]
@cjkpl We are aware of this from another PR which is in progress - https://github.com/octobercms/library/pull/563. As a fix for the moment, you may want to include the relation or model name in front of the field (ie. for a relation `post`, it should be `post.created_at`).

**Comment by cjkpl** [comment]
Hi @bennothommo
Thanks for your reply and for the workaround. I'll do as you suggest for new models (I've already renamed the offending columns as a temporary workaround, and I'm handling timestamps manually).
