### ISSUE TITLE
Button attribs work, Anchor attribs don't in tables

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#548]
Playing around with modals. having a tough time with anchors not accepting attributes. The page just reloads when I click the anchor. No JS errors.

```php
<!-- doesn't work -->
<a data-dismiss="modal" data-control="popup" data-handler="<?= $this->getEventHandler('onLoadUpdateOptionModal') ?>" data-request-data="id: '<?= $option->id ?>'"><?= $option->title ?></a>
 
<!-- does work -->
<button data-dismiss="modal" data-control="popup" data-handler="<?= $this->getEventHandler('onLoadUpdateOptionModal') ?>" data-request-data="id: '<?= $option->id ?>'">Update</button>
```

**Comment by daftspunk** [comment]
This is caused by the october.rowlink.js plugin and is intentional, it will find the first anchor link and use it for the row click event. The anchor is destroyed in the process, so any data-request/popup binding is lost.

You need to add `class="nolink"` to your anchor to overcome this.
