### ISSUE TITLE
svgIcon width and height of sideMenu

### ISSUE THREAD

**Issue by bossleem** [octobercms/october#5488]
- OctoberCMS Build: v1.1.1
- PHP Version: 7.4
- Database Engine:Mysql 
- Plugins Installed: 

### Description:

The size of the svgicon in the sidemenu needs to be adjusted

![image](https://user-images.githubusercontent.com/43752982/106611327-6c395e00-659a-11eb-9a21-e3dbc0d9d1bd.png)

**Comment by bennothommo** [comment]
@kunvn SVG icons resize to the width and height of the surrounding image tag, which is controlled via CSS. If it doesn't appear right, it's likely because the SVG icon has padding (or a custom width and height) embedded in the SVG itself. You'll need to use an SVG editor to remove this padding.

**Comment by bossleem** [comment]
As far as I can see, in mainmenu svgicon is still controlled by html tag. But the sidemenu is not, not even the css

![image](https://user-images.githubusercontent.com/43752982/106615632-38ad0280-659f-11eb-8dc5-e4d39fd5210f.png)

![image](https://user-images.githubusercontent.com/43752982/106611327-6c395e00-659a-11eb-9a21-e3dbc0d9d1bd.png)

**Comment by bennothommo** [comment]
@kunvn It's probably the surrounding tags such as `span.nav-icon` that control the sizing. Nonetheless, if the SVG appears wrong still, it's still likely to be the embedded styling within the SVG itself.
