### ISSUE TITLE
key:generate command not updating .env file

### ISSUE THREAD

**Issue by ericp-mrel** [octobercms/october#5496]
- OctoberCMS Build: v1.1.1
- PHP Version: 7.4
- Database Engine: MySQL

### Description:
When using a `.env` file for OctoberCMS: `php artisan october:env` the `php artisan key:generate` should generate the key and place it in the `.env` file instead of writing it into the app.php file.

### Steps To Reproduce:
1. Run the command `php artisan october:env`
2. Then `php artisan key:generate`
3. Notice how the key gets generated and placed inside of the app.php file instead of the desired .env file.

If you would like, I can send a PR for this since I think this should be included since that is most likely what the developer wants when using the .env file option (at least I know I do).

**Comment by LukeTowers** [comment]
@ericp-mrel a PR for this would be accepted, thanks!

**Comment by daftspunk** [comment]
Thanks for this @ericp-mrel, generally we figured that people would run `key:generate` before `october:env` so it usually isn't a problem in these cases. Anyhow, this will be fixed in the next update we've got coming out soon. Thanks for using October CMS!
