### ISSUE TITLE
extending the refresh results for belongsToMany realtion with pivot is not working as expected

### ISSUE THREAD

**Issue by msomma** [octobercms/october#5498]
- OctoberCMS Build: 471
- PHP Version: 7.3
- Database Engine: MySql

### Description:
relationExtendRefreshResults is not updating partial (example #myCounter) with relation type is  belongsToMany and contains pivot after a record is added while It works correctly when a record is delated from relation manager
It would be very useful for update total amount of pivot child records after refreshing relation

### Steps To Reproduce:
- create a relation in model with pivot data in TestModel
```php
   public $belongsToMany = [
        'relation_name' => [
            ParentModel::class,
            'pivot' => ['test']
        ],
```
- set config_relation.yaml 
```yaml
relation_name:
     label: 'test relation'
     .....
     pivot:
        form: ~formpath
```
- add partial field in TestModel forms and name as relation_name 
- create partial for relation render as: 
```php
  <?= $this->relationRender('relation_name') ?>
  <div id="myCounter">Total records: 0</div>
```
- extending the refresh results in model Controller
```php
   public function relationExtendRefreshResults($field)
    {
        return ['#myCounter' => Carbon::now()->format('Y-m-d H:i:s')];
    }
```
- edit model record
  when a record is added partial is not updated with current time BUG
  when a record is delete partial is correctly updated with current time

**Comment by daftspunk** [comment]
Thanks for the report @msomma. As this is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/octoberrain/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions on how to replicate it *using the test plugin*.
