### ISSUE TITLE
belongsToMany detach() fails when scope is defined on the relationship

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#5499]
This is a problem that was introduced in octobercms/library#543. https://github.com/octobercms/library/pull/543/files#diff-56f77bab4b0aa050a15e11466ccccbe82ce391f7adeed778ddc5c66c41152127R138

The issue stems from the fact that the query object here is not a Eloquent query builder associated with a model but a base query builder that doesn't have any access to the relevant scope methods.

You can replicate the issue by using RainLab.Blog, the WP importer plugin with my PR applied https://github.com/klyp/october-wp-importer/pull/7, and then attempting to import posts that have categories associated with them from a WordPress export file. You'll get the error "method scopeIsPublished does not exist"

```php
$category->posts()->detach($post->id);
```

**Comment by mjauvin** [comment]
@LukeTowers what do you mean by "when scope is defined on the relationship" ?

You mean this from the Blog Category model?
```
    public $belongsToMany = [
        'posts' => ['RainLab\Blog\Models\Post',
            'table' => 'rainlab_blog_posts_categories',
            'order' => 'published_at desc',
            'scope' => 'isPublished'
        ],
    ];
```

**Comment by mjauvin** [comment]
Would it be possible to create a PR to the October Test plugin to help replicate this, your method to reproduce above is inconvenient for me.

**Comment by mjauvin** [comment]
Ok, I was able to reproduce just by toying with the Blog plugin and a few Posts.
