### ISSUE TITLE
[Feature Request] Trigger API inside the Inspector element

### ISSUE THREAD

**Issue by mohsin** [octobercms/october#5501]
The [inspector window](https://github.com/octobercms/october/blob/develop/modules/system/assets/ui/docs/inspector.md) right now allows support for showing strings, booleans, dropdowns, and much other stuff that are comparable with the Form widget properties. However, it does not allow [trigger API](https://octobercms.com/docs/backend/forms#field-trigger-events) and that's a feature that would be beneficial in many scenarios.

**Comment by daftspunk** [comment]
I've added this to our internal tracker for the next time inspector is improved. Thanks, @SaifurRahmanMohsin!
