### ISSUE TITLE
Post published date.

### ISSUE THREAD

**Issue by pavelmoshik** [octobercms/october#5503]
Hello.  Please tell me how, instead of the date, to display the amount of time passed since the post was published?

{{ 'rainlab.blog::lang.post.posted_byline' | trans({
            date: post.published_at | date('Y-m-d H:i:s'),
                        categories: categoryLinks
                    }) }}

**Comment by LukeTowers** [comment]
See all of the options available on https://stackoverflow.com/questions/2915864/php-how-to-find-the-time-elapsed-since-a-date-time and choose the one that works the most for your needs. There's lots of great options there, you just need to evaluate the tradeoffs of each of them.
