### ISSUE TITLE
Image Resizer fails if the input image's filename is too long

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#5505]
The ImageResizer will fail with 
```
file_put_contents(/srv/users/website-oc-newcriterion/apps/website-oc-newcriterion/releases/1611303973/storage/app/resized/0a0/086/dae/florence-flood-november-4-1966-view-from-the-south-bank-of-the-arno-river-florence-italy-the-river-rages-just-beneath-the-stone-arches-of-the-ponte-santa-trinita-photo-by-balthazar-korab-7-0-2018-1084-1612117156_resized_0a0086dae485c1984a4b736baeea002370fc98eb.jpg): failed to open stream: File name too long
```
if it attempts to resize `/storage/app/media/florence-flood-november-4-1966-view-from-the-south-bank-of-the-arno-river-florence-italy-the-river-rages-just-beneath-the-stone-arches-of-the-ponte-santa-trinita-photo-by-balthazar-korab.jpg`. 

Now, why anyone would have files with such long names is beyond me, but the fact of the matter is there isn't anything in the system right now to prevent people from doing silly stuff like that, so it's unhandled when it's encountered.

@bennothommo any thoughts on the best way to deal with this sort of situation? The max path length is generally 255 bytes on most filesystems, but we'd also have to take into account the other parts of the path (the containing folder and the suffix detailing the options and extension).

**Comment by bennothommo** [comment]
@LukeTowers I think the idea has been floated in another issue, but maybe we could rename the files using a random seed on resize and use htaccess rules to allow for the full "SEO" path, since we have full control over the resulting path and URL.

**Comment by LukeTowers** [comment]
Hmm, not super comfortable with using htaccess for this given the limited environments that would work within.

**Comment by bennothommo** [comment]
@LukeTowers we'd have to promote comparable rules for Nginx and IIS, but I feel it could be achievable. We already have a tacit requirement for rewritten URLs anyway.

**Comment by LukeTowers** [comment]
@bennothommo what would that look like that?

**Comment by mjauvin** [comment]
I'm not personally crazy about the idea either... current implementation is clean and simple.

Why would we want to introduce such complexity for an extreme case like this?

**Comment by bennothommo** [comment]
@mjauvin I suggested it merely because it kills two birds with one stone. My company had requests from people using our image resizer plugin to allow for more SEO-friendly URLs for the resized images, so it's sought after. 

While I don't personally believe this does a lot for SEO these days, I'm assured by people in the industry that it does.

If we want to take the more simple route and just block people from using such big paths, that's cool.

**Comment by LukeTowers** [comment]
I think we should be able to just cut off the path after a max length is reached in the resizer specifically

**Comment by bennothommo** [comment]
I could imagine people might not like their filenames being arbitrarily reduced. I think it will be more palatable to users if they have the choice to fix it up themselves.

**Comment by LukeTowers** [comment]
@bennothommo what would that look like?
