### ISSUE TITLE
Rich Editor Auto Paragraph Tag Disable

### ISSUE THREAD

**Issue by mmutlusari** [octobercms/october#5508]
Hello friends,

While creating my content, I include a certain style structure. I use the static page content section for faster editing.
Therefore, I have to edit the richEditor. But I just couldn't figure it out. RichEditor automatically adds the "p" tag, but I don't want that.

I searched on many points, including Froala, but could not figure it out. Can you please tell? How can I remove the auto insertion of the "p" tag in RichEditor?

<img width="449" alt="Ekran Resmi 2021-02-14 12 00 27" src="https://user-images.githubusercontent.com/13905793/107872844-568f3700-6ebe-11eb-97f8-9484ebbc10e1.png">

**Comment by LukeTowers** [comment]
GitHub issues really isn't the place for questions like this. Please use the discussions tab instead.
