### ISSUE TITLE
Replicating the events triggered by dependsOn

### ISSUE THREAD

**Issue by prhost** [octobercms/october#5512]
- OctoberCMS Build: ### develop
- PHP Version: 7.4
- Database Engine: mysql
- Plugins Installed: october/test

### Description:

It is replicating the events triggered by `dependsOn` every time it creates a new repeater or opens a relation mode.

Example in the test plugin, in countries, creates creates several related and selects the country, it triggers several equal ajax events.

### Steps To Reproduce:

![Screen Shot 2021-02-16 at 13 30 24](https://user-images.githubusercontent.com/3984760/108093016-08b03580-705c-11eb-8597-f57a56ffe155.png)

<img width="722" alt="Screen Shot 2021-02-16 at 13 30 28" src="https://user-images.githubusercontent.com/3984760/108093031-0cdc5300-705c-11eb-8b78-8aa4c0088d57.png">

**Comment by daftspunk** [comment]
Hey @prhost! I can confirm this does not happen in the upcoming version of October CMS. That means it was probably introduced by some code added over the past year. Thanks :pray:
