### ISSUE TITLE
Environment variable was renamed to CACHE_DEFAULT (Laravel 5.8 used CACHE_DRIVER)

### ISSUE THREAD

**Issue by adrenth** [octobercms/october#5517]
- OctoberCMS Build: 1.1
- PHP Version: 7.4

### Description:

It seems the current PHPUnit configuration contains some old environment variables. We had to fix this (see attached screenshots) for our tests to work.

![image](https://user-images.githubusercontent.com/5699988/108853719-59d5a180-75e7-11eb-826b-4cd44f4882f3.png)

**Comment by bennothommo** [comment]
@adrenth I don't see `CACHE_DEFAULT` being used anywhere in October CMS or Laravel? Would you mind indicating where this requirement is coming from?
