### ISSUE TITLE
linkpolicy does not affect file uploads, they are always returned with absolute path.

### ISSUE THREAD

**Issue by RoudyTarabay** [octobercms/october#5518]
- OctoberCMS Build: 474
- PHP Version: 7.2
- Database Engine: MySQL
- Plugins Installed: Builder.Plugin

### Description:
Uploading images and files outside of media return the absolute paths regardless of linkpolicy

### Steps To Reproduce:
1- Create a Database. 
2- Create a Model for the database with field and list. 
3- Add File Upload Widget in the model. 
4- Create a Controller for the model. 
5- Add it to the backend menu.
6- Click on the menu and create an entry. 
7- Go to the list view, the path of the image is absolute.

**Comment by LukeTowers** [comment]
Could you describe the contexts and usages of file models where you would think it should be affected by the link policy?

**Comment by mjauvin** [comment]
@LukeTowers just using a model attachment in a template like this:
```
{{ model.image.path }}
```

It should behave the same as using a media file:
```
{{ "myimage.jpg"|media }}
```

If cms.linkPolicy is set to "force", the FULL URL should be returned, otherwise only the public path to the file.

**Comment by mjauvin** [comment]
The following patch brings the same behavior to file attachments:
```
diff --git a/modules/system/models/File.php b/modules/system/models/File.php
index 980da031..bda59797 100644
--- a/modules/system/models/File.php
+++ b/modules/system/models/File.php
@@ -80,7 +80,11 @@ class File extends FileBase
             $uploadsPath .= '/protected';
         }
 
-        return Url::asset($uploadsPath) . '/';
+        if (Config::get('cms.linkPolicy') === 'force') {
+            return Url::asset($uploadsPath) . '/';
+        } else {
+            return $uploadsPath . '/';
+        }
     }
 
     /**
```

**Comment by mjauvin** [comment]
The same thing was fixed here: https://github.com/octobercms/october/pull/5401

**Comment by mjauvin** [comment]
I can submit a PR if you'll accept it. @LukeTowers

**Comment by LukeTowers** [comment]
@mjauvin I think this is somewhat related to @Teranode's PR to make the file models use the storage disk url() method instead of Url::asset(), so probably look at that route

**Comment by mjauvin** [comment]
@LukeTowers Teranode's PR #5504 does resolve the issue as well!

Good catch!

**Comment by daftspunk** [comment]
Confirmed this has been addressed in the next release. Thanks!
