### ISSUE TITLE
plugin:install does not install plugin dependencies

### ISSUE THREAD

**Issue by snakemastr** [octobercms/october#5521]
- OctoberCMS Build: 471
- PHP Version:  7.3

### Description:
Artisan command plugin:install does'nt install Plugin::$require dependencies like the backend module does. The backend module uses a callback /modules/system/controllers/Updates::onInstallPlugin (calls appendRequiredPlugins) to install all plugins marked as a required dependency. The Artisan command does not do anything alike, making it hard to use for a production deployment like oc-bootstrapper.

### Steps To Reproduce:
Install a plugin with a required dependency using the commandline.
In this example: Mohsin.OAuth2 depends on Mohsin.OAuth
```
php artisan plugin:install Mohsin.OAuth2
```
Now the OAuth2 is installed but is missing the plugin OAuth.

https://octobercms.com/forum/post/console-artisan-plugininstall-not-installing-dependencies?page=1#post-35119

**Comment by LukeTowers** [comment]
@snakemastr I would recommend not using plugin:install for deployments anyways, you should be using composer for that.

**Comment by snakemastr** [comment]
@LukeTowers but will composer install dependencies that are defined in Plugin::$require? 

I am not using artisan directly but the oc-bootstrapper from OFFLINE and noticed this behaviour.

**Comment by LukeTowers** [comment]
@snakemastr so long as those plugins also define their dependencies in their composer.json file (which they should be doing), then yes.

**Comment by daftspunk** [comment]
This will be fixed when composer support for October CMS ships in a few weeks. We can keep this open until that time

**Comment by daftspunk** [comment]
I am processing the list of unattended concerns so since this has been addressed, we can actually close it

> will composer install dependencies that are defined in Plugin::$require

Plugins should define their dependencies (libraries, plugins, themes, etc.) in the composer.json file
