### ISSUE TITLE
Delay requests made by the markdown formwidget until the user stops typing momentarily

### ISSUE THREAD

**Issue by multiwebinc** [octobercms/october#5523]
- OctoberCMS Build: 1.0.471

### Description:
With the current markdown editor in split mode, a request is sent to the server for every single keystroke. This doesn't play well with DDoS prevention mechanisms, such as Apache's mod_evasive, which quickly causes a 403 error after just a few keystrokes. Would it be possible to use a client-side markdown parser, or at the very least throttle the number of requests sent to the server to something more sensible?

**Comment by LukeTowers** [comment]
@multiwebinc it should be possible to throttle the requests after a given delay of no keystrokes, if that hasn't already been implemented (I seem to remember something similar being implemented, but I can't remember if it was specifically for the markdown widget or something like the search field).

**Comment by daftspunk** [comment]
> if that hasn't already been implemented

The logic only stops polling when an active request is being made, so if you have a low latency server it could get pinged quite often

> This doesn't play well with DDoS prevention mechanisms

This issue has been addressed in the next version of October CMS. Stay tuned for the announcement!

Thanks
