### ISSUE TITLE
Octobercms can’t be install on 1&1 (ionos)

### ISSUE THREAD

**Issue by frasjaf** [octobercms/october#5524]
- OctoberCMS Build: ### 

### Description:

Hi 
After install Octobercms Successfully on 1&1 (IONOS)
I get error 500 
The problem is .htaccess 

### Steps To Reproduce:

It’s working after changing this on .htaccess

     ## You may need to uncomment the following line for some hosting environments,
     ## if you have installed to a subdirectory, enter the name here also.
     ##
Old    # RewriteBase /
New      RewriteBase /
     
     ##
Add a comment to this line
     ## Uncomment following lines to force HTTPS.
     ##
Old    # RewriteCond %{HTTPS} off
    # RewriteRule (.*) https://%{SERVER_NAME}/$1 [R,L]
New    ## RewriteCond %{HTTPS} off
    #  RewriteRule (.*) https://%{SERVER_NAME}/$1 [R,L]

**Comment by daftspunk** [comment]
```
 ## You may need to uncomment the following line for some hosting environments,
 ## if you have installed to a subdirectory, enter the name here also.
 ##
```

The comment suggests the fix already. Thanks for the report
