### ISSUE TITLE
Installing and Using Theme from Console needs improving

### ISSUE THREAD

**Issue by andy-laravel** [octobercms/october#5526]
I installed a fresh OctoberCMS, removed the Blank theme (I'm pretty much only using the Admin area). Today I tried to login to the Admin area, but because there's no active theme it comes up with an error 
`Call to a member function getPath() on null` 
Which is fine. I'll just install a plain/blank theme from the command line

I found one, so I used `theme:install`, it said `Not enough arguments (missing: "name").` So I typed the name of the theme - I take the name from the Breadcrumbs on the OctoberCMS marketplace. Nope, that's not right. Turns out I need to use the Author.ThemeName.
So my first suggestion is instead of the error saying `missing: "name"`, it should say Author.Name 

OK, theme installed. Lets use it. First lets just list the installed themes to make sure its there
`theme:list`
I see my theme listed, its not active. Lets use the `theme:use` and copy the name from this `theme:list`. 
Nope. That theme doesn't exist (!!?!?!) You've just told me its there and installed in that list!

So it turns out, `theme:use` needs the argument to be the theme directory name for some reason?! 

So the second suggestion is to use the exact name that it lists in `theme:list` please. 

Hope it'll help any future users coming into the same issue

**Comment by daftspunk** [comment]
Thank you for this feedback!

**Comment by daftspunk** [comment]
Upon investigation today, this feature was assembled by multiple hands and has an overall inconsistency as a result. The UX has been addressed in a large update coming shortly
