### ISSUE TITLE
A user was found to match all plain text credentials however hashed credential...

### ISSUE THREAD

**Issue by Niekto350** [octobercms/october#5527]
For the security reasons, you should not display any additional information to the potential attacker. There should be a generic error message that the login attempt have failed / credentials did not match. There should be no information that that specific user exists in the database.

**Comment by jamzy118** [comment]
Is debug mode disabled in your env/config? This was raised and fixed a long time ago. Production-set Octobers display login errors like that:

![image](https://user-images.githubusercontent.com/49433753/110051015-611e4d00-7d55-11eb-8c9c-1f26ff09e168.png)

**Comment by daftspunk** [comment]
Thanks, @jamzy118, exactly this. Check out the documentation for more details:

https://octobercms.com/docs/setup/configuration#debug-mode

> The debug mode uses the following features when enabled:
>
> - Detailed error pages are displayed.
> - **Failed user authentication provides a specific reason.**
> - Combined assets are not minified by default.
> - Safe mode is disabled by default.

**Comment by Niekto350** [comment]
Oh, sorry about that, I've checked the Github issuses and the documentation but didn't find anything related to it. Yes it's in a debug mode, I've just installed it using composer and am taking a closer look at the CMS, really liking it so far by the way. :)
