### ISSUE TITLE
Backend component property type of Set does not work

### ISSUE THREAD

**Issue by maraerben** [octobercms/october#5530]
- OctoberCMS Build: 471
- PHP Version: 7.2
- Database Engine: PostgreSQL 11.3
- Plugins Installed: RainLab.Pages

### Description:
I develop my own plugin with custom Component. This component has property type of Set. This property has defined some options and default value too.

Default value is visible in backend are correctly, see first screenshot. (In CMS editor)

![Snímek obrazovky 2021-03-08 v 10 47 05](https://user-images.githubusercontent.com/17090177/110304301-b2e80100-7ffb-11eb-84ec-998a78323031.png)

When I want to select another (non-default) options, none is actually selected. See second screenshot.

![Snímek obrazovky 2021-03-08 v 10 49 07](https://user-images.githubusercontent.com/17090177/110304608-14a86b00-7ffc-11eb-97e6-0b24c7ff2540.png)

### Steps To Reproduce:
```php
<?php

use Cms\Classes\ComponentBase;

class ProductsList extends ComponentBase {

  public function defineProperties(): array
  {
    return [
      'productTypeExternalIds' ⇒ [
        'title' => 'Product types,
        'type' => 'set', # problem with set, e.g. dropdown works file, but I need multiple items selected
        'default' => [123],
        'required' => true
      ]
    ];
  }

  public function getProductTypeExternalIdsOptions(): array
  {
    return [
      123 => 'Some product',
      200 => 'Another product',
    ];
  }
}
```

**Comment by maraerben** [comment]
Hmm ... It looks like it works when `keys` of options array are strings. E.g. `option-123`, `option-200`, ... It is necessary to parse the integer from key later.

**Comment by daftspunk** [comment]
Confirmed the same thing, the key values must be strings and then you can cast them to integers later, if necessary. Made a note to get this fixed in a later release. Thanks @maraerben !
