### ISSUE TITLE
Issue with October\Rain\Halcyon\MemoryRepository::put

### ISSUE THREAD

**Issue by mlizotteblanko** [octobercms/october#5531]
- OctoberCMS Build: v1.1.1

When using file cache store, the MemoryRepository::put return nothing on mutex creation.
In the code below, the last line should return the parent::put return value.

```
public function put($key, $value, $seconds = null)
    {
        if (is_array($key)) {
            $this->putMany($key, $value);
        }

        $this->putInMemoryCache($key, $value);
        parent::put($key, $value, $seconds);
    }
```

Without this, the code below, in Illuminate\Console\Scheduling\CallbackEvent, always return when description and withoutOverlapping are true because the mutex creation return nothing.

```
    public function run(Container $container)
    {
        if ($this->description && $this->withoutOverlapping &&
            !$this->mutex->create($this)) {
            return;
        }

        $pid = getmypid();
        ...
```

And finaly, any schedule with "withoutOverlapping" will never be executed. The mutex was created, but callback never executed.

### Steps To Reproduce:

Create a schedule withoutOverlapping and set file store in config.
Run scheduler:run with artisan.
You will see that the cache mutex file was created, but code of scheduler callback was never executed.

```
    public function registerSchedule($schedule)
    {
        $schedule->call(function () {

            \Log::info('In scheduler callback.');

        })->name('testOverlapping')->withoutOverlapping();
    }
```

**Comment by daftspunk** [comment]
Yes, you're right. This was introduced in Laravel 5.5.

Fixed in https://github.com/octobercms/library/commit/72d81bc487b35db2801ee944fcf307de38c287be

Thanks @mlizotteblanko 🙏
