### ISSUE TITLE
MySQL error (Daylight Savings Time issue) SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value 

### ISSUE THREAD

**Issue by clearhat** [octobercms/october#5532]
### Description:

When updating a blog post, got an error "SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value..." but it was showing a perfectly valid date for the 'update' column throwing the error. A little research turned up this answer from stackoverflow: 

https://stackoverflow.com/a/55084791

I updated database config by adding  'timezone'   => '+00:00', to the MYSQL stanza and the problem went away

This is probably a Laravel issue but can be fixed in October with the fix above.

### Steps To Reproduce:

Sometime near the Daylight Savings Time change, update a blog post.

**Comment by daftspunk** [comment]
Interesting that this does seem to be an issue with Laravel / MySQL. I'm not sure there is much the blog plugin can do about this specifically. Nonetheless, thanks for sharing your fix! 👍

**Comment by MilosStanic** [comment]
This just happened for me on October build 1.473 after daylight savings time change in my time zone. The users weren't able to login because the 'updated_at' couldn't be set due to time zone difference. 

To make things clear for posterity, in the /config/database.php, the following should be added: 
```
'mysql' => [
    // ...

    'timezone'  => '+00:00'
],
```

**Comment by chhaimlan** [comment]
sad

**Comment by daftspunk** [comment]
Alternatively, you can fix this at the MySQL level with

```
# my.ini
[mysqld]
default_time_zone = "+00:00"
```
