### ISSUE TITLE
Partials of different components doesn't load after install pushed online

### ISSUE THREAD

**Issue by dgtn-va** [octobercms/october#5534]
Hi,

Yesterday, my local site has been switched online:

1. PHP version (7.4.14), extensions and others env parameters checked
2. Cache fully cleared before zip
3. Database imported (under MariaDB via PMA)
4. Files unziped via SSH
5. Update url parameter in config/app.php
6. Update mysql parameter in config/database.php

At this point, **files, database and online env at the same of my local install** (Win10+Laragon), then everything seems to be working well.

But after test starting, it appear that **partials of different components doesn't load anymore**. **No error, and no special event**, including using the [barryvdh/laravel-debugbar](https://github.com/barryvdh/laravel-debugbar) via the [Debug Plus plugin](https://octobercms.com/plugin/napagency-debugplus). No error in storage/logs/system.log either.

**When I paste default partial of some these components directly in the theme pages** - exactly where to the component is supposed to be well loaded and displayed (like on local install) - **that's work**, but definitvly not when just {% component 'myComponentName' %} is kept at this place. Anywhere, I can't paste some partials directly in pages. The chmod of component partials: 755 everywhere (777 on files). I tried to remove components concerned from back-office, saved page, and puted it back: nothing.

The most surprising thing is that the whole **component's controller part seems to work perfectly at all cases** (onRun, etc.), it's seems only a blocking of a part of the display part. Despite this, impossible to find a relevant way to solve this issue.
I have no other choice to rely on you to try to find a new approach.

Thanks for your help.

**Comment by Eoler** [comment]
> At this point, **files, database and online env at the same of my local install** (Laragon)

Windows filesystem is case-insensitive, so double-check your folder/filenames if you're deploying to Linux.

**Comment by dgtn-va** [comment]
From Plugin.php :

![](https://i.imgur.com/uROe6uv.png)

From FTP (default.htm files in respective subfolders):

![](https://i.imgur.com/oLvpSXv.png)

From my different pages (example):

![](https://i.imgur.com/ZcdM3VH.png)

...and always just the layout (with potentially page static content) displayed, without the component's dynamic content.

State of play:
- _userDashboard_ works because code is directly present on the page (not use component partial), like as said
- _breadcrumb_ works because... it is not use camel case style???
- All others components doesn't work online.

NB: I already use OctoberCMS has the same conditions (similar use, same hoster, same client softwares, etc.) for an another project and I didn't have this issue previously.

Thank you.

**Comment by Eoler** [comment]
Filenames are fine, I think - try with all-lowercase folders.

**Comment by dgtn-va** [comment]
That's it, problem solved!

Thank you so much for your help and your time!

**Comment by alxy** [comment]
To mitigate issues like this in the future Id recommend to scaffold components and all the required files and directories via the [artisan command](https://octobercms.com/docs/console/scaffolding#scaffold-create-component). It reolves a lot of head aches usually :)

**Comment by daftspunk** [comment]
Glad you got it sorted @fujitsuDev 😃
