### ISSUE TITLE
[Question] Why does listOverrideColumnValue lack the value as it's parameter?

### ISSUE THREAD

**Issue by mohsin** [octobercms/october#5545]
I've been looking at [listOverrideColumnValue](https://github.com/octobercms/october/blob/9d06eb5c7dc6ad6aa7b57c7a880d0df648d7a8f8/modules/backend/behaviors/ListController.php#L192) and it kind of strips of the $value parameter entirely which is weird for a method that supposedly is used to override a value (I'd hope it has the older value as a parameter). I'm trying to implement some code transformations on values on certain columns and want to make use of the list controller itself. Something like:

    public function listOverrideColumnValue($record, $columnName, $value, $definition = null)
    {
        if ($columnName == 'type') {
            return doTransformations($value);
        }
    }

inside my list controller. However, I realized the third parameter ($value) I put above doesn't exactly exist and therefore I had to use a workaround:
 ```
 Event::listen('backend.list.overrideColumnValue', function ($listWidget, $record, $column, &$value) {
    if ($listWidget->getController() instanceof \Mohsin\Acme\Controllers\Acme) {
        if ($column->columnName == 'type') {
            $value = doTransformations($value);
        }
    }
});
 ```
 
 This is counterintuitive because this is an extension method that's ideally useful when the transformation is being done by another plugin. Whereas here, it's the same plugin. Also, I know one solution would be to use custom column type itself, however that isn't suitable here because there are already column definitions that use a custom column type, so I would have to overload those definitions of the column types to pass the value to `doTransformations()` before returning it, polluting the definition of it. Is there any specific reason the value parameter was ignored and could it be added?

**Comment by prhost** [comment]
you can use `return doTransformations($record->type);`

but it really doesn't make much sense, maybe you just forgot to pass it. Send a PR with this adjustment, I believe @daftspunk will accept it.

PS. for questions use the channels of doubt: [forum](https://octobercms.com/forum), [discord](https://discord.com/invite/gEKgwSZ) or [telegram](https://t.me/octobercms).

**Comment by alxy** [comment]
Keep in mind that this would be a breaking change, as the signature of the method changes

**Comment by daftspunk** [comment]
Yes because there can be only 1 override function in the controller, there can be no other competition, so the value is returned as a halting event

The value is also available via the record object and you're expected to know the format of the value (local attribute, relation, etc). This gives greater flexibility in overriding it to be whatever you like (perhaps a completely different attribute value?)

From some angles, it would be nice to have the value passed as well, but it could also be viewed as a redundancy

```
public function listOverrideColumnValue($record, $columnName, $definition = null)
{
    // Record attribute "type" is known at this point
    if ($columnName == 'type') {
        return doTransformations($record->type);
    }
}
```

Hope this makes sense. Going to close this but we can keep discussing it

**Comment by daftspunk** [comment]
I should also point out that both solutions are perfectly valid. One has finality. The other is open to the workflow of other plugins. The code is a signal of the developer's design decision. It can be easily observed by reading the code

**Comment by daftspunk** [comment]
This might overcome your discomfort since it the way to do it inside the same plugin / in your controller

```
public function index()
{
    $this->asExtension('ListController')->index();
    
    // Let others play too
    $this->listGetWidget()->bindEvent('list.overrideColumnValue', function ($record, $column, &$value) {
        // ...
    });
}
```
