### ISSUE TITLE
Missing Mail Facade

### ISSUE THREAD

**Issue by rebaz88** [octobercms/october#5546]
- OctoberCMS Build: 45901e70d5fd077e60568f3bb5739578e5cd8b66
- PHP Version: 7.4.14

### Description:
Class 'October\Rain\Support\Facades\Mail' not found 

The Mail facade is missing

**Comment by daftspunk** [comment]
This can happen when you receive an old version of the october/rain library. Make sure you remove the `config.platform` section from your composer.json file and run **composer update**

Let us know if this helps

**Comment by rebaz88** [comment]
It works. Thank you
