### ISSUE TITLE
Wrong path on resized image after using image resize filter

### ISSUE THREAD

**Issue by haralake** [octobercms/october#5547]
- OctoberCMS Build: ### v1.1.4
- PHP Version: 7.3
- Database Engine: MariaDB

### Description:
I'm using new image resize filter on a partial:
`<img src="{{ this.theme.site_logo|media|resize(false, 60, { mode: 'auto' }) }}" alt="">`

but on frontend i get:

`<img src="/resizer/f33045f1e4a66eca63e66700933372798d383885/%252Fstorage%252Fapp%252Fresized%252F63c%252F364%252F372%252Flogo_resized_63c364372f3eb92c05fa1c9f85bcbafb7f7c9ed4.png" alt="">`

**Comment by daftspunk** [comment]
The `/resizer/*` route is normal, it is the first route for a resized image. Just like `/combine/`, it should be a valid URL

Is your copy of October CMS installed inside a subdirectory? What do you see at the address, 404?

**Comment by haralake** [comment]
I get error 404 on my console. Octobercms is installed on a nginx server in a local virtual machine environment, like other octobercms projects (Not in subdirectory)

**Comment by haralake** [comment]
I notice that /%252F on path are double slashes, is this ok?

**Comment by daftspunk** [comment]
Just double check that you have the correct config for Nginx

https://octobercms.com/docs/setup/configuration#nginx-configuration

Make sure this line is in there

```
location ~ ^/storage/app/resized { try_files $uri 404; }
```

**Comment by haralake** [comment]
Yes the line is in nginx configuration, but i'm still get this error. Also on risized folder i notice that there is no image.

**Comment by daftspunk** [comment]
> I notice that /%252F on path are double encoded slashes, is this ok?

The encoding is part of the design.

The route should exist here, in modules\system\routes.php

```
Route::get('resizer/{identifier}/{encodedUrl}', 'System\Classes\SystemController@resizer');
```

Make sure this route exists in your codebase. The 404 error should not be returned by this route. It will either throw an exception or error 400 specifically

**Comment by haralake** [comment]
Apparently this nginx.config setting was creating the problem, after remove those lines the problem solved:   
```
# Cache static files
location ~* \.(ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|css|rss|atom|js|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf|swf|woff2|m4a|cur|heic|tiff|webm|mp3|aac|webp)$ {
	include common/headers-http.conf;
	include common/headers-https.conf;
	add_header "Access-Control-Allow-Origin" "*";
	access_log off;
	log_not_found off;
	expires max;
}
```

**Comment by Samuell1** [comment]
I think issue is that there is .png on end then NGINX is taking it as static file i had similar issue with route when i defined extension for css file.

**Comment by haralake** [comment]
Yes if i remove png is working. Is there a proper solution to fix it? Is this a proper solution?

**Comment by daftspunk** [comment]
Yes, this is a real problem...

The resizer has been rewritten in the next version and doesn't include the suffix for non asset URLs, therefore, it will be fixed in the next major release of October CMS

For now, you may need a custom rule that targets the /resizer/* route and instruct it to not treat as an asset file

**Comment by SaifurRahmanMohsin** [comment]
@daftspunk I'm using an S3 bucket to source the media images and my filesystem config has media set to s3 disk so it picks it up. However, when I call resize twig method on this media object, it stores the data into my local disk which is pretty undesirable. Is there a way for me to tell the resizer to store it back into the S3 bucket?

**Comment by daftspunk** [comment]
@SaifurRahmanMohsin I will transfer this to our internal tracker to get it looked at. Thanks
