### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by 0xcrypto** [octobercms/october#5551]
Sorry for reporting vulnerability through huntr.dev and not via provided Security Policy. I couldn't see any reward through the provided medium, I reported through huntr.dev. They are giving bounties so I hope you will understand. 

Please see this: https://github.com/418sec/library/pull/3

**Comment by daftspunk** [comment]
That's OK this time. Yes, please only contact us via the security policy if you notice anything else

https://github.com/octobercms/library/commit/6bcb7b9ad9a91c736b7945ae2927729db81d5d8c
https://github.com/octobercms/library/commit/2ceaf17d0a75537eca0d4d4f4d5dd66ae4d4666e

Fortunately, this is a low severity issue. All the best with huntr.dev

**Comment by 0xcrypto** [comment]
Thanks @daftspunk. Can you please confirm the vulnerability by posting a comment on  https://github.com/418sec/library/pull/3. Would be helpful.
