### ISSUE TITLE
Guide to update from version 1.0 to 1.1

### ISSUE THREAD

**Issue by SciCrea** [octobercms/october#5554]
Hello! How soon will appear guide to update from version 1.0 to 1.1. ? 

Existing upgrade guides are more like a temporary solution than an official method from developers.

Installer with version 1.1?

**Comment by daftspunk** [comment]
We plan to have a new upgrade guide out very soon

For now, there is [a good upgrade guide](https://shopaholic.one/blog/how-upgrade-october-cms-laravel-6) written by the Shopaholic team

Hope this helps!
