### ISSUE TITLE
beforeunload slows down website performance

### ISSUE THREAD

**Issue by mkinternet** [octobercms/october#5556]
In /modules/system/assets/js/framework.js there is a call of beforeunload event: 

https://github.com/octobercms/october/blob/751d687cbfb317e8ce5ad3768aa8fe96b920544a/modules/system/assets/js/framework.js#L561

This function call is triggered every time website is loaded. When i test wbesite performance using Chrome developer tools this call is recorded as long task. Long task negatively affect FID (First Input Delay). Finnaly its affect to insight google score.

**Comment by Samuell1** [comment]
@mkinternet can you paste your benchmarks? Because this event should be called before page is closed not opened.

**Comment by daftspunk** [comment]
Was thinking the same thing, it would slow the Last Input Delay

The function call is necessary because navigating away from a page while an AJAX request is in flight will cause it to terminate and show the user an error when they navigate away. This UX issue is intercepted by this event and suppressed

**Comment by mkinternet** [comment]
![obraz](https://user-images.githubusercontent.com/48510453/114166774-72e3a900-992e-11eb-9c72-a216c331ea65.png)

**Comment by mkinternet** [comment]
So can it be triggered when ajax request is called not on every page load?

**Comment by daftspunk** [comment]
This is the pipeline of the browser. When the browser navigates away from a page, it terminates any pending AJAX requests. This results in a flash error, or even alert beings displayed. The unload logic intercepts this. So we can't really remove it without an alternative

Try changing the code to this to see if it makes any difference

```
window.onbeforeunload = function documentOnBeforeUnload() { window.ocUnloading = true }
```

**Comment by mkinternet** [comment]
I tested it and it makes difference. Long task dissapeared.

**Comment by daftspunk** [comment]
Nice, issue is with jQuery then. Thanks for reporting back

**Comment by mkinternet** [comment]
Will you update framework.js file during OC changes?

**Comment by daftspunk** [comment]
Yes, this will be fixed in the next release. If you want to patch your copy, update `modules\system\assets\js\framework.js` then run ` php artisan october:util compile js`

**Comment by mkinternet** [comment]
Thanks :)
