### ISSUE TITLE
List search breaks when list definition contains custom attributes

### ISSUE THREAD

**Issue by mohsin** [octobercms/october#5558]
I'm using some custom attributes whose values are "calculated" based on other DB fields.

A good example I found to show the problem I am facing is [this post](https://octobercms.com/forum/post/custom-list-columns?page=1#post-1025). Here the status column isn't an actual column in the DB and so when searchable: true is set, OctoberCMS search widget breaks and throws a "Column not found" error. This is weird because ultimately the columns too render down to string values that is shown in the column and ideally I'd want to be able to search them too (rather than implementing the filter widget or some other workaround).

Is there any mechanism by which I can tell octoberCMS on how to perform search for these custom columns in my list controller? Alternatively, it maybe a good idea for the search widget to check the model for the the custom attributes existence and call that function to include search results rather than doing a DB fetch... that way, the searchable: true can be used on such custom attributes as well.

**Comment by alxy** [comment]
I think there are two ways to solve this:

1. If the accessor (computed attribute) is just some composition of two or more other actual database fields, like a `full_name` for example, you can consider using a `select` [column type](https://octobercms.com/docs/backend/lists#column-select) instead. This will compose the value at the database level and is thus searchable and sortable.
2. If there is some more complex logic involved, the search action will also need to be more complex and customly defined. You can do so by adding a [custom search scope](https://octobercms.com/docs/backend/lists#adding-toolbar). Take into consideration that this will override the default search behavior, so you may want to at least also include the [default behavior](https://github.com/octobercms/october/blob/b5323fdae1c3175eb931c99d22ae7be00bef6aca/modules/backend/widgets/Lists.php#L1521) somehow in your custom scope.

**Comment by daftspunk** [comment]
A third option is duplicating the data on the local table and maintaining its state with model events.

```
public function afterSave()
{
    $this->parent->searachable_attribute = $this->searachable_attribute;
    $this->parent->save();
}
```

I have made some complex applications with this pattern with different models calculating local attributes for their relationships. It works well and is a simple solution

**Comment by mohsin** [comment]
@daftspunk I'm reluctant to use the 3rd option since it's data duplication (although search would definitely be faster that way). But these are all good workarounds. Wouldn't it be better to have a way to specify custom search logic on a column-level? I'm thinking something along the lines of:
```
/**
 * returns boolean true if the record must be shown.
 */
function searchFor**ColumnName**($currentSearchTerm, $record, $query) {
}
```

**Comment by daftspunk** [comment]
@SaifurRahmanMohsin The duplication can be considered an index on the table, the models are reliable enough to keep it in sync. The issue is indeed performance, injecting and searching columns will affect performance significantly at scale. At the upper bounds the query can take seconds to process, then you will find you need to duplicate the column anyway

The `select` option mentioned by alxy is the second-best approach to making a column searchable, however, it can make the query very slow for large datasets.

For example, the forum plugin injects a column to the users plugin

```
        UsersController::extendListColumns(function($widget, $model) {
            if (!$model instanceof \RainLab\User\Models\User) {
                return;
            }

            $widget->addColumns([
                'forum_member_username' => [
                    'label'      => 'rainlab.forum::lang.settings.forum_username',
                    'relation'   => 'forum_member',
                    'select'     => 'username',
                    'searchable' => false,
                    'invisible'  => true
                ]
            ]);
        });
```

Notice that it is invisible by default, so if you really need it, you can enable it, but then the query will slow down. 

I think searching on an individual column level could help, but would require a refactor of the widgets. This is on the table already so I have made a note of it

**Comment by mohsin** [comment]
Great. Glad to know this is something that is being considered coz I really think it would be a good feature to have for the platform. And thank you for the quick response.
