### ISSUE TITLE
October installation fails with InvalidArgumentException

### ISSUE THREAD

**Issue by digitreadmedia** [octobercms/october#5559]
Hi,

I'm trying to install a clean OCMS but the installation fails with the errors:

[ERROR] Please try running these commands manually
 * composer require october/system october/backend october/cms october/media october/editor
 * php artisan october:migrate

Running the commands manually I get:

[InvalidArgumentException]
  Could not find a matching version of package october/media. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).
  
[InvalidArgumentException]
  Could not find a matching version of package october/editor. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).

**Comment by daftspunk** [comment]
Thanks @digitreadmedia. There was a problem with today's launch due to some infrastructure issues with AWS. They are currently being rectified and we hope to have it ready over the coming weekend. Will keep you updated

**Comment by daftspunk** [comment]
Update: The core has been fixed and is installable, but there may be issues with some plugins as they are still migrating over to the new system

**Comment by daftspunk** [comment]
This should be fixed now. Thanks!
