### ISSUE TITLE
hasManyThrough still doesn't work

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#556]
This relates to an [earlier issue](https://github.com/octobercms/october/issues/554) you marked as fixed. The reason it was fixed for you was out of coincidence that the IDs happened to all be 1. If you use different IDs for each record, hasManyThrough breaks again.

See https://github.com/Flynsarmy/oc-badhasmanythrough-plugin for an updated demonstration repo.

I have a Product of ID 1, ProductOMRecord of ID 2 and ProductOMOption of ID 3. When loading the OMRecord and trying to grab the OMOption through the Product, the following SQL is generated:
```sql
select o.*, p.id 
from `flynsarmy_droidcommerce_product_om_options` o 
inner join `flynsarmy_droidcommerce_products` p on p.id = o.product_id
where p.id = 2
```
I made the query a bit easier to read in this issue by adding table aliases. Notice the `p.id=2` at the end. The problem is that hasManyThrough is using the ID of the model instance we grabbed (The OMRecord with ID 2) instead of the ID of the relation it's going through (Product of ID 1).

**Comment by daftspunk** [comment]
I got completely different output

```
select 
    `product_om_options`.*, `products`.`id` 
    from `product_om_options` 
    inner join `products` 
        on `products`.`id` = `product_om_options`.`product_id` 
    where `products`.`id` = 2  
```

It shows product.id is 2, not 1. Assume this is fixed by now.
