### ISSUE TITLE
Repeater dropdowns dependency - bug is back

### ISSUE THREAD

**Issue by Rike-cz** [octobercms/october#5560]
This bug was solved in v1.1.1, but is back now in v1.1.4.

I have repeater with form containing two dropdowns. Second depends on first one. When new form is rendered and new repeater item added, selecting first dropdown item triggers every second dropdown's loading event on each form. When I have 5 previous repeater forms on popup, event is triggered 5 times unnecessarily.
When one form is removed and added back, it starts to work as expected.
![repeater](https://user-images.githubusercontent.com/4247582/115012258-ea29b780-9eaf-11eb-8940-ded9de5d96a8.gif)

**Comment by daftspunk** [comment]
Bug was actually introduced in 1.1.4. Fixed in v2.0

**Comment by Rike-cz** [comment]
@daftspunk There is not plan to make last stable 1.1.* before switching to new version?

**Comment by daftspunk** [comment]
If we discover what broke it, happy to backport the fix, but it appears broken due to some introduced reason that I'm not aware of

**Comment by daftspunk** [comment]
Please test in v2.0 and let me know if it still happens. Thanks
