### ISSUE TITLE
[2.0] Reorder throws an error

### ISSUE THREAD

**Issue by FlusherDock1** [octobercms/october#5561]
Custom model. 

Controller code: https://gist.github.com/FlusherDock1/6f53b8a1b92ac3709ce290f4a2613453

![IMAGE 2021-04-16 13:46:51](https://user-images.githubusercontent.com/20070837/115013817-32e66e00-9eba-11eb-9203-b472c8cc1946.jpg)

![IMAGE 2021-04-16 13:46:54](https://user-images.githubusercontent.com/20070837/115013820-34b03180-9eba-11eb-8c5f-853a39f47988.jpg)

![IMAGE 2021-04-16 13:46:57](https://user-images.githubusercontent.com/20070837/115013825-3679f500-9eba-11eb-8a1c-4ada33a4e2e5.jpg)

**Comment by daftspunk** [comment]
Need to flush assets on this handler

**Comment by FlusherDock1** [comment]
Reinstallation whole project helped.
