### ISSUE TITLE
[2.0] Self edit page has empty sidebar

### ISSUE THREAD

**Issue by FlusherDock1** [octobercms/october#5562]
Go to /backend/backend/users/myaccount

![Снимок экрана 2021-04-16 в 13 47 52](https://user-images.githubusercontent.com/20070837/115013971-688b5700-9eba-11eb-9bb8-a8b498870a90.png)

For example if you open role edit page, sidebar is populated with links

![Снимок экрана 2021-04-16 в 13 49 16](https://user-images.githubusercontent.com/20070837/115014069-89ec4300-9eba-11eb-8a6b-41e42724b15f.png)

**Comment by daftspunk** [comment]
Fixed in v2.0.2. Thanks!
