### ISSUE TITLE
[2.0] Internal timeout when install any plugin

### ISSUE THREAD

**Issue by moisessepulveda** [octobercms/october#5564]
When i try to install any plugin i get an error that says "internal timeout"

![CleanShot 2021-04-16 at 20 14 35](https://user-images.githubusercontent.com/69491477/115095785-84a9eb00-9ef0-11eb-8d0d-ef45e90e1c4f.png)

**Comment by daftspunk** [comment]
Hello! Can you check if your CLI version is working?
```
php artisan plugin:install RainLab.Pages
```

**Comment by moisessepulveda** [comment]
Works perfectly

<img width="661" alt="CleanShot 2021-04-16 at 20 22 23@2x" src="https://user-images.githubusercontent.com/69491477/115096048-9475ff00-9ef1-11eb-843e-745774e554b7.png">

**Comment by daftspunk** [comment]
The UI has been removed for the next release. PHP's long-running process does not seem to be a reliable implementation. It might be better to use a queue for processing the commands to bring it closer to CLI reliability

Thanks!
