### ISSUE TITLE
[2.0] List image type not found

### ISSUE THREAD

**Issue by moisessepulveda** [octobercms/october#5565]
According  documentation there is an **image type** in lists, but, when i try to use it, an error shows up saying that Column type "image" could not be found. Here's the error:

![CleanShot 2021-04-16 at 23 37 07](https://user-images.githubusercontent.com/69491477/115100790-09a2fd80-9f0d-11eb-850c-b5de3382b78a.png)

and, here's my columns definition:

<img width="564" alt="CleanShot 2021-04-16 at 23 43 50@2x" src="https://user-images.githubusercontent.com/69491477/115100858-9cdc3300-9f0d-11eb-986a-5482ae021941.png">

**Comment by daftspunk** [comment]
Fixed in v2.0.2 

Please run `composer update`

Don't forget to update your .htaccess file to allow the `resources` path to be accessible. See the change here: https://github.com/octobercms/october/commit/8fe9c7995bd61954ebc695c68493a6d20c698846
