### ISSUE TITLE
Rainlab Static page content not saved whether Rainlab Translate is Active

### ISSUE THREAD

**Issue by massimomegistus** [octobercms/october#5566]
- OctoberCMS Build: 2.0.3 (Clean install)
- RainLab Pages Plugin Version: 1.3.7
- RainLab Translate Plugin Version: 1.8
- PHP Version: 7.4

**Description:**
Unable to update Static Page content after Rainlab Translate activation

**Steps To Reproduce:**
1. Add a secondary language
2. Create a Static Page
3. Write some content

**Off topic**
I also confirm this issue
https://github.com/rainlab/pages-plugin/issues/476

**Comment by daftspunk** [comment]
I was unable to replicate this. Do you see any errors?

**Comment by massimomegistus** [comment]
Hi @daftspunk,
this issue seems solved, I've just updated Ranlab.Pages to 1.4.0 version, I can't say if it depends on this.
Thanks!

**Comment by daftspunk** [comment]
Great! Thanks for letting us know 👍
