### ISSUE TITLE
Unable to use url()

### ISSUE THREAD

**Issue by digitreadmedia** [octobercms/october#5567]
Hi

I first encountered this error with the Rainlab Pages plugin.  When trying to create/edit menus, the following error is thrown: 

Object of class October\Rain\Router\UrlGenerator could not be converted to string" on line 6 of plugins/rainlab/pages/formwidgets/menuitems/partials/_menuitems.htm #https://github.com/rainlab/pages-plugin/issues/476#issue-859795383

However, I'm now also getting the same error "Object of class October\Rain\Router\UrlGenerator could not be converted to string" in themes where {{ url('/') }} is used with dynamically set parameters eg: 
{% set customlink = 'mypage' %}
{{ url(customlink) }}

Update: the issue in the theme was the custom URL parameter did not pass correctly, resulting in an empty url() being called.  However, the issue with the pages plugin still persists.

**Comment by daftspunk** [comment]
Fixed in `rainlab/pages-plugin:1.4.0`. Thanks for the report!
