### ISSUE TITLE
System Update in backend cl only?

### ISSUE THREAD

**Issue by digitreadmedia** [octobercms/october#5569]
Hi

There is no longer a system & plugin update button in the backend, instead just the php artisan october:update
 command.  This is fine when I / a developer works on a website, but once hand-over to a client, they need to be able to update their website systems without requiring/risking them to fiddle in terminals - is it possible to re-add the update button?

![ocmsupdate](https://user-images.githubusercontent.com/48868778/115138346-de630000-a02b-11eb-897d-0475d2368a3e.PNG)

**Comment by daftspunk** [comment]
Hey there

Thanks for your insight. UI updating is a feature that is important to us

We had this button in the original design, however, it became too unreliable in the wild and not good enough to launch with. We have a strategy to add the button back with something more suitable for this purpose. For now, it is ok to get accommodated with the update commands, as these will be the underlying actions that are carried out when the button is pressed 

Going to close this but we can continue to discuss it
