### ISSUE TITLE
artisan plugin:refresh

### ISSUE THREAD

**Issue by Makareene** [octobercms/october#5573]
Hello!
When I try to use command "artisan plugin:refresh", I have error, which you can see to the screenshot n1.
I checked database for table and rows there. Yes that were. Also I checked **PDOConnection.php** (screenshot n2) and $dsn had correct settings ($user and $password also corrects)  (database's name, login, password, host).
My project works fine and hasn't any problems with connection (backend and frontend).
Database is Postgresql.
Please, help.
![изображение](https://user-images.githubusercontent.com/82905264/115449726-c655d100-a223-11eb-85e4-3ca3be10e338.png)
![изображение](https://user-images.githubusercontent.com/82905264/115450733-f8b3fe00-a224-11eb-9e29-952e41838f2c.png)

**Comment by daftspunk** [comment]
Hi @Makareene !

It looks like you may be missing a PDO driver for Postgres. 

If you need technical support for this, follow this link: http://octobercms.com/premium-support

Thanks,
Sam
