### ISSUE TITLE
[2.0] October CMS 2 : can't upload images in backend

### ISSUE THREAD

**Issue by PubliAlex** [octobercms/october#5574]
Hello,

I created a new website with october cms 2. Globally, no problems except when I try to upload something in the backend. I get an error : 

`"array_flip() expects parameter 1 to be array, null given" on line 79 of /plugins/rainlab/translate/behaviors/Purgeable.php`

Best regards,

Alex

**Comment by massimomegistus** [comment]
Same Issue here

**Comment by daftspunk** [comment]
Fixed in core `october/system:2.0.9` and `rainlab/translate-plugin:1.8.2`

Please run `composer update`

Thanks!
