### ISSUE TITLE
[2.0] RichEditor Field: not updated on save if Rainlab.Translate is enabled

### ISSUE THREAD

**Issue by massimomegistus** [octobercms/october#5575]
OctoberCMS Build: 2.0.8 (Clean install)
RainLab Pages Plugin Version: 1.4.3
RainLab Translate Plugin Version: 1.8.1
PHP Version: 7.4
Description:
I have created a Static with useContent = 1 and an additional RichEditor field.
In the main page content, the richeditor and the InsertLink Popup are not changed
<img width="1087" alt="Schermata 2021-04-21 alle 15 18 11" src="https://user-images.githubusercontent.com/39944924/115561276-b555a000-a2b5-11eb-9052-dd360c30241e.png">

While, in the additional RichEditor field the Choose Link search button is missing, the Toggle full screen Overlaps the Lang selector dropdown and the InsertLink Popup is cropped in the richEditor bound box
<img width="1141" alt="Schermata 2021-04-21 alle 15 08 24" src="https://user-images.githubusercontent.com/39944924/115561679-18473700-a2b6-11eb-927a-517da128f7ea.png">

The Choose Link button is useful, because listening the 'backend.richeditor.listTypes' and 'backend.richeditor.getTypeInfo' events the content Editor can link to existing models easily.
In some projects, I would like to exclude 'cms-page' and 'static-page' form the suggested types. I've edited the Richeditor.php getPageLinkTypes to do the job.

    protected function getPageLinkTypes()
    {
        $result = [];

        $apiResult = Event::fire('backend.richeditor.listTypes');
        if (is_array($apiResult)) {
            foreach ($apiResult as $typeList) {
                if (!is_array($typeList)) {
                    continue;
                }

                foreach ($typeList as $typeCode => $typeName) {

                    **if ($typeCode === 'cms-page' || $typeCode === 'static-page'){
                        continue;
                    }**
                    
                    $result[$typeCode] = $typeName;
                }
            }
        }

        return $result;
    }

Could you suggest me a better way? I don't know how to deregister a specific Event::listen('backend.richeditor.listTypes')

Thank you!

**Comment by massimomegistus** [comment]
I've just noticed an additional issue:
Adding a richeditor field in a staticLayout
{variable name="sectionText" label="Intro Text" tab="Section One" type="richeditor"}{/variable}

If the translate plugin is unactive or has one language only, sectionText field is saved in the viewbag as expected, like this
sectionText = "<p>sasasasa1</p>"

Activating the translate plugin and adding a second language, sectionText is not saved anymore.

Switching sectionText to a text or textarea field, everything works fine
{variable name="sectionText" label="Intro Text" tab="Section One" type="textarea"}{/variable}

The issue persists even adding the richeditor using $form->secondaryTabs in 
Event::listen('backend.form.extendFieldsBefore', function ($form) {...

**Comment by massimomegistus** [comment]
Further infos: I've tested a site migrated to OctoberCms 2.0.8 and the bug occurs even in a model FormController
fields.yaml:
        content:
            label: Content
            type: richeditor
            size: giant

<img width="995" alt="Schermata 2021-04-21 alle 19 11 35" src="https://user-images.githubusercontent.com/39944924/115594263-d29a6680-a2d5-11eb-8e9e-0203c6f238d8.png">

Updated text is not saved; switching richeditor to textarea everything works correctly.

**Comment by daftspunk** [comment]
Try place this option on your form field:

```
content:
  label: Content
  type: richeditor
  legacyMode: true
  size: giant

```

**Comment by daftspunk** [comment]
This should be fixed by updating to RainLab.Translate 1.8.3

The others look like they could be fixed recently as well, run `composer update` and try again

Please keep 1 issue per ticket

Thanks
