### ISSUE TITLE
Cannot save data in rich editor with hot key

### ISSUE THREAD

**Issue by huynhnam0613** [octobercms/october#5577]
Build: 2.0.9 - Bug report
I have backend form to save data which is rich-editor field and I found a bug.
Only in rich-editor field, if I changed something and save that data with hot key (I used Cmd + S) to save, data in rich-editor field will not affect. Other type will be saved (I just tested with text and number type).
And if I change the data and click to Save button, data in rich-editor will be affected (will be saved)

**Comment by huynhnam0613** [comment]
I tried to use legacyMode in #5575, and I can save it

**Comment by daftspunk** [comment]
Hi @huynhnamegal 

This will be fixed in `v2.0.10` or is available in `dev-develop` right now

Thanks!
