### ISSUE TITLE
Returning resized images are super slow with getResizerUrl

### ISSUE THREAD

**Issue by mohsin** [octobercms/october#5579]
I wrote some frontend code with `|media|resize(...)` and the code seems to block the frontend and load super slow. The main thing is that I'm using this in my cms.php:
```
    'resized' => [
        'disk'   => 's3',
        'folder' => 'media/resized'
    ],
```
And it's clearly linked to an S3 bucket. The time taken for the method (getResizerUrl in System\Classes\ImageResizer) to return seems to be ~0.5s per image and this is pretty bad because the frontend loads about 15-25 images (blocks the frontend for almost 10 seconds, enough to scare away users). I think it's a terrible implementation of the resizer and would need fixing.

**Comment by daftspunk** [comment]
@SaifurRahmanMohsin This is the v1.1 version, it has been rewritten from the ground up in v2.0 however we need some time to implement s3 support
