### ISSUE TITLE
Installing October v2 - Migration Error

### ISSUE THREAD

**Issue by PictureElement** [octobercms/october#5580]
**Server information:**
Apache Version | 2.4.46
PHP Version | 7.0.33
MySQL Version | 5.6.41-84.1

By running the command ```php artisan october:migrate```, I get the following errors:

```
In Connection.php line 669:
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `deferred_bindings` add index `deferred_bindings_master_type_index`(`master_type`))

In Exception.php line 18:
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

In PDOStatement.php line 112:
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

I changed this:
```
'charset' => 'utf8mb4',
'collation' => 'utf8mb4_unicode_ci',
```
to this:
```
'charset' => 'utf8',
'collation' => 'utf8_unicode_ci',
```

in ```database.php```. 

It seems this solves the issue but I am not sure if there are any other unwanted side effects.

**Comment by daftspunk** [comment]
Hey @PictureElement! This is taken from the upgrade guide: https://octobercms.com/support/article/rn-13

---

### Database Requirements

The new minimum supported version for MariaDB is 10.2 and MySQL is 5.7.7, however, older versions will still work. If you wish to continue to use lower versions, ensure the following is added to your database configuration under the key `database.connections.mysql`.

```
'varcharmax' => 191,
```

---

This should help

**Comment by PictureElement** [comment]
@daftspunk, I've followed your advice and installed another October Project. Installation was smooth with no issues. Thanks a lot.
