### ISSUE TITLE
Let's talk about file management

### ISSUE THREAD

**Issue by PubliAlex** [octobercms/october#5582]
I developped many websites using octobercms in our agency, and even if the system is fantastic in many aspects, there is a long-standing problem with file management to me. I wonder if the recent changes in the cms policy can make it possible to address the issue.

Today, we have 2 choices when dealing with form files, but none of them really fits : 
-  Using media manager widget, you have a nice file browser, you can even crop images, but you can only choose one file with it (putting media manager in a repeater is not a serious options to me if you want to provide best in class UX). In addition, you can't associate meta datas to your files (like a description for example).
- Using fileupload widget, you have a nice interface to upload multiples files, you can activate a nice popup to put some metas datas, but you don't have any file manager or image cropping feature.

I think there is a gap to fill here. We shouldn't have to choose what we want to sacrify when dealing with files. If the goal is to provide In best in class UX, we should be able to pick many files, from our computer or from a file manager, associate metas datas to each of them in a nice and slick interface etc...

I know that there was a media manager revamp project that had the objective to address that issue, but without update since lasts months, and I don't see the project anymore so I wonder what is the position of the maintenance team now.

Best regards,

**Comment by alekseybobkov** [comment]
Hello, thanks for the question. I moved this request to our internal tracking system. We try to keep the scope of each feature request as narrow as possible. In this issue, I identified two ideas:

* Add an ability to select multiple items in the media manager widget.
* Add an ability to crop images selected via the file upload widgets.

In our planning process, we collect insights into the internal system. When we see enough insights supporting a specific idea, we move that idea to the [Portal](https://portal.octobercms.com/) for voting and further consideration. Now you can send your ideas directly to the Portal, using the Submit Idea button.

**Comment by PubliAlex** [comment]
Thank you aleksey for the answer.

My request is not exactly that because : 
- If you just add a select multiple items in the media manager widget, you still don't have solution to set metadatas to your files
- If you just add a crop option to images selected with the file upload widget, you still don't have solution to browse for an existing image using the media manager.

I think it's better to reformulate my request by this : 
- Add "Enable media manager" option for fileupload widget

If you put this option to "true", you have a new "open media manager" next to the "browse" button that already allow to browse files from you computer.

In the case of multiple fileupload widget, the media manager should allow you to pick several images at a time, the same way you can pick several images at a time when browsing from your computer.


Selecting several items using the media manager widget is a plus, but I personnaly don't use it because I prefer ton consider file attachement as a relation, and the fact to not be able so associated metas datas your files is not acceptable to me.

**Comment by snipiba** [comment]
i found your request and i think, i can fill that gap with custom plugin for media finder, like i did with image providers like unsplash or pexels, etc. on my head is for long time to update media finder to extend funcionality for better seo (image metadatas, etc), then, probably same request from here :D

**Comment by PubliAlex** [comment]
Personnaly I'm more waiting for a media manager support for fileupload widget than multiple images selection with media manager widget (cause I prefer relation than adding a column in the database, but both solution should be supported)

So when you talk about working on the improvements, I hope you talk about both form widgets

Best regards,
