### ISSUE TITLE
Issue with plugin updates

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#5583]
Hi guys!

What happened to the plugin update pipeline?

![image](https://user-images.githubusercontent.com/3897579/116200057-8a010400-a740-11eb-89f2-6cc3504949f8.png)

When this changes were introduced and why there were no notifications? Thanks.

**Comment by daftspunk** [comment]
Hey @GinoPane ! The gateway now uses composer to build its packages and now checks the composer.json file for consistency. We are still deciding if the gateway should allow mixed package names (oc- prefix and without), so for now, please use the Packagist source mode in settings.

Hope this helps
