### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by TAZAQ** [octobercms/october#5585]
When I installed "October" I specified host 127.0.0.1, however my hosting operator considers 127.0.0.1 and localhost to be different things. That is, I definitely need to work from 127.0.0.1. When migrating, I get the error:

SQLSTATE[HY000] [1045] Access denied for user 'username'@'localhost' (using password: YES)

Can you fix this so that not localhost is loaded, but 127.0.0.1 if I specified it?

**Comment by daftspunk** [comment]
Can you open your `.env` file and check what value is found for `DB_HOST`?
