### ISSUE TITLE
Function onStart method to add assets does not respect the original path of files on child themes

### ISSUE THREAD

**Issue by charisketikidis** [octobercms/october#5588]
Function onStart method to add assets does not respect the original path of files on child themes
```
function onStart()
{
    $this->addCss('assets/vendor/.../main.css');
    $this->addJs('assets/vendor/.../main.js');
}
```

On child theme you get 404 error because of the wrong path:

http://...../theme/themename-child/assets/vendor/.../main.js

**Comment by daftspunk** [comment]
This has been updated in `develop` and we've instructed the ViewMaker class to respect the parent theme references.

Please update your composer dependencies to target `dev-develop`

        "october/system": "dev-develop",
        "october/backend": "dev-develop",
        "october/cms": "dev-develop",
        "october/media": "dev-develop",
        "october/editor": "dev-develop",


Then run `composer update` and test it and report back

**Comment by charisketikidis** [comment]
Yes it has been fixed. Thanks.
Will it logically move to the next stable version?

**Comment by daftspunk** [comment]
Yes, we will include it in the next patch release v2.0.12

Thanks for testing it!
