### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#5589]
Hi guys!

Docs say that to install v2 you need to create a new composer project, etc. 

Like this: ```composer create-project october/october mywebsite-new```

So I did, but in reality 1.0.471 was installed. Once I entered the backend it advised me to upgrade to the build 472, which failed due to this error:

```
PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/OctoberCmsSandbox/october-cms-sandbox-2.0/vendor/composer/../october/rain/src/Parse/Assetic/Less/lessc.inc.php' (include_path='.:/usr/local/lib/php') in /var/www/OctoberCmsSandbox/october-cms-sandbox-2.0/vendor/composer/autoload_real.php on line 66
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /var/www/OctoberCmsSandbox/october-cms-sandbox-2.0/index.php:0
PHP message: PHP   2. require() /var/www/OctoberCmsSandbox/october-cms-sandbox-2.0/index.php:18
PHP message: PHP   3. require() /var/www/OctoberCmsSandbox/october-cms-sandbox-2.0/bootstrap/autoload.php:37
PHP message: PHP   4. ComposerAutoloaderInitce290a037d2cbd6fc6b8d537449d0ac2::getLoader() /var/www/OctoberCmsSandbox/october-cms-sandbox-2.0/vendor/autoload.php:7
PHP message: PHP   5. composerRequirece290a037d2cbd6fc6b8d537449d0ac2() /var/www/OctoberCmsSandbox/october-cms-sandbox-2.0/vendor/composer/autoload_real.php:56" while reading response header from upstream, clien
```

I went into my container again and run ```composer update``` instead. The CMS updated to 1.1.5 and that's it.

After this I entered the backend again which suggested me to upgrade to the build 472 🦀 

Also, while being on version 1.1.5, if I run ```php artisan october:update``` it tries to install 1.0.472 which is just crazy.

![image](https://user-images.githubusercontent.com/3897579/116609550-2db70380-a93d-11eb-926b-4723d019ef9e.png)

**Comment by GinoPane** [comment]
🤦🏻 Ah, probably ```'disableCoreUpdates' => true``` entry would solve some of this.

**Comment by GinoPane** [comment]
And also this article https://octobercms.com/support/article/rn-13 suggests to run ```october:migrate``` after installation, but:

![image](https://user-images.githubusercontent.com/3897579/116611733-60fa9200-a93f-11eb-967c-4c3451ce9ab9.png)

**Comment by daftspunk** [comment]
Hi @GinoPane. You shouldn't be getting v1 with this. Make sure that you're running PHP 7.2.9 or higher. Or try 

```
composer create-project october/october:2.0.* mywebsite-new
```

And see the output

**Comment by GinoPane** [comment]
@daftspunk yep, solved this by upgrading the php-fpm container to PHP7.4. 

What about `october:migrate`? Will it be available once installation is complete?

Thanks.

**Comment by daftspunk** [comment]
Yes it should
