### ISSUE TITLE
data-request-confirm should take priority over data-dismiss

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#559]
In a modal if you have a button like
```html
<button ... data-dismiss="modal" data-request-confirm="Foo">Click Me</button>
```
click the button and click cancel, the modal will disappear anyway and you'll be left with a modal loader icon that you can't get out of. 

I understand this is a conflict with Bootstrap's data-dismiss functionality, though it would be great if October could be a little bit smarter about using the two side.

I've made a [plugin](https://github.com/Flynsarmy/oc-badconfirm-plugin) to demonstrate this issue.

**Comment by daftspunk** [comment]
Use `data-request-success="$(this).trigger('close.oc.popup');`
