### ISSUE TITLE
Development licenses maybe?

### ISSUE THREAD

**Issue by GinoPane** [octobercms/october#5590]
Hi guys!

Do you have any plans to provide free development licenses maybe?

Because now it seems a little bit illogical to pay for a license in order to develop **free** plugins 🤯

**Comment by daftspunk** [comment]
Hi @GinoPane

You don't need a license to run a development instance of October CMS. You just need at least one license to download the latest source code. Hope this helps

See licensing FAQ for more details: https://octobercms.com/help/license/faqs

**Comment by daftspunk** [comment]
BTW - please send further inquires to hello@octobercms.com

Most appreciated, thank you

**Comment by snipiba** [comment]
question... when you install octobercms with **php artisan october:install** one from installation steps is license, right? then maybe question is pointing to that. when license key was required in october:install, then nobody probably install new october, right?

**Comment by snipiba** [comment]
> Hi @GinoPane
> 
> You don't need a license to run a development instance of October CMS. You just need at least one license to download the latest source code. Hope this helps
> 
> See licensing FAQ for more details: https://octobercms.com/help/license/faqs

At least one license, which is linked to project, then, when u wish to use october instance only for development, then u need to create a new project, without any added themes or plugins, or probably with most used plugins like RainLab.User, RainLab.Blog, etc. and with installation will be loaded whole project with all these plugins, right? 

Here im not sure, if this way is best at all.

**Comment by daftspunk** [comment]
> with installation will be loaded whole project with all these plugins, right?

v2.0 uses Composer as a first class citizen. Taken from upgrade guide: https://octobercms.com/support/article/rn-13

> ### Project is No Longer Syncronised Automatically
> Previously when performing a system update, the platform will check with the server for any new plugins or themes and install  them. This forces the website to use all plugins and themes defined by the project. This functionality has changed to decouple  this process and the plugins and themes are now defined by the composer.json file instead.

**Comment by snipiba** [comment]
still same question... purchase license for "dummy" never used project to be a plugin/theme developer? for me, what ever at all, but as part of community, this will be one big downvote for use october anymore :(

**Comment by daftspunk** [comment]
Please send us an email and we can organise something for your circumstances

**Comment by GinoPane** [comment]
@daftspunk thanks!
sergey.karavay@gmail.com
