### ISSUE TITLE
Error after dependsOn 

### ISSUE THREAD

**Issue by Cryden** [octobercms/october#5592]
Hello, i found this error after dependsOn on my custom formWidget
OctoberCMS 2.0.12

```
Uncaught Error: cannot enable cancellation after promises are in use
    at Function.e.config (storm-min.js?v=dcb118ab:3991)
    at HTMLDocument.<anonymous> (october-min.js?v=dcb118ab:1253)
    at e (jquery.min.js?v=dcb118ab:2)
    at t (jquery.min.js?v=dcb118ab:2)
```

**Comment by daftspunk** [comment]
Hello @Cryden 

This appears to be a bug with the platform, thanks for reporting it.

Please send an email to hello@octobercms.com and attach a copy of the plugin that has your custom form widget so we can troubleshoot the issue. We will respond to you via email as well.

Thanks
