### ISSUE TITLE
When using child theme implementation using @jquery alias in your theme seems to not working

### ISSUE THREAD

**Issue by charisketikidis** [octobercms/october#5594]
I try to use the same jQuery version October ships in my theme by using the @jquery alias

`<script src="{{ ['@jquery'] | theme }}"></script>`

This seems to be working corectly if you don't use child theme implementation. If you use child theme seems to not load jquery.

**Comment by daftspunk** [comment]
Thanks for the report. This is fixed in v2.0.14
