### ISSUE TITLE
When a selection box within the component is opened, the area containing the options appears at the top. 

### ISSUE THREAD

**Issue by RustemHesenov** [octobercms/october#5595]
When a selection box within the component is opened, the area containing the options appears at the top. This is a minor front-end bug, but I wanted to report it.

<img width="491" alt="Screen Shot 2021-05-10 at 23 59 57" src="https://user-images.githubusercontent.com/7926881/117720303-929d1400-b1ef-11eb-84f2-f16a63aa4205.png">

**Comment by daftspunk** [comment]
Thanks for the report. This is fixed in v2.0.14
