### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Event' not found in vendor/october/rain/src/Foundation/Exception/Handler.php:59

### ISSUE THREAD

**Issue by adilshahzad** [octobercms/october#5596]
Hi,
I'm trying to install october version 1.1.x using composer. Installation went very well without any error but when I try to access the website in the browser, it gives the error.  [Here ](https://octobercms.com/forum/post/class-event-not-found?page=1)is the thread someone already opened years ago but the solution provided doesn't work in my case. 

Kind regards,
Adil

**Comment by daftspunk** [comment]
Hi Adil

Add the following code to this file **vendor/october/rain/src/Foundation/Exception/Handler.php**

https://github.com/octobercms/library/commit/55f1aa57ba393b9323fea2efaca8caa908d6a995

This should reveal the underlying error

Thanks!
