### ISSUE TITLE
Add event alllow change the signin form $rules

### ISSUE THREAD

**Issue by lealka** [octobercms/october#5600]
Hi everyone,

My project requires the addition of Google Recaptcha for the Backend Sign In form.

I used `backend.auth.extendSigninView` to add Recaptcha to front-end. But I can not validate it in the Auth controller.

Could we add an event like that:

```Event::fire('backend.auth.signin_onSubmit.beforeValidate', $rules);```

in this file:
https://github.com/octobercms/october/blob/baa41ac8541613caa740325fc1629b6ca85354a6/modules/backend/controllers/Auth.php#L77

I can not create PR for v2.

**Comment by daftspunk** [comment]
Hi @lealka!

Could you send us an email to hello@octobercms.com where we can explore your idea and propose a solution. It's possible a more generic event could help here.

Also, in the email please confirm what version of OCMS you are using (v1 or v2).

Thanks!
