### ISSUE TITLE
How to update the plugins?

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#5601]
I installed a plugin, but the version number is 1.0.0 instead of the higher version. How to update the plugin to latest version?

**Comment by daftspunk** [comment]
Assuming this is with v2.0, the plugin would be installed with composer. Check the composer.json file to see what version it is requesting... sometimes the plugin may not even be in there. If so, require it with the following

```
composer require author/some-plugin
```

**Comment by gergo85** [comment]
Thank you for your help!
