### ISSUE TITLE
can not open assets file in backend

### ISSUE THREAD

**Issue by tamtc84** [octobercms/october#5604]
I used Laragon 4.0.15 with October old version in localhost => It work OK.
Today, i updated October to version 473. 
Access backend, i open file in assets, i receiver message "Template not found" and i can't open file in this folder.
Please help me to fix it.
Thank you.

![image](https://user-images.githubusercontent.com/19953006/121003086-51306200-c7b7-11eb-88a5-a132d7a23ae6.png)

**Comment by daftspunk** [comment]
Hi @tamtc84 

This has been fixed in d371e36aa206c95bb28658aff31ad53ffef9b0bf

You are welcome to patch your code locally to get it fixed, otherwise, it will be included in Build 474

Thanks
