### ISSUE TITLE
Target class [System\Handlers\Installer] does not exist.

### ISSUE THREAD

**Issue by gadimlie** [octobercms/october#5605]
**After installation:**

_**Target class [System\Handlers\Installer] does not exist.**_
Next Illuminate\Contracts\Container\BindingResolutionException: Target class [System\Handlers\Installer] does not exist. in /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Container/Container.php:805
Stack trace:
#0 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build('System\\Handlers...')
#1 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\Container\Container->resolve('System\\Handlers...', Array, true)
#2 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Foundation\Application->resolve('System\\Handlers...', Array)
#3 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\Container\Container->make('System\\Handlers...', Array)
#4 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/october/rain/src/Foundation/Application.php(214): Illuminate\Foundation\Application->make('System\\Handlers...')
#5 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Routing/Route.php(233): October\Rain\Foundation\Application->make('System\\Handlers...')
#6 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Routing/Route.php(833): Illuminate\Routing\Route->getController()
#7 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Routing/Route.php(794): Illuminate\Routing\Route->controllerMiddleware()
#8 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\Routing\Route->gatherMiddleware()
#9 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Routing/Router.php(674): Illuminate\Routing\Router->gatherRouteMiddleware(Object(Illuminate\Routing\Route))
#10 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#11 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#12 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/october/rain/src/Router/CoreRouter.php(25): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#14 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#15 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#21 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#22 /Users/Gadimlie/Desktop/Gadimlie Studio/projects/sherg/server.php(18): require_once('/Users/Gadimlie...')
#23 {main}

**Comment by daftspunk** [comment]
Hello @gadimlie 

Can you please check that this file exists on your filesystem? 

**modules/system/handlers/Installer.php**

https://github.com/octobercms/october/blob/develop/modules/system/handlers/Installer.php
