### ISSUE TITLE
PHP code 

### ISSUE THREAD

**Issue by Kusdrae** [octobercms/october#5606]
So i'm writing a form page in OctoberCMS, and i need it to have both the HTML and PHP in the same page. So the HTML is just a basic form, and it's on the "Markup" section,  so i don't think it's necessary to have it here, but the PHP is in the "Code" section and it's like this:

`function kkk(){
    
if(isset($_POST['submit'])){

$con = mysqli_connect('...', '...', '...','...');
    

$txtName = $_POST['txtName'];
$txtEmail = $_POST['txtEmail'];
$txtPhone = $_POST['txtPhone'];
$txtMessage = $_POST['txtMessage'];
$sql = "INSERT INTO `tbl_contact` (`Id`, `fldName`, `fldEmail`, `fldPhone`, `fldMessage`) VALUES ('0', '$txtName', '$txtEmail', '$txtPhone', '$txtMessage');";

$rs = mysqli_query($con, $sql);

}

}
`

I've placed the if(isset) inside a function because october is not loading the page if it's not inside a function.. The form does not send any data to the database (i've replaced the db data with "..." for security), and i don't know why, if someone could help me in this one i would REALLY aprecciate!!!

**Comment by daftspunk** [comment]
Try changing the function name from `kkk` to `onStart` and this will ensure the code always runs when the page starts, more aligned with what you are expecting.

Take a look at the [page execution lifecycle](https://octobercms.com/docs/cms/pages#page-life-cycle) for more information on how the code section in a page works.

I hope this helps!
