### ISSUE TITLE
Log context not passed to EventLog details

### ISSUE THREAD

**Issue by marcbrouwer** [octobercms/october#5608]
When using `Log::error("some error message", ['user_id' => 123]);` the context `['user_id' => 123]` is written to system.log but not added to the details in the database table system_event_logs

https://github.com/octobercms/october/blob/167b592eed291ae1563c8fcc5b9b34a03a300f26/modules/system/ServiceProvider.php#L297

By changing `EventLog::add($event->message, $event->level);` to `EventLog::add($event->message, $event->level, $event->context);` the context is also stored in the EventLog details

OctoberCMS version 1.1.6

**Comment by daftspunk** [comment]
No problem. Keep in mind this will be captured but the details array does not appear to be used anywhere.

Scheduled for release in v2.0.26 and v1.1.7

Thanks

**Comment by marcbrouwer** [comment]
@daftspunk correct, it would be nice to see the details in the backend also. I'm currently patching `modules/system/controllers/EventLogs.php` and `modules/system/controllers/eventlogs/preview.htm` to make this possible. However this patch will be specific to my details in ths logs

**Comment by daftspunk** [comment]
@marcbrouwer Sounds good :beers: We will likely incorporate this field in the next iteration of the logging screens with some generic method for displaying the array contents. Nonetheless, it is nice that the field was proactively included!
