### ISSUE TITLE
plugins architecture

### ISSUE THREAD

**Issue by Ayman-Nageeb** [octobercms/october#5610]
Hello, I need help

I am planning to build an extensible system (via plugins) using laravel 

it for my project in the university ( I am a student ) 

the issue is that i don't know how to implement a plugins architecture in laravel

but you (the creator of octobercms) did it

i need to know how

so please give me any guide to start with

**Comment by daftspunk** [comment]
Hello @Ayman-Nageeb 

This is an open-ended question. The best place to start is looking at Service Providers and Laravel's auto package discovery system. In and of itself, this isn't much. October CMS is a recipe with many ingredients and we encourage you to study the source code to learn more. Good luck!
