### ISSUE TITLE
how to extend the page settings in the CMS section?

### ISSUE THREAD

**Issue by hiromant** [octobercms/october#5611]
i used the powerSEO plugin. he added different SEO settings to pages, blog, etc.

I bought October CMS and found that the settings in the CMS section were gone.

I started looking for a solution to this problem. but didn't find anything in the documentation.

how can i fix this problem?

![image](https://user-images.githubusercontent.com/14278779/127510985-2751c31f-0e09-4495-81c1-4a30207842f1.png)
![2021-07-29_213247](https://user-images.githubusercontent.com/14278779/127511014-f186d56a-ac14-4754-a415-0d0377bc9581.png)

**Comment by daftspunk** [comment]
Hi @hiromant 

This will be added to the documentation soon. In the meantime, take a look at the announcement post of this feature that describes how to use it

- https://octobercms.com/blog/post/introducing-cms-editor-extensibility-api

I hope this helps!

**Comment by hiromant** [comment]
thank you :)

**Comment by kavishdahekar** [comment]
Hi @daftspunk , is it possible to use the `cms.template.getTemplateToolbarSettingsButtons` event to add a popup with a repeater field?
