### ISSUE TITLE
(small issue) Url at end of october:install incorrect

### ISSUE THREAD

**Issue by andy-laravel** [octobercms/october#5612]
On initial install using command php artisan october:install where you enter all the details such as 'Application URL', after the 'Installation Complete' trees, it says to migrate then the next 2 lines are: 

Then, open the administration area at this URL
* http://localhost/backend

which completely ignores the Application URL I just typed in a minute ago. The .env file has my correct URL, but just this notification could be altered to take it into account.

**Comment by daftspunk** [comment]
Thanks @andy-laravel !
