### ISSUE TITLE
Invalid reference to "route cache" environment variable in config/cms.php

### ISSUE THREAD

**Issue by PictureElement** [octobercms/october#5615]
Invalid reference to "route cache" environment variable in config/cms.php. It should be CMS_ROUTES_CACHE not CMS_ROUTE_CACHE

**Comment by daftspunk** [comment]
Thanks for this, we have updated the variable in 4aa55cc3810ef1ffe6bedcc1e885f77550e6c605

**Comment by PictureElement** [comment]
You are welcome
