### ISSUE TITLE
Setting debug mode to false causes browser error

### ISSUE THREAD

**Issue by PictureElement** [octobercms/october#5616]
I am on a shared hosting environment and when I disable debug mode in `.env` file I get the following browser error:

`Uncaught SyntaxError: Invalid left-hand side expression in postfix operation`

Does it have something to do with the combine and minification process?

I am sorry but I don't know how to provide more information. Any help would be much appreciated.

**Comment by daftspunk** [comment]
Hi @PictureElement 

Please confirm what version of October CMS you are using.

Thanks!

**Comment by PictureElement** [comment]
Version 2.1.4.

**Comment by daftspunk** [comment]
Hi @PictureElement 

I could not replicate this using v2.1.4. What action are you performing when this error occurs?

**Comment by PictureElement** [comment]
The error occurs when setting `APP_DEBUG=false` in `.env` file.
The console error in Firefox is: `Uncaught SyntaxError: invalid increment/decrement operand`

My plugin component injects scripts like so:

```
public function onRun() {
        // Javascript
        $jsAssets = [
            'assets/vendor/@fancyapps/fancybox/dist/jquery.fancybox.min.js',
            'assets/vendor/simplebar/dist/simplebar.min.js',
            'assets/vendor/masonry-layout/dist/masonry.pkgd.min.js',
            'assets/vendor/imagesloaded/imagesloaded.pkgd.min.js',
            'assets/js/portfolio-list.js'
        ];
        $this->addJs(CombineAssets::combine($jsAssets, plugins_path('msof/portfolio/')));
```

I found out that `simplebar.min.js` is causing the error. When I remove  the particular script and setting `APP_DEBUG=false`, I get no errors.

**Comment by PictureElement** [comment]
Do you think it would be better to provide the unminified versions of the scripts instead? Perhaps the error occurs when the combiner tries to minify code that is already minified.

**Comment by PictureElement** [comment]
I've tried with the latest (v5.3.5) unminified `simplebar.js` file and I get the same error.

**Comment by PictureElement** [comment]
I am pretty sure something goes wrong with the minification process because If I set `'enable_asset_minify' => false,` and `APP_DEBUG=false`, everything is fine.

**Comment by daftspunk** [comment]
Yes, minifying already minified scripts can crearte errors like this. In this case you might be minifying ES6 JavaScript which would have a similar outcome. The path you have taken to disable minification via config is the appropriate course of action.

Glad you got it sorted!
