### ISSUE TITLE
PHPUNIT - Controller test - request empty in service provider

### ISSUE THREAD

**Issue by webninja156** [octobercms/october#5617]
Hitting routes via browser works as expected, with request parameters being present but hitting routes via unit testing methods does not work as expected, with request parameters being changed from POST to GET

**Here is the test snippet**

```
public function validate_required_search_fields_test(){
		$response = $this->withHeaders([
			'Authorization' => 'Bearer xyz'
		])->postJson(URL::to('/api/user/searchuser'),[]);
		$response->assertStatus(Response::HTTP_BAD_REQUEST);
		$response->assertJson(['success'=>false]);
}
```
But when i populate this POST request in server provider its gives me following 
`Illuminate\Http\Request {#17
  #json: null
  #convertedFiles: null
  #userResolver: null
  #routeResolver: null
  +attributes: Symfony\Component\HttpFoundation\ParameterBag {#29
    #parameters: []
  }
  +request: Symfony\Component\HttpFoundation\ParameterBag {#370
    #parameters: []
  }
  +query: Symfony\Component\HttpFoundation\ParameterBag {#30
    #parameters: []
  }
  +server: Symfony\Component\HttpFoundation\ServerBag {#36
...
pathInfo: "/"
  requestUri: "/"
  baseUrl: ""
  basePath: ""
  method: "GET"
  format: "html"`
  
  
  I dont know why this happend to me. It seems like i am not alone
 many other guys have similar problem
 https://laracasts.com/discuss/channels/laravel/controller-test-request-empty-in-service-provider
 
 Here is my composer.json
 `{
    "name": "october/october",
    "description": "Built using October CMS: The Platform That Gets Back to Basics",
    "type": "project",
    "homepage": "https://octobercms.com",
    "license": "proprietary",
    "require": {
        "php": ">=7.2.9",
        "october/rain": "^2.0",
        "laravel/framework": "^6.0",
        "phpmd/phpmd": "^2.9",
        "guzzlehttp/guzzle": "^6.5",
        "sendgrid/sendgrid": "^7.3",
        "laravel-validation-rules/credit-card": "^1.6",
        "squizlabs/php_codesniffer": "^3.5",
        "laravel/telescope": "^3.5",
        "zircote/swagger-php": "^3.1",
        "barryvdh/laravel-dompdf": "^0.9.0",
        "ext-json": "*",
        "amrshawky/laravel-currency": "^2.0.0",
        "ext-simplexml": "*",
        "predis/predis":"^1.1.7",
        "pusher/pusher-php-server": "^v3.4.1",
        "october/system": "^2.0",
        "october/backend": "^2.0",
        "october/cms": "^2.0",
        "october/media": "^2.0",
        "october/editor": "^2.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^8.0|^9.0",
        "meyfa/phpunit-assert-gd": "^2.0.0|^3.0.0",
        "fzaninotto/faker": "~1.9",
        "php-parallel-lint/php-parallel-lint": "^1.0",
        "dms/phpunit-arraysubset-asserts": "^0.1.0"
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate --ansi"
        ],
        "post-autoload-dump": [
            "System\\Console\\ComposerScript::postAutoloadDump"
        ],
        "post-update-cmd": [
            "System\\Console\\ComposerScript::postUpdateCmd"
        ],
        "pre-package-uninstall": [
            "System\\Console\\ComposerScript::prePackageUninstall"
        ],
        "test": [
            "phpunit --stop-on-failure"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "autoload": {
        "files": [
            "helpers/helper.php",
            "packages/kount/src/autoload.php"
        ],
        "psr-4": {
            "System\\Console\\": "modules/system/console"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "repositories": {
        "octobercms": {
            "type": "composer",
            "url": "https://gateway.octobercms.com"
        }
    }
}
`

**Comment by daftspunk** [comment]
Hi @webninja156, this appears to be related to the Laravel framework. If you need help with the October CMS platform, please send an email to hello@octobercms.com

**Comment by webninja156** [comment]
hey @daftspunk thank you for your quick reply.  This issue has been resolved in laravel and lumen lastest release. But it still exist in october cms could you please suggest something?

**Comment by webninja156** [comment]
hey @daftspunk thank you for your quick reply.  This issue has been resolved in laravel and lumen lastest release. But it still exist in october cms. could you please suggest something?

**Comment by webninja156** [comment]
hey @daftspunk thank you for your quick reply.  This issue has been resolved in laravel and lumen lastest release. But it still exist in october cms. could you please suggest something?
