### ISSUE TITLE
Javascript error when renaming file in Media section

### ISSUE THREAD

**Issue by Wachem** [octobercms/october#5618]
- October v2.1.6

### Description

When using the rename functionality I get an error in the console and the ajax loader keeps 'loading. Cfr:

![image](https://user-images.githubusercontent.com/6443046/131850172-043dcb0b-315e-43b0-9535-eed29f83822c.png)

**Comment by daftspunk** [comment]
Hey @Wachem 

This is fixed in v2.1.7 shipping today

Thanks!
