### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by Apache46** [octobercms/october#5619]
Hi to all,
when i run composer update it gives me this error:

https://repo.packagist.org could not be fully loaded (curl error 60 while downloading https://repo.packagist.org/packages.json: SSL certificate problem: certificate is not yet valid), package information was loaded from the local cache and may be out of date

[Composer\Downloader\TransportException]
  curl error 60 while downloading https://repo.packagist.org/p2/october/system.json: SSL certificate problem: certificate is not yet valid 
  
  I use octobercms 1.1.*
  
  Can someone help me? Thank you

**Comment by daftspunk** [comment]
Hello @Apache46 

This issue is related to SSL (networking):

> Your system clock is likely set in the past.
>
> Ref: https://serverfault.com/questions/549679/issued-certificate-not-yet-valid-with-wget

**Comment by mohamed-dabach** [comment]
for me me this how i fixed it 
[blog](https://how-i-do-fix-it.blogspot.com/2024/10/root-primary-color-2d3748-secondary.html)
