### ISSUE TITLE
Octobercms 2.0 - framework.js has a small bug. It make notify-plugin can't save

### ISSUE THREAD

**Issue by jackyhuynh0407** [octobercms/october#5622]
when click save in notify-plugin it throw error. `$el is not defined`

and I found the problem. how can i submit the code to fixed it?

``` js
if (options.evalBeforeUpdate && $.proxy(new Function('data', options.evalBeforeUpdate), $el.get(0))(data) === false) {
    return;
}
```
just change this in line 153 to: 

``` js
if (options.evalBeforeUpdate && $.proxy(new Function('$el, context, data, textStatus, jqXHR', options.evalBeforeUpdate), $el.get(0))($el, context, data, textStatus, jqXHR) === false) {
     return;
}
```

**Comment by daftspunk** [comment]
Hi @jackyhuynh0407 

Make sure you are using the latest version of the plugin. This should be fixed by the following commit: https://github.com/rainlab/notify-plugin/commit/1703afe36e7996c61967fb12b540ef09cb17585b

I hope this helps!
