### ISSUE TITLE
The form component taglist has problems with Chinese input

### ISSUE THREAD

**Issue by ZhiweiWu0425** [octobercms/october#5626]
The form component taglist has problems with Chinese input
When typing Chinese on the keyboard, before the Chinese characters are selected, the taglist will record the keyboard letters as tags. This problem will cause Chinese users to be unable to use the backend form normally

Demonstration process:
1. Download Microsoft Chinese Input Method or Sogou Input Method (https://pinyin.sogou.com/)
2. Enter "beijing" on the keyboard and press the space bar. If it is correct, "北京" will be printed. "北京" is a tag

**Comment by jackyhuynh0407** [comment]
@daftspunk update the select2 js to v4.1.0-rc that will fix the issue. Note: after update you need to fix some css. If you can let me make pull a request. I just fixed it yesterday.

**Comment by daftspunk** [comment]
@jackyhuynh0407 Please send an email to hello@octobercms.com to discuss

Thanks!

**Comment by jackyhuynh0407** [comment]
@daftspunk Please check your email. Thanks

**Comment by daftspunk** [comment]
This should be fixed in the next release (v2.1.19)

Thanks
