### ISSUE TITLE
Unable to update Octobercms 1.x through composer

### ISSUE THREAD

**Issue by Klaasie** [octobercms/october#5628]
The most recent [security advisory](https://github.com/octobercms/october/security/advisories/GHSA-6gjf-7w99-j7x7) said to affect version 2.1.11 and was fixed in 2.1.12. It seems this advisory was picked up by Roave/SecurityAdvisories as everything < 2.1.12 was affected. Meaning we're now unable to update composer when using version 1.

Some additional information:
The commit of 6 november that added OctoberCMS: https://github.com/Roave/SecurityAdvisories/commit/bad3752fd78f4a07acb24e56fec0366aa711f150#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L181

The commit from the FriendsOfPHP that resulted in the Roave/SecurityAdvisories update: https://github.com/FriendsOfPHP/security-advisories/commit/9951b99dda2aeef9db18cfd196b89b2595c6f2ec

**Comment by daftspunk** [comment]
The advisory has been updated to specify the version `>2.1` instead and hopefully it will resolve the issue. We will be cognizant of this in future.

**Comment by daftspunk** [comment]
Should be fixed by https://github.com/Roave/SecurityAdvisories/commit/7129fb80fbff54e4803659b5ebda7d8d10e6a3e9

🤞
