### ISSUE TITLE
[Question]  Returning 404 from a component

### ISSUE THREAD

**Issue by DanielHitchen** [octobercms/october#563]
Why is that I sometimes get:

```
HTTP/1.0 200 OK Cache-Control: no-cache Date: Mon, 18 Aug 2014 11:47:46 GMT
```

at the top of the page when using:

```
return Response::make( $this->controller->run('404'), 404 );
```

in a component, in the `onRun()`?

**Comment by sozonovalexey** [comment]
The problem still exists. Yes, I see 404 error page but the headers are wrong

Request URL:http://octobercms.info/docs/123
Request Method:GET
Status Code:200 OK

**Comment by LukeTowers** [comment]
@sozonovalexey Please open a new issue if you are having a problem with the headers being set by a 404 response in your project following the contribution guidelines.
