### ISSUE TITLE
Wrong updates available for fresh installation of October CMS v1.1

### ISSUE THREAD

**Issue by ericp-mrel** [octobercms/october#5630]
Just setup a fresh installation of October CMS and keep notification it wants to install an update for build 473 even though this doesn't apply, because that is for October CMS v1.0 not v1.1.

Running `php artisan october:version` or `php artisan october:util set build` does not set the build number in the database and thus, I will keep getting notifications to apply an update for the wrong build and cannot install any plugins through the marketplace.

**Comment by ericp-mrel** [comment]
Forgot to add screenshots:

![Screenshot from 2021-11-24 17-10-18](https://user-images.githubusercontent.com/63664924/143324051-1a797bd7-c976-4e5b-ad7d-a72f6cfecf5e.png)

![Screenshot from 2021-11-24 17-10-31](https://user-images.githubusercontent.com/63664924/143324063-209083eb-f742-4f1a-a95f-c862f73bede9.png)

**Comment by ericp-mrel** [comment]
Looks like the SourceManifest class now references a file from a repo that no longer exists?

```php
$this->setSource(
                Config::get(
                    'cms.sourceManifestUrl',
                    'https://raw.githubusercontent.com/octoberrain/meta/master/manifest/builds.json'
                )
            );
```

**Comment by daftspunk** [comment]
Hi @ericp-mrel 

Make the change to your configuration file (config/cms.php) in this commit and it should solve it. 

c101238eba2f6367d8887ef7b12992d78fd298f9

Hope this helps!
