### ISSUE TITLE
"A non well formed numeric value encountered" when "upload_max_filesize" is lowercase

### ISSUE THREAD

**Issue by Hunman** [octobercms/october#5634]
When `ini_get('upload_max_filesize')` returns with a string that ends with lowercase, the `array_search()` can't find it in the array

Wanted to send in a merge request, but haven't worked with split subtrees before, so I'll just link the commit with my fix:
https://github.com/Hunman/october/commit/5423d4f30b693464cf7eb8704f57c98158a52656

There's more info in the commit message

**Comment by daftspunk** [comment]
Hi @Hunman!

This should be fixed in v2.1.23 already. Are you running the latest?

**Comment by Hunman** [comment]
Thank you, we were one single patch behind
```
  - Upgrading october/backend (v2.1.22 => v2.1.23)
```
