### ISSUE TITLE
Mailing in docker

### ISSUE THREAD

**Issue by austyuzhaninov** [octobercms/october#5635]
Hi there!
I'am trying to send email in my plugin. I use develop tree for local project and for docker image. locally, october works correctly, in docker image the letter does not queue up and is not sent.

route.php

    Route::group(['prefix' => 'api/v1'], function () {
        Route::apiResource('mails', MailController::class)->middleware('api')->only(['store']);
    });

MailController.php

    use October\Rain\Support\Facades\Mail;
    ...
    Mail::queueOn(
        'emails',
        'acme.blog::mail.new_mail',
        $lead->toArray(),
        function ($message) use ($address) {
            $message->to($address, null);
            $message->subject('new mail');
        });

smtp settings (.env)
```
MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=mail
MAIL_PASSWORD=pass
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=mail
MAIL_FROM_NAME="${APP_NAME}"
```

php7.4
October 2.1

Postman gives 500 error and empty result.
Nginx have only 500 error.
October sys log is empty too. (config/app.php set 'log' => 'errorlog')

Is there any specifics for sending emails from docker image?
Thanks in advance!

**Comment by daftspunk** [comment]
Hi @austyuzhaninov 

For support with the platform, please send an email to hello@octobercms.com

Thanks!
