### ISSUE TITLE
error on upload image in the backend

### ISSUE THREAD

**Issue by DrJimmyJazz** [octobercms/october#5637]
I have an error everytime I try to add an image to any mode in the backend. The code haven't been edited but I use this method very frequently to add image. I tried to run compose update and clear the cache but it didn't fix it.

`  $monImage =  $src;
        //Meme fonction que dans importfile.php
        $info = pathinfo($monImage);
        $image_file = (new File)->fromData($this->curl_get_contents($monImage), strtok($info['basename'], '?'));
        $data->images()->add($image_file);
`

the code work well it's only in the backend that it dsn't work. it dsn't work for every modele (user , shopaholic product, my own plugins etc...)

Upload error
copy(/home/n3rd/public_html/e-illimitees/storage/app/uploads/public/622/b59/06a/622b5906aa75a521034520.jpg): failed to open stream: No such file or directory.

![Capture d’écran 2022-03-11 094437](https://user-images.githubusercontent.com/97046434/157891733-636c5285-63e5-49de-b0ed-6557e812039c.png)

**Comment by daftspunk** [comment]
Hi @DrJimmyJazz 

It looks like the folder `/storage/app/uploads/public` does not exist in your application. Have you checked that it is there?
