### ISSUE TITLE
Plugin deployer not working

### ISSUE THREAD

**Issue by bossleem** [octobercms/october#5642]
I can't find where the error lies, but I think it's with the jquery framework.

This repository is only for keeping an archive of previous information about October CMS. If you need support, please contact us via the contact page:

- Contact Us: https://octobercms.com/contact

For submitting translations. Please open a pull request to this repo:

- https://github.com/octobercms/october/pulls

For documentation changes. Please open a pull request to this repo:

- https://github.com/octobercms/docs/pulls

**Comment by daftspunk** [comment]
Hey. Try clearing your browser cache, if using v3 it just had a big client side update. 

Hope this is it!

**Comment by bossleem** [comment]
<img width="1581" alt="Screen Shot 2022-05-13 at 12 31 42" src="https://user-images.githubusercontent.com/43752982/168218004-1b80490e-91b2-4d12-a09d-206544e69589.png">

the problem is in the file "plugins/rainlab/deploy/widgets/deployer/partials/_execute.htm"

i tried a small "alert(1)" script on the file "plugins/rainlab/deploy/widgets/deployer/partials/_execute.htm" but it doesn't work

**Comment by daftspunk** [comment]
Hello,

A patch is made. Please update to v3.0.31 and try again

**Comment by bossleem** [comment]
Ok. thanks you verymuch
