### ISSUE TITLE
Filter on list controller error

### ISSUE THREAD

**Issue by bossleem** [octobercms/october#5643]
Filter with switch scope only works with the first scope, from the 2nd switch scope onwards, it doesn't work

This repository is only for keeping an archive of previous information about October CMS. If you need support, please contact us via the contact page:

- Contact Us: https://octobercms.com/contact

For submitting translations. Please open a pull request to this repo:

- https://github.com/octobercms/october/pulls

For documentation changes. Please open a pull request to this repo:

- https://github.com/octobercms/docs/pulls

**Comment by daftspunk** [comment]
Fixed in latest. Thanks!
