### ISSUE TITLE
Backend is not available

### ISSUE THREAD

**Issue by webfalter** [octobercms/october#5644]
OctoberCMS Build: 3.0.33
PHP version: 8.1.4
![Bildschirmfoto 2022-05-15 um 15 03 30](https://user-images.githubusercontent.com/481551/168474696-3daba862-9602-4a48-b74d-fd8cb6126d35.png)

Backend is not available
Frontend everything is fine

Before updating with

OctoberCMS Build: 3.0.16
PHP version: 8.1.4
everything was still fine.

**Comment by webfalter** [comment]
it is not clear between upper and lower case in the controller
for example
modules/backend/controllers/
Index.php to index.php works

**Comment by daftspunk** [comment]
Hello

Please try the following command:

```
php artisan cache:clear
```

If it doesn't work, manually delete the PHP files found in `storage/framework/[classes|packages|services].php`

I hope this helps.
