### ISSUE TITLE
Twig v2.15.0 causes issues throughout system

### ISSUE THREAD

**Issue by guus-frenken** [octobercms/october#5645]
I just ran `php artisan october:update` and noticed `twig/twig` was automatically updated to v2.15.0 which was released yesterday.

I am using October CMS v2.2.22. I am not sure if this issue is relevant for October v1 and v3 users.

Ever since Twig v2.15.0 was installed, I have been getting numerous errors in templates that contain Twig. This is the error:

`Symfony\Component\Debug\Exception\FatalThrowableError: Object of class October\Rain\Foundation\Application could not be converted to string in [[project url]\vendor\twig\twig\src\Node\Expression\CallExpression.php:303]`

An example of a piece of Twig code that triggers the error is the `|trans` filter.

The workaround is to simply downgrade to the previous version of twig 2.x by running `composer require twig/twig:2.14.13` in the root directory of your project.

**Comment by daftspunk** [comment]
Hey @guus-frenken 

Thanks for the report. Update to v2.2.24 for the fix.

Best
