### ISSUE TITLE
Unexpected token "name" of value "if" ("end of statement block" expected) after Octobercms 3 update

### ISSUE THREAD

**Issue by haralake** [octobercms/october#5646]
In documentation i saw breaking Change Overview:

Twig Conditions In For Loop
This breakage relates to the upgraded version of Twig and is significant enough that we should mention it here. The Twig v3 changelog mentions the following.

* removed the "if" condition support on the "for" tag

I use Octobercms v. 3.0.37 (latest) with installed Rainlab Statick Pages v1.5.0 (latest) plugin and i get this error:

Unexpected token "name" of value "if" ("end of statement block" expected).
~/plugins/rainlab/pages/components/staticmenu/items.htm line 1

```
{% for item in items if not item.viewBag.isHidden %}
...
```

So i guess that rainlab plugins did not updated to support Octobercms v3. Is this correct?

**Comment by daftspunk** [comment]
That's right, fixed in https://github.com/rainlab/pages-plugin/commit/2d2d7971ec70f8aec3dd056ec88f0d8cf1a9576b

Thanks!
