### ISSUE TITLE
bug in Helper::getParameterName prevents correct parameter name parsing with regex wildcards

### ISSUE THREAD

**Issue by alexwenzel** [octobercms/october#5648]
Hi,

I have found the following issue.

My page url looks like this:

```
url = "/country/:id/:slug|^my-slug-.*"
```

When i want to build the url using `Page::url` it is not working:

```
Page::url("my_page.htm", [
    "id"   => $id,
    "slug" => "my-slug-". $slug,
]);
```

Only after fixing `October\Rain\Router\Helper::getParameterName` line 196 with

````
if ($wildMarkerPos !== false && $regexMarkerPos === false) {
````

it works like expected.

**Comment by daftspunk** [comment]
This should be fixed in v3.0.41

Thanks!
