### ISSUE TITLE
Fail to execute “php artisan project:sync“ command

### ISSUE THREAD

**Issue by alanhwi** [octobercms/october#5649]
Hello, during the process of installing octobercms v2.0, when I execute the “php artisan project:sync” command, The following error occurs, (Executing this command on May 16 was successful)

How can I solve it? thanks a lot!

The error message is as follows:

--------------------------------

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/framework[v6.0.0, ..., 6.x-dev] require symfony/http-kernel ^4.3.4 -> satisfiable by symfony/http-kernel[v4.3.4, ..., 4.4.x-dev].
    - symfony/http-kernel[v4.3.4, ..., 4.4.x-dev] conflict with symfony/translation <4.2.
    - vojtasvoboda/twigextensions-plugin[1.3, ..., 1.x-dev] require symfony/translation ~3.3.9 -> satisfiable by symfony/translation[v3.3.9, ..., 3.3.x-dev].
    - Root composer.json requires vojtasvoboda/twigextensions-plugin ^1.3 -> satisfiable by vojtasvoboda/twigextensions-plugin[1.3, 1.x-dev].
    - Root composer.json requires laravel/framework ^6.0 -> satisfiable by laravel/framework[v6.0.0, ..., 6.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

 [ERROR] The command "'composer' 'update'" failed.

         Exit Code: 2(Misuse of shell builtins)

         Working directory: /Users/apple/october/qianxunelec

         Output:
         ================

         Error Output:
         ================
         Loading composer repositories with package information
         Updating dependencies
         Your requirements could not be resolved to an installable set of packages.

           Problem 1
             - laravel/framework[v6.0.0, ..., 6.x-dev] require symfony/http-kernel
         ^4.3.4 -> satisfiable by symfony/http-kernel[v4.3.4, ..., 4.4.x-dev].
             - symfony/http-kernel[v4.3.4, ..., 4.4.x-dev] conflict with
         symfony/translation <4.2.
             - vojtasvoboda/twigextensions-plugin[1.3, ..., 1.x-dev] require
         symfony/translation ~3.3.9 -> satisfiable by symfony/translation[v3.3.9,
         ..., 3.3.x-dev].
             - Root composer.json requires vojtasvoboda/twigextensions-plugin ^1.3
         -> satisfiable by vojtasvoboda/twigextensions-plugin[1.3, 1.x-dev].
             - Root composer.json requires laravel/framework ^6.0 -> satisfiable by
         laravel/framework[v6.0.0, ..., 6.x-dev].

         Use the option --with-all-dependencies (-W) to allow upgrades, downgrades
         and removals for packages currently locked to specific versions.

**Comment by daftspunk** [comment]
Hello, please try the following command before trying it again.

```
composer update -W
```

**Comment by alanhwi** [comment]
After executing the above command, the problem has been solved, thank you very much!
