### ISSUE TITLE
Reordering issue when records already exist

### ISSUE THREAD

**Issue by blakej115** [octobercms/october#5650]
When setting:

```
structure:
    maxDepth: 1
```

using Tailor, if you add this when you already have existing records, you'll get the following error when trying to reorder records:

`"A node cannot be moved to a descendant of itself." on line 930 of /app/app/vendor/october/rain/src/Database/Traits/NestedTree.php`

I was able to get it sorted by manually editing `nest_left`, `nest_right`, and `nest_depth` in the database, but there should be a better way.

I believe I recall facing a similar issue with regular models in October v2 as well.

**Comment by daftspunk** [comment]
To confirm, this happens when changing blueprint `type` from anything else to `structure` and has existing records? We will need to apply initialization logic in this case.

**Comment by daftspunk** [comment]
This should be fixed in the next patch release. When a blueprint type changes type to "structure" then it will apply a repair tool to the existing records.

https://octobercms.com/changelog >= v3.0.60
