### ISSUE TITLE
The backend primary, secondary and accent color customizations are gone in october 2

### ISSUE THREAD

**Issue by StefanGhiban** [octobercms/october#5653]
Hi! I have been trying to change the primary, secondary and accent colors in an october 2 app. Previously, in october 1 we had 3 color pickers in the System/Customize Backend page. Now, these are gone and I cant find a way to change them.

**Comment by daftspunk** [comment]
Hey @StefanGhiban 

This is correct, version 2 has introduced an updated design and disabled the primary, secondary and accent color customizations. However, we plan on bringing this back. 

Please add your use case to this roadmap item: 
https://portal.octobercms.com/c/38-white-labeling?utm_medium=social&utm_source=github

It helps us prioritize the next feature to work on.

As a workaround for smaller adjustments, it is possible to customize the backend using a custom CSS stylesheet.

**Comment by StefanGhiban** [comment]
@daftspunk Hi. I understand, but for now, how can I customize those colors? Is there a guide somewhere to tell me how can I customize the backend? what classes should I override? The only thing I want is to override the 3 colors mentioned above. Can you please tell me, or guide me to the resource that tells me how to do this? Thank you.

**Comment by daftspunk** [comment]
Hi @StefanGhiban 

This guide is applicable for v3 sites since it uses Bootstrap 5: https://getbootstrap.com/docs/5.0/customize/css-variables/

However, we have not tested this in its current state. Note version 3 is practically stable at this point; we are just finishing up some features before releasing it. I hope this helps.

**Comment by StefanGhiban** [comment]
> https://getbootstrap.com/docs/5.0/customize/css-variables/

@daftspunk Does this guide also apply to v2?

**Comment by daftspunk** [comment]
Hi @StefanGhiban 

Unfortunately not due to the need to support IE11. It has been applied to v3 onwards. We've bumped the roadmap priority +1 for you. Regarding the CSS styles, you can selectively change elements using custom CSS in the branding area (via settings or config). Here is an example of changing the primary buttons

```
.btn.btn-primary {
    background: red;
}
```

I hope this helps as a workaround.

**Comment by StefanGhiban** [comment]
@daftspunk The things I want to override are those 3 colours I have mentioned before. Using those 3 colors, the whole application would take a nice appearence. The problem with your approach is that I have to find each class that is responsible for the layouts and override it. I have done so, but the admin panel becomes ugly as you have to search for every possible class and this is not feasible to be honest. It would be nice if you could tell me, or guide me through what should I override to reach the same effect that resulted from the change of those 3 previous color combinations. Overriding the btn primary like in boostrap does not help me, I do not want to override that. I just want to override the behavior that those 3 color options had before. That's it.

**Comment by daftspunk** [comment]
I understand. I wrote the code for this previous style sheet in v1 and it took several weeks. What I'm suggesting let's you make minor adjustments. You'll need to wait for me to build this style sheet again for v3. It is on the road map.

**Comment by StefanGhiban** [comment]
> I understand. I wrote the code for this previous style sheet in v1 and it took several weeks. What I'm suggesting let's you make minor adjustments. You'll need to wait for me to build this style sheet again for v3. It is on the road map.

@daftspunk Can you please tell me which bootstrap version is being used in v2? Thank you.

**Comment by daftspunk** [comment]
Hi @StefanGhiban, October v2 uses an internal fork of Bootstrap 3 called Storm UI. October v3 uses Bootstrap 5 natively. I hope this helps!
