### ISSUE TITLE
"assetVar" option on theme form fields doesn't supported?

### ISSUE THREAD

**Issue by haralake** [octobercms/october#5662]
After updated to latest Octobercms version v3.1.2 (from 3.0.70) i notticed error on frontend:
`ScssPhp\ScssPhp\Exception\CompilerException: Undefined variable $default-color......`

"assetVar" option on theme form fields doesn't supported on latest version?

If it is no longer supported it is a big problem as too many themes use this feature for customization directly in scss. Many bootstrap themes use theme combiner variables in SCSS.

**Comment by daftspunk** [comment]
This is a bug introduced by multisite. Please update to v3.1.3 and clear the cache (`php artisan cache:clear`), and that should fix it. Thanks for finding this.
