### ISSUE TITLE
Page url that starts with locale letters, causes to switch site

### ISSUE THREAD

**Issue by MilosStanic** [octobercms/october#5672]
This is for October v 3.1.

When I have a site defined for Turkish language, which has a locale prefix "tr", and I have a page in another language whose URL starts with "tr", for example "trends", and I visit this url from the default site (let's say it's English), October switches to Turkish site.  

So, again, when I currently set my site language to English, and I have a link in English called "trends", when I click on that link it will switch to Turkish site because I guess it parses the "tr" in the page URL. 

Note: the default language is not prefixed, only the non-default language versions have the prefixed urls.

Thanks.

**Comment by daftspunk** [comment]
Hi @MilosStanic 

Thanks for reporting this, it will be fixed in v3.1.26
