### ISSUE TITLE
What could cause undefined is not an object (evaluating '$.oc') and missing jQuery errors?

### ISSUE THREAD

**Issue by m1aar** [octobercms/october#5673]
Hello, I'm not sure what I did, probably enabling/disabling rainlab.debugbar plugin but I'm not sure, but right now I'm getting some js errors in the backend and most of the things dont work properly, like "Editor", "lists/tables" etc.?

```
TypeError: undefined is not an object (evaluating '$.fn')
undefined is not an object (evaluating '$.oc')
 Can't find variable: jQuery
```

**Comment by m1aar** [comment]
any idea?

**Comment by daftspunk** [comment]
Hi @m1aar 

This can happen when jQuery is not loaded. Check the developer tools to make sure there are no network problems. If the file doesn't download, then it won't load.

I hope this helps.

**Comment by xyzqtc** [comment]
@daftspunk thanks for you help!

But I still cant solve the problem. What I can see is most of the scripts are commented out on load. What could cause this problem?

<img width="576" alt="Screenshot 2022-12-05 at 12 20 42" src="https://user-images.githubusercontent.com/78330971/205625511-380c2ab3-7b38-42e2-a2a8-3e77758f1e71.png">

**Comment by m1aar** [comment]
<img width="576" alt="Screenshot 2022-12-05 at 12 20 42" src="https://user-images.githubusercontent.com/116883422/205630468-f949a416-a1c1-4fa1-a920-11961b4a7504.png">
not sure if cloudflare has something to do with it, these scripts are commented out.
