### ISSUE TITLE
Inspector data-property-xxx attributes do not support complex values.

### ISSUE THREAD

**Issue by ssi-com-pl** [octobercms/october#5676]
Hi. I'm trying to add an object editor to my component/snippet:

![image](https://user-images.githubusercontent.com/57666038/206649026-2fb7dd40-c6a5-4bd1-9904-2f755858527c.png)
![image](https://user-images.githubusercontent.com/57666038/206649440-797d28b2-b1ed-4e97-8bac-74c5f92f851b.png)

Works great as a component. But when I try to add a code snippet to a static page and edit the options I get an error and I can't close the options screen.
![image](https://user-images.githubusercontent.com/57666038/206648186-4b38dd6f-ce3b-48ef-b802-3c8066f91c45.png)

CMS version: 2.2.34

**Comment by daftspunk** [comment]
Hi. It's a known issue that we will address in next iteration of snippets.

**Comment by daftspunk** [comment]
I see now this is just an error in the syntax...

**Comment by daftspunk** [comment]
This is fixed in October CMS v3.4
