### ISSUE TITLE
Missing parenthesis in the query when using orWhere 

### ISSUE THREAD

**Issue by anestism** [octobercms/october#5679]
If you have a model query like:
 ->where(...)->orWhere(...) the final SQL query looks like
" ... and is not null and .... or .... ", but it should be " ... and is not null and ( ... or ... )".

This happened in version 3.1.28

**Comment by daftspunk** [comment]
Hello @anestism 

Please modify your query like this

```
->where(function($q) {
    $q->where(...)->orWhere(...);
});
```

I hope this helps

**Comment by anestism** [comment]
Hello @daftspunk ,

thank you for the reply. Yes, that code is working. I found it in Laravel's documentation as well and I think it is worth to be included in the OCTOBERCMS documentation.
