### ISSUE TITLE
Tailor  ignoring permissions settings when only primaryNavigation is set

### ISSUE THREAD

**Issue by fgschafer** [octobercms/october#5682]
I'm using OC v3.1.28.
If in the blueprints you only set primaryNavigation and not navigation (this is useful in case you don have other submenu items) the permission settings of the backenduser is ignored, giving multiple Denied Access pages.

**Comment by daftspunk** [comment]
Hi @fgschafer 

This should be fixed in v3.1.29.  Parent items now have the permissions set.

Thanks!
