### ISSUE TITLE
Default locale APP_LOCALE being ignored in sites admin page

### ISSUE THREAD

**Issue by fgschafer** [octobercms/october#5683]
Even though I changed the default locale var in .env file, it seems that the default locale on the sites admin page always shows 'en'.
Using OC v3.1.28
<img width="475" alt="Screen Shot 2023-01-02 at 12 17 58" src="https://user-images.githubusercontent.com/5186031/210250638-512d25fc-3e25-4318-8e9d-bf20d0cd9ca8.png">

Is this ok or is it a bug?

IMPORTANT: Besides, when not using english, at least in spanish, the values are not correctly dynamic, so all of the defaults show ":valor"

<img width="513" alt="Screen Shot 2023-01-02 at 12 33 23" src="https://user-images.githubusercontent.com/5186031/210252170-a0f0d0dc-5f8b-43e0-9f63-d2c9d09af8cb.png">

**Comment by Samuell1** [comment]
Hey, for backend there is new config option to set language separately here:

https://github.com/octobercms/october/blob/3.x/config/backend.php#L158

**Comment by daftspunk** [comment]
Indeed, it's a bug. It will be [fixed in v3.1.29](https://octobercms.com/changelog) along with the translations.

Thanks!
