### ISSUE TITLE
Why do I only see a few plugins and themes in the marketplace？

### ISSUE THREAD

**Issue by Jiawulin** [octobercms/october#5685]
Why do I only see a few plugins and themes in the marketplace？

I remember there were many。

![image](https://user-images.githubusercontent.com/8336695/210973854-91cabac0-97a0-41ae-9c2b-cf668fff2172.png)

**Comment by daftspunk** [comment]
Hi @Jiawulin 

Change the dropdown to "Any version" to see everything. Most plugins and themes are loosely compatible with any version of October CMS, however, not all are actively maintained by their authors. I hope this helps!
