### ISSUE TITLE
Feature Request: Reorder Entries in Tailor

### ISSUE THREAD

**Issue by ogalbnafets** [octobercms/october#5686]
Hello!

It seems that in Tailor, its not possible to order the entries. 
So for a collection, I can not set the view order, I just can setup the already defined sorting mechanisms.

Is it a big deal to make this possible?
I found out, that it is possible to implement this feature in a plugin, but I'm clueless how to make this possible in Tailor.

Thanks in advance!

**Comment by artistro08** [comment]
Hey! So you can reorder tailor entries. Just make sure the blueprint for the tailor entry is set to `structure` instead of `stream`. Once you've verified this, go to the tailor entries page and hover over an item. A handle will appear and you can reorder the entries

**Comment by ogalbnafets** [comment]
> Hey! So you can reorder tailor entries. Just make sure the blueprint for the tailor entry is set to `structure` instead of `stream`. Once you've verified this, go to the tailor entries page and hover over an item. A handle will appear and you can reorder the entries

Wow thank you! I missed this at there was no much documentation about structures. Your tailor-starter looks wild, I will definitely have a deep look into it! Thanks!

I will close this hehe
