### ISSUE TITLE
Plugin upgrade : is it possible to use old branch on October 2, new branch on October 3

### ISSUE THREAD

**Issue by CarolinePublipresse** [octobercms/october#5691]
Hi, 
we made a plugin, and recently planned major changes on it. Some elements won't be compatible. 
As we are moving from October 2 to October 3, we wonder if we can make the new branch installed on new October 3 websites, but prevent form old sites on October 2 to update and stay on the first branch.

I set my new branch version to 2.0.0 and added in its composer.json a requirement : 
```
"require": {
  "october/rain": "^3.2"
}
```
will it be enought to prevent old installs updates (it would break), and allow these old plugins to still be maintained if needed ? 
Is it the right method ?

**Comment by daftspunk** [comment]
Hi @CarolinePublipresse,

Yes, this will prevent older versions from using the newer plugin. There are a few additional steps:

1. Provide instructions on how to install v1 in the README file (eg: `composer require vendor/some-plugin "^1.0"`)
2. Provide compatibility information to the marketplace (Author → Product → Settings → Compatibility)

For point 2, specifically, if you set the compatibility option for October CMS v1 to something, this is what the older gateway will deliver to those users. So if they should get `v1.2.3`, set the value to `1.2`

Here is example of the RainLab.Translate plugin. It suggests v1 should be used for October CMS 1 and 2, and v2 (latest) should be used for October CMS 3.

![image](https://user-images.githubusercontent.com/1392869/212805573-51cdf590-0390-4916-ba41-d3608c64a93f.png)

I hope this helps.

**Comment by CarolinePublipresse** [comment]
It helps a lot, thank you very much

**Comment by Eoler** [comment]
> Yes, this will prevent older versions from using the newer plugin.

This is great @daftspunk - does it also work for themes?

**Comment by daftspunk** [comment]
Yes, it work for themes as well.
