### ISSUE TITLE
{% page %} not resolving Page Finder links

### ISSUE THREAD

**Issue by andysh-uk** [octobercms/october#5692]
Sorry if this is not the correct place to report a bug. Please let me know if there is somewhere else better (other than paid support, I'm no comfortable paying for support when I believe this to be a bug.)

In 3.2.7 and the Pages plugin 1.5.7 (which the release notes said added Page Finder support) the {% page %} tag is not resolving the Page Finder links.

My layout is as simple as:

```
<div class="lead text-muted fs-4" style="font-size: x-large;">
    {% page %}
</div>
```

I've added a link in the Pages rich text editor to a Tailor record linked to a CMS page.

The link in my HTML is output as:

```
<div class="lead text-muted fs-4" style="font-size: x-large;">
    <p>.... text .... <a href="october://entry-740ddc13-a45b-491e-b90c-84b49b898288@link/2?cms_page=software%2Fapplication">.... link text ....</a>.... other text ....</p>
</div>
```

I've tried adding the twig filter [as suggested here](https://docs.octobercms.com/3.x/element/form/widget-pagefinder.html#linking-to-pages) however this is a built-in tag, not a field or variable I can pass to "|link".

**Comment by daftspunk** [comment]
Hi @andysh-uk 

That's ok, bugs in the platform do not require paid support. Paid support is used when you need us to help with bugs in your own code.

A fix for this has been pushed today. Please update to Static Pages v1.5.8 and try again. The links should resolve now. 

Best regards.

**Comment by andysh-uk** [comment]
Hi @daftspunk 

Thanks for such a quick fix :)

Does the URL parameter have to be called something specific to resolve correctly?

My CMS page (where the link is pointing to) has a URL of `/software/:application`.  This looks up a Tailor record where the slug equals the `:application` parameter.

![image](https://user-images.githubusercontent.com/12907944/213462905-e397148a-1249-4c4e-92ab-f7181174018d.png)

When I add the link, I select the Tailor record and the CMS page is automatically populated.

`{% page %}` now resolves the URL correctly, but it points to `/software/default`, instead of `/software/simply-remind-me` (the slug is "simply-remind-me.")

**Comment by daftspunk** [comment]
Hey @andysh-uk 

The lookup keys supported are `:id`, `:slug` and `:fullslug`. 

Where does `:application` come from, is it a form field definition on the blueprint ?

**Comment by andysh-uk** [comment]
Thanks @daftspunk 

I think I had tried :slug just in case.

:application is on the URL of my CMS page that displays the Tailor record.

So my CMS page has the URL /software/:application, then there is a Tailor Section component that looks up a “software” record based on the “:application” URL parameter.

I am trying to use the Page Finder to point a link in a page’s content to a software record (e.g. /software/simply-remind-me).

**Comment by andysh-uk** [comment]
Ah I missed something obvious the other day - although I’d changed the page’s link, I hadn’t re-inserted the link in page finder.

I’ve just changed my page’s parameter to :slug, re-created my link in page finder and this works perfect.

Thanks 😃
