### ISSUE TITLE
Dynamic availableColors in theme.yaml

### ISSUE THREAD

**Issue by ssi-com-pl** [octobercms/october#5694]
Hi! Can someone explain how to create dynamic aviableColors in /themes/xyz/theme.yaml?

I found this but don't know how to use it with a theme instead of a plugin.
![image](https://user-images.githubusercontent.com/57666038/213381406-92be92ff-1971-4d57-bfbf-9d1166e676f0.png)

**Comment by daftspunk** [comment]
The GitHub issue list is for reporting bugs in the October CMS code base specifically. Please try the following support avenues for getting support with using October:

- [October CMS Forum](https://talk.octobercms.com/)
