### ISSUE TITLE
Unable to install octoberCMS

### ISSUE THREAD

**Issue by LTiollier** [octobercms/october#5698]
Hello ✋🏼 

Since yesterday, I can no longer initialize an OctoberCMS project. I have an error in the terminal.

![Capture d’écran 2023-01-25 à 10 30 29](https://user-images.githubusercontent.com/16253697/214527953-35298072-6a54-4757-82d7-a0a50be2314f.png)

I'm on Mac and i'm using Valet. I test with PHP8.2 and PHP8.1.

**Comment by daftspunk** [comment]
Hi @LTiollier 

PHP Version issue causes this. For reference:

- October CMS v2 is compatible with PHP 7.4 and 8.0
- October CMS v3 is compatible with PHP 8.0, 8.1 and 8.2

**Comment by LTiollier** [comment]
Hello !

My bad ! Thx for the response.
