### ISSUE TITLE
Create repeater field with morph to many relationship

### ISSUE THREAD

**Issue by devmansurov** [octobercms/october#5702]
In my model defined `images` field as `jsonable`:

    protected $jsonable = ['images'];

I have like this field in my model `fields.yml` file:

    images:
        label: 'Images'
        prompt: 'Add image'
        maxItems: '1'
        span: left
        containerAttributes:
            items: '1'
        type: repeater
        tab: 'Images'
        form:
            fields:
                img_big:
                    label: 'Big image'
                    mode: image
                    span: auto
                    type: mediafinder
                img_mini:
                    label: 'Mini image'
                    mode: image
                    span: auto
                    type: mediafinder
                alt:
                    label: 'Image Alt'
                    span: left
                    type: text
                title:
                    label: 'Image Title'
                    span: right
                    type: text

The example above works great. But now I have changed the structure of the database by adding a new table for images to separate them.

**Tables:**

 - images 
 - imageables

Then inside my model defined relation for images:

    public $morphToMany = [
      'images' => [
          Image::class,
          'table' => 'my_plugin_imageables',
          'name' => 'imageable'
      ]
    ];

In this case how I can create correctly repeater field with **form behaviors** when images has morph to many relationship?

**Comment by daftspunk** [comment]
Hi @devmansurov 

Take a look at this commit: https://github.com/octobercms/test-plugin/commit/eff308d7847936c4bc52ea47c2568854a881d529

It has useful information in creating repeater items as related models.

I hope this helps.

**Comment by iboved** [comment]
Hi, @daftspunk!

Is Grouped Repeaters work with Related Records? How to handle AttachOne/AttachMany relations in RepeaterItem model if some repeater groups use the same name for fileupload field types?

Thanks)

**Comment by daftspunk** [comment]
Hey @iboved 

It works, and you need to define relations used by all groups.

It is OK for groups to share the same relation name. If you ensure every related field in every group is defined, it should work and currently works like this in Tailor.
