### ISSUE TITLE
Custom field added to cms page model not saved until settings modal is opened and applied

### ISSUE THREAD

**Issue by fgschafer** [octobercms/october#5704]
I'm adding a custom field to the CMS Page Model (using OC 3.1.18), as explained in the october site, in a plugin boot method like this:
```
Event::listen('cms.template.extendTemplateSettingsFields', function ($extension, $dataHolder) {
            if ($dataHolder->templateType === 'page') {
                $dataHolder->settings[] = [
                    'property' => 'robots_noindex',
                    'title' => 'Sitemap No Index',
                    'type' => 'checkbox',
                    'default' => false
                ];
            }
        });
```
The checkbox is added ok.  But, unlike OC 0.X / 1.X, if you create a page and just hit save (without opening the settings modal) the field is not saved as the default.  In fact is not saved at all, until you open the settings modal and hit apply and save.  In this case I'm counting on having a default value, even if I didn't open the settings modal.

**Comment by daftspunk** [comment]
Hi @fgschafer 

The new editor is a rewrite and so its behavior will differ when compared with v1. It is advisable to expect no value and apply a default internally for these instances. This is because a user can update the file manually to not include any value.

I hope this helps.
