### ISSUE TITLE
scss @use breaks styling

### ISSUE THREAD

**Issue by aarondiel** [octobercms/october#5706]
adding `@use "sass:math"`, which should be part of the [sass built in modules](https://sass-lang.com/documentation/modules), results in the file not being compiled.

this can be tested by creating a scss file like this:

```scss
body {
  background-color: red;
}
```

and then adding `@use "sass:math";` anywhere inside the file.

- installed october via composer
- sass version `1.45.0` (from package.json)

**Comment by daftspunk** [comment]
Hi @aarondiel 

This should probably be researched (first) and reported at: https://github.com/scssphp/scssphp

The `scssphp/scssphp` library is used for JIT compilation, when using the asset combiner. The package.json version is used for pre-compilation for the core assets.

**Comment by aarondiel** [comment]
apparently `scssphp` is in many ways not quite compiant with the scss specs.

there are still a number of open issues regarding my problem on the `scssphp` github page, so i will close this issue now.

for now i will have to find some kind of workaround.
