### ISSUE TITLE
'Access denied for user 'root'@'localhost' to database 'information_schema''

### ISSUE THREAD

**Issue by zexter002** [octobercms/october#5707]
'Access denied for user 'root'@'localhost' to database 'information_schema''
WHAT DO I DO I WANT TO DELETE INFORMATON SCHEMA IN KALI LINUX FROM mysql

**Comment by andysh-uk** [comment]
information_schema is a "virtual" database and cannot/should not be deleted.

Why do you feel you need to delete this?
