### ISSUE TITLE
Update to 3.3.2 only updates to 3.3.1

### ISSUE THREAD

**Issue by andysh-uk** [octobercms/october#5710]
The changelog lists 3.3.2 as the current version, but when I updated my two sites from 3.2.x to 3.3.2, it only installed 3.3.1.

The update now says my current version is 3.3.1 and needs updating to 3.3.2, but after installing the updates, the site is still only on 3.3.1.

**Comment by daftspunk** [comment]
Should be fixed now.

Related issue: https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/
