### ISSUE TITLE
bootstrap/scss/variables-dark missing

### ISSUE THREAD

**Issue by ChristianKuhn** [octobercms/october#5711]
Hi!
It seems that the current installation of OctoberCMS 3.3.0 requires Bootstrap >= 5.3 in modules/backend but installs Bootstrap 5.2.3 as a dependency. When running npm run watch for the mix plugin, building fails with:

`ERROR in ./modules/backend/assets/vendor/bootstrap/bootstrap.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
   ╷
17 │ @import "bootstrap/scss/variables-dark"; // Required
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  modules/backend/assets/vendor/bootstrap/bootstrap.scss 17:9  root stylesheet
    at processResult (/var/www/html/node_modules/webpack/lib/NormalModule.js:760:19)
    at /var/www/html/node_modules/webpack/lib/NormalModule.js:862:5
    at /var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/var/www/html/node_modules/sass-loader/dist/index.js:69:5)

ERROR in ./modules/backend/assets/vendor/bootstrap/bootstrap-lite.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
   ╷
17 │ @import "bootstrap/scss/variables-dark"; // Required
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  modules/backend/assets/vendor/bootstrap/bootstrap-lite.scss 17:9  root stylesheet
    at processResult (/var/www/html/node_modules/webpack/lib/NormalModule.js:760:19)
    at /var/www/html/node_modules/webpack/lib/NormalModule.js:862:5
    at /var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/var/www/html/node_modules/sass-loader/dist/index.js:69:5)

2 ERRORS in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 4 errors
`

Apparently variable-dark.scss is missing in the Bootstrap 5.2.3 dep installed by npm. Seems it was added with Bootstrap 5.3.

Hope the info is sufficient. Thanks for October CMS.

**Comment by daftspunk** [comment]
Thanks for reporting this @ChristianKuhn 

We have included the **package.json** file in the upstream sync. This commit should fix it: https://github.com/octobercms/october/commit/735210cd789e07a289afb24f0ad86ce5b59c930d
