### ISSUE TITLE
Custom settings can't be opened after update to October v3.3 and usage of new SettingModel

### ISSUE THREAD

**Issue by tschortsch** [octobercms/october#5712]
Hi,

After upgrading from October 3.2 to 3.3 and migrating our Plugin Settings from implementing the `\System\Behaviors\SettingsModel::class` to extend the `SettingModel` the page can't be opened anymore and throws the following error:
```
array_merge(): Argument #1 must be of type array, null given

in ~/vendor/october/rain/src/Database/ExpandoModel.php line 44
$this->attributes = array_merge($this->{$this->expandoColumn}, $this->attributes);
```

I guess this is happening because of our custom setting only has one relation field (`$belongsToMany`) and no other fields defined. I don't really know for what this `ExpandoModel` is for but I guess the following check in the `expandoAfterFetch()` function should fix the issue:

```
public function expandoAfterFetch()
 {
     if ($this->{$this->expandoColumn}) {
        $this->attributes = array_merge($this->{$this->expandoColumn}, $this->attributes);
     }
     $this->syncOriginal();
 }
```

**Comment by daftspunk** [comment]
Hey @tschortsch 

See if this change helps: https://github.com/octobercms/library/commit/57cd62364a60aba41a9f7b4172f0ff39efe0bd0a

**Comment by tschortsch** [comment]
It does! Quick as always. 🥇  Thanks a lot!
