### ISSUE TITLE
Members area?

### ISSUE THREAD

**Issue by hmsuchier** [octobercms/october#5714]
Hi, 
 Just a question before eventually choosing October as my next project platform. Does it allow "members only" area ? With a registration/subscription form, and content/pages restricted to authenticated members?
Thanks!

**Comment by Eoler** [comment]
> Does it allow "members only" area ? With a registration/subscription form, and content/pages restricted to authenticated members?

Yes, with at least RainLab.User plugin: https://octobercms.com/plugin/rainlab-user

**Comment by hmsuchier** [comment]
Thanks for your answer!
