### ISSUE TITLE
Error: properties.sort is not a function

### ISSUE THREAD

**Issue by ssi-com-pl** [octobercms/october#5716]
I tried to use the code from the documentation:
![image](https://user-images.githubusercontent.com/57666038/229782550-2cc1af01-8bda-4496-a0e2-11331b5dda31.png)
But I can't  edit properties:
![image](https://user-images.githubusercontent.com/57666038/229782914-deea7e8e-aa92-48ba-a0a8-7865b51ece1d.png)
![image](https://user-images.githubusercontent.com/57666038/229782995-27f38155-5d82-48ee-8bbd-b27c33d8158c.png)

**Comment by daftspunk** [comment]
This should be fixed in v3.3.7+

Thanks!
