### ISSUE TITLE
Backend draggable tabs prevents the from content scrolling

### ISSUE THREAD

**Issue by flyingbaba** [octobercms/october#5717]
Our client just noticed that is not possible to drag the contents of the form if tapped to the tabs. IMHO this should be considered as an issue because it is not intuitive and prevents managers from beeing efficient users. 

https://user-images.githubusercontent.com/10512039/229788738-ebc5466e-5d51-446f-93df-902f036a5f34.mp4

Possible solution coud be just to wrap tabs without drag functionality.

**Comment by flyingbaba** [comment]
Forgot to mention october version 2.x

**Comment by daftspunk** [comment]
Hi @flyingbaba 

The logic has improved in v3 as part of a wider refactor. If the tabs don't need to scroll (like in your example) then it doesn't lock the window scroll. If the tabs overflow and do need to scroll, it will scroll to the end of the tabs before scrolling the window.
