### ISSUE TITLE
No language translations for "prohibited" rules

### ISSUE THREAD

**Issue by jexme** [octobercms/october#5719]
No language translations for "prohibited" rules
- [prohibited](https://laravel.com/docs/9.x/validation#rule-prohibited)
- [prohibited_if](https://laravel.com/docs/9.x/validation#rule-prohibited-if)
- [prohibited_unless](https://laravel.com/docs/9.x/validation#rule-prohibited-unless)
- [prohibits](https://laravel.com/docs/9.x/validation#rule-prohibits)

Also decimal:

- [decimal](https://laravel.com/docs/9.x/validation#rule-decimal)

**Comment by daftspunk** [comment]
Fixed by https://github.com/octobercms/october/commit/45f2afd226966efc8f45acff99f8d27a929c8da7
