### ISSUE TITLE
RecordFinder Bug

### ISSUE THREAD

**Issue by hackolein** [octobercms/october#5721]
Hello,

I think I found a bug in the RecordFinder widget, when you specify a modelClass and take as keyFrom not ID but a custom key. When selecting a record, Undefined appears in the field. The correct value is saved, but after a reload the value is not written back into the field. Here is my config of the field:
`form_code:

        label: Formular
        type: recordfinder
        tab: Allgemein
        title: Formular auswählen
        list:
            columns:
                name:
                    label: renatio.formbuilder::lang.field.name
                    searchable: true
        keyFrom: code
        useRelation: false
        modelClass: Renatio\FormBuilder\Models\Form`

I have solved the problem as follows.
`modules/backend/formwidgets/RecordFinder.php`
I change in getLoadValue method the call find method in 
`$value = $this->modelClass::where($this->getKeyFromAttributeName(), $value)->first();`
Line 280

Maybe cam someone check this.

many greetings
Heiko

**Comment by daftspunk** [comment]
Hello Heiko!

Thank you for this suggestion, we have included this fix in the next patch release.

Best regards
