### ISSUE TITLE
Page Finder widget with structure and fullslug with wildcard route

### ISSUE THREAD

**Issue by VojtechKlos** [octobercms/october#5725]
Hello,

I have a problem with url resolving in Page Finder widget.

I have created a Tailor blueprint of type "structure" and I am using a page with url `/product/:slug*`. When I try to select the correct Tailor entry it let's me select it correctly but the URL generated is always `/product/default` no matter if I select the parent entry or nested one. The final url should look something like this: `/product/app` for the parent and `/product/app/mobile` for the nested posts. The slug is always `default` now.

Currently I use a workaround of manually typing the url in the Page Finder but I would like this to be automated.

Thanks for reply.

**Comment by VojtechKlos** [comment]
By the way the same thing happens when I use the Static Pages plugin menus.

**Comment by snipiba** [comment]
> Hello,
> 
> I have a problem with url resolving in Page Finder widget.
> 
> I have created a Tailor blueprint of type "structure" and I am using a page with url `/product/:slug*`. When I try to select the correct Tailor entry it let's me select it correctly but the URL generated is always `/product/default` no matter if I select the parent entry or nested one. The final url should look something like this: `/product/app` for the parent and `/product/app/mobile` for the nested posts. The slug is always `default` now.
> 
> Currently I use a workaround of manually typing the url in the Page Finder but I would like this to be automated.
> 
> Thanks for reply.

i think, when you wish an optional slug, then it was `/product/:slug?` instead of `*` at ending, right?

**Comment by VojtechKlos** [comment]
> 

Yes that is true. However `*` is wildcard that matches everything. It is described in documentation here

https://docs.octobercms.com/3.x/cms/themes/pages.html#url-syntax

In my case I want the wildcard parameter to match both `/product/app` and `/product/app/mobile`. The URL parameter is not optional here.

EDIT:
The website is working correctly. The routing is not an issue. What is an issue however is that the Page Finder widget does not resolve the URL correctly and always generates `/default` even though the entry has full slug `/app/mobile`

**Comment by daftspunk** [comment]
Hi @VojtechKlos ,

Changing the URL definition to `/product/:fullslug*` should incorporate the full slug from the model.

A newer pattern we are using in v3.4 demo theme is to include the ID in the URL at the end, so it is still nice for SEO, and the slug can change about freely without breaking links. It implements a permanent redirect for any previous URLs. Here is a summarized example:

```twig
url = "/product/:fullslug*/:id"

[section product]
handle = "Acme\Product"
entrySlug = "{{ :id }}"
entryColumn = "id"
==
{% if product is empty %}
    {% do abort(404) %}
{% elseif product.fullslug != this.param.fullslug %}
    {% do redirect(''|page({ slug: article.fullslug }), 301) %}
{% endif %}

<!-- Contents here -->
```

**Comment by VojtechKlos** [comment]
> Hi @VojtechKlos ,
> 
> Changing the URL definition to `/product/:fullslug*` should incorporate the full slug from the model.
> 
> A newer pattern we are using in v3.4 demo theme is to include the ID in the URL at the end, so it is still nice for SEO, and the slug can change about freely without breaking links. It implements a permanent redirect for any previous URLs. Here is a summarized example:
> 
> ```
> url = "/product/:fullslug*/:id"
> 
> [section product]
> handle = "Acme\Product"
> entrySlug = "{{ :id }}"
> entryColumn = "id"
> ==
> {% if product is empty %}
>     {% do abort(404) %}
> {% elseif product.fullslug != this.param.fullslug %}
>     {% do redirect(''|page({ slug: article.fullslug }), 301) %}
> {% endif %}
> 
> 
> ```

Hello!

I can confirm putting `/product/:fullslug*` as URL definition works. It is a bit inconvenient naming wise but still perfectly usable. Thanky you!

**Comment by daftspunk** [comment]
Glad you got it sorted! Yes, we will hopefully come up with a nice solution that allows flexible URL parameters in the future. At the moment the lookup is too expensive to occur at runtime and hurt performance.
