### ISSUE TITLE
Non backend super-users shouldn't be able to create new users without a role

### ISSUE THREAD

**Issue by najbo** [octobercms/october#5726]
A non super-user can create a new backend user without a role assigned. When creating the new user, an error occurs, saying : "Form record with an ID of 7 could not be found.". To be noted : the user is not member of Developer or Publisher role.

![Capture d'écran 2023-05-23 101820](https://github.com/octobercms/october/assets/18056783/17270f98-9fba-4456-bf14-a10794aa78dd)

The new created user does not appear in the adminstrator list, but it appears in the list when logged as a super-user.

Here are the permissions of the non super-user with role "Administrateurr OMO" that created a new user : 

![Capture d'écran 2023-05-23 102233](https://github.com/octobercms/october/assets/18056783/820fdb65-d3ac-46c3-90cc-5b0e2452e763)

And the role hierarchy : 

![Capture d'écran 2023-05-23 102352](https://github.com/octobercms/october/assets/18056783/0acf1233-ef7f-4203-9192-e942fe50fe24)

My question : shouldn't it be prohibited to create a new user **without** a role ? Allowing this will conduct the non super-user to create again the same user, again and again.

By the way, I also noticed that the role hierarchy had to be moved once "manualy" in order to list subsequent roles (maybe because the field "sort_order" of table "backend_users_roles" was left empty after an OCMS Update ; probably this works on fresh OCMS installations).

PHP : 8.2
OCMS : 3.3.14

**Comment by daftspunk** [comment]
Hey @najbo 

> shouldn't it be prohibited to create a new user without a role ?

Yes, we should make the role field required for non-superadmins. You've found a way to create an inaccessible user which is undesirable.

> By the way, I also noticed that the role hierarchy had to be moved once "manualy" in order to list subsequent roles

That's right, you need to sort the list at least once to activate this feature.

**Comment by najbo** [comment]
Hi Sam,

Thank you very much for your kind answer and for the reminder (sorting at least 1 element in a list to activate feature).

Regards,
Jan

**Comment by daftspunk** [comment]
Hey Jan,

This is fixed in v3.3.18 - The role field is now a required field for non super users. Moving forward, this should prevent the lockout scenario described by this issue.

Thanks!

**Comment by najbo** [comment]
Thanks a lot Sam !

 

I wish you a nice & happy day.

 

Best regards,

Jan

 

De : daft ***@***.***> 
Envoyé : 31 mai 2023 03:20
À : octobercms/october ***@***.***>
Cc : Jan Boech ***@***.***>; Mention ***@***.***>
Objet : Re: [octobercms/october] Non backend super-users shouldn't be able to create new users without a role (Issue #5726)

 

Hey Jan,

This is fixed in v3.3.18 - The role field is now a required field for non super users. Moving forward, this should prevent the lockout scenario described by this issue.

Thanks!
