### ISSUE TITLE
Custom CSS not working

### ISSUE THREAD

**Issue by ssi-com-pl** [octobercms/october#5727]
Hi! The code entered in the 'custom_css' field in Brand Settings does not work. October v3. I cleared the cache. Also Custom Color Palette doesn't work.

**Comment by daftspunk** [comment]
Hey @ssi-com-pl 

Make sure you have valid CSS/LESS in there. If there is something invalid, it will print the error to the page and may take the appearance of not working. Check the source to confirm, you might see something like

```html
    <style>
        /* ParseError: Unexpected input in anonymous-file-0.less on line 43, column 40
41|     }
42| }
43| #layout-mainmenu { background: purple; !important } */    </style>
```

We should make a note to include validation as part of the form saving to catch this earlier.

**Comment by ssi-com-pl** [comment]
The background of the counter should change from red to green:
![image](https://github.com/octobercms/october/assets/57666038/af52d8a9-965f-447b-baf1-d20c8d347b40)
There are no errors in the browser DevTools. I don't find my code in the page source, but I found this:
![image](https://github.com/octobercms/october/assets/57666038/41925bae-d9c0-46d8-869e-51df2dfb6409)

**Comment by ssi-com-pl** [comment]
I found the problem! The custom color palette must have all fields filled in:
![image](https://github.com/octobercms/october/assets/57666038/a4c21ea1-0e59-4155-a5bb-09cfa1394c5d)
