### ISSUE TITLE
MinIO S3

### ISSUE THREAD

**Issue by 1Khaireddine** [octobercms/october#5729]
When I install `league/flysystem-aws-s3-v3` to manage disks, after set all settings in the `filesystems.php` and `.env`, I have been finding this error below,

`ERROR 
We're sorry, but an unhandled error occurred. Please see the details below. 
Undefined array key "region" 
~/vendor/aws/aws-sdk-php/src/S3/S3Client.php line 730`

**Comment by snipiba** [comment]
did you configure whole config file filesystems.php under /config ?
``

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
            'throw' => false,
        ],
``

**Comment by daftspunk** [comment]
Hi @khaireddine19 

It looks like your [default region](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) is not configured or is missing from the configuration values. In October CMS this configuration is controlled by config/filesystems.php

```php
'disks' => [
    // ...
    's3' => [
        // ...
        'region' => env('AWS_DEFAULT_REGION'),
        // ...
    ],
],
```

Some things to try:

- Setting it to a static value
- Setting the environment variable at the OS level

Alternatively, the repo for this package can be found here: https://github.com/thephpleague/flysystem-aws-s3-v3

Hopefully this helps,

Best regards

**Comment by 1Khaireddine** [comment]
Hello @daftspunk,
TThanks for that answer, I have defined a default region in ‘. Env' but it is the same for this error.
`AWS_DEFAULT_REGION=ca-central-1`

**Comment by 1Khaireddine** [comment]
```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Filesystem Disk
    |--------------------------------------------------------------------------
    |
    | Here you may specify the default filesystem disk that should be used
    | by the framework. A "local" driver, as well as a variety of cloud
    | based drivers are available for your choosing. Just store away!
    |
    */

    'default' => env('FILESYSTEM_DRIVER', 's3'),

    /*
    |--------------------------------------------------------------------------
    | Filesystem Disks
    |--------------------------------------------------------------------------
    |
    | Here you may configure as many filesystem "disks" as you wish, and you
    | may even configure multiple disks of the same driver. Defaults have
    | been setup for each driver as an example of the required options.
    |
    | Supported Drivers: "local", "ftp", "sftp", "s3"
    |
    */

    'disks' => [

        'local' => [
            'driver' => 's3',
            'root' => storage_path(env('AWS_BUCKET')),
            'throw' => false,
        ],

        'uploads' => [
            'driver' => 's3',
            'root' => storage_path(env('AWS_BUCKET')."/uploads"),
            'url' => env('AWS_BUCKET')."/uploads",
            'visibility' => 'public',
            'throw' => false,
        ],

        'media' => [
            'driver' => 's3',
            'folder' => '/',
            'root' => storage_path('app/media'),
            'url' => env('AWS_BUCKET')."/media",
            'visibility' => 'public',
            'throw' => false,
        ],

        'resources' => [
            'driver' => 's3',
            'root' => storage_path(env('AWS_BUCKET')."/resources"),
            'url' => env('AWS_BUCKET')."/resources",
            'visibility' => 'public',
            'throw' => false,
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'bucket' => env('AWS_BUCKET'),
            'region' => env('AWS_DEFAULT_REGION'),
            'use_path_style_endpoint' => true,
            'url' => env('AWS_URL'),
            'visibility' => 'public',
            'throw' => false,
        ],

    ],

];

```

**Comment by daftspunk** [comment]
Could you kindly verify the version of `league/flysystem-aws-s3-v3` that is currently installed? You can find this information in the composer.json file.

**Comment by 1Khaireddine** [comment]
> Could you kindly verify the version of `league/flysystem-aws-s3-v3` that is currently installed? You can find this information in the composer.json file.

"league/flysystem-aws-s3-v3": "^3.15"

**Comment by daftspunk** [comment]
I can confirm that this version is compatible with version 3 of October CMS. For all other versions, it is recommended to use the flysystem driver version ~1.0.

**Comment by Khaireddine-dev** [comment]
@daftspunk 
`
composer require league/flysystem-aws-s3-v3 "^1.0"

./composer.json has been updated
Running composer update league/flysystem-aws-s3-v3
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages
`

**Comment by 1Khaireddine** [comment]
@daftspunk 
Is not the best solution !!!

**Comment by daftspunk** [comment]
Could you kindly confirm the version of October CMS that you are using?
