### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by jkluo** [octobercms/october#5732]
![image](https://github.com/octobercms/october/assets/12638923/df580782-b36d-424b-a8ee-7a2c2cc061ac)
help me .

**Comment by daftspunk** [comment]
Hi, it looks like the October CMS gateway is missing. You can set it again with the following command

```
php artisan project:set <key>
```

I hope this helps. If you need further assistance, feel free to reach out to the team at hello@octobercms.com

Best regards
