### ISSUE TITLE
Error thrown after update to 3.4.5

### ISSUE THREAD

**Issue by cajunpepper** [octobercms/october#5733]
I just used the console to run an October Update in my development environment: 
```
php artisan october:update
```

which resulted in this error:
```
Finishing update process
------------------------

In Macroable.php line 113:
   Method October\Rain\Foundation\Application::registerClassAliases does not exist.
[ERROR] Migration failed. Check output above
```

This 100% broke everything in my project. So, I couldn't try any other artisan commands (eg. cache:clear, etc.). I went as far as completely deleting my ~/vendor folder and running a fresh composer install, which resulted in the same error.

I was able to trace through the stack and find that \modules\cms\ServiceProvider.php and \modules\tailor\ServiceProvider.php both have a new method, ::registerRenamedClasses(), that is calling a nonexistent method, $this->app->registerClassAliases();

The class October\Rain\Foundation\Application does have a singular version of the method, registerClassAlias(), and making the following quick adjustments to each of the ServiceProvider.php files fixed the problem:

In \modules\cms\ServiceProvider.php line 372
```
protected function registerRenamedClasses()
    {
        foreach ([ \Cms\Classes\PageLookup::class => \Cms\Classes\PageManager::class ] as $k => $v)
        {
            $this->app->registerClassAlias($k, $v);
        }
        /*$this->app->registerClassAliases([
            \Cms\Classes\PageLookup::class => \Cms\Classes\PageManager::class,
        ]);*/
    }
```

In \modules\tailor\ServiceProvider.php line 174
```
protected function registerRenamedClasses()
    {
        foreach([
                    \Tailor\Models\EntryRecordImport::class => \Tailor\Models\RecordImport::class,
                    \Tailor\Models\EntryRecordExport::class => \Tailor\Models\RecordExport::class
                ] as $k => $v)
        {
            $this->app->registerClassAlias($k, $v);
        }

        /*$this->app->registerClassAliases([
            \Tailor\Models\EntryRecordImport::class => \Tailor\Models\RecordImport::class,
            \Tailor\Models\EntryRecordExport::class => \Tailor\Models\RecordExport::class
        ]);*/
    }
```

After the changes, I was able to execute the migration console command successfully and my staging site is back in action:
```
php artisan october:migrate
```

So to me, it seems like an update to October\Rain\Foundation\Application to add the registerRenamedClasses() method must have not gotten pushed into the release.

**Comment by daftspunk** [comment]
Hi @cajunpepper 

It does indeed look like your environment is [missing some critical files](https://github.com/octobercms/library/blob/3.x/src/Foundation/Application.php#L399). Some things to check:

- Make sure `october/rain` version matches `october/system`
- Restart your web server
- Run `composer update`

I hope this helps.

**Comment by cajunpepper** [comment]
Thanks for the speedy response!

There was no "october/system" in my composer.json at all only
"october/rain" and "october/all".  Adding it, restarting apache, and
running composer update resolved the issue.

Not sure why that was missing as I haven't edited it manually. I do greatly
appreciate your help!

**Comment by daftspunk** [comment]
No problem. Glad you got it sorted!

`october/all` includes `october/system` so you can remove it again if you like. Most likely it was a failed composer update, running `composer update` should refresh the files too.
