### ISSUE TITLE
Problems after update

### ISSUE THREAD

**Issue by ssi-com-pl** [octobercms/october#5734]
Hi! Yesterday I updated cms to version 3.4.5
Everything worked fine until now.

The Repeater field has stopped working:
- I can't reorder items
- I can't view the settings and remove repeater item (settings are empty)
![image](https://github.com/octobercms/october/assets/57666038/4613836e-c3a4-44e0-a80a-0db2b2b817e4)
![image](https://github.com/octobercms/october/assets/57666038/689db294-f0e1-45d9-88de-0694a5419710)
![image](https://github.com/octobercms/october/assets/57666038/3fd0601b-fd40-47a1-bda6-500e668ac979)

Latest plugin versions and october compilation not loading:
![image](https://github.com/octobercms/october/assets/57666038/21255606-9fc0-4822-9547-8df02fde3f11)
![image](https://github.com/octobercms/october/assets/57666038/bd6d5c32-6f31-47df-a067-84306d8a850d)

Site switcher error:
![image](https://github.com/octobercms/october/assets/57666038/6727a6fd-419c-4811-be2a-d5e5391829cc)
![image](https://github.com/octobercms/october/assets/57666038/c981a1f0-ddb0-4c3a-961e-5e76db1748d9)

**Comment by ssi-com-pl** [comment]
I ran Composer Update but it didn't help.
![image](https://github.com/octobercms/october/assets/57666038/2fe3a482-dba4-493f-a398-0b33856ad452)

composer.json:
![image](https://github.com/octobercms/october/assets/57666038/4309c4a0-3f2c-4cf4-9a7d-22c82c6c0ae8)

**Comment by daftspunk** [comment]
Please try clearing the browser cache to see if it helps.

**Comment by ssi-com-pl** [comment]
@daftspunk unfortunately, clearing cache didn't help

**Comment by daftspunk** [comment]
The `oc.FoundationPlugin` object comes from the file **backend/assets/js/foundation-min.js**. Check to see if it is loaded. Otherwise, please send us an email hello@octobercms.com for personalized support.

Thanks!

**Comment by ssi-com-pl** [comment]
@daftspunk  The file is loaded but doesn't contain any code
![image](https://github.com/octobercms/october/assets/57666038/ca51f303-2719-47eb-a328-8f33a9daa653)

**Comment by daftspunk** [comment]
Thanks @ssi-com-pl 

I hope this means it wasn't picked up by a virus scanner... Please try running `composer update` to restore the file contents.
