### ISSUE TITLE
update issues with dev-develop

### ISSUE THREAD

**Issue by rajakhoury** [octobercms/october#5735]
composer.json

        "php": "^8.0.2",
        "october/all": "dev-develop",
        "october/rain": "dev-develop",
        "laravel/framework": "^10.0",
        
Update error;

![1](https://github.com/octobercms/october/assets/4506434/31ffd3e1-2fac-4d65-84d7-dcf457158068)

**Comment by daftspunk** [comment]
We have updated `dev-develop` for `october/all`. Please try again.

**Comment by rajakhoury** [comment]
Thanks!
