### ISSUE TITLE
Fallback getAttribute to Eloquent Model

### ISSUE THREAD

**Issue by Xaero** [octobercms/october#5739]
When using casts that resolve to a class, f.e. when using https://github.com/spatie/laravel-schemaless-attributes, October does not work due lack of support in the getAttribute method in the Model class.

Would it be possible to fall back to the Eloquents getAttribute method, when the 'normal' behaviour of Octobers getAttribute do not suffice?

Ref: https://github.com/wintercms/winter/issues/776

**Comment by daftspunk** [comment]
No problem, see if this fixes it:

https://github.com/octobercms/library/commit/35dff9660ca59c9c3cdc99b9e135eec7041c43f0
