### ISSUE TITLE
How about Crowdin?

### ISSUE THREAD

**Issue by anik1ng** [octobercms/october#5740]
Hello! We want to help translate October CMS. How about Crowdin?

**Comment by croqo** [comment]
> Hello! We want to help translate October CMS. How about Crowdin?

How about [RTFM](https://docs.octobercms.com/3.x/extend/system/localization.html#contributing-language-strings)? 🙂

**Comment by anik1ng** [comment]
> How about [RTFM](https://docs.octobercms.com/3.x/extend/system/localization.html#contributing-language-strings)? 🙂

If you compare language files for different languages, you will see that these files are different. And sometimes, developers like to change lines in core lang files (en).

Try to compare lines in files — https://github.com/octobercms/october/blob/3.x/modules/tailor/lang/ru.json, https://github.com/octobercms/october/blob/3.x/modules/tailor/lang/en.json

Absolutely different files. Tracking file changes line by line is very difficult.

**Comment by daftspunk** [comment]
A project has been established in Crowdin using the link below. 

---
### https://crowdin.com/project/octobercms
---

The following languages have been included:

- [ ] `fr` @OlinB @MallauryGerard @najbo
- [ ] `de` @DavidBrogli @tobias-kuendig 
- [ ] `fi` @mediaclinic
- [ ] `nl` @adrenth @jacobdekeizer 
- [ ] `pl` @yersey
- [ ] `pt-br` @prhost @peuweb
- [ ] `ru` @FlusherDock1 @igor-tv
- [ ] `sl` @BlazOrazem
- [ ] `uk` @croqo
- [ ] `zh-cn` @ZhiweiWu0425
- [ ] `hu` @gergo85 
- [ ] `sk` @Samuell1

Please let us know if your language needs to be added and if you want to use Crowdin. 

Dormant languages may be replaced with more active ones. The documentation has been updated with additional instructions https://github.com/octobercms/docs/commit/73a8eeadd89bff4062e5711c8fb82bec29f865f1

Enjoy <3
