### ISSUE TITLE
Line graph is not compatible with dark mode

### ISSUE THREAD

**Issue by Dahfrenk** [octobercms/october#5743]
<img width="827" alt="Scherm­afbeelding 2023-07-29 om 17 14 30" src="https://github.com/octobercms/october/assets/11441869/39b523b7-0aa5-40be-a048-51fd284015ae">

The line graph will always show with a light background.
This is rendered within the canvas.

**Comment by daftspunk** [comment]
Thanks @Dahfrenk 

Patch coming for this in v3.4.12

![image](https://github.com/octobercms/october/assets/1392869/845bc041-f50e-4df4-a2fc-f7ae3aa408be)
