### ISSUE TITLE
Read-only fields not properly styled in dark mode

### ISSUE THREAD

**Issue by Dahfrenk** [octobercms/october#5744]
<img width="791" alt="Scherm­afbeelding 2023-07-29 om 17 17 14" src="https://github.com/octobercms/october/assets/11441869/3cd5419a-ee00-45a3-b2dc-fc2fd3d5b4ab">
Read only fields do not have the proper background in dark mode. I am assuming they need the same styling the disabled fields have.

<img width="805" alt="Scherm­afbeelding 2023-07-29 om 17 20 19" src="https://github.com/octobercms/october/assets/11441869/1e1f7165-2c02-4bea-b201-39ed6de733c3">

I have currently added my own CSS to patch this;

`.form-control[readonly="readonly"], .form-control[disabled="disabled"] {
background-color: var(--oc-form-control-disabled-bg) !important;
}`

**Comment by daftspunk** [comment]
Hmm, I can't seem to reproduce this one. 

![image](https://github.com/octobercms/october/assets/1392869/ffac57f9-83ae-46f9-a90e-b8ed157a2ebd)

In above screenshot, **Name** is `readOnly: true` and **Slug** is `disabled: true`

Can you verify the source of the styling when the modification is removed? Could it be a plugin?

**Comment by Dahfrenk** [comment]
Ah yes sorry you were right. The bright background of the field was a mistake from myself. I was indeed overriding it with own styling. The original issue I had was that readonly fields have no color difference to regular input fields so it was unclear for a user which fields could or could not be filled in.

But if this is intentional then you can close this issue, personally I would have the same styling on readonly as on disabled.

**Comment by daftspunk** [comment]
This display is intentional from Bootstrap, which appears based on native HTML behaviour. Keeping a visual difference between readOnly and disabled is desirable.

IIRC read-only inputs used to grey out the text. Now, looking at Chrome, they appear to look identical to write-enabled inputs.
