### ISSUE TITLE
Tailor + Page Finder on multisite gives wrong (?) references

### ISSUE THREAD

**Issue by morelmm** [octobercms/october#5745]
Hi, i've been struggling to make menu for tailor entries for my website and i've found that Page Finder entries are not working properly for sites other than default sites due to reference numbers form tailor taken from site_root_id fields instead of record id field. site_root_id is the id of base record of default site, so adding page finder records to other sites with id of base site does not work.
so changing /modules/tailor/classes/blueprintindexer/PageManagerRegistry.php:85
```
// $id = $record->site_root_id ?: $record->id;
$id = $record->id;
```
made this working properly
maybe i'm wrong, then correct me :D but for my case it's working

**Comment by daftspunk** [comment]
Hey @morelmm 

Thanks for reporting this. Please update to v3.4.12 to see if it resolves the issue. We used a slightly different change to fix it.

**Comment by uitlaber** [comment]
> Hi, i've been struggling to make menu for tailor entries for my website and i've found that Page Finder entries are not working properly for sites other than default sites due to reference numbers form tailor taken from site_root_id fields instead of record id field. site_root_id is the id of base record of default site, so adding page finder records to other sites with id of base site does not work. so changing /modules/tailor/classes/blueprintindexer/PageManagerRegistry.php:85
> 
> ```
> // $id = $record->site_root_id ?: $record->id;
> $id = $record->id;
> ```
> 
> made this working properly maybe i'm wrong, then correct me :D but for my case it's working

This work for me! Thanks! ) Just replace it

**Comment by uitlaber** [comment]
It's not fixed today :(

**Comment by uitlaber** [comment]
> Hi, i've been struggling to make menu for tailor entries for my website and i've found that Page Finder entries are not working properly for sites other than default sites due to reference numbers form tailor taken from site_root_id fields instead of record id field. site_root_id is the id of base record of default site, so adding page finder records to other sites with id of base site does not work. so changing /modules/tailor/classes/blueprintindexer/PageManagerRegistry.php:85
> 
> ```
> // $id = $record->site_root_id ?: $record->id;
> $id = $record->id;
> ```
> 
> made this working properly maybe i'm wrong, then correct me :D but for my case it's working

Working! Thanks!

**Comment by daftspunk** [comment]
Hey @uitlaber 

We've changed the iterator function in v3.6.18, hopefully it helps

```php
$iterator = function($records) use (&$iterator) {
    $result = [];
    $hasMultisite = null;
    foreach ($records as $record) {
        $hasMultisite ??= $record->isClassInstanceOf(\October\Contracts\Database\MultisiteInterface::class) &&
            $record->isMultisiteEnabled();

        $id = $hasMultisite ? ($record->site_root_id ?: $record->id) : $record->id;
        if (!$record->children) {
            $result[$id] = $record->title;
        }
        else {
            $result[$id] = [
                'title' => $record->title,
                'items' => $iterator($record->children)
            ];
        }
    }
    return $result;
};
```
