### ISSUE TITLE
Column selectable not translate

### ISSUE THREAD

**Issue by winai543** [octobercms/october#5747]
In file: modules/backend/widgets/lists/partials/_column_selectable.php

Line: 27

`<?= implode(', ', $selectedValues) ?>`

Change To 

`<?= implode(', ', array_map(function($value){ return e(__($value)); }, $selectedValues)) ?>`

**Comment by daftspunk** [comment]
Hey @winai543 

Thanks for this bug report. It will be fixed in the next patch release (v3.4.14)

BTW - There is an `Arr::trans` helper for this type of thing:

```
<?= e(implode(', ', Arr::trans($selectedValues))) ?>
```

Hopefully it helps!
