### ISSUE TITLE
Error Create new backend user with database prefix 

### ISSUE THREAD

**Issue by zimbar** [octobercms/october#5751]
Hi,
I just installed the latest version of october cms with composer and I put "oc_" as a prefix for the mysql database. The installation went well and I was able to access the backend.

but when I want to add a new admin user I get this error

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'oc_oc_system_files.id' in 'IN/ALL/ANY subquery' (SQL: select * from `oc_system_files` where (`oc_oc_system_files`.`id` in (select `slave_id` from `oc_deferred_bindings` where `master_field` = avatar and `master_type` = Backend\Models\User and `session_key` = SaZHYqrUMTlI1v8a9XWCQlupSEamR2fJQZOjP3QH and `is_bind` = 1)) and `oc_oc_system_files`.`id` not in (select `slave_id` from `oc_deferred_bindings` where `master_field` = avatar and `master_type` = Backend\Models\User and `session_key` = SaZHYqrUMTlI1v8a9XWCQlupSEamR2fJQZOjP3QH and `is_bind` = 0 and id > ifnull((select max(id) from oc_deferred_bindings where slave_id = oc_system_files and master_field = avatar and master_type = Backend\Models\User and session_key = SaZHYqrUMTlI1v8a9XWCQlupSEamR2fJQZOjP3QH and is_bind = 1 ), 0)) order by `sort_order` asc)

Same thing if I want to customize the backend

"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'oc_oc_system_files.id' in 'IN/ALL/ANY subquery' (SQL: select * from `oc_system_files` where (`oc_oc_system_files`.`id` in (select `slave_id ` from `oc_deferred_bindings` where `master_field` = logo and `master_type` = Backend\Models\BrandSetting and `session_key` = A09V8zAYFDg80MeqLm5pFmt5GIXHVbv9gp9PtQ6B and `is_bind` = 1)) and `oc_oc_system_files`.`id` not in (select `slave_id` from `oc_deferred_bindings` where `master_field` = logo and `master_type` = Backend\Models\BrandSetting and `session_key` = A09V8zAYFDg80MeqLm5pFmt5GIXHVbv9gp9PtQ6B and `is_bind` = 0 and id > ifnull((select max(id) from oc_deferred_bindings_ where slave_id = oc system_files. id and master_field = logo and master_type = Backend\Models\BrandSetting and session_key = A09V8zAYFDg80MeqLm5pFmt5GIXHVbv9gp9PtQ6B and is_bind = 1 ), 0)) order by `sort_order` asc)"

There is a problem with the table prefix

Thanks

**Comment by daftspunk** [comment]
Hi @zimbar 

This should be fixed in https://github.com/octobercms/library/commit/0ebeae46b86097442576d25b2ebbfbe004800228 and available in the next patch v3.4.16

Thanks!

**Comment by zimbar** [comment]
Hi,

Thanks
