### ISSUE TITLE
Table prefix error with list search

### ISSUE THREAD

**Issue by zimbar** [octobercms/october#5753]
Hy,

I have a database with table prefix, all work fine except when i want to search via a list grid, there is a query error because the prefix is duplicated in the name of the table

my prefix is "edt_" normally the name of the table in the query should be "edt_rinc_magento_sales_invoice"  and not "edt_edt_rinc_magento_sales_invoice" 

![Capture d’écran du 2023-09-21 09-26-41](https://github.com/octobercms/october/assets/1899203/3ef66d71-3b88-4522-94fa-a06da298bcd4)

Thanks

**Comment by daftspunk** [comment]
Thanks, this will be fixed in the next patch
