### ISSUE TITLE
rainlab-blog-content_html-formHtml is truncates the html behind the first firstChild

### ISSUE THREAD

**Issue by DZotya** [octobercms/october#5754]
Hi,

The Post model of the rainlab blog plugin has a formatHtml() calling for the content_html in the beforeValidate(). Inside formatHtml() there is a processTag calling inside the ParsedonwnExtra. 

In my opition this line is wrong _(ParsedownExtra:630 - processTag method)_:
`$DOMDocument->replaceChild($DOMDocument->firstChild->firstChild->firstChild, $DOMDocument->firstChild);`

This truncates the html text behind the first child.

For example:
`$elementMarkup = '<p><img src="dog.jpg"></p><p>teszt</p>';`

After the `$nodeMarkup = $DOMDocument->saveHTML($Node);` the $nodeMarkup will contain the first tag and the other tags will be truncated.
But the this line `$DOMDocument->replaceChild($DOMDocument->firstChild->firstChild, $DOMDocument->firstChild);` holds the body content and not only the first tag.

**Comment by daftspunk** [comment]
Hello @DZotya 

What version of October CMS are you using?

**Comment by DZotya** [comment]
Hello @daftspunk 
I'm using the v3.5.0 of October CMS.

**Comment by daftspunk** [comment]
Thanks for confirming. There are some patches to the Markdown parser in this version but this specific issue is addressed in the documentation here: https://docs.octobercms.com/3.x/extend/services/parser.html#using-html-in-markdown

I hope this helps!
