### ISSUE TITLE
Problem with export page ("File not found")

### ISSUE THREAD

**Issue by MartinZboril** [octobercms/october#5763]
Hello, sometimes it happens to me that after exporting records, when I go to the export form page again, I get the message "File not found".

After exporting the records, I click on completed and I am redirected to the page that is set in the export configuration redirect property(correctly). Then I go to the export page again, but the url is loaded with the name of the previous downloaded file, e.g. /download/oc6553ab88d1663xcsv/export.csv, so it throws me "File not found". Is there any cache that will add the preview file concept to my url?

![Screenshot 2023-11-14 at 18 09 20 (2)](https://github.com/octobercms/october/assets/24566086/557cc191-9835-4f09-b2cf-177ddbe07e59)

**Comment by MartinZboril** [comment]
Hello, do you have any ideas how to fix the problem?

**Comment by daftspunk** [comment]
Hi @MartinZboril 

It looks like the export is not creating the file in the temporary directory, usually found in the /storage/temp directory. Make sure it is writable and readable by the web server.

If the export is CSV, the logic to save to this location is found in `Backend\Models\ExportModel\EncodesCsv::processExportDataAsCsv`

If you are exporting in JSON, the logic to save to this location is found in `Backend\Models\ExportModel\EncodesJson::processExportDataAsJson`

This logic should display an error if the write fails, however, this error would occur only if it failed silently.

I hope this helps.
