### ISSUE TITLE
Allow Maintenance Mode per Site / Site Group

### ISSUE THREAD

**Issue by sqwk** [octobercms/october#5764]
Currently one can select different maintenance mode pages per site, but can only toggle the mode on/off globally. Please allow individual maintenance modes per site/site group.

**Comment by daftspunk** [comment]
This has been added to the next minor release, included as configuration key `multisite.cms_maintenance_setting`.

https://github.com/octobercms/october/blob/fb583d105f1ef28cf72c776aa8501a111bcd4146/config/multisite.php#L28

Thanks
