### ISSUE TITLE
[Feature] Assigning content to a selected website + linking pages

### ISSUE THREAD

**Issue by michallkanak** [octobercms/october#5766]
I am looking for a solution in which I will be able to present selected, language-compatible content for a given website, for example documentation in many languages. That is, you can simply assign a page/article to a given website.

An additional advantage would be to link pages/articles from different languages to each other, so as to present the language change for a given article.

I looked at the code and it wouldn't be too complicated, are you planning to add something like this in the near future?

**Comment by daftspunk** [comment]
Hi @michallkanak 

If I understand correctly, take a look at the Multisite feature. This is already integrated with Tailor and allows different content for another site. It should serve the use-case of a documentation site using different languages.

Here is a link to the documentation: https://docs.octobercms.com/3.x/cms/resources/multisite.html

The `newOtherSiteQuery` query method allows you to query articles found on other sites.

I hope this helps!
