### ISSUE TITLE
Last update v.3.5.14

### ISSUE THREAD

**Issue by az-vm** [octobercms/october#5767]
Hello, 

regular update on the system, but on the end got this message on terminal:

Setting build number
--------------------

In OctoberUpdate.php line 76:
                                                        
  Call to undefined function System\Console\passthru()  
                                                        

Doing a composer update, got this:

> System\Console\ComposerScript::postAutoloadDump

In ComposerScript.php line 89:
                                                        
  [Error]                                               
  Call to undefined function System\Console\passthru()  
                                                        

What could be ?

**Comment by daftspunk** [comment]
Hi @az-vm 

The `passthru` command allows shell commands to run other shell commands. It looks like this PHP function has been blocked on your server.

**Comment by az-vm** [comment]
@daftspunk hum... strange i have this website on this server for some months and have update it before with no issues... i will check.

The config files on the folder i think i did not update them for sometime, could be? I will try. -> Done! Not solve the issue.

**Comment by az-vm** [comment]
@daftspunk your right! the passthru,escapeshellarg was disabled on the php settings on the hosting... i have enabled and now updates with no error! Thank you for pointing the right direction!

![unnamed](https://github.com/octobercms/october/assets/2712273/0f5b17a0-f457-4c4b-847d-63a221980791)

**Comment by az-vm** [comment]
@daftspunk your right! the passthru,escapeshellarg was disabled on the php settings on the hosting... i have enabled and now updates with no error! Thank you for pointing the right direction!

![unnamed](https://github.com/octobercms/october/assets/2712273/d4832e7a-00c7-4746-b2fc-37e7cfc3a008)
