### ISSUE TITLE
Column not found: 1054 Unknown column 'nest_depth' in 'field list'

### ISSUE THREAD

**Issue by andysh-uk** [octobercms/october#5768]
I'm logging an issue for this as it is happening on pretty much every Tailor blue print that links to another in my site.

Page Error when editing or creating a Tailor record in a blue print that relates to another "entry" blue print.

```
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nest_depth' in 'field list' in /.../vendor/laravel/framework/src/Illuminate/Database/Connection.php:416
```

The work around is to change the related blue print to a "structure" type, migrate, then back again, and migrate again.

This was discussed here: https://talk.octobercms.com/t/cant-create-tailor-sql-error-unknown-column-nest-depth/2068

**Comment by daftspunk** [comment]
Hey @andysh-uk 

Thanks for this. We found out why it occurred yesterday and made a specific patch for it (v3.5.12). Updating to this version should resolve it.
