### ISSUE TITLE
October 3.6 - InvalidArgumentException: View [lang.strings.mail_form_submit] not found.

### ISSUE THREAD

**Issue by Dahfrenk** [octobercms/october#5780]
After the update to OctoberCMS 3.6 I am receiving the following error when navigating to admin/system/mailtemplates;

`InvalidArgumentException: View [lang.strings.mail_form_submit] not found. in .../vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137`

I am using OctoberCMS in the Dutch system language and I have added custom e-mail templates, if needed I can provide them. My PHP version is 8.3

**Comment by daftspunk** [comment]
Hey @Dahfrenk 

Check the `registerMailTemplates` method. Some older plugins were using this format:

```php
// Invalid syntax from v3.6
[
    'vendor.plugin::view.hint.1' => 'vendor.plugin::lang.string.1',
    'vendor.plugin::view.hint.2' => 'vendor.plugin::lang.string.2',
    'vendor.plugin::view.hint.3' => 'vendor.plugin::lang.string.3',
]
```

The language string part was never used for anything, or documented anywhere, but some plugins were using this syntax (including official ones) and it likely replicated from there.

Change it to either:

```php
// Valid syntax (backward compatible)
[
    'vendor.plugin::view.hint.1',
    'vendor.plugin::view.hint.2',
    'vendor.plugin::view.hint.3',
]
```

Or, if you want to use the 3.6 syntax:

```php
// Newer syntax
[
    'shorter:mail.code.1' => 'vendor.plugin::view.hint.1',
    'shorter:mail.code.2' => 'vendor.plugin::view.hint.2',
    'shorter:mail.code.3' => 'vendor.plugin::view.hint.3',
]
```

Related documentation: https://docs.octobercms.com/3.x/extend/system/sending-mail.html#registering-a-template

Hopefully it helps.

**Comment by Dahfrenk** [comment]
@daftspunk You were right, I was using the format below. I will follow the documentation to revision my function. Thanks!

```    
public function registerMailTemplates()
    {
        return [
            'templates' => [
                'vendor.plugin::mail.form_submit'   => 'vendor.plugin::lang.strings.mail_form_submit',
            ],
            'layouts' => [
                'custom' => 'vendor.plugin::layouts.artisan'
            ],
            'partials' => [
                'custom_header'  => 'vendor.plugin::partials.header',
                'custom_footer'  => 'vendor.plugin::partials.footer',
            ]
        ];
    }
```

**Comment by daftspunk** [comment]
Thanks for reporting back, we've added something to the release notes about this: https://octobercms.com/support/article/rn-37#short-mail-templates
