### ISSUE TITLE
Missing background image on login page

### ISSUE THREAD

**Issue by Dahfrenk** [octobercms/october#5782]
From what I can see, prior to October 3.6 this would be the css on the login page;
```
body.outer .layout>.layout-row>.layout-cell.theme-cell {
    background-color: #fef6eb;
    background-image: url(https:/domain.com/storage/app/uploads/public/654/11a/2e8/65411a2….jpg);
    background-position: left top;
    background-repeat: repeat;
    background-size: cover;
}
```
<img width="353" alt="Scherm­afbeelding 2024-02-24 om 16 26 14" src="https://github.com/octobercms/october/assets/11441869/4e287e11-4606-491d-875a-c335ee778568">

-----

After October 3.6 the login page HTML structure of the login page seems to have changed. 
<img width="355" alt="Scherm­afbeelding 2024-02-24 om 16 32 23" src="https://github.com/octobercms/october/assets/11441869/397e3311-0c3e-4965-aaf1-4e6a5aabbf58">

The CSS is still inline in the head of the page but it is not correct anymore for the new html layout. Below in Dutch my general setup for the login page.
<img width="738" alt="Scherm­afbeelding 2024-02-24 om 16 30 00" src="https://github.com/octobercms/october/assets/11441869/41219a77-8c58-4bb6-a322-c633889b8f4b">

**Comment by daftspunk** [comment]
Thanks for finding this! 

The layout uses flexbox now instead of table layouts. Changing to `body.outer .outer-theme-cell` fixes it. 

We'll get a patch out for this soon (v3.6.1).
