### ISSUE TITLE
Navigation items visible without permissions

### ISSUE THREAD

**Issue by Dahfrenk** [octobercms/october#5783]
After the OctoberCMS 3.6 update I have noticed that a customer can see all the settings and menu items without the permissions to it. When attempting to access the items a no permissions error comes up. But none of the tiles / menu items are hidden anymore.
All of the user permissions are inherited from a role.

If you require more information, please let me know!

**Comment by daftspunk** [comment]
Hey @Dahfrenk 

I can't seem to reproduce this, settings and navigation are hidden as expected based on the role's permissions:

![image](https://github.com/octobercms/october/assets/1392869/09ae46d2-f7a0-435c-9876-b788a43cbd69)

**Comment by Dahfrenk** [comment]
@daftspunk Thank you for your response, I am closing this issue. After some debugging I realized I had a used plugin on this website that caused this issue: https://octobercms.com/plugin/indikator-devtools. After deleting the plugin the issue was resolved. I do wonder if this has always been the case in the past.
