### ISSUE TITLE
In Safari, list filters are not aligned correctly.

### ISSUE THREAD

**Issue by Dahfrenk** [octobercms/october#5785]
Within Safari (It works fine in Chrome) the dropdown filters above a list do not properly align and cause the filter to be higher than intended. See the example below;
<img width="592" alt="Scherm­afbeelding 2024-02-27 om 00 18 47" src="https://github.com/octobercms/october/assets/11441869/59eb0eb7-14ca-458b-9664-8d54685e3cc3">

I have made a small fix that I currently use as custom css, I am not sure if this is the solution you want to implement but it might point you in the right direction;
```
.control-filter>.filter-group {
    vertical-align: middle;

}
```
This results in the following;
<img width="617" alt="Scherm­afbeelding 2024-02-27 om 00 19 01" src="https://github.com/octobercms/october/assets/11441869/daffe2e2-8e85-490f-a666-ac847edcc7e1">

**Comment by daftspunk** [comment]
Fixed in v3.6.4

Thanks!
