### ISSUE TITLE
Wrong Order for displayMode: sidebar on Small Screens

### ISSUE THREAD

**Issue by sqwk** [octobercms/october#5787]
```
design:
    displayMode: sidebar
```

`displayMode: sidebar` displays the "secondary" tabs before the main content on small screens. Being secondary tabs, shouldn't they be displayed between the main fields and the submit button?

**Comment by daftspunk** [comment]
Hi @sqwk 

It's by design since the buttons are part of the left section, it displays the "secondary" tabs before the main content.

Otherwise, it looks like this:

![image](https://github.com/octobercms/october/assets/1392869/6ec2785c-713d-4bb7-83ae-5016d7255d2b)
