### ISSUE TITLE
Class 'Str' not found

### ISSUE THREAD

**Issue by lubinMathew1991** [octobercms/october#5789]
Class 'Str' not found

october cms suddenly stopped and showing

<html>
<body>

(1/1) ErrorClass 'Str' not found
--
in Application.php line 390
at Application->October\Rain\Foundation\{closure}('Illuminate\\Broadcasting\\BroadcastServiceProvider', 0)in EnumeratesValues.php line 371
at Collection->partition(0)in Application.php line 391
at Application->registerConfiguredProviders()in RegisterProviders.php line 17
at RegisterProviders->bootstrap(object(Application))in Application.php line 127
at Application->bootstrapWith(array('October\\Rain\\Foundation\\Bootstrap\\RegisterClassLoader', 'October\\Rain\\Foundation\\Bootstrap\\LoadEnvironmentVariables', 'October\\Rain\\Foundation\\Bootstrap\\LoadConfiguration', 'October\\Rain\\Foundation\\Bootstrap\\LoadTranslation', 'Illuminate\\Foundation\\Bootstrap\\HandleExceptions', 'Illuminate\\Foundation\\Bootstrap\\RegisterFacades', 'October\\Rain\\Foundation\\Bootstrap\\RegisterOctober', 'Illuminate\\Foundation\\Bootstrap\\RegisterProviders', 'Illuminate\\Foundation\\Bootstrap\\BootProviders'))in Kernel.php line 162
at Kernel->bootstrap()in Kernel.php line 146
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 43

</body>
</html>

**Comment by daftspunk** [comment]
Hi @lubinMathew1991,

Your installation appears to be missing some files. Some things to try:

1. Rename vendor directory to vendor2, then run `composer update`
2. Restart the web server

I hope this helps.

**Comment by lubinMathew1991** [comment]
@daftspunk 

tried but not working

Also not able to clear cache while running php artisan cache:clear it shows class str not found, please help me
