### ISSUE TITLE
Call to undefined method October\Rain\Database\Relations\AttachMany::getRelatedKeyName()

### ISSUE THREAD

**Issue by wpluut** [octobercms/october#5790]
I have a model with an attachMany relation:

`public $attachMany = [
    'attachments' => File::class
];`

 When adding an attachment and saving the model, I'm getting this error:
 
 `Call to undefined method October\Rain\Database\Relations\AttachMany::getRelatedKeyName()`
 
 The method `getRelatedKeyName` seems missing.
  
 I am running OctoberCMS  v3.6.7

**Comment by daftspunk** [comment]
Thanks for finding this!
