### ISSUE TITLE
How i can get EntryRecord october://<TYPE>@link/<REFERENCE>?<PARAM>=<VALUE> 

### ISSUE THREAD

**Issue by uitlaber** [octobercms/october#5794]
How i can get EntryRecord october://<TYPE>@link/<REFERENCE>?<PARAM>=<VALUE>

**Comment by daftspunk** [comment]
This should help: https://docs.octobercms.com/3.x/markup/filter/link.html#php-interface

**Comment by uitlaber** [comment]
i need generate 
`ctober://<TYPE>@link/<REFERENCE>?<PARAM>=<VALUE> `  like pagefinder result value

**Comment by daftspunk** [comment]
Here you go: https://octobercms.com/docs/api/cms/models/pagelookupitem

Some examples:

```php
\Cms\Models\PageLookupItem::encodeSchema($type, $reference, $params = [])

\Cms\Models\PageLookupItem::encodeSchema('cms-page', 'about/home/index', ['target' => '_blank'])
```
