### ISSUE TITLE
"Method October\Rain\Database\Collection::hasRelation does not exist." on line 113 of 

### ISSUE THREAD

**Issue by xyz1123581321** [octobercms/october#5797]
When trying to created nested relation using relation form widget I get this error, before the last update the model_id was not set, was always null, now I'm getting this error

"Method October\Rain\Database\Collection::hasRelation does not exist." on line 113 of trait Macroable.php

**Comment by daftspunk** [comment]
Hi @xyz1123581321 

Can you paste the full stack trace?

**Comment by daftspunk** [comment]
Take a look at this file `modules\backend\behaviors\relationcontroller\HasNestedRelations.php` and the `makeNestedRelationModel` method. It looks like the error comes from here, and it is returning a multiple relation (collection) instead of a singular one.

If we can figure out how you arrived here, we can include some exception handling here. Alternatively, the [test plugin](https://github.com/octobercms/test-plugin) has a working example.

**Comment by xyz1123581321** [comment]
BadMethodCallException: Method October\Rain\Database\Collection::hasRelation does not exist. in /xyz/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113
#0
/xyz/modules/backend/behaviors/RelationController.php(391):
Illuminate\Support\Collection->__call('hasRelation', Array)
#1
/xyz/modules/backend/behaviors/RelationController.php(336):
Backend\Behaviors\RelationController->initRelationInternal(Object(CompanyName\MyPlugin\Models\Customer), 'quotes[plans]')
#2
[internal function]:
Backend\Behaviors\RelationController->initRelation(Object(CompanyName\MyPlugin\Models\Customer))
#3
/xyz/vendor/october/rain/src/Extension/ExtendableTrait.php(504):
call_user_func_array(Array, Array)
#4
/xyz/vendor/october/rain/src/Extension/Extendable.php(55):
October\Rain\Extension\Extendable->extendableCall('initRelation', Array)
#5
/xyz/modules/backend/behaviors/FormController.php(188):
October\Rain\Extension\Extendable->__call('initRelation', Array)
#6
/xyz/modules/backend/behaviors/FormController.php(344):
Backend\Behaviors\FormController->initForm(Object(CompanyName\MyPlugin\Models\Customer))
#7
[internal function]:
Backend\Behaviors\FormController->update('01hgt5q27jd4gz5...', NULL)
#8
/xyz/vendor/october/rain/src/Extension/ExtendableTrait.php(504):
call_user_func_array(Array, Array)
#9
/xyz/vendor/october/rain/src/Extension/Extendable.php(55):
October\Rain\Extension\Extendable->extendableCall('update', Array)
#10
/xyz/modules/system/traits/DependencyMaker.php(29):
October\Rain\Extension\Extendable->__call('update', Array)
#11
/xyz/modules/backend/classes/Controller.php(392):
Backend\Classes\Controller->makeCallMethod(Object(CompanyName\MyPlugin\Controllers\Customers), 'update', Array)
#12
/xyz/modules/backend/classes/Controller.php(365):
Backend\Classes\Controller->execPageAction('update', Array)
#13
/xyz/modules/backend/classes/Controller.php(454):
Backend\Classes\Controller->pageAction()
#14
/xyz/modules/backend/classes/Controller.php(265):
Backend\Classes\Controller->execAjaxHandlers()
#15
/xyz/modules/backend/classes/BackendController.php(137):
Backend\Classes\Controller->run('update', Array)
#16
/xyz/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54):
Backend\Classes\BackendController->run('CompanyName/MyPlugin/...')
#17
/xyz/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43):
Illuminate\Routing\Controller->callAction('run', Array)
#18
/xyz/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259):
Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Backend\Classes\BackendController), 'run')
#19
/xyz/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205):
Illuminate\Routing\Route->runController()
#20
/xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798):
Illuminate\Routing\Route->run()
#21
/xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141):
Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22
/xyz/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23
/xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180):
Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#24
/xyz/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25
/xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180):
Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#26
/xyz/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27
/xyz/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64):
Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#28
/xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180):
Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#29
/xyz/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30
/xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180):
Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#31
/xyz/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32
/xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180):
Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#33
/xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34
/xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797):
Illuminate\Pipeline\Pipeline->then(Object(Closure))
#35
/xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776):
Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#36
/xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740):
Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#37
/xyz/vendor/october/rain/src/Router/CoreRouter.php(32):
Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#38
/xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190):
October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#39
/xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141):
Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#40
/xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41
/xyz/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23):
Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#42
/xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180):
October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#43
/xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44
/xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165):
Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45
/xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134):
Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#46
/xyz/index.php(42):
Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#47
{main}
