### ISSUE TITLE
Video from media not showing

### ISSUE THREAD

**Issue by ssi-com-pl** [octobercms/october#5798]
Hi! I added a video from the Media Library, but it is not showing on the frontend.

![image](https://github.com/octobercms/october/assets/57666038/b8c24f64-5022-4dbd-9871-228b30f215f6)

In the page code I only see this:
`<figure class="" data-label="mywideo.mp4" data-video=".../mywideo.mp4">&nbsp;</figure>`

**Comment by daftspunk** [comment]
This will be fixed in v3.6.19

Thanks @ssi-com-pl !
