### ISSUE TITLE
Command "october:install" is not defined

### ISSUE THREAD

**Issue by bastian-schur** [octobercms/october#5803]
Hi,

i've a problem with my october installation. After moving the whole directory to my stage server i can't run the install-command again:

`ERROR  Command "october:install" is not defined. Did you mean one of these?  

  ⇂ migrate:install  
  ⇂ october:about  
  ⇂ october:down  
  ⇂ october:fresh  
  ⇂ october:migrate  
  ⇂ october:mirror  
  ⇂ october:optimize  
  ⇂ october:passwd  
  ⇂ october:up  
  ⇂ october:update  
  ⇂ october:util  
  ⇂ plugin:install  
  ⇂ theme:install  
`
Does the installer remove the command after the first run?

Can't find anything on google about this.

**october:about**
`  Environment ......................................................................................................................................  
  Application Name ..................................................................................................................... October CMS  
  Laravel Version .......................................................................................................................... 9.52.16  
  PHP Version ............................................................................................................................... 8.2.20  
  Composer Version ............................................................................................................................... -  
  Environment ................................................................................................................................ local  
  Debug Mode ................................................................................................................................... OFF  
  URL .................................................................................................................................... localhost  
  Maintenance Mode ............................................................................................................................. OFF  

  Cache ............................................................................................................................................  
  Config ................................................................................................................................ NOT CACHED  
  Events ................................................................................................................................ NOT CACHED  
  Routes ................................................................................................................................ NOT CACHED  
  Views ................................................................................................................................. NOT CACHED  

  Drivers ..........................................................................................................................................  
  Broadcasting .............................................................................................................................. pusher  
  Cache ....................................................................................................................................... file  
  Database ................................................................................................................................... mysql  
  Logs ............................................................................................................................... stack / daily  
  Mail ........................................................................................................................................ smtp  
  Queue ....................................................................................................................................... sync  
  Session ..................................................................................................................................... file  

  October CMS ......................................................................................................................................  
  October CMS Version ....................................................................................................................... 3.6.24  
  Plugin Updates Count ........................................................................................................................... 0`

**Comment by daftspunk** [comment]
Hi @bastian-schur 

The install command only works for new installations. When migrating to a new server, open the `.env` file and modify the configuration there.

> Does the installer remove the command after the first run?

Yes, but we are in the process of including it in the main project in a later version.

I hope this helps.
