### ISSUE TITLE
RichEditor is stripping all formatting and tags

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#5807]
Hi,
Not sure with which version it started, but the Rich Text Editor is stripping all formatting, images and tags, in the page plugin, in the campaign plugin, in my plugins as well. 
Actually tested on the latest OC v3.6.26.
Issues appears on my client server and on my local dev server as well.
no log error.
very weird. 
is there a new security settings introduced maybe recently for this behavior ?

**Comment by daftspunk** [comment]
Hey @chrisvidal 

There haven't been any recent changes that would cause this. However, take a look at the **Settings → Editor Settings → Markup Tags** area. If these text fields are blank, it could cause this behaviour. Resetting to default should restore the default settings.

I hope this helps.

**Comment by chrisvidal** [comment]
thanks @daftspunk it looks ok on that editor settings side

<img width="777" alt="image" src="https://github.com/user-attachments/assets/8c74bf4e-8d92-479b-a313-8e935dbea370">

**Comment by chrisvidal** [comment]
I found my issue...I had to develop a XSS middleware that prevent any html tag in the user inputs on the website side.
Unfortunately, it applies as well to the backend.

What would be the best way to handle that ?

```php
if(\App::runningInBackend()) {}
```

would this be enough?

**Comment by daftspunk** [comment]
Yes, that would work, that context check should be reliable in middleware.
