### ISSUE TITLE
Resize Pipe Sometimes Creates Redirect Urls

### ISSUE THREAD

**Issue by sqwk** [octobercms/october#5809]
I have multiple instances of a resize pipe on a page, usually something likes this: `{{ article.photo|media|resize(1200, 630, { mode: 'auto',  quality: '40', compress: true}) }}`

Usually the resulting url looks something like this: `https://domain.com/storage/app/resources/resize/1328_0_0_0_auto/img_897e46091e294c82030581c8e124e0ac.jpg`

However, sometimes it looks like this :`https://domain.com/resize/8d02b322c7df48400b9bf3c04aefc015-1`

The latter produces two requests instead of one and creates unnecessary 302 redirects.

The only difference that I can find is that the redirected resizes are nested in a `{% put foo %} ... {% endput %}`. Could this cause the redirect wrapped resize urls?

**Comment by daftspunk** [comment]
Hi @sqwk 

The redirect happens when the resized object doesn't exist yet. It is a slower request and results in a redirect. Subsequent requests will directly reference the object and are fast.

> Could this cause the redirect wrapped resize URLs?

It shouldn't make any difference, in theory.

I hope this helps.

**Comment by sqwk** [comment]
ok, so it turns out that the distinguishing mark wasn't the `put`, but that the image was mentioned as part of a `og:image`, which browsers don't request. The redirect url stays around until someone does request it (usually a Google bot), at which point it will update to the resized image.

**Comment by daftspunk** [comment]
Oh, that is interesting indeed!
