### ISSUE TITLE
Timezone bug whenever datepicker mode is set to date during time rollovers

### ISSUE THREAD

**Issue by blakej115** [octobercms/october#5815]
Note that I experienced this bug when using Tailor and am unsure if it effects non-Tailor fields or not.

1. Create a `datepicker` field through Tailor with the mode set to `date`.
2. Create an entry during a time whenever a timezone conversion would cause the date to roll over once converted. For example, the system uses `UTC`, but my timezone prefrence is set to `America/New_York` (-04:00). If I go and save an entry anytime between 8:00 PM EST and 12:00 AM EST, the date displayed on the edit screen will be incorrect.

When checking the database, you can see that even though the `mode` is set to `date`, there is still a time stored, and the time stored is whatever time you save the record at converted to UTC. In the list view, you'll see the date converted to your time zone preference, but in the edit view, the time zone is not converted. Whenever you are saving the record, the current time is being converted to UTC for the database, but is not converted back to your time zone preference on the edit screen as it should be. This is problematic during times when the current time converted back to UTC will cause the date to rollover, such as between 8:00 PM and 12:00 AM EST when using `America/New_York` (-04:00) as your timezone preference.

Please let me know if I need to clarify further. I am aware that this is confusing.

**Comment by daftspunk** [comment]
Hey @blakej115 

You've found a bug! We will fix it in the next patch (v3.6.30). In the meantime, you can use the following `column` definition as a workaround:

```yaml
my_date:
    label: My Date
    type: datepicker
    mode: date
    column:
        useTimezone: false
```

In the patched version the above column configuration will be the default. 

Timezones are complicated, for sure! That's why they are not applied to "time" or "date" by default, only when date and time are used together.

I hope this helps!
