### ISSUE TITLE
Error when install ocotber withowt theme

### ISSUE THREAD

**Issue by zimbar** [octobercms/october#5825]
Hy,

I installed October with composer but I did not install the default theme, when I access the admin I have this error "Call to a member function getDirname() on null" 

![Capture d’écran du 2024-10-24 15-01-12](https://github.com/user-attachments/assets/9245b7da-a216-40af-bc86-816a89a03b7a)

Thanks

**Comment by daftspunk** [comment]
Thanks for reporting this, @zimbar 

A patch has been included for this in v3.7.4

Best regards
