### ISSUE TITLE
Unaligned legacy modal titles

### ISSUE THREAD

**Issue by Eoler** [octobercms/october#5830]
OctoberCMS v3.7.6, PHP v8.3.15, Laravel v10.48.25

Document [Upgrading Backend Panel to Bootstrap 5](https://octobercms.com/support/article/rn-31) suggests alternatively updating modals with `flex-row-reverse` class for backward-compatibiliy with older OC versions. Latest included Bootstrap removed CSS property value `justify-content: space-between` that make this work.

### Workaround 
Customize backend stylesheet with
```
.modal-header.flex-row-reverse {
    justify-content: space-between;
}
```

**Comment by daftspunk** [comment]
Thanks @Eoler !

Added this fix in v3.7.7
