### ISSUE TITLE
No URLs working except home page after install

### ISSUE THREAD

**Issue by jekinney** [octobercms/october#59]
I posted on the forums also.

After various install methods (composer, github and auto install) I get a home page in html with no CSS. No other URLs work (localhost/backend). No login etc can be found.

I am using Wamp on W8. No install errors etc and migrates the databse fine.

**Comment by dennyhalim** [comment]
must do:
  sudo a2enmod rewrite
  sudo service apache2 restart
so that mod rewrite works

imho, these should be mention somewhere in installation doc and the install success message.

**Comment by henrytubritt** [comment]
For me it required making sure that I had AllowOverride all in the <Directory /var/www> directive in /etc/apache2/apache2.conf. It was set to None by default. Then restarted the service /etc/init.d/apache2 restart

**Comment by Ayeshh** [comment]
@dennyhalim

 Worked after moving to php7, hadnt realised rewrite was disabled.
