### ISSUE TITLE
Call to undefined method Event::listen()

### ISSUE THREAD

**Issue by hollycoder** [octobercms/october#603]
This shows when I use the installer in the last step.
And also when I use october:up command when following CLI install.

~~~
        App::singleton('user.auth', function() {
            return \RainLab\User\Classes\AuthManager::instance();
        });
 
        /*
         * Apply user-based mail blocking 
         */
=>        Event::listen('mailer.beforeSend', function($mailer, $view, $message){
            return MailBlocker::filterMessage($view, $message);
        });
~~~

**Comment by daftspunk** [comment]
It would appear this is a very rare example, I was unable to find anything on it relating to Laravel and their advice.

**Comment by lostsnow** [comment]
https://github.com/octobercms/october/blob/master/modules/system/aliases.php#L17

it seems this class alias cause this problem
