### ISSUE TITLE
Cannot post to root when root is subdirectory

### ISSUE THREAD

**Issue by RoySchoep** [octobercms/october#634]
It is not possible to send  a POST request to the root of your application if your application is in a subdirectory (`localhost/app/` for example) with a form generated by `form_open`.

The form action is `/localhost/app` which redirects to `/localhost/app/` so the POST variables are lost...

I solved this temporarily to manually set the url for the form with a trailing slash, but this shouldn't be the way I guess...

This is the code I have used in my page
`
function onStart(){
    $this['url'] = Request::url() ."/";
}`

In my HTML/TWIG

`
{{ form_open({ 'files': 'true', 'url': url}) }}
{{ form_close}}
`

**Comment by sulazix** [comment]
I can confirm this issue, can be problematic with fileupload which won't work with {{form_ajax()}} #1112

**Comment by daftspunk** [comment]
This is actually caused by your webserver adding the trailing slash because the public path is treated as a directory. This only occurs when the website exists in a subdirectory.

The solution used by @RoySchoep is the best workaround.
