### ISSUE TITLE
Implement hotkeys in MD editor for tools

### ISSUE THREAD

**Issue by that0n3guy** [octobercms/october#635]
I love ghost's (blog engine) simple ability to upload images.  October would do well to implement something like it.

Check out this simple video to see how it works:
http://screencast.com/t/sAsol3Z5L

Basically I hit ctrl+shift-i (it inserts `![](http://)`) and it shows an something in the preview to upload something.

**Comment by nsrosenqvist** [comment]
Is there any progress on this issue? It's really hard to build a client friendly website if the user can't easily upload and attach images to blog posts

**Comment by daftspunk** [comment]
The markdown editor now has a toolbar so the hotkeys are not really necessary anymore.
