### ISSUE TITLE
Weird fillable behavior

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#640]
I have a demonstration repo located [here](https://github.com/Flynsarmy/oc-badfillable-plugin) that shows some strange behavior will fillable. Looks like a bug but hard to tell.

**Comment by daftspunk** [comment]
When fillable is empty, guarded is taking effect. When you enter something in to fillable, it overrides guarded as *. If everything is guarded, the model takes on a heavily restricted behavior. This is by design of Laravel, not related to October specifically.
