### ISSUE TITLE
onText, offText options for switch field

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#672]
People often want custom text in their boolean fields. Someone tonight asked for Active/Inactive. The answer is always to make a partial field but that seems to overkill for something that really should be very simple.

Could onText and offText options be made available for the switch field type? It would save a lot of time and effort.

**Comment by SebastiaanKloos** [comment]
It would be really nice to have this option!

**Comment by daftspunk** [comment]
As above, using the `type: partial` in the list column will work just fine

```
<?= $record ? 'Yes' : 'No' ?>
```

Or you can define your own custom column types:

https://octobercms.com/docs/backend/lists#custom-column-types

**Comment by daftspunk** [comment]
Refer to #2487 for referencing a form field over a list column.
