### ISSUE TITLE
Ability to remove plugins from Projects

### ISSUE THREAD

**Issue by JohannesMP** [octobercms/october#68]
While plugins can be installed to a project via the plugins page: http://octobercms.com/plugins/ there seems to be no way to remove the plugin once installed.

When viewing a given project, you can see a tag-style list of installed plugins:
![screenshot_2014-05-15_10 22 32](https://cloud.githubusercontent.com/assets/662874/2981229/fa610fb8-dc01-11e3-8075-dce307ec6dd6.png)
However clicking on them takes you to the plugin's page with no way of removing it from the project you just came from; clicking 'add to project' and selecting the project only brings up a dialogue box that says 'You have already added this product to the project.'

Ideally when viewing a project I would like to have a dedicated 'Plugins' or 'Installed Products' section that lists them in a sorted table, not just a list, and provides some management features such as removing them.

---

This would be less crucial if there was a way of removing/disabling a plugin from the System/Updates section when administrating the projects backend, but that currently doesn't exist either, and has already been suggested in #53. Even if #53 is implemented, I feel a proper plugin management section would be good to have on http://octobercms.com/account/projects

**Comment by daftspunk** [comment]
This has been implemented.
