### ISSUE TITLE
Very high CPU load

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#683]
I created a new installation of October (with the GUI) that included RainLab.User (not that this really matters). I went to Backend - CMS and just loaded the page. The Chrome task manager showed the page using 19% cpu for a very long time after the page had finished loading.

I feel this happens on every october backend page, not just CMS, though I tested above with CMS. The amount of CPU required for October's backend causes my laptops fan to fire up no matter what I'm doing and generates a lot of heat. It makes October very uncomfortable to work with.

**Comment by Flynsarmy** [comment]
Seems all good now.

**Comment by daftspunk** [comment]
Might've been something to do with the recent minifcation of backend JS assets.
