### ISSUE TITLE
can't install plugin from backend

### ISSUE THREAD

**Issue by Dmi3yy** [octobercms/october#69]
![manage updates october cms 2014-05-15 10-32-33 2014-05-15 10-32-38](https://cloud.githubusercontent.com/assets/669491/2981277/23d954da-dc03-11e3-940e-4f8acd08d805.jpg)

PHP Version 5.5.7
OctoberCMS build 67

**Comment by Simplesmente** [comment]
Hey, I have been the some problem always that i try to run the installer Octobercms. I searched everywhere but i don't found a solution, I already spoke with a buddy and he never saw something like it, I don't understand. Do you can help me ?

**Comment by fredec** [comment]
The solution is here: https://github.com/octobercms/october/issues/3490
