### ISSUE TITLE
CSRF vulnerability

### ISSUE THREAD

**Issue by sercanvirlan** [octobercms/october#696]
I think there is no csrf check for ajax. I have removed the token value from frontside, the server accepted my request.

This is very important thing. Am i right?

**Comment by daftspunk** [comment]
More on this can be found here: 

https://github.com/octobercms/library/issues/105

**Comment by oliverpool** [comment]
> More on this can be found here:
> https://github.com/octobercms/library/issues/105

@daftspunk : the issues are now closed on https://github.com/octobercms/library, which means that the link you provided returns an error 404 (maybe only for non-contributors)

Could you maybe copy/paste the relevant informations from this issue ?

**Comment by daftspunk** [comment]
Comment updated
