### ISSUE TITLE
Install plugins and themes from the backend

### ISSUE THREAD

**Issue by JohannesMP** [octobercms/october#70]
As is described in its help text, the current plugin search functionality on the `system/updates` backend page seems to only work when you "`Name the plugin by its unique code. For example, RainLab.Blog`".

This is really not that useful, since you need to know the exact code of a plugin to be able to install it. For example if I'm looking for the google analytics plugin, even typing 'analytics' will not work. 

This is especially the case because there is actually no intuitive way of viewing said unique code when browsing a plugin on http://octobercms.com/plugins. For example nowhere on the page of the google analytics plugin - http://octobercms.com/plugin/rainlab-googleanalytics - does it say that its unique code is `RainLab.GoogleAnalytics`. the only way you can infer that is by looking at its URL, which is very clunky.

I think it would make a lot more sense if instead the UI on `system/updates` mirrored the functionality of http://octobercms.com/plugins/, with more forgiving search and browsing functionality, and access to the categories and so on.

**Comment by daftspunk** [comment]
A cut down version of this proposal has been implemented. Plugins and Themes can now be installed by searching for any text, not just the code.
