### ISSUE TITLE
Png transparancey using getThumb() using crop mode

### ISSUE THREAD

**Issue by mradamwood** [octobercms/october#707]
Uploading a transparent png works fine but when using crop mode with getThumb() transparency is replaced with black.

E.g:

<code>
$product->image->getThumb(210,210,['mode' => 'crop','quality'=>'100','extension'=>'png']);
</code>

Also note that the extenstion has to be explicitly set even though the docs say it defaults to png - it seems to default to jpg

<blockquote>
<b>extension</b>	jpg, png, gif. Default: png
</blockquote>
https://github.com/octobercms/docs/blob/master/database-model.md#viewing-attachments

**Comment by daftspunk** [comment]
This was fixed in https://github.com/octobercms/library/commit/3bbf14808a54ff4b2967336387361666db20aba6

Docs have also been updated to reflect the new "auto" mode.
