### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by yuri25** [octobercms/october#726]
open-server win - 64

Create admin account

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'october.rainlab_blog_posts' doesn't exist (SQL: alter table `rainlab_blog_posts` add `seo_title` varchar(255) null, add `seo_description` varchar(255) null, add `seo_keywords` varchar(255) null, add `canonical_url` varchar(255) null, add `redirect_url` varchar(255) null, add `robot_index` varchar(255) null, add `robot_follow` varchar(255) null)

Something went wrong during the installation. Please see the documentation for more information.

**Comment by isbkch** [comment]
still having this, I'm not even installing the blog plugin, I'm skipping without installing any addons

**Comment by toscho** [comment]
Same problem here, right after installation, no plugins installed, same system as OP. This is not a duplicate.

**Comment by eigotec** [comment]
Same problem...and a real show stopper.

**Comment by daftspunk** [comment]
Help us help you: Please report this as a new issue with complete replication instructions.
