### ISSUE TITLE
Error: "error" on save of any CMS file containing the pattern "><" with or without whitespace in between... (so virtually all nested HTML)

### ISSUE THREAD

**Issue by kyestork** [octobercms/october#727]
I save a file. If it contains ">" + any whitespace or tabs + "<", it throws a browser alert with only one single word: "error".

This fails...
```
<div></div>
```

This fails...
```
<div>
    <p>
        hello world
    </p>
</div>
```

This works...
```
<div>
    hello
</div>
```

This works...
```
<div/div>
```

I built the majority of the install on localhost (WAMP server). Made a new theme, modified the layout and pages through the CMS, installed the following plugins:
 * Wysiwyg Editors by Anand Patel
 * Todo Plugin / Task manager by ShahiemSeymor
 * User by Alexey Bobkov, Samuel Georges
 * Frontend User Roles Manager by ShahiemSeymor
 * Parallax by Freestream
 * Blog by Alexey Bobkov, Samuel Georges
 * MenuManager by Ben Freke

I moved it to the live server (LAMP) by FTP.

I exported the database in phpMyAdmin and imported it to the server through the same, and changed the database config accordingly.

I updated it to Build 159.

I went to go edit a page and the error pops up. It's the same for any content, partial, layout, whether using WYSIWYG or not, whether any or all of the plugins are disabled or not....

I followed it a bit the best I could. It's returning "error", because that's the `jqXHR.statusText`, meaning `jqXHR.responseText` is not present (framework.js, line 124). (Don't know if that may help lol) From there, I have no clue. I looked around some CMS classes (`CMSCompoundObject`, `CMSObject`, `Page`, `CMSException`), but nothing stood out to me...

**Comment by daftspunk** [comment]
Most likely caused by hosting.
