### ISSUE TITLE
The test suite cannot be properly executed on the default install

### ISSUE THREAD

**Issue by galaxy4public** [octobercms/october#728]
The test suite included with OctoberCMS (phpunit.xml) defines three sub test suites:
1. OctoberCMS
2. OctoberCMS (the rain library)
3. Laravel

The first two are running fine by themselves (the only problem is that you can't run the OctoberCMS one if you installed your vendors/ using 'composer install --nodev').

The Laravel test suite, however, fails miserably since it requires aws/aws-sdk-php, mockery/mockery, and pda/pheanstalk to run successfully.  Lavarel's composer.json properly specifies these dependencies:
```
$ grep require-dev -A5 vendor/laravel/framework/composer.json
    "require-dev": {
        "aws/aws-sdk-php": "~2.6",
        "iron-io/iron_mq": "~1.5",
        "pda/pheanstalk": "~2.1",
        "mockery/mockery": "~0.9",
        "phpunit/phpunit": "~4.0"
```
However, composer does not pick them up when executed as 'composer install' (which includes require-dev by default).  This is obviously an issue with the composer itself.  So the intermediate workaround would be to introduce the "require-dev" section in OctoberCMS'es composer.json like the following:
```
"require-dev": {
    "aws/aws-sdk-php": "~2.6",
    "mockery/mockery": "~0.9",
    "pda/pheanstalk": "~2.1"
},
```
This way once the vendor/ directory populated one can immediately run the test suite with
```
php path_to_downloaded/phpunit.phar
```
to check that their install is sane.

**Comment by daftspunk** [comment]
This was/is a bug in composer, not pulling in child dependencies properly. If this is still an issue feel free to reopen it.
