### ISSUE TITLE
File upload error

### ISSUE THREAD

**Issue by Shahiem** [octobercms/october#741]
I'm busy with an avatar plugin but I get this error when I try to upload a new image.
 
unexpected type of array, should attribute data be jsonable.

Code part
```
	$model = User::find(3);

	$file = new System\Models\File;
	$file->data = Input::file('dsd');
	$file->save();

	$model->avatar()->add($file);
```
How can I solve this issue?  Thank you :)

Shahiem

**Comment by daftspunk** [comment]
Unable to replicate. Please reopen if it is still occuring.
