### ISSUE TITLE
Apache backend crash since build 160

### ISSUE THREAD

**Issue by ArisuOngaku** [octobercms/october#742]
I have a local problem : I'm running wamp server on windows 8 64bit for development, and since the build 160, when I try to access to the backend, I get a connection reset error in my browser and apache seems to crash.

The access log is empty and the apache error log says it has restarted...

http://puu.sh/cyFdN/ada835422b.png

I can't find what is making it crash, and I tested it on my production server and everything works fine so it's quite weird.

**Comment by maoosi** [comment]
It also crash for me when I customize my backend. Exactly the same case as @itutorage

**Comment by flip4bytes** [comment]
Same is happening for me when I customize the backend on my Heroku server. Everything works great but the second I edit the site via the backend, it crashes the site and requires a server restart to get it running again.

**Comment by Shahiem** [comment]
There is still a problem.  I can't access my backend when  I customize my backend. But it works fine when I remove this line and put it back.

    y="0px" width="100px" height="110px" viewBox="0 0 100 110" enable-background="new 0 0 100 110" xml:space="preserve">

from     
    $svgOpen  = static::cssEscape('<svg xmlns="http://www.w3.org/2000/svg" version="1.1" x="0px" y="0px" width="100px" height="110px" viewBox="0 0 100 110" enable-background="new 0 0 100 110" xml:space="preserve">');

**Comment by lukaszbanas** [comment]
in my case, disabling xdebug fixes problem
