### ISSUE TITLE
Template engine

### ISSUE THREAD

**Issue by mpaleo** [octobercms/october#744]
Hi, I'm sure it was a design decision, but there is a way to use Blade instead of Twig ? Twig seems a bit old, it is true that it is very popular, but blade is extremely easy to learn for a twig user dev, and its ok for a new user. I love the idea of a cms based on Laravel but twig is what stops me to using it

**Comment by ahangarha** [comment]
This is an old discussion. Things have changed since then. Any new thought on using Blade?
