### ISSUE TITLE
Add one-to-one support to Model

### ISSUE THREAD

**Issue by ArisuOngaku** [octobercms/october#752]
I actually need to modify both primaryKey and foreignKey for my relationaship (which is gonna be a belongsTo relationship) and October actually don't support it, while laravel allow it directly.

http://laravel.com/docs/4.2/eloquent#one-to-one

I don't think it's a bad idea and I hope you'll agree with me that it would be cool.
Also, I don't think there's lot of work to do to add this tiny feature.

**Comment by daftspunk** [comment]
This is supported

```
    /**
     * protected $hasOne = [
     *     'owner' => ['User', 'key' => 'user_id']
     * ];
     */
    public $hasOne = [];
```

Use `otherKey` for the other key.
