### ISSUE TITLE
Critical permission bug: User with dashboard-only permissions can change backend settings!

### ISSUE THREAD

**Issue by BMCouto** [octobercms/october#776]
If you give a user access to dashboard only, if he clicks on his name (top right corner) he has access to all settings... needs urgent fix, critical permissions bug.

**Comment by tresbach** [comment]
I can confirm that once a user clicks on her name on the corner, the full administration menu is displayed, although all links but _myaccount_ and _editorpreferences_ are not really accessible, they will point to an "Access Denied" page.

**Comment by Litvinenko** [comment]
I think, will be much better if the backend user without any permission or groups could not authorize by default

**Comment by daftspunk** [comment]
Permissions have been audited and this should be fixed now.

**Comment by lcdss** [comment]
Even now If an user has no permission at all he still can edit his group. Is it suppose to happen?

**Comment by LukeTowers** [comment]
@lcdss what build are you using? And could you please describe in detail what's happening? Preferably with screenshots?

**Comment by lcdss** [comment]
@LukeTowers I'm using the last version (v1.0.426). The user below have just one custom permission and can edit his own group but not the role:

![peek 2017-10-31 01-17](https://user-images.githubusercontent.com/6903590/32205990-aae044fa-bdd9-11e7-992b-a2d1d7a4072a.gif)

**Comment by daftspunk** [comment]
If this is a new issue please create a new issue.
