### ISSUE TITLE
More standard Form Widgets

### ISSUE THREAD

**Issue by romaldyminaya** [octobercms/october#790]
Hi,

I'm thinking in writhing some Form Widget like a **tagField** and a **maskedTextbox**.

After developed, is there a possibility that you include those Form Widgets to  the OctoberCms as part of itself?

> Of course after tested :)

**Comment by daftspunk** [comment]
It is best to keep these form widgets contained inside your plugins at the moment. We only want minimal features in the core to keep the platform agile.

**Comment by romaldyminaya** [comment]
@daftspunk  As you wish :)
