### ISSUE TITLE
Pagination problem

### ISSUE THREAD

**Issue by egrego-dot-re** [octobercms/october#793]
In modules/backend/widgets/lists/partials/_list_pagination.php there's line

    <?= e(trans('backend::lang.list.pagination', ['from' => $pageFrom, 'to' => $pageTo, 'total' => $recordTotal])) ?>

which corresponds to all :total keys in translations. This however triggers strange and unexpected behavior of str_replace used by Laravel's Translator class which uses this code:

    foreach ($replace as $key => $value)
    {
        $line = str_replace(':'.$key, $value, $line);
    }

in makeReplacements method. As you are using keys __:to__ and __:total__ you have __:to__ in both keys. PHP str_replace somehow replaces only one occurence of __:to__ and ignores second in __:total__ without implicit replacement count as 4th parameter (which is strange, as documentation says explicitly that it should replace all occurences up to count parameter, regardless if they are whole words or not). HHVM hasn't got that particular issue and it replaces that string correctly, meaning we get __Displayed records: 1-15 of 15tal__ for example. I propose that translation line in _list_pagination.php is changed to: 

    <?= e(trans('backend::lang.list.pagination', ['from' => $pageFrom, 'to' => $pageTo, 'all' => $recordTotal])) ?>

and all __:total__ keys in translations are changed to __:all__ to bypass this strange problem. I know that it somehow works on php, but it's more a troublemaker than it could be.

**Comment by daftspunk** [comment]
This function used should be `strtr()` instead of `str_replace()`. If this is a bug in Laravel, they should be informed. @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Could you send a PR please?
