### ISSUE TITLE
Plugin security

### ISSUE THREAD

**Issue by egrego-dot-re** [octobercms/october#794]
First thing: currently there is a mechanism, that allows for composer.json usage in plugins. October, after it has found composer.json in plugin root folder, proceeds with installation of required libraries in plugin/vendor. This operation creates a new composer scope under plugin root and that scope is then required via composer autoloader into global php scope of OctoberCMS application. As composer doesn't work like node.js npm, which hides libraries in parent library scope and prevents their leaking into global scope, this allows for same library being loaded multiple times, even in different versions, therefore redefining symbols declared before. If there are no checks on what is actually going on with composer dependencies, one can easily imagine situation, where this causes hard to understand inter-plugin bugs. With enough misfortune that can also break octobercms if overridden libraries are used by core.

Solution 1:
Analyze composer.json of plugin and add required libraries to global composer.json would let composer to handle different version matches and conflicts. October could store information about dependencies of plugins in a file allowing for easy check-up (and user notification of conflicts) of what is currently installed and removal of unused dependencies when dependent plugin is removed. That would also allow for code reuse of libraries. Composer dependencies could be also presented in plugin manifests in infrastructure, allowing to show which plugins share libraries or conflict with another before installation attempt.

Solution 2:
Allow for local composer scopes of plugins, but still track dependencies already installed with their version. October therefore would know what dependencies are available from plugin composer scopes and not allow for version conflicts.

Second thing:
Google Play market has a neat solution for security of permissions being granted to applications and shows required permissions to user during app installation. October currently relies on code review of plugins by CMS authors for security audit and user is not notified what is provided by plugin to october and what subsystems plugin tries to use. Wordpress has huge problems with plugin security and multiple backdoors can be installed via plugin. Therefore:

Solution:
Plugin installer could analyze plugin code with regex matching and find any and all implicitly requested permissions plugin tries to use, ie CURL uses (might get complicated if such operations are called via composer dependency, ie Guzzle as CURL abstraction), access to filesystem, access to core database tables, access to other plugins tables (and extend operations), javascript injections (explicit as $this->addJs() or implicit as <script> tags) and others. After analysis window presenting required permissions would be shown to user requiring his acceptance.

**Comment by daftspunk** [comment]
This is a relatively unlikely event to occur, we will address it if it becomes a problem in future. Plugins can and will clash, generally it is up to the authors to work together to resolve any issues that arise.

Tagged these notes for future reference.
