### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by mikelmi** [octobercms/october#796]
Package files from server are corrupt.
But I can download needed packages from server manualy.
Are you sure you know php? ))
Is the Installation script wrotten by schoolboys? ))

**Comment by daftspunk** [comment]
Sorry there is not enough detail provided here. Things to check:

* [Read the documentation](http://octobercms.com/docs/help/installation#wizard-installation) -- check server timeout limit?
* Look at the install.log file, what md5 results are displayed?
* Debug the code, are contents being written to files?
* Check are the developers schoolboys?
