### ISSUE TITLE
Class auth does not exist

### ISSUE THREAD

**Issue by Whyounes** [octobercms/october#799]
Inside my `NotesController@store` method i'm trying to access the logged in user, but i'm getting `Class auth does not exist`. I tried to resolve it through the from the container directly (`App::make('auth')`) but i'm getting the same error.

The only way i can do it is to instantiate the `AuthManager` directly!!

Can anyone try to reproduce this error and confirm?

Thanks

**Comment by dudheit** [comment]
Hi, I ran into the same problem when using the jwt-auth package in a plugin. 
My ``routes.php`` with DingoAPI and JWT looks like this:

    \App::register('\Dingo\Api\Provider\LaravelServiceProvider');
    \App::register('Tymon\JWTAuth\Providers\JWTAuthServiceProvider'); 
 
    $api->version('v1', function ($api) {
          $api->group( [ 'middleware' => '\Tymon\JWTAuth\Middleware\GetUserFromToken' ], function ($api) {
               $api->resource('foo', 'Bar');
     ....

Then JWTAuth raises the 'Class auth does not exist' exeption. Is there any way how I can register the Auth class of the Rainlab.User plugin, such that JWTAuth makes use of it?

**Comment by daftspunk** [comment]
The RainLab.User plugin uses this code to do it:

        $alias = AliasLoader::getInstance();
        $alias->alias('Auth', 'RainLab\User\Facades\Auth');

        App::singleton('user.auth', function() {
            return \RainLab\User\Classes\AuthManager::instance();
        });
