### ISSUE TITLE
Checkbox and external parameter in component properties

### ISSUE THREAD

**Issue by ghost** [octobercms/october#804]
## Bug summary
According to [latest blog entry](http://octobercms.com/blog/post/updates-core-components-features), right now `showExternalParameter` key is by default set to `true`. However, if in component properties you have checkbox field and you don't set `showExternalParameter` key to `false`, in backend you're are not able to properly edit component params.

## Request location
Backend - CMS

## Reproduce steps
1. add some component with checkbox field
2. edit this component using inspector and check the checkbox, then close inspector
3. try to edit again the same component

## Expected result
Component values are properly filled and ready for changes

## Actual result
No values are filled and there will be JS error about missing alias when you'll try to close inspector. Chrome inspector says that error is in line 312 in `october.inspector.js`.

In my opinion showExternalParameter key should be set to `false` for checkboxes field or at least there could be some information to 'set it off'.

**Comment by daftspunk** [comment]
Confirmed and was able to replicate this. Checkboxes appear to stop working with `showExternalParam` enabled

**Comment by alekseybobkov** [comment]
I can't replicate the problem. We have [rewrote the Inspector from scratch](http://octobercms.com/blog/post/inspector-2) some time ago, many old bugs were fixed in the process.
