### ISSUE TITLE
Component usage of attribute-modifier settings

### ISSUE THREAD

**Issue by scottbedard** [octobercms/october#806]
I'm trying to access a settings field modified by the Encryptable trait. From the back end this works perfectly, my data is encrypted on the way in, and decrypted on the way back out. But when I try to access my model from a component via Settings::get(), it's returning the raw encrypted data as it appears in the database. While trying to track down the problem, I've also noticed that components aren't making use of model accessors either.

**Comment by daftspunk** [comment]
To try: The getSettingsValue() in SettingsModel behavior method should use the model mutator workflow. Requires testing.

**Comment by daftspunk** [comment]
You'll need to use

```
Settings::instance()->encrypted_thing;
```
