### ISSUE TITLE
.AppleDouble directories showing in the backend

### ISSUE THREAD

**Issue by gpunx** [octobercms/october#814]
In the backend, while listing pages and partials, .AppleDouble files are included in the list. Also, while editing pages, .AppleDirectories appear in the layout dropdown list
![screenshot 2014-12-03 16 49 42](https://cloud.githubusercontent.com/assets/275590/5289529/8c4fe51c-7b0c-11e4-9191-e46c201cce81.png)
![screenshot 2014-12-03 16 50 10](https://cloud.githubusercontent.com/assets/275590/5289533/924af04c-7b0c-11e4-99f9-f48379de07ae.png)

**Comment by daftspunk** [comment]
Confirmed, the same is true for `.git` folders. This should be handled by checking the `October\Rain\Filesystem\Definitions::ignoreFiles` collection and ignore those folders.

**Comment by LukeTowers** [comment]
Fixed by #2858.
