### ISSUE TITLE
Backend settings form

### ISSUE THREAD

**Issue by hydreflab** [octobercms/october#816]
I have two proposals concering settings form in backend (in Settings section).

I'm trying to create a form using switch type fields and field dependencies, i.e. if one setting is 'off', some others are also 'off' and disabled. The problem I have is that switch field type does not include 'disabled' param in field configuration. I was wondering why is that exactly? Without it, I'm having big problems with introducing desired functionality. Fix is very easy and it is one line of code (which I introduced in my project).
Second thing is that I want to add some additional CSS styles for those disabled switchers. I was able to do this in my `Settings` model, using `AssetMaker` trait and binding to `backend.form.extendFields` event (there are also some others that I can bind to). Ok, it is working, but I think this is not the best/elegant way to 'plug in' additional CSS. Maybe some event firing can be added to `Form` widget in `loadAssets` method? Or maybe somewhere in the trait (however, this may not be a good idea). What do you think? Or maybe I can 'plug in' somewhere else?

I have to add, that I don't want to create separate widget nor controller, etc.

**Comment by daftspunk** [comment]
Sure, submit a Pull Request for the first thing.

For the second, this will allow you to inject a custom stylesheet to every backend page:

```
Backend\Classes\Controller::extend(function($controller) { 
    $controller->addCss('/path/to/my/custom/file.css');
});
```
