### ISSUE TITLE
Disable CURLOPT_FOLLOWLOCATION

### ISSUE THREAD

**Issue by Jadaw1n** [octobercms/october#817]
Hello

I'm in a shared hosting environment where open_basedir is set. I then get the following error on registering my project with the website. 
```Warning: curl_setopt() [function.curl-setopt]: CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set```
Do you really need this setting? I disabled it in /vendor/october/rain/src/Network/Http.php and the project registration ran just fine.

**Comment by daftspunk** [comment]
[A workaround](https://github.com/octobercms/library/pull/67) has been implemented
