### ISSUE TITLE
Call to undefined method October\Rain\Database\DataFeed::limit()

### ISSUE THREAD

**Issue by karnold** [octobercms/october#818]
Going directly off of the documentation located at https://octobercms.com/docs/database/collection I get the error message "Call to undefined method October\Rain\Database\DataFeed::limit()" when trying to get results from a DataFeed collection.

here is my sample code

```
        $feed = new DataFeed;
        $feed->add('activity', $user->activities);
        $feed->add('badge', $user->badges);
        $feed->add('reward', $user->rewards);
    
        \Debugbar::info($feed);
        $this->page['results'] = $feed->limit(10)->get();
```

When dumping the feed instance I am seeing that it has the expected models in the collection items.

**Comment by keiosweb** [comment]
PR was merged, no love for this?
