### ISSUE TITLE
Inconsistency in Cms\Classes\Controller::renderPartial();

### ISSUE THREAD

**Issue by karnold** [octobercms/october#839]
In implementing a custom component I have come across some inconsistencies in how the renderPartial method works.

For example I have a folder for shared partials in MyPlugin\components\partials.  Which contains a partial called modalDisplay.htm.

Now I implement a custom component in MyPlugin\components\UserLogin.  In that class I have the following code which works just fine and the content is rendered with the shared partial @modalDisplay:

```
    public function onLogin()
    {

        return $this->renderPartial('@modalDisplay', [
            'title'     => 'Login',
            'content'   => 'This is some content',
        ]);
    }
```

However if I nest a partial in this like so where 'login-form' exists in MyPlugin\components\userlogin\login-form.htm:

```
    public function onLogin()
    {

        return $this->renderPartial('@modalDisplay', [
            'title'     => 'Login',
            'content'   => $this->renderPartial('login-form'),
        ]);
    }
```

I receive the following error message:

*The partial 'login-form' is not found.*

So I tried implicitly calling the partial with the controller alias referenced like so:

```
    public function onLogin()
    {

        return $this->renderPartial('@modalDisplay', [
            'title'     => 'Login',
            'content'   => $this->renderPartial('UserLogin::login-form'),
        ]);
    }
```

and that fails with the error

*The partial '::modalDisplay' is not found.*

So it seems that whenever you are rendering more then one partial in a single method and one of those is not in the controller that the references get b0rked up.

For the moment I have found a work around by using \System\Traits\ViewMaker; and implementing the following in my component, but this seems like a redundant work around.

```
    public function onLogin()
    {

        return $this->renderPartial('@modalDisplay', [
            'title'     => 'Login',
            'content'   => $this->makePartial('login-form'),
        ]);
    }

    public function makePartial($partial, $params = [], $throwException = true)
    {   
        $partialsDir = self::getThemePartialsDir();
        $partialPath = $partialsDir . $partial . '.htm';

        if (!File::isFile($partialPath)) {
            $partialPath = $this->getViewPath($partial) . '.htm';
        }

        if (!File::isFile($partialPath)) {
            if ($throwException)
                throw new SystemException(Lang::get('backend::lang.partial.not_found', ['name' => $partialPath]));
            else
                return false;
        }   

        return $this->makeFileContents($partialPath, $params);
    }   

    /**
     * Get the path to the theme's partials
     *
     * @return string $path
     */ 
    protected static function getThemePartialsDir()
    {
        $theme = Theme::getActiveTheme();
        return $theme->getPath() . '/partials/';
    }

**Comment by daslicht** [comment]
So any solution for this ?

I also get partial not found : 
https://github.com/daslicht/octobercms-bootstrap4/blob/master/plugins/daslicht/contact/components/Contact.php#L66

**Comment by joseph-d** [comment]
I'm also experiencing this issue. 

The docs at https://octobercms.com/docs/plugin/components#render-partial-method say that this should be possible:

```
function onFilterResumes()
{
    return ['#someDiv' => $this->renderPartial('my-partial.htm')];
}
```

But October only reads it from the theme partials directory. It won't read it from the component partial.

I posted a more detailed description at http://stackoverflow.com/questions/42326511/rendering-a-component-partial-from-code-in-octobercms

**Comment by LukeTowers** [comment]
@joseph-d The answer on your StackOverflow question should be correct, place the context indicator `@` symbol in front of your partial name to indicate to load it from your component but let the theme override it. https://octobercms.com/docs/plugin/components#component-partials

**Comment by joseph-d** [comment]
@LukeTowers Yes, thank you, the answer on SO does solve the issue. The link you provided to the docs also answers my question. 

Should I do a pull request in the docs to add the info about the @ sign to the information at https://octobercms.com/docs/plugin/components#render-partial-method (ie: change `return ['#someDiv' => $this->renderPartial('component-partial.htm')];` to `return ['#someDiv' => $this->renderPartial('@component-partial.htm')];` or did I misinterpret the purpose of the instructions in this part of the docs?

**Comment by uitlaber** [comment]
how to disable cache when ajax request $this->renderPartial('@like' )  ?

**Comment by sushmak2216** [comment]
How to add the partial(SiteHeader) into custom plugin views?

**Comment by LukeTowers** [comment]
@sushmak2216 Github issues really isn't the place for questions like that. Please use one of the many other avenues available instead of hijacking existing issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
