### ISSUE TITLE
Using the Ajax framework in javascript.

### ISSUE THREAD

**Issue by karnold** [octobercms/october#841]
I have a question about working with the AJAX framework in javascript.

So I have a simple modal dialog. It is reusing all of the javascript that is implemented on the back end to initiate the models.  And then a simple link to open the modal as such:

```
<a href="#" class="button alternate login pop" data-control="popup" data-handler="onLogin">Log in</a>
```

Along with this i need to execute some javascript code once the modal opens.  I have tried to implement the following

```
(function($) {
    $(document).ready(function(){
        $('a.login').request('onLogin', {
            complete: function(data) {
                console.log('it worked');
            }
        });
    });
})(window.jQuery);
```

And what happens is that request.onLogin.complete is getting called when the page loads and not when the link is clicked and the modal opens.  Any advice would be greatly appreciated.

**Comment by daftspunk** [comment]
The first DIV inside the popup has the popup control added to it, eg:

```
<div id="checkUpdatesPopup">
    ...This is the modal content...
</div>

<script>
    $('#checkUpdatesPopup').on('popupComplete', function(){
        console.log('it worked');
    })
</script>
```
