### ISSUE TITLE
When using ckeditor, uploaded files throw 404

### ISSUE THREAD

**Issue by serialscoper101** [octobercms/october#842]
Using the ckeditor's file manager, i am trying to upload an image into a folder.  The resulting url is http://www.example.com/uploads/public/folder/file.png.  This does not work as october or the server does not recognise the routing and throws up a 404 when visiting that url.  Any way to fix this? Maybe allow route exceptions in the backend? I don't know how to fix this for now.

**Comment by daftspunk** [comment]
This should be taken up with the plugin author.
