### ISSUE TITLE
Untranslated strings found in a theme customization page

### ISSUE THREAD

**Issue by jtherczeg** [octobercms/october#844]
1. Add one or more form keys in a theme information file. The Customize button will appear for the correspondig theme in Backend > Settings > Front-end Theme page.
2. Click this Customize button. A new page will be loaded with the form items you defined in the theme.yaml file.
3. "Themes", the first item of the breadcrumbs, remains English.
4. "Save", "Save and Close", "or" and "Cancel" also remain untranslated.

These strings should be translatable.

The related file is /modules/cms/controllers/themes/update.htm

**Comment by daftspunk** [comment]
Yes, please do it.
