### ISSUE TITLE
Link assets onRender plugin + Twig plugin filter

### ISSUE THREAD

**Issue by Whyounes** [octobercms/october#854]
I think i should be able to do:

```
public function onRender(){
        $this->controller->addJs('validate.min.js');
}
```
and it should output a link to my plugin assets folder, not a theme asset! Also we must have a `plugin` filter to use inside the partials

```
<script src="{{ [ 'validate.min.js' ]|plugin }}"></script>
```

But the way your creating the `theme` filter does not make extensible. What doe the `Cms\Classes\Controller` has to do with creating twig filters!

**Comment by daftspunk** [comment]
```
    public function onRun()
    {
        $this->addCss('assets/css/uploader.css');
        $this->addJs('assets/js/uploader.js');
    }
```

and

```
{{ __SELF__.getAssetPath('assets/js/uploader.js') }}
```

If we made it a filter, it would have to look like this I suppose:

```
{{ 'assets/js/uploader.js' |plugin(__SELF__) }}
```
