### ISSUE TITLE
Frontend controllers

### ISSUE THREAD

**Issue by Whyounes** [octobercms/october#855]
How can i create a controller for a frontend action? i can't find something on the soc!

**Comment by gergo85** [comment]
Do you mean that you want to create the registration and the sign in, etc.?

**Comment by Whyounes** [comment]
yes, something like that

**Comment by daftspunk** [comment]
Components are a form of front-end controller. You can use a traditional Laravel route and controller if you really want.

**Comment by Whyounes** [comment]
I don't mean using the AJAX Framework, i want to submit a form directly to a defined route in my plugin.
I also want to have an file input to submit to the backend, is that supported by the AJAX Framework?

**Comment by Flynsarmy** [comment]
Plugins support a routes.php file - see [the documentation](http://octobercms.com/docs/plugin/registration#routing-initialization). As for submitting files via AJAX, I'm not sure. Please close this issue and move your question to the forum.

**Comment by chrisvanderpoel** [comment]
@daftspunk could you elaborate on the use of custom front end controllers a bit.  I'm having a little bit of difficulty wrapping my head around this.

You had mentioned using a traditional Laravel route and controller; can you provide a quick example and maybe show where we should store (and reference) our view files?  It would be really helpful as we're having difficulty getting that to work at all.

**Comment by daftspunk** [comment]
Have a look at [the documentation](http://octobercms.com/docs/plugin/registration#routing-initialization) for information on how to define Laravel routes in your plugin's routes.php file. The [translation plugin](https://github.com/rainlab/translate-plugin/blob/master/routes.php) makes use of this feature.

**Comment by chrisvanderpoel** [comment]
@daftspunk Thanks for following up!  Yeah, we've actually gotten a little past that and had created a plugin and leveraged the `routes.php` file within it.  What has us a bit confused is what core controller we should leverage so that we can render views properly.

So, for example, we have our custom route like this:

```php
Route::get('/custom', 'Vendor\Namespace\Controllers\Custom@index');
```

Which would point to this controller:

```php
<?php namespace Vendor\Namespace\Controllers;

use Illuminate\Routing\Controller;

class Custom extends Controller
{
    public function index()
    {
        return view('some.view');
    }
}
```

So, this doesn't work, no matter where we try and place our views.  Any suggestions?

**Comment by daftspunk** [comment]
I have prepared [a sample plugin](https://github.com/daftspunk/oc-laravelapi-plugin) that shows how this works.

**Comment by chrisvanderpoel** [comment]
@daftspunk Ah-ha!  This clears things up a lot!  Thank you for providing such a detailed example!

**Comment by daftspunk** [comment]
No problemo
