### ISSUE TITLE
Why using Twig instead of Blade?

### ISSUE THREAD

**Issue by Whyounes** [octobercms/october#863]
When returning from a route i'm using

```
return Redirect::back()->with(['error' => $error, 'messages' => $messages]);
```

and inside my view i'm used to Blade as the template engine, is there something in Twig that doesn't exist in Blade? can i know the reasoning behind this choice plz? Thanks

**Comment by daftspunk** [comment]
Blade is young and uncommon outside Laravel. Twig is mature and shares syntax other frameworks such as AngularJS and Django.

[It is a debate that will likely continue](https://octobercms.com/forum/post/why-twig), the solution is to take 15 minutes and learn Twig, it's not nearly as difficult as learning Blade.
