### ISSUE TITLE
app variable is null inside twig template

### ISSUE THREAD

**Issue by Whyounes** [octobercms/october#864]
I'm only trying to dump the `app` variable inside a plugin component partial, but i keep getting NULL

**Comment by daftspunk** [comment]
Please be more detailed in bug reports or consider using [Live chat (IRC)](https://octobercms.com/chat). Also have a look over the [contribution guidelines](https://github.com/octobercms/october/blob/develop/CONTRIBUTING.md) on how to use the OctoberCMS Github Issues.

Might be easier to solve this one on IRC, thanks!
