### ISSUE TITLE
Using composer dependencies in packages

### ISSUE THREAD

**Issue by muuknl** [octobercms/october#870]
I am trying to pull in a composer package for a plugin, but can't find out how to do it. How would I go about doing so?

**Comment by robin007bond** [comment]
Do you have composer installed? You can simply install a package by editing your composer.json and running:

> php composer.phar install

Or do you mean developing for October and adding a Composer dependency for a plugin? 

Usage of composer is documented at:

https://getcomposer.org/doc/01-basic-usage.md

**Comment by muuknl** [comment]
I mean adding a composer dependency for a plugin

**Comment by daftspunk** [comment]
Take a look at the demo plugin, it contains a composer.json file, this can be used to pull in packages. You need to run composer install/update separate to the main app. The OctoberCMS website will also build composer.json files for you when published as a Plugin.

**Comment by longcnn** [comment]
Note: To use composer with an October instance that has been installed using the Wizard installation, simply copy the tests/ directory, composer.json file and server.php file from GitHub into your October instance and then run composer install.
from:
https://octobercms.com/docs/console/commands

**Comment by LukeTowers** [comment]
As a side note to anyone looking at this issue, I've written an [article on using Laravel packages within October plugins](https://luketowers.ca/blog/how-to-use-laravel-packages-in-october-cms-plugins/), feel free to check it out for some handy approaches to doing that.
