### ISSUE TITLE
Reusing form widgets in components

### ISSUE THREAD

**Issue by karnold** [octobercms/october#871]
What is the best way to go about reusing some of the backend form widgets?  Specifically I am trying to implement the dropdown and datepicker widgets in a form that is contained within a custom component that I am developing.

I've dug into how the registration and login forms are implemented in the RainLab\User plugin, and it looks like the form is just manually created as html in a partial.  Which is fine for standard elements, but it would be really helpful to be able to implement custom elements as well without having to manually load the javascript and css files as well as figuring out how to properly layout the DOM.

**Comment by Whyounes** [comment]
I think that the plugin should create theme independently as form widgets,
and you can require them in your Plugin.php file.

**Comment by daftspunk** [comment]
Widgets are the backend version of Components, they are not really intended to be used on the front end.  [Here is an example of the FileUpload form widget converted to the CMS Component](https://github.com/responsiv/uploader-plugin) (note this is an experimental plugin, for learning purposes only).

It is possible for Components to act as helpers by setting 'isHidden' property to `true`, then your primary components can load them programatically using `$this->addComponent()` (see Cms\Classes\Controller)
