### ISSUE TITLE
Translation manager?

### ISSUE THREAD

**Issue by mrmlnc** [octobercms/october#880]
Maybe should start to use something like [Transifex](https://www.transifex.com/), [Pootle](http://pootle.translatehouse.org/index.html) or [Zanata](translate.zanata.org) and etc? Or own solution based on a your [plugin](http://octobercms.com/plugin/rainlab-translate)?

It became difficult to watch the translation keys, because of addition and removal of keys.

For example, in the previous version, I removed a duplicate key of 'sendmail'. Now he is back again (line [108](https://github.com/octobercms/october/blob/master/modules/system/lang/en/lang.php#L108) and [117](https://github.com/octobercms/october/blob/master/modules/system/lang/en/lang.php#L117)).

Another example, removed keys for `reset_default`, `resetting` and `resetting_name`, although they are used in the code ([commit](https://github.com/octobercms/october/commit/c43680b2ef28885a4511f8dce0fa2c3da415f9bf#diff-73ae1299d2c352fefb63eb86c178f48dL162)).

It seems to me that with further development, there can be problems with the synchronization translations.

**Comment by jtherczeg** [comment]
I am in favor of an external localization tool, because it has many advantages, like coordination, international collaboration and team work, picking up an abandoned translation.

**Comment by msimkunas** [comment]
Agreed. I would gladly translate some or all of the backend interface of October CMS to my native language if only it was more straightforward than it currently is.

Manually editing translation files is easy, however, an external localization tool has many advantages (@jtherczeg has already pointed them out).

**Comment by daftspunk** [comment]
Sounds good to me! A complimentary plugin or third party application could work well.
