### ISSUE TITLE
extendFormFields statically - not working

### ISSUE THREAD

**Issue by dimti** [octobercms/october#881]
Here is tell of extending form fields via static method:
http://octobercms.com/docs/backend/forms#extend-form-fields

But it not working.
In this code https://github.com/octobercms/october/blob/master/modules/backend/behaviors/FormController.php#L676
called function self::getCalledExtensionClass(); But is function return null.
If var $calledClass is null, then next expression is performed:
<pre><code>
 if (!is_a($widget->getController(), $calledClass)) {
return;
}
</code></pre>

In this class returned required value $extendableStaticCalledClass:
https://github.com/octobercms/library/blob/master/src/Extension/ExtensionTrait.php#L44
<pre><code>
    public static function getCalledExtensionClass()
    {
        return self::$extendableStaticCalledClass;
    }
</code></pre>

This var "$extendableStaticCalledClass" defined in class ExtendableTrait:
https://github.com/octobercms/library/blob/master/src/Extension/ExtendableTrait.php#L311
But, in result of programm cycle on a page /author/plugin/controller/update this method "extendableCallStatic" not a called.

**Comment by dimti** [comment]
Some wrong with static call magic function.
https://github.com/octobercms/library/blob/master/src/Extension/Extendable.php#L42

<pre><code>
    Categories::extendFormFields(function($form, $model, $context){

        if (!$model instanceof MyModel)
            return;

        $form->addFields([
            'my_field' => [
                'label'   => 'My Field',
                'comment' => 'This is a custom field I have added.',
            ],
        ]);

    });
</code></pre>

Actual results.
Previous function called that function:
<pre><code>
class Extendable
{
    use ExtendableTrait;

    public function __call($name, $params)
    {
        return $this->extendableCall($name, $params);
    }

}
</pre></code>

Needing result.
extendFormFields should be called __callStatic magic method:

<pre><code>
class Extendable
{
    use ExtendableTrait;

    public static function __callStatic($name, $params)
    {
        return self::extendableCallStatic($name, $params);
    }

}
</pre></code>

If hand mode - extending form fields is works
<pre><code>
\Dimti\Spim\Controllers\Product::__callStatic('extendFormFields', array(function(Form $form, $model, $context) use ($option_item, $relation_key){
				if (!$model instanceof \Dimti\Spim\Models\Product)
					return;
				$form->addFields( [
					$relation_key => [
						'label'    => $option_item->name,
						'type'     => 'relation',
						'nameFrom' => 'name'
					],
				] );
			}));
</pre></code>

**Comment by daftspunk** [comment]
I was unable to replicate this, can you confirm this issue occurs by installing the forum plugin?

The following code works for me:
https://github.com/rainlab/forum-plugin/commit/f4655c766f77659a1f0e3689530347e17c338009

If this code does not work for you, please supply your code and what version of PHP you are using.
