### ISSUE TITLE
Add Save as Copy feature to front-end theme customization

### ISSUE THREAD

**Issue by jtherczeg** [octobercms/october#887]
1. In the back-end top menu bar click Settings.
2. In the left menu click CMS > Front-end theme.
3. Activate a theme which supports customization.
4. Click Customization.

It would be highly recommended to have a **Save as Copy** button (or similar label and function) on this page, to be able to duplicate the current changes, as a starter point of the next level of customization.

**Comment by daftspunk** [comment]
I think if you hold down Ctrl and click Save, it should open a Modal popup asking for a new file name (Save as...). There should also be a tooltip on the Save button to signify this behavior.

**Comment by jtherczeg** [comment]
Yes, that would be great.

**Comment by daftspunk** [comment]
Haven't seen any support for this or needed to do it myself. Flagged for later if we need to come back to it.
