### ISSUE TITLE
Is it possible to provide theme specific settings?

### ISSUE THREAD

**Issue by karnold** [octobercms/october#888]
So when developing a custom theme is it possible to provide administrative settings specific to the theme?  I see this is possible within plugins.  But in my use case I have a theme that will be distributed and certain settings would need to be adjusted per the clients liking.  For example someone using the theme may want to provide different thumbnail image sizes for a specific view that is being rendered in the theme.

**Comment by Whyounes** [comment]
Have you checked https://octobercms.com/docs/themes/development#customization ?

**Comment by karnold** [comment]
that is exactly what i was looking for.  I must have overlooked it when i was reading the docs.  Thanks!
