### ISSUE TITLE
Invalid json decode testing in Model class

### ISSUE THREAD

**Issue by egrego-dot-re** [octobercms/october#889]
Let field in database be saved with value [] - empty json array.

October\Rain\Database\Model:

    protected function getAttributeValue($key)
    {
        $attr = parent::getAttributeValue($key);

        // Handle jsonable
        if (in_array($key, $this->jsonable) && !empty($attr)) {
            if ($value = json_decode($attr, true))   // json_decode('[]') will return empty array, empty array evaluates to false in php (because f*** you, that's why), therefore...
                $attr = $value;
        }

        return $attr; // we are returning string(2) '[]' here
    }

Posting rage angry, did 1h debug to find this php fuckup. Thanks, php. Solution: as php's json_decode is retarded you have to:

    $value = json_decode($attr, true) // throw every possible outcome of json_decode into $value
     if (json_last_error() === JSON_ERROR_NONE) // check that operation wasn't botched
        $attr = $value;  // no errors, assign whatever value was in that json to $attr and return it

Cheers.

**Comment by daftspunk** [comment]
Thanks for this, sorry about the frustration. Fixed
