### ISSUE TITLE
Closing a popup modal in a component callback

### ISSUE THREAD

**Issue by karnold** [octobercms/october#899]
I have a component that is leveraging the modal popup api from the back end.  What do i need to call in the callback to dismiss the modal popup if my condition is successful?

example:

```
    public function onStayLoggedIn()
    {
        $user = Auth::getUser();
        $password = post('password');

        if (Hash::check($password, $user->password)) {
            // Here i want to close the modal on success
        } else {
            // Here i want to return an error
        }

    }
```

**Comment by karnold** [comment]
nm, i figured out a solution

**Comment by ariponce** [comment]
You could post the solution, so people with the same problem can see it.

**Comment by karnold** [comment]
It's a bit of a hack, not sure how useful my solution is.  I just ended up doing a page redirect
