### ISSUE TITLE
Installing a plugin via CLI throwing error

### ISSUE THREAD

**Issue by studiopersona** [octobercms/october#906]
Getting the following error while trying to install a plugin through CLI
[ErrorException]
  Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT_FOLLOWLOCATION'

**Comment by Flynsarmy** [comment]
This make have been fixed though https://github.com/octobercms/library/commit/5eaebf80d8837d3810a150d07f170c5b0d6c2bca. Please confirm you can still replicate after updating your copy of October.

**Comment by studiopersona** [comment]
Still getting the same error after updating.

**Comment by daftspunk** [comment]
Please disable the open_basedir restriction on your web server, this is the cause for this error. Also the latest version has logic to address this, try reinstalling and repeat.
