### ISSUE TITLE
Bugs on the Manage plugins page

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#907]
__Request location__
Settings -> Updates -> Manage plugins page

__1. Bug summary__
I removed a plugin, but the buttons are not disabled. So there aren't any selected plugins but buttons are clickable.

__1. Reproduce steps__
* Go to the Manage plugins page.
* Select the any plugin.
* Click the Remove button.
* Click again the Remove button.

__2. Bug summary__
Disabling the plugin its detalis are not appear. Instead of the details the source code appears.

__2. Reproduce steps__
* Go to the Manage plugins page.
* Select the any plugin.
* Click the Enable or disable button.
* Disable the selected plugin.

**Comment by daftspunk** [comment]
Missing 
- **Expected result**: How OctoberCMS should behave on above mentioned steps.

**Comment by daftspunk** [comment]
Look at this as part of https://github.com/octobercms/october/issues/70#issuecomment-63933198

**Comment by gergo85** [comment]
1. When I uninstall the plugin, the Remove button need to be disabled.
2. Show the translation text instead of source code. See the picture:
![issue](https://cloud.githubusercontent.com/assets/2959112/6319929/4276a0bc-bad0-11e4-92d9-d2f9370ddeee.jpg)

**Comment by daftspunk** [comment]
Ah yes, this may be an issue with the javascript, it should refresh the trigger api after AJAX updates.

Thanks

**Comment by daftspunk** [comment]
Fixed by #2034
