### ISSUE TITLE
'Required' validation doesn't work correctly on relation fields

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#908]
Say *Post* belongs to many *Categories*. If I put 
```php
public $belongsToMany = [
    'categories' => ['My\Plugin\Models\Category', 'table' => 'my_plugin_posts_categories', 'order' => 'name']
];

public $rules = [
    'categories' => 'required'
];
```
into my Post model and hit save on a record that doesn't already have categories - even if I have a category selected in the form it will error with a message about categories being required.

Some things to note:
* If the record already has categories attached to it, so long as you leave at least one selected the form will save successfully
* If you have no categories selected, the form will error as expected
* If you have categories selected, the form will still error if your record in the DB doesn't already have categories attached to it.

I've whipped up a demo repo complete with instructions to replicate [here](https://github.com/Flynsarmy/oc-badvalidation-plugin).

**Comment by daftspunk** [comment]
Can you retest using the latest build? There has been some work performed to the validation of related fields lately.

**Comment by Flynsarmy** [comment]
This is not fixed. The instructions on the git repo posted in my issue above still replicate the issue.

**Comment by pomek** [comment]
+1 / the same problem.

**Comment by Albert221** [comment]
:+1: same here

**Comment by Comandeer** [comment]
+1

**Comment by Sobak** [comment]
+1, it would be nice to have it fixed

**Comment by michieldewilde** [comment]
+1, got the same issue.

**Comment by jovib** [comment]
+1

**Comment by cybear-d** [comment]
i've also got the same issue. 

after some debugging, i found that in October\Rain\Database\Traits\Validation, line 138 is not getting the related model value, it returning empty array. 

```
...
$data[$attribute] = $this->getRelationValue($attribute);
```

i don't know if this related to laravel itself or not.

for now i change the above snippet to,

```
...
$data[$attribute] = $this->getAttribute($attribute)->lists('id');
```

hope this will help you find out what the bug is.

**Comment by mohammadmojrian** [comment]
+1

**Comment by seanthepottingshed** [comment]
Any progress on this issue?

**Comment by tranlamnhatnam** [comment]
Does anyone resolve this issue?

**Comment by iboved** [comment]
+1

**Comment by deckymcdonough** [comment]
+1

**Comment by nozreh** [comment]
+1 this is kinda problematic especially on pivot data for extending a plugin.

**Comment by pomek** [comment]
I've never seen more ignorant people than here... I abandoned this "CMS". I suggest the same thing to you.

**Comment by daftspunk** [comment]
If you lack the ability to read the documentation or understand the concept of open source. You should probably abandon programming too.

For the rest of you, this can be overcome by simply using the `beforeValidate` method in your model, or the `formBeforeSave` method in the controller. All issues are important to us, we are working as hard as we can. Thank you for your patience.

**Comment by pomek** [comment]
Thanks for your interesting response. If you would learn anybody, I suggest to begin from yourself.

Open source is not about "made a software and ignore the community". 

You needed my opinion and one year for mark this bug as "Status: Review Needed" and "Priority: Medium". 

> All issues are important to us, we are working as hard as we can. Thank you for your patience.

Sorry, but it looks like:
![image](https://cloud.githubusercontent.com/assets/2270764/15158993/a97d3436-16f2-11e6-8fe9-0827f06d6a42.png)

PS: I will consider your tip: "abandon programming". Have a nice evening!

**Comment by daftspunk** [comment]
Sorry @pomek I think I missed the part where we somehow owe you something? You are indeed an interesting "person". Are you sure you are not cancer? Please take your toxic attitude elsewhere.

**Comment by daftspunk** [comment]
The squeaky wheel gets the grease, I suppose.

**Comment by daftspunk** [comment]
This issue is now resolved.

- Functional tests: https://github.com/daftspunk/oc-test-plugin/commit/77571477e8df7546b5abe5fd166e25a593e6f05f
- Unit tests: https://github.com/octobercms/october/commit/b268f54189e2233211259f3b182e3009c0bc7599
- Code changes: https://github.com/octobercms/library/commit/58f1b1c6ab741d45b17aa63589aff81cf572948c
- Time taken for this work: **2 hours and 28 minutes**
- Estimated wholesale cost: **~USD $400**

Please don't be rude. We do this for love.
