### ISSUE TITLE
Better formatting requried for Logs

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#910]
I don't know how to write acceptable targeted CSS for this given your class names but it's very hard to read PHP tracebacks in the event logs due to the line breaks. Here's a before and after pic of how they should look IMO:

Before:
![](http://i.imgur.com/U6bvXg5.png)

After:
![](http://i.imgur.com/hPDV6Qw.png)

**Comment by flip4bytes** [comment]
I agree, the logs formatting could be improved. Here is an example of how papertrail displays their logs for instance:

![Logs](https://s3.amazonaws.com/f.cl.ly/items/0q2J3Z3b280x3N180Q1c/Image%202015-01-25%20at%206.12.15%20AM.png)

They use both color and indentation to break up each line making it a lot easier to scan (with wordwrap on).

Also, @Flynsarmy if you don't mind me asking, what plugin(s) are you using for the payments on the backend? Or did you build that payment settings section yourself?

Thanks!

**Comment by Flynsarmy** [comment]
[responsiv/pay](https://github.com/responsiv/pay-plugin).

**Comment by flip4bytes** [comment]
@Flynsarmy Ah, it's a WIP, gotcha. I'll check it out, thanks!

**Comment by daftspunk** [comment]
Fixed by #2035
