### ISSUE TITLE
Eager loading morphTo polymorphic relations

### ISSUE THREAD

**Issue by karnold** [octobercms/october#917]
I have encountered an issue where i need to eager load the object relation of a model that has a morphTo relationship. And it does not work.  It just doesnt load the related object.

After some google searching it appears that this is an issue in laravel and not october...however according to this stackoverflow link the issue appears to have been corrected in newer versions of laravel?

http://stackoverflow.com/questions/21528346/laravel-4-1-eager-loading-polymorphic-relation-morphto

So I am wondering if there is any immediate plan to update laravel in october so that this issue is resolved?

**Comment by daftspunk** [comment]
Yes, the update to Laravel 5 should coincide with the first Release Candidate (RC) version.
