### ISSUE TITLE
Ability to render components inside of partials

### ISSUE THREAD

**Issue by karnold** [octobercms/october#918]
Currently a component can be placed into a partial via the ui, however the component is not rendered when attempting to view a page that renders the partial

**Comment by daftspunk** [comment]
Just making sure, are you aware of the [limitations when using components in partials](http://octobercms.com/docs/cms/partials#life-cycle-limitations)?

**Comment by karnold** [comment]
Yup, aware of that.  I was in a particular situation where it would have been useful to put some small snippets of html into partials that could be reused across several components.  

This is more of a feature request, as it was an issue that was easy enough to work around.  but i did end up duplicating html in different components.

**Comment by daftspunk** [comment]
Hmm, I'm not quite sure I fully understand the problem.
