### ISSUE TITLE
contain composer.lock in repository

### ISSUE THREAD

**Issue by wppd** [octobercms/october#922]
see this article https://blog.engineyard.com/2014/composer-its-all-about-the-lock-file

**Comment by flip4bytes** [comment]
Yeah, for hosting on Heroku, the repository must contain the composer.lock file. I always remove the composer.lock file from the .gitignore on my installs.

**Comment by daftspunk** [comment]
I always thought this was a great idea, I just wasn't sure if we should do it because I don't see other projects doing it. There must be a reason why they don't do it, to make a decision we need to know why.

**Comment by wppd** [comment]
@daftspunk  it's so sad... I thought the link explains the "why" very well.

**Comment by shina** [comment]
The latest build of october beta is broken because of laravel 4.2.17




My lucky is that I had another project with 4.2.16 on composer.lock then I am using it.

**Comment by wppd** [comment]
@shina @daftspunk lol, what a coincident! that's the proof.

that's the reason why you need to keep the composer.lock.

users do the "composer update" but the third packages got upgraded and break BC after the "release" of octobercms.

anyway, just my 2 cents. your project your call.

**Comment by dgleba** [comment]
I have read the article and agree that composer.lock should be included. I have tried to install and run many projects and only ended in errors due to version issues. How can composer.lock hurt?

**Comment by saleksin** [comment]
Why, after this discussion, in [this](https://github.com/octobercms/october/commit/8c689d63ea5d580d9e0981da273cf5cae061220b#diff-a084b794bc0759e7a6b77810e01874f2) commit someone added composer.lock file to gitignore again?

**Comment by daftspunk** [comment]
This is to add composer.lock to the git project, we decided against it because it added complications. Composer will merge plugin dependencies in to the lock file.
