### ISSUE TITLE
[Bug ?] Checkbox in components

### ISSUE THREAD

**Issue by tiipiik** [octobercms/october#928]
When using a checkbox in a component there is a bug (for me at all, if someone could validate it would be greate)

To test:
Opening a CMS page, adding a component, click on the component to open it's parameter's, then click outside the parameter's component and then click again on the component to open it's parameters. You should see that fields are empty and style has bugs too.

**Comment by SASniper** [comment]
Hey there Yohann,

I've just followed your steps and came across the same issue as yourself.
In my case I used the Component ProBlog ProBlogList.
Add the component, open it's parameters change a checkbox and either hit
close or click off the popup results in all of the parameters being empty

--------------
Steven Walker
stevenwalker.eu

**Comment by tiipiik** [comment]
Thank you SASniper,

Thanks for validating that !

I told that to daftpunk. As they are in Laravel5 upgrade they will take a look at that after the RC.

**Comment by DanielHitchen** [comment]
I came across this also in some of my plugins - can you just check that in the component ```defineProperties()``` that any options for ```showExternalParameter``` have been changed to ```showExternalParam```, as this is what was tripping my plugins up?

**Comment by tiipiik** [comment]
I don't have any showExternalParam in my plugins, and there's no one in the Blog (Rainlab) plugin.

**Comment by riuson** [comment]
I have defined property of type 'checkbox' in custom component and came to the same problem.
Then I checkbox to checked state and open properties again, all values are empty.

    public function defineProperties()
    {
        return [
            'showAll' => [
                'description' => 'Show status messages for all users',
                'title' => 'Show All',
                'default' => false,
                'type' => 'checkbox'
            ]
        ];
    }

**Comment by t2t2** [comment]
I think I found the bug, it's the inspector javascript assuming the values are strings:

![octobercms_inspector_exception](https://cloud.githubusercontent.com/assets/1122555/7485223/37030fe6-f39b-11e4-8780-a616e063f4c6.PNG)  
TypeError: propertyValue.match is not a function

(above happened just by adding demoTodo component and on first open)

Related file: [october/modules/backend/assets/js/october.inspector.js](https://github.com/octobercms/october/blob/9470259727855b1abde72f9b86e0af2c09674d7e/modules/backend/assets/js/october.inspector.js#L382)

Reproduction steps: Have a default value for property that isn't a string, or if type=checkbox, having it be checked leads to true value

**Comment by FirestarterUA** [comment]
2.71. 
After the second click into component, have the same.
![bag](https://cloud.githubusercontent.com/assets/5495023/8500980/07203500-21aa-11e5-9c80-a62d6040b0f4.png)

**Comment by rjchauhan** [comment]
Yes, I found same issue in my plugin too. After second click it shows empty fields on component and javascript errors.

**Comment by CptMeatball** [comment]
I've experienced similar problems. Component settings appear empty on opening the component directly after drag & drop into page.

**Comment by daftspunk** [comment]
This issue has been fixed in the latest build (Build 30x) as the component plugin has been rebuilt
