### ISSUE TITLE
fatal error on develop branch

### ISSUE THREAD

**Issue by karnold** [octobercms/october#939]
I have started a fresh install with the develop branch and updated composer dependencies but it completely dies with the following error

"Fatal error: Class 'October\Rain\Foundation\Application' not found in /Users/karnold/src/octoberfriends/bootstrap/app.php on line 14"

**Comment by daftspunk** [comment]
Might need to require october\rain version `dev-develop`

**Comment by karnold** [comment]
that doesnt seem to work either

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for october/system ~1.0 -> satisfiable by october/system[1.0.x-dev].
    - Can only install one of: october/rain[1.0.x-dev, dev-develop].
    - october/system 1.0.x-dev requires october/rain ~1.0 -> satisfiable by october/rain[1.0.x-dev].
    - Installation request for october/rain dev-develop -> satisfiable by october/rain[dev-develop].


```

**Comment by karnold** [comment]
I have also tried setting all of the october/* packages to dev-develop and that does not work either

**Comment by daftspunk** [comment]
Ditch all october/* ones except october/rain, because modules/ should come as part of the repo.

You are the first to try it, I hope we can find something that works.

**Comment by karnold** [comment]
getting closer...

it failed with

```
FatalErrorException in ProviderRepository.php line 150:
Class 'Illuminate\Log\LogServiceProvider' not found
```

so i tried installing illuminate/log and that fails too

```
karnolds-mbp:octoberfriends karnold$ composer require illuminate/log
Using version ~5.1@dev for illuminate/log
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - don't install illuminate/support 5.1.x-dev|don't install laravel/framework v5.0.0
    - don't install illuminate/support 5.1.x-dev|don't install laravel/framework v5.0.1
    - don't install illuminate/support 5.1.x-dev|don't install laravel/framework v5.0.2
    - don't install illuminate/support 5.1.x-dev|remove laravel/framework v5.0.2
    - illuminate/log 5.1.x-dev requires illuminate/support 5.1.* -> satisfiable by illuminate/support[5.1.x-dev].
    - don't install illuminate/log 5.1.x-dev|don't install laravel/framework 5.0.x-dev
    - Installation request for illuminate/log ~5.1@dev -> satisfiable by illuminate/log[5.1.x-dev].
    - Installation request for laravel/framework 5.0.* -> satisfiable by laravel/framework[5.0.x-dev, v5.0.0, v5.0.1, v5.0.2].

```

**Comment by daftspunk** [comment]
LogServiceProvider should come as part of `"laravel/framework": "5.0.*",`

Your require section should look like this

```
    "require": {
        "php": ">=5.4",
        "laravel/framework": "5.0.*",
        "illuminate/html": "5.0.*",
        "october/rain": "~1.0"
    },
```

**Comment by karnold** [comment]
yup, that is what i have

```
    "require": {
        "php": ">=5.4",
        "laravel/framework": "5.0.*",
        "illuminate/html": "5.0.*",
        "october/rain": "dev-develop"
    }, 
```

**Comment by daftspunk** [comment]
I'll try, one sec

**Comment by daftspunk** [comment]
It seems to work without error for me, just a whole bunch of suggestions.

**Comment by karnold** [comment]
ok I think i figured this out.....Possibly my install of git is messed up or something.  After starting over I checked out the develop branch and did a git diff and it wanted to commit all of the differences between the master branch.  As if it was on the develop branch but the code base hadnt actually changed.  After getting the develop branch to properly commit and updating the composer.json file it worked.

**Comment by daftspunk** [comment]
Great success!
