### ISSUE TITLE
Cannot update to build 185

### ISSUE THREAD

**Issue by jbibbs** [octobercms/october#942]
I'm unable to update to build 185. I'm running PHP 5.5 on MAMP.

Edit: It looks like this issue only effects the Composer install. With the Composer install, when I log in I see there is an available update for build 185. Trying to update to this build fails. (see below)

With the Wizard install, it looks like I'm already running build 185, as it's shown right in the backend. I'm not prompted to update.

**PHP Logs:**
```
PHP Fatal error:  require_once(): Failed opening required
'/Applications/MAMP/htdocs/october/bootstrap/start.php'
(include_path='/Applications/MAMP/htdocs/october/vendor/phpseclib/phpseclib/phpseclib:.:/Applications
MAMP/bin/php/php5.5.10/lib/php') in /Applications/MAMP/htdocs/october/index.php on line 29
```

**The Exception reads:**
```
Declaration of Illuminate\Database\Schema\Grammars\Grammar::wrap() should be compatible with
Illuminate\Database\Grammar::wrap($value, $prefixAlias = false)' in
 /Applications/MAMP/htdocs/october/vendor/laravel/framework/src/Illuminate/Database/Schema/Grammar
s/Grammar.php:270
```

**Comment by edhardie** [comment]
I'm experiencing the same issue on a Win7 dev machine running PHP 5.5

**Comment by jbibbs** [comment]
If you just want to get up and running, you can use the installer: https://octobercms.com/docs/help/installation#wizard-installation

I think the issue has something to do with the Composer package using a slightly newer build. It uses Laravel 5 (for example), while the master branch is still technically on Laravel 4.

**Comment by jbibbs** [comment]
Looks like this commit from the 12th has the answer: 3d04f06ad1cadc35313686041051857d4457a8a2
Changelog says we are now on L5. There is a link for instructions on how to upgrade to the Release Candidate version. I'll test out the upgrade, but closing this issue as it has been addressed.
