### ISSUE TITLE
CodeEditor "Ctrl + F" will make document "dirty"

### ISSUE THREAD

**Issue by cirdog** [octobercms/october#946]
Code Editor: "Ctrl + F" will make document "dirty".

To me it's an unintended effect, please kindly exclude similar key combos.

Thanks.

**Comment by daftspunk** [comment]
Can you please add more detail?

- **Request location**: Enter the URL where this bug occurs, if applicable.

- **Reproduce steps**: Clearly mention the steps to reproduce the bug.

- **Expected result**: How OctoberCMS should behave on above mentioned steps.

**Comment by cirdog** [comment]
**Request Location:**

http://<domain>/backend/cms
for ANY page to be edited.

**Reproduce steps:**

1) CMS section
2) Open a page to edit
3) Cursor/Focus on page content
4) Press "Ctrl + F" to trigger in-page search
5) Left sidebar's "content type" tab (say Partials) will light up with a "red badge" marked as "1" (1 dirty page)

**Expected result:**

1) "Ctrl + F" is a function key, not an editing action, therefore it shouldn't trigger a "page dirty" result.
2) The "content type" tab shouldn't have a dirty badge after pressing merely "Ctrl + F" on the content.
3) Please exclude editing function from triggering "dirty flag", since it's not an "editing action".

**Comment by cirdog** [comment]
Hi Devs,

I guess this problem is trivial enough to fix and annoying enough not to be omitted, please kindly fix it.

Thanks & Push.

**Comment by keiosweb** [comment]
This is true, triggering search in any CMS document marks it as dirty.

**Comment by daftspunk** [comment]
Confirmed, any key press in side the code editor will make it dirty, even when searching.

**Comment by cirdog** [comment]
Thanks!

**Comment by LukeTowers** [comment]
Fixed by @w20k!
