### ISSUE TITLE
search widget do not working

### ISSUE THREAD

**Issue by NemoD503** [octobercms/october#947]
Bug summary:
-------------------
1. In build 192 there is no Class <code>October\rain\Support\Util</code>, but, search widget and filter widget want to use it.
2. After fixing first problem (replace Util::arrayMerge() to array_merge()) in search widget, the search widget working, but list Table do not refresh after ajax request ..

Reproduce steps:
-------------------------
use filter widget on any model (I tested in RU local and Sqlite)

**Comment by OlyCCW** [comment]
I came across this issue as well as a temporary fix I added:

/**
    * Extension of PHPs array_merge() except supporting
    * an array of arrays to merge.
    */
    private function arrayMerge ($collection)
    {
        if (func_num_args() > 1)
        $collection = func_get_args();
        return call_user_func_array('array_merge', $collection);
    }

To Search.php in the search widget, pretty much lifted straight out of the old Util class, and changed the onSubmit function to:

/**
     * Search field has been submitted.
     */
    public function onSubmit()
    {
        /*
         * Save or reset search term in session
         */
        $this->setActiveTerm(post($this->getName()));

        /*
         * Trigger class event, merge results as viewable array
         */
        $params = func_get_args();
        $result = $this->fireEvent('search.submit', [$params]);
        if ($result && is_array($result)) {
            return $this->arrayMerge($result);
        }
    }

**Comment by NemoD503** [comment]
Thanks alot, maybe, can you create pull request, and discuss this solution with @daftspunk

**Comment by daftspunk** [comment]
Fixed in 7145aac45798fe8fe624e18cbdb28cdb989ce04e and Build 194

**Comment by NemoD503** [comment]
Thanks!!!
