### ISSUE TITLE
Fatal Error in octobercms after fresh install (cli) with pages module

### ISSUE THREAD

**Issue by leancode** [octobercms/october#948]
![screen shot 2015-02-16 at 01 51 12](https://cloud.githubusercontent.com/assets/611460/6205897/6b4a87da-b57e-11e4-9e65-44447f428a38.png)
Tonight tried to install October freshly using cli method (which was different from the installer method in that it no longer had an app folder). I then also installed pages and received PHP Fatal Error: Class 'October\Rain\Support\Yaml' not found in ...html/plugins/rainlab/pages/classes/Menu.php on line 258.
To make a long story short I compared my previous install with the current one and copied .../html/vendor/october/rain/src/Support/Yaml.php from an earlier install to this one and the error disappeared. Don't know what the real problem is but I am glad I got it running but would appreciate an autoloading expert to taking a look since the Yaml.php seems only a wrapper for the symphony yaml class which is probably meant to be found by its own now - I am speculating.

**Comment by NemoD503** [comment]
See http://octobercms.com/beta#breaking-changes
(Old Class Name)                         -> (New Class Name)
October\Rain\Support\Yaml                -> Yaml

**Comment by daftspunk** [comment]
If you are installing via the CLI method, it means you have downloaded the RC version. You will need to enable `cms.edgeUpdates` to ensure you are getting the RC versions of plugins.

It would appear you are running RC and have downloaded a Beta plugin =)

You could also use the GUI installer to get the Beta version of October.
