### ISSUE TITLE
Edge update errors

### ISSUE THREAD

**Issue by Shahiem** [octobercms/october#949]
In the latest build and  latest version of the User plugin I get this error when I try to create a new user or edit a user:

   Call to undefined method System\Classes\ErrorHandler::getDetailedMessage()

My Frontend roles plugin displays this error on the backend roles page. This is only when I use build 193.There are no errors in the previous build (185)

    SQLSTATE[42S22]: Column not found: 1054 Unknown column 'shahiemseymor_permission_role.user_group_id' in 'where clause' (SQL: select `shahiemseymor_roles`.*, (select group_concat(shahiemseymor_permissions.name separator ', ') from `shahiemseymor_permissions` inner join `shahiemseymor_permission_role` on `shahiemseymor_permissions`.`id` = `shahiemseymor_permission_role`.`user_permission_id` where `shahiemseymor_permission_role`.`user_group_id` = `shahiemseymor_roles`.`id`) as `permissions`, (SELECT COUNT(1) FROM shahiemseymor_assigned_roles WHERE role_id = shahiemseymor_roles.id) as `users` from `shahiemseymor_roles` order by `name` desc limit 20 offset 0)

How can I solve this issue?

**Comment by daftspunk** [comment]
What file and line number does this error occur?

**Comment by Shahiem** [comment]
Call to undefined method System\Classes\ErrorHandler::getDetailedMessage()
C:\wamp\www\labrat\modules\backend\classes\Controller.php line 540

Second bug
C:\wamp\www\labrat\vendor\laravel\framework\src\Illuminate\Database\Connection.php line 614

**Comment by daftspunk** [comment]
Just comment this line out and perform an update again, I think your vendor folder may be out of date.

**Comment by Shahiem** [comment]
Doesn't work

**Comment by daftspunk** [comment]
Please update to the latest, this should be fixed in Build 189.
