### ISSUE TITLE
Install fails at "Create admin account"

### ISSUE THREAD

**Issue by shoostar** [octobercms/october#95]
Initial installer startup works just fine, including adding all database connection and admin account details. Once you give the installer the final okay to actually install October, it fails at this point:

![october-install-fail](https://cloud.githubusercontent.com/assets/883933/2984285/9255e04a-dc30-11e3-8fea-a722c54ca253.jpg)
### Issue Summary

I was having issues with getting October to work yesterday afternoon, although I was using PHP 5.4.12, which led to me have the same exact issue as described [here](https://github.com/octobercms/october/issues/67). I proceeded to download/install a newer version of PHP, now currently 5.5.12 (running on WAMP 2.5).
### Steps to Reproduce
1. Download most recent release of October CMS
2. Create database and follow installation process
3. Slam keyboard repeatedly across desk upon installer failure

As mentioned above, I had updated my WAMP server to run on a newer version of PHP, but it should be noted that I did not encounter this problem while running 5.4.12.
### Technical details:
- October CMS Version: master (latest commit: https://github.com/octobercms/october/commit/bdff075058498e26ea0cd1c50f55b8c5783e9298)
- Client OS: Windows 7 64-bit
- Server OS: Apache 2.4.9
- PHP Version: 5.5.12
- Browser: Chrome 37.0.1992.1 Canary
- Database: MySQL 5.6.17

**Comment by polikin** [comment]
same problem as @shoostar
