### ISSUE TITLE
Request URI via Twig

### ISSUE THREAD

**Issue by davidbwaters** [octobercms/october#952]
Hey, I want to pull in the same thing as $_SERVER['REQUEST_URI'] using Twig and {{ app.request.uri }} doesn't work, any suggestions? 
i.e.
```
<link  ... href=" http://this.url<?=$_SERVER['REQUEST_URI']?>"/>
```

**Comment by flip4bytes** [comment]
You don't have to close an issue and create a new one just to edit your comment FYI.

**Comment by davidbwaters** [comment]
yeah, accidently used the back button to add the markdown syntax around the code portion.  sorry, thanks though.

**Comment by daftspunk** [comment]
```
function onStart() {
    $this['uri'] = Request::server('REQUEST_URI');
}
==
{{ uri }}
```
