### ISSUE TITLE
Making ajax calls to report widget.

### ISSUE THREAD

**Issue by karnold** [octobercms/october#953]
I have a report widget that needs to be able to do ajax polling to update its data.  Im having diffuculty figuring out how to properly initiate the request to the appropriate callback.

Here is an example of the code I am using

MyReportWidget.php
```
class MyReportWidget extends ReportWidgetBase
{
    public function render()
    {
        $this->addAssets();
        return $this->makePartial('widget');
    }

    public function onGenerateData()
    {
        // return an array of data
        return $data;
    }
}
```

myreportwidget.js
```
setInterval(function() {
     $(this).request('onGenerateData');
}
```

The problem being that $(this).request('onGenerateData'); fails with the error message "AJAX handler 'onGenerateData' was not found."  

If i had to take a guess maybe its some sort of namespacing issue?  After a little bit of reverse engineering against an ajax request that worked, nothing stood out in the header requests or ajax call as to what the issue is.

**Comment by daftspunk** [comment]
This occurs for the same reason AJAX is not supported in partials, they are being registered too late in the application life cycle for the handlers to be picked up. It is a flaw in the logic that can be fixed, I'll see what can be done.
