### ISSUE TITLE
Reinstalling composer dependencies

### ISSUE THREAD

**Issue by abbasadel** [octobercms/october#954]
Hi,

I'd like to know what to do if I want to reinstall the composer vendor directory. I tried the normal 
```
composer install
```
but I received a lot of errors like

```
Class 'October\Rain\Cron\CronServiceProvider' not found
```

Thank you,
Abbas

**Comment by daftspunk** [comment]
You should reinstall using the [CLI instructions](http://octobercms.com/docs/help/installation#command-line-installation)
