### ISSUE TITLE
Duplicating Plugins

### ISSUE THREAD

**Issue by yusufff** [octobercms/october#956]
Hi

I want to duplicate a plugin for use another purpose. I am using Blog plugin from Rainlab for listing Stores and I'll use same plugin for listing campaigns and listing movies. Searched for some other blog plugin but there isn't i guess. How can I do that?

Thank you

**Comment by mosid** [comment]
I think its better to ask this kind of questions in the forums not here.

**Comment by daftspunk** [comment]
You would need to copy and paste the files, rename the namespaces, rename the database tables and so on. It's often better to build from a fresh plugin and use the other plugin as a reference.
