### ISSUE TITLE
Annoyance when trying to close and remove component

### ISSUE THREAD

**Issue by swengmatt** [octobercms/october#962]
When I click on a component to change the settings, and then realize I want to go ahead and remove the component, I try to exit out of the settings, but an error pops up until I fill out valid data in the settings. 
This could be solved with default settings, so that when you try to exit the settings of the component, there are already valid settings, therefore no error. Otherwise, just get rid of the pop up error message.

**Comment by daftspunk** [comment]
Tough call, the component with required fields needs a value to proceed otherwise it can break further down the track. Supplying default values is up to the plugin author.
