### ISSUE TITLE
Setting filename and path with System\Models\File

### ISSUE THREAD

**Issue by that0n3guy** [octobercms/october#964]
I'm creating a frontend for users to upload their files and was planning on using `System\Models\File` since its stinkin easy.... but I ran into some issues:

* we can not set the disk_name or path if we want to.  Since you get path from the diskname... this gets tricky.  I need to make my filename something nice like "john_smith_contract_1.pdf" so when they are in their account, they can download something nice and not a random number pdf.  
* looking up images by file_name (based on how they are currently stored) is a bad idea.  I saw: https://github.com/octobercms/october/issues/286.   Since file_name in the database doesn't have to be unique, I could (or rather, some CMS content editor) upload different images that happen to have the same filename and not get the file I want.
* (small issue, but still) you aren't using SEO'able disk_names .  doing something like `{{ post.content_images().whereFileName('image-1.jpg').first.path }}` shows the search engines the disk_name, not the nice 'file_name'.  Even `image_1_5l3kj435jkl34.png` is better than `5l3kj435jkl34.png`

**Comment by daftspunk** [comment]
I assume this will be less of a problem when the Media Manager feature is introduced, this will use SEO friendly paths and is probably where you want to be storing your SEO related images and so on.

The System Files table / naming is for exactly that. We can look at revisiting this if it still a problem after media manager is implemented.
