### ISSUE TITLE
CMS Content area (contents of div.layout) is empty on vidacloud hosting environment

### ISSUE THREAD

**Issue by daveharrisonnet** [octobercms/october#970]
Anyone any idea what could be up. Something blocked? Its like any page using the console/WYSIWYG editor doesn't get rendered?
I have pages in CMS with just the menus and no content [any of the code editor pages, partials, content, layouts etc). However when I view other pages like account details they show fine, like http://....system/settings/mysettings for example

Something like http://....backend/editorpreferences again doesn't show properly even though i don;t think it uses the code editor

I thought it may have been my configuration but I created 2 identical installs of the RC using exact same details and both work fine, but not on vidacloud. I have asked their support team but the seem at a loss to give me a reason, so i wondered if anyone has any idea where i could ask them to start looking

All permissions were set recursively to 775 so it shouldn't be a permission issue and in in any case it is only a READ!

**Comment by daftspunk** [comment]
I am not sure, there is no immediate reason that comes to mind. There is not much we can use here to replicate and find a solution. For us to fix a bug we must be able to replicate it, it would be up to you to find out the cause and provide more information. 

Have you checked the error logs? Do you get any JavaScript errors?

**Comment by daveharrisonnet** [comment]
NO errors are thrown, it fails silently. I will investigate some more now that I know you have no ideas, thank-you. Funny the host support team say to ask you, although I feel it is an issue with their cloud config. I'll speak to them again about it. The reason I asked you is because I am not sure how the app actually works in terms of calls etc. I am guessing it maybe some sort of server security is blocking the content??? I'll report back if i find anything out

**Comment by daveharrisonnet** [comment]
Ok so The support guys at vidahost got this to install tonight. However totally unsure why it failed for me (8 times in a row). My best guess is that the install files they used were more up-to-date than mine and whatever bug was present was fixed in the install files they used? Is this a possibility?

**Comment by daftspunk** [comment]
I would say a file was orphaned some how in the deployment process. This could occur for any number of reasons depending on the server's architecture. I'd be looking for files with 0KB size.

Glad you got this sorted.
