### ISSUE TITLE
detectEnvironment is gone ?

### ISSUE THREAD

**Issue by Hakadel** [octobercms/october#976]
Hello,

Since the beta is done, you have deleted the file "/bootstrap/start.php".

But now, my environments folders in the "config" folder are not working.

ex:
- config
 - dev
 - testing
 - myCustomEnvFolder

So when I put a file from "config" folder to "myCustomEnvFolder" folder, it's not working.

I have setted the CMS_ENV environment variable.

Where is the detectEnvironment method ?

How can I manage multiple environment ?

Thank you.

**Comment by StudioLE** [comment]
October has updated to Laravel 5 which uses `.env` files for environment configuration.  [Refer to the Laravel 5 documentation](http://laravel.com/docs/5.0/configuration#environment-configuration).

In simple terms: you define environment variables in a `.env` file [see example](https://github.com/laravel/laravel/blob/master/.env.example) then use the `env('EXAMPLE_VAR', 'default')` [helper function](http://laravel.com/docs/5.0/helpers#miscellaneous) in your `config/*.php` files.

**Comment by shina** [comment]
The laurence approach is correct.

But you can try with APP_ENV instead of CMS_ENV too.

**Comment by Hakadel** [comment]
@StudioLE Thanks for the link, very helpful.
@shina It works like before with APP_ENV, thank you too ;)
