### ISSUE TITLE
Missing argument 2 for post(), called in /modules/cms/classes/Controller.php on line 289

### ISSUE THREAD

**Issue by Hakadel** [octobercms/october#978]
Hello,

It's a real bug or it's only for me ?
Because it works on local, but not on my AWS server.

**Missing argument 2 for post(), called in /modules/cms/classes/Controller.php on line 289 and defined**
*/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php line 317*

You can see the code here :
https://github.com/octobercms/october/blob/master/modules/cms/classes/Controller.php#L289

I have this bug on all my pages.

**Comment by daftspunk** [comment]
Update composer to the latest version, that should fix it

**Comment by Hakadel** [comment]
It works, thank you!

Do you know why the composer.lock file is ignored by git ?

**Comment by oliverpool** [comment]
@Hakadel: Take a look at https://github.com/octobercms/october/blob/master/.gitignore#L3
