### ISSUE TITLE
Remove Attachment's in DataBase if refresh plugin

### ISSUE THREAD

**Issue by Quiss** [octobercms/october#979]
Bug WTR:

1. Upload Photo (4 files)
  1. php artisan plugin:refresh Acme.Plugin
2. Upload photo (2 file)
  1. Save
  2. Reload Page
3. ???
4. Profit

Sorry for my bad english =)

**Comment by daftspunk** [comment]
The migrations, specifically dropping tables, occurs too low level to know about these relationships.

You could run a `Model::all()->photo->delete()` in your `down()` migration to solve this problem.

**Comment by rajakhoury** [comment]
@daftspunk  Does adding delete in the relation works when refreshing the plugin ? or should i do what you mentioned ?  ( build 428 )

	public $attachOne = [
		'avatar' => [
			File::class ,
			'delete'    => true
		]
	];

**Comment by LukeTowers** [comment]
@rajakhoury no it wouldn't, you'd need to do @daftspunk's suggestion. The migration file only deals directly with the database by default, unless you add the suggested code by @daftspunk into your down() method of your migration then it won't happen automatically.
