### ISSUE TITLE
Missing PublisherServiceProvider

### ISSUE THREAD

**Issue by itangiang** [octobercms/october#984]
In console after run ```php artisan create:controller```. I have error:

```
Class 'Illuminate\Foundation\Providers\PublisherServiceProvider' not found
```
October CMS build 215
How to fixed it. Thanks !!!

**Comment by daftspunk** [comment]
This seems to be an intermittent problem with Laravel 5. How have you installed, via composer or using the wizard installer?

**Comment by itangiang** [comment]
@daftspunk, My October CMS fresh installed using wizard installer.

**Comment by daftspunk** [comment]
Haven't seen this reported recently or experienced it again. Assume resolved.
