### ISSUE TITLE
Defining a report widget property options via a method fails

### ISSUE THREAD

**Issue by ariponce** [octobercms/october#987]
**Reproduce steps:**
* Inside a report widget, create a property of type dropdown.
* Create a method getPropertyOptions()
* Load the widget and click on the cog icon to apply the property

**Expected result:** The property displays and i can select an option

**Actual result:** An error message **"Undefined property: Class::$widget" on line 113 of /modules/backend/classes/WidgetBase.php** is shown.

If i define the options on the defineProperties method doing 
```php
'options' => $this->getPropertyOptions()
```
it works as intended.

**Comment by daftspunk** [comment]
Unable to replicate this, perhaps you need to supply us with a copy of your report widget or one that can accurately replicate this.

**Comment by ariponce** [comment]
The problem was because i used a widget inside the report widget, and did the initialization of the other widget on the report widget init method, causing an override of the widget config. Passing the initialization of the other widget to the render method solved the problem.
