### ISSUE TITLE
plz help fix error : return file_exists($path);

### ISSUE THREAD

**Issue by AhrimanSefid** [octobercms/october#990]
We're sorry, but an unhandled error occurred. Please see the details below. file_exists(): open_basedir restriction in effect. File(C:\Inetpub\vhosts\yekia.ir\httpdocs/lang/fa/Do you really want to delete selected files or directories?.php) is not within the allowed path(s): (C:/Inetpub/vhosts/yekia.ir\;C:\Windows\Temp)

C:\Inetpub\vhosts\yekia.ir\httpdocs\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php line 20

**Comment by AhrimanSefid** [comment]
Server win 2012 R2 CP: Plesk 12
http://yekia.ir/index.php/backend/cms

**Comment by daftspunk** [comment]
This seems to be a problem with Plesk, the error contradicts itself since the paths do match. You should disable open_basedir restriction in your webserver configuration to workaround it.
