### ISSUE TITLE
Customize back-end Page additional JS support

### ISSUE THREAD

**Issue by mahony0** [octobercms/october#993]
We (as company) need to change some graphical layout for backend, because Colors and Styles tab is not enough. Actually if there's a support for backend theme (with OctoberCMS branding) would be nice.

If that is not possible, there's a Custom stylesheet section in "/settings/update/october/backend/branding" page but I think if system have custom javascript tab, it'll be more flexible for most users (right now for us).

I can help by adding that features both but first we need to know if there are conflicts for that support?

Thanks.

**Comment by daftspunk** [comment]
[This plugin](https://github.com/daftspunk/oc-rtl-plugin) details creating backend skins, although it is not officially support until we have solidified the backend, which will occur during the stable release.
